ioquake3: code/game/ai_cmd.c File Reference
ai_cmd.c File Reference
#include "g_local.h"
#include "../botlib/botlib.h"
#include "../botlib/be_aas.h"
#include "../botlib/be_ea.h"
#include "../botlib/be_ai_char.h"
#include "../botlib/be_ai_chat.h"
#include "../botlib/be_ai_gen.h"
#include "../botlib/be_ai_goal.h"
#include "../botlib/be_ai_move.h"
#include "../botlib/be_ai_weap.h"
#include "ai_main.h"
#include "ai_dmq3.h"
#include "ai_chat.h"
#include "ai_cmd.h"
#include "ai_dmnet.h"
#include "ai_team.h"
#include "chars.h"
#include "inv.h"
#include "syn.h"
#include "match.h"
#include "../../ui/menudef.h"
Functions
int BotGetItemTeamGoal (char *goalname, bot_goal_t *goal)
int BotGetMessageTeamGoal (bot_state_t *bs, char *goalname, bot_goal_t *goal)
float BotGetTime (bot_match_t *match)
int FindClientByName (char *name)
int FindEnemyByName (bot_state_t *bs, char *name)
int NumPlayersOnSameTeam (bot_state_t *bs)
int BotGetPatrolWaypoints (bot_state_t *bs, bot_match_t *match)
int BotAddressedToBot (bot_state_t *bs, bot_match_t *match)
int BotGPSToPosition (char *buf, vec3_t position)
void BotMatch_HelpAccompany (bot_state_t *bs, bot_match_t *match)
void BotMatch_DefendKeyArea (bot_state_t *bs, bot_match_t *match)
void BotMatch_GetItem (bot_state_t *bs, bot_match_t *match)
void BotMatch_Camp (bot_state_t *bs, bot_match_t *match)
void BotMatch_Patrol (bot_state_t *bs, bot_match_t *match)
void BotMatch_GetFlag (bot_state_t *bs, bot_match_t *match)
void BotMatch_AttackEnemyBase (bot_state_t *bs, bot_match_t *match)
void BotMatch_RushBase (bot_state_t *bs, bot_match_t *match)
void BotMatch_TaskPreference (bot_state_t *bs, bot_match_t *match)
void BotMatch_ReturnFlag (bot_state_t *bs, bot_match_t *match)
void BotMatch_JoinSubteam (bot_state_t *bs, bot_match_t *match)
void BotMatch_LeaveSubteam (bot_state_t *bs, bot_match_t *match)
void BotMatch_WhichTeam (bot_state_t *bs, bot_match_t *match)
void BotMatch_CheckPoint (bot_state_t *bs, bot_match_t *match)
void BotMatch_FormationSpace (bot_state_t *bs, bot_match_t *match)
void BotMatch_Dismiss (bot_state_t *bs, bot_match_t *match)
void BotMatch_Suicide (bot_state_t *bs, bot_match_t *match)
void BotMatch_StartTeamLeaderShip (bot_state_t *bs, bot_match_t *match)
void BotMatch_StopTeamLeaderShip (bot_state_t *bs, bot_match_t *match)
void BotMatch_WhoIsTeamLeader (bot_state_t *bs, bot_match_t *match)
void BotMatch_WhatAreYouDoing (bot_state_t *bs, bot_match_t *match)
void BotMatch_WhatIsMyCommand (bot_state_t *bs, bot_match_t *match)
float BotNearestVisibleItem (bot_state_t *bs, char *itemname, bot_goal_t *goal)
void BotMatch_WhereAreYou (bot_state_t *bs, bot_match_t *match)
void BotMatch_LeadTheWay (bot_state_t *bs, bot_match_t *match)
void BotMatch_Kill (bot_state_t *bs, bot_match_t *match)
void BotMatch_CTF (bot_state_t *bs, bot_match_t *match)
void BotMatch_EnterGame (bot_state_t *bs, bot_match_t *match)
void BotMatch_NewLeader (bot_state_t *bs, bot_match_t *match)
int BotMatchMessage (bot_state_t *bs, char *message)
Variables
int notleader [MAX_CLIENTS]
Function Documentation
int BotAddressedToBot (bot_state_t * bs, bot_match_t * match)
References ADDRESSEE, bot_state_s::client, ClientName(), ClientOnSameTeamFromName(), MAX_MESSAGE_SIZE, MORE, MSG_CHATTELL, MSG_EVERYONE, MSG_MULTIPLENAMES, MTCONTEXT_ADDRESSEE, MTCONTEXT_REPLYCHAT, NETNAME, NumPlayersOnSameTeam(), qfalse, qtrue, random, ST_ADDRESSED, bot_match_s::string, stristr(), bot_state_s::subteam, bot_match_s::subtype, TEAMMATE, trap_BotFindMatch(), trap_BotMatchVariable(), and bot_match_s::type.
Referenced by BotMatch_AttackEnemyBase(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_DefendKeyArea(), BotMatch_Dismiss(), BotMatch_FormationSpace(), BotMatch_GetFlag(), BotMatch_GetItem(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_Patrol(), BotMatch_ReturnFlag(), BotMatch_RushBase(), BotMatch_Suicide(), BotMatch_WhatAreYouDoing(), BotMatch_WhereAreYou(), and BotMatch_WhichTeam().
int BotGetItemTeamGoal (char * goalname, bot_goal_t * goal)
References bot_goal_s::flags, GFL_DROPPED, qfalse, qtrue, and trap_BotGetLevelItemGoal().
Referenced by BotGetMessageTeamGoal().
int BotGetMessageTeamGoal (bot_state_t * bs, char * goalname, bot_goal_t * goal)
References BotFindWayPoint(), BotGetItemTeamGoal(), bot_state_s::checkpoints, cp, bot_waypoint_s::goal, qfalse, and qtrue.
Referenced by BotGetPatrolWaypoints(), BotMatch_Camp(), BotMatch_DefendKeyArea(), BotMatch_GetItem(), and BotMatch_HelpAccompany().
int BotGetPatrolWaypoints (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, BotCreateWayPoint(), BotFreeWaypoints(), BotGetMessageTeamGoal(), bot_state_s::client, bot_state_s::curpatrolpoint, KEYAREA, MAX_MESSAGE_SIZE, MORE, MTCONTEXT_PATROLKEYAREA, bot_waypoint_s::next, NULL, bot_goal_s::origin, PATROL_LOOP, PATROL_REVERSE, bot_state_s::patrolflags, bot_state_s::patrolpoints, bot_waypoint_s::prev, qfalse, qtrue, ST_BACK, ST_MORE, ST_REVERSE, bot_match_s::subtype, trap_BotFindMatch(), trap_BotMatchVariable(), and trap_EA_SayTeam().
Referenced by BotMatch_Patrol().
float BotGetTime (bot_match_t * match)
References FloatTime, MAX_MESSAGE_SIZE, MSG_FORALONGTIME, MSG_FORAWHILE, MSG_FOREVER, MSG_MINUTES, MSG_SECONDS, MTCONTEXT_TIME, ST_TIME, bot_match_s::subtype, t, TIME, trap_BotFindMatch(), trap_BotMatchVariable(), and bot_match_s::type.
Referenced by BotMatch_Camp(), BotMatch_DefendKeyArea(), BotMatch_HelpAccompany(), and BotMatch_Patrol().
int BotGPSToPosition (char * buf, vec3_t position)
References BotAI_Print(), PRT_MESSAGE, and qtrue.
void BotMatch_AttackEnemyBase (bot_state_t * bs, bot_match_t * match)
References bot_state_s::attackaway_time, BotAddressedToBot(), BotMatch_GetFlag(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), bot_state_s::decisionmaker, FindClientByName(), FloatTime, gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, LTG_ATTACKENEMYBASE, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, TEAM_ATTACKENEMYBASE_TIME, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_Camp (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, bot_state_s::areanum, bot_state_s::arrive_time, BotAddressedToBot(), BotAI_BotInitialChat(), BotEntityInfo(), BotGetMessageTeamGoal(), BotGetTime(), BotPointAreaNum(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), CHAT_TEAM, CHAT_TELL, bot_state_s::client, ClientFromName(), bot_state_s::cs, bot_state_s::decisionmaker, bot_goal_s::entitynum, bot_state_s::entitynum, FindClientByName(), FloatTime, KEYAREA, LTG_CAMPORDER, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, bot_goal_s::maxs, bot_goal_s::mins, NETNAME, NULL, bot_state_s::order_time, bot_state_s::ordered, bot_goal_s::origin, aas_entityinfo_s::origin, bot_state_s::origin, qtrue, random, ST_HERE, ST_THERE, bot_match_s::subtype, TEAM_CAMP_TIME, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, TeamPlayIsOn(), trap_BotEnterChat(), trap_BotMatchVariable(), aas_entityinfo_s::valid, VectorCopy, and VectorSet.
Referenced by BotMatchMessage().
void BotMatch_CheckPoint (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), BotCreateWayPoint(), BotFindWayPoint(), BotPointAreaNum(), CHAT_TELL, bot_state_s::checkpoints, ClientFromName(), Com_sprintf(), cp, bot_state_s::cs, bot_waypoint_s::goal, bot_waypoint_s::inuse, MAX_MESSAGE_SIZE, bot_waypoint_s::name, NAME, NETNAME, bot_waypoint_s::next, NULL, bot_goal_s::origin, POSITION, bot_waypoint_s::prev, qfalse, TeamPlayIsOn(), trap_BotEnterChat(), trap_BotMatchVariable(), and VectorClear.
Referenced by BotMatchMessage().
void BotMatch_CTF (bot_state_t * bs, bot_match_t * match)
References bot_state_s::blueflagstatus, BotTeam(), ClientFromName(), FLAG, bot_state_s::flagcarrier, bot_state_s::flagstatuschanged, FloatTime, gametype, GT_1FCTF, GT_CTF, bot_state_s::lastflagcapture_time, MAX_NETNAME, NETNAME, Q_stricmp(), bot_state_s::redflagstatus, ST_1FCTFGOTFLAG, ST_CAPTUREDFLAG, ST_GOTFLAG, ST_RETURNEDFLAG, bot_match_s::subtype, TEAM_BLUE, TEAM_RED, and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_DefendKeyArea (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotGetMessageTeamGoal(), BotGetTime(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), ClientFromName(), bot_state_s::decisionmaker, bot_state_s::defendaway_time, FloatTime, KEYAREA, LTG_DEFENDKEYAREA, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, TEAM_DEFENDKEYAREA_TIME, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, TeamPlayIsOn(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_Dismiss (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), CHAT_TELL, ClientFromName(), bot_state_s::cs, bot_state_s::decisionmaker, bot_state_s::lastgoal_ltgtype, bot_state_s::lead_time, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, NULL, TeamPlayIsOn(), trap_BotEnterChat(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_EnterGame (bot_state_t * bs, bot_match_t * match)
References FindClientByName(), MAX_NETNAME, NETNAME, notleader, qfalse, and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_FormationSpace (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), bot_state_s::formation_dist, MAX_MESSAGE_SIZE, NUMBER, space(), ST_FEET, bot_match_s::subtype, TeamPlayIsOn(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_GetFlag (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, BotAddressedToBot(), BotGetAlternateRouteGoal(), BotOppositeTeam(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), ctf_blueflag, CTF_GETFLAG_TIME, ctf_redflag, bot_state_s::decisionmaker, FindClientByName(), FloatTime, gametype, GT_1FCTF, GT_CTF, LTG_GETFLAG, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, and trap_BotMatchVariable().
Referenced by BotMatch_AttackEnemyBase(), and BotMatchMessage().
void BotMatch_GetItem (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotGetMessageTeamGoal(), BotPrintTeamGoal(), BotSetTeamStatus(), ClientOnSameTeamFromName(), bot_state_s::decisionmaker, FloatTime, ITEM, LTG_GETITEM, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, TEAM_GETITEM_TIME, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, TeamPlayIsOn(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_HelpAccompany (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, bot_state_s::arrive_time, BotAddressedToBot(), BotAI_BotInitialChat(), BotEntityInfo(), BotGetMessageTeamGoal(), BotGetTime(), BotPointAreaNum(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSameTeam(), BotSetTeamStatus(), CHAT_TEAM, CHAT_TELL, bot_state_s::client, ClientFromName(), bot_state_s::cs, bot_state_s::decisionmaker, bot_goal_s::entitynum, FindClientByName(), FloatTime, bot_state_s::formation_dist, ITEM, LTG_TEAMACCOMPANY, LTG_TEAMHELP, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, bot_goal_s::maxs, bot_goal_s::mins, MSG_HELP, MSG_ME, MTCONTEXT_TEAMMATE, NETNAME, NULL, bot_state_s::order_time, bot_state_s::ordered, bot_goal_s::origin, aas_entityinfo_s::origin, qfalse, qtrue, random, ST_NEARITEM, bot_match_s::subtype, TEAM_ACCOMPANY_TIME, TEAM_HELP_TIME, bot_state_s::teamgoal, bot_state_s::teamgoal_time, TEAMMATE, bot_state_s::teammate, bot_state_s::teammatevisible_time, bot_state_s::teammessage_time, TeamPlayIsOn(), trap_BotEnterChat(), trap_BotFindMatch(), trap_BotMatchVariable(), bot_match_s::type, aas_entityinfo_s::valid, VectorCopy, and VectorSet.
Referenced by BotMatchMessage().
void BotMatch_JoinSubteam (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), CHAT_TELL, ClientFromName(), bot_state_s::cs, MAX_MESSAGE_SIZE, NETNAME, NULL, bot_state_s::subteam, TEAMNAME, TeamPlayIsOn(), trap_BotEnterChat(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_Kill (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), BotPrintTeamGoal(), BotSetTeamStatus(), CHAT_TELL, ClientFromName(), bot_state_s::cs, ENEMY, bot_goal_s::entitynum, FindEnemyByName(), FloatTime, LTG_KILL, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, NULL, random, TEAM_KILL_SOMEONE, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, TeamPlayIsOn(), trap_BotEnterChat(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_LeadTheWay (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, BotAddressedToBot(), BotAI_BotInitialChat(), BotEntityInfo(), BotPointAreaNum(), BotSameTeam(), CHAT_TEAM, bot_state_s::client, ClientFromName(), bot_state_s::cs, bot_goal_s::entitynum, FindClientByName(), FloatTime, bot_state_s::lead_teamgoal, bot_state_s::lead_teammate, bot_state_s::lead_time, bot_state_s::leadmessage_time, bot_state_s::leadvisible_time, MAX_MESSAGE_SIZE, bot_goal_s::maxs, bot_goal_s::mins, NETNAME, NULL, bot_goal_s::origin, aas_entityinfo_s::origin, qfalse, qtrue, random, ST_SOMEONE, bot_match_s::subtype, TEAM_LEAD_TIME, bot_state_s::teamgoal, TEAMMATE, TeamPlayIsOn(), trap_BotEnterChat(), trap_BotMatchVariable(), aas_entityinfo_s::valid, VectorCopy, and VectorSet.
Referenced by BotMatchMessage().
void BotMatch_LeaveSubteam (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), CHAT_TELL, ClientFromName(), bot_state_s::cs, MAX_MESSAGE_SIZE, NETNAME, NULL, bot_state_s::subteam, TeamPlayIsOn(), trap_BotEnterChat(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_NewLeader (bot_state_t * bs, bot_match_t * match)
References BotSameTeam(), FindClientByName(), MAX_NETNAME, NETNAME, Q_strncpyz(), bot_state_s::teamleader, and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_Patrol (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotGetPatrolWaypoints(), BotGetTime(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), bot_state_s::decisionmaker, FindClientByName(), FloatTime, LTG_PATROL, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, TEAM_PATROL_TIME, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, TeamPlayIsOn(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_ReturnFlag (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotPrintTeamGoal(), BotSetTeamStatus(), CTF_RETURNFLAG_TIME, bot_state_s::decisionmaker, FindClientByName(), FloatTime, gametype, GT_1FCTF, GT_CTF, LTG_RETURNFLAG, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, bot_state_s::rushbaseaway_time, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_RushBase (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, BotAddressedToBot(), BotPrintTeamGoal(), BotSetTeamStatus(), ctf_blueflag, ctf_redflag, CTF_RUSHBASE_TIME, bot_state_s::decisionmaker, FindClientByName(), FloatTime, gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, LTG_RUSHBASE, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, bot_state_s::rushbaseaway_time, bot_state_s::teamgoal_time, bot_state_s::teammessage_time, and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_StartTeamLeaderShip (bot_state_t * bs, bot_match_t * match)
References ClientName(), FindClientByName(), MAX_MESSAGE_SIZE, NETNAME, ST_I, bot_match_s::subtype, bot_state_s::teamleader, TEAMMATE, TeamPlayIsOn(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_StopTeamLeaderShip (bot_state_t * bs, bot_match_t * match)
References ClientName(), FindClientByName(), MAX_MESSAGE_SIZE, NETNAME, notleader, Q_stricmp(), qtrue, ST_I, bot_match_s::subtype, bot_state_s::teamleader, TEAMMATE, TeamPlayIsOn(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_Suicide (bot_state_t * bs, bot_match_t * match)
References ACTION_AFFIRMATIVE, BotAddressedToBot(), BotVoiceChat(), bot_state_s::client, ClientFromName(), MAX_MESSAGE_SIZE, NETNAME, TeamPlayIsOn(), trap_BotMatchVariable(), trap_EA_Action(), trap_EA_Command(), and VOICECHAT_TAUNT.
Referenced by BotMatchMessage().
void BotMatch_TaskPreference (bot_state_t * bs, bot_match_t * match)
References ACTION_AFFIRMATIVE, BotAI_BotInitialChat(), BotGetTeamMateTaskPreference(), BotSetTeamMateTaskPreference(), BotVoiceChatOnly(), CHAT_TELL, bot_state_s::client, ClientFromName(), ClientName(), bot_state_s::cs, EasyClientName(), MAX_MESSAGE_SIZE, MAX_NETNAME, NETNAME, NULL, Q_stricmp(), ST_ATTACKER, ST_DEFENDER, ST_ROAMER, bot_match_s::subtype, bot_state_s::teamleader, TEAMTP_ATTACKER, TEAMTP_DEFENDER, trap_BotEnterChat(), trap_BotMatchVariable(), trap_EA_Action(), and VOICECHAT_YES.
Referenced by BotMatchMessage().
void BotMatch_WhatAreYouDoing (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), CHAT_TELL, ClientFromName(), ClientName(), bot_state_s::cs, EasyClientName(), bot_goal_s::entitynum, LTG_ATTACKENEMYBASE, LTG_CAMP, LTG_CAMPORDER, LTG_DEFENDKEYAREA, LTG_GETFLAG, LTG_GETITEM, LTG_HARVEST, LTG_KILL, LTG_PATROL, LTG_RETURNFLAG, LTG_RUSHBASE, LTG_TEAMACCOMPANY, LTG_TEAMHELP, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, NETNAME, NULL, bot_goal_s::number, bot_state_s::teamgoal, bot_state_s::teammate, trap_BotEnterChat(), trap_BotGoalName(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_WhatIsMyCommand (bot_state_t * bs, bot_match_t * match)
References bot_state_s::client, ClientName(), bot_state_s::forceorders, MAX_NETNAME, Q_stricmp(), qtrue, and bot_state_s::teamleader.
Referenced by BotMatchMessage().
void BotMatch_WhereAreYou (bot_state_t * bs, bot_match_t * match)
References bot_goal_s::areanum, bot_state_s::areanum, BotAddressedToBot(), BotAI_BotInitialChat(), BotNearestVisibleItem(), CHAT_TELL, ClientFromName(), bot_state_s::cs, ctf_blueflag, ctf_redflag, gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, MAX_MESSAGE_SIZE, NETNAME, NULL, bot_state_s::origin, TeamPlayIsOn(), TFL_DEFAULT, trap_AAS_AreaTravelTimeToGoalArea(), trap_BotEnterChat(), and trap_BotMatchVariable().
Referenced by BotMatchMessage().
void BotMatch_WhichTeam (bot_state_t * bs, bot_match_t * match)
References BotAddressedToBot(), BotAI_BotInitialChat(), CHAT_TEAM, bot_state_s::client, bot_state_s::cs, NULL, bot_state_s::subteam, TeamPlayIsOn(), and trap_BotEnterChat().
Referenced by BotMatchMessage().
void BotMatch_WhoIsTeamLeader (bot_state_t * bs, bot_match_t * match)
References bot_state_s::client, ClientName(), MAX_MESSAGE_SIZE, Q_stricmp(), bot_state_s::teamleader, TeamPlayIsOn(), and trap_EA_SayTeam().
Referenced by BotMatchMessage().
int BotMatchMessage (bot_state_t * bs, char * message)
References BotAI_Print(), BotMatch_AttackEnemyBase(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_CTF(), BotMatch_DefendKeyArea(), BotMatch_Dismiss(), BotMatch_EnterGame(), BotMatch_FormationSpace(), BotMatch_GetFlag(), BotMatch_GetItem(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_NewLeader(), BotMatch_Patrol(), BotMatch_ReturnFlag(), BotMatch_RushBase(), BotMatch_StartTeamLeaderShip(), BotMatch_StopTeamLeaderShip(), BotMatch_Suicide(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), BotMatch_WhatIsMyCommand(), BotMatch_WhereAreYou(), BotMatch_WhichTeam(), BotMatch_WhoIsTeamLeader(), bot_state_s::client, MSG_ACCOMPANY, MSG_ATTACKENEMYBASE, MSG_CAMP, MSG_CHECKPOINT, MSG_CREATENEWFORMATION, MSG_CTF, MSG_DEFENDKEYAREA, MSG_DISMISS, MSG_DOFORMATION, MSG_ENTERGAME, MSG_FORMATIONPOSITION, MSG_FORMATIONSPACE, MSG_GETFLAG, MSG_GETITEM, MSG_HARVEST, MSG_HELP, MSG_JOINSUBTEAM, MSG_KILL, MSG_LEADTHEWAY, MSG_LEAVESUBTEAM, MSG_NEWLEADER, MSG_PATROL, MSG_RETURNFLAG, MSG_RUSHBASE, MSG_STARTTEAMLEADERSHIP, MSG_STOPTEAMLEADERSHIP, MSG_SUICIDE, MSG_TASKPREFERENCE, MSG_WAIT, MSG_WHATAREYOUDOING, MSG_WHATISMYCOMMAND, MSG_WHEREAREYOU, MSG_WHICHTEAM, MSG_WHOISTEAMLAEDER, MTCONTEXT_CTF, MTCONTEXT_INITIALTEAMCHAT, MTCONTEXT_MISC, PRT_MESSAGE, qfalse, qtrue, trap_BotFindMatch(), trap_EA_SayTeam(), and bot_match_s::type.
Referenced by BotCheckConsoleMessages().
float BotNearestVisibleItem (bot_state_t * bs, char * itemname, bot_goal_t * goal)
References BotAI_Trace(), bot_state_s::client, CONTENTS_PLAYERCLIP, CONTENTS_SOLID, bot_state_s::eye, NULL, bot_goal_s::number, bot_goal_s::origin, bot_state_s::origin, Q_stricmp(), trap_BotGetLevelItemGoal(), trap_BotGoalName(), VectorLength(), and VectorSubtract.
Referenced by BotMatch_WhereAreYou().
int FindClientByName (char * name)
References ClientName(), MAX_CLIENTS, MAX_INFO_STRING, maxclients, Q_stricmp(), stristr(), and trap_Cvar_VariableIntegerValue().
Referenced by BotMatch_AttackEnemyBase(), BotMatch_Camp(), BotMatch_EnterGame(), BotMatch_GetFlag(), BotMatch_HelpAccompany(), BotMatch_LeadTheWay(), BotMatch_NewLeader(), BotMatch_Patrol(), BotMatch_ReturnFlag(), BotMatch_RushBase(), BotMatch_StartTeamLeaderShip(), and BotMatch_StopTeamLeaderShip().
int FindEnemyByName (bot_state_t * bs, char * name)
References BotSameTeam(), ClientName(), MAX_CLIENTS, MAX_INFO_STRING, maxclients, Q_stricmp(), stristr(), and trap_Cvar_VariableIntegerValue().
Referenced by BotMatch_Kill().
int NumPlayersOnSameTeam (bot_state_t * bs)
References BotSameTeam(), CS_PLAYERS, MAX_CLIENTS, MAX_INFO_STRING, maxclients, trap_Cvar_VariableIntegerValue(), and trap_GetConfigstring().
Referenced by BotAddressedToBot().
Variable Documentation
int notleader[MAX_CLIENTS]
Referenced by BotMatch_EnterGame(), BotMatch_StopTeamLeaderShip(), BotVoiceChat_StopLeader(), and FindHumanTeamLeader().