ioquake3: code/game/ai_team.c File Reference
ai_team.c File Reference
#include "g_local.h"
#include "../botlib/botlib.h"
#include "../botlib/be_aas.h"
#include "../botlib/be_ea.h"
#include "../botlib/be_ai_char.h"
#include "../botlib/be_ai_chat.h"
#include "../botlib/be_ai_gen.h"
#include "../botlib/be_ai_goal.h"
#include "../botlib/be_ai_move.h"
#include "../botlib/be_ai_weap.h"
#include "ai_main.h"
#include "ai_dmq3.h"
#include "ai_chat.h"
#include "ai_cmd.h"
#include "ai_dmnet.h"
#include "ai_team.h"
#include "ai_vcmd.h"
#include "match.h"
#include "../../ui/menudef.h"
Data Structures
struct bot_ctftaskpreference_s
Typedefs
typedef struct
bot_ctftaskpreference_s bot_ctftaskpreference_t
Functions
int BotValidTeamLeader (bot_state_t *bs)
int BotNumTeamMates (bot_state_t *bs)
int BotClientTravelTimeToGoal (int client, bot_goal_t *goal)
int BotSortTeamMatesByBaseTravelTime (bot_state_t *bs, int *teammates, int maxteammates)
void BotSetTeamMateTaskPreference (bot_state_t *bs, int teammate, int preference)
int BotGetTeamMateTaskPreference (bot_state_t *bs, int teammate)
int BotSortTeamMatesByTaskPreference (bot_state_t *bs, int *teammates, int numteammates)
void BotSayTeamOrderAlways (bot_state_t *bs, int toclient)
void BotSayTeamOrder (bot_state_t *bs, int toclient)
void BotVoiceChat (bot_state_t *bs, int toclient, char *voicechat)
void BotVoiceChatOnly (bot_state_t *bs, int toclient, char *voicechat)
void BotSayVoiceTeamOrder (bot_state_t *bs, int toclient, char *voicechat)
void BotCTFOrders_BothFlagsNotAtBase (bot_state_t *bs)
void BotCTFOrders_FlagNotAtBase (bot_state_t *bs)
void BotCTFOrders_EnemyFlagNotAtBase (bot_state_t *bs)
void BotCTFOrders_BothFlagsAtBase (bot_state_t *bs)
void BotCTFOrders (bot_state_t *bs)
void BotCreateGroup (bot_state_t *bs, int *teammates, int groupsize)
void BotTeamOrders (bot_state_t *bs)
int FindHumanTeamLeader (bot_state_t *bs)
void BotTeamAI (bot_state_t *bs)
Variables
bot_ctftaskpreference_t ctftaskpreferences [MAX_CLIENTS]
Typedef Documentation
typedef struct bot_ctftaskpreference_s bot_ctftaskpreference_t
Function Documentation
int BotClientTravelTimeToGoal (int client, bot_goal_t * goal)
References bot_goal_s::areanum, BotAI_GetClientState(), BotPointAreaNum(), playerState_s::origin, TFL_DEFAULT, and trap_AAS_AreaTravelTimeToGoalArea().
Referenced by BotSortTeamMatesByBaseTravelTime().
void BotCreateGroup (bot_state_t * bs, int * teammates, int groupsize)
References BotAI_BotInitialChat(), BotSayTeamOrderAlways(), bot_state_s::client, ClientName(), MAX_NETNAME, and NULL.
Referenced by BotTeamOrders().
void BotCTFOrders (bot_state_t * bs)
References bot_state_s::blueflagstatus, BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), BotCTFOrders_FlagNotAtBase(), BotTeam(), bot_state_s::redflagstatus, and TEAM_RED.
Referenced by BotTeamAI().
void BotCTFOrders_BothFlagsAtBase (bot_state_t * bs)
References BotAI_BotInitialChat(), BotSayTeamOrder(), BotSayVoiceTeamOrder(), BotSortTeamMatesByBaseTravelTime(), BotSortTeamMatesByTaskPreference(), ClientName(), CTFS_AGRESSIVE, bot_state_s::ctfstrategy, int(), MAX_CLIENTS, MAX_NETNAME, NULL, VOICECHAT_DEFEND, and VOICECHAT_GETFLAG.
Referenced by BotCTFOrders().
void BotCTFOrders_BothFlagsNotAtBase (bot_state_t * bs)
References BotAI_BotInitialChat(), BotSayTeamOrder(), BotSayVoiceTeamOrder(), BotSortTeamMatesByBaseTravelTime(), BotSortTeamMatesByTaskPreference(), bot_state_s::client, ClientName(), bot_state_s::flagcarrier, int(), MAX_CLIENTS, MAX_NETNAME, NULL, bot_state_s::numteammates, VOICECHAT_FOLLOWFLAGCARRIER, VOICECHAT_FOLLOWME, VOICECHAT_GETFLAG, and VOICECHAT_RETURNFLAG.
Referenced by BotCTFOrders().
void BotCTFOrders_EnemyFlagNotAtBase (bot_state_t * bs)
References BotAI_BotInitialChat(), BotSayTeamOrder(), BotSayVoiceTeamOrder(), BotSortTeamMatesByBaseTravelTime(), BotSortTeamMatesByTaskPreference(), bot_state_s::client, ClientName(), bot_state_s::flagcarrier, int(), MAX_CLIENTS, MAX_NETNAME, NULL, VOICECHAT_DEFEND, VOICECHAT_FOLLOWFLAGCARRIER, VOICECHAT_FOLLOWME, and VOICECHAT_GETFLAG.
Referenced by BotCTFOrders().
void BotCTFOrders_FlagNotAtBase (bot_state_t * bs)
References BotAI_BotInitialChat(), BotSayTeamOrder(), BotSayVoiceTeamOrder(), BotSortTeamMatesByBaseTravelTime(), BotSortTeamMatesByTaskPreference(), ClientName(), CTFS_AGRESSIVE, bot_state_s::ctfstrategy, int(), MAX_CLIENTS, MAX_NETNAME, NULL, bot_state_s::numteammates, VOICECHAT_DEFEND, and VOICECHAT_GETFLAG.
Referenced by BotCTFOrders().
int BotGetTeamMateTaskPreference (bot_state_t * bs, int teammate)
References ClientName(), MAX_NETNAME, bot_ctftaskpreference_s::preference, and Q_stricmp().
Referenced by BotMatch_TaskPreference(), BotSortTeamMatesByTaskPreference(), BotVoiceChat_WantOnDefense(), and BotVoiceChat_WantOnOffense().
int BotNumTeamMates (bot_state_t * bs)
References BotSameTeam(), CS_PLAYERS, Info_ValueForKey(), MAX_CLIENTS, MAX_INFO_STRING, maxclients, TEAM_SPECTATOR, trap_Cvar_VariableIntegerValue(), and trap_GetConfigstring().
Referenced by BotTeamAI().
void BotSayTeamOrder (bot_state_t * bs, int toclient)
References BotSayTeamOrderAlways(), bot_state_s::cs, MAX_MESSAGE_SIZE, and trap_BotGetChatMessage().
Referenced by BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), and BotCTFOrders_FlagNotAtBase().
void BotSayTeamOrderAlways (bot_state_t * bs, int toclient)
References CHAT_TELL, bot_state_s::client, ClientName(), CMS_CHAT, Com_sprintf(), bot_state_s::cs, EC, MAX_MESSAGE_SIZE, MAX_NETNAME, trap_BotEnterChat(), trap_BotGetChatMessage(), and trap_BotQueueConsoleMessage().
Referenced by BotCreateGroup(), and BotSayTeamOrder().
void BotSayVoiceTeamOrder (bot_state_t * bs, int toclient, char * voicechat)
References BotVoiceChat().
Referenced by BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), BotCTFOrders_FlagNotAtBase(), and BotTeamAI().
void BotSetTeamMateTaskPreference (bot_state_t * bs, int teammate, int preference)
References ClientName(), MAX_NETNAME, and bot_ctftaskpreference_s::preference.
Referenced by BotMatch_TaskPreference(), BotVoiceChat_WantOnDefense(), and BotVoiceChat_WantOnOffense().
int BotSortTeamMatesByBaseTravelTime (bot_state_t * bs, int * teammates, int maxteammates)
References BotClientTravelTimeToGoal(), BotSameTeam(), BotTeam(), CS_PLAYERS, ctf_blueflag, ctf_redflag, gametype, GT_1FCTF, GT_CTF, Info_ValueForKey(), MAX_CLIENTS, MAX_INFO_STRING, maxclients, NULL, TEAM_RED, TEAM_SPECTATOR, trap_Cvar_VariableIntegerValue(), and trap_GetConfigstring().
Referenced by BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), and BotCTFOrders_FlagNotAtBase().
int BotSortTeamMatesByTaskPreference (bot_state_t * bs, int * teammates, int numteammates)
References BotGetTeamMateTaskPreference(), MAX_CLIENTS, TEAMTP_ATTACKER, and TEAMTP_DEFENDER.
Referenced by BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), and BotCTFOrders_FlagNotAtBase().
void BotTeamAI (bot_state_t * bs)
References bot_state_s::askteamleader_time, bot_state_s::becometeamleader_time, BotAI_BotInitialChat(), BotCTFOrders(), BotNumTeamMates(), BotSayVoiceTeamOrder(), BotTeamOrders(), BotValidTeamLeader(), CHAT_TEAM, bot_state_s::client, ClientName(), bot_state_s::cs, CTFS_AGRESSIVE, bot_state_s::ctfstrategy, bot_state_s::entergame_time, FindHumanTeamLeader(), bot_state_s::flagstatuschanged, FloatTime, bot_state_s::forceorders, gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, GT_TEAM, bot_state_s::lastflagcapture_time, MAX_NETNAME, NULL, bot_state_s::numteammates, Q_stricmp(), qfalse, random, bot_state_s::teamgiveorders_time, bot_state_s::teamleader, trap_BotEnterChat(), and VOICECHAT_STARTLEADER.
Referenced by BotDeathmatchAI().
void BotTeamOrders (bot_state_t * bs)
References BotCreateGroup(), BotSameTeam(), CS_PLAYERS, Info_ValueForKey(), MAX_CLIENTS, MAX_INFO_STRING, maxclients, TEAM_SPECTATOR, trap_Cvar_VariableIntegerValue(), and trap_GetConfigstring().
Referenced by BotTeamAI().
int BotValidTeamLeader (bot_state_t * bs)
References ClientFromName(), qfalse, qtrue, and bot_state_s::teamleader.
Referenced by BotTeamAI().
void BotVoiceChat (bot_state_t * bs, int toclient, char * voicechat)
References bot_state_s::client, trap_EA_Command(), and va().
Referenced by BotCheckItemPickup(), BotCTFSeekGoals(), BotMatch_Suicide(), BotRefuseOrder(), and BotSayVoiceTeamOrder().
void BotVoiceChatOnly (bot_state_t * bs, int toclient, char * voicechat)
References bot_state_s::client, trap_EA_Command(), and va().
Referenced by BotGetLongTermGoal(), BotMatch_TaskPreference(), BotVoiceChat_Patrol(), BotVoiceChat_WantOnDefense(), BotVoiceChat_WantOnOffense(), and BotVoiceChat_WhoIsLeader().
int FindHumanTeamLeader (bot_state_t * bs)
References BotSameTeam(), BotSetLastOrderedTask(), BotVoiceChat_Defend(), ClientName(), g_entities, MAX_CLIENTS, notleader, qfalse, qtrue, SAY_TELL, SVF_BOT, and bot_state_s::teamleader.
Referenced by BotTeamAI().
Variable Documentation
bot_ctftaskpreference_t ctftaskpreferences[MAX_CLIENTS]