ioquake3: code/game/ai_dmnet.c File Reference
ai_dmnet.c File Reference
#include "g_local.h"
#include "../botlib/botlib.h"
#include "../botlib/be_aas.h"
#include "../botlib/be_ea.h"
#include "../botlib/be_ai_char.h"
#include "../botlib/be_ai_chat.h"
#include "../botlib/be_ai_gen.h"
#include "../botlib/be_ai_goal.h"
#include "../botlib/be_ai_move.h"
#include "../botlib/be_ai_weap.h"
#include "ai_main.h"
#include "ai_dmq3.h"
#include "ai_chat.h"
#include "ai_cmd.h"
#include "ai_dmnet.h"
#include "ai_team.h"
#include "chars.h"
#include "inv.h"
#include "syn.h"
#include "match.h"
#include "../../ui/menudef.h"
Defines
#define GFL_AIR 128
#define LOOKAHEAD_DISTANCE 300
Functions
void BotResetNodeSwitches (void)
void BotDumpNodeSwitches (bot_state_t *bs)
void BotRecordNodeSwitch (bot_state_t *bs, char *node, char *str, char *s)
int BotGetAirGoal (bot_state_t *bs, bot_goal_t *goal)
int BotGoForAir (bot_state_t *bs, int tfl, bot_goal_t *ltg, float range)
int BotNearbyGoal (bot_state_t *bs, int tfl, bot_goal_t *ltg, float range)
int BotReachedGoal (bot_state_t *bs, bot_goal_t *goal)
int BotGetItemLongTermGoal (bot_state_t *bs, int tfl, bot_goal_t *goal)
int BotGetLongTermGoal (bot_state_t *bs, int tfl, int retreat, bot_goal_t *goal)
int BotLongTermGoal (bot_state_t *bs, int tfl, int retreat, bot_goal_t *goal)
void AIEnter_Intermission (bot_state_t *bs, char *s)
int AINode_Intermission (bot_state_t *bs)
void AIEnter_Observer (bot_state_t *bs, char *s)
int AINode_Observer (bot_state_t *bs)
void AIEnter_Stand (bot_state_t *bs, char *s)
int AINode_Stand (bot_state_t *bs)
void AIEnter_Respawn (bot_state_t *bs, char *s)
int AINode_Respawn (bot_state_t *bs)
int BotSelectActivateWeapon (bot_state_t *bs)
void BotClearPath (bot_state_t *bs, bot_moveresult_t *moveresult)
void AIEnter_Seek_ActivateEntity (bot_state_t *bs, char *s)
int AINode_Seek_ActivateEntity (bot_state_t *bs)
void AIEnter_Seek_NBG (bot_state_t *bs, char *s)
int AINode_Seek_NBG (bot_state_t *bs)
void AIEnter_Seek_LTG (bot_state_t *bs, char *s)
int AINode_Seek_LTG (bot_state_t *bs)
void AIEnter_Battle_Fight (bot_state_t *bs, char *s)
void AIEnter_Battle_SuicidalFight (bot_state_t *bs, char *s)
int AINode_Battle_Fight (bot_state_t *bs)
void AIEnter_Battle_Chase (bot_state_t *bs, char *s)
int AINode_Battle_Chase (bot_state_t *bs)
void AIEnter_Battle_Retreat (bot_state_t *bs, char *s)
int AINode_Battle_Retreat (bot_state_t *bs)
void AIEnter_Battle_NBG (bot_state_t *bs, char *s)
int AINode_Battle_NBG (bot_state_t *bs)
Variables
int numnodeswitches
char nodeswitch [MAX_NODESWITCHES+1][144]
Define Documentation
#define GFL_AIR 128
Referenced by BotGetAirGoal(), and BotReachedGoal().
#define LOOKAHEAD_DISTANCE 300
Function Documentation
void AIEnter_Battle_Chase (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Battle_Chase(), BotRecordNodeSwitch(), bot_state_s::chase_time, and FloatTime.
Referenced by AINode_Battle_Fight(), and AINode_Battle_Retreat().
void AIEnter_Battle_Fight (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Battle_Fight(), BFL_FIGHTSUICIDAL, BotRecordNodeSwitch(), bot_state_s::flags, bot_state_s::ms, and trap_BotResetLastAvoidReach().
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), and AINode_Stand().
void AIEnter_Battle_NBG (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Battle_NBG(), and BotRecordNodeSwitch().
Referenced by AINode_Battle_Chase(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), and AINode_Seek_NBG().
void AIEnter_Battle_Retreat (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Battle_Retreat(), and BotRecordNodeSwitch().
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), and AINode_Seek_LTG().
void AIEnter_Battle_SuicidalFight (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Battle_Fight(), BFL_FIGHTSUICIDAL, BotRecordNodeSwitch(), bot_state_s::flags, bot_state_s::ms, and trap_BotResetLastAvoidReach().
Referenced by AINode_Battle_Retreat().
void AIEnter_Intermission (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Intermission(), BotChat_EndLevel(), BotRecordNodeSwitch(), BotResetState(), bot_state_s::chatto, bot_state_s::cs, and trap_BotEnterChat().
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
void AIEnter_Observer (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Observer(), BotRecordNodeSwitch(), and BotResetState().
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
void AIEnter_Respawn (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Respawn(), BotChat_Death(), BotChatTime(), BotRecordNodeSwitch(), FloatTime, bot_state_s::gs, bot_state_s::ms, qfalse, random, bot_state_s::respawn_time, bot_state_s::respawn_wait, bot_state_s::respawnchat_time, trap_BotResetAvoidGoals(), trap_BotResetAvoidReach(), trap_BotResetGoalState(), and trap_BotResetMoveState().
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
void AIEnter_Seek_ActivateEntity (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Seek_ActivateEntity(), and BotRecordNodeSwitch().
Referenced by BotGoForActivateGoal().
void AIEnter_Seek_LTG (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Seek_LTG(), BotRecordNodeSwitch(), bot_state_s::gs, bot_goal_s::number, trap_BotGetTopGoal(), and trap_BotGoalName().
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_Retreat(), AINode_Respawn(), AINode_Seek_NBG(), AINode_Stand(), and BotDeathmatchAI().
void AIEnter_Seek_NBG (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Seek_NBG(), BotRecordNodeSwitch(), bot_state_s::gs, bot_goal_s::number, trap_BotGetTopGoal(), and trap_BotGoalName().
Referenced by AINode_Battle_NBG(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and BotGetLongTermGoal().
void AIEnter_Stand (bot_state_t * bs, char * s)
References bot_state_s::ainode, AINode_Stand(), BotRecordNodeSwitch(), FloatTime, and bot_state_s::standfindenemy_time.
Referenced by AINode_Battle_Fight(), AINode_Intermission(), AINode_Observer(), AINode_Seek_LTG(), BotCheckConsoleMessages(), and BotDeathmatchAI().
int AINode_Battle_Chase (bot_state_t * bs)
References AIEnter_Battle_Fight(), AIEnter_Battle_NBG(), AIEnter_Battle_Retreat(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_LTG(), bot_goal_s::areanum, bot_state_s::areanum, BFL_IDEALVIEWSET, bot_grapple, BotAIBlocked(), BotAimAtEnemy(), BotCanAndWantsToRocketJump(), BotEntityVisible(), BotFindEnemy(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotMapScripts(), BotNearbyGoal(), BotSetupForMovement(), BotUpdateBattleInventory(), BotWantsToRetreat(), bot_state_s::chase_time, bot_state_s::check_time, bot_state_s::enemy, bot_goal_s::entitynum, bot_state_s::entitynum, bot_state_s::eye, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_state_s::flags, FloatTime, bot_moveresult_s::ideal_viewangles, bot_state_s::ideal_viewangles, vmCvar_t::integer, bot_state_s::lastenemyareanum, bot_state_s::lastenemyorigin, bot_state_s::ltg_time, bot_goal_s::maxs, bot_goal_s::mins, bot_moveresult_s::movedir, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTVIEWSET, MOVERESULT_MOVEMENTWEAPON, MOVERESULT_SWIMVIEW, bot_state_s::ms, bot_state_s::nbg_time, bot_goal_s::origin, bot_state_s::origin, qfalse, qtrue, range(), bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_ROCKETJUMP, TFL_SLIME, trap_BotMovementViewTarget(), trap_BotMoveToGoal(), trap_BotResetAvoidReach(), trap_BotResetLastAvoidReach(), trap_BotTouchingGoal(), vectoangles(), VectorCopy, VectorSet, VectorSubtract, bot_state_s::viewangles, bot_moveresult_s::weapon, and bot_state_s::weaponnum.
Referenced by AIEnter_Battle_Chase().
int AINode_Battle_Fight (bot_state_t * bs)
References AIEnter_Battle_Chase(), AIEnter_Battle_Retreat(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_LTG(), AIEnter_Stand(), BFL_FIGHTSUICIDAL, bot_grapple, BotAI_Print(), BotAIBlocked(), BotAimAtEnemy(), BotAttackMove(), BotBattleUseItems(), BotCanAndWantsToRocketJump(), BotChat_EnemySuicide(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_Kill(), BotChatTime(), BotCheckAttack(), BotChooseWeapon(), BotEntityInfo(), BotEntityVisible(), BotFindEnemy(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotPointAreaNum(), BotUpdateBattleInventory(), BotWantsToChase(), BotWantsToRetreat(), bot_state_s::cur_ps, bot_state_s::enemy, bot_state_s::enemydeath_time, bot_state_s::enemysuicide, EntityIsDead(), EntityIsInvisible(), EntityIsShooting(), bot_state_s::entitynum, bot_state_s::eye, bot_moveresult_s::failure, bot_state_s::flags, FloatTime, vmCvar_t::integer, bot_state_s::inventory, INVENTORY_HEALTH, bot_state_s::lastenemyareanum, bot_state_s::lastenemyorigin, bot_state_s::lastframe_health, bot_state_s::lasthitcount, bot_state_s::lastkilledplayer, bot_state_s::ltg_time, MAX_CLIENTS, bot_state_s::ms, aas_entityinfo_s::origin, PERS_HITS, playerState_s::persistant, PRT_MESSAGE, qfalse, qtrue, random, bot_state_s::stand_time, bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_ROCKETJUMP, TFL_SLIME, trap_AAS_AreaReachability(), trap_BotResetAvoidReach(), VectorCopy, and bot_state_s::viewangles.
Referenced by AIEnter_Battle_Fight(), and AIEnter_Battle_SuicidalFight().
int AINode_Battle_NBG (bot_state_t * bs)
References AIEnter_Battle_Fight(), AIEnter_Battle_Retreat(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_NBG(), BFL_IDEALVIEWSET, bot_grapple, BotAIBlocked(), BotAimAtEnemy(), BotCanAndWantsToRocketJump(), BotCheckAttack(), BotChooseWeapon(), BotEntityInfo(), BotEntityVisible(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotMapScripts(), BotPointAreaNum(), BotReachedGoal(), BotSetupForMovement(), BotUpdateBattleInventory(), bot_state_s::character, CHARACTERISTIC_ATTACK_SKILL, bot_state_s::enemy, bot_state_s::enemyvisible_time, EntityIsDead(), bot_state_s::entitynum, bot_state_s::eye, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_state_s::flags, FloatTime, bot_state_s::gs, bot_moveresult_s::ideal_viewangles, bot_state_s::ideal_viewangles, vmCvar_t::integer, bot_state_s::lastenemyareanum, bot_state_s::lastenemyorigin, MAX_CLIENTS, bot_moveresult_s::movedir, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTVIEWSET, MOVERESULT_MOVEMENTWEAPON, MOVERESULT_SWIMVIEW, bot_state_s::ms, bot_state_s::nbg_time, aas_entityinfo_s::origin, bot_state_s::origin, qfalse, qtrue, bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_ROCKETJUMP, TFL_SLIME, trap_AAS_AreaReachability(), trap_BotGetTopGoal(), trap_BotMovementViewTarget(), trap_BotMoveToGoal(), trap_BotPopGoal(), trap_BotResetAvoidReach(), trap_Characteristic_BFloat(), vectoangles(), VectorCopy, VectorSubtract, bot_state_s::viewangles, bot_moveresult_s::weapon, and bot_state_s::weaponnum.
Referenced by AIEnter_Battle_NBG().
int AINode_Battle_Retreat (bot_state_t * bs)
References AIEnter_Battle_Chase(), AIEnter_Battle_Fight(), AIEnter_Battle_NBG(), AIEnter_Battle_SuicidalFight(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_LTG(), BFL_IDEALVIEWSET, bot_grapple, BotAI_Print(), BotAIBlocked(), BotAimAtEnemy(), BotBattleUseItems(), BotCheckAttack(), BotChooseWeapon(), BotCTFCarryingFlag(), BotEntityInfo(), BotEntityVisible(), BotFindEnemy(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotLongTermGoal(), BotMapScripts(), BotNearbyGoal(), BotPointAreaNum(), BotSetupForMovement(), BotTeamGoals(), BotUpdateBattleInventory(), BotWantsToChase(), bot_state_s::character, CHARACTERISTIC_ATTACK_SKILL, bot_state_s::check_time, bot_state_s::enemy, bot_state_s::enemyvisible_time, EntityIsDead(), bot_state_s::entitynum, bot_state_s::eye, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_state_s::flags, FloatTime, gametype, bot_state_s::gs, GT_1FCTF, GT_CTF, GT_HARVESTER, bot_moveresult_s::ideal_viewangles, bot_state_s::ideal_viewangles, vmCvar_t::integer, bot_state_s::lastenemyareanum, bot_state_s::lastenemyorigin, bot_state_s::ltg_time, MAX_CLIENTS, bot_moveresult_s::movedir, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTVIEWSET, MOVERESULT_MOVEMENTWEAPON, MOVERESULT_SWIMVIEW, bot_state_s::ms, bot_state_s::nbg_time, aas_entityinfo_s::origin, bot_state_s::origin, PRT_MESSAGE, qfalse, qtrue, range(), bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_SLIME, trap_AAS_AreaReachability(), trap_BotEmptyGoalStack(), trap_BotMovementViewTarget(), trap_BotMoveToGoal(), trap_BotResetAvoidReach(), trap_BotResetLastAvoidReach(), trap_Characteristic_BFloat(), vectoangles(), VectorCopy, VectorSubtract, bot_state_s::viewangles, bot_moveresult_s::weapon, and bot_state_s::weaponnum.
Referenced by AIEnter_Battle_Retreat().
int AINode_Intermission (bot_state_t * bs)
References AIEnter_Stand(), BotChat_StartLevel(), BotChatTime(), BotIntermission(), FloatTime, qtrue, and bot_state_s::stand_time.
Referenced by AIEnter_Intermission().
int AINode_Observer (bot_state_t * bs)
References AIEnter_Stand(), BotIsObserver(), and qtrue.
Referenced by AIEnter_Observer().
int AINode_Respawn (bot_state_t * bs)
References AIEnter_Seek_LTG(), BotIsDead(), bot_state_s::chatto, bot_state_s::client, bot_state_s::cs, bot_state_s::enemy, FloatTime, qtrue, bot_state_s::respawn_time, bot_state_s::respawn_wait, bot_state_s::respawnchat_time, trap_BotEnterChat(), trap_EA_Respawn(), and trap_EA_Talk().
Referenced by AIEnter_Respawn().
int AINode_Seek_ActivateEntity (bot_state_t * bs)
References bot_state_s::activatestack, AIEnter_Battle_Fight(), AIEnter_Battle_NBG(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_NBG(), BFL_IDEALVIEWSET, bot_grapple, BotAI_Print(), BotAI_Trace(), BotAIBlocked(), BotAIPredictObstacles(), BotClearActivateGoalStack(), BotClearPath(), BotEntityInfo(), BotFindEnemy(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotMapScripts(), BotPopFromActivateGoalStack(), BotRoamGoal(), BotSelectActivateWeapon(), BotSetupForMovement(), BotWantsToRetreat(), bot_state_s::client, bot_state_s::cur_ps, bot_state_s::enemy, bot_goal_s::entitynum, bot_state_s::entitynum, bot_state_s::eye, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_state_s::flags, FloatTime, bot_activategoal_s::goal, bot_state_s::gs, bot_moveresult_s::ideal_viewangles, bot_state_s::ideal_viewangles, InFieldOfVision(), vmCvar_t::integer, MASK_SHOT, bot_moveresult_s::movedir, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTVIEWSET, MOVERESULT_MOVEMENTWEAPON, MOVERESULT_SWIMVIEW, MOVERESULT_WAITING, bot_state_s::ms, NULL, bot_activategoal_s::origin, aas_entityinfo_s::origin, bot_state_s::origin, PRT_MESSAGE, qfalse, qtrue, random, bot_activategoal_s::shoot, bot_activategoal_s::target, bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_SLIME, bot_state_s::thinktime, bot_activategoal_s::time, trap_BotEmptyGoalStack(), trap_BotMovementViewTarget(), trap_BotMoveToGoal(), trap_BotResetAvoidReach(), trap_BotResetLastAvoidReach(), trap_BotTouchingGoal(), trap_EA_Attack(), vectoangles(), VectorCompare(), VectorCopy, VectorSubtract, bot_state_s::viewangles, bot_moveresult_s::weapon, bot_activategoal_s::weapon, playerState_s::weapon, and bot_state_s::weaponnum.
Referenced by AIEnter_Seek_ActivateEntity().
int AINode_Seek_LTG (bot_state_t * bs)
References AIEnter_Battle_Fight(), AIEnter_Battle_Retreat(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_NBG(), AIEnter_Stand(), BFL_IDEALVIEWSET, bot_grapple, BotAIBlocked(), BotAIPredictObstacles(), BotCanAndWantsToRocketJump(), BotChat_Random(), BotChatTime(), BotClearPath(), BotCTFCarryingFlag(), BotFindEnemy(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotLongTermGoal(), BotMapScripts(), BotNearbyGoal(), BotRoamGoal(), BotSetupForMovement(), BotTeamGoals(), BotWantsToCamp(), BotWantsToRetreat(), bot_state_s::check_time, bot_state_s::client, bot_state_s::enemy, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_state_s::flags, FloatTime, gametype, bot_state_s::gs, GT_1FCTF, GT_CTF, GT_HARVESTER, bot_moveresult_s::ideal_viewangles, bot_state_s::ideal_viewangles, vmCvar_t::integer, bot_state_s::killedenemy_time, LTG_DEFENDKEYAREA, bot_state_s::ltg_time, bot_state_s::ltgtype, bot_moveresult_s::movedir, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTVIEWSET, MOVERESULT_MOVEMENTWEAPON, MOVERESULT_SWIMVIEW, MOVERESULT_WAITING, bot_state_s::ms, bot_state_s::nbg_time, bot_state_s::origin, qfalse, qtrue, random, range(), bot_state_s::stand_time, bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_ROCKETJUMP, TFL_SLIME, bot_state_s::thinktime, trap_BotEmptyGoalStack(), trap_BotMovementViewTarget(), trap_BotMoveToGoal(), trap_BotResetAvoidReach(), trap_BotResetLastAvoidReach(), trap_EA_Gesture(), vectoangles(), VectorCopy, VectorLengthSquared(), VectorSubtract, bot_moveresult_s::weapon, and bot_state_s::weaponnum.
Referenced by AIEnter_Seek_LTG(), and BotAIBlocked().
int AINode_Seek_NBG (bot_state_t * bs)
References AIEnter_Battle_Fight(), AIEnter_Battle_NBG(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_LTG(), BFL_IDEALVIEWSET, bot_grapple, BotAIBlocked(), BotAIPredictObstacles(), BotCanAndWantsToRocketJump(), BotChooseWeapon(), BotClearPath(), BotFindEnemy(), BotInLavaOrSlime(), BotIntermission(), BotIsDead(), BotIsObserver(), BotMapScripts(), BotReachedGoal(), BotRoamGoal(), BotSetupForMovement(), BotWantsToRetreat(), bot_state_s::check_time, bot_state_s::enemy, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_state_s::flags, FloatTime, bot_state_s::gs, bot_moveresult_s::ideal_viewangles, bot_state_s::ideal_viewangles, vmCvar_t::integer, bot_moveresult_s::movedir, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTVIEWSET, MOVERESULT_MOVEMENTWEAPON, MOVERESULT_SWIMVIEW, MOVERESULT_WAITING, bot_state_s::ms, bot_state_s::nbg_time, bot_state_s::origin, qfalse, qtrue, random, bot_state_s::tfl, TFL_DEFAULT, TFL_GRAPPLEHOOK, TFL_LAVA, TFL_ROCKETJUMP, TFL_SLIME, bot_state_s::thinktime, trap_BotEmptyGoalStack(), trap_BotGetSecondGoal(), trap_BotGetTopGoal(), trap_BotMovementViewTarget(), trap_BotMoveToGoal(), trap_BotPopGoal(), trap_BotResetAvoidReach(), trap_BotResetLastAvoidReach(), vectoangles(), VectorCopy, VectorSubtract, bot_moveresult_s::weapon, and bot_state_s::weaponnum.
Referenced by AIEnter_Seek_NBG(), and BotAIBlocked().
int AINode_Stand (bot_state_t * bs)
References AIEnter_Battle_Fight(), AIEnter_Seek_LTG(), BotChat_HitTalking(), BotChatTime(), BotFindEnemy(), bot_state_s::chatto, bot_state_s::client, bot_state_s::cs, FloatTime, bot_state_s::inventory, INVENTORY_HEALTH, bot_state_s::lastframe_health, qfalse, qtrue, bot_state_s::stand_time, bot_state_s::standfindenemy_time, trap_BotEnterChat(), and trap_EA_Talk().
Referenced by AIEnter_Stand(), and BotCheckConsoleMessages().
void BotClearPath (bot_state_t * bs, bot_moveresult_t * moveresult)
References bot_state_s::blockedbyavoidspot_time, BotAI_GetEntityState(), BotAI_Trace(), BotSelectActivateWeapon(), bot_state_s::client, bot_state_s::cur_ps, bot_state_s::entitynum, bot_state_s::eye, bot_moveresult_s::flags, FloatTime, bot_moveresult_s::ideal_viewangles, InFieldOfVision(), bot_state_s::inventory, INVENTORY_BFG10K, INVENTORY_BFGAMMO, INVENTORY_CELLS, INVENTORY_PLASMAGUN, INVENTORY_ROCKETLAUNCHER, INVENTORY_ROCKETS, bot_state_s::kamikazebody, MASK_SHOT, MOVERESULT_BLOCKEDBYAVOIDSPOT, MOVERESULT_MOVEMENTVIEW, MOVERESULT_MOVEMENTWEAPON, NULL, entityState_s::number, bot_state_s::numproxmines, bot_state_s::origin, entityState_s::pos, bot_state_s::proxmines, trap_EA_Attack(), trajectory_t::trBase, vectoangles(), VectorCopy, VectorLength(), VectorSubtract, bot_state_s::viewangles, bot_moveresult_s::weapon, playerState_s::weapon, WEAPONINDEX_BFG, WEAPONINDEX_PLASMAGUN, and WEAPONINDEX_ROCKET_LAUNCHER.
Referenced by AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
void BotDumpNodeSwitches (bot_state_t * bs)
References BotAI_Print(), bot_state_s::client, ClientName(), FloatTime, MAX_NETNAME, MAX_NODESWITCHES, nodeswitch, numnodeswitches, PRT_FATAL, and PRT_MESSAGE.
Referenced by BotDeathmatchAI().
int BotGetAirGoal (bot_state_t * bs, bot_goal_t * goal)
References bot_goal_s::areanum, BotAI_Trace(), BotPointAreaNum(), CONTENTS_LAVA, CONTENTS_PLAYERCLIP, CONTENTS_SLIME, CONTENTS_SOLID, CONTENTS_WATER, end, bot_goal_s::entitynum, bot_state_s::entitynum, bot_goal_s::flags, GFL_AIR, bot_goal_s::iteminfo, bot_goal_s::maxs, bot_goal_s::mins, bot_goal_s::number, bot_goal_s::origin, bot_state_s::origin, qfalse, qtrue, and VectorCopy.
Referenced by BotGoForAir().
int BotGetItemLongTermGoal (bot_state_t * bs, int tfl, bot_goal_t * goal)
References BotAI_Print(), BotChooseWeapon(), BotReachedGoal(), bot_state_s::client, ClientName(), FloatTime, bot_state_s::gs, bot_state_s::inventory, bot_state_s::ltg_time, bot_state_s::ms, bot_state_s::origin, PRT_MESSAGE, qtrue, trap_BotChooseLTGItem(), trap_BotGetTopGoal(), trap_BotPopGoal(), trap_BotResetAvoidGoals(), and trap_BotResetAvoidReach().
Referenced by BotGetLongTermGoal().
int BotGetLongTermGoal (bot_state_t * bs, int tfl, int retreat, bot_goal_t * goal)
References ACTION_AFFIRMATIVE, AIEnter_Seek_NBG(), aas_entityinfo_s::angles, AngleVectors(), bot_goal_s::areanum, bot_state_s::areanum, bot_state_s::arrive_time, bot_state_s::attackaway_time, bot_state_s::attackcrouch_time, bot_state_s::blueflagstatus, BotAI_BotInitialChat(), BotAlternateRoute(), BotCTFCarryingFlag(), BotEntityInfo(), BotEntityVisible(), BotFeelingBad(), BotGetItemLongTermGoal(), BotGoForAir(), BotHasPersistantPowerupAndWeapon(), BotPointAreaNum(), BotReachedGoal(), BotRoamGoal(), BotSetupForMovement(), BotTeam(), BotVoiceChatOnly(), bot_state_s::character, CHARACTERISTIC_CROUCHER, CHAT_TEAM, CHAT_TELL, bot_state_s::client, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, bot_state_s::cs, ctf_blueflag, ctf_redflag, bot_state_s::curpatrolpoint, bot_state_s::decisionmaker, bot_state_s::defendaway_range, bot_state_s::defendaway_time, DotProduct, EasyClientName(), bot_goal_s::entitynum, bot_state_s::entitynum, bot_state_s::eye, FloatTime, bot_state_s::formation_dist, gametype, bot_waypoint_s::goal, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, bot_state_s::harvestaway_time, bot_state_s::ideal_viewangles, bot_state_s::lastgoal_ltgtype, bot_state_s::lastkilledplayer, LTG_ATTACKENEMYBASE, LTG_CAMP, LTG_CAMPORDER, LTG_DEFENDKEYAREA, LTG_GETFLAG, LTG_GETITEM, LTG_HARVEST, LTG_KILL, LTG_PATROL, LTG_RETURNFLAG, LTG_RUSHBASE, LTG_TEAMACCOMPANY, LTG_TEAMHELP, bot_state_s::ltgtype, MAX_MESSAGE_SIZE, MAX_NETNAME, bot_goal_s::maxs, aas_entityinfo_s::maxs, bot_goal_s::mins, aas_entityinfo_s::mins, MOVE_WALK, bot_state_s::ms, bot_waypoint_s::name, bot_state_s::nbg_time, bot_waypoint_s::next, NULL, bot_goal_s::number, bot_goal_s::origin, aas_entityinfo_s::origin, bot_state_s::origin, PATROL_BACK, bot_state_s::patrolflags, bot_state_s::patrolpoints, bot_waypoint_s::prev, qfalse, qtrue, random, bot_state_s::redflagstatus, bot_state_s::rushbaseaway_time, Square, TEAM_BLUE, TEAM_RED, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammate, bot_state_s::teammatevisible_time, bot_state_s::teammessage_time, bot_state_s::tfl, TFL_DEFAULT, bot_state_s::thinktime, trap_AAS_AreaReachability(), trap_AAS_AreaTravelTimeToGoalArea(), trap_AAS_Swimming(), trap_BotEnterChat(), trap_BotGoalName(), trap_BotItemGoalInVisButNotVisible(), trap_BotMoveInDirection(), trap_BotResetAvoidReach(), trap_BotResetLastAvoidReach(), trap_BotTouchingGoal(), trap_Characteristic_BFloat(), trap_EA_Action(), trap_EA_Crouch(), trap_EA_Gesture(), trap_PointContents(), aas_entityinfo_s::valid, vectoangles(), VectorCopy, VectorLengthSquared(), VectorNormalize(), VectorSet, VectorSubtract, bot_state_s::viewangles, VOICECHAT_INPOSITION, VOICECHAT_ONDEFENSE, VOICECHAT_ONGETFLAG, VOICECHAT_ONOFFENSE, VOICECHAT_ONRETURNFLAG, and VOICECHAT_YES.
Referenced by BotLongTermGoal().
int BotGoForAir (bot_state_t * bs, int tfl, bot_goal_t * ltg, float range)
References BotGetAirGoal(), CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, FloatTime, bot_state_s::gs, bot_state_s::inventory, bot_state_s::lastair_time, bot_goal_s::origin, bot_state_s::origin, qfalse, qtrue, trap_AAS_PointContents(), trap_BotChooseNBGItem(), trap_BotGetTopGoal(), trap_BotPopGoal(), trap_BotPushGoal(), and trap_BotResetAvoidGoals().
Referenced by BotGetLongTermGoal(), and BotNearbyGoal().
int BotLongTermGoal (bot_state_t * bs, int tfl, int retreat, bot_goal_t * goal)
References bot_goal_s::areanum, BotAI_BotInitialChat(), BotEntityInfo(), BotEntityVisible(), BotGetLongTermGoal(), BotPointAreaNum(), CHAT_TELL, bot_state_s::cs, EasyClientName(), bot_goal_s::entitynum, bot_state_s::entitynum, bot_state_s::eye, FloatTime, bot_state_s::ideal_viewangles, bot_state_s::lead_teamgoal, bot_state_s::lead_teammate, bot_state_s::lead_time, bot_state_s::leadbackup_time, bot_state_s::leadmessage_time, bot_state_s::leadvisible_time, MAX_MESSAGE_SIZE, bot_goal_s::maxs, bot_goal_s::mins, NULL, bot_goal_s::origin, aas_entityinfo_s::origin, bot_state_s::origin, qfalse, qtrue, Square, bot_state_s::teammate, trap_AAS_AreaReachability(), trap_BotEnterChat(), aas_entityinfo_s::valid, vectoangles(), VectorCopy, VectorLengthSquared(), VectorSet, VectorSubtract, and bot_state_s::viewangles.
Referenced by AINode_Battle_Retreat(), and AINode_Seek_LTG().
int BotNearbyGoal (bot_state_t * bs, int tfl, bot_goal_t * ltg, float range)
References bot_goal_s::areanum, bot_state_s::areanum, BotCTFCarryingFlag(), BotGoForAir(), bot_state_s::gs, bot_state_s::inventory, bot_state_s::origin, qtrue, bot_state_s::teamgoal, TFL_DEFAULT, trap_AAS_AreaTravelTimeToGoalArea(), and trap_BotChooseNBGItem().
Referenced by AINode_Battle_Chase(), AINode_Battle_Retreat(), and AINode_Seek_LTG().
int BotReachedGoal (bot_state_t * bs, bot_goal_t * goal)
References bot_goal_s::areanum, bot_state_s::areanum, bot_state_s::entitynum, bot_state_s::eye, bot_goal_s::flags, FloatTime, GFL_AIR, GFL_DROPPED, GFL_ITEM, bot_state_s::gs, bot_state_s::lastair_time, bot_goal_s::maxs, bot_goal_s::mins, bot_goal_s::number, bot_goal_s::origin, bot_state_s::origin, qfalse, qtrue, trap_AAS_Swimming(), trap_BotItemGoalInVisButNotVisible(), trap_BotSetAvoidGoalTime(), trap_BotTouchingGoal(), and bot_state_s::viewangles.
Referenced by AINode_Battle_NBG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), and BotGetLongTermGoal().
void BotRecordNodeSwitch (bot_state_t * bs, char * node, char * str, char * s)
References BotAI_Print(), bot_state_s::client, ClientName(), Com_sprintf(), FloatTime, MAX_NETNAME, nodeswitch, numnodeswitches, and PRT_MESSAGE.
Referenced by AIEnter_Battle_Chase(), AIEnter_Battle_Fight(), AIEnter_Battle_NBG(), AIEnter_Battle_Retreat(), AIEnter_Battle_SuicidalFight(), AIEnter_Intermission(), AIEnter_Observer(), AIEnter_Respawn(), AIEnter_Seek_ActivateEntity(), AIEnter_Seek_LTG(), AIEnter_Seek_NBG(), and AIEnter_Stand().
void BotResetNodeSwitches (void)
References numnodeswitches.
Referenced by BotDeathmatchAI().
int BotSelectActivateWeapon (bot_state_t * bs)
References bot_state_s::inventory, INVENTORY_BELT, INVENTORY_BFG10K, INVENTORY_BFGAMMO, INVENTORY_BULLETS, INVENTORY_CELLS, INVENTORY_CHAINGUN, INVENTORY_GRENADELAUNCHER, INVENTORY_GRENADES, INVENTORY_LIGHTNING, INVENTORY_LIGHTNINGAMMO, INVENTORY_MACHINEGUN, INVENTORY_MINES, INVENTORY_NAILGUN, INVENTORY_NAILS, INVENTORY_PLASMAGUN, INVENTORY_PROXLAUNCHER, INVENTORY_RAILGUN, INVENTORY_ROCKETLAUNCHER, INVENTORY_ROCKETS, INVENTORY_SHELLS, INVENTORY_SHOTGUN, INVENTORY_SLUGS, WEAPONINDEX_BFG, WEAPONINDEX_CHAINGUN, WEAPONINDEX_GRENADE_LAUNCHER, WEAPONINDEX_LIGHTNING, WEAPONINDEX_MACHINEGUN, WEAPONINDEX_NAILGUN, WEAPONINDEX_PLASMAGUN, WEAPONINDEX_PROXLAUNCHER, WEAPONINDEX_RAILGUN, WEAPONINDEX_ROCKET_LAUNCHER, and WEAPONINDEX_SHOTGUN.
Referenced by AINode_Seek_ActivateEntity(), and BotClearPath().
Variable Documentation
char nodeswitch[MAX_NODESWITCHES+1][144]
Referenced by BotDumpNodeSwitches(), and BotRecordNodeSwitch().
int numnodeswitches
Referenced by BotDumpNodeSwitches(), BotRecordNodeSwitch(), and BotResetNodeSwitches().