ioquake3: code/botlib/be_aas_optimize.c File Reference
be_aas_optimize.c File Reference
#include "../qcommon/q_shared.h"
#include "l_libvar.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_aas_def.h"
Data Structures
struct optimized_s
Typedefs
typedef struct optimized_s optimized_t
Functions
int AAS_KeepEdge (aas_edge_t *edge)
int AAS_OptimizeEdge (optimized_t *optimized, int edgenum)
int AAS_KeepFace (aas_face_t *face)
int AAS_OptimizeFace (optimized_t *optimized, int facenum)
void AAS_OptimizeArea (optimized_t *optimized, int areanum)
void AAS_OptimizeAlloc (optimized_t *optimized)
void AAS_OptimizeStore (optimized_t *optimized)
void AAS_Optimize (void)
Typedef Documentation
typedef struct optimized_s optimized_t
Function Documentation
int AAS_KeepEdge (aas_edge_t * edge)
Referenced by AAS_OptimizeEdge().
int AAS_KeepFace (aas_face_t * face)
References FACE_LADDER, and aas_face_s::faceflags.
Referenced by AAS_OptimizeFace().
void AAS_Optimize (void)
References AAS_OptimizeAlloc(), AAS_OptimizeArea(), AAS_OptimizeStore(), aasworld, abs(), botimport, aas_reachability_s::edgenum, optimized_s::edgeoptimizeindex, aas_reachability_s::facenum, optimized_s::faceoptimizeindex, aas_s::numareas, PRT_MESSAGE, aas_s::reachability, aas_s::reachabilitysize, TRAVEL_ELEVATOR, TRAVEL_FUNCBOB, TRAVEL_JUMPPAD, aas_reachability_s::traveltype, and TRAVELTYPE_MASK.
Referenced by AAS_ContinueInit().
void AAS_OptimizeAlloc (optimized_t * optimized)
References aasworld, optimized_s::areas, optimized_s::edgeindex, optimized_s::edgeindexsize, aas_s::edgeindexsize, optimized_s::edgeoptimizeindex, optimized_s::edges, optimized_s::faceindex, optimized_s::faceindexsize, aas_s::faceindexsize, optimized_s::faceoptimizeindex, optimized_s::faces, GetClearedMemory(), optimized_s::numareas, aas_s::numareas, optimized_s::numedges, aas_s::numedges, optimized_s::numfaces, aas_s::numfaces, optimized_s::numvertexes, aas_s::numvertexes, optimized_s::vertexes, and optimized_s::vertexoptimizeindex.
Referenced by AAS_Optimize().
void AAS_OptimizeArea (optimized_t * optimized, int areanum)
References AAS_OptimizeFace(), aasworld, optimized_s::areas, aas_s::areas, Com_Memcpy, optimized_s::faceindex, aas_s::faceindex, optimized_s::faceindexsize, aas_area_s::firstface, and aas_area_s::numfaces.
Referenced by AAS_Optimize().
int AAS_OptimizeEdge (optimized_t * optimized, int edgenum)
References AAS_KeepEdge(), aasworld, abs(), optimized_s::edgeoptimizeindex, optimized_s::edges, aas_s::edges, optimized_s::numedges, optimized_s::numvertexes, aas_edge_s::v, VectorCopy, optimized_s::vertexes, aas_s::vertexes, and optimized_s::vertexoptimizeindex.
Referenced by AAS_OptimizeFace().
int AAS_OptimizeFace (optimized_t * optimized, int facenum)
References AAS_KeepFace(), AAS_OptimizeEdge(), aasworld, abs(), Com_Memcpy, optimized_s::edgeindex, aas_s::edgeindex, optimized_s::edgeindexsize, optimized_s::faceoptimizeindex, optimized_s::faces, aas_s::faces, aas_face_s::firstedge, aas_face_s::numedges, and optimized_s::numfaces.
Referenced by AAS_OptimizeArea().
void AAS_OptimizeStore (optimized_t * optimized)
References aasworld, optimized_s::areas, aas_s::areas, optimized_s::edgeindex, aas_s::edgeindex, optimized_s::edgeindexsize, aas_s::edgeindexsize, optimized_s::edgeoptimizeindex, optimized_s::edges, aas_s::edges, optimized_s::faceindex, aas_s::faceindex, optimized_s::faceindexsize, aas_s::faceindexsize, optimized_s::faceoptimizeindex, optimized_s::faces, aas_s::faces, FreeMemory(), optimized_s::numareas, aas_s::numareas, optimized_s::numedges, aas_s::numedges, optimized_s::numfaces, aas_s::numfaces, optimized_s::numvertexes, aas_s::numvertexes, optimized_s::vertexes, aas_s::vertexes, and optimized_s::vertexoptimizeindex.
Referenced by AAS_Optimize().