ioquake3: code/botlib/be_ai_weight.c File Reference
be_ai_weight.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_log.h"
#include "l_utils.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_libvar.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_ai_weight.h"
Defines
#define MAX_INVENTORYVALUE 999999
#define EVALUATERECURSIVELY
#define MAX_WEIGHT_FILES 128
Functions
int ReadValue (source_t *source, float *value)
int ReadFuzzyWeight (source_t *source, fuzzyseperator_t *fs)
void FreeFuzzySeperators_r (fuzzyseperator_t *fs)
void FreeWeightConfig2 (weightconfig_t *config)
void FreeWeightConfig (weightconfig_t *config)
fuzzyseperator_t * ReadFuzzySeperators_r (source_t *source)
weightconfig_t * ReadWeightConfig (char *filename)
int FindFuzzyWeight (weightconfig_t *wc, char *name)
float FuzzyWeight_r (int *inventory, fuzzyseperator_t *fs)
float FuzzyWeightUndecided_r (int *inventory, fuzzyseperator_t *fs)
float FuzzyWeight (int *inventory, weightconfig_t *wc, int weightnum)
float FuzzyWeightUndecided (int *inventory, weightconfig_t *wc, int weightnum)
void EvolveFuzzySeperator_r (fuzzyseperator_t *fs)
void EvolveWeightConfig (weightconfig_t *config)
void ScaleFuzzySeperator_r (fuzzyseperator_t *fs, float scale)
void ScaleWeight (weightconfig_t *config, char *name, float scale)
void ScaleFuzzySeperatorBalanceRange_r (fuzzyseperator_t *fs, float scale)
void ScaleFuzzyBalanceRange (weightconfig_t *config, float scale)
int InterbreedFuzzySeperator_r (fuzzyseperator_t *fs1, fuzzyseperator_t *fs2, fuzzyseperator_t *fsout)
void InterbreedWeightConfigs (weightconfig_t *config1, weightconfig_t *config2, weightconfig_t *configout)
void BotShutdownWeights (void)
Variables
weightconfig_t * weightFileList [MAX_WEIGHT_FILES]
Define Documentation
#define EVALUATERECURSIVELY
#define MAX_INVENTORYVALUE 999999
Referenced by FuzzyWeight_r(), FuzzyWeightUndecided_r(), ReadFuzzySeperators_r(), and ReadWeightConfig().
#define MAX_WEIGHT_FILES 128
Referenced by BotShutdownWeights(), and ReadWeightConfig().
Function Documentation
void BotShutdownWeights (void)
References FreeWeightConfig2(), MAX_WEIGHT_FILES, and NULL.
Referenced by Export_BotLibShutdown().
void EvolveFuzzySeperator_r (fuzzyseperator_t * fs)
References fuzzyseperator_s::child, crandom, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, random, fuzzyseperator_s::type, fuzzyseperator_s::weight, and WT_BALANCE.
Referenced by EvolveWeightConfig().
void EvolveWeightConfig (weightconfig_t * config)
References EvolveFuzzySeperator_r(), weight_s::firstseperator, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by BotMutateGoalFuzzyLogic().
int FindFuzzyWeight (weightconfig_t * wc, char * name)
References weight_s::name, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by ItemWeightIndex(), and WeaponWeightIndex().
void FreeFuzzySeperators_r (fuzzyseperator_t * fs)
References fuzzyseperator_s::child, FreeMemory(), and fuzzyseperator_s::next.
Referenced by FreeWeightConfig2(), and ReadFuzzySeperators_r().
void FreeWeightConfig (weightconfig_t * config)
References FreeWeightConfig2(), and LibVarGetValue().
Referenced by BotFreeItemWeights(), BotFreeWeaponWeights(), and ReadWeightConfig().
void FreeWeightConfig2 (weightconfig_t * config)
References weight_s::firstseperator, FreeFuzzySeperators_r(), FreeMemory(), weight_s::name, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by BotShutdownWeights(), and FreeWeightConfig().
float FuzzyWeight (int * inventory, weightconfig_t * wc, int weightnum)
References fuzzyseperator_s::child, weight_s::firstseperator, FuzzyWeight_r(), fuzzyseperator_s::index, fuzzyseperator_s::next, s, fuzzyseperator_s::value, fuzzyseperator_s::weight, and weightconfig_s::weights.
Referenced by BotChooseBestFightWeapon(), BotChooseLTGItem(), and BotChooseNBGItem().
float FuzzyWeight_r (int * inventory, fuzzyseperator_t * fs)
References fuzzyseperator_s::child, fuzzyseperator_s::index, MAX_INVENTORYVALUE, fuzzyseperator_s::next, fuzzyseperator_s::value, and fuzzyseperator_s::weight.
Referenced by FuzzyWeight(), and FuzzyWeightUndecided_r().
float FuzzyWeightUndecided (int * inventory, weightconfig_t * wc, int weightnum)
References fuzzyseperator_s::child, weight_s::firstseperator, FuzzyWeightUndecided_r(), fuzzyseperator_s::index, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, random, s, fuzzyseperator_s::value, and weightconfig_s::weights.
Referenced by BotChooseLTGItem(), and BotChooseNBGItem().
float FuzzyWeightUndecided_r (int * inventory, fuzzyseperator_t * fs)
References fuzzyseperator_s::child, FuzzyWeight_r(), fuzzyseperator_s::index, MAX_INVENTORYVALUE, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, random, fuzzyseperator_s::value, and fuzzyseperator_s::weight.
Referenced by FuzzyWeightUndecided().
int InterbreedFuzzySeperator_r (fuzzyseperator_t * fs1, fuzzyseperator_t * fs2, fuzzyseperator_t * fsout)
References botimport, fuzzyseperator_s::child, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, PRT_ERROR, qfalse, qtrue, fuzzyseperator_s::type, fuzzyseperator_s::weight, and WT_BALANCE.
Referenced by InterbreedWeightConfigs().
void InterbreedWeightConfigs (weightconfig_t * config1, weightconfig_t * config2, weightconfig_t * configout)
References botimport, weight_s::firstseperator, InterbreedFuzzySeperator_r(), weightconfig_s::numweights, PRT_ERROR, and weightconfig_s::weights.
Referenced by BotInterbreedGoalFuzzyLogic().
fuzzyseperator_t* ReadFuzzySeperators_r (source_t * source)
References fuzzyseperator_s::child, FreeFuzzySeperators_r(), GetClearedMemory(), fuzzyseperator_s::index, MAX_INVENTORYVALUE, fuzzyseperator_s::next, NULL, PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), qfalse, qtrue, ReadFuzzyWeight(), SourceError(), SourceWarning(), token, TT_INTEGER, TT_NUMBER, fuzzyseperator_s::value, and fuzzyseperator_s::weight.
Referenced by ReadWeightConfig().
int ReadFuzzyWeight (source_t * source, fuzzyseperator_t * fs)
References fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, PC_CheckTokenString(), PC_ExpectTokenString(), qfalse, qtrue, ReadValue(), fuzzyseperator_s::type, fuzzyseperator_s::weight, and WT_BALANCE.
Referenced by ReadFuzzySeperators_r(), and ReadWeightConfig().
int ReadValue (source_t * source, float * value)
References PC_ExpectAnyToken(), qfalse, qtrue, SourceError(), SourceWarning(), token, and TT_NUMBER.
Referenced by ReadFuzzyWeight().
weightconfig_t* ReadWeightConfig (char * filename)
References botDeveloper, BOTFILESBASEFOLDER, botimport, fuzzyseperator_s::child, weightconfig_s::filename, weight_s::firstseperator, FreeMemory(), FreeSource(), FreeWeightConfig(), GetClearedMemory(), fuzzyseperator_s::index, LibVarGetValue(), LoadSourceFile(), MAX_INVENTORYVALUE, MAX_WEIGHT_FILES, MAX_WEIGHTS, n, weight_s::name, fuzzyseperator_s::next, NULL, weightconfig_s::numweights, PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, Q_strncpyz(), qfalse, qtrue, ReadFuzzySeperators_r(), ReadFuzzyWeight(), SourceError(), SourceWarning(), StripDoubleQuotes(), Sys_MilliSeconds(), token, TT_STRING, fuzzyseperator_s::value, and weightconfig_s::weights.
Referenced by BotLoadItemWeights(), and BotLoadWeaponWeights().
void ScaleFuzzyBalanceRange (weightconfig_t * config, float scale)
References weight_s::firstseperator, weightconfig_s::numweights, ScaleFuzzySeperatorBalanceRange_r(), and weightconfig_s::weights.
void ScaleFuzzySeperator_r (fuzzyseperator_t * fs, float scale)
References fuzzyseperator_s::child, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, fuzzyseperator_s::type, fuzzyseperator_s::weight, and WT_BALANCE.
Referenced by ScaleWeight().
void ScaleFuzzySeperatorBalanceRange_r (fuzzyseperator_t * fs, float scale)
References fuzzyseperator_s::child, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, fuzzyseperator_s::type, and WT_BALANCE.
Referenced by ScaleFuzzyBalanceRange().
void ScaleWeight (weightconfig_t * config, char * name, float scale)
References weight_s::firstseperator, weight_s::name, weightconfig_s::numweights, ScaleFuzzySeperator_r(), and weightconfig_s::weights.
Variable Documentation
weightconfig_t* weightFileList[MAX_WEIGHT_FILES]