ioquake3: code/botlib/be_ea.c File Reference
be_ea.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "botlib.h"
#include "be_interface.h"
#include "be_ea.h"
Defines
#define MAX_USERMOVE 400
#define MAX_COMMANDARGUMENTS 10
Functions
void EA_Say (int client, char *str)
void EA_SayTeam (int client, char *str)
void EA_Tell (int client, int clientto, char *str)
void EA_UseItem (int client, char *it)
void EA_DropItem (int client, char *it)
void EA_UseInv (int client, char *inv)
void EA_DropInv (int client, char *inv)
void EA_Gesture (int client)
void EA_Command (int client, char *command)
void EA_SelectWeapon (int client, int weapon)
void EA_Attack (int client)
void EA_Talk (int client)
void EA_Use (int client)
void EA_Respawn (int client)
void EA_Jump (int client)
void EA_DelayedJump (int client)
void EA_Crouch (int client)
void EA_Walk (int client)
void EA_Action (int client, int action)
void EA_MoveUp (int client)
void EA_MoveDown (int client)
void EA_MoveForward (int client)
void EA_MoveBack (int client)
void EA_MoveLeft (int client)
void EA_MoveRight (int client)
void EA_Move (int client, vec3_t dir, float speed)
void EA_View (int client, vec3_t viewangles)
void EA_EndRegular (int client, float thinktime)
void EA_GetInput (int client, float thinktime, bot_input_t *input)
void EA_ResetInput (int client)
int EA_Setup (void)
void EA_Shutdown (void)
Variables
bot_input_t * botinputs
Define Documentation
#define MAX_COMMANDARGUMENTS 10
#define MAX_USERMOVE 400
Referenced by EA_Move().
Function Documentation
void EA_Action (int client, int action)
References bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_Attack (int client)
References ACTION_ATTACK, and bot_input_s::actionflags.
Referenced by BotTravel_BFGJump(), BotTravel_Grapple(), BotTravel_RocketJump(), and Init_EA_Export().
void EA_Command (int client, char * command)
References botlib_import_s::BotClientCommand, and botimport.
Referenced by BotEnterChat(), BotResetGrapple(), BotTravel_Grapple(), and Init_EA_Export().
void EA_Crouch (int client)
References ACTION_CROUCH, and bot_input_s::actionflags.
Referenced by BotTravel_Crouch(), BotTravel_Walk(), BotWalkInDirection(), and Init_EA_Export().
void EA_DelayedJump (int client)
References ACTION_DELAYEDJUMP, ACTION_JUMPEDLASTFRAME, and bot_input_s::actionflags.
Referenced by BotTravel_Jump(), and Init_EA_Export().
void EA_DropInv (int client, char * inv)
References botlib_import_s::BotClientCommand, botimport, and va().
void EA_DropItem (int client, char * it)
References botlib_import_s::BotClientCommand, botimport, and va().
void EA_EndRegular (int client, float thinktime)
Referenced by Init_EA_Export().
void EA_Gesture (int client)
References ACTION_GESTURE, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_GetInput (int client, float thinktime, bot_input_t * input)
References Com_Memcpy, and bot_input_s::thinktime.
Referenced by Init_EA_Export().
void EA_Jump (int client)
References ACTION_JUMP, ACTION_JUMPEDLASTFRAME, and bot_input_s::actionflags.
Referenced by BotCheckBarrierJump(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Jump(), BotTravel_RocketJump(), BotWalkInDirection(), and Init_EA_Export().
void EA_Move (int client, vec3_t dir, float speed)
References bot_input_s::dir, MAX_USERMOVE, bot_input_s::speed, and VectorCopy.
Referenced by BotCheckBarrierJump(), BotFinishTravel_BarrierJump(), BotFinishTravel_Elevator(), BotFinishTravel_FuncBobbing(), BotFinishTravel_Jump(), BotFinishTravel_JumpPad(), BotFinishTravel_Walk(), BotFinishTravel_WalkOffLedge(), BotFinishTravel_WaterJump(), BotFinishTravel_WeaponJump(), BotMoveInGoalArea(), BotSwimInDirection(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Crouch(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotTravel_Jump(), BotTravel_JumpPad(), BotTravel_Ladder(), BotTravel_RocketJump(), BotTravel_Swim(), BotTravel_Teleport(), BotTravel_Walk(), BotTravel_WalkOffLedge(), BotWalkInDirection(), and Init_EA_Export().
void EA_MoveBack (int client)
References ACTION_MOVEBACK, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_MoveDown (int client)
References ACTION_MOVEDOWN, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_MoveForward (int client)
References ACTION_MOVEFORWARD, and bot_input_s::actionflags.
Referenced by BotTravel_Ladder(), BotTravel_WaterJump(), and Init_EA_Export().
void EA_MoveLeft (int client)
References ACTION_MOVELEFT, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_MoveRight (int client)
References ACTION_MOVERIGHT, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_MoveUp (int client)
References ACTION_MOVEUP, and bot_input_s::actionflags.
Referenced by BotTravel_WaterJump(), and Init_EA_Export().
void EA_ResetInput (int client)
References ACTION_JUMP, ACTION_JUMPEDLASTFRAME, bot_input_s::actionflags, bot_input_s::dir, qfalse, bot_input_s::speed, bot_input_s::thinktime, and VectorClear.
Referenced by Init_EA_Export().
void EA_Respawn (int client)
References ACTION_RESPAWN, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_Say (int client, char * str)
References botlib_import_s::BotClientCommand, botimport, and va().
Referenced by Init_EA_Export().
void EA_SayTeam (int client, char * str)
References botlib_import_s::BotClientCommand, botimport, and va().
Referenced by Init_EA_Export().
void EA_SelectWeapon (int client, int weapon)
References bot_input_s::weapon.
Referenced by BotTravel_BFGJump(), BotTravel_RocketJump(), and Init_EA_Export().
int EA_Setup (void)
References BLERR_NOERROR, botlibglobals, GetClearedHunkMemory(), and botlib_globals_s::maxclients.
Referenced by Export_BotLibSetup().
void EA_Shutdown (void)
References FreeMemory(), and NULL.
Referenced by Export_BotLibShutdown().
void EA_Talk (int client)
References ACTION_TALK, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_Tell (int client, int clientto, char * str)
References botlib_import_s::BotClientCommand, botimport, and va().
void EA_Use (int client)
References ACTION_USE, and bot_input_s::actionflags.
Referenced by Init_EA_Export().
void EA_UseInv (int client, char * inv)
References botlib_import_s::BotClientCommand, botimport, and va().
void EA_UseItem (int client, char * it)
References botlib_import_s::BotClientCommand, botimport, and va().
void EA_View (int client, vec3_t viewangles)
References VectorCopy, and bot_input_s::viewangles.
Referenced by BotTravel_BFGJump(), BotTravel_RocketJump(), and Init_EA_Export().
void EA_Walk (int client)
References ACTION_WALK, and bot_input_s::actionflags.
Referenced by BotTravel_Walk().
Variable Documentation
bot_input_t* botinputs