ioquake3: code/botlib/be_ai_weight.h File Reference
be_ai_weight.h File Reference
Data Structures
struct fuzzyseperator_s
struct weight_s
struct weightconfig_s
Defines
#define WT_BALANCE 1
#define MAX_WEIGHTS 128
Typedefs
typedef struct fuzzyseperator_s fuzzyseperator_t
typedef struct weight_s weight_t
typedef struct weightconfig_s weightconfig_t
Functions
weightconfig_t * ReadWeightConfig (char *filename)
void FreeWeightConfig (weightconfig_t *config)
qboolean WriteWeightConfig (char *filename, weightconfig_t *config)
int FindFuzzyWeight (weightconfig_t *wc, char *name)
float FuzzyWeight (int *inventory, weightconfig_t *wc, int weightnum)
float FuzzyWeightUndecided (int *inventory, weightconfig_t *wc, int weightnum)
void ScaleWeight (weightconfig_t *config, char *name, float scale)
void ScaleBalanceRange (weightconfig_t *config, float scale)
void EvolveWeightConfig (weightconfig_t *config)
void InterbreedWeightConfigs (weightconfig_t *config1, weightconfig_t *config2, weightconfig_t *configout)
void BotShutdownWeights (void)
Define Documentation
#define MAX_WEIGHTS 128
Referenced by ReadWeightConfig().
#define WT_BALANCE 1
Referenced by EvolveFuzzySeperator_r(), InterbreedFuzzySeperator_r(), ReadFuzzyWeight(), ScaleFuzzySeperator_r(), and ScaleFuzzySeperatorBalanceRange_r().
Typedef Documentation
typedef struct fuzzyseperator_s fuzzyseperator_t
typedef struct weight_s weight_t
typedef struct weightconfig_s weightconfig_t
Function Documentation
void BotShutdownWeights (void)
References FreeWeightConfig2(), MAX_WEIGHT_FILES, and NULL.
Referenced by Export_BotLibShutdown().
void EvolveWeightConfig (weightconfig_t * config)
References EvolveFuzzySeperator_r(), weight_s::firstseperator, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by BotMutateGoalFuzzyLogic().
int FindFuzzyWeight (weightconfig_t * wc, char * name)
References weight_s::name, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by ItemWeightIndex(), and WeaponWeightIndex().
void FreeWeightConfig (weightconfig_t * config)
References FreeWeightConfig2(), and LibVarGetValue().
Referenced by BotFreeItemWeights(), BotFreeWeaponWeights(), and ReadWeightConfig().
float FuzzyWeight (int * inventory, weightconfig_t * wc, int weightnum)
References fuzzyseperator_s::child, weight_s::firstseperator, FuzzyWeight_r(), fuzzyseperator_s::index, fuzzyseperator_s::next, s, fuzzyseperator_s::value, fuzzyseperator_s::weight, and weightconfig_s::weights.
Referenced by BotChooseBestFightWeapon(), BotChooseLTGItem(), and BotChooseNBGItem().
float FuzzyWeightUndecided (int * inventory, weightconfig_t * wc, int weightnum)
References fuzzyseperator_s::child, weight_s::firstseperator, FuzzyWeightUndecided_r(), fuzzyseperator_s::index, fuzzyseperator_s::maxweight, fuzzyseperator_s::minweight, fuzzyseperator_s::next, random, s, fuzzyseperator_s::value, and weightconfig_s::weights.
Referenced by BotChooseLTGItem(), and BotChooseNBGItem().
void InterbreedWeightConfigs (weightconfig_t * config1, weightconfig_t * config2, weightconfig_t * configout)
References botimport, weight_s::firstseperator, InterbreedFuzzySeperator_r(), weightconfig_s::numweights, PRT_ERROR, and weightconfig_s::weights.
Referenced by BotInterbreedGoalFuzzyLogic().
weightconfig_t* ReadWeightConfig (char * filename)
References botDeveloper, BOTFILESBASEFOLDER, botimport, fuzzyseperator_s::child, weightconfig_s::filename, weight_s::firstseperator, FreeMemory(), FreeSource(), FreeWeightConfig(), GetClearedMemory(), fuzzyseperator_s::index, LibVarGetValue(), LoadSourceFile(), MAX_INVENTORYVALUE, MAX_WEIGHT_FILES, MAX_WEIGHTS, n, weight_s::name, fuzzyseperator_s::next, NULL, weightconfig_s::numweights, PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, Q_strncpyz(), qfalse, qtrue, ReadFuzzySeperators_r(), ReadFuzzyWeight(), SourceError(), SourceWarning(), StripDoubleQuotes(), Sys_MilliSeconds(), token, TT_STRING, fuzzyseperator_s::value, and weightconfig_s::weights.
Referenced by BotLoadItemWeights(), and BotLoadWeaponWeights().
void ScaleBalanceRange (weightconfig_t * config, float scale)
void ScaleWeight (weightconfig_t * config, char * name, float scale)
References weight_s::firstseperator, weight_s::name, weightconfig_s::numweights, ScaleFuzzySeperator_r(), and weightconfig_s::weights.
qboolean WriteWeightConfig (char * filename, weightconfig_t * config)