ioquake3: code/botlib/be_aas_routealt.c File Reference
be_aas_routealt.c File Reference
#include "../qcommon/q_shared.h"
#include "l_utils.h"
#include "l_memory.h"
#include "l_log.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_aas_def.h"
Data Structures
struct midrangearea_s
Defines
#define ENABLE_ALTROUTING
Typedefs
typedef struct midrangearea_s midrangearea_t
Functions
void AAS_AltRoutingFloodCluster_r (int areanum)
int AAS_AlternativeRouteGoals (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, aas_altroutegoal_t *altroutegoals, int maxaltroutegoals, int type)
void AAS_InitAlternativeRouting (void)
void AAS_ShutdownAlternativeRouting (void)
Variables
midrangearea_t * midrangeareas
int * clusterareas
int numclusterareas
Define Documentation
#define ENABLE_ALTROUTING
Typedef Documentation
typedef struct midrangearea_s midrangearea_t
Function Documentation
int AAS_AlternativeRouteGoals (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, aas_altroutegoal_t * altroutegoals, int maxaltroutegoals, int type)
References AAS_AltRoutingFloodCluster_r(), AAS_AreaReachability(), AAS_AreaTravelTimeToGoalArea(), AAS_ShowAreaPolygons(), aasworld, ALTROUTEGOAL_ALL, ALTROUTEGOAL_CLUSTERPORTALS, ALTROUTEGOAL_VIEWPORTALS, AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_VIEWPORTAL, aas_altroutegoal_s::areanum, aas_s::areas, aas_s::areasettings, botimport, aas_area_s::center, clusterareas, Com_Memset, aas_areasettings_s::contents, aas_altroutegoal_s::extratraveltime, midrangearea_s::goaltime, aas_altroutegoal_s::goaltraveltime, Log_Write(), NULL, aas_s::numareas, numclusterareas, aas_altroutegoal_s::origin, PRT_MESSAGE, qtrue, midrangearea_s::starttime, aas_altroutegoal_s::starttraveltime, Sys_MilliSeconds(), midrangearea_s::valid, VectorAdd, VectorClear, VectorCopy, VectorLength(), VectorScale, and VectorSubtract.
Referenced by Init_AAS_Export().
void AAS_AltRoutingFloodCluster_r (int areanum)
References aasworld, abs(), aas_s::areas, aas_face_s::backarea, clusterareas, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_face_s::frontarea, numclusterareas, aas_area_s::numfaces, qfalse, and midrangearea_s::valid.
Referenced by AAS_AlternativeRouteGoals().
void AAS_InitAlternativeRouting (void)
References aasworld, clusterareas, FreeMemory(), GetMemory(), and aas_s::numareas.
Referenced by AAS_LoadMap().
void AAS_ShutdownAlternativeRouting (void)
References clusterareas, FreeMemory(), NULL, and numclusterareas.
Referenced by AAS_Shutdown().
Variable Documentation
int* clusterareas
Referenced by AAS_AlternativeRouteGoals(), AAS_AltRoutingFloodCluster_r(), AAS_InitAlternativeRouting(), and AAS_ShutdownAlternativeRouting().
midrangearea_t* midrangeareas
int numclusterareas
Referenced by AAS_AlternativeRouteGoals(), AAS_AltRoutingFloodCluster_r(), and AAS_ShutdownAlternativeRouting().