ioquake3: code/botlib/be_aas_debug.c File Reference
be_aas_debug.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_libvar.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_interface.h"
#include "be_aas_funcs.h"
#include "be_aas_def.h"
Defines
#define MAX_DEBUGLINES 1024
#define MAX_DEBUGPOLYGONS 8192
Functions
void AAS_ClearShownPolygons (void)
void AAS_ShowPolygon (int color, int numpoints, vec3_t *points)
void AAS_ClearShownDebugLines (void)
void AAS_DebugLine (vec3_t start, vec3_t end, int color)
void AAS_PermanentLine (vec3_t start, vec3_t end, int color)
void AAS_DrawPermanentCross (vec3_t origin, float size, int color)
void AAS_DrawPlaneCross (vec3_t point, vec3_t normal, float dist, int type, int color)
void AAS_ShowBoundingBox (vec3_t origin, vec3_t mins, vec3_t maxs)
void AAS_ShowFace (int facenum)
void AAS_ShowFacePolygon (int facenum, int color, int flip)
void AAS_ShowArea (int areanum, int groundfacesonly)
void AAS_ShowAreaPolygons (int areanum, int color, int groundfacesonly)
void AAS_DrawCross (vec3_t origin, float size, int color)
void AAS_PrintTravelType (int traveltype)
void AAS_DrawArrow (vec3_t start, vec3_t end, int linecolor, int arrowcolor)
void AAS_ShowReachability (aas_reachability_t *reach)
void AAS_ShowReachableAreas (int areanum)
void AAS_FloodAreas_r (int areanum, int cluster, int *done)
void AAS_FloodAreas (vec3_t origin)
Variables
int debuglines [MAX_DEBUGLINES]
int debuglinevisible [MAX_DEBUGLINES]
int numdebuglines
static int debugpolygons [MAX_DEBUGPOLYGONS]
Define Documentation
#define MAX_DEBUGLINES 1024
Referenced by AAS_ClearShownDebugLines(), AAS_DebugLine(), AAS_DrawPlaneCross(), AAS_ShowArea(), and AAS_ShowBoundingBox().
#define MAX_DEBUGPOLYGONS 8192
Referenced by AAS_ClearShownPolygons(), and AAS_ShowPolygon().
Function Documentation
void AAS_ClearShownDebugLines (void)
References botimport, botlib_import_s::DebugLineDelete, debuglines, debuglinevisible, MAX_DEBUGLINES, and qfalse.
Referenced by AAS_TestMovementPrediction(), BotExportTest(), and BotMoveToGoal().
void AAS_ClearShownPolygons (void)
References botimport, botlib_import_s::DebugPolygonDelete, debugpolygons, and MAX_DEBUGPOLYGONS.
Referenced by BotExportTest().
void AAS_DebugLine (vec3_t start, vec3_t end, int color)
References botimport, botlib_import_s::DebugLineCreate, debuglines, botlib_import_s::DebugLineShow, debuglinevisible, line, MAX_DEBUGLINES, numdebuglines, qfalse, and qtrue.
Referenced by AAS_ClientMovementPrediction(), AAS_DrawArrow(), AAS_DrawCross(), AAS_DrawPermanentCross(), and AAS_ShowFace().
void AAS_DrawArrow (vec3_t start, vec3_t end, int linecolor, int arrowcolor)
References AAS_DebugLine(), CrossProduct(), DotProduct, up, VectorCopy, VectorMA(), VectorNormalize(), VectorSet, and VectorSubtract.
Referenced by AAS_ShowReachability().
void AAS_DrawCross (vec3_t origin, float size, int color)
References AAS_DebugLine(), end, start, and VectorCopy.
Referenced by AAS_ShowReachability().
void AAS_DrawPermanentCross (vec3_t origin, float size, int color)
References AAS_DebugLine(), botimport, botlib_import_s::DebugLineCreate, botlib_import_s::DebugLineShow, end, start, and VectorCopy.
Referenced by AAS_BestReachableArea().
void AAS_DrawPlaneCross (vec3_t point, vec3_t normal, float dist, int type, int color)
References botimport, botlib_import_s::DebugLineCreate, debuglines, botlib_import_s::DebugLineShow, debuglinevisible, line, MAX_DEBUGLINES, numdebuglines, qtrue, and VectorCopy.
Referenced by BotExportTest().
void AAS_FloodAreas (vec3_t origin)
References AAS_AreaCluster(), AAS_FloodAreas_r(), AAS_PointAreaNum(), aasworld, GetClearedMemory(), and aas_s::numareas.
Referenced by BotExportTest().
void AAS_FloodAreas_r (int areanum, int cluster, int * done)
References AAS_AreaCluster(), AAS_ShowAreaPolygons(), aasworld, abs(), AREACONTENTS_VIEWPORTAL, aas_reachability_s::areanum, aas_s::areas, aas_s::areasettings, aas_face_s::backarea, aas_areasettings_s::contents, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_areasettings_s::firstreachablearea, aas_face_s::frontarea, aas_area_s::numfaces, aas_areasettings_s::numreachableareas, qtrue, reach(), and aas_s::reachability.
Referenced by AAS_FloodAreas().
void AAS_PermanentLine (vec3_t start, vec3_t end, int color)
References botimport, botlib_import_s::DebugLineCreate, botlib_import_s::DebugLineShow, and line.
Referenced by AAS_FindFaceReachabilities(), and AAS_Reachability_FuncBobbing().
void AAS_PrintTravelType (int traveltype)
References botimport, PRT_MESSAGE, TRAVEL_BARRIERJUMP, TRAVEL_BFGJUMP, TRAVEL_CROUCH, TRAVEL_ELEVATOR, TRAVEL_FUNCBOB, TRAVEL_GRAPPLEHOOK, TRAVEL_INVALID, TRAVEL_JUMP, TRAVEL_JUMPPAD, TRAVEL_LADDER, TRAVEL_ROCKETJUMP, TRAVEL_SWIM, TRAVEL_TELEPORT, TRAVEL_WALK, TRAVEL_WALKOFFLEDGE, TRAVEL_WATERJUMP, and TRAVELTYPE_MASK.
Referenced by AAS_ShowReachableAreas(), and BotMoveToGoal().
void AAS_ShowArea (int areanum, int groundfacesonly)
References aasworld, abs(), aas_s::areas, botimport, botlib_import_s::DebugLineCreate, debuglines, botlib_import_s::DebugLineShow, debuglinevisible, aas_s::edgeindex, aas_s::edges, FACE_GROUND, FACE_LADDER, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, line, LINECOLOR_BLUE, LINECOLOR_GREEN, LINECOLOR_RED, LINECOLOR_YELLOW, MAX_DEBUGLINES, n, aas_s::numareas, numdebuglines, aas_face_s::numedges, aas_s::numedges, aas_area_s::numfaces, aas_s::numfaces, PRT_ERROR, qfalse, qtrue, aas_edge_s::v, and aas_s::vertexes.
void AAS_ShowAreaPolygons (int areanum, int color, int groundfacesonly)
References AAS_ShowFacePolygon(), aasworld, abs(), aas_s::areas, botimport, FACE_GROUND, FACE_LADDER, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_face_s::frontarea, aas_s::numareas, aas_area_s::numfaces, aas_s::numfaces, and PRT_ERROR.
Referenced by AAS_AlternativeRouteGoals(), AAS_FloodAreas_r(), AAS_ShowReachability(), and BotExportTest().
void AAS_ShowBoundingBox (vec3_t origin, vec3_t mins, vec3_t maxs)
References botimport, Com_Memcpy, botlib_import_s::DebugLineCreate, debuglines, botlib_import_s::DebugLineShow, debuglinevisible, line, LINECOLOR_RED, MAX_DEBUGLINES, numdebuglines, and qtrue.
Referenced by BotExportTest().
void AAS_ShowFace (int facenum)
References AAS_DebugLine(), aasworld, abs(), botimport, aas_s::edgeindex, aas_s::edges, end, aas_s::faces, aas_face_s::firstedge, LINECOLOR_BLUE, LINECOLOR_GREEN, LINECOLOR_RED, LINECOLOR_YELLOW, aas_plane_s::normal, aas_face_s::numedges, aas_s::numedges, aas_s::numfaces, aas_face_s::planenum, aas_s::planes, PRT_ERROR, start, aas_edge_s::v, VectorCopy, VectorMA(), and aas_s::vertexes.
Referenced by BotExportTest().
void AAS_ShowFacePolygon (int facenum, int color, int flip)
References AAS_ShowPolygon(), aasworld, abs(), botimport, aas_s::edgeindex, aas_s::edges, aas_s::faces, aas_face_s::firstedge, aas_face_s::numedges, aas_s::numfaces, PRT_ERROR, aas_edge_s::v, VectorCopy, and aas_s::vertexes.
Referenced by AAS_ShowAreaPolygons().
void AAS_ShowPolygon (int color, int numpoints, vec3_t * points)
References botimport, botlib_import_s::DebugPolygonCreate, debugpolygons, and MAX_DEBUGPOLYGONS.
Referenced by AAS_ShowFacePolygon().
void AAS_ShowReachability (aas_reachability_t * reach)
References AAS_DrawArrow(), AAS_DrawCross(), AAS_HorizontalVelocityForJump(), AAS_JumpReachRunStart(), AAS_PredictClientMovement(), AAS_RocketJumpZVelocity(), AAS_ShowAreaPolygons(), aassettings, aas_reachability_s::areanum, aas_reachability_s::edgenum, aas_reachability_s::end, aas_reachability_s::facenum, LINECOLOR_BLUE, LINECOLOR_YELLOW, move(), aas_settings_s::phys_jumpvel, PRESENCE_NORMAL, qtrue, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_HITGROUND, SE_HITGROUNDAREA, SE_HITGROUNDDAMAGE, SE_TOUCHJUMPPAD, aas_reachability_s::start, TRAVEL_JUMP, TRAVEL_JUMPPAD, TRAVEL_ROCKETJUMP, TRAVEL_WALKOFFLEDGE, aas_reachability_s::traveltype, TRAVELTYPE_MASK, VectorClear, VectorNormalize(), VectorScale, VectorSet, and VectorSubtract.
Referenced by AAS_ShowReachableAreas(), BotExportTest(), and BotMoveToGoal().
void AAS_ShowReachableAreas (int areanum)
References AAS_PrintTravelType(), AAS_ShowReachability(), AAS_Time(), aasworld, aas_s::areasettings, botimport, Com_Memcpy, aas_areasettings_s::firstreachablearea, aas_areasettings_s::numreachableareas, PRT_MESSAGE, reach(), aas_s::reachability, aas_reachability_s::traveltype, and TRAVELTYPE_MASK.
Referenced by BotExportTest().
Variable Documentation
int debuglines[MAX_DEBUGLINES]
Referenced by AAS_ClearShownDebugLines(), AAS_DebugLine(), AAS_DrawPlaneCross(), AAS_ShowArea(), and AAS_ShowBoundingBox().
int debuglinevisible[MAX_DEBUGLINES]
Referenced by AAS_ClearShownDebugLines(), AAS_DebugLine(), AAS_DrawPlaneCross(), AAS_ShowArea(), and AAS_ShowBoundingBox().
int debugpolygons[MAX_DEBUGPOLYGONS] [static]
Referenced by AAS_ClearShownPolygons(), and AAS_ShowPolygon().
int numdebuglines
Referenced by AAS_DebugLine(), AAS_DrawPlaneCross(), AAS_ShowArea(), and AAS_ShowBoundingBox().