ioquake3: code/botlib/be_interface.c File Reference
be_interface.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_log.h"
#include "l_libvar.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_aas_def.h"
#include "be_interface.h"
#include "be_ea.h"
#include "be_ai_weight.h"
#include "be_ai_goal.h"
#include "be_ai_move.h"
#include "be_ai_weap.h"
#include "be_ai_chat.h"
#include "be_ai_char.h"
#include "be_ai_gen.h"
Functions
int Sys_MilliSeconds (void)
qboolean ValidClientNumber (int num, char *str)
qboolean ValidEntityNumber (int num, char *str)
qboolean BotLibSetup (char *str)
int Export_BotLibSetup (void)
int Export_BotLibShutdown (void)
int Export_BotLibVarSet (char *var_name, char *value)
int Export_BotLibVarGet (char *var_name, char *value, int size)
int Export_BotLibStartFrame (float time)
int Export_BotLibLoadMap (const char *mapname)
int Export_BotLibUpdateEntity (int ent, bot_entitystate_t *state)
void AAS_TestMovementPrediction (int entnum, vec3_t origin, vec3_t dir)
void ElevatorBottomCenter (aas_reachability_t *reach, vec3_t bottomcenter)
int BotGetReachabilityToGoal (vec3_t origin, int areanum, int lastgoalareanum, int lastareanum, int *avoidreach, float *avoidreachtimes, int *avoidreachtries, bot_goal_t *goal, int travelflags, int movetravelflags, struct bot_avoidspot_s *avoidspots, int numavoidspots, int *flags)
int AAS_PointLight (vec3_t origin, int *red, int *green, int *blue)
int AAS_TraceAreas (vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
int AAS_Reachability_WeaponJump (int area1num, int area2num)
int BotFuzzyPointReachabilityArea (vec3_t origin)
float BotGapDistance (vec3_t origin, vec3_t hordir, int entnum)
void AAS_FloodAreas (vec3_t origin)
int BotExportTest (int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
static void Init_AAS_Export (aas_export_t *aas)
static void Init_EA_Export (ea_export_t *ea)
static void Init_AI_Export (ai_export_t *ai)
botlib_export_t * GetBotLibAPI (int apiVersion, botlib_import_t *import)
Variables
botlib_globals_t botlibglobals
botlib_export_t be_botlib_export
botlib_import_t botimport
int botDeveloper
int botlibsetup = qfalse
Function Documentation
void AAS_FloodAreas (vec3_t origin)
References AAS_AreaCluster(), AAS_FloodAreas_r(), AAS_PointAreaNum(), aasworld, GetClearedMemory(), and aas_s::numareas.
Referenced by BotExportTest().
int AAS_PointLight (vec3_t origin, int * red, int * green, int * blue)
int AAS_Reachability_WeaponJump (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaGrounded(), AAS_AreaSwim(), AAS_BFGJumpZVelocity(), AAS_FaceCenter(), AAS_HorizontalVelocityForJump(), AAS_PointAreaNum(), AAS_PredictClientMovement(), AAS_RocketJumpZVelocity(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), AREA_WEAPONJUMP, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, aas_s::areas, aas_s::areasettings, aas_area_s::center, aas_lreachability_s::edgenum, end, aas_lreachability_s::end, aas_trace_s::endpos, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_area_s::firstface, aas_clientmove_s::frames, Log_Write(), aas_area_s::maxs, aas_area_s::mins, move(), n, aas_lreachability_s::next, aas_area_s::numfaces, PRESENCE_CROUCH, PRESENCE_NORMAL, qfalse, qtrue, reach_rocketjump, aas_settings_s::rs_bfgjump, aas_settings_s::rs_rocketjump, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_HITGROUND, SE_HITGROUNDAREA, SE_HITGROUNDDAMAGE, SE_TOUCHJUMPPAD, start, aas_lreachability_s::start, aas_trace_s::startsolid, aas_clientmove_s::stopevent, TRAVEL_BFGJUMP, TRAVEL_ROCKETJUMP, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorCopy, VectorScale, VectorSet, and VectorSubtract.
Referenced by AAS_ContinueInitReachability().
void AAS_TestMovementPrediction (int entnum, vec3_t origin, vec3_t dir)
References AAS_ClearShownDebugLines(), AAS_PredictClientMovement(), AAS_Swimming(), move(), PRESENCE_NORMAL, PRT_MESSAGE, qtrue, SE_HITGROUND, SE_LEAVEGROUND, aas_clientmove_s::stopevent, VectorClear, VectorNormalize(), and VectorScale.
int AAS_TraceAreas (vec3_t start, vec3_t end, int * areas, vec3_t * points, int maxareas)
References aasworld, botimport, aas_node_s::children, aas_plane_s::dist, DotProduct, aas_tracestack_s::end, aas_s::loaded, aas_tracestack_s::nodenum, aas_s::nodes, aas_plane_s::normal, aas_s::numareasettings, aas_s::numnodes, aas_tracestack_s::planenum, aas_node_s::planenum, aas_s::planes, PRT_ERROR, aas_tracestack_s::start, aas_plane_s::type, and VectorCopy.
Referenced by AAS_ClientMovementPrediction(), AAS_InitReachabilityAreas(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_WalkOffLedge(), BotFuzzyPointReachabilityArea(), BotMoveToGoal(), and Init_AAS_Export().
int BotExportTest (int parm0, char * parm1, vec3_t parm2, vec3_t parm3)
References AAS_AreaCluster(), AAS_AreaTravelTimeToGoalArea(), AAS_ClearShownDebugLines(), AAS_ClearShownPolygons(), AAS_DrawPlaneCross(), AAS_FloodAreas(), AAS_PointPresenceType(), AAS_ReachabilityFromNum(), AAS_ShowAreaPolygons(), AAS_ShowBoundingBox(), AAS_ShowFace(), AAS_ShowReachability(), AAS_ShowReachableAreas(), AAS_Trace(), AAS_TraceEndFace(), aasworld, AngleVectors(), AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_DONOTENTER, AREACONTENTS_JUMPPAD, AREACONTENTS_LAVA, AREACONTENTS_MOVER, AREACONTENTS_SLIME, AREACONTENTS_VIEWPORTAL, AREACONTENTS_WATER, bot_goal_s::areanum, aas_reachability_s::areanum, aas_s::areasettings, BotFuzzyPointReachabilityArea(), BotGetReachabilityToGoal(), aas_areasettings_s::contents, botlib_import_s::DebugLineCreate, botlib_import_s::DebugLineShow, end, aas_reachability_s::end, aas_s::entities, aas_s::faces, forward, LibVarGetValue(), line, LINECOLOR_BLUE, LINECOLOR_GREEN, LINECOLOR_RED, LINECOLOR_YELLOW, aas_s::loaded, MASK_PLAYERSOLID, MAX_AVOIDREACH, NULL, bot_goal_s::origin, PRT_MESSAGE, reach(), right, TFL_DEFAULT, TFL_FUNCBOB, TFL_ROCKETJUMP, VectorClear, VectorCopy, and VectorMA().
Referenced by GetBotLibAPI().
int BotFuzzyPointReachabilityArea (vec3_t origin)
References AAS_AreaReachability(), AAS_PointAreaNum(), AAS_TraceAreas(), end, VectorCopy, VectorLength(), and VectorSubtract.
Referenced by BotExportTest(), BotMoveToGoal(), and BotReachabilityArea().
float BotGapDistance (vec3_t origin, vec3_t hordir, int entnum)
References AAS_PointContents(), AAS_TraceClientBBox(), CONTENTS_WATER, end, aas_trace_s::endpos, aas_trace_s::fraction, PRESENCE_CROUCH, start, aas_trace_s::startsolid, libvar_s::value, VectorCopy, and VectorMA().
Referenced by BotTravel_Walk(), and BotWalkInDirection().
int BotGetReachabilityToGoal (vec3_t origin, int areanum, int lastgoalareanum, int lastareanum, int * avoidreach, float * avoidreachtimes, int * avoidreachtries, bot_goal_t * goal, int travelflags, int movetravelflags, struct bot_avoidspot_s * avoidspots, int numavoidspots, int * flags)
References AAS_AreaDoNotEnter(), AAS_AreaTravelTimeToGoalArea(), AAS_NextAreaReachability(), AAS_ReachabilityFromNum(), AAS_Time(), bot_goal_s::areanum, aas_reachability_s::areanum, AVOIDREACH_TRIES, BotAvoidSpots(), botDeveloper, botimport, BotValidTravel(), aas_reachability_s::end, MAX_AVOIDREACH, MOVERESULT_BLOCKEDBYAVOIDSPOT, PRT_MESSAGE, reach(), t, TFL_DONOTENTER, and aas_reachability_s::traveltime.
Referenced by BotExportTest(), BotMovementViewTarget(), BotMoveToGoal(), and BotPredictVisiblePosition().
qboolean BotLibSetup (char * str)
References botlib_globals_s::botlibsetup, PRT_ERROR, qfalse, and qtrue.
Referenced by Export_BotLibLoadMap(), Export_BotLibShutdown(), Export_BotLibStartFrame(), and Export_BotLibUpdateEntity().
void ElevatorBottomCenter (aas_reachability_t * reach, vec3_t bottomcenter)
int Export_BotLibLoadMap (const char * mapname)
References AAS_LoadMap(), BLERR_LIBRARYNOTSETUP, BLERR_NOERROR, BotInitLevelItems(), BotLibSetup(), BotSetBrushModelTypes(), PRT_MESSAGE, and Sys_MilliSeconds().
Referenced by GetBotLibAPI().
int Export_BotLibSetup (void)
References AAS_Setup(), BASEGAME, BLERR_NOERROR, botDeveloper, botlib_globals_s::botlibsetup, botlibsetup, BotSetupChatAI(), BotSetupGoalAI(), BotSetupMoveAI(), BotSetupWeaponAI(), Com_sprintf(), EA_Setup(), gamedir, int(), LibVarGetString(), LibVarGetValue(), LibVarValue(), Log_Open(), MAX_OSPATH, botlib_globals_s::maxclients, botlib_globals_s::maxentities, PRT_MESSAGE, and qtrue.
Referenced by GetBotLibAPI().
int Export_BotLibShutdown (void)
References AAS_Shutdown(), BLERR_LIBRARYNOTSETUP, BLERR_NOERROR, botlib_globals_s::botlibsetup, botlibsetup, BotLibSetup(), BotShutdownCharacters(), BotShutdownChatAI(), BotShutdownGoalAI(), BotShutdownMoveAI(), BotShutdownWeaponAI(), BotShutdownWeights(), EA_Shutdown(), LibVarDeAllocAll(), Log_Shutdown(), PC_CheckOpenSourceHandles(), PC_RemoveAllGlobalDefines(), PrintMemoryLabels(), and qfalse.
Referenced by GetBotLibAPI().
int Export_BotLibStartFrame (float time)
References AAS_StartFrame(), BLERR_LIBRARYNOTSETUP, and BotLibSetup().
Referenced by GetBotLibAPI().
int Export_BotLibUpdateEntity (int ent, bot_entitystate_t * state)
References AAS_UpdateEntity(), BLERR_INVALIDENTITYNUMBER, BLERR_LIBRARYNOTSETUP, BotLibSetup(), and ValidEntityNumber().
Referenced by GetBotLibAPI().
int Export_BotLibVarGet (char * var_name, char * value, int size)
References BLERR_NOERROR, and LibVarGetString().
Referenced by GetBotLibAPI().
int Export_BotLibVarSet (char * var_name, char * value)
References BLERR_NOERROR, and LibVarSet().
Referenced by GetBotLibAPI().
botlib_export_t* GetBotLibAPI (int apiVersion, botlib_import_t * import)
References botlib_export_s::aas, botlib_export_s::ai, be_botlib_export, BotExportTest(), BOTLIB_API_VERSION, botlib_export_s::BotLibLoadMap, botlib_export_s::BotLibSetup, botlib_export_s::BotLibShutdown, botlib_export_s::BotLibStartFrame, botlib_export_s::BotLibUpdateEntity, botlib_export_s::BotLibVarGet, botlib_export_s::BotLibVarSet, Com_Memset, botlib_export_s::ea, Export_BotLibLoadMap(), Export_BotLibSetup(), Export_BotLibShutdown(), Export_BotLibStartFrame(), Export_BotLibUpdateEntity(), Export_BotLibVarGet(), Export_BotLibVarSet(), Init_AAS_Export(), Init_AI_Export(), Init_EA_Export(), NULL, botlib_export_s::PC_AddGlobalDefine, PC_AddGlobalDefine(), botlib_export_s::PC_FreeSourceHandle, PC_FreeSourceHandle(), botlib_export_s::PC_LoadSourceHandle, PC_LoadSourceHandle(), botlib_export_s::PC_ReadTokenHandle, PC_ReadTokenHandle(), botlib_export_s::PC_SourceFileAndLine, PC_SourceFileAndLine(), PRT_ERROR, and botlib_export_s::Test.
Referenced by SV_BotInitBotLib().
static void Init_AAS_Export (aas_export_t * aas) [static]
References AAS_AlternativeRouteGoals(), aas_export_s::AAS_AlternativeRouteGoals, aas_export_s::AAS_AreaInfo, AAS_AreaInfo(), aas_export_s::AAS_AreaReachability, AAS_AreaReachability(), aas_export_s::AAS_AreaTravelTimeToGoalArea, AAS_AreaTravelTimeToGoalArea(), aas_export_s::AAS_BBoxAreas, AAS_BBoxAreas(), aas_export_s::AAS_EnableRoutingArea, AAS_EnableRoutingArea(), AAS_EntityInfo(), aas_export_s::AAS_EntityInfo, AAS_FloatForBSPEpairKey(), aas_export_s::AAS_FloatForBSPEpairKey, AAS_Initialized(), aas_export_s::AAS_Initialized, AAS_IntForBSPEpairKey(), aas_export_s::AAS_IntForBSPEpairKey, AAS_NextBSPEntity(), aas_export_s::AAS_NextBSPEntity, AAS_PointAreaNum(), aas_export_s::AAS_PointAreaNum, AAS_PointContents(), aas_export_s::AAS_PointContents, aas_export_s::AAS_PointReachabilityAreaIndex, AAS_PointReachabilityAreaIndex(), aas_export_s::AAS_PredictClientMovement, AAS_PredictClientMovement(), aas_export_s::AAS_PredictRoute, AAS_PredictRoute(), AAS_PresenceTypeBoundingBox(), aas_export_s::AAS_PresenceTypeBoundingBox, AAS_Swimming(), aas_export_s::AAS_Swimming, aas_export_s::AAS_Time, AAS_Time(), aas_export_s::AAS_TraceAreas, AAS_TraceAreas(), AAS_ValueForBSPEpairKey(), aas_export_s::AAS_ValueForBSPEpairKey, AAS_VectorForBSPEpairKey(), and aas_export_s::AAS_VectorForBSPEpairKey.
Referenced by GetBotLibAPI().
static void Init_AI_Export (ai_export_t * ai) [static]
References ai_export_s::BotAddAvoidSpot, BotAddAvoidSpot(), ai_export_s::BotAllocChatState, BotAllocChatState(), ai_export_s::BotAllocGoalState, BotAllocGoalState(), BotAllocMoveState(), ai_export_s::BotAllocMoveState, ai_export_s::BotAllocWeaponState, BotAllocWeaponState(), ai_export_s::BotAvoidGoalTime, BotAvoidGoalTime(), ai_export_s::BotChatLength, BotChatLength(), ai_export_s::BotChooseBestFightWeapon, BotChooseBestFightWeapon(), ai_export_s::BotChooseLTGItem, BotChooseLTGItem(), ai_export_s::BotChooseNBGItem, BotChooseNBGItem(), ai_export_s::BotDumpAvoidGoals, BotDumpAvoidGoals(), ai_export_s::BotDumpGoalStack, BotDumpGoalStack(), ai_export_s::BotEmptyGoalStack, BotEmptyGoalStack(), ai_export_s::BotEnterChat, BotEnterChat(), ai_export_s::BotFindMatch, BotFindMatch(), BotFreeCharacter(), ai_export_s::BotFreeCharacter, ai_export_s::BotFreeChatState, BotFreeChatState(), ai_export_s::BotFreeGoalState, BotFreeGoalState(), ai_export_s::BotFreeItemWeights, BotFreeItemWeights(), BotFreeMoveState(), ai_export_s::BotFreeMoveState, ai_export_s::BotFreeWeaponState, BotFreeWeaponState(), ai_export_s::BotGetChatMessage, BotGetChatMessage(), ai_export_s::BotGetLevelItemGoal, BotGetLevelItemGoal(), ai_export_s::BotGetMapLocationGoal, BotGetMapLocationGoal(), ai_export_s::BotGetNextCampSpotGoal, BotGetNextCampSpotGoal(), ai_export_s::BotGetSecondGoal, BotGetSecondGoal(), ai_export_s::BotGetTopGoal, BotGetTopGoal(), ai_export_s::BotGetWeaponInfo, BotGetWeaponInfo(), ai_export_s::BotGoalName, BotGoalName(), ai_export_s::BotInitialChat, BotInitialChat(), ai_export_s::BotInitLevelItems, BotInitLevelItems(), BotInitMoveState(), ai_export_s::BotInitMoveState, BotInterbreedGoalFuzzyLogic(), ai_export_s::BotInterbreedGoalFuzzyLogic, ai_export_s::BotItemGoalInVisButNotVisible, BotItemGoalInVisButNotVisible(), ai_export_s::BotLoadCharacter, BotLoadCharacter(), ai_export_s::BotLoadChatFile, BotLoadChatFile(), ai_export_s::BotLoadItemWeights, BotLoadItemWeights(), BotLoadWeaponWeights(), ai_export_s::BotLoadWeaponWeights, ai_export_s::BotMatchVariable, BotMatchVariable(), ai_export_s::BotMoveInDirection, BotMoveInDirection(), ai_export_s::BotMovementViewTarget, BotMovementViewTarget(), ai_export_s::BotMoveToGoal, BotMoveToGoal(), BotMutateGoalFuzzyLogic(), ai_export_s::BotMutateGoalFuzzyLogic, ai_export_s::BotNextConsoleMessage, BotNextConsoleMessage(), ai_export_s::BotNumConsoleMessages, BotNumConsoleMessages(), ai_export_s::BotNumInitialChats, BotNumInitialChats(), ai_export_s::BotPopGoal, BotPopGoal(), ai_export_s::BotPredictVisiblePosition, BotPredictVisiblePosition(), ai_export_s::BotPushGoal, BotPushGoal(), ai_export_s::BotQueueConsoleMessage, BotQueueConsoleMessage(), BotReachabilityArea(), ai_export_s::BotReachabilityArea, BotRemoveConsoleMessage(), ai_export_s::BotRemoveConsoleMessage, ai_export_s::BotRemoveFromAvoidGoals, BotRemoveFromAvoidGoals(), ai_export_s::BotReplaceSynonyms, BotReplaceSynonyms(), ai_export_s::BotReplyChat, BotReplyChat(), ai_export_s::BotResetAvoidGoals, BotResetAvoidGoals(), ai_export_s::BotResetAvoidReach, BotResetAvoidReach(), ai_export_s::BotResetGoalState, BotResetGoalState(), ai_export_s::BotResetLastAvoidReach, BotResetLastAvoidReach(), ai_export_s::BotResetMoveState, BotResetMoveState(), ai_export_s::BotResetWeaponState, BotResetWeaponState(), BotSaveGoalFuzzyLogic(), ai_export_s::BotSaveGoalFuzzyLogic, ai_export_s::BotSetAvoidGoalTime, BotSetAvoidGoalTime(), ai_export_s::BotSetChatGender, BotSetChatGender(), ai_export_s::BotSetChatName, BotSetChatName(), ai_export_s::BotTouchingGoal, BotTouchingGoal(), ai_export_s::BotUpdateEntityItems, BotUpdateEntityItems(), ai_export_s::Characteristic_BFloat, Characteristic_BFloat(), ai_export_s::Characteristic_BInteger, Characteristic_BInteger(), ai_export_s::Characteristic_Float, Characteristic_Float(), ai_export_s::Characteristic_Integer, Characteristic_Integer(), ai_export_s::Characteristic_String, Characteristic_String(), GeneticParentsAndChildSelection(), ai_export_s::GeneticParentsAndChildSelection, ai_export_s::StringContains, StringContains(), ai_export_s::UnifyWhiteSpaces, and UnifyWhiteSpaces().
Referenced by GetBotLibAPI().
static void Init_EA_Export (ea_export_t * ea) [static]
References ea_export_s::EA_Action, EA_Action(), EA_Attack(), ea_export_s::EA_Attack, EA_Command(), ea_export_s::EA_Command, EA_Crouch(), ea_export_s::EA_Crouch, EA_DelayedJump(), ea_export_s::EA_DelayedJump, ea_export_s::EA_EndRegular, EA_EndRegular(), EA_Gesture(), ea_export_s::EA_Gesture, ea_export_s::EA_GetInput, EA_GetInput(), EA_Jump(), ea_export_s::EA_Jump, ea_export_s::EA_Move, EA_Move(), ea_export_s::EA_MoveBack, EA_MoveBack(), ea_export_s::EA_MoveDown, EA_MoveDown(), ea_export_s::EA_MoveForward, EA_MoveForward(), ea_export_s::EA_MoveLeft, EA_MoveLeft(), ea_export_s::EA_MoveRight, EA_MoveRight(), ea_export_s::EA_MoveUp, EA_MoveUp(), ea_export_s::EA_ResetInput, EA_ResetInput(), EA_Respawn(), ea_export_s::EA_Respawn, EA_Say(), ea_export_s::EA_Say, EA_SayTeam(), ea_export_s::EA_SayTeam, EA_SelectWeapon(), ea_export_s::EA_SelectWeapon, EA_Talk(), ea_export_s::EA_Talk, EA_Use(), ea_export_s::EA_Use, ea_export_s::EA_View, and EA_View().
Referenced by GetBotLibAPI().
int Sys_MilliSeconds (void)
Referenced by AAS_AlternativeRouteGoals(), AAS_CalculateAreaTravelTimes(), AAS_ContinueInitReachability(), AAS_CreateReversedReachability(), BotLoadCachedCharacter(), BotLoadInitialChat(), BotLoadRandomStrings(), BotSetupChatAI(), Export_BotLibLoadMap(), and ReadWeightConfig().
qboolean ValidClientNumber (int num, char * str)
References botlib_globals_s::maxclients, PRT_ERROR, qfalse, and qtrue.
qboolean ValidEntityNumber (int num, char * str)
References botlib_globals_s::maxentities, PRT_ERROR, qfalse, and qtrue.
Referenced by Export_BotLibUpdateEntity().
Variable Documentation
botlib_export_t be_botlib_export
Referenced by GetBotLibAPI().
int botDeveloper
Referenced by AAS_AllocAASLink(), AAS_AreaRouteToGoalArea(), AAS_EnableRoutingArea(), AAS_StartFrame(), BotGetReachabilityToGoal(), BotInitInfoEntities(), BotLoadCachedCharacter(), BotLoadInitialChat(), BotLoadReplyChat(), BotMoveToGoal(), Export_BotLibSetup(), and ReadWeightConfig().
botlib_import_t botimport
Referenced by AAS_AASLinkEntity(), AAS_AllocAASLink(), AAS_AlternativeRouteGoals(), AAS_AreaCluster(), AAS_AreaInfo(), AAS_AreaPresenceType(), AAS_AreaRouteToGoalArea(), AAS_CalculateAreaTravelTimes(), AAS_ClearShownDebugLines(), AAS_ClearShownPolygons(), AAS_ContinueInit(), AAS_CreateAllRoutingCache(), AAS_CreateReversedReachability(), AAS_DebugLine(), AAS_DrawPermanentCross(), AAS_DrawPlaneCross(), AAS_EnableRoutingArea(), AAS_EntityInfo(), AAS_EntityModelindex(), AAS_EntityModelNum(), AAS_EntityOrigin(), AAS_EntitySize(), AAS_EntityType(), AAS_Error(), AAS_IndexFromString(), AAS_InsideFace(), AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_LoadFiles(), AAS_NextAreaReachability(), AAS_Optimize(), AAS_PermanentLine(), AAS_PointAreaNum(), AAS_PresenceTypeBoundingBox(), AAS_PrintTravelType(), AAS_ReadCache(), AAS_ReadRouteCache(), AAS_RoutingInfo(), AAS_SetInitialized(), AAS_ShowArea(), AAS_ShowAreaPolygons(), AAS_ShowBoundingBox(), AAS_ShowFace(), AAS_ShowFacePolygon(), AAS_ShowPolygon(), AAS_ShowReachableAreas(), AAS_Shutdown(), AAS_StringFromIndex(), AAS_TraceAreas(), AAS_TraceClientBBox(), AAS_UpdateEntity(), AAS_WriteAASFile(), AAS_WriteAASLump(), AAS_WriteRouteCache(), AllocLevelItem(), AvailableMemory(), BotCharacterFromHandle(), BotChatStateFromHandle(), BotCheckChatMessageIntegrety(), BotConstructChatMessage(), BotEnterChat(), BotExpandChatMessage(), BotFreeCharacter2(), BotFreeChatState(), BotFreeGoalState(), BotFreeMoveState(), BotFreeWeaponState(), BotFuncBobStartEnd(), BotGetReachabilityToGoal(), BotGoalStateFromHandle(), BotInitialChat(), BotInitInfoEntities(), BotInitLevelItems(), BotLoadCachedCharacter(), BotLoadCharacter(), BotLoadCharacterFromFile(), BotLoadChatFile(), BotLoadInitialChat(), BotLoadItemWeights(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), BotLoadWeaponWeights(), BotMatchVariable(), BotMoveStateFromHandle(), BotMoveToGoal(), BotNumInitialChats(), BotOnMover(), BotPrintReplyChatKeys(), BotPushGoal(), BotQueueConsoleMessage(), BotReachabilityTime(), BotReplyChat(), BotResetGrapple(), BotSetBrushModelTypes(), BotSetupChatAI(), BotSetupGoalAI(), BotSetupWeaponAI(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotValidWeaponNumber(), BotWeaponStateFromHandle(), Characteristic_BFloat(), Characteristic_BInteger(), Characteristic_Float(), Characteristic_Integer(), Characteristic_String(), CheckCharacteristicIndex(), EA_Command(), EA_DropInv(), EA_DropItem(), EA_Say(), EA_SayTeam(), EA_Tell(), EA_UseInv(), EA_UseItem(), FreeMemory(), GeneticParentsAndChildSelection(), GetHunkMemory(), GetMemory(), InterbreedFuzzySeperator_r(), InterbreedWeightConfigs(), LoadItemConfig(), LoadScriptFile(), LoadWeaponConfig(), Log_Close(), Log_Open(), MoverBottomCenter(), MoverDown(), PC_CheckOpenSourceHandles(), ReadWeightConfig(), ScriptError(), ScriptWarning(), SourceError(), and SourceWarning().
botlib_globals_t botlibglobals
Referenced by EA_Setup(), and Log_WriteTimeStamped().
int botlibsetup = qfalse
Referenced by Export_BotLibSetup(), and Export_BotLibShutdown().