ioquake3: code/botlib/be_ai_chat.c File Reference
be_ai_chat.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_libvar.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_utils.h"
#include "l_log.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_ea.h"
#include "be_ai_chat.h"
Data Structures
struct bot_chatmessage_s
struct bot_chattype_s
struct bot_chat_s
struct bot_randomstring_s
struct bot_randomlist_s
struct bot_synonym_s
struct bot_synonymlist_s
struct bot_matchstring_s
struct bot_matchpiece_s
struct bot_matchtemplate_s
struct bot_replychatkey_s
struct bot_replychat_s
struct bot_stringlist_s
struct bot_chatstate_s
struct bot_ichatdata_t
Defines
#define ESCAPE_CHAR 0x01
#define MT_VARIABLE 1
#define MT_STRING 2
#define RCKFL_AND 1
#define RCKFL_NOT 2
#define RCKFL_NAME 4
#define RCKFL_STRING 8
#define RCKFL_VARIABLES 16
#define RCKFL_BOTNAMES 32
#define RCKFL_GENDERFEMALE 64
#define RCKFL_GENDERMALE 128
#define RCKFL_GENDERLESS 256
#define CHATMESSAGE_RECENTTIME 20
Typedefs
typedef struct bot_chatmessage_s bot_chatmessage_t
typedef struct bot_chattype_s bot_chattype_t
typedef struct bot_chat_s bot_chat_t
typedef struct bot_randomstring_s bot_randomstring_t
typedef struct bot_randomlist_s bot_randomlist_t
typedef struct bot_synonym_s bot_synonym_t
typedef struct bot_synonymlist_s bot_synonymlist_t
typedef struct bot_matchstring_s bot_matchstring_t
typedef struct bot_matchpiece_s bot_matchpiece_t
typedef struct bot_matchtemplate_s bot_matchtemplate_t
typedef struct bot_replychatkey_s bot_replychatkey_t
typedef struct bot_replychat_s bot_replychat_t
typedef struct bot_stringlist_s bot_stringlist_t
typedef struct bot_chatstate_s bot_chatstate_t
Functions
bot_chatstate_t * BotChatStateFromHandle (int handle)
void InitConsoleMessageHeap (void)
bot_consolemessage_t * AllocConsoleMessage (void)
void FreeConsoleMessage (bot_consolemessage_t *message)
void BotRemoveConsoleMessage (int chatstate, int handle)
void BotQueueConsoleMessage (int chatstate, int type, char *message)
int BotNextConsoleMessage (int chatstate, bot_consolemessage_t *cm)
int BotNumConsoleMessages (int chatstate)
int IsWhiteSpace (char c)
void BotRemoveTildes (char *message)
void UnifyWhiteSpaces (char *string)
int StringContains (char *str1, char *str2, int casesensitive)
char * StringContainsWord (char *str1, char *str2, int casesensitive)
void StringReplaceWords (char *string, char *synonym, char *replacement)
void BotDumpSynonymList (bot_synonymlist_t *synlist)
bot_synonymlist_t * BotLoadSynonyms (char *filename)
void BotReplaceSynonyms (char *string, unsigned long int context)
void BotReplaceWeightedSynonyms (char *string, unsigned long int context)
void BotReplaceReplySynonyms (char *string, unsigned long int context)
int BotLoadChatMessage (source_t *source, char *chatmessagestring)
void BotDumpRandomStringList (bot_randomlist_t *randomlist)
bot_randomlist_t * BotLoadRandomStrings (char *filename)
char * RandomString (char *name)
void BotDumpMatchTemplates (bot_matchtemplate_t *matches)
void BotFreeMatchPieces (bot_matchpiece_t *matchpieces)
bot_matchpiece_t * BotLoadMatchPieces (source_t *source, char *endtoken)
void BotFreeMatchTemplates (bot_matchtemplate_t *mt)
bot_matchtemplate_t * BotLoadMatchTemplates (char *matchfile)
int StringsMatch (bot_matchpiece_t *pieces, bot_match_t *match)
int BotFindMatch (char *str, bot_match_t *match, unsigned long int context)
void BotMatchVariable (bot_match_t *match, int variable, char *buf, int size)
bot_stringlist_t * BotFindStringInList (bot_stringlist_t *list, char *string)
bot_stringlist_t * BotCheckChatMessageIntegrety (char *message, bot_stringlist_t *stringlist)
void BotCheckInitialChatIntegrety (bot_chat_t *chat)
void BotCheckReplyChatIntegrety (bot_replychat_t *replychat)
void BotDumpReplyChat (bot_replychat_t *replychat)
void BotFreeReplyChat (bot_replychat_t *replychat)
void BotCheckValidReplyChatKeySet (source_t *source, bot_replychatkey_t *keys)
bot_replychat_t * BotLoadReplyChat (char *filename)
void BotDumpInitialChat (bot_chat_t *chat)
bot_chat_t * BotLoadInitialChat (char *chatfile, char *chatname)
void BotFreeChatFile (int chatstate)
int BotLoadChatFile (int chatstate, char *chatfile, char *chatname)
int BotExpandChatMessage (char *outmessage, char *message, unsigned long mcontext, bot_match_t *match, unsigned long vcontext, int reply)
void BotConstructChatMessage (bot_chatstate_t *chatstate, char *message, unsigned long mcontext, bot_match_t *match, unsigned long vcontext, int reply)
char * BotChooseInitialChatMessage (bot_chatstate_t *cs, char *type)
int BotNumInitialChats (int chatstate, char *type)
void BotInitialChat (int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
void BotPrintReplyChatKeys (bot_replychat_t *replychat)
int BotReplyChat (int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int BotChatLength (int chatstate)
void BotEnterChat (int chatstate, int clientto, int sendto)
void BotGetChatMessage (int chatstate, char *buf, int size)
void BotSetChatGender (int chatstate, int gender)
void BotSetChatName (int chatstate, char *name, int client)
void BotResetChatAI (void)
int BotAllocChatState (void)
void BotFreeChatState (int handle)
int BotSetupChatAI (void)
void BotShutdownChatAI (void)
Variables
bot_ichatdata_t * ichatdata [MAX_CLIENTS]
bot_chatstate_t * botchatstates [MAX_CLIENTS+1]
bot_consolemessage_t * consolemessageheap = NULL
bot_consolemessage_t * freeconsolemessages = NULL
bot_matchtemplate_t * matchtemplates = NULL
bot_synonymlist_t * synonyms = NULL
bot_randomlist_t * randomstrings = NULL
bot_replychat_t * replychats = NULL
Define Documentation
#define CHATMESSAGE_RECENTTIME 20
Referenced by BotChooseInitialChatMessage(), BotLoadInitialChat(), BotLoadReplyChat(), and BotReplyChat().
#define ESCAPE_CHAR 0x01
Referenced by BotCheckChatMessageIntegrety(), BotExpandChatMessage(), and BotLoadChatMessage().
#define MT_STRING 2
Referenced by BotCheckValidReplyChatKeySet(), BotDumpMatchTemplates(), BotDumpReplyChat(), BotFreeMatchPieces(), BotLoadMatchPieces(), BotPrintReplyChatKeys(), and StringsMatch().
#define MT_VARIABLE 1
Referenced by BotCheckValidReplyChatKeySet(), BotDumpMatchTemplates(), BotLoadMatchPieces(), and StringsMatch().
#define RCKFL_AND 1
Referenced by BotCheckValidReplyChatKeySet(), BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_BOTNAMES 32
Referenced by BotLoadReplyChat(), and BotReplyChat().
#define RCKFL_GENDERFEMALE 64
Referenced by BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_GENDERLESS 256
Referenced by BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_GENDERMALE 128
Referenced by BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_NAME 4
Referenced by BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_NOT 2
Referenced by BotCheckValidReplyChatKeySet(), BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_STRING 8
Referenced by BotCheckValidReplyChatKeySet(), BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
#define RCKFL_VARIABLES 16
Referenced by BotCheckValidReplyChatKeySet(), BotDumpReplyChat(), BotLoadReplyChat(), BotPrintReplyChatKeys(), and BotReplyChat().
Typedef Documentation
typedef struct bot_chat_s bot_chat_t
typedef struct bot_chatmessage_s bot_chatmessage_t
typedef struct bot_chatstate_s bot_chatstate_t
typedef struct bot_chattype_s bot_chattype_t
typedef struct bot_matchpiece_s bot_matchpiece_t
typedef struct bot_matchstring_s bot_matchstring_t
typedef struct bot_matchtemplate_s bot_matchtemplate_t
typedef struct bot_randomlist_s bot_randomlist_t
typedef struct bot_randomstring_s bot_randomstring_t
typedef struct bot_replychat_s bot_replychat_t
typedef struct bot_replychatkey_s bot_replychatkey_t
typedef struct bot_stringlist_s bot_stringlist_t
typedef struct bot_synonym_s bot_synonym_t
typedef struct bot_synonymlist_s bot_synonymlist_t
Function Documentation
bot_consolemessage_t* AllocConsoleMessage (void)
References freeconsolemessages, bot_consolemessage_s::next, NULL, and bot_consolemessage_s::prev.
Referenced by BotQueueConsoleMessage().
int BotAllocChatState (void)
References GetClearedMemory(), and MAX_CLIENTS.
Referenced by Init_AI_Export().
int BotChatLength (int chatstate)
References BotChatStateFromHandle(), and bot_chatstate_s::chatmessage.
Referenced by Init_AI_Export().
bot_chatstate_t* BotChatStateFromHandle (int handle)
References botimport, MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotChatLength(), BotEnterChat(), BotFreeChatFile(), BotGetChatMessage(), BotInitialChat(), BotLoadChatFile(), BotNextConsoleMessage(), BotNumConsoleMessages(), BotNumInitialChats(), BotQueueConsoleMessage(), BotRemoveConsoleMessage(), BotReplyChat(), BotSetChatGender(), and BotSetChatName().
bot_stringlist_t* BotCheckChatMessageIntegrety (char * message, bot_stringlist_t * stringlist)
References BotFindStringInList(), botimport, ESCAPE_CHAR, GetClearedMemory(), Log_Write(), MAX_MESSAGE_SIZE, bot_stringlist_s::next, PRT_FATAL, RandomString(), s, and bot_stringlist_s::string.
Referenced by BotCheckInitialChatIntegrety(), and BotCheckReplyChatIntegrety().
void BotCheckInitialChatIntegrety (bot_chat_t * chat)
References BotCheckChatMessageIntegrety(), bot_chatmessage_s::chatmessage, cm, bot_chattype_s::firstchatmessage, FreeMemory(), bot_chatmessage_s::next, bot_chattype_s::next, bot_stringlist_s::next, NULL, s, t, and bot_chat_s::types.
Referenced by BotLoadInitialChat().
void BotCheckReplyChatIntegrety (bot_replychat_t * replychat)
References BotCheckChatMessageIntegrety(), bot_chatmessage_s::chatmessage, cm, bot_replychat_s::firstchatmessage, FreeMemory(), bot_chatmessage_s::next, bot_replychat_s::next, bot_stringlist_s::next, NULL, and s.
Referenced by BotLoadReplyChat().
void BotCheckValidReplyChatKeySet (source_t * source, bot_replychatkey_t * keys)
References bot_matchpiece_s::firststring, bot_replychatkey_s::flags, m, bot_replychatkey_s::match, MT_STRING, MT_VARIABLE, bot_matchstring_s::next, bot_matchpiece_s::next, bot_replychatkey_s::next, qfalse, qtrue, RCKFL_AND, RCKFL_NOT, RCKFL_STRING, RCKFL_VARIABLES, SourceWarning(), bot_matchstring_s::string, bot_replychatkey_s::string, StringContains(), and bot_matchpiece_s::type.
Referenced by BotLoadReplyChat().
char* BotChooseInitialChatMessage (bot_chatstate_t * cs, char * type)
References AAS_Time(), bot_chatstate_s::chat, bot_chatmessage_s::chatmessage, CHATMESSAGE_RECENTTIME, bot_chattype_s::firstchatmessage, m, n, bot_chattype_s::name, bot_chatmessage_s::next, bot_chattype_s::next, NULL, Q_stricmp(), random, t, bot_chatmessage_s::time, and bot_chat_s::types.
Referenced by BotInitialChat().
void BotConstructChatMessage (bot_chatstate_t * chatstate, char * message, unsigned long mcontext, bot_match_t * match, unsigned long vcontext, int reply)
References BotExpandChatMessage(), botimport, bot_chatstate_s::chatmessage, MAX_MESSAGE_SIZE, and PRT_WARNING.
Referenced by BotInitialChat(), and BotReplyChat().
void BotDumpInitialChat (bot_chat_t * chat)
References bot_chatmessage_s::chatmessage, bot_chattype_s::firstchatmessage, Log_Write(), m, bot_chattype_s::name, bot_chatmessage_s::next, bot_chattype_s::next, bot_chattype_s::numchatmessages, t, and bot_chat_s::types.
void BotDumpMatchTemplates (bot_matchtemplate_t * matches)
References bot_matchtemplate_s::first, bot_matchpiece_s::firststring, fp, Log_FilePointer(), MT_STRING, MT_VARIABLE, bot_matchstring_s::next, bot_matchpiece_s::next, bot_matchtemplate_s::next, bot_matchstring_s::string, bot_matchtemplate_s::subtype, bot_matchpiece_s::type, bot_matchtemplate_s::type, and bot_matchpiece_s::variable.
void BotDumpRandomStringList (bot_randomlist_t * randomlist)
References bot_randomlist_s::firstrandomstring, fp, Log_FilePointer(), bot_randomstring_s::next, bot_randomlist_s::next, random, bot_randomstring_s::string, and bot_randomlist_s::string.
void BotDumpReplyChat (bot_replychat_t * replychat)
References bot_chatmessage_s::chatmessage, cm, bot_replychat_s::firstchatmessage, bot_matchpiece_s::firststring, bot_replychatkey_s::flags, fp, bot_replychat_s::keys, Log_FilePointer(), bot_replychatkey_s::match, MT_STRING, bot_chatmessage_s::next, bot_matchpiece_s::next, bot_replychatkey_s::next, bot_replychat_s::next, bot_replychat_s::priority, RCKFL_AND, RCKFL_GENDERFEMALE, RCKFL_GENDERLESS, RCKFL_GENDERMALE, RCKFL_NAME, RCKFL_NOT, RCKFL_STRING, RCKFL_VARIABLES, bot_matchstring_s::string, bot_replychatkey_s::string, bot_matchpiece_s::type, and bot_matchpiece_s::variable.
void BotDumpSynonymList (bot_synonymlist_t * synlist)
References bot_synonymlist_s::context, bot_synonymlist_s::firstsynonym, fp, Log_FilePointer(), bot_synonym_s::next, bot_synonymlist_s::next, bot_synonym_s::string, and bot_synonym_s::weight.
void BotEnterChat (int chatstate, int clientto, int sendto)
References BotChatStateFromHandle(), botimport, BotRemoveTildes(), CHAT_TEAM, CHAT_TELL, bot_chatstate_s::chatmessage, bot_chatstate_s::client, EA_Command(), LibVarGetValue(), PRT_MESSAGE, and va().
Referenced by Init_AI_Export().
int BotExpandChatMessage (char * outmessage, char * message, unsigned long mcontext, bot_match_t * match, unsigned long vcontext, int reply)
References botimport, BotReplaceReplySynonyms(), BotReplaceSynonyms(), BotReplaceWeightedSynonyms(), ESCAPE_CHAR, int(), bot_matchvariable_s::length, MAX_MATCHVARIABLES, MAX_MESSAGE_SIZE, bot_matchvariable_s::offset, PRT_ERROR, PRT_FATAL, ptr(), qfalse, qtrue, RandomString(), bot_match_s::string, and bot_match_s::variables.
Referenced by BotConstructChatMessage().
int BotFindMatch (char * str, bot_match_t * match, unsigned long int context)
References bot_matchtemplate_s::context, bot_matchtemplate_s::first, if(), MAX_MATCHVARIABLES, MAX_MESSAGE_SIZE, bot_matchtemplate_s::next, bot_matchvariable_s::offset, qfalse, qtrue, bot_match_s::string, StringsMatch(), bot_match_s::subtype, bot_matchtemplate_s::subtype, bot_match_s::type, bot_matchtemplate_s::type, and bot_match_s::variables.
Referenced by Init_AI_Export().
bot_stringlist_t* BotFindStringInList (bot_stringlist_t * list, char * string)
References bot_stringlist_s::next, NULL, s, and bot_stringlist_s::string.
Referenced by BotCheckChatMessageIntegrety().
void BotFreeChatFile (int chatstate)
References BotChatStateFromHandle(), bot_chatstate_s::chat, FreeMemory(), and NULL.
Referenced by BotFreeChatState(), and BotLoadChatFile().
void BotFreeChatState (int handle)
References BotFreeChatFile(), botimport, BotNextConsoleMessage(), BotRemoveConsoleMessage(), FreeMemory(), h, LibVarGetValue(), m, MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotShutdownChatAI(), and Init_AI_Export().
void BotFreeMatchPieces (bot_matchpiece_t * matchpieces)
References bot_matchpiece_s::firststring, FreeMemory(), MT_STRING, bot_matchstring_s::next, bot_matchpiece_s::next, and bot_matchpiece_s::type.
Referenced by BotFreeMatchTemplates(), BotFreeReplyChat(), and BotLoadMatchPieces().
void BotFreeMatchTemplates (bot_matchtemplate_t * mt)
References BotFreeMatchPieces(), bot_matchtemplate_s::first, FreeMemory(), and bot_matchtemplate_s::next.
Referenced by BotLoadMatchTemplates(), and BotShutdownChatAI().
void BotFreeReplyChat (bot_replychat_t * replychat)
References BotFreeMatchPieces(), cm, bot_replychat_s::firstchatmessage, FreeMemory(), bot_replychat_s::keys, bot_replychatkey_s::match, bot_chatmessage_s::next, bot_replychatkey_s::next, bot_replychat_s::next, and bot_replychatkey_s::string.
Referenced by BotLoadReplyChat(), and BotShutdownChatAI().
void BotGetChatMessage (int chatstate, char * buf, int size)
References BotChatStateFromHandle(), BotRemoveTildes(), and bot_chatstate_s::chatmessage.
Referenced by Init_AI_Export().
void BotInitialChat (int chatstate, char * type, int mcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
References BotChatStateFromHandle(), BotChooseInitialChatMessage(), BotConstructChatMessage(), botimport, bot_chatstate_s::chat, Com_Memset, bot_matchvariable_s::length, bot_matchvariable_s::offset, PRT_MESSAGE, qfalse, bot_match_s::string, and bot_match_s::variables.
Referenced by Init_AI_Export().
int BotLoadChatFile (int chatstate, char * chatfile, char * chatname)
References BLERR_CANNOTLOADICHAT, BLERR_NOERROR, BotChatStateFromHandle(), BotFreeChatFile(), botimport, BotLoadInitialChat(), bot_chatstate_s::chat, bot_ichatdata_t::chat, GetClearedMemory(), LibVarGetValue(), MAX_CLIENTS, n, PRT_FATAL, and Q_strncpyz().
Referenced by Init_AI_Export().
int BotLoadChatMessage (source_t * source, char * chatmessagestring)
References ESCAPE_CHAR, MAX_MESSAGE_SIZE, PC_CheckTokenString(), PC_ExpectAnyToken(), PC_ExpectTokenString(), ptr(), qfalse, qtrue, SourceError(), StripDoubleQuotes(), token, TT_INTEGER, TT_NAME, TT_NUMBER, and TT_STRING.
Referenced by BotLoadInitialChat(), BotLoadRandomStrings(), and BotLoadReplyChat().
bot_chat_t* BotLoadInitialChat (char * chatfile, char * chatname)
References BotCheckInitialChatIntegrety(), botDeveloper, BOTFILESBASEFOLDER, botimport, BotLoadChatMessage(), bot_chatmessage_s::chatmessage, CHATMESSAGE_RECENTTIME, bot_chattype_s::firstchatmessage, FreeSource(), GetClearedMemory(), LoadSourceFile(), MAX_CHATTYPE_NAME, MAX_MESSAGE_SIZE, bot_chattype_s::name, bot_chatmessage_s::next, bot_chattype_s::next, NULL, bot_chattype_s::numchatmessages, PAD, pass, PC_CheckTokenString(), PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, ptr(), Q_stricmp(), qfalse, qtrue, SourceError(), StripDoubleQuotes(), Sys_MilliSeconds(), bot_chatmessage_s::time, token, TT_STRING, and bot_chat_s::types.
Referenced by BotLoadChatFile().
bot_matchpiece_t* BotLoadMatchPieces (source_t * source, char * endtoken)
References BotFreeMatchPieces(), emptystring, bot_matchpiece_s::firststring, FreeSource(), GetClearedHunkMemory(), MAX_MATCHVARIABLES, MT_STRING, MT_VARIABLE, bot_matchstring_s::next, bot_matchpiece_s::next, NULL, PC_CheckTokenString(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), qfalse, qtrue, SourceError(), bot_matchstring_s::string, StripDoubleQuotes(), token, TT_INTEGER, TT_NUMBER, TT_STRING, bot_matchpiece_s::type, and bot_matchpiece_s::variable.
Referenced by BotLoadMatchTemplates(), and BotLoadReplyChat().
bot_matchtemplate_t* BotLoadMatchTemplates (char * matchfile)
References BOTFILESBASEFOLDER, BotFreeMatchTemplates(), botimport, BotLoadMatchPieces(), bot_matchtemplate_s::context, bot_matchtemplate_s::first, FreeSource(), GetClearedHunkMemory(), LoadSourceFile(), bot_matchtemplate_s::next, NULL, PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PC_UnreadLastToken(), PRT_ERROR, PRT_MESSAGE, SourceError(), bot_matchtemplate_s::subtype, token, TT_INTEGER, TT_NUMBER, and bot_matchtemplate_s::type.
Referenced by BotSetupChatAI().
bot_randomlist_t* BotLoadRandomStrings (char * filename)
References BOTFILESBASEFOLDER, botimport, BotLoadChatMessage(), bot_randomlist_s::firstrandomstring, FreeSource(), GetClearedHunkMemory(), LoadSourceFile(), MAX_MESSAGE_SIZE, bot_randomstring_s::next, bot_randomlist_s::next, NULL, bot_randomlist_s::numstrings, PAD, pass, PC_CheckTokenString(), PC_ExpectTokenString(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, ptr(), random, SourceError(), bot_randomstring_s::string, bot_randomlist_s::string, Sys_MilliSeconds(), token, and TT_NAME.
Referenced by BotSetupChatAI().
bot_replychat_t* BotLoadReplyChat (char * filename)
References BotCheckReplyChatIntegrety(), BotCheckValidReplyChatKeySet(), botDeveloper, BOTFILESBASEFOLDER, BotFreeReplyChat(), botimport, BotLoadChatMessage(), BotLoadMatchPieces(), bot_chatmessage_s::chatmessage, CHATMESSAGE_RECENTTIME, bot_replychat_s::firstchatmessage, bot_replychatkey_s::flags, FreeSource(), GetClearedHunkMemory(), if(), bot_replychat_s::keys, LoadSourceFile(), bot_replychatkey_s::match, MAX_MESSAGE_SIZE, bot_chatmessage_s::next, bot_replychatkey_s::next, bot_replychat_s::next, NULL, bot_replychat_s::numchatmessages, PC_CheckTokenString(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), bot_replychat_s::priority, PRT_ERROR, PRT_MESSAGE, RCKFL_AND, RCKFL_BOTNAMES, RCKFL_GENDERFEMALE, RCKFL_GENDERLESS, RCKFL_GENDERMALE, RCKFL_NAME, RCKFL_NOT, RCKFL_STRING, RCKFL_VARIABLES, SourceError(), bot_replychatkey_s::string, StripDoubleQuotes(), bot_chatmessage_s::time, token, TT_NUMBER, and TT_STRING.
Referenced by BotSetupChatAI().
bot_synonymlist_t* BotLoadSynonyms (char * filename)
References BOTFILESBASEFOLDER, botimport, bot_synonymlist_s::context, bot_synonymlist_s::firstsynonym, FreeSource(), GetClearedHunkMemory(), LoadSourceFile(), bot_synonym_s::next, bot_synonymlist_s::next, NULL, PAD, pass, PC_CheckTokenString(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, ptr(), SourceError(), bot_synonym_s::string, StripDoubleQuotes(), token, bot_synonymlist_s::totalweight, TT_NUMBER, TT_PUNCTUATION, TT_STRING, and bot_synonym_s::weight.
Referenced by BotSetupChatAI().
void BotMatchVariable (bot_match_t * match, int variable, char * buf, int size)
References botimport, bot_matchvariable_s::length, MAX_MATCHVARIABLES, bot_matchvariable_s::offset, PRT_FATAL, bot_match_s::string, and bot_match_s::variables.
Referenced by Init_AI_Export().
int BotNextConsoleMessage (int chatstate, bot_consolemessage_t * cm)
References BotChatStateFromHandle(), bot_chatstate_s::firstmessage, bot_consolemessage_s::handle, bot_consolemessage_s::message, Q_strncpyz(), bot_consolemessage_s::time, and bot_consolemessage_s::type.
Referenced by BotFreeChatState(), and Init_AI_Export().
int BotNumConsoleMessages (int chatstate)
References BotChatStateFromHandle(), and bot_chatstate_s::numconsolemessages.
Referenced by Init_AI_Export().
int BotNumInitialChats (int chatstate, char * type)
References BotChatStateFromHandle(), botimport, bot_chatstate_s::chat, LibVarGetValue(), bot_chattype_s::name, bot_chattype_s::next, bot_chattype_s::numchatmessages, PRT_MESSAGE, Q_stricmp(), t, and bot_chat_s::types.
Referenced by Init_AI_Export().
void BotPrintReplyChatKeys (bot_replychat_t * replychat)
References botimport, bot_matchpiece_s::firststring, bot_replychatkey_s::flags, bot_replychat_s::keys, bot_replychatkey_s::match, MT_STRING, bot_matchpiece_s::next, bot_replychatkey_s::next, bot_replychat_s::priority, PRT_MESSAGE, RCKFL_AND, RCKFL_GENDERFEMALE, RCKFL_GENDERLESS, RCKFL_GENDERMALE, RCKFL_NAME, RCKFL_NOT, RCKFL_STRING, RCKFL_VARIABLES, bot_matchstring_s::string, bot_replychatkey_s::string, bot_matchpiece_s::type, and bot_matchpiece_s::variable.
void BotQueueConsoleMessage (int chatstate, int type, char * message)
References AAS_Time(), AllocConsoleMessage(), BotChatStateFromHandle(), botimport, bot_chatstate_s::firstmessage, bot_consolemessage_s::handle, bot_chatstate_s::handle, bot_chatstate_s::lastmessage, m, MAX_MESSAGE_SIZE, bot_consolemessage_s::message, bot_consolemessage_s::next, NULL, bot_chatstate_s::numconsolemessages, bot_consolemessage_s::prev, PRT_ERROR, bot_consolemessage_s::time, type(), and bot_consolemessage_s::type.
Referenced by Init_AI_Export().
void BotRemoveConsoleMessage (int chatstate, int handle)
References BotChatStateFromHandle(), bot_chatstate_s::firstmessage, FreeConsoleMessage(), bot_consolemessage_s::handle, bot_chatstate_s::lastmessage, m, bot_consolemessage_s::next, bot_chatstate_s::numconsolemessages, and bot_consolemessage_s::prev.
Referenced by BotFreeChatState(), and Init_AI_Export().
void BotRemoveTildes (char * message)
References memmove().
Referenced by BotEnterChat(), BotGetChatMessage(), and BotReplyChat().
void BotReplaceReplySynonyms (char * string, unsigned long int context)
References Com_Memcpy, bot_synonymlist_s::context, bot_synonymlist_s::firstsynonym, memmove(), bot_synonym_s::next, bot_synonymlist_s::next, qfalse, bot_synonym_s::string, and StringContainsWord().
Referenced by BotExpandChatMessage().
void BotReplaceSynonyms (char * string, unsigned long int context)
References bot_synonymlist_s::context, bot_synonymlist_s::firstsynonym, bot_synonym_s::next, bot_synonymlist_s::next, bot_synonym_s::string, and StringReplaceWords().
Referenced by BotExpandChatMessage(), and Init_AI_Export().
void BotReplaceWeightedSynonyms (char * string, unsigned long int context)
References bot_synonymlist_s::context, bot_synonymlist_s::firstsynonym, bot_synonym_s::next, bot_synonymlist_s::next, random, bot_synonym_s::string, StringReplaceWords(), bot_synonymlist_s::totalweight, and bot_synonym_s::weight.
Referenced by BotExpandChatMessage().
int BotReplyChat (int chatstate, char * message, int mcontext, int vcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
References AAS_Time(), BotChatStateFromHandle(), BotConstructChatMessage(), botimport, BotRemoveTildes(), CHAT_GENDERFEMALE, CHAT_GENDERLESS, CHAT_GENDERMALE, bot_chatmessage_s::chatmessage, bot_chatstate_s::chatmessage, CHATMESSAGE_RECENTTIME, Com_Memcpy, Com_Memset, bot_replychat_s::firstchatmessage, bot_replychatkey_s::flags, bot_chatstate_s::gender, bot_replychat_s::keys, bot_matchvariable_s::length, LibVarGetValue(), m, bot_replychatkey_s::match, bot_chatstate_s::name, bot_chatmessage_s::next, bot_replychatkey_s::next, bot_replychat_s::next, NULL, bot_matchvariable_s::offset, bot_replychat_s::priority, PRT_MESSAGE, qfalse, qtrue, random, RCKFL_AND, RCKFL_BOTNAMES, RCKFL_GENDERFEMALE, RCKFL_GENDERLESS, RCKFL_GENDERMALE, RCKFL_NAME, RCKFL_NOT, RCKFL_STRING, RCKFL_VARIABLES, bot_match_s::string, bot_replychatkey_s::string, StringContains(), StringContainsWord(), StringsMatch(), bot_chatmessage_s::time, and bot_match_s::variables.
Referenced by Init_AI_Export().
void BotResetChatAI (void)
References bot_replychat_s::firstchatmessage, m, bot_chatmessage_s::next, bot_replychat_s::next, and bot_chatmessage_s::time.
void BotSetChatGender (int chatstate, int gender)
References BotChatStateFromHandle(), CHAT_GENDERFEMALE, CHAT_GENDERLESS, CHAT_GENDERMALE, and bot_chatstate_s::gender.
Referenced by Init_AI_Export().
void BotSetChatName (int chatstate, char * name, int client)
References BotChatStateFromHandle(), bot_chatstate_s::client, Com_Memset, and bot_chatstate_s::name.
Referenced by Init_AI_Export().
int BotSetupChatAI (void)
References BLERR_NOERROR, botimport, BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), file, InitConsoleMessageHeap(), LibVarString(), LibVarValue(), PRT_MESSAGE, and Sys_MilliSeconds().
Referenced by Export_BotLibSetup().
void BotShutdownChatAI (void)
References BotFreeChatState(), BotFreeMatchTemplates(), BotFreeReplyChat(), FreeMemory(), MAX_CLIENTS, and NULL.
Referenced by Export_BotLibShutdown().
void FreeConsoleMessage (bot_consolemessage_t * message)
References freeconsolemessages, bot_consolemessage_s::next, NULL, and bot_consolemessage_s::prev.
Referenced by BotRemoveConsoleMessage().
void InitConsoleMessageHeap (void)
References consolemessageheap, FreeMemory(), GetClearedHunkMemory(), int(), LibVarValue(), bot_consolemessage_s::next, NULL, and bot_consolemessage_s::prev.
Referenced by BotSetupChatAI().
int IsWhiteSpace (char c)
References qfalse, and qtrue.
Referenced by UnifyWhiteSpaces().
char* RandomString (char * name)
References bot_randomlist_s::firstrandomstring, bot_randomstring_s::next, bot_randomlist_s::next, NULL, bot_randomlist_s::numstrings, random, bot_randomstring_s::string, and bot_randomlist_s::string.
Referenced by BotCheckChatMessageIntegrety(), and BotExpandChatMessage().
int StringContains (char * str1, char * str2, int casesensitive)
References NULL.
Referenced by BotCheckValidReplyChatKeySet(), BotReplyChat(), Init_AI_Export(), and StringsMatch().
char* StringContainsWord (char * str1, char * str2, int casesensitive)
References NULL.
Referenced by BotReplaceReplySynonyms(), BotReplyChat(), and StringReplaceWords().
void StringReplaceWords (char * string, char * synonym, char * replacement)
References Com_Memcpy, memmove(), qfalse, and StringContainsWord().
Referenced by BotReplaceSynonyms(), and BotReplaceWeightedSynonyms().
int StringsMatch (bot_matchpiece_t * pieces, bot_match_t * match)
References bot_matchpiece_s::firststring, bot_matchvariable_s::length, MT_STRING, MT_VARIABLE, bot_matchstring_s::next, bot_matchpiece_s::next, NULL, bot_matchvariable_s::offset, qfalse, qtrue, bot_match_s::string, bot_matchstring_s::string, StringContains(), bot_matchpiece_s::type, bot_matchpiece_s::variable, and bot_match_s::variables.
Referenced by BotFindMatch(), and BotReplyChat().
void UnifyWhiteSpaces (char * string)
References IsWhiteSpace(), memmove(), and ptr().
Referenced by Init_AI_Export().
Variable Documentation
bot_chatstate_t* botchatstates[MAX_CLIENTS+1]
bot_consolemessage_t* consolemessageheap = NULL
Referenced by InitConsoleMessageHeap().
bot_consolemessage_t* freeconsolemessages = NULL
Referenced by AllocConsoleMessage(), and FreeConsoleMessage().
bot_ichatdata_t* ichatdata[MAX_CLIENTS]
bot_matchtemplate_t* matchtemplates = NULL
bot_randomlist_t* randomstrings = NULL
bot_replychat_t* replychats = NULL
bot_synonymlist_t* synonyms = NULL