ioquake3: code/botlib/be_ai_goal.h File Reference
be_ai_goal.h File Reference
Data Structures
struct bot_goal_s
Defines
#define MAX_AVOIDGOALS 256
#define MAX_GOALSTACK 8
#define GFL_NONE 0
#define GFL_ITEM 1
#define GFL_ROAM 2
#define GFL_DROPPED 4
Typedefs
typedef struct bot_goal_s bot_goal_t
Functions
void BotResetGoalState (int goalstate)
void BotResetAvoidGoals (int goalstate)
void BotRemoveFromAvoidGoals (int goalstate, int number)
void BotPushGoal (int goalstate, bot_goal_t *goal)
void BotPopGoal (int goalstate)
void BotEmptyGoalStack (int goalstate)
void BotDumpAvoidGoals (int goalstate)
void BotDumpGoalStack (int goalstate)
void BotGoalName (int number, char *name, int size)
int BotGetTopGoal (int goalstate, bot_goal_t *goal)
int BotGetSecondGoal (int goalstate, bot_goal_t *goal)
int BotChooseLTGItem (int goalstate, vec3_t origin, int *inventory, int travelflags)
int BotChooseNBGItem (int goalstate, vec3_t origin, int *inventory, int travelflags, bot_goal_t *ltg, float maxtime)
int BotTouchingGoal (vec3_t origin, bot_goal_t *goal)
int BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, bot_goal_t *goal)
int BotGetLevelItemGoal (int index, char *classname, bot_goal_t *goal)
int BotGetNextCampSpotGoal (int num, bot_goal_t *goal)
int BotGetMapLocationGoal (char *name, bot_goal_t *goal)
float BotAvoidGoalTime (int goalstate, int number)
void BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
void BotInitLevelItems (void)
void BotUpdateEntityItems (void)
void BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
void BotSaveGoalFuzzyLogic (int goalstate, char *filename)
void BotMutateGoalFuzzyLogic (int goalstate, float range)
int BotLoadItemWeights (int goalstate, char *filename)
void BotFreeItemWeights (int goalstate)
int BotAllocGoalState (int client)
void BotFreeGoalState (int handle)
int BotSetupGoalAI (void)
void BotShutdownGoalAI (void)
Define Documentation
#define GFL_DROPPED 4
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), BotGetItemTeamGoal(), BotGetLevelItemGoal(), and BotReachedGoal().
#define GFL_ITEM 1
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), BotGetLevelItemGoal(), BotItemGoalInVisButNotVisible(), and BotReachedGoal().
#define GFL_NONE 0
#define GFL_ROAM 2
Referenced by BotChooseLTGItem(), and BotChooseNBGItem().
#define MAX_AVOIDGOALS 256
Referenced by BotAddToAvoidGoals(), BotAvoidGoalTime(), BotDumpAvoidGoals(), BotRemoveFromAvoidGoals(), and BotResetAvoidGoals().
#define MAX_GOALSTACK 8
Referenced by BotPushGoal(), and BotResetGoalState().
Typedef Documentation
typedef struct bot_goal_s bot_goal_t
Function Documentation
int BotAllocGoalState (int client)
References bot_goalstate_s::client, GetClearedMemory(), and MAX_CLIENTS.
Referenced by Init_AI_Export().
float BotAvoidGoalTime (int goalstate, int number)
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalStateFromHandle(), and MAX_AVOIDGOALS.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and Init_AI_Export().
int BotChooseLTGItem (int goalstate, vec3_t origin, int * inventory, int travelflags)
References AAS_AreaReachability(), AAS_AreaTravelTimeToGoalArea(), bot_goal_s::areanum, AVOID_DEFAULT_TIME, AVOID_DROPPED_TIME, AVOID_MINIMUM_TIME, BotAddToAvoidGoals(), BotAvoidGoalTime(), BotGoalStateFromHandle(), BotPushGoal(), BotReachabilityArea(), bot_goalstate_s::client, Com_Memset, bot_goal_s::entitynum, levelitem_s::entitynum, bot_goal_s::flags, levelitem_s::flags, FuzzyWeight(), FuzzyWeightUndecided(), GFL_DROPPED, GFL_ITEM, GFL_ROAM, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, IFL_ROAM, itemconfig, bot_goal_s::iteminfo, levelitem_s::iteminfo, itemconfig_s::iteminfo, bot_goalstate_s::itemweightconfig, bot_goalstate_s::itemweightindex, bot_goalstate_s::lastreachabilityarea, bot_goal_s::maxs, iteminfo_s::maxs, bot_goal_s::mins, iteminfo_s::mins, levelitem_s::next, NULL, bot_goal_s::number, levelitem_s::number, iteminfo_s::number, bot_goal_s::origin, qfalse, qtrue, iteminfo_s::respawntime, t, levelitem_s::timeout, TRAVELTIME_SCALE, libvar_s::value, VectorCopy, and levelitem_s::weight.
Referenced by Init_AI_Export().
int BotChooseNBGItem (int goalstate, vec3_t origin, int * inventory, int travelflags, bot_goal_t * ltg, float maxtime)
References AAS_AreaReachability(), AAS_AreaTravelTimeToGoalArea(), bot_goal_s::areanum, AVOID_DEFAULT_TIME, AVOID_DROPPED_TIME, AVOID_MINIMUM_TIME, BotAddToAvoidGoals(), BotAvoidGoalTime(), BotGoalStateFromHandle(), BotPushGoal(), BotReachabilityArea(), bot_goalstate_s::client, Com_Memset, bot_goal_s::entitynum, levelitem_s::entitynum, bot_goal_s::flags, levelitem_s::flags, FuzzyWeight(), FuzzyWeightUndecided(), GFL_DROPPED, GFL_ITEM, GFL_ROAM, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, IFL_ROAM, itemconfig, bot_goal_s::iteminfo, levelitem_s::iteminfo, itemconfig_s::iteminfo, bot_goalstate_s::itemweightconfig, bot_goalstate_s::itemweightindex, bot_goalstate_s::lastreachabilityarea, bot_goal_s::maxs, iteminfo_s::maxs, bot_goal_s::mins, iteminfo_s::mins, levelitem_s::next, NULL, bot_goal_s::number, levelitem_s::number, iteminfo_s::number, bot_goal_s::origin, qfalse, qtrue, iteminfo_s::respawntime, t, levelitem_s::timeout, TRAVELTIME_SCALE, libvar_s::value, VectorCopy, and levelitem_s::weight.
Referenced by Init_AI_Export().
void BotDumpAvoidGoals (int goalstate)
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalName(), BotGoalStateFromHandle(), Log_Write(), and MAX_AVOIDGOALS.
Referenced by Init_AI_Export().
void BotDumpGoalStack (int goalstate)
References BotGoalName(), BotGoalStateFromHandle(), bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, Log_Write(), and bot_goal_s::number.
Referenced by BotPushGoal(), and Init_AI_Export().
void BotEmptyGoalStack (int goalstate)
References BotGoalStateFromHandle(), and bot_goalstate_s::goalstacktop.
Referenced by Init_AI_Export().
void BotFreeGoalState (int handle)
References BotFreeItemWeights(), botimport, FreeMemory(), MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotShutdownGoalAI(), and Init_AI_Export().
void BotFreeItemWeights (int goalstate)
References BotGoalStateFromHandle(), FreeMemory(), FreeWeightConfig(), bot_goalstate_s::itemweightconfig, and bot_goalstate_s::itemweightindex.
Referenced by BotFreeGoalState(), and Init_AI_Export().
int BotGetLevelItemGoal (int index, char * classname, bot_goal_t * goal)
References bot_goal_s::areanum, bot_goal_s::entitynum, levelitem_s::entitynum, bot_goal_s::flags, levelitem_s::flags, GFL_DROPPED, GFL_ITEM, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, levelitem_s::iteminfo, itemconfig_s::iteminfo, levelitems, bot_goal_s::maxs, iteminfo_s::maxs, bot_goal_s::mins, iteminfo_s::mins, iteminfo_s::name, levelitem_s::next, bot_goal_s::number, levelitem_s::number, bot_goal_s::origin, Q_stricmp(), levelitem_s::timeout, and VectorCopy.
Referenced by Init_AI_Export().
int BotGetMapLocationGoal (char * name, bot_goal_t * goal)
References bot_goal_s::areanum, maplocation_s::areanum, bot_goal_s::entitynum, bot_goal_s::maxs, bot_goal_s::mins, maplocation_s::name, maplocation_s::next, bot_goal_s::origin, maplocation_s::origin, Q_stricmp(), qfalse, qtrue, and VectorCopy.
Referenced by Init_AI_Export().
int BotGetNextCampSpotGoal (int num, bot_goal_t * goal)
References bot_goal_s::areanum, campspot_s::areanum, bot_goal_s::entitynum, bot_goal_s::maxs, bot_goal_s::mins, campspot_s::next, bot_goal_s::origin, campspot_s::origin, and VectorCopy.
Referenced by Init_AI_Export().
int BotGetSecondGoal (int goalstate, bot_goal_t * goal)
References BotGoalStateFromHandle(), Com_Memcpy, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, qfalse, and qtrue.
Referenced by Init_AI_Export().
int BotGetTopGoal (int goalstate, bot_goal_t * goal)
References BotGoalStateFromHandle(), Com_Memcpy, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, qfalse, and qtrue.
Referenced by Init_AI_Export().
void BotGoalName (int number, char * name, int size)
References levelitem_s::iteminfo, itemconfig_s::iteminfo, iteminfo_s::name, levelitem_s::next, and levelitem_s::number.
Referenced by BotDumpAvoidGoals(), BotDumpGoalStack(), and Init_AI_Export().
void BotInitLevelItems (void)
References AAS_BestReachableArea(), AAS_BestReachableFromJumpPadArea(), AAS_DropToFloor(), AAS_FloatForBSPEpairKey(), AAS_IntForBSPEpairKey(), AAS_Loaded(), AAS_NextBSPEntity(), AAS_PointContents(), AAS_Trace(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), AddLevelItemToList(), AllocLevelItem(), botimport, BotInitInfoEntities(), iteminfo_s::classname, CONTENTS_PLAYERCLIP, CONTENTS_SOLID, CONTENTS_WATER, end, levelitem_s::entitynum, levelitem_s::flags, levelitem_s::goalareanum, levelitem_s::goalorigin, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, IFL_ROAM, InitLevelItemHeap(), itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, Log_Write(), MAX_EPAIRKEY, iteminfo_s::maxs, iteminfo_s::mins, iteminfo_s::modelindex, NULL, levelitem_s::number, itemconfig_s::numiteminfo, numlevelitems, levelitem_s::origin, PRT_ERROR, PRT_MESSAGE, levelitem_s::timeout, value(), VectorCopy, and levelitem_s::weight.
Referenced by Export_BotLibLoadMap(), and Init_AI_Export().
void BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
References BotGoalStateFromHandle(), InterbreedWeightConfigs(), and bot_goalstate_s::itemweightconfig.
Referenced by Init_AI_Export().
int BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, bot_goal_t * goal)
References AAS_EntityInfo(), AAS_Time(), AAS_Trace(), CONTENTS_SOLID, bot_goal_s::entitynum, bot_goal_s::flags, GFL_ITEM, aas_entityinfo_s::ltime, bot_goal_s::mins, NULL, bot_goal_s::origin, qfalse, qtrue, VectorAdd, and VectorScale.
Referenced by Init_AI_Export().
int BotLoadItemWeights (int goalstate, char * filename)
References BLERR_CANNOTLOADITEMWEIGHTS, BLERR_NOERROR, BotGoalStateFromHandle(), botimport, bot_goalstate_s::itemweightconfig, bot_goalstate_s::itemweightindex, ItemWeightIndex(), PRT_FATAL, and ReadWeightConfig().
Referenced by Init_AI_Export().
void BotMutateGoalFuzzyLogic (int goalstate, float range)
References BotGoalStateFromHandle(), EvolveWeightConfig(), and bot_goalstate_s::itemweightconfig.
Referenced by Init_AI_Export().
void BotPopGoal (int goalstate)
References BotGoalStateFromHandle(), and bot_goalstate_s::goalstacktop.
Referenced by Init_AI_Export().
void BotPushGoal (int goalstate, bot_goal_t * goal)
References BotDumpGoalStack(), BotGoalStateFromHandle(), botimport, Com_Memcpy, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, MAX_GOALSTACK, and PRT_ERROR.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and Init_AI_Export().
void BotRemoveFromAvoidGoals (int goalstate, int number)
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalStateFromHandle(), and MAX_AVOIDGOALS.
Referenced by Init_AI_Export().
void BotResetAvoidGoals (int goalstate)
References bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalStateFromHandle(), Com_Memset, and MAX_AVOIDGOALS.
Referenced by BotResetGoalState(), and Init_AI_Export().
void BotResetGoalState (int goalstate)
References BotGoalStateFromHandle(), BotResetAvoidGoals(), Com_Memset, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, and MAX_GOALSTACK.
Referenced by Init_AI_Export().
void BotSaveGoalFuzzyLogic (int goalstate, char * filename)
Referenced by Init_AI_Export().
void BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
References AVOID_DEFAULT_TIME, AVOID_MINIMUM_TIME, BotAddToAvoidGoals(), BotGoalStateFromHandle(), levelitem_s::iteminfo, itemconfig_s::iteminfo, levelitem_s::next, levelitem_s::number, and iteminfo_s::respawntime.
Referenced by Init_AI_Export().
int BotSetupGoalAI (void)
References BLERR_CANNOTLOADITEMCONFIG, BLERR_NOERROR, botimport, LibVar(), LibVarString(), LibVarValue(), LoadItemConfig(), and PRT_FATAL.
Referenced by Export_BotLibSetup().
void BotShutdownGoalAI (void)
References BotFreeGoalState(), BotFreeInfoEntities(), FreeMemory(), MAX_CLIENTS, and NULL.
Referenced by Export_BotLibShutdown().
int BotTouchingGoal (vec3_t origin, bot_goal_t * goal)
References AAS_PresenceTypeBoundingBox(), bot_goal_s::maxs, bot_goal_s::mins, bot_goal_s::origin, PRESENCE_NORMAL, qfalse, qtrue, VectorAdd, and VectorSubtract.
Referenced by Init_AI_Export().
void BotUpdateEntityItems (void)
References AAS_AreaJumpPad(), AAS_BestReachableArea(), AAS_EntityInfo(), AAS_EntityModelindex(), AAS_EntityType(), AAS_NextEntity(), AAS_Time(), AddLevelItemToList(), AllocLevelItem(), iteminfo_s::classname, levelitem_s::entitynum, ET_ITEM, levelitem_s::flags, FreeLevelItem(), levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, aas_entityinfo_s::lastvisorigin, Log_Write(), iteminfo_s::maxs, iteminfo_s::mins, iteminfo_s::modelindex, levelitem_s::next, NULL, levelitem_s::number, itemconfig_s::numiteminfo, levelitem_s::origin, aas_entityinfo_s::origin, RemoveLevelItemFromList(), levelitem_s::timeout, VectorCopy, VectorLength(), and VectorSubtract.
Referenced by Init_AI_Export().