ioquake3: code/botlib/be_aas_main.c File Reference
be_aas_main.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_libvar.h"
#include "l_utils.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_log.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_aas_def.h"
Functions
void QDECL AAS_Error (char *fmt,...)
char * AAS_StringFromIndex (char *indexname, char *stringindex[], int numindexes, int index)
int AAS_IndexFromString (char *indexname, char *stringindex[], int numindexes, char *string)
char * AAS_ModelFromIndex (int index)
int AAS_IndexFromModel (char *modelname)
void AAS_UpdateStringIndexes (int numconfigstrings, char *configstrings[])
int AAS_Loaded (void)
int AAS_Initialized (void)
void AAS_SetInitialized (void)
void AAS_ContinueInit (float time)
int AAS_StartFrame (float time)
float AAS_Time (void)
void AAS_ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
int AAS_LoadFiles (const char *mapname)
int AAS_LoadMap (const char *mapname)
int AAS_Setup (void)
void AAS_Shutdown (void)
Variables
aas_t aasworld
libvar_t * saveroutingcache
Function Documentation
void AAS_ContinueInit (float time)
References AAS_ContinueInitReachability(), AAS_InitClustering(), AAS_InitRouting(), AAS_Optimize(), AAS_SetInitialized(), AAS_WriteAASFile(), botimport, aas_s::filename, aas_s::initialized, LibVarGetValue(), LibVarValue(), aas_s::loaded, PRT_ERROR, PRT_MESSAGE, and aas_s::savefile.
Referenced by AAS_StartFrame().
void QDECL AAS_Error (char * fmt, ...)
References botimport, PRT_FATAL, and Q_vsnprintf.
Referenced by AAS_AllocReachability(), AAS_AreaReachability(), AAS_CreatePortals(), AAS_FindClusters(), AAS_FloodClusterAreas_r(), AAS_GetAdjacentAreasWithLessPresenceTypes_r(), AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_ReadRouteCache(), AAS_UpdatePortal(), and AAS_WriteRouteCache().
int AAS_IndexFromModel (char * modelname)
References AAS_IndexFromString(), aas_s::configstrings, CS_MODELS, and MAX_MODELS.
int AAS_IndexFromString (char * indexname, char * stringindex[], int numindexes, char * string)
References botimport, aas_s::indexessetup, PRT_ERROR, and Q_stricmp().
Referenced by AAS_IndexFromModel().
int AAS_Initialized (void)
References aas_s::initialized.
Referenced by Init_AAS_Export().
int AAS_Loaded (void)
References aas_s::loaded.
Referenced by BotInitLevelItems().
int AAS_LoadFiles (const char * mapname)
References AAS_LoadAASFile(), AAS_LoadBSPFile(), AAS_ResetEntityLinks(), BLERR_NOERROR, botimport, Com_sprintf(), aas_s::filename, aas_s::mapname, MAX_PATH, and PRT_MESSAGE.
Referenced by AAS_LoadMap().
int AAS_LoadMap (const char * mapname)
References AAS_FreeRoutingCaches(), AAS_InitAASLinkedEntities(), AAS_InitAASLinkHeap(), AAS_InitAlternativeRouting(), AAS_InitReachability(), AAS_InitSettings(), AAS_LoadFiles(), BLERR_NOERROR, aas_s::initialized, aas_s::loaded, and qfalse.
Referenced by Export_BotLibLoadMap().
char* AAS_ModelFromIndex (int index)
References AAS_StringFromIndex(), aas_s::configstrings, CS_MODELS, and MAX_MODELS.
void AAS_ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
References DotProduct, VectorMA(), VectorNormalize(), and VectorSubtract.
Referenced by AAS_NearestHideArea(), DistanceFromLineSquared(), and DistancePointToLine().
void AAS_SetInitialized (void)
References botimport, aas_s::initialized, PRT_MESSAGE, and qtrue.
Referenced by AAS_ContinueInit().
int AAS_Setup (void)
References AAS_InvalidateEntities(), BLERR_NOERROR, aas_s::entities, FreeMemory(), GetClearedHunkMemory(), int(), LibVar(), LibVarValue(), aas_s::maxclients, aas_s::maxentities, and aas_s::numframes.
Referenced by Export_BotLibSetup().
void AAS_Shutdown (void)
References AAS_DumpAASData(), AAS_DumpBSPData(), AAS_FreeAASLinkedEntities(), AAS_FreeAASLinkHeap(), AAS_FreeRoutingCaches(), AAS_ShutdownAlternativeRouting(), botimport, Com_Memset, aas_s::entities, FreeMemory(), aas_s::initialized, PRT_MESSAGE, and qfalse.
Referenced by Export_BotLibShutdown().
int AAS_StartFrame (float time)
References AAS_ContinueInit(), AAS_InvalidateEntities(), AAS_RoutingInfo(), AAS_UnlinkInvalidEntities(), AAS_WriteRouteCache(), BLERR_NOERROR, botDeveloper, aas_s::frameroutingupdates, LibVarGetValue(), LibVarSet(), aas_s::numframes, PrintMemoryLabels(), PrintUsedMemorySize(), aas_s::time, and libvar_s::value.
Referenced by Export_BotLibStartFrame().
char* AAS_StringFromIndex (char * indexname, char * stringindex[], int numindexes, int index)
References botimport, aas_s::indexessetup, and PRT_ERROR.
Referenced by AAS_ModelFromIndex().
float AAS_Time (void)
References aas_s::time.
Referenced by AAS_RoutingTime(), AAS_ShowReachableAreas(), AAS_UpdateEntity(), BotAddToAvoidGoals(), BotAddToAvoidReach(), BotAvoidGoalTime(), BotChooseInitialChatMessage(), BotDumpAvoidGoals(), BotGetReachabilityToGoal(), BotItemGoalInVisButNotVisible(), BotMoveToGoal(), BotQueueConsoleMessage(), BotRemoveFromAvoidGoals(), BotReplyChat(), BotTravel_Grapple(), BotUpdateEntityItems(), and Init_AAS_Export().
void AAS_UpdateStringIndexes (int numconfigstrings, char * configstrings[])
References aas_s::configstrings, GetMemory(), aas_s::indexessetup, and qtrue.
Variable Documentation
aas_t aasworld
Referenced by AAS_AASLinkEntity(), AAS_AgainstLadder(), AAS_AllocAASLink(), AAS_AlternativeRouteGoals(), AAS_AltRoutingFloodCluster_r(), AAS_AreaCluster(), AAS_AreaClusterPortal(), AAS_AreaContentsTravelFlags(), AAS_AreaContentsTravelFlags_inline(), AAS_AreaCrouch(), AAS_AreaDoNotEnter(), AAS_AreaEntityCollision(), AAS_AreaGrounded(), AAS_AreaGroundFace(), AAS_AreaGroundFaceArea(), AAS_AreaInfo(), AAS_AreaJumpPad(), AAS_AreaLadder(), AAS_AreaLava(), AAS_AreaLiquid(), AAS_AreaPresenceType(), AAS_AreaReachability(), AAS_AreaRouteToGoalArea(), AAS_AreaSlime(), AAS_AreaSwim(), AAS_AreaTeleporter(), AAS_AreaVolume(), AAS_BestReachableArea(), AAS_BestReachableEntityArea(), AAS_CalculateAreaTravelTimes(), AAS_CheckAreaForPossiblePortals(), AAS_ClearCluster(), AAS_ClientMovementPrediction(), AAS_ClusterAreaNum(), AAS_ConnectedAreas_r(), AAS_ContinueInitReachability(), AAS_CountForcedClusterPortals(), AAS_CreateAllRoutingCache(), AAS_CreatePortals(), AAS_CreateReversedReachability(), AAS_CreateViewPortals(), AAS_DeAllocAASLink(), AAS_DumpAASData(), AAS_EnableRoutingArea(), AAS_EntityBSPData(), AAS_EntityInfo(), AAS_EntityModelindex(), AAS_EntityModelNum(), AAS_EntityOrigin(), AAS_EntitySize(), AAS_EntityType(), AAS_FaceArea(), AAS_FaceCenter(), AAS_FacePlane(), AAS_FindClusters(), AAS_FindFaceReachabilities(), AAS_FindPossiblePortals(), AAS_FloodAreas(), AAS_FloodAreas_r(), AAS_FloodClusterAreas_r(), AAS_FloodClusterAreasUsingReachabilities(), AAS_FreeAASLinkedEntities(), AAS_FreeAASLinkHeap(), AAS_FreeAllClusterAreaCache(), AAS_FreeAllPortalCache(), AAS_FreeOldestCache(), AAS_FreeRoutingCaches(), AAS_GetAdjacentAreasWithLessPresenceTypes_r(), AAS_GetAreaContentsTravelFlags(), AAS_GetAreaRoutingCache(), AAS_GetPortalRoutingCache(), AAS_InitAASLinkedEntities(), AAS_InitAASLinkHeap(), AAS_InitAlternativeRouting(), AAS_InitAreaContentsTravelFlags(), AAS_InitClusterAreaCache(), AAS_InitClustering(), AAS_InitPortalCache(), AAS_InitPortalMaxTravelTimes(), AAS_InitReachability(), AAS_InitReachabilityAreas(), AAS_InitRoutingUpdate(), AAS_InitTravelFlagFromType(), AAS_InsideFace(), AAS_InvalidateEntities(), AAS_LinkCache(), AAS_LoadAASFile(), AAS_NearestEntity(), AAS_NearestHideArea(), AAS_NextAreaReachability(), AAS_NextEntity(), AAS_NextModelReachability(), AAS_NumberClusterAreas(), AAS_NumberClusterPortals(), AAS_Optimize(), AAS_OptimizeAlloc(), AAS_OptimizeArea(), AAS_OptimizeEdge(), AAS_OptimizeFace(), AAS_OptimizeStore(), AAS_OriginOfMoverWithModelNum(), AAS_PlaneFromNum(), AAS_PointAreaNum(), AAS_PointInsideFace(), AAS_PointPresenceType(), AAS_PointReachabilityAreaIndex(), AAS_PortalMaxTravelTime(), AAS_PredictRoute(), AAS_RandomGoalArea(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Swim(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), AAS_ReachabilityFromNum(), AAS_ReadRouteCache(), AAS_RemoveAllPortals(), AAS_RemoveClusterAreas(), AAS_RemovePortalsClusterReference(), AAS_RemoveRoutingCacheInCluster(), AAS_RemoveRoutingCacheUsingArea(), AAS_ResetEntityLinks(), AAS_SetViewPortalsAsClusterPortals(), AAS_SetWeaponJumpAreaFlags(), AAS_ShowArea(), AAS_ShowAreaPolygons(), AAS_ShowFace(), AAS_ShowFacePolygon(), AAS_ShowReachableAreas(), AAS_StoreReachability(), AAS_SwapAASData(), AAS_TestPortals(), AAS_TraceAreas(), AAS_TraceClientBBox(), AAS_TraceEndFace(), AAS_TravelFlagForType_inline(), AAS_UnlinkCache(), AAS_UnlinkFromAreas(), AAS_UnlinkInvalidEntities(), AAS_UpdateAreaRoutingCache(), AAS_UpdateEntity(), AAS_UpdatePortal(), AAS_UpdatePortalRoutingCache(), AAS_WriteAASFile(), AAS_WriteRouteCache(), and BotExportTest().
libvar_t* saveroutingcache