ioquake3: code/botlib/be_aas_move.c File Reference
be_aas_move.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_libvar.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_aas_def.h"
Functions
int AAS_DropToFloor (vec3_t origin, vec3_t mins, vec3_t maxs)
void AAS_InitSettings (void)
int AAS_AgainstLadder (vec3_t origin)
int AAS_OnGround (vec3_t origin, int presencetype, int passent)
int AAS_Swimming (vec3_t origin)
void AAS_SetMovedir (vec3_t angles, vec3_t movedir)
void AAS_JumpReachRunStart (aas_reachability_t *reach, vec3_t runstart)
float AAS_WeaponJumpZVelocity (vec3_t origin, float radiusdamage)
float AAS_RocketJumpZVelocity (vec3_t origin)
float AAS_BFGJumpZVelocity (vec3_t origin)
void AAS_Accelerate (vec3_t velocity, float frametime, vec3_t wishdir, float wishspeed, float accel)
void AAS_ApplyFriction (vec3_t vel, float friction, float stopspeed, float frametime)
int AAS_ClipToBBox (aas_trace_t *trace, vec3_t start, vec3_t end, int presencetype, vec3_t mins, vec3_t maxs)
int AAS_ClientMovementPrediction (struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, vec3_t mins, vec3_t maxs, int visualize)
int AAS_PredictClientMovement (struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
int AAS_ClientMovementHitBBox (struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, vec3_t mins, vec3_t maxs, int visualize)
void AAS_TestMovementPrediction (int entnum, vec3_t origin, vec3_t dir)
int AAS_HorizontalVelocityForJump (float zvel, vec3_t start, vec3_t end, float *velocity)
Variables
botlib_import_t botimport
aas_settings_t aassettings
static vec3_t VEC_UP = {0, -1, 0}
static vec3_t MOVEDIR_UP = {0, 0, 1}
static vec3_t VEC_DOWN = {0, -2, 0}
static vec3_t MOVEDIR_DOWN = {0, 0, -1}
Function Documentation
void AAS_Accelerate (vec3_t velocity, float frametime, vec3_t wishdir, float wishspeed, float accel)
References DotProduct.
Referenced by AAS_ClientMovementPrediction().
int AAS_AgainstLadder (vec3_t origin)
References AAS_PointAreaNum(), AAS_PointInsideFace(), aasworld, abs(), AREA_LADDER, aas_areasettings_s::areaflags, aas_s::areas, aas_s::areasettings, aas_plane_s::dist, DotProduct, FACE_LADDER, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_plane_s::normal, aas_area_s::numfaces, aas_face_s::planenum, aas_s::planes, PRESENCE_NORMAL, aas_areasettings_s::presencetype, qfalse, qtrue, and VectorCopy.
Referenced by BotMoveToGoal().
void AAS_ApplyFriction (vec3_t vel, float friction, float stopspeed, float frametime)
References control().
Referenced by AAS_ClientMovementPrediction().
float AAS_BFGJumpZVelocity (vec3_t origin)
References AAS_WeaponJumpZVelocity().
Referenced by AAS_Reachability_WeaponJump().
int AAS_ClientMovementHitBBox (struct aas_clientmove_s * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, vec3_t mins, vec3_t maxs, int visualize)
References AAS_ClientMovementPrediction(), and SE_HITBOUNDINGBOX.
Referenced by AAS_BestReachableFromJumpPadArea().
int AAS_ClientMovementPrediction (struct aas_clientmove_s * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, vec3_t mins, vec3_t maxs, int visualize)
References AAS_Accelerate(), AAS_ApplyFriction(), AAS_ClipToBBox(), AAS_DebugLine(), AAS_OnGround(), AAS_PlaneFromNum(), AAS_PointAreaNum(), AAS_PointContents(), AAS_PointPresenceType(), AAS_Swimming(), AAS_TraceAreas(), AAS_TraceClientBBox(), aasworld, AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_JUMPPAD, AREACONTENTS_LAVA, AREACONTENTS_SLIME, AREACONTENTS_TELEPORTER, AREACONTENTS_WATER, aas_s::areasettings, Com_Memset, aas_areasettings_s::contents, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, DotProduct, end, aas_clientmove_s::endarea, aas_clientmove_s::endcontents, aas_trace_s::endpos, aas_clientmove_s::endpos, aas_trace_s::fraction, aas_clientmove_s::frames, LINECOLOR_BLUE, LINECOLOR_RED, n, aas_plane_s::normal, pc, aas_settings_s::phys_airaccelerate, aas_settings_s::phys_friction, aas_settings_s::phys_gravity, aas_settings_s::phys_jumpvel, aas_settings_s::phys_maxbarrier, aas_settings_s::phys_maxcrouchvelocity, aas_settings_s::phys_maxsteepness, aas_settings_s::phys_maxstep, aas_settings_s::phys_maxswimvelocity, aas_settings_s::phys_maxwalkvelocity, aas_settings_s::phys_stopspeed, aas_settings_s::phys_swimaccelerate, aas_settings_s::phys_walkaccelerate, aas_settings_s::phys_waterfriction, aas_settings_s::phys_watergravity, aas_trace_s::planenum, PRESENCE_CROUCH, PRESENCE_NORMAL, aas_clientmove_s::presencetype, PRT_MESSAGE, qfalse, qtrue, SE_ENTERAREA, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_GAP, SE_HITBOUNDINGBOX, SE_HITGROUND, SE_HITGROUNDAREA, SE_HITGROUNDDAMAGE, SE_LEAVEGROUND, SE_NONE, SE_TOUCHCLUSTERPORTAL, SE_TOUCHJUMPPAD, SE_TOUCHTELEPORTER, start, aas_trace_s::startsolid, aas_clientmove_s::stopevent, aas_clientmove_s::time, aas_clientmove_s::trace, up, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and aas_clientmove_s::velocity.
Referenced by AAS_ClientMovementHitBBox(), and AAS_PredictClientMovement().
int AAS_ClipToBBox (aas_trace_t * trace, vec3_t start, vec3_t end, int presencetype, vec3_t mins, vec3_t maxs)
References AAS_PresenceTypeBoundingBox(), aas_trace_s::area, aas_trace_s::endpos, aas_trace_s::ent, aas_trace_s::fraction, aas_trace_s::lastarea, aas_trace_s::planenum, qfalse, qtrue, aas_trace_s::startsolid, VectorCopy, and VectorSubtract.
Referenced by AAS_ClientMovementPrediction().
int AAS_DropToFloor (vec3_t origin, vec3_t mins, vec3_t maxs)
References AAS_Trace(), CONTENTS_SOLID, end, qfalse, qtrue, and VectorCopy.
Referenced by AAS_SetWeaponJumpAreaFlags(), and BotInitLevelItems().
int AAS_HorizontalVelocityForJump (float zvel, vec3_t start, vec3_t end, float * velocity)
References aas_settings_s::phys_gravity, aas_settings_s::phys_maxvelocity, t, and VectorSubtract.
Referenced by AAS_FindFaceReachabilities(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_WeaponJump(), AAS_ShowReachability(), and BotTravel_WalkOffLedge().
void AAS_InitSettings (void)
References LibVarValue(), aas_settings_s::phys_airaccelerate, aas_settings_s::phys_falldelta10, aas_settings_s::phys_falldelta5, aas_settings_s::phys_friction, aas_settings_s::phys_gravity, aas_settings_s::phys_gravitydirection, aas_settings_s::phys_jumpvel, aas_settings_s::phys_maxbarrier, aas_settings_s::phys_maxcrouchvelocity, aas_settings_s::phys_maxsteepness, aas_settings_s::phys_maxstep, aas_settings_s::phys_maxswimvelocity, aas_settings_s::phys_maxvelocity, aas_settings_s::phys_maxwalkvelocity, aas_settings_s::phys_maxwaterjump, aas_settings_s::phys_stopspeed, aas_settings_s::phys_swimaccelerate, aas_settings_s::phys_walkaccelerate, aas_settings_s::phys_waterfriction, aas_settings_s::phys_watergravity, aas_settings_s::rs_aircontrolledjumppad, aas_settings_s::rs_barrierjump, aas_settings_s::rs_bfgjump, aas_settings_s::rs_falldamage10, aas_settings_s::rs_falldamage5, aas_settings_s::rs_funcbob, aas_settings_s::rs_jumppad, aas_settings_s::rs_maxfallheight, aas_settings_s::rs_maxjumpfallheight, aas_settings_s::rs_rocketjump, aas_settings_s::rs_startcrouch, aas_settings_s::rs_startelevator, aas_settings_s::rs_startgrapple, aas_settings_s::rs_startjump, aas_settings_s::rs_startwalkoffledge, aas_settings_s::rs_teleport, and aas_settings_s::rs_waterjump.
Referenced by AAS_LoadMap().
void AAS_JumpReachRunStart (aas_reachability_t * reach, vec3_t runstart)
References AAS_PredictClientMovement(), aas_reachability_s::end, aas_clientmove_s::endpos, move(), PRESENCE_NORMAL, qfalse, qtrue, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_GAP, SE_HITGROUNDDAMAGE, start, aas_reachability_s::start, aas_clientmove_s::stopevent, vec3_origin, VectorCopy, VectorNormalize(), and VectorScale.
Referenced by AAS_ShowReachability(), and BotTravel_Jump().
int AAS_OnGround (vec3_t origin, int presencetype, int passent)
References AAS_PlaneFromNum(), AAS_TraceClientBBox(), DotProduct, end, aas_trace_s::endpos, aas_trace_s::fraction, aas_plane_s::normal, aas_settings_s::phys_maxsteepness, aas_trace_s::planenum, qfalse, qtrue, aas_trace_s::startsolid, up, and VectorCopy.
Referenced by AAS_ClientMovementPrediction(), BotMoveToGoal(), and BotWalkInDirection().
int AAS_PredictClientMovement (struct aas_clientmove_s * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
References AAS_ClientMovementPrediction().
Referenced by AAS_JumpReachRunStart(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Teleport(), AAS_Reachability_WeaponJump(), AAS_ShowReachability(), AAS_TestMovementPrediction(), BotWalkInDirection(), and Init_AAS_Export().
float AAS_RocketJumpZVelocity (vec3_t origin)
References AAS_WeaponJumpZVelocity().
Referenced by AAS_Reachability_WeaponJump(), and AAS_ShowReachability().
void AAS_SetMovedir (vec3_t angles, vec3_t movedir)
References AngleVectors(), MOVEDIR_DOWN, MOVEDIR_UP, NULL, VEC_DOWN, VEC_UP, VectorCompare(), and VectorCopy.
int AAS_Swimming (vec3_t origin)
References AAS_PointContents(), CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, qfalse, qtrue, and VectorCopy.
Referenced by AAS_ClientMovementPrediction(), AAS_TestMovementPrediction(), BotMoveInDirection(), BotMoveToGoal(), BotReachabilityArea(), and Init_AAS_Export().
void AAS_TestMovementPrediction (int entnum, vec3_t origin, vec3_t dir)
References AAS_ClearShownDebugLines(), AAS_PredictClientMovement(), AAS_Swimming(), move(), PRESENCE_NORMAL, PRT_MESSAGE, qtrue, SE_HITGROUND, SE_LEAVEGROUND, aas_clientmove_s::stopevent, VectorClear, VectorNormalize(), and VectorScale.
float AAS_WeaponJumpZVelocity (vec3_t origin, float radiusdamage)
References AAS_Trace(), AngleVectors(), CONTENTS_SOLID, end, forward, NULL, aas_settings_s::phys_jumpvel, PITCH, right, ROLL, start, VectorAdd, VectorCopy, VectorLength(), VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and YAW.
Referenced by AAS_BFGJumpZVelocity(), and AAS_RocketJumpZVelocity().
Variable Documentation
aas_settings_t aassettings
Referenced by AAS_BarrierJumpTravelTime(), AAS_FallDamageDistance(), AAS_FallDelta(), AAS_FindFaceReachabilities(), AAS_GetJumpPadInfo(), AAS_MaxJumpDistance(), AAS_MaxJumpHeight(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), and AAS_ShowReachability().
botlib_import_t botimport
vec3_t MOVEDIR_DOWN = {0, 0, -1} [static]
Referenced by AAS_SetMovedir(), and G_SetMovedir().
vec3_t MOVEDIR_UP = {0, 0, 1} [static]
Referenced by AAS_SetMovedir(), and G_SetMovedir().
vec3_t VEC_DOWN = {0, -2, 0} [static]
Referenced by AAS_SetMovedir(), and G_SetMovedir().
vec3_t VEC_UP = {0, -1, 0} [static]
Referenced by AAS_SetMovedir(), and G_SetMovedir().