ioquake3: code/botlib/be_aas_reach.c File Reference
be_aas_reach.c File Reference
#include "../qcommon/q_shared.h"
#include "l_log.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_libvar.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_aas_def.h"
Data Structures
struct aas_lreachability_s
Defines
#define AAS_MAX_REACHABILITYSIZE 65536
#define REACHABILITYAREASPERCYCLE 15
#define INSIDEUNITS 2
#define INSIDEUNITS_WALKEND 5
#define INSIDEUNITS_WALKSTART 0.1
#define INSIDEUNITS_WATERJUMP 15
#define AREA_WEAPONJUMP 8192
Typedefs
typedef struct aas_lreachability_s aas_lreachability_t
Functions
int Sys_MilliSeconds (void)
float AAS_FaceArea (aas_face_t *face)
float AAS_AreaVolume (int areanum)
int AAS_BestReachableLinkArea (aas_link_t *areas)
int AAS_GetJumpPadInfo (int ent, vec3_t areastart, vec3_t absmins, vec3_t absmaxs, vec3_t velocity)
int AAS_BestReachableFromJumpPadArea (vec3_t origin, vec3_t mins, vec3_t maxs)
int AAS_BestReachableArea (vec3_t origin, vec3_t mins, vec3_t maxs, vec3_t goalorigin)
void AAS_SetupReachabilityHeap (void)
void AAS_ShutDownReachabilityHeap (void)
aas_lreachability_t * AAS_AllocReachability (void)
void AAS_FreeReachability (aas_lreachability_t *lreach)
int AAS_AreaReachability (int areanum)
float AAS_AreaGroundFaceArea (int areanum)
void AAS_FaceCenter (int facenum, vec3_t center)
int AAS_FallDamageDistance (void)
float AAS_FallDelta (float distance)
float AAS_MaxJumpHeight (float phys_jumpvel)
float AAS_MaxJumpDistance (float phys_jumpvel)
int AAS_AreaCrouch (int areanum)
int AAS_AreaSwim (int areanum)
int AAS_AreaLiquid (int areanum)
int AAS_AreaLava (int areanum)
int AAS_AreaSlime (int areanum)
int AAS_AreaGrounded (int areanum)
int AAS_AreaLadder (int areanum)
int AAS_AreaJumpPad (int areanum)
int AAS_AreaTeleporter (int areanum)
int AAS_AreaClusterPortal (int areanum)
int AAS_AreaDoNotEnter (int areanum)
unsigned short int AAS_BarrierJumpTravelTime (void)
qboolean AAS_ReachabilityExists (int area1num, int area2num)
int AAS_NearbySolidOrGap (vec3_t start, vec3_t end)
int AAS_Reachability_Swim (int area1num, int area2num)
int AAS_Reachability_EqualFloorHeight (int area1num, int area2num)
int AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge (int area1num, int area2num)
float VectorDistance (vec3_t v1, vec3_t v2)
int VectorBetweenVectors (vec3_t v, vec3_t v1, vec3_t v2)
void VectorMiddle (vec3_t v1, vec3_t v2, vec3_t middle)
float AAS_ClosestEdgePoints (vec3_t v1, vec3_t v2, vec3_t v3, vec3_t v4, aas_plane_t *plane1, aas_plane_t *plane2, vec3_t beststart1, vec3_t bestend1, vec3_t beststart2, vec3_t bestend2, float bestdist)
int AAS_Reachability_Jump (int area1num, int area2num)
int AAS_Reachability_Ladder (int area1num, int area2num)
int AAS_TravelFlagsForTeam (int ent)
void AAS_Reachability_Teleport (void)
void AAS_Reachability_Elevator (void)
aas_lreachability_t * AAS_FindFaceReachabilities (vec3_t *facepoints, int numpoints, aas_plane_t *plane, int towardsface)
void AAS_Reachability_FuncBobbing (void)
void AAS_Reachability_JumpPad (void)
int AAS_Reachability_Grapple (int area1num, int area2num)
void AAS_SetWeaponJumpAreaFlags (void)
int AAS_Reachability_WeaponJump (int area1num, int area2num)
void AAS_Reachability_WalkOffLedge (int areanum)
void AAS_StoreReachability (void)
int AAS_ContinueInitReachability (float time)
void AAS_InitReachability (void)
Variables
botlib_import_t botimport
int reach_swim
int reach_equalfloor
int reach_step
int reach_walk
int reach_barrier
int reach_waterjump
int reach_walkoffledge
int reach_jump
int reach_ladder
int reach_teleport
int reach_elevator
int reach_funcbob
int reach_grapple
int reach_doublejump
int reach_rampjump
int reach_strafejump
int reach_rocketjump
int reach_bfgjump
int reach_jumppad
int calcgrapplereach
aas_lreachability_t * reachabilityheap
aas_lreachability_t * nextreachability
aas_lreachability_t ** areareachability
int numlreachabilities
Define Documentation
#define AAS_MAX_REACHABILITYSIZE 65536
Referenced by AAS_SetupReachabilityHeap().
#define AREA_WEAPONJUMP 8192
Referenced by AAS_Reachability_WeaponJump(), and AAS_SetWeaponJumpAreaFlags().
#define INSIDEUNITS 2
Referenced by AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), and AAS_Reachability_Swim().
#define INSIDEUNITS_WALKEND 5
Referenced by AAS_Reachability_EqualFloorHeight(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
#define INSIDEUNITS_WALKSTART 0.1
Referenced by AAS_Reachability_EqualFloorHeight(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
#define INSIDEUNITS_WATERJUMP 15
Referenced by AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
#define REACHABILITYAREASPERCYCLE 15
Typedef Documentation
typedef struct aas_lreachability_s aas_lreachability_t
Function Documentation
aas_lreachability_t* AAS_AllocReachability (void)
References AAS_Error(), aas_lreachability_s::next, nextreachability, NULL, and numlreachabilities.
Referenced by AAS_FindFaceReachabilities(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Swim(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), and AAS_Reachability_WeaponJump().
int AAS_AreaClusterPortal (int areanum)
References aasworld, AREACONTENTS_CLUSTERPORTAL, aas_s::areasettings, and aas_areasettings_s::contents.
Referenced by AAS_Reachability_Jump(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), and AAS_Reachability_WalkOffLedge().
int AAS_AreaCrouch (int areanum)
References aasworld, aas_s::areasettings, PRESENCE_NORMAL, aas_areasettings_s::presencetype, qfalse, and qtrue.
Referenced by AAS_AreaTravelTime(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Jump(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
int AAS_AreaDoNotEnter (int areanum)
References aasworld, AREACONTENTS_DONOTENTER, aas_s::areasettings, and aas_areasettings_s::contents.
Referenced by AAS_AreaRouteToGoalArea(), and BotGetReachabilityToGoal().
int AAS_AreaGrounded (int areanum)
References aasworld, AREA_GROUNDED, aas_areasettings_s::areaflags, and aas_s::areasettings.
Referenced by AAS_BestReachableLinkArea(), AAS_NearbySolidOrGap(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_WalkOffLedge(), and AAS_Reachability_WeaponJump().
float AAS_AreaGroundFaceArea (int areanum)
References AAS_FaceArea(), aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, and aas_area_s::numfaces.
Referenced by AAS_RandomGoalArea().
int AAS_AreaJumpPad (int areanum)
References aasworld, AREACONTENTS_JUMPPAD, aas_s::areasettings, and aas_areasettings_s::contents.
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), BotMoveToGoal(), and BotUpdateEntityItems().
int AAS_AreaLadder (int areanum)
References aasworld, AREA_LADDER, aas_areasettings_s::areaflags, and aas_s::areasettings.
Referenced by AAS_Reachability_Ladder().
int AAS_AreaLava (int areanum)
References aasworld, AREACONTENTS_LAVA, aas_s::areasettings, and aas_areasettings_s::contents.
int AAS_AreaLiquid (int areanum)
References aasworld, AREA_LIQUID, aas_areasettings_s::areaflags, aas_s::areasettings, qfalse, and qtrue.
int AAS_AreaReachability (int areanum)
References AAS_Error(), aasworld, aas_lreachability_s::areanum, aas_s::areasettings, aas_s::numareas, and aas_areasettings_s::numreachableareas.
Referenced by AAS_AlternativeRouteGoals(), AAS_BestReachableLinkArea(), AAS_CreateAllRoutingCache(), AAS_NumberClusterAreas(), AAS_PointReachabilityAreaIndex(), AAS_RandomGoalArea(), BotCheckBlocked(), BotChooseLTGItem(), BotChooseNBGItem(), BotFuzzyPointReachabilityArea(), BotMoveToGoal(), BotReachabilityArea(), and Init_AAS_Export().
int AAS_AreaSlime (int areanum)
References aasworld, AREACONTENTS_SLIME, aas_s::areasettings, and aas_areasettings_s::contents.
int AAS_AreaSwim (int areanum)
References aasworld, AREA_LIQUID, aas_areasettings_s::areaflags, aas_s::areasettings, qfalse, and qtrue.
Referenced by AAS_AreaTravelTime(), AAS_BestReachableLinkArea(), AAS_NearbySolidOrGap(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_Grapple(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Swim(), AAS_Reachability_WalkOffLedge(), and AAS_Reachability_WeaponJump().
int AAS_AreaTeleporter (int areanum)
References aasworld, AREACONTENTS_TELEPORTER, aas_s::areasettings, and aas_areasettings_s::contents.
Referenced by AAS_Reachability_Teleport().
float AAS_AreaVolume (int areanum)
References AAS_FaceArea(), aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, aas_face_s::backarea, aas_plane_s::dist, DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, aas_plane_s::normal, aas_area_s::numfaces, aas_face_s::planenum, aas_s::planes, aas_edge_s::v, VectorCopy, and aas_s::vertexes.
Referenced by AAS_BestReachableFromJumpPadArea(), and AAS_Reachability_Swim().
unsigned short int AAS_BarrierJumpTravelTime (void)
References aassettings, aas_settings_s::phys_gravity, and aas_settings_s::phys_jumpvel.
int AAS_BestReachableArea (vec3_t origin, vec3_t mins, vec3_t maxs, vec3_t goalorigin)
References AAS_BestReachableLinkArea(), AAS_DrawPermanentCross(), AAS_LinkEntityClientBBox(), AAS_PointAreaNum(), AAS_TraceClientBBox(), AAS_UnlinkFromAreas(), aasworld, aas_lreachability_s::areanum, end, aas_trace_s::endpos, LINECOLOR_RED, aas_s::loaded, Log_Write(), PRESENCE_CROUCH, PRT_ERROR, PRT_MESSAGE, start, aas_trace_s::startsolid, VectorAdd, and VectorCopy.
Referenced by AAS_SetWeaponJumpAreaFlags(), BotInitLevelItems(), and BotUpdateEntityItems().
int AAS_BestReachableFromJumpPadArea (vec3_t origin, vec3_t mins, vec3_t maxs)
References AAS_AreaJumpPad(), AAS_AreaVolume(), AAS_ClientMovementHitBBox(), AAS_GetJumpPadInfo(), AAS_LinkEntityClientBBox(), AAS_NextBSPEntity(), AAS_UnlinkFromAreas(), AAS_ValueForBSPEpairKey(), aas_link_s::areanum, Com_Memset, aas_clientmove_s::frames, LibVarValue(), MAX_EPAIRKEY, move(), aas_link_s::next_area, PRESENCE_CROUCH, PRESENCE_NORMAL, PRT_MESSAGE, qfalse, VectorAdd, and VectorSet.
Referenced by BotInitLevelItems().
int AAS_BestReachableLinkArea (aas_link_t * areas)
References AAS_AreaGrounded(), AAS_AreaReachability(), AAS_AreaSwim(), aas_link_s::areanum, and aas_link_s::next_area.
Referenced by AAS_BestReachableArea(), and AAS_BestReachableEntityArea().
float AAS_ClosestEdgePoints (vec3_t v1, vec3_t v2, vec3_t v3, vec3_t v4, aas_plane_t * plane1, aas_plane_t * plane2, vec3_t beststart1, vec3_t bestend1, vec3_t beststart2, vec3_t bestend2, float bestdist)
References b1, b2, aas_plane_s::dist, DotProduct, if(), aas_plane_s::normal, qfalse, qtrue, VectorBetweenVectors(), VectorCopy, VectorDistance(), and VectorSubtract.
Referenced by AAS_FindFaceReachabilities(), and AAS_Reachability_Jump().
int AAS_ContinueInitReachability (float time)
References AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Swim(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), AAS_ReachabilityExists(), AAS_ShutDownReachabilityHeap(), AAS_StoreReachability(), aasworld, AREACONTENTS_JUMPPAD, AREACONTENTS_TELEPORTER, aas_s::areasettings, calcgrapplereach, aas_areasettings_s::contents, FreeMemory(), int(), aas_s::loaded, aas_s::numareas, aas_s::numreachabilityareas, PRT_MESSAGE, qfalse, qtrue, reach_barrier, reach_elevator, reach_equalfloor, reach_funcbob, reach_grapple, reach_jump, reach_jumppad, reach_ladder, reach_rocketjump, reach_step, reach_swim, reach_teleport, reach_walk, reach_walkoffledge, reach_waterjump, and Sys_MilliSeconds().
Referenced by AAS_ContinueInit().
float AAS_FaceArea (aas_face_t * face)
References aasworld, abs(), CrossProduct(), aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, aas_face_s::firstedge, aas_face_s::numedges, aas_edge_s::v, VectorLength(), VectorSubtract, and aas_s::vertexes.
Referenced by AAS_AreaGroundFaceArea(), AAS_AreaVolume(), and AAS_Reachability_Ladder().
void AAS_FaceCenter (int facenum, vec3_t center)
References aasworld, abs(), aas_s::edgeindex, aas_s::edges, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_face_s::numedges, aas_edge_s::v, VectorAdd, VectorClear, VectorScale, and aas_s::vertexes.
Referenced by AAS_Reachability_Grapple(), AAS_Reachability_JumpPad(), AAS_Reachability_Swim(), and AAS_Reachability_WeaponJump().
int AAS_FallDamageDistance (void)
References aassettings, aas_settings_s::phys_gravity, and t.
Referenced by AAS_Reachability_Grapple().
float AAS_FallDelta (float distance)
References aassettings, aas_settings_s::phys_gravity, and t.
Referenced by AAS_Reachability_Jump(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), and AAS_Reachability_WalkOffLedge().
aas_lreachability_t* AAS_FindFaceReachabilities (vec3_t * facepoints, int numpoints, aas_plane_t * plane, int towardsface)
References AAS_AllocReachability(), AAS_ClosestEdgePoints(), AAS_HorizontalVelocityForJump(), AAS_MaxJumpDistance(), AAS_PermanentLine(), AAS_PointInsideFace(), aassettings, aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, aas_plane_s::dist, DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, aas_lreachability_s::end, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, if(), aas_lreachability_s::next, aas_plane_s::normal, NULL, aas_s::numareas, aas_face_s::numedges, aas_area_s::numfaces, aas_settings_s::phys_jumpvel, aas_face_s::planenum, aas_s::planes, aas_lreachability_s::start, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, aas_edge_s::v, VectorCopy, VectorLength(), VectorMiddle(), VectorSubtract, and aas_s::vertexes.
Referenced by AAS_Reachability_FuncBobbing().
void AAS_FreeReachability (aas_lreachability_t * lreach)
References Com_Memset, aas_lreachability_s::next, nextreachability, and numlreachabilities.
Referenced by AAS_Reachability_FuncBobbing().
int AAS_GetJumpPadInfo (int ent, vec3_t areastart, vec3_t absmins, vec3_t absmaxs, vec3_t velocity)
References AAS_BSPModelMinsMaxsOrigin(), AAS_FloatForBSPEpairKey(), AAS_NextBSPEntity(), AAS_TraceClientBBox(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), aassettings, aas_trace_s::endpos, forward, height, MAX_EPAIRKEY, aas_settings_s::phys_gravity, PRESENCE_CROUCH, PRT_MESSAGE, qfalse, qtrue, aas_trace_s::startsolid, VectorAdd, VectorClear, VectorCopy, VectorNormalize(), VectorScale, and VectorSubtract.
Referenced by AAS_BestReachableFromJumpPadArea(), and AAS_Reachability_JumpPad().
void AAS_InitReachability (void)
References AAS_SetupReachabilityHeap(), AAS_SetWeaponJumpAreaFlags(), aasworld, calcgrapplereach, GetClearedMemory(), LibVarGetValue(), aas_s::loaded, aas_s::numareas, aas_s::numreachabilityareas, qtrue, aas_s::reachabilitysize, and aas_s::savefile.
Referenced by AAS_LoadMap().
float AAS_MaxJumpDistance (float phys_jumpvel)
References aassettings, aas_settings_s::phys_gravity, aas_settings_s::phys_maxvelocity, aas_settings_s::rs_maxjumpfallheight, and t.
Referenced by AAS_FindFaceReachabilities(), and AAS_Reachability_Jump().
float AAS_MaxJumpHeight (float phys_jumpvel)
References aassettings, and aas_settings_s::phys_gravity.
Referenced by AAS_Reachability_Jump(), and AAS_Reachability_Ladder().
int AAS_NearbySolidOrGap (vec3_t start, vec3_t end)
References AAS_AreaGrounded(), AAS_AreaSwim(), AAS_PointAreaNum(), aas_lreachability_s::areanum, qfalse, qtrue, VectorMA(), VectorNormalize(), and VectorSubtract.
void AAS_Reachability_Elevator (void)
References AAS_AllocReachability(), AAS_AreaGrounded(), AAS_AreaSwim(), AAS_BSPModelMinsMaxsOrigin(), AAS_FloatForBSPEpairKey(), AAS_NextBSPEntity(), AAS_PointAreaNum(), AAS_ReachabilityExists(), AAS_TraceClientBBox(), AAS_TravelFlagsForTeam(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), aassettings, aas_lreachability_s::areanum, aas_lreachability_s::edgenum, end, aas_lreachability_s::end, aas_lreachability_s::facenum, aas_trace_s::fraction, height, int(), Log_Write(), MAX_EPAIRKEY, n, aas_lreachability_s::next, PRESENCE_CROUCH, PRT_ERROR, reach_elevator, aas_settings_s::rs_startelevator, start, aas_lreachability_s::start, TRAVEL_ELEVATOR, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, and VectorSubtract.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_EqualFloorHeight (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaCrouch(), AAS_AreaGrounded(), aassettings, aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, Com_Memset, CrossProduct(), DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, end, aas_lreachability_s::end, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, height, INSIDEUNITS_WALKEND, INSIDEUNITS_WALKSTART, length(), aas_area_s::maxs, aas_area_s::mins, aas_lreachability_s::next, aas_plane_s::normal, aas_face_s::numedges, aas_area_s::numfaces, aas_face_s::planenum, aas_s::planes, qfalse, qtrue, reach_equalfloor, aas_settings_s::rs_startcrouch, start, aas_lreachability_s::start, TRAVEL_WALK, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, aas_edge_s::v, VectorAdd, VectorCopy, VectorInverse(), VectorLength(), VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and aas_s::vertexes.
Referenced by AAS_ContinueInitReachability().
void AAS_Reachability_FuncBobbing (void)
References AAS_AllocReachability(), AAS_BSPModelMinsMaxsOrigin(), AAS_FindFaceReachabilities(), AAS_FloatForBSPEpairKey(), AAS_FreeReachability(), AAS_IntForBSPEpairKey(), AAS_NextBSPEntity(), AAS_PermanentLine(), AAS_PointAreaNum(), AAS_TraceAreas(), AAS_TravelFlagsForTeam(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), aassettings, aas_lreachability_s::areanum, aas_plane_s::dist, aas_lreachability_s::edgenum, end, aas_lreachability_s::end, aas_lreachability_s::facenum, height, int(), Log_Write(), MAX_EPAIRKEY, aas_lreachability_s::next, aas_plane_s::normal, NULL, PRT_ERROR, qfalse, qtrue, reach_funcbob, aas_settings_s::rs_funcbob, start, aas_lreachability_s::start, TRAVEL_FUNCBOB, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, VectorSet, and VectorSubtract.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_Grapple (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaGrounded(), AAS_AreaPresenceType(), AAS_AreaSwim(), AAS_FaceCenter(), AAS_FallDamageDistance(), AAS_PointAreaNum(), AAS_PointContents(), AAS_ReachabilityExists(), AAS_Trace(), AAS_TraceAreas(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_LAVA, AREACONTENTS_SLIME, aas_lreachability_s::areanum, aas_s::areas, aas_s::areasettings, aas_area_s::center, aas_areasettings_s::contents, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_SOLID, CONTENTS_WATER, DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, end, aas_lreachability_s::end, aas_trace_s::endpos, FACE_SOLID, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, aas_trace_s::fraction, Log_Write(), M_PI, aas_area_s::maxs, aas_area_s::mins, aas_lreachability_s::next, aas_plane_s::normal, NULL, aas_area_s::numfaces, aas_face_s::planenum, aas_s::planes, PRESENCE_CROUCH, PRESENCE_NORMAL, qfalse, reach_grapple, aas_settings_s::rs_startgrapple, start, aas_lreachability_s::start, aas_trace_s::startsolid, SURF_SKY, TRAVEL_GRAPPLEHOOK, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, aas_edge_s::v, VectorCopy, VectorLength(), VectorMA(), VectorNormalize(), VectorSubtract, and aas_s::vertexes.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_Jump (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaClusterPortal(), AAS_AreaCrouch(), AAS_AreaGrounded(), AAS_AreaJumpPad(), AAS_ClosestEdgePoints(), AAS_FallDelta(), AAS_HorizontalVelocityForJump(), AAS_MaxJumpDistance(), AAS_MaxJumpHeight(), AAS_PointContents(), AAS_PredictClientMovement(), AAS_TraceAreas(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, ARRAY_LEN, CONTENTS_LAVA, CONTENTS_SLIME, CrossProduct(), DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, aas_lreachability_s::end, aas_trace_s::endpos, aas_clientmove_s::endpos, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, aas_trace_s::fraction, aas_clientmove_s::frames, height, Log_Write(), aas_area_s::maxs, aas_area_s::mins, move(), aas_lreachability_s::next, aas_plane_s::normal, NULL, aas_face_s::numedges, aas_area_s::numfaces, aas_settings_s::phys_falldelta10, aas_settings_s::phys_falldelta5, aas_settings_s::phys_gravity, aas_settings_s::phys_jumpvel, aas_settings_s::phys_maxbarrier, aas_settings_s::phys_maxwalkvelocity, aas_trace_s::planenum, aas_face_s::planenum, aas_s::planes, PRESENCE_NORMAL, qfalse, qtrue, reach_jump, reach_walkoffledge, aas_settings_s::rs_falldamage10, aas_settings_s::rs_falldamage5, aas_settings_s::rs_startjump, aas_settings_s::rs_startwalkoffledge, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_HITGROUND, SE_HITGROUNDDAMAGE, SE_TOUCHCLUSTERPORTAL, aas_lreachability_s::start, aas_trace_s::startsolid, aas_clientmove_s::stopevent, TRAVEL_JUMP, TRAVEL_WALKOFFLEDGE, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, TRAVELTYPE_MASK, up, aas_edge_s::v, VectorAdd, VectorClear, VectorCopy, VectorDistance(), VectorLength(), VectorMA(), VectorMiddle(), VectorNormalize(), VectorScale, VectorSubtract, and aas_s::vertexes.
Referenced by AAS_ContinueInitReachability().
void AAS_Reachability_JumpPad (void)
References AAS_AllocReachability(), AAS_AreaJumpPad(), AAS_FaceCenter(), AAS_GetJumpPadInfo(), AAS_HorizontalVelocityForJump(), AAS_LinkEntityClientBBox(), AAS_NextBSPEntity(), AAS_PredictClientMovement(), AAS_ReachabilityExists(), AAS_TravelFlagsForTeam(), AAS_UnlinkFromAreas(), AAS_ValueForBSPEpairKey(), aassettings, aasworld, abs(), aas_link_s::areanum, aas_lreachability_s::areanum, aas_s::areas, Com_Memset, aas_lreachability_s::edgenum, aas_lreachability_s::end, aas_clientmove_s::endarea, aas_clientmove_s::endpos, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_area_s::firstface, aas_clientmove_s::frames, LibVarValue(), MAX_EPAIRKEY, move(), aas_lreachability_s::next, aas_link_s::next_area, aas_s::numareas, aas_area_s::numfaces, PRESENCE_CROUCH, PRESENCE_NORMAL, PRT_MESSAGE, qfalse, reach_jumppad, aas_settings_s::rs_aircontrolledjumppad, aas_settings_s::rs_jumppad, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_HITGROUND, SE_HITGROUNDAREA, SE_HITGROUNDDAMAGE, SE_TOUCHJUMPPAD, SE_TOUCHTELEPORTER, aas_lreachability_s::start, aas_clientmove_s::stopevent, TRAVEL_JUMPPAD, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorCopy, VectorScale, VectorSet, VectorSubtract, and aas_clientmove_s::velocity.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_Ladder (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaLadder(), AAS_FaceArea(), AAS_MaxJumpHeight(), AAS_PointAreaNum(), AAS_ReachabilityExists(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, CrossProduct(), DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, end, aas_lreachability_s::end, aas_trace_s::endpos, FACE_GROUND, FACE_LADDER, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, Log_Write(), aas_lreachability_s::next, aas_plane_s::normal, NULL, aas_face_s::numedges, aas_area_s::numfaces, aas_settings_s::phys_jumpvel, aas_face_s::planenum, aas_s::planes, PRESENCE_NORMAL, qfalse, qtrue, reach_jump, reach_ladder, reach_walkoffledge, start, aas_lreachability_s::start, aas_trace_s::startsolid, TRAVEL_JUMP, TRAVEL_LADDER, TRAVEL_WALKOFFLEDGE, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, up, aas_edge_s::v, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and aas_s::vertexes.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaClusterPortal(), AAS_AreaCrouch(), AAS_AreaGrounded(), AAS_AreaJumpPad(), AAS_AreaSwim(), AAS_FallDelta(), AAS_PointAreaNum(), AAS_TraceAreas(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), AREA_LIQUID, aas_lreachability_s::areanum, aas_s::areas, aas_s::areasettings, ARRAY_LEN, CrossProduct(), DotProduct, aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, end, aas_lreachability_s::end, aas_trace_s::endpos, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, aas_trace_s::fraction, INSIDEUNITS, INSIDEUNITS_WALKEND, INSIDEUNITS_WALKSTART, INSIDEUNITS_WATERJUMP, length(), aas_area_s::maxs, aas_area_s::mins, aas_lreachability_s::next, aas_plane_s::normal, NULL, aas_face_s::numedges, aas_area_s::numfaces, aas_settings_s::phys_falldelta10, aas_settings_s::phys_falldelta5, aas_settings_s::phys_gravity, aas_settings_s::phys_maxbarrier, aas_settings_s::phys_maxstep, aas_settings_s::phys_maxwaterjump, aas_face_s::planenum, aas_s::planes, PRESENCE_NORMAL, aas_areasettings_s::presencetype, qfalse, qtrue, reach_barrier, reach_step, reach_walk, reach_walkoffledge, reach_waterjump, aas_settings_s::rs_barrierjump, aas_settings_s::rs_falldamage10, aas_settings_s::rs_falldamage5, aas_settings_s::rs_maxfallheight, aas_settings_s::rs_startcrouch, aas_settings_s::rs_startwalkoffledge, aas_settings_s::rs_waterjump, start, aas_lreachability_s::start, aas_trace_s::startsolid, TRAVEL_BARRIERJUMP, TRAVEL_WALK, TRAVEL_WALKOFFLEDGE, TRAVEL_WATERJUMP, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, aas_edge_s::v, VectorAdd, VectorCopy, VectorLength(), VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and aas_s::vertexes.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_Swim (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaSwim(), AAS_AreaVolume(), AAS_FaceCenter(), AAS_PointContents(), aasworld, abs(), aas_lreachability_s::areanum, aas_s::areas, aas_s::areasettings, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, aas_lreachability_s::edgenum, aas_lreachability_s::end, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_area_s::firstface, INSIDEUNITS, aas_area_s::maxs, aas_area_s::mins, aas_lreachability_s::next, aas_plane_s::normal, aas_area_s::numfaces, aas_face_s::planenum, aas_s::planes, PRESENCE_NORMAL, aas_areasettings_s::presencetype, qfalse, qtrue, reach_swim, start, aas_lreachability_s::start, TRAVEL_SWIM, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorCopy, and VectorMA().
Referenced by AAS_ContinueInitReachability().
void AAS_Reachability_Teleport (void)
References AAS_AllocReachability(), AAS_AreaJumpPad(), AAS_AreaTeleporter(), AAS_BSPModelMinsMaxsOrigin(), AAS_FloatForBSPEpairKey(), AAS_LinkEntityClientBBox(), AAS_NextBSPEntity(), AAS_PointAreaNum(), AAS_PredictClientMovement(), AAS_TraceClientBBox(), AAS_TravelFlagsForTeam(), AAS_UnlinkFromAreas(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), aassettings, AngleVectors(), aas_link_s::areanum, aas_lreachability_s::areanum, aas_lreachability_s::edgenum, end, aas_lreachability_s::end, aas_clientmove_s::endpos, aas_lreachability_s::facenum, MAX_EPAIRKEY, move(), aas_lreachability_s::next, aas_link_s::next_area, NULL, PRESENCE_CROUCH, PRESENCE_NORMAL, PRT_ERROR, PRT_MESSAGE, PRT_WARNING, qfalse, reach_teleport, aas_settings_s::rs_teleport, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_HITGROUND, SE_HITGROUNDDAMAGE, SE_TOUCHJUMPPAD, SE_TOUCHTELEPORTER, aas_lreachability_s::start, aas_trace_s::startsolid, aas_clientmove_s::stopevent, TRAVEL_TELEPORT, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorAdd, VectorClear, VectorCopy, VectorScale, and VectorSet.
Referenced by AAS_ContinueInitReachability().
void AAS_Reachability_WalkOffLedge (int areanum)
References AAS_AllocReachability(), AAS_AreaClusterPortal(), AAS_AreaGrounded(), AAS_AreaJumpPad(), AAS_AreaSwim(), AAS_FallDelta(), AAS_PointAreaNum(), AAS_ReachabilityExists(), AAS_TraceAreas(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), AREA_GROUNDED, AREACONTENTS_LAVA, AREACONTENTS_SLIME, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, aas_s::areas, aas_s::areasettings, ARRAY_LEN, aas_face_s::backarea, aas_areasettings_s::contents, CrossProduct(), aas_s::edgeindex, aas_lreachability_s::edgenum, aas_s::edges, aas_lreachability_s::end, aas_trace_s::endpos, FACE_GROUND, FACE_SOLID, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, aas_face_s::frontarea, m, n, aas_lreachability_s::next, aas_plane_s::normal, NULL, aas_face_s::numedges, aas_area_s::numfaces, aas_settings_s::phys_falldelta10, aas_settings_s::phys_falldelta5, aas_settings_s::phys_gravity, aas_face_s::planenum, aas_s::planes, PRESENCE_CROUCH, qfalse, qtrue, reach_walkoffledge, aas_settings_s::rs_falldamage10, aas_settings_s::rs_falldamage5, aas_settings_s::rs_maxfallheight, aas_settings_s::rs_startwalkoffledge, aas_lreachability_s::start, aas_trace_s::startsolid, TRAVEL_WALKOFFLEDGE, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, aas_edge_s::v, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and aas_s::vertexes.
Referenced by AAS_ContinueInitReachability().
int AAS_Reachability_WeaponJump (int area1num, int area2num)
References AAS_AllocReachability(), AAS_AreaGrounded(), AAS_AreaSwim(), AAS_BFGJumpZVelocity(), AAS_FaceCenter(), AAS_HorizontalVelocityForJump(), AAS_PointAreaNum(), AAS_PredictClientMovement(), AAS_RocketJumpZVelocity(), AAS_TraceClientBBox(), aassettings, aasworld, abs(), AREA_WEAPONJUMP, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, aas_s::areas, aas_s::areasettings, aas_area_s::center, aas_lreachability_s::edgenum, end, aas_lreachability_s::end, aas_trace_s::endpos, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_lreachability_s::facenum, aas_s::faces, aas_area_s::firstface, aas_clientmove_s::frames, Log_Write(), aas_area_s::maxs, aas_area_s::mins, move(), n, aas_lreachability_s::next, aas_area_s::numfaces, PRESENCE_CROUCH, PRESENCE_NORMAL, qfalse, qtrue, reach_rocketjump, aas_settings_s::rs_bfgjump, aas_settings_s::rs_rocketjump, SE_ENTERLAVA, SE_ENTERSLIME, SE_ENTERWATER, SE_HITGROUND, SE_HITGROUNDAREA, SE_HITGROUNDDAMAGE, SE_TOUCHJUMPPAD, start, aas_lreachability_s::start, aas_trace_s::startsolid, aas_clientmove_s::stopevent, TRAVEL_BFGJUMP, TRAVEL_ROCKETJUMP, aas_lreachability_s::traveltime, aas_lreachability_s::traveltype, VectorCopy, VectorScale, VectorSet, and VectorSubtract.
Referenced by AAS_ContinueInitReachability().
qboolean AAS_ReachabilityExists (int area1num, int area2num)
References aas_lreachability_s::areanum, aas_lreachability_s::next, qfalse, and qtrue.
Referenced by AAS_ContinueInitReachability(), AAS_Reachability_Elevator(), AAS_Reachability_Grapple(), AAS_Reachability_JumpPad(), AAS_Reachability_Ladder(), and AAS_Reachability_WalkOffLedge().
void AAS_SetupReachabilityHeap (void)
References AAS_MAX_REACHABILITYSIZE, GetClearedMemory(), aas_lreachability_s::next, NULL, numlreachabilities, and reachabilityheap.
Referenced by AAS_InitReachability().
void AAS_SetWeaponJumpAreaFlags (void)
References AAS_BestReachableArea(), AAS_DropToFloor(), AAS_IntForBSPEpairKey(), AAS_NextBSPEntity(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), aasworld, AREA_WEAPONJUMP, AREACONTENTS_JUMPPAD, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, aas_s::areasettings, aas_areasettings_s::contents, MAX_EPAIRKEY, aas_s::numareas, and PRT_MESSAGE.
Referenced by AAS_InitReachability().
void AAS_ShutDownReachabilityHeap (void)
References FreeMemory(), and numlreachabilities.
Referenced by AAS_ContinueInitReachability().
void AAS_StoreReachability (void)
References aasworld, aas_lreachability_s::areanum, aas_reachability_s::areanum, aas_s::areasettings, aas_lreachability_s::edgenum, aas_reachability_s::edgenum, aas_lreachability_s::end, aas_reachability_s::end, aas_lreachability_s::facenum, aas_reachability_s::facenum, aas_areasettings_s::firstreachablearea, FreeMemory(), GetClearedMemory(), aas_lreachability_s::next, aas_s::numareas, numlreachabilities, aas_areasettings_s::numreachableareas, reach(), aas_s::reachability, aas_s::reachabilitysize, aas_lreachability_s::start, aas_reachability_s::start, aas_lreachability_s::traveltime, aas_reachability_s::traveltime, aas_lreachability_s::traveltype, aas_reachability_s::traveltype, and VectorCopy.
Referenced by AAS_ContinueInitReachability().
int AAS_TravelFlagsForTeam (int ent)
References AAS_IntForBSPEpairKey(), TRAVELFLAG_NOTTEAM1, and TRAVELFLAG_NOTTEAM2.
Referenced by AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_JumpPad(), and AAS_Reachability_Teleport().
int Sys_MilliSeconds (void)
Referenced by AAS_AlternativeRouteGoals(), AAS_CalculateAreaTravelTimes(), AAS_ContinueInitReachability(), AAS_CreateReversedReachability(), BotLoadCachedCharacter(), BotLoadInitialChat(), BotLoadRandomStrings(), BotSetupChatAI(), Export_BotLibLoadMap(), and ReadWeightConfig().
int VectorBetweenVectors (vec3_t v, vec3_t v1, vec3_t v2)
References DotProduct, and VectorSubtract.
Referenced by AAS_ClosestEdgePoints().
float VectorDistance (vec3_t v1, vec3_t v2)
References VectorLength(), and VectorSubtract.
Referenced by AAS_ClosestEdgePoints(), and AAS_Reachability_Jump().
void VectorMiddle (vec3_t v1, vec3_t v2, vec3_t middle)
References VectorAdd, and VectorScale.
Referenced by AAS_FindFaceReachabilities(), and AAS_Reachability_Jump().
Variable Documentation
aas_lreachability_t** areareachability
botlib_import_t botimport
int calcgrapplereach
Referenced by AAS_ContinueInitReachability(), and AAS_InitReachability().
aas_lreachability_t* nextreachability
Referenced by AAS_AllocReachability(), and AAS_FreeReachability().
int numlreachabilities
Referenced by AAS_AllocReachability(), AAS_FreeReachability(), AAS_SetupReachabilityHeap(), AAS_ShutDownReachabilityHeap(), and AAS_StoreReachability().
int reach_barrier
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
int reach_bfgjump
int reach_doublejump
int reach_elevator
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Elevator().
int reach_equalfloor
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_EqualFloorHeight().
int reach_funcbob
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_FuncBobbing().
int reach_grapple
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Grapple().
int reach_jump
Referenced by AAS_ContinueInitReachability(), AAS_Reachability_Jump(), and AAS_Reachability_Ladder().
int reach_jumppad
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_JumpPad().
int reach_ladder
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Ladder().
int reach_rampjump
int reach_rocketjump
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_WeaponJump().
int reach_step
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
int reach_strafejump
int reach_swim
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Swim().
int reach_teleport
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Teleport().
int reach_walk
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
int reach_walkoffledge
Referenced by AAS_ContinueInitReachability(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), and AAS_Reachability_WalkOffLedge().
int reach_waterjump
Referenced by AAS_ContinueInitReachability(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
aas_lreachability_t* reachabilityheap
Referenced by AAS_SetupReachabilityHeap().