ioquake3: code/botlib/be_ai_char.c File Reference
be_ai_char.c File Reference
#include "../qcommon/q_shared.h"
#include "l_log.h"
#include "l_memory.h"
#include "l_utils.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_libvar.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_ai_char.h"
Data Structures
union cvalue
struct bot_characteristic_s
struct bot_character_s
Defines
#define MAX_CHARACTERISTICS 80
#define CT_INTEGER 1
#define CT_FLOAT 2
#define CT_STRING 3
#define DEFAULT_CHARACTER "bots/default_c.c"
Typedefs
typedef struct bot_characteristic_s bot_characteristic_t
typedef struct bot_character_s bot_character_t
Functions
bot_character_t * BotCharacterFromHandle (int handle)
void BotDumpCharacter (bot_character_t *ch)
void BotFreeCharacterStrings (bot_character_t *ch)
void BotFreeCharacter2 (int handle)
void BotFreeCharacter (int handle)
void BotDefaultCharacteristics (bot_character_t *ch, bot_character_t *defaultch)
bot_character_t * BotLoadCharacterFromFile (char *charfile, int skill)
int BotFindCachedCharacter (char *charfile, float skill)
int BotLoadCachedCharacter (char *charfile, float skill, int reload)
int BotLoadCharacterSkill (char *charfile, float skill)
int BotInterpolateCharacters (int handle1, int handle2, float desiredskill)
int BotLoadCharacter (char *charfile, float skill)
int CheckCharacteristicIndex (int character, int index)
float Characteristic_Float (int character, int index)
float Characteristic_BFloat (int character, int index, float min, float max)
int Characteristic_Integer (int character, int index)
int Characteristic_BInteger (int character, int index, int min, int max)
void Characteristic_String (int character, int index, char *buf, int size)
void BotShutdownCharacters (void)
Variables
bot_character_t * botcharacters [MAX_CLIENTS+1]
Define Documentation
#define CT_FLOAT 2
Referenced by BotDefaultCharacteristics(), BotDumpCharacter(), BotInterpolateCharacters(), BotLoadCharacterFromFile(), Characteristic_Float(), and Characteristic_Integer().
#define CT_INTEGER 1
Referenced by BotDefaultCharacteristics(), BotDumpCharacter(), BotInterpolateCharacters(), BotLoadCharacterFromFile(), Characteristic_Float(), and Characteristic_Integer().
#define CT_STRING 3
Referenced by BotDefaultCharacteristics(), BotDumpCharacter(), BotFreeCharacterStrings(), BotInterpolateCharacters(), BotLoadCharacterFromFile(), and Characteristic_String().
#define DEFAULT_CHARACTER "bots/default_c.c"
Referenced by BotLoadCachedCharacter(), and BotLoadCharacterSkill().
#define MAX_CHARACTERISTICS 80
Referenced by BotDefaultCharacteristics(), BotDumpCharacter(), BotFreeCharacterStrings(), BotInterpolateCharacters(), BotLoadCharacterFromFile(), and CheckCharacteristicIndex().
Typedef Documentation
typedef struct bot_character_s bot_character_t
typedef struct bot_characteristic_s bot_characteristic_t
Function Documentation
bot_character_t* BotCharacterFromHandle (int handle)
References botimport, MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotInterpolateCharacters(), Characteristic_BFloat(), Characteristic_BInteger(), Characteristic_Float(), Characteristic_Integer(), Characteristic_String(), and CheckCharacteristicIndex().
void BotDefaultCharacteristics (bot_character_t * ch, bot_character_t * defaultch)
References cvalue::_float, bot_character_s::c, CT_FLOAT, CT_INTEGER, CT_STRING, GetMemory(), cvalue::integer, MAX_CHARACTERISTICS, cvalue::string, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by BotLoadCharacterSkill().
void BotDumpCharacter (bot_character_t * ch)
References cvalue::_float, bot_character_s::c, CT_FLOAT, CT_INTEGER, CT_STRING, bot_character_s::filename, cvalue::integer, Log_Write(), MAX_CHARACTERISTICS, bot_character_s::skill, cvalue::string, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by BotLoadCharacter().
int BotFindCachedCharacter (char * charfile, float skill)
References MAX_CLIENTS.
Referenced by BotLoadCachedCharacter(), and BotLoadCharacter().
void BotFreeCharacter (int handle)
References BotFreeCharacter2(), and LibVarGetValue().
Referenced by Init_AI_Export().
void BotFreeCharacter2 (int handle)
References BotFreeCharacterStrings(), botimport, FreeMemory(), MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotFreeCharacter(), and BotShutdownCharacters().
void BotFreeCharacterStrings (bot_character_t * ch)
References bot_character_s::c, CT_STRING, FreeMemory(), MAX_CHARACTERISTICS, cvalue::string, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by BotFreeCharacter2(), and BotLoadCharacterFromFile().
int BotInterpolateCharacters (int handle1, int handle2, float desiredskill)
References cvalue::_float, BotCharacterFromHandle(), bot_character_s::c, CT_FLOAT, CT_INTEGER, CT_STRING, bot_character_s::filename, GetClearedMemory(), GetMemory(), cvalue::integer, MAX_CHARACTERISTICS, MAX_CLIENTS, out, bot_character_s::skill, cvalue::string, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by BotLoadCharacter().
int BotLoadCachedCharacter (char * charfile, float skill, int reload)
References botDeveloper, BotFindCachedCharacter(), botimport, BotLoadCharacterFromFile(), DEFAULT_CHARACTER, int(), MAX_CLIENTS, NULL, PRT_MESSAGE, PRT_WARNING, bot_character_s::skill, and Sys_MilliSeconds().
Referenced by BotLoadCharacterSkill().
int BotLoadCharacter (char * charfile, float skill)
References BotDumpCharacter(), BotFindCachedCharacter(), botimport, BotInterpolateCharacters(), BotLoadCharacterSkill(), and PRT_MESSAGE.
Referenced by Init_AI_Export().
bot_character_t* BotLoadCharacterFromFile (char * charfile, int skill)
References cvalue::_float, BOTFILESBASEFOLDER, BotFreeCharacterStrings(), botimport, bot_character_s::c, CT_FLOAT, CT_INTEGER, CT_STRING, bot_character_s::filename, FreeMemory(), FreeSource(), GetClearedMemory(), GetMemory(), cvalue::integer, LoadSourceFile(), MAX_CHARACTERISTICS, NULL, PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, qfalse, qtrue, bot_character_s::skill, SourceError(), cvalue::string, StripDoubleQuotes(), token, TT_FLOAT, TT_INTEGER, TT_NUMBER, TT_STRING, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by BotLoadCachedCharacter().
int BotLoadCharacterSkill (char * charfile, float skill)
References BotDefaultCharacteristics(), BotLoadCachedCharacter(), DEFAULT_CHARACTER, LibVarGetValue(), and qfalse.
Referenced by BotLoadCharacter().
void BotShutdownCharacters (void)
References BotFreeCharacter2(), and MAX_CLIENTS.
Referenced by Export_BotLibShutdown().
float Characteristic_BFloat (int character, int index, float min, float max)
References BotCharacterFromHandle(), botimport, Characteristic_Float(), PRT_ERROR, and value().
Referenced by Init_AI_Export().
int Characteristic_BInteger (int character, int index, int min, int max)
References BotCharacterFromHandle(), botimport, Characteristic_Integer(), PRT_ERROR, and value().
Referenced by Init_AI_Export().
float Characteristic_Float (int character, int index)
References cvalue::_float, BotCharacterFromHandle(), botimport, bot_character_s::c, CheckCharacteristicIndex(), CT_FLOAT, CT_INTEGER, cvalue::integer, PRT_ERROR, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by Characteristic_BFloat(), and Init_AI_Export().
int Characteristic_Integer (int character, int index)
References cvalue::_float, BotCharacterFromHandle(), botimport, bot_character_s::c, CheckCharacteristicIndex(), CT_FLOAT, CT_INTEGER, cvalue::integer, PRT_ERROR, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by Characteristic_BInteger(), and Init_AI_Export().
void Characteristic_String (int character, int index, char * buf, int size)
References BotCharacterFromHandle(), botimport, bot_character_s::c, CheckCharacteristicIndex(), CT_STRING, PRT_ERROR, cvalue::string, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by Init_AI_Export().
int CheckCharacteristicIndex (int character, int index)
References BotCharacterFromHandle(), botimport, bot_character_s::c, MAX_CHARACTERISTICS, PRT_ERROR, qfalse, qtrue, and bot_characteristic_s::type.
Referenced by Characteristic_Float(), Characteristic_Integer(), and Characteristic_String().
Variable Documentation
bot_character_t* botcharacters[MAX_CLIENTS+1]