ioquake3: code/game/bg_local.h File Reference
bg_local.h File Reference
Data Structures
struct pml_t
Defines
#define MIN_WALK_NORMAL 0.7f
#define STEPSIZE 18
#define JUMP_VELOCITY 270
#define TIMER_LAND 130
#define TIMER_GESTURE (34*66+50)
#define OVERCLIP 1.001f
Functions
void PM_ClipVelocity (vec3_t in, vec3_t normal, vec3_t out, float overbounce)
void PM_AddTouchEnt (int entityNum)
void PM_AddEvent (int newEvent)
qboolean PM_SlideMove (qboolean gravity)
void PM_StepSlideMove (qboolean gravity)
Variables
pmove_t * pm
pml_t pml
float pm_stopspeed
float pm_duckScale
float pm_swimScale
float pm_accelerate
float pm_airaccelerate
float pm_wateraccelerate
float pm_flyaccelerate
float pm_friction
float pm_waterfriction
float pm_flightfriction
int c_pmove
Define Documentation
#define JUMP_VELOCITY 270
Referenced by PM_CheckJump().
#define MIN_WALK_NORMAL 0.7f
Referenced by PM_GroundTrace().
#define OVERCLIP 1.001f
Referenced by PM_AirMove(), PM_SlideMove(), PM_StepSlideMove(), PM_WalkMove(), and PM_WaterMove().
#define STEPSIZE 18
Referenced by init_error_limit(), and PM_StepSlideMove().
#define TIMER_GESTURE (34*66+50)
Referenced by PM_Animate().
#define TIMER_LAND 130
Referenced by PM_CrashLand().
Function Documentation
void PM_AddEvent (int newEvent)
References BG_AddPredictableEventToPlayerstate(), and pmove_t::ps.
Referenced by PM_Animate(), PM_BeginWeaponChange(), PM_CheckJump(), PM_CrashLand(), PM_Footsteps(), PM_StepSlideMove(), PM_WaterEvents(), and PM_Weapon().
void PM_AddTouchEnt (int entityNum)
References ENTITYNUM_WORLD, MAXTOUCH, pmove_t::numtouch, and pmove_t::touchents.
Referenced by PM_GroundTrace(), and PM_SlideMove().
void PM_ClipVelocity (vec3_t in, vec3_t normal, vec3_t out, float overbounce)
References DotProduct.
Referenced by PM_AirMove(), PM_SlideMove(), PM_StepSlideMove(), PM_WalkMove(), and PM_WaterMove().
qboolean PM_SlideMove (qboolean gravity)
References trace_t::allsolid, playerState_s::clientNum, CrossProduct(), DotProduct, end, trace_t::endpos, trace_t::entityNum, trace_t::fraction, pml_t::frametime, playerState_s::gravity, pml_t::groundPlane, pml_t::groundTrace, pml_t::impactSpeed, MAX_CLIP_PLANES, pmove_t::maxs, pmove_t::mins, cplane_s::normal, playerState_s::origin, OVERCLIP, trace_t::plane, planes, pm, PM_AddTouchEnt(), PM_ClipVelocity(), playerState_s::pm_time, pml, pmove_t::ps, qtrue, pmove_t::trace, pmove_t::tracemask, VectorAdd, VectorClear, VectorCopy, VectorMA(), VectorNormalize(), VectorNormalize2(), VectorScale, and playerState_s::velocity.
Referenced by PM_AirMove(), PM_StepSlideMove(), and PM_WaterMove().
void PM_StepSlideMove (qboolean gravity)
References trace_t::allsolid, c_pmove, playerState_s::clientNum, Com_Printf(), pmove_t::debugLevel, DotProduct, trace_t::endpos, EV_STEP_12, EV_STEP_16, EV_STEP_4, EV_STEP_8, trace_t::fraction, pmove_t::maxs, pmove_t::mins, cplane_s::normal, playerState_s::origin, OVERCLIP, trace_t::plane, pm, PM_AddEvent(), PM_ClipVelocity(), PM_SlideMove(), pmove_t::ps, STEPSIZE, pmove_t::trace, pmove_t::tracemask, up, VectorCopy, VectorSet, and playerState_s::velocity.
Referenced by PM_AirMove(), PM_FlyMove(), PM_WalkMove(), and PM_WaterJumpMove().
Variable Documentation
int c_pmove
Referenced by PM_CorrectAllSolid(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_StepSlideMove(), and PmoveSingle().
pmove_t* pm
Referenced by ClientThink_real(), PM_SlideMove(), PM_StepSlideMove(), and SpectatorThink().
float pm_accelerate
Referenced by PM_NoclipMove(), and PM_WalkMove().
float pm_airaccelerate
Referenced by PM_AirMove(), and PM_WalkMove().
float pm_duckScale
Referenced by PM_WalkMove().
float pm_flightfriction
Referenced by PM_Friction().
float pm_flyaccelerate
Referenced by PM_FlyMove().
float pm_friction
Referenced by PM_Friction(), and PM_NoclipMove().
float pm_stopspeed
Referenced by PM_Friction(), and PM_NoclipMove().
float pm_swimScale
Referenced by PM_WalkMove(), and PM_WaterMove().
float pm_wateraccelerate
Referenced by PM_WaterMove().
float pm_waterfriction
Referenced by PM_Friction().
pml_t pml
Referenced by PM_SlideMove().