ioquake3: code/tools/lcc/src/c.h File Reference
c.h File Reference
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <string.h>
#include "config.h"
#include "token.h"
Data Structures
struct coord
union value
struct Xtype
union floatint_t
struct metrics
struct interface
struct binding
struct Events
struct node
struct list
struct code
struct swtch
struct symbol
struct tree
struct type
struct field
Defines
#define NEW(p, a) ((p) = allocate(sizeof *(p), (a)))
#define NEW0(p, a) memset(NEW((p),(a)), 0, sizeof *(p))
#define isaddrop(op)
#define MAXLINE 512
#define BUFSIZE 4096
#define istypename(t, tsym)
#define sizeop(n) ((n)<<10)
#define generic(op) ((op)&0x3F0)
#define specific(op) ((op)&0x3FF)
#define opindex(op) (((op)>>4)&0x3F)
#define opkind(op) ((op)&~0x3F0)
#define opsize(op) ((op)>>10)
#define optype(op) ((op)&0xF)
#define NELEMS(a) ((int)(sizeof (a)/sizeof ((a)[0])))
#define roundup(x, n) (((x)+((n)-1))&(~((n)-1)))
#define mkop(op, ty) (specific((op) + ttob(ty)))
#define extend(x, ty) ((x)&(1<<(8*(ty)->size-1)) ? (x)|((~0UL)<<(8*(ty)->size-1)) : (x)&ones(8*(ty)->size))
#define ones(n) ((n)>=8*sizeof (unsigned long) ? ~0UL : ~((~0UL)<<(n)))
#define isqual(t) ((t)->op >= CONST)
#define unqual(t) (isqual(t) ? (t)->type : (t))
#define isvolatile(t)
#define isconst(t)
#define isarray(t) (unqual(t)->op == ARRAY)
#define isstruct(t)
#define isunion(t) (unqual(t)->op == UNION)
#define isfunc(t) (unqual(t)->op == FUNCTION)
#define isptr(t) (unqual(t)->op == POINTER)
#define ischar(t) ((t)->size == 1 && isint(t))
#define isint(t)
#define isfloat(t) (unqual(t)->op == FLOAT)
#define isarith(t) (unqual(t)->op <= UNSIGNED)
#define isunsigned(t) (unqual(t)->op == UNSIGNED)
#define isscalar(t)
#define isenum(t) (unqual(t)->op == ENUM)
#define fieldsize(p) (p)->bitsize
#define fieldright(p) ((p)->lsb - 1)
#define fieldleft(p)
#define fieldmask(p) (~(~(unsigned)0<<fieldsize(p)))
#define xx(a, b, c, d, e, f, g) a=b,
#define yy(a, b, c, d, e, f, g)
#define gop(name, value) name=value<<4,
#define op(name, type, sizes)
Typedefs
typedef struct node * Node
typedef struct list * List
typedef struct code * Code
typedef struct swtch * Swtch
typedef struct symbol * Symbol
typedef struct coord Coordinate
typedef struct table * Table
typedef union value Value
typedef struct tree * Tree
typedef struct type * Type
typedef struct field * Field
typedef struct metrics Metrics
typedef struct interface Interface
typedef struct binding Binding
typedef void(* Apply)(void *, void *, void *)
Enumerations
enum { OR = 40<<4 }
enum {
F = FLOAT, I = INT, U = UNSIGNED, P = POINTER,
V = VOID, B = STRUCT
}
enum { gop }
enum { CODE = 1, BSS, DATA, LIT }
enum { PERM = 0, FUNC, STMT }
enum {
CONSTANTS = 1, LABELS, GLOBAL, PARAM,
LOCAL
}
enum {
AND = 38<<4, NOT = 39<<4, OR = 40<<4, COND = 41<<4,
RIGHT = 42<<4, FIELD = 43<<4
}
Functions
void * allocate (unsigned long n, unsigned a)
void deallocate (unsigned a)
void * newarray (unsigned long m, unsigned long n, unsigned a)
void walk (Tree e, int tlab, int flab)
Node listnodes (Tree e, int tlab, int flab)
Node newnode (int op, Node left, Node right, Symbol p)
Tree cvtconst (Tree)
void printdag (Node, int)
void compound (int, Swtch, int)
void defglobal (Symbol, int)
void finalize (void)
void program (void)
Tree vcall (Symbol func, Type ty,...)
Tree addrof (Tree)
Tree asgn (Symbol, Tree)
Tree asgntree (int, Tree, Tree)
Type assign (Type, Tree)
Tree bittree (int, Tree, Tree)
Tree call (Tree, Type, Coordinate)
Tree calltree (Tree, Type, Tree, Symbol)
Tree condtree (Tree, Tree, Tree)
Tree cnsttree (Type,...)
Tree consttree (unsigned int, Type)
Tree eqtree (int, Tree, Tree)
int iscallb (Tree)
Tree shtree (int, Tree, Tree)
void typeerror (int, Tree, Tree)
void test (int tok, char set[])
void expect (int tok)
void skipto (int tok, char set[])
void error (const char *,...)
int fatal (const char *, const char *, int)
void warning (const char *,...)
void attach (Apply, void *, List *)
void apply (List event, void *arg1, void *arg2)
Tree retype (Tree p, Type ty)
Tree rightkid (Tree p)
int hascall (Tree p)
Type binary (Type, Type)
Tree cast (Tree, Type)
Tree cond (Tree)
Tree expr0 (int)
Tree expr (int)
Tree expr1 (int)
Tree field (Tree, const char *)
char * funcname (Tree)
Tree idtree (Symbol)
Tree incr (int, Tree, Tree)
Tree lvalue (Tree)
Tree nullcall (Type, Symbol, Tree, Tree)
Tree pointer (Tree)
Tree rvalue (Tree)
Tree value (Tree)
void defpointer (Symbol)
Type initializer (Type, int)
void swtoseg (int)
void input_init (int, char *[])
void fillbuf (void)
void nextline (void)
int getchr (void)
int gettok (void)
void emitcode (void)
void gencode (Symbol[], Symbol[])
void fprint (FILE *f, const char *fmt,...)
char * stringf (const char *,...)
void check (Node)
void print (const char *,...)
List append (void *x, List list)
int length (List list)
void * ltov (List *list, unsigned a)
void init (int, char *[])
Type typename (void)
void checklab (Symbol p, void *cl)
Type enumdcl (void)
void main_init (int, char *[])
int main (int, char *[])
void vfprint (FILE *, char *, const char *, va_list)
int process (char *)
int findfunc (char *, char *)
int findcount (char *, int, int)
Tree constexpr (int)
int intexpr (int, int)
Tree simplify (int, Type, Tree, Tree)
int ispow2 (unsigned long u)
int reachable (int)
void addlocal (Symbol)
void branch (int)
Code code (int)
void definelab (int)
void definept (Coordinate *)
void equatelab (Symbol, Symbol)
Node jump (int)
void retcode (Tree)
void statement (int, Swtch, int)
void swcode (Swtch, int *, int, int)
void swgen (Swtch)
char * string (const char *str)
char * stringn (const char *str, int len)
char * stringd (long n)
Symbol relocate (const char *name, Table src, Table dst)
void use (Symbol p, Coordinate src)
void locus (Table tp, Coordinate *cp)
Symbol allsymbols (Table)
Symbol constant (Type, Value)
void enterscope (void)
void exitscope (void)
Symbol findlabel (int)
Symbol findtype (Type)
void foreach (Table, int, void(*)(Symbol, void *), void *)
Symbol genident (int, Type, int)
int genlabel (int)
Symbol install (const char *, Table *, int, int)
Symbol intconst (int)
Symbol lookup (const char *, Table)
Symbol mkstr (char *)
Symbol mksymbol (int, const char *, Type)
Symbol newtemp (int, int, int)
Table table (Table, int)
Symbol temporary (int, Type)
char * vtoa (Type, Value)
int nodeid (Tree)
char * opname (int)
int * printed (int)
void printtree (Tree, int)
Tree root (Tree)
Tree texpr (Tree(*)(int), int, int)
Tree tree (int, Type, Tree, Tree)
void type_init (int, char *[])
Type signedint (Type)
int hasproto (Type)
void outtype (Type, FILE *)
void printdecl (Symbol p, Type ty)
void printproto (Symbol p, Symbol args[])
char * typestring (Type ty, char *id)
Field fieldref (const char *name, Type ty)
Type array (Type, int, int)
Type atop (Type)
Type btot (int, int)
Type compose (Type, Type)
Type deref (Type)
int eqtype (Type, Type, int)
Field fieldlist (Type)
Type freturn (Type)
Type ftype (Type, Type)
Type func (Type, Type *, int)
Field newfield (char *, Type, Type)
Type newstruct (int, char *)
void printtype (Type, int)
Type promote (Type)
Type ptr (Type)
Type qual (int, Type)
void rmtypes (int)
int ttob (Type)
int variadic (Type)
Variables
Binding bindings []
Interface * IR
int assignargs
int prunetemps
int nodecount
Symbol cfunc
Symbol retv
Tree(* optree [])(int, Tree, Tree)
char kind []
int errcnt
int errlimit
int wflag
Events events
float refinc
unsigned char * cp
unsigned char * limit
char * firstfile
char * file
char * line
int lineno
int t
char * token
Symbol tsym
Coordinate src
int Aflag
int Pflag
Symbol YYnull
Symbol YYcheck
int glevel
int xref
int ncalled
int npoints
int needconst
int explicitCast
struct code codehead
Code codelist
Table stmtlabs
float density
Table constants
Table externals
Table globals
Table identifiers
Table labels
Table types
int level
List loci
List symbols
int where
Type chartype
Type doubletype
Type floattype
Type inttype
Type longdouble
Type longtype
Type longlong
Type shorttype
Type signedchar
Type unsignedchar
Type unsignedlonglong
Type unsignedlong
Type unsignedshort
Type unsignedtype
Type charptype
Type funcptype
Type voidptype
Type voidtype
Type unsignedptr
Type signedptr
Type widechar
Define Documentation
#define BUFSIZE 4096
Referenced by fillbuf(), and scon().
#define extend (x, ty) ((x)&(1<<(8*(ty)->size-1)) ? (x)|((~0UL)<<(8*(ty)->size-1)) : (x)&ones(8*(ty)->size))
Referenced by gettok(), simplify(), and statement().
#define fieldleft (p)
Value:
(8*(p)->type->size - \
                        fieldsize(p) - fieldright(p))
Referenced by initfields(), and listnodes().
#define fieldmask (p) (~(~(unsigned)0<<fieldsize(p)))
Referenced by asgntree(), initfields(), and listnodes().
#define fieldright (p) ((p)->lsb - 1)
Referenced by initfields(), listnodes(), printtree1(), and prtype().
#define fieldsize (p) (p)->bitsize
Referenced by asgntree(), initfields(), listnodes(), printtree1(), and prtype().
#define generic (op) ((op)&0x3F0)
#define gop (name, value) name=value<<4,
#define isaddrop (op)
Value:
(specific(op)==ADDRG+P || specific(op)==ADDRL+P \
        || specific(op)==ADDRF+P)
Referenced by asgntree(), field(), foldcond(), funcname(), iscallb(), kill(), listnodes(), postfix(), prune(), replace(), simplify(), swstmt(), and unary().
#define isarith (t) (unqual(t)->op <= UNSIGNED)
Referenced by assign(), cmptree(), condtree(), genconst(), and unary().
#define isarray (t) (unqual(t)->op == ARRAY)
Referenced by addrtree(), array(), asgn(), atop(), call(), consttree(), cvtconst(), dcllocal(), dclparam(), doconst(), doglobal(), field(), func(), genconst(), idtree(), initglobal(), initializer(), nullcall(), outtype(), pointer(), postfix(), qual(), tracevalue(), typestring(), and unary().
#define ischar (t) ((t)->size == 1 && isint(t))
Referenced by initializer(), primary(), printtoken(), and typestring().
#define isconst (t)
Value:
((t)->op == CONST \
                    || (t)->op == CONST+VOLATILE)
Referenced by asgntree(), assign(), compose(), condtree(), dcllocal(), field(), initglobal(), qual(), specifier(), and unary().
#define isenum (t) (unqual(t)->op == ENUM)
Referenced by assign(), call(), calltree(), decl(), deref(), eqtype(), funcdefn(), and unary().
#define isfloat (t) (unqual(t)->op == FLOAT)
Referenced by calltree(), cast(), and retcode().
#define isfunc (t) (unqual(t)->op == FUNCTION)
Referenced by array(), cast(), checkref(), compatible(), conditional(), condtree(), dclglobal(), dcllocal(), dclparam(), decl(), doglobal(), eqtree(), expr2(), freturn(), func(), funcdefn(), idtree(), listnodes(), pointer(), postfix(), qual(), typestab(), typestring(), unary(), variadic(), and vcall().
#define isint (t)
Value:
(unqual(t)->op == INT \
                    || unqual(t)->op == UNSIGNED)
Referenced by bittree(), call(), cast(), consttree(), funcdefn(), listnodes(), shtree(), statement(), swstmt(), and unary().
#define isptr (t) (unqual(t)->op == POINTER)
Referenced by addrtree(), asgntree(), assign(), calltree(), compatible(), condtree(), deref(), eqtree(), field(), funcdefn(), idtree(), listnodes(), nullcheck(), postfix(), retcode(), root1(), tracevalue(), typestring(), and unary().
#define isqual (t) ((t)->op >= CONST)
Referenced by qual(), and specifier().
#define isscalar (t)
Value:
(unqual(t)->op <= POINTER \
                    || unqual(t)->op == ENUM)
Referenced by askregvar(), checkref(), dcllocal(), initializer(), and unary().
#define isstruct (t)
Value:
(unqual(t)->op == STRUCT \
                    || unqual(t)->op == UNION)
Referenced by asgn(), asgntree(), assign(), call(), calltree(), compound(), dcllocal(), dclparam(), decl(), funcdefn(), idtree(), initializer(), listnodes(), and postfix().
#define istypename (t, tsym)
Value:
(kind[t] == CHAR \
        || (t == ID && tsym && tsym->sclass == TYPEDEF))
Referenced by compound(), dclr1(), decl(), funcdefn(), parameters(), specifier(), structdcl(), and unary().
#define isunion (t) (unqual(t)->op == UNION)
Referenced by initializer().
#define isunsigned (t) (unqual(t)->op == UNSIGNED)
Referenced by asgntree(), cast(), swcode(), and unary().
#define isvolatile (t)
Value:
((t)->op == VOLATILE \
                    || (t)->op == CONST+VOLATILE)
Referenced by assign(), checkref(), compose(), condtree(), dcllocal(), dclparam(), field(), listnodes(), qual(), root1(), specifier(), swstmt(), and unary().
#define MAXLINE 512
Referenced by fillbuf(), gettok(), input_init(), and resynch().
#define mkop (op, ty) (specific((op) + ttob(ty)))
Referenced by asgntree(), call(), calltree(), cmptree(), cnsttree(), eqtree(), idtree(), primary(), retcode(), rvalue(), simplify(), tracevalue(), and vcall().
#define NELEMS (a) ((int)(sizeof (a)/sizeof ((a)[0])))
Referenced by allocate(), bbincr(), deallocate(), emit(), emitasm(), gather(), gen(), kill(), linearize(), node(), opname(), printdag1(), printnode(), printtree1(), ralloc(), rmtypes(), spill(), spillr(), stringn(), type(), and uses().
#define NEW (p, a) ((p) = allocate(sizeof *(p), (a)))
Referenced by acaller(), afunction(), append(), attach(), bbincr(), code(), funcdefn(), gather(), stringn(), and use().
#define NEW0 (p, a) memset(NEW((p),(a)), 0, sizeof *(p))
Referenced by addrtree(), constant(), dagnode(), findlabel(), genident(), genspill(), install(), listnodes(), mkreg(), mksymbol(), mkwildcard(), newfield(), table(), temporary(), tnode(), tree(), and type().
#define ones (n) ((n)>=8*sizeof (unsigned long) ? ~0UL : ~((~0UL)<<(n)))
Referenced by backslash(), CG_DrawOldTourneyScoreboard(), cnsttree(), simplify(), type_init(), and xxinit().
#define op (name, type, sizes)
#define opindex (op) (((op)>>4)&0x3F)
Referenced by gen(), genspill(), node(), opname(), prelabel(), and ralloc().
#define opkind (op) ((op)&~0x3F0)
Referenced by gen(), genreload(), genspill(), listnodes(), prelabel(), ralloc(), and rtarget().
#define opsize (op) ((op)>>10)
Referenced by opname(), prelabel(), spillr(), and visit().
#define optype (op) ((op)&0xF)
Referenced by btot(), defsymbol(), dumptree(), listnodes(), opname(), prelabel(), simplify(), and spillr().
#define roundup (x, n) (((x)+((n)-1))&(~((n)-1)))
Referenced by allocate(), function(), initstruct(), local(), mkactual(), and mkauto().
#define sizeop (n) ((n)<<10)
Referenced by genreload(), genspill(), listnodes(), and ttob().
#define specific (op) ((op)&0x3FF)
Referenced by definelab(), dumptree(), fixup(), range(), and visit().
#define unqual (t) (isqual(t) ? (t)->type : (t))
Referenced by array(), asgn(), asgntree(), assign(), call(), calltree(), cast(), compatible(), compose(), condtree(), constant(), decl(), deref(), eqtree(), eqtype(), field(), fieldref(), funcdefn(), idtree(), initializer(), isnullptr(), listnodes(), lvalue(), nullcall(), promote(), root1(), rvalue(), specifier(), tracevalue(), unary(), and vtoa().
#define xx (a, b, c, d, e, f, g) a=b,
#define yy (a, b, c, d, e, f, g)
Referenced by filter_mem16_10(), filter_mem16_8(), fir_mem16_10(), fir_mem16_8(), iir_mem16(), iir_mem16_10(), iir_mem16_8(), JointToMatrix(), pitch_xcorr(), and R_LevelShot().
Typedef Documentation
typedef void(* Apply)(void *, void *, void *)
typedef struct binding Binding
typedef struct code* Code
typedef struct coord Coordinate
typedef struct field* Field
typedef struct interface Interface
typedef struct list* List
typedef struct metrics Metrics
typedef struct node* Node
typedef struct swtch* Swtch
typedef struct symbol* Symbol
typedef struct table* Table
typedef struct tree* Tree
typedef struct type* Type
typedef union value Value
Enumeration Type Documentation
anonymous enum
Enumerator:
OR
anonymous enum
Enumerator:
F
I
U
P
V
B
anonymous enum
Enumerator:
gop
anonymous enum
Enumerator:
CODE
BSS
DATA
LIT
anonymous enum
Enumerator:
PERM
FUNC
STMT
anonymous enum
Enumerator:
CONSTANTS
LABELS
GLOBAL
PARAM
LOCAL
anonymous enum
Enumerator:
AND
NOT
OR
COND
RIGHT
FIELD
Function Documentation
void addlocal (Symbol)
References code, symbol::defined, level, code::Local, and symbol::scope.
Referenced by addrtree(), listnodes(), primary(), retcode(), swstmt(), tracecall(), and undag().
Tree addrof (Tree)
References ASGN, COND, error(), idtree(), tree::kids, tree::op, RIGHT, root(), tree::sym, tree(), tree::type, tree::u, and value().
Referenced by call(), calltree(), postfix(), and tracevalue().
void* allocate (unsigned long n, unsigned a)
References block::avail, error(), block::limit, m, n, NELEMS, block::next, NULL, and roundup.
Referenced by appendstr(), newarray(), primary(), prof_init(), and stringn().
Symbol allsymbols (Table)
References table::all.
Referenced by locus().
List append (void * x, List list)
References list::link, NEW, NULL, PERM, and list::x.
void apply (List event, void * arg1, void * arg2)
References entry::cl, entry::func, list::link, and list::x.
Referenced by call(), compound(), definept(), expr2(), expr3(), funcdefn(), main(), and retcode().
Type array (Type , int , int)
References Aflag, type::align, array(), error(), INT_MAX, isarray, isfunc, NULL, type::size, type(), unqual, and warning().
Referenced by array(), bbcall(), bbentry(), bbvars(), compose(), dcllocal(), dclr(), doglobal(), field(), gettok(), initializer(), ltov(), mkstr(), prof_init(), and swcode().
Tree asgn (Symbol , Tree)
References ASGN, asgntree, B, idtree(), isarray, isstruct, NULL, symbol::s, type::sym, tree(), symbol::type, tree::type, symbol::u, type::u, and unqual.
Referenced by bbcall(), call(), condtree(), dcllocal(), gencode(), nullcheck(), retcode(), swstmt(), and tracecall().
Tree asgntree (int , Tree , Tree)
References ASGN, assign(), B, bittree, CALL, cast(), cnsttree(), symbol::computed, error(), tree::field, FIELD, fieldmask, fieldsize, symbol::generated, value::i, I, idtree(), inttype, isaddrop, iscallb(), isconst, isptr, isstruct, isunsigned, tree::kids, LSH, lvalue(), mkop, symbol::name, tree::op, pointer(), retype(), RIGHT, RSH, shtree(), type::size, tree::sym, tree(), tree::type, field::type, typeerror(), symbol::u, tree::u, unqual, tree::v, and voidtype.
Type assign (Type , Tree)
References Aflag, eqtype(), inttype, isarith, isconst, isenum, isnullptr(), isptr, isstruct, isvoidptr, isvolatile, NULL, type::size, tree::type, type::type, unqual, and warning().
Referenced by asgntree(), call(), initializer(), initvalue(), and retcode().
Type atop (Type)
References error(), isarray, ptr(), and type::type.
Referenced by consttree(), cvtconst(), dclparam(), nullcall(), and pointer().
void attach (Apply , void * , List *)
References append(), entry::cl, cl, entry::func, func(), NEW, and PERM.
Referenced by prof_init(), and trace_init().
Type binary (Type , Type)
References doubletype, floattype, inttype, longdouble, longlong, longtype, type::size, unsignedlong, unsignedlonglong, unsignedtype, and xx.
Referenced by bittree(), cmptree(), and condtree().
Tree bittree (int , Tree , Tree)
References binary(), cast(), inttype, isint, simplify(), tree::type, and typeerror().
void branch (int)
References code, cp, equal(), equatelab(), findlabel(), code::forest, jump(), code::kind, code::next, NULL, node::op, code::prev, symbol::ref, node::syms, code::u, V, walk(), and warning().
Referenced by forstmt(), ifstmt(), statement(), swcode(), swstmt(), and whilestmt().
Type btot (int , int)
References F, I, INT, type::op, optype, P, U, and xx.
Referenced by newtemp(), and visit().
Tree call (Tree , Type , Coordinate)
References addrof(), Aflag, apply(), args, asgn(), assign(), Events::calls, calltree(), cast(), error(), events, expect(), expr1(), symbol::f, type::f, freturn(), funcname(), gettok(), hascall(), idtree(), inttype, IR, isarray, iscallb(), isenum, isint, isstruct, lvalue(), mkop, n, NULL, pointer(), promote(), ptr(), RIGHT, root(), type::size, t, temporary(), tree(), symbol::type, tree::type, type::u, unqual, value(), voidtype, interface::wants_argb, and warning().
Referenced by asmcall(), postfix(), and VM_CallCompiled().
Tree calltree (Tree , Type , Tree , Symbol)
References addrof(), B, CALL, cast(), idtree(), isenum, isfloat, isptr, isstruct, mkop, NULL, promote(), RIGHT, type::size, tree(), tree::type, and unqual.
Referenced by call(), tracefinis(), and vcall().
Tree cast (Tree , Type)
References ADD, cast(), cnsttree(), condtree(), consttree(), INT, inttype, isfloat, isfunc, isint, isunsigned, symbol::limits, longdouble, NULL, type::op, optree, retype(), RSH, signedint(), simplify(), type::size, src, SUB, super(), type::sym, tree::type, type::type, symbol::u, type::u, unqual, unsignedlong, unsignedtype, value(), and warning().
Referenced by asgntree(), bittree(), call(), calltree(), cast(), cmp(), cmptree(), condtree(), eqtree(), initializer(), initvalue(), intexpr(), listnodes(), nullcheck(), retcode(), shtree(), simplify(), statement(), swcode(), swstmt(), tracevalue(), and unary().
void check (Node)
Referenced by G_MoverPush(), G_TryPushingEntity(), gen(), SV_AreaEntities_r(), and Svcmd_EntityList_f().
void checklab (Symbol p, void * cl)
References symbol::defined, error(), and symbol::name.
Referenced by funcdefn().
Tree cnsttree (Type , ...)
References value::d, value::i, INT, mkop, NULL, ones, type::op, value::p, type::size, tree(), value::u, tree::u, and tree::v.
Referenced by asgntree(), cast(), cmp(), consttree(), funcdefn(), listnodes(), nullcall(), nullcheck(), primary(), simplify(), swcode(), and unary().
Code code (int)
References codelist, cp, FUNC, code::kind, kind, NEW, code::next, NULL, code::prev, reachable(), and warning().
Type compose (Type , Type)
References type::align, append(), array(), compose(), type::f, func(), isconst, isvolatile, ltov(), NULL, type::op, PERM, ptr(), qual(), type::size, type::type, type::u, and unqual.
void compound (int , Swtch , int)
Referenced by funcdefn(), and statement().
Tree cond (Tree)
References AND, consttree(), EQ, GT, inttype, LT, NEQ, NOT, tree::op, op, optree, OR, pointer(), and rightkid().
Referenced by addd(), addi(), conditional(), condtree(), divd(), divi(), muld(), muli(), nullcheck(), simplify(), and unary().
Tree condtree (Tree , Tree , Tree)
References asgn(), binary(), cast(), COND, cond(), consttree(), value::d, eqtype(), F, genident(), value::i, I, inttype, isarith, isconst, isfunc, isnullptr(), isptr, isvoidptr, isvolatile, level, NULL, tree::op, value::p, P, ptr(), qual(), RIGHT, root(), type::size, tree::sym, tree(), tree::type, type::type, typeerror(), value::u, U, tree::u, unqual, tree::v, voidptype, and voidtype.
Referenced by cast(), expr2(), tracevalue(), and value().
Symbol constant (Type , Value)
References symbol::addressed, table::all, table::buckets, CONSTANTS, interface::defsymbol, eqtype(), equalp, h, HASHSIZE, INT, IR, entry::link, entry::name, NEW0, type::op, PERM, entry::sym, type::sym, entry::type, value::u, type::u, unqual, and vtoa().
Referenced by cvtconst(), intconst(), listnodes(), mkstr(), and primary().
Tree constexpr (int)
References expr1(), and needconst.
Referenced by intexpr(), and statement().
Tree consttree (unsigned int, Type)
References atop(), cnsttree(), isarray, and isint.
Referenced by bbincr(), cast(), cond(), condtree(), field(), genconst(), initvalue(), postfix(), primary(), tracecall(), tracevalue(), unary(), and value().
Tree cvtconst (Tree)
References atop(), symbol::c, constant(), genident(), GLOBAL, idtree(), isarray, NULL, simplify(), tree::sym, tree::type, symbol::u, tree::u, and tree::v.
Referenced by genconst(), and listnodes().
void deallocate (unsigned a)
References freeblocks, NELEMS, block::next, and NULL.
Referenced by initializer(), main(), program(), statement(), and walk().
void defglobal (Symbol , int)
References symbol::defined, interface::export, interface::global, IR, symbol::sclass, symbol::seg, swtoseg(), and symbol::u.
Referenced by bbcall(), bbfunc(), bbvars(), dcllocal(), doconst(), doglobal(), emitcode(), initglobal(), and tracecall().
void definelab (int)
References code, cp, findlabel(), code::forest, node::kids, code::kind, symbol::l, newnode(), code::next, NULL, node::op, P, code::prev, symbol::ref, specific, node::syms, code::u, symbol::u, V, and walk().
Referenced by dostmt(), forstmt(), funcdefn(), ifstmt(), statement(), stmtlabel(), swcode(), swstmt(), and whilestmt().
void definept (Coordinate *)
References apply(), code, cp, code::Defpoint, events, findcount(), code::Gen, glevel, identifiers, listnodes(), locus(), n, ncalled, npoints, NULL, code::point, Events::points, reachable(), refinc, src, and code::u.
Referenced by compound(), dcllocal(), dostmt(), forstmt(), ifstmt(), statement(), swstmt(), and whilestmt().
void defpointer (Symbol)
References interface::defaddress, interface::defconst, IR, P, symbol::ref, type::size, and voidptype.
Referenced by bbcall(), bbfunc(), and bbvars().
Type deref (Type)
References error(), isenum, isptr, type::type, and unqual.
Referenced by field(), and rvalue().
void emitcode (void)
References code::begin, code::block, bp, CODE, codehead, cp, interface::defaddress, defglobal(), interface::emit, equated(), errcnt, code::forest, glevel, IR, code::kind, LIT, LOCAL, code::next, NULL, code::point, src, interface::stabblock, interface::stabline, interface::stabsym, code::swtch, swtoseg(), typestab(), code::u, and code::var.
Referenced by function().
void enterscope (void)
References level, LOCAL, and tempid.
Referenced by compound(), dclr1(), and funcdefn().
Type enumdcl (void)
References Aflag, type::align, append(), symbol::defined, error(), FUNC, gettok(), ID, identifiers, symbol::idlist, install(), intexpr(), inttype, level, symbol::limits, LOCAL, lookup(), ltov(), newstruct(), NULL, type::op, PERM, s, symbol::sclass, symbol::scope, type::size, symbol::src, src, type::sym, t, test(), token, tsym, symbol::type, type::type, types, symbol::u, type::u, use(), symbol::value, warning(), and xref.
Referenced by specifier().
Tree eqtree (int , Tree , Tree)
References cast(), cmptree(), eqtree, eqtype(), inttype, isfunc, isnullptr(), isptr, isvoidptr, mkop, simplify(), tree::type, type::type, unqual, and unsignedptr.
int eqtype (Type , Type , int)
References eqtype(), type::f, INT, isenum, NULL, type::op, promote(), type::size, type::type, type::u, unqual, and variadic().
Referenced by assign(), compatible(), condtree(), constant(), dclglobal(), dcllocal(), eqtree(), eqtype(), funcdefn(), and primary().
void equatelab (Symbol , Symbol)
References symbol::l, NULL, and symbol::u.
Referenced by branch(), labelnode(), and listnodes().
void error (const char * , ...)
References errcnt, errlimit, error(), firstfile, fprint(), NULL, src, and vfprint().
void exitscope (void)
References Aflag, table::all, GLOBAL, table::level, level, n, table::previous, rmtypes(), symbol::scope, symbol::up, and warning().
Referenced by compound(), decl(), exitparams(), and funcdefn().
void expect (int tok)
References error(), fprint(), gettok(), printtoken(), and t.
Referenced by call(), compound(), dcllocal(), dclr1(), dostmt(), expr1(), forstmt(), funcdefn(), ifstmt(), parameters(), statement(), stmtlabel(), swstmt(), test(), unary(), and whilestmt().
Tree expr (int)
References expr1(), gettok(), ID, pointer(), RIGHT, root(), t, test(), tree(), tree::type, and value().
Referenced by conditional(), expr0(), expr2(), postfix(), statement(), swstmt(), and unary().
Tree expr0 (int)
References expr(), and root().
Referenced by forstmt(), and statement().
Tree expr1 (int)
References ASGN, asgntree, expect(), expr1(), expr2(), gettok(), ID, incr(), op, oper, prec, t, test(), and value().
Referenced by call(), constexpr(), dcllocal(), dclparam(), expr(), expr1(), initializer(), and initvalue().
int fatal (const char * , const char * , int)
References errcnt, error(), EXIT_FAILURE, fprint(), and print().
Tree field (Tree , const char *)
References ADD, type::align, array(), consttree(), deref(), error(), tree::field, FIELD, fieldref(), inttype, isaddrop, isarray, isconst, isptr, isvolatile, field::lsb, NULL, nullcall(), field::offset, tree::op, P, ptr(), qual(), retype(), rvalue(), simplify(), type::size, tree(), tree::type, type::type, field::type, tree::u, unqual, and YYcheck.
Referenced by Field_AutoComplete(), Hist_Add(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), postfix(), and tracevalue().
Field fieldlist (Type)
References symbol::s, type::sym, symbol::u, and type::u.
Field fieldref (const char * name, Type ty)
References isfield(), lookup(), src, unqual, use(), and xref.
Referenced by field().
void fillbuf (void)
References bsize, buffer, BUFSIZE, cp, error(), EXIT_FAILURE, fread(), limit, line, MAXLINE, n, and s.
void finalize (void)
References checkref(), CONSTANTS, constants, doconst(), doextern(), doglobal(), externals, GLOBAL, identifiers, and NULL.
Referenced by main().
int findcount (char * , int , int)
References count::count, file::count, file::counts, findfile(), and file::name.
Referenced by definept().
int findfunc (char * , char *)
References findfile(), file::funcs, func::link, func::name, and file::name.
Referenced by funcdefn().
Symbol findlabel (int)
References table::all, table::buckets, interface::defsymbol, FUNC, h, HASHSIZE, IR, LABELS, entry::link, entry::name, NEW0, stringd(), and entry::sym.
Referenced by branch(), caselabel(), definelab(), dostmt(), forstmt(), ifstmt(), jump(), labelnode(), listnodes(), statement(), swstmt(), and whilestmt().
Symbol findtype (Type)
References table::buckets, HASHSIZE, identifiers, entry::link, NULL, table::previous, entry::sym, and entry::type.
Referenced by outtype(), and typestring().
void foreach (Table , int , void(*)(Symbol, void *) , void *)
References table::all, cl, table::level, table::previous, symbol::scope, symbol::src, src, and symbol::up.
void fprint (FILE * f, const char * fmt, ...)
References NULL, and vfprint().
Referenced by dumpcover(), dumpregs(), dumprule(), dumptree(), error(), expect(), fatal(), genreload(), genspill(), getrule(), linearize(), main(), main_init(), outtype(), printdag(), printdecl(), printnode(), printtoken(), printtree1(), printtype(), prtype(), prune(), ralloc(), reduce(), reprune(), requate(), rewrite(), rtarget(), and skipto().
Type freturn (Type)
References error(), inttype, isfunc, and type::type.
Referenced by call(), compound(), funcdefn(), printproto(), retcode(), statement(), tracefinis(), tracereturn(), and vcall().
Type ftype (Type , Type)
References append(), func(), ltov(), NULL, and PERM.
Referenced by bbentry(), bbexit(), and trace_init().
Type func (Type , Type * , int)
References error(), type::f, isarray, isfunc, NULL, type(), and type::u.
Referenced by attach(), compose(), dclr(), ftype(), funcdefn(), main_init(), postfix(), primary(), printproto(), and type_init().
char* funcname (Tree)
References isaddrop, symbol::name, tree::op, stringf(), tree::sym, and tree::u.
Referenced by call(), conditional(), and expr2().
void gencode (Symbol [], Symbol [])
References code::addr, interface::address, asgn(), assignargs, code::begin, code::block, interface::blockbeg, interface::blockend, CODE, codehead, codelist, cp, errcnt, fixup(), code::forest, interface::gen, glevel, idtree(), IR, code::kind, interface::local, code::next, NULL, code::point, code::prev, prune(), prunetemps, symbol::sclass, src, interface::stabsym, swtoseg(), symbol::type, code::u, code::var, walk(), and interface::wants_dag.
Referenced by function().
Symbol genident (int , Type , int)
References interface::defsymbol, FUNC, symbol::generated, genlabel(), GLOBAL, IR, LOCAL, symbol::name, NEW0, PERM, symbol::sclass, symbol::scope, stringd(), and symbol::type.
Referenced by bbcall(), bbentry(), bbvars(), compound(), condtree(), cvtconst(), dcllocal(), funcdefn(), mkstr(), primary(), prof_init(), retcode(), swcode(), swstmt(), and tracecall().
int genlabel (int)
References n.
Referenced by addrtree(), defsymbol(), funcdefn(), genident(), listnodes(), newfield(), newstruct(), statement(), stmtlabel(), and swcode().
int getchr (void)
References BLANK, cp, limit, NEWLINE, and nextline().
Referenced by compound(), primary(), scon(), and statement().
int gettok (void)
References array(), BLANK, symbol::c, cbuf, CHAR, chartype, cp, cput(), DEREF, DIGIT, doubletype, EQL, error(), extend, EXTERN, fcon(), coord::file, file, fillbuf(), floattype, GEQ, icon(), ID, identifiers, INT, inttype, LEQ, LETTER, limit, line, lineno, LONG, lookup(), MAXLINE, MAXTOKEN, n, NEQ, NEWLINE, nextline(), NULL, type::op, OROR, s, scon(), SIZEOF, stringn(), type::sym, token, tval, symbol::type, symbol::u, type::u, voidtype, warning(), wcbuf, wcput(), widechar, coord::x, and coord::y.
Referenced by call(), dclglobal(), dcllocal(), dclparam(), dclr1(), decl(), dostmt(), enumdcl(), expect(), expr(), expr1(), expr2(), expr3(), forstmt(), ifstmt(), initarray(), initchar(), initend(), initfields(), initglobal(), initializer(), initstruct(), main(), parameters(), postfix(), pragma(), primary(), program(), skipto(), specifier(), statement(), stmtlabel(), structdcl(), swstmt(), test(), unary(), and whilestmt().
int hascall (Tree p)
References CALL, DIV, hascall(), I, IR, tree::kids, MOD, interface::mulops_calls, tree::op, and U.
Referenced by call(), hascall(), and vcall().
int hasproto (Type)
References type::f, hasproto(), INT, type::op, type::type, and type::u.
Referenced by decl(), hasproto(), parameters(), and typename().
Tree idtree (Symbol)
References symbol::alias, EXTERN, funcptype, GLOBAL, IR, isarray, isfunc, isptr, isstruct, mkop, NULL, op, PARAM, ptr(), symbol::ref, refinc, rvalue(), symbol::sclass, symbol::scope, tree::sym, tree(), symbol::type, tree::type, symbol::u, tree::u, unqual, voidptype, and interface::wants_argb.
Referenced by addrof(), asgn(), asgntree(), bbcall(), bbentry(), bbexit(), bbincr(), call(), calltree(), cmp(), cvtconst(), dcllocal(), gencode(), listnodes(), nullcall(), nullcheck(), primary(), retcode(), swcode(), tracecall(), tracefinis(), tracereturn(), tracevalue(), and vcall().
Tree incr (int , Tree , Tree)
References ASGN, asgntree, oper, and optree.
Referenced by bbincr(), expr1(), inflate_table(), postfix(), tracecall(), and unary().
void init (int , char * [])
References input_init(), main_init(), prof_init(), trace_init(), and type_init().
Referenced by main(), SV_RankBegin(), SV_RankUserCreate(), SV_RankUserLogin(), SV_RankUserValidate(), and UI_HeadCountByTeam().
Type initializer (Type , int)
References array(), assign(), symbol::c, cast(), CHAR, chartype, deallocate(), interface::defconst, interface::defstring, error(), expr1(), genconst(), gettok(), initarray(), initchar(), initend(), initializer(), initstruct(), IR, isarray, ischar, isscalar, isstruct, isunion, n, needconst, NULL, type::op, pointer(), s, symbol::s, type::size, skipto(), interface::space, STMT, type::sym, t, test(), tsym, symbol::type, tree::type, type::type, value::u, symbol::u, type::u, unqual, and widechar.
Referenced by dclglobal(), initarray(), initglobal(), initializer(), and initstruct().
void input_init (int , char * [])
References bsize, buffer, cp, fillbuf(), limit, lineno, main_init(), MAXLINE, nextline(), and NULL.
Referenced by init().
Symbol install (const char * , Table * , int , int)
References table::all, table::buckets, h, HASHSIZE, table::level, level, entry::link, long(), entry::name, NEW0, entry::sym, and table.
Symbol intconst (int)
References constant(), value::i, inttype, and n.
Referenced by asgnnode(), docall(), and listnodes().
int intexpr (int , int)
References cast(), constexpr(), error(), value::i, I, inttype, n, needconst, tree::op, U, tree::u, and tree::v.
Referenced by dclr1(), and enumdcl().
int iscallb (Tree)
References B, CALL, isaddrop, tree::kids, tree::op, RIGHT, tree::sym, symbol::temporary, and tree::u.
Referenced by asgntree(), call(), and retcode().
int ispow2 (unsigned long u)
References n.
Referenced by simplify().
Node jump (int)
References findlabel(), newnode(), NULL, symbol::ref, ttob(), V, and voidptype.
Referenced by branch(), and listnodes().
int length (List list)
References list::link, list(), and n.
Referenced by AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_WriteAASLump(), CG_ParticleBloodCloud(), CG_ParticleDust(), CM_LoadMap(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), Com_TruncateLongString(), compound(), CON_LogWrite(), CRC_ContinueProcessString(), CRC_ProcessString(), dst_new(), emit_dac(), emit_dht(), FS_ListFilteredFiles(), get_dac(), get_dht(), get_dqt(), get_dri(), get_interesting_appn(), get_sof(), get_sos(), LoadFile(), LoadFileBlock(), LoadScriptFile(), LoadScriptMemory(), LoadSourceFile(), ltov(), MSG_Init(), MSG_InitOOB(), MSG_WriteData(), NET_QueuePacket(), NET_SendLoopPacket(), Netchan_Transmit(), parameters(), QCopyFile(), R_LoadBMP(), R_LoadTGA(), R_SetupFrustum(), Rankings_DrawName(), Rankings_DrawPassword(), Reached_Train(), S_CodecUtilOpen(), save_marker(), skip_variable(), SP_func_pendulum(), StripExtension(), StripFilename(), Sys_AnsiColorPrint(), Sys_AppendToExecBuffer(), Sys_Basename(), Sys_Dirname(), Sys_TempPath(), TryLoadFile(), VectorNormalize(), and VectorNormalize2().
Node listnodes (Tree e, int tlab, int flab)
References ADD, addlocal(), symbol::addressed, type::align, AND, ASGN, B, bittree, CALL, cast(), cfunc, cnsttree(), symbol::computed, COND, constant(), cvtconst(), depth, DIV, EQ, equatelab(), errcnt, symbol::f, tree::field, FIELD, fieldleft, fieldmask, fieldright, fieldsize, findlabel(), firstarg, FUNC, genlabel(), GT, value::i, I, idtree(), intconst(), inttype, IR, isaddrop, isfunc, isint, isptr, isstruct, isvolatile, jump(), tree::kids, kill(), labelnode(), interface::left_to_right, list(), listnodes(), LSH, LT, lvalue(), MOD, interface::mulops_calls, n, NEW0, newnode(), node(), tree::node, NOT, NULL, tree::op, op, node::op, opkind, optype, OR, P, symbol::ref, reset(), RIGHT, RSH, rvalue(), shtree(), type::size, sizeop, SUB, tree::sym, type::sym, node::syms, symbol::temporary, tree(), ttob(), symbol::type, tree::type, type::type, field::type, value::u, U, symbol::u, tree::u, type::u, unlist(), unqual, unsignedtype, V, tree::v, voidptype, and interface::wants_callb.
Referenced by cmp(), definept(), listnodes(), statement(), and walk().
void locus (Table tp, Coordinate * cp)
References allsymbols(), and append().
Referenced by definept().
Symbol lookup (const char * , Table)
References table::buckets, h, HASHSIZE, entry::link, long(), entry::name, NULL, table::previous, and entry::sym.
void* ltov (List * list, unsigned a)
References array(), freenodes, length(), list::link, list(), newarray(), NULL, and list::x.
Referenced by bbvars(), compose(), compound(), enumdcl(), ftype(), main(), parameters(), and printproto().
Tree lvalue (Tree)
References error(), tree::kids, tree::op, tree::type, unqual, value(), voidtype, and warning().
Referenced by asgntree(), call(), listnodes(), and unary().
int main (int , char * [])
References ac, alloc(), append(), apply(), av, b, bindings, callsys(), cflag, ckreach(), compose(), concat(), deallocate(), Eflag, emitclosure(), emitdefs(), emitheader(), emitkids(), emitlabel(), emitnts(), emitrule(), emitstring(), emitstruct(), Events::end, errcnt, error(), events, exists(), EXIT_FAILURE, coord::file, finalize(), first(), firstfile, fprint(), gettok(), glevel, GLOBAL, help(), identifiers, ilist, include, infp, init(), initinputs(), interrupt(), binding::ir, ld, lineno, block::link, list::link, nonterm::link, loci, ltov(), memlist, nonterm::name, binding::name, nrules, ntnumber, NULL, opt(), option(), outfile, outfp, PERM, prefix, interface::progbeg, interface::progend, progname, program(), nonterm::reached, rm(), nonterm::rules, s, Sflag, src, interface::stabend, interface::stabinit, list::str, stringf(), suffix(), suffixes, symbols, t, tempdir, Tflag, types, typestab(), UpdatePaths(), coord::x, xref, coord::y, yyerror(), and yyparse().
void main_init (int , char * [])
References Aflag, comment, interface::defsymbol, density, errlimit, EXIT_FAILURE, EXTERN, fclose(), fprint(), func(), glevel, GLOBAL, globals, infile, install(), interface::left_to_right, interface::little_endian, interface::mulops_calls, NULL, outfile, PERM, Pflag, rcsid, symbol::sclass, stabend(), interface::stabend, stabline(), interface::stabline, string(), stringn(), symbol::type, type_init(), voidptype, interface::wants_argb, interface::wants_callb, interface::wants_dag, wflag, and xref.
Referenced by init(), and input_init().
Symbol mkstr (char *)
References array(), symbol::c, chartype, constant(), genident(), GLOBAL, NULL, value::p, symbol::type, and symbol::u.
Referenced by bbcall(), bbfile(), bbfunc(), nullcall(), nullcheck(), tracefinis(), and tracevalue().
Symbol mksymbol (int , const char * , Type)
References symbol::defined, interface::defsymbol, EXTERN, GLOBAL, install(), IR, symbol::name, NEW0, PERM, symbol::sclass, symbol::scope, string(), and symbol::type.
Referenced by bbcall(), bbentry(), bbexit(), and trace_init().
void* newarray (unsigned long m, unsigned long n, unsigned a)
References allocate().
Referenced by apoint(), caselabel(), funcdefn(), ltov(), parameters(), swgen(), and swstmt().
Field newfield (char * , Type , Type)
References error(), genlabel(), install(), level, field::link, entry::name, field::name, NEW0, NULL, PERM, symbol::s, src, stringd(), type::sym, table, field::type, symbol::u, type::u, and xref.
Node newnode (int op, Node left, Node right, Symbol p)
References dagnode(), and dag::node.
Referenced by asgnnode(), definelab(), genreload(), genspill(), jump(), labelnode(), listnodes(), replace(), rtarget(), tmpnode(), and visit().
Type newstruct (int , char *)
References symbol::defined, error(), genlabel(), install(), level, lookup(), maxlevel, symbol::name, NULL, type::op, PARAM, PERM, symbol::scope, symbol::src, src, stringd(), type(), symbol::type, and types.
Referenced by enumdcl(), and structdcl().
Symbol newtemp (int , int , int)
References btot(), symbol::defined, IR, interface::local, and temporary().
Referenced by spillr().
void nextline (void)
References cp, fillbuf(), limit, line, lineno, nextline(), and resynch().
Referenced by getchr(), gettok(), input_init(), nextline(), resynch(), and scon().
int nodeid (Tree)
References ids, nid, nodeid::node, and nodeid::printed.
Referenced by printdag(), printdag1(), printnode(), and printtree1().
Tree nullcall (Type , Symbol , Tree , Tree)
References type::align, atop(), symbol::c, cnsttree(), idtree(), inttype, isarray, lineno, mkstr(), NULL, nullcall(), pointer(), retype(), type::size, tree::type, unqual, vcall(), and voidptype.
Referenced by field(), nullcall(), and nullcheck().
char* opname (int)
References AND, FIELD, NELEMS, opindex, opnames, opsize, optype, stringd(), stringf(), and suffixes.
Referenced by dumptree(), emit(), getrule(), printnode(), and printtree1().
void outtype (Type , FILE *)
References type::f, findtype(), fprint(), INT, isarray, symbol::name, type::op, type::size, symbol::src, type::sym, type::type, and type::u.
Referenced by vfprint().
Tree pointer (Tree)
References atop(), isarray, isfunc, ptr(), retype(), and tree::type.
Referenced by asgntree(), bbentry(), bbexit(), bbincr(), call(), cond(), expr(), expr2(), expr3(), initializer(), nullcall(), nullcheck(), postfix(), retcode(), swcode(), tracefinis(), tracevalue(), unary(), and vcall().
void print (const char * , ...)
References NULL, and vfprint().
void printdag (Node , int)
References fprint(), node::link, nodeid(), NULL, printdag1(), and printed().
void printdecl (Symbol p, Type ty)
References EXTERN, fprint(), symbol::name, symbol::sclass, and typestring().
Referenced by doglobal(), and printproto().
int* printed (int)
References ids, nid, and nodeid::printed.
Referenced by opt(), printdag(), printdag1(), printtree(), and printtree1().
void printproto (Symbol p, Symbol args[])
References append(), type::f, freturn(), func(), ltov(), PERM, printdecl(), symbol::type, and type::u.
Referenced by funcdefn().
void printtree (Tree , int)
References printed(), printtree1(), and void().
void printtype (Type , int)
References fprint(), and prtype().
int process (char *)
References compare(), file::count, file::counts, fclose(), filelist, fp, gather(), int(), file::link, and NULL.
void program (void)
References CHAR, dclglobal(), deallocate(), decl(), error(), FUNC, gettok(), glevel, GLOBAL, ID, kind, level, n, STMT, t, warning(), and xref.
Referenced by main().
Type promote (Type)
References doubletype, INT, inttype, type::op, type::size, unqual, and unsignedtype.
Referenced by call(), calltree(), eqtype(), funcdefn(), retcode(), shtree(), swstmt(), tracevalue(), and unary().
Type ptr (Type)
References metrics::align, IR, interface::ptrmetric, metrics::size, and type().
Referenced by AAS_CalculateAreaTravelTimes(), AAS_CreateReversedReachability(), AAS_InitClusterAreaCache(), Assemble(), atop(), bbcall(), BotCheckConsoleMessages(), BotExpandChatMessage(), BotImport_GetMemory(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadRandomStrings(), BotLoadSynonyms(), BotVoiceChatCommand(), call(), CG_DrawField(), CG_HeadModelVoiceChats(), CG_ParseVoiceChats(), Com_Filter(), Com_QueueEvent(), compose(), compound(), condtree(), create_colormap(), dclparam(), dclr(), DoSyscall(), EasyClientName(), expand_right_edge(), field(), funcdefn(), GetClearedHunkMemory(), GetClearedMemory(), GetHunkMemory(), GetMemory(), GLimp_HaveExtension(), idtree(), jitter_buffer_ctl(), jzero_far(), lsp_quant(), lsp_weight_quant(), nb_decoder_ctl(), nb_encoder_ctl(), nb_mode_query(), PC_ConvertPath(), pitch_gain_search_3tap_vq(), pointer(), postfix(), prescan_quantize(), R_Init(), RB_IQMSurfaceAnim(), resampler_basic_direct_double(), resampler_basic_direct_single(), resampler_basic_interpolate_double(), resampler_basic_interpolate_single(), sb_decoder_ctl(), sb_encoder_ctl(), speex_preprocess_ctl(), trace_init(), type_init(), UI_StartServerRefresh(), unary(), UnifyWhiteSpaces(), VM_CallCompiled(), wb_mode_query(), and Z_LogZoneHeap().
Type qual (int , Type)
References type::align, error(), isarray, isconst, isfunc, isqual, isvolatile, NULL, type::op, qual(), type::size, type(), type::type, and warning().
Referenced by compose(), condtree(), dcllocal(), dclr(), field(), qual(), sb_encoder_ctl(), specifier(), speex_std_vbr_quality_request_handler(), trace_init(), unary(), and vbr_analysis().
int reachable (int)
References cp, if(), code::Jump, code::kind, code::Label, code::prev, code::Start, and code::Switch.
Referenced by code(), compound(), and definept().
Symbol relocate (const char * name, Table src, Table dst)
References table::all, table::buckets, h, HASHSIZE, entry::link, long(), entry::sym, and symbol::up.
Referenced by dclglobal().
void retcode (Tree)
References addlocal(), apply(), ASGN, asgn(), asgntree, assign(), B, CALL, cast(), cfunc, symbol::computed, error(), events, freturn(), symbol::generated, genident(), idtree(), iscallb(), isfloat, isptr, tree::kids, level, localaddr(), mkop, symbol::name, NULL, PARAM, pointer(), promote(), Events::returns, retv, RIGHT, rvalue(), symbol::scope, tree(), symbol::type, tree::type, walk(), and warning().
Referenced by funcdefn(), jpeg_consume_input(), jpeg_read_header(), LOCAL(), and statement().
Tree retype (Tree p, Type ty)
References tree::kids, tree::node, tree::op, tree(), tree::type, and tree::u.
Referenced by asgntree(), cast(), field(), initvalue(), nullcall(), pointer(), postfix(), simplify(), swstmt(), tracevalue(), and unary().
Tree rightkid (Tree p)
References tree::kids, tree::op, and RIGHT.
Referenced by cond(), postfix(), unary(), and value().
void rmtypes (int)
References entry::link, maxlevel, NELEMS, NULL, type::op, symbol::scope, type::sym, entry::type, typetable, and type::u.
Referenced by exitscope().
Tree root (Tree)
References root1(), and warn.
Referenced by addrof(), call(), condtree(), dcllocal(), expr(), expr0(), inflate_table(), and simplify().
Tree rvalue (Tree)
References deref(), mkop, NULL, tree(), tree::type, and unqual.
Referenced by bbincr(), field(), idtree(), listnodes(), postfix(), retcode(), swcode(), tracevalue(), and unary().
Tree shtree (int , Tree , Tree)
References cast(), inttype, isint, promote(), simplify(), tree::type, and typeerror().
Referenced by asgntree(), and listnodes().
Type signedint (Type)
References INT, NULL, type::op, and xx.
Referenced by cast(), cmp(), and swcode().
Tree simplify (int , Type , Tree , Tree)
References ADD, addd(), addi(), addrtree(), AND, bittree, cast(), cfoldcnst, cnsttree(), commute, cond(), value::d, DIV, divd(), divi(), EQ, eqtree, explicitCast, extend, F, foldaddp, foldcnst, geu, GT, value::i, I, idempotent, identity, inttype, isaddrop, ispow2(), tree::kids, symbol::limits, longtype, LSH, LT, mkop, MOD, muld(), muli(), n, needconst, NOT, NULL, ones, tree::op, optype, OR, value::p, P, retype(), RIGHT, root(), RSH, sfoldcnst, simplify(), type::size, SUB, subd(), subi(), type::sym, tree(), tree::type, value::u, U, symbol::u, tree::u, type::u, ufoldcnst, tree::v, warning(), xcvtcnst, xfoldcnst, and zerofield.
Referenced by bittree(), cast(), cmptree(), cvtconst(), eqtree(), field(), foldcond(), shtree(), simplify(), and unary().
void skipto (int tok, char set[])
References error(), fprint(), gettok(), kind, n, printtoken(), s, and t.
Referenced by initializer(), parameters(), statement(), and test().
void statement (int , Swtch , int)
References Aflag, branch(), caselabel(), cast(), cfunc, compound(), constexpr(), deallocate(), definelab(), definept(), swtch::deflab, dostmt(), error(), expect(), expr(), expr0(), extend, symbol::f, findlabel(), forstmt(), freturn(), FUNC, genlabel(), getchr(), gettok(), glevel, value::i, ID, ifstmt(), install(), isint, kind, symbol::l, swtch::lab, LABELS, listnodes(), lookup(), needconst, nodecount, NULL, tree::op, type::op, refinc, retcode(), symbol::scope, skipto(), symbol::src, src, statement(), STMT, stmtlabel(), swstmt(), swtch::sym, t, test(), symbol::type, tree::type, value::u, symbol::u, tree::u, use(), tree::v, voidtype, walk(), warning(), and whilestmt().
Referenced by compound(), dostmt(), forstmt(), ifstmt(), statement(), swstmt(), and whilestmt().
char* string (const char * str)
References s, and stringn().
Referenced by CG_DrawStringExt(), CL_Netchan_Decode(), CL_Netchan_Encode(), GametypeBits(), main_init(), mksymbol(), MSG_ReadBigString(), MSG_ReadString(), MSG_ReadStringLine(), NET_OutOfBandData(), PC_AddBuiltinDefines(), Q_CleanStr(), Q_CountChar(), Q_PrintStrlen(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), stringf(), SV_ExpandNewlines(), SV_Netchan_Decode(), SV_Netchan_Encode(), and VM_Indent().
char* stringd (long n)
References long(), m, n, s, string::str, and stringn().
Referenced by addrtree(), defsymbol(), findlabel(), genident(), mkauto(), newfield(), newstruct(), opname(), parameters(), temporary(), and vtoa().
char* stringf (const char * , ...)
References NULL, string(), strsave(), and vfprint().
Referenced by address(), callsys(), computekids(), dclparam(), defsymbol(), emitcost(), emittest(), funcname(), function(), local(), main(), mkreg(), opname(), rule(), tempname(), typestring(), and vtoa().
char* stringn (const char * str, int len)
References allocate(), buckets, end, h, string::len, string::link, n, NELEMS, NEW, PERM, scatter, and string::str.
Referenced by gettok(), main_init(), primary(), resynch(), string(), and stringd().
void swcode (Swtch , int * , int , int)
Referenced by swcode(), and swgen().
void swgen (Swtch)
References buckets, den, density, FUNC, n, swtch::ncases, newarray(), swcode(), and swtch::values.
Referenced by swstmt().
void swtoseg (int)
References curseg, IR, and interface::segment.
Referenced by dclglobal(), defglobal(), emitcode(), funcdefn(), and gencode().
Table table (Table , int)
References table::all, FUNC, table::level, level, and NEW0.
Symbol temporary (int , Type)
References FUNC, symbol::generated, level, LOCAL, symbol::name, NEW0, symbol::sclass, symbol::scope, stringd(), tempid, symbol::temporary, and symbol::type.
Referenced by call(), newtemp(), nullcheck(), and visit().
void test (int tok, char set[])
References expect(), gettok(), skipto(), and t.
Referenced by CG_TargetCommand_f(), decl(), enumdcl(), expr(), expr1(), forstmt(), initend(), initializer(), statement(), structdcl(), UI_BotSelectMenu_Default(), and UI_hasSkinForBase().
Tree texpr (Tree(*)(int) , int , int)
References where.
Referenced by forstmt(), and whilestmt().
Tree tree (int , Type , Tree , Tree)
References tree::kids, NEW0, tree::op, op, right, type(), tree::type, and where.
int ttob (Type)
References INT, type::op, type::size, sizeop, ttob(), and type::type.
Referenced by asgnnode(), defsymbol(), jump(), listnodes(), tmpnode(), and ttob().
void type_init (int , char * [])
References symbol::addressed, type::align, func(), GLOBAL, install(), INT, IR, symbol::limits, NULL, ones, metrics::outofline, PERM, ptr(), interface::ptrmetric, metrics::size, type::size, type::sym, type(), symbol::type, types, symbol::u, type::u, interface::unsigned_char, unsignedshort, voidtype, and xx.
Referenced by init(), main_init(), prof_init(), and trace_init().
void typeerror (int , Tree , Tree)
References ADD, AND, ASGN, COND, DIV, EQ, error(), GT, LSH, LT, MOD, symbol::name, NOT, op, ops, OR, RSH, SUB, and tree::type.
Referenced by asgntree(), bittree(), cmptree(), condtree(), shtree(), and unary().
Type typename (void)
References Aflag, dclr(), hasproto(), NULL, specifier(), t, and warning().
char* typestring (Type ty, char * id)
References type::f, findtype(), INT, isarray, ischar, isfunc, isptr, symbol::name, NULL, type::op, type::size, stringf(), type::sym, type::type, typestring(), type::u, and warning().
Referenced by funcdefn(), printdecl(), tracevalue(), and typestring().
void use (Symbol p, Coordinate src)
References append(), cp, NEW, PERM, src, and symbol::uses.
Referenced by enumdcl(), fieldref(), funcdefn(), pragma(), primary(), specifier(), statement(), and structdcl().
Tree value (Tree)
References AND, condtree(), consttree(), EQ, GT, inttype, LT, NOT, tree::op, op, OR, rightkid(), tree::type, and voidtype.
Referenced by addrof(), BotInitLevelItems(), call(), cast(), CG_DrawBlueScore(), CG_DrawCTFPowerUp(), CG_DrawField(), CG_DrawHoldableItem(), CG_DrawInformation(), CG_DrawPickupItem(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawRedScore(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHealth(), CG_DrawStatusBar(), Characteristic_BFloat(), Characteristic_BInteger(), CL_JoystickEvent(), ClientConnect(), Com_Clamp(), Com_QueueEvent(), Cvar_Validate(), DefineSymbol(), expr(), expr1(), G_AddRandomBot(), G_GetBotInfoByName(), G_InitSessionData(), G_SpawnGEntityFromSpawnVars(), Info_NextPair(), Info_Print(), Info_RemoveKey(), Info_RemoveKey_Big(), Item_Slider_HandleKey(), Item_Slider_ThumbPosition(), Item_YesNo_Paint(), Key_GetBindingBuf(), LibVarStringValue(), lvalue(), MSG_ReadBits(), MSG_WriteBits(), nullcheck(), ParseHex(), PC_Directive_elif(), PC_Directive_eval(), PC_Directive_evalfloat(), PC_Directive_if(), PC_DollarDirective_evalfloat(), PC_DollarDirective_evalint(), SCR_DebugGraph(), ScriptSkipTo(), Scroll_Slider_ThumbFunc(), UI_BotName_HandleKey(), UI_ClampCvar(), UI_DrawBotName(), UI_DrawTeamMember(), UI_GetArenaInfoByNumber(), UI_GetBotInfoByName(), UI_OwnerDrawWidth(), and VM_LoadSymbols().
int variadic (Type)
References type::f, isfunc, type::u, and voidtype.
Referenced by eqtype(), funcdefn(), and tracecall().
Tree vcall (Symbol func, Type ty, ...)
References args, calltree(), symbol::f, freturn(), hascall(), idtree(), isfunc, mkop, NULL, pointer(), RIGHT, tree(), symbol::type, and voidtype.
Referenced by bbentry(), bbexit(), nullcall(), and nullcheck().
void vfprint (FILE * , char * , const char * , va_list)
References coord::file, fmt, format(), n, outd(), outs(), outtype(), outu(), s, t, void(), voidtype, and coord::y.
Referenced by error(), fprint(), print(), stringf(), and warning().
char* vtoa (Type , Value)
References chartype, value::d, value::g, value::i, INT, NULL, type::op, value::p, signedchar, stringd(), stringf(), type::type, value::u, unqual, and unsignedchar.
Referenced by constant(), printtoken(), and printtree1().
void walk (Tree e, int tlab, int flab)
References code, deallocate(), IR, node::link, list(), listnodes(), NULL, reset(), STMT, undag(), and interface::wants_dag.
Referenced by bbentry(), bbexit(), branch(), compound(), dcllocal(), definelab(), dostmt(), forstmt(), funcdefn(), gencode(), ifstmt(), retcode(), statement(), swcode(), swstmt(), tracefinis(), and whilestmt().
void warning (const char * , ...)
References errcnt, error(), NULL, vfprint(), and wflag.
Referenced by addd(), addi(), array(), assign(), backslash(), branch(), call(), caselabel(), cast(), checkref(), code(), conditional(), cput(), dclglobal(), dcllocal(), dclparam(), dclr(), decl(), divd(), divi(), enumdcl(), exitscope(), expr2(), fcon(), funcdefn(), gettok(), icon(), initfields(), lvalue(), muld(), muli(), parameters(), primary(), program(), qual(), resynch(), retcode(), root1(), scon(), simplify(), specifier(), statement(), swcode(), swstmt(), typename(), typestring(), and unary().
Variable Documentation
int Aflag
Referenced by array(), assign(), call(), caselabel(), checkref(), conditional(), dclglobal(), dclr(), decl(), enumdcl(), exitscope(), expr2(), funcdefn(), main_init(), parameters(), primary(), resynch(), scon(), specifier(), statement(), typename(), and unary().
int assignargs
Referenced by gencode().
Binding bindings[]
Referenced by main().
Symbol cfunc
Referenced by bbcall(), listnodes(), primary(), retcode(), and statement().
Type charptype
Referenced by bbvars(), funcdefn(), and tracefinis().
Type chartype
Referenced by gettok(), initializer(), mkstr(), trace_init(), tracevalue(), and vtoa().
struct code codehead
Referenced by emitcode(), funcdefn(), and gencode().
Code codelist
Referenced by code(), funcdefn(), gencode(), and swstmt().
Table constants
Referenced by finalize().
unsigned char* cp
Referenced by addrtree(), AngleVectors(), backslash(), BotGetMessageTeamGoal(), BotMatch_CheckPoint(), branch(), code(), compound(), definelab(), definept(), emitcode(), error(), expr3(), fcon(), fillbuf(), funcdefn(), gencode(), getchr(), gettok(), icon(), input_init(), lcc_getopt(), lookup(), nextline(), ppnumber(), pragma(), printtoken(), reachable(), resynch(), scon(), stabline(), stringify(), and use().
float density
Referenced by main_init(), and swgen().
Type doubletype
Referenced by binary(), fcon(), gettok(), and promote().
int errcnt
int errlimit
Referenced by error(), and main_init().
Events events
Referenced by call(), compound(), CON_Input(), definept(), expr2(), expr3(), funcdefn(), main(), prof_init(), retcode(), and trace_init().
int explicitCast
Referenced by simplify(), and unary().
Table externals
Referenced by dclglobal(), dcllocal(), finalize(), and primary().
char* file
Referenced by _MULT16_16(), _MULT16_32_QX(), acaller(), BotSetupChatAI(), BotSetupWeaponAI(), fopen_file_func(), FS_FOpenFileReadDir(), FS_ForceFlush(), FS_GetModList(), FS_Seek(), gather(), gettok(), Hunk_AllocDebug(), PC_Directive_include(), resynch(), S_WAV_CodecLoad(), and Z_TagMallocDebug().
char* firstfile
Referenced by error(), main(), progbeg(), and resynch().
Type floattype
Referenced by binary(), fcon(), and gettok().
Type funcptype
Referenced by idtree().
int glevel
Referenced by dclglobal(), definept(), doglobal(), emitcode(), funcdefn(), gencode(), main(), main_init(), program(), and statement().
Table globals
Referenced by dclglobal(), dcllocal(), and main_init().
Table identifiers
Referenced by compound(), dclglobal(), dcllocal(), dclparam(), decl(), definept(), enumdcl(), finalize(), findtype(), funcdefn(), gettok(), main(), and primary().
Type inttype
Referenced by asgntree(), assign(), bbentry(), bbexit(), bbincr(), binary(), bittree(), call(), cast(), cmptree(), cond(), condtree(), enumdcl(), eqtree(), field(), freturn(), funcdefn(), genconst(), gettok(), icon(), initchar(), initfields(), initvalue(), intconst(), intexpr(), listnodes(), nullcall(), nullcheck(), parameters(), postfix(), primary(), promote(), shtree(), simplify(), specifier(), super(), swstmt(), trace_init(), tracecall(), tracevalue(), unary(), and value().
Interface* IR
Referenced by address(), addrtree(), bbcall(), bbfunc(), bbincr(), bbvars(), blkcopy(), blkunroll(), call(), compound(), constant(), dclglobal(), dcllocal(), defglobal(), defpointer(), doconst(), doextern(), doglobal(), dumpcover(), dumprule(), emitasm(), emitcode(), emitSymbol(), emitSymRef(), findlabel(), funcdefn(), function(), gen(), gencode(), genconst(), genident(), genreload(), genspill(), getrule(), hascall(), idtree(), initchar(), initfields(), initializer(), initstruct(), listnodes(), local(), mksymbol(), newtemp(), prelabel(), primary(), prof_init(), prune(), ptr(), ralloc(), reduce(), reprune(), rewrite(), swcode(), swtoseg(), trace_init(), tracecall(), type_init(), typestab(), and walk().
char kind[]
Referenced by code(), compound(), dclr1(), decl(), forstmt(), funcdefn(), parameters(), program(), skipto(), and statement().
Table labels
Referenced by funcdefn().
int level
unsigned char* limit
Referenced by alloc(), CG_DrawCapFragLimit(), CG_Text_Paint_Limit(), fillbuf(), getchr(), gettok(), input_init(), nextline(), resynch(), save_marker(), scon(), Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), and Text_Width().
char* line
Referenced by __attribute__(), _MULT16_16(), _MULT16_32_QX(), AAS_DebugLine(), AAS_DrawPlaneCross(), AAS_PermanentLine(), AAS_ShowArea(), AAS_ShowBoundingBox(), assemble_line(), BotExportTest(), Cbuf_Execute(), CG_Tracer(), Con_Dump_f(), CON_Show(), ConcatArgs(), fillbuf(), gettok(), Hunk_AllocDebug(), nextline(), resynch(), and Z_TagMallocDebug().
int lineno
Referenced by funcdefn(), gettok(), input_init(), main(), nextline(), nullcall(), nullcheck(), and resynch().
List loci
Referenced by main().
Type longdouble
Referenced by binary(), cast(), fcon(), specifier(), and tracevalue().
Type longlong
Referenced by binary(), and specifier().
Type longtype
Referenced by binary(), icon(), simplify(), specifier(), and tracevalue().
int ncalled
Referenced by definept(), funcdefn(), and prof_init().
int needconst
Referenced by constexpr(), initializer(), initvalue(), intexpr(), nullcheck(), root1(), simplify(), and statement().
int nodecount
Referenced by kill(), node(), reset(), and statement().
int npoints
Referenced by bbincr(), bbvars(), definept(), and gather().
Tree(* optree[])(int, Tree, Tree)
Referenced by bbincr(), cast(), cond(), expr3(), incr(), postfix(), swcode(), and tracevalue().
int Pflag
Referenced by doglobal(), funcdefn(), and main_init().
int prunetemps
Referenced by gencode().
float refinc
Referenced by definept(), dostmt(), forstmt(), funcdefn(), idtree(), ifstmt(), statement(), swstmt(), and whilestmt().
Symbol retv
Referenced by funcdefn(), and retcode().
Type shorttype
Referenced by specifier().
Type signedchar
Referenced by specifier(), tracevalue(), and vtoa().
Type signedptr
Coordinate src
Referenced by builtin(), cast(), CopyLongSwap(), CopyShortSwap(), dcllocal(), decl(), DefaultExtension(), definept(), emitcode(), emitSymbol(), enumdcl(), error(), expr2(), expr3(), ExtractFileBase(), ExtractFileExtension(), ExtractFilePath(), fieldref(), fill_input_buffer(), foreach(), forstmt(), funcdefn(), gencode(), get_byte(), getrule(), init_source(), jpeg_mem_src(), jpeg_stdio_src(), main(), newfield(), newstruct(), parameters(), PC_DefineFromString(), postfix(), pragma(), primary(), R_LevelShot(), R_LoadTGA(), requate(), S_Base_RawSamples(), skip_input_data(), specifier(), statement(), stmtlabel(), structdcl(), Sys_ConcatenateFileLists(), use(), and whilestmt().
Table stmtlabs
Referenced by funcdefn().
List symbols
Referenced by main(), and VM_LoadSymbols().
int t
Referenced by AAS_AreaRouteToGoalArea(), AAS_FallDamageDistance(), AAS_FallDelta(), AAS_HorizontalVelocityForJump(), AAS_MaxJumpDistance(), AAS_NearestHideArea(), AAS_PortalMaxTravelTime(), AAS_RandomGoalArea(), AAS_UpdateAreaRoutingCache(), AAS_UpdatePortalRoutingCache(), AddSkyPolygon(), basename(), bbcall(), bbincr(), BotAlternateRoute(), BotCheckInitialChatIntegrety(), BotChooseInitialChatMessage(), BotChooseLTGItem(), BotChooseNBGItem(), BotDumpInitialChat(), BotGetActivateGoal(), BotGetReachabilityToGoal(), BotGetTime(), BotNumInitialChats(), call(), CG_AddFragment(), CG_AddMarks(), CG_AddPainTwitch(), CG_BloodTrail(), CG_CalcViewValues(), CG_DamageBlendBlob(), CG_DrawAreaPowerUp(), CG_DrawAttacker(), CG_DrawFPS(), CG_DrawPowerups(), CG_FadeColor(), CG_PlaceString(), CG_Player(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_RocketTrail(), CG_ShaderStateChanged(), CG_TeamBase(), CG_Trace(), CL_SystemInfoChanged(), ClientTimerActions(), CM_DistanceFromLineSquared(), CM_PositionTestInPatchCollide(), CM_TestBoxInBrush(), CM_TraceThroughBrush(), CM_TraceThroughPatchCollide(), CM_TransformedBoxTrace(), Com_RealTime(), compound(), dclglobal(), dcllocal(), dclparam(), dclr1(), decl(), DoRailCore(), dostmt(), DrawSkyBox(), DrawSkySide(), enumdcl(), expect(), expr(), expr1(), expr2(), expr3(), FillCloudBox(), FillCloudySkySide(), forstmt(), funcdefn(), G_Damage(), G_ProcessIPBans(), G_UseTargets(), get_bit(), getop(), HSVtoRGB(), Huff_getBit(), I_FloatTime(), ifstmt(), initarray(), initchar(), initend(), initfields(), initglobal(), initializer(), initstruct(), kf_bfly2(), kf_bfly_generic(), labelhash_free(), main(), MakeSkyVec(), MD5Update(), parameters(), PC_CopyToken(), PC_DefineFromString(), PC_Directive_define(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ExpandBuiltinDefine(), PC_ExpandDefine(), PC_FreeDefine(), PC_ReadDefineParms(), PC_ReadSourceToken(), PC_StringizeTokens(), PC_UnreadSourceToken(), PM_CrashLand(), postfix(), pragma(), primary(), print(), printtoken(), progend(), program(), puttokens(), Q_rsqrt(), R_InitSkyTexCoords(), R_SubdividePatchToGrid(), RaySphereIntersections(), RB_CalcFogTexCoords(), RB_CalcTransformTexCoords(), RB_CalcTurbulentTexCoords(), SendPendingPredictableEvents(), setup_kwtab(), skipto(), specifier(), split_cb_search_shape_sign(), split_cb_search_shape_sign_N1(), spx_fft(), spx_fft_destroy(), spx_ifft(), SquareRootFloat(), statement(), stmtlabel(), stringify(), structdcl(), suffix(), swstmt(), test(), tree(), typename(), unary(), Use_Target_Give(), vfprint(), and whilestmt().
char* token
Referenced by AAS_ParseBSPEntities(), Alias_Parse(), Asset_Parse(), BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), CG_HeadModelVoiceChats(), CG_NewParticleArea(), CG_ParseAnimationFile(), CG_ParseVoiceChats(), Character_Parse(), CL_LoadConsoleHistory(), COM_MatchToken(), dclr1(), enumdcl(), FindShaderInShaderText(), Float_Parse(), FreeSource(), G_ParseInfos(), GameType_Parse(), GametypeBits(), gettok(), IN_IsConsoleKey(), Int_Parse(), Item_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), Load_Menu(), LoadItemConfig(), LoadWeaponConfig(), MapList_Parse(), Menu_Parse(), Parse1DMatrix(), ParseDeform(), ParseShader(), ParseSkyParms(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), ParseVector(), ParseWaveForm(), PC_CopyDefine(), PC_Directive_define(), PC_Directive_error(), PC_Directive_eval(), PC_Directive_evalfloat(), PC_Directive_if_def(), PC_Directive_include(), PC_Directive_pragma(), PC_Directive_undef(), PC_DollarDirective_evalfloat(), PC_DollarDirective_evalint(), PC_DollarEvaluate(), PC_Evaluate(), PC_ExpandBuiltinDefine(), PC_ExpandDefine(), PC_ExpectTokenString(), PC_Float_Parse(), PC_Int_Parse(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadTokenHandle(), PC_Script_Parse(), PC_SkipUntilString(), PC_String_Parse(), PS_ExpectTokenString(), PS_SkipUntilString(), R_LoadEntities(), RE_RegisterSkin(), ReadChar(), ReadFuzzySeperators_r(), ReadNumber(), ReadSignedFloat(), ReadSignedInt(), ReadString(), ReadStructure(), ReadValue(), ReadWeightConfig(), ScanAndLoadShaderFiles(), SkipBracedSection(), String_Parse(), structdcl(), Team_Parse(), UI_LoadMenus(), UI_ParseAnimationFile(), UI_ParseGameInfo(), UI_ParseInfos(), UI_ParseMenu(), UI_ParseTeamInfo(), UnreadSignToken(), and VM_LoadSymbols().
Symbol tsym
Referenced by compound(), dclr1(), decl(), enumdcl(), funcdefn(), initializer(), parameters(), pragma(), primary(), printtoken(), specifier(), structdcl(), and unary().
Table types
Referenced by compound(), enumdcl(), main(), newstruct(), structdcl(), type_init(), and xxinit().
Type unsignedchar
Referenced by initfields(), specifier(), tracevalue(), and vtoa().
Type unsignedlong
Referenced by binary(), cast(), icon(), specifier(), swcode(), tracevalue(), and unary().
Type unsignedlonglong
Referenced by binary(), and specifier().
Type unsignedptr
Referenced by cmptree(), eqtree(), super(), and swcode().
Type unsignedshort
Referenced by specifier(), and type_init().
Type unsignedtype
Referenced by bbcall(), bbfunc(), bbvars(), binary(), cast(), cmptree(), icon(), initfields(), listnodes(), prof_init(), promote(), specifier(), super(), and tracevalue().
Type voidptype
Referenced by asgnnode(), bbcall(), bbentry(), bbexit(), condtree(), defpointer(), idtree(), jump(), listnodes(), main_init(), nullcall(), nullcheck(), swcode(), and tmpnode().
Type voidtype
Referenced by asgntree(), bbentry(), bbexit(), call(), condtree(), funcdefn(), gettok(), lvalue(), nullcheck(), parameters(), postfix(), root1(), statement(), swcode(), tracereturn(), type_init(), unary(), value(), variadic(), vcall(), and vfprint().
int wflag
Referenced by main_init(), and warning().
int where
Referenced by texpr(), and tree().
Type widechar
Referenced by backslash(), doconst(), gettok(), initializer(), and printtoken().
int xref
Referenced by enumdcl(), fieldref(), funcdefn(), main(), main_init(), newfield(), primary(), program(), and structdcl().
Symbol YYcheck
Referenced by field().
Symbol YYnull
Referenced by nullcheck(), postfix(), and unary().