ioquake3: code/libspeex/cb_search.c File Reference
cb_search.c File Reference
#include "cb_search.h"
#include "filters.h"
#include "stack_alloc.h"
#include "vq.h"
#include "arch.h"
#include "math_approx.h"
#include "os_support.h"
Functions
static void compute_weighted_codebook (const signed char *shape_cb, const spx_word16_t *r, spx_word16_t *resp, spx_word16_t *resp2, spx_word32_t *E, int shape_cb_size, int subvect_size, char *stack)
static void target_update (spx_word16_t *t, spx_word16_t g, spx_word16_t *r, int len)
static void split_cb_search_shape_sign_N1 (spx_word16_t target[], spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], const void *par, int p, int nsf, spx_sig_t *exc, spx_word16_t *r, SpeexBits *bits, char *stack, int update_target)
void split_cb_search_shape_sign (spx_word16_t target[], spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], const void *par, int p, int nsf, spx_sig_t *exc, spx_word16_t *r, SpeexBits *bits, char *stack, int complexity, int update_target)
void split_cb_shape_sign_unquant (spx_sig_t *exc, const void *par, int nsf, SpeexBits *bits, char *stack, spx_int32_t *seed)
void noise_codebook_quant (spx_word16_t target[], spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], const void *par, int p, int nsf, spx_sig_t *exc, spx_word16_t *r, SpeexBits *bits, char *stack, int complexity, int update_target)
void noise_codebook_unquant (spx_sig_t *exc, const void *par, int nsf, SpeexBits *bits, char *stack, spx_int32_t *seed)
Function Documentation
static void compute_weighted_codebook (const signed char * shape_cb, const spx_word16_t * r, spx_word16_t * resp, spx_word16_t * resp2, spx_word32_t * E, int shape_cb_size, int subvect_size, char * stack) [static]
References ALLOC, EXTRACT16, MAC16_16, SHR32, and VARDECL.
Referenced by split_cb_search_shape_sign(), and split_cb_search_shape_sign_N1().
void noise_codebook_quant (spx_word16_t target[], spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], const void * par, int p, int nsf, spx_sig_t * exc, spx_word16_t * r, SpeexBits * bits, char * stack, int complexity, int update_target)
References ALLOC, EXTEND32, residue_percep_zero16(), SHL32, SPEEX_MEMSET, and VARDECL.
Referenced by nb_encode().
void noise_codebook_unquant (spx_sig_t * exc, const void * par, int nsf, SpeexBits * bits, char * stack, spx_int32_t * seed)
References EXTEND32, SHL32, and speex_rand().
void split_cb_search_shape_sign (spx_word16_t target[], spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], const void * par, int p, int nsf, spx_sig_t * exc, spx_word16_t * r, SpeexBits * bits, char * stack, int complexity, int update_target)
References ADD32, ALLOC, compute_weighted_codebook(), EXTEND32, EXTRACT16, split_cb_params::have_sign, m, MAC16_16, N, n, split_cb_params::nb_subvect, NEG32, PSHR16, PSHR32, r2, split_cb_params::shape_bits, split_cb_params::shape_cb, SHL32, SHR32, speex_bits_pack(), SPEEX_COPY, split_cb_search_shape_sign_N1(), SUB16, split_cb_params::subvect_size, syn_percep_zero16(), t, target_update(), VARDECL, VERY_LARGE32, vq_nbest(), and vq_nbest_sign().
static void split_cb_search_shape_sign_N1 (spx_word16_t target[], spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], const void * par, int p, int nsf, spx_sig_t * exc, spx_word16_t * r, SpeexBits * bits, char * stack, int update_target) [static]
References ADD16, ADD32, ALLOC, compute_weighted_codebook(), EXTEND32, EXTRACT16, split_cb_params::have_sign, m, split_cb_params::nb_subvect, NEG32, PSHR16, PSHR32, r2, split_cb_params::shape_bits, split_cb_params::shape_cb, SHL32, speex_bits_pack(), SPEEX_COPY, SUB16, split_cb_params::subvect_size, syn_percep_zero16(), t, target_update(), VARDECL, vq_nbest(), and vq_nbest_sign().
Referenced by split_cb_search_shape_sign().
void split_cb_shape_sign_unquant (spx_sig_t * exc, const void * par, int nsf, SpeexBits * bits, char * stack, spx_int32_t * seed)
References ALLOC, EXTEND32, split_cb_params::have_sign, split_cb_params::nb_subvect, NEG32, s, split_cb_params::shape_bits, split_cb_params::shape_cb, SHL32, speex_bits_unpack_unsigned(), split_cb_params::subvect_size, and VARDECL.
static void target_update (spx_word16_t * t, spx_word16_t g, spx_word16_t * r, int len) [inline, static]
References MULT16_16, n, PSHR32, and SUB16.
Referenced by split_cb_search_shape_sign(), and split_cb_search_shape_sign_N1().