ioquake3: code/cgame/cg_playerstate.c File Reference
cg_playerstate.c File Reference
#include "cg_local.h"
Functions
void CG_CheckAmmo (void)
void CG_DamageFeedback (int yawByte, int pitchByte, int damage)
void CG_Respawn (void)
void CG_CheckPlayerstateEvents (playerState_t *ps, playerState_t *ops)
void CG_CheckChangedPredictableEvents (playerState_t *ps)
static void pushReward (sfxHandle_t sfx, qhandle_t shader, int rewardCount)
void CG_CheckLocalSounds (playerState_t *ps, playerState_t *ops)
void CG_TransitionPlayerState (playerState_t *ps, playerState_t *ops)
Variables
char * eventnames []
Function Documentation
void CG_CheckAmmo (void)
References playerState_s::ammo, cg, cgs, CHAN_LOCAL_SOUND, cg_t::lowAmmoWarning, cgs_t::media, cgMedia_t::noAmmoSound, snapshot_t::ps, cg_t::snap, STAT_WEAPONS, playerState_s::stats, trap_S_StartLocalSound(), WP_GRENADE_LAUNCHER, WP_MACHINEGUN, WP_NUM_WEAPONS, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by CG_TransitionPlayerState().
void CG_CheckChangedPredictableEvents (playerState_t * ps)
References cg, CG_EntityEvent(), CG_Printf(), cg_showmiss, centity_s::currentState, entityState_s::event, entityState_s::eventParm, playerState_s::eventParms, playerState_s::events, cg_t::eventSequence, playerState_s::eventSequence, vmCvar_t::integer, centity_s::lerpOrigin, MAX_PREDICTED_EVENTS, MAX_PS_EVENTS, cg_t::predictableEvents, and cg_t::predictedPlayerEntity.
void CG_CheckLocalSounds (playerState_t * ps, playerState_t * ops)
References cgMedia_t::assistSound, cgMedia_t::captureAwardSound, cg, CG_AddBufferedSound(), CG_PainEvent(), cgs, CHAN_ANNOUNCER, CHAN_LOCAL_SOUND, cgMedia_t::defendSound, cgMedia_t::deniedSound, cgMedia_t::excellentSound, cgMedia_t::firstExcellentSound, cgMedia_t::firstHumiliationSound, cgMedia_t::firstImpressiveSound, cgMedia_t::fiveMinuteSound, cgs_t::fraglimit, cg_t::fraglimitWarnings, cgs_t::gametype, GT_CTF, GT_TEAM, cgMedia_t::hitSound, cgMedia_t::hitSoundHighArmor, cgMedia_t::hitSoundLowArmor, cgMedia_t::hitTeamSound, cgMedia_t::holyShitSound, cgMedia_t::humiliationSound, cgMedia_t::impressiveSound, cg_t::intermissionStarted, cgs_t::levelStartTime, cgMedia_t::lostLeadSound, cgMedia_t::medalAssist, cgMedia_t::medalCapture, cgMedia_t::medalDefend, cgMedia_t::medalExcellent, cgMedia_t::medalGauntlet, cgMedia_t::medalImpressive, cgs_t::media, cgMedia_t::oneFragSound, cgMedia_t::oneMinuteSound, PERS_ASSIST_COUNT, PERS_ATTACKEE_ARMOR, PERS_CAPTURES, PERS_DEFEND_COUNT, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_HITS, PERS_IMPRESSIVE_COUNT, PERS_PLAYEREVENTS, PERS_RANK, PERS_TEAM, playerState_s::persistant, PLAYEREVENT_DENIEDREWARD, PLAYEREVENT_GAUNTLETREWARD, PLAYEREVENT_HOLYSHIT, playerState_s::powerups, cg_t::predictedPlayerEntity, pushReward(), PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, qfalse, qtrue, RANK_TIED_FLAG, cgs_t::scores1, cgs_t::scores2, STAT_HEALTH, playerState_s::stats, cgMedia_t::suddenDeathSound, cgMedia_t::takenLeadSound, cgMedia_t::threeFragSound, cgMedia_t::tiedLeadSound, cg_t::time, cgs_t::timelimit, cg_t::timelimitWarnings, trap_S_StartLocalSound(), cgMedia_t::twoFragSound, cg_t::warmup, and cgMedia_t::youHaveFlagSound.
Referenced by CG_TransitionPlayerState().
void CG_CheckPlayerstateEvents (playerState_t * ps, playerState_t * ops)
References cg, cg_entities, CG_EntityEvent(), playerState_s::clientNum, centity_s::currentState, entityState_s::event, entityState_s::eventParm, playerState_s::eventParms, playerState_s::events, cg_t::eventSequence, playerState_s::eventSequence, playerState_s::externalEvent, playerState_s::externalEventParm, centity_s::lerpOrigin, MAX_PREDICTED_EVENTS, MAX_PS_EVENTS, cg_t::predictableEvents, and cg_t::predictedPlayerEntity.
Referenced by CG_TransitionPlayerState().
void CG_DamageFeedback (int yawByte, int pitchByte, int damage)
References AngleVectors(), cg_t::attackerTime, cg, DAMAGE_TIME, cg_t::damageTime, cg_t::damageValue, cg_t::damageX, cg_t::damageY, DotProduct, NULL, PITCH, snapshot_t::ps, cg_t::refdef, ROLL, snapshot_t::serverTime, cg_t::snap, STAT_HEALTH, playerState_s::stats, cg_t::time, up, cg_t::v_dmg_pitch, cg_t::v_dmg_roll, cg_t::v_dmg_time, vec3_origin, VectorLength(), VectorSubtract, refdef_t::viewaxis, and YAW.
Referenced by CG_TransitionPlayerState().
void CG_Respawn (void)
References cg, snapshot_t::ps, qtrue, cg_t::snap, cg_t::thisFrameTeleport, cg_t::time, playerState_s::weapon, cg_t::weaponSelect, and cg_t::weaponSelectTime.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionPlayerState().
void CG_TransitionPlayerState (playerState_t * ps, playerState_t * ops)
References cg, CG_CheckAmmo(), CG_CheckLocalSounds(), CG_CheckPlayerstateEvents(), CG_DamageFeedback(), CG_Respawn(), playerState_s::clientNum, playerState_s::damageCount, playerState_s::damageEvent, playerState_s::damagePitch, playerState_s::damageYaw, cg_t::duckChange, cg_t::duckTime, cg_t::mapRestart, PERS_SPAWN_COUNT, PERS_TEAM, playerState_s::persistant, PM_INTERMISSION, playerState_s::pm_type, snapshot_t::ps, qfalse, qtrue, cg_t::snap, TEAM_SPECTATOR, cg_t::thisFrameTeleport, cg_t::time, and playerState_s::viewheight.
Referenced by CG_PredictPlayerState(), and CG_TransitionSnapshot().
static void pushReward (sfxHandle_t sfx, qhandle_t shader, int rewardCount) [static]
References cg, MAX_REWARDSTACK, cg_t::rewardCount, cg_t::rewardShader, cg_t::rewardSound, cg_t::rewardStack, and shader.
Referenced by CG_CheckLocalSounds().
Variable Documentation
char* eventnames[]
Referenced by BG_AddPredictableEventToPlayerstate().