ioquake3: code/cgame/cg_weapons.c File Reference
cg_weapons.c File Reference
#include "cg_local.h"
Defines
#define RADIUS 4
#define ROTATION 1
#define SPACING 5
#define SPIN_SPEED 0.9
#define COAST_TIME 1000
Functions
static void CG_MachineGunEjectBrass (centity_t *cent)
static void CG_ShotgunEjectBrass (centity_t *cent)
void CG_RailTrail (clientInfo_t *ci, vec3_t start, vec3_t end)
static void CG_RocketTrail (centity_t *ent, const weaponInfo_t *wi)
static void CG_PlasmaTrail (centity_t *cent, const weaponInfo_t *wi)
void CG_GrappleTrail (centity_t *ent, const weaponInfo_t *wi)
static void CG_GrenadeTrail (centity_t *ent, const weaponInfo_t *wi)
void CG_RegisterWeapon (int weaponNum)
void CG_RegisterItemVisuals (int itemNum)
static int CG_MapTorsoToWeaponFrame (clientInfo_t *ci, int frame)
static void CG_CalculateWeaponPosition (vec3_t origin, vec3_t angles)
static void CG_LightningBolt (centity_t *cent, vec3_t origin)
static float CG_MachinegunSpinAngle (centity_t *cent)
static void CG_AddWeaponWithPowerups (refEntity_t *gun, int powerups)
void CG_AddPlayerWeapon (refEntity_t *parent, playerState_t *ps, centity_t *cent, int team)
void CG_AddViewWeapon (playerState_t *ps)
void CG_DrawWeaponSelect (void)
static qboolean CG_WeaponSelectable (int i)
void CG_NextWeapon_f (void)
void CG_PrevWeapon_f (void)
void CG_Weapon_f (void)
void CG_OutOfAmmoChange (void)
void CG_FireWeapon (centity_t *cent)
void CG_MissileHitWall (int weapon, int clientNum, vec3_t origin, vec3_t dir, impactSound_t soundType)
void CG_MissileHitPlayer (int weapon, vec3_t origin, vec3_t dir, int entityNum)
static void CG_ShotgunPellet (vec3_t start, vec3_t end, int skipNum)
static void CG_ShotgunPattern (vec3_t origin, vec3_t origin2, int seed, int otherEntNum)
void CG_ShotgunFire (entityState_t *es)
void CG_Tracer (vec3_t source, vec3_t dest)
static qboolean CG_CalcMuzzlePoint (int entityNum, vec3_t muzzle)
void CG_Bullet (vec3_t end, int sourceEntityNum, vec3_t normal, qboolean flesh, int fleshEntityNum)
Define Documentation
#define COAST_TIME 1000
Referenced by CG_MachinegunSpinAngle().
#define RADIUS 4
Referenced by CG_RailTrail().
#define ROTATION 1
Referenced by CG_RailTrail().
#define SPACING 5
Referenced by CG_RailTrail().
#define SPIN_SPEED 0.9
Referenced by CG_MachinegunSpinAngle().
Function Documentation
void CG_AddPlayerWeapon (refEntity_t * parent, playerState_t * ps, centity_t * cent, int team)
References AnglesToAxis(), refEntity_t::axis, orientation_t::axis, refEntity_t::backlerp, weaponInfo_s::barrelModel, Byte4Copy, clientInfo_t::c1RGBA, cg, CG_AddWeaponWithPowerups(), cg_drawGun, cg_entities, CG_LightningBolt(), CG_MachinegunSpinAngle(), CG_PositionRotatedEntityOnTag(), CG_RegisterWeapon(), cg_weapons, cgs, cgs_t::clientinfo, playerState_s::clientNum, entityState_s::clientNum, clientInfo_t::color1, crandom, centity_s::currentState, EF_FIRING, entityState_s::eFlags, weaponInfo_s::firingSound, weaponInfo_s::flashDlightColor, weaponInfo_s::flashModel, refEntity_t::frame, refEntity_t::hModel, vmCvar_t::integer, centity_s::lerpOrigin, refEntity_t::lightingOrigin, playerEntity_t::lightningFiring, MatrixMultiply(), MUZZLE_FLASH_TIME, centity_s::muzzleFlashTime, entityState_s::number, refEntity_t::oldframe, refEntity_t::origin, orientation_t::origin, centity_s::pe, PITCH, entityState_s::powerups, cg_t::predictedPlayerState, qfalse, qtrue, playerEntity_t::railFireTime, weaponInfo_s::readySound, refEntity_t::renderfx, cg_t::renderingThirdPerson, ROLL, refEntity_t::shaderRGBA, refEntity_t::shadowPlane, cg_t::time, trap_R_AddLightToScene(), trap_R_AddRefEntityToScene(), trap_R_LerpTag(), trap_S_AddLoopingSound(), vec3_origin, VectorCopy, VectorMA(), entityState_s::weapon, weaponInfo_s::weaponModel, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_LIGHTNING, WP_RAILGUN, and YAW.
Referenced by CG_AddViewWeapon(), and CG_Player().
void CG_AddViewWeapon (playerState_t * ps)
References AnglesToAxis(), refEntity_t::axis, refEntity_t::backlerp, lerpFrame_t::backlerp, cg, CG_AddPlayerWeapon(), CG_CalculateWeaponPosition(), cg_drawGun, cg_entities, cg_fov, cg_gun_frame, cg_gun_x, cg_gun_y, cg_gun_z, CG_LightningBolt(), CG_MapTorsoToWeaponFrame(), CG_RegisterWeapon(), cg_weapons, cgs, cgs_t::clientinfo, playerState_s::clientNum, entityState_s::clientNum, centity_s::currentState, EF_FIRING, playerState_s::eFlags, refEntity_t::frame, lerpFrame_t::frame, weaponInfo_s::handsModel, refEntity_t::hModel, vmCvar_t::integer, refEntity_t::oldframe, lerpFrame_t::oldFrame, refEntity_t::origin, centity_s::pe, PERS_TEAM, playerState_s::persistant, PM_INTERMISSION, playerState_s::pm_type, cg_t::predictedPlayerEntity, cg_t::predictedPlayerState, cg_t::refdef, refEntity_t::renderfx, cg_t::renderingThirdPerson, RF_DEPTHHACK, RF_FIRST_PERSON, RF_MINLIGHT, TEAM_SPECTATOR, cg_t::testGun, playerEntity_t::torso, vmCvar_t::value, VectorCopy, VectorMA(), refdef_t::viewaxis, refdef_t::vieworg, and playerState_s::weapon.
Referenced by CG_DrawActiveFrame().
static void CG_AddWeaponWithPowerups (refEntity_t * gun, int powerups) [static]
References cgMedia_t::battleWeaponShader, cgs, refEntity_t::customShader, cgMedia_t::invisShader, cgs_t::media, PW_BATTLESUIT, PW_INVIS, PW_QUAD, cgMedia_t::quadWeaponShader, and trap_R_AddRefEntityToScene().
Referenced by CG_AddPlayerWeapon().
void CG_Bullet (vec3_t end, int sourceEntityNum, vec3_t normal, qboolean flesh, int fleshEntityNum)
References CG_Bleed(), CG_BubbleTrail(), CG_CalcMuzzlePoint(), CG_MissileHitWall(), CG_PointContents(), CG_Tracer(), cg_tracerChance, CONTENTS_WATER, trace_t::endpos, IMPACTSOUND_DEFAULT, NULL, random, start, trap_CM_BoxTrace(), vmCvar_t::value, and WP_MACHINEGUN.
Referenced by CG_EntityEvent().
static qboolean CG_CalcMuzzlePoint (int entityNum, vec3_t muzzle) [static]
References AngleVectors(), ANIM_TOGGLEBIT, entityState_s::apos, cg, cg_entities, playerState_s::clientNum, CROUCH_VIEWHEIGHT, centity_s::currentState, centity_s::currentValid, DEFAULT_VIEWHEIGHT, forward, LEGS_IDLECR, LEGS_WALKCR, entityState_s::legsAnim, NULL, playerState_s::origin, entityState_s::pos, snapshot_t::ps, qfalse, qtrue, cg_t::snap, trajectory_t::trBase, VectorCopy, VectorMA(), playerState_s::viewangles, and playerState_s::viewheight.
Referenced by CG_Bullet().
static void CG_CalculateWeaponPosition (vec3_t origin, vec3_t angles) [static]
References cg_t::bobcycle, cg_t::bobfracsin, cg, LAND_DEFLECT_TIME, LAND_RETURN_TIME, cg_t::landChange, cg_t::landTime, PITCH, cg_t::refdef, cg_t::refdefViewAngles, ROLL, STEP_TIME, cg_t::stepChange, cg_t::stepTime, cg_t::time, VectorCopy, refdef_t::vieworg, cg_t::xyspeed, and YAW.
Referenced by CG_AddViewWeapon().
void CG_DrawWeaponSelect (void)
References playerState_s::ammo, BIGCHAR_WIDTH, bits(), cg, CG_DrawBigStringColor(), CG_DrawPic(), CG_DrawStrlen(), CG_FadeColor(), CG_RegisterWeapon(), cg_weapons, cgs, count, weaponInfo_s::item, cg_t::itemPickupTime, MAX_WEAPONS, cgs_t::media, cgMedia_t::noammoShader, NULL, gitem_s::pickup_name, cg_t::predictedPlayerState, snapshot_t::ps, SCREEN_WIDTH, cgMedia_t::selectShader, cg_t::snap, STAT_HEALTH, STAT_WEAPONS, playerState_s::stats, trap_R_SetColor(), WEAPON_SELECT_TIME, cg_t::weaponSelect, and cg_t::weaponSelectTime.
Referenced by CG_Draw2D().
void CG_FireWeapon (centity_t * cent)
References cg, cg_brassTime, CG_Error(), cg_weapons, cgs, CHAN_ITEM, CHAN_WEAPON, centity_s::currentState, weaponInfo_s::ejectBrassFunc, weaponInfo_s::flashSound, vmCvar_t::integer, playerEntity_t::lightningFiring, cgs_t::media, centity_s::muzzleFlashTime, NULL, entityState_s::number, centity_s::pe, entityState_s::powerups, PW_QUAD, cgMedia_t::quadSound, playerEntity_t::railFireTime, cg_t::time, trap_S_StartSound(), entityState_s::weapon, WP_LIGHTNING, WP_NONE, WP_NUM_WEAPONS, and WP_RAILGUN.
Referenced by CG_EntityEvent().
void CG_GrappleTrail (centity_t * ent, const weaponInfo_t * wi)
References AngleVectors(), refEntity_t::axis, AxisClear(), BG_EvaluateTrajectory(), cg, cg_entities, cgs, centity_s::currentState, refEntity_t::customShader, Distance(), forward, centity_s::lerpAngles, centity_s::lerpOrigin, cgMedia_t::lightningShader, cgs_t::media, NULL, refEntity_t::oldorigin, refEntity_t::origin, entityState_s::otherEntityNum, entityState_s::pos, refEntity_t::reType, RT_LIGHTNING, refEntity_t::shaderRGBA, cg_t::time, centity_s::trailTime, trap_R_AddRefEntityToScene(), up, VectorCopy, and VectorMA().
Referenced by CG_Grapple(), and CG_RegisterWeapon().
static void CG_GrenadeTrail (centity_t * ent, const weaponInfo_t * wi) [static]
References CG_RocketTrail().
Referenced by CG_RegisterWeapon().
static void CG_LightningBolt (centity_t * cent, vec3_t origin) [static]
References AnglesToAxis(), AngleVectors(), ANIM_TOGGLEBIT, refEntity_t::axis, cg, CG_Trace(), cg_trueLightning, cgs, playerState_s::clientNum, CROUCH_VIEWHEIGHT, centity_s::currentState, refEntity_t::customShader, DEFAULT_VIEWHEIGHT, trace_t::endpos, forward, trace_t::fraction, refEntity_t::hModel, LEGS_IDLECR, LEGS_WALKCR, entityState_s::legsAnim, centity_s::lerpAngles, centity_s::lerpOrigin, LIGHTNING_RANGE, cgMedia_t::lightningExplosionModel, cgMedia_t::lightningShader, MASK_SHOT, cgs_t::media, NULL, entityState_s::number, refEntity_t::oldorigin, refEntity_t::origin, cg_t::predictedPlayerState, cg_t::refdefViewAngles, refEntity_t::reType, RT_LIGHTNING, trap_R_AddRefEntityToScene(), vmCvar_t::value, vec3_origin, VectorCopy, VectorMA(), VectorNormalize(), VectorSubtract, entityState_s::weapon, and WP_LIGHTNING.
Referenced by CG_AddPlayerWeapon(), and CG_AddViewWeapon().
static void CG_MachineGunEjectBrass (centity_t * cent) [static]
References localEntity_s::angles, AnglesToAxis(), refEntity_t::axis, AxisCopy(), axisDefault, localEntity_s::bounceFactor, cg, CG_AllocLocalEntity(), cg_brassTime, CG_PointContents(), cgs, CONTENTS_WATER, crandom, localEntity_s::endTime, refEntity_t::hModel, vmCvar_t::integer, LE_FRAGMENT, localEntity_s::leBounceSoundType, LEBS_BRASS, LEF_TUMBLE, localEntity_s::leFlags, localEntity_s::leMarkType, LEMT_NONE, centity_s::lerpAngles, centity_s::lerpOrigin, localEntity_s::leType, cgMedia_t::machinegunBrassModel, cgs_t::media, refEntity_t::origin, localEntity_s::pos, random, re, localEntity_s::refEntity, localEntity_s::startTime, cg_t::time, TR_GRAVITY, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorAdd, VectorCopy, and VectorScale.
Referenced by CG_RegisterWeapon().
static float CG_MachinegunSpinAngle (centity_t * cent) [static]
References AngleMod(), playerEntity_t::barrelAngle, playerEntity_t::barrelSpinning, playerEntity_t::barrelTime, cg, CHAN_WEAPON, COAST_TIME, centity_s::currentState, EF_FIRING, entityState_s::eFlags, NULL, entityState_s::number, centity_s::pe, qfalse, SPIN_SPEED, cg_t::time, trap_S_RegisterSound(), trap_S_StartSound(), and entityState_s::weapon.
Referenced by CG_AddPlayerWeapon().
static int CG_MapTorsoToWeaponFrame (clientInfo_t * ci, int frame) [static]
References clientInfo_t::animations, animation_s::firstFrame, TORSO_ATTACK, TORSO_ATTACK2, and TORSO_DROP.
Referenced by CG_AddViewWeapon().
void CG_MissileHitPlayer (int weapon, vec3_t origin, vec3_t dir, int entityNum)
References CG_Bleed(), CG_MissileHitWall(), IMPACTSOUND_FLESH, WP_BFG, WP_GRENADE_LAUNCHER, WP_PLASMAGUN, and WP_ROCKET_LAUNCHER.
Referenced by CG_EntityEvent(), and CG_ShotgunPellet().
void CG_MissileHitWall (int weapon, int clientNum, vec3_t origin, vec3_t dir, impactSound_t soundType)
References cgMedia_t::bfgExplosionShader, cgMedia_t::bulletExplosionShader, cgMedia_t::bulletFlashModel, cgMedia_t::bulletMarkShader, cgMedia_t::burnMarkShader, CG_ImpactMark(), CG_MakeExplosion(), cg_oldRocket, CG_ParticleExplosion(), cgs, CHAN_AUTO, cgs_t::clientinfo, localEntity_s::color, clientInfo_t::color1, cgMedia_t::dishFlashModel, cgMedia_t::energyMarkShader, ENTITYNUM_WORLD, cgMedia_t::grenadeExplosionShader, cgMedia_t::holeMarkShader, IMPACTSOUND_FLESH, IMPACTSOUND_METAL, vmCvar_t::integer, localEntity_s::light, localEntity_s::lightColor, cgs_t::media, cgMedia_t::plasmaExplosionShader, qfalse, qtrue, cgMedia_t::railExplosionShader, random, localEntity_s::refEntity, cgMedia_t::ringFlashModel, cgMedia_t::rocketExplosionShader, cgMedia_t::sfx_lghit1, cgMedia_t::sfx_lghit2, cgMedia_t::sfx_lghit3, cgMedia_t::sfx_plasmaexp, cgMedia_t::sfx_ric1, cgMedia_t::sfx_ric2, cgMedia_t::sfx_ric3, cgMedia_t::sfx_rockexp, shader, refEntity_t::shaderRGBA, trap_S_StartSound(), VectorCopy, VectorMA(), VectorScale, WP_BFG, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by CG_Bullet(), CG_EntityEvent(), CG_MissileHitPlayer(), and CG_ShotgunPellet().
void CG_NextWeapon_f (void)
References cg, CG_WeaponSelectable(), MAX_WEAPONS, playerState_s::pm_flags, PMF_FOLLOW, snapshot_t::ps, cg_t::snap, cg_t::time, cg_t::weaponSelect, cg_t::weaponSelectTime, and WP_GAUNTLET.
void CG_OutOfAmmoChange (void)
References cg, CG_WeaponSelectable(), MAX_WEAPONS, cg_t::time, cg_t::weaponSelect, and cg_t::weaponSelectTime.
Referenced by CG_EntityEvent().
static void CG_PlasmaTrail (centity_t * cent, const weaponInfo_t * wi) [static]
References localEntity_s::angles, AnglesToAxis(), refEntity_t::axis, AxisCopy(), axisDefault, BG_EvaluateTrajectory(), localEntity_s::bounceFactor, cg, CG_AllocLocalEntity(), cg_noProjectileTrail, cg_oldPlasma, CG_PointContents(), cgs, localEntity_s::color, CONTENTS_WATER, crandom, centity_s::currentState, refEntity_t::customShader, localEntity_s::endTime, weaponInfo_s::flashDlightColor, vmCvar_t::integer, LE_MOVE_SCALE_FADE, localEntity_s::leBounceSoundType, LEBS_NONE, LEF_TUMBLE, localEntity_s::leFlags, localEntity_s::leMarkType, LEMT_NONE, centity_s::lerpAngles, localEntity_s::leType, cgs_t::media, refEntity_t::origin, localEntity_s::pos, entityState_s::pos, refEntity_t::radius, cgMedia_t::railRingsShader, re, localEntity_s::refEntity, refEntity_t::reType, RT_SPRITE, refEntity_t::shaderRGBA, refEntity_t::shaderTime, localEntity_s::startTime, cg_t::time, TR_GRAVITY, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorAdd, VectorCopy, and VectorScale.
Referenced by CG_RegisterWeapon().
void CG_PrevWeapon_f (void)
References cg, CG_WeaponSelectable(), MAX_WEAPONS, playerState_s::pm_flags, PMF_FOLLOW, snapshot_t::ps, cg_t::snap, cg_t::time, cg_t::weaponSelect, cg_t::weaponSelectTime, and WP_GAUNTLET.
void CG_RailTrail (clientInfo_t * ci, vec3_t start, vec3_t end)
References refEntity_t::axis, AxisClear(), cg, CG_AllocLocalEntity(), cg_oldRail, cg_railTrailTime, cgs, localEntity_s::color, clientInfo_t::color1, clientInfo_t::color2, refEntity_t::customShader, localEntity_s::endTime, vmCvar_t::integer, LE_FADE_RGB, LE_MOVE_SCALE_FADE, LEF_PUFF_DONT_SCALE, localEntity_s::leFlags, localEntity_s::leType, localEntity_s::lifeRate, cgs_t::media, move(), refEntity_t::oldorigin, refEntity_t::origin, PerpendicularVector(), localEntity_s::pos, refEntity_t::radius, RADIUS, cgMedia_t::railCoreShader, cgMedia_t::railRingsShader, re, localEntity_s::refEntity, refEntity_t::reType, RotatePointAroundVector(), ROTATION, RT_RAIL_CORE, RT_SPRITE, refEntity_t::shaderRGBA, refEntity_t::shaderTime, SPACING, localEntity_s::startTime, cg_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, vmCvar_t::value, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, and VectorSubtract.
Referenced by CG_EntityEvent().
void CG_RegisterItemVisuals (int itemNum)
References bg_itemlist, bg_numItems, CG_Error(), cg_items, CG_RegisterWeapon(), gitem_s::giTag, gitem_s::giType, itemInfo_t::icon, gitem_s::icon, IT_ARMOR, IT_HEALTH, IT_HOLDABLE, IT_POWERUP, IT_WEAPON, itemInfo_t::models, qtrue, itemInfo_t::registered, trap_R_RegisterModel(), trap_R_RegisterShader(), and gitem_s::world_model.
Referenced by CG_DrawCTFPowerUp(), CG_DrawHoldableItem(), CG_DrawPickupItem(), CG_DrawPlayerItem(), CG_RegisterGraphics(), and CG_RegisterWeapon().
void CG_RegisterWeapon (int weaponNum)
References weaponInfo_s::ammoIcon, weaponInfo_s::ammoModel, weaponInfo_s::barrelModel, cgMedia_t::bfgExplosionShader, bg_itemlist, cgMedia_t::bulletExplosionShader, CG_Error(), CG_GrappleTrail(), CG_GrenadeTrail(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), CG_RegisterItemVisuals(), CG_RocketTrail(), CG_ShotgunEjectBrass(), cg_weapons, cgs, gitem_s::classname, COM_StripExtension(), weaponInfo_s::ejectBrassFunc, weaponInfo_s::firingSound, weaponInfo_s::flashDlightColor, weaponInfo_s::flashModel, weaponInfo_s::flashSound, gitem_s::giTag, gitem_s::giType, cgMedia_t::grenadeExplosionShader, weaponInfo_s::handsModel, gitem_s::icon, IT_AMMO, IT_WEAPON, weaponInfo_s::item, cgMedia_t::lightningExplosionModel, cgMedia_t::lightningShader, MAKERGB, MAX_QPATH, cgs_t::media, weaponInfo_s::missileDlight, weaponInfo_s::missileDlightColor, weaponInfo_s::missileModel, weaponInfo_s::missileSound, weaponInfo_s::missileTrailFunc, cgMedia_t::plasmaExplosionShader, qfalse, qtrue, cgMedia_t::railCoreShader, cgMedia_t::railExplosionShader, cgMedia_t::railRingsShader, weaponInfo_s::readySound, weaponInfo_s::registered, cgMedia_t::rocketExplosionShader, cgMedia_t::sfx_lghit1, cgMedia_t::sfx_lghit2, cgMedia_t::sfx_lghit3, weaponInfo_s::trailRadius, trap_R_ModelBounds(), trap_R_RegisterModel(), trap_R_RegisterShader(), trap_S_RegisterSound(), weaponInfo_s::weaponIcon, weaponInfo_s::weaponMidpoint, weaponInfo_s::weaponModel, weaponInfo_s::wiTrailTime, gitem_s::world_model, WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_DrawWeaponSelect(), and CG_RegisterItemVisuals().
static void CG_RocketTrail (centity_t * ent, const weaponInfo_t * wi) [static]
References BG_EvaluateTrajectory(), cg, CG_BubbleTrail(), cg_noProjectileTrail, CG_PointContents(), CG_SmokePuff(), cgs, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, centity_s::currentState, vmCvar_t::integer, LE_SCALE_FADE, localEntity_s::leType, cgs_t::media, entityState_s::pos, cgMedia_t::smokePuffShader, startTime, t, cg_t::time, TR_STATIONARY, weaponInfo_s::trailRadius, centity_s::trailTime, trajectory_t::trType, up, and weaponInfo_s::wiTrailTime.
Referenced by CG_GrenadeTrail(), and CG_RegisterWeapon().
static void CG_ShotgunEjectBrass (centity_t * cent) [static]
References localEntity_s::angles, AnglesToAxis(), refEntity_t::axis, AxisCopy(), axisDefault, localEntity_s::bounceFactor, cg, CG_AllocLocalEntity(), cg_brassTime, CG_PointContents(), cgs, CONTENTS_WATER, crandom, localEntity_s::endTime, refEntity_t::hModel, vmCvar_t::integer, LE_FRAGMENT, localEntity_s::leBounceSoundType, LEBS_BRASS, LEF_TUMBLE, localEntity_s::leFlags, localEntity_s::leMarkType, LEMT_NONE, centity_s::lerpAngles, centity_s::lerpOrigin, localEntity_s::leType, cgs_t::media, refEntity_t::origin, localEntity_s::pos, random, re, localEntity_s::refEntity, cgMedia_t::shotgunBrassModel, localEntity_s::startTime, cg_t::time, TR_GRAVITY, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorAdd, VectorCopy, and VectorScale.
Referenced by CG_RegisterWeapon().
void CG_ShotgunFire (entityState_t * es)
References cg, CG_PointContents(), CG_ShotgunPattern(), CG_SmokePuff(), cgs, CONTENTS_WATER, entityState_s::eventParm, cgs_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, LEF_PUFF_DONT_SCALE, cgs_t::media, entityState_s::origin2, entityState_s::otherEntityNum, entityState_s::pos, cgMedia_t::shotgunSmokePuffShader, cg_t::time, trajectory_t::trBase, up, VectorAdd, VectorNormalize(), VectorScale, VectorSet, and VectorSubtract.
Referenced by CG_EntityEvent().
static void CG_ShotgunPattern (vec3_t origin, vec3_t origin2, int seed, int otherEntNum) [static]
References CG_ShotgunPellet(), CrossProduct(), DEFAULT_SHOTGUN_COUNT, DEFAULT_SHOTGUN_SPREAD, end, forward, PerpendicularVector(), Q_crandom(), right, up, VectorMA(), and VectorNormalize2().
Referenced by CG_ShotgunFire().
static void CG_ShotgunPellet (vec3_t start, vec3_t end, int skipNum) [static]
References CG_BubbleTrail(), cg_entities, CG_MissileHitPlayer(), CG_MissileHitWall(), CG_PointContents(), CG_Trace(), CONTENTS_WATER, centity_s::currentState, trace_t::endpos, trace_t::entityNum, ET_PLAYER, entityState_s::eType, IMPACTSOUND_DEFAULT, IMPACTSOUND_METAL, MASK_SHOT, cplane_s::normal, NULL, trace_t::plane, SURF_METALSTEPS, SURF_NOIMPACT, trace_t::surfaceFlags, tr, trap_CM_BoxTrace(), and WP_SHOTGUN.
Referenced by CG_ShotgunPattern().
void CG_Tracer (vec3_t source, vec3_t dest)
References cg, cg_tracerLength, cg_tracerWidth, cgs, CHAN_AUTO, DotProduct, end, ENTITYNUM_WORLD, forward, line, cgs_t::media, polyVert_t::modulate, random, cg_t::refdef, right, polyVert_t::st, start, cgMedia_t::tracerShader, cgMedia_t::tracerSound, trap_R_AddPolyToScene(), trap_S_StartSound(), vmCvar_t::value, VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, refdef_t::viewaxis, and polyVert_t::xyz.
Referenced by CG_Bullet().
void CG_Weapon_f (void)
References cg, CG_Argv(), MAX_WEAPONS, playerState_s::pm_flags, PMF_FOLLOW, snapshot_t::ps, cg_t::snap, STAT_WEAPONS, playerState_s::stats, cg_t::time, cg_t::weaponSelect, and cg_t::weaponSelectTime.
static qboolean CG_WeaponSelectable (int i) [static]
References playerState_s::ammo, cg, snapshot_t::ps, qfalse, qtrue, cg_t::snap, STAT_WEAPONS, and playerState_s::stats.
Referenced by CG_NextWeapon_f(), CG_OutOfAmmoChange(), and CG_PrevWeapon_f().