ioquake3: code/cgame/cg_newdraw.c File Reference
cg_newdraw.c File Reference
#include "cg_local.h"
#include "../ui/ui_shared.h"
Defines
#define PIC_WIDTH 12
Functions
void CG_InitTeamChat (void)
void CG_SetPrintString (int type, const char *p)
void CG_CheckOrderPending (void)
static void CG_SetSelectedPlayerName (void)
int CG_GetSelectedPlayer (void)
void CG_SelectNextPlayer (void)
void CG_SelectPrevPlayer (void)
static void CG_DrawPlayerArmorIcon (rectDef_t *rect, qboolean draw2D)
static void CG_DrawPlayerArmorValue (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawPlayerAmmoIcon (rectDef_t *rect, qboolean draw2D)
static void CG_DrawPlayerAmmoValue (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawPlayerHead (rectDef_t *rect, qboolean draw2D)
static void CG_DrawSelectedPlayerHealth (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawSelectedPlayerArmor (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
qhandle_t CG_StatusHandle (int task)
static void CG_DrawSelectedPlayerStatus (rectDef_t *rect)
static void CG_DrawPlayerStatus (rectDef_t *rect)
static void CG_DrawSelectedPlayerName (rectDef_t *rect, float scale, vec4_t color, qboolean voice, int textStyle)
static void CG_DrawSelectedPlayerLocation (rectDef_t *rect, float scale, vec4_t color, int textStyle)
static void CG_DrawPlayerLocation (rectDef_t *rect, float scale, vec4_t color, int textStyle)
static void CG_DrawSelectedPlayerWeapon (rectDef_t *rect)
static void CG_DrawPlayerScore (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawPlayerItem (rectDef_t *rect, float scale, qboolean draw2D)
static void CG_DrawSelectedPlayerPowerup (rectDef_t *rect, qboolean draw2D)
static void CG_DrawSelectedPlayerHead (rectDef_t *rect, qboolean draw2D, qboolean voice)
static void CG_DrawPlayerHealth (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawRedScore (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawBlueScore (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawRedName (rectDef_t *rect, float scale, vec4_t color, int textStyle)
static void CG_DrawBlueName (rectDef_t *rect, float scale, vec4_t color, int textStyle)
static void CG_DrawBlueFlagName (rectDef_t *rect, float scale, vec4_t color, int textStyle)
static void CG_DrawBlueFlagStatus (rectDef_t *rect, qhandle_t shader)
static void CG_DrawBlueFlagHead (rectDef_t *rect)
static void CG_DrawRedFlagName (rectDef_t *rect, float scale, vec4_t color, int textStyle)
static void CG_DrawRedFlagStatus (rectDef_t *rect, qhandle_t shader)
static void CG_DrawRedFlagHead (rectDef_t *rect)
static void CG_HarvesterSkulls (rectDef_t *rect, float scale, vec4_t color, qboolean force2D, int textStyle)
static void CG_OneFlagStatus (rectDef_t *rect)
static void CG_DrawCTFPowerUp (rectDef_t *rect)
static void CG_DrawTeamColor (rectDef_t *rect, vec4_t color)
static void CG_DrawAreaPowerUp (rectDef_t *rect, int align, float special, float scale, vec4_t color)
float CG_GetValue (int ownerDraw)
qboolean CG_OtherTeamHasFlag (void)
qboolean CG_YourTeamHasFlag (void)
qboolean CG_OwnerDrawVisible (int flags)
static void CG_DrawPlayerHasFlag (rectDef_t *rect, qboolean force2D)
static void CG_DrawAreaSystemChat (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader)
static void CG_DrawAreaTeamChat (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader)
static void CG_DrawAreaChat (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader)
const char * CG_GetKillerText (void)
static void CG_DrawKiller (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_DrawCapFragLimit (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_Draw1stPlace (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_Draw2ndPlace (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
const char * CG_GetGameStatusText (void)
static void CG_DrawGameStatus (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
const char * CG_GameTypeString (void)
static void CG_DrawGameType (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader, int textStyle)
static void CG_Text_Paint_Limit (float *maxX, float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit)
void CG_DrawNewTeamInfo (rectDef_t *rect, float text_x, float text_y, float scale, vec4_t color, qhandle_t shader)
void CG_DrawTeamSpectators (rectDef_t *rect, float scale, vec4_t color, qhandle_t shader)
void CG_DrawMedal (int ownerDraw, rectDef_t *rect, float scale, vec4_t color, qhandle_t shader)
void CG_OwnerDraw (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, float scale, vec4_t color, qhandle_t shader, int textStyle)
void CG_MouseEvent (int x, int y)
void CG_HideTeamMenu (void)
void CG_ShowTeamMenu (void)
void CG_EventHandling (int type)
void CG_KeyEvent (int key, qboolean down)
int CG_ClientNumFromName (const char *p)
void CG_ShowResponseHead (void)
void CG_RunMenuScript (char **args)
void CG_GetTeamColor (vec4_t *color)
Variables
displayContextDef_t cgDC
int drawTeamOverlayModificationCount = -1
static float healthColors [4][4]
Define Documentation
#define PIC_WIDTH 12
Referenced by CG_DrawNewTeamInfo().
Function Documentation
void CG_CheckOrderPending (void)
References b, cg, cgs, playerState_s::clientNum, cgs_t::currentOrder, cgs_t::gametype, GT_CTF, NULL, numSortedTeamPlayers, cgs_t::orderPending, snapshot_t::ps, qfalse, cg_t::snap, sortedTeamPlayers, TEAMTASK_CAMP, TEAMTASK_DEFENSE, TEAMTASK_ESCORT, TEAMTASK_FOLLOW, TEAMTASK_OFFENSE, TEAMTASK_PATROL, TEAMTASK_RETRIEVE, trap_SendConsoleCommand(), va(), VOICECHAT_CAMP, VOICECHAT_DEFEND, VOICECHAT_FOLLOWFLAGCARRIER, VOICECHAT_FOLLOWME, VOICECHAT_OFFENSE, VOICECHAT_ONCAMPING, VOICECHAT_ONDEFENSE, VOICECHAT_ONFOLLOW, VOICECHAT_ONFOLLOWCARRIER, VOICECHAT_ONGETFLAG, VOICECHAT_ONOFFENSE, VOICECHAT_ONPATROL, VOICECHAT_PATROL, and VOICECHAT_RETURNFLAG.
Referenced by CG_Draw2D(), CG_SelectNextPlayer(), and CG_SelectPrevPlayer().
int CG_ClientNumFromName (const char * p)
References cgs, cgs_t::clientinfo, clientInfo_t::infoValid, cgs_t::maxclients, clientInfo_t::name, and Q_stricmp().
static void CG_Draw1stPlace (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_Text_Paint(), cgs, SCORE_NOT_PRESENT, cgs_t::scores1, va(), rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_Draw2ndPlace (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_Text_Paint(), cgs, SCORE_NOT_PRESENT, cgs_t::scores2, va(), rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawAreaChat (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader) [static]
References CG_Text_Paint(), rectDef_t::h, teamChat2, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawAreaPowerUp (rectDef_t * rect, int align, float special, float scale, vec4_t color) [static]
References BG_FindItemForPowerup(), cg, CG_DrawPic(), CG_Text_Paint(), Com_sprintf(), rectDef_t::h, HUD_VERTICAL, gitem_s::icon, if(), int(), MAX_POWERUPS, NULL, POWERUP_BLINK_TIME, POWERUP_BLINKS, playerState_s::powerups, snapshot_t::ps, r2, cg_t::snap, STAT_HEALTH, playerState_s::stats, t, cg_t::time, trap_R_RegisterShader(), trap_R_SetColor(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawAreaSystemChat (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader) [static]
References CG_Text_Paint(), rectDef_t::h, systemChat, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawAreaTeamChat (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader) [static]
References CG_Text_Paint(), rectDef_t::h, teamChat1, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawBlueFlagHead (rectDef_t * rect) [static]
References cg, CG_DrawHead(), cgs, cgs_t::clientinfo, rectDef_t::h, clientInfo_t::infoValid, cgs_t::maxclients, clientInfo_t::powerups, PW_BLUEFLAG, clientInfo_t::team, TEAM_RED, cg_t::time, VectorClear, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawBlueFlagName (rectDef_t * rect, float scale, vec4_t color, int textStyle) [static]
References CG_Text_Paint(), cgs, cgs_t::clientinfo, rectDef_t::h, clientInfo_t::infoValid, cgs_t::maxclients, clientInfo_t::name, clientInfo_t::powerups, PW_BLUEFLAG, clientInfo_t::team, TEAM_RED, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawBlueFlagStatus (rectDef_t * rect, qhandle_t shader) [static]
References BG_FindItemForPowerup(), cgs_t::blueflag, CG_DrawPic(), cgs, cgs_t::gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, rectDef_t::h, cgs_t::media, NULL, PW_BLUEFLAG, trap_R_SetColor(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawBlueName (rectDef_t * rect, float scale, vec4_t color, int textStyle) [static]
References CG_Text_Paint(), rectDef_t::h, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawBlueScore (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_Text_Paint(), CG_Text_Width(), cgs, Com_sprintf(), rectDef_t::h, SCORE_NOT_PRESENT, cgs_t::scores2, value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawCapFragLimit (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References cgs_t::capturelimit, CG_Text_Paint(), cgs, cgs_t::fraglimit, cgs_t::gametype, GT_CTF, limit, va(), rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawCTFPowerUp (rectDef_t * rect) [static]
References cg, CG_DrawPic(), cg_items, CG_RegisterItemVisuals(), cgs, cgs_t::gametype, GT_CTF, rectDef_t::h, itemInfo_t::icon, snapshot_t::ps, cg_t::snap, playerState_s::stats, value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawGameStatus (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_GetGameStatusText(), CG_Text_Paint(), rectDef_t::h, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawGameType (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_GameTypeString(), CG_Text_Paint(), rectDef_t::h, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawKiller (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References cg, CG_GetKillerText(), CG_Text_Paint(), CG_Text_Width(), rectDef_t::h, cg_t::killerName, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
void CG_DrawMedal (int ownerDraw, rectDef_t * rect, float scale, vec4_t color, qhandle_t shader)
References score_t::accuracy, score_t::assistCount, score_t::captures, cg, CG_ACCURACY, CG_ASSISTS, CG_CAPTURES, CG_DEFEND, CG_DrawPic(), CG_EXCELLENT, CG_GAUNTLET, CG_IMPRESSIVE, CG_PERFECT, CG_Text_Paint(), CG_Text_Width(), score_t::defendCount, score_t::excellentCount, score_t::guantletCount, rectDef_t::h, score_t::impressiveCount, NULL, score_t::perfect, cg_t::scores, cg_t::selectedScore, trap_R_SetColor(), va(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
void CG_DrawNewTeamInfo (rectDef_t * rect, float text_x, float text_y, float scale, vec4_t color, qhandle_t shader)
References clientInfo_t::armor, BG_FindItemForPowerup(), cg, CG_ConfigString(), CG_DrawPic(), CG_GetColorForHealth(), CG_StatusHandle(), CG_Text_Paint_Limit(), CG_Text_Width(), cg_weapons, cgs, cgs_t::clientinfo, count, CS_LOCATIONS, cgs_t::currentOrder, clientInfo_t::curWeapon, cgMedia_t::deferShader, h, rectDef_t::h, clientInfo_t::health, gitem_s::icon, clientInfo_t::infoValid, clientInfo_t::location, MAX_LOCATIONS, cgs_t::media, clientInfo_t::name, NULL, numSortedTeamPlayers, cgs_t::orderPending, cgs_t::orderTime, PERS_TEAM, playerState_s::persistant, PIC_WIDTH, clientInfo_t::powerups, snapshot_t::ps, PW_NUM_POWERUPS, cg_t::snap, sortedTeamPlayers, clientInfo_t::team, clientInfo_t::teamTask, cg_t::time, trap_R_RegisterShader(), trap_R_SetColor(), rectDef_t::w, weaponInfo_s::weaponIcon, rectDef_t::x, xx, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerAmmoIcon (rectDef_t * rect, qboolean draw2D) [static]
References weaponInfo_s::ammoIcon, weaponInfo_s::ammoModel, cg, cg_draw3dIcons, CG_Draw3DModel(), cg_drawIcons, CG_DrawPic(), cg_entities, cg_weapons, playerState_s::clientNum, centity_s::currentState, rectDef_t::h, icon(), vmCvar_t::integer, cg_t::predictedPlayerState, snapshot_t::ps, cg_t::snap, cg_t::time, VectorClear, rectDef_t::w, playerState_s::weapon, entityState_s::weapon, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerAmmoValue (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References playerState_s::ammo, cg, CG_DrawPic(), cg_entities, CG_Text_Paint(), CG_Text_Width(), playerState_s::clientNum, Com_sprintf(), centity_s::currentState, rectDef_t::h, NULL, snapshot_t::ps, cg_t::snap, trap_R_SetColor(), value(), rectDef_t::w, entityState_s::weapon, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerArmorIcon (rectDef_t * rect, qboolean draw2D) [static]
References cgMedia_t::armorIcon, cgMedia_t::armorModel, cg, cg_draw3dIcons, CG_Draw3DModel(), cg_drawIcons, CG_DrawPic(), cg_drawStatus, cgs, rectDef_t::h, vmCvar_t::integer, cgs_t::media, cg_t::time, VectorClear, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerArmorValue (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References cg, CG_DrawPic(), CG_Text_Paint(), CG_Text_Width(), Com_sprintf(), rectDef_t::h, NULL, snapshot_t::ps, cg_t::snap, STAT_ARMOR, playerState_s::stats, trap_R_SetColor(), value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerHasFlag (rectDef_t * rect, qboolean force2D) [static]
References cg, CG_DrawFlagModel(), rectDef_t::h, playerState_s::powerups, cg_t::predictedPlayerState, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, TEAM_BLUE, TEAM_FREE, TEAM_RED, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerHead (rectDef_t * rect, qboolean draw2D) [static]
References cg, CG_DrawHead(), playerState_s::clientNum, crandom, DAMAGE_TIME, cg_t::damageTime, cg_t::damageX, rectDef_t::h, cg_t::headEndPitch, cg_t::headEndTime, cg_t::headEndYaw, cg_t::headStartPitch, cg_t::headStartTime, cg_t::headStartYaw, M_PI, PITCH, snapshot_t::ps, random, cg_t::snap, cg_t::time, VectorClear, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerHealth (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References cg, CG_DrawPic(), CG_Text_Paint(), CG_Text_Width(), Com_sprintf(), rectDef_t::h, NULL, snapshot_t::ps, cg_t::snap, STAT_HEALTH, playerState_s::stats, trap_R_SetColor(), value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerItem (rectDef_t * rect, float scale, qboolean draw2D) [static]
References cg, CG_Draw3DModel(), CG_DrawPic(), cg_items, CG_RegisterItemVisuals(), rectDef_t::h, itemInfo_t::icon, itemInfo_t::models, snapshot_t::ps, qtrue, cg_t::snap, STAT_HOLDABLE_ITEM, playerState_s::stats, cg_t::time, value(), VectorClear, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerLocation (rectDef_t * rect, float scale, vec4_t color, int textStyle) [static]
References cg, CG_ConfigString(), CG_Text_Paint(), cgs, cgs_t::clientinfo, playerState_s::clientNum, CS_LOCATIONS, rectDef_t::h, clientInfo_t::location, snapshot_t::ps, cg_t::snap, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerScore (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References cg, CG_DrawPic(), CG_Text_Paint(), CG_Text_Width(), Com_sprintf(), rectDef_t::h, NULL, PERS_SCORE, playerState_s::persistant, snapshot_t::ps, cg_t::snap, trap_R_SetColor(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawPlayerStatus (rectDef_t * rect) [static]
References cg, CG_DrawPic(), CG_StatusHandle(), cgs, cgs_t::clientinfo, playerState_s::clientNum, h, rectDef_t::h, snapshot_t::ps, cg_t::snap, clientInfo_t::teamTask, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawRedFlagHead (rectDef_t * rect) [static]
References cg, CG_DrawHead(), cgs, cgs_t::clientinfo, rectDef_t::h, clientInfo_t::infoValid, cgs_t::maxclients, clientInfo_t::powerups, PW_REDFLAG, clientInfo_t::team, TEAM_BLUE, cg_t::time, VectorClear, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawRedFlagName (rectDef_t * rect, float scale, vec4_t color, int textStyle) [static]
References CG_Text_Paint(), cgs, cgs_t::clientinfo, rectDef_t::h, clientInfo_t::infoValid, cgs_t::maxclients, clientInfo_t::name, clientInfo_t::powerups, PW_REDFLAG, clientInfo_t::team, TEAM_BLUE, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawRedFlagStatus (rectDef_t * rect, qhandle_t shader) [static]
References BG_FindItemForPowerup(), CG_DrawPic(), cgs, cgs_t::gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, rectDef_t::h, cgs_t::media, NULL, PW_REDFLAG, cgs_t::redflag, trap_R_SetColor(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawRedName (rectDef_t * rect, float scale, vec4_t color, int textStyle) [static]
References CG_Text_Paint(), rectDef_t::h, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawRedScore (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_Text_Paint(), CG_Text_Width(), cgs, Com_sprintf(), rectDef_t::h, SCORE_NOT_PRESENT, cgs_t::scores1, value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerArmor (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References clientInfo_t::armor, CG_DrawPic(), CG_GetSelectedPlayer(), CG_Text_Paint(), CG_Text_Width(), cgs, cgs_t::clientinfo, Com_sprintf(), rectDef_t::h, NULL, sortedTeamPlayers, trap_R_SetColor(), value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerHead (rectDef_t * rect, qboolean draw2D, qboolean voice) [static]
References cg_draw3dIcons, CG_Draw3DModel(), cg_drawIcons, CG_DrawPic(), CG_GetSelectedPlayer(), cgs, cgs_t::clientinfo, cm, cgs_t::currentVoiceClient, clientInfo_t::deferred, cgMedia_t::deferShader, rectDef_t::h, clientInfo_t::headModel, clientInfo_t::headOffset, clientInfo_t::headSkin, vmCvar_t::integer, cgs_t::media, clientInfo_t::modelIcon, PITCH, ROLL, sortedTeamPlayers, trap_R_ModelBounds(), VectorAdd, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerHealth (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader, int textStyle) [static]
References CG_DrawPic(), CG_GetSelectedPlayer(), CG_Text_Paint(), CG_Text_Width(), cgs, cgs_t::clientinfo, Com_sprintf(), rectDef_t::h, clientInfo_t::health, NULL, sortedTeamPlayers, trap_R_SetColor(), value(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerLocation (rectDef_t * rect, float scale, vec4_t color, int textStyle) [static]
References CG_ConfigString(), CG_GetSelectedPlayer(), CG_Text_Paint(), cgs, cgs_t::clientinfo, CS_LOCATIONS, rectDef_t::h, clientInfo_t::location, sortedTeamPlayers, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerName (rectDef_t * rect, float scale, vec4_t color, qboolean voice, int textStyle) [static]
References CG_GetSelectedPlayer(), CG_Text_Paint(), cgs, cgs_t::clientinfo, cgs_t::currentVoiceClient, rectDef_t::h, clientInfo_t::name, sortedTeamPlayers, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerPowerup (rectDef_t * rect, qboolean draw2D) [static]
References BG_FindItemForPowerup(), CG_DrawPic(), CG_GetSelectedPlayer(), cgs, cgs_t::clientinfo, rectDef_t::h, gitem_s::icon, clientInfo_t::powerups, PW_NUM_POWERUPS, sortedTeamPlayers, trap_R_RegisterShader(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerStatus (rectDef_t * rect) [static]
References cg, CG_DrawPic(), CG_GetSelectedPlayer(), CG_StatusHandle(), cgs, cgs_t::clientinfo, cgs_t::currentOrder, h, rectDef_t::h, cgs_t::orderPending, cgs_t::orderTime, sortedTeamPlayers, clientInfo_t::teamTask, cg_t::time, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawSelectedPlayerWeapon (rectDef_t * rect) [static]
References CG_DrawPic(), CG_GetSelectedPlayer(), cg_weapons, cgs, cgs_t::clientinfo, clientInfo_t::curWeapon, cgMedia_t::deferShader, rectDef_t::h, cgs_t::media, sortedTeamPlayers, rectDef_t::w, weaponInfo_s::weaponIcon, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
static void CG_DrawTeamColor (rectDef_t * rect, vec4_t color) [static]
References cg, CG_DrawTeamBackground(), rectDef_t::h, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, cg_t::snap, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
void CG_DrawTeamSpectators (rectDef_t * rect, float scale, vec4_t color, qhandle_t shader)
References cg, CG_Text_Paint_Limit(), CG_Text_Width(), rectDef_t::h, cg_t::spectatorLen, cg_t::spectatorList, cg_t::spectatorOffset, cg_t::spectatorPaintX, cg_t::spectatorPaintX2, cg_t::spectatorTime, cg_t::spectatorWidth, cg_t::time, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
void CG_EventHandling (int type)
References CG_HideTeamMenu(), CGAME_EVENT_NONE, CGAME_EVENT_SCOREBOARD, CGAME_EVENT_TEAMMENU, cgs, cgs_t::eventHandling, and type().
Referenced by CG_KeyEvent(), and vmMain().
const char* CG_GameTypeString (void)
References cgs, cgs_t::gametype, GT_1FCTF, GT_CTF, GT_FFA, GT_HARVESTER, GT_OBELISK, and GT_TEAM.
Referenced by CG_DrawGameType().
const char* CG_GetGameStatusText (void)
References cg, CG_PlaceString(), cgs, cgs_t::gametype, GT_TEAM, PERS_RANK, PERS_SCORE, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, s, cg_t::snap, TEAM_SPECTATOR, cg_t::teamScores, and va().
Referenced by CG_DrawGameStatus().
const char* CG_GetKillerText (void)
References cg, cg_t::killerName, s, and va().
Referenced by CG_DrawKiller().
int CG_GetSelectedPlayer (void)
References numSortedTeamPlayers.
Referenced by CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), and CG_GetValue().
void CG_GetTeamColor (vec4_t * color)
References cg, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, cg_t::snap, TEAM_BLUE, and TEAM_RED.
float CG_GetValue (int ownerDraw)
References playerState_s::ammo, clientInfo_t::armor, cg, CG_BLUE_SCORE, cg_entities, CG_GetSelectedPlayer(), CG_PLAYER_AMMO_VALUE, CG_PLAYER_ARMOR_VALUE, CG_PLAYER_HEALTH, CG_PLAYER_SCORE, CG_RED_SCORE, CG_SELECTEDPLAYER_ARMOR, CG_SELECTEDPLAYER_HEALTH, cgs, cgs_t::clientinfo, playerState_s::clientNum, centity_s::currentState, clientInfo_t::health, PERS_SCORE, playerState_s::persistant, snapshot_t::ps, cgs_t::scores1, cgs_t::scores2, cg_t::snap, sortedTeamPlayers, STAT_ARMOR, STAT_HEALTH, playerState_s::stats, and entityState_s::weapon.
static void CG_HarvesterSkulls (rectDef_t * rect, float scale, vec4_t color, qboolean force2D, int textStyle) [static]
References cg, cg_draw3dIcons, CG_Draw3DModel(), cg_drawIcons, CG_DrawPic(), CG_Text_Paint(), CG_Text_Width(), cgs, Com_sprintf(), cgs_t::gametype, playerState_s::generic1, GT_HARVESTER, rectDef_t::h, vmCvar_t::integer, cgs_t::media, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, cg_t::snap, TEAM_BLUE, cg_t::time, VectorClear, rectDef_t::w, rectDef_t::x, rectDef_t::y, and YAW.
Referenced by CG_OwnerDraw().
void CG_HideTeamMenu (void)
References Menus_CloseByName().
Referenced by CG_EventHandling().
void CG_InitTeamChat (void)
References systemChat, teamChat1, and teamChat2.
Referenced by CG_Init().
void CG_KeyEvent (int key, qboolean down)
References cgs_t::capturedItem, cg, CG_EventHandling(), CGAME_EVENT_NONE, cgs, cgs_t::cursorX, cgs_t::cursorY, Display_CaptureItem(), Display_HandleKey(), K_MOUSE2, NULL, PM_NORMAL, PM_SPECTATOR, playerState_s::pm_type, cg_t::predictedPlayerState, qfalse, cg_t::showScores, and trap_Key_SetCatcher().
Referenced by vmMain().
void CG_MouseEvent (int x, int y)
References cgs_t::activeCursor, cgs_t::capturedItem, cg, cgs, CURSOR_ARROW, CURSOR_SIZER, cgs_t::cursorX, cgs_t::cursorY, Display_CursorType(), Display_MouseMove(), cgs_t::media, n, NULL, PM_NORMAL, PM_SPECTATOR, playerState_s::pm_type, cg_t::predictedPlayerState, qfalse, cgMedia_t::selectCursor, cg_t::showScores, cgMedia_t::sizeCursor, and trap_Key_SetCatcher().
Referenced by vmMain().
static void CG_OneFlagStatus (rectDef_t * rect) [static]
References BG_FindItemForPowerup(), CG_DrawPic(), cgs, FLAG_DROPPED, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, rectDef_t::h, cgs_t::media, PW_NEUTRALFLAG, trap_R_SetColor(), rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by CG_OwnerDraw().
qboolean CG_OtherTeamHasFlag (void)
References cgs_t::blueflag, cg, cgs, FLAG_TAKEN, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, qfalse, qtrue, cgs_t::redflag, cg_t::snap, TEAM_BLUE, and TEAM_RED.
Referenced by CG_OwnerDrawVisible().
void CG_OwnerDraw (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, float scale, vec4_t color, qhandle_t shader, int textStyle)
References CG_1STPLACE, CG_2NDPLACE, CG_ACCURACY, CG_AREA_CHAT, CG_AREA_POWERUP, CG_AREA_SYSTEMCHAT, CG_AREA_TEAMCHAT, CG_ASSISTS, CG_BLUE_FLAGHEAD, CG_BLUE_FLAGNAME, CG_BLUE_FLAGSTATUS, CG_BLUE_NAME, CG_BLUE_SCORE, CG_CAPFRAGLIMIT, CG_CAPTURES, CG_CTF_POWERUP, CG_DEFEND, CG_Draw1stPlace(), CG_Draw2ndPlace(), CG_DrawAreaChat(), CG_DrawAreaPowerUp(), CG_DrawAreaSystemChat(), CG_DrawAreaTeamChat(), CG_DrawBlueFlagHead(), CG_DrawBlueFlagName(), CG_DrawBlueFlagStatus(), CG_DrawBlueName(), CG_DrawBlueScore(), CG_DrawCapFragLimit(), CG_DrawCTFPowerUp(), CG_DrawGameStatus(), CG_DrawGameType(), CG_DrawKiller(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHasFlag(), CG_DrawPlayerHead(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawPlayerLocation(), CG_DrawPlayerScore(), CG_DrawPlayerStatus(), CG_DrawRedFlagHead(), CG_DrawRedFlagName(), CG_DrawRedFlagStatus(), CG_DrawRedName(), CG_DrawRedScore(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), cg_drawStatus, CG_DrawTeamColor(), CG_DrawTeamSpectators(), CG_EXCELLENT, CG_GAME_STATUS, CG_GAME_TYPE, CG_GAUNTLET, CG_HARVESTER_SKULLS, CG_HARVESTER_SKULLS2D, CG_HarvesterSkulls(), CG_IMPRESSIVE, CG_KILLER, CG_ONEFLAG_STATUS, CG_OneFlagStatus(), CG_PERFECT, CG_PLAYER_AMMO_ICON, CG_PLAYER_AMMO_ICON2D, CG_PLAYER_AMMO_VALUE, CG_PLAYER_ARMOR_ICON, CG_PLAYER_ARMOR_ICON2D, CG_PLAYER_ARMOR_VALUE, CG_PLAYER_HASFLAG, CG_PLAYER_HASFLAG2D, CG_PLAYER_HEAD, CG_PLAYER_HEALTH, CG_PLAYER_ITEM, CG_PLAYER_LOCATION, CG_PLAYER_SCORE, CG_PLAYER_STATUS, CG_RED_FLAGHEAD, CG_RED_FLAGNAME, CG_RED_FLAGSTATUS, CG_RED_NAME, CG_RED_SCORE, CG_SELECTEDPLAYER_ARMOR, CG_SELECTEDPLAYER_HEAD, CG_SELECTEDPLAYER_HEALTH, CG_SELECTEDPLAYER_LOCATION, CG_SELECTEDPLAYER_NAME, CG_SELECTEDPLAYER_POWERUP, CG_SELECTEDPLAYER_STATUS, CG_SELECTEDPLAYER_WEAPON, CG_SHOW_2DONLY, CG_SPECTATORS, CG_TEAM_COLOR, CG_TEAMINFO, CG_VOICE_HEAD, CG_VOICE_NAME, h, rectDef_t::h, vmCvar_t::integer, numSortedTeamPlayers, qfalse, qtrue, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
qboolean CG_OwnerDrawVisible (int flags)
References cgs_t::blueflag, cg, CG_OtherTeamHasFlag(), CG_SHOW_ANYNONTEAMGAME, CG_SHOW_ANYTEAMGAME, CG_SHOW_BLUE_TEAM_HAS_REDFLAG, CG_SHOW_CTF, CG_SHOW_DURINGINCOMINGVOICE, CG_SHOW_HARVESTER, CG_SHOW_HEALTHCRITICAL, CG_SHOW_HEALTHOK, CG_SHOW_IF_PLAYER_HAS_FLAG, CG_SHOW_NOTEAMINFO, CG_SHOW_OBELISK, CG_SHOW_ONEFLAG, CG_SHOW_OTHERTEAMHASFLAG, CG_SHOW_RED_TEAM_HAS_BLUEFLAG, CG_SHOW_SINGLEPLAYER, CG_SHOW_TEAMINFO, CG_SHOW_TOURNAMENT, CG_SHOW_YOURTEAMHASENEMYFLAG, CG_YourTeamHasFlag(), cgs, FLAG_TAKEN, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, numSortedTeamPlayers, playerState_s::powerups, snapshot_t::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, qfalse, qtrue, cgs_t::redflag, cg_t::snap, STAT_HEALTH, and playerState_s::stats.
void CG_RunMenuScript (char ** args)
void CG_SelectNextPlayer (void)
References CG_CheckOrderPending(), CG_SetSelectedPlayerName(), and numSortedTeamPlayers.
void CG_SelectPrevPlayer (void)
References CG_CheckOrderPending(), CG_SetSelectedPlayerName(), and numSortedTeamPlayers.
void CG_SetPrintString (int type, const char * p)
References SYSTEM_PRINT, systemChat, teamChat1, and teamChat2.
static void CG_SetSelectedPlayerName (void) [static]
References cgs, cgs_t::clientinfo, cgs_t::currentOrder, clientInfo_t::name, numSortedTeamPlayers, sortedTeamPlayers, clientInfo_t::teamTask, trap_Cvar_Set(), and va().
Referenced by CG_SelectNextPlayer(), and CG_SelectPrevPlayer().
void CG_ShowResponseHead (void)
References cg, Menus_OpenByName(), cg_t::time, trap_Cvar_Set(), and cg_t::voiceTime.
Referenced by CG_PlayVoiceChat().
void CG_ShowTeamMenu (void)
References Menus_OpenByName().
qhandle_t CG_StatusHandle (int task)
References cgs, h, cgs_t::media, TEAMTASK_CAMP, TEAMTASK_DEFENSE, TEAMTASK_ESCORT, TEAMTASK_FOLLOW, TEAMTASK_OFFENSE, TEAMTASK_PATROL, and TEAMTASK_RETRIEVE.
Referenced by CG_DrawNewTeamInfo(), CG_DrawPlayerStatus(), and CG_DrawSelectedPlayerStatus().
static void CG_Text_Paint_Limit (float * maxX, float x, float y, float scale, vec4_t color, const char * text, float adjust, int limit) [static]
References displayContextDef_t::Assets, cachedAssets_t::bigFont, cg_bigFont, cg_smallFont, CG_Text_PaintChar(), CG_Text_Width(), ColorIndex, count, g_color_table, glyphInfo_t::glyph, fontInfo_t::glyphs, fontInfo_t::glyphScale, glyphInfo_t::imageHeight, glyphInfo_t::imageWidth, int(), limit, NULL, Q_IsColorString, s, glyphInfo_t::s, glyphInfo_t::s2, cachedAssets_t::smallFont, glyphInfo_t::t, glyphInfo_t::t2, cachedAssets_t::textFont, glyphInfo_t::top, trap_R_SetColor(), vmCvar_t::value, and glyphInfo_t::xSkip.
Referenced by CG_DrawNewTeamInfo(), and CG_DrawTeamSpectators().
qboolean CG_YourTeamHasFlag (void)
References cgs_t::blueflag, cg, cgs, FLAG_TAKEN, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, qfalse, qtrue, cgs_t::redflag, cg_t::snap, TEAM_BLUE, and TEAM_RED.
Referenced by CG_OwnerDrawVisible().
Variable Documentation
displayContextDef_t cgDC
int drawTeamOverlayModificationCount = -1
float healthColors[4][4] [static]
Initial value:
 {
  { 1.0f, 0.69f, 0.0f, 1.0f } ,
  { 1.0f, 0.2f, 0.2f, 1.0f },
  { 0.5f, 0.5f, 0.5f, 1.0f},
  { 1.0f, 1.0f, 1.0f, 1.0f } }