ioquake3: code/cgame/cg_local.h File Reference
cg_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../renderer/tr_types.h"
#include "../game/bg_public.h"
#include "cg_public.h"
Data Structures
struct lerpFrame_t
struct playerEntity_t
struct centity_s
struct markPoly_s
struct localEntity_s
struct score_t
struct clientInfo_t
struct weaponInfo_s
struct itemInfo_t
struct powerupInfo_t
struct skulltrail_t
struct cg_t
struct cgMedia_t
struct cgs_t
Defines
#define POWERUP_BLINKS 5
#define POWERUP_BLINK_TIME 1000
#define FADE_TIME 200
#define PULSE_TIME 200
#define DAMAGE_DEFLECT_TIME 100
#define DAMAGE_RETURN_TIME 400
#define DAMAGE_TIME 500
#define LAND_DEFLECT_TIME 150
#define LAND_RETURN_TIME 300
#define STEP_TIME 200
#define DUCK_TIME 100
#define PAIN_TWITCH_TIME 200
#define WEAPON_SELECT_TIME 1400
#define ITEM_SCALEUP_TIME 1000
#define ZOOM_TIME 150
#define ITEM_BLOB_TIME 200
#define MUZZLE_FLASH_TIME 20
#define SINK_TIME 1000
#define ATTACKER_HEAD_TIME 10000
#define REWARD_TIME 3000
#define PULSE_SCALE 1.5
#define MAX_STEP_CHANGE 32
#define MAX_VERTS_ON_POLY 10
#define MAX_MARK_POLYS 256
#define STAT_MINUS 10
#define ICON_SIZE 48
#define CHAR_WIDTH 32
#define CHAR_HEIGHT 48
#define TEXT_ICON_SPACE 4
#define TEAMCHAT_WIDTH 80
#define TEAMCHAT_HEIGHT 8
#define GIANT_WIDTH 32
#define GIANT_HEIGHT 48
#define NUM_CROSSHAIRS 10
#define TEAM_OVERLAY_MAXNAME_WIDTH 12
#define TEAM_OVERLAY_MAXLOCATION_WIDTH 16
#define DEFAULT_MODEL "sarge"
#define DEFAULT_TEAM_MODEL "sarge"
#define DEFAULT_TEAM_HEAD "sarge"
#define DEFAULT_REDTEAM_NAME "Stroggs"
#define DEFAULT_BLUETEAM_NAME "Pagans"
#define MAX_CUSTOM_SOUNDS 32
#define MAX_SKULLTRAIL 10
#define MAX_REWARDSTACK 10
#define MAX_SOUNDBUFFER 20
#define MAX_PREDICTED_EVENTS 16
Typedefs
typedef struct centity_s centity_t
typedef struct markPoly_s markPoly_t
typedef struct localEntity_s localEntity_t
typedef struct weaponInfo_s weaponInfo_t
Enumerations
enum footstep_t {
FOOTSTEP_NORMAL, FOOTSTEP_BOOT, FOOTSTEP_FLESH, FOOTSTEP_MECH,
FOOTSTEP_ENERGY, FOOTSTEP_METAL, FOOTSTEP_SPLASH, FOOTSTEP_TOTAL
}
enum impactSound_t { IMPACTSOUND_DEFAULT, IMPACTSOUND_METAL, IMPACTSOUND_FLESH }
enum leType_t {
LE_MARK, LE_EXPLOSION, LE_SPRITE_EXPLOSION, LE_FRAGMENT,
LE_MOVE_SCALE_FADE, LE_FALL_SCALE_FADE, LE_FADE_RGB, LE_SCALE_FADE,
LE_SCOREPLUM
}
enum leFlag_t { LEF_PUFF_DONT_SCALE = 0x0001, LEF_TUMBLE = 0x0002, LEF_SOUND1 = 0x0004, LEF_SOUND2 = 0x0008 }
enum leMarkType_t { LEMT_NONE, LEMT_BURN, LEMT_BLOOD }
enum leBounceSoundType_t { LEBS_NONE, LEBS_BLOOD, LEBS_BRASS }
enum q3print_t { SYSTEM_PRINT, CHAT_PRINT, TEAMCHAT_PRINT }
Functions
const char * CG_ConfigString (int index)
const char * CG_Argv (int arg)
void QDECL CG_Printf (const char *msg,...) __attribute__((format(printf
void QDECL void QDECL CG_Error (const char *msg,...) __attribute__((noreturn
void QDECL void QDECL format (printf, 1, 2)))
void CG_StartMusic (void)
void CG_UpdateCvars (void)
int CG_CrosshairPlayer (void)
int CG_LastAttacker (void)
void CG_LoadMenus (const char *menuFile)
void CG_KeyEvent (int key, qboolean down)
void CG_MouseEvent (int x, int y)
void CG_EventHandling (int type)
void CG_RankRunFrame (void)
void CG_SetScoreSelection (void *menu)
score_t * CG_GetSelectedScore (void)
void CG_BuildSpectatorString (void)
void CG_TestModel_f (void)
void CG_TestGun_f (void)
void CG_TestModelNextFrame_f (void)
void CG_TestModelPrevFrame_f (void)
void CG_TestModelNextSkin_f (void)
void CG_TestModelPrevSkin_f (void)
void CG_ZoomDown_f (void)
void CG_ZoomUp_f (void)
void CG_AddBufferedSound (sfxHandle_t sfx)
void CG_DrawActiveFrame (int serverTime, stereoFrame_t stereoView, qboolean demoPlayback)
void CG_AdjustFrom640 (float *x, float *y, float *w, float *h)
void CG_FillRect (float x, float y, float width, float height, const float *color)
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
void CG_DrawString (float x, float y, const char *string, float charWidth, float charHeight, const float *modulate)
void CG_DrawStringExt (int x, int y, const char *string, const float *setColor, qboolean forceColor, qboolean shadow, int charWidth, int charHeight, int maxChars)
void CG_DrawBigString (int x, int y, const char *s, float alpha)
void CG_DrawBigStringColor (int x, int y, const char *s, vec4_t color)
void CG_DrawSmallString (int x, int y, const char *s, float alpha)
void CG_DrawSmallStringColor (int x, int y, const char *s, vec4_t color)
int CG_DrawStrlen (const char *str)
float * CG_FadeColor (int startMsec, int totalMsec)
float * CG_TeamColor (int team)
void CG_TileClear (void)
void CG_ColorForHealth (vec4_t hcolor)
void CG_GetColorForHealth (int health, int armor, vec4_t hcolor)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
void CG_DrawRect (float x, float y, float width, float height, float size, const float *color)
void CG_DrawSides (float x, float y, float w, float h, float size)
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
void CG_AddLagometerFrameInfo (void)
void CG_AddLagometerSnapshotInfo (snapshot_t *snap)
void CG_CenterPrint (const char *str, int y, int charWidth)
void CG_DrawHead (float x, float y, float w, float h, int clientNum, vec3_t headAngles)
void CG_DrawActive (stereoFrame_t stereoView)
void CG_DrawFlagModel (float x, float y, float w, float h, int team, qboolean force2D)
void CG_DrawTeamBackground (int x, int y, int w, int h, float alpha, int team)
void CG_OwnerDraw (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, float scale, vec4_t color, qhandle_t shader, int textStyle)
void CG_Text_Paint (float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
int CG_Text_Width (const char *text, float scale, int limit)
int CG_Text_Height (const char *text, float scale, int limit)
void CG_SelectPrevPlayer (void)
void CG_SelectNextPlayer (void)
float CG_GetValue (int ownerDraw)
qboolean CG_OwnerDrawVisible (int flags)
void CG_RunMenuScript (char **args)
void CG_ShowResponseHead (void)
void CG_SetPrintString (int type, const char *p)
void CG_InitTeamChat (void)
void CG_GetTeamColor (vec4_t *color)
const char * CG_GetGameStatusText (void)
const char * CG_GetKillerText (void)
void CG_Draw3DModel (float x, float y, float w, float h, qhandle_t model, qhandle_t skin, vec3_t origin, vec3_t angles)
void CG_Text_PaintChar (float x, float y, float width, float height, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
void CG_CheckOrderPending (void)
const char * CG_GameTypeString (void)
qboolean CG_YourTeamHasFlag (void)
qboolean CG_OtherTeamHasFlag (void)
qhandle_t CG_StatusHandle (int task)
void CG_Player (centity_t *cent)
void CG_ResetPlayerEntity (centity_t *cent)
void CG_AddRefEntityWithPowerups (refEntity_t *ent, entityState_t *state, int team)
void CG_NewClientInfo (int clientNum)
sfxHandle_t CG_CustomSound (int clientNum, const char *soundName)
void CG_BuildSolidList (void)
int CG_PointContents (const vec3_t point, int passEntityNum)
void CG_Trace (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
void CG_PredictPlayerState (void)
void CG_LoadDeferredPlayers (void)
void CG_CheckEvents (centity_t *cent)
const char * CG_PlaceString (int rank)
void CG_EntityEvent (centity_t *cent, vec3_t position)
void CG_PainEvent (centity_t *cent, int health)
void CG_SetEntitySoundPosition (centity_t *cent)
void CG_AddPacketEntities (void)
void CG_Beam (centity_t *cent)
void CG_AdjustPositionForMover (const vec3_t in, int moverNum, int fromTime, int toTime, vec3_t out)
void CG_PositionEntityOnTag (refEntity_t *entity, const refEntity_t *parent, qhandle_t parentModel, char *tagName)
void CG_PositionRotatedEntityOnTag (refEntity_t *entity, const refEntity_t *parent, qhandle_t parentModel, char *tagName)
void CG_NextWeapon_f (void)
void CG_PrevWeapon_f (void)
void CG_Weapon_f (void)
void CG_RegisterWeapon (int weaponNum)
void CG_RegisterItemVisuals (int itemNum)
void CG_FireWeapon (centity_t *cent)
void CG_MissileHitWall (int weapon, int clientNum, vec3_t origin, vec3_t dir, impactSound_t soundType)
void CG_MissileHitPlayer (int weapon, vec3_t origin, vec3_t dir, int entityNum)
void CG_ShotgunFire (entityState_t *es)
void CG_Bullet (vec3_t origin, int sourceEntityNum, vec3_t normal, qboolean flesh, int fleshEntityNum)
void CG_RailTrail (clientInfo_t *ci, vec3_t start, vec3_t end)
void CG_GrappleTrail (centity_t *ent, const weaponInfo_t *wi)
void CG_AddViewWeapon (playerState_t *ps)
void CG_AddPlayerWeapon (refEntity_t *parent, playerState_t *ps, centity_t *cent, int team)
void CG_DrawWeaponSelect (void)
void CG_OutOfAmmoChange (void)
void CG_InitMarkPolys (void)
void CG_AddMarks (void)
void CG_ImpactMark (qhandle_t markShader, const vec3_t origin, const vec3_t dir, float orientation, float r, float g, float b, float a, qboolean alphaFade, float radius, qboolean temporary)
void CG_InitLocalEntities (void)
localEntity_t * CG_AllocLocalEntity (void)
void CG_AddLocalEntities (void)
localEntity_t * CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
void CG_BubbleTrail (vec3_t start, vec3_t end, float spacing)
void CG_SpawnEffect (vec3_t org)
void CG_ScorePlum (int client, vec3_t org, int score)
void CG_GibPlayer (vec3_t playerOrigin)
void CG_BigExplode (vec3_t playerOrigin)
void CG_Bleed (vec3_t origin, int entityNum)
localEntity_t * CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
void CG_ProcessSnapshots (void)
void CG_LoadingString (const char *s)
void CG_LoadingItem (int itemNum)
void CG_LoadingClient (int clientNum)
void CG_DrawInformation (void)
qboolean CG_DrawOldScoreboard (void)
void CG_DrawOldTourneyScoreboard (void)
qboolean CG_ConsoleCommand (void)
void CG_InitConsoleCommands (void)
void CG_ExecuteNewServerCommands (int latestSequence)
void CG_ParseServerinfo (void)
void CG_SetConfigValues (void)
void CG_LoadVoiceChats (void)
void CG_ShaderStateChanged (void)
void CG_VoiceChatLocal (int mode, qboolean voiceOnly, int clientNum, int color, const char *cmd)
void CG_PlayBufferedVoiceChats (void)
void CG_Respawn (void)
void CG_TransitionPlayerState (playerState_t *ps, playerState_t *ops)
void CG_CheckChangedPredictableEvents (playerState_t *ps)
void trap_Print (const char *fmt)
void trap_Error (const char *fmt) __attribute__((noreturn))
int trap_Milliseconds (void)
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
void trap_Cvar_Update (vmCvar_t *vmCvar)
void trap_Cvar_Set (const char *var_name, const char *value)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
int trap_Argc (void)
void trap_Argv (int n, char *buffer, int bufferLength)
void trap_Args (char *buffer, int bufferLength)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
void trap_SendConsoleCommand (const char *text)
void trap_AddCommand (const char *cmdName)
void trap_SendClientCommand (const char *s)
void trap_UpdateScreen (void)
void trap_CM_LoadMap (const char *mapname)
int trap_CM_NumInlineModels (void)
clipHandle_t trap_CM_InlineModel (int index)
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
void trap_CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
void trap_CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
int trap_CM_MarkFragments (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
void trap_S_StopLoopingSound (int entnum)
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
void trap_S_ClearLoopingSounds (qboolean killall)
void trap_S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void trap_S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
void trap_S_StartBackgroundTrack (const char *intro, const char *loop)
void trap_S_StopBackgroundTrack (void)
void trap_R_LoadWorldMap (const char *mapname)
qhandle_t trap_R_RegisterModel (const char *name)
qhandle_t trap_R_RegisterSkin (const char *name)
qhandle_t trap_R_RegisterShader (const char *name)
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
void trap_R_ClearScene (void)
void trap_R_AddRefEntityToScene (const refEntity_t *re)
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys)
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
int trap_R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void trap_R_RenderScene (const refdef_t *fd)
void trap_R_SetColor (const float *rgba)
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
int trap_R_LerpTag (orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName)
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
void trap_GetGlconfig (glconfig_t *glconfig)
void trap_GetGameState (gameState_t *gamestate)
void trap_GetCurrentSnapshotNumber (int *snapshotNumber, int *serverTime)
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t *snapshot)
qboolean trap_GetServerCommand (int serverCommandNumber)
int trap_GetCurrentCmdNumber (void)
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t *ucmd)
void trap_SetUserCmdValue (int stateValue, float sensitivityScale)
void testPrintInt (char *string, int i)
void testPrintFloat (char *string, float f)
int trap_MemoryRemaining (void)
void trap_R_RegisterFont (const char *fontName, int pointSize, fontInfo_t *font)
qboolean trap_Key_IsDown (int keynum)
int trap_Key_GetCatcher (void)
void trap_Key_SetCatcher (int catcher)
int trap_Key_GetKey (const char *binding)
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
e_status trap_CIN_StopCinematic (int handle)
e_status trap_CIN_RunCinematic (int handle)
void trap_CIN_DrawCinematic (int handle)
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
void trap_SnapVector (float *v)
qboolean trap_loadCamera (const char *name)
void trap_startCamera (int time)
qboolean trap_getCameraInfo (int time, vec3_t *origin, vec3_t *angles)
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
void CG_ClearParticles (void)
void CG_AddParticles (void)
void CG_ParticleSnow (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
void CG_ParticleSmoke (qhandle_t pshader, centity_t *cent)
void CG_AddParticleShrapnel (localEntity_t *le)
void CG_ParticleSnowFlurry (qhandle_t pshader, centity_t *cent)
void CG_ParticleBulletDebris (vec3_t org, vec3_t vel, int duration)
void CG_ParticleSparks (vec3_t org, vec3_t vel, int duration, float x, float y, float speed)
void CG_ParticleDust (centity_t *cent, vec3_t origin, vec3_t dir)
void CG_ParticleMisc (qhandle_t pshader, vec3_t origin, int size, int duration, float alpha)
void CG_ParticleExplosion (char *animStr, vec3_t origin, vec3_t vel, int duration, int sizeStart, int sizeEnd)
int CG_NewParticleArea (int num)
Variables
cgs_t cgs
cg_t cg
centity_t cg_entities [MAX_GENTITIES]
weaponInfo_t cg_weapons [MAX_WEAPONS]
itemInfo_t cg_items [MAX_ITEMS]
markPoly_t cg_markPolys [MAX_MARK_POLYS]
vmCvar_t cg_centertime
vmCvar_t cg_runpitch
vmCvar_t cg_runroll
vmCvar_t cg_bobup
vmCvar_t cg_bobpitch
vmCvar_t cg_bobroll
vmCvar_t cg_swingSpeed
vmCvar_t cg_shadows
vmCvar_t cg_gibs
vmCvar_t cg_drawTimer
vmCvar_t cg_drawFPS
vmCvar_t cg_drawSnapshot
vmCvar_t cg_draw3dIcons
vmCvar_t cg_drawIcons
vmCvar_t cg_drawAmmoWarning
vmCvar_t cg_drawCrosshair
vmCvar_t cg_drawCrosshairNames
vmCvar_t cg_drawRewards
vmCvar_t cg_drawTeamOverlay
vmCvar_t cg_teamOverlayUserinfo
vmCvar_t cg_crosshairX
vmCvar_t cg_crosshairY
vmCvar_t cg_crosshairSize
vmCvar_t cg_crosshairHealth
vmCvar_t cg_drawStatus
vmCvar_t cg_draw2D
vmCvar_t cg_animSpeed
vmCvar_t cg_debugAnim
vmCvar_t cg_debugPosition
vmCvar_t cg_debugEvents
vmCvar_t cg_railTrailTime
vmCvar_t cg_errorDecay
vmCvar_t cg_nopredict
vmCvar_t cg_noPlayerAnims
vmCvar_t cg_showmiss
vmCvar_t cg_footsteps
vmCvar_t cg_addMarks
vmCvar_t cg_brassTime
vmCvar_t cg_gun_frame
vmCvar_t cg_gun_x
vmCvar_t cg_gun_y
vmCvar_t cg_gun_z
vmCvar_t cg_drawGun
vmCvar_t cg_viewsize
vmCvar_t cg_tracerChance
vmCvar_t cg_tracerWidth
vmCvar_t cg_tracerLength
vmCvar_t cg_autoswitch
vmCvar_t cg_ignore
vmCvar_t cg_simpleItems
vmCvar_t cg_fov
vmCvar_t cg_zoomFov
vmCvar_t cg_thirdPersonRange
vmCvar_t cg_thirdPersonAngle
vmCvar_t cg_thirdPerson
vmCvar_t cg_lagometer
vmCvar_t cg_drawAttacker
vmCvar_t cg_synchronousClients
vmCvar_t cg_teamChatTime
vmCvar_t cg_teamChatHeight
vmCvar_t cg_stats
vmCvar_t cg_forceModel
vmCvar_t cg_buildScript
vmCvar_t cg_paused
vmCvar_t cg_blood
vmCvar_t cg_predictItems
vmCvar_t cg_deferPlayers
vmCvar_t cg_drawFriend
vmCvar_t cg_teamChatsOnly
vmCvar_t cg_noVoiceChats
vmCvar_t cg_noVoiceText
vmCvar_t cg_scorePlum
vmCvar_t cg_smoothClients
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t cg_cameraOrbit
vmCvar_t cg_cameraOrbitDelay
vmCvar_t cg_timescaleFadeEnd
vmCvar_t cg_timescaleFadeSpeed
vmCvar_t cg_timescale
vmCvar_t cg_cameraMode
vmCvar_t cg_smallFont
vmCvar_t cg_bigFont
vmCvar_t cg_noTaunt
vmCvar_t cg_noProjectileTrail
vmCvar_t cg_oldRail
vmCvar_t cg_oldRocket
vmCvar_t cg_oldPlasma
vmCvar_t cg_trueLightning
int sortedTeamPlayers [TEAM_MAXOVERLAY]
int numSortedTeamPlayers
int drawTeamOverlayModificationCount
char systemChat [256]
char teamChat1 [256]
char teamChat2 [256]
qboolean initparticles
Define Documentation
#define ATTACKER_HEAD_TIME 10000
Referenced by CG_DrawAttacker().
#define CHAR_HEIGHT 48
Referenced by CG_DrawField().
#define CHAR_WIDTH 32
Referenced by CG_DrawField(), CG_DrawPowerups(), and CG_DrawStatusBar().
#define DAMAGE_DEFLECT_TIME 100
Referenced by CG_OffsetFirstPersonView().
#define DAMAGE_RETURN_TIME 400
Referenced by CG_OffsetFirstPersonView().
#define DAMAGE_TIME 500
Referenced by CG_DamageBlendBlob(), CG_DamageFeedback(), CG_DrawPlayerHead(), and CG_DrawStatusBarHead().
#define DEFAULT_BLUETEAM_NAME "Pagans"
Referenced by CG_LoadClientInfo(), and CG_RegisterClientModelname().
#define DEFAULT_MODEL "sarge"
Referenced by CG_LoadClientInfo(), CG_LoadingClient(), and CG_RegisterCvars().
#define DEFAULT_REDTEAM_NAME "Stroggs"
Referenced by CG_LoadClientInfo(), and CG_RegisterClientModelname().
#define DEFAULT_TEAM_HEAD "sarge"
Referenced by CG_LoadClientInfo(), CG_NewClientInfo(), and CG_RegisterCvars().
#define DEFAULT_TEAM_MODEL "sarge"
Referenced by CG_LoadClientInfo(), CG_NewClientInfo(), and CG_RegisterCvars().
#define DUCK_TIME 100
Referenced by CG_OffsetFirstPersonView().
#define FADE_TIME 200
Referenced by CG_DrawOldScoreboard(), CG_DrawScoreboard(), and CG_FadeColor().
#define GIANT_HEIGHT 48
Referenced by CG_CenterGiantLine(), CG_DrawFollow(), and CG_DrawOldTourneyScoreboard().
#define GIANT_WIDTH 32
Referenced by CG_CenterGiantLine(), CG_DrawFollow(), CG_DrawOldTourneyScoreboard(), and CG_DrawWarmup().
#define ICON_SIZE 48
Referenced by CG_DrawAttacker(), CG_DrawClientScore(), CG_DrawHoldableItem(), CG_DrawLowerLeft(), CG_DrawLowerRight(), CG_DrawPickupItem(), CG_DrawPowerups(), CG_DrawReward(), CG_DrawStatusBar(), CG_DrawStatusBarFlag(), and CG_DrawStatusBarHead().
#define ITEM_BLOB_TIME 200
Referenced by CG_DrawCrosshair(), and CG_DrawCrosshair3D().
#define ITEM_SCALEUP_TIME 1000
Referenced by CG_Item().
#define LAND_DEFLECT_TIME 150
Referenced by CG_CalculateWeaponPosition(), and CG_OffsetFirstPersonView().
#define LAND_RETURN_TIME 300
Referenced by CG_CalculateWeaponPosition(), and CG_OffsetFirstPersonView().
#define MAX_CUSTOM_SOUNDS 32
Referenced by CG_CustomSound(), and CG_LoadClientInfo().
#define MAX_MARK_POLYS 256
Referenced by CG_InitMarkPolys().
#define MAX_PREDICTED_EVENTS 16
Referenced by CG_CheckChangedPredictableEvents(), and CG_CheckPlayerstateEvents().
#define MAX_REWARDSTACK 10
Referenced by pushReward().
#define MAX_SKULLTRAIL 10
#define MAX_SOUNDBUFFER 20
Referenced by CG_AddBufferedSound(), and CG_PlayBufferedSounds().
#define MAX_STEP_CHANGE 32
Referenced by CG_EntityEvent().
#define MAX_VERTS_ON_POLY 10
Referenced by CG_ImpactMark().
#define MUZZLE_FLASH_TIME 20
Referenced by CG_AddPlayerWeapon().
#define NUM_CROSSHAIRS 10
Referenced by AssetCache(), CG_DrawCrosshair(), CG_DrawCrosshair3D(), CG_RegisterGraphics(), UI_Crosshair_HandleKey(), and UI_DrawCrosshair().
#define PAIN_TWITCH_TIME 200
Referenced by CG_AddPainTwitch().
#define POWERUP_BLINK_TIME 1000
Referenced by CG_DrawAreaPowerUp(), CG_DrawPowerups(), and CG_PowerupTimerSounds().
#define POWERUP_BLINKS 5
Referenced by CG_DrawAreaPowerUp(), CG_DrawPowerups(), and CG_PowerupTimerSounds().
#define PULSE_SCALE 1.5
Referenced by CG_DrawPowerups().
#define PULSE_TIME 200
Referenced by CG_DrawPowerups().
#define REWARD_TIME 3000
Referenced by CG_DrawReward().
#define SINK_TIME 1000
Referenced by CG_AddFragment().
#define STAT_MINUS 10
Referenced by CG_DrawField().
#define STEP_TIME 200
Referenced by CG_CalculateWeaponPosition(), CG_EntityEvent(), and CG_StepOffset().
#define TEAM_OVERLAY_MAXLOCATION_WIDTH 16
Referenced by CG_DrawTeamOverlay().
#define TEAM_OVERLAY_MAXNAME_WIDTH 12
Referenced by CG_DrawTeamOverlay().
#define TEAMCHAT_HEIGHT 8
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
#define TEAMCHAT_WIDTH 80
Referenced by CG_AddToTeamChat().
#define TEXT_ICON_SPACE 4
Referenced by CG_DrawStatusBar().
#define WEAPON_SELECT_TIME 1400
Referenced by CG_DrawWeaponSelect().
#define ZOOM_TIME 150
Referenced by CG_CalcFov().
Typedef Documentation
typedef struct centity_s centity_t
typedef struct localEntity_s localEntity_t
typedef struct markPoly_s markPoly_t
typedef struct weaponInfo_s weaponInfo_t
Enumeration Type Documentation
enum footstep_t
Enumerator:
FOOTSTEP_NORMAL
FOOTSTEP_BOOT
FOOTSTEP_FLESH
FOOTSTEP_MECH
FOOTSTEP_ENERGY
FOOTSTEP_METAL
FOOTSTEP_SPLASH
FOOTSTEP_TOTAL
enum impactSound_t
Enumerator:
IMPACTSOUND_DEFAULT
IMPACTSOUND_METAL
IMPACTSOUND_FLESH
enum leBounceSoundType_t
Enumerator:
LEBS_NONE
LEBS_BLOOD
LEBS_BRASS
enum leFlag_t
Enumerator:
LEF_PUFF_DONT_SCALE
LEF_TUMBLE
LEF_SOUND1
LEF_SOUND2
enum leMarkType_t
Enumerator:
LEMT_NONE
LEMT_BURN
LEMT_BLOOD
enum leType_t
Enumerator:
LE_MARK
LE_EXPLOSION
LE_SPRITE_EXPLOSION
LE_FRAGMENT
LE_MOVE_SCALE_FADE
LE_FALL_SCALE_FADE
LE_FADE_RGB
LE_SCALE_FADE
LE_SCOREPLUM
enum q3print_t
Enumerator:
SYSTEM_PRINT
CHAT_PRINT
TEAMCHAT_PRINT
Function Documentation
void CG_AddBufferedSound (sfxHandle_t sfx)
References cg, MAX_SOUNDBUFFER, cg_t::soundBuffer, cg_t::soundBufferIn, and cg_t::soundBufferOut.
Referenced by CG_CheckLocalSounds(), and CG_EntityEvent().
void CG_AddLagometerFrameInfo (void)
References cg, lagometer_t::frameCount, lagometer_t::frameSamples, LAG_SAMPLES, cg_t::latestSnapshotTime, and cg_t::time.
Referenced by CG_DrawActiveFrame().
void CG_AddLagometerSnapshotInfo (snapshot_t * snap)
References LAG_SAMPLES, snapshot_t::ping, snapshot_t::snapFlags, lagometer_t::snapshotCount, lagometer_t::snapshotFlags, and lagometer_t::snapshotSamples.
Referenced by CG_ReadNextSnapshot().
void CG_AddLocalEntities (void)
References cg, cg_activeLocalEntities, CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddMoveScaleFade(), CG_AddScaleFade(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_Error(), CG_FreeLocalEntity(), localEntity_s::endTime, LE_EXPLOSION, LE_FADE_RGB, LE_FALL_SCALE_FADE, LE_FRAGMENT, LE_MARK, LE_MOVE_SCALE_FADE, LE_SCALE_FADE, LE_SCOREPLUM, LE_SPRITE_EXPLOSION, localEntity_s::leType, localEntity_s::prev, and cg_t::time.
Referenced by CG_DrawActiveFrame().
void CG_AddMarks (void)
References markPoly_s::alphaFade, cg, cg_activeMarkPolys, cg_addMarks, CG_FreeMarkPoly(), cgs, markPoly_s::color, cgMedia_t::energyMarkShader, vmCvar_t::integer, MARK_FADE_TIME, MARK_TOTAL_TIME, markPoly_s::markShader, cgs_t::media, polyVert_t::modulate, markPoly_s::nextMark, poly_s::numVerts, markPoly_s::poly, t, markPoly_s::time, cg_t::time, trap_R_AddPolyToScene(), and markPoly_s::verts.
Referenced by CG_DrawActiveFrame().
void CG_AddPacketEntities (void)
References AnglesToAxis(), cg_t::autoAngles, cg_t::autoAnglesFast, cg_t::autoAxis, cg_t::autoAxisFast, BG_PlayerStateToEntityState(), cg, CG_AddCEntity(), CG_CalcEntityLerpPositions(), cg_entities, playerState_s::clientNum, centity_s::currentState, snapshot_t::entities, cg_t::frameInterpolation, cg_t::nextSnap, entityState_s::number, snapshot_t::numEntities, cg_t::predictedPlayerEntity, cg_t::predictedPlayerState, snapshot_t::ps, qfalse, snapshot_t::serverTime, cg_t::snap, and cg_t::time.
Referenced by CG_DrawActiveFrame().
void CG_AddParticles (void)
References particle_s::accel, particle_s::alpha, particle_s::alphavel, AngleVectors(), cg, CG_AddParticleToScene(), CG_ClearParticles(), particle_s::color, particle_s::endtime, free_particles, initparticles, particle_s::next, NULL, oldtime, particle_s::org, P_ANIM, P_BAT, P_BLEED, P_FLAT_SCALEUP_FADE, P_SMOKE, P_SMOKE_IMPACT, P_SPRITE, P_WEATHER_FLURRY, cg_t::refdef, rforward, ROLL, roll, rright, rup, tail, particle_s::time, cg_t::time, particle_s::type, vectoangles(), VectorCopy, particle_s::vel, vforward, refdef_t::viewaxis, vright, and vup.
Referenced by CG_DrawActiveFrame().
void CG_AddParticleShrapnel (localEntity_t * le)
void CG_AddPlayerWeapon (refEntity_t * parent, playerState_t * ps, centity_t * cent, int team)
References AnglesToAxis(), refEntity_t::axis, orientation_t::axis, refEntity_t::backlerp, weaponInfo_s::barrelModel, Byte4Copy, clientInfo_t::c1RGBA, cg, CG_AddWeaponWithPowerups(), cg_drawGun, cg_entities, CG_LightningBolt(), CG_MachinegunSpinAngle(), CG_PositionRotatedEntityOnTag(), CG_RegisterWeapon(), cg_weapons, cgs, cgs_t::clientinfo, playerState_s::clientNum, entityState_s::clientNum, clientInfo_t::color1, crandom, centity_s::currentState, EF_FIRING, entityState_s::eFlags, weaponInfo_s::firingSound, weaponInfo_s::flashDlightColor, weaponInfo_s::flashModel, refEntity_t::frame, refEntity_t::hModel, vmCvar_t::integer, centity_s::lerpOrigin, refEntity_t::lightingOrigin, playerEntity_t::lightningFiring, MatrixMultiply(), MUZZLE_FLASH_TIME, centity_s::muzzleFlashTime, entityState_s::number, refEntity_t::oldframe, refEntity_t::origin, orientation_t::origin, centity_s::pe, PITCH, entityState_s::powerups, cg_t::predictedPlayerState, qfalse, qtrue, playerEntity_t::railFireTime, weaponInfo_s::readySound, refEntity_t::renderfx, cg_t::renderingThirdPerson, ROLL, refEntity_t::shaderRGBA, refEntity_t::shadowPlane, cg_t::time, trap_R_AddLightToScene(), trap_R_AddRefEntityToScene(), trap_R_LerpTag(), trap_S_AddLoopingSound(), vec3_origin, VectorCopy, VectorMA(), entityState_s::weapon, weaponInfo_s::weaponModel, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_LIGHTNING, WP_RAILGUN, and YAW.
Referenced by CG_AddViewWeapon(), and CG_Player().
void CG_AddRefEntityWithPowerups (refEntity_t * ent, entityState_t * state, int team)
References cgMedia_t::battleSuitShader, cg, cgs, refEntity_t::customShader, cgMedia_t::invisShader, cgs_t::media, entityState_s::powerups, PW_BATTLESUIT, PW_INVIS, PW_QUAD, PW_REGEN, cgMedia_t::quadShader, cgMedia_t::redQuadShader, cgMedia_t::regenShader, TEAM_RED, cg_t::time, and trap_R_AddRefEntityToScene().
Referenced by CG_Missile(), and CG_Player().
void CG_AddViewWeapon (playerState_t * ps)
References AnglesToAxis(), refEntity_t::axis, refEntity_t::backlerp, lerpFrame_t::backlerp, cg, CG_AddPlayerWeapon(), CG_CalculateWeaponPosition(), cg_drawGun, cg_entities, cg_fov, cg_gun_frame, cg_gun_x, cg_gun_y, cg_gun_z, CG_LightningBolt(), CG_MapTorsoToWeaponFrame(), CG_RegisterWeapon(), cg_weapons, cgs, cgs_t::clientinfo, playerState_s::clientNum, entityState_s::clientNum, centity_s::currentState, EF_FIRING, playerState_s::eFlags, refEntity_t::frame, lerpFrame_t::frame, weaponInfo_s::handsModel, refEntity_t::hModel, vmCvar_t::integer, refEntity_t::oldframe, lerpFrame_t::oldFrame, refEntity_t::origin, centity_s::pe, PERS_TEAM, playerState_s::persistant, PM_INTERMISSION, playerState_s::pm_type, cg_t::predictedPlayerEntity, cg_t::predictedPlayerState, cg_t::refdef, refEntity_t::renderfx, cg_t::renderingThirdPerson, RF_DEPTHHACK, RF_FIRST_PERSON, RF_MINLIGHT, TEAM_SPECTATOR, cg_t::testGun, playerEntity_t::torso, vmCvar_t::value, VectorCopy, VectorMA(), refdef_t::viewaxis, refdef_t::vieworg, and playerState_s::weapon.
Referenced by CG_DrawActiveFrame().
void CG_AdjustFrom640 (float * x, float * y, float * w, float * h)
References cgs, cgs_t::glconfig, cgs_t::screenXScale, cgs_t::screenYScale, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by CG_Draw3DModel(), CG_DrawChar(), CG_DrawCrosshair(), CG_DrawLagometer(), CG_DrawPic(), CG_DrawSides(), CG_DrawTopBottom(), and CG_FillRect().
void CG_AdjustPositionForMover (const vec3_t in, int moverNum, int fromTime, int toTime, vec3_t out)
References entityState_s::apos, BG_EvaluateTrajectory(), cg_entities, centity_s::currentState, ENTITYNUM_MAX_NORMAL, ET_MOVER, entityState_s::eType, entityState_s::pos, VectorAdd, VectorCopy, and VectorSubtract.
Referenced by CG_CalcEntityLerpPositions(), and CG_PredictPlayerState().
localEntity_t* CG_AllocLocalEntity (void)
References cg_activeLocalEntities, cg_freeLocalEntities, CG_FreeLocalEntity(), localEntity_s::next, and localEntity_s::prev.
Referenced by CG_Bleed(), CG_BubbleTrail(), CG_LaunchExplode(), CG_LaunchGib(), CG_MachineGunEjectBrass(), CG_MakeExplosion(), CG_PlasmaTrail(), CG_RailTrail(), CG_ScorePlum(), CG_ShotgunEjectBrass(), CG_SmokePuff(), and CG_SpawnEffect().
const char* CG_Argv (int arg)
References buffer, MAX_STRING_CHARS, and trap_Argv().
Referenced by CG_ConfigStringModified(), CG_ConsoleCommand(), CG_ParseScores(), CG_ParseTeamInfo(), CG_ServerCommand(), CG_TestModel_f(), CG_VoiceChat(), and CG_Weapon_f().
void CG_Beam (centity_t * cent)
References refEntity_t::axis, AxisClear(), centity_s::currentState, refEntity_t::oldorigin, refEntity_t::origin, entityState_s::origin2, entityState_s::pos, refEntity_t::renderfx, refEntity_t::reType, RF_NOSHADOW, RT_BEAM, trap_R_AddRefEntityToScene(), trajectory_t::trBase, and VectorCopy.
Referenced by CG_AddCEntity(), and CG_EntityEvent().
void CG_BigExplode (vec3_t playerOrigin)
References cg_blood, CG_LaunchExplode(), cgs, crandom, EXP_JUMP, EXP_VELOCITY, vmCvar_t::integer, cgs_t::media, cgMedia_t::smoke2, and VectorCopy.
void CG_Bleed (vec3_t origin, int entityNum)
References cgMedia_t::bloodExplosionShader, cg, CG_AllocLocalEntity(), cg_blood, cgs, playerState_s::clientNum, refEntity_t::customShader, localEntity_s::endTime, vmCvar_t::integer, LE_EXPLOSION, localEntity_s::leType, cgs_t::media, refEntity_t::origin, snapshot_t::ps, refEntity_t::radius, localEntity_s::refEntity, refEntity_t::renderfx, refEntity_t::reType, RF_THIRD_PERSON, refEntity_t::rotation, RT_SPRITE, cg_t::snap, localEntity_s::startTime, cg_t::time, and VectorCopy.
Referenced by CG_Bullet(), and CG_MissileHitPlayer().
void CG_BubbleTrail (vec3_t start, vec3_t end, float spacing)
References cg, CG_AllocLocalEntity(), cg_noProjectileTrail, cgs, localEntity_s::color, crandom, refEntity_t::customShader, localEntity_s::endTime, int(), vmCvar_t::integer, LE_MOVE_SCALE_FADE, LEF_PUFF_DONT_SCALE, localEntity_s::leFlags, localEntity_s::leType, localEntity_s::lifeRate, cgs_t::media, move(), localEntity_s::pos, refEntity_t::radius, random, re, localEntity_s::refEntity, refEntity_t::reType, refEntity_t::rotation, RT_SPRITE, refEntity_t::shaderRGBA, refEntity_t::shaderTime, localEntity_s::startTime, cg_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and cgMedia_t::waterBubbleShader.
Referenced by CG_Bullet(), CG_RocketTrail(), and CG_ShotgunPellet().
void CG_BuildSolidList (void)
References cg, cg_entities, cg_numSolidEntities, cg_numTriggerEntities, centity_s::currentState, snapshot_t::entities, ET_ITEM, ET_PUSH_TRIGGER, ET_TELEPORT_TRIGGER, entityState_s::eType, cg_t::nextFrameTeleport, cg_t::nextSnap, centity_s::nextState, entityState_s::number, snapshot_t::numEntities, cg_t::snap, entityState_s::solid, and cg_t::thisFrameTeleport.
Referenced by CG_SetInitialSnapshot(), and CG_SetNextSnap().
void CG_BuildSpectatorString (void)
References cgs_t::clientinfo, clientInfo_t::infoValid, MAX_CLIENTS, clientInfo_t::name, Q_strcat(), cg_t::spectatorLen, cg_t::spectatorList, cg_t::spectatorWidth, clientInfo_t::team, TEAM_SPECTATOR, and va().
Referenced by CG_ConfigStringModified(), CG_RegisterClients(), and CG_ScoresDown_f().
void CG_Bullet (vec3_t origin, int sourceEntityNum, vec3_t normal, qboolean flesh, int fleshEntityNum)
References CG_Bleed(), CG_BubbleTrail(), CG_CalcMuzzlePoint(), CG_MissileHitWall(), CG_PointContents(), CG_Tracer(), cg_tracerChance, CONTENTS_WATER, trace_t::endpos, IMPACTSOUND_DEFAULT, NULL, random, start, trap_CM_BoxTrace(), vmCvar_t::value, and WP_MACHINEGUN.
Referenced by CG_EntityEvent().
void CG_CenterPrint (const char * str, int y, int charWidth)
References cg_t::centerPrint, cg_t::centerPrintCharWidth, cg_t::centerPrintLines, cg_t::centerPrintTime, cg_t::centerPrintY, cg, Q_strncpyz(), s, and cg_t::time.
Referenced by CG_MapRestart(), CG_Obituary(), CG_ServerCommand(), and CG_UseItem().
void CG_CheckChangedPredictableEvents (playerState_t * ps)
References cg, CG_EntityEvent(), CG_Printf(), cg_showmiss, centity_s::currentState, entityState_s::event, entityState_s::eventParm, playerState_s::eventParms, playerState_s::events, cg_t::eventSequence, playerState_s::eventSequence, vmCvar_t::integer, centity_s::lerpOrigin, MAX_PREDICTED_EVENTS, MAX_PS_EVENTS, cg_t::predictableEvents, and cg_t::predictedPlayerEntity.
void CG_CheckEvents (centity_t * cent)
References BG_EvaluateTrajectory(), cg, CG_EntityEvent(), CG_SetEntitySoundPosition(), centity_s::currentState, EF_PLAYER_EVENT, entityState_s::eFlags, ET_EVENTS, entityState_s::eType, EV_EVENT_BITS, entityState_s::event, centity_s::lerpOrigin, entityState_s::number, entityState_s::otherEntityNum, entityState_s::pos, centity_s::previousEvent, snapshot_t::serverTime, and cg_t::snap.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionEntity().
void CG_CheckOrderPending (void)
References b, cg, cgs, playerState_s::clientNum, cgs_t::currentOrder, cgs_t::gametype, GT_CTF, NULL, numSortedTeamPlayers, cgs_t::orderPending, snapshot_t::ps, qfalse, cg_t::snap, sortedTeamPlayers, TEAMTASK_CAMP, TEAMTASK_DEFENSE, TEAMTASK_ESCORT, TEAMTASK_FOLLOW, TEAMTASK_OFFENSE, TEAMTASK_PATROL, TEAMTASK_RETRIEVE, trap_SendConsoleCommand(), va(), VOICECHAT_CAMP, VOICECHAT_DEFEND, VOICECHAT_FOLLOWFLAGCARRIER, VOICECHAT_FOLLOWME, VOICECHAT_OFFENSE, VOICECHAT_ONCAMPING, VOICECHAT_ONDEFENSE, VOICECHAT_ONFOLLOW, VOICECHAT_ONFOLLOWCARRIER, VOICECHAT_ONGETFLAG, VOICECHAT_ONOFFENSE, VOICECHAT_ONPATROL, VOICECHAT_PATROL, and VOICECHAT_RETURNFLAG.
Referenced by CG_Draw2D(), CG_SelectNextPlayer(), and CG_SelectPrevPlayer().
void CG_ClearParticles (void)
References cg, cl_numparticles, initparticles, particle_s::next, NULL, numShaderAnims, oldtime, qtrue, shaderAnimCounts, shaderAnimNames, shaderAnims, cg_t::time, trap_R_RegisterShader(), particle_s::type, and va().
Referenced by CG_AddParticles(), CG_MapRestart(), and CG_RegisterGraphics().
void CG_ColorForHealth (vec4_t hcolor)
References cg, CG_GetColorForHealth(), snapshot_t::ps, cg_t::snap, STAT_ARMOR, STAT_HEALTH, and playerState_s::stats.
Referenced by CG_DrawCrosshair(), and CG_DrawStatusBar().
const char* CG_ConfigString (int index)
References CG_Error(), cgs_t::gameState, MAX_CONFIGSTRINGS, gameState_t::stringData, and gameState_t::stringOffsets.
Referenced by CG_ConfigStringModified(), CG_DrawAttacker(), CG_DrawInformation(), CG_DrawNewTeamInfo(), CG_DrawOldTourneyScoreboard(), CG_DrawPlayerLocation(), CG_DrawSelectedPlayerLocation(), CG_DrawTeamOverlay(), CG_EntityEvent(), CG_ForceModelChange(), CG_Init(), CG_LoadingClient(), CG_NewClientInfo(), CG_NewParticleArea(), CG_Obituary(), CG_ParseServerinfo(), CG_ParseWarmup(), CG_RegisterClients(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_SetConfigValues(), CG_ShaderStateChanged(), and CG_StartMusic().
qboolean CG_ConsoleCommand (void)
References ARRAY_LEN, CG_Argv(), consoleCommand_t::function, Q_stricmp(), qfalse, and qtrue.
Referenced by vmMain().
int CG_CrosshairPlayer (void)
References cg_t::crosshairClientNum, cg_t::crosshairClientTime, and cg_t::time.
Referenced by CG_TargetCommand_f(), CG_TellTarget_f(), CG_VoiceTellTarget_f(), and vmMain().
sfxHandle_t CG_CustomSound (int clientNum, const char * soundName)
References cg_customSoundNames, CG_Error(), cgs, cgs_t::clientinfo, MAX_CLIENTS, MAX_CUSTOM_SOUNDS, qfalse, clientInfo_t::sounds, and trap_S_RegisterSound().
Referenced by CG_EntityEvent(), and CG_PainEvent().
void CG_Draw3DModel (float x, float y, float w, float h, qhandle_t model, qhandle_t skin, vec3_t origin, vec3_t angles)
References AnglesToAxis(), refEntity_t::axis, AxisClear(), cg, CG_AdjustFrom640(), cg_draw3dIcons, cg_drawIcons, refEntity_t::customSkin, refdef_t::fov_x, refdef_t::fov_y, h, refdef_t::height, refEntity_t::hModel, vmCvar_t::integer, refEntity_t::origin, RDF_NOWORLDMODEL, refdef_t::rdflags, refEntity_t::renderfx, RF_NOSHADOW, refdef_t::time, cg_t::time, trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RenderScene(), VectorCopy, refdef_t::viewaxis, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by CG_DrawFlagModel(), CG_DrawHead(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerItem(), CG_DrawSelectedPlayerHead(), CG_DrawStatusBar(), and CG_HarvesterSkulls().
void CG_DrawActive (stereoFrame_t stereoView)
References cg, CG_Draw2D(), CG_DrawCrosshair3D(), CG_DrawInformation(), CG_DrawTourneyScoreboard(), CG_TileClear(), PERS_TEAM, playerState_s::persistant, playerState_s::pm_flags, PMF_SCOREBOARD, snapshot_t::ps, cg_t::refdef, cg_t::snap, STEREO_CENTER, TEAM_SPECTATOR, and trap_R_RenderScene().
Referenced by CG_DrawActiveFrame().
void CG_DrawActiveFrame (int serverTime, stereoFrame_t stereoView, qboolean demoPlayback)
References snapshot_t::areamask, refdef_t::areamask, cg, CG_AddLagometerFrameInfo(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddPacketEntities(), CG_AddParticles(), CG_AddTestModel(), CG_AddViewWeapon(), CG_CalcViewValues(), CG_DamageBlendBlob(), CG_DrawActive(), CG_DrawInformation(), CG_PlayBufferedSounds(), CG_PlayBufferedVoiceChats(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_Printf(), CG_ProcessSnapshots(), cg_stats, cg_thirdPerson, cg_timescale, cg_timescaleFadeEnd, cg_timescaleFadeSpeed, CG_UpdateCvars(), cg_t::clientFrame, playerState_s::clientNum, cg_t::demoPlayback, cg_t::frametime, refEntity_t::hModel, cg_t::hyperspace, cg_t::infoScreenText, vmCvar_t::integer, cg_t::oldTime, cg_t::predictedPlayerState, snapshot_t::ps, qfalse, cg_t::refdef, cg_t::renderingThirdPerson, cg_t::snap, SNAPFLAG_NOT_ACTIVE, snapshot_t::snapFlags, STAT_HEALTH, playerState_s::stats, STEREO_RIGHT, cg_t::testModelEntity, refdef_t::time, cg_t::time, trap_Cvar_Set(), trap_R_ClearScene(), trap_S_ClearLoopingSounds(), trap_S_Respatialize(), trap_SetUserCmdValue(), va(), vmCvar_t::value, refdef_t::viewaxis, refdef_t::vieworg, cg_t::weaponSelect, and cg_t::zoomSensitivity.
Referenced by vmMain().
void CG_DrawBigString (int x, int y, const char * s, float alpha)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, CG_DrawStringExt(), qfalse, and qtrue.
Referenced by CG_DrawAmmoWarning(), CG_DrawAttacker(), CG_DrawClientScore(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawScores(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawTimer(), and CG_DrawWarmup().
void CG_DrawBigStringColor (int x, int y, const char * s, vec4_t color)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, CG_DrawStringExt(), and qtrue.
Referenced by CG_DrawClientScore(), and CG_DrawWeaponSelect().
void CG_DrawFlagModel (float x, float y, float w, float h, int team, qboolean force2D)
References BG_FindItemForPowerup(), cgMedia_t::blueFlagModel, cg, cg_draw3dIcons, CG_Draw3DModel(), cg_drawIcons, CG_DrawPic(), cg_items, cgs, cm, icon(), vmCvar_t::integer, ITEM_INDEX, cgs_t::media, cgMedia_t::neutralFlagModel, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, cgMedia_t::redFlagModel, TEAM_BLUE, TEAM_FREE, TEAM_RED, cg_t::time, trap_R_ModelBounds(), VectorClear, and YAW.
Referenced by CG_DrawClientScore(), CG_DrawPlayerHasFlag(), and CG_DrawStatusBarFlag().
void CG_DrawHead (float x, float y, float w, float h, int clientNum, vec3_t headAngles)
References cg_draw3dIcons, CG_Draw3DModel(), cg_drawIcons, CG_DrawPic(), cgs, cgs_t::clientinfo, cm, clientInfo_t::deferred, cgMedia_t::deferShader, clientInfo_t::headModel, clientInfo_t::headOffset, clientInfo_t::headSkin, vmCvar_t::integer, cgs_t::media, clientInfo_t::modelIcon, trap_R_ModelBounds(), and VectorAdd.
Referenced by CG_DrawAttacker(), CG_DrawBlueFlagHead(), CG_DrawClientScore(), CG_DrawPlayerHead(), CG_DrawRedFlagHead(), and CG_DrawStatusBarHead().
void CG_DrawInformation (void)
References cg, CG_ConfigString(), CG_DrawLoadingIcons(), CG_DrawPic(), cgs, colorWhite, CS_MESSAGE, CS_MOTD, CS_SERVERINFO, CS_SYSTEMINFO, cgs_t::gametype, cgs_t::glconfig, GT_1FCTF, GT_CTF, GT_FFA, GT_HARVESTER, GT_OBELISK, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, info, Info_ValueForKey(), cg_t::infoScreenText, NULL, PROP_HEIGHT, Q_CleanStr(), Q_strncpyz(), s, SCREEN_HEIGHT, SCREEN_WIDTH, trap_Cvar_VariableStringBuffer(), trap_R_DrawStretchPic(), trap_R_RegisterShader(), trap_R_RegisterShaderNoMip(), trap_R_SetColor(), UI_CENTER, UI_DrawProportionalString(), UI_DROPSHADOW, UI_SMALLFONT, va(), value(), glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by CG_DrawActive(), and CG_DrawActiveFrame().
qboolean CG_DrawOldScoreboard (void)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, cg, CG_DrawBigString(), CG_DrawClientScore(), CG_DrawPic(), CG_DrawStrlen(), CG_DrawTeamBackground(), CG_FadeColor(), CG_LoadDeferredPlayers(), cg_paused, CG_PlaceString(), CG_TeamScoreboard(), cgs, score_t::client, playerState_s::clientNum, colorWhite, cg_t::deferredPlayerLoading, FADE_TIME, cgs_t::gametype, GT_SINGLE_PLAYER, GT_TEAM, vmCvar_t::integer, cg_t::killerName, localClient, cgs_t::media, cg_t::numScores, PERS_RANK, PERS_SCORE, PERS_TEAM, playerState_s::persistant, PM_DEAD, PM_INTERMISSION, playerState_s::pm_type, cg_t::predictedPlayerState, snapshot_t::ps, qfalse, qtrue, s, SB_HEADER, SB_INTER_HEIGHT, SB_MAXCLIENTS_INTER, SB_MAXCLIENTS_NORMAL, SB_NAME_X, SB_NORMAL_HEIGHT, SB_PING_X, SB_RATING_WIDTH, SB_SCORE_X, SB_TIME_X, SB_TOP, cgMedia_t::scoreboardName, cgMedia_t::scoreboardPing, cgMedia_t::scoreboardScore, cgMedia_t::scoreboardTime, cg_t::scoreFadeTime, cg_t::scores, SCREEN_WIDTH, cg_t::showScores, cg_t::snap, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, cg_t::teamScores, va(), and cg_t::warmup.
Referenced by CG_DrawScoreboard().
void CG_DrawOldTourneyScoreboard (void)
References cg, CG_CenterGiantLine(), CG_ConfigString(), CG_DrawStringExt(), CG_FillRect(), cgs, cgs_t::clientinfo, CS_MOTD, cgs_t::gametype, GIANT_HEIGHT, GIANT_WIDTH, GT_TEAM, clientInfo_t::infoValid, MAX_CLIENTS, clientInfo_t::name, ones, qtrue, s, clientInfo_t::score, cg_t::scoresRequestTime, SCREEN_HEIGHT, SCREEN_WIDTH, clientInfo_t::team, TEAM_FREE, cg_t::teamScores, cg_t::time, trap_SendClientCommand(), and va().
Referenced by CG_DrawTourneyScoreboard().
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
References CG_AdjustFrom640(), and trap_R_DrawStretchPic().
Referenced by CG_DrawAreaPowerUp(), CG_DrawBlueFlagStatus(), CG_DrawClientScore(), CG_DrawCTFPowerUp(), CG_DrawDisconnect(), CG_DrawField(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawHoldableItem(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawLoadingIcons(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawPlayerScore(), CG_DrawPlayerStatus(), CG_DrawPowerups(), CG_DrawRedFlagStatus(), CG_DrawReward(), CG_DrawScores(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), CG_DrawStatusBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawWeaponSelect(), CG_HarvesterSkulls(), and CG_OneFlagStatus().
void CG_DrawRect (float x, float y, float width, float height, float size, const float * color)
References CG_DrawSides(), CG_DrawTopBottom(), NULL, and trap_R_SetColor().
void CG_DrawSides (float x, float y, float w, float h, float size)
References CG_AdjustFrom640(), cgs, cgs_t::media, cgs_t::screenXScale, trap_R_DrawStretchPic(), and cgMedia_t::whiteShader.
Referenced by CG_DrawRect().
void CG_DrawSmallString (int x, int y, const char * s, float alpha)
References CG_DrawStringExt(), qfalse, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by CG_DrawTeamVote(), and CG_DrawVote().
void CG_DrawSmallStringColor (int x, int y, const char * s, vec4_t color)
References CG_DrawStringExt(), qfalse, qtrue, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by CG_DrawClientScore().
void CG_DrawString (float x, float y, const char * string, float charWidth, float charHeight, const float * modulate)
void CG_DrawStringExt (int x, int y, const char * string, const float * setColor, qboolean forceColor, qboolean shadow, int charWidth, int charHeight, int maxChars)
References CG_DrawChar(), ColorIndex, g_color_table, NULL, Q_IsColorString, s, string(), trap_R_SetColor(), and xx.
Referenced by CG_CenterGiantLine(), CG_DrawBigString(), CG_DrawBigStringColor(), CG_DrawCenterString(), CG_DrawFollow(), CG_DrawOldTourneyScoreboard(), CG_DrawReward(), CG_DrawSmallString(), CG_DrawSmallStringColor(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), and CG_DrawWarmup().
int CG_DrawStrlen (const char * str)
References count, Q_IsColorString, and s.
Referenced by CG_CenterGiantLine(), CG_DrawAmmoWarning(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawOldScoreboard(), CG_DrawReward(), CG_DrawScores(), CG_DrawSnapshot(), CG_DrawTeamOverlay(), CG_DrawTimer(), CG_DrawWarmup(), and CG_DrawWeaponSelect().
void CG_DrawTeamBackground (int x, int y, int w, int h, float alpha, int team)
References CG_DrawPic(), cgs, cgs_t::media, NULL, TEAM_BLUE, TEAM_RED, cgMedia_t::teamStatusBar, and trap_R_SetColor().
Referenced by CG_DrawOldScoreboard(), CG_DrawStatusBar(), and CG_DrawTeamColor().
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
References CG_AdjustFrom640(), cgs, cgs_t::media, cgs_t::screenYScale, trap_R_DrawStretchPic(), and cgMedia_t::whiteShader.
Referenced by CG_DrawRect().
void CG_DrawWeaponSelect (void)
References playerState_s::ammo, BIGCHAR_WIDTH, bits(), cg, CG_DrawBigStringColor(), CG_DrawPic(), CG_DrawStrlen(), CG_FadeColor(), CG_RegisterWeapon(), cg_weapons, cgs, count, weaponInfo_s::item, cg_t::itemPickupTime, MAX_WEAPONS, cgs_t::media, cgMedia_t::noammoShader, NULL, gitem_s::pickup_name, cg_t::predictedPlayerState, snapshot_t::ps, SCREEN_WIDTH, cgMedia_t::selectShader, cg_t::snap, STAT_HEALTH, STAT_WEAPONS, playerState_s::stats, trap_R_SetColor(), WEAPON_SELECT_TIME, cg_t::weaponSelect, and cg_t::weaponSelectTime.
Referenced by CG_Draw2D().
void CG_EntityEvent (centity_t * cent, vec3_t position)
References entityState_s::angles, bg_itemlist, bg_numItems, cgMedia_t::blueFlagReturnedSound, cgMedia_t::blueLeadsSound, cgMedia_t::blueScoredSound, ByteToDir(), cgMedia_t::captureOpponentSound, cgMedia_t::captureYourTeamSound, cg, CG_AddBufferedSound(), CG_Beam(), CG_Bullet(), CG_ConfigString(), CG_CustomSound(), cg_debugEvents, cg_drawGun, CG_Error(), CG_FireWeapon(), cg_footsteps, CG_GibPlayer(), CG_ItemPickup(), CG_MissileHitPlayer(), CG_MissileHitWall(), cg_nopredict, CG_Obituary(), CG_OutOfAmmoChange(), CG_PainEvent(), CG_Printf(), CG_RailTrail(), CG_ScorePlum(), CG_ShotgunFire(), CG_SmokePuff(), CG_SpawnEffect(), cg_synchronousClients, CG_UseItem(), CG_VoiceChatLocal(), CG_WaterLevel(), cgs, CHAN_ANNOUNCER, CHAN_AUTO, CHAN_BODY, CHAN_ITEM, CHAN_VOICE, cgs_t::clientinfo, cg_t::clientNum, playerState_s::clientNum, entityState_s::clientNum, COLOR_CYAN, CS_SOUNDS, centity_s::currentState, DEBUGNAME, cg_t::demoPlayback, EF_KAMIKAZE, entityState_s::eFlags, cgMedia_t::enemyTookTheFlagSound, cgMedia_t::enemyTookYourFlagSound, ENTITYNUM_WORLD, EV_BULLET_HIT_FLESH, EV_BULLET_HIT_WALL, EV_CHANGE_WEAPON, EV_DEATH1, EV_DEATH2, EV_DEATH3, EV_DEBUG_LINE, EV_EVENT_BITS, EV_FALL_FAR, EV_FALL_MEDIUM, EV_FALL_SHORT, EV_FIRE_WEAPON, EV_FOOTSPLASH, EV_FOOTSTEP, EV_FOOTSTEP_METAL, EV_FOOTWADE, EV_GENERAL_SOUND, EV_GIB_PLAYER, EV_GLOBAL_ITEM_PICKUP, EV_GLOBAL_SOUND, EV_GLOBAL_TEAM_SOUND, EV_GRENADE_BOUNCE, EV_INVUL_IMPACT, EV_ITEM_PICKUP, EV_ITEM_POP, EV_ITEM_RESPAWN, EV_JUICED, EV_JUMP, EV_JUMP_PAD, EV_KAMIKAZE, EV_LIGHTNINGBOLT, EV_MISSILE_HIT, EV_MISSILE_MISS, EV_MISSILE_MISS_METAL, EV_NOAMMO, EV_OBELISKEXPLODE, EV_OBELISKPAIN, EV_OBITUARY, EV_PAIN, EV_PLAYER_TELEPORT_IN, EV_PLAYER_TELEPORT_OUT, EV_POWERUP_BATTLESUIT, EV_POWERUP_QUAD, EV_POWERUP_REGEN, EV_PROXIMITY_MINE_STICK, EV_PROXIMITY_MINE_TRIGGER, EV_RAILTRAIL, EV_SCOREPLUM, EV_SHOTGUN, EV_STEP_12, EV_STEP_16, EV_STEP_4, EV_STEP_8, EV_STOPLOOPINGSOUND, EV_SWIM, EV_TAUNT, EV_TAUNT_FOLLOWME, EV_TAUNT_GETFLAG, EV_TAUNT_GUARDBASE, EV_TAUNT_NO, EV_TAUNT_PATROL, EV_TAUNT_YES, EV_USE_ITEM0, EV_USE_ITEM1, EV_USE_ITEM10, EV_USE_ITEM11, EV_USE_ITEM12, EV_USE_ITEM13, EV_USE_ITEM14, EV_USE_ITEM2, EV_USE_ITEM3, EV_USE_ITEM4, EV_USE_ITEM5, EV_USE_ITEM6, EV_USE_ITEM7, EV_USE_ITEM8, EV_USE_ITEM9, EV_WATER_CLEAR, EV_WATER_LEAVE, EV_WATER_TOUCH, EV_WATER_UNDER, entityState_s::event, entityState_s::eventParm, FOOTSTEP_METAL, FOOTSTEP_SPLASH, clientInfo_t::footsteps, cgMedia_t::footsteps, cgs_t::gameSounds, cgs_t::gametype, cgMedia_t::gibSound, gitem_s::giTag, gitem_s::giType, GT_1FCTF, GTS_BLUE_CAPTURE, GTS_BLUE_RETURN, GTS_BLUE_TAKEN, GTS_BLUEOBELISK_ATTACKED, GTS_BLUETEAM_SCORED, GTS_BLUETEAM_TOOK_LEAD, GTS_KAMIKAZE, GTS_RED_CAPTURE, GTS_RED_RETURN, GTS_RED_TAKEN, GTS_REDOBELISK_ATTACKED, GTS_REDTEAM_SCORED, GTS_REDTEAM_TOOK_LEAD, GTS_TEAMS_ARE_TIED, cgMedia_t::hgrenb1aSound, cgMedia_t::hgrenb2aSound, IMPACTSOUND_DEFAULT, IMPACTSOUND_METAL, vmCvar_t::integer, IT_PERSISTANT_POWERUP, IT_POWERUP, IT_TEAM, cgMedia_t::jumpPadSound, cg_t::landChange, cgMedia_t::landSound, cg_t::landTime, LEF_PUFF_DONT_SCALE, centity_s::lerpOrigin, entityState_s::loopSound, MAX_CLIENTS, MAX_STEP_CHANGE, cgs_t::media, centity_s::miscTime, cgMedia_t::n_healthSound, NULL, entityState_s::number, entityState_s::origin2, entityState_s::otherEntityNum, playerEntity_t::painTime, centity_s::pe, gitem_s::pickup_sound, playerState_s::pm_flags, PMF_FOLLOW, entityState_s::pos, cg_t::powerupActive, playerState_s::powerups, cg_t::powerupTime, cg_t::predictedPlayerState, cgMedia_t::protectSound, snapshot_t::ps, PW_AMMOREGEN, PW_BATTLESUIT, PW_BLUEFLAG, PW_DOUBLER, PW_GUARD, PW_NEUTRALFLAG, PW_QUAD, PW_REDFLAG, PW_REGEN, PW_SCOUT, qfalse, qtrue, cgMedia_t::quadSound, cgMedia_t::redFlagReturnedSound, cgMedia_t::redLeadsSound, cgMedia_t::redScoredSound, cg_t::refdef, cgMedia_t::regenSound, cg_t::renderingThirdPerson, cgMedia_t::respawnSound, cgMedia_t::returnOpponentSound, cgMedia_t::returnYourTeamSound, s, SAY_TEAM, cgMedia_t::selectSound, cgMedia_t::smokePuffShader, cg_t::snap, STEP_TIME, cg_t::stepChange, cg_t::stepTime, SURF_FLESH, SURF_METALSTEPS, clientInfo_t::team, TEAM_BLUE, TEAM_RED, cgMedia_t::teamsTiedSound, cgMedia_t::teleInSound, cgMedia_t::teleOutSound, cg_t::time, entityState_s::time, trap_S_RegisterSound(), trap_S_StartLocalSound(), trap_S_StartSound(), trap_S_StopLoopingSound(), trajectory_t::trBase, up, va(), VectorMA(), refdef_t::viewaxis, VOICECHAT_FOLLOWME, VOICECHAT_NO, VOICECHAT_ONDEFENSE, VOICECHAT_ONGETFLAG, VOICECHAT_ONPATROL, VOICECHAT_YES, cgMedia_t::watrInSound, cgMedia_t::watrOutSound, cgMedia_t::watrUnSound, entityState_s::weapon, WP_RAILGUN, cgMedia_t::wstbactvSound, cgMedia_t::wstbimpdSound, cgMedia_t::wstbimplSound, cgMedia_t::wstbimpmSound, cgMedia_t::yourBaseIsUnderAttackSound, cgMedia_t::yourTeamTookEnemyFlagSound, and cgMedia_t::yourTeamTookTheFlagSound.
Referenced by CG_CheckChangedPredictableEvents(), CG_CheckEvents(), and CG_CheckPlayerstateEvents().
void QDECL void QDECL CG_Error (const char * msg, ...)
Referenced by CG_AddCEntity(), CG_AddLocalEntities(), CG_ConfigString(), CG_CustomSound(), CG_EntityEvent(), CG_FireWeapon(), CG_FreeLocalEntity(), CG_FreeMarkPoly(), CG_ImpactMark(), CG_Init(), CG_InterpolateEntityPosition(), CG_Item(), CG_LoadClientInfo(), CG_MakeExplosion(), CG_Obituary(), CG_ParseTeamInfo(), CG_ParticleExplosion(), CG_Player(), CG_PlayerAngles(), CG_ProcessSnapshots(), CG_RegisterItemSounds(), CG_RegisterItemVisuals(), CG_RegisterWeapon(), CG_SetLerpFrameAnimation(), CG_TransitionSnapshot(), Com_Error(), and vmMain().
void CG_EventHandling (int type)
References CG_HideTeamMenu(), CGAME_EVENT_NONE, CGAME_EVENT_SCOREBOARD, CGAME_EVENT_TEAMMENU, cgs, cgs_t::eventHandling, and type().
Referenced by CG_KeyEvent(), and vmMain().
void CG_ExecuteNewServerCommands (int latestSequence)
References CG_ServerCommand(), cgs, cgs_t::serverCommandSequence, and trap_GetServerCommand().
Referenced by CG_SetInitialSnapshot(), and CG_TransitionSnapshot().
float* CG_FadeColor (int startMsec, int totalMsec)
References cg, FADE_TIME, NULL, t, and cg_t::time.
Referenced by CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawReward(), CG_DrawScoreboard(), and CG_DrawWeaponSelect().
void CG_FillRect (float x, float y, float width, float height, const float * color)
References CG_AdjustFrom640(), cgs, cgs_t::media, NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), and cgMedia_t::whiteShader.
Referenced by CG_DrawClientScore(), CG_DrawOldTourneyScoreboard(), and CG_DrawScores().
void CG_FireWeapon (centity_t * cent)
References cg, cg_brassTime, CG_Error(), cg_weapons, cgs, CHAN_ITEM, CHAN_WEAPON, centity_s::currentState, weaponInfo_s::ejectBrassFunc, weaponInfo_s::flashSound, vmCvar_t::integer, playerEntity_t::lightningFiring, cgs_t::media, centity_s::muzzleFlashTime, NULL, entityState_s::number, centity_s::pe, entityState_s::powerups, PW_QUAD, cgMedia_t::quadSound, playerEntity_t::railFireTime, cg_t::time, trap_S_StartSound(), entityState_s::weapon, WP_LIGHTNING, WP_NONE, WP_NUM_WEAPONS, and WP_RAILGUN.
Referenced by CG_EntityEvent().
const char* CG_GameTypeString (void)
References cgs, cgs_t::gametype, GT_1FCTF, GT_CTF, GT_FFA, GT_HARVESTER, GT_OBELISK, and GT_TEAM.
Referenced by CG_DrawGameType().
void CG_GetColorForHealth (int health, int armor, vec4_t hcolor)
References ARMOR_PROTECTION, count, and VectorClear.
Referenced by CG_ColorForHealth(), CG_DrawNewTeamInfo(), and CG_DrawTeamOverlay().
const char* CG_GetGameStatusText (void)
References cg, CG_PlaceString(), cgs, cgs_t::gametype, GT_TEAM, PERS_RANK, PERS_SCORE, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, s, cg_t::snap, TEAM_SPECTATOR, cg_t::teamScores, and va().
Referenced by CG_DrawGameStatus().
const char* CG_GetKillerText (void)
References cg, cg_t::killerName, s, and va().
Referenced by CG_DrawKiller().
score_t* CG_GetSelectedScore (void)
void CG_GetTeamColor (vec4_t * color)
References cg, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, cg_t::snap, TEAM_BLUE, and TEAM_RED.
float CG_GetValue (int ownerDraw)
References playerState_s::ammo, clientInfo_t::armor, cg, CG_BLUE_SCORE, cg_entities, CG_GetSelectedPlayer(), CG_PLAYER_AMMO_VALUE, CG_PLAYER_ARMOR_VALUE, CG_PLAYER_HEALTH, CG_PLAYER_SCORE, CG_RED_SCORE, CG_SELECTEDPLAYER_ARMOR, CG_SELECTEDPLAYER_HEALTH, cgs, cgs_t::clientinfo, playerState_s::clientNum, centity_s::currentState, clientInfo_t::health, PERS_SCORE, playerState_s::persistant, snapshot_t::ps, cgs_t::scores1, cgs_t::scores2, cg_t::snap, sortedTeamPlayers, STAT_ARMOR, STAT_HEALTH, playerState_s::stats, and entityState_s::weapon.
void CG_GibPlayer (vec3_t playerOrigin)
References cg_blood, cg_gibs, CG_LaunchGib(), cgs, crandom, GIB_JUMP, GIB_VELOCITY, cgMedia_t::gibAbdomen, cgMedia_t::gibArm, cgMedia_t::gibBrain, cgMedia_t::gibChest, cgMedia_t::gibFist, cgMedia_t::gibFoot, cgMedia_t::gibForearm, cgMedia_t::gibIntestine, cgMedia_t::gibLeg, cgMedia_t::gibSkull, vmCvar_t::integer, cgs_t::media, and VectorCopy.
Referenced by CG_EntityEvent().
void CG_GrappleTrail (centity_t * ent, const weaponInfo_t * wi)
References AngleVectors(), refEntity_t::axis, AxisClear(), BG_EvaluateTrajectory(), cg, cg_entities, cgs, centity_s::currentState, refEntity_t::customShader, Distance(), forward, centity_s::lerpAngles, centity_s::lerpOrigin, cgMedia_t::lightningShader, cgs_t::media, NULL, refEntity_t::oldorigin, refEntity_t::origin, entityState_s::otherEntityNum, entityState_s::pos, refEntity_t::reType, RT_LIGHTNING, refEntity_t::shaderRGBA, cg_t::time, centity_s::trailTime, trap_R_AddRefEntityToScene(), up, VectorCopy, and VectorMA().
Referenced by CG_Grapple(), and CG_RegisterWeapon().
void CG_ImpactMark (qhandle_t markShader, const vec3_t origin, const vec3_t dir, float orientation, float r, float g, float b, float a, qboolean alphaFade, float radius, qboolean temporary)
References markPoly_s::alphaFade, cg, cg_addMarks, CG_AllocMark(), CG_Error(), markPoly_s::color, CrossProduct(), DotProduct, markFragment_t::firstPoint, vmCvar_t::integer, markPoly_s::markShader, markTotal, MAX_MARK_FRAGMENTS, MAX_MARK_POINTS, MAX_VERTS_ON_POLY, polyVert_t::modulate, markFragment_t::numPoints, poly_s::numVerts, PerpendicularVector(), markPoly_s::poly, RotatePointAroundVector(), polyVert_t::st, markPoly_s::time, cg_t::time, trap_CM_MarkFragments(), trap_R_AddPolyToScene(), VectorCopy, VectorNormalize2(), VectorScale, VectorSubtract, markPoly_s::verts, and polyVert_t::xyz.
Referenced by CG_FragmentBounceMark(), CG_MissileHitWall(), and CG_PlayerShadow().
void CG_InitConsoleCommands (void)
References ARRAY_LEN, and trap_AddCommand().
Referenced by CG_Init().
void CG_InitLocalEntities (void)
References cg_activeLocalEntities, cg_localEntities, MAX_LOCAL_ENTITIES, localEntity_s::next, and localEntity_s::prev.
Referenced by CG_Init(), and CG_MapRestart().
void CG_InitMarkPolys (void)
References cg_activeMarkPolys, cg_markPolys, MAX_MARK_POLYS, markPoly_s::nextMark, and markPoly_s::prevMark.
Referenced by CG_Init(), and CG_MapRestart().
void CG_InitTeamChat (void)
References systemChat, teamChat1, and teamChat2.
Referenced by CG_Init().
void CG_KeyEvent (int key, qboolean down)
References cgs_t::capturedItem, cg, CG_EventHandling(), CGAME_EVENT_NONE, cgs, cgs_t::cursorX, cgs_t::cursorY, Display_CaptureItem(), Display_HandleKey(), K_MOUSE2, NULL, PM_NORMAL, PM_SPECTATOR, playerState_s::pm_type, cg_t::predictedPlayerState, qfalse, cg_t::showScores, and trap_Key_SetCatcher().
Referenced by vmMain().
int CG_LastAttacker (void)
References cg_t::attackerTime, PERS_ATTACKER, playerState_s::persistant, snapshot_t::ps, and cg_t::snap.
Referenced by CG_TellAttacker_f(), CG_VoiceTellAttacker_f(), and vmMain().
void CG_LoadDeferredPlayers (void)
References CG_LoadClientInfo(), CG_Printf(), cgs, cgs_t::clientinfo, clientInfo_t::deferred, clientInfo_t::infoValid, cgs_t::maxclients, qfalse, and trap_MemoryRemaining().
Referenced by CG_DrawOldScoreboard(), CG_DrawScoreboard(), and CG_ServerCommand().
void CG_LoadingClient (int clientNum)
References CG_ConfigString(), CG_LoadingString(), cgs, Com_sprintf(), CS_PLAYERS, DEFAULT_MODEL, cgs_t::gametype, GT_SINGLE_PLAYER, info, Info_ValueForKey(), loadingPlayerIconCount, loadingPlayerIcons, MAX_LOADING_PLAYER_ICONS, MAX_QPATH, Q_CleanStr(), Q_strncpyz(), qtrue, trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), and va().
Referenced by CG_RegisterClients().
void CG_LoadingItem (int itemNum)
References bg_itemlist, CG_LoadingString(), gitem_s::icon, loadingItemIconCount, loadingItemIcons, MAX_LOADING_ITEM_ICONS, gitem_s::pickup_name, and trap_R_RegisterShaderNoMip().
Referenced by CG_RegisterGraphics().
void CG_LoadingString (const char * s)
References cg, cg_t::infoScreenText, Q_strncpyz(), and trap_UpdateScreen().
Referenced by CG_Init(), CG_LoadingClient(), CG_LoadingItem(), and CG_RegisterGraphics().
void CG_LoadMenus (const char * menuFile)
void CG_LoadVoiceChats (void)
References CG_ParseVoiceChats(), CG_Printf(), MAX_VOICECHATS, and trap_MemoryRemaining().
Referenced by CG_RegisterSounds().
localEntity_t* CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
References refEntity_t::axis, AxisClear(), cg, CG_AllocLocalEntity(), CG_Error(), localEntity_s::color, refEntity_t::customShader, localEntity_s::endTime, refEntity_t::hModel, LE_EXPLOSION, LE_SPRITE_EXPLOSION, localEntity_s::leType, refEntity_t::oldorigin, refEntity_t::origin, localEntity_s::refEntity, RotateAroundDirection(), refEntity_t::rotation, shader, refEntity_t::shaderTime, localEntity_s::startTime, cg_t::time, VectorAdd, VectorCopy, and VectorScale.
Referenced by CG_MissileHitWall().
void CG_MissileHitPlayer (int weapon, vec3_t origin, vec3_t dir, int entityNum)
References CG_Bleed(), CG_MissileHitWall(), IMPACTSOUND_FLESH, WP_BFG, WP_GRENADE_LAUNCHER, WP_PLASMAGUN, and WP_ROCKET_LAUNCHER.
Referenced by CG_EntityEvent(), and CG_ShotgunPellet().
void CG_MissileHitWall (int weapon, int clientNum, vec3_t origin, vec3_t dir, impactSound_t soundType)
References cgMedia_t::bfgExplosionShader, cgMedia_t::bulletExplosionShader, cgMedia_t::bulletFlashModel, cgMedia_t::bulletMarkShader, cgMedia_t::burnMarkShader, CG_ImpactMark(), CG_MakeExplosion(), cg_oldRocket, CG_ParticleExplosion(), cgs, CHAN_AUTO, cgs_t::clientinfo, localEntity_s::color, clientInfo_t::color1, cgMedia_t::dishFlashModel, cgMedia_t::energyMarkShader, ENTITYNUM_WORLD, cgMedia_t::grenadeExplosionShader, cgMedia_t::holeMarkShader, IMPACTSOUND_FLESH, IMPACTSOUND_METAL, vmCvar_t::integer, localEntity_s::light, localEntity_s::lightColor, cgs_t::media, cgMedia_t::plasmaExplosionShader, qfalse, qtrue, cgMedia_t::railExplosionShader, random, localEntity_s::refEntity, cgMedia_t::ringFlashModel, cgMedia_t::rocketExplosionShader, cgMedia_t::sfx_lghit1, cgMedia_t::sfx_lghit2, cgMedia_t::sfx_lghit3, cgMedia_t::sfx_plasmaexp, cgMedia_t::sfx_ric1, cgMedia_t::sfx_ric2, cgMedia_t::sfx_ric3, cgMedia_t::sfx_rockexp, shader, refEntity_t::shaderRGBA, trap_S_StartSound(), VectorCopy, VectorMA(), VectorScale, WP_BFG, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by CG_Bullet(), CG_EntityEvent(), CG_MissileHitPlayer(), and CG_ShotgunPellet().
void CG_MouseEvent (int x, int y)
References cgs_t::activeCursor, cgs_t::capturedItem, cg, cgs, CURSOR_ARROW, CURSOR_SIZER, cgs_t::cursorX, cgs_t::cursorY, Display_CursorType(), Display_MouseMove(), cgs_t::media, n, NULL, PM_NORMAL, PM_SPECTATOR, playerState_s::pm_type, cg_t::predictedPlayerState, qfalse, cgMedia_t::selectCursor, cg_t::showScores, cgMedia_t::sizeCursor, and trap_Key_SetCatcher().
Referenced by vmMain().
void CG_NewClientInfo (int clientNum)
References clientInfo_t::blueTeam, clientInfo_t::botSkill, clientInfo_t::c1RGBA, clientInfo_t::c2RGBA, cg, cg_buildScript, CG_ColorFromString(), CG_ConfigString(), cg_deferPlayers, cg_forceModel, CG_LoadClientInfo(), CG_Printf(), CG_ScanForExistingClientInfo(), CG_SetDeferredClientInfo(), cgs, cgs_t::clientinfo, clientInfo_t::color1, clientInfo_t::color2, CS_PLAYERS, DEFAULT_TEAM_HEAD, DEFAULT_TEAM_MODEL, clientInfo_t::deferred, cgs_t::gametype, GT_TEAM, clientInfo_t::handicap, clientInfo_t::headModelName, clientInfo_t::headSkinName, Info_ValueForKey(), clientInfo_t::infoValid, vmCvar_t::integer, cg_t::loading, clientInfo_t::losses, MAX_QPATH, MAX_TEAMNAME, clientInfo_t::modelName, clientInfo_t::name, NULL, Q_strncpyz(), qfalse, qtrue, clientInfo_t::redTeam, clientInfo_t::skinName, clientInfo_t::team, clientInfo_t::teamLeader, clientInfo_t::teamTask, trap_Cvar_VariableStringBuffer(), trap_MemoryRemaining(), and clientInfo_t::wins.
Referenced by CG_ConfigStringModified(), CG_ForceModelChange(), and CG_RegisterClients().
int CG_NewParticleArea (int num)
References CG_ConfigString(), CG_ParticleBubble(), CG_ParticleSnow(), cgs, COM_Parse(), cgs_t::media, range(), particle_s::snum, token, type(), and cgMedia_t::waterBubbleShader.
void CG_NextWeapon_f (void)
References cg, CG_WeaponSelectable(), MAX_WEAPONS, playerState_s::pm_flags, PMF_FOLLOW, snapshot_t::ps, cg_t::snap, cg_t::time, cg_t::weaponSelect, cg_t::weaponSelectTime, and WP_GAUNTLET.
qboolean CG_OtherTeamHasFlag (void)
References cgs_t::blueflag, cg, cgs, FLAG_TAKEN, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, qfalse, qtrue, cgs_t::redflag, cg_t::snap, TEAM_BLUE, and TEAM_RED.
Referenced by CG_OwnerDrawVisible().
void CG_OutOfAmmoChange (void)
References cg, CG_WeaponSelectable(), MAX_WEAPONS, cg_t::time, cg_t::weaponSelect, and cg_t::weaponSelectTime.
Referenced by CG_EntityEvent().
void CG_OwnerDraw (float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, float scale, vec4_t color, qhandle_t shader, int textStyle)
References CG_1STPLACE, CG_2NDPLACE, CG_ACCURACY, CG_AREA_CHAT, CG_AREA_POWERUP, CG_AREA_SYSTEMCHAT, CG_AREA_TEAMCHAT, CG_ASSISTS, CG_BLUE_FLAGHEAD, CG_BLUE_FLAGNAME, CG_BLUE_FLAGSTATUS, CG_BLUE_NAME, CG_BLUE_SCORE, CG_CAPFRAGLIMIT, CG_CAPTURES, CG_CTF_POWERUP, CG_DEFEND, CG_Draw1stPlace(), CG_Draw2ndPlace(), CG_DrawAreaChat(), CG_DrawAreaPowerUp(), CG_DrawAreaSystemChat(), CG_DrawAreaTeamChat(), CG_DrawBlueFlagHead(), CG_DrawBlueFlagName(), CG_DrawBlueFlagStatus(), CG_DrawBlueName(), CG_DrawBlueScore(), CG_DrawCapFragLimit(), CG_DrawCTFPowerUp(), CG_DrawGameStatus(), CG_DrawGameType(), CG_DrawKiller(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHasFlag(), CG_DrawPlayerHead(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawPlayerLocation(), CG_DrawPlayerScore(), CG_DrawPlayerStatus(), CG_DrawRedFlagHead(), CG_DrawRedFlagName(), CG_DrawRedFlagStatus(), CG_DrawRedName(), CG_DrawRedScore(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), cg_drawStatus, CG_DrawTeamColor(), CG_DrawTeamSpectators(), CG_EXCELLENT, CG_GAME_STATUS, CG_GAME_TYPE, CG_GAUNTLET, CG_HARVESTER_SKULLS, CG_HARVESTER_SKULLS2D, CG_HarvesterSkulls(), CG_IMPRESSIVE, CG_KILLER, CG_ONEFLAG_STATUS, CG_OneFlagStatus(), CG_PERFECT, CG_PLAYER_AMMO_ICON, CG_PLAYER_AMMO_ICON2D, CG_PLAYER_AMMO_VALUE, CG_PLAYER_ARMOR_ICON, CG_PLAYER_ARMOR_ICON2D, CG_PLAYER_ARMOR_VALUE, CG_PLAYER_HASFLAG, CG_PLAYER_HASFLAG2D, CG_PLAYER_HEAD, CG_PLAYER_HEALTH, CG_PLAYER_ITEM, CG_PLAYER_LOCATION, CG_PLAYER_SCORE, CG_PLAYER_STATUS, CG_RED_FLAGHEAD, CG_RED_FLAGNAME, CG_RED_FLAGSTATUS, CG_RED_NAME, CG_RED_SCORE, CG_SELECTEDPLAYER_ARMOR, CG_SELECTEDPLAYER_HEAD, CG_SELECTEDPLAYER_HEALTH, CG_SELECTEDPLAYER_LOCATION, CG_SELECTEDPLAYER_NAME, CG_SELECTEDPLAYER_POWERUP, CG_SELECTEDPLAYER_STATUS, CG_SELECTEDPLAYER_WEAPON, CG_SHOW_2DONLY, CG_SPECTATORS, CG_TEAM_COLOR, CG_TEAMINFO, CG_VOICE_HEAD, CG_VOICE_NAME, h, rectDef_t::h, vmCvar_t::integer, numSortedTeamPlayers, qfalse, qtrue, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
qboolean CG_OwnerDrawVisible (int flags)
References cgs_t::blueflag, cg, CG_OtherTeamHasFlag(), CG_SHOW_ANYNONTEAMGAME, CG_SHOW_ANYTEAMGAME, CG_SHOW_BLUE_TEAM_HAS_REDFLAG, CG_SHOW_CTF, CG_SHOW_DURINGINCOMINGVOICE, CG_SHOW_HARVESTER, CG_SHOW_HEALTHCRITICAL, CG_SHOW_HEALTHOK, CG_SHOW_IF_PLAYER_HAS_FLAG, CG_SHOW_NOTEAMINFO, CG_SHOW_OBELISK, CG_SHOW_ONEFLAG, CG_SHOW_OTHERTEAMHASFLAG, CG_SHOW_RED_TEAM_HAS_BLUEFLAG, CG_SHOW_SINGLEPLAYER, CG_SHOW_TEAMINFO, CG_SHOW_TOURNAMENT, CG_SHOW_YOURTEAMHASENEMYFLAG, CG_YourTeamHasFlag(), cgs, FLAG_TAKEN, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, numSortedTeamPlayers, playerState_s::powerups, snapshot_t::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, qfalse, qtrue, cgs_t::redflag, cg_t::snap, STAT_HEALTH, and playerState_s::stats.
void CG_PainEvent (centity_t * cent, int health)
References cg, CG_CustomSound(), CG_WaterLevel(), CHAN_VOICE, centity_s::currentState, NULL, entityState_s::number, playerEntity_t::painDirection, playerEntity_t::painTime, centity_s::pe, cg_t::time, and trap_S_StartSound().
Referenced by CG_CheckLocalSounds(), and CG_EntityEvent().
void CG_ParseServerinfo (void)
References cgs_t::blueTeam, cgs_t::capturelimit, CG_ConfigString(), cgs, Com_sprintf(), CS_SERVERINFO, cgs_t::dmflags, cgs_t::fraglimit, cgs_t::gametype, info, Info_ValueForKey(), cgs_t::mapname, cgs_t::maxclients, Q_strncpyz(), cgs_t::redTeam, cgs_t::teamflags, cgs_t::timelimit, trap_Cvar_Set(), and va().
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ParticleBulletDebris (vec3_t org, vec3_t vel, int duration)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, cgs, particle_s::color, EMISIVEFADE, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, cgs_t::media, particle_s::next, particle_s::org, P_SMOKE, particle_s::pshader, particle_s::startfade, particle_s::time, cg_t::time, cgMedia_t::tracerShader, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleDust (centity_t * cent, vec3_t origin, vec3_t dir)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, AngleVectors(), cg, cgs, crandom, particle_s::endheight, particle_s::endtime, particle_s::endwidth, forward, free_particles, particle_s::height, LARGESIZE, length(), cgs_t::media, particle_s::next, NORMALSIZE, NULL, particle_s::org, P_SMOKE, PARTICLE_GRAVITY, particle_s::pshader, qfalse, random, particle_s::roll, particle_s::rotate, cgMedia_t::smokePuffShader, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, vectoangles(), VectorClear, VectorCopy, VectorLength(), VectorMA(), VectorNegate, particle_s::vel, and particle_s::width.
void CG_ParticleExplosion (char * animStr, vec3_t origin, vec3_t vel, int duration, int sizeStart, int sizeEnd)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Error(), crandom, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_ANIM, Q_stricmp(), particle_s::roll, particle_s::shaderAnim, shaderAnimNames, shaderAnimSTRatio, particle_s::time, cg_t::time, particle_s::type, VectorClear, VectorCopy, particle_s::vel, and particle_s::width.
Referenced by CG_MissileHitWall().
void CG_ParticleMisc (qhandle_t pshader, vec3_t origin, int size, int duration, float alpha)
References active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_SPRITE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, VectorCopy, and particle_s::width.
void CG_ParticleSmoke (qhandle_t pshader, centity_t * cent)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::color, crandom, centity_s::currentState, particle_s::end, particle_s::endheight, particle_s::endtime, particle_s::endwidth, entityState_s::frame, free_particles, particle_s::height, particle_s::next, particle_s::org, entityState_s::origin, entityState_s::origin2, P_SMOKE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::start, particle_s::startfade, particle_s::time, cg_t::time, entityState_s::time, entityState_s::time2, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleSnow (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::color, crandom, particle_s::end, free_particles, particle_s::height, particle_s::link, particle_s::next, particle_s::org, P_WEATHER, P_WEATHER_TURBULENT, particle_s::pshader, qtrue, range(), particle_s::snum, particle_s::start, particle_s::time, cg_t::time, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
Referenced by CG_NewParticleArea().
void CG_ParticleSnowFlurry (qhandle_t pshader, centity_t * cent)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, entityState_s::angles, cg, CG_Printf(), particle_s::color, crandom, centity_s::currentState, particle_s::end, particle_s::endtime, free_particles, particle_s::height, particle_s::next, particle_s::org, entityState_s::origin, entityState_s::origin2, P_WEATHER_FLURRY, particle_s::pshader, qtrue, particle_s::start, particle_s::startfade, particle_s::time, cg_t::time, entityState_s::time, entityState_s::time2, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleSparks (vec3_t org, vec3_t vel, int duration, float x, float y, float speed)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, cgs, particle_s::color, crandom, EMISIVEFADE, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, cgs_t::media, particle_s::next, particle_s::org, P_SMOKE, particle_s::pshader, particle_s::startfade, particle_s::time, cg_t::time, cgMedia_t::tracerShader, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
const char* CG_PlaceString (int rank)
References Com_sprintf(), RANK_TIED_FLAG, s, S_COLOR_BLUE, S_COLOR_RED, S_COLOR_WHITE, S_COLOR_YELLOW, t, and va().
Referenced by CG_DrawOldScoreboard(), CG_GetGameStatusText(), and CG_Obituary().
void CG_PlayBufferedVoiceChats (void)
References cg, CG_PlayVoiceChat(), MAX_VOICECHATBUFFER, bufferedVoiceChat_s::snd, cg_t::time, cg_t::voiceChatBufferIn, cg_t::voiceChatBufferOut, and cg_t::voiceChatTime.
Referenced by CG_DrawActiveFrame().
void CG_Player (centity_t * cent)
References AnglesToAxis(), refEntity_t::axis, refEntity_t::backlerp, cg, CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), cg_cameraMode, CG_Error(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PlayerPowerups(), CG_PlayerShadow(), CG_PlayerSplash(), CG_PlayerSprites(), CG_PositionRotatedEntityOnTag(), cg_shadows, cgs, cgs_t::clientinfo, playerState_s::clientNum, entityState_s::clientNum, CrossProduct(), centity_s::currentState, refEntity_t::customSkin, EF_DEAD, EF_KAMIKAZE, entityState_s::eFlags, refEntity_t::frame, cgs_t::gametype, GT_HARVESTER, head, clientInfo_t::headModel, clientInfo_t::headSkin, refEntity_t::hModel, clientInfo_t::infoValid, vmCvar_t::integer, cgMedia_t::invulnerabilityPowerupModel, clientInfo_t::invulnerabilityStartTime, clientInfo_t::invulnerabilityStopTime, clientInfo_t::legsModel, clientInfo_t::legsSkin, centity_s::lerpOrigin, refEntity_t::lightingOrigin, M_PI, MAX_CLIENTS, cgs_t::media, clientInfo_t::medkitUsageTime, NULL, entityState_s::number, refEntity_t::oldframe, refEntity_t::oldorigin, refEntity_t::origin, entityState_s::powerups, snapshot_t::ps, PW_AMMOREGEN, PW_DOUBLER, PW_GUARD, PW_INVULNERABILITY, PW_SCOUT, refEntity_t::renderfx, cg_t::renderingThirdPerson, RF_LIGHTING_ORIGIN, RF_SHADOW_PLANE, RF_THIRD_PERSON, refEntity_t::shaderRGBA, refEntity_t::shadowPlane, cg_t::snap, t, clientInfo_t::team, cg_t::time, clientInfo_t::torsoModel, clientInfo_t::torsoSkin, trap_R_AddRefEntityToScene(), VectorAdd, VectorClear, VectorCopy, VectorInverse(), VectorNormalize(), and VectorSet.
Referenced by CG_AddCEntity().
int CG_PointContents (const vec3_t point, int passEntityNum)
References cg_numSolidEntities, centity_s::currentState, centity_s::lerpAngles, centity_s::lerpOrigin, entityState_s::modelindex, entityState_s::number, entityState_s::solid, SOLID_BMODEL, trap_CM_InlineModel(), trap_CM_PointContents(), and trap_CM_TransformedPointContents().
Referenced by CG_AddFragment(), CG_Bullet(), CG_CalcFov(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), CG_PlayerSplash(), CG_PredictPlayerState(), CG_RocketTrail(), CG_ScanForCrosshairEntity(), CG_ShotgunEjectBrass(), CG_ShotgunFire(), CG_ShotgunPellet(), and CG_WaterLevel().
void CG_PositionEntityOnTag (refEntity_t * entity, const refEntity_t * parent, qhandle_t parentModel, char * tagName)
References refEntity_t::axis, orientation_t::axis, refEntity_t::backlerp, refEntity_t::frame, MatrixMultiply(), refEntity_t::oldframe, refEntity_t::origin, orientation_t::origin, trap_R_LerpTag(), VectorCopy, and VectorMA().
Referenced by CG_PlayerFlag().
void CG_PositionRotatedEntityOnTag (refEntity_t * entity, const refEntity_t * parent, qhandle_t parentModel, char * tagName)
References refEntity_t::axis, orientation_t::axis, refEntity_t::backlerp, refEntity_t::frame, MatrixMultiply(), refEntity_t::oldframe, refEntity_t::origin, orientation_t::origin, trap_R_LerpTag(), VectorCopy, and VectorMA().
Referenced by CG_AddPlayerWeapon(), CG_Item(), CG_Player(), and CG_PlayerFlag().
void CG_PredictPlayerState (void)
References cg, CG_AdjustPositionForMover(), cg_errorDecay, CG_InterpolatePlayerState(), cg_nopredict, CG_PointContents(), CG_Printf(), cg_showmiss, cg_synchronousClients, CG_TouchTriggerPrediction(), CG_Trace(), CG_TransitionPlayerState(), cgs, pmove_t::cmd, CMD_BACKUP, playerState_s::commandTime, CONTENTS_BODY, current, cg_t::demoPlayback, DF_NO_FOOTSTEPS, cgs_t::dmflags, cg_t::eventSequence, playerState_s::eventSequence, pmove_t::gauntletHit, playerState_s::groundEntityNum, cg_t::hyperspace, if(), vmCvar_t::integer, MASK_PLAYERSOLID, MAX_PS_EVENTS, cg_t::nextFrameTeleport, cg_t::nextSnap, pmove_t::noFootsteps, cg_t::oldTime, playerState_s::origin, PERS_TEAM, playerState_s::persistant, cg_t::physicsTime, PM_DEAD, playerState_s::pm_flags, playerState_s::pm_type, PM_UpdateViewAngles(), PMF_FOLLOW, Pmove(), pmove_t::pmove_fixed, pmove_fixed, pmove_t::pmove_msec, pmove_msec, pmove_t::pointcontents, cg_t::predictedError, cg_t::predictedErrorTime, cg_t::predictedPlayerState, snapshot_t::ps, pmove_t::ps, qfalse, qtrue, snapshot_t::serverTime, usercmd_s::serverTime, cg_t::snap, t, TEAM_SPECTATOR, cg_t::thisFrameTeleport, cg_t::time, pmove_t::trace, pmove_t::tracemask, trap_Cvar_Set(), trap_GetCurrentCmdNumber(), trap_GetUserCmd(), cg_t::validPPS, vmCvar_t::value, VectorAdd, VectorClear, VectorCompare(), VectorLength(), VectorScale, and VectorSubtract.
Referenced by CG_DrawActiveFrame().
void CG_PrevWeapon_f (void)
References cg, CG_WeaponSelectable(), MAX_WEAPONS, playerState_s::pm_flags, PMF_FOLLOW, snapshot_t::ps, cg_t::snap, cg_t::time, cg_t::weaponSelect, cg_t::weaponSelectTime, and WP_GAUNTLET.
void QDECL CG_Printf (const char * msg, ...)
Referenced by CG_AddTestModel(), CG_BloodPool(), CG_CheckChangedPredictableEvents(), CG_DrawActiveFrame(), CG_EntityEvent(), CG_LoadDeferredPlayers(), CG_LoadVoiceChats(), CG_MapRestart(), CG_NewClientInfo(), CG_Obituary(), CG_OilSlickRemove(), CG_ParseAnimationFile(), CG_Particle_Bleed(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBubble(), CG_ParticleImpactSmokePuff(), CG_ParticleMisc(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), CG_PlayVoiceChat(), CG_PredictPlayerState(), CG_ReadNextSnapshot(), CG_ResetPlayerEntity(), CG_RunLerpFrame(), CG_ServerCommand(), CG_SetDeferredClientInfo(), CG_SetLerpFrameAnimation(), CG_TestModel_f(), CG_TestModelNextFrame_f(), CG_TestModelNextSkin_f(), CG_TestModelPrevFrame_f(), CG_TestModelPrevSkin_f(), CG_Viewpos_f(), and Com_Printf().
void CG_ProcessSnapshots (void)
References cg, CG_Error(), CG_ReadNextSnapshot(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), cg_t::latestSnapshotNum, cg_t::latestSnapshotTime, n, cg_t::nextSnap, NULL, snapshot_t::serverTime, cg_t::snap, SNAPFLAG_NOT_ACTIVE, snapshot_t::snapFlags, cg_t::time, and trap_GetCurrentSnapshotNumber().
Referenced by CG_DrawActiveFrame().
void CG_RailTrail (clientInfo_t * ci, vec3_t start, vec3_t end)
References refEntity_t::axis, AxisClear(), cg, CG_AllocLocalEntity(), cg_oldRail, cg_railTrailTime, cgs, localEntity_s::color, clientInfo_t::color1, clientInfo_t::color2, refEntity_t::customShader, localEntity_s::endTime, vmCvar_t::integer, LE_FADE_RGB, LE_MOVE_SCALE_FADE, LEF_PUFF_DONT_SCALE, localEntity_s::leFlags, localEntity_s::leType, localEntity_s::lifeRate, cgs_t::media, move(), refEntity_t::oldorigin, refEntity_t::origin, PerpendicularVector(), localEntity_s::pos, refEntity_t::radius, RADIUS, cgMedia_t::railCoreShader, cgMedia_t::railRingsShader, re, localEntity_s::refEntity, refEntity_t::reType, RotatePointAroundVector(), ROTATION, RT_RAIL_CORE, RT_SPRITE, refEntity_t::shaderRGBA, refEntity_t::shaderTime, SPACING, localEntity_s::startTime, cg_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, vmCvar_t::value, VectorAdd, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, and VectorSubtract.
Referenced by CG_EntityEvent().
void CG_RankRunFrame (void)
void CG_RegisterItemVisuals (int itemNum)
References bg_itemlist, bg_numItems, CG_Error(), cg_items, CG_RegisterWeapon(), gitem_s::giTag, gitem_s::giType, itemInfo_t::icon, gitem_s::icon, IT_ARMOR, IT_HEALTH, IT_HOLDABLE, IT_POWERUP, IT_WEAPON, itemInfo_t::models, qtrue, itemInfo_t::registered, trap_R_RegisterModel(), trap_R_RegisterShader(), and gitem_s::world_model.
Referenced by CG_DrawCTFPowerUp(), CG_DrawHoldableItem(), CG_DrawPickupItem(), CG_DrawPlayerItem(), CG_RegisterGraphics(), and CG_RegisterWeapon().
void CG_RegisterWeapon (int weaponNum)
References weaponInfo_s::ammoIcon, weaponInfo_s::ammoModel, weaponInfo_s::barrelModel, cgMedia_t::bfgExplosionShader, bg_itemlist, cgMedia_t::bulletExplosionShader, CG_Error(), CG_GrappleTrail(), CG_GrenadeTrail(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), CG_RegisterItemVisuals(), CG_RocketTrail(), CG_ShotgunEjectBrass(), cg_weapons, cgs, gitem_s::classname, COM_StripExtension(), weaponInfo_s::ejectBrassFunc, weaponInfo_s::firingSound, weaponInfo_s::flashDlightColor, weaponInfo_s::flashModel, weaponInfo_s::flashSound, gitem_s::giTag, gitem_s::giType, cgMedia_t::grenadeExplosionShader, weaponInfo_s::handsModel, gitem_s::icon, IT_AMMO, IT_WEAPON, weaponInfo_s::item, cgMedia_t::lightningExplosionModel, cgMedia_t::lightningShader, MAKERGB, MAX_QPATH, cgs_t::media, weaponInfo_s::missileDlight, weaponInfo_s::missileDlightColor, weaponInfo_s::missileModel, weaponInfo_s::missileSound, weaponInfo_s::missileTrailFunc, cgMedia_t::plasmaExplosionShader, qfalse, qtrue, cgMedia_t::railCoreShader, cgMedia_t::railExplosionShader, cgMedia_t::railRingsShader, weaponInfo_s::readySound, weaponInfo_s::registered, cgMedia_t::rocketExplosionShader, cgMedia_t::sfx_lghit1, cgMedia_t::sfx_lghit2, cgMedia_t::sfx_lghit3, weaponInfo_s::trailRadius, trap_R_ModelBounds(), trap_R_RegisterModel(), trap_R_RegisterShader(), trap_S_RegisterSound(), weaponInfo_s::weaponIcon, weaponInfo_s::weaponMidpoint, weaponInfo_s::weaponModel, weaponInfo_s::wiTrailTime, gitem_s::world_model, WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_DrawWeaponSelect(), and CG_RegisterItemVisuals().
void CG_ResetPlayerEntity (centity_t * cent)
References entityState_s::apos, BG_EvaluateTrajectory(), cg, CG_ClearLerpFrame(), cg_debugPosition, CG_Printf(), cgs, cgs_t::clientinfo, entityState_s::clientNum, centity_s::currentState, centity_s::errorTime, centity_s::extrapolated, vmCvar_t::integer, playerEntity_t::legs, entityState_s::legsAnim, centity_s::lerpAngles, centity_s::lerpOrigin, entityState_s::number, centity_s::pe, PITCH, lerpFrame_t::pitchAngle, lerpFrame_t::pitching, entityState_s::pos, qfalse, centity_s::rawAngles, centity_s::rawOrigin, cg_t::time, playerEntity_t::torso, entityState_s::torsoAnim, VectorCopy, YAW, lerpFrame_t::yawAngle, and lerpFrame_t::yawing.
Referenced by CG_LoadClientInfo(), and CG_ResetEntity().
void CG_Respawn (void)
References cg, snapshot_t::ps, qtrue, cg_t::snap, cg_t::thisFrameTeleport, cg_t::time, playerState_s::weapon, cg_t::weaponSelect, and cg_t::weaponSelectTime.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionPlayerState().
void CG_RunMenuScript (char ** args)
void CG_ScorePlum (int client, vec3_t org, int score)
References AnglesToAxis(), refEntity_t::axis, cg, CG_AllocLocalEntity(), cg_scorePlum, playerState_s::clientNum, localEntity_s::color, localEntity_s::endTime, vmCvar_t::integer, LE_SCOREPLUM, localEntity_s::leFlags, localEntity_s::leType, localEntity_s::lifeRate, localEntity_s::pos, cg_t::predictedPlayerState, refEntity_t::radius, localEntity_s::radius, re, localEntity_s::refEntity, refEntity_t::reType, RT_SPRITE, localEntity_s::startTime, cg_t::time, trajectory_t::trBase, VectorClear, and VectorCopy.
Referenced by CG_EntityEvent().
void CG_SelectNextPlayer (void)
References CG_CheckOrderPending(), CG_SetSelectedPlayerName(), and numSortedTeamPlayers.
void CG_SelectPrevPlayer (void)
References CG_CheckOrderPending(), CG_SetSelectedPlayerName(), and numSortedTeamPlayers.
void CG_SetConfigValues (void)
References cgs_t::blueflag, cg, CG_ConfigString(), cgs, CS_FLAGSTATUS, CS_LEVEL_START_TIME, CS_SCORES1, CS_SCORES2, CS_WARMUP, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, cgs_t::levelStartTime, cgs_t::redflag, s, cgs_t::scores1, cgs_t::scores2, and cg_t::warmup.
Referenced by CG_Init().
void CG_SetEntitySoundPosition (centity_t * cent)
References cgs, centity_s::currentState, cgs_t::inlineModelMidpoints, centity_s::lerpOrigin, entityState_s::modelindex, entityState_s::number, entityState_s::solid, SOLID_BMODEL, trap_S_UpdateEntityPosition(), and VectorAdd.
Referenced by CG_CheckEvents(), and CG_EntityEffects().
void CG_SetPrintString (int type, const char * p)
References SYSTEM_PRINT, systemChat, teamChat1, and teamChat2.
void CG_SetScoreSelection (void * menu)
Referenced by CG_DrawScoreboard(), and CG_ParseScores().
void CG_ShaderStateChanged (void)
References CG_ConfigString(), CS_SHADERSTATE, MAX_QPATH, n, t, and trap_R_RemapShader().
Referenced by CG_ConfigStringModified(), and CG_Init().
void CG_ShotgunFire (entityState_t * es)
References cg, CG_PointContents(), CG_ShotgunPattern(), CG_SmokePuff(), cgs, CONTENTS_WATER, entityState_s::eventParm, cgs_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, LEF_PUFF_DONT_SCALE, cgs_t::media, entityState_s::origin2, entityState_s::otherEntityNum, entityState_s::pos, cgMedia_t::shotgunSmokePuffShader, cg_t::time, trajectory_t::trBase, up, VectorAdd, VectorNormalize(), VectorScale, VectorSet, and VectorSubtract.
Referenced by CG_EntityEvent().
void CG_ShowResponseHead (void)
References cg, Menus_OpenByName(), cg_t::time, trap_Cvar_Set(), and cg_t::voiceTime.
Referenced by CG_PlayVoiceChat().
localEntity_t* CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
References b, CG_AllocLocalEntity(), cgs, localEntity_s::color, refEntity_t::customShader, localEntity_s::endTime, localEntity_s::fadeInTime, cgs_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, LE_MOVE_SCALE_FADE, localEntity_s::leFlags, localEntity_s::leType, localEntity_s::lifeRate, cgs_t::media, refEntity_t::origin, localEntity_s::pos, Q_random(), refEntity_t::radius, localEntity_s::radius, re, localEntity_s::refEntity, refEntity_t::reType, refEntity_t::rotation, RT_SPRITE, refEntity_t::shaderRGBA, refEntity_t::shaderTime, cgMedia_t::smokePuffRageProShader, localEntity_s::startTime, startTime, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, and VectorCopy.
Referenced by CG_BloodTrail(), CG_EntityEvent(), CG_HasteTrail(), CG_RocketTrail(), and CG_ShotgunFire().
void CG_SpawnEffect (vec3_t org)
References refEntity_t::axis, AxisClear(), cg, CG_AllocLocalEntity(), cgs, localEntity_s::color, refEntity_t::customShader, localEntity_s::endTime, refEntity_t::hModel, LE_FADE_RGB, localEntity_s::leFlags, localEntity_s::leType, localEntity_s::lifeRate, cgs_t::media, refEntity_t::origin, re, localEntity_s::refEntity, refEntity_t::reType, RT_MODEL, refEntity_t::shaderTime, localEntity_s::startTime, cgMedia_t::teleportEffectModel, cgMedia_t::teleportEffectShader, cg_t::time, and VectorCopy.
Referenced by CG_EntityEvent().
void CG_StartMusic (void)
References CG_ConfigString(), COM_Parse(), CS_MUSIC, MAX_QPATH, Q_strncpyz(), s, and trap_S_StartBackgroundTrack().
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
qhandle_t CG_StatusHandle (int task)
References cgs, h, cgs_t::media, TEAMTASK_CAMP, TEAMTASK_DEFENSE, TEAMTASK_ESCORT, TEAMTASK_FOLLOW, TEAMTASK_OFFENSE, TEAMTASK_PATROL, and TEAMTASK_RETRIEVE.
Referenced by CG_DrawNewTeamInfo(), CG_DrawPlayerStatus(), and CG_DrawSelectedPlayerStatus().
float* CG_TeamColor (int team)
References TEAM_BLUE, TEAM_RED, and TEAM_SPECTATOR.
void CG_TestGun_f (void)
References cg, CG_TestModel_f(), qtrue, refEntity_t::renderfx, RF_DEPTHHACK, RF_FIRST_PERSON, RF_MINLIGHT, cg_t::testGun, and cg_t::testModelEntity.
void CG_TestModel_f (void)
References AnglesToAxis(), refEntity_t::axis, refEntity_t::backlerp, cg, CG_Argv(), CG_Printf(), refEntity_t::frame, refEntity_t::hModel, MAX_QPATH, refEntity_t::oldframe, refEntity_t::origin, PITCH, Q_strncpyz(), qfalse, cg_t::refdef, cg_t::refdefViewAngles, ROLL, cg_t::testGun, cg_t::testModelEntity, cg_t::testModelName, trap_Argc(), trap_R_RegisterModel(), VectorMA(), refdef_t::viewaxis, refdef_t::vieworg, and YAW.
Referenced by CG_TestGun_f().
void CG_TestModelNextFrame_f (void)
References cg, CG_Printf(), refEntity_t::frame, and cg_t::testModelEntity.
void CG_TestModelNextSkin_f (void)
References cg, CG_Printf(), refEntity_t::skinNum, and cg_t::testModelEntity.
void CG_TestModelPrevFrame_f (void)
References cg, CG_Printf(), refEntity_t::frame, and cg_t::testModelEntity.
void CG_TestModelPrevSkin_f (void)
References cg, CG_Printf(), refEntity_t::skinNum, and cg_t::testModelEntity.
int CG_Text_Height (const char * text, float scale, int limit)
Referenced by CG_DrawCenterString().
void CG_Text_Paint (float x, float y, float scale, vec4_t color, const char * text, float adjust, int limit, int style)
Referenced by CG_Draw1stPlace(), CG_Draw2ndPlace(), CG_DrawAreaChat(), CG_DrawAreaPowerUp(), CG_DrawAreaSystemChat(), CG_DrawAreaTeamChat(), CG_DrawBlueFlagName(), CG_DrawBlueName(), CG_DrawBlueScore(), CG_DrawCapFragLimit(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawGameStatus(), CG_DrawGameType(), CG_DrawKiller(), CG_DrawMedal(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerLocation(), CG_DrawPlayerScore(), CG_DrawRedFlagName(), CG_DrawRedName(), CG_DrawRedScore(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawWarmup(), and CG_HarvesterSkulls().
void CG_Text_PaintChar (float x, float y, float width, float height, float scale, float s, float t, float s2, float t2, qhandle_t hShader)
Referenced by CG_Text_Paint_Limit().
int CG_Text_Width (const char * text, float scale, int limit)
Referenced by CG_DrawBlueScore(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawKiller(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerScore(), CG_DrawRedScore(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHealth(), CG_DrawTeamSpectators(), CG_DrawWarmup(), CG_HarvesterSkulls(), and CG_Text_Paint_Limit().
void CG_TileClear (void)
References cgMedia_t::backTileShader, cg, CG_TileClearBox(), cgs, cgs_t::glconfig, h, refdef_t::height, cgs_t::media, cg_t::refdef, right, glconfig_t::vidHeight, glconfig_t::vidWidth, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by CG_DrawActive().
void CG_Trace (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
References CG_ClipMoveToEntities(), trace_t::entityNum, ENTITYNUM_NONE, ENTITYNUM_WORLD, trace_t::fraction, t, and trap_CM_BoxTrace().
Referenced by CG_AddFragment(), CG_DrawCrosshair3D(), CG_LightningBolt(), CG_OffsetThirdPersonView(), CG_PredictPlayerState(), CG_ScanForCrosshairEntity(), CG_ShotgunPellet(), and ValidBloodPool().
void CG_TransitionPlayerState (playerState_t * ps, playerState_t * ops)
References cg, CG_CheckAmmo(), CG_CheckLocalSounds(), CG_CheckPlayerstateEvents(), CG_DamageFeedback(), CG_Respawn(), playerState_s::clientNum, playerState_s::damageCount, playerState_s::damageEvent, playerState_s::damagePitch, playerState_s::damageYaw, cg_t::duckChange, cg_t::duckTime, cg_t::mapRestart, PERS_SPAWN_COUNT, PERS_TEAM, playerState_s::persistant, PM_INTERMISSION, playerState_s::pm_type, snapshot_t::ps, qfalse, qtrue, cg_t::snap, TEAM_SPECTATOR, cg_t::thisFrameTeleport, cg_t::time, and playerState_s::viewheight.
Referenced by CG_PredictPlayerState(), and CG_TransitionSnapshot().
void CG_UpdateCvars (void)
References CG_ForceModelChange(), cvarTableSize, drawTeamOverlayModificationCount, forceModelModificationCount, vmCvar_t::integer, vmCvar_t::modificationCount, trap_Cvar_Set(), trap_Cvar_Update(), and cvarTable_t::vmCvar.
Referenced by CG_DrawActiveFrame().
void CG_VoiceChatLocal (int mode, qboolean voiceOnly, int clientNum, int color, const char * cmd)
References cg, CG_AddBufferedVoiceChat(), CG_GetVoiceChat(), cg_teamChatsOnly, CG_VoiceChatListForClient(), cgs, cgs_t::clientinfo, bufferedVoiceChat_s::clientNum, bufferedVoiceChat_s::cmd, Com_sprintf(), cgs_t::currentVoiceClient, vmCvar_t::integer, cg_t::intermissionStarted, MAX_CLIENTS, bufferedVoiceChat_s::message, clientInfo_t::name, Q_COLOR_ESCAPE, Q_strncpyz(), SAY_TEAM, SAY_TELL, bufferedVoiceChat_s::snd, and bufferedVoiceChat_s::voiceOnly.
Referenced by CG_EntityEvent(), and CG_VoiceChat().
void CG_Weapon_f (void)
References cg, CG_Argv(), MAX_WEAPONS, playerState_s::pm_flags, PMF_FOLLOW, snapshot_t::ps, cg_t::snap, STAT_WEAPONS, playerState_s::stats, cg_t::time, cg_t::weaponSelect, and cg_t::weaponSelectTime.
qboolean CG_YourTeamHasFlag (void)
References cgs_t::blueflag, cg, cgs, FLAG_TAKEN, FLAG_TAKEN_BLUE, FLAG_TAKEN_RED, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, PERS_TEAM, playerState_s::persistant, snapshot_t::ps, qfalse, qtrue, cgs_t::redflag, cg_t::snap, TEAM_BLUE, and TEAM_RED.
Referenced by CG_OwnerDrawVisible().
void CG_ZoomDown_f (void)
References cg, qtrue, cg_t::time, cg_t::zoomed, and cg_t::zoomTime.
void CG_ZoomUp_f (void)
References cg, qfalse, cg_t::time, cg_t::zoomed, and cg_t::zoomTime.
void QDECL void QDECL format (printf , 1 , 2)
Referenced by vfprint().
void testPrintFloat (char * string, float f)
References CG_TESTPRINTFLOAT, and PASSFLOAT().
void testPrintInt (char * string, int i)
References CG_TESTPRINTINT.
void trap_AddCommand (const char * cmdName)
References CG_ADDCOMMAND.
Referenced by CG_InitConsoleCommands().
int trap_Argc (void)
Referenced by CG_ServerCommand(), CG_TestModel_f(), Cmd_CallTeamVote_f(), Cmd_Follow_f(), Cmd_Say_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_Tell_f(), Cmd_Voice_f(), Cmd_VoiceTell_f(), ConcatArgs(), Svcmd_AddIP_f(), Svcmd_RemoveIP_f(), and UI_ConsoleCommand().
void trap_Args (char * buffer, int bufferLength)
Referenced by CG_TellAttacker_f(), CG_TellTarget_f(), CG_VoiceTellAttacker_f(), and CG_VoiceTellTarget_f().
void trap_Argv (int n, char * buffer, int bufferLength)
Referenced by CG_Argv(), CG_TargetCommand_f(), ClientCommand(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_GameCommand_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_VoiceTell_f(), Cmd_Vote_f(), ConcatArgs(), ConsoleCommand(), Svcmd_AddBot_f(), Svcmd_AddIP_f(), Svcmd_ForceTeam_f(), Svcmd_RemoveIP_f(), and UI_Argv().
void trap_CIN_DrawCinematic (int handle)
Referenced by UI_DrawCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawNetMapCinematic(), and UI_DrawPreviewCinematic().
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
Referenced by UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawPreviewCinematic(), UI_FeederSelection(), and UI_PlayCinematic().
e_status trap_CIN_RunCinematic (int handle)
Referenced by UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawNetMapCinematic(), UI_DrawPreviewCinematic(), and UI_RunCinematicFrame().
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Referenced by UI_DrawCinematic(), UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawNetMapCinematic(), and UI_DrawPreviewCinematic().
e_status trap_CIN_StopCinematic (int handle)
Referenced by UI_ClanName_HandleKey(), UI_FeederSelection(), UI_RunMenuScript(), and UI_StopCinematic().
void trap_CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
References CG_CM_BOXTRACE.
Referenced by CG_Bullet(), CG_PlayerShadow(), CG_PlayerSplash(), CG_ShotgunPellet(), CG_TouchTriggerPrediction(), and CG_Trace().
clipHandle_t trap_CM_InlineModel (int index)
References CG_CM_INLINEMODEL.
Referenced by CG_ClipMoveToEntities(), CG_PointContents(), and CG_TouchTriggerPrediction().
void trap_CM_LoadMap (const char * mapname)
References CG_CM_LOADMAP.
Referenced by CG_Init().
int trap_CM_MarkFragments (int numPoints, const vec3_t * points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t * fragmentBuffer)
References CG_CM_MARKFRAGMENTS.
Referenced by CG_ImpactMark().
int trap_CM_NumInlineModels (void)
References CG_CM_NUMINLINEMODELS.
Referenced by CG_RegisterGraphics().
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
References CG_CM_POINTCONTENTS.
Referenced by CG_PointContents().
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
References CG_CM_TEMPBOXMODEL.
Referenced by CG_ClipMoveToEntities().
void trap_CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
References CG_CM_TRANSFORMEDBOXTRACE.
Referenced by CG_ClipMoveToEntities().
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
References CG_CM_TRANSFORMEDPOINTCONTENTS.
Referenced by CG_PointContents().
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
Referenced by _UI_Init(), ArenaServers_MenuInit(), BotAILoadMap(), BotAISetup(), BotSetupDeathmatchAI(), CG_RegisterCvars(), G_InitBots(), G_LoadArenas(), G_LoadBots(), G_RegisterCvars(), UI_LoadArenas(), UI_LoadBots(), and UI_RegisterCvars().
void trap_Cvar_Set (const char * var_name, const char * value)
Referenced by _UI_Init(), _UI_KeyEvent(), _UI_SetActiveMenu(), ArenaServers_SaveChanges(), BeginIntermission(), BotAIStartFrame(), BotInterbreedEndMatch(), BotInterbreeding(), BotWriteSessionData(), CG_CalcVrect(), CG_DrawActiveFrame(), CG_MapRestart(), CG_ParseServerinfo(), CG_PredictPlayerState(), CG_SetSelectedPlayerName(), CG_ShowResponseHead(), CG_SizeDown_f(), CG_SizeUp_f(), CG_StartOrbit_f(), CG_UpdateCvars(), CheckCvars(), CheckTournament(), ClientThink_real(), ErrorMessage_Key(), ExitLevel(), Favorites_Add(), G_InitBots(), G_RankRunFrame(), G_RegisterCvars(), G_RunFrame(), G_SpawnBots(), G_WriteClientSessionData(), G_WriteSessionData(), GraphicsOptions_ApplyChanges(), Main_MenuEvent(), PlayerModel_SaveChanges(), PlayerSettings_MenuEvent(), PlayerSettings_SaveChanges(), ServerOptions_Start(), SP_worldspawn(), SpecifyLeague_Event(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Event(), UI_ClanName_HandleKey(), UI_Crosshair_HandleKey(), UI_DrawJoinGameType(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_DrawMapTimeToBeat(), UI_DrawNetGameType(), UI_DrawNetMapCinematic(), UI_FeederSelection(), UI_ForceMenuOff(), UI_GameType_HandleKey(), UI_Handicap_HandleKey(), UI_JoinGameType_HandleKey(), UI_LogAwardData(), UI_MainMenu(), UI_Mods_MenuEvent(), UI_NetGameType_HandleKey(), UI_NetSource_HandleKey(), UI_NewGame(), UI_NextOpponent(), UI_Pause(), UI_PriorOpponent(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_SetBestScore(), UI_SetBestScores(), UI_SetCapFragLimits(), UI_ShowPostGame(), UI_ShowTierVideo(), UI_Skill_HandleKey(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_MenuDraw(), UI_SPUnlock_f(), UI_SPUnlockMedals_f(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_TeamMember_HandleKey(), UI_TeamName_HandleKey(), UI_Update(), and UpdateIPBans().
void trap_Cvar_Update (vmCvar_t * vmCvar)
Referenced by BotAIStartFrame(), BotCheckConsoleMessages(), BotInterbreedEndMatch(), BotInterbreeding(), BotTestAAS(), CG_UpdateCvars(), G_CheckMinimumPlayers(), G_UpdateCvars(), and UI_UpdateCvars().
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Referenced by _UI_Init(), _UI_SetActiveMenu(), ArenaServers_LoadFavorites(), ArenaServers_SetType(), ArenaServers_StartRefresh(), BG_AddPredictableEventToPlayerstate(), BotInitLibrary(), BotReadSessionData(), CG_DrawCrosshair3D(), CG_DrawInformation(), CG_NewClientInfo(), CG_RegisterCvars(), CG_StartOrbit_f(), Cmd_CallVote_f(), Controls_DrawPlayer(), Controls_MenuInit(), ExitLevel(), Favorites_Add(), G_InitWorldSession(), G_RankGameOver(), G_ReadSessionData(), GraphicsOptions_SetMenuItems(), PlayerModel_SetMenuItems(), PlayerSettings_DrawPlayer(), ServerOptions_InitPlayerItems(), SpecifyLeague_GetList(), trap_Cvar_VariableValue(), UI_BuildFindPlayerList(), UI_BuildServerDisplayList(), UI_CanShowTierVideo(), UI_Cvar_VariableString(), UI_DrawConnectScreen(), UI_GetAwardLevel(), UI_GetBestScore(), UI_LogAwardData(), UI_MainMenu(), UI_NetSource_HandleKey(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPUnlock_f(), and UI_SPUnlockMedals_f().
void trap_Error (const char * fmt)
Referenced by CG_Error(), Com_Error(), G_Error(), Menu_AddItem(), Menu_Draw(), MField_Draw(), UI_LoadMenus(), UI_PopMenu(), UI_PushMenu(), and UI_SetLerpFrameAnimation().
void trap_FS_FCloseFile (fileHandle_t f)
Referenced by CG_HeadModelVoiceChats(), CG_ParseAnimationFile(), CG_ParseVoiceChats(), G_LoadArenasFromFile(), G_LoadBotsFromFile(), G_ShutdownGame(), GetMenuBuffer(), UI_CalcPostGameStats(), UI_ClearScores(), UI_LoadArenasFromFile(), UI_LoadBestScores(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
Referenced by CG_FileExists(), CG_HeadModelVoiceChats(), CG_ParseAnimationFile(), CG_ParseVoiceChats(), G_InitGame(), G_LoadArenasFromFile(), G_LoadBotsFromFile(), GetMenuBuffer(), UI_CalcPostGameStats(), UI_ClearScores(), UI_FileExists(), UI_hasSkinForBase(), UI_LoadArenasFromFile(), UI_LoadBestScores(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
Referenced by CG_HeadModelVoiceChats(), CG_ParseAnimationFile(), CG_ParseVoiceChats(), G_LoadArenasFromFile(), G_LoadBotsFromFile(), GetMenuBuffer(), UI_CalcPostGameStats(), UI_LoadArenasFromFile(), UI_LoadBestScores(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
Referenced by G_LogPrintf(), UI_CalcPostGameStats(), and UI_ClearScores().
qboolean trap_getCameraInfo (int time, vec3_t * origin, vec3_t * angles)
int trap_GetCurrentCmdNumber (void)
References CG_GETCURRENTCMDNUMBER.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
void trap_GetCurrentSnapshotNumber (int * snapshotNumber, int * serverTime)
References CG_GETCURRENTSNAPSHOTNUMBER.
Referenced by CG_ProcessSnapshots().
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
Referenced by G_ParseSpawnVars().
void trap_GetGameState (gameState_t * gamestate)
References CG_GETGAMESTATE.
Referenced by CG_ConfigStringModified(), and CG_Init().
void trap_GetGlconfig (glconfig_t * glconfig)
Referenced by _UI_Init(), CG_Init(), and UI_Init().
qboolean trap_GetServerCommand (int serverCommandNumber)
References CG_GETSERVERCOMMAND.
Referenced by CG_ExecuteNewServerCommands().
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t * snapshot)
References CG_GETSNAPSHOT.
Referenced by CG_ReadNextSnapshot().
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t * ucmd)
References CG_GETUSERCMD.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
int trap_Key_GetCatcher (void)
Referenced by _UI_KeyEvent(), _UI_SetActiveMenu(), UI_ForceMenuOff(), UI_IsFullscreen(), UI_Pause(), UI_Refresh(), and UI_RunMenuScript().
int trap_Key_GetKey (const char * binding)
References CG_KEY_GETKEY.
qboolean trap_Key_IsDown (int keynum)
Referenced by MField_KeyDownEvent().
void trap_Key_SetCatcher (int catcher)
Referenced by _UI_KeyEvent(), _UI_SetActiveMenu(), CG_KeyEvent(), CG_MouseEvent(), UI_ForceMenuOff(), UI_MainMenu(), UI_Pause(), UI_PushMenu(), UI_RunMenuScript(), UI_SPLevelMenu_f(), and UI_SPPostgameMenu_f().
qboolean trap_loadCamera (const char * name)
int trap_MemoryRemaining (void)
Referenced by CG_LoadDeferredPlayers(), CG_LoadVoiceChats(), CG_NewClientInfo(), PlayerModel_DrawPlayer(), and PlayerModel_PicEvent().
int trap_Milliseconds (void)
Referenced by CG_DrawFPS(), and UI_LoadMenus().
void trap_Print (const char * fmt)
Referenced by CG_HeadModelVoiceChats(), CG_ParseVoiceChats(), CG_Printf(), Com_Printf(), GetMenuBuffer(), UI_GetArenaInfoByNumber(), UI_GetBotInfoByNumber(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadBots(), UI_LoadBotsFromFile(), UI_LogAwardData(), UI_Mods_LoadMods(), UI_SPUnlock_f(), and UI_SPUnlockMedals_f().
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
Referenced by CG_AddExplosion(), CG_AddPlayerWeapon(), CG_AddSpriteExplosion(), CG_EntityEffects(), CG_Missile(), CG_PlayerPowerups(), and UI_DrawPlayer().
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int numPolys)
References CG_R_ADDPOLYSTOSCENE.
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
Referenced by CG_AddMarks(), CG_AddParticleToScene(), CG_ImpactMark(), CG_PlayerSplash(), and CG_Tracer().
void trap_R_AddRefEntityToScene (const refEntity_t * re)
Referenced by _UI_Init(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddMoveScaleFade(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_AddTestModel(), CG_AddWeaponWithPowerups(), CG_Beam(), CG_DamageBlendBlob(), CG_Draw3DModel(), CG_DrawCrosshair3D(), CG_General(), CG_Grapple(), CG_GrappleTrail(), CG_Item(), CG_LightningBolt(), CG_Missile(), CG_Mover(), CG_Player(), CG_PlayerFlag(), CG_PlayerFloatSprite(), CG_Portal(), CG_TeamBase(), CG_TrailItem(), Main_MenuDraw(), UI_DrawPlayer(), and UI_PlayerFloatSprite().
void trap_R_ClearScene (void)
Referenced by _UI_Init(), CG_Draw3DModel(), CG_DrawActiveFrame(), CG_RegisterGraphics(), Main_MenuDraw(), and UI_DrawPlayer().
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), _UI_Init(), CG_DrawChar(), CG_DrawCrosshair(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawPic(), CG_DrawSides(), CG_DrawTopBottom(), CG_FillRect(), CG_TileClearBox(), Text_PaintChar(), UI_DrawBannerString2(), UI_DrawHandlePic(), UI_DrawNamedPic(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawSides(), UI_DrawString2(), UI_DrawTopBottom(), and UI_FillRect().
int trap_R_LerpTag (orientation_t * tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char * tagName)
References CG_R_LERPTAG, and PASSFLOAT().
Referenced by CG_AddPlayerWeapon(), CG_LoadClientInfo(), CG_PositionEntityOnTag(), and CG_PositionRotatedEntityOnTag().
int trap_R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
References CG_R_LIGHTFORPOINT.
Referenced by CG_LightVerts().
void trap_R_LoadWorldMap (const char * mapname)
References CG_R_LOADWORLDMAP.
Referenced by CG_RegisterGraphics().
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
Referenced by _UI_Init(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawSelectedPlayerHead(), CG_RegisterGraphics(), and CG_RegisterWeapon().
void trap_R_RegisterFont (const char * fontName, int pointSize, fontInfo_t * font)
Referenced by _UI_Init(), and Asset_Parse().
qhandle_t trap_R_RegisterModel (const char * name)
Referenced by _UI_Init(), CG_AddTestModel(), CG_ConfigStringModified(), CG_RegisterClientModelname(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RegisterWeapon(), CG_TestModel_f(), Controls_InitWeapons(), MainMenu_Cache(), UI_PlayerInfo_SetWeapon(), and UI_RegisterClientModelname().
qhandle_t trap_R_RegisterShader (const char * name)
References CG_R_REGISTERSHADER.
Referenced by CG_ClearParticles(), CG_DrawAreaPowerUp(), CG_DrawDisconnect(), CG_DrawInformation(), CG_DrawNewTeamInfo(), CG_DrawPowerups(), CG_DrawSelectedPlayerPowerup(), CG_DrawTeamOverlay(), CG_Init(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), and CG_RegisterWeapon().
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
Referenced by _UI_Init(), ArenaServers_Cache(), Asset_Parse(), AssetCache(), Bitmap_Draw(), CG_DrawInformation(), CG_Init(), CG_LoadingClient(), CG_LoadingItem(), CG_RegisterClientModelname(), CG_RegisterGraphics(), ConfirmMenu_Cache(), Controls_Cache(), Demos_Cache(), DriverInfo_Cache(), GraphicsOptions_Cache(), InGame_Cache(), Login_Cache(), MapList_Parse(), Menu_Cache(), PlayerIcon(), PlayerIconHandle(), PlayerModel_Cache(), PlayerSettings_Cache(), Preferences_Cache(), Rankings_Cache(), RankStatus_Cache(), Reset_Cache(), ServerInfo_Cache(), ServerOptions_Cache(), ServerPlayerIcon(), Signup_Cache(), SpecifyLeague_Cache(), SpecifyServer_Cache(), StartServer_Cache(), StartServer_LevelshotDraw(), SystemConfig_Cache(), Team_Parse(), TeamMain_Cache(), UI_AddBots_Cache(), UI_BotSelectMenu_Cache(), UI_BuildQ3Model_List(), UI_CDKeyMenu_Cache(), UI_CinematicsMenu_Cache(), UI_DisplayOptionsMenu_Cache(), UI_DrawClanLogo(), UI_DrawMapPreview(), UI_DrawNamedPic(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayer(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawTierMap(), UI_FeederItemImage(), UI_FeederSelection(), UI_LoadConfig_Cache(), UI_ModsMenu_Cache(), UI_NetworkOptionsMenu_Cache(), UI_RemoveBots_Cache(), UI_SaveConfigMenu_Cache(), UI_SetupMenu_Cache(), UI_SoundOptionsMenu_Cache(), UI_SPLevelMenu_Cache(), UI_SPLevelMenu_SetMenuArena(), UI_SPPostgameMenu_Cache(), UI_SPSkillMenu_Cache(), and UI_TeamOrdersMenu_Cache().
qhandle_t trap_R_RegisterSkin (const char * name)
Referenced by CG_RegisterClientSkin(), CG_RegisterGraphics(), and UI_RegisterClientSkin().
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
Referenced by CG_ServerCommand(), CG_ShaderStateChanged(), and UI_ConsoleCommand().
void trap_R_RenderScene (const refdef_t * fd)
Referenced by _UI_Init(), CG_Draw3DModel(), CG_DrawActive(), Main_MenuDraw(), and UI_DrawPlayer().
void trap_R_SetColor (const float * rgba)
Referenced by _UI_DrawRect(), Bitmap_Draw(), CG_DrawAreaPowerUp(), CG_DrawBlueFlagStatus(), CG_DrawCenterString(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawPickupItem(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerScore(), CG_DrawPowerups(), CG_DrawRect(), CG_DrawRedFlagStatus(), CG_DrawReward(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHealth(), CG_DrawStatusBar(), CG_DrawStringExt(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawWeaponSelect(), CG_FillRect(), CG_OneFlagStatus(), CG_Text_Paint_Limit(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), UI_DrawBannerString2(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawCrosshair(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawString2(), UI_FillRect(), UI_SetColor(), and UI_SPLevelMenu_MenuDraw().
void trap_S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
References CG_S_ADDLOOPINGSOUND.
Referenced by CG_AddPlayerWeapon(), CG_EntityEffects(), CG_Grapple(), CG_Item(), CG_Missile(), and CG_PlayerPowerups().
void trap_S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
References CG_S_ADDREALLOOPINGSOUND.
Referenced by CG_EntityEffects().
void trap_S_ClearLoopingSounds (qboolean killall)
References CG_S_CLEARLOOPINGSOUNDS.
Referenced by CG_DrawActiveFrame(), CG_Init(), and CG_MapRestart().
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
Referenced by _UI_Init(), Asset_Parse(), AssetCache(), CG_ConfigStringModified(), CG_CustomSound(), CG_EntityEvent(), CG_LoadClientInfo(), CG_LoadingClient(), CG_MachinegunSpinAngle(), CG_ParseVoiceChats(), CG_RegisterItemSounds(), CG_RegisterSounds(), CG_RegisterWeapon(), Menu_Cache(), PlayerModel_BuildList(), UI_SPLevelMenu_Cache(), UI_SPPostgameMenu_Cache(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_f(), and UI_SPSkillMenu_Cache().
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
References CG_S_RESPATIALIZE.
Referenced by CG_DrawActiveFrame().
void trap_S_StartBackgroundTrack (const char * intro, const char * loop)
Referenced by _UI_Init(), and CG_StartMusic().
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Referenced by _UI_Init(), CG_CheckAmmo(), CG_CheckLocalSounds(), CG_ConfigStringModified(), CG_DrawReward(), CG_DrawTeamVote(), CG_DrawVote(), CG_DrawWarmup(), CG_EntityEvent(), CG_MapRestart(), CG_ParseWarmup(), CG_PlayBufferedSounds(), CG_PlayVoiceChat(), CG_ServerCommand(), UI_DrawPlayer(), UI_KeyEvent(), UI_MouseEvent(), UI_OwnerDrawVisible(), UI_PopMenu(), UI_Refresh(), UI_SPLevelMenu_AwardEvent(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_MenuDraw(), UI_SPSkillMenu_BackEvent(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_Key(), and UI_SPSkillMenu_SkillEvent().
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
References CG_S_STARTSOUND.
Referenced by CG_EntityEvent(), CG_FireWeapon(), CG_FragmentBounceSound(), CG_MachinegunSpinAngle(), CG_MissileHitWall(), CG_PainEvent(), CG_PowerupTimerSounds(), CG_Speaker(), CG_TeamBase(), CG_Tracer(), and CG_UseItem().
void trap_S_StopBackgroundTrack (void)
Referenced by _UI_Init().
void trap_S_StopLoopingSound (int entnum)
References CG_S_STOPLOOPINGSOUND.
Referenced by CG_EntityEvent().
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
References CG_S_UPDATEENTITYPOSITION.
Referenced by CG_SetEntitySoundPosition().
void trap_SendClientCommand (const char * s)
References CG_SENDCLIENTCOMMAND.
Referenced by CG_DrawOldTourneyScoreboard(), CG_ScoresDown_f(), CG_TellAttacker_f(), CG_TellTarget_f(), CG_VoiceTellAttacker_f(), and CG_VoiceTellTarget_f().
void trap_SendConsoleCommand (const char * text)
References CG_SENDCONSOLECOMMAND.
Referenced by BotInterbreeding(), CG_CheckOrderPending(), CG_MapRestart(), CG_TargetCommand_f(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientDisconnect(), ClientThink_real(), Cmd_CallVote_f(), ConsoleCommand(), ExitLevel(), G_AddRandomBot(), G_RankRunFrame(), G_RemoveRandomBot(), G_SpawnBots(), LogExit(), PlayerIntroSound(), and UpdateTournamentInfo().
void trap_SetUserCmdValue (int stateValue, float sensitivityScale)
References CG_SETUSERCMDVALUE, and PASSFLOAT().
Referenced by CG_DrawActiveFrame().
void trap_SnapVector (float * v)
Referenced by PmoveSingle().
void trap_startCamera (int time)
void trap_UpdateScreen (void)
Referenced by CG_LoadingString(), and UI_UpdateScreen().
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Variable Documentation
cg_t cg
Referenced by CG_AddBufferedSound(), CG_AddBufferedVoiceChat(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddLagometerFrameInfo(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddMoveScaleFade(), CG_AddPacketEntities(), CG_AddPainTwitch(), CG_AddParticles(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_AddTestModel(), CG_AddToTeamChat(), CG_AddViewWeapon(), CG_Bleed(), CG_BloodPool(), CG_BloodTrail(), CG_BubbleTrail(), CG_BuildSolidList(), CG_CalcEntityLerpPositions(), CG_CalcFov(), CG_CalcMuzzlePoint(), CG_CalculateWeaponPosition(), CG_CalcViewValues(), CG_CalcVrect(), CG_CenterPrint(), CG_CheckAmmo(), CG_CheckChangedPredictableEvents(), CG_CheckEvents(), CG_CheckLocalSounds(), CG_CheckOrderPending(), CG_CheckPlayerstateEvents(), CG_ClearLerpFrame(), CG_ClearParticles(), CG_ClipMoveToEntities(), CG_ColorForHealth(), CG_ConfigStringModified(), CG_DamageBlendBlob(), CG_DamageFeedback(), CG_Draw2D(), CG_Draw3DModel(), CG_DrawActive(), CG_DrawActiveFrame(), CG_DrawAmmoWarning(), CG_DrawAreaPowerUp(), CG_DrawAttacker(), CG_DrawBlueFlagHead(), CG_DrawCenterString(), CG_DrawClientScore(), CG_DrawCrosshair(), CG_DrawCrosshair3D(), CG_DrawCrosshairNames(), CG_DrawCTFPowerUp(), CG_DrawDisconnect(), CG_DrawFlagModel(), CG_DrawFollow(), CG_DrawHoldableItem(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawKiller(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawOldScoreboard(), CG_DrawOldTourneyScoreboard(), CG_DrawPickupItem(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHasFlag(), CG_DrawPlayerHead(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawPlayerLocation(), CG_DrawPlayerScore(), CG_DrawPlayerStatus(), CG_DrawPowerups(), CG_DrawRedFlagHead(), CG_DrawReward(), CG_DrawScoreboard(), CG_DrawScores(), CG_DrawSelectedPlayerStatus(), CG_DrawSnapshot(), CG_DrawStatusBar(), CG_DrawStatusBarHead(), CG_DrawTeamColor(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawTeamSpectators(), CG_DrawTeamVote(), CG_DrawTimer(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeaponSelect(), CG_EntityEvent(), CG_FadeColor(), CG_FireWeapon(), CG_General(), CG_GetGameStatusText(), CG_GetKillerText(), CG_GetTeamColor(), CG_GetValue(), CG_Grapple(), CG_GrappleTrail(), CG_HarvesterSkulls(), CG_HasteTrail(), CG_ImpactMark(), CG_InterpolateEntityPosition(), CG_InterpolatePlayerState(), CG_Item(), CG_ItemPickup(), CG_KeyEvent(), CG_LaunchExplode(), CG_LaunchGib(), CG_LightningBolt(), CG_LoadingString(), CG_MachineGunEjectBrass(), CG_MachinegunSpinAngle(), CG_MakeExplosion(), CG_MapRestart(), CG_Missile(), CG_MouseEvent(), CG_Mover(), CG_NewClientInfo(), CG_NextWeapon_f(), CG_Obituary(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_OilSlickRemove(), CG_OtherTeamHasFlag(), CG_OutOfAmmoChange(), CG_OwnerDrawVisible(), CG_PainEvent(), CG_ParseScores(), CG_ParseWarmup(), CG_Particle_Bleed(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBloodCloud(), CG_ParticleBubble(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleExplosion(), CG_ParticleImpactSmokePuff(), CG_ParticleMisc(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), CG_ParticleSparks(), CG_PlasmaTrail(), CG_PlayBufferedSounds(), CG_PlayBufferedVoiceChats(), CG_Player(), CG_PlayerFloatSprite(), CG_PlayerSprites(), CG_PlayVoiceChat(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_PrevWeapon_f(), CG_ProcessSnapshots(), CG_RailTrail(), CG_ReadNextSnapshot(), CG_ReflectVelocity(), CG_ResetEntity(), CG_ResetPlayerEntity(), CG_Respawn(), CG_RocketTrail(), CG_RunLerpFrame(), CG_ScanForCrosshairEntity(), CG_ScorePlum(), CG_ScoresDown_f(), CG_ScoresUp_f(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_ShotgunEjectBrass(), CG_ShotgunFire(), CG_ShowResponseHead(), CG_SpawnEffect(), CG_Speaker(), CG_StepOffset(), CG_SwingAngles(), CG_TeamBase(), CG_TeamScoreboard(), CG_TestGun_f(), CG_TestModel_f(), CG_TestModelNextFrame_f(), CG_TestModelNextSkin_f(), CG_TestModelPrevFrame_f(), CG_TestModelPrevSkin_f(), CG_TileClear(), CG_TouchItem(), CG_TouchTriggerPrediction(), CG_Tracer(), CG_TransitionPlayerState(), CG_TransitionSnapshot(), CG_UseItem(), CG_Viewpos_f(), CG_VoiceChatLocal(), CG_Weapon_f(), CG_WeaponSelectable(), CG_YourTeamHasFlag(), CG_ZoomDown_f(), CG_ZoomUp_f(), pushReward(), and UI_DrawProportionalString().
vmCvar_t cg_addMarks
Referenced by CG_AddMarks(), and CG_ImpactMark().
vmCvar_t cg_animSpeed
Referenced by CG_RunLerpFrame().
vmCvar_t cg_autoswitch
Referenced by CG_ItemPickup().
vmCvar_t cg_bigFont
Referenced by CG_Text_Paint_Limit().
vmCvar_t cg_blood
Referenced by CG_BigExplode(), CG_Bleed(), CG_DamageBlendBlob(), and CG_GibPlayer().
vmCvar_t cg_bobpitch
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_bobroll
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_bobup
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_brassTime
Referenced by CG_FireWeapon(), CG_MachineGunEjectBrass(), and CG_ShotgunEjectBrass().
vmCvar_t cg_buildScript
Referenced by CG_LoadClientInfo(), CG_NewClientInfo(), and CG_ParseVoiceChats().
vmCvar_t cg_cameraMode
Referenced by CG_OffsetThirdPersonView(), and CG_Player().
vmCvar_t cg_cameraOrbit
Referenced by CG_CalcViewValues(), CG_Obituary(), and CG_StartOrbit_f().
vmCvar_t cg_cameraOrbitDelay
Referenced by CG_CalcViewValues().
vmCvar_t cg_centertime
Referenced by CG_DrawCenterString().
vmCvar_t cg_crosshairHealth
Referenced by CG_DrawCrosshair().
vmCvar_t cg_crosshairSize
Referenced by CG_DrawCrosshair(), and CG_DrawCrosshair3D().
vmCvar_t cg_crosshairX
Referenced by CG_DrawCrosshair().
vmCvar_t cg_crosshairY
Referenced by CG_DrawCrosshair().
vmCvar_t cg_debugAnim
Referenced by CG_RunLerpFrame(), and CG_SetLerpFrameAnimation().
vmCvar_t cg_debugEvents
Referenced by CG_EntityEvent().
vmCvar_t cg_debugPosition
Referenced by CG_ResetPlayerEntity().
vmCvar_t cg_deferPlayers
Referenced by CG_NewClientInfo().
vmCvar_t cg_draw2D
Referenced by CG_Draw2D().
vmCvar_t cg_draw3dIcons
Referenced by CG_Draw3DModel(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerArmorIcon(), CG_DrawSelectedPlayerHead(), CG_DrawStatusBar(), and CG_HarvesterSkulls().
vmCvar_t cg_drawAmmoWarning
Referenced by CG_DrawAmmoWarning().
vmCvar_t cg_drawAttacker
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawCrosshair
Referenced by CG_DrawCrosshair(), CG_DrawCrosshair3D(), and CG_DrawCrosshairNames().
vmCvar_t cg_drawCrosshairNames
Referenced by CG_DrawCrosshairNames().
vmCvar_t cg_drawFPS
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawFriend
Referenced by CG_PlayerSprites().
vmCvar_t cg_drawGun
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), and CG_EntityEvent().
vmCvar_t cg_drawIcons
Referenced by CG_Draw3DModel(), CG_DrawClientScore(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerArmorIcon(), CG_DrawSelectedPlayerHead(), CG_DrawStatusBar(), and CG_HarvesterSkulls().
vmCvar_t cg_drawRewards
Referenced by CG_DrawReward().
vmCvar_t cg_drawSnapshot
Referenced by CG_DrawUpperRight().
vmCvar_t cg_drawStatus
Referenced by CG_Draw2D(), CG_DrawPlayerArmorIcon(), CG_DrawStatusBar(), and CG_OwnerDraw().
vmCvar_t cg_drawTeamOverlay
Referenced by CG_DrawLowerLeft(), CG_DrawLowerRight(), CG_DrawTeamOverlay(), and CG_DrawUpperRight().
vmCvar_t cg_drawTimer
Referenced by CG_DrawUpperRight().
centity_t cg_entities[MAX_GENTITIES]
Referenced by CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_AdjustPositionForMover(), CG_BuildSolidList(), CG_CalcMuzzlePoint(), CG_CheckPlayerstateEvents(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawStatusBar(), CG_GetValue(), CG_GrappleTrail(), CG_LoadClientInfo(), CG_ScanForCrosshairEntity(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_ShotgunPellet(), and CG_TransitionSnapshot().
vmCvar_t cg_errorDecay
Referenced by CG_CalcViewValues(), and CG_PredictPlayerState().
vmCvar_t cg_footsteps
Referenced by CG_EntityEvent().
vmCvar_t cg_forceModel
Referenced by CG_NewClientInfo().
vmCvar_t cg_fov
Referenced by CG_AddViewWeapon(), and CG_CalcFov().
vmCvar_t cg_gibs
Referenced by CG_GibPlayer().
vmCvar_t cg_gun_frame
Referenced by CG_AddViewWeapon().
vmCvar_t cg_gun_x
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_gun_y
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_gun_z
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
vmCvar_t cg_ignore
itemInfo_t cg_items[MAX_ITEMS]
Referenced by CG_DrawCTFPowerUp(), CG_DrawFlagModel(), CG_DrawHoldableItem(), CG_DrawPickupItem(), CG_DrawPlayerItem(), CG_Item(), and CG_RegisterItemVisuals().
vmCvar_t cg_lagometer
Referenced by CG_DrawLagometer().
markPoly_t cg_markPolys[MAX_MARK_POLYS]
Referenced by CG_InitMarkPolys().
vmCvar_t cg_noPlayerAnims
Referenced by CG_PlayerAnimation().
vmCvar_t cg_nopredict
Referenced by CG_DrawLagometer(), CG_EntityEvent(), CG_PredictPlayerState(), and CG_TransitionSnapshot().
vmCvar_t cg_noProjectileTrail
Referenced by CG_BubbleTrail(), CG_PlasmaTrail(), and CG_RocketTrail().
vmCvar_t cg_noTaunt
Referenced by CG_VoiceChat().
vmCvar_t cg_noVoiceChats
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_noVoiceText
Referenced by CG_PlayVoiceChat().
vmCvar_t cg_oldPlasma
Referenced by CG_PlasmaTrail().
vmCvar_t cg_oldRail
Referenced by CG_RailTrail().
vmCvar_t cg_oldRocket
Referenced by CG_MissileHitWall().
vmCvar_t cg_paused
Referenced by CG_Draw2D(), CG_DrawOldScoreboard(), and CG_DrawScoreboard().
vmCvar_t cg_predictItems
Referenced by CG_TouchItem().
vmCvar_t cg_railTrailTime
Referenced by CG_RailTrail().
vmCvar_t cg_runpitch
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_runroll
Referenced by CG_OffsetFirstPersonView().
vmCvar_t cg_scorePlum
Referenced by CG_ScorePlum().
vmCvar_t cg_shadows
Referenced by CG_Player(), CG_PlayerShadow(), and CG_PlayerSplash().
vmCvar_t cg_showmiss
Referenced by CG_CheckChangedPredictableEvents(), CG_MapRestart(), and CG_PredictPlayerState().
vmCvar_t cg_simpleItems
Referenced by CG_Item().
vmCvar_t cg_smallFont
Referenced by CG_Text_Paint_Limit().
vmCvar_t cg_smoothClients
Referenced by CG_CalcEntityLerpPositions().
vmCvar_t cg_stats
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_swingSpeed
Referenced by CG_PlayerAngles().
vmCvar_t cg_synchronousClients
Referenced by CG_DrawLagometer(), CG_EntityEvent(), CG_PredictPlayerState(), and CG_TransitionSnapshot().
vmCvar_t cg_teamChatHeight
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
vmCvar_t cg_teamChatsOnly
Referenced by CG_ServerCommand(), and CG_VoiceChatLocal().
vmCvar_t cg_teamChatTime
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
vmCvar_t cg_teamOverlayUserinfo
vmCvar_t cg_thirdPerson
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_thirdPersonAngle
Referenced by CG_CalcViewValues(), and CG_OffsetThirdPersonView().
vmCvar_t cg_thirdPersonRange
Referenced by CG_OffsetThirdPersonView().
vmCvar_t cg_timescale
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_timescaleFadeEnd
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_timescaleFadeSpeed
Referenced by CG_DrawActiveFrame().
vmCvar_t cg_tracerChance
Referenced by CG_Bullet().
vmCvar_t cg_tracerLength
Referenced by CG_Tracer().
vmCvar_t cg_tracerWidth
Referenced by CG_Tracer().
vmCvar_t cg_trueLightning
Referenced by CG_LightningBolt().
vmCvar_t cg_viewsize
Referenced by CG_CalcVrect(), CG_SizeDown_f(), and CG_SizeUp_f().
weaponInfo_t cg_weapons[MAX_WEAPONS]
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_DrawNewTeamInfo(), CG_DrawPlayerAmmoIcon(), CG_DrawSelectedPlayerWeapon(), CG_DrawStatusBar(), CG_DrawTeamOverlay(), CG_DrawWeaponSelect(), CG_FireWeapon(), CG_Grapple(), CG_Item(), CG_Missile(), and CG_RegisterWeapon().
vmCvar_t cg_zoomFov
Referenced by CG_CalcFov().
cgs_t cgs
Referenced by CG_AddMarks(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScorePlum(), CG_AddToTeamChat(), CG_AddViewWeapon(), CG_AddWeaponWithPowerups(), CG_AdjustFrom640(), CG_BigExplode(), CG_Bleed(), CG_BloodTrail(), CG_BubbleTrail(), CG_CalcFov(), CG_CalcVrect(), CG_CheckAmmo(), CG_CheckLocalSounds(), CG_CheckOrderPending(), CG_ClientNumFromName(), CG_ConfigStringModified(), CG_CustomSound(), CG_DamageBlendBlob(), CG_Draw1stPlace(), CG_Draw2D(), CG_Draw2ndPlace(), CG_DrawBlueFlagHead(), CG_DrawBlueFlagName(), CG_DrawBlueFlagStatus(), CG_DrawBlueScore(), CG_DrawCapFragLimit(), CG_DrawChar(), CG_DrawClientScore(), CG_DrawCrosshair(), CG_DrawCrosshair3D(), CG_DrawCrosshairNames(), CG_DrawCTFPowerUp(), CG_DrawField(), CG_DrawFlagModel(), CG_DrawFollow(), CG_DrawHead(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawLagometer(), CG_DrawLowerLeft(), CG_DrawLowerRight(), CG_DrawNewTeamInfo(), CG_DrawOldScoreboard(), CG_DrawOldTourneyScoreboard(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerLocation(), CG_DrawPlayerStatus(), CG_DrawRedFlagHead(), CG_DrawRedFlagName(), CG_DrawRedFlagStatus(), CG_DrawRedScore(), CG_DrawScoreboard(), CG_DrawScores(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), CG_DrawSides(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawStatusBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawTeamVote(), CG_DrawTimer(), CG_DrawTopBottom(), CG_DrawUpperRight(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeaponSelect(), CG_EntityEffects(), CG_EntityEvent(), CG_EventHandling(), CG_ExecuteNewServerCommands(), CG_FillRect(), CG_FindClientHeadFile(), CG_FindClientModelFile(), CG_FireWeapon(), CG_FragmentBounceMark(), CG_FragmentBounceSound(), CG_GameTypeString(), CG_General(), CG_GetGameStatusText(), CG_GetValue(), CG_GibPlayer(), CG_GrappleTrail(), CG_HarvesterSkulls(), CG_HasteTrail(), CG_Item(), CG_KeyEvent(), CG_LightningBolt(), CG_LoadClientInfo(), CG_LoadDeferredPlayers(), CG_LoadingClient(), CG_MachineGunEjectBrass(), CG_MapRestart(), CG_Missile(), CG_MissileHitWall(), CG_MouseEvent(), CG_Mover(), CG_NewClientInfo(), CG_NewParticleArea(), CG_Obituary(), CG_OneFlagStatus(), CG_OtherTeamHasFlag(), CG_OwnerDrawVisible(), CG_ParseScores(), CG_ParseServerinfo(), CG_ParseTeamInfo(), CG_ParseWarmup(), CG_ParticleBloodCloud(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleSparks(), CG_PlasmaTrail(), CG_Player(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PlayerFlag(), CG_PlayerPowerups(), CG_PlayerShadow(), CG_PlayerSplash(), CG_PlayerSprites(), CG_PlayVoiceChat(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_RailTrail(), CG_ReadNextSnapshot(), CG_RegisterWeapon(), CG_ResetPlayerEntity(), CG_RocketTrail(), CG_ScanForExistingClientInfo(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetDeferredClientInfo(), CG_SetEntitySoundPosition(), CG_SetSelectedPlayerName(), CG_ShotgunEjectBrass(), CG_ShotgunFire(), CG_SmokePuff(), CG_SpawnEffect(), CG_Speaker(), CG_StatusHandle(), CG_TeamBase(), CG_TeamScoreboard(), CG_TileClear(), CG_TouchItem(), CG_Tracer(), CG_UseItem(), CG_VoiceChatListForClient(), CG_VoiceChatLocal(), CG_YourTeamHasFlag(), UI_DrawBannerString2(), UI_DrawProportionalString(), UI_DrawProportionalString2(), and vmMain().
int drawTeamOverlayModificationCount
Referenced by CG_UpdateCvars().
qboolean initparticles
Referenced by CG_AddParticles(), and CG_ClearParticles().
int numSortedTeamPlayers
Referenced by CG_CheckOrderPending(), CG_DrawNewTeamInfo(), CG_DrawTeamOverlay(), CG_GetSelectedPlayer(), CG_OwnerDraw(), CG_OwnerDrawVisible(), CG_ParseTeamInfo(), CG_SelectNextPlayer(), CG_SelectPrevPlayer(), and CG_SetSelectedPlayerName().
vmCvar_t pmove_fixed
Referenced by CG_PredictPlayerState(), and ClientThink_real().
vmCvar_t pmove_msec
Referenced by CG_PredictPlayerState(), and ClientThink_real().
int sortedTeamPlayers[TEAM_MAXOVERLAY]
Referenced by CG_CheckOrderPending(), CG_DrawNewTeamInfo(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), CG_DrawTeamOverlay(), CG_GetValue(), CG_ParseTeamInfo(), and CG_SetSelectedPlayerName().
char systemChat[256]
Referenced by CG_DrawAreaSystemChat(), CG_InitTeamChat(), and CG_SetPrintString().
char teamChat1[256]
Referenced by CG_DrawAreaTeamChat(), CG_InitTeamChat(), and CG_SetPrintString().
char teamChat2[256]
Referenced by CG_DrawAreaChat(), CG_InitTeamChat(), and CG_SetPrintString().