ioquake3: code/cgame/cg_view.c File Reference
cg_view.c File Reference
#include "cg_local.h"
Defines
#define FOCUS_DISTANCE 512
#define WAVE_AMPLITUDE 1
#define WAVE_FREQUENCY 0.4
Functions
void CG_TestModel_f (void)
void CG_TestGun_f (void)
void CG_TestModelNextFrame_f (void)
void CG_TestModelPrevFrame_f (void)
void CG_TestModelNextSkin_f (void)
void CG_TestModelPrevSkin_f (void)
static void CG_AddTestModel (void)
static void CG_CalcVrect (void)
static void CG_OffsetThirdPersonView (void)
static void CG_StepOffset (void)
static void CG_OffsetFirstPersonView (void)
void CG_ZoomDown_f (void)
void CG_ZoomUp_f (void)
static int CG_CalcFov (void)
static void CG_DamageBlendBlob (void)
static int CG_CalcViewValues (void)
static void CG_PowerupTimerSounds (void)
void CG_AddBufferedSound (sfxHandle_t sfx)
static void CG_PlayBufferedSounds (void)
void CG_DrawActiveFrame (int serverTime, stereoFrame_t stereoView, qboolean demoPlayback)
Define Documentation
#define FOCUS_DISTANCE 512
Referenced by CG_OffsetThirdPersonView().
#define WAVE_AMPLITUDE 1
Referenced by CG_CalcFov().
#define WAVE_FREQUENCY 0.4
Referenced by CG_CalcFov().
Function Documentation
void CG_AddBufferedSound (sfxHandle_t sfx)
References cg, MAX_SOUNDBUFFER, cg_t::soundBuffer, cg_t::soundBufferIn, and cg_t::soundBufferOut.
Referenced by CG_CheckLocalSounds(), and CG_EntityEvent().
static void CG_AddTestModel (void) [static]
References refEntity_t::axis, cg, cg_gun_x, cg_gun_y, cg_gun_z, CG_Printf(), refEntity_t::hModel, refEntity_t::origin, cg_t::refdef, cg_t::testGun, cg_t::testModelEntity, cg_t::testModelName, trap_R_AddRefEntityToScene(), trap_R_RegisterModel(), vmCvar_t::value, VectorCopy, refdef_t::viewaxis, and refdef_t::vieworg.
Referenced by CG_DrawActiveFrame().
static int CG_CalcFov (void) [static]
References cg, cg_fov, CG_PointContents(), cg_zoomFov, cgs, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, DF_FIXED_FOV, cgs_t::dmflags, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, M_PI, PM_INTERMISSION, playerState_s::pm_type, cg_t::predictedPlayerState, qfalse, qtrue, cg_t::refdef, cg_t::time, vmCvar_t::value, refdef_t::vieworg, WAVE_AMPLITUDE, WAVE_FREQUENCY, refdef_t::width, ZOOM_TIME, cg_t::zoomed, cg_t::zoomSensitivity, and cg_t::zoomTime.
Referenced by CG_CalcViewValues().
static int CG_CalcViewValues (void) [static]
References AnglesToAxis(), cg_t::bobcycle, playerState_s::bobCycle, cg_t::bobfracsin, cg, CG_CalcFov(), CG_CalcVrect(), cg_cameraOrbit, cg_cameraOrbitDelay, cg_errorDecay, CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), cg_thirdPersonAngle, cg_t::hyperspace, if(), vmCvar_t::integer, M_PI, cg_t::nextOrbitTime, playerState_s::origin, PM_INTERMISSION, playerState_s::pm_type, cg_t::predictedError, cg_t::predictedErrorTime, cg_t::predictedPlayerState, RDF_HYPERSPACE, RDF_NOWORLDMODEL, refdef_t::rdflags, cg_t::refdef, cg_t::refdefViewAngles, cg_t::renderingThirdPerson, t, cg_t::time, vmCvar_t::value, VectorCopy, VectorMA(), playerState_s::velocity, playerState_s::viewangles, refdef_t::viewaxis, refdef_t::vieworg, and cg_t::xyspeed.
Referenced by CG_DrawActiveFrame().
static void CG_CalcVrect (void) [static]
References cg, cg_viewsize, cgs, cgs_t::glconfig, refdef_t::height, vmCvar_t::integer, PM_INTERMISSION, playerState_s::pm_type, snapshot_t::ps, cg_t::refdef, cg_t::snap, trap_Cvar_Set(), glconfig_t::vidHeight, glconfig_t::vidWidth, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by CG_CalcViewValues().
static void CG_DamageBlendBlob (void) [static]
References cg, cg_blood, cgs, refEntity_t::customShader, DAMAGE_TIME, cg_t::damageTime, cg_t::damageValue, cg_t::damageX, cg_t::damageY, cgs_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, vmCvar_t::integer, cgs_t::media, refEntity_t::origin, refEntity_t::radius, cg_t::refdef, refEntity_t::renderfx, refEntity_t::reType, RF_FIRST_PERSON, RT_SPRITE, refEntity_t::shaderRGBA, t, cg_t::time, trap_R_AddRefEntityToScene(), VectorMA(), refdef_t::viewaxis, cgMedia_t::viewBloodShader, and refdef_t::vieworg.
Referenced by CG_DrawActiveFrame().
void CG_DrawActiveFrame (int serverTime, stereoFrame_t stereoView, qboolean demoPlayback)
References snapshot_t::areamask, refdef_t::areamask, cg, CG_AddLagometerFrameInfo(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddPacketEntities(), CG_AddParticles(), CG_AddTestModel(), CG_AddViewWeapon(), CG_CalcViewValues(), CG_DamageBlendBlob(), CG_DrawActive(), CG_DrawInformation(), CG_PlayBufferedSounds(), CG_PlayBufferedVoiceChats(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_Printf(), CG_ProcessSnapshots(), cg_stats, cg_thirdPerson, cg_timescale, cg_timescaleFadeEnd, cg_timescaleFadeSpeed, CG_UpdateCvars(), cg_t::clientFrame, playerState_s::clientNum, cg_t::demoPlayback, cg_t::frametime, refEntity_t::hModel, cg_t::hyperspace, cg_t::infoScreenText, vmCvar_t::integer, cg_t::oldTime, cg_t::predictedPlayerState, snapshot_t::ps, qfalse, cg_t::refdef, cg_t::renderingThirdPerson, cg_t::snap, SNAPFLAG_NOT_ACTIVE, snapshot_t::snapFlags, STAT_HEALTH, playerState_s::stats, STEREO_RIGHT, cg_t::testModelEntity, refdef_t::time, cg_t::time, trap_Cvar_Set(), trap_R_ClearScene(), trap_S_ClearLoopingSounds(), trap_S_Respatialize(), trap_SetUserCmdValue(), va(), vmCvar_t::value, refdef_t::viewaxis, refdef_t::vieworg, cg_t::weaponSelect, and cg_t::zoomSensitivity.
Referenced by vmMain().
static void CG_OffsetFirstPersonView (void) [static]
References AngleVectors(), cg_t::bobcycle, cg_t::bobfracsin, cg, cg_bobpitch, cg_bobroll, cg_bobup, cg_runpitch, cg_runroll, CG_StepOffset(), DAMAGE_DEFLECT_TIME, DAMAGE_RETURN_TIME, cg_t::damageTime, DotProduct, DUCK_TIME, cg_t::duckChange, cg_t::duckTime, forward, LAND_DEFLECT_TIME, LAND_RETURN_TIME, cg_t::landChange, cg_t::landTime, NULL, PITCH, playerState_s::pm_flags, PM_INTERMISSION, playerState_s::pm_type, PMF_DUCKED, cg_t::predictedPlayerState, snapshot_t::ps, cg_t::refdef, cg_t::refdefViewAngles, ROLL, cg_t::snap, STAT_DEAD_YAW, STAT_HEALTH, playerState_s::stats, cg_t::time, up, cg_t::v_dmg_pitch, cg_t::v_dmg_roll, vmCvar_t::value, VectorCopy, VectorMA(), playerState_s::velocity, refdef_t::viewaxis, playerState_s::viewheight, refdef_t::vieworg, cg_t::xyspeed, and YAW.
Referenced by CG_CalcViewValues().
static void CG_OffsetThirdPersonView (void) [static]
References AngleVectors(), cg, cg_cameraMode, cg_thirdPersonAngle, cg_thirdPersonRange, CG_Trace(), playerState_s::clientNum, trace_t::endpos, FOCUS_DISTANCE, forward, trace_t::fraction, vmCvar_t::integer, M_PI, MASK_SOLID, NULL, PITCH, cg_t::predictedPlayerState, cg_t::refdef, cg_t::refdefViewAngles, right, STAT_DEAD_YAW, STAT_HEALTH, playerState_s::stats, up, vmCvar_t::value, VectorCopy, VectorMA(), VectorSubtract, playerState_s::viewheight, refdef_t::vieworg, and YAW.
Referenced by CG_CalcViewValues().
static void CG_PlayBufferedSounds (void) [static]
References cg, CHAN_ANNOUNCER, MAX_SOUNDBUFFER, cg_t::soundBuffer, cg_t::soundBufferIn, cg_t::soundBufferOut, cg_t::soundTime, cg_t::time, and trap_S_StartLocalSound().
Referenced by CG_DrawActiveFrame().
static void CG_PowerupTimerSounds (void) [static]
References cg, cgs, CHAN_ITEM, playerState_s::clientNum, MAX_POWERUPS, cgs_t::media, NULL, cg_t::oldTime, POWERUP_BLINK_TIME, POWERUP_BLINKS, playerState_s::powerups, snapshot_t::ps, cg_t::snap, t, cg_t::time, trap_S_StartSound(), and cgMedia_t::wearOffSound.
Referenced by CG_DrawActiveFrame().
static void CG_StepOffset (void) [static]
References cg, cg_t::refdef, STEP_TIME, cg_t::stepChange, cg_t::stepTime, cg_t::time, and refdef_t::vieworg.
Referenced by CG_OffsetFirstPersonView().
void CG_TestGun_f (void)
References cg, CG_TestModel_f(), qtrue, refEntity_t::renderfx, RF_DEPTHHACK, RF_FIRST_PERSON, RF_MINLIGHT, cg_t::testGun, and cg_t::testModelEntity.
void CG_TestModel_f (void)
References AnglesToAxis(), refEntity_t::axis, refEntity_t::backlerp, cg, CG_Argv(), CG_Printf(), refEntity_t::frame, refEntity_t::hModel, MAX_QPATH, refEntity_t::oldframe, refEntity_t::origin, PITCH, Q_strncpyz(), qfalse, cg_t::refdef, cg_t::refdefViewAngles, ROLL, cg_t::testGun, cg_t::testModelEntity, cg_t::testModelName, trap_Argc(), trap_R_RegisterModel(), VectorMA(), refdef_t::viewaxis, refdef_t::vieworg, and YAW.
Referenced by CG_TestGun_f().
void CG_TestModelNextFrame_f (void)
References cg, CG_Printf(), refEntity_t::frame, and cg_t::testModelEntity.
void CG_TestModelNextSkin_f (void)
References cg, CG_Printf(), refEntity_t::skinNum, and cg_t::testModelEntity.
void CG_TestModelPrevFrame_f (void)
References cg, CG_Printf(), refEntity_t::frame, and cg_t::testModelEntity.
void CG_TestModelPrevSkin_f (void)
References cg, CG_Printf(), refEntity_t::skinNum, and cg_t::testModelEntity.
void CG_ZoomDown_f (void)
References cg, qtrue, cg_t::time, cg_t::zoomed, and cg_t::zoomTime.
void CG_ZoomUp_f (void)
References cg, qfalse, cg_t::time, cg_t::zoomed, and cg_t::zoomTime.