ioquake3: code/cgame/cg_particles.c File Reference
cg_particles.c File Reference
#include "cg_local.h"
Data Structures
struct particle_s
Defines
#define BLOODRED 2
#define EMISIVEFADE 3
#define GREY75 4
#define MAX_SHADER_ANIMS 32
#define MAX_SHADER_ANIM_FRAMES 64
#define PARTICLE_GRAVITY 40
#define MAX_PARTICLES 1024
#define EXTRUDE_DIST 0.5
#define NORMALSIZE 16
#define LARGESIZE 32
Typedefs
typedef struct particle_s cparticle_t
Enumerations
enum particle_type_t {
P_NONE, P_WEATHER, P_FLAT, P_SMOKE,
P_ROTATE, P_WEATHER_TURBULENT, P_ANIM, P_BAT,
P_BLEED, P_FLAT_SCALEUP, P_FLAT_SCALEUP_FADE, P_WEATHER_FLURRY,
P_SMOKE_IMPACT, P_BUBBLE, P_BUBBLE_TURBULENT, P_SPRITE
}
Functions
void CG_ClearParticles (void)
void CG_AddParticleToScene (cparticle_t *p, vec3_t org, float alpha)
void CG_AddParticles (void)
void CG_ParticleSnowFlurry (qhandle_t pshader, centity_t *cent)
void CG_ParticleSnow (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
void CG_ParticleBubble (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
void CG_ParticleSmoke (qhandle_t pshader, centity_t *cent)
void CG_ParticleBulletDebris (vec3_t org, vec3_t vel, int duration)
void CG_ParticleExplosion (char *animStr, vec3_t origin, vec3_t vel, int duration, int sizeStart, int sizeEnd)
void CG_AddParticleShrapnel (localEntity_t *le)
int CG_NewParticleArea (int num)
void CG_SnowLink (centity_t *cent, qboolean particleOn)
void CG_ParticleImpactSmokePuff (qhandle_t pshader, vec3_t origin)
void CG_Particle_Bleed (qhandle_t pshader, vec3_t start, vec3_t dir, int fleshEntityNum, int duration)
void CG_Particle_OilParticle (qhandle_t pshader, centity_t *cent)
void CG_Particle_OilSlick (qhandle_t pshader, centity_t *cent)
void CG_OilSlickRemove (centity_t *cent)
qboolean ValidBloodPool (vec3_t start)
void CG_BloodPool (localEntity_t *le, qhandle_t pshader, trace_t *tr)
void CG_ParticleBloodCloud (centity_t *cent, vec3_t origin, vec3_t dir)
void CG_ParticleSparks (vec3_t org, vec3_t vel, int duration, float x, float y, float speed)
void CG_ParticleDust (centity_t *cent, vec3_t origin, vec3_t dir)
void CG_ParticleMisc (qhandle_t pshader, vec3_t origin, int size, int duration, float alpha)
Variables
static char * shaderAnimNames [MAX_SHADER_ANIMS]
static qhandle_t shaderAnims [MAX_SHADER_ANIMS][MAX_SHADER_ANIM_FRAMES]
static int shaderAnimCounts [MAX_SHADER_ANIMS]
static float shaderAnimSTRatio [MAX_SHADER_ANIMS]
static int numShaderAnims
cparticle_t * active_particles
cparticle_t * free_particles
cparticle_t particles [MAX_PARTICLES]
int cl_numparticles = MAX_PARTICLES
qboolean initparticles = qfalse
vec3_t vforward
vec3_t vright
vec3_t vup
vec3_t rforward
vec3_t rright
vec3_t rup
float oldtime
static float roll = 0.0
Define Documentation
#define BLOODRED 2
Referenced by CG_AddParticleToScene(), CG_BloodPool(), CG_Particle_Bleed(), and CG_ParticleBloodCloud().
#define EMISIVEFADE 3
Referenced by CG_AddParticleToScene(), CG_ParticleBulletDebris(), and CG_ParticleSparks().
#define EXTRUDE_DIST 0.5
Referenced by ValidBloodPool().
#define GREY75 4
Referenced by CG_AddParticleToScene().
#define LARGESIZE 32
Referenced by CG_ParticleBloodCloud(), and CG_ParticleDust().
#define MAX_PARTICLES 1024
#define MAX_SHADER_ANIM_FRAMES 64
#define MAX_SHADER_ANIMS 32
#define NORMALSIZE 16
Referenced by CG_ParticleDust().
#define PARTICLE_GRAVITY 40
Referenced by CG_ParticleDust().
Typedef Documentation
typedef struct particle_s cparticle_t
Enumeration Type Documentation
enum particle_type_t
Enumerator:
P_NONE
P_WEATHER
P_FLAT
P_SMOKE
P_ROTATE
P_WEATHER_TURBULENT
P_ANIM
P_BAT
P_BLEED
P_FLAT_SCALEUP
P_FLAT_SCALEUP_FADE
P_WEATHER_FLURRY
P_SMOKE_IMPACT
P_BUBBLE
P_BUBBLE_TURBULENT
P_SPRITE
Function Documentation
void CG_AddParticles (void)
References particle_s::accel, particle_s::alpha, particle_s::alphavel, AngleVectors(), cg, CG_AddParticleToScene(), CG_ClearParticles(), particle_s::color, particle_s::endtime, free_particles, initparticles, particle_s::next, NULL, oldtime, particle_s::org, P_ANIM, P_BAT, P_BLEED, P_FLAT_SCALEUP_FADE, P_SMOKE, P_SMOKE_IMPACT, P_SPRITE, P_WEATHER_FLURRY, cg_t::refdef, rforward, ROLL, roll, rright, rup, tail, particle_s::time, cg_t::time, particle_s::type, vectoangles(), VectorCopy, particle_s::vel, vforward, refdef_t::viewaxis, vright, and vup.
Referenced by CG_DrawActiveFrame().
void CG_AddParticleShrapnel (localEntity_t * le)
void CG_AddParticleToScene (cparticle_t * p, vec3_t org, float alpha)
References particle_s::accumroll, particle_s::alpha, AngleVectors(), BLOODRED, cg, cgs, particle_s::color, crandom, DEG2RAD, Distance(), EMISIVEFADE, particle_s::end, particle_s::endheight, particle_s::endtime, particle_s::endwidth, cgs_t::glconfig, GLHW_RAGEPRO, GREY75, glconfig_t::hardwareType, height, particle_s::height, int(), particle_s::link, polyVert_t::modulate, NULL, particle_s::org, playerState_s::origin, P_ANIM, P_BLEED, P_BUBBLE, P_BUBBLE_TURBULENT, P_FLAT, P_FLAT_SCALEUP, P_SMOKE, P_SMOKE_IMPACT, P_SPRITE, P_WEATHER, P_WEATHER_FLURRY, P_WEATHER_TURBULENT, snapshot_t::ps, particle_s::pshader, cg_t::refdef, rforward, particle_s::roll, ROLL, particle_s::rotate, rright, rup, particle_s::shaderAnim, shaderAnimCounts, shaderAnims, cg_t::snap, polyVert_t::st, particle_s::start, particle_s::startfade, particle_s::time, cg_t::time, trap_R_AddPolyToScene(), particle_s::type, val, vectoangles(), VectorCopy, VectorMA(), VectorSet, particle_s::vel, refdef_t::viewaxis, vright, vup, width, particle_s::width, and polyVert_t::xyz.
Referenced by CG_AddParticles().
void CG_BloodPool (localEntity_t * le, qhandle_t pshader, trace_t * tr)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, BLOODRED, cg, CG_Printf(), particle_s::color, particle_s::endheight, trace_t::endpos, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_FLAT_SCALEUP, particle_s::pshader, qfalse, random, particle_s::roll, particle_s::rotate, start, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, ValidBloodPool(), VectorClear, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ClearParticles (void)
References cg, cl_numparticles, initparticles, particle_s::next, NULL, numShaderAnims, oldtime, qtrue, shaderAnimCounts, shaderAnimNames, shaderAnims, cg_t::time, trap_R_RegisterShader(), particle_s::type, and va().
Referenced by CG_AddParticles(), CG_MapRestart(), and CG_RegisterGraphics().
int CG_NewParticleArea (int num)
References CG_ConfigString(), CG_ParticleBubble(), CG_ParticleSnow(), cgs, COM_Parse(), cgs_t::media, range(), particle_s::snum, token, type(), and cgMedia_t::waterBubbleShader.
void CG_OilSlickRemove (centity_t * cent)
References cg, CG_Printf(), particle_s::endtime, particle_s::next, P_FLAT_SCALEUP, P_FLAT_SCALEUP_FADE, particle_s::snum, particle_s::startfade, cg_t::time, and particle_s::type.
void CG_Particle_Bleed (qhandle_t pshader, vec3_t start, vec3_t dir, int fleshEntityNum, int duration)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, BLOODRED, cg, CG_Printf(), particle_s::color, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_SMOKE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, VectorClear, VectorCopy, particle_s::vel, and particle_s::width.
void CG_Particle_OilParticle (qhandle_t pshader, centity_t * cent)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), centity_s::currentState, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, entityState_s::origin, entityState_s::origin2, P_SMOKE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::snum, particle_s::startfade, particle_s::time, cg_t::time, entityState_s::time, particle_s::type, VectorClear, VectorCopy, particle_s::vel, and particle_s::width.
void CG_Particle_OilSlick (qhandle_t pshader, centity_t * cent)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, entityState_s::angles2, cg, CG_Printf(), crandom, centity_s::currentState, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, entityState_s::origin, P_FLAT_SCALEUP, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::snum, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, VectorClear, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleBloodCloud (centity_t * cent, vec3_t origin, vec3_t dir)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, AngleVectors(), BLOODRED, cg, cgs, particle_s::color, crandom, particle_s::endheight, particle_s::endtime, particle_s::endwidth, forward, free_particles, particle_s::height, LARGESIZE, length(), cgs_t::media, particle_s::next, NULL, particle_s::org, P_SMOKE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, cgMedia_t::smokePuffShader, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, vectoangles(), VectorClear, VectorCopy, VectorLength(), VectorMA(), particle_s::vel, and particle_s::width.
void CG_ParticleBubble (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::color, crandom, particle_s::end, free_particles, particle_s::height, particle_s::link, particle_s::next, particle_s::org, P_BUBBLE, P_BUBBLE_TURBULENT, particle_s::pshader, qtrue, range(), particle_s::snum, particle_s::start, particle_s::time, cg_t::time, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
Referenced by CG_NewParticleArea().
void CG_ParticleBulletDebris (vec3_t org, vec3_t vel, int duration)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, cgs, particle_s::color, EMISIVEFADE, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, cgs_t::media, particle_s::next, particle_s::org, P_SMOKE, particle_s::pshader, particle_s::startfade, particle_s::time, cg_t::time, cgMedia_t::tracerShader, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleDust (centity_t * cent, vec3_t origin, vec3_t dir)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, AngleVectors(), cg, cgs, crandom, particle_s::endheight, particle_s::endtime, particle_s::endwidth, forward, free_particles, particle_s::height, LARGESIZE, length(), cgs_t::media, particle_s::next, NORMALSIZE, NULL, particle_s::org, P_SMOKE, PARTICLE_GRAVITY, particle_s::pshader, qfalse, random, particle_s::roll, particle_s::rotate, cgMedia_t::smokePuffShader, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, vectoangles(), VectorClear, VectorCopy, VectorLength(), VectorMA(), VectorNegate, particle_s::vel, and particle_s::width.
void CG_ParticleExplosion (char * animStr, vec3_t origin, vec3_t vel, int duration, int sizeStart, int sizeEnd)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Error(), crandom, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_ANIM, Q_stricmp(), particle_s::roll, particle_s::shaderAnim, shaderAnimNames, shaderAnimSTRatio, particle_s::time, cg_t::time, particle_s::type, VectorClear, VectorCopy, particle_s::vel, and particle_s::width.
Referenced by CG_MissileHitWall().
void CG_ParticleImpactSmokePuff (qhandle_t pshader, vec3_t origin)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), crandom, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_SMOKE_IMPACT, particle_s::pshader, qtrue, particle_s::roll, particle_s::rotate, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, VectorCopy, VectorSet, particle_s::vel, and particle_s::width.
void CG_ParticleMisc (qhandle_t pshader, vec3_t origin, int size, int duration, float alpha)
References active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, particle_s::next, particle_s::org, P_SPRITE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::startfade, particle_s::time, cg_t::time, particle_s::type, VectorCopy, and particle_s::width.
void CG_ParticleSmoke (qhandle_t pshader, centity_t * cent)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::color, crandom, centity_s::currentState, particle_s::end, particle_s::endheight, particle_s::endtime, particle_s::endwidth, entityState_s::frame, free_particles, particle_s::height, particle_s::next, particle_s::org, entityState_s::origin, entityState_s::origin2, P_SMOKE, particle_s::pshader, qfalse, particle_s::roll, particle_s::rotate, particle_s::start, particle_s::startfade, particle_s::time, cg_t::time, entityState_s::time, entityState_s::time2, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleSnow (qhandle_t pshader, vec3_t origin, vec3_t origin2, int turb, float range, int snum)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, CG_Printf(), particle_s::color, crandom, particle_s::end, free_particles, particle_s::height, particle_s::link, particle_s::next, particle_s::org, P_WEATHER, P_WEATHER_TURBULENT, particle_s::pshader, qtrue, range(), particle_s::snum, particle_s::start, particle_s::time, cg_t::time, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
Referenced by CG_NewParticleArea().
void CG_ParticleSnowFlurry (qhandle_t pshader, centity_t * cent)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, entityState_s::angles, cg, CG_Printf(), particle_s::color, crandom, centity_s::currentState, particle_s::end, particle_s::endtime, free_particles, particle_s::height, particle_s::next, particle_s::org, entityState_s::origin, entityState_s::origin2, P_WEATHER_FLURRY, particle_s::pshader, qtrue, particle_s::start, particle_s::startfade, particle_s::time, cg_t::time, entityState_s::time, entityState_s::time2, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_ParticleSparks (vec3_t org, vec3_t vel, int duration, float x, float y, float speed)
References particle_s::accel, active_particles, particle_s::alpha, particle_s::alphavel, cg, cgs, particle_s::color, crandom, EMISIVEFADE, particle_s::endheight, particle_s::endtime, particle_s::endwidth, free_particles, particle_s::height, cgs_t::media, particle_s::next, particle_s::org, P_SMOKE, particle_s::pshader, particle_s::startfade, particle_s::time, cg_t::time, cgMedia_t::tracerShader, particle_s::type, VectorCopy, particle_s::vel, and particle_s::width.
void CG_SnowLink (centity_t * cent, qboolean particleOn)
References centity_s::currentState, entityState_s::frame, particle_s::link, particle_s::next, P_WEATHER, P_WEATHER_TURBULENT, qfalse, qtrue, particle_s::snum, and particle_s::type.
qboolean ValidBloodPool (vec3_t start)
References AngleVectors(), CG_Trace(), CONTENTS_SOLID, trace_t::entityNum, ENTITYNUM_WORLD, EXTRUDE_DIST, trace_t::fraction, NULL, qfalse, qtrue, right, trace_t::startsolid, up, vectoangles(), VectorMA(), and VectorSet.
Referenced by CG_BloodPool().
Variable Documentation
cparticle_t* active_particles
Referenced by CG_BloodPool(), CG_Particle_Bleed(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBloodCloud(), CG_ParticleBubble(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleExplosion(), CG_ParticleImpactSmokePuff(), CG_ParticleMisc(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), and CG_ParticleSparks().
int cl_numparticles = MAX_PARTICLES
Referenced by CG_ClearParticles().
cparticle_t * free_particles
Referenced by CG_AddParticles(), CG_BloodPool(), CG_Particle_Bleed(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBloodCloud(), CG_ParticleBubble(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleExplosion(), CG_ParticleImpactSmokePuff(), CG_ParticleMisc(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), and CG_ParticleSparks().
qboolean initparticles = qfalse
Referenced by CG_AddParticles(), and CG_ClearParticles().
int numShaderAnims [static]
Referenced by CG_ClearParticles().
float oldtime
Referenced by CG_AddParticles(), and CG_ClearParticles().
cparticle_t particles[MAX_PARTICLES]
vec3_t rforward
Referenced by CG_AddParticles(), and CG_AddParticleToScene().
float roll = 0.0 [static]
Referenced by CG_AddParticles(), and SP_misc_portal_camera().
vec3_t rright
Referenced by CG_AddParticles(), and CG_AddParticleToScene().
vec3_t rup
Referenced by CG_AddParticles(), and CG_AddParticleToScene().
int shaderAnimCounts[MAX_SHADER_ANIMS] [static]
Initial value:
 {
        23
}
Referenced by CG_AddParticleToScene(), and CG_ClearParticles().
char* shaderAnimNames[MAX_SHADER_ANIMS] [static]
Initial value:
 {
        "explode1",
        NULL
}
Referenced by CG_ClearParticles(), and CG_ParticleExplosion().
qhandle_t shaderAnims[MAX_SHADER_ANIMS][MAX_SHADER_ANIM_FRAMES] [static]
Referenced by CG_AddParticleToScene(), and CG_ClearParticles().
float shaderAnimSTRatio[MAX_SHADER_ANIMS] [static]
Initial value:
 {
        1.0f
}
Referenced by CG_ParticleExplosion().
vec3_t vforward
Referenced by CG_AddParticles().
vec3_t vright
Referenced by BaseWindingForPlane(), CG_AddParticles(), and CG_AddParticleToScene().
vec3_t vup
Referenced by BaseWindingForPlane(), CG_AddParticles(), CG_AddParticleToScene(), and RotatePointAroundVector().