ioquake3: code/client/cl_ui.c File Reference
cl_ui.c File Reference
#include "client.h"
#include "../botlib/botlib.h"
Defines
#define UI_OLD_API_VERSION 4
Functions
static void GetClientState (uiClientState_t *state)
void LAN_LoadCachedServers (void)
void LAN_SaveServersToCache (void)
static void LAN_ResetPings (int source)
static int LAN_AddServer (int source, const char *name, const char *address)
static void LAN_RemoveServer (int source, const char *addr)
static int LAN_GetServerCount (int source)
static void LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
static void LAN_GetServerInfo (int source, int n, char *buf, int buflen)
static int LAN_GetServerPing (int source, int n)
static serverInfo_t * LAN_GetServerPtr (int source, int n)
static int LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
static int LAN_GetPingQueueCount (void)
static void LAN_ClearPing (int n)
static void LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
static void LAN_GetPingInfo (int n, char *buf, int buflen)
static void LAN_MarkServerVisible (int source, int n, qboolean visible)
static int LAN_ServerIsVisible (int source, int n)
qboolean LAN_UpdateVisiblePings (int source)
int LAN_GetServerStatus (char *serverAddress, char *serverStatus, int maxLen)
static void CL_GetGlconfig (glconfig_t *config)
static void CL_GetClipboardData (char *buf, int buflen)
static void Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
static void Key_GetBindingBuf (int keynum, char *buf, int buflen)
static void CLUI_GetCDKey (char *buf, int buflen)
static void CLUI_SetCDKey (char *buf)
static int GetConfigString (int index, char *buf, int size)
static int FloatAsInt (float f)
intptr_t CL_UISystemCalls (intptr_t *args)
void CL_ShutdownUI (void)
void CL_InitUI (void)
qboolean UI_usesUniqueCDKey (void)
qboolean UI_GameCommand (void)
Variables
botlib_export_t * botlib_export
vm_t * uivm
Define Documentation
#define UI_OLD_API_VERSION 4
Referenced by CL_InitUI().
Function Documentation
static void CL_GetClipboardData (char * buf, int buflen) [static]
References Q_strncpyz(), Sys_GetClipboardData(), and Z_Free().
Referenced by CL_UISystemCalls().
static void CL_GetGlconfig (glconfig_t * config) [static]
References cls, and clientStatic_t::glconfig.
void CL_InitUI (void)
References CA_ACTIVE, CA_AUTHORIZING, cl_connectedToPureServer, CL_UISystemCalls(), clc, cls, Com_Error(), Cvar_VariableValue(), ERR_DROP, ERR_FATAL, NULL, qfalse, clientConnection_t::state, UI_API_VERSION, UI_GETAPIVERSION, UI_INIT, UI_OLD_API_VERSION, clientStatic_t::uiStarted, VM_Call(), VM_Create(), VM_Free(), VMI_BYTECODE, and VMI_COMPILED.
Referenced by CL_StartHunkUsers().
void CL_ShutdownUI (void)
References cls, Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_UI, NULL, qfalse, UI_SHUTDOWN, clientStatic_t::uiStarted, VM_Call(), and VM_Free().
Referenced by CL_ShutdownAll(), CL_Vid_Restart_f(), and Hunk_Clear().
intptr_t CL_UISystemCalls (intptr_t * args)
References refexport_t::AddLightToScene, refexport_t::AddPolyToScene, refexport_t::AddRefEntityToScene, Cbuf_ExecuteText(), CIN_DrawCinematic(), CIN_PlayCinematic(), CIN_RunCinematic(), CIN_SetExtents(), CIN_StopCinematic(), CL_CDKeyValidate(), CL_GetClipboardData(), CL_GetGlconfig(), refexport_t::ClearScene, CLUI_GetCDKey(), CLUI_SetCDKey(), Cmd_Argc(), Cmd_ArgvBuffer(), Com_DPrintf(), Com_Error(), Com_Memcpy, Com_Memset, Com_Printf(), Com_RealTime(), Cvar_Get(), Cvar_InfoStringBuffer(), Cvar_Register(), Cvar_Reset(), Cvar_SetSafe(), Cvar_SetValueSafe(), Cvar_Update(), Cvar_VariableStringBuffer(), Cvar_VariableValue(), refexport_t::DrawStretchPic, ERR_DROP, EXEC_INSERT, EXEC_NOW, FloatAsInt(), FS_FCloseFile(), FS_FOpenFileByMode(), FS_GetFileList(), FS_Read2(), FS_Seek(), FS_Write(), GetClientState(), GetConfigString(), Hunk_MemoryRemaining(), Key_ClearStates(), Key_GetBindingBuf(), Key_GetCatcher(), Key_GetOverstrikeMode(), Key_IsDown(), Key_KeynumToStringBuf(), Key_SetBinding(), Key_SetCatcher(), Key_SetOverstrikeMode(), KEYCATCH_CONSOLE, LAN_AddServer(), LAN_ClearPing(), LAN_CompareServers(), LAN_GetPing(), LAN_GetPingInfo(), LAN_GetPingQueueCount(), LAN_GetServerAddressString(), LAN_GetServerCount(), LAN_GetServerInfo(), LAN_GetServerPing(), LAN_GetServerStatus(), LAN_LoadCachedServers(), LAN_MarkServerVisible(), LAN_RemoveServer(), LAN_ResetPings(), LAN_SaveServersToCache(), LAN_ServerIsVisible(), LAN_UpdateVisiblePings(), refexport_t::LerpTag, refexport_t::ModelBounds, botlib_export_s::PC_AddGlobalDefine, botlib_export_s::PC_FreeSourceHandle, botlib_export_s::PC_LoadSourceHandle, botlib_export_s::PC_ReadTokenHandle, botlib_export_s::PC_SourceFileAndLine, re, refexport_t::RegisterFont, refexport_t::RegisterModel, refexport_t::RegisterShaderNoMip, refexport_t::RegisterSkin, refexport_t::RemapShader, refexport_t::RenderScene, S_COLOR_YELLOW, S_RegisterSound(), S_StartBackgroundTrack(), S_StartLocalSound(), S_StopBackgroundTrack(), SCR_UpdateScreen(), refexport_t::SetColor, Sys_Milliseconds(), UI_ARGC, UI_ARGV, UI_ATAN2, UI_CEIL, UI_CIN_DRAWCINEMATIC, UI_CIN_PLAYCINEMATIC, UI_CIN_RUNCINEMATIC, UI_CIN_SETEXTENTS, UI_CIN_STOPCINEMATIC, UI_CM_LERPTAG, UI_CMD_EXECUTETEXT, UI_COS, UI_CVAR_CREATE, UI_CVAR_INFOSTRINGBUFFER, UI_CVAR_REGISTER, UI_CVAR_RESET, UI_CVAR_SET, UI_CVAR_SETVALUE, UI_CVAR_UPDATE, UI_CVAR_VARIABLESTRINGBUFFER, UI_CVAR_VARIABLEVALUE, UI_ERROR, UI_FLOOR, UI_FS_FCLOSEFILE, UI_FS_FOPENFILE, UI_FS_GETFILELIST, UI_FS_READ, UI_FS_SEEK, UI_FS_WRITE, UI_GET_CDKEY, UI_GETCLIENTSTATE, UI_GETCLIPBOARDDATA, UI_GETCONFIGSTRING, UI_GETGLCONFIG, UI_KEY_CLEARSTATES, UI_KEY_GETBINDINGBUF, UI_KEY_GETCATCHER, UI_KEY_GETOVERSTRIKEMODE, UI_KEY_ISDOWN, UI_KEY_KEYNUMTOSTRINGBUF, UI_KEY_SETBINDING, UI_KEY_SETCATCHER, UI_KEY_SETOVERSTRIKEMODE, UI_LAN_ADDSERVER, UI_LAN_CLEARPING, UI_LAN_COMPARESERVERS, UI_LAN_GETPING, UI_LAN_GETPINGINFO, UI_LAN_GETPINGQUEUECOUNT, UI_LAN_GETSERVERADDRESSSTRING, UI_LAN_GETSERVERCOUNT, UI_LAN_GETSERVERINFO, UI_LAN_GETSERVERPING, UI_LAN_LOADCACHEDSERVERS, UI_LAN_MARKSERVERVISIBLE, UI_LAN_REMOVESERVER, UI_LAN_RESETPINGS, UI_LAN_SAVECACHEDSERVERS, UI_LAN_SERVERISVISIBLE, UI_LAN_SERVERSTATUS, UI_LAN_UPDATEVISIBLEPINGS, UI_MEMCPY, UI_MEMORY_REMAINING, UI_MEMSET, UI_MILLISECONDS, UI_PC_ADD_GLOBAL_DEFINE, UI_PC_FREE_SOURCE, UI_PC_LOAD_SOURCE, UI_PC_READ_TOKEN, UI_PC_SOURCE_FILE_AND_LINE, UI_PRINT, UI_R_ADDLIGHTTOSCENE, UI_R_ADDPOLYTOSCENE, UI_R_ADDREFENTITYTOSCENE, UI_R_CLEARSCENE, UI_R_DRAWSTRETCHPIC, UI_R_MODELBOUNDS, UI_R_REGISTERFONT, UI_R_REGISTERMODEL, UI_R_REGISTERSHADERNOMIP, UI_R_REGISTERSKIN, UI_R_REMAP_SHADER, UI_R_RENDERSCENE, UI_R_SETCOLOR, UI_REAL_TIME, UI_S_REGISTERSOUND, UI_S_STARTBACKGROUNDTRACK, UI_S_STARTLOCALSOUND, UI_S_STOPBACKGROUNDTRACK, UI_SET_CDKEY, UI_SET_PBCLSTATUS, UI_SIN, UI_SQRT, UI_STRNCPY, UI_UPDATESCREEN, UI_VERIFY_CDKEY, VMA, and VMF.
Referenced by CL_InitUI().
static void CLUI_GetCDKey (char * buf, int buflen) [static]
References cl_cdkey, Com_Memcpy, Cvar_Get(), CVAR_INIT, CVAR_SYSTEMINFO, cvar_s::string, and UI_usesUniqueCDKey().
Referenced by CL_UISystemCalls().
static void CLUI_SetCDKey (char * buf) [static]
References cl_cdkey, Com_Memcpy, CVAR_ARCHIVE, Cvar_Get(), CVAR_INIT, cvar_modifiedFlags, CVAR_SYSTEMINFO, cvar_s::string, and UI_usesUniqueCDKey().
Referenced by CL_UISystemCalls().
static int FloatAsInt (float f) [static]
References floatint_t::f, and floatint_t::i.
Referenced by CL_UISystemCalls().
static void GetClientState (uiClientState_t * state) [static]
References cl, clc, uiClientState_t::clientNum, playerState_s::clientNum, cls, uiClientState_t::connectPacketCount, clientConnection_t::connectPacketCount, uiClientState_t::connState, uiClientState_t::messageString, clSnapshot_t::ps, Q_strncpyz(), clientConnection_t::serverMessage, uiClientState_t::servername, clientConnection_t::servername, clientActive_t::snap, clientConnection_t::state, uiClientState_t::updateInfoString, and clientStatic_t::updateInfoString.
Referenced by CL_UISystemCalls().
static int GetConfigString (int index, char * buf, int size) [static]
References cl, clientActive_t::gameState, MAX_CONFIGSTRINGS, Q_strncpyz(), qfalse, qtrue, gameState_t::stringData, and gameState_t::stringOffsets.
Referenced by CL_UISystemCalls().
static void Key_GetBindingBuf (int keynum, char * buf, int buflen) [static]
References Key_GetBinding(), Q_strncpyz(), and value().
Referenced by CL_UISystemCalls().
static void Key_KeynumToStringBuf (int keynum, char * buf, int buflen) [static]
References Key_KeynumToString(), and Q_strncpyz().
Referenced by CL_UISystemCalls().
static int LAN_AddServer (int source, const char * name, const char * address) [static]
References serverInfo_t::adr, AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, count, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, NA_IP, NET_CompareAdr(), NET_StringToAdr(), NULL, clientStatic_t::numfavoriteservers, clientStatic_t::numglobalservers, clientStatic_t::numlocalservers, Q_strncpyz(), qtrue, and serverInfo_t::visible.
Referenced by CL_UISystemCalls().
static void LAN_ClearPing (int n) [static]
References CL_ClearPing().
Referenced by CL_UISystemCalls().
static int LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2) [static]
References serverInfo_t::clients, serverInfo_t::gameType, serverInfo_t::hostName, LAN_GetServerPtr(), serverInfo_t::mapName, serverInfo_t::ping, Q_stricmp(), SORT_CLIENTS, SORT_GAME, SORT_HOST, SORT_MAP, and SORT_PING.
Referenced by CL_UISystemCalls().
static void LAN_GetPing (int n, char * buf, int buflen, int * pingtime) [static]
References CL_GetPing().
Referenced by CL_UISystemCalls().
static void LAN_GetPingInfo (int n, char * buf, int buflen) [static]
References CL_GetPingInfo().
Referenced by CL_UISystemCalls().
static int LAN_GetPingQueueCount (void) [static]
References CL_GetPingQueueCount().
Referenced by CL_UISystemCalls().
static void LAN_GetServerAddressString (int source, int n, char * buf, int buflen) [static]
References serverInfo_t::adr, AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, NET_AdrToStringwPort(), and Q_strncpyz().
Referenced by CL_UISystemCalls().
static int LAN_GetServerCount (int source) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, clientStatic_t::numfavoriteservers, clientStatic_t::numglobalservers, and clientStatic_t::numlocalservers.
Referenced by CL_UISystemCalls().
static void LAN_GetServerInfo (int source, int n, char * buf, int buflen) [static]
References serverInfo_t::adr, AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, serverInfo_t::clients, cls, clientStatic_t::favoriteServers, serverInfo_t::g_humanplayers, serverInfo_t::g_needpass, serverInfo_t::game, serverInfo_t::gameType, clientStatic_t::globalServers, serverInfo_t::hostName, info, Info_SetValueForKey(), clientStatic_t::localServers, serverInfo_t::mapName, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, MAX_STRING_CHARS, serverInfo_t::maxClients, serverInfo_t::maxPing, serverInfo_t::minPing, n, NET_AdrToStringwPort(), serverInfo_t::netType, NULL, serverInfo_t::ping, serverInfo_t::punkbuster, Q_strncpyz(), and va().
Referenced by CL_UISystemCalls().
static int LAN_GetServerPing (int source, int n) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, n, NULL, and serverInfo_t::ping.
Referenced by CL_UISystemCalls().
static serverInfo_t* LAN_GetServerPtr (int source, int n) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, n, and NULL.
Referenced by LAN_CompareServers().
int LAN_GetServerStatus (char * serverAddress, char * serverStatus, int maxLen)
References CL_ServerStatus().
Referenced by CL_UISystemCalls().
void LAN_LoadCachedServers (void)
References cls, clientStatic_t::favoriteServers, FS_FCloseFile(), FS_Read(), FS_SV_FOpenFileRead(), clientStatic_t::globalServers, clientStatic_t::numfavoriteservers, clientStatic_t::numGlobalServerAddresses, and clientStatic_t::numglobalservers.
Referenced by CL_UISystemCalls().
static void LAN_MarkServerVisible (int source, int n, qboolean visible) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, count, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, n, NULL, and serverInfo_t::visible.
Referenced by CL_UISystemCalls().
static void LAN_RemoveServer (int source, const char * addr) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, Com_Memcpy, count, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, NA_IP, NET_CompareAdr(), NET_StringToAdr(), NULL, clientStatic_t::numfavoriteservers, clientStatic_t::numglobalservers, and clientStatic_t::numlocalservers.
Referenced by CL_UISystemCalls().
static void LAN_ResetPings (int source) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, count, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, NULL, and serverInfo_t::ping.
Referenced by CL_UISystemCalls().
void LAN_SaveServersToCache (void)
References cls, clientStatic_t::favoriteServers, FS_FCloseFile(), FS_SV_FOpenFileWrite(), FS_Write(), clientStatic_t::globalServers, clientStatic_t::numfavoriteservers, and clientStatic_t::numglobalservers.
Referenced by CL_UISystemCalls().
static int LAN_ServerIsVisible (int source, int n) [static]
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, AS_MPLAYER, cls, clientStatic_t::favoriteServers, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, n, qfalse, and serverInfo_t::visible.
Referenced by CL_UISystemCalls().
qboolean LAN_UpdateVisiblePings (int source)
References CL_UpdateVisiblePings_f().
Referenced by CL_UISystemCalls().
qboolean UI_GameCommand (void)
Referenced by Cmd_ExecuteString().
qboolean UI_usesUniqueCDKey (void)
References qfalse, qtrue, UI_HASUNIQUECDKEY, and VM_Call().
Referenced by CLUI_GetCDKey(), CLUI_SetCDKey(), and Com_WriteConfiguration().
Variable Documentation
botlib_export_t* botlib_export
vm_t* uivm
Referenced by CIN_PlayCinematic(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), SCR_DrawScreenField(), and SCR_UpdateScreen().