ioquake3: code/client/cl_avi.c File Reference
cl_avi.c File Reference
#include "client.h"
#include "snd_local.h"
Data Structures
struct audioFormat_s
struct aviFileData_s
Defines
#define INDEX_FILE_EXTENSION ".index.dat"
#define MAX_RIFF_CHUNKS 16
#define MAX_AVI_BUFFER 2048
#define MAX_PACK_LEN 16
#define PCM_BUFFER_SIZE 44100
Typedefs
typedef struct audioFormat_s audioFormat_t
typedef struct aviFileData_s aviFileData_t
Functions
static ID_INLINE void SafeFS_Write (const void *buffer, int len, fileHandle_t f)
static ID_INLINE void WRITE_STRING (const char *s)
static ID_INLINE void WRITE_4BYTES (int x)
static ID_INLINE void WRITE_2BYTES (int x)
static ID_INLINE void WRITE_1BYTES (int x)
static ID_INLINE void START_CHUNK (const char *s)
static ID_INLINE void END_CHUNK (void)
void CL_WriteAVIHeader (void)
qboolean CL_OpenAVIForWriting (const char *fileName)
static qboolean CL_CheckFileSize (int bytesToAdd)
void CL_WriteAVIVideoFrame (const byte *imageBuffer, int size)
void CL_WriteAVIAudioFrame (const byte *pcmBuffer, int size)
void CL_TakeVideoFrame (void)
qboolean CL_CloseAVI (void)
qboolean CL_VideoRecording (void)
Variables
static aviFileData_t afd
static byte buffer [MAX_AVI_BUFFER]
static int bufIndex
Define Documentation
#define INDEX_FILE_EXTENSION ".index.dat"
Referenced by CL_CloseAVI(), and CL_OpenAVIForWriting().
#define MAX_AVI_BUFFER 2048
Referenced by CL_CloseAVI().
#define MAX_PACK_LEN 16
Referenced by CL_OpenAVIForWriting().
#define MAX_RIFF_CHUNKS 16
Referenced by START_CHUNK().
#define PCM_BUFFER_SIZE 44100
Referenced by CL_WriteAVIAudioFrame().
Typedef Documentation
typedef struct audioFormat_s audioFormat_t
typedef struct aviFileData_s aviFileData_t
Function Documentation
static qboolean CL_CheckFileSize (int bytesToAdd) [static]
References CL_CloseAVI(), CL_OpenAVIForWriting(), aviFileData_s::fileName, aviFileData_s::fileSize, INT_MAX, aviFileData_s::numIndices, qfalse, qtrue, and va().
Referenced by CL_WriteAVIAudioFrame(), and CL_WriteAVIVideoFrame().
qboolean CL_CloseAVI (void)
References buffer, bufIndex, aviFileData_s::cBuffer, CL_WriteAVIHeader(), Com_Printf(), aviFileData_s::eBuffer, aviFileData_s::f, aviFileData_s::fileName, aviFileData_s::fileOpen, aviFileData_s::fileSize, FS_FCloseFile(), FS_FOpenFileRead(), FS_HomeRemove(), FS_Read(), FS_Seek(), FS_SEEK_SET, aviFileData_s::idxF, INDEX_FILE_EXTENSION, MAX_AVI_BUFFER, aviFileData_s::moviOffset, aviFileData_s::moviSize, aviFileData_s::numAudioFrames, aviFileData_s::numIndices, aviFileData_s::numVideoFrames, qfalse, qtrue, SafeFS_Write(), va(), WRITE_4BYTES(), and Z_Free().
Referenced by CL_CheckFileSize(), CL_Disconnect(), CL_ShutdownAll(), CL_StopVideo_f(), and CL_Vid_Restart_f().
qboolean CL_OpenAVIForWriting (const char * fileName)
References aviFileData_s::a, aviFileData_s::audio, AVI_LINE_PADDING, audioFormat_s::bits, buffer, bufIndex, aviFileData_s::cBuffer, audioFormat_s::channels, dma_t::channels, cl_aviFrameRate, cl_aviMotionJpeg, CL_WriteAVIHeader(), cls, Com_Memset, Com_Printf(), Cvar_VariableIntegerValue(), Cvar_VariableString(), dma, aviFileData_s::eBuffer, aviFileData_s::f, aviFileData_s::fileName, aviFileData_s::fileOpen, aviFileData_s::fileSize, audioFormat_s::format, aviFileData_s::framePeriod, aviFileData_s::frameRate, FS_FCloseFile(), FS_FOpenFileWrite(), clientStatic_t::glconfig, aviFileData_s::height, aviFileData_s::idxF, INDEX_FILE_EXTENSION, int(), cvar_s::integer, MAX_PACK_LEN, MAX_QPATH, aviFileData_s::motionJpeg, aviFileData_s::moviSize, PAD, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, audioFormat_s::rate, S_COLOR_RED, S_COLOR_YELLOW, SafeFS_Write(), dma_t::samplebits, audioFormat_s::sampleSize, dma_t::speed, START_CHUNK(), va(), glconfig_t::vidHeight, glconfig_t::vidWidth, WAV_FORMAT_PCM, aviFileData_s::width, and Z_Malloc.
Referenced by CL_CheckFileSize(), and CL_Video_f().
void CL_TakeVideoFrame (void)
References aviFileData_s::cBuffer, aviFileData_s::eBuffer, aviFileData_s::fileOpen, aviFileData_s::height, aviFileData_s::motionJpeg, re, refexport_t::TakeVideoFrame, and aviFileData_s::width.
Referenced by CL_Frame().
qboolean CL_VideoRecording (void)
References aviFileData_s::fileOpen.
Referenced by CL_Disconnect(), CL_Frame(), CL_ShutdownAll(), CL_Vid_Restart_f(), S_GetSoundtime(), and S_TransferStereo16().
void CL_WriteAVIAudioFrame (const byte * pcmBuffer, int size)
References aviFileData_s::a, aviFileData_s::audio, buffer, bufIndex, CL_CheckFileSize(), Com_Memcpy, Com_Printf(), aviFileData_s::f, aviFileData_s::fileOpen, aviFileData_s::fileSize, aviFileData_s::frameRate, aviFileData_s::idxF, aviFileData_s::moviOffset, aviFileData_s::moviSize, aviFileData_s::numAudioFrames, aviFileData_s::numIndices, PADLEN, PCM_BUFFER_SIZE, audioFormat_s::rate, S_COLOR_YELLOW, SafeFS_Write(), audioFormat_s::sampleSize, audioFormat_s::totalBytes, WRITE_4BYTES(), and WRITE_STRING().
Referenced by S_TransferStereo16().
void CL_WriteAVIHeader (void)
References aviFileData_s::a, aviFileData_s::audio, audioFormat_s::bits, bufIndex, audioFormat_s::channels, aviFileData_s::chunkStackTop, END_CHUNK(), audioFormat_s::format, aviFileData_s::framePeriod, aviFileData_s::frameRate, aviFileData_s::height, aviFileData_s::maxRecordSize, aviFileData_s::motionJpeg, aviFileData_s::moviOffset, aviFileData_s::numVideoFrames, audioFormat_s::rate, audioFormat_s::sampleSize, START_CHUNK(), audioFormat_s::totalBytes, aviFileData_s::width, WRITE_2BYTES(), WRITE_4BYTES(), and WRITE_STRING().
Referenced by CL_CloseAVI(), and CL_OpenAVIForWriting().
void CL_WriteAVIVideoFrame (const byte * imageBuffer, int size)
References buffer, bufIndex, CL_CheckFileSize(), aviFileData_s::f, aviFileData_s::fileOpen, aviFileData_s::fileSize, aviFileData_s::idxF, aviFileData_s::maxRecordSize, aviFileData_s::moviOffset, aviFileData_s::moviSize, aviFileData_s::numIndices, aviFileData_s::numVideoFrames, PADLEN, SafeFS_Write(), WRITE_4BYTES(), and WRITE_STRING().
Referenced by CL_InitRef().
static ID_INLINE void END_CHUNK (void) [static]
References bufIndex, aviFileData_s::chunkStack, aviFileData_s::chunkStackTop, Com_Error(), ERR_DROP, PAD, and WRITE_4BYTES().
Referenced by CL_WriteAVIHeader().
static ID_INLINE void SafeFS_Write (const void * buffer, int len, fileHandle_t f) [static]
References Com_Error(), ERR_DROP, and FS_Write().
Referenced by CL_CloseAVI(), CL_OpenAVIForWriting(), CL_WriteAVIAudioFrame(), and CL_WriteAVIVideoFrame().
static ID_INLINE void START_CHUNK (const char * s) [static]
References bufIndex, aviFileData_s::chunkStack, aviFileData_s::chunkStackTop, Com_Error(), ERR_DROP, MAX_RIFF_CHUNKS, WRITE_4BYTES(), and WRITE_STRING().
Referenced by CL_OpenAVIForWriting(), and CL_WriteAVIHeader().
static ID_INLINE void WRITE_1BYTES (int x) [static]
References buffer, and bufIndex.
static ID_INLINE void WRITE_2BYTES (int x) [static]
References buffer, and bufIndex.
Referenced by CL_WriteAVIHeader().
static ID_INLINE void WRITE_4BYTES (int x) [static]
References buffer, and bufIndex.
Referenced by CL_CloseAVI(), CL_WriteAVIAudioFrame(), CL_WriteAVIHeader(), CL_WriteAVIVideoFrame(), END_CHUNK(), and START_CHUNK().
static ID_INLINE void WRITE_STRING (const char * s) [static]
References buffer, bufIndex, and Com_Memcpy.
Referenced by CL_WriteAVIAudioFrame(), CL_WriteAVIHeader(), CL_WriteAVIVideoFrame(), and START_CHUNK().
Variable Documentation
aviFileData_t afd [static]
byte buffer[MAX_AVI_BUFFER] [static]
Referenced by CG_Argv(), CL_CloseAVI(), CL_DemoCompleted(), CL_LoadConsoleHistory(), CL_OpenAVIForWriting(), CL_SaveConsoleHistory(), CL_WriteAVIAudioFrame(), CL_WriteAVIVideoFrame(), Cmd_SetViewpos_f(), Com_BeginRedirect(), Com_MD5File(), compress_first_pass(), compress_output(), Con_Dump_f(), consume_data(), Cvar_WriteVariables(), decompress_data(), decompress_smooth_data(), FS_Seek(), Huff_Compress(), Huff_Decompress(), jinit_c_coef_controller(), jinit_d_coef_controller(), LoadFile(), LoadFileBlock(), LoadScriptFile(), LoadScriptMemory(), Message_Key(), output_message(), ParseStage(), QCopyFile(), R_JPGErrorExit(), R_JPGOutputMessage(), R_LevelShot(), R_LoadBMP(), R_LoadJPG(), R_LoadTGA(), RB_ReadPixels(), RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), RE_LoadWorldMap(), ReadBufferedFile(), S_FreeOldestSound(), S_WAV_CodecLoad(), SP_target_speaker(), SV_RankDecodePlayerID(), SV_RankDecodePlayerKey(), Sys_AnsiColorPrint(), Sys_ErrorDialog(), transencode_coef_controller(), TryLoadFile(), UI_Argv(), UI_Cvar_VariableString(), WRITE_1BYTES(), WRITE_2BYTES(), WRITE_4BYTES(), and WRITE_STRING().
int bufIndex [static]
Referenced by CL_CloseAVI(), CL_OpenAVIForWriting(), CL_WriteAVIAudioFrame(), CL_WriteAVIHeader(), CL_WriteAVIVideoFrame(), END_CHUNK(), START_CHUNK(), WRITE_1BYTES(), WRITE_2BYTES(), WRITE_4BYTES(), and WRITE_STRING().