ioquake3: code/client/cl_console.c File Reference
cl_console.c File Reference
#include "client.h"
Data Structures
struct console_t
Defines
#define NUM_CON_TIMES 4
#define CON_TEXTSIZE 32768
#define DEFAULT_CONSOLE_WIDTH 78
Functions
void Con_ToggleConsole_f (void)
void Con_MessageMode_f (void)
void Con_MessageMode2_f (void)
void Con_MessageMode3_f (void)
void Con_MessageMode4_f (void)
void Con_Clear_f (void)
void Con_Dump_f (void)
void Con_ClearNotify (void)
void Con_CheckResize (void)
void Cmd_CompleteTxtName (char *args, int argNum)
void Con_Init (void)
void Con_Shutdown (void)
void Con_Linefeed (qboolean skipnotify)
void CL_ConsolePrint (char *txt)
void Con_DrawInput (void)
void Con_DrawNotify (void)
void Con_DrawSolidConsole (float frac)
void Con_DrawConsole (void)
void Con_RunConsole (void)
void Con_PageUp (void)
void Con_PageDown (void)
void Con_Top (void)
void Con_Bottom (void)
void Con_Close (void)
Variables
int g_console_field_width = 78
console_t con
cvar_t * con_conspeed
cvar_t * con_notifytime
Define Documentation
#define CON_TEXTSIZE 32768
Referenced by Con_CheckResize(), and Con_Clear_f().
#define DEFAULT_CONSOLE_WIDTH 78
Referenced by Con_CheckResize().
#define NUM_CON_TIMES 4
Referenced by CL_ConsolePrint(), Con_ClearNotify(), Con_DrawNotify(), and Con_Linefeed().
Function Documentation
void CL_ConsolePrint (char * txt)
Referenced by Com_Printf().
void Cmd_CompleteTxtName (char * args, int argNum)
References Field_CompleteFilename(), qfalse, and qtrue.
Referenced by Con_Init().
void Con_Bottom (void)
References console_t::current, and console_t::display.
Referenced by Con_Clear_f(), and Console_Key().
void Con_CheckResize (void)
References COLOR_WHITE, ColorIndex, Com_Memcpy, Con_ClearNotify(), CON_TEXTSIZE, console_t::current, DEFAULT_CONSOLE_WIDTH, console_t::display, console_t::linewidth, SCREEN_WIDTH, SMALLCHAR_WIDTH, console_t::text, console_t::totallines, and width.
Referenced by CL_ConsolePrint(), and Con_DrawConsole().
void Con_Clear_f (void)
References COLOR_WHITE, ColorIndex, Con_Bottom(), CON_TEXTSIZE, and console_t::text.
Referenced by Con_Init().
void Con_ClearNotify (void)
References NUM_CON_TIMES, and console_t::times.
Referenced by CL_GetServerCommand(), CL_InitCGame(), Con_CheckResize(), Con_Close(), and Con_ToggleConsole_f().
void Con_Close (void)
References com_cl_running, Con_ClearNotify(), console_t::displayFrac, Field_Clear(), console_t::finalFrac, g_consoleField, cvar_s::integer, Key_GetCatcher(), Key_SetCatcher(), and KEYCATCH_CONSOLE.
Referenced by CIN_PlayCinematic(), CL_Connect_f(), CL_GetServerCommand(), CL_InitCGame(), CL_MapLoading(), CL_ParseGamestate(), and CL_PlayDemo_f().
void Con_DrawConsole (void)
References CA_ACTIVE, CA_DISCONNECTED, clc, Con_CheckResize(), Con_DrawNotify(), Con_DrawSolidConsole(), console_t::displayFrac, Key_GetCatcher(), KEYCATCH_CGAME, KEYCATCH_UI, and clientConnection_t::state.
Referenced by SCR_DrawScreenField().
void Con_DrawInput (void)
References CA_DISCONNECTED, clc, console_t::color, Field_Draw(), g_consoleField, Key_GetCatcher(), KEYCATCH_CONSOLE, qtrue, re, SCR_DrawSmallChar(), SCREEN_WIDTH, refexport_t::SetColor, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, clientConnection_t::state, console_t::vislines, and console_t::xadjust.
Referenced by Con_DrawSolidConsole().
void Con_DrawNotify (void)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, chat_team, chatField, cl, cl_conXOffset, cls, console_t::current, Field_BigDraw(), g_color_table, if(), cvar_s::integer, Key_GetCatcher(), KEYCATCH_CGAME, KEYCATCH_MESSAGE, KEYCATCH_UI, console_t::linewidth, NULL, NUM_CON_TIMES, PM_INTERMISSION, playerState_s::pm_type, clSnapshot_t::ps, qfalse, qtrue, re, clientStatic_t::realtime, SCR_DrawBigString(), SCR_DrawSmallChar(), SCREEN_WIDTH, refexport_t::SetColor, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, clientActive_t::snap, console_t::text, console_t::times, console_t::totallines, cvar_s::value, and console_t::xadjust.
Referenced by Con_DrawConsole().
void Con_DrawSolidConsole (float frac)
References cls, COLOR_RED, ColorIndex, Con_DrawInput(), clientStatic_t::consoleShader, console_t::current, console_t::display, g_color_table, clientStatic_t::glconfig, console_t::linewidth, NULL, Q3_VERSION, re, SCR_AdjustFrom640(), SCR_DrawPic(), SCR_DrawSmallChar(), SCR_FillRect(), SCREEN_HEIGHT, SCREEN_WIDTH, refexport_t::SetColor, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, console_t::text, console_t::totallines, glconfig_t::vidHeight, glconfig_t::vidWidth, console_t::vislines, console_t::x, and console_t::xadjust.
Referenced by Con_DrawConsole().
void Con_Dump_f (void)
References buffer, Cmd_Argc(), Cmd_Argv(), Com_Printf(), console_t::current, FS_FCloseFile(), FS_FOpenFileWrite(), FS_Write(), line, console_t::linewidth, console_t::text, and console_t::totallines.
Referenced by Con_Init().
void Con_Init (void)
References CL_LoadConsoleHistory(), Cmd_AddCommand(), Cmd_CompleteTxtName(), Cmd_SetCommandCompletionFunc(), COMMAND_HISTORY, Con_Clear_f(), Con_Dump_f(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), Con_ToggleConsole_f(), Cvar_Get(), Field_Clear(), g_console_field_width, g_consoleField, historyEditLines, and field_t::widthInChars.
Referenced by CL_Init().
void Con_Linefeed (qboolean skipnotify)
References cls, COLOR_WHITE, ColorIndex, console_t::current, console_t::display, console_t::linewidth, NUM_CON_TIMES, clientStatic_t::realtime, console_t::text, console_t::times, console_t::totallines, and console_t::x.
Referenced by CL_ConsolePrint().
void Con_MessageMode2_f (void)
References chat_playerNum, chat_team, chatField, Field_Clear(), Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_MESSAGE, qtrue, and field_t::widthInChars.
Referenced by Con_Init().
void Con_MessageMode3_f (void)
References CG_CROSSHAIR_PLAYER, cgvm, chat_playerNum, chat_team, chatField, Field_Clear(), Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_MESSAGE, MAX_CLIENTS, qfalse, VM_Call(), and field_t::widthInChars.
Referenced by Con_Init().
void Con_MessageMode4_f (void)
References CG_LAST_ATTACKER, cgvm, chat_playerNum, chat_team, chatField, Field_Clear(), Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_MESSAGE, MAX_CLIENTS, qfalse, VM_Call(), and field_t::widthInChars.
Referenced by Con_Init().
void Con_MessageMode_f (void)
References chat_playerNum, chat_team, chatField, Field_Clear(), Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_MESSAGE, qfalse, and field_t::widthInChars.
Referenced by Con_Init().
void Con_PageDown (void)
References console_t::current, and console_t::display.
Referenced by Console_Key().
void Con_PageUp (void)
References console_t::current, console_t::display, and console_t::totallines.
Referenced by Console_Key().
void Con_RunConsole (void)
References cls, console_t::displayFrac, console_t::finalFrac, Key_GetCatcher(), KEYCATCH_CONSOLE, clientStatic_t::realFrametime, and cvar_s::value.
Referenced by CL_Frame().
void Con_Shutdown (void)
References Cmd_RemoveCommand().
Referenced by CL_Shutdown().
void Con_ToggleConsole_f (void)
References CA_DISCONNECTED, clc, Con_ClearNotify(), Field_Clear(), g_console_field_width, g_consoleField, Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_CONSOLE, clientConnection_t::state, and field_t::widthInChars.
Referenced by CL_KeyDownEvent(), and Con_Init().
void Con_Top (void)
References console_t::current, console_t::display, and console_t::totallines.
Referenced by Console_Key().
Variable Documentation
console_t con
Referenced by CM_FloodArea_r().
cvar_t* con_conspeed
cvar_t* con_notifytime
int g_console_field_width = 78
Referenced by CL_InitRenderer(), Con_Init(), Con_ToggleConsole_f(), and Console_Key().