ioquake3: code/client/cl_input.c File Reference
cl_input.c File Reference
#include "client.h"
Functions
void IN_MLookDown (void)
void IN_MLookUp (void)
void IN_KeyDown (kbutton_t *b)
void IN_KeyUp (kbutton_t *b)
float CL_KeyState (kbutton_t *key)
void IN_UpDown (void)
void IN_UpUp (void)
void IN_DownDown (void)
void IN_DownUp (void)
void IN_LeftDown (void)
void IN_LeftUp (void)
void IN_RightDown (void)
void IN_RightUp (void)
void IN_ForwardDown (void)
void IN_ForwardUp (void)
void IN_BackDown (void)
void IN_BackUp (void)
void IN_LookupDown (void)
void IN_LookupUp (void)
void IN_LookdownDown (void)
void IN_LookdownUp (void)
void IN_MoveleftDown (void)
void IN_MoveleftUp (void)
void IN_MoverightDown (void)
void IN_MoverightUp (void)
void IN_SpeedDown (void)
void IN_SpeedUp (void)
void IN_StrafeDown (void)
void IN_StrafeUp (void)
void IN_Button0Down (void)
void IN_Button0Up (void)
void IN_Button1Down (void)
void IN_Button1Up (void)
void IN_Button2Down (void)
void IN_Button2Up (void)
void IN_Button3Down (void)
void IN_Button3Up (void)
void IN_Button4Down (void)
void IN_Button4Up (void)
void IN_Button5Down (void)
void IN_Button5Up (void)
void IN_Button6Down (void)
void IN_Button6Up (void)
void IN_Button7Down (void)
void IN_Button7Up (void)
void IN_Button8Down (void)
void IN_Button8Up (void)
void IN_Button9Down (void)
void IN_Button9Up (void)
void IN_Button10Down (void)
void IN_Button10Up (void)
void IN_Button11Down (void)
void IN_Button11Up (void)
void IN_Button12Down (void)
void IN_Button12Up (void)
void IN_Button13Down (void)
void IN_Button13Up (void)
void IN_Button14Down (void)
void IN_Button14Up (void)
void IN_Button15Down (void)
void IN_Button15Up (void)
void IN_CenterView (void)
void CL_AdjustAngles (void)
void CL_KeyMove (usercmd_t *cmd)
void CL_MouseEvent (int dx, int dy, int time)
void CL_JoystickEvent (int axis, int value, int time)
void CL_JoystickMove (usercmd_t *cmd)
void CL_MouseMove (usercmd_t *cmd)
void CL_CmdButtons (usercmd_t *cmd)
void CL_FinishMove (usercmd_t *cmd)
usercmd_t CL_CreateCmd (void)
void CL_CreateNewCommands (void)
qboolean CL_ReadyToSendPacket (void)
void CL_WritePacket (void)
void CL_SendCmd (void)
void CL_InitInput (void)
void CL_ShutdownInput (void)
Variables
unsigned frame_msec
int old_com_frameTime
kbutton_t in_left
kbutton_t in_right
kbutton_t in_forward
kbutton_t in_back
kbutton_t in_lookup
kbutton_t in_lookdown
kbutton_t in_moveleft
kbutton_t in_moveright
kbutton_t in_strafe
kbutton_t in_speed
kbutton_t in_up
kbutton_t in_down
kbutton_t in_buttons [16]
qboolean in_mlooking
cvar_t * cl_yawspeed
cvar_t * cl_pitchspeed
cvar_t * cl_run
cvar_t * cl_anglespeedkey
Function Documentation
void CL_AdjustAngles (void)
References kbutton_t::active, cl, CL_KeyState(), cls, clientStatic_t::frametime, PITCH, cvar_s::value, clientActive_t::viewangles, and YAW.
Referenced by CL_CreateCmd().
void CL_CmdButtons (usercmd_t * cmd)
References anykeydown, BUTTON_ANY, BUTTON_TALK, usercmd_s::buttons, Key_GetCatcher(), qfalse, and kbutton_t::wasPressed.
Referenced by CL_CreateCmd().
usercmd_t CL_CreateCmd (void)
References abs(), cl, CL_AdjustAngles(), CL_CmdButtons(), cl_debugMove, CL_FinishMove(), CL_JoystickMove(), CL_KeyMove(), CL_MouseMove(), Com_Memset, cvar_s::integer, PITCH, SCR_DebugGraph(), VectorCopy, clientActive_t::viewangles, and YAW.
Referenced by CL_CreateNewCommands().
void CL_CreateNewCommands (void)
References CA_PRIMED, cl, CL_CreateCmd(), clc, CMD_MASK, clientActive_t::cmdNumber, clientActive_t::cmds, com_frameTime, frame_msec, old_com_frameTime, and clientConnection_t::state.
Referenced by CL_SendCmd().
void CL_FinishMove (usercmd_t * cmd)
References ANGLE2SHORT, usercmd_s::angles, clientActive_t::cgameUserCmdValue, cl, clientActive_t::serverTime, usercmd_s::serverTime, clientActive_t::viewangles, and usercmd_s::weapon.
Referenced by CL_CreateCmd().
void CL_InitInput (void)
References cl_debugMove, cl_nodelta, Cmd_AddCommand(), Cvar_Get(), IN_BackDown(), IN_BackUp(), IN_Button0Down(), IN_Button0Up(), IN_Button10Down(), IN_Button10Up(), IN_Button11Down(), IN_Button11Up(), IN_Button12Down(), IN_Button12Up(), IN_Button13Down(), IN_Button13Up(), IN_Button14Down(), IN_Button14Up(), IN_Button1Down(), IN_Button1Up(), IN_Button2Down(), IN_Button2Up(), IN_Button3Down(), IN_Button3Up(), IN_Button4Down(), IN_Button4Up(), IN_Button5Down(), IN_Button5Up(), IN_Button6Down(), IN_Button6Up(), IN_Button7Down(), IN_Button7Up(), IN_Button8Down(), IN_Button8Up(), IN_Button9Down(), IN_Button9Up(), IN_CenterView(), IN_DownDown(), IN_DownUp(), IN_ForwardDown(), IN_ForwardUp(), IN_LeftDown(), IN_LeftUp(), IN_LookdownDown(), IN_LookdownUp(), IN_LookupDown(), IN_LookupUp(), IN_MLookDown(), IN_MLookUp(), IN_MoveleftDown(), IN_MoveleftUp(), IN_MoverightDown(), IN_MoverightUp(), IN_RightDown(), IN_RightUp(), IN_SpeedDown(), IN_SpeedUp(), IN_StrafeDown(), IN_StrafeUp(), IN_UpDown(), and IN_UpUp().
Referenced by CL_Init().
void CL_JoystickEvent (int axis, int value, int time)
Referenced by Com_EventLoop().
void CL_JoystickMove (usercmd_t * cmd)
References kbutton_t::active, BUTTON_WALKING, usercmd_s::buttons, cl, ClampChar(), cls, usercmd_s::forwardmove, clientStatic_t::frametime, in_mlooking, cvar_s::integer, j_forward, j_forward_axis, j_pitch, j_pitch_axis, j_side, j_side_axis, j_up, j_up_axis, j_yaw, j_yaw_axis, clientActive_t::joystickAxis, PITCH, usercmd_s::rightmove, usercmd_s::upmove, cvar_s::value, clientActive_t::viewangles, and YAW.
Referenced by CL_CreateCmd().
void CL_KeyMove (usercmd_t * cmd)
References kbutton_t::active, BUTTON_WALKING, usercmd_s::buttons, CL_KeyState(), ClampChar(), forward, usercmd_s::forwardmove, cvar_s::integer, usercmd_s::rightmove, up, and usercmd_s::upmove.
Referenced by CL_CreateCmd().
float CL_KeyState (kbutton_t * key)
References kbutton_t::active, com_frameTime, Com_Printf(), kbutton_t::downtime, frame_msec, kbutton_t::msec, and val.
Referenced by CL_AdjustAngles(), and CL_KeyMove().
void CL_MouseEvent (int dx, int dy, int time)
Referenced by Com_EventLoop().
void CL_MouseMove (usercmd_t * cmd)
References kbutton_t::active, clientActive_t::cgameSensitivity, cl, cl_freelook, cl_mouseAccel, cl_mouseAccelOffset, cl_mouseAccelStyle, cl_sensitivity, cl_showMouseRate, ClampChar(), Com_Printf(), usercmd_s::forwardmove, frame_msec, in_mlooking, cvar_s::integer, m_filter, m_forward, m_pitch, m_side, m_yaw, clientActive_t::mouseDx, clientActive_t::mouseDy, clientActive_t::mouseIndex, PITCH, usercmd_s::rightmove, cvar_s::value, clientActive_t::viewangles, and YAW.
Referenced by CL_CreateCmd().
qboolean CL_ReadyToSendPacket (void)
References CA_ACTIVE, CA_CINEMATIC, CA_PRIMED, cl, cl_lanForcePackets, cl_maxpackets, clc, cls, Cvar_Set(), clientConnection_t::demoplaying, clientConnection_t::downloadTempName, cvar_s::integer, clientConnection_t::lastPacketSentTime, NA_LOOPBACK, clientConnection_t::netchan, netchan_t::outgoingSequence, clientActive_t::outPackets, outPacket_t::p_realtime, PACKET_MASK, qfalse, qtrue, clientStatic_t::realtime, netchan_t::remoteAddress, clientConnection_t::state, Sys_IsLANAddress(), and netadr_t::type.
Referenced by CL_SendCmd().
void CL_SendCmd (void)
References CA_CONNECTED, CL_CreateNewCommands(), cl_paused, CL_ReadyToSendPacket(), cl_showSend, CL_WritePacket(), clc, Com_Printf(), com_sv_running, cvar_s::integer, clientConnection_t::state, and sv_paused.
Referenced by CL_Frame().
void CL_ShutdownInput (void)
References Cmd_RemoveCommand().
Referenced by CL_Shutdown().
void CL_WritePacket (void)
References CA_CINEMATIC, clientConnection_t::checksumFeed, cl, CL_Netchan_Transmit(), cl_nodelta, cl_packetdup, cl_showSend, CL_WriteDemoMessage(), clc, clc_clientCommand, clc_move, clc_moveNoDelta, clc_voip, clientConnection_t::clientNum, cls, CMD_MASK, clientActive_t::cmdNumber, clientActive_t::cmds, Com_IsVoipTarget(), Com_Memset, Com_Printf(), count, msg_t::cursize, Cvar_Set(), data, clientConnection_t::demoplaying, clientConnection_t::demorecording, clientConnection_t::demowaiting, cvar_s::integer, clientConnection_t::lastPacketSentTime, MAX_MSGLEN, MAX_PACKET_USERCMDS, MAX_RELIABLE_COMMANDS, clSnapshot_t::messageNum, MSG_Bitstream(), MSG_HashKey(), MSG_Init(), MSG_WriteByte(), MSG_WriteData(), MSG_WriteDeltaUsercmdKey(), MSG_WriteLong(), MSG_WriteShort(), MSG_WriteString(), clientConnection_t::netchan, netchan_t::outgoingSequence, clientActive_t::outPackets, outPacket_t::p_cmdNumber, outPacket_t::p_realtime, outPacket_t::p_serverTime, PACKET_MASK, clientStatic_t::realtime, clientConnection_t::reliableAcknowledge, clientConnection_t::reliableCommands, clientConnection_t::reliableSequence, clientConnection_t::serverCommands, clientConnection_t::serverCommandSequence, clientActive_t::serverId, clientConnection_t::serverMessageSequence, usercmd_s::serverTime, clientActive_t::snap, clientConnection_t::state, svc_EOF, svc_voip, clSnapshot_t::valid, and VOIP_SPATIAL.
Referenced by CL_Disconnect(), CL_DownloadsComplete(), CL_ParseDownload(), and CL_SendCmd().
void IN_BackDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_BackUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button0Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button0Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button10Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button10Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button11Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button11Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button12Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button12Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button13Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button13Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button14Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button14Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button15Down (void)
References IN_KeyDown().
void IN_Button15Up (void)
References IN_KeyUp().
void IN_Button1Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button1Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button2Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button2Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button3Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button3Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button4Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button4Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button5Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button5Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button6Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button6Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button7Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button7Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button8Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button8Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_Button9Down (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_Button9Up (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_CenterView (void)
References cl, playerState_s::delta_angles, PITCH, clSnapshot_t::ps, SHORT2ANGLE, clientActive_t::snap, and clientActive_t::viewangles.
Referenced by CL_InitInput(), and IN_MLookUp().
void IN_DownDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_DownUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_ForwardDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_ForwardUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_KeyDown (kbutton_t * b)
References kbutton_t::active, Cmd_Argv(), Com_Printf(), kbutton_t::down, kbutton_t::downtime, qtrue, and kbutton_t::wasPressed.
Referenced by IN_BackDown(), IN_Button0Down(), IN_Button10Down(), IN_Button11Down(), IN_Button12Down(), IN_Button13Down(), IN_Button14Down(), IN_Button15Down(), IN_Button1Down(), IN_Button2Down(), IN_Button3Down(), IN_Button4Down(), IN_Button5Down(), IN_Button6Down(), IN_Button7Down(), IN_Button8Down(), IN_Button9Down(), IN_DownDown(), IN_ForwardDown(), IN_LeftDown(), IN_LookdownDown(), IN_LookupDown(), IN_MoveleftDown(), IN_MoverightDown(), IN_RightDown(), IN_SpeedDown(), IN_StrafeDown(), and IN_UpDown().
void IN_KeyUp (kbutton_t * b)
References kbutton_t::active, Cmd_Argv(), kbutton_t::down, kbutton_t::downtime, frame_msec, kbutton_t::msec, and qfalse.
Referenced by IN_BackUp(), IN_Button0Up(), IN_Button10Up(), IN_Button11Up(), IN_Button12Up(), IN_Button13Up(), IN_Button14Up(), IN_Button15Up(), IN_Button1Up(), IN_Button2Up(), IN_Button3Up(), IN_Button4Up(), IN_Button5Up(), IN_Button6Up(), IN_Button7Up(), IN_Button8Up(), IN_Button9Up(), IN_DownUp(), IN_ForwardUp(), IN_LeftUp(), IN_LookdownUp(), IN_LookupUp(), IN_MoveleftUp(), IN_MoverightUp(), IN_RightUp(), IN_SpeedUp(), IN_StrafeUp(), and IN_UpUp().
void IN_LeftDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_LeftUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_LookdownDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_LookdownUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_LookupDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_LookupUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_MLookDown (void)
References in_mlooking, and qtrue.
Referenced by CL_InitInput().
void IN_MLookUp (void)
References cl_freelook, IN_CenterView(), in_mlooking, cvar_s::integer, and qfalse.
Referenced by CL_InitInput().
void IN_MoveleftDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_MoveleftUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_MoverightDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_MoverightUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_RightDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_RightUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_SpeedDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_SpeedUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_StrafeDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_StrafeUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
void IN_UpDown (void)
References IN_KeyDown().
Referenced by CL_InitInput().
void IN_UpUp (void)
References IN_KeyUp().
Referenced by CL_InitInput().
Variable Documentation
cvar_t* cl_anglespeedkey
Referenced by CL_Init().
cvar_t* cl_pitchspeed
Referenced by CL_Init().
cvar_t* cl_run
Referenced by CL_Init().
cvar_t* cl_yawspeed
Referenced by CL_Init().
unsigned frame_msec
Referenced by CL_CreateNewCommands(), CL_KeyState(), CL_MouseMove(), and IN_KeyUp().
kbutton_t in_back
kbutton_t in_buttons[16]
kbutton_t in_down
kbutton_t in_forward
kbutton_t in_left
kbutton_t in_lookdown
kbutton_t in_lookup
qboolean in_mlooking
Referenced by CL_JoystickMove(), CL_MouseMove(), IN_MLookDown(), and IN_MLookUp().
kbutton_t in_moveleft
kbutton_t in_moveright
kbutton_t in_right
kbutton_t in_speed
kbutton_t in_strafe
kbutton_t in_up
int old_com_frameTime
Referenced by CL_CreateNewCommands().