ioquake3: code/client/cl_parse.c File Reference
cl_parse.c File Reference
#include "client.h"
Functions
void SHOWNET (msg_t *msg, char *s)
void CL_DeltaEntity (msg_t *msg, clSnapshot_t *frame, int newnum, entityState_t *old, qboolean unchanged)
void CL_ParsePacketEntities (msg_t *msg, clSnapshot_t *oldframe, clSnapshot_t *newframe)
void CL_ParseSnapshot (msg_t *msg)
void CL_SystemInfoChanged (void)
static void CL_ParseServerInfo (void)
void CL_ParseGamestate (msg_t *msg)
void CL_ParseDownload (msg_t *msg)
void CL_ParseCommandString (msg_t *msg)
void CL_ParseServerMessage (msg_t *msg)
Variables
char * svc_strings [256]
int cl_connectedToPureServer
int cl_connectedToCheatServer
Function Documentation
void CL_DeltaEntity (msg_t * msg, clSnapshot_t * frame, int newnum, entityState_t * old, qboolean unchanged)
References cl, MAX_GENTITIES, MAX_PARSE_ENTITIES, MSG_ReadDeltaEntity(), entityState_s::number, clSnapshot_t::numEntities, clientActive_t::parseEntities, and clientActive_t::parseEntitiesNum.
Referenced by CL_ParsePacketEntities().
void CL_ParseCommandString (msg_t * msg)
References clc, MAX_RELIABLE_COMMANDS, MSG_ReadLong(), MSG_ReadString(), Q_strncpyz(), s, clientConnection_t::serverCommands, and clientConnection_t::serverCommandSequence.
Referenced by CL_ParseServerMessage().
void CL_ParseDownload (msg_t * msg)
References CL_AddReliableCommand(), CL_NextDownload(), CL_WritePacket(), clc, Com_DPrintf(), Com_Error(), Com_Printf(), Cvar_SetValue(), data, clientConnection_t::download, clientConnection_t::downloadBlock, clientConnection_t::downloadCount, clientConnection_t::downloadName, clientConnection_t::downloadSize, clientConnection_t::downloadTempName, ERR_DROP, FS_FCloseFile(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_Write(), MAX_MSGLEN, MSG_ReadData(), MSG_ReadLong(), MSG_ReadShort(), MSG_ReadString(), qfalse, and va().
Referenced by CL_ParseServerMessage().
void CL_ParseGamestate (msg_t * msg)
References clientConnection_t::checksumFeed, cl, cl_autoRecordDemo, CL_ClearState(), CL_InitDownloads(), CL_ParseServerInfo(), CL_StopRecord_f(), CL_SystemInfoChanged(), clc, clientConnection_t::clientNum, cls, Com_Error(), Com_Memcpy, Com_Memset, Con_Close(), clientConnection_t::connectPacketCount, Cvar_Flags(), CVAR_MODIFIED, Cvar_Set(), Cvar_VariableStringBuffer(), gameState_t::dataCount, clientConnection_t::demorecording, clientActive_t::entityBaselines, ERR_DROP, FS_ConditionalRestart(), clientActive_t::gameState, GENTITYNUM_BITS, cvar_s::integer, MAX_CONFIGSTRINGS, MAX_GAMESTATE_CHARS, MAX_GENTITIES, MAX_QPATH, MSG_ReadBigString(), MSG_ReadBits(), MSG_ReadByte(), MSG_ReadDeltaEntity(), MSG_ReadLong(), MSG_ReadShort(), clientStatic_t::oldGame, clientStatic_t::oldGameSet, Q_strncpyz(), qfalse, qtrue, s, clientConnection_t::serverCommandSequence, gameState_t::stringData, gameState_t::stringOffsets, svc_baseline, svc_configstring, and svc_EOF.
Referenced by CL_ParseServerMessage().
void CL_ParsePacketEntities (msg_t * msg, clSnapshot_t * oldframe, clSnapshot_t * newframe)
References cl, CL_DeltaEntity(), cl_shownet, Com_Error(), Com_Printf(), msg_t::cursize, clientActive_t::entityBaselines, ERR_DROP, GENTITYNUM_BITS, cvar_s::integer, MAX_GENTITIES, MAX_PARSE_ENTITIES, MSG_ReadBits(), NULL, entityState_s::number, clSnapshot_t::numEntities, clientActive_t::parseEntities, clSnapshot_t::parseEntitiesNum, clientActive_t::parseEntitiesNum, qfalse, qtrue, and msg_t::readcount.
Referenced by CL_ParseSnapshot().
static void CL_ParseServerInfo (void) [static]
References cl, clc, CS_SERVERINFO, clientActive_t::gameState, Info_ValueForKey(), Q_strncpyz(), gameState_t::stringData, gameState_t::stringOffsets, clientConnection_t::sv_allowDownload, and clientConnection_t::sv_dlURL.
Referenced by CL_ParseGamestate().
void CL_ParseServerMessage (msg_t * msg)
References CL_ParseCommandString(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParseSnapshot(), cl_shownet, clc, Com_Error(), Com_Printf(), msg_t::cursize, ERR_DROP, cvar_s::integer, MAX_RELIABLE_COMMANDS, MSG_Bitstream(), MSG_ReadByte(), MSG_ReadLong(), msg_t::readcount, clientConnection_t::reliableAcknowledge, clientConnection_t::reliableSequence, SHOWNET(), svc_download, svc_EOF, svc_gamestate, svc_nop, svc_serverCommand, svc_snapshot, svc_strings, and svc_voip.
Referenced by CL_PacketEvent(), and CL_ReadDemoMessage().
void CL_ParseSnapshot (msg_t * msg)
References clSnapshot_t::areamask, cl, CL_ParsePacketEntities(), cl_paused, cl_shownet, clc, cls, Com_Error(), Com_Memset, Com_Printf(), playerState_s::commandTime, clSnapshot_t::deltaNum, clientConnection_t::demowaiting, ERR_DROP, cvar_s::integer, MAX_PARSE_ENTITIES, clSnapshot_t::messageNum, cvar_s::modified, MSG_ReadByte(), MSG_ReadData(), MSG_ReadDeltaPlayerstate(), MSG_ReadLong(), clientConnection_t::netchan, clientActive_t::newSnapshots, NULL, netchan_t::outgoingSequence, clientActive_t::outPackets, outPacket_t::p_realtime, outPacket_t::p_serverTime, PACKET_BACKUP, PACKET_MASK, clSnapshot_t::parseEntitiesNum, clientActive_t::parseEntitiesNum, clSnapshot_t::ping, clSnapshot_t::ps, qfalse, qtrue, clientStatic_t::realtime, clSnapshot_t::serverCommandNum, clientConnection_t::serverCommandSequence, clientConnection_t::serverMessageSequence, clSnapshot_t::serverTime, SHOWNET(), clientActive_t::snap, clSnapshot_t::snapFlags, clientActive_t::snapshots, and clSnapshot_t::valid.
Referenced by CL_ParseServerMessage().
void CL_SystemInfoChanged (void)
References BIG_INFO_KEY, BIG_INFO_VALUE, cl, cl_connectedToCheatServer, cl_connectedToPureServer, clc, Com_Printf(), clientConnection_t::compat, CS_SYSTEMINFO, Cvar_Flags(), Cvar_Get(), CVAR_NONEXISTENT, CVAR_ROM, CVAR_SERVER_CREATED, Cvar_Set(), Cvar_SetCheatState(), Cvar_SetSafe(), CVAR_SYSTEMINFO, CVAR_USER_CREATED, Cvar_VariableString(), Cvar_VariableValue(), clientConnection_t::demoplaying, FS_CheckDirTraversal(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), clientActive_t::gameState, GT_SINGLE_PLAYER, Info_NextPair(), Info_ValueForKey(), Q_stricmp(), qfalse, qtrue, s, S_COLOR_YELLOW, clientActive_t::serverId, gameState_t::stringData, gameState_t::stringOffsets, and t.
Referenced by CL_ConfigstringModified(), and CL_ParseGamestate().
void SHOWNET (msg_t * msg, char * s)
References cl_shownet, Com_Printf(), cvar_s::integer, and msg_t::readcount.
Referenced by CL_ParseServerMessage(), and CL_ParseSnapshot().
Variable Documentation
int cl_connectedToCheatServer
Referenced by CL_InitCGame(), and CL_SystemInfoChanged().
int cl_connectedToPureServer
Referenced by CL_Disconnect(), CL_InitCGame(), CL_InitUI(), and CL_SystemInfoChanged().
char* svc_strings[256]
Initial value:
 {
        "svc_bad",
        "svc_nop",
        "svc_gamestate",
        "svc_configstring",
        "svc_baseline",
        "svc_serverCommand",
        "svc_download",
        "svc_snapshot",
        "svc_EOF",
        "svc_voip",
}
Referenced by CL_ParseServerMessage().