ioquake3: code/qcommon/cm_test.c File Reference
cm_test.c File Reference
#include "cm_local.h"
Functions
int CM_PointLeafnum_r (const vec3_t p, int num)
int CM_PointLeafnum (const vec3_t p)
void CM_StoreLeafs (leafList_t *ll, int nodenum)
void CM_StoreBrushes (leafList_t *ll, int nodenum)
void CM_BoxLeafnums_r (leafList_t *ll, int nodenum)
int CM_BoxLeafnums (const vec3_t mins, const vec3_t maxs, int *list, int listsize, int *lastLeaf)
int CM_BoxBrushes (const vec3_t mins, const vec3_t maxs, cbrush_t **list, int listsize)
int CM_PointContents (const vec3_t p, clipHandle_t model)
int CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
byte * CM_ClusterPVS (int cluster)
void CM_FloodArea_r (int areaNum, int floodnum)
void CM_FloodAreaConnections (void)
void CM_AdjustAreaPortalState (int area1, int area2, qboolean open)
qboolean CM_AreasConnected (int area1, int area2)
int CM_WriteAreaBits (byte *buffer, int area)
qboolean CM_BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
qboolean CM_BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t point)
Function Documentation
void CM_AdjustAreaPortalState (int area1, int area2, qboolean open)
References clipMap_t::areaPortals, cm, CM_FloodAreaConnections(), Com_Error(), ERR_DROP, and clipMap_t::numAreas.
Referenced by SV_AdjustAreaPortalState().
qboolean CM_AreasConnected (int area1, int area2)
References clipMap_t::areas, cm, cm_noAreas, Com_Error(), ERR_DROP, cArea_t::floodnum, cvar_s::integer, clipMap_t::numAreas, qfalse, and qtrue.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_GameSystemCalls(), and SV_inPVS().
qboolean CM_BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
References qfalse, qtrue, and SURFACE_CLIP_EPSILON.
Referenced by CM_TraceThroughLeaf(), and CM_TraceThroughPatchCollide().
qboolean CM_BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t point)
References qfalse, qtrue, and SURFACE_CLIP_EPSILON.
Referenced by CM_PointContents().
int CM_BoxBrushes (const vec3_t mins, const vec3_t maxs, cbrush_t ** list, int listsize)
References leafList_s::bounds, clipMap_t::checkcount, cm, CM_BoxLeafnums_r(), CM_StoreBrushes(), leafList_s::count, leafList_s::lastLeaf, leafList_s::list, leafList_s::maxcount, leafList_s::overflowed, qfalse, leafList_s::storeLeafs, and VectorCopy.
int CM_BoxLeafnums (const vec3_t mins, const vec3_t maxs, int * list, int listsize, int * lastLeaf)
References leafList_s::bounds, clipMap_t::checkcount, cm, CM_BoxLeafnums_r(), CM_StoreLeafs(), leafList_s::count, leafList_s::lastLeaf, list(), leafList_s::list, leafList_s::maxcount, leafList_s::overflowed, qfalse, leafList_s::storeLeafs, and VectorCopy.
Referenced by SV_LinkEntity().
void CM_BoxLeafnums_r (leafList_t * ll, int nodenum)
References leafList_s::bounds, BoxOnPlaneSide(), cNode_t::children, cm, CM_BoxLeafnums_r(), node(), clipMap_t::nodes, cNode_t::plane, s, and leafList_s::storeLeafs.
Referenced by CM_BoxBrushes(), CM_BoxLeafnums(), CM_BoxLeafnums_r(), and CM_PositionTest().
byte* CM_ClusterPVS (int cluster)
References clipMap_t::clusterBytes, cm, clipMap_t::numClusters, clipMap_t::vised, and clipMap_t::visibility.
Referenced by CL_InitRef(), SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_inPVSIgnorePortals().
void CM_FloodArea_r (int areaNum, int floodnum)
References clipMap_t::areaPortals, clipMap_t::areas, cm, Com_Error(), con, ERR_DROP, cArea_t::floodnum, cArea_t::floodvalid, clipMap_t::floodvalid, and clipMap_t::numAreas.
Referenced by CM_FloodAreaConnections().
void CM_FloodAreaConnections (void)
References clipMap_t::areas, cm, CM_FloodArea_r(), cArea_t::floodvalid, clipMap_t::floodvalid, and clipMap_t::numAreas.
Referenced by CM_AdjustAreaPortalState(), and CM_LoadMap().
int CM_PointContents (const vec3_t p, clipHandle_t model)
References b, cbrush_t::bounds, clipMap_t::brushes, cm, CM_BoundsIntersectPoint(), CM_ClipHandleToModel(), CM_PointLeafnum_r(), cbrush_t::contents, cplane_s::dist, DotProduct, cLeaf_t::firstLeafBrush, cmodel_s::leaf, clipMap_t::leafbrushes, clipMap_t::leafs, cplane_s::normal, cLeaf_t::numLeafBrushes, clipMap_t::numNodes, cbrush_t::numsides, cbrushside_t::plane, and cbrush_t::sides.
Referenced by CL_CgameSystemCalls(), CM_TransformedPointContents(), and SV_PointContents().
int CM_PointLeafnum (const vec3_t p)
References cm, CM_PointLeafnum_r(), and clipMap_t::numNodes.
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_inPVSIgnorePortals().
int CM_PointLeafnum_r (const vec3_t p, int num)
References c_pointcontents, cNode_t::children, cm, cplane_s::dist, DotProduct, node(), clipMap_t::nodes, cplane_s::normal, cNode_t::plane, and cplane_s::type.
Referenced by CM_PointContents(), and CM_PointLeafnum().
void CM_StoreBrushes (leafList_t * ll, int nodenum)
References b, cbrush_t::bounds, leafList_s::bounds, clipMap_t::brushes, cbrush_t::checkcount, clipMap_t::checkcount, cm, leafList_s::count, cLeaf_t::firstLeafBrush, clipMap_t::leafbrushes, clipMap_t::leafs, clipMap_t::leafsurfaces, leafList_s::list, leafList_s::maxcount, cLeaf_t::numLeafBrushes, cLeaf_t::numLeafSurfaces, leafList_s::overflowed, qtrue, and clipMap_t::surfaces.
Referenced by CM_BoxBrushes().
void CM_StoreLeafs (leafList_t * ll, int nodenum)
References cLeaf_t::cluster, cm, leafList_s::count, leafList_s::lastLeaf, clipMap_t::leafs, leafList_s::list, leafList_s::maxcount, leafList_s::overflowed, and qtrue.
Referenced by CM_BoxLeafnums(), and CM_PositionTest().
int CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
References AngleVectors(), BOX_MODEL_HANDLE, CM_PointContents(), DotProduct, forward, right, up, VectorCopy, and VectorSubtract.
Referenced by CL_CgameSystemCalls(), and SV_PointContents().
int CM_WriteAreaBits (byte * buffer, int area)
References clipMap_t::areas, cm, cm_noAreas, Com_Memset, cArea_t::floodnum, cvar_s::integer, and clipMap_t::numAreas.
Referenced by SV_AddEntitiesVisibleFromPoint().