ioquake3: code/qcommon/cm_patch.h File Reference
cm_patch.h File Reference
Data Structures
struct patchPlane_t
struct facet_t
struct patchCollide_s
struct cGrid_t
Defines
#define MAX_FACETS 1024
#define MAX_PATCH_PLANES 2048
#define MAX_GRID_SIZE 129
#define SUBDIVIDE_DISTANCE 16
#define PLANE_TRI_EPSILON 0.1
#define WRAP_POINT_EPSILON 0.1
Typedefs
typedef struct patchCollide_s patchCollide_t
Functions
struct patchCollide_s * CM_GeneratePatchCollide (int width, int height, vec3_t *points)
Define Documentation
#define MAX_FACETS 1024
Referenced by CM_PatchCollideFromGrid().
#define MAX_GRID_SIZE 129
Referenced by CM_GeneratePatchCollide(), CM_PatchCollideFromGrid(), InvertErrorTable(), R_GridInsertColumn(), R_GridInsertRow(), R_StitchPatches(), R_SubdividePatchToGrid(), and RB_SurfaceGrid().
#define MAX_PATCH_PLANES 2048
Referenced by CM_FindPlane(), CM_FindPlane2(), and CM_TracePointThroughPatchCollide().
#define PLANE_TRI_EPSILON 0.1
Referenced by CM_FindPlane(), and CM_PointOnPlaneSide().
#define SUBDIVIDE_DISTANCE 16
Referenced by CM_NeedsSubdivision().
#define WRAP_POINT_EPSILON 0.1
Referenced by CM_SetGridWrapWidth().
Typedef Documentation
typedef struct patchCollide_s patchCollide_t
Function Documentation
struct patchCollide_s* CM_GeneratePatchCollide (int width, int height, vec3_t * points) [read]
References AddPointToBounds(), patchCollide_s::bounds, c_totalPatchBlocks, ClearBounds(), CM_PatchCollideFromGrid(), CM_RemoveDegenerateColumns(), CM_SetGridWrapWidth(), CM_SubdivideGridColumns(), CM_TransposeGrid(), Com_Error(), ERR_DROP, h_high, height, cGrid_t::height, Hunk_Alloc, MAX_GRID_SIZE, cGrid_t::points, qfalse, VectorCopy, width, cGrid_t::width, cGrid_t::wrapHeight, and cGrid_t::wrapWidth.