ioquake3: code/qcommon/cm_polylib.h File Reference
cm_polylib.h File Reference
Data Structures
struct winding_t
Defines
#define MAX_POINTS_ON_WINDING 64
#define SIDE_FRONT 0
#define SIDE_BACK 1
#define SIDE_ON 2
#define SIDE_CROSS 3
#define CLIP_EPSILON 0.1f
#define MAX_MAP_BOUNDS 65535
Functions
winding_t * AllocWinding (int points)
vec_t WindingArea (winding_t *w)
void WindingCenter (winding_t *w, vec3_t center)
void ClipWindingEpsilon (winding_t *in, vec3_t normal, vec_t dist, vec_t epsilon, winding_t **front, winding_t **back)
winding_t * ChopWinding (winding_t *in, vec3_t normal, vec_t dist)
winding_t * CopyWinding (winding_t *w)
winding_t * ReverseWinding (winding_t *w)
winding_t * BaseWindingForPlane (vec3_t normal, vec_t dist)
void CheckWinding (winding_t *w)
void WindingPlane (winding_t *w, vec3_t normal, vec_t *dist)
void RemoveColinearPoints (winding_t *w)
int WindingOnPlaneSide (winding_t *w, vec3_t normal, vec_t dist)
void FreeWinding (winding_t *w)
void WindingBounds (winding_t *w, vec3_t mins, vec3_t maxs)
void AddWindingToConvexHull (winding_t *w, winding_t **hull, vec3_t normal)
void ChopWindingInPlace (winding_t **w, vec3_t normal, vec_t dist, vec_t epsilon)
void pw (winding_t *w)
Define Documentation
#define CLIP_EPSILON 0.1f
#define MAX_MAP_BOUNDS 65535
Referenced by BaseWindingForPlane(), CheckWinding(), CM_ValidateFacet(), and WindingBounds().
#define MAX_POINTS_ON_WINDING 64
Referenced by ChopWindingInPlace(), ClipWindingEpsilon(), and RemoveColinearPoints().
#define SIDE_BACK 1
Referenced by ChopWindingInPlace(), ClipSkyPolygon(), ClipWindingEpsilon(), CM_PointOnPlaneSide(), CM_SetBorderInward(), and WindingOnPlaneSide().
#define SIDE_CROSS 3
Referenced by WindingOnPlaneSide().
#define SIDE_FRONT 0
Referenced by ChopWindingInPlace(), ClipSkyPolygon(), ClipWindingEpsilon(), CM_PointOnPlaneSide(), CM_SetBorderInward(), and WindingOnPlaneSide().
#define SIDE_ON 2
Referenced by ChopWindingInPlace(), ClipSkyPolygon(), ClipWindingEpsilon(), CM_PointOnPlaneSide(), and WindingOnPlaneSide().
Function Documentation
void AddWindingToConvexHull (winding_t * w, winding_t ** hull, vec3_t normal)
References AllocWinding(), Com_Memcpy, CopyWinding(), CrossProduct(), DotProduct, FreeWinding(), MAX_HULL_POINTS, winding_t::numpoints, ON_EPSILON, winding_t::p, qfalse, qtrue, VectorCopy, VectorNormalize2(), and VectorSubtract.
winding_t* AllocWinding (int points)
References c_active_windings, c_peak_windings, c_winding_allocs, c_winding_points, Com_Memset, s, and Z_Malloc.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), ChopWindingInPlace(), ClipWindingEpsilon(), CopyWinding(), and ReverseWinding().
winding_t* BaseWindingForPlane (vec3_t normal, vec_t dist)
References AllocWinding(), Com_Error(), CrossProduct(), DotProduct, ERR_DROP, MAX_MAP_BOUNDS, winding_t::numpoints, winding_t::p, vec3_origin, VectorAdd, VectorCopy, VectorMA(), VectorNormalize2(), VectorScale, VectorSubtract, vright, and vup.
Referenced by CM_AddFacetBevels(), CM_DrawDebugSurface(), and CM_ValidateFacet().
void CheckWinding (winding_t * w)
References Com_Error(), CrossProduct(), DotProduct, ERR_DROP, MAX_MAP_BOUNDS, winding_t::numpoints, ON_EPSILON, winding_t::p, VectorLength(), VectorNormalize2(), VectorSubtract, WindingArea(), and WindingPlane().
winding_t* ChopWinding (winding_t * in, vec3_t normal, vec_t dist)
References b, ClipWindingEpsilon(), FreeWinding(), and ON_EPSILON.
void ChopWindingInPlace (winding_t ** w, vec3_t normal, vec_t dist, vec_t epsilon)
References AllocWinding(), Com_Error(), DotProduct, ERR_DROP, FreeWinding(), in, MAX_POINTS_ON_WINDING, NULL, winding_t::numpoints, winding_t::p, SIDE_BACK, SIDE_FRONT, SIDE_ON, and VectorCopy.
Referenced by CM_AddFacetBevels(), CM_DrawDebugSurface(), and CM_ValidateFacet().
void ClipWindingEpsilon (winding_t * in, vec3_t normal, vec_t dist, vec_t epsilon, winding_t ** front, winding_t ** back)
References AllocWinding(), b, Com_Error(), CopyWinding(), DotProduct, ERR_DROP, MAX_POINTS_ON_WINDING, NULL, winding_t::numpoints, winding_t::p, SIDE_BACK, SIDE_FRONT, SIDE_ON, and VectorCopy.
Referenced by ChopWinding().
winding_t* CopyWinding (winding_t * w)
References AllocWinding(), Com_Memcpy, intptr_t(), and winding_t::numpoints.
Referenced by AddWindingToConvexHull(), ClipWindingEpsilon(), and CM_AddFacetBevels().
void FreeWinding (winding_t * w)
References c_active_windings, Com_Error(), ERR_FATAL, and Z_Free().
Referenced by AddWindingToConvexHull(), ChopWinding(), ChopWindingInPlace(), CM_AddFacetBevels(), CM_DrawDebugSurface(), and CM_ValidateFacet().
void pw (winding_t * w)
References winding_t::numpoints, winding_t::p, and printf().
Referenced by lsp_to_lpc().
void RemoveColinearPoints (winding_t * w)
References c_removed, Com_Memcpy, DotProduct, MAX_POINTS_ON_WINDING, winding_t::numpoints, winding_t::p, VectorCopy, VectorNormalize2(), and VectorSubtract.
winding_t* ReverseWinding (winding_t * w)
References AllocWinding(), winding_t::numpoints, winding_t::p, and VectorCopy.
vec_t WindingArea (winding_t * w)
References CrossProduct(), winding_t::numpoints, winding_t::p, VectorLength(), and VectorSubtract.
Referenced by CheckWinding().
void WindingBounds (winding_t * w, vec3_t mins, vec3_t maxs)
References MAX_MAP_BOUNDS, winding_t::numpoints, and winding_t::p.
Referenced by CM_AddFacetBevels(), and CM_ValidateFacet().
void WindingCenter (winding_t * w, vec3_t center)
References winding_t::numpoints, winding_t::p, vec3_origin, VectorAdd, VectorCopy, and VectorScale.
int WindingOnPlaneSide (winding_t * w, vec3_t normal, vec_t dist)
References DotProduct, winding_t::numpoints, ON_EPSILON, winding_t::p, qfalse, qtrue, SIDE_BACK, SIDE_CROSS, SIDE_FRONT, and SIDE_ON.
void WindingPlane (winding_t * w, vec3_t normal, vec_t * dist)
References CrossProduct(), DotProduct, winding_t::p, VectorNormalize2(), and VectorSubtract.
Referenced by CheckWinding().