ioquake3: code/qcommon/cm_patch.c File Reference
cm_patch.c File Reference
#include "cm_local.h"
#include "cm_patch.h"
Defines
#define POINT_EPSILON 0.1
#define NORMAL_EPSILON 0.0001
#define DIST_EPSILON 0.02
Enumerations
enum edgeName_t { EN_TOP, EN_RIGHT, EN_BOTTOM, EN_LEFT }
Functions
void CM_ClearLevelPatches (void)
static int CM_SignbitsForNormal (vec3_t normal)
static qboolean CM_PlaneFromPoints (vec4_t plane, vec3_t a, vec3_t b, vec3_t c)
static qboolean CM_NeedsSubdivision (vec3_t a, vec3_t b, vec3_t c)
static void CM_Subdivide (vec3_t a, vec3_t b, vec3_t c, vec3_t out1, vec3_t out2, vec3_t out3)
static void CM_TransposeGrid (cGrid_t *grid)
static void CM_SetGridWrapWidth (cGrid_t *grid)
static void CM_SubdivideGridColumns (cGrid_t *grid)
static qboolean CM_ComparePoints (float *a, float *b)
static void CM_RemoveDegenerateColumns (cGrid_t *grid)
int CM_PlaneEqual (patchPlane_t *p, float plane[4], int *flipped)
void CM_SnapVector (vec3_t normal)
int CM_FindPlane2 (float plane[4], int *flipped)
static int CM_FindPlane (float *p1, float *p2, float *p3)
static int CM_PointOnPlaneSide (float *p, int planeNum)
static int CM_GridPlane (int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int tri)
static int CM_EdgePlaneNum (cGrid_t *grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int k)
static void CM_SetBorderInward (facet_t *facet, cGrid_t *grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int which)
static qboolean CM_ValidateFacet (facet_t *facet)
void CM_AddFacetBevels (facet_t *facet)
static void CM_PatchCollideFromGrid (cGrid_t *grid, patchCollide_t *pf)
struct patchCollide_s * CM_GeneratePatchCollide (int width, int height, vec3_t *points)
void CM_TracePointThroughPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
int CM_CheckFacetPlane (float *plane, vec3_t start, vec3_t end, float *enterFrac, float *leaveFrac, int *hit)
void CM_TraceThroughPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
qboolean CM_PositionTestInPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
void BotDrawDebugPolygons (void(*drawPoly)(int color, int numPoints, float *points), int value)
void CM_DrawDebugSurface (void(*drawPoly)(int color, int numPoints, float *points))
Variables
int c_totalPatchBlocks
int c_totalPatchSurfaces
int c_totalPatchEdges
static const patchCollide_t * debugPatchCollide
static const facet_t * debugFacet
static qboolean debugBlock
static vec3_t debugBlockPoints [4]
static int numPlanes
static patchPlane_t planes [MAX_PATCH_PLANES]
static int numFacets
static facet_t facets [MAX_PATCH_PLANES]
Define Documentation
#define DIST_EPSILON 0.02
Referenced by CM_PlaneEqual().
#define NORMAL_EPSILON 0.0001
Referenced by CM_PlaneEqual(), and CM_SnapVector().
#define POINT_EPSILON 0.1
Referenced by CM_ComparePoints().
Enumeration Type Documentation
enum edgeName_t
Enumerator:
EN_TOP
EN_RIGHT
EN_BOTTOM
EN_LEFT
Function Documentation
void BotDrawDebugPolygons (void(*)(int color, int numPoints, float *points) drawPoly, int value)
References bot_enable, bot_maxdebugpolys, botlib_export_s::BotLibVarSet, BUTTON_ATTACK, usercmd_s::buttons, serverStatic_t::clients, bot_debugpoly_s::color, entityShared_t::currentAngles, entityShared_t::currentOrigin, Cvar_Get(), client_s::gentity, cvar_s::integer, bot_debugpoly_s::inuse, client_s::lastUsercmd, NULL, bot_debugpoly_s::numPoints, bot_debugpoly_s::points, sharedEntity_t::r, cvar_s::string, svs, and botlib_export_s::Test.
Referenced by CM_DrawDebugSurface().
void CM_AddFacetBevels (facet_t * facet)
References BaseWindingForPlane(), facet_t::borderInward, facet_t::borderNoAdjust, facet_t::borderPlanes, ChopWindingInPlace(), CM_FindPlane2(), CM_PlaneEqual(), CM_SnapVector(), Com_DPrintf(), Com_Printf(), CopyWinding(), CrossProduct(), DotProduct, FreeWinding(), facet_t::numBorders, winding_t::numpoints, winding_t::p, patchPlane_t::plane, qtrue, facet_t::surfacePlane, vec3_origin, Vector4Copy, VectorClear, VectorNegate, VectorNormalize(), VectorSubtract, and WindingBounds().
Referenced by CM_PatchCollideFromGrid().
int CM_CheckFacetPlane (float * plane, vec3_t start, vec3_t end, float * enterFrac, float * leaveFrac, int * hit)
References DotProduct, qfalse, qtrue, and SURFACE_CLIP_EPSILON.
Referenced by CM_TraceThroughPatchCollide().
void CM_ClearLevelPatches (void)
References NULL.
Referenced by CM_ClearMap(), and CM_LoadMap().
static qboolean CM_ComparePoints (float * a, float * b) [static]
References POINT_EPSILON, qfalse, and qtrue.
Referenced by CM_RemoveDegenerateColumns().
void CM_DrawDebugSurface (void(*)(int color, int numPoints, float *points) drawPoly)
References BaseWindingForPlane(), facet_t::borderInward, facet_t::borderPlanes, BotDrawDebugPolygons(), patchCollide_s::bounds, ChopWindingInPlace(), Com_Printf(), Cvar_Get(), debugBlockPoints, debugPatchCollide, DotProduct, patchCollide_s::facets, FreeWinding(), cvar_s::integer, n, facet_t::numBorders, numFacets, winding_t::numpoints, winding_t::p, pc, patchPlane_t::plane, patchCollide_s::planes, qfalse, facet_t::surfacePlane, cvar_s::value, vec3_origin, Vector4Copy, VectorCopy, VectorNegate, and VectorSubtract.
Referenced by CL_InitRef().
static int CM_EdgePlaneNum (cGrid_t * grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int k) [static]
References CM_FindPlane(), CM_GridPlane(), Com_Error(), ERR_DROP, cGrid_t::points, up, and VectorMA().
Referenced by CM_PatchCollideFromGrid().
static int CM_FindPlane (float * p1, float * p2, float * p3) [static]
References CM_PlaneFromPoints(), CM_SignbitsForNormal(), Com_Error(), DotProduct, ERR_DROP, MAX_PATCH_PLANES, numPlanes, patchPlane_t::plane, PLANE_TRI_EPSILON, patchPlane_t::signbits, and Vector4Copy.
Referenced by CM_EdgePlaneNum(), and CM_PatchCollideFromGrid().
int CM_FindPlane2 (float plane[4], int * flipped)
References CM_PlaneEqual(), CM_SignbitsForNormal(), Com_Error(), ERR_DROP, MAX_PATCH_PLANES, numPlanes, qfalse, patchPlane_t::signbits, and Vector4Copy.
Referenced by CM_AddFacetBevels().
struct patchCollide_s* CM_GeneratePatchCollide (int width, int height, vec3_t * points) [read]
References AddPointToBounds(), patchCollide_s::bounds, c_totalPatchBlocks, ClearBounds(), CM_PatchCollideFromGrid(), CM_RemoveDegenerateColumns(), CM_SetGridWrapWidth(), CM_SubdivideGridColumns(), CM_TransposeGrid(), Com_Error(), ERR_DROP, h_high, height, cGrid_t::height, Hunk_Alloc, MAX_GRID_SIZE, cGrid_t::points, qfalse, VectorCopy, width, cGrid_t::width, cGrid_t::wrapHeight, and cGrid_t::wrapWidth.
Referenced by CMod_LoadPatches().
static int CM_GridPlane (int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int tri) [static]
References Com_Printf().
Referenced by CM_EdgePlaneNum().
static qboolean CM_NeedsSubdivision (vec3_t a, vec3_t b, vec3_t c) [static]
References SUBDIVIDE_DISTANCE, VectorLength(), and VectorSubtract.
Referenced by CM_SubdivideGridColumns().
static void CM_PatchCollideFromGrid (cGrid_t * grid, patchCollide_t * pf) [static]
References facet_t::borderNoAdjust, facet_t::borderPlanes, CM_AddFacetBevels(), CM_EdgePlaneNum(), CM_FindPlane(), CM_SetBorderInward(), CM_ValidateFacet(), Com_Error(), Com_Memcpy, Com_Memset, EN_BOTTOM, EN_LEFT, EN_RIGHT, EN_TOP, ERR_DROP, patchCollide_s::facets, h_high, height, cGrid_t::height, Hunk_Alloc, MAX_FACETS, MAX_GRID_SIZE, facet_t::numBorders, patchCollide_s::numFacets, numFacets, patchCollide_s::numPlanes, numPlanes, patchCollide_s::planes, cGrid_t::points, facet_t::surfacePlane, width, cGrid_t::width, cGrid_t::wrapHeight, and cGrid_t::wrapWidth.
Referenced by CM_GeneratePatchCollide().
int CM_PlaneEqual (patchPlane_t * p, float plane[4], int * flipped)
References DIST_EPSILON, NORMAL_EPSILON, patchPlane_t::plane, qfalse, qtrue, and VectorNegate.
Referenced by CM_AddFacetBevels(), and CM_FindPlane2().
static qboolean CM_PlaneFromPoints (vec4_t plane, vec3_t a, vec3_t b, vec3_t c) [static]
References CrossProduct(), DotProduct, qfalse, qtrue, VectorNormalize(), and VectorSubtract.
Referenced by CM_FindPlane().
static int CM_PointOnPlaneSide (float * p, int planeNum) [static]
References DotProduct, patchPlane_t::plane, PLANE_TRI_EPSILON, SIDE_BACK, SIDE_FRONT, and SIDE_ON.
Referenced by CM_SetBorderInward().
qboolean CM_PositionTestInPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
References facet_t::borderInward, facet_t::borderPlanes, DotProduct, patchCollide_s::facets, traceWork_t::isPoint, facet_t::numBorders, patchCollide_s::numFacets, sphere_t::offset, traceWork_t::offsets, patchPlane_t::plane, patchCollide_s::planes, planes, qfalse, qtrue, sphere_t::radius, patchPlane_t::signbits, traceWork_t::sphere, traceWork_t::start, facet_t::surfacePlane, t, sphere_t::use, VectorAdd, VectorCopy, VectorNegate, and VectorSubtract.
Referenced by CM_TestInLeaf().
static void CM_RemoveDegenerateColumns (cGrid_t * grid) [static]
References CM_ComparePoints(), cGrid_t::height, cGrid_t::points, VectorCopy, and cGrid_t::width.
Referenced by CM_GeneratePatchCollide().
static void CM_SetBorderInward (facet_t * facet, cGrid_t * grid, int gridPlanes[MAX_GRID_SIZE][MAX_GRID_SIZE][2], int i, int j, int which) [static]
References facet_t::borderInward, facet_t::borderPlanes, CM_PointOnPlaneSide(), Com_DPrintf(), Com_Error(), debugBlock, debugBlockPoints, ERR_FATAL, facet_t::numBorders, cGrid_t::points, qfalse, qtrue, SIDE_BACK, SIDE_FRONT, and VectorCopy.
Referenced by CM_PatchCollideFromGrid().
static void CM_SetGridWrapWidth (cGrid_t * grid) [static]
References cGrid_t::height, cGrid_t::points, qfalse, qtrue, cGrid_t::width, WRAP_POINT_EPSILON, and cGrid_t::wrapWidth.
Referenced by CM_GeneratePatchCollide().
static int CM_SignbitsForNormal (vec3_t normal) [static]
References bits().
Referenced by CM_FindPlane(), and CM_FindPlane2().
void CM_SnapVector (vec3_t normal)
References NORMAL_EPSILON, and VectorClear.
Referenced by CM_AddFacetBevels().
static void CM_Subdivide (vec3_t a, vec3_t b, vec3_t c, vec3_t out1, vec3_t out2, vec3_t out3) [static]
Referenced by CM_SubdivideGridColumns().
static void CM_SubdivideGridColumns (cGrid_t * grid) [static]
References CM_NeedsSubdivision(), CM_Subdivide(), cGrid_t::height, cGrid_t::points, VectorCopy, and cGrid_t::width.
Referenced by CM_GeneratePatchCollide().
void CM_TracePointThroughPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
References facet_t::borderInward, facet_t::borderPlanes, cm_playerCurveClip, Cvar_Get(), cplane_s::dist, DotProduct, traceWork_t::end, patchCollide_s::facets, trace_t::fraction, cvar_s::integer, traceWork_t::isPoint, MAX_PATCH_PLANES, cplane_s::normal, facet_t::numBorders, patchCollide_s::numFacets, patchCollide_s::numPlanes, traceWork_t::offsets, pc, patchPlane_t::plane, trace_t::plane, patchCollide_s::planes, planes, qfalse, qtrue, patchPlane_t::signbits, traceWork_t::start, SURFACE_CLIP_EPSILON, facet_t::surfacePlane, traceWork_t::trace, and VectorCopy.
Referenced by CM_TraceThroughPatchCollide().
void CM_TraceThroughPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
References facet_t::borderInward, facet_t::borderPlanes, patchCollide_s::bounds, traceWork_t::bounds, CM_BoundsIntersect(), CM_CheckFacetPlane(), CM_TracePointThroughPatchCollide(), Cvar_Get(), cplane_s::dist, DotProduct, traceWork_t::end, patchCollide_s::facets, trace_t::fraction, cvar_s::integer, traceWork_t::isPoint, cplane_s::normal, facet_t::numBorders, patchCollide_s::numFacets, sphere_t::offset, traceWork_t::offsets, pc, patchPlane_t::plane, trace_t::plane, patchCollide_s::planes, planes, sphere_t::radius, patchPlane_t::signbits, traceWork_t::sphere, traceWork_t::start, facet_t::surfacePlane, t, traceWork_t::trace, sphere_t::use, Vector4Copy, VectorAdd, VectorCopy, VectorNegate, and VectorSubtract.
Referenced by CM_TraceThroughPatch().
static void CM_TransposeGrid (cGrid_t * grid) [static]
References height, cGrid_t::height, cGrid_t::points, VectorCopy, width, cGrid_t::width, cGrid_t::wrapHeight, and cGrid_t::wrapWidth.
Referenced by CM_GeneratePatchCollide().
static qboolean CM_ValidateFacet (facet_t * facet) [static]
References BaseWindingForPlane(), facet_t::borderInward, facet_t::borderPlanes, patchCollide_s::bounds, ChopWindingInPlace(), FreeWinding(), MAX_MAP_BOUNDS, facet_t::numBorders, patchPlane_t::plane, qfalse, qtrue, facet_t::surfacePlane, vec3_origin, Vector4Copy, VectorSubtract, and WindingBounds().
Referenced by CM_PatchCollideFromGrid().
Variable Documentation
int c_totalPatchBlocks
Referenced by CM_GeneratePatchCollide().
int c_totalPatchEdges
int c_totalPatchSurfaces
qboolean debugBlock [static]
Referenced by CM_SetBorderInward().
vec3_t debugBlockPoints[4] [static]
Referenced by CM_DrawDebugSurface(), and CM_SetBorderInward().
const facet_t* debugFacet [static]
const patchCollide_t* debugPatchCollide [static]
Referenced by CM_DrawDebugSurface().
facet_t facets[MAX_PATCH_PLANES] [static]
int numFacets [static]
Referenced by CM_DrawDebugSurface(), and CM_PatchCollideFromGrid().
int numPlanes [static]
Referenced by CM_FindPlane(), CM_FindPlane2(), CM_PatchCollideFromGrid(), R_AddMarkFragments(), and R_MarkFragments().
patchPlane_t planes[MAX_PATCH_PLANES] [static]
Referenced by CM_PositionTestInPatchCollide(), CM_TracePointThroughPatchCollide(), CM_TraceThroughPatchCollide(), and PM_SlideMove().