ioquake3: code/tools/asm/cmdlib.c File Reference
cmdlib.c File Reference
#include "cmdlib.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
union _FloatByteUnion
Defines
#define BASEDIRNAME "quake"
#define PATHSEPERATOR '/'
#define MAX_EX_ARGC 1024
#define MAX_PATH 4096
#define CRC_INIT_VALUE 0xffff
#define CRC_XOR_VALUE 0x0000
Functions
void ExpandWildcards (int *argc, char ***argv)
void Error (const char *error,...)
void qprintf (const char *format,...)
void _printf (const char *format,...)
void SetQdirFromPath (const char *path)
char * ExpandArg (const char *path)
char * ExpandPath (const char *path)
char * ExpandGamePath (const char *path)
char * ExpandPathAndArchive (const char *path)
char * copystring (const char *s)
double I_FloatTime (void)
void Q_getwd (char *out)
void Q_mkdir (const char *path)
int FileTime (const char *path)
char * COM_Parse (char *data)
int Q_strncasecmp (const char *s1, const char *s2, int n)
int Q_stricmp (const char *s1, const char *s2)
char * strupr (char *start)
char * strlower (char *start)
int CheckParm (const char *check)
int Q_filelength (FILE *f)
static FILE * myfopen (const char *filename, const char *mode)
FILE * SafeOpenWrite (const char *filename)
FILE * SafeOpenRead (const char *filename)
void SafeRead (FILE *f, void *buffer, int count)
void SafeWrite (FILE *f, const void *buffer, int count)
qboolean FileExists (const char *filename)
int LoadFile (const char *filename, void **bufferptr)
int LoadFileBlock (const char *filename, void **bufferptr)
int TryLoadFile (const char *filename, void **bufferptr)
void SaveFile (const char *filename, const void *buffer, int count)
void DefaultExtension (char *path, const char *extension)
void DefaultPath (char *path, const char *basepath)
void StripFilename (char *path)
void StripExtension (char *path)
void ExtractFilePath (const char *path, char *dest)
void ExtractFileBase (const char *path, char *dest)
void ExtractFileExtension (const char *path, char *dest)
int ParseHex (const char *hex)
int ParseNum (const char *str)
short ShortSwap (short l)
int LongSwap (int l)
float FloatSwap (const float *f)
void CRC_Init (unsigned short *crcvalue)
void CRC_ProcessByte (unsigned short *crcvalue, byte data)
unsigned short CRC_Value (unsigned short crcvalue)
void CreatePath (const char *path)
void QCopyFile (const char *from, const char *to)
Variables
int myargc
char ** myargv
char com_token [1024]
qboolean com_eof
qboolean archive
char archivedir [1024]
int ex_argc
char * ex_argv [MAX_EX_ARGC]
qboolean verbose = qfalse
char qdir [1024]
char gamedir [1024]
char writedir [1024]
static unsigned short crctable [256]
Define Documentation
#define BASEDIRNAME "quake"
Referenced by SetQdirFromPath().
#define CRC_INIT_VALUE 0xffff
Referenced by CRC_Init().
#define CRC_XOR_VALUE 0x0000
Referenced by CRC_Value().
#define MAX_EX_ARGC 1024
#define MAX_PATH 4096
Referenced by myfopen().
#define PATHSEPERATOR '/'
Referenced by DefaultPath(), ExtractFileBase(), and StripFilename().
Function Documentation
void _printf (const char * format, ...)
References NULL, printf(), and qtrue.
Referenced by Error().
int CheckParm (const char * check)
References myargc, myargv, and Q_stricmp().
char* COM_Parse (char * data)
References com_eof, com_token, data, NULL, and qtrue.
char* copystring (const char * s)
References b.
Referenced by DefineSymbol(), main(), and ParseOptionFile().
void CRC_Init (unsigned short * crcvalue)
References CRC_INIT_VALUE.
void CRC_ProcessByte (unsigned short * crcvalue, byte data)
unsigned short CRC_Value (unsigned short crcvalue)
References CRC_XOR_VALUE.
void CreatePath (const char * path)
References Q_mkdir().
Referenced by QCopyFile(), and WriteVmFile().
void DefaultExtension (char * path, const char * extension)
References src.
Referenced by Assemble(), and ParseOptionFile().
void DefaultPath (char * path, const char * basepath)
References PATHSEPERATOR.
void Error (const char * error, ...)
References _printf().
Referenced by EmitByte(), EmitInt(), ExpandGamePath(), ExpandPath(), main(), ParseHex(), PC_CopyToken(), Q_mkdir(), SafeOpenRead(), SafeOpenWrite(), SafeRead(), SafeWrite(), SetQdirFromPath(), and ShowHelp().
char* ExpandArg (const char * path)
References Q_getwd().
char* ExpandGamePath (const char * path)
References Error(), gamedir, and qdir.
char* ExpandPath (const char * path)
References Error(), and qdir.
Referenced by ExpandPathAndArchive().
char* ExpandPathAndArchive (const char * path)
References archive, archivedir, ExpandPath(), and QCopyFile().
void ExpandWildcards (int * argc, char *** argv)
void ExtractFileBase (const char * path, char * dest)
References PATHSEPERATOR, and src.
void ExtractFileExtension (const char * path, char * dest)
References src.
void ExtractFilePath (const char * path, char * dest)
References src.
qboolean FileExists (const char * filename)
References fclose(), myfopen(), qfalse, and qtrue.
int FileTime (const char * path)
float FloatSwap (const float * f)
References _FloatByteUnion::f, _FloatByteUnion::i, LongSwap(), and out.
double I_FloatTime (void)
References t.
Referenced by main().
int LoadFile (const char * filename, void ** bufferptr)
References buffer, fclose(), length(), Q_filelength(), SafeOpenRead(), and SafeRead().
Referenced by Assemble(), ParseOptionFile(), and QCopyFile().
int LoadFileBlock (const char * filename, void ** bufferptr)
References buffer, fclose(), length(), MEM_BLOCKSIZE, Q_filelength(), SafeOpenRead(), and SafeRead().
int LongSwap (int l)
References b1, and b2.
Referenced by FloatSwap().
static FILE* myfopen (const char * filename, const char * mode) [static]
References MAX_PATH.
Referenced by FileExists(), SafeOpenRead(), SafeOpenWrite(), and TryLoadFile().
int ParseHex (const char * hex)
References Error().
int ParseNum (const char * str)
References ParseHex().
int Q_filelength (FILE * f)
References end, SEEK_END, and SEEK_SET.
Referenced by LoadFile(), LoadFileBlock(), and TryLoadFile().
void Q_getwd (char * out)
References NULL.
Referenced by ExpandArg(), and SetQdirFromPath().
void Q_mkdir (const char * path)
References Error().
Referenced by CreatePath().
int Q_stricmp (const char * s1, const char * s2)
References Q_stricmpn(), and Q_strncasecmp().
int Q_strncasecmp (const char * s1, const char * s2, int n)
Referenced by Q_stricmp(), and SetQdirFromPath().
void QCopyFile (const char * from, const char * to)
References buffer, CreatePath(), length(), LoadFile(), and SaveFile().
Referenced by ExpandPathAndArchive().
void qprintf (const char * format, ...)
References verbose.
Referenced by SetQdirFromPath().
FILE* SafeOpenRead (const char * filename)
References Error(), and myfopen().
Referenced by LoadFile(), and LoadFileBlock().
FILE* SafeOpenWrite (const char * filename)
References Error(), and myfopen().
Referenced by SaveFile(), WriteMapFile(), and WriteVmFile().
void SafeRead (FILE * f, void * buffer, int count)
References Error(), and fread().
Referenced by LoadFile(), LoadFileBlock(), and TryLoadFile().
void SafeWrite (FILE * f, const void * buffer, int count)
References Error(), and fwrite().
Referenced by SaveFile(), and WriteVmFile().
void SaveFile (const char * filename, const void * buffer, int count)
References fclose(), SafeOpenWrite(), and SafeWrite().
Referenced by QCopyFile().
void SetQdirFromPath (const char * path)
References BASEDIRNAME, count, Error(), gamedir, Q_getwd(), Q_strncasecmp(), qdir, qprintf(), and writedir.
short ShortSwap (short l)
References b1, and b2.
void StripExtension (char * path)
References length().
Referenced by WriteMapFile(), and WriteVmFile().
void StripFilename (char * path)
References length(), and PATHSEPERATOR.
char* strlower (char * start)
References in, and start.
char* strupr (char * start)
References in, and start.
int TryLoadFile (const char * filename, void ** bufferptr)
References buffer, fclose(), length(), myfopen(), NULL, Q_filelength(), and SafeRead().
Variable Documentation
qboolean archive
Referenced by ExpandPathAndArchive().
char archivedir[1024]
Referenced by ExpandPathAndArchive().
qboolean com_eof
Referenced by COM_Parse().
char com_token[1024]
unsigned short crctable[256] [static]
int ex_argc
char* ex_argv[MAX_EX_ARGC]
char gamedir[1024]
Referenced by ExpandGamePath(), Export_BotLibSetup(), SetQdirFromPath(), SVC_Info(), and Sys_ErrorDialog().
int myargc
Referenced by CheckParm().
char** myargv
Referenced by CheckParm().
char qdir[1024]
Referenced by ExpandGamePath(), ExpandPath(), and SetQdirFromPath().
qboolean verbose = qfalse
Referenced by callsys(), emitSymbol(), exists(), opt(), progbeg(), puttokens(), qprintf(), rm(), and setup().
char writedir[1024]
Referenced by SetQdirFromPath().