ioquake3: code/sys/con_tty.c File Reference
con_tty.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "sys_local.h"
#include "../client/client.h"
#include <unistd.h>
#include <signal.h>
#include <termios.h>
#include <fcntl.h>
#include <sys/time.h>
Defines
#define CON_HISTORY 32
#define TTY_CONSOLE_PROMPT "tty]"
Functions
static void CON_FlushIn (void)
static void CON_Back (void)
static void CON_Hide (void)
static void CON_Show (void)
void CON_Shutdown (void)
void Hist_Add (field_t *field)
field_t * Hist_Prev (void)
field_t * Hist_Next (void)
void CON_SigCont (int signum)
void CON_Init (void)
char * CON_Input (void)
void CON_Print (const char *msg)
Variables
qboolean stdinIsATTY
static qboolean stdin_active
static qboolean ttycon_on = qfalse
static int ttycon_hide = 0
static int ttycon_show_overdue = 0
static int TTY_erase
static int TTY_eof
static struct termios TTY_tc
static field_t TTY_con
static field_t ttyEditLines [CON_HISTORY]
static int hist_current = -1
static int hist_count = 0
Define Documentation
#define CON_HISTORY 32
Referenced by Hist_Add(), Hist_Next(), and Hist_Prev().
#define TTY_CONSOLE_PROMPT "tty]"
Referenced by CON_Hide(), CON_Input(), and CON_Show().
Function Documentation
static void CON_Back (void) [static]
References UNUSED_VAR.
Referenced by CON_Hide(), and CON_Input().
static void CON_FlushIn (void) [static]
Referenced by CON_Input().
static void CON_Hide (void) [static]
References CON_Back(), field_t::cursor, TTY_CONSOLE_PROMPT, ttycon_hide, and ttycon_on.
Referenced by CON_Input(), CON_Print(), and CON_Shutdown().
void CON_Init (void)
References Com_Printf(), CON_Show(), CON_SigCont(), Field_Clear(), qfalse, qtrue, stdin_active, stdinIsATTY, TTY_eof, TTY_erase, TTY_tc, ttycon_hide, and ttycon_on.
char* CON_Input (void)
References field_t::buffer, CA_ACTIVE, clc, Com_DPrintf(), Com_Printf(), Com_sprintf(), CON_Back(), CON_FlushIn(), CON_Hide(), CON_Show(), field_t::cursor, Field_AutoComplete(), Field_Clear(), Hist_Add(), Hist_Next(), Hist_Prev(), MAX_EDIT_LINE, memmove(), NULL, Q_strncpyz(), qfalse, clientConnection_t::state, stdin_active, TTY_CONSOLE_PROMPT, TTY_erase, ttycon_on, and UNUSED_VAR.
void CON_Print (const char * msg)
References com_ansiColor, CON_Hide(), CON_Show(), cvar_s::integer, Sys_AnsiColorPrint(), ttycon_on, and ttycon_show_overdue.
static void CON_Show (void) [static]
References field_t::buffer, field_t::cursor, TTY_CONSOLE_PROMPT, ttycon_hide, ttycon_on, and UNUSED_VAR.
Referenced by CON_Init(), CON_Input(), and CON_Print().
void CON_Shutdown (void)
References CON_Hide(), TTY_tc, and ttycon_on.
void CON_SigCont (int signum)
References CON_Init().
Referenced by CON_Init().
void Hist_Add (field_t * field)
References CON_HISTORY, field_t::cursor, field(), hist_count, and hist_current.
Referenced by CON_Input().
field_t* Hist_Next (void)
References CON_HISTORY, hist_count, hist_current, and NULL.
Referenced by CON_Input().
field_t* Hist_Prev (void)
References CON_HISTORY, hist_count, hist_current, and NULL.
Referenced by CON_Input().
Variable Documentation
int hist_count = 0 [static]
Referenced by Hist_Add(), Hist_Next(), and Hist_Prev().
int hist_current = -1 [static]
Referenced by Hist_Add(), Hist_Next(), and Hist_Prev().
qboolean stdin_active [static]
Referenced by CON_Init(), and CON_Input().
qboolean stdinIsATTY
Referenced by CON_Init(), Sys_PlatformInit(), and Sys_Sleep().
field_t TTY_con [static]
int TTY_eof [static]
Referenced by CON_Init().
int TTY_erase [static]
Referenced by CON_Init(), and CON_Input().
struct termios TTY_tc [static]
Referenced by CON_Init(), and CON_Shutdown().
int ttycon_hide = 0 [static]
Referenced by CON_Hide(), CON_Init(), and CON_Show().
qboolean ttycon_on = qfalse [static]
Referenced by CON_Hide(), CON_Init(), CON_Input(), CON_Print(), CON_Show(), and CON_Shutdown().
int ttycon_show_overdue = 0 [static]
Referenced by CON_Print().
field_t ttyEditLines[CON_HISTORY] [static]