ioquake3: code/libspeex/echo_diagnostic.m File Reference
echo_diagnostic.m File Reference
Functions
fclose (F)
zeros (1024, 1)]
end printf ("Far end to near end delay is %d samples\n", b)
if (b >.3 *tail_length) printf('This is too much delay
id n ()
else if (b< 0) printf('You have a negative delay
else printf ('Delay looks OK.\n')
printf ('Drift estimate is%f%%(%d samples)\n', 100 *drift, b1-b2)
if abs (b1-b2)< 10 printf('A drift of a few(+-10) samples is normal.\n')
else printf ('Your clock is drifting!No way the AEC will be able to do anything with that.Most likely, you''re doing capture and playback from two different cards.\n')
end end end acorr (1)
fwrite (F, out,'short')
Variables
Attempts to diagnose AEC
problems from recorded samples out
rec = fread(F,Inf,'short')
F = fopen(play_file,'rb')
play = fread(F,Inf,'short')
N = length(rec)
corr = real(ifft(fft(rec).*conj(fft(play))))
acorr = real(ifft(fft(play).*conj(fft(play))))
if b N b = max(corr) b-N
else the echo canceller has no
chance to cancel anything n
end end end N2 = round(N/2)
corr1 = real(ifft(fft(rec(1:N2)).*conj(fft(play(1:N2)))))
corr2 = real(ifft(fft(rec(N2+1:end)).*conj(fft(play(N2+1:end)))))
if b1 N2 b1 = max(corr1) b1-N2
end [a, b2] = max(corr2)
if b2 N2 b2 = b2-N2
end drift = (b1-b2)/N2
AtA = toeplitz(acorr(1:tail_length))
bb = corr(1:tail_length)
h = AtA\bb
Function Documentation
else if abs (b1- b2)
Referenced by AAS_AgainstLadder(), AAS_AltRoutingFloodCluster_r(), AAS_AreaGroundFace(), AAS_AreaGroundFaceArea(), AAS_AreaVolume(), AAS_CheckAreaForPossiblePortals(), AAS_ConnectedAreas_r(), AAS_FaceArea(), AAS_FaceCenter(), AAS_FindFaceReachabilities(), AAS_FloodAreas_r(), AAS_FloodClusterAreas_r(), AAS_GetAdjacentAreasWithLessPresenceTypes_r(), AAS_InsideFace(), AAS_NearestEntity(), AAS_Optimize(), AAS_OptimizeEdge(), AAS_OptimizeFace(), AAS_PointInsideFace(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Swim(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), AAS_ShowArea(), AAS_ShowAreaPolygons(), AAS_ShowFace(), AAS_ShowFacePolygon(), AAS_TraceEndFace(), BotChangeViewAngles(), BotInputToUserCommand(), BotTravel_Elevator(), CIN_RunCinematic(), CL_AdjustTimeDelta(), CL_CreateCmd(), emit_condjump(), HashString(), hashtable_add(), hashtable_get(), hashtable_symbol_exists(), IN_JoyMove(), Menu_TransitionItemByName(), PC_Directive_eval(), PC_DollarDirective_evalint(), PM_CmdScale(), PmoveSingle(), PredictPaeth(), and UI_StopCinematic().
end end end acorr (1)
fclose (F)
Referenced by fclose_file_func(), FileExists(), FS_FCloseFile(), FS_FileInPathExists(), FS_FOpenFileReadDir(), FS_Shutdown(), LoadFile(), LoadFileBlock(), LoadScriptFile(), LoadSourceFile(), Log_Close(), main(), main_init(), process(), SaveFile(), speex_echo_state_destroy(), stabend(), stabline(), Sys_RandomBytes(), Sys_WritePIDFile(), TryLoadFile(), VM_Compile(), WriteMapFile(), and WriteVmFile().
fwrite (F , out , 'short')
if (b , .3 * tail_length)
Referenced by AAS_ClosestEdgePoints(), AAS_FindFaceReachabilities(), alloc_large(), alloc_small(), arith_encode(), BotFindMatch(), BotLoadReplyChat(), BotMoveToGoal(), CG_AddScorePlum(), CG_CalcViewValues(), CG_DrawAreaPowerUp(), CG_PredictPlayerState(), CG_RunLerpFrame(), Con_DrawNotify(), consume_markers(), create_colorindex(), decode_mcu(), decode_mcu_AC_first(), decode_mcu_AC_refine(), decode_mcu_DC_first(), decode_mcu_DC_refine(), decode_mcu_sub(), empty_output_buffer(), encode_mcu(), encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), encode_mcu_DC_refine(), encode_mcu_gather(), finish_output_pass(), finish_pass(), finish_pass_gather(), finish_pass_huff(), free_pool(), hashtable_symbol_exists(), inflate(), inflateEnd(), inflateGetHeader(), inflatePrime(), inflateSetDictionary(), inflateSync(), Item_InitControls(), Item_ListBox_MouseEnter(), Item_Model_Paint(), Item_Multi_CountSettings(), Item_Multi_FindCvarByValue(), Item_Multi_HandleKey(), Item_Multi_Paint(), Item_Multi_Setting(), Item_Paint(), Item_SetFocus(), Item_SetTextExtents(), Item_Slider_Paint(), Item_TextField_HandleKey(), ItemParse_asset_model(), ItemParse_columns(), ItemParse_cvarFloat(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), ItemParse_doubleClick(), ItemParse_elementheight(), ItemParse_elementtype(), ItemParse_elementwidth(), ItemParse_model_angle(), ItemParse_model_fovx(), ItemParse_model_fovy(), ItemParse_model_origin(), ItemParse_model_rotation(), ItemParse_notselectable(), jinit_d_post_controller(), jpeg_make_c_derived_tbl(), jpeg_make_d_derived_tbl(), jpeg_mem_dest(), jpeg_new_colormap(), jpeg_set_marker_processor(), LoadConfig_MenuInit(), LookupSymbol(), MD5Update(), Menu_AdjustCursor(), Menu_Draw(), merged_2v_upsample(), METHODDEF(), post_process_1pass(), post_process_2pass(), post_process_prepass(), prepare_for_output_pass(), process_data_context_main(), process_data_simple_main(), process_restart(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_FixSharedVertexLodError(), R_FixSharedVertexLodError_r(), R_MovePatchSurfacesToHunk(), R_StitchAllPatches(), R_StitchPatches(), R_TryStitchingPatch(), RB_BeginSurface(), RB_SurfaceRailRings(), reachable(), request_virt_barray(), request_virt_sarray(), S_Base_RawSamples(), S_TransferPaintBuffer(), Scroll_ListBox_ThumbFunc(), ScrollList_Key(), sep_upsample(), smoothing_ok(), SNDDMA_Init(), speex_compute_agc(), speex_echo_playback(), speex_preprocess_run(), speex_preprocess_state_init(), start_iMCU_row(), start_output_pass(), start_pass(), start_pass_2_quant(), start_pass_coef(), start_pass_huff(), start_pass_huff_decoder(), start_pass_prep(), SV_ClipMoveToEntities(), term_destination(), UI_DrawAllMapsSelection(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_FeederSelection(), UI_MouseEvent(), UI_PushMenu(), UI_RunLerpFrame(), unzOpenCurrentFile3(), unzReadCurrentFile(), update_box(), updatewindow(), VM_Compile(), and write_scan_header().
else if ()
id n () [virtual]
end printf ("Far end to near end delay is %d samples\n" , b)
Referenced by _printf(), asm_instruction(), dumptree(), labelhash_free(), main(), print_vec(), pw(), ScriptError(), ScriptWarning(), SourceError(), SourceWarning(), Sys_EarlyOutput(), Sys_Error(), VM_CallCompiled(), and yyparse().
else printf ('Delay looks OK.\n')
printf ('Drift estimate is%f%%(%d samples)\n' , 100 * drift, b1- b2)
else printf ('Your clock is drifting!No way the AEC will be able to do anything with that.Most likely, you''re doing capture and playback from two different cards.\n')
zeros (1024 , 1)
Variable Documentation
acorr = real(ifft(fft(play).*conj(fft(play))))
AtA = toeplitz(acorr(1:tail_length))
if b N b = max(corr) b-N
if b1 N2 b1 = max(corr1) b1-N2
Referenced by AAS_ClosestEdgePoints(), BindingFromName(), cheb_poly_eva(), Controls_DrawKeyBinding(), LongSwap(), median_cut(), and ShortSwap().
if b2 N2 b2 = b2-N2
Referenced by AAS_ClosestEdgePoints(), BindingFromName(), Controls_DrawKeyBinding(), LongSwap(), median_cut(), and ShortSwap().
bb = corr(1:tail_length)
Referenced by DIV32_16(), paksort(), and PDIV32_16().
corr = real(ifft(fft(rec).*conj(fft(play))))
Referenced by interp_pitch(), and open_loop_nbest_pitch().
corr1 = real(ifft(fft(rec(1:N2)).*conj(fft(play(1:N2)))))
Referenced by multicomb().
corr2 = real(ifft(fft(rec(N2+1:end)).*conj(fft(play(N2+1:end)))))
end drift = (b1-b2)/N2
end[a, b2] = max(corr2)
Referenced by AAS_BestReachableArea(), AAS_CalculateAreaTravelTimes(), AAS_ClientMovementPrediction(), AAS_DrawCross(), AAS_DrawPermanentCross(), AAS_DropToFloor(), AAS_InitReachabilityAreas(), AAS_OnGround(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Teleport(), AAS_Reachability_WeaponJump(), AAS_ShowFace(), AAS_WeaponJumpZVelocity(), BotAimAtEnemy(), BotCheckAttack(), BotCheckBarrierJump(), BotCheckBlocked(), BotEntityVisible(), BotExportTest(), BotFinishTravel_WalkOffLedge(), BotFuncButtonActivateGoal(), BotFuzzyPointReachabilityArea(), BotGapDistance(), BotGetAirGoal(), BotGoalForBSPEntity(), BotInitLevelItems(), BotMovementViewTarget(), BotMoveToGoal(), BotOnMover(), BotOnTopOfEntity(), BotPointAreaNum(), BotPredictVisiblePosition(), BotReachabilityArea(), BotTravel_Jump(), BotTriggerMultipleActivateGoal(), BotValidChatPosition(), Bullet_Fire(), CG_PlayerShadow(), CG_PlayerSplash(), CG_ScanForCrosshairEntity(), CG_ShotgunPattern(), CG_Tracer(), CheckGauntletAttack(), CL_ParseBinding(), Com_TouchMemory(), filelength(), FileLength(), FS_fplength(), G_CheckProxMinePosition(), inflate_fast(), inflate_table(), main(), open_loop_nbest_pitch(), PM_SlideMove(), Q_filelength(), R_LerpTag(), R_LoadBMP(), R_LoadPCX(), R_LoadTGA(), R_Radix(), RB_ShowImages(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RE_StretchRaw(), rule(), S_PaintChannels(), ShotgunPattern(), speex_buffer_read(), speex_buffer_write(), speex_buffer_writezeros(), stringn(), target_laser_think(), Weapon_LightningFire(), and weapon_railgun_fire().
F = fopen(play_file,'rb')
h = AtA\bb
Referenced by Bitmap_Draw(), Bitmap_Init(), BotFreeChatState(), BotImport_BSPModelMinsMaxsOrigin(), CG_Draw3DModel(), CG_DrawCenterString(), CG_DrawCrosshair(), CG_DrawNewTeamInfo(), CG_DrawPlayerStatus(), CG_DrawSelectedPlayerStatus(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_OwnerDraw(), CG_StatusHandle(), CG_TeamBase(), CG_TileClear(), CG_TileClearBox(), CIN_DrawCinematic(), CIN_SetExtents(), CM_TestBoundingBoxInCapsule(), CM_TraceBoundingBoxThroughCapsule(), CM_TraceCapsuleThroughCapsule(), constant(), DecodeImageInterlaced(), DecodeImageNonInterlaced(), findlabel(), FS_filelength(), FS_ReadFileDir(), GLimp_DetectAvailableModes(), GraphicsOptions_ApplyChanges(), GraphicsOptions_GetAspectRatios(), hash(), hash_add_label(), install(), int_downsample(), int_upsample(), Item_Model_Paint(), Item_Paint(), labelhash_free(), lookup(), lookup_label(), Main_MenuDraw(), Menu_Draw(), MenuField_Init(), NET_OpenSocks(), PlayerSettings_SetMenuItems(), PText_Init(), R_LoadPCX(), R_RemapShader(), RB_ProjectionShadowDeform(), RB_ShowImages(), RB_SurfaceGrid(), RE_RegisterFont(), RE_StretchPic(), relocate(), S_Play_f(), SCR_DrawDebugGraph(), speex_init_header(), speex_packet_to_header(), StartServer_LevelshotDraw(), stringn(), SV_ClearWorld(), SV_SetBrushModel(), TeamplayInfoMessage(), Text_PaintChar(), type(), UI_DrawCenteredPic(), UI_DrawHandicap(), UI_DrawHandlePic(), UI_DrawPlayer(), UI_Handicap_HandleKey(), UI_OwnerDraw(), UI_OwnerDrawWidth(), UnfilterImage(), and VM_LoadQVM().
N = length(rec)
Referenced by compute_impulse_response(), filter_mem16(), filter_mem16_10(), filter_mem16_8(), fir_mem16(), fir_mem16_10(), fir_mem16_8(), iir_mem16(), iir_mem16_10(), iir_mem16_8(), kf_bfly2(), kf_bfly4(), kf_work(), mdf_adjust_prop(), open_loop_nbest_pitch(), pitch_search_3tap(), pitch_xcorr(), preprocess_analysis(), qmf_decomp(), resampler_basic_direct_double(), resampler_basic_direct_single(), resampler_basic_interpolate_double(), resampler_basic_interpolate_single(), spectral_mul_accum(), speex_compute_agc(), speex_decode_int(), speex_echo_cancellation(), speex_echo_get_residual(), speex_echo_state_init(), speex_echo_state_reset(), speex_encode_int(), speex_preprocess_estimate_update(), speex_preprocess_run(), speex_preprocess_state_init(), split_cb_search_shape_sign(), and update_noise_prob().
else the echo canceller has no chance to cancel anything n
Referenced by _spx_autocorr(), AAS_CalculateAreaTravelTimes(), AAS_ClientMovementPrediction(), AAS_CreateReversedReachability(), AAS_InitClustering(), AAS_PortalMaxTravelTime(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), AAS_ShowArea(), AddBotToSpawnQueue(), address(), addrtree(), adler32(), alloc(), allocate(), askfixedreg(), AssetCache(), bbvars(), BotAlreadySelected(), BotChooseInitialChatMessage(), BotLoadChatFile(), call(), CG_DrawLoadingIcons(), CG_MouseEvent(), CG_ProcessSnapshots(), CG_ShaderStateChanged(), CL_ClearPing(), CL_GetPing(), CM_DrawDebugSurface(), Com_HexStrToInt(), concat(), construct(), crc32_combine(), daub4(), dclr1(), definept(), drftb1(), drftf1(), drfti1(), emitstruct(), exitscope(), fillbuf(), funcdefn(), G_AddRandomBot(), G_CheckBotSpawn(), G_CountBotPlayers(), G_GetArenaInfoByMap(), G_GetBotInfoByName(), G_LoadArenas(), G_RemoveQueuedBotBegin(), gen(), genlabel(), get_dqt(), get_sos(), getd(), gettok(), gf2_matrix_square(), icon(), initarray(), initchar(), initfields(), initializer(), initstruct(), intconst(), intexpr(), ispow2(), Key_StringToKeynum(), kf_factor(), labelhash_free(), LAN_GetServerInfo(), LAN_GetServerPing(), LAN_GetServerPtr(), LAN_MarkServerVisible(), LAN_ServerIsVisible(), length(), listnodes(), mdfour_tail(), median_cut(), memmove(), mkactual(), mkreg(), outd(), parameters(), ParseDeform(), PlayerSettings_DrawName(), Preferences_Cache(), print(), printtoken(), program(), ProjectPointOnPlane(), R_FixSharedVertexLodError_r(), R_LoadIQM(), R_MarkFragments(), R_StitchPatches(), ReadWeightConfig(), reprune(), requate(), rtarget(), S_AdpcmEncodeSound(), scon(), segment(), ServerOptions_InitBotNames(), ServerOptions_InitPlayerItems(), ServerOptions_MenuInit(), ServerOptions_PlayerNameEvent(), ServerOptions_SetPlayerItems(), ServerOptions_Start(), setobjname(), simplify(), skipto(), space(), spawn(), speex_bits_advance(), spill(), split_cb_search_shape_sign(), spx_drft_init(), StartServer_LevelshotDraw(), stringd(), stringn(), suffix(), swgen(), target_location_linkup(), target_update(), tempname(), tokval(), UI_AddBotsMenu_GetSortedBotNums(), UI_AddBotsMenu_Init(), UI_AddBotsMenu_SetBotNames(), UI_BotSelectMenu_BuildList(), UI_BotSelectMenu_Default(), UI_BuildPlayerList(), UI_CinematicsMenu_Event(), UI_CinematicsMenu_f(), UI_DisplayDownloadInfo(), UI_GetArenaInfoByMap(), UI_GetArenaInfoByNumber(), UI_GetBestScore(), UI_GetBotInfoByName(), UI_GetSpecialArenaInfo(), UI_LoadArenas(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_Init(), UI_RemoveBotsMenu_SetBotNames(), UI_SPArena_Start(), UI_SPLevelMenu_AwardEvent(), UI_SPLevelMenu_Cache(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetMenuArena(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_Cache(), UI_SPPostgameMenu_DrawAwardsMedals(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_SPUnlockMedals_f(), UI_TeamOrdersMenu_BuildBotList(), UI_TierCompleted(), UpdateTournamentInfo(), vfprint(), visit(), wt1(), yylex(), and yyparse().
end end end N2 = round(N/2)
Referenced by qmf_synth().
out
Initial value:
 echo_diagnostic(rec_file, play_file, out_file, tail_length)
%
% Computes the full matrix inversion to cancel echo from the
% recording 'rec_file' using the far end signal 'play_file' using
% a filter length of 'tail_length'. The output is saved to 'out_file'.
function out = echo_diagnostic(rec_file, play_file, out_file, tail_length)
F=fopen(rec_file,'rb')
Referenced by assembler_set_output(), BotInterpolateCharacters(), BuildShaderStateConfig(), CG_InterpolatePlayerState(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadShaders(), CMod_LoadSubmodels(), COM_Compress(), Com_WriteCDKey(), CopyString(), decodeMuLaw(), decodeWavelet(), emit1(), encodeMuLaw(), encodeWavelet(), FloatSwap(), inflate(), inflate_fast(), inflateSync(), init_error_limit(), nb_decode(), NXPutc(), PC_String_Parse(), R_LoadFogs(), R_LoadJPG(), R_LoadLightmaps(), R_LoadMarksurfaces(), R_LoadNodesAndLeafs(), R_LoadPCX(), R_LoadPlanes(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_MipMap(), RE_RegisterFont(), RE_SaveJPG(), S_AdpcmEncodeSound(), S_AdpcmGetSamples(), S_Base_AddLoopingSound(), S_TransferPaintBuffer(), sb_decode(), Script_SetColor(), Script_SetItemColor(), String_Parse(), Text_Width(), and UI_RunMenuScript().
play = fread(F,Inf,'short')
rec = fread(F,Inf,'short')