ioquake3: code/libspeex/fftwrap.c File Reference
fftwrap.c File Reference
#include "arch.h"
#include "os_support.h"
#include "kiss_fftr.h"
#include "kiss_fft.h"
Data Structures
struct kiss_config
Defines
#define USE_KISS_FFT
#define MAX_FFT_SIZE 2048
Functions
void * spx_fft_init (int size)
void spx_fft_destroy (void *table)
void spx_fft (void *table, spx_word16_t *in, spx_word16_t *out)
void spx_ifft (void *table, spx_word16_t *in, spx_word16_t *out)
void spx_fft_float (void *table, float *in, float *out)
void spx_ifft_float (void *table, float *in, float *out)
Define Documentation
#define MAX_FFT_SIZE 2048
#define USE_KISS_FFT
Function Documentation
void spx_fft (void * table, spx_word16_t * in, spx_word16_t * out)
Forward (real to half-complex) transform
References kiss_config::forward, kiss_fftr2(), kiss_config::N, and t.
Referenced by preprocess_analysis(), speex_echo_cancellation(), speex_echo_get_residual(), and spx_fft_float().
void spx_fft_destroy (void * table)
Destroy tables for an FFT
References kiss_config::backward, kiss_config::forward, kiss_fftr_free, speex_free(), and t.
Referenced by speex_echo_state_destroy(), and speex_preprocess_state_destroy().
void spx_fft_float (void * table, float * in, float * out)
Forward (real to half-complex) transform of float data
References spx_fft().
void* spx_fft_init (int size)
Compute tables for an FFT
References kiss_config::backward, kiss_config::forward, kiss_fftr_alloc(), kiss_config::N, NULL, speex_alloc(), and table.
Referenced by speex_echo_state_init(), and speex_preprocess_state_init().
void spx_ifft (void * table, spx_word16_t * in, spx_word16_t * out)
Backward (half-complex to real) transform
References kiss_config::backward, kiss_fftri2(), and t.
Referenced by speex_echo_cancellation(), speex_preprocess_run(), and spx_ifft_float().
void spx_ifft_float (void * table, float * in, float * out)
Backward (half-complex to real) transform of float data
References spx_ifft().