ioquake3: code/libspeex/filters.h File Reference
filters.h File Reference
Various analysis/synthesis filters.
#include "arch.h"
Defines
#define HIGHPASS_NARROWBAND 0
#define HIGHPASS_WIDEBAND 2
#define HIGHPASS_INPUT 0
#define HIGHPASS_OUTPUT 1
#define HIGHPASS_IRS 4
Functions
spx_word16_t compute_rms (const spx_sig_t *x, int len)
spx_word16_t compute_rms16 (const spx_word16_t *x, int len)
void signal_mul (const spx_sig_t *x, spx_sig_t *y, spx_word32_t scale, int len)
void signal_div (const spx_word16_t *x, spx_word16_t *y, spx_word32_t scale, int len)
void highpass (const spx_word16_t *x, spx_word16_t *y, int len, int filtID, spx_mem_t *mem)
void qmf_decomp (const spx_word16_t *xx, const spx_word16_t *aa, spx_word16_t *, spx_word16_t *y2, int N, int M, spx_word16_t *mem, char *stack)
void qmf_synth (const spx_word16_t *x1, const spx_word16_t *x2, const spx_word16_t *a, spx_word16_t *y, int N, int M, spx_word16_t *mem1, spx_word16_t *mem2, char *stack)
void filter_mem16 (const spx_word16_t *x, const spx_coef_t *num, const spx_coef_t *den, spx_word16_t *y, int N, int ord, spx_mem_t *mem, char *stack)
void iir_mem16 (const spx_word16_t *x, const spx_coef_t *den, spx_word16_t *y, int N, int ord, spx_mem_t *mem, char *stack)
void fir_mem16 (const spx_word16_t *x, const spx_coef_t *num, spx_word16_t *y, int N, int ord, spx_mem_t *mem, char *stack)
void bw_lpc (spx_word16_t, const spx_coef_t *lpc_in, spx_coef_t *lpc_out, int order)
void sanitize_values32 (spx_word32_t *vec, spx_word32_t min_val, spx_word32_t max_val, int len)
void syn_percep_zero16 (const spx_word16_t *xx, const spx_coef_t *ak, const spx_coef_t *awk1, const spx_coef_t *awk2, spx_word16_t *y, int N, int ord, char *stack)
void residue_percep_zero16 (const spx_word16_t *xx, const spx_coef_t *ak, const spx_coef_t *awk1, const spx_coef_t *awk2, spx_word16_t *y, int N, int ord, char *stack)
void compute_impulse_response (const spx_coef_t *ak, const spx_coef_t *awk1, const spx_coef_t *awk2, spx_word16_t *y, int N, int ord, char *stack)
void multicomb (spx_word16_t *exc, spx_word16_t *new_exc, spx_coef_t *ak, int p, int nsf, int pitch, int max_pitch, spx_word16_t comb_gain, char *stack)
Detailed Description
Various analysis/synthesis filters.
Define Documentation
#define HIGHPASS_INPUT 0
Referenced by nb_encode().
#define HIGHPASS_IRS 4
#define HIGHPASS_NARROWBAND 0
Referenced by nb_decode(), nb_decode_lost(), and nb_encode().
#define HIGHPASS_OUTPUT 1
Referenced by nb_decode(), and nb_decode_lost().
#define HIGHPASS_WIDEBAND 2
Referenced by nb_decode(), and nb_encode().
Function Documentation
void bw_lpc (spx_word16_t , const spx_coef_t * lpc_in, spx_coef_t * lpc_out, int order)
References MULT16_16_P15.
Referenced by nb_decode(), nb_decode_lost(), nb_encode(), sb_decode_lost(), and sb_encode().
void compute_impulse_response (const spx_coef_t * ak, const spx_coef_t * awk1, const spx_coef_t * awk2, spx_word16_t * y, int N, int ord, char * stack)
References ADD16, ADD32, ALLOC, EXTEND32, EXTRACT16, LPC_SCALING, MAC16_16, MULT16_16, N, NEG16, PSHR32, SHL32, VARDECL, and VERY_SMALL.
Referenced by nb_encode(), and sb_encode().
spx_word16_t compute_rms (const spx_sig_t * x, int len)
Referenced by compute_rms16(), nb_encode(), and sb_encode().
spx_word16_t compute_rms16 (const spx_word16_t * x, int len)
References compute_rms().
Referenced by multicomb(), nb_decode(), nb_decode_lost(), nb_decoder_ctl(), nb_encode(), nb_encoder_ctl(), sb_decode(), and sb_encode().
void filter_mem16 (const spx_word16_t * x, const spx_coef_t * num, const spx_coef_t * den, spx_word16_t * y, int N, int ord, spx_mem_t * mem, char * stack)
References ADD32, ALLOC, EXTEND32, EXTRACT16, filter_mem16_10(), filter_mem16_8(), MAC16_16, MULT16_16, N, NEG16, PSHR32, SATURATE, and VARDECL.
Referenced by fir_mem16(), nb_encode(), pitch_gain_search_3tap(), residue_percep_zero16(), sb_encode(), and syn_percep_zero16().
void fir_mem16 (const spx_word16_t * x, const spx_coef_t * num, spx_word16_t * y, int N, int ord, spx_mem_t * mem, char * stack)
References ADD32, den, EXTEND32, EXTRACT16, filter_mem16(), fir_mem16_10(), fir_mem16_8(), MAC16_16, MULT16_16, N, PSHR32, and SATURATE.
Referenced by nb_encode(), residue_percep_zero16(), and sb_encode().
void highpass (const spx_word16_t * x, spx_word16_t * y, int len, int filtID, spx_mem_t * mem)
References ADD32, den, EXTRACT16, MAC16_16, MULT16_16, MULT16_32_Q15, PSHR32, SATURATE, and SHL32.
Referenced by nb_decode(), nb_decode_lost(), and nb_encode().
void iir_mem16 (const spx_word16_t * x, const spx_coef_t * den, spx_word16_t * y, int N, int ord, spx_mem_t * mem, char * stack)
References ADD32, ALLOC, EXTEND32, EXTRACT16, iir_mem16_10(), iir_mem16_8(), MAC16_16, MULT16_16, N, NEG16, PSHR32, SATURATE, VARDECL, and yy.
Referenced by nb_decode(), nb_decode_lost(), nb_encode(), pitch_gain_search_3tap(), sb_decode(), sb_decode_lost(), sb_encode(), and syn_percep_zero16().
void multicomb (spx_word16_t * exc, spx_word16_t * new_exc, spx_coef_t * ak, int p, int nsf, int pitch, int max_pitch, spx_word16_t comb_gain, char * stack)
References ABS, ABS16, ADD16, ADD32, ALLOC, compute_rms16(), corr1, EXTEND32, EXTRACT16, inner_prod(), interp_pitch(), MULT16_16, MULT16_16_Q13, MULT16_16_Q14, MULT16_16_Q15, open_loop_nbest_pitch(), PDIV32, PDIV32_16, PSHR16, PSHR32, QCONST16, SATURATE16, SHL16, SHL32, SHR16, spx_sqrt, and VARDECL.
Referenced by nb_decode().
void qmf_decomp (const spx_word16_t * xx, const spx_word16_t * aa, spx_word16_t * , spx_word16_t * y2, int N, int M, spx_word16_t * mem, char * stack)
References ADD16, ADD32, ALLOC, EXTRACT16, M, MULT16_16, N, PSHR32, SATURATE, SHR16, SUB16, SUB32, and VARDECL.
Referenced by sb_encode().
void qmf_synth (const spx_word16_t * x1, const spx_word16_t * x2, const spx_word16_t * a, spx_word16_t * y, int N, int M, spx_word16_t * mem1, spx_word16_t * mem2, char * stack)
References ADD32, ALLOC, EXTRACT16, MAC16_16, MULT16_16, N2, NEG16, PSHR32, SATURATE32, and VARDECL.
Referenced by sb_decode(), and sb_decode_lost().
void residue_percep_zero16 (const spx_word16_t * xx, const spx_coef_t * ak, const spx_coef_t * awk1, const spx_coef_t * awk2, spx_word16_t * y, int N, int ord, char * stack)
References ALLOC, filter_mem16(), fir_mem16(), and VARDECL.
Referenced by noise_codebook_quant().
void sanitize_values32 (spx_word32_t * vec, spx_word32_t min_val, spx_word32_t max_val, int len)
Referenced by nb_decode().
void signal_div (const spx_word16_t * x, spx_word16_t * y, spx_word32_t scale, int len)
Referenced by nb_encode(), and sb_encode().
void signal_mul (const spx_sig_t * x, spx_sig_t * y, spx_word32_t scale, int len)
Referenced by nb_decode(), nb_encode(), sb_decode(), and sb_encode().
void syn_percep_zero16 (const spx_word16_t * xx, const spx_coef_t * ak, const spx_coef_t * awk1, const spx_coef_t * awk2, spx_word16_t * y, int N, int ord, char * stack)
References ALLOC, filter_mem16(), iir_mem16(), and VARDECL.
Referenced by forced_pitch_quant(), split_cb_search_shape_sign(), and split_cb_search_shape_sign_N1().