ioquake3: code/libspeex/filters_sse.h File Reference
filters_sse.h File Reference
Various analysis/synthesis filters (SSE version)
#include <xmmintrin.h>
Defines
#define OVERRIDE_FILTER_MEM16
#define OVERRIDE_IIR_MEM16
#define OVERRIDE_FIR_MEM16
Functions
void filter_mem16_10 (const float *x, const float *_num, const float *_den, float *y, int N, int ord, float *_mem)
void filter_mem16_8 (const float *x, const float *_num, const float *_den, float *y, int N, int ord, float *_mem)
void filter_mem16 (const float *x, const float *_num, const float *_den, float *y, int N, int ord, float *_mem, char *stack)
void iir_mem16_10 (const float *x, const float *_den, float *y, int N, int ord, float *_mem)
void iir_mem16_8 (const float *x, const float *_den, float *y, int N, int ord, float *_mem)
void iir_mem16 (const float *x, const float *_den, float *y, int N, int ord, float *_mem, char *stack)
void fir_mem16_10 (const float *x, const float *_num, float *y, int N, int ord, float *_mem)
void fir_mem16_8 (const float *x, const float *_num, float *y, int N, int ord, float *_mem)
void fir_mem16 (const float *x, const float *_num, float *y, int N, int ord, float *_mem, char *stack)
Detailed Description
Various analysis/synthesis filters (SSE version)
Define Documentation
#define OVERRIDE_FILTER_MEM16
#define OVERRIDE_FIR_MEM16
#define OVERRIDE_IIR_MEM16
Function Documentation
void filter_mem16 (const float * x, const float * _num, const float * _den, float * y, int N, int ord, float * _mem, char * stack)
References ADD32, EXTEND32, EXTRACT16, filter_mem16_10(), filter_mem16_8(), MAC16_16, MULT16_16, N, NEG16, PSHR32, and SATURATE.
void filter_mem16_10 (const float * x, const float * _num, const float * _den, float * y, int N, int ord, float * _mem)
References den, N, xx, and yy.
Referenced by filter_mem16().
void filter_mem16_8 (const float * x, const float * _num, const float * _den, float * y, int N, int ord, float * _mem)
References den, N, xx, and yy.
Referenced by filter_mem16().
void fir_mem16 (const float * x, const float * _num, float * y, int N, int ord, float * _mem, char * stack)
References ADD32, EXTEND32, EXTRACT16, fir_mem16_10(), fir_mem16_8(), MAC16_16, MULT16_16, N, PSHR32, and SATURATE.
void fir_mem16_10 (const float * x, const float * _num, float * y, int N, int ord, float * _mem)
References N, xx, and yy.
Referenced by fir_mem16().
void fir_mem16_8 (const float * x, const float * _num, float * y, int N, int ord, float * _mem)
References N, xx, and yy.
Referenced by fir_mem16().
void iir_mem16 (const float * x, const float * _den, float * y, int N, int ord, float * _mem, char * stack)
References ADD32, EXTEND32, EXTRACT16, iir_mem16_10(), iir_mem16_8(), MAC16_16, MULT16_16, N, NEG16, PSHR32, and SATURATE.
void iir_mem16_10 (const float * x, const float * _den, float * y, int N, int ord, float * _mem)
References den, N, xx, and yy.
Referenced by iir_mem16().
void iir_mem16_8 (const float * x, const float * _den, float * y, int N, int ord, float * _mem)
References den, N, xx, and yy.
Referenced by iir_mem16().