ioquake3: code/game/g_main.c File Reference
g_main.c File Reference
#include "g_local.h"
Data Structures
struct cvarTable_t
Functions
void G_InitGame (int levelTime, int randomSeed, int restart)
void G_RunFrame (int levelTime)
void G_ShutdownGame (int restart)
void CheckExitRules (void)
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
void QDECL G_Printf (const char *fmt,...)
void QDECL G_Error (const char *fmt,...)
void G_FindTeams (void)
void G_RemapTeamShaders (void)
void G_RegisterCvars (void)
void G_UpdateCvars (void)
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
void AddTournamentPlayer (void)
void AddTournamentQueue (gclient_t *client)
void RemoveTournamentLoser (void)
void RemoveTournamentWinner (void)
void AdjustTournamentScores (void)
int QDECL SortRanks (const void *a, const void *b)
void CalculateRanks (void)
void SendScoreboardMessageToAllClients (void)
void MoveClientToIntermission (gentity_t *ent)
void FindIntermissionPoint (void)
void BeginIntermission (void)
void ExitLevel (void)
void QDECL G_LogPrintf (const char *fmt,...)
void LogExit (const char *string)
void CheckIntermissionExit (void)
qboolean ScoreIsTied (void)
void CheckTournament (void)
void CheckVote (void)
void PrintTeam (int team, char *message)
void SetLeader (int team, int client)
void CheckTeamLeader (int team)
void CheckTeamVote (int team)
void CheckCvars (void)
void G_RunThink (gentity_t *ent)
Variables
level_locals_t level
gentity_t g_entities [MAX_GENTITIES]
gclient_t g_clients [MAX_CLIENTS]
vmCvar_t g_gametype
vmCvar_t g_dmflags
vmCvar_t g_fraglimit
vmCvar_t g_timelimit
vmCvar_t g_capturelimit
vmCvar_t g_friendlyFire
vmCvar_t g_password
vmCvar_t g_needpass
vmCvar_t g_maxclients
vmCvar_t g_maxGameClients
vmCvar_t g_dedicated
vmCvar_t g_speed
vmCvar_t g_gravity
vmCvar_t g_cheats
vmCvar_t g_knockback
vmCvar_t g_quadfactor
vmCvar_t g_forcerespawn
vmCvar_t g_inactivity
vmCvar_t g_debugMove
vmCvar_t g_debugDamage
vmCvar_t g_debugAlloc
vmCvar_t g_weaponRespawn
vmCvar_t g_weaponTeamRespawn
vmCvar_t g_motd
vmCvar_t g_synchronousClients
vmCvar_t g_warmup
vmCvar_t g_doWarmup
vmCvar_t g_restarted
vmCvar_t g_logfile
vmCvar_t g_logfileSync
vmCvar_t g_blood
vmCvar_t g_podiumDist
vmCvar_t g_podiumDrop
vmCvar_t g_allowVote
vmCvar_t g_teamAutoJoin
vmCvar_t g_teamForceBalance
vmCvar_t g_banIPs
vmCvar_t g_filterBan
vmCvar_t g_smoothClients
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t g_rankings
vmCvar_t g_listEntity
static cvarTable_t gameCvarTable []
static int gameCvarTableSize = ARRAY_LEN(gameCvarTable)
Function Documentation
void AddTournamentPlayer (void)
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, level_locals_t::intermissiontime, level_locals_t::maxclients, NULL, level_locals_t::numPlayingClients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_SCOREBOARD, clientSession_t::spectatorClient, clientSession_t::spectatorNum, clientSession_t::spectatorState, TEAM_SPECTATOR, and level_locals_t::warmupTime.
Referenced by CheckTournament().
void AddTournamentQueue (gclient_t * client)
References level_locals_t::clients, CON_DISCONNECTED, clientPersistant_t::connected, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorNum, and TEAM_SPECTATOR.
Referenced by G_InitSessionData(), and SetTeam().
void AdjustTournamentScores (void)
References level_locals_t::clients, ClientUserinfoChanged(), CON_CONNECTED, clientPersistant_t::connected, clientSession_t::losses, gclient_s::pers, gclient_s::sess, level_locals_t::sortedClients, and clientSession_t::wins.
Referenced by BeginIntermission().
void BeginIntermission (void)
References AdjustTournamentScores(), ClientRespawn(), GT_SINGLE_PLAYER, GT_TOURNAMENT, gentity_s::health, vmCvar_t::integer, level_locals_t::intermissiontime, gentity_s::inuse, level_locals_t::maxclients, MoveClientToIntermission(), SendScoreboardMessageToAllClients(), SpawnModelsOnVictoryPads(), level_locals_t::time, trap_Cvar_Set(), and UpdateTournamentInfo().
Referenced by CheckExitRules(), and Cmd_LevelShot_f().
void CalculateRanks (void)
References ARRAY_LEN, CheckExitRules(), cl, level_locals_t::clients, CON_CONNECTED, CON_DISCONNECTED, clientPersistant_t::connected, CS_SCORES1, CS_SCORES2, level_locals_t::follow1, level_locals_t::follow2, GT_SINGLE_PLAYER, GT_TEAM, vmCvar_t::integer, level_locals_t::intermissiontime, level_locals_t::maxclients, level_locals_t::numConnectedClients, level_locals_t::numNonSpectatorClients, level_locals_t::numPlayingClients, level_locals_t::numteamVotingClients, level_locals_t::numVotingClients, gclient_s::pers, PERS_RANK, PERS_SCORE, playerState_s::persistant, gclient_s::ps, RANK_TIED_FLAG, SCORE_NOT_PRESENT, SendScoreboardMessageToAllClients(), gclient_s::sess, clientSession_t::sessionTeam, level_locals_t::sortedClients, SortRanks(), SVF_BOT, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::teamScores, trap_SetConfigstring(), and va().
Referenced by AddScore(), ClientBegin(), ClientConnect(), ClientDisconnect(), Team_TouchOurFlag(), and UpdateTournamentInfo().
void CheckCvars (void)
References vmCvar_t::modificationCount, Q_stricmp(), vmCvar_t::string, and trap_Cvar_Set().
Referenced by G_RunFrame().
void CheckExitRules (void)
References BeginIntermission(), CheckIntermissionExit(), cl, level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, GT_CTF, vmCvar_t::integer, INTERMISSION_DELAY_TIME, level_locals_t::intermissionQueued, level_locals_t::intermissiontime, LogExit(), clientPersistant_t::netname, level_locals_t::numPlayingClients, gclient_s::pers, PERS_SCORE, playerState_s::persistant, gclient_s::ps, S_COLOR_WHITE, ScoreIsTied(), gclient_s::sess, clientSession_t::sessionTeam, SP_INTERMISSION_DELAY_TIME, level_locals_t::startTime, TEAM_BLUE, TEAM_FREE, TEAM_RED, level_locals_t::teamScores, level_locals_t::time, trap_SendServerCommand(), va(), and level_locals_t::warmupTime.
Referenced by CalculateRanks(), and G_RunFrame().
void CheckIntermissionExit (void)
References cl, playerState_s::clientNum, level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, ExitLevel(), level_locals_t::exitTime, GT_SINGLE_PLAYER, vmCvar_t::integer, level_locals_t::intermissiontime, gclient_s::pers, gclient_s::ps, qfalse, qtrue, gentity_s::r, gclient_s::readyToExit, level_locals_t::readyToExit, STAT_CLIENTS_READY, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, and level_locals_t::time.
Referenced by CheckExitRules().
void CheckTeamLeader (int team)
References level_locals_t::clients, level_locals_t::maxclients, qtrue, gclient_s::sess, clientSession_t::sessionTeam, SVF_BOT, and clientSession_t::teamLeader.
Referenced by SetTeam().
void CheckTeamVote (int team)
References CS_TEAMVOTE_TIME, EXEC_APPEND, level_locals_t::numteamVotingClients, Q_strncmp(), SetLeader(), TEAM_BLUE, TEAM_RED, level_locals_t::teamVoteNo, level_locals_t::teamVoteString, level_locals_t::teamVoteTime, level_locals_t::teamVoteYes, level_locals_t::time, trap_SendConsoleCommand(), trap_SendServerCommand(), trap_SetConfigstring(), va(), and VOTE_TIME.
Referenced by G_RunFrame().
void CheckTournament (void)
References AddTournamentPlayer(), CS_WARMUP, EXEC_APPEND, G_LogPrintf(), GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, vmCvar_t::integer, vmCvar_t::modificationCount, level_locals_t::numPlayingClients, qfalse, qtrue, level_locals_t::restarted, TEAM_BLUE, TEAM_NUM_TEAMS, TEAM_RED, TeamCount(), level_locals_t::time, trap_Cvar_Set(), trap_SendConsoleCommand(), trap_SetConfigstring(), va(), level_locals_t::warmupModificationCount, and level_locals_t::warmupTime.
Referenced by G_RunFrame().
void CheckVote (void)
References CS_VOTE_TIME, EXEC_APPEND, level_locals_t::numVotingClients, level_locals_t::time, trap_SendConsoleCommand(), trap_SendServerCommand(), trap_SetConfigstring(), va(), VOTE_TIME, level_locals_t::voteExecuteTime, level_locals_t::voteNo, level_locals_t::voteString, level_locals_t::voteTime, and level_locals_t::voteYes.
Referenced by G_RunFrame().
void QDECL Com_Error (int level, const char * error, ...)
References G_Error(), and Q_vsnprintf.
void QDECL Com_Printf (const char * msg, ...)
References G_Printf(), and Q_vsnprintf.
void ExitLevel (void)
References BotInterbreedEndMatch(), level_locals_t::changemap, cl, level_locals_t::clients, CON_CONNECTED, CON_CONNECTING, clientPersistant_t::connected, EXEC_APPEND, G_WriteSessionData(), GT_TOURNAMENT, vmCvar_t::integer, level_locals_t::intermissiontime, MAX_STRING_CHARS, NULL, gclient_s::pers, PERS_SCORE, playerState_s::persistant, gclient_s::ps, Q_stricmp(), qtrue, RemoveTournamentLoser(), level_locals_t::restarted, TEAM_BLUE, TEAM_RED, level_locals_t::teamScores, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and trap_SendConsoleCommand().
Referenced by BotInterbreeding(), and CheckIntermissionExit().
void FindIntermissionPoint (void)
References entityState_s::angles, FOFS, G_Find(), G_PickTarget(), level_locals_t::intermission_angle, level_locals_t::intermission_origin, NULL, entityState_s::origin, qfalse, gentity_s::s, SelectSpawnPoint(), gentity_s::target, vec3_origin, vectoangles(), VectorCopy, and VectorSubtract.
Referenced by MoveClientToIntermission(), and SelectSpectatorSpawnPoint().
void QDECL G_Error (const char * fmt, ...)
References Q_vsnprintf, and trap_Error().
void G_FindTeams (void)
References FL_TEAMSLAVE, gentity_s::flags, G_Printf(), gentity_s::inuse, NULL, level_locals_t::num_entities, gentity_s::targetname, gentity_s::team, gentity_s::teamchain, and gentity_s::teammaster.
Referenced by G_InitGame().
void G_InitGame (int levelTime, int randomSeed, int restart)
References BotAILoadMap(), BotAISetup(), gentity_s::classname, ClearRegisteredItems(), gentity_s::client, level_locals_t::clients, FS_APPEND, FS_APPEND_SYNC, G_CheckTeamItems(), g_clients, g_entities, G_FindTeams(), G_InitBots(), G_InitMemory(), G_InitWorldSession(), G_LogPrintf(), G_ModelIndex(), G_Printf(), G_ProcessIPBans(), G_RegisterCvars(), G_RemapTeamShaders(), G_SoundIndex(), G_SpawnEntitiesFromString(), GAMEVERSION, level_locals_t::gentities, GT_SINGLE_PLAYER, GT_TEAM, InitBodyQue(), vmCvar_t::integer, level_locals_t::logFile, MAX_CLIENTS, MAX_GENTITIES, MAX_INFO_STRING, level_locals_t::maxclients, level_locals_t::num_entities, gclient_s::ps, SaveRegisteredItems(), level_locals_t::snd_fry, SP_PODIUM_MODEL, level_locals_t::startTime, vmCvar_t::string, level_locals_t::time, trap_Cvar_VariableIntegerValue(), trap_FS_FOpenFile(), trap_GetServerinfo(), and trap_LocateGameData().
Referenced by vmMain().
void QDECL G_LogPrintf (const char * fmt, ...)
References Com_sprintf(), G_Printf(), vmCvar_t::integer, level_locals_t::logFile, Q_vsnprintf, level_locals_t::startTime, level_locals_t::time, and trap_FS_Write().
void QDECL G_Printf (const char * fmt, ...)
References Q_vsnprintf, and trap_Printf().
void G_RegisterCvars (void)
References cvarTable_t::cvarFlags, cvarTable_t::cvarName, cvarTable_t::defaultString, G_Printf(), G_RemapTeamShaders(), gameCvarTableSize, GT_MAX_GAME_TYPE, vmCvar_t::integer, cvarTable_t::modificationCount, vmCvar_t::modificationCount, qfalse, qtrue, cvarTable_t::teamShader, trap_Cvar_Register(), trap_Cvar_Set(), cvarTable_t::vmCvar, and level_locals_t::warmupModificationCount.
Referenced by G_InitGame().
void G_RemapTeamShaders (void)
References AddRemap(), BuildShaderStateConfig(), Com_sprintf(), CS_SHADERSTATE, vmCvar_t::string, level_locals_t::time, and trap_SetConfigstring().
Referenced by G_InitGame(), G_RegisterCvars(), and G_UpdateCvars().
void G_RunFrame (int levelTime)
References CheckCvars(), CheckExitRules(), CheckTeamStatus(), CheckTeamVote(), CheckTournament(), CheckVote(), gentity_s::client, ClientEndFrame(), ET_ITEM, ET_MISSILE, ET_MOVER, entityState_s::eType, entityState_s::event, EVENT_VALID_MSEC, gentity_s::eventTime, playerState_s::externalEvent, level_locals_t::framenum, gentity_s::freeAfterEvent, G_FreeEntity(), G_Printf(), G_RunClient(), G_RunItem(), G_RunMissile(), G_RunMover(), G_RunThink(), G_UpdateCvars(), vmCvar_t::integer, gentity_s::inuse, entityShared_t::linked, MAX_CLIENTS, MAX_GENTITIES, level_locals_t::maxclients, gentity_s::neverFree, level_locals_t::num_entities, gentity_s::physicsObject, level_locals_t::previousTime, gclient_s::ps, qfalse, gentity_s::r, level_locals_t::restarted, gentity_s::s, TEAM_BLUE, TEAM_RED, level_locals_t::time, trap_Cvar_Set(), trap_UnlinkEntity(), and gentity_s::unlinkAfterEvent.
Referenced by vmMain().
void G_RunThink (gentity_t * ent)
References G_Error(), gentity_s::nextthink, gentity_s::think, and level_locals_t::time.
Referenced by G_RunFrame(), G_RunItem(), G_RunMissile(), and G_RunMover().
void G_ShutdownGame (int restart)
References BotAIShutdown(), G_LogPrintf(), G_Printf(), G_WriteSessionData(), level_locals_t::logFile, trap_Cvar_VariableIntegerValue(), and trap_FS_FCloseFile().
Referenced by vmMain().
void G_UpdateCvars (void)
References cvarTable_t::cvarName, G_RemapTeamShaders(), gameCvarTableSize, cvarTable_t::modificationCount, vmCvar_t::modificationCount, qfalse, qtrue, vmCvar_t::string, cvarTable_t::teamShader, cvarTable_t::trackChange, trap_Cvar_Update(), trap_SendServerCommand(), va(), and cvarTable_t::vmCvar.
Referenced by G_RunFrame().
void LogExit (const char * string)
References cl, level_locals_t::clients, CON_CONNECTING, clientPersistant_t::connected, CS_INTERMISSION, EXEC_APPEND, G_LogPrintf(), GT_CTF, GT_TEAM, GT_TOURNAMENT, vmCvar_t::integer, level_locals_t::intermissionQueued, clientPersistant_t::netname, level_locals_t::numConnectedClients, gclient_s::pers, PERS_RANK, PERS_SCORE, playerState_s::persistant, playerState_s::ping, gclient_s::ps, qfalse, qtrue, gentity_s::r, gclient_s::sess, clientSession_t::sessionTeam, level_locals_t::sortedClients, SVF_BOT, entityShared_t::svFlags, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::teamScores, level_locals_t::time, trap_SendConsoleCommand(), and trap_SetConfigstring().
Referenced by CheckExitRules().
void MoveClientToIntermission (gentity_t * ent)
References gentity_s::client, entityShared_t::contents, playerState_s::eFlags, entityState_s::eFlags, ET_GENERAL, entityState_s::eType, entityState_s::event, FindIntermissionPoint(), level_locals_t::intermission_angle, level_locals_t::intermission_origin, entityState_s::loopSound, entityState_s::modelindex, playerState_s::origin, entityState_s::origin, PM_INTERMISSION, playerState_s::pm_type, playerState_s::powerups, gclient_s::ps, gentity_s::r, gentity_s::s, gclient_s::sess, SPECTATOR_FOLLOW, clientSession_t::spectatorState, StopFollowing(), VectorCopy, and playerState_s::viewangles.
Referenced by BeginIntermission(), and ClientSpawn().
void PrintTeam (int team, char * message)
References level_locals_t::clients, level_locals_t::maxclients, gclient_s::sess, clientSession_t::sessionTeam, and trap_SendServerCommand().
Referenced by SetLeader().
void RemoveTournamentLoser (void)
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, level_locals_t::numPlayingClients, gclient_s::pers, SetTeam(), and level_locals_t::sortedClients.
Referenced by ExitLevel().
void RemoveTournamentWinner (void)
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, level_locals_t::numPlayingClients, gclient_s::pers, SetTeam(), and level_locals_t::sortedClients.
qboolean ScoreIsTied (void)
References b, level_locals_t::clients, GT_TEAM, vmCvar_t::integer, level_locals_t::numPlayingClients, PERS_SCORE, playerState_s::persistant, gclient_s::ps, qfalse, level_locals_t::sortedClients, TEAM_BLUE, TEAM_RED, and level_locals_t::teamScores.
Referenced by CheckExitRules().
void SendScoreboardMessageToAllClients (void)
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, DeathmatchScoreboardMessage(), level_locals_t::maxclients, and gclient_s::pers.
Referenced by BeginIntermission(), and CalculateRanks().
void SetLeader (int team, int client)
References level_locals_t::clients, ClientUserinfoChanged(), CON_DISCONNECTED, clientPersistant_t::connected, level_locals_t::maxclients, clientPersistant_t::netname, gclient_s::pers, PrintTeam(), qfalse, qtrue, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::teamLeader, and va().
Referenced by CheckTeamVote(), and SetTeam().
int QDECL SortRanks (const void * a, const void * b)
References level_locals_t::clients, CON_CONNECTING, clientPersistant_t::connected, gclient_s::pers, PERS_SCORE, playerState_s::persistant, gclient_s::ps, gclient_s::sess, clientSession_t::sessionTeam, SPECTATOR_SCOREBOARD, clientSession_t::spectatorClient, clientSession_t::spectatorNum, clientSession_t::spectatorState, and TEAM_SPECTATOR.
Referenced by CalculateRanks().
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
References BOTAI_START_FRAME, BotAIStartFrame(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientThink(), ClientUserinfoChanged(), ConsoleCommand(), G_InitGame(), G_RunFrame(), G_ShutdownGame(), GAME_CLIENT_BEGIN, GAME_CLIENT_COMMAND, GAME_CLIENT_CONNECT, GAME_CLIENT_DISCONNECT, GAME_CLIENT_THINK, GAME_CLIENT_USERINFO_CHANGED, GAME_CONSOLE_COMMAND, GAME_INIT, GAME_RUN_FRAME, GAME_SHUTDOWN, and intptr_t().
Variable Documentation
vmCvar_t g_allowVote
Referenced by Cmd_CallTeamVote_f(), and Cmd_CallVote_f().
vmCvar_t g_banIPs
Referenced by G_ProcessIPBans().
vmCvar_t g_blood
Referenced by body_die(), and player_die().
vmCvar_t g_capturelimit
vmCvar_t g_cheats
Referenced by CheatsOk(), and Cmd_SetViewpos_f().
gclient_t g_clients[MAX_CLIENTS]
Referenced by G_InitGame().
vmCvar_t g_debugAlloc
Referenced by G_Alloc().
vmCvar_t g_debugDamage
Referenced by G_Damage().
vmCvar_t g_debugMove
Referenced by ClientThink_real().
vmCvar_t g_dedicated
Referenced by ConsoleCommand(), G_Say(), and G_Voice().
vmCvar_t g_dmflags
Referenced by ClientEvents(), and ClientThink_real().
vmCvar_t g_doWarmup
Referenced by SP_worldspawn().
gentity_t g_entities[MAX_GENTITIES]
Referenced by __attribute__(), BotAI_GetClientState(), BotAI_GetEntityState(), BotAIStartFrame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChatTest(), BotCheckAttack(), BotCheckEvents(), BotModelMinsMaxs(), BotSetEntityNumForGoal(), BotSetEntityNumForGoalWithModel(), Bullet_Fire(), CheatsOk(), CheckGauntletAttack(), CheckTeamStatus(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientImpacts(), ClientNumberFromString(), ClientSpawn(), ClientThink(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_God_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_VoiceTaunt_f(), Cmd_VoiceTell_f(), Cmd_Vote_f(), Cmd_Where_f(), CopyToBodyQue(), DeathmatchScoreboardMessage(), FindHumanTeamLeader(), G_AddBot(), G_AddRandomBot(), G_CountBotPlayers(), G_CountHumanPlayers(), G_Damage(), G_EntitiesFree(), G_ExplodeMissile(), G_Find(), G_InitGame(), G_InitGentity(), G_KillBox(), G_MissileImpact(), G_MoverPush(), G_RadiusDamage(), G_RankClientDisconnect(), G_RankDamage(), G_RankRunFrame(), G_RankWeaponTime(), G_RemoveRandomBot(), G_Say(), G_SayTo(), G_Spawn(), G_TestEntityPosition(), G_TouchTriggers(), G_Voice(), G_VoiceTo(), GibEntity(), player_die(), SetTeam(), ShotgunPellet(), SP_worldspawn(), SpawnModelOnVictoryPad(), SpawnModelsOnVictoryPads(), SpawnPodium(), SpotWouldTelefrag(), StopFollowing(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), target_laser_think(), target_location_linkup(), Team_ForceGesture(), Team_FragBonuses(), Team_TouchOurFlag(), TeamplayInfoMessage(), UpdateTournamentInfo(), Use_Target_Print(), Weapon_LightningFire(), and weapon_railgun_fire().
vmCvar_t g_filterBan
Referenced by G_FilterPacket().
vmCvar_t g_forcerespawn
Referenced by ClientThink_real().
vmCvar_t g_fraglimit
Referenced by G_RankRunFrame().
vmCvar_t g_friendlyFire
Referenced by G_Damage().
vmCvar_t g_gametype
vmCvar_t g_gravity
Referenced by AimAtTarget(), ClientThink_real(), and SP_func_pendulum().
vmCvar_t g_inactivity
Referenced by ClientInactivityTimer(), and ClientSpawn().
vmCvar_t g_knockback
Referenced by G_Damage().
vmCvar_t g_listEntity
vmCvar_t g_logfile
vmCvar_t g_logfileSync
vmCvar_t g_maxclients
Referenced by CheckTeamStatus(), G_AddRandomBot(), G_CheckMinimumPlayers(), G_CountBotPlayers(), G_CountHumanPlayers(), G_RemoveRandomBot(), Team_FragBonuses(), Team_TouchOurFlag(), and TeamplayInfoMessage().
vmCvar_t g_maxGameClients
Referenced by G_InitSessionData(), and SetTeam().
vmCvar_t g_motd
Referenced by SP_worldspawn().
vmCvar_t g_needpass
vmCvar_t g_password
Referenced by ClientConnect().
vmCvar_t g_podiumDist
vmCvar_t g_podiumDrop
vmCvar_t g_quadfactor
Referenced by CheckGauntletAttack(), and FireWeapon().
vmCvar_t g_rankings
vmCvar_t g_restarted
Referenced by SP_worldspawn().
vmCvar_t g_smoothClients
Referenced by ClientEndFrame(), and ClientThink_real().
vmCvar_t g_speed
Referenced by ClientThink_real().
vmCvar_t g_synchronousClients
Referenced by ClientEndFrame(), ClientThink(), and G_RunClient().
vmCvar_t g_teamAutoJoin
Referenced by G_InitSessionData().
vmCvar_t g_teamForceBalance
Referenced by SetTeam().
vmCvar_t g_timelimit
Referenced by G_RankRunFrame().
vmCvar_t g_warmup
vmCvar_t g_weaponRespawn
Referenced by Pickup_Weapon().
vmCvar_t g_weaponTeamRespawn
Referenced by Pickup_Weapon().
cvarTable_t gameCvarTable[] [static]
int gameCvarTableSize = ARRAY_LEN(gameCvarTable) [static]
Referenced by G_RegisterCvars(), and G_UpdateCvars().
level_locals_t level
vmCvar_t pmove_fixed
Referenced by CG_PredictPlayerState(), and ClientThink_real().
vmCvar_t pmove_msec
Referenced by CG_PredictPlayerState(), and ClientThink_real().