ioquake3: code/game/g_rankings.c File Reference
g_rankings.c File Reference
#include "g_local.h"
#include "g_rankings.h"
Functions
void G_RankRunFrame ()
void G_RankFireWeapon (int self, int weapon)
void G_RankDamage (int self, int attacker, int damage, int means_of_death)
void G_RankPlayerDie (int self, int attacker, int means_of_death)
void G_RankWeaponTime (int self, int weapon)
void G_RankPickupWeapon (int self, int weapon)
void G_RankPickupAmmo (int self, int weapon, int quantity)
void G_RankPickupHealth (int self, int quantity)
void G_RankPickupArmor (int self, int quantity)
void G_RankPickupPowerup (int self, int powerup)
void G_RankPickupHoldable (int self, int holdable)
void G_RankUseHoldable (int self, int holdable)
void G_RankReward (int self, int award)
void G_RankCapture (int self)
void G_RankUserTeamName (int self, char *team_name)
void G_RankClientDisconnect (int self)
void G_RankGameOver (void)
Function Documentation
void G_RankCapture (int self)
References level, QGR_KEY_FLAG_CAPTURE, and level_locals_t::warmupTime.
void G_RankClientDisconnect (int self)
References gentity_s::client, clientPersistant_t::enterTime, g_entities, level, gclient_s::pers, playerState_s::persistant, gclient_s::ps, QGR_KEY_MATCH_RATING, level_locals_t::time, and level_locals_t::warmupTime.
Referenced by G_RankGameOver().
void G_RankDamage (int self, int attacker, int damage, int means_of_death)
References gentity_s::client, ENTITYNUM_WORLD, level_locals_t::framenum, g_entities, level, MOD_BFG, MOD_BFG_SPLASH, MOD_CRUSH, MOD_FALLING, MOD_GAUNTLET, MOD_GRAPPLE, MOD_GRENADE, MOD_GRENADE_SPLASH, MOD_LAVA, MOD_LIGHTNING, MOD_MACHINEGUN, MOD_PLASMA, MOD_PLASMA_SPLASH, MOD_RAILGUN, MOD_ROCKET, MOD_ROCKET_SPLASH, MOD_SHOTGUN, MOD_SLIME, MOD_SUICIDE, MOD_TELEFRAG, MOD_TRIGGER_HURT, MOD_UNKNOWN, MOD_WATER, OnSameTeam(), QGR_KEY_DAMAGE_GIVEN, QGR_KEY_DAMAGE_GIVEN_BFG, QGR_KEY_DAMAGE_GIVEN_GAUNTLET, QGR_KEY_DAMAGE_GIVEN_GRAPPLE, QGR_KEY_DAMAGE_GIVEN_GRENADE, QGR_KEY_DAMAGE_GIVEN_LIGHTNING, QGR_KEY_DAMAGE_GIVEN_MACHINEGUN, QGR_KEY_DAMAGE_GIVEN_PLASMA, QGR_KEY_DAMAGE_GIVEN_RAILGUN, QGR_KEY_DAMAGE_GIVEN_ROCKET, QGR_KEY_DAMAGE_GIVEN_SHOTGUN, QGR_KEY_DAMAGE_GIVEN_UNKNOWN, QGR_KEY_DAMAGE_TAKEN, QGR_KEY_DAMAGE_TAKEN_BFG, QGR_KEY_DAMAGE_TAKEN_GAUNTLET, QGR_KEY_DAMAGE_TAKEN_GRAPPLE, QGR_KEY_DAMAGE_TAKEN_GRENADE, QGR_KEY_DAMAGE_TAKEN_LIGHTNING, QGR_KEY_DAMAGE_TAKEN_MACHINEGUN, QGR_KEY_DAMAGE_TAKEN_PLASMA, QGR_KEY_DAMAGE_TAKEN_RAILGUN, QGR_KEY_DAMAGE_TAKEN_ROCKET, QGR_KEY_DAMAGE_TAKEN_SHOTGUN, QGR_KEY_DAMAGE_TAKEN_UNKNOWN, QGR_KEY_HIT_GIVEN, QGR_KEY_HIT_GIVEN_BFG, QGR_KEY_HIT_GIVEN_GAUNTLET, QGR_KEY_HIT_GIVEN_GRAPPLE, QGR_KEY_HIT_GIVEN_GRENADE, QGR_KEY_HIT_GIVEN_LIGHTNING, QGR_KEY_HIT_GIVEN_MACHINEGUN, QGR_KEY_HIT_GIVEN_PLASMA, QGR_KEY_HIT_GIVEN_RAILGUN, QGR_KEY_HIT_GIVEN_ROCKET, QGR_KEY_HIT_GIVEN_SHOTGUN, QGR_KEY_HIT_GIVEN_UNKNOWN, QGR_KEY_HIT_TAKEN, QGR_KEY_HIT_TAKEN_BFG, QGR_KEY_HIT_TAKEN_GAUNTLET, QGR_KEY_HIT_TAKEN_GRAPPLE, QGR_KEY_HIT_TAKEN_GRENADE, QGR_KEY_HIT_TAKEN_LIGHTNING, QGR_KEY_HIT_TAKEN_MACHINEGUN, QGR_KEY_HIT_TAKEN_PLASMA, QGR_KEY_HIT_TAKEN_RAILGUN, QGR_KEY_HIT_TAKEN_ROCKET, QGR_KEY_HIT_TAKEN_SHOTGUN, QGR_KEY_HIT_TAKEN_UNKNOWN, QGR_KEY_SHOT_FIRED_GAUNTLET, QGR_KEY_SPLASH_GIVEN, QGR_KEY_SPLASH_GIVEN_BFG, QGR_KEY_SPLASH_GIVEN_GRENADE, QGR_KEY_SPLASH_GIVEN_PLASMA, QGR_KEY_SPLASH_GIVEN_ROCKET, QGR_KEY_SPLASH_TAKEN, QGR_KEY_SPLASH_TAKEN_BFG, QGR_KEY_SPLASH_TAKEN_GRENADE, QGR_KEY_SPLASH_TAKEN_PLASMA, QGR_KEY_SPLASH_TAKEN_ROCKET, QGR_KEY_TEAMMATE_DAMAGE_GIVEN, QGR_KEY_TEAMMATE_DAMAGE_TAKEN, QGR_KEY_TEAMMATE_HIT_GIVEN, QGR_KEY_TEAMMATE_HIT_TAKEN, QGR_KEY_TEAMMATE_SPLASH_GIVEN, QGR_KEY_TEAMMATE_SPLASH_TAKEN, and level_locals_t::warmupTime.
void G_RankFireWeapon (int self, int weapon)
References level, QGR_KEY_SHOT_FIRED, QGR_KEY_SHOT_FIRED_BFG, QGR_KEY_SHOT_FIRED_GRAPPLE, QGR_KEY_SHOT_FIRED_GRENADE, QGR_KEY_SHOT_FIRED_LIGHTNING, QGR_KEY_SHOT_FIRED_MACHINEGUN, QGR_KEY_SHOT_FIRED_PLASMA, QGR_KEY_SHOT_FIRED_RAILGUN, QGR_KEY_SHOT_FIRED_ROCKET, QGR_KEY_SHOT_FIRED_SHOTGUN, level_locals_t::warmupTime, WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
void G_RankGameOver (void)
References G_RankClientDisconnect(), level, MAX_INFO_VALUE, level_locals_t::maxclients, QGR_KEY_DEDICATED, QGR_KEY_FRAGLIMIT, QGR_KEY_GAMETYPE, QGR_KEY_HOSTNAME, QGR_KEY_MAP, QGR_KEY_MAXCLIENTS, QGR_KEY_MAXPING, QGR_KEY_MAXRATE, QGR_KEY_MINPING, QGR_KEY_MOD, QGR_KEY_TIMELIMIT, QGR_KEY_VERSION, trap_Cvar_VariableIntegerValue(), trap_Cvar_VariableStringBuffer(), and level_locals_t::warmupTime.
void G_RankPickupAmmo (int self, int weapon, int quantity)
References level, QGR_KEY_BOXES, QGR_KEY_BOXES_BFG_AMMO, QGR_KEY_BOXES_BULLETS, QGR_KEY_BOXES_CELLS, QGR_KEY_BOXES_GRENADES, QGR_KEY_BOXES_LG_AMMO, QGR_KEY_BOXES_ROCKETS, QGR_KEY_BOXES_SHELLS, QGR_KEY_BOXES_SLUGS, QGR_KEY_ROUNDS, QGR_KEY_ROUNDS_BFG_AMMO, QGR_KEY_ROUNDS_BULLETS, QGR_KEY_ROUNDS_CELLS, QGR_KEY_ROUNDS_GRENADES, QGR_KEY_ROUNDS_LG_AMMO, QGR_KEY_ROUNDS_ROCKETS, QGR_KEY_ROUNDS_SHELLS, QGR_KEY_ROUNDS_SLUGS, level_locals_t::warmupTime, WP_BFG, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
void G_RankPickupArmor (int self, int quantity)
References level, QGR_KEY_ARMOR, QGR_KEY_ARMOR_RED, QGR_KEY_ARMOR_SHARD, QGR_KEY_ARMOR_TOTAL, QGR_KEY_ARMOR_YELLOW, and level_locals_t::warmupTime.
void G_RankPickupHealth (int self, int quantity)
References level, QGR_KEY_HEALTH, QGR_KEY_HEALTH_25, QGR_KEY_HEALTH_5, QGR_KEY_HEALTH_50, QGR_KEY_HEALTH_MEGA, QGR_KEY_HEALTH_TOTAL, and level_locals_t::warmupTime.
void G_RankPickupHoldable (int self, int holdable)
References HI_MEDKIT, HI_TELEPORTER, level, QGR_KEY_MEDKIT, QGR_KEY_TELEPORTER, and level_locals_t::warmupTime.
void G_RankPickupPowerup (int self, int powerup)
References level, PW_BATTLESUIT, PW_BLUEFLAG, PW_FLIGHT, PW_HASTE, PW_INVIS, PW_QUAD, PW_REDFLAG, PW_REGEN, QGR_KEY_FLAG_PICKUP, QGR_KEY_FLIGHT, QGR_KEY_HASTE, QGR_KEY_INVIS, QGR_KEY_POWERUP, QGR_KEY_QUAD, QGR_KEY_REGEN, QGR_KEY_SUIT, and level_locals_t::warmupTime.
void G_RankPickupWeapon (int self, int weapon)
References level, QGR_KEY_PICKUP_BFG, QGR_KEY_PICKUP_GAUNTLET, QGR_KEY_PICKUP_GRAPPLE, QGR_KEY_PICKUP_GRENADE, QGR_KEY_PICKUP_LIGHTNING, QGR_KEY_PICKUP_MACHINEGUN, QGR_KEY_PICKUP_PLASMA, QGR_KEY_PICKUP_RAILGUN, QGR_KEY_PICKUP_ROCKET, QGR_KEY_PICKUP_SHOTGUN, QGR_KEY_PICKUP_WEAPON, level_locals_t::warmupTime, WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
void G_RankPlayerDie (int self, int attacker, int means_of_death)
References ENTITYNUM_WORLD, level, MOD_BFG, MOD_BFG_SPLASH, MOD_CRUSH, MOD_FALLING, MOD_GAUNTLET, MOD_GRAPPLE, MOD_GRENADE, MOD_GRENADE_SPLASH, MOD_LAVA, MOD_LIGHTNING, MOD_MACHINEGUN, MOD_PLASMA, MOD_PLASMA_SPLASH, MOD_RAILGUN, MOD_ROCKET, MOD_ROCKET_SPLASH, MOD_SHOTGUN, MOD_SLIME, MOD_SUICIDE, MOD_TELEFRAG, MOD_TRIGGER_HURT, MOD_WATER, QGR_KEY_CRUSH, QGR_KEY_FALLING, QGR_KEY_FRAG, QGR_KEY_FRAG_BFG, QGR_KEY_FRAG_GAUNTLET, QGR_KEY_FRAG_GRAPPLE, QGR_KEY_FRAG_GRENADE, QGR_KEY_FRAG_LIGHTNING, QGR_KEY_FRAG_MACHINEGUN, QGR_KEY_FRAG_PLASMA, QGR_KEY_FRAG_RAILGUN, QGR_KEY_FRAG_ROCKET, QGR_KEY_FRAG_SHOTGUN, QGR_KEY_FRAG_UNKNOWN, QGR_KEY_HAZARD_DEATH, QGR_KEY_HAZARD_MISC, QGR_KEY_LAVA, QGR_KEY_SLIME, QGR_KEY_SUICIDE, QGR_KEY_SUICIDE_BFG, QGR_KEY_SUICIDE_CMD, QGR_KEY_SUICIDE_GAUNTLET, QGR_KEY_SUICIDE_GRAPPLE, QGR_KEY_SUICIDE_GRENADE, QGR_KEY_SUICIDE_LIGHTNING, QGR_KEY_SUICIDE_MACHINEGUN, QGR_KEY_SUICIDE_PLASMA, QGR_KEY_SUICIDE_RAILGUN, QGR_KEY_SUICIDE_ROCKET, QGR_KEY_SUICIDE_SHOTGUN, QGR_KEY_SUICIDE_UNKNOWN, QGR_KEY_TELEFRAG, QGR_KEY_TRIGGER_HURT, QGR_KEY_WATER, and level_locals_t::warmupTime.
void G_RankReward (int self, int award)
References EF_AWARD_EXCELLENT, EF_AWARD_IMPRESSIVE, level, QGR_KEY_EXCELLENT, QGR_KEY_IMPRESSIVE, and level_locals_t::warmupTime.
void G_RankRunFrame ()
References gentity_s::client, entityState_s::clientNum, ClientSpawn(), DeathmatchScoreboardMessage(), clientPersistant_t::enterTime, EXEC_INSERT, g_entities, g_fraglimit, g_gametype, g_timelimit, GT_TEAM, vmCvar_t::integer, level_locals_t::intermissiontime, gentity_s::inuse, level, level_locals_t::maxclients, clientPersistant_t::netname, NULL, gclient_s::pers, playerState_s::persistant, gclient_s::ps, QGR_KEY_PLAYED_WITH, gentity_s::r, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_FREE, clientSession_t::spectatorState, SVF_BOT, entityShared_t::svFlags, TEAM_SPECTATOR, level_locals_t::time, trap_Cvar_Set(), trap_SendConsoleCommand(), trap_SendServerCommand(), and va().
void G_RankUseHoldable (int self, int holdable)
References HI_MEDKIT, HI_TELEPORTER, level, QGR_KEY_MEDKIT_USE, QGR_KEY_TELEPORTER_USE, and level_locals_t::warmupTime.
void G_RankUserTeamName (int self, char * team_name)
References level, QGR_KEY_TEAM_NAME, and level_locals_t::warmupTime.
void G_RankWeaponTime (int self, int weapon)
References gentity_s::client, g_entities, level, QGR_KEY_TIME, QGR_KEY_TIME_BFG, QGR_KEY_TIME_GAUNTLET, QGR_KEY_TIME_GRAPPLE, QGR_KEY_TIME_GRENADE, QGR_KEY_TIME_LIGHTNING, QGR_KEY_TIME_MACHINEGUN, QGR_KEY_TIME_PLASMA, QGR_KEY_TIME_RAILGUN, QGR_KEY_TIME_ROCKET, QGR_KEY_TIME_SHOTGUN, level_locals_t::time, level_locals_t::warmupTime, WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.