ioquake3: SpeexHeader: Makes it easy to write/parse an Ogg/Speex header
SpeexHeader: Makes it easy to write/parse an Ogg/Speex header
Data Structures
struct SpeexHeader
Defines
#define SPEEX_HEADER_STRING_LENGTH 8
#define SPEEX_HEADER_VERSION_LENGTH 20
Typedefs
typedef struct SpeexHeader SpeexHeader
Functions
void speex_init_header (SpeexHeader *header, int rate, int nb_channels, const struct SpeexMode *m)
char * speex_header_to_packet (SpeexHeader *header, int *size)
SpeexHeader * speex_packet_to_header (char *packet, int size)
void speex_header_free (void *ptr)
Detailed Description
This is the Speex header for the Ogg encapsulation. You don't need that if you just use RTP.
Define Documentation
#define SPEEX_HEADER_STRING_LENGTH 8
Length of the Speex header identifier
#define SPEEX_HEADER_VERSION_LENGTH 20
Maximum number of characters for encoding the Speex version number in the header
Referenced by speex_init_header().
Typedef Documentation
typedef struct SpeexHeader SpeexHeader
Speex header info for file-based formats
Function Documentation
void speex_header_free (void * ptr)
Frees the memory allocated by either speex_header_to_packet() or speex_packet_to_header()
References speex_free().
char* speex_header_to_packet (SpeexHeader * header, int * size)
Creates the header packet from the header itself (mostly involves endianness conversion)
References bitrate, ENDIAN_SWITCH, extra_headers, frame_size, frames_per_packet, header_size, mode, mode_bitstream_version, nb_channels, rate, speex_alloc(), SPEEX_COPY, speex_version_id, and vbr.
void speex_init_header (SpeexHeader * header, int rate, int nb_channels, const struct SpeexMode * m)
Initializes a SpeexHeader using basic information
SpeexHeader* speex_packet_to_header (char * packet, int size)
Creates a SpeexHeader from a packet
References bitrate, ENDIAN_SWITCH, extra_headers, frame_size, frames_per_packet, h, header_size, mode, mode_bitstream_version, nb_channels, NULL, rate, speex_alloc(), SPEEX_COPY, speex_notify(), speex_version_id, and vbr.