ioquake3: SpeexPreprocessState: The Speex preprocessor
SpeexPreprocessState: The Speex preprocessor
Defines
#define SPEEX_PREPROCESS_SET_DENOISE 0
#define SPEEX_PREPROCESS_GET_DENOISE 1
#define SPEEX_PREPROCESS_SET_AGC 2
#define SPEEX_PREPROCESS_GET_AGC 3
#define SPEEX_PREPROCESS_SET_VAD 4
#define SPEEX_PREPROCESS_GET_VAD 5
#define SPEEX_PREPROCESS_SET_AGC_LEVEL 6
#define SPEEX_PREPROCESS_GET_AGC_LEVEL 7
#define SPEEX_PREPROCESS_SET_DEREVERB 8
#define SPEEX_PREPROCESS_GET_DEREVERB 9
#define SPEEX_PREPROCESS_SET_DEREVERB_LEVEL 10
#define SPEEX_PREPROCESS_GET_DEREVERB_LEVEL 11
#define SPEEX_PREPROCESS_SET_DEREVERB_DECAY 12
#define SPEEX_PREPROCESS_GET_DEREVERB_DECAY 13
#define SPEEX_PREPROCESS_SET_PROB_START 14
#define SPEEX_PREPROCESS_GET_PROB_START 15
#define SPEEX_PREPROCESS_SET_PROB_CONTINUE 16
#define SPEEX_PREPROCESS_GET_PROB_CONTINUE 17
#define SPEEX_PREPROCESS_SET_NOISE_SUPPRESS 18
#define SPEEX_PREPROCESS_GET_NOISE_SUPPRESS 19
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS 20
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS 21
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE 22
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE 23
#define SPEEX_PREPROCESS_SET_ECHO_STATE 24
#define SPEEX_PREPROCESS_GET_ECHO_STATE 25
#define SPEEX_PREPROCESS_SET_AGC_INCREMENT 26
#define SPEEX_PREPROCESS_GET_AGC_INCREMENT 27
#define SPEEX_PREPROCESS_SET_AGC_DECREMENT 28
#define SPEEX_PREPROCESS_GET_AGC_DECREMENT 29
#define SPEEX_PREPROCESS_SET_AGC_MAX_GAIN 30
#define SPEEX_PREPROCESS_GET_AGC_MAX_GAIN 31
#define SPEEX_PREPROCESS_GET_AGC_LOUDNESS 33
Typedefs
typedef struct
SpeexPreprocessState_ SpeexPreprocessState
Functions
SpeexPreprocessState * speex_preprocess_state_init (int frame_size, int sampling_rate)
void speex_preprocess_state_destroy (SpeexPreprocessState *st)
int speex_preprocess_run (SpeexPreprocessState *st, spx_int16_t *x)
int speex_preprocess (SpeexPreprocessState *st, spx_int16_t *x, spx_int32_t *echo)
void speex_preprocess_estimate_update (SpeexPreprocessState *st, spx_int16_t *x)
int speex_preprocess_ctl (SpeexPreprocessState *st, int request, void *ptr)
Detailed Description
This is the Speex preprocessor. The preprocess can do noise suppression, residual echo suppression (after using the echo canceller), automatic gain control (AGC) and voice activity detection (VAD).
Define Documentation
#define SPEEX_PREPROCESS_GET_AGC 3
Get preprocessor Automatic Gain Control state
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_AGC_DECREMENT 29
Get maximal gain decrease in dB/second (int32)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_AGC_INCREMENT 27
Get maximal gain increase in dB/second (int32)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_AGC_LEVEL 7
Get preprocessor Automatic Gain Control level
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_AGC_LOUDNESS 33
Get loudness
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_AGC_MAX_GAIN 31
Get maximal gain in dB (int32)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_DENOISE 1
Get preprocessor denoiser state
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_DEREVERB 9
Get preprocessor dereverb state
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_DEREVERB_DECAY 13
Get preprocessor dereverb decay
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_DEREVERB_LEVEL 11
Get preprocessor dereverb level
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_ECHO_STATE 25
Get the corresponding echo canceller state
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS 21
Get maximum attenuation of the residual echo in dB (negative number)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE 23
Get maximum attenuation of the residual echo in dB when near end is active (negative number)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_NOISE_SUPPRESS 19
Get maximum attenuation of the noise in dB (negative number)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_PROB_CONTINUE 17
Get probability required for the VAD to stay in the voice state (integer percent)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_PROB_START 15
Get probability required for the VAD to go from silence to voice
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_GET_VAD 5
Get preprocessor Voice Activity Detection state
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_AGC 2
Set preprocessor Automatic Gain Control state
Referenced by CL_FirstSnapshot(), main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_AGC_DECREMENT 28
Set maximal gain decrease in dB/second (int32)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_AGC_INCREMENT 26
Set maximal gain increase in dB/second (int32)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_AGC_LEVEL 6
Set preprocessor Automatic Gain Control level
Referenced by main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_AGC_MAX_GAIN 30
Set maximal gain in dB (int32)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_DENOISE 0
Set preprocessor denoiser state
Referenced by CL_FirstSnapshot(), main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_DEREVERB 8
Set preprocessor dereverb state
Referenced by main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_DEREVERB_DECAY 12
Set preprocessor dereverb decay
Referenced by main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_DEREVERB_LEVEL 10
Set preprocessor dereverb level
Referenced by main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_ECHO_STATE 24
Set the corresponding echo canceller state so that residual echo suppression can be performed (NULL for no residual echo suppression)
Referenced by main(), and speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS 20
Set maximum attenuation of the residual echo in dB (negative number)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE 22
Set maximum attenuation of the residual echo in dB when near end is active (negative number)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_NOISE_SUPPRESS 18
Set maximum attenuation of the noise in dB (negative number)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_PROB_CONTINUE 16
Set probability required for the VAD to stay in the voice state (integer percent)
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_PROB_START 14
Set probability required for the VAD to go from silence to voice
Referenced by speex_preprocess_ctl().
#define SPEEX_PREPROCESS_SET_VAD 4
Set preprocessor Voice Activity Detection state
Referenced by speex_preprocess_ctl().
Typedef Documentation
typedef struct SpeexPreprocessState_ SpeexPreprocessState
State of the preprocessor (one per channel). Should never be accessed directly.
Function Documentation
int speex_preprocess (SpeexPreprocessState * st, spx_int16_t * x, spx_int32_t * echo)
Preprocess a frame (deprecated, use speex_preprocess_run() instead)
References speex_preprocess_run().
int speex_preprocess_ctl (SpeexPreprocessState * st, int request, void * ptr)
Used like the ioctl function to control the preprocessor parameters
Parameters:
st Preprocessor state
request ioctl-type request (one of the SPEEX_PREPROCESS_* macros)
ptr Data exchanged to-from function
Returns:
0 if no error, -1 if request in unknown
References ABS, SpeexPreprocessState_::agc_enabled, SpeexPreprocessState_::agc_level, SpeexPreprocessState_::denoise_enabled, SpeexPreprocessState_::dereverb_enabled, DIV32_16, SpeexPreprocessState_::echo_state, SpeexPreprocessState_::echo_suppress, SpeexPreprocessState_::echo_suppress_active, SpeexPreprocessState_::frame_size, SpeexPreprocessState_::loudness, LOUDNESS_EXP, MAX32, SpeexPreprocessState_::max_decrease_step, SpeexPreprocessState_::max_gain, SpeexPreprocessState_::max_increase_step, MIN32, MULT16_16, MULT16_16_Q15, SpeexPreprocessState_::noise_suppress, SpeexPreprocessState_::ps_size, ptr(), Q15ONE, SpeexPreprocessState_::reverb_estimate, SpeexPreprocessState_::sampling_rate, SpeexPreprocessState_::speech_prob_continue, SpeexPreprocessState_::speech_prob_start, SPEEX_PREPROCESS_GET_AGC, SPEEX_PREPROCESS_GET_AGC_DECREMENT, SPEEX_PREPROCESS_GET_AGC_INCREMENT, SPEEX_PREPROCESS_GET_AGC_LEVEL, SPEEX_PREPROCESS_GET_AGC_LOUDNESS, SPEEX_PREPROCESS_GET_AGC_MAX_GAIN, SPEEX_PREPROCESS_GET_DENOISE, SPEEX_PREPROCESS_GET_DEREVERB, SPEEX_PREPROCESS_GET_DEREVERB_DECAY, SPEEX_PREPROCESS_GET_DEREVERB_LEVEL, SPEEX_PREPROCESS_GET_ECHO_STATE, SPEEX_PREPROCESS_GET_ECHO_SUPPRESS, SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE, SPEEX_PREPROCESS_GET_NOISE_SUPPRESS, SPEEX_PREPROCESS_GET_PROB_CONTINUE, SPEEX_PREPROCESS_GET_PROB_START, SPEEX_PREPROCESS_GET_VAD, SPEEX_PREPROCESS_SET_AGC, SPEEX_PREPROCESS_SET_AGC_DECREMENT, SPEEX_PREPROCESS_SET_AGC_INCREMENT, SPEEX_PREPROCESS_SET_AGC_LEVEL, SPEEX_PREPROCESS_SET_AGC_MAX_GAIN, SPEEX_PREPROCESS_SET_DENOISE, SPEEX_PREPROCESS_SET_DEREVERB, SPEEX_PREPROCESS_SET_DEREVERB_DECAY, SPEEX_PREPROCESS_SET_DEREVERB_LEVEL, SPEEX_PREPROCESS_SET_ECHO_STATE, SPEEX_PREPROCESS_SET_ECHO_SUPPRESS, SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE, SPEEX_PREPROCESS_SET_NOISE_SUPPRESS, SPEEX_PREPROCESS_SET_PROB_CONTINUE, SPEEX_PREPROCESS_SET_PROB_START, SPEEX_PREPROCESS_SET_VAD, speex_warning(), speex_warning_int(), and SpeexPreprocessState_::vad_enabled.
Referenced by CL_FirstSnapshot(), and main().
void speex_preprocess_estimate_update (SpeexPreprocessState * st, spx_int16_t * x)
Update preprocessor state, but do not compute the output
Parameters:
st Preprocessor state
x Audio sample vector (in only). Must be same size as specified in speex_preprocess_state_init().
References SpeexPreprocessState_::frame_size, M, SpeexPreprocessState_::min_count, MULT16_16_Q15, MULT16_32_Q15, N, SpeexPreprocessState_::nbands, SpeexPreprocessState_::noise, NOISE_SHIFT, SpeexPreprocessState_::old_ps, SpeexPreprocessState_::outbuf, preprocess_analysis(), SpeexPreprocessState_::ps, SpeexPreprocessState_::ps_size, PSHR32, QCONST16, SpeexPreprocessState_::reverb_decay, SpeexPreprocessState_::reverb_estimate, SHL32, update_noise_prob(), SpeexPreprocessState_::update_prob, and SpeexPreprocessState_::window.
int speex_preprocess_run (SpeexPreprocessState * st, spx_int16_t * x)
Preprocess a frame
Parameters:
st Preprocessor state
x Audio sample vector (in and out). Must be same size as specified in speex_preprocess_state_init().
Returns:
Bool value for voice activity (1 for speech, 0 for noise/silence), ONLY if VAD turned on.
References ADD16, ADD32, SpeexPreprocessState_::agc_enabled, SpeexPreprocessState_::bank, compute_gain_floor(), SpeexPreprocessState_::denoise_enabled, DIV32_16, DIV32_16_Q15, DIV32_16_Q8, SpeexPreprocessState_::echo_noise, SpeexPreprocessState_::echo_state, SpeexPreprocessState_::echo_suppress, SpeexPreprocessState_::echo_suppress_active, EXTEND32, EXTRACT16, SpeexPreprocessState_::fft_lookup, filterbank_compute_bank32(), filterbank_compute_psd16(), SpeexPreprocessState_::frame, SpeexPreprocessState_::frame_size, SpeexPreprocessState_::ft, SpeexPreprocessState_::gain, SpeexPreprocessState_::gain2, SpeexPreprocessState_::gain_floor, hypergeom_gain(), if(), M, MAX16, MAX32, MIN16, MIN32, SpeexPreprocessState_::min_count, MULT16_16, MULT16_16_P15, MULT16_16_Q15, MULT16_32_P15, MULT16_32_Q15, N, SpeexPreprocessState_::nb_adapt, SpeexPreprocessState_::nbands, SpeexPreprocessState_::noise, NOISE_SHIFT, SpeexPreprocessState_::noise_suppress, SpeexPreprocessState_::old_ps, SpeexPreprocessState_::outbuf, PDIV32_16, SpeexPreprocessState_::post, preprocess_analysis(), SpeexPreprocessState_::prior, SpeexPreprocessState_::ps, SpeexPreprocessState_::ps_size, PSHR16, PSHR32, Q15_ONE, Q15ONE, QCONST16, QCONST32, qcurve(), SpeexPreprocessState_::residual_echo, SpeexPreprocessState_::reverb_estimate, SHL32, SHR32, SNR_SHIFT, SpeexPreprocessState_::speech_prob_continue, SpeexPreprocessState_::speech_prob_start, speex_compute_agc(), speex_echo_get_residual(), spx_exp, spx_ifft(), spx_sqrt, SQR16_Q15, SUB16, update_noise_prob(), SpeexPreprocessState_::update_prob, SpeexPreprocessState_::vad_enabled, SpeexPreprocessState_::was_speech, SpeexPreprocessState_::window, and SpeexPreprocessState_::zeta.
Referenced by main(), and speex_preprocess().
void speex_preprocess_state_destroy (SpeexPreprocessState * st)
Destroys a preprocessor state
Parameters:
st Preprocessor state to destroy
References SpeexPreprocessState_::bank, SpeexPreprocessState_::echo_noise, SpeexPreprocessState_::fft_lookup, filterbank_destroy(), SpeexPreprocessState_::frame, SpeexPreprocessState_::ft, SpeexPreprocessState_::gain, SpeexPreprocessState_::gain2, SpeexPreprocessState_::gain_floor, SpeexPreprocessState_::inbuf, SpeexPreprocessState_::loudness_weight, SpeexPreprocessState_::noise, SpeexPreprocessState_::old_ps, SpeexPreprocessState_::outbuf, SpeexPreprocessState_::post, SpeexPreprocessState_::prior, SpeexPreprocessState_::ps, SpeexPreprocessState_::residual_echo, SpeexPreprocessState_::reverb_estimate, SpeexPreprocessState_::S, SpeexPreprocessState_::Smin, speex_free(), spx_fft_destroy(), SpeexPreprocessState_::Stmp, SpeexPreprocessState_::update_prob, SpeexPreprocessState_::window, and SpeexPreprocessState_::zeta.
Referenced by CL_Disconnect(), and main().
SpeexPreprocessState* speex_preprocess_state_init (int frame_size, int sampling_rate)
Creates a new preprocessing state. You MUST create one state per channel processed.
Parameters:
frame_size Number of samples to process at one time (should correspond to 10-20 ms). Must be the same value as that used for the echo canceller for residual echo cancellation to work.
sampling_rate Sampling rate used for the input.
Returns:
Newly created preprocessor state
References SpeexPreprocessState_::agc_enabled, SpeexPreprocessState_::agc_gain, SpeexPreprocessState_::agc_level, SpeexPreprocessState_::bank, conj_window(), SpeexPreprocessState_::denoise_enabled, SpeexPreprocessState_::dereverb_enabled, SpeexPreprocessState_::echo_noise, SpeexPreprocessState_::echo_state, SpeexPreprocessState_::echo_suppress, SpeexPreprocessState_::echo_suppress_active, ECHO_SUPPRESS_ACTIVE_DEFAULT, ECHO_SUPPRESS_DEFAULT, SpeexPreprocessState_::fft_lookup, filterbank_new(), SpeexPreprocessState_::frame, SpeexPreprocessState_::frame_size, SpeexPreprocessState_::ft, SpeexPreprocessState_::gain, SpeexPreprocessState_::gain2, SpeexPreprocessState_::gain_floor, if(), SpeexPreprocessState_::inbuf, SpeexPreprocessState_::init_max, SpeexPreprocessState_::loudness, SpeexPreprocessState_::loudness_weight, M, SpeexPreprocessState_::max_decrease_step, SpeexPreprocessState_::max_gain, SpeexPreprocessState_::max_increase_step, SpeexPreprocessState_::min_count, N, SpeexPreprocessState_::nb_adapt, NB_BANDS, SpeexPreprocessState_::nb_loudness_adapt, SpeexPreprocessState_::nbands, SpeexPreprocessState_::noise, NOISE_SHIFT, SpeexPreprocessState_::noise_suppress, NOISE_SUPPRESS_DEFAULT, NULL, SpeexPreprocessState_::old_ps, SpeexPreprocessState_::outbuf, SpeexPreprocessState_::post, SpeexPreprocessState_::prev_loudness, SpeexPreprocessState_::prior, SpeexPreprocessState_::ps, SpeexPreprocessState_::ps_size, Q15_ONE, QCONST32, SpeexPreprocessState_::residual_echo, SpeexPreprocessState_::reverb_decay, SpeexPreprocessState_::reverb_estimate, SpeexPreprocessState_::reverb_level, SpeexPreprocessState_::S, SpeexPreprocessState_::sampling_rate, SHL16, SpeexPreprocessState_::Smin, SNR_SHIFT, SpeexPreprocessState_::speech_prob_continue, SPEECH_PROB_CONTINUE_DEFAULT, SpeexPreprocessState_::speech_prob_start, SPEECH_PROB_START_DEFAULT, speex_alloc(), spx_fft_init(), SpeexPreprocessState_::Stmp, SpeexPreprocessState_::update_prob, SpeexPreprocessState_::vad_enabled, SpeexPreprocessState_::was_speech, SpeexPreprocessState_::window, and SpeexPreprocessState_::zeta.
Referenced by CL_FirstSnapshot(), and main().