ioquake3: code/qcommon/huffman.c File Reference
huffman.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Functions
void Huff_putBit (int bit, byte *fout, int *offset)
int Huff_getBloc (void)
void Huff_setBloc (int _bloc)
int Huff_getBit (byte *fin, int *offset)
static void add_bit (char bit, byte *fout)
static int get_bit (byte *fin)
static node_t ** get_ppnode (huff_t *huff)
static void free_ppnode (huff_t *huff, node_t **ppnode)
static void swap (huff_t *huff, node_t *node1, node_t *node2)
static void swaplist (node_t *node1, node_t *node2)
static void increment (huff_t *huff, node_t *node)
void Huff_addRef (huff_t *huff, byte ch)
int Huff_Receive (node_t *node, int *ch, byte *fin)
void Huff_offsetReceive (node_t *node, int *ch, byte *fin, int *offset)
static void send (node_t *node, node_t *child, byte *fout)
void Huff_transmit (huff_t *huff, int ch, byte *fout)
void Huff_offsetTransmit (huff_t *huff, int ch, byte *fout, int *offset)
void Huff_Decompress (msg_t *mbuf, int offset)
void Huff_Compress (msg_t *mbuf, int offset)
void Huff_Init (huffman_t *huff)
Variables
static int bloc = 0
int oldsize
Function Documentation
static void add_bit (char bit, byte * fout) [static]
References bloc.
Referenced by Huff_transmit(), and send().
static void free_ppnode (huff_t * huff, node_t ** ppnode) [static]
References huff_t::freelist.
Referenced by increment().
static int get_bit (byte * fin) [static]
References bloc, and t.
Referenced by Huff_Decompress(), Huff_offsetReceive(), and Huff_Receive().
static node_t** get_ppnode (huff_t * huff) [static]
References huff_t::blocPtrs, huff_t::freelist, and huff_t::nodePtrs.
Referenced by Huff_addRef(), and increment().
void Huff_addRef (huff_t * huff, byte ch)
References huff_t::blocNode, get_ppnode(), nodetype::head, increment(), INTERNAL_NODE, nodetype::left, huff_t::lhead, huff_t::loc, nodetype::next, huff_t::nodeList, NULL, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, tnode(), huff_t::tree, and nodetype::weight.
Referenced by Huff_Compress(), Huff_Decompress(), and MSG_initHuffman().
void Huff_Compress (msg_t * mbuf, int offset)
References bloc, huff_t::blocNode, buffer, Com_Memcpy, Com_Memset, msg_t::cursize, msg_t::data, Huff_addRef(), Huff_transmit(), nodetype::left, huff_t::lhead, huff_t::loc, nodetype::next, huff_t::nodeList, NULL, NYT, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, huff_t::tree, and nodetype::weight.
Referenced by NET_OutOfBandData().
void Huff_Decompress (msg_t * mbuf, int offset)
References bloc, huff_t::blocNode, buffer, Com_Memcpy, Com_Memset, msg_t::cursize, msg_t::data, get_bit(), Huff_addRef(), Huff_Receive(), nodetype::left, huff_t::lhead, huff_t::loc, huff_t::ltail, msg_t::maxsize, nodetype::next, huff_t::nodeList, NULL, NYT, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, huff_t::tree, and nodetype::weight.
Referenced by SV_ConnectionlessPacket().
int Huff_getBit (byte * fin, int * offset)
References bloc, and t.
Referenced by MSG_ReadBits().
int Huff_getBloc (void)
References bloc.
Referenced by MSG_LookaheadByte().
void Huff_Init (huffman_t * huff)
References huff_t::blocNode, Com_Memset, huffman_t::compressor, huffman_t::decompressor, nodetype::left, huff_t::lhead, huff_t::loc, huff_t::ltail, nodetype::next, huff_t::nodeList, NULL, NYT, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, huff_t::tree, and nodetype::weight.
Referenced by MSG_initHuffman().
void Huff_offsetReceive (node_t * node, int * ch, byte * fin, int * offset)
References bloc, get_bit(), INTERNAL_NODE, nodetype::left, nodetype::right, and nodetype::symbol.
Referenced by MSG_ReadBits().
void Huff_offsetTransmit (huff_t * huff, int ch, byte * fout, int * offset)
References bloc, huff_t::loc, NULL, and send().
Referenced by MSG_WriteBits().
void Huff_putBit (int bit, byte * fout, int * offset)
References bloc.
Referenced by MSG_WriteBits().
int Huff_Receive (node_t * node, int * ch, byte * fin)
References get_bit(), INTERNAL_NODE, nodetype::left, nodetype::right, and nodetype::symbol.
Referenced by Huff_Decompress().
void Huff_setBloc (int _bloc)
References bloc.
Referenced by MSG_LookaheadByte().
void Huff_transmit (huff_t * huff, int ch, byte * fout)
References add_bit(), Huff_transmit(), huff_t::loc, NULL, NYT, and send().
Referenced by Huff_Compress(), and Huff_transmit().
static void increment (huff_t * huff, node_t * node) [static]
References free_ppnode(), get_ppnode(), nodetype::head, nodetype::next, node(), NULL, nodetype::parent, nodetype::prev, swap, swaplist(), and nodetype::weight.
Referenced by Huff_addRef().
static void send (node_t * node, node_t * child, byte * fout) [static]
References add_bit(), nodetype::parent, and nodetype::right.
Referenced by Huff_offsetTransmit(), Huff_transmit(), NET_OpenSocks(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
static void swap (huff_t * huff, node_t * node1, node_t * node2) [static]
References nodetype::left, nodetype::parent, nodetype::right, and huff_t::tree.
static void swaplist (node_t * node1, node_t * node2) [static]
References nodetype::next, and nodetype::prev.
Referenced by increment().
Variable Documentation
int bloc = 0 [static]
Referenced by add_bit(), get_bit(), Huff_Compress(), Huff_Decompress(), Huff_getBit(), Huff_getBloc(), Huff_offsetReceive(), Huff_offsetTransmit(), Huff_putBit(), Huff_setBloc(), and MSG_LookaheadByte().
int oldsize
Referenced by MSG_WriteBits(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), and MSG_WriteDeltaUsercmdKey().