ioquake3: code/tools/lcc/cpp/include.c File Reference
include.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Functions
void appendDirToIncludeList (char *dir)
void doinclude (Tokenrow *trp)
void genline (void)
void setobjname (char *f)
Variables
Includelist includelist [NINCLUDE]
char * objname
Function Documentation
void appendDirToIncludeList (char * dir)
References includelist::always, error(), FATAL, includelist::file, value::i, newstring(), NINCLUDE, and NULL.
Referenced by doinclude(), and setup().
void doinclude (Tokenrow * trp)
References includelist::always, appendDirToIncludeList(), basepath(), tokenrow::bp, includelist::deleted, ERROR, error(), expandrow(), FATAL, includelist::file, genline(), GT, value::i, incdepth, token::len, tokenrow::lp, LT, Mflag, newstring(), NINCLUDE, NULL, objname, setsource(), STRING, token::t, tokenrow::tp, and token::type.
Referenced by control().
void genline (void)
References tokenrow::bp, cursource, source::filename, token::len, source::line, outnum(), outp, value::p, puttokens(), token::t, tokenrow::tp, tr, UNCLASS, and wd.
Referenced by doinclude(), main(), and process().
void setobjname (char * f)
References domalloc(), n, and objname.
Referenced by setup().
Variable Documentation
Includelist includelist[NINCLUDE]
char* objname
Referenced by doinclude(), and setobjname().