ioquake3: code/tools/lcc/src/inits.c File Reference
inits.c File Reference
Functions
void init (int argc, char *argv[])
Function Documentation
void init (int argc, char * argv[])
References input_init(), main_init(), prof_init(), trace_init(), and type_init().
Referenced by main(), SV_RankBegin(), SV_RankUserCreate(), SV_RankUserLogin(), SV_RankUserValidate(), and UI_HeadCountByTeam().