ioquake3: code/qcommon/ioapi.c File Reference
ioapi.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>
#include "ioapi.h"
Defines
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
Functions
voidpf ZCALLBACK fopen_file_func OF ((voidpf opaque, const char *filename, int mode))
uLong ZCALLBACK fread_file_func OF ((voidpf opaque, voidpf stream, void *buf, uLong size))
uLong ZCALLBACK fwrite_file_func OF ((voidpf opaque, voidpf stream, const void *buf, uLong size))
long ZCALLBACK ftell_file_func OF ((voidpf opaque, voidpf stream))
long ZCALLBACK fseek_file_func OF ((voidpf opaque, voidpf stream, uLong offset, int origin))
voidpf ZCALLBACK fopen_file_func (voidpf opaque, const char *filename, int mode)
uLong ZCALLBACK fread_file_func (voidpf opaque, voidpf stream, void *buf, uLong size)
uLong ZCALLBACK fwrite_file_func (voidpf opaque, voidpf stream, const void *buf, uLong size)
long ZCALLBACK ftell_file_func (voidpf opaque, voidpf stream)
long ZCALLBACK fseek_file_func (voidpf opaque, voidpf stream, uLong offset, int origin)
int ZCALLBACK fclose_file_func (voidpf opaque, voidpf stream)
int ZCALLBACK ferror_file_func (voidpf opaque, voidpf stream)
void fill_fopen_filefunc (zlib_filefunc_def *pzlib_filefunc_def)
Define Documentation
#define SEEK_CUR 1
Referenced by FS_Seek(), and fseek_file_func().
#define SEEK_END 2
Referenced by filelength(), FileLength(), FS_fplength(), FS_Seek(), fseek_file_func(), and Q_filelength().
#define SEEK_SET 0
Referenced by filelength(), FileLength(), FS_fplength(), FS_Seek(), fseek_file_func(), Q_filelength(), and unzOpenCurrentFile3().
Function Documentation
int ZCALLBACK fclose_file_func (voidpf opaque, voidpf stream)
References fclose().
Referenced by fill_fopen_filefunc().
int ZCALLBACK ferror_file_func (voidpf opaque, voidpf stream)
Referenced by fill_fopen_filefunc().
void fill_fopen_filefunc (zlib_filefunc_def* pzlib_filefunc_def)
References fclose_file_func(), ferror_file_func(), fopen_file_func(), fread_file_func(), fseek_file_func(), ftell_file_func(), fwrite_file_func(), NULL, and zlib_filefunc_def_s::zopen_file.
Referenced by unzOpen2().
voidpf ZCALLBACK fopen_file_func (voidpf opaque, const char* filename, int mode)
References file, NULL, ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, and ZLIB_FILEFUNC_MODE_READWRITEFILTER.
Referenced by fill_fopen_filefunc().
uLong ZCALLBACK fread_file_func (voidpf opaque, voidpf stream, void* buf, uLong size)
References fread().
Referenced by fill_fopen_filefunc().
long ZCALLBACK fseek_file_func (voidpf opaque, voidpf stream, uLong offset, int origin)
References SEEK_CUR, SEEK_END, SEEK_SET, ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_fopen_filefunc().
long ZCALLBACK ftell_file_func (voidpf opaque, voidpf stream)
Referenced by fill_fopen_filefunc().
uLong ZCALLBACK fwrite_file_func (voidpf opaque, voidpf stream, const void* buf, uLong size)
References fwrite().
Referenced by fill_fopen_filefunc().
voidpf ZCALLBACK fopen_file_func OF ((voidpf opaque, const char *filename, int mode))
uLong ZCALLBACK fread_file_func OF ((voidpf opaque, voidpf stream, void *buf, uLong size))
uLong ZCALLBACK fwrite_file_func OF ((voidpf opaque, voidpf stream, const void *buf, uLong size))
long ZCALLBACK ftell_file_func OF ((voidpf opaque, voidpf stream))
long ZCALLBACK fseek_file_func OF ((voidpf opaque, voidpf stream, uLong offset, int origin))