ioquake3: code/jpeg-8c/jcarith.c File Reference
jcarith.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct arith_entropy_encoder
Defines
#define JPEG_INTERNALS
#define DC_STAT_BINS 64
#define AC_STAT_BINS 256
#define ISHIFT_TEMPS
#define IRIGHT_SHIFT(x, shft) ((x) >> (shft))
Typedefs
typedef arith_entropy_encoder * arith_entropy_ptr
Functions
emit_byte (int val, j_compress_ptr cinfo)
finish_pass (j_compress_ptr cinfo)
arith_encode (j_compress_ptr cinfo, unsigned char *st, int val)
emit_restart (j_compress_ptr cinfo, int restart_num)
encode_mcu_DC_first (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_AC_first (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_DC_refine (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_AC_refine (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
start_pass (j_compress_ptr cinfo, boolean gather_statistics)
jinit_arith_encoder (j_compress_ptr cinfo)
Define Documentation
#define AC_STAT_BINS 256
Referenced by emit_restart(), and start_pass().
#define DC_STAT_BINS 64
Referenced by emit_restart(), and start_pass().
#define IRIGHT_SHIFT (x, shft) ((x) >> (shft))
Referenced by encode_mcu_DC_first().
#define ISHIFT_TEMPS
Referenced by encode_mcu_DC_first().
#define JPEG_INTERNALS
Typedef Documentation
typedef arith_entropy_encoder* arith_entropy_ptr
Function Documentation
arith_encode (j_compress_ptr cinfo, unsigned char * st, int val)
References arith_entropy_encoder::a, arith_entropy_encoder::buffer, arith_entropy_encoder::c, arith_entropy_encoder::ct, emit_byte(), if(), jpeg_aritab, arith_entropy_encoder::sc, sv, and arith_entropy_encoder::zc.
Referenced by encode_mcu(), encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), and encode_mcu_DC_refine().
emit_byte (int val, j_compress_ptr cinfo)
References jpeg_destination_mgr::free_in_buffer, and jpeg_destination_mgr::next_output_byte.
Referenced by arith_encode(), emit_2bytes(), emit_adobe_app14(), emit_dac(), emit_dht(), emit_dqt(), emit_jfif_app0(), emit_marker(), emit_pseudo_sos(), emit_restart(), emit_sof(), emit_sos(), finish_pass(), and write_marker_byte().
emit_restart (j_compress_ptr cinfo, int restart_num)
References arith_entropy_encoder::a, AC_STAT_BINS, arith_entropy_encoder::ac_stats, jpeg_component_info::ac_tbl_no, arith_entropy_encoder::buffer, arith_entropy_encoder::c, compptr, arith_entropy_encoder::ct, arith_entropy_encoder::dc_context, DC_STAT_BINS, arith_entropy_encoder::dc_stats, jpeg_component_info::dc_tbl_no, emit_byte(), finish_pass(), JPEG_RST0, arith_entropy_encoder::last_dc_val, MEMZERO, arith_entropy_encoder::sc, and arith_entropy_encoder::zc.
Referenced by encode_mcu(), encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), and encode_mcu_DC_refine().
encode_mcu (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
References arith_entropy_encoder::ac_stats, jpeg_component_info::ac_tbl_no, arith_encode(), compptr, arith_entropy_encoder::dc_context, arith_entropy_encoder::dc_stats, jpeg_component_info::dc_tbl_no, emit_restart(), arith_entropy_encoder::fixed_bin, if(), arith_entropy_encoder::last_dc_val, m, arith_entropy_encoder::next_restart_num, and arith_entropy_encoder::restarts_to_go.
Referenced by start_pass().
encode_mcu_AC_first (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
References arith_entropy_encoder::ac_stats, arith_encode(), emit_restart(), arith_entropy_encoder::fixed_bin, if(), m, arith_entropy_encoder::next_restart_num, and arith_entropy_encoder::restarts_to_go.
Referenced by start_pass(), and start_pass_huff().
encode_mcu_AC_refine (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
References arith_entropy_encoder::ac_stats, arith_encode(), emit_restart(), arith_entropy_encoder::fixed_bin, if(), arith_entropy_encoder::next_restart_num, and arith_entropy_encoder::restarts_to_go.
Referenced by start_pass(), and start_pass_huff().
encode_mcu_DC_first (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
References arith_encode(), arith_entropy_encoder::dc_context, arith_entropy_encoder::dc_stats, emit_restart(), if(), IRIGHT_SHIFT, ISHIFT_TEMPS, arith_entropy_encoder::last_dc_val, m, arith_entropy_encoder::next_restart_num, and arith_entropy_encoder::restarts_to_go.
Referenced by start_pass(), and start_pass_huff().
encode_mcu_DC_refine (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
References arith_encode(), emit_restart(), arith_entropy_encoder::fixed_bin, if(), arith_entropy_encoder::next_restart_num, and arith_entropy_encoder::restarts_to_go.
Referenced by start_pass(), and start_pass_huff().
finish_pass (j_compress_ptr cinfo)
References arith_entropy_encoder::a, arith_entropy_encoder::buffer, arith_entropy_encoder::c, arith_entropy_encoder::ct, emit_byte(), if(), arith_entropy_encoder::sc, and arith_entropy_encoder::zc.
Referenced by emit_restart(), and jinit_arith_encoder().
jinit_arith_encoder (j_compress_ptr cinfo)
References arith_entropy_encoder::ac_stats, arith_entropy_encoder::dc_stats, finish_pass(), arith_entropy_encoder::fixed_bin, JPOOL_IMAGE, NULL, NUM_ARITH_TBLS, arith_entropy_encoder::pub, SIZEOF, and start_pass().
Referenced by jinit_compress_master(), and transencode_master_selection().
start_pass (j_compress_ptr cinfo, boolean gather_statistics)
References arith_entropy_encoder::a, AC_STAT_BINS, arith_entropy_encoder::ac_stats, jpeg_component_info::ac_tbl_no, arith_entropy_encoder::buffer, arith_entropy_encoder::c, compptr, arith_entropy_encoder::ct, arith_entropy_encoder::dc_context, DC_STAT_BINS, arith_entropy_encoder::dc_stats, jpeg_component_info::dc_tbl_no, encode_mcu(), encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), encode_mcu_DC_refine(), if(), JPOOL_IMAGE, arith_entropy_encoder::last_dc_val, MEMZERO, arith_entropy_encoder::next_restart_num, NULL, NUM_ARITH_TBLS, arith_entropy_encoder::pub, arith_entropy_encoder::restarts_to_go, arith_entropy_encoder::sc, and arith_entropy_encoder::zc.
Referenced by jinit_arith_decoder(), jinit_arith_encoder(), and jinit_inverse_dct().