ioquake3: code/jpeg-8c/jcmaster.c File Reference
jcmaster.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_comp_master
Defines
#define JPEG_INTERNALS
#define MAX_AH_AL 10
Typedefs
typedef my_comp_master * my_master_ptr
Enumerations
enum c_pass_type { main_pass, huff_opt_pass, output_pass }
Functions
jpeg_calc_jpeg_dimensions (j_compress_ptr cinfo)
jpeg_calc_trans_dimensions (j_compress_ptr cinfo)
initial_setup (j_compress_ptr cinfo, boolean transcode_only)
validate_script (j_compress_ptr cinfo)
reduce_script (j_compress_ptr cinfo)
select_scan_parameters (j_compress_ptr cinfo)
per_scan_setup (j_compress_ptr cinfo)
prepare_for_pass (j_compress_ptr cinfo)
pass_startup (j_compress_ptr cinfo)
finish_pass_master (j_compress_ptr cinfo)
jinit_c_master_control (j_compress_ptr cinfo, boolean transcode_only)
Define Documentation
#define JPEG_INTERNALS
#define MAX_AH_AL 10
Referenced by validate_script().
Typedef Documentation
typedef my_comp_master* my_master_ptr
Enumeration Type Documentation
enum c_pass_type
Enumerator:
main_pass
huff_opt_pass
output_pass
Function Documentation
finish_pass_master (j_compress_ptr cinfo)
References huff_opt_pass, main_pass, output_pass, my_comp_master::pass_number, my_comp_master::pass_type, and my_comp_master::scan_number.
Referenced by jinit_c_master_control().
initial_setup (j_compress_ptr cinfo, boolean transcode_only)
References BITS_IN_JSAMPLE, jpeg_component_info::component_index, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, DCTSIZE, DCTSIZE2, jpeg_component_info::downsampled_height, jpeg_component_info::downsampled_width, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, jdiv_round_up(), jpeg_calc_jpeg_dimensions(), jpeg_calc_trans_dimensions(), JPEG_MAX_DIMENSION, jpeg_natural_order, jpeg_natural_order2, jpeg_natural_order3, jpeg_natural_order4, jpeg_natural_order5, jpeg_natural_order6, jpeg_natural_order7, long(), MAX, MAX_COMPONENTS, MAX_SAMP_FACTOR, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by consume_markers(), and jinit_c_master_control().
jinit_c_master_control (j_compress_ptr cinfo, boolean transcode_only)
References DCTSIZE, finish_pass_master(), huff_opt_pass, initial_setup(), jpeg_comp_master::is_last_pass, JPOOL_IMAGE, main_pass, NULL, output_pass, my_comp_master::pass_number, pass_startup(), my_comp_master::pass_type, prepare_for_pass(), my_comp_master::pub, reduce_script(), my_comp_master::scan_number, SIZEOF, my_comp_master::total_passes, and validate_script().
Referenced by jinit_compress_master(), and transencode_master_selection().
jpeg_calc_jpeg_dimensions (j_compress_ptr cinfo)
References DCTSIZE, jdiv_round_up(), and JPEG_MAX_DIMENSION.
Referenced by initial_setup().
jpeg_calc_trans_dimensions (j_compress_ptr cinfo)
Referenced by initial_setup().
pass_startup (j_compress_ptr cinfo)
Referenced by jinit_c_master_control().
per_scan_setup (j_compress_ptr cinfo)
References C_MAX_BLOCKS_IN_MCU, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, int(), jdiv_round_up(), jpeg_component_info::last_col_width, jpeg_component_info::last_row_height, long(), MAX_COMPS_IN_SCAN, jpeg_component_info::MCU_blocks, jpeg_component_info::MCU_height, jpeg_component_info::MCU_sample_width, jpeg_component_info::MCU_width, MIN, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by prepare_for_pass(), and start_input_pass().
prepare_for_pass (j_compress_ptr cinfo)
References jpeg_comp_master::call_pass_startup, huff_opt_pass, jpeg_comp_master::is_last_pass, JBUF_CRANK_DEST, JBUF_PASS_THRU, JBUF_SAVE_AND_PASS, main_pass, NULL, output_pass, my_comp_master::pass_number, my_comp_master::pass_type, per_scan_setup(), my_comp_master::pub, my_comp_master::scan_number, select_scan_parameters(), and my_comp_master::total_passes.
Referenced by jinit_c_master_control().
reduce_script (j_compress_ptr cinfo)
References jpeg_scan_info::Se.
Referenced by jinit_c_master_control().
select_scan_parameters (j_compress_ptr cinfo)
References MAX_COMPS_IN_SCAN, NULL, and my_comp_master::scan_number.
Referenced by prepare_for_pass().
validate_script (j_compress_ptr cinfo)
References jpeg_scan_info::Ah, jpeg_scan_info::Al, jpeg_scan_info::component_index, jpeg_scan_info::comps_in_scan, DCTSIZE2, MAX_AH_AL, MAX_COMPONENTS, MAX_COMPS_IN_SCAN, jpeg_scan_info::Se, and jpeg_scan_info::Ss.
Referenced by jinit_c_master_control().