ioquake3: code/jpeg-8c/jcparam.c File Reference
jcparam.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Defines
#define JPEG_INTERNALS
#define SET_COMP(index, id, hsamp, vsamp, quant, dctbl, actbl)
Functions
jpeg_add_quant_table (j_compress_ptr cinfo, int which_tbl, const unsigned int *basic_table, int scale_factor, boolean force_baseline)
jpeg_default_qtables (j_compress_ptr cinfo, boolean force_baseline)
jpeg_set_linear_quality (j_compress_ptr cinfo, int scale_factor, boolean force_baseline)
jpeg_quality_scaling (int quality)
jpeg_set_quality (j_compress_ptr cinfo, int quality, boolean force_baseline)
add_huff_table (j_compress_ptr cinfo, JHUFF_TBL **htblptr, const UINT8 *bits, const UINT8 *val)
std_huff_tables (j_compress_ptr cinfo)
jpeg_set_defaults (j_compress_ptr cinfo)
jpeg_default_colorspace (j_compress_ptr cinfo)
jpeg_set_colorspace (j_compress_ptr cinfo, J_COLOR_SPACE colorspace)
fill_a_scan (jpeg_scan_info *scanptr, int ci, int Ss, int Se, int Ah, int Al)
fill_scans (jpeg_scan_info *scanptr, int ncomps, int Ss, int Se, int Ah, int Al)
fill_dc_scans (jpeg_scan_info *scanptr, int ncomps, int Ah, int Al)
jpeg_simple_progression (j_compress_ptr cinfo)
Variables
static const unsigned int std_luminance_quant_tbl [DCTSIZE2]
static const unsigned int std_chrominance_quant_tbl [DCTSIZE2]
Define Documentation
#define JPEG_INTERNALS
#define SET_COMP (index, id, hsamp, vsamp, quant, dctbl, actbl)
Value:
(compptr = &cinfo->comp_info[index], \
   compptr->component_id = (id), \
   compptr->h_samp_factor = (hsamp), \
   compptr->v_samp_factor = (vsamp), \
   compptr->quant_tbl_no = (quant), \
   compptr->dc_tbl_no = (dctbl), \
   compptr->ac_tbl_no = (actbl) )
Referenced by jpeg_set_colorspace().
Function Documentation
add_huff_table (j_compress_ptr cinfo, JHUFF_TBL ** htblptr, const UINT8 * bits, const UINT8 * val)
References jpeg_alloc_huff_table(), MEMCOPY, NULL, and SIZEOF.
Referenced by std_huff_tables().
fill_a_scan (jpeg_scan_info * scanptr, int ci, int Ss, int Se, int Ah, int Al)
Referenced by jpeg_simple_progression().
fill_dc_scans (jpeg_scan_info * scanptr, int ncomps, int Ah, int Al)
References fill_scans(), and MAX_COMPS_IN_SCAN.
Referenced by jpeg_simple_progression().
fill_scans (jpeg_scan_info * scanptr, int ncomps, int Ss, int Se, int Ah, int Al)
Referenced by fill_dc_scans(), and jpeg_simple_progression().
jpeg_add_quant_table (j_compress_ptr cinfo, int which_tbl, const unsigned int * basic_table, int scale_factor, boolean force_baseline)
References CSTATE_START, DCTSIZE2, jpeg_alloc_quant_table(), long(), NULL, NUM_QUANT_TBLS, and which_tbl.
Referenced by jpeg_default_qtables(), and jpeg_set_linear_quality().
jpeg_default_colorspace (j_compress_ptr cinfo)
References JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, and jpeg_set_colorspace().
Referenced by jpeg_set_defaults().
jpeg_default_qtables (j_compress_ptr cinfo, boolean force_baseline)
References jpeg_add_quant_table(), std_chrominance_quant_tbl, and std_luminance_quant_tbl.
jpeg_quality_scaling (int quality)
References quality.
Referenced by jpeg_set_quality().
jpeg_set_colorspace (j_compress_ptr cinfo, J_COLOR_SPACE colorspace)
References colorspace, compptr, CSTATE_START, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, MAX_COMPONENTS, and SET_COMP.
Referenced by jpeg_copy_critical_parameters(), and jpeg_default_colorspace().
jpeg_set_defaults (j_compress_ptr cinfo)
References BITS_IN_JSAMPLE, CSTATE_START, jpeg_default_colorspace(), jpeg_set_quality(), JPOOL_PERMANENT, MAX_COMPONENTS, NULL, NUM_ARITH_TBLS, SIZEOF, and std_huff_tables().
Referenced by jpeg_copy_critical_parameters(), and RE_SaveJPGToBuffer().
jpeg_set_linear_quality (j_compress_ptr cinfo, int scale_factor, boolean force_baseline)
References jpeg_add_quant_table(), std_chrominance_quant_tbl, and std_luminance_quant_tbl.
Referenced by jpeg_set_quality().
jpeg_set_quality (j_compress_ptr cinfo, int quality, boolean force_baseline)
References jpeg_quality_scaling(), and jpeg_set_linear_quality().
Referenced by jpeg_set_defaults(), and RE_SaveJPGToBuffer().
jpeg_simple_progression (j_compress_ptr cinfo)
References CSTATE_START, fill_a_scan(), fill_dc_scans(), fill_scans(), JCS_YCbCr, JPOOL_PERMANENT, MAX, MAX_COMPS_IN_SCAN, NULL, and SIZEOF.
std_huff_tables (j_compress_ptr cinfo)
References add_huff_table().
Referenced by jpeg_set_defaults().
Variable Documentation
const unsigned int std_chrominance_quant_tbl[DCTSIZE2] [static]
Initial value:
 {
  17,  18,  24,  47,  99,  99,  99,  99,
  18,  21,  26,  66,  99,  99,  99,  99,
  24,  26,  56,  99,  99,  99,  99,  99,
  47,  66,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99,
  99,  99,  99,  99,  99,  99,  99,  99
}
Referenced by jpeg_default_qtables(), and jpeg_set_linear_quality().
const unsigned int std_luminance_quant_tbl[DCTSIZE2] [static]
Initial value:
 {
  16,  11,  10,  16,  24,  40,  51,  61,
  12,  12,  14,  19,  26,  58,  60,  55,
  14,  13,  16,  24,  40,  57,  69,  56,
  14,  17,  22,  29,  51,  87,  80,  62,
  18,  22,  37,  56,  68, 109, 103,  77,
  24,  35,  55,  64,  81, 104, 113,  92,
  49,  64,  78,  87, 103, 121, 120, 101,
  72,  92,  95,  98, 112, 100, 103,  99
}
Referenced by jpeg_default_qtables(), and jpeg_set_linear_quality().