ioquake3: code/jpeg-8c/jdinput.c File Reference
jdinput.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_input_controller
Defines
#define JPEG_INTERNALS
Typedefs
typedef my_input_controller * my_inputctl_ptr
Functions
METHODDEF (int)
initial_setup (j_decompress_ptr cinfo)
per_scan_setup (j_decompress_ptr cinfo)
latch_quant_tables (j_decompress_ptr cinfo)
start_input_pass (j_decompress_ptr cinfo)
finish_input_pass (j_decompress_ptr cinfo)
consume_markers (j_decompress_ptr cinfo)
reset_input_controller (j_decompress_ptr cinfo)
jinit_input_controller (j_decompress_ptr cinfo)
Define Documentation
#define JPEG_INTERNALS
Typedef Documentation
typedef my_input_controller* my_inputctl_ptr
Function Documentation
consume_markers (j_decompress_ptr cinfo)
References jpeg_input_controller::eoi_reached, jpeg_input_controller::has_multiple_scans, if(), my_input_controller::inheaders, initial_setup(), JPEG_REACHED_EOI, JPEG_REACHED_SOS, JPEG_SUSPENDED, my_input_controller::pub, start_input_pass(), and val.
Referenced by finish_input_pass(), jinit_input_controller(), and reset_input_controller().
finish_input_pass (j_decompress_ptr cinfo)
References consume_markers().
Referenced by jinit_input_controller().
initial_setup (j_decompress_ptr cinfo)
References BITS_IN_JSAMPLE, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, DCTSIZE, DCTSIZE2, jpeg_component_info::downsampled_height, jpeg_component_info::downsampled_width, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, jdiv_round_up(), JPEG_MAX_DIMENSION, jpeg_natural_order, jpeg_natural_order2, jpeg_natural_order3, jpeg_natural_order4, jpeg_natural_order5, jpeg_natural_order6, jpeg_natural_order7, long(), MAX, MAX_COMPONENTS, MAX_SAMP_FACTOR, NULL, jpeg_component_info::quant_table, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
jinit_input_controller (j_decompress_ptr cinfo)
References consume_markers(), jpeg_input_controller::eoi_reached, finish_input_pass(), jpeg_input_controller::has_multiple_scans, my_input_controller::inheaders, JPOOL_PERMANENT, my_input_controller::pub, reset_input_controller(), SIZEOF, and start_input_pass().
Referenced by jpeg_CreateDecompress().
latch_quant_tables (j_decompress_ptr cinfo)
References compptr, JPOOL_IMAGE, MEMCOPY, NULL, NUM_QUANT_TBLS, jpeg_component_info::quant_table, jpeg_component_info::quant_tbl_no, and SIZEOF.
Referenced by start_input_pass().
METHODDEF (int)
References compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, jdiv_round_up(), and long().
per_scan_setup (j_decompress_ptr cinfo)
References compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, int(), jdiv_round_up(), jpeg_component_info::last_col_width, jpeg_component_info::last_row_height, long(), MAX_COMPS_IN_SCAN, jpeg_component_info::MCU_blocks, jpeg_component_info::MCU_height, jpeg_component_info::MCU_sample_width, jpeg_component_info::MCU_width, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
reset_input_controller (j_decompress_ptr cinfo)
References consume_markers(), jpeg_input_controller::eoi_reached, jpeg_input_controller::has_multiple_scans, my_input_controller::inheaders, NULL, and my_input_controller::pub.
Referenced by jinit_input_controller().
start_input_pass (j_decompress_ptr cinfo)
References latch_quant_tables(), and per_scan_setup().