ioquake3: code/libspeex/kiss_fftr.h File Reference
kiss_fftr.h File Reference
#include "kiss_fft.h"
Defines
#define kiss_fftr_free speex_free
Typedefs
typedef struct kiss_fftr_state * kiss_fftr_cfg
Functions
kiss_fftr_cfg kiss_fftr_alloc (int nfft, int inverse_fft, void *mem, size_t *lenmem)
void kiss_fftr (kiss_fftr_cfg cfg, const kiss_fft_scalar *timedata, kiss_fft_cpx *freqdata)
void kiss_fftr2 (kiss_fftr_cfg st, const kiss_fft_scalar *timedata, kiss_fft_scalar *freqdata)
void kiss_fftri (kiss_fftr_cfg cfg, const kiss_fft_cpx *freqdata, kiss_fft_scalar *timedata)
void kiss_fftri2 (kiss_fftr_cfg st, const kiss_fft_scalar *freqdata, kiss_fft_scalar *timedata)
Define Documentation
#define kiss_fftr_free speex_free
Referenced by spx_fft_destroy().
Typedef Documentation
typedef struct kiss_fftr_state* kiss_fftr_cfg
Function Documentation
void kiss_fftr (kiss_fftr_cfg cfg, const kiss_fft_scalar * timedata, kiss_fft_cpx * freqdata)
References C_ADD, C_FIXDIV, C_MUL, C_SUB, CHECK_OVERFLOW_OP, HALF_OF, kiss_fft_cpx::i, kiss_fft_state::inverse, kiss_fft(), kiss_fft_state::nfft, kiss_fft_cpx::r, speex_fatal, kiss_fftr_state::substate, kiss_fftr_state::super_twiddles, and kiss_fftr_state::tmpbuf.
void kiss_fftr2 (kiss_fftr_cfg st, const kiss_fft_scalar * timedata, kiss_fft_scalar * freqdata)
References ADD32, C_FIXDIV, CHECK_OVERFLOW_OP, EXTEND32, kiss_fft_cpx::i, kiss_fft_state::inverse, kiss_fft(), MULT16_16, kiss_fft_state::nfft, PSHR32, kiss_fft_cpx::r, SHL32, SHR32, speex_fatal, SUB32, kiss_fftr_state::substate, kiss_fftr_state::super_twiddles, and kiss_fftr_state::tmpbuf.
Referenced by spx_fft().
kiss_fftr_cfg kiss_fftr_alloc (int nfft, int inverse_fft, void * mem, size_t * lenmem)
References DIV32, kf_cexp, kf_cexp2, kiss_fft_alloc(), KISS_FFT_MALLOC, NULL, SHL32, speex_warning(), kiss_fftr_state::substate, kiss_fftr_state::super_twiddles, and kiss_fftr_state::tmpbuf.
Referenced by spx_fft_init().
void kiss_fftri (kiss_fftr_cfg cfg, const kiss_fft_cpx * freqdata, kiss_fft_scalar * timedata)
References C_ADD, C_MUL, C_SUB, kiss_fft_cpx::i, kiss_fft_state::inverse, kiss_fft(), kiss_fft_state::nfft, kiss_fft_cpx::r, speex_fatal, kiss_fftr_state::substate, kiss_fftr_state::super_twiddles, and kiss_fftr_state::tmpbuf.
void kiss_fftri2 (kiss_fftr_cfg st, const kiss_fft_scalar * freqdata, kiss_fft_scalar * timedata)
References C_ADD, C_MUL, C_SUB, kiss_fft_cpx::i, kiss_fft_state::inverse, kiss_fft(), kiss_fft_state::nfft, kiss_fft_cpx::r, speex_fatal, kiss_fftr_state::substate, kiss_fftr_state::super_twiddles, and kiss_fftr_state::tmpbuf.
Referenced by spx_ifft().