ioquake3: code/libspeex/kiss_fft.c File Reference
kiss_fft.c File Reference
#include "_kiss_fft_guts.h"
#include "arch.h"
#include "os_support.h"
Functions
static void kf_bfly2 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m, int N, int mm)
static void kf_bfly4 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m, int N, int mm)
static void kf_bfly3 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, size_t m)
static void kf_bfly5 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m)
static void kf_bfly_generic (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m, int p)
static void kf_shuffle (kiss_fft_cpx *Fout, const kiss_fft_cpx *f, const size_t fstride, int in_stride, int *factors, const kiss_fft_cfg st)
static void kf_work (kiss_fft_cpx *Fout, const kiss_fft_cpx *f, const size_t fstride, int in_stride, int *factors, const kiss_fft_cfg st, int N, int s2, int m2)
static void kf_factor (int n, int *facbuf)
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void *mem, size_t *lenmem)
void kiss_fft_stride (kiss_fft_cfg st, const kiss_fft_cpx *fin, kiss_fft_cpx *fout, int in_stride)
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout)
Function Documentation
static void kf_bfly2 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m, int N, int mm) [static]
References ADD32, C_ADDTO, C_MUL, C_SUB, EXTEND32, kiss_fft_cpx::i, kiss_fft_state::inverse, m, MULT16_16, N, PSHR32, kiss_fft_cpx::r, SHL32, SHR32, SUB32, t, tr, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly3 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, size_t m) [static]
References C_ADD, C_ADDTO, C_FIXDIV, C_MUL, C_MULBYSCALAR, C_SUB, HALF_OF, kiss_fft_cpx::i, kiss_fft_state::inverse, m, kiss_fft_cpx::r, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly4 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m, int N, int mm) [static]
References C_ADD, C_ADDTO, C_MUL, C_MUL4, C_SUB, kiss_fft_cpx::i, kiss_fft_state::inverse, m, N, PSHR16, kiss_fft_cpx::r, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly5 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m) [static]
References C_ADD, C_FIXDIV, C_MUL, C_SUB, kiss_fft_cpx::i, kiss_fft_state::inverse, m, kiss_fft_cpx::r, S_MUL, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly_generic (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m, int p) [static]
References C_ADDTO, C_FIXDIV, C_MUL, kiss_fft_state::inverse, m, kiss_fft_state::nfft, speex_fatal, t, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_factor (int n, int * facbuf) [static]
References n.
Referenced by kiss_fft_alloc().
static void kf_shuffle (kiss_fft_cpx * Fout, const kiss_fft_cpx * f, const size_t fstride, int in_stride, int * factors, const kiss_fft_cfg st) [static]
References m.
Referenced by kiss_fft_stride().
static void kf_work (kiss_fft_cpx * Fout, const kiss_fft_cpx * f, const size_t fstride, int in_stride, int * factors, const kiss_fft_cfg st, int N, int s2, int m2) [static]
References kf_bfly2(), kf_bfly3(), kf_bfly4(), kf_bfly5(), kf_bfly_generic(), m, and N.
Referenced by kiss_fft_stride().
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout)
References kiss_fft_stride().
Referenced by kiss_fftr(), kiss_fftr2(), kiss_fftri(), and kiss_fftri2().
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void * mem, size_t * lenmem)
References DIV32, kiss_fft_state::factors, kiss_fft_state::inverse, kf_cexp, kf_cexp2, kf_factor(), KISS_FFT_MALLOC, kiss_fft_state::nfft, NULL, SHL32, and kiss_fft_state::twiddles.
Referenced by kiss_fftr_alloc().
void kiss_fft_stride (kiss_fft_cfg st, const kiss_fft_cpx * fin, kiss_fft_cpx * fout, int in_stride)
References kiss_fft_state::factors, kf_shuffle(), kf_work(), and speex_fatal.
Referenced by kiss_fft().