ioquake3: code/botlib/l_crc.c File Reference
l_crc.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "../qcommon/q_shared.h"
#include "botlib.h"
#include "be_interface.h"
#include "l_crc.h"
Defines
#define CRC_INIT_VALUE 0xffff
#define CRC_XOR_VALUE 0x0000
Functions
void CRC_Init (unsigned short *crcvalue)
void CRC_ProcessByte (unsigned short *crcvalue, byte data)
unsigned short CRC_Value (unsigned short crcvalue)
unsigned short CRC_ProcessString (unsigned char *data, int length)
void CRC_ContinueProcessString (unsigned short *crc, char *data, int length)
Variables
unsigned short crctable [257]
Define Documentation
#define CRC_INIT_VALUE 0xffff
Referenced by CRC_Init().
#define CRC_XOR_VALUE 0x0000
Referenced by CRC_Value().
Function Documentation
void CRC_ContinueProcessString (unsigned short * crc, char * data, int length)
References length().
void CRC_Init (unsigned short * crcvalue)
Referenced by CRC_ProcessString().
void CRC_ProcessByte (unsigned short * crcvalue, byte data)
unsigned short CRC_ProcessString (unsigned char * data, int length)
References CRC_Init(), CRC_Value(), crctable, and length().
Referenced by AAS_ReadRouteCache(), and AAS_WriteRouteCache().
unsigned short CRC_Value (unsigned short crcvalue)
Referenced by CRC_ProcessString().
Variable Documentation
unsigned short crctable[257]
Referenced by CRC_ProcessString().