ioquake3: code/botlib/l_libvar.h File Reference
l_libvar.h File Reference
Data Structures
struct libvar_s
Typedefs
typedef struct libvar_s libvar_t
Functions
void LibVarDeAllocAll (void)
libvar_t * LibVarGet (char *var_name)
char * LibVarGetString (char *var_name)
float LibVarGetValue (char *var_name)
libvar_t * LibVar (char *var_name, char *value)
float LibVarValue (char *var_name, char *value)
char * LibVarString (char *var_name, char *value)
void LibVarSet (char *var_name, char *value)
qboolean LibVarChanged (char *var_name)
void LibVarSetNotModified (char *var_name)
Typedef Documentation
typedef struct libvar_s libvar_t
Function Documentation
libvar_t* LibVar (char * var_name, char * value)
References GetMemory(), LibVarAlloc(), LibVarGet(), LibVarStringValue(), libvar_s::modified, qtrue, libvar_s::string, and libvar_s::value.
Referenced by AAS_Setup(), BotSetupGoalAI(), BotSetupMoveAI(), LibVarString(), and LibVarValue().
qboolean LibVarChanged (char * var_name)
References LibVarGet(), libvar_s::modified, and qfalse.
void LibVarDeAllocAll (void)
References LibVarDeAlloc(), libvarlist, libvar_s::next, and NULL.
Referenced by Export_BotLibShutdown().
libvar_t* LibVarGet (char * var_name)
References libvar_s::name, libvar_s::next, NULL, and Q_stricmp().
Referenced by LibVar(), LibVarChanged(), LibVarGetString(), LibVarGetValue(), LibVarSet(), and LibVarSetNotModified().
char* LibVarGetString (char * var_name)
References LibVarGet(), and libvar_s::string.
Referenced by AAS_LoadAASFile(), Export_BotLibSetup(), and Export_BotLibVarGet().
float LibVarGetValue (char * var_name)
References LibVarGet(), and libvar_s::value.
Referenced by AAS_ContinueInit(), AAS_InitClustering(), AAS_InitReachability(), AAS_StartFrame(), BotEnterChat(), BotExportTest(), BotFreeCharacter(), BotFreeChatState(), BotLoadCharacterSkill(), BotLoadChatFile(), BotNumInitialChats(), BotReplyChat(), Export_BotLibSetup(), FreeWeightConfig(), and ReadWeightConfig().
void LibVarSet (char * var_name, char * value)
References FreeMemory(), GetMemory(), LibVarAlloc(), LibVarGet(), LibVarStringValue(), libvar_s::modified, qtrue, libvar_s::string, and libvar_s::value.
Referenced by AAS_StartFrame(), Export_BotLibVarSet(), LoadItemConfig(), and LoadWeaponConfig().
void LibVarSetNotModified (char * var_name)
References LibVarGet(), libvar_s::modified, and qfalse.
char* LibVarString (char * var_name, char * value)
References LibVar(), and libvar_s::string.
Referenced by BotSetupChatAI(), BotSetupGoalAI(), and BotSetupWeaponAI().
float LibVarValue (char * var_name, char * value)
References LibVar(), and libvar_s::value.
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_ContinueInit(), AAS_InitAASLinkHeap(), AAS_InitRouting(), AAS_InitSettings(), AAS_Reachability_JumpPad(), AAS_Setup(), BotSetupChatAI(), BotSetupGoalAI(), Export_BotLibSetup(), InitConsoleMessageHeap(), InitLevelItemHeap(), LoadItemConfig(), LoadWeaponConfig(), and Log_Open().