ioquake3: code/botlib/l_precomp.c File Reference
l_precomp.c File Reference
Data Structures
struct directive_s
struct operator_s
struct value_s
Defines
#define MAX_DEFINEPARMS 128
#define DEFINEHASHING 1
#define DEFINEHASHSIZE 1024
#define TOKEN_HEAP_SIZE 4096
#define MAX_VALUES 64
#define MAX_OPERATORS 64
#define AllocValue(val)
#define FreeValue(val)
#define AllocOperator(op)
#define FreeOperator(op)
#define MAX_SOURCEFILES 64
Typedefs
typedef struct directive_s directive_t
typedef struct operator_s operator_t
typedef struct value_s value_t
Functions
void QDECL SourceError (source_t *source, char *str,...)
void QDECL SourceWarning (source_t *source, char *str,...)
void PC_PushIndent (source_t *source, int type, int skip)
void PC_PopIndent (source_t *source, int *type, int *skip)
void PC_PushScript (source_t *source, script_t *script)
void PC_InitTokenHeap (void)
token_t * PC_CopyToken (token_t *token)
void PC_FreeToken (token_t *token)
int PC_ReadSourceToken (source_t *source, token_t *token)
int PC_UnreadSourceToken (source_t *source, token_t *token)
int PC_ReadDefineParms (source_t *source, define_t *define, token_t **parms, int maxparms)
int PC_StringizeTokens (token_t *tokens, token_t *token)
int PC_MergeTokens (token_t *t1, token_t *t2)
void PC_PrintDefineHashTable (define_t **definehash)
int PC_NameHash (char *name)
void PC_AddDefineToHash (define_t *define, define_t **definehash)
define_t * PC_FindHashedDefine (define_t **definehash, char *name)
define_t * PC_FindDefine (define_t *defines, char *name)
int PC_FindDefineParm (define_t *define, char *name)
void PC_FreeDefine (define_t *define)
void PC_AddBuiltinDefines (source_t *source)
int PC_ExpandBuiltinDefine (source_t *source, token_t *deftoken, define_t *define, token_t **firsttoken, token_t **lasttoken)
int PC_ExpandDefine (source_t *source, token_t *deftoken, define_t *define, token_t **firsttoken, token_t **lasttoken)
int PC_ExpandDefineIntoSource (source_t *source, token_t *deftoken, define_t *define)
void PC_ConvertPath (char *path)
int PC_Directive_include (source_t *source)
int PC_ReadLine (source_t *source, token_t *token)
int PC_WhiteSpaceBeforeToken (token_t *token)
void PC_ClearTokenWhiteSpace (token_t *token)
int PC_Directive_undef (source_t *source)
int PC_Directive_define (source_t *source)
define_t * PC_DefineFromString (char *string)
int PC_AddDefine (source_t *source, char *string)
int PC_AddGlobalDefine (char *string)
int PC_RemoveGlobalDefine (char *name)
void PC_RemoveAllGlobalDefines (void)
define_t * PC_CopyDefine (source_t *source, define_t *define)
void PC_AddGlobalDefinesToSource (source_t *source)
int PC_Directive_if_def (source_t *source, int type)
int PC_Directive_ifdef (source_t *source)
int PC_Directive_ifndef (source_t *source)
int PC_Directive_else (source_t *source)
int PC_Directive_endif (source_t *source)
int PC_OperatorPriority (int op)
int PC_EvaluateTokens (source_t *source, token_t *tokens, signed long int *intvalue, float *floatvalue, int integer)
int PC_Evaluate (source_t *source, signed long int *intvalue, float *floatvalue, int integer)
int PC_DollarEvaluate (source_t *source, signed long int *intvalue, float *floatvalue, int integer)
int PC_Directive_elif (source_t *source)
int PC_Directive_if (source_t *source)
int PC_Directive_line (source_t *source)
int PC_Directive_error (source_t *source)
int PC_Directive_pragma (source_t *source)
void UnreadSignToken (source_t *source)
int PC_Directive_eval (source_t *source)
int PC_Directive_evalfloat (source_t *source)
int PC_ReadDirective (source_t *source)
int PC_DollarDirective_evalint (source_t *source)
int PC_DollarDirective_evalfloat (source_t *source)
int PC_ReadDollarDirective (source_t *source)
int PC_ReadToken (source_t *source, token_t *token)
int PC_ExpectTokenString (source_t *source, char *string)
int PC_ExpectTokenType (source_t *source, int type, int subtype, token_t *token)
int PC_ExpectAnyToken (source_t *source, token_t *token)
int PC_CheckTokenString (source_t *source, char *string)
int PC_CheckTokenType (source_t *source, int type, int subtype, token_t *token)
int PC_SkipUntilString (source_t *source, char *string)
void PC_UnreadLastToken (source_t *source)
void PC_UnreadToken (source_t *source, token_t *token)
void PC_SetIncludePath (source_t *source, char *path)
void PC_SetPunctuations (source_t *source, punctuation_t *p)
source_t * LoadSourceFile (const char *filename)
source_t * LoadSourceMemory (char *ptr, int length, char *name)
void FreeSource (source_t *source)
int PC_LoadSourceHandle (const char *filename)
int PC_FreeSourceHandle (int handle)
int PC_ReadTokenHandle (int handle, pc_token_t *pc_token)
int PC_SourceFileAndLine (int handle, char *filename, int *line)
void PC_SetBaseFolder (char *path)
void PC_CheckOpenSourceHandles (void)
Variables
int numtokens
define_t * globaldefines
directive_t directives [20]
directive_t dollardirectives [20]
source_t * sourceFiles [MAX_SOURCEFILES]
Define Documentation
#define AllocOperator (op)
Value:
if (numoperators >= MAX_OPERATORS) {                            \
                SourceError(source, "out of operator space\n"); \
                error = 1;                                                                              \
                break;                                                                                  \
        }                                                                                                       \
        else                                                                                            \
                op = &operator_heap[numoperators++];
Referenced by PC_EvaluateTokens().
#define AllocValue (val)
Value:
if (numvalues >= MAX_VALUES) {                                          \
                SourceError(source, "out of value space\n");            \
                error = 1;                                                                              \
                break;                                                                                  \
        }                                                                                                       \
        else                                                                                            \
                val = &value_heap[numvalues++];
Referenced by PC_EvaluateTokens().
#define DEFINEHASHING 1
#define DEFINEHASHSIZE 1024
Referenced by FreeSource(), LoadSourceFile(), LoadSourceMemory(), PC_DefineFromString(), PC_NameHash(), and PC_PrintDefineHashTable().
#define FreeOperator (op)
Referenced by PC_EvaluateTokens().
#define FreeValue (val)
Referenced by PC_EvaluateTokens().
#define MAX_DEFINEPARMS 128
Referenced by PC_ExpandDefine().
#define MAX_OPERATORS 64
Referenced by PC_EvaluateTokens().
#define MAX_SOURCEFILES 64
Referenced by PC_CheckOpenSourceHandles(), PC_FreeSourceHandle(), PC_LoadSourceHandle(), PC_ReadTokenHandle(), and PC_SourceFileAndLine().
#define MAX_VALUES 64
Referenced by PC_EvaluateTokens().
#define TOKEN_HEAP_SIZE 4096
Typedef Documentation
typedef struct directive_s directive_t
typedef struct operator_s operator_t
typedef struct value_s value_t
Function Documentation
void FreeSource (source_t * source)
References source_s::definehash, DEFINEHASHSIZE, source_s::defines, FreeMemory(), FreeScript(), define_s::hashnext, source_s::indentstack, define_s::next, indent_s::next, script_s::next, PC_FreeDefine(), PC_FreeToken(), source_s::scriptstack, token, and source_s::tokens.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), PC_FreeSourceHandle(), and ReadWeightConfig().
source_t* LoadSourceFile (const char * filename)
References Com_Memset, source_s::definehash, DEFINEHASHSIZE, source_s::defines, source_s::filename, GetClearedMemory(), GetMemory(), source_s::indentstack, LoadScriptFile(), MAX_PATH, script_s::next, NULL, PC_AddGlobalDefinesToSource(), PC_InitTokenHeap(), source_s::scriptstack, source_s::skip, and source_s::tokens.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), PC_LoadSourceHandle(), ReadWeightConfig(), and stabline().
source_t* LoadSourceMemory (char * ptr, int length, char * name)
References Com_Memset, source_s::definehash, DEFINEHASHSIZE, source_s::defines, source_s::filename, GetClearedMemory(), GetMemory(), source_s::indentstack, LoadScriptMemory(), MAX_PATH, script_s::next, NULL, PC_AddGlobalDefinesToSource(), PC_InitTokenHeap(), source_s::scriptstack, source_s::skip, and source_s::tokens.
void PC_AddBuiltinDefines (source_t * source)
References define_s::builtin, builtin(), BUILTIN_DATE, BUILTIN_FILE, BUILTIN_LINE, BUILTIN_TIME, Com_Memset, DEFINE_FIXED, source_s::definehash, source_s::defines, define_s::flags, GetMemory(), define_s::name, define_s::next, NULL, PC_AddDefineToHash(), and string().
int PC_AddDefine (source_t * source, char * string)
References source_s::definehash, source_s::defines, define_s::next, PC_AddDefineToHash(), PC_DefineFromString(), qfalse, and qtrue.
void PC_AddDefineToHash (define_t * define, define_t ** definehash)
References hash(), define_s::hashnext, define_s::name, and PC_NameHash().
Referenced by PC_AddBuiltinDefines(), PC_AddDefine(), PC_AddGlobalDefinesToSource(), and PC_Directive_define().
int PC_AddGlobalDefine (char * string)
References globaldefines, define_s::next, PC_DefineFromString(), qfalse, and qtrue.
Referenced by GetBotLibAPI().
void PC_AddGlobalDefinesToSource (source_t * source)
References source_s::definehash, source_s::defines, define_s::next, PC_AddDefineToHash(), and PC_CopyDefine().
Referenced by LoadSourceFile(), and LoadSourceMemory().
void PC_CheckOpenSourceHandles (void)
References botimport, source_s::filename, MAX_SOURCEFILES, and PRT_ERROR.
Referenced by Export_BotLibShutdown().
int PC_CheckTokenString (source_t * source, char * string)
References PC_ReadToken(), PC_UnreadSourceToken(), qfalse, and qtrue.
Referenced by BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), PC_Directive_define(), ReadFuzzyWeight(), and ReadStructure().
int PC_CheckTokenType (source_t * source, int type, int subtype, token_t * token)
References Com_Memcpy, PC_ReadToken(), PC_UnreadSourceToken(), qfalse, and qtrue.
void PC_ClearTokenWhiteSpace (token_t * token)
References NULL.
Referenced by PC_Directive_define().
void PC_ConvertPath (char * path)
References memmove(), PATHSEPERATOR_CHAR, and ptr().
Referenced by PC_Directive_include().
define_t* PC_CopyDefine (source_t * source, define_t * define)
References define_s::builtin, define_s::flags, GetMemory(), define_s::hashnext, define_s::name, define_s::next, NULL, define_s::numparms, define_s::parms, PC_CopyToken(), token, and define_s::tokens.
Referenced by PC_AddGlobalDefinesToSource().
token_t* PC_CopyToken (token_t * token)
References Com_Error(), Com_Memcpy, ERR_FATAL, Error(), GetMemory(), NULL, numtokens, and t.
Referenced by PC_CopyDefine(), PC_Directive_define(), PC_DollarEvaluate(), PC_Evaluate(), PC_ExpandBuiltinDefine(), PC_ExpandDefine(), PC_ReadDefineParms(), and PC_UnreadSourceToken().
define_t* PC_DefineFromString (char * string)
References Com_Memset, source_s::definehash, DEFINEHASHSIZE, source_s::defines, source_s::filename, FreeMemory(), FreeScript(), GetClearedMemory(), LoadScriptMemory(), MAX_PATH, NULL, PC_Directive_define(), PC_FreeDefine(), PC_FreeToken(), PC_InitTokenHeap(), source_s::scriptstack, src, t, and source_s::tokens.
Referenced by PC_AddDefine(), and PC_AddGlobalDefine().
int PC_Directive_define (source_t * source)
References Com_Memset, DEFINE_FIXED, source_s::definehash, source_s::defines, define_s::flags, GetMemory(), define_s::name, define_s::next, NULL, define_s::numparms, define_s::parms, PC_AddDefineToHash(), PC_CheckTokenString(), PC_ClearTokenWhiteSpace(), PC_CopyToken(), PC_Directive_undef(), PC_FindDefine(), PC_FindDefineParm(), PC_FindHashedDefine(), PC_ReadLine(), PC_UnreadSourceToken(), PC_WhiteSpaceBeforeToken(), qfalse, qtrue, source_s::skip, SourceError(), SourceWarning(), t, token, define_s::tokens, and TT_NAME.
Referenced by PC_DefineFromString().
int PC_Directive_elif (source_t * source)
References INDENT_ELIF, INDENT_ELSE, NULL, PC_Evaluate(), PC_PopIndent(), PC_PushIndent(), qfalse, qtrue, SourceError(), type(), and value().
int PC_Directive_else (source_t * source)
References INDENT_ELSE, PC_PopIndent(), PC_PushIndent(), qfalse, qtrue, SourceError(), and type().
int PC_Directive_endif (source_t * source)
References PC_PopIndent(), qfalse, qtrue, SourceError(), and type().
int PC_Directive_error (source_t * source)
References PC_ReadSourceToken(), qfalse, SourceError(), and token.
int PC_Directive_eval (source_t * source)
References abs(), script_s::line, NULL, PC_Evaluate(), PC_UnreadSourceToken(), qfalse, qtrue, script_s::script_p, source_s::scriptstack, token, TT_DECIMAL, TT_INTEGER, TT_LONG, TT_NUMBER, UnreadSignToken(), and value().
int PC_Directive_evalfloat (source_t * source)
References script_s::line, NULL, PC_Evaluate(), PC_UnreadSourceToken(), qfalse, qtrue, script_s::script_p, source_s::scriptstack, token, TT_DECIMAL, TT_FLOAT, TT_LONG, TT_NUMBER, UnreadSignToken(), and value().
int PC_Directive_if (source_t * source)
References INDENT_IF, NULL, PC_Evaluate(), PC_PushIndent(), qfalse, qtrue, and value().
int PC_Directive_if_def (source_t * source, int type)
References source_s::definehash, source_s::defines, INDENT_IFDEF, NULL, PC_FindDefine(), PC_FindHashedDefine(), PC_PushIndent(), PC_ReadLine(), PC_UnreadSourceToken(), qfalse, qtrue, SourceError(), token, and TT_NAME.
Referenced by PC_Directive_ifdef(), and PC_Directive_ifndef().
int PC_Directive_ifdef (source_t * source)
References INDENT_IFDEF, and PC_Directive_if_def().
int PC_Directive_ifndef (source_t * source)
References INDENT_IFNDEF, and PC_Directive_if_def().
int PC_Directive_include (source_t * source)
References Com_Memset, file, script_s::filename, source_s::includepath, LoadScriptFile(), MAX_PATH, PC_ConvertPath(), PC_PushScript(), PC_ReadSourceToken(), PC_UnreadSourceToken(), qfalse, qtrue, source_s::skip, SourceError(), SourceWarning(), StripDoubleQuotes(), token, TT_PUNCTUATION, and TT_STRING.
int PC_Directive_line (source_t * source)
References qfalse, and SourceError().
int PC_Directive_pragma (source_t * source)
References PC_ReadLine(), qtrue, SourceWarning(), and token.
int PC_Directive_undef (source_t * source)
References DEFINE_FIXED, source_s::definehash, source_s::defines, define_s::flags, hash(), define_s::hashnext, define_s::name, define_s::next, NULL, PC_FreeDefine(), PC_NameHash(), PC_ReadLine(), PC_UnreadSourceToken(), qfalse, qtrue, source_s::skip, SourceError(), SourceWarning(), token, and TT_NAME.
Referenced by PC_Directive_define().
int PC_DollarDirective_evalfloat (source_t * source)
References script_s::line, long(), NULL, PC_DollarEvaluate(), PC_UnreadSourceToken(), qfalse, qtrue, script_s::script_p, source_s::scriptstack, token, TT_DECIMAL, TT_FLOAT, TT_LONG, TT_NUMBER, UnreadSignToken(), and value().
int PC_DollarDirective_evalint (source_t * source)
References abs(), script_s::line, NULL, PC_DollarEvaluate(), PC_UnreadSourceToken(), qfalse, qtrue, script_s::script_p, source_s::scriptstack, token, TT_DECIMAL, TT_INTEGER, TT_LONG, TT_NUMBER, UnreadSignToken(), and value().
int PC_DollarEvaluate (source_t * source, signed long int * intvalue, float * floatvalue, int integer)
References source_s::definehash, source_s::defines, Log_Write(), NULL, PC_CopyToken(), PC_EvaluateTokens(), PC_ExpandDefineIntoSource(), PC_FindDefine(), PC_FindHashedDefine(), PC_FreeToken(), PC_ReadSourceToken(), qfalse, qtrue, SourceError(), t, token, TT_NAME, TT_NUMBER, and TT_PUNCTUATION.
Referenced by PC_DollarDirective_evalfloat(), and PC_DollarDirective_evalint().
int PC_Evaluate (source_t * source, signed long int * intvalue, float * floatvalue, int integer)
References source_s::definehash, source_s::defines, Log_Write(), NULL, PC_CopyToken(), PC_EvaluateTokens(), PC_ExpandDefineIntoSource(), PC_FindDefine(), PC_FindHashedDefine(), PC_FreeToken(), PC_ReadLine(), qfalse, qtrue, SourceError(), t, token, TT_NAME, TT_NUMBER, and TT_PUNCTUATION.
Referenced by PC_Directive_elif(), PC_Directive_eval(), PC_Directive_evalfloat(), and PC_Directive_if().
int PC_EvaluateTokens (source_t * source, token_t * tokens, signed long int * intvalue, float * floatvalue, int integer)
References AllocOperator, AllocValue, source_s::definehash, source_s::defines, error(), value_s::floatvalue, FreeOperator, FreeValue, int(), value_s::intvalue, Log_Write(), MAX_OPERATORS, MAX_VALUES, operator_s::next, value_s::next, NULL, operator_s::operator, P_ADD, P_BIN_AND, P_BIN_NOT, P_BIN_OR, P_BIN_XOR, P_COLON, P_DEC, P_DIV, P_INC, P_LOGIC_AND, P_LOGIC_EQ, P_LOGIC_GEQ, P_LOGIC_GREATER, P_LOGIC_LEQ, P_LOGIC_LESS, P_LOGIC_NOT, P_LOGIC_OR, P_LOGIC_UNEQ, P_LSHIFT, P_MOD, P_MUL, P_PARENTHESESCLOSE, P_PARENTHESESOPEN, P_QUESTIONMARK, P_RSHIFT, P_SUB, operator_s::parentheses, value_s::parentheses, PC_FindDefine(), PC_FindHashedDefine(), PC_OperatorPriority(), operator_s::prev, value_s::prev, operator_s::priority, PunctuationFromNum(), qfalse, qtrue, source_s::scriptstack, SourceError(), t, TT_NAME, TT_NUMBER, and TT_PUNCTUATION.
Referenced by PC_DollarEvaluate(), and PC_Evaluate().
int PC_ExpandBuiltinDefine (source_t * source, token_t * deftoken, define_t * define, token_t ** firsttoken, token_t ** lasttoken)
References define_s::builtin, BUILTIN_DATE, BUILTIN_FILE, BUILTIN_LINE, BUILTIN_STDC, BUILTIN_TIME, curtime, script_s::filename, NULL, PC_CopyToken(), qtrue, source_s::scriptstack, t, token, TT_DECIMAL, TT_INTEGER, TT_NAME, and TT_NUMBER.
Referenced by PC_ExpandDefine().
int PC_ExpandDefine (source_t * source, token_t * deftoken, define_t * define, token_t ** firsttoken, token_t ** lasttoken)
References define_s::builtin, first, Log_Write(), MAX_DEFINEPARMS, block::next, define_s::next, NULL, define_s::numparms, PC_CopyToken(), PC_ExpandBuiltinDefine(), PC_FindDefineParm(), PC_FreeToken(), PC_MergeTokens(), PC_ReadDefineParms(), PC_StringizeTokens(), qfalse, qtrue, SourceError(), SourceWarning(), t, token, define_s::tokens, and TT_NAME.
Referenced by PC_ExpandDefineIntoSource().
int PC_ExpandDefineIntoSource (source_t * source, token_t * deftoken, define_t * define)
References PC_ExpandDefine(), qfalse, qtrue, and source_s::tokens.
Referenced by PC_DollarEvaluate(), PC_Evaluate(), and PC_ReadToken().
int PC_ExpectAnyToken (source_t * source, token_t * token)
References PC_ReadToken(), qfalse, qtrue, and SourceError().
Referenced by BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), ReadChar(), ReadFuzzySeperators_r(), ReadNumber(), ReadStructure(), ReadValue(), and ReadWeightConfig().
int PC_ExpectTokenString (source_t * source, char * string)
References PC_ReadToken(), qfalse, qtrue, SourceError(), and token.
Referenced by BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), ReadFuzzySeperators_r(), ReadFuzzyWeight(), ReadStructure(), and ReadWeightConfig().
int PC_ExpectTokenType (source_t * source, int type, int subtype, token_t * token)
References MAX_TOKEN, PC_ReadToken(), qfalse, qtrue, SourceError(), TT_BINARY, TT_DECIMAL, TT_FLOAT, TT_HEX, TT_INTEGER, TT_LITERAL, TT_LONG, TT_NAME, TT_NUMBER, TT_OCTAL, TT_PUNCTUATION, TT_STRING, and TT_UNSIGNED.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), ReadFuzzySeperators_r(), ReadString(), and ReadWeightConfig().
define_t* PC_FindDefine (define_t * defines, char * name)
References define_s::name, define_s::next, and NULL.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ReadToken(), and PC_RemoveGlobalDefine().
int PC_FindDefineParm (define_t * define, char * name)
References define_s::parms.
Referenced by PC_Directive_define(), and PC_ExpandDefine().
define_t* PC_FindHashedDefine (define_t ** definehash, char * name)
References hash(), define_s::hashnext, define_s::name, NULL, and PC_NameHash().
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), and PC_ReadToken().
void PC_FreeDefine (define_t * define)
References FreeMemory(), define_s::name, define_s::parms, PC_FreeToken(), t, and define_s::tokens.
Referenced by FreeSource(), PC_DefineFromString(), PC_Directive_undef(), PC_RemoveAllGlobalDefines(), and PC_RemoveGlobalDefine().
int PC_FreeSourceHandle (int handle)
References FreeSource(), MAX_SOURCEFILES, NULL, qfalse, and qtrue.
Referenced by GetBotLibAPI().
void PC_FreeToken (token_t * token)
References FreeMemory(), and numtokens.
Referenced by FreeSource(), PC_DefineFromString(), PC_DollarEvaluate(), PC_Evaluate(), PC_ExpandDefine(), PC_FreeDefine(), and PC_ReadSourceToken().
void PC_InitTokenHeap (void)
Referenced by LoadSourceFile(), LoadSourceMemory(), and PC_DefineFromString().
int PC_LoadSourceHandle (const char * filename)
References LoadSourceFile(), MAX_SOURCEFILES, and PS_SetBaseFolder().
Referenced by GetBotLibAPI().
int PC_MergeTokens (token_t * t1, token_t * t2)
References qfalse, qtrue, TT_NAME, TT_NUMBER, and TT_STRING.
Referenced by PC_ExpandDefine().
int PC_NameHash (char * name)
References DEFINEHASHSIZE, and hash().
Referenced by PC_AddDefineToHash(), PC_Directive_undef(), and PC_FindHashedDefine().
int PC_OperatorPriority (int op)
References P_ADD, P_BIN_AND, P_BIN_NOT, P_BIN_OR, P_BIN_XOR, P_COLON, P_DIV, P_LOGIC_AND, P_LOGIC_EQ, P_LOGIC_GEQ, P_LOGIC_GREATER, P_LOGIC_LEQ, P_LOGIC_LESS, P_LOGIC_NOT, P_LOGIC_OR, P_LOGIC_UNEQ, P_LSHIFT, P_MOD, P_MUL, P_QUESTIONMARK, P_RSHIFT, P_SUB, and qfalse.
Referenced by PC_EvaluateTokens().
void PC_PopIndent (source_t * source, int * type, int * skip)
References FreeMemory(), source_s::indentstack, indent_s::next, indent_s::script, source_s::scriptstack, indent_s::skip, source_s::skip, and indent_s::type.
Referenced by PC_Directive_elif(), PC_Directive_else(), PC_Directive_endif(), and PC_ReadSourceToken().
void PC_PrintDefineHashTable (define_t ** definehash)
References DEFINEHASHSIZE, define_s::hashnext, Log_Write(), and define_s::name.
void PC_PushIndent (source_t * source, int type, int skip)
References GetMemory(), source_s::indentstack, indent_s::next, indent_s::script, source_s::scriptstack, indent_s::skip, source_s::skip, type(), and indent_s::type.
Referenced by PC_Directive_elif(), PC_Directive_else(), PC_Directive_if(), and PC_Directive_if_def().
void PC_PushScript (source_t * source, script_t * script)
References script_s::filename, script_s::next, Q_stricmp(), s, source_s::scriptstack, and SourceError().
Referenced by PC_Directive_include().
int PC_ReadDefineParms (source_t * source, define_t * define, token_t ** parms, int maxparms)
References define_s::name, NULL, define_s::numparms, PC_CopyToken(), PC_ReadSourceToken(), PC_UnreadSourceToken(), qfalse, qtrue, SourceError(), SourceWarning(), t, and token.
Referenced by PC_ExpandDefine().
int PC_ReadDirective (source_t * source)
References directive_s::func, directive_s::name, PC_ReadSourceToken(), PC_UnreadSourceToken(), qfalse, SourceError(), token, and TT_NAME.
Referenced by PC_ReadToken().
int PC_ReadDollarDirective (source_t * source)
References directive_s::func, directive_s::name, PC_ReadSourceToken(), PC_UnreadSourceToken(), qfalse, SourceError(), token, and TT_NAME.
Referenced by PC_ReadToken().
int PC_ReadLine (source_t * source, token_t * token)
References PC_ReadSourceToken(), PC_UnreadSourceToken(), qfalse, and qtrue.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_Directive_pragma(), PC_Directive_undef(), and PC_Evaluate().
int PC_ReadSourceToken (source_t * source, token_t * token)
References Com_Memcpy, EndOfScript(), FreeScript(), source_s::indentstack, script_s::next, PC_FreeToken(), PC_PopIndent(), PS_ReadToken(), qfalse, qtrue, indent_s::script, source_s::scriptstack, SourceWarning(), t, source_s::tokens, and type().
Referenced by PC_Directive_error(), PC_Directive_include(), PC_DollarEvaluate(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadLine(), and PC_ReadToken().
int PC_ReadToken (source_t * source, token_t * token)
References Com_Memcpy, source_s::definehash, source_s::defines, MAX_TOKEN, PC_ExpandDefineIntoSource(), PC_FindDefine(), PC_FindHashedDefine(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadSourceToken(), PC_ReadToken(), PC_UnreadToken(), qfalse, qtrue, source_s::skip, SourceError(), source_s::token, TT_NAME, TT_PUNCTUATION, and TT_STRING.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), PC_CheckTokenString(), PC_CheckTokenType(), PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_ReadTokenHandle(), PC_SkipUntilString(), and ReadWeightConfig().
int PC_ReadTokenHandle (int handle, pc_token_t * pc_token)
References pc_token_s::floatvalue, pc_token_s::intvalue, MAX_SOURCEFILES, PC_ReadToken(), pc_token_s::string, StripDoubleQuotes(), pc_token_s::subtype, token, TT_STRING, and pc_token_s::type.
Referenced by GetBotLibAPI().
void PC_RemoveAllGlobalDefines (void)
References globaldefines, define_s::next, and PC_FreeDefine().
Referenced by Export_BotLibShutdown().
int PC_RemoveGlobalDefine (char * name)
References PC_FindDefine(), PC_FreeDefine(), qfalse, and qtrue.
void PC_SetBaseFolder (char * path)
References PS_SetBaseFolder().
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), and ReadWeightConfig().
void PC_SetIncludePath (source_t * source, char * path)
References source_s::includepath, MAX_PATH, and PATHSEPERATOR_STR.
void PC_SetPunctuations (source_t * source, punctuation_t * p)
References source_s::punctuations.
int PC_SkipUntilString (source_t * source, char * string)
References PC_ReadToken(), qfalse, qtrue, and token.
int PC_SourceFileAndLine (int handle, char * filename, int * line)
References script_s::line, MAX_SOURCEFILES, qfalse, qtrue, and source_s::scriptstack.
Referenced by GetBotLibAPI().
int PC_StringizeTokens (token_t * tokens, token_t * token)
References MAX_TOKEN, NULL, qtrue, t, and TT_STRING.
Referenced by PC_ExpandDefine().
void PC_UnreadLastToken (source_t * source)
References PC_UnreadSourceToken(), and source_s::token.
Referenced by BotLoadMatchTemplates(), and ReadChar().
int PC_UnreadSourceToken (source_t * source, token_t * token)
References PC_CopyToken(), qtrue, t, and source_s::tokens.
Referenced by PC_CheckTokenString(), PC_CheckTokenType(), PC_Directive_define(), PC_Directive_eval(), PC_Directive_evalfloat(), PC_Directive_if_def(), PC_Directive_include(), PC_Directive_undef(), PC_DollarDirective_evalfloat(), PC_DollarDirective_evalint(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadLine(), PC_UnreadLastToken(), PC_UnreadToken(), and UnreadSignToken().
void PC_UnreadToken (source_t * source, token_t * token)
References PC_UnreadSourceToken().
Referenced by PC_ReadToken().
int PC_WhiteSpaceBeforeToken (token_t * token)
Referenced by PC_Directive_define().
void QDECL SourceError (source_t * source, char * str, ...)
References botimport, script_s::filename, script_s::line, printf(), PRT_ERROR, Q_vsnprintf, and source_s::scriptstack.
Referenced by BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), PC_Directive_define(), PC_Directive_elif(), PC_Directive_else(), PC_Directive_endif(), PC_Directive_error(), PC_Directive_if_def(), PC_Directive_include(), PC_Directive_line(), PC_Directive_undef(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ExpandDefine(), PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_PushScript(), PC_ReadDefineParms(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadToken(), ReadFuzzySeperators_r(), ReadNumber(), ReadStructure(), ReadValue(), and ReadWeightConfig().
void QDECL SourceWarning (source_t * source, char * str, ...)
References botimport, script_s::filename, script_s::line, printf(), PRT_WARNING, Q_vsnprintf, and source_s::scriptstack.
Referenced by BotCheckValidReplyChatKeySet(), PC_Directive_define(), PC_Directive_include(), PC_Directive_pragma(), PC_Directive_undef(), PC_ExpandDefine(), PC_ReadDefineParms(), PC_ReadSourceToken(), ReadFuzzySeperators_r(), ReadValue(), and ReadWeightConfig().
void UnreadSignToken (source_t * source)
References script_s::line, P_SUB, PC_UnreadSourceToken(), script_s::script_p, source_s::scriptstack, token, and TT_PUNCTUATION.
Referenced by PC_Directive_eval(), PC_Directive_evalfloat(), PC_DollarDirective_evalfloat(), and PC_DollarDirective_evalint().
Variable Documentation
directive_t directives[20]
Initial value:
{
        {"if", PC_Directive_if},
        {"ifdef", PC_Directive_ifdef},
        {"ifndef", PC_Directive_ifndef},
        {"elif", PC_Directive_elif},
        {"else", PC_Directive_else},
        {"endif", PC_Directive_endif},
        {"include", PC_Directive_include},
        {"define", PC_Directive_define},
        {"undef", PC_Directive_undef},
        {"line", PC_Directive_line},
        {"error", PC_Directive_error},
        {"pragma", PC_Directive_pragma},
        {"eval", PC_Directive_eval},
        {"evalfloat", PC_Directive_evalfloat},
        {NULL, NULL}
}
directive_t dollardirectives[20]
Initial value:
{
        {"evalint", PC_DollarDirective_evalint},
        {"evalfloat", PC_DollarDirective_evalfloat},
        {NULL, NULL}
}
define_t* globaldefines
Referenced by PC_AddGlobalDefine(), and PC_RemoveAllGlobalDefines().
int numtokens
Referenced by PC_CopyToken(), and PC_FreeToken().
source_t* sourceFiles[MAX_SOURCEFILES]