ioquake3: code/botlib/l_struct.c File Reference
l_struct.c File Reference
Functions
fielddef_t * FindField (fielddef_t *defs, char *name)
qboolean ReadNumber (source_t *source, fielddef_t *fd, void *p)
qboolean ReadChar (source_t *source, fielddef_t *fd, void *p)
int ReadString (source_t *source, fielddef_t *fd, void *p)
int ReadStructure (source_t *source, structdef_t *def, char *structure)
int WriteIndent (FILE *fp, int indent)
int WriteFloat (FILE *fp, float value)
int WriteStructWithIndent (FILE *fp, structdef_t *def, char *structure, int indent)
int WriteStructure (FILE *fp, structdef_t *def, char *structure)
Function Documentation
fielddef_t* FindField (fielddef_t * defs, char * name)
References fielddef_s::name, and NULL.
Referenced by ReadStructure().
qboolean ReadChar (source_t * source, fielddef_t * fd, void * p)
References PC_ExpectAnyToken(), PC_UnreadLastToken(), ReadNumber(), StripSingleQuotes(), token, and TT_LITERAL.
Referenced by ReadStructure().
qboolean ReadNumber (source_t * source, fielddef_t * fd, void * p)
References fielddef_s::floatmax, fielddef_s::floatmin, FT_BOUNDED, FT_CHAR, FT_FLOAT, FT_INT, FT_TYPE, FT_UNSIGNED, Maximum, Minimum, PC_ExpectAnyToken(), qfalse, qtrue, SourceError(), token, TT_FLOAT, TT_NUMBER, TT_PUNCTUATION, and fielddef_s::type.
Referenced by ReadChar(), and ReadStructure().
int ReadString (source_t * source, fielddef_t * fd, void * p)
References MAX_STRINGFIELD, PC_ExpectTokenType(), StripDoubleQuotes(), token, and TT_STRING.
Referenced by ReadStructure().
int ReadStructure (source_t * source, structdef_t * def, char * structure)
References structdef_s::fields, FindField(), FT_ARRAY, FT_CHAR, FT_FLOAT, FT_INT, FT_STRING, FT_STRUCT, FT_TYPE, MAX_STRINGFIELD, fielddef_s::maxarray, fielddef_s::offset, PC_CheckTokenString(), PC_ExpectAnyToken(), PC_ExpectTokenString(), qfalse, qtrue, ReadChar(), ReadNumber(), ReadString(), ReadStructure(), structdef_s::size, SourceError(), fielddef_s::substruct, token, and fielddef_s::type.
Referenced by LoadItemConfig(), LoadWeaponConfig(), and ReadStructure().
int WriteFloat (FILE * fp, float value)
References Com_sprintf().
Referenced by WriteStructWithIndent().
int WriteIndent (FILE * fp, int indent)
References qfalse, and qtrue.
Referenced by WriteStructWithIndent().
int WriteStructure (FILE * fp, structdef_t * def, char * structure)
References WriteStructWithIndent().
int WriteStructWithIndent (FILE * fp, structdef_t * def, char * structure, int indent)
References structdef_s::fields, FT_ARRAY, FT_CHAR, FT_FLOAT, FT_INT, FT_STRING, FT_STRUCT, FT_TYPE, MAX_STRINGFIELD, fielddef_s::maxarray, fielddef_s::name, fielddef_s::offset, qfalse, qtrue, structdef_s::size, fielddef_s::substruct, fielddef_s::type, WriteFloat(), and WriteIndent().
Referenced by WriteStructure().