ioquake3: code/tools/lcc/src/list.c File Reference
list.c File Reference
#include "c.h"
Functions
List append (void *x, List list)
int length (List list)
void * ltov (List *list, unsigned arena)
Variables
static List freenodes
Function Documentation
List append (void * x, List list)
References list::link, NEW, NULL, PERM, and list::x.
int length (List list)
References list::link, list(), and n.
Referenced by AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_WriteAASLump(), CG_ParticleBloodCloud(), CG_ParticleDust(), CM_LoadMap(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), Com_TruncateLongString(), compound(), CON_LogWrite(), CRC_ContinueProcessString(), CRC_ProcessString(), dst_new(), emit_dac(), emit_dht(), FS_ListFilteredFiles(), get_dac(), get_dht(), get_dqt(), get_dri(), get_interesting_appn(), get_sof(), get_sos(), LoadFile(), LoadFileBlock(), LoadScriptFile(), LoadScriptMemory(), LoadSourceFile(), ltov(), MSG_Init(), MSG_InitOOB(), MSG_WriteData(), NET_QueuePacket(), NET_SendLoopPacket(), Netchan_Transmit(), parameters(), QCopyFile(), R_LoadBMP(), R_LoadTGA(), R_SetupFrustum(), Rankings_DrawName(), Rankings_DrawPassword(), Reached_Train(), S_CodecUtilOpen(), save_marker(), skip_variable(), SP_func_pendulum(), StripExtension(), StripFilename(), Sys_AnsiColorPrint(), Sys_AppendToExecBuffer(), Sys_Basename(), Sys_Dirname(), Sys_TempPath(), TryLoadFile(), VectorNormalize(), and VectorNormalize2().
void* ltov (List * list, unsigned arena)
References array(), freenodes, length(), list::link, list(), newarray(), NULL, and list::x.
Referenced by bbvars(), compose(), compound(), enumdcl(), ftype(), main(), parameters(), and printproto().
Variable Documentation
List freenodes [static]
Referenced by ltov().