ioquake3: code/libspeex/lpc.c File Reference
lpc.c File Reference
#include "lpc.h"
Functions
spx_word32_t _spx_lpc (spx_coef_t *lpc, const spx_word16_t *ac, int p)
void _spx_autocorr (const spx_word16_t *x, float *ac, int lag, int n)
Function Documentation
void _spx_autocorr (const spx_word16_t * x, float * ac, int lag, int n)
Referenced by nb_encode(), and sb_encode().
spx_word32_t _spx_lpc (spx_coef_t * lpc, const spx_word16_t * ac, int p)
References ADD16, DIV32_16, error(), EXTEND32, MAC16_16_P13, MULT16_16, MULT16_16_Q13, NEG32, PSHR32, SHL32, SUB16, and SUB32.
Referenced by nb_encode(), and sb_encode().