ioquake3: code/null/mac_net.c File Reference
mac_net.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
Functions
qboolean NET_StringToAdr (char *s, netadr_t *a)
void Sys_SendPacket (int length, void *data, netadr_t to)
Function Documentation
qboolean NET_StringToAdr (char * s, netadr_t * a)
References NA_LOOPBACK, and netadr_t::type.
Referenced by CL_Connect_f(), CL_GlobalServers_f(), CL_MapLoading(), CL_Ping_f(), CL_Rcon_f(), CL_RequestAuthorization(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), LAN_AddServer(), LAN_RemoveServer(), SV_Ban_f(), SV_BanNum_f(), SV_GetChallenge(), SV_MasterHeartbeat(), SV_ParseCIDRNotation(), and SV_RehashBans_f().
void Sys_SendPacket (int length, void * data, netadr_t to)
Referenced by NET_FlushPacketQueue(), and NET_SendPacket().