ioquake3: code/tools/lcc/cpp/macro.c File Reference
macro.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Defines
#define STRLEN 512
Functions
void dodefine (Tokenrow *trp)
void doadefine (Tokenrow *trp, int type)
void expandrow (Tokenrow *trp, char *flag)
void expand (Tokenrow *trp, Nlist *np)
int gatherargs (Tokenrow *trp, Tokenrow **atr, int *narg)
void substargs (Nlist *np, Tokenrow *rtr, Tokenrow **atr)
void doconcat (Tokenrow *trp)
int lookuparg (Nlist *mac, Token *tp)
Tokenrow * stringify (Tokenrow *vp)
void builtin (Tokenrow *trp, int biname)
Define Documentation
#define STRLEN 512
Referenced by stringify().
Function Documentation
void builtin (Tokenrow * trp, int biname)
References cursource, curtime, ERROR, error(), source::fd, source::filename, KDATE, KFILE, KLINENO, KTIME, token::len, source::line, source::next, NULL, NUMBER, op, outnum(), outp, s, src, STRING, token::t, tokenrow::tp, token::type, and token::wslen.
Referenced by expandrow(), and PC_AddBuiltinDefines().
void doadefine (Tokenrow * trp, int type)
References ASGN, tokenrow::bp, END, error(), FATAL, nlist::flag, ISDEFINED, lookup(), tokenrow::lp, NAME, normtokenrow(), np, NULL, NUMBER, tokenrow::tp, token::type, and nlist::vp.
Referenced by setup().
void doconcat (Tokenrow * trp)
References tokenrow::bp, bp, dofree(), DSHARP, DSHARP1, ERROR, error(), gettokens(), insertrow(), token::len, tokenrow::lp, makespace(), maketokenrow(), setsource(), token::t, tokenrow::tp, token::type, UNCLASS, unsetsource(), and WARNING.
Referenced by expand().
void dodefine (Tokenrow * trp)
References nlist::ap, args, tokenrow::bp, COMMA, comparetokens(), dofree(), ERROR, error(), nlist::flag, growtokenrow(), ISDEFINED, ISUNCHANGE, token::len, lookup(), LP, tokenrow::lp, maketokenrow(), tokenrow::max, NAME, NL, normtokenrow(), np, NULL, RP, token::t, tokenrow::tp, token::type, nlist::vp, and token::wslen.
Referenced by control().
void expand (Tokenrow * trp, Nlist * np)
References nlist::ap, tokenrow::bp, bp, copytokenrow(), doconcat(), dofree(), ERROR, error(), gatherargs(), token::hideset, insertrow(), tokenrow::lp, NAME, NARG, newhideset(), NULL, rowlen, substargs(), tokenrow::tp, token::type, unionhideset(), and nlist::vp.
Referenced by expandrow().
void expandrow (Tokenrow * trp, char * flag)
References builtin(), checkhideset(), DEFINED, ERROR, error(), expand(), nlist::flag, token::hideset, ISDEFINED, ISMAC, KDEFINED, token::len, lookup(), LP, tokenrow::lp, NAME, NAME1, np, NULL, quicklook, RP, setsource(), token::t, tokenrow::tp, token::type, unsetsource(), and nlist::val.
Referenced by control(), doinclude(), eval(), process(), and substargs().
int gatherargs (Tokenrow * trp, Tokenrow ** atr, int * narg)
References adjustrow(), tokenrow::bp, bp, COMMA, DSHARP, DSHARP1, END, ERROR, error(), FATAL, gettokens(), LP, tokenrow::lp, makespace(), NARG, NL, normtokenrow(), RP, tokenrow::tp, and token::type.
Referenced by expand().
int lookuparg (Nlist * mac, Token * tp)
References nlist::ap, tokenrow::bp, token::len, NAME, NULL, token::t, and token::type.
Referenced by substargs().
Tokenrow* stringify (Tokenrow * vp)
References tokenrow::bp, CCON, cp, ERROR, error(), token::flag, token::len, newstring(), s, STRING, STRLEN, t, token::t, tr, token::type, token::wslen, and XPWS.
Referenced by substargs().
void substargs (Nlist * np, Tokenrow * rtr, Tokenrow ** atr)
References tokenrow::bp, copytokenrow(), dofree(), DSHARP, ERROR, error(), expandrow(), insertrow(), lookuparg(), tokenrow::lp, NAME, SHARP, stringify(), tokenrow::tp, and token::type.
Referenced by expand().