ioquake3: code/libspeex/nb_celp.h File Reference
nb_celp.h File Reference
Narrowband CELP encoder/decoder.
#include "modes.h"
#include <speex/speex_bits.h>
#include <speex/speex_callbacks.h>
#include "vbr.h"
#include "filters.h"
Data Structures
struct EncState
struct DecState
Typedefs
typedef struct EncState EncState
typedef struct DecState DecState
Functions
void * nb_encoder_init (const SpeexMode *m)
void nb_encoder_destroy (void *state)
int nb_encode (void *state, void *in, SpeexBits *bits)
void * nb_decoder_init (const SpeexMode *m)
void nb_decoder_destroy (void *state)
int nb_decode (void *state, SpeexBits *bits, void *out)
int nb_encoder_ctl (void *state, int request, void *ptr)
int nb_decoder_ctl (void *state, int request, void *ptr)
Detailed Description
Narrowband CELP encoder/decoder.
Typedef Documentation
typedef struct DecState DecState
Structure representing the full state of the narrowband decoder
typedef struct EncState EncState
Structure representing the full state of the narrowband encoder
Function Documentation
int nb_decode (void * state, SpeexBits * bits, void * out)
Decodes one frame
References ABS, ADD16, ADD32, ALLOC, bits(), bw_lpc(), compute_rms16(), DecState::count_lost, SpeexCallback::data, DecState::dtx_enabled, DecState::encode_submode, DecState::exc, exc_gain_quant_scal1, exc_gain_quant_scal3, DecState::excBuf, EXTEND32, EXTRACT16, DecState::first, DecState::frameSize, SpeexCallback::func, gain_3tap_to_1tap, GAIN_SCALING, highpass(), DecState::highpass_enabled, HIGHPASS_NARROWBAND, HIGHPASS_OUTPUT, HIGHPASS_WIDEBAND, iir_mem16(), DecState::innov_save, DecState::interp_qlpc, DecState::isWideband, DecState::last_ol_gain, DecState::last_pitch, DecState::last_pitch_gain, DecState::level, DecState::lpc_enh_enabled, LPC_SCALING, DecState::lpcSize, lsp_enforce_margin(), lsp_interpolate(), LSP_MARGIN, lsp_to_lpc(), m, MAX16, DecState::max_level, DecState::max_pitch, DecState::mem_hp, DecState::mem_sp, MIN16, DecState::min_level, DecState::min_pitch, MULT16_16, MULT16_16_16, MULT16_16_P14, MULT16_16_P15, MULT16_16_Q14, MULT16_16_Q15, MULT16_32_Q14, MULT16_32_Q15, multicomb(), nb_decode_lost(), DecState::nbSubframes, NEG32, NULL, DecState::old_qlsp, out, PDIV32, DecState::pi_gain, DecState::pitch_gain_buf, DecState::pitch_gain_buf_idx, PSHR16, PSHR32, Q15_ONE, QCONST16, QCONST32, sanitize_values32(), SATURATE32, SB_SUBMODE_BITS, DecState::seed, SHL16, SHL32, SHR16, SHR32, SIG_SCALING, signal_mul(), speex_assert, speex_bits_advance(), speex_bits_remaining(), speex_bits_unpack_unsigned(), DecState::speex_callbacks, SPEEX_COPY, speex_inband_handler(), SPEEX_MEMSET, SPEEX_MOVE, speex_notify(), speex_rand(), spx_sqrt, DecState::stack, SUB16, SUB32, DecState::subframeSize, SUBMODE, DecState::submodeID, DecState::submodes, DecState::user_callback, VARDECL, DecState::voc_m1, DecState::voc_m2, DecState::voc_mean, DecState::voc_offset, and wb_skip_table.
int nb_decoder_ctl (void * state, int request, void * ptr)
ioctl-like function for controlling a narrowband decoder
References SpeexCallback::callback_id, compute_rms16(), SpeexCallback::data, DecState::dtx_enabled, DecState::encode_submode, DecState::exc, DecState::excBuf, DecState::frameSize, SpeexCallback::func, DecState::highpass_enabled, DecState::innov_save, int(), DecState::isWideband, DecState::level, DecState::lpc_enh_enabled, DecState::lpcSize, DecState::max_level, DecState::max_pitch, DecState::mem_sp, DecState::min_level, NB_SUBMODE_BITS, DecState::nbSubframes, DecState::pi_gain, ptr(), DecState::sampling_rate, DecState::speex_callbacks, SPEEX_GET_ACTIVITY, SPEEX_GET_BITRATE, SPEEX_GET_DTX_STATUS, SPEEX_GET_ENH, SPEEX_GET_EXC, SPEEX_GET_FRAME_SIZE, SPEEX_GET_HIGHPASS, SPEEX_GET_LOOKAHEAD, SPEEX_GET_LOW_MODE, SPEEX_GET_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_GET_SUBMODE_ENCODING, SPEEX_RESET_STATE, SPEEX_SET_ENH, SPEEX_SET_HANDLER, SPEEX_SET_HIGHPASS, SPEEX_SET_INNOVATION_SAVE, SPEEX_SET_LOW_MODE, SPEEX_SET_MODE, SPEEX_SET_SAMPLING_RATE, SPEEX_SET_SUBMODE_ENCODING, SPEEX_SET_USER_HANDLER, SPEEX_SET_WIDEBAND, speex_warning_int(), DecState::stack, DecState::subframeSize, SUBMODE, DecState::submodeID, DecState::submodes, and DecState::user_callback.
void nb_decoder_destroy (void * state)
De-allocates decoder state resources
References DecState::excBuf, DecState::interp_qlpc, DecState::mem_sp, DecState::old_qlsp, DecState::pi_gain, speex_free(), speex_free_scratch(), and DecState::stack.
void* nb_decoder_init (const SpeexMode * m)
Initializes decoder state
References DecState::count_lost, SpeexCallback::data, SpeexNBMode::defaultSubmode, DecState::dtx_enabled, DecState::encode_submode, DecState::exc, DecState::excBuf, DecState::first, SpeexNBMode::frameSize, DecState::frameSize, SpeexCallback::func, DecState::highpass_enabled, DecState::interp_qlpc, DecState::isWideband, DecState::last_ol_gain, DecState::last_pitch, DecState::lpc_enh_enabled, SpeexNBMode::lpcSize, DecState::lpcSize, m, DecState::max_pitch, DecState::mem_sp, DecState::min_pitch, DecState::mode, SpeexMode::mode, NB_DEC_STACK, DecState::nbSubframes, NULL, DecState::old_qlsp, DecState::pi_gain, DecState::pitch_gain_buf, DecState::pitch_gain_buf_idx, SpeexNBMode::pitchEnd, SpeexNBMode::pitchStart, DecState::sampling_rate, DecState::seed, speex_alloc(), speex_alloc_scratch(), DecState::speex_callbacks, speex_default_user_handler(), SPEEX_MEMSET, DecState::stack, SpeexNBMode::subframeSize, DecState::subframeSize, DecState::submodeID, SpeexNBMode::submodes, DecState::submodes, DecState::user_callback, DecState::voc_m1, DecState::voc_m2, DecState::voc_mean, and DecState::voc_offset.
int nb_encode (void * state, void * in, SpeexBits * bits)
Encodes one frame
References _spx_autocorr(), _spx_lpc(), EncState::abr_count, EncState::abr_drift, EncState::abr_drift2, EncState::abr_enabled, ABS, ADD16, ADD32, ALLOC, bits(), EncState::bounded_pitch, bw_lpc(), EncState::complexity, compute_impulse_response(), compute_rms(), compute_rms16(), EncState::cumul_gain, EncState::dtx_count, EncState::dtx_enabled, EncState::encode_submode, EncState::exc, exc_gain_quant_scal1, exc_gain_quant_scal1_bound, exc_gain_quant_scal3, exc_gain_quant_scal3_bound, EncState::excBuf, EXTEND32, EXTRACT16, filter_mem16(), fir_mem16(), EncState::first, EncState::frameSize, GAIN_SCALING_1, EncState::gamma1, EncState::gamma2, highpass(), EncState::highpass_enabled, HIGHPASS_INPUT, HIGHPASS_NARROWBAND, HIGHPASS_WIDEBAND, iir_mem16(), in, EncState::innov_rms_save, int(), EncState::isWideband, EncState::lagWindow, EncState::lpc_floor, LPC_SCALING, lpc_to_lsp(), EncState::lpcSize, LSP_DELTA1, lsp_enforce_margin(), lsp_interpolate(), LSP_MARGIN, lsp_quant(), LSP_SCALING, lsp_to_lpc(), EncState::max_pitch, EncState::mem_exc, EncState::mem_exc2, EncState::mem_hp, EncState::mem_sp, EncState::mem_sw, EncState::mem_sw_whole, EncState::min_pitch, MULT16_16, MULT16_16_16, MULT16_16_P13, MULT16_16_P15, MULT16_16_Q14, MULT16_16_Q15, MULT16_32_Q14, MULT16_32_Q15, NB_SUBMODE_BITS, EncState::nbSubframes, noise_codebook_quant(), NULL, EncState::old_lsp, EncState::old_qlsp, open_loop_nbest_pitch(), PDIV32, PDIV32_16, EncState::pi_gain, EncState::pitch, EncState::plc_tuning, PSHR16, PSHR32, QCONST16, QCONST32, EncState::relative_quality, SATURATE, SATURATE32, scal_quant(), scal_quant32(), SHL16, SHL32, SHR32, SIG_SCALING, signal_div(), signal_mul(), speex_assert, speex_bits_pack(), SPEEX_COPY, speex_encoder_ctl(), SPEEX_GET_BITRATE, SPEEX_MEMSET, SPEEX_MOVE, SPEEX_SET_BITRATE, SPEEX_SET_MODE, spx_sqrt, EncState::stack, SUB32, EncState::subframeSize, SUBMODE, EncState::submodeID, EncState::submodes, EncState::submodeSelect, EncState::sw, EncState::swBuf, EncState::vad_enabled, VARDECL, EncState::vbr, vbr_analysis(), EncState::vbr_enabled, EncState::vbr_max, vbr_nb_thresh, EncState::vbr_quality, VERY_SMALL, EncState::winBuf, EncState::window, and EncState::windowSize.
int nb_encoder_ctl (void * state, int request, void * ptr)
ioctl-like function for controlling a narrowband encoder
References EncState::abr_count, EncState::abr_drift, EncState::abr_drift2, EncState::abr_enabled, EncState::bounded_pitch, EncState::complexity, compute_rms16(), DIV32, EncState::dtx_enabled, EncState::encode_submode, EncState::exc, EncState::excBuf, EncState::first, EncState::frameSize, EncState::highpass_enabled, EncState::innov_rms_save, EncState::isWideband, EncState::lpcSize, EncState::max_pitch, EncState::mem_exc, EncState::mem_sp, EncState::mem_sw, EncState::mem_sw_whole, EncState::mode, SpeexMode::mode, MULT16_16, NB_SUBMODE_BITS, EncState::nbSubframes, EncState::old_lsp, EncState::pi_gain, EncState::plc_tuning, ptr(), QCONST16, quality, quality_map, EncState::relative_quality, EncState::sampling_rate, speex_encoder_ctl(), SPEEX_GET_ABR, SPEEX_GET_BITRATE, SPEEX_GET_COMPLEXITY, SPEEX_GET_DTX, SPEEX_GET_EXC, SPEEX_GET_FRAME_SIZE, SPEEX_GET_HIGHPASS, SPEEX_GET_LOOKAHEAD, SPEEX_GET_LOW_MODE, SPEEX_GET_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_PLC_TUNING, SPEEX_GET_RELATIVE_QUALITY, SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_GET_SUBMODE_ENCODING, SPEEX_GET_VAD, SPEEX_GET_VBR, SPEEX_GET_VBR_MAX_BITRATE, SPEEX_GET_VBR_QUALITY, SPEEX_RESET_STATE, SPEEX_SET_ABR, SPEEX_SET_BITRATE, SPEEX_SET_COMPLEXITY, SPEEX_SET_DTX, SPEEX_SET_HIGHPASS, SPEEX_SET_INNOVATION_SAVE, SPEEX_SET_LOW_MODE, SPEEX_SET_MODE, SPEEX_SET_PLC_TUNING, SPEEX_SET_QUALITY, SPEEX_SET_SAMPLING_RATE, SPEEX_SET_SUBMODE_ENCODING, SPEEX_SET_VAD, SPEEX_SET_VBR, SPEEX_SET_VBR_MAX_BITRATE, SPEEX_SET_VBR_QUALITY, SPEEX_SET_WIDEBAND, speex_warning_int(), EncState::stack, EncState::subframeSize, SUBMODE, EncState::submodeID, EncState::submodes, EncState::submodeSelect, EncState::swBuf, EncState::vad_enabled, EncState::vbr_enabled, EncState::vbr_max, EncState::vbr_quality, EncState::winBuf, and EncState::windowSize.
void nb_encoder_destroy (void * state)
De-allocates encoder state resources
References EncState::excBuf, EncState::mem_exc, EncState::mem_exc2, EncState::mem_sp, EncState::mem_sw, EncState::mem_sw_whole, EncState::old_lsp, EncState::old_qlsp, EncState::pi_gain, EncState::pitch, speex_free(), speex_free_scratch(), EncState::stack, EncState::swBuf, EncState::vbr, vbr_destroy(), and EncState::winBuf.
void* nb_encoder_init (const SpeexMode * m)
Initializes encoder state
References EncState::abr_drift, EncState::abr_drift2, EncState::abr_enabled, EncState::bounded_pitch, EncState::complexity, EncState::cumul_gain, SpeexNBMode::defaultSubmode, DIV32, EncState::dtx_count, EncState::dtx_enabled, EncState::encode_submode, EncState::exc, EncState::excBuf, EncState::first, EncState::frameSize, SpeexNBMode::frameSize, EncState::gamma1, SpeexNBMode::gamma1, EncState::gamma2, SpeexNBMode::gamma2, EncState::highpass_enabled, EncState::innov_rms_save, int(), EncState::isWideband, lag_window, EncState::lagWindow, EncState::lpc_floor, SpeexNBMode::lpc_floor, lpc_window, EncState::lpcSize, SpeexNBMode::lpcSize, m, EncState::max_pitch, EncState::mem_exc, EncState::mem_exc2, EncState::mem_sp, EncState::mem_sw, EncState::mem_sw_whole, EncState::min_pitch, EncState::mode, SpeexMode::mode, MULT16_16, NB_ENC_STACK, EncState::nbSubframes, NULL, EncState::old_lsp, EncState::old_qlsp, EncState::pi_gain, EncState::pitch, SpeexNBMode::pitchEnd, SpeexNBMode::pitchStart, EncState::plc_tuning, QCONST16, EncState::sampling_rate, speex_alloc(), speex_alloc_scratch(), EncState::stack, EncState::subframeSize, SpeexNBMode::subframeSize, EncState::submodeID, EncState::submodes, SpeexNBMode::submodes, EncState::submodeSelect, EncState::sw, EncState::swBuf, EncState::vad_enabled, EncState::vbr, EncState::vbr_enabled, vbr_init(), EncState::vbr_max, EncState::vbr_quality, EncState::winBuf, EncState::window, and EncState::windowSize.