ioquake3: code/null/null_input.c File Reference
null_input.c File Reference
Functions
void IN_Init (void)
void IN_Frame (void)
void IN_Shutdown (void)
void IN_Restart (void)
void Sys_SendKeyEvents (void)
Function Documentation
void IN_Frame (void)
Referenced by main().
void IN_Init (void)
Referenced by CL_InitRef(), and IN_Restart().
void IN_Restart (void)
Referenced by CL_InitRef(), and Sys_In_Restart_f().
void IN_Shutdown (void)
Referenced by CL_InitRef().
void Sys_SendKeyEvents (void)