ioquake3: code/qcommon/qcommon.h File Reference
qcommon.h File Reference
definitions common between client and server, but not game or ref modules
#include "../qcommon/cm_public.h"
Data Structures
struct msg_t
Basic data structure for msg.c.
struct netadr_t
struct netchan_t
Network channel.
struct field_t
struct sysEvent_t
struct nodetype
struct huff_t
struct huffman_t
Defines
#define __attribute__(x)
#define NET_ENABLEV4 0x01
Whether to enable IPv4.
#define NET_ENABLEV6 0x02
Whether to enable IPv6.
#define NET_PRIOV6 0x04
Always attempt IPv6 connections instead of IPv4 if a IPv6 address is found.
#define NET_DISABLEMCAST 0x08
Disable IPv6 multicast support.
#define PACKET_BACKUP 32
Number of old messages that must be kept on client and server for delta compression and ping estimation.
#define PACKET_MASK (PACKET_BACKUP-1)
Mask the packet backup.
#define MAX_PACKET_USERCMDS 32
Max number of usercmd_t in a packet.
#define PORT_ANY -1
#define MAX_RELIABLE_COMMANDS 64
Max string commands buffered for retransmit.
#define NET_ADDRSTRMAXLEN 48
Maximum length of an IPv6 address string including trailing NUL.
#define MAX_MSGLEN 16384
Max length of a message which may be fragmented into multiple packets.
#define MAX_DOWNLOAD_WINDOW 48
ACK window of MAX_DOWNLOAD_WINDOW chunks. Cannot set this higher or clients will overflow the reliable commands buffer.
#define MAX_DOWNLOAD_BLKSIZE 1024
Maximum block size for downloads.
#define NETCHAN_GENCHECKSUM(challenge, sequence) ((challenge) ^ ((sequence) * (challenge)))
Generate a checksum for the network channel.
#define PROTOCOL_VERSION 71
Protocol version when the new protocol is in affect.
#define PROTOCOL_LEGACY_VERSION 68
When using LEGACY_PROTOCOL, this is the identifier.
#define PORT_MASTER 27950
#define PORT_UPDATE 27951
#define PORT_SERVER 27960
Port for the server to listen on by default.
#define NUM_SERVER_PORTS 4
Broadcast scan this many ports after PORT_SERVER so a single machine can run multiple servers.
#define VMA(x) VM_ArgPtr(args[x])
#define VMF(x) _vmf(args[x])
#define FS_GENERAL_REF 0x01
#define FS_UI_REF 0x02
#define FS_CGAME_REF 0x04
#define FS_QAGAME_REF 0x08
#define NUM_ID_PAKS 9
#define NUM_TA_PAKS 4
#define MAX_FILE_HANDLES 64
#define Q3CONFIG_CFG "q3config.cfg"
#define MAX_EDIT_LINE 256
#define MAXPRINTMSG 4096
#define ZONE_DEBUG
#define Z_TagMalloc(size, tag) Z_TagMallocDebug(size, tag, #size, __FILE__, __LINE__)
#define Z_Malloc(size) Z_MallocDebug(size, #size, __FILE__, __LINE__)
#define S_Malloc(size) S_MallocDebug(size, #size, __FILE__, __LINE__)
#define AVI_LINE_PADDING 4
#define MAX_JOYSTICK_AXIS 16
#define NYT HMAX /* NYT = Not Yet Transmitted */
#define INTERNAL_NODE (HMAX+1)
#define HMAX 256 /* Maximum symbol */
#define SV_ENCODE_START 4
#define SV_DECODE_START 12
#define CL_ENCODE_START 12
#define CL_DECODE_START 4
#define DLF_ENABLE 1
#define DLF_NO_REDIRECT 2
#define DLF_NO_UDP 4
#define DLF_NO_DISCONNECT 8
Typedefs
typedef struct vm_s vm_t
typedef void(* xcommand_t)(void)
typedef void(* completionFunc_t)(char *args, int argNum)
typedef struct nodetype node_t
Enumerations
enum netadrtype_t {
NA_BAD = 0, NA_BOT, NA_LOOPBACK, NA_BROADCAST,
NA_IP, NA_IP6, NA_MULTICAST6, NA_UNSPEC
}
A network address type enum.
enum netsrc_t { NS_CLIENT, NS_SERVER }
Network source.
enum svc_ops_e {
svc_bad, svc_nop, svc_gamestate, svc_configstring,
svc_baseline, svc_serverCommand, svc_download, svc_snapshot,
svc_EOF, svc_voip
}
Server to client commands.
enum clc_ops_e {
clc_bad, clc_nop, clc_move, clc_moveNoDelta,
clc_clientCommand, clc_EOF, clc_voip
}
Client to server commands.
enum vmInterpret_t { VMI_NATIVE, VMI_BYTECODE, VMI_COMPILED }
enum sharedTraps_t {
TRAP_MEMSET = 100, TRAP_MEMCPY, TRAP_STRNCPY, TRAP_SIN,
TRAP_COS, TRAP_ATAN2, TRAP_SQRT, TRAP_MATRIXMULTIPLY,
TRAP_ANGLEVECTORS, TRAP_PERPENDICULARVECTOR, TRAP_FLOOR, TRAP_CEIL,
TRAP_TESTPRINTINT, TRAP_TESTPRINTFLOAT
}
enum cpuFeatures_t {
CF_RDTSC = 1 << 0, CF_MMX = 1 << 1, CF_MMX_EXT = 1 << 2, CF_3DNOW = 1 << 3,
CF_3DNOW_EXT = 1 << 4, CF_SSE = 1 << 5, CF_SSE2 = 1 << 6, CF_ALTIVEC = 1 << 7
}
enum sysEventType_t {
SE_NONE = 0, SE_KEY, SE_CHAR, SE_MOUSE,
SE_JOYSTICK_AXIS, SE_CONSOLE
}
enum memtag_t {
TAG_FREE, TAG_GENERAL, TAG_BOTLIB, TAG_RENDERER,
TAG_SMALL, TAG_STATIC
}
enum dialogResult_t { DR_YES = 0, DR_NO = 1, DR_OK = 0, DR_CANCEL = 1 }
enum dialogType_t {
DT_INFO, DT_WARNING, DT_ERROR, DT_YES_NO,
DT_OK_CANCEL
}
Functions
void MSG_Init (msg_t *buf, byte *data, int length)
void MSG_InitOOB (msg_t *buf, byte *data, int length)
void MSG_Clear (msg_t *buf)
void MSG_WriteData (msg_t *buf, const void *data, int length)
void MSG_Bitstream (msg_t *buf)
void MSG_Copy (msg_t *buf, byte *data, int length, msg_t *src)
void MSG_WriteBits (msg_t *msg, int value, int bits)
void MSG_WriteChar (msg_t *sb, int c)
void MSG_WriteByte (msg_t *sb, int c)
void MSG_WriteShort (msg_t *sb, int c)
void MSG_WriteLong (msg_t *sb, int c)
void MSG_WriteFloat (msg_t *sb, float f)
void MSG_WriteString (msg_t *sb, const char *s)
void MSG_WriteBigString (msg_t *sb, const char *s)
void MSG_WriteAngle16 (msg_t *sb, float f)
int MSG_HashKey (const char *string, int maxlen)
void MSG_BeginReading (msg_t *sb)
void MSG_BeginReadingOOB (msg_t *sb)
int MSG_ReadBits (msg_t *msg, int bits)
int MSG_ReadChar (msg_t *sb)
int MSG_ReadByte (msg_t *sb)
int MSG_ReadShort (msg_t *sb)
int MSG_ReadLong (msg_t *sb)
float MSG_ReadFloat (msg_t *sb)
char * MSG_ReadString (msg_t *sb)
char * MSG_ReadBigString (msg_t *sb)
char * MSG_ReadStringLine (msg_t *sb)
float MSG_ReadAngle16 (msg_t *sb)
void MSG_ReadData (msg_t *sb, void *buffer, int size)
int MSG_LookaheadByte (msg_t *msg)
void MSG_WriteDeltaUsercmd (msg_t *msg, struct usercmd_s *from, struct usercmd_s *to)
void MSG_ReadDeltaUsercmd (msg_t *msg, struct usercmd_s *from, struct usercmd_s *to)
void MSG_WriteDeltaUsercmdKey (msg_t *msg, int key, usercmd_t *from, usercmd_t *to)
void MSG_ReadDeltaUsercmdKey (msg_t *msg, int key, usercmd_t *from, usercmd_t *to)
void MSG_WriteDeltaEntity (msg_t *msg, struct entityState_s *from, struct entityState_s *to, qboolean force)
void MSG_ReadDeltaEntity (msg_t *msg, entityState_t *from, entityState_t *to, int number)
void MSG_WriteDeltaPlayerstate (msg_t *msg, struct playerState_s *from, struct playerState_s *to)
void MSG_ReadDeltaPlayerstate (msg_t *msg, struct playerState_s *from, struct playerState_s *to)
void MSG_ReportChangeVectors_f (void)
void NET_Init (void)
void NET_Shutdown (void)
void NET_Restart_f (void)
void NET_Config (qboolean enableNetworking)
void NET_FlushPacketQueue (void)
void NET_SendPacket (netsrc_t sock, int length, const void *data, netadr_t to)
void QDECL NET_OutOfBandPrint (netsrc_t net_socket, netadr_t adr, const char *format,...) __attribute__((format(printf
void QDECL void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, byte *format, int len)
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
qboolean NET_CompareBaseAdrMask (netadr_t a, netadr_t b, int netmask)
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
qboolean NET_IsLocalAddress (netadr_t adr)
const char * NET_AdrToString (netadr_t a)
const char * NET_AdrToStringwPort (netadr_t a)
int NET_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t *net_from, msg_t *net_message)
void NET_JoinMulticast6 (void)
void NET_LeaveMulticast6 (void)
void NET_Sleep (int msec)
void Netchan_Init (int qport)
void Netchan_Setup (netsrc_t sock, netchan_t *chan, netadr_t adr, int qport, int challenge, qboolean compat)
void Netchan_Transmit (netchan_t *chan, int length, const byte *data)
void Netchan_TransmitNextFragment (netchan_t *chan)
qboolean Netchan_Process (netchan_t *chan, msg_t *msg)
void VM_Init (void)
vm_t * VM_Create (const char *module, intptr_t(*systemCalls)(intptr_t *), vmInterpret_t interpret)
void VM_Free (vm_t *vm)
void VM_Clear (void)
void VM_Forced_Unload_Start (void)
void VM_Forced_Unload_Done (void)
vm_t * VM_Restart (vm_t *vm, qboolean unpure)
intptr_t QDECL VM_Call (vm_t *vm, int callNum,...)
void VM_Debug (int level)
void * VM_ArgPtr (intptr_t intValue)
void * VM_ExplicitArgPtr (vm_t *vm, intptr_t intValue)
static ID_INLINE float _vmf (intptr_t x)
void Cbuf_Init (void)
void Cbuf_AddText (const char *text)
void Cbuf_ExecuteText (int exec_when, const char *text)
void Cbuf_Execute (void)
void Cmd_Init (void)
void Cmd_AddCommand (const char *cmd_name, xcommand_t function)
void Cmd_RemoveCommand (const char *cmd_name)
void Cmd_RemoveCommandSafe (const char *cmd_name)
void Cmd_CommandCompletion (void(*callback)(const char *s))
void Cmd_SetCommandCompletionFunc (const char *command, completionFunc_t complete)
void Cmd_CompleteArgument (const char *command, char *args, int argNum)
void Cmd_CompleteCfgName (char *args, int argNum)
int Cmd_Argc (void)
char * Cmd_Argv (int arg)
void Cmd_ArgvBuffer (int arg, char *buffer, int bufferLength)
char * Cmd_Args (void)
char * Cmd_ArgsFrom (int arg)
void Cmd_ArgsBuffer (char *buffer, int bufferLength)
char * Cmd_Cmd (void)
void Cmd_Args_Sanitize (void)
void Cmd_TokenizeString (const char *text)
void Cmd_TokenizeStringIgnoreQuotes (const char *text_in)
void Cmd_ExecuteString (const char *text)
cvar_t * Cvar_Get (const char *var_name, const char *value, int flags)
void Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
void Cvar_Update (vmCvar_t *vmCvar)
void Cvar_Set (const char *var_name, const char *value)
cvar_t * Cvar_Set2 (const char *var_name, const char *value, qboolean force)
void Cvar_SetSafe (const char *var_name, const char *value)
void Cvar_SetLatched (const char *var_name, const char *value)
void Cvar_SetValue (const char *var_name, float value)
void Cvar_SetValueSafe (const char *var_name, float value)
float Cvar_VariableValue (const char *var_name)
int Cvar_VariableIntegerValue (const char *var_name)
char * Cvar_VariableString (const char *var_name)
void Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
int Cvar_Flags (const char *var_name)
void Cvar_CommandCompletion (void(*callback)(const char *s))
void Cvar_Reset (const char *var_name)
void Cvar_ForceReset (const char *var_name)
void Cvar_SetCheatState (void)
qboolean Cvar_Command (void)
void Cvar_WriteVariables (fileHandle_t f)
void Cvar_Init (void)
char * Cvar_InfoString (int bit)
char * Cvar_InfoString_Big (int bit)
void Cvar_InfoStringBuffer (int bit, char *buff, int buffsize)
void Cvar_CheckRange (cvar_t *cv, float minVal, float maxVal, qboolean shouldBeIntegral)
void Cvar_Restart (qboolean unsetVM)
void Cvar_Restart_f (void)
void Cvar_CompleteCvarName (char *args, int argNum)
qboolean FS_Initialized (void)
void FS_InitFilesystem (void)
void FS_Shutdown (qboolean closemfp)
qboolean FS_ConditionalRestart (int checksumFeed, qboolean disconnect)
void FS_Restart (int checksumFeed)
void FS_AddGameDirectory (const char *path, const char *dir)
char ** FS_ListFiles (const char *directory, const char *extension, int *numfiles)
void FS_FreeFileList (char **list)
qboolean FS_FileExists (const char *file)
qboolean FS_CreatePath (char *OSPath)
vmInterpret_t FS_FindVM (void **startSearch, char *found, int foundlen, const char *name, int enableDll)
char * FS_BuildOSPath (const char *base, const char *game, const char *qpath)
qboolean FS_CompareZipChecksum (const char *zipfile)
int FS_LoadStack (void)
int FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
int FS_GetModList (char *listbuf, int bufsize)
fileHandle_t FS_FOpenFileWrite (const char *qpath)
fileHandle_t FS_FOpenFileAppend (const char *filename)
fileHandle_t FS_FCreateOpenPipeFile (const char *filename)
fileHandle_t FS_SV_FOpenFileWrite (const char *filename)
long FS_SV_FOpenFileRead (const char *filename, fileHandle_t *fp)
void FS_SV_Rename (const char *from, const char *to)
long FS_FOpenFileRead (const char *qpath, fileHandle_t *file, qboolean uniqueFILE)
int FS_FileIsInPAK (const char *filename, int *pChecksum)
int FS_Write (const void *buffer, int len, fileHandle_t f)
int FS_Read2 (void *buffer, int len, fileHandle_t f)
int FS_Read (void *buffer, int len, fileHandle_t f)
void FS_FCloseFile (fileHandle_t f)
long FS_ReadFileDir (const char *qpath, void *searchPath, qboolean unpure, void **buffer)
long FS_ReadFile (const char *qpath, void **buffer)
void FS_ForceFlush (fileHandle_t f)
void FS_FreeFile (void *buffer)
void FS_WriteFile (const char *qpath, const void *buffer, int size)
long FS_filelength (fileHandle_t f)
int FS_FTell (fileHandle_t f)
void FS_Flush (fileHandle_t f)
void QDECL FS_Printf (fileHandle_t f, const char *fmt,...) __attribute__((format(printf
void QDECL int FS_FOpenFileByMode (const char *qpath, fileHandle_t *f, fsMode_t mode)
int FS_Seek (fileHandle_t f, long offset, int origin)
qboolean FS_FilenameCompare (const char *s1, const char *s2)
const char * FS_GamePureChecksum (void)
const char * FS_LoadedPakNames (void)
const char * FS_LoadedPakChecksums (void)
const char * FS_LoadedPakPureChecksums (void)
const char * FS_ReferencedPakNames (void)
const char * FS_ReferencedPakChecksums (void)
const char * FS_ReferencedPakPureChecksums (void)
void FS_ClearPakReferences (int flags)
void FS_PureServerSetReferencedPaks (const char *pakSums, const char *pakNames)
void FS_PureServerSetLoadedPaks (const char *pakSums, const char *pakNames)
qboolean FS_CheckDirTraversal (const char *checkdir)
qboolean FS_idPak (char *pak, char *base, int numPaks)
qboolean FS_ComparePaks (char *neededpaks, int len, qboolean dlstring)
void FS_Rename (const char *from, const char *to)
void FS_Remove (const char *osPath)
void FS_HomeRemove (const char *homePath)
void FS_FilenameCompletion (const char *dir, const char *ext, qboolean stripExt, void(*callback)(const char *s), qboolean allowNonPureFilesOnDisk)
const char * FS_GetCurrentGameDir (void)
qboolean FS_Which (const char *filename, void *searchPath)
void Field_Clear (field_t *edit)
void Field_AutoComplete (field_t *edit)
void Field_CompleteKeyname (void)
void Field_CompleteFilename (const char *dir, const char *ext, qboolean stripExt, qboolean allowNonPureFilesOnDisk)
void Field_CompleteCommand (char *cmd, qboolean doCommands, qboolean doCvars)
void Com_QueueEvent (int time, sysEventType_t type, int value, int value2, int ptrLength, void *ptr)
int Com_EventLoop (void)
sysEvent_t Com_GetSystemEvent (void)
char * CopyString (const char *in)
void Info_Print (const char *s)
void Com_BeginRedirect (char *buffer, int buffersize, void(*flush)(char *))
void Com_EndRedirect (void)
void QDECL Com_Printf (const char *fmt,...) __attribute__((format(printf
void QDECL void QDECL Com_DPrintf (const char *fmt,...) __attribute__((format(printf
void QDECL void QDECL void QDECL Com_Error (int code, const char *fmt,...) __attribute__((noreturn
void QDECL void QDECL void QDECL format (printf, 2, 3)))
void Com_Quit_f (void) __attribute__((noreturn))
void Com_GameRestart (int checksumFeed, qboolean disconnect)
int Com_Milliseconds (void)
unsigned Com_BlockChecksum (const void *buffer, int length)
char * Com_MD5File (const char *filename, int length, const char *prefix, int prefix_len)
int Com_Filter (char *filter, char *name, int casesensitive)
int Com_FilterPath (char *filter, char *name, int casesensitive)
int Com_RealTime (qtime_t *qtime)
qboolean Com_SafeMode (void)
void Com_RunAndTimeServerPacket (netadr_t *evFrom, msg_t *buf)
qboolean Com_IsVoipTarget (uint8_t *voipTargets, int voipTargetsSize, int clientNum)
void Com_StartupVariable (const char *match)
void * Z_TagMallocDebug (int size, int tag, char *label, char *file, int line)
void * Z_MallocDebug (int size, char *label, char *file, int line)
void * S_MallocDebug (int size, char *label, char *file, int line)
void Z_Free (void *ptr)
void Z_FreeTags (int tag)
int Z_AvailableMemory (void)
void Z_LogHeap (void)
void Hunk_Clear (void)
void Hunk_ClearToMark (void)
void Hunk_SetMark (void)
qboolean Hunk_CheckMark (void)
void Hunk_ClearTempMemory (void)
void * Hunk_AllocateTempMemory (int size)
void Hunk_FreeTempMemory (void *buf)
int Hunk_MemoryRemaining (void)
void Hunk_Log (void)
void Com_TouchMemory (void)
void Com_Init (char *commandLine)
void Com_Frame (void)
void Com_Shutdown (void)
void CL_InitKeyCommands (void)
void CL_Init (void)
void CL_Disconnect (qboolean showMainMenu)
void CL_Shutdown (char *finalmsg, qboolean disconnect, qboolean quit)
void CL_Frame (int msec)
qboolean CL_GameCommand (void)
void CL_KeyEvent (int key, qboolean down, unsigned time)
void CL_CharEvent (int key)
void CL_MouseEvent (int dx, int dy, int time)
void CL_JoystickEvent (int axis, int value, int time)
void CL_PacketEvent (netadr_t from, msg_t *msg)
void CL_ConsolePrint (char *text)
void CL_MapLoading (void)
void CL_ForwardCommandToServer (const char *string)
void CL_CDDialog (void)
void CL_FlushMemory (void)
void CL_ShutdownAll (qboolean shutdownRef)
void CL_InitRef (void)
void CL_StartHunkUsers (qboolean rendererOnly)
void CL_Snd_Shutdown (void)
void Key_KeynameCompletion (void(*callback)(const char *s))
void Key_WriteBindings (fileHandle_t f)
void S_ClearSoundBuffer (void)
void SCR_DebugGraph (float value)
void SV_Init (void)
void SV_Shutdown (char *finalmsg)
void SV_Frame (int msec)
void SV_PacketEvent (netadr_t from, msg_t *msg)
int SV_FrameMsec (void)
qboolean SV_GameCommand (void)
int SV_SendQueuedPackets (void)
qboolean UI_GameCommand (void)
qboolean UI_usesUniqueCDKey (void)
void Sys_Init (void)
void *QDECL Sys_LoadGameDll (const char *name, intptr_t(QDECL **entryPoint)(int,...), intptr_t(QDECL *systemcalls)(intptr_t,...))
void Sys_UnloadDll (void *dllHandle)
void Sys_UnloadGame (void)
void * Sys_GetGameAPI (void *parms)
void Sys_UnloadCGame (void)
void * Sys_GetCGameAPI (void)
void Sys_UnloadUI (void)
void * Sys_GetUIAPI (void)
void Sys_UnloadBotLib (void)
void * Sys_GetBotLibAPI (void *parms)
char * Sys_GetCurrentUser (void)
void QDECL Sys_Error (const char *error,...) __attribute__((noreturn
void QDECL format (printf, 1, 2)))
void Sys_Quit (void) __attribute__((noreturn))
char * Sys_GetClipboardData (void)
void Sys_Print (const char *msg)
int Sys_Milliseconds (void)
void Sys_SnapVector (float *v)
qboolean Sys_RandomBytes (byte *string, int len)
void Sys_DisplaySystemConsole (qboolean show)
cpuFeatures_t Sys_GetProcessorFeatures (void)
void Sys_SetErrorText (const char *text)
void Sys_SendPacket (int length, const void *data, netadr_t to)
qboolean Sys_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
qboolean Sys_IsLANAddress (netadr_t adr)
void Sys_ShowIP (void)
qboolean Sys_Mkdir (const char *path)
FILE * Sys_Mkfifo (const char *ospath)
char * Sys_Cwd (void)
void Sys_SetDefaultInstallPath (const char *path)
char * Sys_DefaultInstallPath (void)
void Sys_SetDefaultHomePath (const char *path)
char * Sys_DefaultHomePath (void)
const char * Sys_TempPath (void)
const char * Sys_Dirname (char *path)
const char * Sys_Basename (char *path)
char * Sys_ConsoleInput (void)
char ** Sys_ListFiles (const char *directory, const char *extension, char *filter, int *numfiles, qboolean wantsubs)
void Sys_FreeFileList (char **list)
void Sys_Sleep (int msec)
qboolean Sys_LowPhysicalMemory (void)
void Sys_SetEnv (const char *name, const char *value)
dialogResult_t Sys_Dialog (dialogType_t type, const char *message, const char *title)
qboolean Sys_WritePIDFile (void)
void Huff_Compress (msg_t *buf, int offset)
void Huff_Decompress (msg_t *buf, int offset)
void Huff_Init (huffman_t *huff)
void Huff_addRef (huff_t *huff, byte ch)
int Huff_Receive (node_t *node, int *ch, byte *fin)
void Huff_transmit (huff_t *huff, int ch, byte *fout)
void Huff_offsetReceive (node_t *node, int *ch, byte *fin, int *offset)
void Huff_offsetTransmit (huff_t *huff, int ch, byte *fout, int *offset)
void Huff_putBit (int bit, byte *fout, int *offset)
int Huff_getBit (byte *fout, int *offset)
int Huff_getBloc (void)
void Huff_setBloc (int _bloc)
Variables
int demo_protocols []
int cvar_modifiedFlags
char cl_cdkey [34]
cvar_t * com_developer
cvar_t * com_dedicated
cvar_t * com_speeds
cvar_t * com_timescale
cvar_t * com_sv_running
cvar_t * com_cl_running
cvar_t * com_version
cvar_t * com_blood
cvar_t * com_buildScript
cvar_t * com_journal
cvar_t * com_cameraMode
cvar_t * com_ansiColor
cvar_t * com_unfocused
cvar_t * com_maxfpsUnfocused
cvar_t * com_minimized
cvar_t * com_maxfpsMinimized
cvar_t * com_altivec
cvar_t * com_standalone
cvar_t * com_basegame
cvar_t * com_homepath
cvar_t * cl_paused
cvar_t * sv_paused
cvar_t * cl_packetdelay
cvar_t * sv_packetdelay
cvar_t * com_gamename
cvar_t * com_protocol
int time_game
int time_frontend
int time_backend
int com_frameTime
qboolean com_errorEntered
qboolean com_fullyInitialized
fileHandle_t com_journalFile
fileHandle_t com_journalDataFile
huffman_t clientHuffTables
Detailed Description
definitions common between client and server, but not game or ref modules
More details about this file
Define Documentation
#define __attribute__ (x)
#define AVI_LINE_PADDING 4
Referenced by CL_OpenAVIForWriting(), and RB_TakeVideoFrameCmd().
#define CL_DECODE_START 4
Referenced by CL_Netchan_Decode().
#define CL_ENCODE_START 12
Referenced by CL_Netchan_Encode().
#define DLF_ENABLE 1
Referenced by CL_InitDownloads(), and SV_WriteDownloadToClient().
#define DLF_NO_DISCONNECT 8
#define DLF_NO_REDIRECT 2
Referenced by CL_NextDownload().
#define DLF_NO_UDP 4
Referenced by CL_NextDownload(), and SV_WriteDownloadToClient().
#define FS_CGAME_REF 0x04
Referenced by CL_Vid_Restart_f(), FS_FOpenFileReadDir(), and FS_ReferencedPakPureChecksums().
#define FS_GENERAL_REF 0x01
Referenced by FS_FOpenFileReadDir(), and FS_ReferencedPakPureChecksums().
#define FS_QAGAME_REF 0x08
Referenced by FS_FOpenFileReadDir(), and FS_GamePureChecksum().
#define FS_UI_REF 0x02
Referenced by CL_Vid_Restart_f(), FS_FOpenFileReadDir(), and FS_ReferencedPakPureChecksums().
#define HMAX 256 /* Maximum symbol */
#define INTERNAL_NODE (HMAX+1)
Referenced by Huff_addRef(), Huff_offsetReceive(), and Huff_Receive().
#define MAX_DOWNLOAD_BLKSIZE 1024
Maximum block size for downloads.
Referenced by SV_SendQueuedPackets(), and SV_WriteDownloadToClient().
#define MAX_DOWNLOAD_WINDOW 48
ACK window of MAX_DOWNLOAD_WINDOW chunks. Cannot set this higher or clients will overflow the reliable commands buffer.
Referenced by SV_CloseDownload(), SV_NextDownload_f(), and SV_WriteDownloadToClient().
#define MAX_EDIT_LINE 256
#define MAX_FILE_HANDLES 64
Referenced by FS_FileForHandle(), FS_HandleForFile(), FS_Path_f(), and FS_Shutdown().
#define MAX_JOYSTICK_AXIS 16
Referenced by CL_Init(), CL_JoystickEvent(), and IN_JoyMove().
#define MAX_MSGLEN 16384
Max length of a message which may be fragmented into multiple packets.
Referenced by CL_ParseDownload(), CL_ReadDemoMessage(), CL_Record_f(), CL_WritePacket(), Com_EventLoop(), NET_Event(), NET_OutOfBandData(), NET_OutOfBandPrint(), Netchan_Transmit(), SV_SendClientGameState(), SV_SendClientSnapshot(), SV_SendDownloadMessages(), SV_SendServerCommand(), and SVC_Status().
#define MAX_PACKET_USERCMDS 32
Max number of usercmd_t in a packet.
Referenced by CL_WritePacket(), and SV_UserMove().
#define MAX_RELIABLE_COMMANDS 64
Max string commands buffered for retransmit.
Referenced by CL_AddReliableCommand(), CL_ChangeReliableCommand(), CL_GetServerCommand(), CL_Netchan_Decode(), CL_Netchan_Encode(), CL_ParseCommandString(), CL_ParseServerMessage(), CL_WritePacket(), SV_AddServerCommand(), SV_BotGetConsoleMessage(), SV_ExecuteClientMessage(), SV_Netchan_Decode(), SV_UpdateServerCommandsToClient(), and SV_UserMove().
#define MAXPRINTMSG 4096
Referenced by __attribute__(), Com_DPrintf(), Com_Printf(), FS_Printf(), and Sys_AnsiColorPrint().
#define NET_ADDRSTRMAXLEN 48
Maximum length of an IPv6 address string including trailing NUL.
Referenced by NET_AdrToString(), NET_AdrToStringwPort(), SV_AddBanToList(), and Sys_ShowIP().
#define NET_DISABLEMCAST 0x08
Disable IPv6 multicast support.
Referenced by NET_JoinMulticast6(), NET_SetMulticast6(), and Sys_SendPacket().
#define NET_ENABLEV4 0x01
Whether to enable IPv4.
Referenced by CL_GlobalServers_f(), NET_OpenIP(), SV_MasterHeartbeat(), and Sys_StringToSockaddr().
#define NET_ENABLEV6 0x02
Whether to enable IPv6.
Referenced by NET_OpenIP(), SV_MasterHeartbeat(), and Sys_StringToSockaddr().
#define NET_PRIOV6 0x04
Always attempt IPv6 connections instead of IPv4 if a IPv6 address is found.
Referenced by Sys_StringToSockaddr().
#define NETCHAN_GENCHECKSUM (challenge, sequence) ((challenge) ^ ((sequence) * (challenge)))
Generate a checksum for the network channel.
Referenced by Netchan_Process(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
#define NUM_ID_PAKS 9
Referenced by FS_CheckPak0(), FS_ComparePaks(), FS_idPak(), and SV_WriteDownloadToClient().
#define NUM_SERVER_PORTS 4
Broadcast scan this many ports after PORT_SERVER so a single machine can run multiple servers.
Referenced by CL_LocalServers_f().
#define NUM_TA_PAKS 4
Referenced by FS_CheckPak0(), FS_ComparePaks(), and SV_WriteDownloadToClient().
#define NYT HMAX /* NYT = Not Yet Transmitted */
Referenced by Huff_Compress(), Huff_Decompress(), Huff_Init(), and Huff_transmit().
#define PACKET_BACKUP 32
Number of old messages that must be kept on client and server for delta compression and ping estimation.
Referenced by CL_GetSnapshot(), CL_ParseSnapshot(), SV_CalcPings(), SV_ChangeMaxClients(), SV_Startup(), and SV_WriteSnapshotToClient().
#define PACKET_MASK (PACKET_BACKUP-1)
Mask the packet backup.
Referenced by CL_GetSnapshot(), CL_ParseSnapshot(), CL_ReadyToSendPacket(), CL_WritePacket(), SV_BotGetSnapshotEntity(), SV_BuildClientSnapshot(), SV_SendMessageToClient(), SV_UserMove(), and SV_WriteSnapshotToClient().
#define PORT_ANY -1
Referenced by NET_IP6Socket(), and NET_IPSocket().
#define PORT_MASTER 27950
Referenced by CL_GlobalServers_f(), and SV_MasterHeartbeat().
#define PORT_SERVER 27960
Port for the server to listen on by default.
Referenced by CL_Connect_f(), CL_LocalServers_f(), CL_Rcon_f(), NET_GetCvars(), and NET_StringToAdr().
#define PORT_UPDATE 27951
Referenced by CL_RequestMotd().
#define PROTOCOL_LEGACY_VERSION 68
When using LEGACY_PROTOCOL, this is the identifier.
Referenced by Com_Init().
#define PROTOCOL_VERSION 71
Protocol version when the new protocol is in affect.
Referenced by Com_Init().
#define Q3CONFIG_CFG "q3config.cfg"
Referenced by Com_ExecuteCfg(), Com_WriteConfiguration(), and FS_Restart().
#define S_Malloc (size) S_MallocDebug(size, #size, __FILE__, __LINE__)
Referenced by Cmd_AddCommand(), CopyString(), and NET_QueuePacket().
#define SV_DECODE_START 12
Referenced by SV_Netchan_Decode().
#define SV_ENCODE_START 4
Referenced by SV_Netchan_Encode().
#define VMA (x) VM_ArgPtr(args[x])
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
#define VMF (x) _vmf(args[x])
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
#define Z_Malloc (size) Z_MallocDebug(size, #size, __FILE__, __LINE__)
Referenced by AllocWinding(), CL_OpenAVIForWriting(), Com_GetRealEvent(), Com_GetSystemEvent(), dst_new(), FS_AddGameDirectory(), FS_ListFilteredFiles(), FS_LoadZipFile(), FS_SortFileList(), hash_add_label(), Hunk_AllocateTempMemory(), jump_insn_append(), S_CodecUtilOpen(), sparc_push_data(), SV_BotInitBotLib(), SV_ChangeMaxClients(), SV_Netchan_Transmit(), SV_RankBegin(), SV_RehashBans_f(), SV_Startup(), SV_WriteDownloadToClient(), Sys_ConcatenateFileLists(), Sys_GetClipboardData(), Sys_ListFiles(), VM_Compile(), VM_VmProfile_f(), and Z_MallocDebug().
#define Z_TagMalloc (size, tag) Z_TagMallocDebug(size, tag, #size, __FILE__, __LINE__)
Referenced by BotImport_GetMemory(), CL_RefMalloc(), Z_MallocDebug(), and Z_TagMallocDebug().
#define ZONE_DEBUG
Typedef Documentation
typedef void(* completionFunc_t)(char *args, int argNum)
typedef struct nodetype node_t
typedef struct vm_s vm_t
typedef void(* xcommand_t)(void)
Enumeration Type Documentation
enum clc_ops_e
Client to server commands.
Enumerator:
clc_bad
Client sends a bad command.
clc_nop
Client sends a no-op command.
clc_move
clc_moveNoDelta
...
clc_clientCommand
Client sends a command to the server.
clc_EOF
Client sends an end of file command.
clc_voip
Client VoIP.
enum cpuFeatures_t
Enumerator:
CF_RDTSC
CF_MMX
CF_MMX_EXT
CF_3DNOW
CF_3DNOW_EXT
CF_SSE
CF_SSE2
CF_ALTIVEC
enum dialogResult_t
Enumerator:
DR_YES
DR_NO
DR_OK
DR_CANCEL
enum dialogType_t
Enumerator:
DT_INFO
DT_WARNING
DT_ERROR
DT_YES_NO
DT_OK_CANCEL
enum memtag_t
Enumerator:
TAG_FREE
TAG_GENERAL
TAG_BOTLIB
TAG_RENDERER
TAG_SMALL
TAG_STATIC
enum netadrtype_t
A network address type enum.
Enumerator:
NA_BAD
An address lookup failed.
NA_BOT
Bot (fake) address.
NA_LOOPBACK
Loopback address.
NA_BROADCAST
Broadcast address.
NA_IP
IPv4 address.
NA_IP6
IPv6 address.
NA_MULTICAST6
IPv6 multicast.
NA_UNSPEC
Unspecified address.
enum netsrc_t
Network source.
Enumerator:
NS_CLIENT
Client.
NS_SERVER
Server.
enum sharedTraps_t
Enumerator:
TRAP_MEMSET
TRAP_MEMCPY
TRAP_STRNCPY
TRAP_SIN
TRAP_COS
TRAP_ATAN2
TRAP_SQRT
TRAP_MATRIXMULTIPLY
TRAP_ANGLEVECTORS
TRAP_PERPENDICULARVECTOR
TRAP_FLOOR
TRAP_CEIL
TRAP_TESTPRINTINT
TRAP_TESTPRINTFLOAT
enum svc_ops_e
Server to client commands.
The svc_strings[] array in cl_parse.c should mirror this.
Enumerator:
svc_bad
Bad server command.
svc_nop
No-op command for server.
svc_gamestate
Server command for a gamestate.
svc_configstring
Server command for sending a config string.
[short] [string] only in gamestate messages
svc_baseline
Server command for sending baselines.
This is only in gamestate messages.
svc_serverCommand
Server command for the client game module to execute.
svc_download
Server command for a download.
svc_snapshot
Server command for sending a snapshot.
svc_EOF
Server command for sending end of file.
svc_voip
Server command for VoIP.
This is only supported by ioquake3 protocol and not the legacy. It is not wrapped in USE_VOIP so the value is reserved.
enum sysEventType_t
Enumerator:
SE_NONE
SE_KEY
SE_CHAR
SE_MOUSE
SE_JOYSTICK_AXIS
SE_CONSOLE
enum vmInterpret_t
Enumerator:
VMI_NATIVE
VMI_BYTECODE
VMI_COMPILED
Function Documentation
static ID_INLINE float _vmf (intptr_t x) [static]
References floatint_t::f, floatint_t::i, and int().
void Cbuf_AddText (const char * text)
References Com_Memcpy, Com_Printf(), cmd_t::cursize, cmd_t::data, and cmd_t::maxsize.
Referenced by Cbuf_ExecuteText(), CL_CgameSystemCalls(), CL_FirstSnapshot(), CL_GetServerCommand(), CL_NextDemo(), CL_ParseBinding(), CL_Reconnect_f(), CL_StartDemoLoop(), Com_AddStartupCommands(), Com_EventLoop(), Com_Init(), Console_Key(), FS_Restart(), IN_Frame(), SV_Frame(), and SV_Init().
void Cbuf_Execute (void)
References Cmd_ExecuteString(), cmd_wait, Com_Memcpy, cmd_t::cursize, cmd_t::data, line, MAX_CMD_LINE, memmove(), qfalse, and qtrue.
Referenced by Cbuf_ExecuteText(), CL_NextDemo(), Com_ExecuteCfg(), and Com_Frame().
void Cbuf_ExecuteText (int exec_when, const char * text)
References Cbuf_AddText(), Cbuf_Execute(), Cbuf_InsertText(), Cmd_ExecuteString(), Com_DPrintf(), Com_Error(), cmd_t::data, ERR_FATAL, EXEC_APPEND, EXEC_INSERT, EXEC_NOW, and S_COLOR_YELLOW.
Referenced by CL_Frame(), CL_InitRef(), CL_UISystemCalls(), Com_ExecuteCfg(), Com_ReadFromPipe(), IN_ProcessEvents(), RoQShutdown(), and SV_GameSystemCalls().
void Cbuf_Init (void)
References cmd_text_buf, cmd_t::cursize, cmd_t::data, MAX_CMD_BUFFER, and cmd_t::maxsize.
Referenced by Com_Init().
void CL_CDDialog (void)
References clientStatic_t::cddialog, and qtrue.
Referenced by Com_Error().
void CL_CharEvent (int key)
References CA_DISCONNECTED, clc, Field_CharEvent(), K_CHAR_FLAG, Key_GetCatcher(), KEYCATCH_CONSOLE, KEYCATCH_MESSAGE, KEYCATCH_UI, qtrue, clientConnection_t::state, UI_KEY_EVENT, uivm, and VM_Call().
Referenced by Com_EventLoop().
void CL_ConsolePrint (char * text)
References cl_noprint, cls, console_t::color, COLOR_WHITE, ColorIndex, Con_CheckResize(), Con_Linefeed(), console_t::current, console_t::initialized, cvar_s::integer, console_t::linewidth, NUM_CON_TIMES, Q_IsColorString, Q_strncmp(), qfalse, qtrue, clientStatic_t::realtime, console_t::text, console_t::times, console_t::totallines, and console_t::x.
Referenced by Com_Printf().
void CL_Disconnect (qboolean showMainMenu)
References CA_CONNECTED, CA_DISCONNECTED, CL_AddReliableCommand(), CL_ClearState(), CL_CloseAVI(), cl_connectedToPureServer, CL_OldGame(), CL_StopRecord_f(), CL_UpdateGUID(), CL_VideoRecording(), CL_WritePacket(), Cmd_RemoveCommand(), com_cl_running, Com_Memset, Com_Printf(), Cvar_Set(), clientConnection_t::demofile, clientConnection_t::demorecording, clientConnection_t::download, clientConnection_t::downloadName, clientConnection_t::downloadTempName, FS_FCloseFile(), FS_PureServerSetLoadedPaks(), cvar_s::integer, MAX_CLIENTS, mumble_islinked(), mumble_unlink(), noGameRestart, NULL, qfalse, qtrue, S_ClearSoundBuffer(), SCR_StopCinematic(), SCR_UpdateScreen(), speex_bits_destroy(), speex_decoder_destroy(), speex_encoder_destroy(), speex_preprocess_state_destroy(), clientConnection_t::state, UI_SET_ACTIVE_MENU, UIMENU_NONE, uivm, and VM_Call().
Referenced by CL_CheckTimeout(), CL_Connect_f(), CL_DemoCompleted(), CL_DisconnectPacket(), CL_MapLoading(), CL_PlayDemo_f(), CL_Shutdown(), Com_Error(), Com_GameRestart(), and SV_Shutdown().
void CL_FlushMemory (void)
References CL_ClearMemory(), CL_StartHunkUsers(), and qfalse.
Referenced by CL_DownloadsComplete(), Com_Error(), and Com_Frame().
void CL_ForwardCommandToServer (const char * string)
References CA_CONNECTED, CL_AddReliableCommand(), Cmd_Argc(), Cmd_Argv(), Com_Printf(), clientConnection_t::demoplaying, qfalse, S_COLOR_WHITE, and clientConnection_t::state.
Referenced by Cmd_ExecuteString().
void CL_Frame (int msec)
References CA_ACTIVE, CA_DISCONNECTED, Cbuf_ExecuteText(), clientStatic_t::cddialog, CL_CheckForResend(), CL_CheckTimeout(), CL_CheckUserinfo(), CL_cURL_PerformDownload(), CL_SendCmd(), CL_SetCGameTime(), CL_StopRecord_f(), CL_TakeVideoFrame(), cl_timegraph, CL_VideoRecording(), com_cl_running, Com_RealTime(), COM_SkipPath(), COM_StripExtension(), com_sv_running, com_timescale, Con_RunConsole(), clientConnection_t::demoplaying, clientConnection_t::demorecording, EXEC_NOW, clientStatic_t::framecount, clientStatic_t::frametime, int(), cvar_s::integer, Key_GetCatcher(), KEYCATCH_UI, clientActive_t::mapname, MAX_OSPATH, MAX_QPATH, Q_strncpyz(), qfalse, clientStatic_t::realFrametime, clientStatic_t::realtime, S_StopAllSounds(), S_Update(), SCR_DebugGraph(), SCR_RunCinematic(), SCR_UpdateScreen(), clientConnection_t::servername, clientConnection_t::state, qtime_s::tm_hour, qtime_s::tm_mday, qtime_s::tm_min, qtime_s::tm_mon, qtime_s::tm_sec, qtime_s::tm_year, UI_SET_ACTIVE_MENU, UIMENU_MAIN, UIMENU_NEED_CD, uivm, va(), cvar_s::value, and VM_Call().
Referenced by Com_Frame().
qboolean CL_GameCommand (void)
References CG_CONSOLE_COMMAND, cgvm, qfalse, and VM_Call().
Referenced by Cmd_ExecuteString().
void CL_Init (void)
References CA_DISCONNECTED, cl_anglespeedkey, CL_ClearState(), CL_Clientinfo_f(), CL_CompleteDemoName(), CL_CompleteRcon(), CL_Configstrings_f(), CL_Connect_f(), CL_Disconnect_f(), CL_ForwardToServer_f(), CL_GenerateQKey(), CL_GlobalServers_f(), CL_InitInput(), CL_InitRef(), CL_LocalServers_f(), CL_OpenedPK3List_f(), CL_Ping_f(), cl_pitchspeed, CL_PlayCinematic_f(), CL_PlayDemo_f(), CL_Rcon_f(), CL_Reconnect_f(), CL_Record_f(), CL_ReferencedPK3List_f(), cl_run, CL_ServerStatus_f(), CL_SetModel_f(), CL_ShowIP_f(), CL_Snd_Restart_f(), CL_StopRecord_f(), CL_StopVideo_f(), CL_UpdateGUID(), CL_Vid_Restart_f(), CL_Video_f(), cl_yawspeed, Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), com_fullyInitialized, Com_Printf(), Con_Init(), CVAR_ARCHIVE, Cvar_CheckRange(), Cvar_Get(), CVAR_LATCH, CVAR_ROM, CVAR_SERVERINFO, Cvar_Set(), CVAR_TEMP, CVAR_USERINFO, Cvar_VariableIntegerValue(), cvar_s::integer, MAX_JOYSTICK_AXIS, NULL, clientStatic_t::oldGameSet, qfalse, qtrue, clientStatic_t::realtime, S_COLOR_YELLOW, SCR_Init(), and clientConnection_t::state.
Referenced by Com_GameRestart(), and Com_Init().
void CL_InitKeyCommands (void)
References Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), Key_Bind_f(), Key_Bindlist_f(), Key_CompleteBind(), Key_CompleteUnbind(), Key_Unbind_f(), and Key_Unbindall_f().
Referenced by Com_Init().
void CL_InitRef (void)
References Cbuf_ExecuteText(), refimport_t::CIN_PlayCinematic, CIN_PlayCinematic(), refimport_t::CIN_RunCinematic, CIN_RunCinematic(), refimport_t::CIN_UploadCinematic, CIN_UploadCinematic(), CL_RefMalloc(), CL_ScaledMilliseconds(), refimport_t::CL_WriteAVIVideoFrame, CL_WriteAVIVideoFrame(), CM_ClusterPVS(), refimport_t::CM_ClusterPVS, refimport_t::CM_DrawDebugSurface, CM_DrawDebugSurface(), refimport_t::Cmd_AddCommand, Cmd_AddCommand(), refimport_t::Cmd_Argc, Cmd_Argc(), refimport_t::Cmd_Argv, Cmd_Argv(), refimport_t::Cmd_ExecuteText, refimport_t::Cmd_RemoveCommand, Cmd_RemoveCommand(), Com_Error(), Com_Printf(), Com_sprintf(), CVAR_ARCHIVE, refimport_t::Cvar_CheckRange, Cvar_CheckRange(), Cvar_ForceReset(), refimport_t::Cvar_Get, Cvar_Get(), CVAR_LATCH, refimport_t::Cvar_Set, Cvar_Set(), refimport_t::Cvar_SetValue, Cvar_SetValue(), Cvar_VariableIntegerValue(), refimport_t::Cvar_VariableIntegerValue, ERR_FATAL, refimport_t::Free, refimport_t::FS_FileExists, FS_FileExists(), refimport_t::FS_FileIsInPAK, FS_FileIsInPAK(), refimport_t::FS_FreeFile, FS_FreeFile(), refimport_t::FS_FreeFileList, FS_FreeFileList(), refimport_t::FS_ListFiles, FS_ListFiles(), refimport_t::FS_ReadFile, FS_ReadFile(), refimport_t::FS_WriteFile, FS_WriteFile(), refimport_t::ftol, GetRefAPI(), refimport_t::Hunk_Alloc, Hunk_Alloc, refimport_t::Hunk_AllocateTempMemory, Hunk_AllocateTempMemory(), Hunk_AllocDebug(), refimport_t::Hunk_FreeTempMemory, Hunk_FreeTempMemory(), IN_Init(), refimport_t::IN_Init, IN_Restart(), refimport_t::IN_Restart, IN_Shutdown(), refimport_t::IN_Shutdown, refimport_t::Malloc, MAX_OSPATH, refimport_t::Milliseconds, Q_ftol, qfalse, REF_API_VERSION, cvar_s::resetString, ri, cvar_s::string, Sys_GLimpInit(), refimport_t::Sys_GLimpInit, Sys_GLimpSafeInit(), refimport_t::Sys_GLimpSafeInit, Sys_LibraryError, Sys_LoadDll(), Sys_LoadFunction, Sys_LoadLibrary, refimport_t::Sys_LowPhysicalMemory, Sys_LowPhysicalMemory(), refimport_t::Sys_SetEnv, Sys_SetEnv(), and Z_Free().
Referenced by CL_Init(), and CL_Vid_Restart_f().
void CL_JoystickEvent (int axis, int value, int time)
References cl, Com_Error(), ERR_DROP, clientActive_t::joystickAxis, MAX_JOYSTICK_AXIS, and value().
Referenced by Com_EventLoop().
void CL_KeyEvent (int key, qboolean down, unsigned time)
References CL_KeyDownEvent(), and CL_KeyUpEvent().
Referenced by Com_EventLoop(), and Key_ClearStates().
void CL_MapLoading (void)
References CA_CHALLENGING, CA_CONNECTED, CA_DISCONNECTED, CL_CheckForResend(), CL_Disconnect(), com_cl_running, com_dedicated, Com_Memset, Con_Close(), clientConnection_t::connectTime, Cvar_Set(), clientActive_t::gameState, cvar_s::integer, Key_SetCatcher(), KEYCATCH_CONSOLE, clientConnection_t::lastPacketSentTime, NA_UNSPEC, NET_StringToAdr(), Q_stricmp(), Q_strncpyz(), qtrue, RETRANSMIT_TIMEOUT, SCR_UpdateScreen(), clientConnection_t::serverAddress, clientConnection_t::serverMessage, clientConnection_t::servername, clientConnection_t::state, and clientStatic_t::updateInfoString.
Referenced by SV_SpawnServer().
void CL_MouseEvent (int dx, int dy, int time)
References CG_MOUSE_EVENT, cgvm, cl, Key_GetCatcher(), KEYCATCH_CGAME, KEYCATCH_UI, clientActive_t::mouseDx, clientActive_t::mouseDy, clientActive_t::mouseIndex, UI_MOUSE_EVENT, uivm, and VM_Call().
Referenced by Com_EventLoop().
void CL_PacketEvent (netadr_t from, msg_t * msg)
References CA_CONNECTED, CL_ConnectionlessPacket(), CL_Netchan_Process(), CL_ParseServerMessage(), CL_WriteDemoMessage(), Com_DPrintf(), Com_Printf(), msg_t::cursize, msg_t::data, clientConnection_t::demorecording, clientConnection_t::demowaiting, clientConnection_t::lastPacketTime, NET_AdrToStringwPort(), NET_CompareAdr(), clientConnection_t::netchan, msg_t::readcount, clientStatic_t::realtime, netchan_t::remoteAddress, clientConnection_t::serverMessageSequence, and clientConnection_t::state.
Referenced by Com_EventLoop(), and NET_Event().
void CL_Shutdown (char * finalmsg, qboolean disconnect, qboolean quit)
References CL_ClearMemory(), CL_Disconnect(), CL_ShutdownInput(), CL_Snd_Shutdown(), Cmd_RemoveCommand(), com_cl_running, Com_Memset, Com_Printf(), Con_Shutdown(), Cvar_Set(), cvar_s::integer, Key_SetCatcher(), noGameRestart, qfalse, and qtrue.
Referenced by Com_Error(), Com_GameRestart(), Com_Quit_f(), and Sys_SigHandler().
void CL_ShutdownAll (qboolean shutdownRef)
References clientStatic_t::cgameStarted, CL_CloseAVI(), CL_cURL_Shutdown(), CL_ShutdownCGame(), CL_ShutdownRef(), CL_ShutdownUI(), CL_StopRecord_f(), CL_VideoRecording(), clientConnection_t::demorecording, qfalse, clientStatic_t::rendererStarted, S_DisableSounds(), refexport_t::Shutdown, clientStatic_t::soundRegistered, and clientStatic_t::uiStarted.
Referenced by CL_ClearMemory(), and SV_SpawnServer().
void CL_Snd_Shutdown (void)
References qfalse, S_Shutdown(), and clientStatic_t::soundStarted.
Referenced by CL_Shutdown(), and CL_Snd_Restart_f().
void CL_StartHunkUsers (qboolean rendererOnly)
References CL_InitRenderer(), CL_InitUI(), com_cl_running, com_dedicated, cvar_s::integer, qtrue, clientStatic_t::rendererStarted, S_BeginRegistration(), S_Init(), clientStatic_t::soundRegistered, clientStatic_t::soundStarted, and clientStatic_t::uiStarted.
Referenced by CL_FlushMemory(), CL_Vid_Restart_f(), Com_GameRestart(), Com_Init(), and SV_SpawnServer().
void Cmd_AddCommand (const char * cmd_name, xcommand_t function)
References Cmd_FindCommand(), cmd_functions, Com_Printf(), cmd_function_s::complete, CopyString(), cmd_function_s::function, cmd_function_s::name, cmd_function_s::next, NULL, and S_Malloc.
Referenced by CL_AddCgameCommand(), CL_FirstSnapshot(), CL_Init(), CL_InitInput(), CL_InitKeyCommands(), CL_InitRef(), Cmd_Init(), Com_Init(), Com_InitHunkMemory(), Con_Init(), Cvar_Init(), FS_Startup(), NET_Init(), S_Init(), SV_AddOperatorCommands(), Sys_Init(), and VM_Init().
int Cmd_Argc (void)
References cmd_argc.
Referenced by CL_CgameSystemCalls(), CL_Connect_f(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitRef(), CL_Ping_f(), CL_PlayDemo_f(), CL_Record_f(), CL_ServerStatus_f(), CL_UISystemCalls(), CL_Video_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_List_f(), Cmd_Vstr_f(), Cmd_Wait_f(), Com_Error_f(), Com_Freeze_f(), Com_Meminfo_f(), Com_Setenv_f(), Com_WriteConfig_f(), Con_Dump_f(), Cvar_Command(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Field_CompleteCommand(), FS_Dir_f(), FS_NewDir_f(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_TouchFile_f(), Key_Bind_f(), Key_Unbind_f(), S_Music_f(), S_Play_f(), SV_AddBanToList(), SV_Ban_f(), SV_BanNum_f(), SV_ConSay_f(), SV_DelBanFromList(), SV_DumpUser_f(), SV_GameSystemCalls(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickNum_f(), SV_MapRestart_f(), SV_VerifyPaks_f(), and SV_WriteDownloadToClient().
char* Cmd_Args (void)
References cmd_argc, cmd_argv, and MAX_STRING_CHARS.
Referenced by CL_ForwardToServer_f(), Cmd_ArgsBuffer(), Cmd_Echo_f(), Com_Quit_f(), Cvar_Command(), and SV_ConSay_f().
void Cmd_Args_Sanitize (void)
References cmd_argc, cmd_argv, and MAX_CVAR_VALUE_STRING.
Referenced by SV_ExecuteClientCommand().
void Cmd_ArgsBuffer (char * buffer, int bufferLength)
References Cmd_Args(), and Q_strncpyz().
Referenced by CL_CgameSystemCalls().
char* Cmd_ArgsFrom (int arg)
References BIG_INFO_STRING, cmd_argc, and cmd_argv.
Referenced by CL_ConfigstringModified(), Com_Setenv_f(), Cvar_Set_f(), and SVC_RemoteCommand().
char* Cmd_Argv (int arg)
References cmd_argc, and cmd_argv.
Referenced by CL_ConfigstringModified(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_ForwardCommandToServer(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitRef(), CL_MotdPacket(), CL_Ping_f(), CL_PlayCinematic_f(), CL_PlayDemo_f(), CL_Record_f(), CL_ServerStatus_f(), CL_SetModel_f(), CL_Video_f(), Cmd_ArgvBuffer(), Cmd_Exec_f(), Cmd_List_f(), Cmd_Vstr_f(), Cmd_Wait_f(), Com_Freeze_f(), Com_GameRestart_f(), Com_SafeMode(), Com_Setenv_f(), Com_StartupVariable(), Com_WriteConfig_f(), Con_Dump_f(), Cvar_Command(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Field_CompleteCommand(), FS_Dir_f(), FS_NewDir_f(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_TouchFile_f(), FS_Which_f(), IN_KeyDown(), IN_KeyUp(), Key_Bind_f(), Key_Unbind_f(), S_Music_f(), S_Play_f(), SV_AddBanToList(), SV_AuthorizeIpPacket(), SV_BeginDownload_f(), SV_ConnectionlessPacket(), SV_DelBanFromList(), SV_DirectConnect(), SV_ExecuteClientCommand(), SV_GetChallenge(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_Map_f(), SV_MapRestart_f(), SV_NextDownload_f(), SV_UpdateUserinfo_f(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
void Cmd_ArgvBuffer (int arg, char * buffer, int bufferLength)
References Cmd_Argv(), and Q_strncpyz().
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
char* Cmd_Cmd (void)
References cmd_cmd.
Referenced by CL_Rcon_f(), and SVC_RemoteCommand().
void Cmd_CommandCompletion (void(*)(const char *s) callback)
References cmd_function_s::name, and cmd_function_s::next.
Referenced by Field_CompleteCommand().
void Cmd_CompleteArgument (const char * command, char * args, int argNum)
References cmd_function_s::complete, cmd_function_s::name, cmd_function_s::next, and Q_stricmp().
Referenced by Field_CompleteCommand().
void Cmd_CompleteCfgName (char * args, int argNum)
References Field_CompleteFilename(), qfalse, and qtrue.
Referenced by Cmd_Init(), and Com_Init().
void Cmd_ExecuteString (const char * text)
References CL_ForwardCommandToServer(), CL_GameCommand(), Cmd_Argc(), cmd_argv, cmd_functions, Cmd_TokenizeString(), com_cl_running, com_sv_running, Cvar_Command(), cmd_function_s::function, cvar_s::integer, cmd_function_s::name, cmd_function_s::next, Q_stricmp(), SV_GameCommand(), and UI_GameCommand().
Referenced by Cbuf_Execute(), Cbuf_ExecuteText(), and SVC_RemoteCommand().
void Cmd_Init (void)
References Cmd_AddCommand(), Cmd_CompleteCfgName(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_List_f(), Cmd_SetCommandCompletionFunc(), Cmd_Vstr_f(), Cmd_Wait_f(), and Cvar_CompleteCvarName().
Referenced by Com_Init().
void Cmd_RemoveCommand (const char * cmd_name)
References cmd_functions, cmd_function_s::name, cmd_function_s::next, and Z_Free().
Referenced by CL_Disconnect(), CL_InitRef(), CL_Shutdown(), CL_ShutdownInput(), Cmd_RemoveCommandSafe(), Con_Shutdown(), FS_Shutdown(), S_Base_Shutdown(), S_Shutdown(), and SV_RemoveOperatorCommands().
void Cmd_RemoveCommandSafe (const char * cmd_name)
References Cmd_FindCommand(), Cmd_RemoveCommand(), Com_Error(), ERR_DROP, and cmd_function_s::function.
Referenced by CL_CgameSystemCalls().
void Cmd_SetCommandCompletionFunc (const char * command, completionFunc_t complete)
References cmd_function_s::complete, cmd_function_s::name, cmd_function_s::next, and Q_stricmp().
Referenced by CL_Init(), CL_InitKeyCommands(), Cmd_Init(), Com_Init(), Con_Init(), Cvar_Init(), and SV_AddOperatorCommands().
void Cmd_TokenizeString (const char * text)
References Cmd_TokenizeString2(), and qfalse.
Referenced by CL_ConnectionlessPacket(), CL_GetServerCommand(), Cmd_ExecuteString(), Com_SafeMode(), Com_StartupVariable(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), SV_ConnectionlessPacket(), SV_ExecuteClientCommand(), and SV_VerifyPaks_f().
void Cmd_TokenizeStringIgnoreQuotes (const char * text_in)
References Cmd_TokenizeString2(), and qtrue.
Referenced by Field_CompleteCommand(), and SV_WriteDownloadToClient().
void Com_BeginRedirect (char * buffer, int buffersize, void(*)(char *) flush)
References buffer, rd_buffer, rd_buffersize, and rd_flush.
Referenced by SVC_RemoteCommand().
unsigned Com_BlockChecksum (const void * buffer, int length)
References mdfour(), and val.
Referenced by CM_Checksum(), CM_LoadMap(), CM_LumpChecksum(), and FS_LoadZipFile().
void QDECL void QDECL Com_DPrintf (const char * fmt, ...)
void Com_EndRedirect (void)
References NULL, rd_buffer, rd_buffersize, and rd_flush.
Referenced by SVC_RemoteCommand().
void QDECL void QDECL void QDECL Com_Error (int code, const char * fmt, ...)
int Com_EventLoop (void)
References Cbuf_AddText(), CL_CharEvent(), CL_JoystickEvent(), CL_KeyEvent(), CL_MouseEvent(), CL_PacketEvent(), Com_Error(), Com_GetEvent(), Com_RunAndTimeServerPacket(), ERR_FATAL, sysEvent_t::evPtr, sysEvent_t::evTime, sysEvent_t::evType, sysEvent_t::evValue, sysEvent_t::evValue2, cvar_s::integer, MAX_MSGLEN, MSG_Init(), NET_GetLoopPacket(), NS_CLIENT, NS_SERVER, SE_CHAR, SE_CONSOLE, SE_JOYSTICK_AXIS, SE_KEY, SE_MOUSE, SE_NONE, and Z_Free().
Referenced by CL_DownloadsComplete(), and Com_Frame().
int Com_Filter (char * filter, char * name, int casesensitive)
References Com_StringContains(), MAX_TOKEN_CHARS, ptr(), qfalse, and qtrue.
Referenced by Cmd_List_f(), Com_FilterPath(), and Cvar_List_f().
int Com_FilterPath (char * filter, char * name, int casesensitive)
References Com_Filter(), and MAX_QPATH.
Referenced by FS_ListFilteredFiles(), and Sys_ListFilteredFiles().
void Com_Frame (void)
References abortframe, c_brush_traces, c_patch_traces, c_pointcontents, c_traces, Cbuf_Execute(), cl, CL_FlushMemory(), CL_Frame(), Com_DetectAltivec(), Com_EventLoop(), com_frameNumber, com_frameTime, Com_ModifyMsec(), Com_Printf(), Com_ReadFromPipe(), Com_TimeVal(), Com_WriteConfiguration(), Cvar_Get(), cvar_s::integer, cvar_s::modified, NET_FlushPacketQueue(), NET_Sleep(), qfalse, sv, SV_Frame(), SV_FrameMsec(), SV_SendQueuedPackets(), SV_Shutdown(), Sys_Milliseconds(), time_backend, time_frontend, and time_game.
Referenced by main().
void Com_GameRestart (int checksumFeed, qboolean disconnect)
References CL_Disconnect(), CL_Init(), CL_Shutdown(), CL_StartHunkUsers(), Com_ExecuteCfg(), com_fullyInitialized, com_gameRestarting, Cvar_Restart(), FS_Restart(), cvar_s::integer, NET_Restart_f(), qfalse, qtrue, and SV_Shutdown().
Referenced by Com_GameRestart_f(), and FS_ConditionalRestart().
sysEvent_t Com_GetSystemEvent (void)
References b, Com_QueueEvent(), sysEvent_t::evTime, MASK_QUEUED_EVENTS, s, SE_CONSOLE, Sys_ConsoleInput(), Sys_Milliseconds(), and Z_Malloc.
Referenced by Com_GetRealEvent().
void Com_Init (char * commandLine)
References abortframe, BASEGAME, Cbuf_AddText(), Cbuf_Init(), CL_Init(), CL_InitKeyCommands(), CL_StartHunkUsers(), CLIENT_WINDOW_TITLE, Cmd_AddCommand(), Cmd_CompleteCfgName(), Cmd_Init(), Cmd_SetCommandCompletionFunc(), Com_AddStartupCommands(), Com_Crash_f(), Com_DetectAltivec(), Com_DetectSSE, Com_Error_f(), Com_ExecuteCfg(), com_frameTime, Com_Freeze_f(), com_fullyInitialized, Com_GameRestart_f(), Com_InitHunkMemory(), Com_InitJournaling(), Com_InitPushEvent(), Com_InitRand(), Com_InitSmallZoneMemory(), Com_InitZoneMemory(), Com_Memset, Com_Milliseconds(), Com_ParseCommandLine(), Com_Printf(), Com_Quit_f(), Com_RandomBytes(), Com_Setenv_f(), Com_StartupVariable(), Com_WriteConfig_f(), CVAR_ARCHIVE, CVAR_CHEAT, Cvar_CheckRange(), Cvar_ForceReset(), Cvar_Get(), CVAR_INIT, Cvar_Init(), CVAR_LATCH, cvar_modifiedFlags, CVAR_NORESTART, CVAR_ROM, CVAR_SERVERINFO, Cvar_Set(), CVAR_SYSTEMINFO, CVAR_TEMP, DR_YES, DT_YES_NO, FS_FCreateOpenPipeFile(), FS_InitFilesystem(), GAMENAME_FOR_MASTER, cvar_s::integer, MAX_QUEUED_EVENTS, cvar_s::modified, MSG_ReportChangeVectors_f(), cvar_s::name, Netchan_Init(), NULL, pipefile, PLATFORM_STRING, PROTOCOL_LEGACY_VERSION, PROTOCOL_VERSION, Q3_VERSION, qfalse, qport, qtrue, s, cvar_s::string, SV_Init(), Sys_Dialog(), Sys_Error(), Sys_Init(), Sys_WritePIDFile(), va(), and VM_Init().
Referenced by main().
qboolean Com_IsVoipTarget (uint8_t * voipTargets, int voipTargetsSize, int clientNum)
References qfalse, and qtrue.
Referenced by CL_WritePacket().
char* Com_MD5File (const char * filename, int length, const char * prefix, int prefix_len)
References buffer, FS_FCloseFile(), FS_Read2(), FS_SV_FOpenFileRead(), MD5Final(), MD5Init(), MD5Update(), Q_strcat(), Q_strncpyz(), and va().
Referenced by CL_UpdateGUID().
int Com_Milliseconds (void)
References Com_GetRealEvent(), Com_PushEvent(), sysEvent_t::evTime, sysEvent_t::evType, and SE_NONE.
Referenced by CL_Connect_f(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatusResponse(), Com_Freeze_f(), Com_Init(), S_AddLoopSounds(), S_Base_StartSound(), S_ChannelMalloc(), S_FreeOldestSound(), S_LoadSound(), S_Update_(), SV_InitGameVM(), and SV_SpawnServer().
void QDECL Com_Printf (const char * fmt, ...)
void Com_QueueEvent (int time, sysEventType_t type, int value, int value2, int ptrLength, void * ptr)
References Com_Printf(), sysEvent_t::evPtr, sysEvent_t::evPtrLength, sysEvent_t::evTime, sysEvent_t::evType, sysEvent_t::evValue, sysEvent_t::evValue2, MASK_QUEUED_EVENTS, MAX_QUEUED_EVENTS, ptr(), Sys_Milliseconds(), type(), value(), and Z_Free().
Referenced by Com_GetSystemEvent(), IN_JoyMove(), and IN_ProcessEvents().
void Com_Quit_f (void)
References CL_Shutdown(), Cmd_Args(), com_errorEntered, Com_Shutdown(), FS_Shutdown(), qtrue, SV_Shutdown(), Sys_Quit(), VM_Forced_Unload_Done(), and VM_Forced_Unload_Start().
Referenced by Com_Init().
int Com_RealTime (qtime_t * qtime)
References NULL, t, qtime_s::tm_hour, qtime_s::tm_isdst, qtime_s::tm_mday, qtime_s::tm_min, qtime_s::tm_mon, qtime_s::tm_sec, qtime_s::tm_wday, qtime_s::tm_yday, and qtime_s::tm_year.
Referenced by CL_CgameSystemCalls(), CL_Frame(), CL_UISystemCalls(), and SV_GameSystemCalls().
void Com_RunAndTimeServerPacket (netadr_t * evFrom, msg_t * buf)
References Com_Printf(), cvar_s::integer, SV_PacketEvent(), and Sys_Milliseconds().
Referenced by Com_EventLoop(), and NET_Event().
qboolean Com_SafeMode (void)
References Cmd_Argv(), Cmd_TokenizeString(), com_numConsoleLines, Q_stricmp(), qfalse, and qtrue.
Referenced by Com_ExecuteCfg(), and FS_Restart().
void Com_Shutdown (void)
References com_journalFile, FS_FCloseFile(), FS_HomeRemove(), logfile, pipefile, and cvar_s::string.
Referenced by Com_Error(), and Com_Quit_f().
void Com_StartupVariable (const char * match)
References Cmd_Argv(), Cmd_TokenizeString(), com_numConsoleLines, Cvar_Flags(), Cvar_Get(), CVAR_NONEXISTENT, Cvar_Set2(), CVAR_USER_CREATED, qfalse, and s.
Referenced by Com_Init(), Com_InitJournaling(), and FS_InitFilesystem().
void Com_TouchMemory (void)
References memzone_t::blocklist, Com_Printf(), end, memblock_s::next, hunkUsed_t::permanent, memblock_s::size, start, Sys_Milliseconds(), memblock_s::tag, and Z_CheckHeap().
Referenced by CL_InitCGame().
char* CopyString (const char * in)
References out, and S_Malloc.
Referenced by Cmd_AddCommand(), Cvar_Get(), Cvar_Set2(), FS_AddFileToList(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), Key_SetBinding(), SV_SetConfigstring(), SV_SpawnServer(), Sys_ListFiles(), and Sys_ListFilteredFiles().
void Cvar_CheckRange (cvar_t * cv, float minVal, float maxVal, qboolean shouldBeIntegral)
References Cvar_Set(), cvar_s::integral, cvar_s::max, cvar_s::min, cvar_s::name, qtrue, cvar_s::string, and cvar_s::validate.
Referenced by CL_Init(), CL_InitRef(), Com_Init(), and SV_Init().
qboolean Cvar_Command (void)
References Cmd_Argc(), Cmd_Args(), Cmd_Argv(), Cvar_FindVar(), Cvar_Print(), Cvar_Set2(), cvar_s::name, qfalse, and qtrue.
Referenced by Cmd_ExecuteString().
void Cvar_CommandCompletion (void(*)(const char *s) callback)
References cvar_s::name, and cvar_s::next.
Referenced by Field_CompleteCommand().
void Cvar_CompleteCvarName (char * args, int argNum)
References Com_SkipTokens(), Field_CompleteCommand(), qfalse, and qtrue.
Referenced by Cmd_Init(), and Cvar_Init().
int Cvar_Flags (const char * var_name)
References Cvar_FindVar(), CVAR_MODIFIED, CVAR_NONEXISTENT, cvar_s::flags, and cvar_s::modified.
Referenced by CL_ParseGamestate(), CL_SystemInfoChanged(), Com_StartupVariable(), and Cvar_SetSafe().
void Cvar_ForceReset (const char * var_name)
References Cvar_Set2(), NULL, and qtrue.
Referenced by CL_InitRef(), and Com_Init().
cvar_t* Cvar_Get (const char * var_name, const char * value, int flags)
References Com_DPrintf(), Com_Error(), com_errorEntered, Com_Printf(), CopyString(), Cvar_FindVar(), cvar_modifiedFlags, cvar_numIndexes, CVAR_ROM, CVAR_SERVER_CREATED, Cvar_Set2(), CVAR_USER_CREATED, Cvar_Validate(), Cvar_ValidateString(), cvar_vars, CVAR_VM_CREATED, ERR_FATAL, cvar_s::flags, generateHashValue(), hash(), cvar_s::hashIndex, cvar_s::hashNext, cvar_s::hashPrev, cvar_s::integer, cvar_s::latchedString, MAX_CVARS, cvar_s::modificationCount, cvar_s::modified, cvar_s::name, cvar_s::next, NULL, cvar_s::prev, qfalse, qtrue, cvar_s::resetString, s, cvar_s::string, cvar_s::validate, cvar_s::value, and Z_Free().
Referenced by BotDrawDebugPolygons(), CL_Init(), CL_InitInput(), CL_InitRef(), CL_RequestAuthorization(), CL_SystemInfoChanged(), CL_UISystemCalls(), CLUI_GetCDKey(), CLUI_SetCDKey(), CM_DrawDebugSurface(), CM_LoadMap(), CM_TracePointThroughPatchCollide(), CM_TraceThroughPatchCollide(), Com_Frame(), Com_Init(), Com_InitHunkMemory(), Com_InitJournaling(), Com_InitZoneMemory(), Com_StartupVariable(), Com_WriteConfiguration(), Con_Init(), Cvar_Init(), Cvar_Register(), Cvar_Set2(), FS_Startup(), IN_Init(), IN_InitJoystick(), NET_GetCvars(), Netchan_Init(), S_AL_Init(), S_Base_Init(), S_Init(), SCR_Init(), SND_setup(), SNDDMA_Init(), SV_BotInitCvars(), SV_BoundMaxClients(), SV_GetChallenge(), SV_Init(), SV_InitGameProgs(), SV_Map_f(), and VM_Init().
char* Cvar_InfoString (int bit)
References cvar_s::flags, info, Info_SetValueForKey(), MAX_INFO_STRING, cvar_s::name, cvar_s::next, and cvar_s::string.
Referenced by CL_CheckForResend(), CL_CheckUserinfo(), CL_Clientinfo_f(), Cvar_InfoStringBuffer(), SV_Frame(), SV_GetServerinfo(), SV_Serverinfo_f(), SV_SpawnServer(), and SVC_Status().
char* Cvar_InfoString_Big (int bit)
References BIG_INFO_STRING, cvar_s::flags, info, Info_SetValueForKey_Big(), cvar_s::name, cvar_s::next, and cvar_s::string.
Referenced by SV_Frame(), SV_SpawnServer(), and SV_Systeminfo_f().
void Cvar_InfoStringBuffer (int bit, char * buff, int buffsize)
References Cvar_InfoString(), and Q_strncpyz().
Referenced by CL_UISystemCalls().
void Cvar_Init (void)
References Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), Com_Memset, Cvar_CompleteCvarName(), Cvar_Get(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Restart_f(), CVAR_ROM, Cvar_Set_f(), CVAR_SYSTEMINFO, Cvar_Toggle_f(), and Cvar_Unset_f().
Referenced by Com_Init().
void Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
References Com_DPrintf(), CVAR_ARCHIVE, Cvar_Get(), cvar_indexes, CVAR_ROM, Cvar_Update(), CVAR_VM_CREATED, vmCvar_t::handle, vmCvar_t::modificationCount, and S_COLOR_YELLOW.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
void Cvar_Reset (const char * var_name)
References Cvar_Set2(), NULL, and qfalse.
Referenced by CL_UISystemCalls(), and Cvar_Reset_f().
void Cvar_Restart (qboolean unsetVM)
References CVAR_INIT, CVAR_NORESTART, CVAR_ROM, Cvar_Set2(), Cvar_Unset(), CVAR_USER_CREATED, cvar_vars, CVAR_VM_CREATED, cvar_s::flags, cvar_s::name, cvar_s::next, qfalse, and cvar_s::resetString.
Referenced by Com_GameRestart(), and Cvar_Restart_f().
void Cvar_Restart_f (void)
References Cvar_Restart(), and qfalse.
Referenced by Cvar_Init().
void Cvar_Set (const char * var_name, const char * value)
References Cvar_Set2(), and qtrue.
Referenced by CL_BeginDownload(), CL_Connect_f(), CL_Disconnect(), CL_Disconnect_f(), CL_DisconnectPacket(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_Init(), CL_InitDownloads(), CL_InitRef(), CL_KeyDownEvent(), CL_MapLoading(), CL_MotdPacket(), CL_NextDemo(), CL_NextDownload(), CL_ParseGamestate(), CL_PlayDemo_f(), CL_ReadyToSendPacket(), CL_Reconnect_f(), CL_SetModel_f(), CL_Shutdown(), CL_SystemInfoChanged(), CL_UpdateGUID(), CL_Vid_Restart_f(), CL_WritePacket(), Com_DetectAltivec(), Com_Error(), Com_GameRestart_f(), Com_Init(), Com_InitJournaling(), Cvar_CheckRange(), Cvar_SetCheatState(), Cvar_SetSafe(), Cvar_SetValue(), FS_CheckPak0(), FS_InitFilesystem(), FS_Restart(), IN_ActivateMouse(), IN_InitJoystick(), IN_ProcessEvents(), RoQShutdown(), S_Init(), SV_BoundMaxClients(), SV_CheckPaused(), SV_Frame(), SV_Map_f(), SV_MapRestart_f(), SV_MasterHeartbeat(), SV_RankBegin(), SV_RankCloseContext(), SV_RankEnd(), SV_RankError(), SV_RankNewGameCBF(), SV_RateMsec(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), and Sys_Init().
cvar_t* Cvar_Set2 (const char * var_name, const char * value, qboolean force)
References Com_Printf(), CopyString(), CVAR_CHEAT, Cvar_FindVar(), Cvar_Get(), CVAR_INIT, CVAR_LATCH, cvar_modifiedFlags, CVAR_ROM, CVAR_USER_CREATED, Cvar_Validate(), Cvar_ValidateString(), cvar_s::flags, cvar_s::integer, cvar_s::latchedString, cvar_s::modificationCount, cvar_s::modified, NULL, qtrue, cvar_s::resetString, cvar_s::string, cvar_s::value, and Z_Free().
Referenced by CL_OldGame(), Com_StartupVariable(), Cvar_Command(), Cvar_ForceReset(), Cvar_Get(), Cvar_Reset(), Cvar_Restart(), Cvar_Set(), Cvar_Set_f(), Cvar_SetLatched(), and Cvar_Toggle_f().
void Cvar_SetCheatState (void)
References CVAR_CHEAT, Cvar_Set(), cvar_s::flags, cvar_s::latchedString, cvar_s::name, cvar_s::next, NULL, cvar_s::resetString, cvar_s::string, and Z_Free().
Referenced by CL_InitCGame(), and CL_SystemInfoChanged().
void Cvar_SetLatched (const char * var_name, const char * value)
References Cvar_Set2(), and qfalse.
Referenced by SV_Map_f().
void Cvar_SetSafe (const char * var_name, const char * value)
References Com_Error(), Cvar_Flags(), CVAR_NONEXISTENT, CVAR_PROTECTED, Cvar_Set(), and ERR_DROP.
Referenced by CL_CgameSystemCalls(), CL_SystemInfoChanged(), CL_UISystemCalls(), Cvar_SetValueSafe(), and SV_GameSystemCalls().
void Cvar_SetValue (const char * var_name, float value)
References Com_sprintf(), Cvar_Set(), and val.
Referenced by CL_BeginDownload(), CL_InitRef(), CL_KeyDownEvent(), CL_ParseDownload(), Com_Printf(), IN_Init(), IN_ProcessEvents(), NET_OpenIP(), NET_SetMulticast6(), and SV_Map_f().
void Cvar_SetValueSafe (const char * var_name, float value)
References Com_sprintf(), Cvar_SetSafe(), Q_isintegral(), and val.
Referenced by CL_UISystemCalls().
void Cvar_Update (vmCvar_t * vmCvar)
References Com_Error(), cvar_numIndexes, ERR_DROP, vmCvar_t::handle, cvar_s::integer, vmCvar_t::integer, MAX_CVAR_VALUE_STRING, cvar_s::modificationCount, vmCvar_t::modificationCount, NULL, Q_strncpyz(), cvar_s::string, vmCvar_t::string, cvar_s::value, and vmCvar_t::value.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Cvar_Register(), and SV_GameSystemCalls().
int Cvar_VariableIntegerValue (const char * var_name)
References Cvar_FindVar(), and cvar_s::integer.
Referenced by CL_GetPing(), CL_GlobalServers_f(), CL_Init(), CL_InitRef(), CL_KeyDownEvent(), CL_OpenAVIForWriting(), IN_ActivateMouse(), IN_DeactivateMouse(), IN_Frame(), SCR_UpdateScreen(), SV_BotInitBotLib(), SV_GameSystemCalls(), SV_MasterHeartbeat(), SVC_Info(), and Sys_GLimpInit().
char* Cvar_VariableString (const char * var_name)
References Cvar_FindVar(), and cvar_s::string.
Referenced by CL_GlobalServers_f(), CL_NextDemo(), CL_NextDownload(), CL_OpenAVIForWriting(), CL_SystemInfoChanged(), Cmd_Vstr_f(), Cvar_Toggle_f(), FS_InitFilesystem(), PrintCvarMatches(), RoQShutdown(), SV_Frame(), SV_MapRestart_f(), SV_RankBegin(), SVC_Info(), Sys_ErrorDialog(), Sys_LoadDll(), and UI_DrawConnectScreen().
void Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
References Cvar_FindVar(), Q_strncpyz(), and cvar_s::string.
Referenced by CL_CgameSystemCalls(), CL_ParseGamestate(), CL_SetModel_f(), CL_UISystemCalls(), and SV_GameSystemCalls().
float Cvar_VariableValue (const char * var_name)
References Cvar_FindVar(), and cvar_s::value.
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_InitCGame(), CL_InitUI(), CL_KeyDownEvent(), CL_Record_f(), CL_SystemInfoChanged(), CL_UISystemCalls(), Cvar_Toggle_f(), SV_GetChallenge(), SV_InitGameProgs(), SV_MapRestart_f(), SV_RankBegin(), SV_SpawnServer(), SVC_Info(), and SVC_Status().
void Cvar_WriteVariables (fileHandle_t f)
References buffer, Com_Printf(), Com_sprintf(), CVAR_ARCHIVE, cvar_s::flags, FS_Write(), cvar_s::latchedString, cvar_s::name, cvar_s::next, Q_stricmp(), S_COLOR_YELLOW, and cvar_s::string.
Referenced by Com_WriteConfigToFile().
void Field_AutoComplete (field_t * edit)
References field_t::buffer, field(), Field_CompleteCommand(), and qtrue.
Referenced by CON_Input(), and Console_Key().
void Field_Clear (field_t * edit)
References field_t::buffer, field_t::cursor, MAX_EDIT_LINE, and field_t::scroll.
Referenced by CL_LoadConsoleHistory(), Con_Close(), CON_Init(), Con_Init(), CON_Input(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), Con_ToggleConsole_f(), Console_Key(), Field_CharEvent(), Message_Key(), and UI_DrawConnectScreen().
void Field_CompleteCommand (char * cmd, qboolean doCommands, qboolean doCvars)
References field_t::buffer, Cmd_Argc(), Cmd_Argv(), Cmd_CommandCompletion(), Cmd_CompleteArgument(), Cmd_TokenizeStringIgnoreQuotes(), Com_SkipCharset(), field_t::cursor, Cvar_CommandCompletion(), Field_Complete(), Field_CompleteCommand(), Field_FindFirstSeparator(), FindMatches(), memmove(), PrintCvarMatches(), PrintMatches(), and qtrue.
Referenced by CL_CompleteRcon(), Cvar_CompleteCvarName(), Field_AutoComplete(), Field_CompleteCommand(), and Key_CompleteBind().
void Field_CompleteFilename (const char * dir, const char * ext, qboolean stripExt, qboolean allowNonPureFilesOnDisk)
References Field_Complete(), FindMatches(), FS_FilenameCompletion(), and PrintMatches().
Referenced by CL_CompleteDemoName(), Cmd_CompleteCfgName(), Cmd_CompleteTxtName(), and SV_CompleteMapName().
void Field_CompleteKeyname (void)
References Field_Complete(), FindMatches(), Key_KeynameCompletion(), and PrintMatches().
Referenced by Key_CompleteBind(), and Key_CompleteUnbind().
void QDECL void QDECL void QDECL format (printf , 2 , 3)
void QDECL format (printf , 1 , 2)
void FS_AddGameDirectory (const char * path, const char * dir)
References searchpath_s::dir, FS_BuildOSPath(), fs_gamedir, FS_LoadZipFile(), fs_packFiles, fs_searchpaths, directory_t::fullpath, directory_t::gamedir, MAX_OSPATH, searchpath_s::next, NULL, pack_t::numfiles, searchpath_s::pack, pack_t::pakGamename, pack_t::pakPathname, paksort(), directory_t::path, Q_stricmp(), Q_strncpyz(), qfalse, Sys_FreeFileList(), Sys_ListFiles(), and Z_Malloc.
Referenced by FS_Startup().
char* FS_BuildOSPath (const char * base, const char * game, const char * qpath)
References Com_sprintf(), fs_gamedir, FS_ReplaceSeparators(), and MAX_OSPATH.
Referenced by CL_NextDownload(), FS_AddGameDirectory(), FS_FCreateOpenPipeFile(), FS_FileExists(), FS_FindVM(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_GetModList(), FS_HomeRemove(), FS_ListFilteredFiles(), FS_Rename(), FS_SV_FileExists(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), and Sys_ErrorDialog().
qboolean FS_CheckDirTraversal (const char * checkdir)
References qfalse, and qtrue.
Referenced by CL_SystemInfoChanged(), and FS_ComparePaks().
void FS_ClearPakReferences (int flags)
References searchpath_s::next, searchpath_s::pack, and pack_t::referenced.
Referenced by CL_Vid_Restart_f(), FS_Restart(), and SV_SpawnServer().
qboolean FS_ComparePaks (char * neededpaks, int len, qboolean dlstring)
References BASEGAME, BASETA, pack_t::checksum, Com_Printf(), Com_sprintf(), FS_CheckDirTraversal(), FS_idPak(), fs_numServerReferencedPaks, fs_serverReferencedPakNames, fs_serverReferencedPaks, FS_SV_FileExists(), MAX_ZPATH, searchpath_s::next, NUM_ID_PAKS, NUM_TA_PAKS, searchpath_s::pack, Q_strcat(), qfalse, qtrue, and va().
Referenced by CL_InitDownloads().
qboolean FS_CompareZipChecksum (const char * zipfile)
References pack_t::checksum, FS_FreePak(), FS_LoadZipFile(), fs_numServerReferencedPaks, fs_serverReferencedPaks, qfalse, and qtrue.
Referenced by CL_NextDownload().
qboolean FS_ConditionalRestart (int checksumFeed, qboolean disconnect)
References com_basegame, Com_GameRestart(), fs_checksumFeed, FS_FilenameCompare(), fs_numServerPaks, fs_reordered, FS_ReorderPurePaks(), FS_Restart(), lastValidGame, cvar_s::modified, qfalse, qtrue, and cvar_s::string.
Referenced by CL_OldGame(), CL_ParseGamestate(), and CL_Vid_Restart_f().
qboolean FS_CreatePath (char * OSPath)
References Com_Error(), Com_Printf(), ERR_FATAL, FS_ReplaceSeparators(), MAX_OSPATH, NULL, Q_strncpyz(), qfalse, qtrue, and Sys_Mkdir().
Referenced by FS_FOpenFileAppend(), FS_FOpenFileWrite(), FS_Startup(), FS_SV_FOpenFileWrite(), and Sys_ErrorDialog().
void FS_FCloseFile (fileHandle_t f)
References Com_Error(), Com_Memset, ERR_FATAL, fclose(), qtrue, unzClose(), and unzCloseCurrentFile().
Referenced by CL_CgameSystemCalls(), CL_CloseAVI(), CL_DemoCompleted(), CL_Disconnect(), CL_GenerateQKey(), CL_LoadConsoleHistory(), CL_OpenAVIForWriting(), CL_ParseDownload(), CL_SaveConsoleHistory(), CL_StopRecord_f(), CL_UISystemCalls(), CL_UpdateGUID(), Com_AppendCDKey(), Com_MD5File(), Com_ReadCDKey(), Com_Shutdown(), Com_WriteCDKey(), Com_WriteConfigToFile(), Con_Dump_f(), FS_GetModList(), FS_ReadFileDir(), FS_Shutdown(), FS_TouchFile_f(), FS_WriteFile(), LAN_LoadCachedServers(), LAN_SaveServersToCache(), RoQReset(), RoQShutdown(), S_CodecUtilClose(), S_CodecUtilOpen(), S_WAV_CodecLoad(), SV_BotInitBotLib(), SV_CloseDownload(), SV_GameSystemCalls(), SV_RehashBans_f(), SV_TouchCGame(), SV_WriteBans(), and SV_WriteDownloadToClient().
fileHandle_t FS_FCreateOpenPipeFile (const char * filename)
References __func__, Com_Error(), Com_Printf(), ERR_FATAL, qfile_us::file, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), fs_gamedir, FS_HandleForFile(), fileHandleData_t::handleFiles, fileHandleData_t::handleSync, cvar_s::integer, qfile_gus::o, Q_strncpyz(), qfalse, S_ClearSoundBuffer(), S_COLOR_YELLOW, cvar_s::string, Sys_Mkfifo(), and fileHandleData_t::zipFile.
Referenced by Com_Init().
qboolean FS_FileExists (const char * file)
References FS_BuildOSPath(), FS_FileInPathExists(), fs_gamedir, and cvar_s::string.
Referenced by CL_InitRef(), CL_Record_f(), and CL_Video_f().
int FS_FileIsInPAK (const char * filename, int * pChecksum)
References Com_Error(), ERR_FATAL, FS_FilenameCompare(), FS_HashFileName(), FS_PakIsPure(), hash(), pack_t::hashSize, pack_t::hashTable, fileInPack_s::name, fileInPack_s::next, searchpath_s::next, NULL, searchpath_s::pack, and pack_t::pure_checksum.
Referenced by CL_InitRef(), and SV_VerifyPaks_f().
long FS_filelength (fileHandle_t f)
References FS_FileForHandle(), FS_fplength(), h, and NULL.
Referenced by FS_SV_FOpenFileRead().
qboolean FS_FilenameCompare (const char * s1, const char * s2)
References qfalse, and qtrue.
Referenced by Com_GameRestart_f(), FS_ConditionalRestart(), FS_FileIsInPAK(), FS_FindVM(), FS_FOpenFileReadDir(), FS_idPak(), FS_InitFilesystem(), SV_WriteDownloadToClient(), and Sys_LoadDll().
void FS_FilenameCompletion (const char * dir, const char * ext, qboolean stripExt, void(*)(const char *s) callback, qboolean allowNonPureFilesOnDisk)
References COM_StripExtension(), FS_ConvertPath(), FS_FreeFileList(), FS_ListFilteredFiles(), FS_SortFileList(), MAX_STRING_CHARS, NULL, and Q_strncpyz().
Referenced by Field_CompleteFilename().
vmInterpret_t FS_FindVM (void ** startSearch, char * found, int foundlen, const char * name, int enableDll)
References Com_Error(), Com_sprintf(), searchpath_s::dir, ERR_FATAL, FS_BuildOSPath(), FS_FileInPathExists(), FS_FilenameCompare(), FS_FOpenFileReadDir(), fs_numServerPaks, fs_searchpaths, directory_t::gamedir, MAX_OSPATH, searchpath_s::next, NULL, searchpath_s::pack, pack_t::pakPathname, directory_t::path, Q_strncpyz(), qfalse, VMI_COMPILED, and VMI_NATIVE.
Referenced by VM_Create().
void FS_Flush (fileHandle_t f)
Referenced by FS_ReadFileDir().
fileHandle_t FS_FOpenFileAppend (const char * filename)
References __func__, Com_Error(), Com_Printf(), ERR_FATAL, qfile_us::file, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), FS_CreatePath(), fs_gamedir, FS_HandleForFile(), fileHandleData_t::handleFiles, fileHandleData_t::handleSync, cvar_s::integer, qfile_gus::o, Q_strncpyz(), qfalse, S_ClearSoundBuffer(), cvar_s::string, and fileHandleData_t::zipFile.
Referenced by FS_FOpenFileByMode().
void QDECL int FS_FOpenFileByMode (const char * qpath, fileHandle_t * f, fsMode_t mode)
References fileHandleData_t::baseOffset, Com_Error(), ERR_FATAL, fileHandleData_t::fileSize, FS_APPEND, FS_APPEND_SYNC, FS_FOpenFileAppend(), FS_FOpenFileRead(), FS_FOpenFileWrite(), FS_READ, FS_WRITE, fileHandleData_t::handleSync, qfalse, qtrue, fileHandleData_t::streamed, and unztell().
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), SV_BotInitBotLib(), and SV_GameSystemCalls().
long FS_FOpenFileRead (const char * qpath, fileHandle_t * file, qboolean uniqueFILE)
References Com_Error(), ERR_FATAL, FS_FOpenFileReadDir(), searchpath_s::next, NULL, and qfalse.
Referenced by CIN_PlayCinematic(), CL_CloseAVI(), CL_LoadConsoleHistory(), CL_PlayDemo_f(), CL_WalkDemoExt(), Com_InitJournaling(), FS_FOpenFileByMode(), FS_ReadFileDir(), FS_TouchFile_f(), RoQReset(), S_CodecUtilOpen(), S_WAV_CodecLoad(), and SV_TouchCGame().
fileHandle_t FS_FOpenFileWrite (const char * qpath)
References __func__, Com_Error(), Com_Printf(), ERR_FATAL, qfile_us::file, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), FS_CreatePath(), fs_gamedir, FS_HandleForFile(), fileHandleData_t::handleFiles, fileHandleData_t::handleSync, cvar_s::integer, qfile_gus::o, Q_strncpyz(), qfalse, cvar_s::string, and fileHandleData_t::zipFile.
Referenced by CL_DemoCompleted(), CL_OpenAVIForWriting(), CL_Record_f(), CL_SaveConsoleHistory(), Com_InitJournaling(), Com_Printf(), Com_WriteConfigToFile(), Con_Dump_f(), FS_FOpenFileByMode(), and FS_WriteFile().
void FS_ForceFlush (fileHandle_t f)
References file, FS_FileForHandle(), and NULL.
Referenced by Com_Printf().
void FS_FreeFile (void * buffer)
References Com_Error(), ERR_FATAL, fs_loadStack, Hunk_ClearTempMemory(), and Hunk_FreeTempMemory().
Referenced by CL_InitRef(), CM_LoadMap(), Cmd_Exec_f(), VM_Create(), VM_LoadQVM(), VM_LoadSymbols(), and VM_Restart().
void FS_FreeFileList (char ** list)
References Com_Error(), ERR_FATAL, and Z_Free().
Referenced by CL_InitRef(), FS_Dir_f(), FS_FilenameCompletion(), FS_GetFileList(), and FS_NewDir_f().
int FS_FTell (fileHandle_t f)
References qtrue, and unztell().
Referenced by SCR_DrawDemoRecording().
const char* FS_GamePureChecksum (void)
References pack_t::checksum, Com_sprintf(), FS_QAGAME_REF, info, MAX_STRING_TOKENS, searchpath_s::next, searchpath_s::pack, and pack_t::referenced.
const char* FS_GetCurrentGameDir (void)
References com_basegame, and cvar_s::string.
Referenced by SV_RehashBans_f(), and SV_WriteBans().
int FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
References FS_FreeFileList(), FS_GetModList(), FS_ListFiles(), NULL, and Q_stricmp().
Referenced by CL_UISystemCalls(), and SV_GameSystemCalls().
int FS_GetModList (char * listbuf, int bufsize)
References com_basegame, Com_Memset, file, fread(), FS_BuildOSPath(), FS_FCloseFile(), FS_FileForHandle(), FS_SV_FOpenFileRead(), MAX_OSPATH, NULL, Q_stricmp(), Q_stricmpn(), qfalse, qtrue, cvar_s::string, Sys_ConcatenateFileLists(), Sys_CountFileList(), Sys_FreeFileList(), and Sys_ListFiles().
Referenced by FS_GetFileList().
void FS_HomeRemove (const char * homePath)
References __func__, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), fs_gamedir, and cvar_s::string.
Referenced by CL_CloseAVI(), and Com_Shutdown().
qboolean FS_idPak (char * pak, char * base, int numPaks)
References FS_FilenameCompare(), NUM_ID_PAKS, qfalse, qtrue, and va().
Referenced by FS_ComparePaks(), and SV_WriteDownloadToClient().
void FS_InitFilesystem (void)
References com_basegame, Com_Error(), Com_StartupVariable(), Cvar_Set(), Cvar_VariableString(), ERR_FATAL, FS_CheckPak0(), FS_FilenameCompare(), FS_ReadFile(), FS_Startup(), lastValidBase, lastValidGame, NULL, Q_strncpyz(), and cvar_s::string.
Referenced by Com_Init().
qboolean FS_Initialized (void)
References NULL.
Referenced by Com_Printf(), Hunk_Log(), Hunk_SmallLog(), and Z_LogZoneHeap().
char** FS_ListFiles (const char * directory, const char * extension, int * numfiles)
References FS_ListFilteredFiles(), NULL, and qfalse.
Referenced by CL_InitRef(), FS_Dir_f(), and FS_GetFileList().
const char* FS_LoadedPakChecksums (void)
References BIG_INFO_STRING, pack_t::checksum, info, searchpath_s::next, searchpath_s::pack, Q_strcat(), and va().
Referenced by SV_SpawnServer().
const char* FS_LoadedPakNames (void)
References BIG_INFO_STRING, info, searchpath_s::next, searchpath_s::pack, pack_t::pakBasename, and Q_strcat().
Referenced by CL_OpenedPK3List_f(), and SV_SpawnServer().
const char* FS_LoadedPakPureChecksums (void)
References BIG_INFO_STRING, info, searchpath_s::next, searchpath_s::pack, pack_t::pure_checksum, Q_strcat(), and va().
Referenced by SV_VerifyPaks_f().
int FS_LoadStack (void)
References fs_loadStack.
Referenced by Com_InitHunkMemory().
void QDECL FS_Printf (fileHandle_t f, const char * fmt, ...)
void FS_PureServerSetLoadedPaks (const char * pakSums, const char * pakNames)
References Cmd_Argc(), Cmd_Argv(), Cmd_TokenizeString(), Com_DPrintf(), CopyString(), fs_checksumFeed, fs_numServerPaks, fs_reordered, FS_Restart(), fs_serverPakNames, fs_serverPaks, MAX_SEARCH_PATHS, NULL, and Z_Free().
Referenced by CL_Disconnect(), CL_SystemInfoChanged(), Com_Error(), and FS_Restart().
void FS_PureServerSetReferencedPaks (const char * pakSums, const char * pakNames)
References ARRAY_LEN, Cmd_Argc(), Cmd_Argv(), Cmd_TokenizeString(), CopyString(), fs_numServerReferencedPaks, fs_serverReferencedPakNames, fs_serverReferencedPaks, MAX_SEARCH_PATHS, NULL, and Z_Free().
Referenced by CL_SystemInfoChanged().
int FS_Read (void * buffer, int len, fileHandle_t f)
References Com_Error(), ERR_FATAL, fread(), fs_readCount, qfalse, and unzReadCurrentFile().
Referenced by CIN_PlayCinematic(), CL_CloseAVI(), CL_LoadConsoleHistory(), CL_ReadDemoMessage(), Com_AppendCDKey(), Com_GetRealEvent(), Com_ReadCDKey(), Com_ReadFromPipe(), FGetLittleLong(), FGetLittleShort(), FS_Read2(), FS_ReadFileDir(), FS_Seek(), LAN_LoadCachedServers(), RoQInterrupt(), RoQReset(), S_ReadChunkInfo(), S_ReadRIFFHeader(), S_WAV_CodecLoad(), S_WAV_CodecReadStream(), SV_RehashBans_f(), and SV_WriteDownloadToClient().
int FS_Read2 (void * buffer, int len, fileHandle_t f)
References Com_Error(), ERR_FATAL, FS_Read(), qfalse, qtrue, and fileHandleData_t::streamed.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Com_MD5File(), SV_BotInitBotLib(), and SV_GameSystemCalls().
long FS_ReadFile (const char * qpath, void ** buffer)
References FS_ReadFileDir(), NULL, and qfalse.
Referenced by CL_InitRef(), CM_LoadMap(), Cmd_Exec_f(), FS_InitFilesystem(), FS_Restart(), SV_Map_f(), and VM_LoadSymbols().
long FS_ReadFileDir (const char * qpath, void * searchPath, qboolean unpure, void ** buffer)
References Com_DPrintf(), Com_Error(), com_journal, com_journalDataFile, ERR_FATAL, FS_FCloseFile(), FS_Flush(), FS_FOpenFileRead(), FS_FOpenFileReadDir(), fs_loadCount, fs_loadStack, FS_Read(), FS_Write(), h, Hunk_AllocateTempMemory(), cvar_s::integer, NULL, qfalse, and qtrue.
Referenced by FS_ReadFile(), and VM_LoadQVM().
const char* FS_ReferencedPakChecksums (void)
References BIG_INFO_STRING, pack_t::checksum, com_basegame, info, searchpath_s::next, searchpath_s::pack, pack_t::pakGamename, Q_strcat(), Q_stricmpn(), pack_t::referenced, cvar_s::string, and va().
Referenced by SV_SpawnServer().
const char* FS_ReferencedPakNames (void)
References BIG_INFO_STRING, com_basegame, info, searchpath_s::next, searchpath_s::pack, pack_t::pakBasename, pack_t::pakGamename, Q_strcat(), Q_stricmpn(), pack_t::referenced, and cvar_s::string.
Referenced by CL_ReferencedPK3List_f(), SV_SpawnServer(), and SV_WriteDownloadToClient().
const char* FS_ReferencedPakPureChecksums (void)
References BIG_INFO_STRING, FS_CGAME_REF, fs_checksumFeed, FS_GENERAL_REF, FS_UI_REF, info, searchpath_s::next, searchpath_s::pack, pack_t::pure_checksum, Q_strcat(), pack_t::referenced, and va().
Referenced by CL_SendPureChecksums().
void FS_Remove (const char * osPath)
References __func__, and FS_CheckFilenameIsNotExecutable().
Referenced by Sys_Mkfifo().
void FS_Rename (const char * from, const char * to)
References __func__, Com_Error(), Com_Printf(), ERR_FATAL, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), fs_gamedir, cvar_s::integer, S_ClearSoundBuffer(), and cvar_s::string.
void FS_Restart (int checksumFeed)
References Cbuf_AddText(), com_basegame, Com_Error(), Com_SafeMode(), Cvar_Set(), ERR_DROP, ERR_FATAL, FS_CheckPak0(), fs_checksumFeed, FS_ClearPakReferences(), FS_PureServerSetLoadedPaks(), FS_ReadFile(), FS_Restart(), FS_Shutdown(), FS_Startup(), lastValidBase, lastValidGame, NULL, Q3CONFIG_CFG, Q_stricmp(), Q_strncpyz(), qfalse, and cvar_s::string.
Referenced by CL_DownloadsComplete(), Com_GameRestart(), FS_ConditionalRestart(), FS_PureServerSetLoadedPaks(), FS_Restart(), and SV_SpawnServer().
int FS_Seek (fileHandle_t f, long offset, int origin)
References buffer, Com_Error(), ERR_FATAL, file, FS_FileForHandle(), FS_Read(), FS_Seek(), FS_SEEK_CUR, FS_SEEK_END, FS_SEEK_SET, PK3_SEEK_BUFFER_SIZE, qfalse, qtrue, SEEK_CUR, SEEK_END, SEEK_SET, fileHandleData_t::streamed, unzOpenCurrentFile(), unzSetOffset(), and fileHandleData_t::zipFilePos.
Referenced by CL_CgameSystemCalls(), CL_CloseAVI(), CL_UISystemCalls(), FS_Seek(), S_FindRIFFChunk(), S_ReadRIFFHeader(), SV_BotInitBotLib(), and SV_GameSystemCalls().
void FS_Shutdown (qboolean closemfp)
References Cmd_RemoveCommand(), searchpath_s::dir, fclose(), FS_FCloseFile(), FS_FreePak(), MAX_FILE_HANDLES, searchpath_s::next, NULL, searchpath_s::pack, and Z_Free().
Referenced by Com_Quit_f(), and FS_Restart().
long FS_SV_FOpenFileRead (const char * filename, fileHandle_t * fp)
References Com_Error(), Com_Printf(), ERR_FATAL, qfile_us::file, FS_BuildOSPath(), FS_filelength(), FS_HandleForFile(), fileHandleData_t::handleFiles, fileHandleData_t::handleSync, cvar_s::integer, qfile_gus::o, Q_stricmp(), Q_strncpyz(), qfalse, S_ClearSoundBuffer(), cvar_s::string, and fileHandleData_t::zipFile.
Referenced by CL_GenerateQKey(), CL_UpdateGUID(), Com_AppendCDKey(), Com_MD5File(), Com_ReadCDKey(), FS_GetModList(), LAN_LoadCachedServers(), SV_RehashBans_f(), and SV_WriteDownloadToClient().
fileHandle_t FS_SV_FOpenFileWrite (const char * filename)
References __func__, Com_DPrintf(), Com_Error(), Com_Printf(), ERR_FATAL, qfile_us::file, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), FS_CreatePath(), FS_HandleForFile(), fileHandleData_t::handleFiles, fileHandleData_t::handleSync, cvar_s::integer, qfile_gus::o, Q_strncpyz(), qfalse, cvar_s::string, and fileHandleData_t::zipFile.
Referenced by CL_GenerateQKey(), CL_ParseDownload(), Com_WriteCDKey(), LAN_SaveServersToCache(), and SV_WriteBans().
void FS_SV_Rename (const char * from, const char * to)
References __func__, Com_Error(), Com_Printf(), ERR_FATAL, FS_BuildOSPath(), FS_CheckFilenameIsNotExecutable(), cvar_s::integer, S_ClearSoundBuffer(), and cvar_s::string.
Referenced by CL_ParseDownload().
qboolean FS_Which (const char * filename, void * searchPath)
References Com_Printf(), searchpath_s::dir, FS_FOpenFileReadDir(), directory_t::fullpath, NULL, searchpath_s::pack, pack_t::pakFilename, qfalse, and qtrue.
Referenced by FS_Which_f(), and VM_LoadQVM().
int FS_Write (const void * buffer, int len, fileHandle_t f)
References Com_Error(), Com_Printf(), ERR_FATAL, FS_FileForHandle(), and fwrite().
Referenced by CL_CgameSystemCalls(), CL_GenerateQKey(), CL_ParseDownload(), CL_Record_f(), CL_SaveConsoleHistory(), CL_StopRecord_f(), CL_UISystemCalls(), CL_WriteDemoMessage(), Com_GetRealEvent(), Com_Printf(), Com_WriteCDKey(), Con_Dump_f(), Cvar_WriteVariables(), FS_Printf(), FS_ReadFileDir(), FS_WriteFile(), Hunk_Log(), Hunk_SmallLog(), LAN_SaveServersToCache(), SafeFS_Write(), SV_BotInitBotLib(), SV_GameSystemCalls(), SV_WriteBans(), and Z_LogZoneHeap().
void FS_WriteFile (const char * qpath, const void * buffer, int size)
References Com_Error(), Com_Printf(), ERR_FATAL, FS_FCloseFile(), FS_FOpenFileWrite(), and FS_Write().
Referenced by CL_InitRef().
void Huff_addRef (huff_t * huff, byte ch)
References huff_t::blocNode, get_ppnode(), nodetype::head, increment(), INTERNAL_NODE, nodetype::left, huff_t::lhead, huff_t::loc, nodetype::next, huff_t::nodeList, NULL, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, tnode(), huff_t::tree, and nodetype::weight.
Referenced by Huff_Compress(), Huff_Decompress(), and MSG_initHuffman().
void Huff_Compress (msg_t * buf, int offset)
References bloc, huff_t::blocNode, buffer, Com_Memcpy, Com_Memset, msg_t::cursize, msg_t::data, Huff_addRef(), Huff_transmit(), nodetype::left, huff_t::lhead, huff_t::loc, nodetype::next, huff_t::nodeList, NULL, NYT, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, huff_t::tree, and nodetype::weight.
Referenced by NET_OutOfBandData().
void Huff_Decompress (msg_t * buf, int offset)
References bloc, huff_t::blocNode, buffer, Com_Memcpy, Com_Memset, msg_t::cursize, msg_t::data, get_bit(), Huff_addRef(), Huff_Receive(), nodetype::left, huff_t::lhead, huff_t::loc, huff_t::ltail, msg_t::maxsize, nodetype::next, huff_t::nodeList, NULL, NYT, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, huff_t::tree, and nodetype::weight.
Referenced by SV_ConnectionlessPacket().
int Huff_getBit (byte * fout, int * offset)
References bloc, and t.
Referenced by MSG_ReadBits().
int Huff_getBloc (void)
References bloc.
Referenced by MSG_LookaheadByte().
void Huff_Init (huffman_t * huff)
References huff_t::blocNode, Com_Memset, huffman_t::compressor, huffman_t::decompressor, nodetype::left, huff_t::lhead, huff_t::loc, huff_t::ltail, nodetype::next, huff_t::nodeList, NULL, NYT, nodetype::parent, nodetype::prev, nodetype::right, nodetype::symbol, huff_t::tree, and nodetype::weight.
Referenced by MSG_initHuffman().
void Huff_offsetReceive (node_t * node, int * ch, byte * fin, int * offset)
References bloc, get_bit(), INTERNAL_NODE, nodetype::left, nodetype::right, and nodetype::symbol.
Referenced by MSG_ReadBits().
void Huff_offsetTransmit (huff_t * huff, int ch, byte * fout, int * offset)
References bloc, huff_t::loc, NULL, and send().
Referenced by MSG_WriteBits().
void Huff_putBit (int bit, byte * fout, int * offset)
References bloc.
Referenced by MSG_WriteBits().
int Huff_Receive (node_t * node, int * ch, byte * fin)
References get_bit(), INTERNAL_NODE, nodetype::left, nodetype::right, and nodetype::symbol.
Referenced by Huff_Decompress().
void Huff_setBloc (int _bloc)
References bloc.
Referenced by MSG_LookaheadByte().
void Huff_transmit (huff_t * huff, int ch, byte * fout)
References add_bit(), Huff_transmit(), huff_t::loc, NULL, NYT, and send().
Referenced by Huff_Compress(), and Huff_transmit().
void* Hunk_AllocateTempMemory (int size)
References Com_Error(), ERR_DROP, HUNK_MAGIC, Hunk_SwapBanks(), intptr_t(), hunkHeader_t::magic, NULL, PAD, hunkUsed_t::permanent, hunkHeader_t::size, hunkUsed_t::temp, hunkUsed_t::tempHighwater, and Z_Malloc.
Referenced by CIN_DrawCinematic(), CIN_UploadCinematic(), CL_InitRef(), FS_ReadFileDir(), S_LoadSound(), S_WAV_CodecLoad(), and SV_ChangeMaxClients().
qboolean Hunk_CheckMark (void)
References hunkUsed_t::mark, qfalse, and qtrue.
Referenced by BotImport_HunkAlloc().
void Hunk_Clear (void)
References CIN_CloseAllVideos(), CL_ShutdownCGame(), CL_ShutdownUI(), Com_Printf(), hunk_high, hunk_low, hunkUsed_t::mark, NULL, hunkUsed_t::permanent, SV_ShutdownGameProgs(), hunkUsed_t::temp, hunkUsed_t::tempHighwater, and VM_Clear().
Referenced by CL_ClearMemory(), CL_Vid_Restart_f(), Com_InitHunkMemory(), and SV_SpawnServer().
void Hunk_ClearTempMemory (void)
References NULL, hunkUsed_t::permanent, and hunkUsed_t::temp.
Referenced by FS_FreeFile().
void Hunk_ClearToMark (void)
References hunkUsed_t::mark, hunkUsed_t::permanent, and hunkUsed_t::temp.
Referenced by CL_ClearMemory(), and CL_Vid_Restart_f().
void Hunk_FreeTempMemory (void * buf)
References Com_Error(), Com_Printf(), ERR_FATAL, HUNK_FREE_MAGIC, HUNK_MAGIC, hunkHeader_t::magic, NULL, hunkHeader_t::size, hunkUsed_t::temp, and Z_Free().
Referenced by CIN_DrawCinematic(), CIN_UploadCinematic(), CL_InitRef(), FS_FreeFile(), S_LoadSound(), and SV_ChangeMaxClients().
void Hunk_Log (void)
References Com_sprintf(), hunkblock_s::file, FS_Initialized(), FS_Write(), hunkblock_s::label, hunkblock_s::line, logfile, hunkblock_s::next, and hunkblock_s::size.
Referenced by Com_InitHunkMemory(), and Hunk_AllocDebug().
int Hunk_MemoryRemaining (void)
References hunkUsed_t::permanent, and hunkUsed_t::temp.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and VM_Create().
void Hunk_SetMark (void)
References hunkUsed_t::mark, and hunkUsed_t::permanent.
Referenced by SV_SpawnServer().
void Info_Print (const char * s)
References BIG_INFO_KEY, BIG_INFO_VALUE, Com_Memset, Com_Printf(), and value().
Referenced by CL_Clientinfo_f(), SV_DumpUser_f(), SV_Serverinfo_f(), and SV_Systeminfo_f().
void Key_KeynameCompletion (void(*)(const char *s) callback)
References keyname_t::name, and NULL.
Referenced by Field_CompleteKeyname().
void Key_WriteBindings (fileHandle_t f)
References FS_Printf(), Key_KeynumToString(), and MAX_KEYS.
Referenced by Com_WriteConfigToFile().
void MSG_BeginReading (msg_t * sb)
References msg_t::bit, msg_t::oob, qfalse, and msg_t::readcount.
void MSG_BeginReadingOOB (msg_t * sb)
References msg_t::bit, msg_t::oob, qtrue, and msg_t::readcount.
Referenced by CL_ConnectionlessPacket(), Netchan_Process(), SV_ConnectionlessPacket(), and SV_PacketEvent().
void MSG_Bitstream (msg_t * buf)
References msg_t::oob, and qfalse.
Referenced by CL_ParseServerMessage(), CL_Record_f(), CL_WritePacket(), and SV_ExecuteClientMessage().
void MSG_Clear (msg_t * buf)
References msg_t::bit, msg_t::cursize, msg_t::overflowed, and qfalse.
Referenced by SV_SendClientSnapshot().
void MSG_Copy (msg_t * buf, byte * data, int length, msg_t * src)
References Com_Error(), Com_Memcpy, msg_t::cursize, msg_t::data, data, and ERR_DROP.
Referenced by SV_Netchan_Transmit().
int MSG_HashKey (const char * string, int maxlen)
References hash().
Referenced by CL_WritePacket(), and SV_UserMove().
void MSG_Init (msg_t * buf, byte * data, int length)
References Com_Memset, msg_t::data, data, length(), msg_t::maxsize, MSG_initHuffman(), and msgInit.
Referenced by CL_ReadDemoMessage(), CL_Record_f(), CL_WritePacket(), Com_EventLoop(), NET_Event(), SV_SendClientGameState(), SV_SendClientSnapshot(), and SV_SendDownloadMessages().
void MSG_InitOOB (msg_t * buf, byte * data, int length)
References Com_Memset, msg_t::data, data, length(), msg_t::maxsize, MSG_initHuffman(), msgInit, msg_t::oob, and qtrue.
Referenced by Netchan_Transmit(), and Netchan_TransmitNextFragment().
int MSG_LookaheadByte (msg_t * msg)
References msg_t::bit, bloc, Huff_getBloc(), Huff_setBloc(), MSG_ReadByte(), and msg_t::readcount.
float MSG_ReadAngle16 (msg_t * sb)
References MSG_ReadShort(), and SHORT2ANGLE.
char* MSG_ReadBigString (msg_t * sb)
References BIG_INFO_STRING, MSG_ReadByte(), and string().
Referenced by CL_ParseGamestate().
int MSG_ReadBits (msg_t * msg, int bits)
References msg_t::bit, bits(), Com_Error(), msg_t::data, huffman_t::decompressor, ERR_DROP, Huff_getBit(), Huff_offsetReceive(), msg_t::oob, qfalse, qtrue, msg_t::readcount, huff_t::tree, and value().
Referenced by CL_ParseGamestate(), CL_ParsePacketEntities(), MSG_ReadByte(), MSG_ReadChar(), MSG_ReadDelta(), MSG_ReadDeltaEntity(), MSG_ReadDeltaFloat(), MSG_ReadDeltaKey(), MSG_ReadDeltaKeyFloat(), MSG_ReadDeltaPlayerstate(), MSG_ReadDeltaUsercmd(), MSG_ReadDeltaUsercmdKey(), MSG_ReadFloat(), MSG_ReadLong(), and MSG_ReadShort().
int MSG_ReadByte (msg_t * sb)
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
Referenced by CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), MSG_LookaheadByte(), MSG_ReadBigString(), MSG_ReadData(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReadString(), MSG_ReadStringLine(), SV_ExecuteClientMessage(), and SV_UserMove().
int MSG_ReadChar (msg_t * sb)
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
void MSG_ReadData (msg_t * sb, void * buffer, int size)
References MSG_ReadByte().
Referenced by CL_ParseDownload(), and CL_ParseSnapshot().
void MSG_ReadDeltaEntity (msg_t * msg, entityState_t * from, entityState_t * to, int number)
References ARRAY_LEN, msg_t::bit, netField_t::bits, Com_Error(), Com_Memset, Com_Printf(), ERR_DROP, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, GENTITYNUM_BITS, cvar_s::integer, MAX_GENTITIES, MSG_ReadBits(), MSG_ReadByte(), netField_t::name, entityState_s::number, netField_t::offset, print(), and msg_t::readcount.
Referenced by CL_DeltaEntity(), and CL_ParseGamestate().
void MSG_ReadDeltaPlayerstate (msg_t * msg, struct playerState_s * from, struct playerState_s * to)
References playerState_s::ammo, ARRAY_LEN, msg_t::bit, bits(), netField_t::bits, Com_Error(), Com_Memset, Com_Printf(), ERR_DROP, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, GENTITYNUM_BITS, cvar_s::integer, LOG, MAX_PERSISTANT, MAX_POWERUPS, MAX_STATS, MAX_WEAPONS, MSG_ReadBits(), MSG_ReadByte(), MSG_ReadLong(), MSG_ReadShort(), netField_t::name, netField_t::offset, playerState_s::persistant, playerState_s::powerups, print(), msg_t::readcount, and playerState_s::stats.
Referenced by CL_ParseSnapshot().
void MSG_ReadDeltaUsercmd (msg_t * msg, struct usercmd_s * from, struct usercmd_s * to)
References usercmd_s::angles, usercmd_s::buttons, usercmd_s::forwardmove, MSG_ReadBits(), MSG_ReadDelta(), usercmd_s::rightmove, usercmd_s::serverTime, usercmd_s::upmove, and usercmd_s::weapon.
void MSG_ReadDeltaUsercmdKey (msg_t * msg, int key, usercmd_t * from, usercmd_t * to)
References usercmd_s::angles, usercmd_s::buttons, usercmd_s::forwardmove, MSG_ReadBits(), MSG_ReadDeltaKey(), usercmd_s::rightmove, usercmd_s::serverTime, usercmd_s::upmove, and usercmd_s::weapon.
Referenced by SV_UserMove().
float MSG_ReadFloat (msg_t * sb)
References msg_t::cursize, floatint_t::f, floatint_t::i, MSG_ReadBits(), and msg_t::readcount.
int MSG_ReadLong (msg_t * sb)
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
Referenced by CL_ConnectionlessPacket(), CL_Netchan_Decode(), CL_Netchan_Encode(), CL_ParseCommandString(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), MSG_ReadDeltaPlayerstate(), Netchan_Process(), SV_ClientCommand(), SV_ConnectionlessPacket(), SV_ExecuteClientMessage(), SV_Netchan_Decode(), SV_Netchan_Encode(), and SV_PacketEvent().
int MSG_ReadShort (msg_t * sb)
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
Referenced by CL_ParseDownload(), CL_ParseGamestate(), MSG_ReadAngle16(), MSG_ReadDeltaPlayerstate(), Netchan_Process(), and SV_PacketEvent().
char* MSG_ReadString (msg_t * sb)
References MAX_STRING_CHARS, MSG_ReadByte(), and string().
Referenced by CL_ConnectionlessPacket(), CL_ParseCommandString(), CL_ParseDownload(), CL_ServerInfoPacket(), and SV_ClientCommand().
char* MSG_ReadStringLine (msg_t * sb)
References MAX_STRING_CHARS, MSG_ReadByte(), and string().
Referenced by CL_ConnectionlessPacket(), CL_ServerStatusResponse(), and SV_ConnectionlessPacket().
void MSG_ReportChangeVectors_f (void)
References Com_Printf(), and pcount.
Referenced by Com_Init().
void MSG_WriteAngle16 (msg_t * sb, float f)
References ANGLE2SHORT, and MSG_WriteShort().
void MSG_WriteBigString (msg_t * sb, const char * s)
References BIG_INFO_STRING, Com_Printf(), MSG_WriteData(), and Q_strncpyz().
Referenced by CL_Record_f(), and SV_SendClientGameState().
void MSG_WriteBits (msg_t * msg, int value, int bits)
References msg_t::bit, bits(), Com_Error(), huffman_t::compressor, msg_t::cursize, msg_t::data, ERR_DROP, Huff_offsetTransmit(), Huff_putBit(), msg_t::maxsize, oldsize, msg_t::oob, msg_t::overflowed, overflows, qtrue, and value().
Referenced by MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDelta(), MSG_WriteDeltaEntity(), MSG_WriteDeltaFloat(), MSG_WriteDeltaKey(), MSG_WriteDeltaKeyFloat(), MSG_WriteDeltaPlayerstate(), MSG_WriteDeltaUsercmd(), MSG_WriteDeltaUsercmdKey(), MSG_WriteFloat(), MSG_WriteLong(), MSG_WriteShort(), and SV_EmitPacketEntities().
void MSG_WriteByte (msg_t * sb, int c)
References Com_Error(), ERR_FATAL, and MSG_WriteBits().
Referenced by CL_Netchan_Transmit(), CL_Record_f(), CL_WritePacket(), MSG_WriteAngle(), MSG_WriteData(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), SV_Netchan_Transmit(), SV_SendClientGameState(), SV_SendDownloadMessages(), SV_UpdateServerCommandsToClient(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
void MSG_WriteChar (msg_t * sb, int c)
References Com_Error(), ERR_FATAL, and MSG_WriteBits().
void MSG_WriteData (msg_t * buf, const void * data, int length)
References length(), and MSG_WriteByte().
Referenced by CL_WritePacket(), MSG_WriteBigString(), MSG_WriteString(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
void MSG_WriteDeltaEntity (msg_t * msg, struct entityState_s * from, struct entityState_s * to, qboolean force)
References ARRAY_LEN, netField_t::bits, Com_Error(), ERR_FATAL, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, GENTITYNUM_BITS, int(), MAX_GENTITIES, MSG_WriteBits(), MSG_WriteByte(), NULL, entityState_s::number, netField_t::offset, and oldsize.
Referenced by CL_Record_f(), SV_EmitPacketEntities(), and SV_SendClientGameState().
void MSG_WriteDeltaPlayerstate (msg_t * msg, struct playerState_s * from, struct playerState_s * to)
References playerState_s::ammo, ARRAY_LEN, netField_t::bits, Com_Memset, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, int(), MAX_PERSISTANT, MAX_POWERUPS, MAX_STATS, MAX_WEAPONS, MSG_WriteBits(), MSG_WriteByte(), MSG_WriteLong(), MSG_WriteShort(), netField_t::offset, oldsize, playerState_s::persistant, playerState_s::powerups, and playerState_s::stats.
Referenced by SV_WriteSnapshotToClient().
void MSG_WriteDeltaUsercmd (msg_t * msg, struct usercmd_s * from, struct usercmd_s * to)
References usercmd_s::angles, usercmd_s::buttons, usercmd_s::forwardmove, MSG_WriteBits(), MSG_WriteDelta(), usercmd_s::rightmove, usercmd_s::serverTime, usercmd_s::upmove, and usercmd_s::weapon.
void MSG_WriteDeltaUsercmdKey (msg_t * msg, int key, usercmd_t * from, usercmd_t * to)
References usercmd_s::angles, usercmd_s::buttons, usercmd_s::forwardmove, MSG_WriteBits(), MSG_WriteDeltaKey(), oldsize, usercmd_s::rightmove, usercmd_s::serverTime, usercmd_s::upmove, and usercmd_s::weapon.
Referenced by CL_WritePacket().
void MSG_WriteFloat (msg_t * sb, float f)
References floatint_t::f, floatint_t::i, and MSG_WriteBits().
void MSG_WriteLong (msg_t * sb, int c)
References MSG_WriteBits().
Referenced by CL_Record_f(), CL_WritePacket(), MSG_WriteDeltaPlayerstate(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_SendClientGameState(), SV_SendClientSnapshot(), SV_SendDownloadMessages(), SV_UpdateServerCommandsToClient(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
void MSG_WriteShort (msg_t * sb, int c)
References Com_Error(), ERR_FATAL, and MSG_WriteBits().
Referenced by CL_Record_f(), CL_WritePacket(), MSG_WriteAngle16(), MSG_WriteDeltaPlayerstate(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_SendClientGameState(), and SV_WriteDownloadToClient().
void MSG_WriteString (msg_t * sb, const char * s)
References Com_Printf(), MAX_STRING_CHARS, MSG_WriteData(), and Q_strncpyz().
Referenced by CL_WritePacket(), SV_UpdateServerCommandsToClient(), and SV_WriteDownloadToClient().
const char* NET_AdrToString (netadr_t a)
References Com_sprintf(), NA_BOT, NA_IP, NA_IP6, NA_LOOPBACK, NET_ADDRSTRMAXLEN, NetadrToSockadr(), s, Sys_SockaddrToString(), and netadr_t::type.
Referenced by CL_ServerInfoPacket(), NET_AdrToStringwPort(), NET_GetPacket(), Netchan_Process(), SV_AddBanToList(), SV_ConnectionlessPacket(), SV_DelBanFromList(), SV_DirectConnect(), SV_GetChallenge(), SV_ListBans_f(), SV_Status_f(), SV_UserinfoChanged(), SV_WriteBans(), SVC_RemoteCommand(), and SVC_Status().
const char* NET_AdrToStringwPort (netadr_t a)
References Com_sprintf(), NA_BOT, NA_IP, NA_IP6, NA_LOOPBACK, NET_ADDRSTRMAXLEN, NET_AdrToString(), netadr_t::port, s, and netadr_t::type.
Referenced by CL_Connect_f(), CL_ConnectionlessPacket(), CL_GetPing(), CL_PacketEvent(), CL_ServerInfoPacket(), LAN_GetServerAddressString(), LAN_GetServerInfo(), and SV_MasterHeartbeat().
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
References NA_IP, NA_IP6, NET_CompareBaseAdr(), netadr_t::port, qfalse, qtrue, and netadr_t::type.
Referenced by CL_ConnectionlessPacket(), CL_DisconnectPacket(), CL_GetServerStatus(), CL_MotdPacket(), CL_PacketEvent(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus(), CL_ServerStatusResponse(), CL_SetServerInfoByAddress(), CL_UpdateVisiblePings_f(), LAN_AddServer(), LAN_RemoveServer(), SV_DirectConnect(), SV_DropClient(), and SV_GetChallenge().
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
References NET_CompareBaseAdrMask().
Referenced by NET_CompareAdr(), SV_AuthorizeIpPacket(), SV_DirectConnect(), and SV_PacketEvent().
qboolean NET_CompareBaseAdrMask (netadr_t a, netadr_t b, int netmask)
References Com_Printf(), netadr_t::ip, netadr_t::ip6, NA_IP, NA_IP6, NA_LOOPBACK, qfalse, qtrue, and netadr_t::type.
Referenced by NET_CompareBaseAdr(), SV_AddBanToList(), SV_DelBanFromList(), and SV_IsBanned().
void NET_Config (qboolean enableNetworking)
References closesocket, cvar_s::integer, INVALID_SOCKET, ip6_socket, ip_socket, multicast6_socket, NET_GetCvars(), NET_OpenIP(), NET_SetMulticast6(), networkingEnabled, qfalse, qtrue, socks_socket, and start.
Referenced by NET_Init(), NET_Restart_f(), and NET_Shutdown().
void NET_FlushPacketQueue (void)
References packetQueue_s::data, packetQueue_s::length, packetQueue_s::next, packetQueue, packetQueue_s::release, Sys_Milliseconds(), Sys_SendPacket(), packetQueue_s::to, and Z_Free().
Referenced by Com_Frame().
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t * net_from, msg_t * net_message)
References Com_Memcpy, Com_Memset, msg_t::cursize, msg_t::data, loopmsg_t::data, loopmsg_t::datalen, loopback_t::get, MAX_LOOPBACK, loopback_t::msgs, NA_LOOPBACK, qfalse, qtrue, loopback_t::send, and netadr_t::type.
Referenced by Com_EventLoop().
void NET_Init (void)
References Cmd_AddCommand(), Com_Printf(), NET_Config(), NET_Restart_f(), and qtrue.
Referenced by main().
qboolean NET_IsLocalAddress (netadr_t adr)
References NA_LOOPBACK, and netadr_t::type.
Referenced by CL_Connect_f(), CL_Record_f(), SV_DirectConnect(), and SV_UserinfoChanged().
void NET_JoinMulticast6 (void)
References boundto, closesocket, Com_Printf(), curgroup, cvar_s::integer, INVALID_SOCKET, ip6_socket, multicast6_socket, NET_DISABLEMCAST, NET_ErrorString(), NET_IP6Socket(), NULL, and cvar_s::string.
Referenced by SV_Startup().
void NET_LeaveMulticast6 (void)
References closesocket, curgroup, INVALID_SOCKET, ip6_socket, and multicast6_socket.
Referenced by SV_Shutdown().
void QDECL void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, byte * format, int len)
References msg_t::cursize, msg_t::data, Huff_Compress(), MAX_MSGLEN, NET_SendPacket(), and string().
Referenced by CL_CheckForResend().
void QDECL NET_OutOfBandPrint (netsrc_t net_socket, netadr_t adr, const char * format, ...)
void NET_Restart_f (void)
References NET_Config(), and qtrue.
Referenced by Com_GameRestart(), and NET_Init().
void NET_SendPacket (netsrc_t sock, int length, const void * data, netadr_t to)
References cl_packetdelay, Com_Printf(), cvar_s::integer, NA_BAD, NA_BOT, NA_LOOPBACK, NET_QueuePacket(), NET_SendLoopPacket(), NS_CLIENT, NS_SERVER, sv_packetdelay, Sys_SendPacket(), and netadr_t::type.
Referenced by CL_LocalServers_f(), CL_Rcon_f(), NET_OutOfBandData(), NET_OutOfBandPrint(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
void NET_Shutdown (void)
References NET_Config(), networkingEnabled, and qfalse.
void NET_Sleep (int msec)
References Com_Printf(), INVALID_SOCKET, ip6_socket, ip_socket, NET_ErrorString(), NET_Event(), and NULL.
Referenced by Com_Frame().
int NET_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
References Com_Memset, MAX_STRING_CHARS, NA_BAD, NA_LOOPBACK, NULL, netadr_t::port, PORT_SERVER, Q_CountChar(), Q_strncpyz(), Sys_StringToAdr(), and netadr_t::type.
void Netchan_Init (int qport)
References Cvar_Get(), CVAR_INIT, CVAR_TEMP, and va().
Referenced by Com_Init().
qboolean Netchan_Process (netchan_t * chan, msg_t * msg)
References msg_t::bit, netchan_t::challenge, Com_Memcpy, Com_Printf(), msg_t::cursize, msg_t::data, netchan_t::dropped, FRAGMENT_BIT, FRAGMENT_SIZE, netchan_t::fragmentBuffer, netchan_t::fragmentLength, netchan_t::fragmentSequence, netchan_t::incomingSequence, cvar_s::integer, msg_t::maxsize, MSG_BeginReadingOOB(), MSG_ReadLong(), MSG_ReadShort(), NET_AdrToString(), NETCHAN_GENCHECKSUM, netsrcString, NS_SERVER, qfalse, qtrue, msg_t::readcount, netchan_t::remoteAddress, and netchan_t::sock.
Referenced by CL_Netchan_Process(), and SV_Netchan_Process().
void Netchan_Setup (netsrc_t sock, netchan_t * chan, netadr_t adr, int qport, int challenge, qboolean compat)
References netchan_t::challenge, Com_Memset, netchan_t::incomingSequence, netchan_t::outgoingSequence, qport, netchan_t::qport, netchan_t::remoteAddress, and netchan_t::sock.
Referenced by CL_ConnectionlessPacket(), and SV_DirectConnect().
void Netchan_Transmit (netchan_t * chan, int length, const byte * data)
References netchan_t::challenge, Com_Error(), Com_Memcpy, Com_Printf(), msg_t::cursize, msg_t::data, ERR_DROP, FRAGMENT_SIZE, netchan_t::incomingSequence, cvar_s::integer, netchan_t::lastSentSize, netchan_t::lastSentTime, length(), MAX_MSGLEN, MAX_PACKETLEN, MSG_InitOOB(), MSG_WriteData(), MSG_WriteLong(), MSG_WriteShort(), NET_SendPacket(), NETCHAN_GENCHECKSUM, Netchan_TransmitNextFragment(), netsrcString, NS_CLIENT, netchan_t::outgoingSequence, qtrue, netchan_t::remoteAddress, send(), netchan_t::sock, Sys_Milliseconds(), netchan_t::unsentBuffer, netchan_t::unsentFragments, netchan_t::unsentFragmentStart, and netchan_t::unsentLength.
Referenced by CL_Netchan_Transmit(), SV_Netchan_Transmit(), and SV_Netchan_TransmitNextInQueue().
void Netchan_TransmitNextFragment (netchan_t * chan)
References netchan_t::challenge, Com_Printf(), msg_t::cursize, msg_t::data, FRAGMENT_BIT, FRAGMENT_SIZE, cvar_s::integer, netchan_t::lastSentSize, netchan_t::lastSentTime, MAX_PACKETLEN, MSG_InitOOB(), MSG_WriteData(), MSG_WriteLong(), MSG_WriteShort(), NET_SendPacket(), NETCHAN_GENCHECKSUM, netsrcString, NS_CLIENT, netchan_t::outgoingSequence, qfalse, netchan_t::remoteAddress, send(), netchan_t::sock, Sys_Milliseconds(), netchan_t::unsentBuffer, netchan_t::unsentFragments, netchan_t::unsentFragmentStart, and netchan_t::unsentLength.
Referenced by CL_Netchan_TransmitNextFragment(), Netchan_Transmit(), and SV_Netchan_TransmitNextFragment().
void S_ClearSoundBuffer (void)
References soundInterface_t::ClearSoundBuffer.
Referenced by CL_Disconnect(), FS_FCreateOpenPipeFile(), FS_FOpenFileAppend(), FS_Rename(), FS_SV_FOpenFileRead(), and FS_SV_Rename().
void* S_MallocDebug (int size, char * label, char * file, int line)
References TAG_SMALL, and Z_TagMallocDebug().
void SCR_DebugGraph (float value)
References ARRAY_LEN, current, and value().
Referenced by CL_CreateCmd(), and CL_Frame().
void SV_Frame (int msec)
References Cbuf_AddText(), com_dedicated, com_speeds, com_sv_running, com_timescale, CS_SERVERINFO, CS_SYSTEMINFO, Cvar_InfoString(), Cvar_InfoString_Big(), cvar_modifiedFlags, CVAR_SERVERINFO, Cvar_Set(), CVAR_SYSTEMINFO, Cvar_VariableString(), GAME_RUN_FRAME, HEARTBEAT_FOR_MASTER, cvar_s::integer, serverStatic_t::nextSnapshotEntities, serverStatic_t::numSnapshotEntities, server_t::restartTime, startTime, SV_BotFrame(), SV_CalcPings(), SV_CheckPaused(), SV_CheckTimeouts(), SV_MasterHeartbeat(), SV_SendClientMessages(), SV_SetConfigstring(), SV_Shutdown(), Sys_Milliseconds(), Sys_Sleep(), server_t::time, serverStatic_t::time, time_game, server_t::timeResidual, va(), cvar_s::value, and VM_Call().
Referenced by CL_Connect_f(), and Com_Frame().
int SV_FrameMsec (void)
References server_t::timeResidual, and cvar_s::value.
Referenced by Com_Frame().
qboolean SV_GameCommand (void)
References GAME_CONSOLE_COMMAND, gvm, qfalse, SS_GAME, server_t::state, sv, and VM_Call().
Referenced by Cmd_ExecuteString().
void SV_Init (void)
References Cbuf_AddText(), CVAR_ARCHIVE, Cvar_CheckRange(), Cvar_Get(), CVAR_LATCH, CVAR_ROM, CVAR_SERVERINFO, CVAR_SYSTEMINFO, CVAR_TEMP, MAX_MASTER_SERVERS, qtrue, SV_AddOperatorCommands(), sv_allowDownload, sv_banFile, SV_BotInitBotLib(), SV_BotInitCvars(), sv_dlRate, sv_floodProtect, sv_fps, sv_gametype, sv_hostname, sv_killserver, sv_lanForceRate, sv_mapChecksum, sv_mapname, sv_master, sv_maxclients, sv_maxPing, sv_maxRate, sv_minPing, sv_minRate, sv_padPackets, sv_privateClients, sv_privatePassword, sv_pure, sv_rconPassword, sv_reconnectlimit, sv_serverid, sv_showloss, sv_strictAuth, sv_timeout, sv_zombietime, and va().
Referenced by Com_Init().
void SV_PacketEvent (netadr_t from, msg_t * msg)
References cl, serverStatic_t::clients, Com_Printf(), CS_FREE, CS_ZOMBIE, msg_t::cursize, msg_t::data, client_s::lastPacketTime, MSG_BeginReadingOOB(), MSG_ReadLong(), MSG_ReadShort(), NET_CompareBaseAdr(), client_s::netchan, netadr_t::port, qport, netchan_t::qport, netchan_t::remoteAddress, client_s::state, SV_ConnectionlessPacket(), SV_ExecuteClientMessage(), SV_Netchan_Process(), and serverStatic_t::time.
Referenced by Com_RunAndTimeServerPacket().
int SV_SendQueuedPackets (void)
References INT_MAX, cvar_s::integer, MAX_DOWNLOAD_BLKSIZE, SV_SendDownloadMessages(), SV_SendQueuedMessages(), and Sys_Milliseconds().
Referenced by Com_Frame().
void SV_Shutdown (char * finalmsg)
References CL_Disconnect(), serverStatic_t::clients, com_errorEntered, Com_Memset, Com_Printf(), com_sv_running, Cvar_Set(), cvar_s::integer, NET_LeaveMulticast6(), qfalse, SV_ClearServer(), SV_FinalMessage(), SV_FreeClient(), sv_killserver, SV_MasterShutdown(), sv_maxclients, SV_RemoveOperatorCommands(), SV_ShutdownGameProgs(), svs, and Z_Free().
Referenced by CL_Connect_f(), Com_Error(), Com_Frame(), Com_GameRestart(), Com_Quit_f(), SV_Frame(), SV_KillServer_f(), and Sys_SigHandler().
const char* Sys_Basename (char * path)
References basename(), length(), MAX_OSPATH, and Q_strncpyz().
Referenced by Sys_StripAppBundle().
char* Sys_ConsoleInput (void)
References CON_Input().
Referenced by Com_GetSystemEvent().
char* Sys_Cwd (void)
References MAX_OSPATH, and NULL.
Referenced by Sys_DefaultInstallPath().
char* Sys_DefaultHomePath (void)
References com_homepath, Com_Printf(), Com_sprintf(), homePath, HOMEPATH_NAME_MACOSX, HOMEPATH_NAME_UNIX, HOMEPATH_NAME_WIN, MAX_PATH, NULL, Q_strcat(), and cvar_s::string.
Referenced by FS_Startup(), and Sys_TempPath().
char* Sys_DefaultInstallPath (void)
References installPath, and Sys_Cwd().
Referenced by FS_Startup().
dialogResult_t Sys_Dialog (dialogType_t type, const char * message, const char * title)
References Com_DPrintf(), commands, DR_CANCEL, DR_NO, DR_OK, DR_YES, DT_ERROR, DT_INFO, DT_OK_CANCEL, DT_WARNING, DT_YES_NO, NULL, Q_stricmp(), qfalse, qtrue, S_COLOR_YELLOW, Sys_Exec(), Sys_KdialogCommand(), Sys_XmessageCommand(), Sys_ZenityCommand(), type(), and void().
Referenced by Com_Init(), main(), and Sys_ErrorDialog().
const char* Sys_Dirname (char * path)
References length(), MAX_OSPATH, and Q_strncpyz().
Referenced by main(), and Sys_StripAppBundle().
void Sys_DisplaySystemConsole (qboolean show)
void QDECL Sys_Error (const char * error, ...)
void Sys_FreeFileList (char ** list)
References Z_Free().
Referenced by FS_AddGameDirectory(), FS_GetModList(), and FS_ListFilteredFiles().
void* Sys_GetBotLibAPI (void * parms)
void* Sys_GetCGameAPI (void)
char* Sys_GetClipboardData (void)
References data, NULL, Q_strncpyz(), and Z_Malloc.
Referenced by CL_GetClipboardData(), and Field_Paste().
char* Sys_GetCurrentUser (void)
References NULL.
Referenced by Sys_Init().
void* Sys_GetGameAPI (void * parms)
References NULL.
cpuFeatures_t Sys_GetProcessorFeatures (void)
References CF_3DNOW, CF_3DNOW_EXT, CF_ALTIVEC, CF_MMX, CF_MMX_EXT, CF_RDTSC, CF_SSE, CF_SSE2, SDL_Has3DNow(), SDL_Has3DNowExt(), SDL_HasAltiVec(), SDL_HasMMX(), SDL_HasMMXExt(), SDL_HasRDTSC(), SDL_HasSSE(), and SDL_HasSSE2().
Referenced by Com_DetectAltivec().
void* Sys_GetUIAPI (void)
void Sys_Init (void)
References Cmd_AddCommand(), Cvar_Set(), Sys_GetCurrentUser(), and Sys_In_Restart_f().
Referenced by Com_Init().
qboolean Sys_IsLANAddress (netadr_t adr)
References nip_localaddr_t::addr, netadr_t::ip, netadr_t::ip6, NA_IP, NA_IP6, NA_LOOPBACK, nip_localaddr_t::netmask, numIP, qfalse, qtrue, and netadr_t::type.
Referenced by CL_CheckForResend(), CL_ReadyToSendPacket(), SV_DirectConnect(), SV_GetChallenge(), SV_SendClientMessages(), and SV_UserinfoChanged().
char** Sys_ListFiles (const char * directory, const char * extension, char * filter, int * numfiles, qboolean wantsubs)
References Com_sprintf(), CopyString(), intptr_t(), MAX_FOUND_FILES, MAX_OSPATH, NULL, Q_stricmp(), qtrue, strgtr(), Sys_ListFilteredFiles(), and Z_Malloc.
Referenced by FS_AddGameDirectory(), FS_GetModList(), and FS_ListFilteredFiles().
void* QDECL Sys_LoadGameDll (const char * name, intptr_t(QDECL **entryPoint)(int,...) , intptr_t(QDECL *systemcalls)(intptr_t,...))
Referenced by VM_Create().
qboolean Sys_LowPhysicalMemory (void)
References MEM_THRESHOLD, qfalse, and qtrue.
Referenced by CL_InitCGame(), and CL_InitRef().
int Sys_Milliseconds (void)
References curtime, NULL, qfalse, qtrue, sys_curtime, and sys_timeBase.
Referenced by CL_CgameSystemCalls(), CL_DemoCompleted(), CL_GetFreePing(), CL_GetPing(), CL_InitCGame(), CL_Ping_f(), CL_ScaledMilliseconds(), CL_ServerInfoPacket(), CL_SetCGameTime(), CL_UISystemCalls(), CL_UpdateVisiblePings_f(), Com_Error(), Com_Frame(), Com_GetSystemEvent(), Com_QueueEvent(), Com_RunAndTimeServerPacket(), Com_TimeVal(), Com_TouchMemory(), IN_Frame(), IN_ProcessEvents(), main(), NET_FlushPacketQueue(), NET_QueuePacket(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_Frame(), SV_GameSystemCalls(), SV_RateMsec(), SV_SendQueuedPackets(), SVC_BucketForAddress(), and SVC_RateLimit().
qboolean Sys_Mkdir (const char * path)
References NULL, qfalse, and qtrue.
FILE* Sys_Mkfifo (const char * ospath)
References FS_Remove(), and NULL.
Referenced by FS_FCreateOpenPipeFile().
void Sys_Print (const char * msg)
References CON_LogWrite(), and CON_Print().
Referenced by Com_Printf(), and Sys_ErrorDialog().
void Sys_Quit (void)
Referenced by Com_Quit_f().
qboolean Sys_RandomBytes (byte * string, int len)
References fclose(), fp, fread(), NULL, qfalse, and qtrue.
Referenced by Com_InitRand(), and Com_RandomBytes().
void Sys_SendPacket (int length, const void * data, netadr_t to)
References Com_Error(), Com_Printf(), ERR_FATAL, cvar_s::integer, INVALID_SOCKET, ip6_socket, ip_socket, NA_BROADCAST, NA_IP, NA_IP6, NA_MULTICAST6, NET_DISABLEMCAST, NET_ErrorString(), NetadrToSockadr(), SOCKET_ERROR, socketError, socksBuf, socksRelayAddr, netadr_t::type, and usingSocks.
void Sys_SetDefaultHomePath (const char * path)
void Sys_SetDefaultInstallPath (const char * path)
References installPath, and Q_strncpyz().
Referenced by main().
void Sys_SetEnv (const char * name, const char * value)
References va().
Referenced by CL_InitRef(), and Com_Setenv_f().
void Sys_SetErrorText (const char * text)
void Sys_ShowIP (void)
References Com_Printf(), NA_IP, NA_IP6, NET_ADDRSTRMAXLEN, numIP, and Sys_SockaddrToString().
Referenced by CL_ShowIP_f(), and NET_GetLocalAddress().
void Sys_Sleep (int msec)
References INFINITE, NULL, and stdinIsATTY.
Referenced by SV_Frame().
void Sys_SnapVector (float * v)
qboolean Sys_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
References NA_IP, NA_IP6, qfalse, qtrue, SockadrToNetadr(), and Sys_StringToSockaddr().
Referenced by NET_StringToAdr().
const char* Sys_TempPath (void)
References length(), MAX_PATH, NULL, and Sys_DefaultHomePath().
Referenced by Sys_PIDFileName().
void Sys_UnloadBotLib (void)
void Sys_UnloadCGame (void)
void Sys_UnloadDll (void * dllHandle)
References Com_Printf(), and Sys_UnloadLibrary.
Referenced by VM_Free().
void Sys_UnloadGame (void)
void Sys_UnloadUI (void)
qboolean Sys_WritePIDFile (void)
References Com_Printf(), fclose(), fread(), NULL, qfalse, qtrue, S_COLOR_YELLOW, Sys_PID(), Sys_PIDFileName(), and Sys_PIDIsRunning().
Referenced by Com_Init().
qboolean UI_GameCommand (void)
References cls, qfalse, clientStatic_t::realtime, UI_CONSOLE_COMMAND, and VM_Call().
Referenced by Cmd_ExecuteString().
qboolean UI_usesUniqueCDKey (void)
References qfalse, qtrue, UI_HASUNIQUECDKEY, and VM_Call().
Referenced by CLUI_GetCDKey(), CLUI_SetCDKey(), and Com_WriteConfiguration().
void* VM_ArgPtr (intptr_t intValue)
References vm_s::dataBase, vm_s::dataMask, and NULL.
intptr_t QDECL VM_Call (vm_t * vm, int callNum, ...)
References args, ARRAY_LEN, vm_s::callLevel, Com_Error(), Com_Printf(), vm_s::compiled, currentVM, ERR_FATAL, intptr_t(), vm_s::name, NULL, VM_CallCompiled(), VM_CallInterpreted(), and vm_debugLevel.
Referenced by CIN_PlayCinematic(), CL_CGameRendering(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_GameCommand(), CL_InitCGame(), CL_InitUI(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ShutdownCGame(), CL_ShutdownUI(), Con_MessageMode3_f(), Con_MessageMode4_f(), SCR_DrawScreenField(), SV_BotFrame(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_Frame(), SV_GameCommand(), SV_InitGameVM(), SV_MapRestart_f(), SV_RestartGameProgs(), SV_ShutdownGameProgs(), SV_SpawnServer(), SV_UpdateUserinfo_f(), UI_GameCommand(), and UI_usesUniqueCDKey().
void VM_Clear (void)
References MAX_VM, and VM_Free().
Referenced by Hunk_Clear().
vm_t* VM_Create (const char * module, intptr_t(*)(intptr_t *) systemCalls, vmInterpret_t interpret)
References vmHeader_t::codeLength, vm_s::codeLength, Com_Error(), Com_Printf(), vm_s::compiled, vm_s::dataMask, vm_s::dllHandle, ERR_FATAL, FS_FindVM(), FS_FreeFile(), h_high, Hunk_Alloc, Hunk_MemoryRemaining(), vmHeader_t::instructionCount, vm_s::instructionCount, vm_s::instructionPointers, MAX_OSPATH, MAX_VM, vm_s::name, NULL, PROGRAM_STACK_SIZE, vm_s::programStack, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, vm_s::searchPath, vm_s::stackBottom, Sys_LoadGameDll(), vm_s::systemCall, VM_Compile(), VM_DllSyscall(), VM_LoadQVM(), VM_LoadSymbols(), VM_PrepareInterpreter(), VMI_BYTECODE, VMI_COMPILED, and VMI_NATIVE.
Referenced by CL_InitCGame(), CL_InitUI(), SV_InitGameProgs(), and VM_Restart().
void VM_Debug (int level)
References level, and vm_debugLevel.
Referenced by CL_CGameRendering(), and VM_CallInterpreted().
void* VM_ExplicitArgPtr (vm_t * vm, intptr_t intValue)
References vm_s::dataBase, vm_s::dataMask, and NULL.
Referenced by SV_DirectConnect(), SV_MapRestart_f(), and SV_SpawnServer().
void VM_Forced_Unload_Done (void)
References forced_unload.
Referenced by Com_Error(), Com_Quit_f(), and Sys_SigHandler().
void VM_Forced_Unload_Start (void)
References forced_unload.
Referenced by Com_Error(), Com_Quit_f(), and Sys_SigHandler().
void VM_Free (vm_t * vm)
References vm_s::callLevel, vm_s::codeBase, Com_Error(), Com_Memset, Com_Printf(), vm_s::dataBase, vm_s::destroy, vm_s::dllHandle, ERR_FATAL, forced_unload, vm_s::instructionPointers, vm_s::name, NULL, Sys_UnloadDll(), and Z_Free().
Referenced by CL_InitUI(), CL_ShutdownCGame(), CL_ShutdownUI(), SV_ShutdownGameProgs(), VM_Clear(), VM_LoadQVM(), and VM_Restart().
void VM_Init (void)
References Cmd_AddCommand(), Com_Memset, CVAR_ARCHIVE, Cvar_Get(), VM_VmInfo_f(), and VM_VmProfile_f().
Referenced by Com_Init().
vm_t* VM_Restart (vm_t * vm, qboolean unpure)
References Com_Error(), Com_Printf(), vm_s::dllHandle, ERR_DROP, FS_FreeFile(), intptr_t(), MAX_QPATH, vm_s::name, NULL, Q_strncpyz(), qfalse, vm_s::systemCall, VM_Create(), VM_Free(), VM_LoadQVM(), and VMI_NATIVE.
Referenced by SV_RestartGameProgs().
int Z_AvailableMemory (void)
References Z_AvailableZoneMemory().
Referenced by SV_BotInitBotLib().
void Z_Free (void * ptr)
References Com_Error(), Com_Memset, ERR_DROP, ERR_FATAL, memblock_s::id, mainzone, memblock_s::next, memblock_s::prev, memzone_t::rover, memblock_s::size, smallzone, memblock_s::tag, TAG_SMALL, TAG_STATIC, memzone_t::used, and ZONEID.
Referenced by BotImport_FreeMemory(), CL_CloseAVI(), CL_GetClipboardData(), CL_InitRef(), Cmd_RemoveCommand(), Com_EventLoop(), Com_PushEvent(), Com_QueueEvent(), Cvar_Get(), Cvar_Set2(), Cvar_SetCheatState(), Cvar_Unset(), Field_Paste(), free_source_insns(), FreeWinding(), FS_FreeFileList(), FS_FreePak(), FS_LoadZipFile(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_Shutdown(), FS_SortFileList(), Hunk_FreeTempMemory(), Key_SetBinding(), labelhash_free(), NET_FlushPacketQueue(), S_CodecUtilClose(), sparc_compute_code(), SV_BotInitBotLib(), SV_ChangeMaxClients(), SV_ClearServer(), SV_CloseDownload(), SV_FreeClient(), SV_Netchan_FreeQueue(), SV_Netchan_TransmitNextInQueue(), SV_RankCloseContext(), SV_RehashBans_f(), SV_SetConfigstring(), SV_Shutdown(), Sys_ConcatenateFileLists(), Sys_FreeFileList(), VM_Compile(), VM_Free(), VM_VmProfile_f(), and Z_FreeTags().
void Z_FreeTags (int tag)
References memzone_t::blocklist, count, mainzone, memblock_s::next, memzone_t::rover, smallzone, memblock_s::tag, TAG_SMALL, and Z_Free().
void Z_LogHeap (void)
References Z_LogZoneHeap().
Referenced by Com_InitHunkMemory(), and Z_TagMallocDebug().
void* Z_MallocDebug (int size, char * label, char * file, int line)
References Com_Memset, TAG_GENERAL, Z_Malloc, Z_TagMalloc, and Z_TagMallocDebug().
void* Z_TagMallocDebug (int size, int tag, char * label, char * file, int line)
References zonedebug_s::allocSize, Com_Error(), memblock_s::d, ERR_FATAL, file, zonedebug_s::file, memblock_s::id, intptr_t(), zonedebug_s::label, line, zonedebug_s::line, mainzone, MINFRAGMENT, memblock_s::next, NULL, PAD, memblock_s::prev, memzone_t::rover, memblock_s::size, smallzone, start, memblock_s::tag, TAG_SMALL, memzone_t::used, Z_LogHeap(), Z_TagMalloc, and ZONEID.
Referenced by S_MallocDebug(), and Z_MallocDebug().
Variable Documentation
char cl_cdkey[34]
Referenced by CL_RequestAuthorization(), CLUI_GetCDKey(), and CLUI_SetCDKey().
cvar_t* cl_packetdelay
Referenced by NET_SendPacket().
cvar_t* cl_paused
Referenced by CL_CheckPaused(), CL_ParseSnapshot(), CL_SendCmd(), and SV_CheckPaused().
huffman_t clientHuffTables
cvar_t* com_altivec
Referenced by LerpMeshVertexes(), ProjectDlightTexture(), RB_CalcDiffuseColor(), and S_PaintChannelFrom16().
cvar_t* com_ansiColor
Referenced by CON_Print().
cvar_t* com_basegame
Referenced by FS_CheckPak0(), FS_ConditionalRestart(), FS_GetCurrentGameDir(), FS_GetModList(), FS_InitFilesystem(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), and FS_Restart().
cvar_t* com_blood
cvar_t* com_buildScript
cvar_t* com_cameraMode
cvar_t* com_cl_running
Referenced by CL_Disconnect(), CL_Frame(), CL_MapLoading(), CL_Shutdown(), CL_StartHunkUsers(), Cmd_ExecuteString(), Con_Close(), and SV_ClientCommand().
cvar_t* com_dedicated
Referenced by CL_MapLoading(), CL_StartHunkUsers(), SCR_UpdateScreen(), SV_AddOperatorCommands(), SV_ChangeMaxClients(), SV_Frame(), SV_MasterHeartbeat(), SV_SendServerCommand(), SV_SpawnServer(), SV_Startup(), and SV_UserinfoChanged().
cvar_t* com_developer
Referenced by SV_RankBegin(), and VM_LoadSymbols().
qboolean com_errorEntered
Referenced by CL_AddReliableCommand(), Com_Error(), Com_Quit_f(), Cvar_Get(), and SV_Shutdown().
int com_frameTime
Referenced by CL_CreateNewCommands(), CL_KeyState(), Com_Frame(), Com_Init(), Com_TimeVal(), SV_MapRestart_f(), and SV_SpawnServer().
qboolean com_fullyInitialized
Referenced by CL_Init(), Com_GameRestart(), Com_Init(), Com_WriteConfiguration(), and FS_FOpenFileReadDir().
cvar_t* com_gamename
Referenced by CL_CheckForResend(), CL_GlobalServers_f(), CL_ServerInfoPacket(), SV_GetChallenge(), and SVC_Info().
cvar_t* com_homepath
Referenced by Sys_DefaultHomePath().
cvar_t* com_journal
Referenced by FS_ReadFileDir().
fileHandle_t com_journalDataFile
Referenced by Com_InitJournaling(), and FS_ReadFileDir().
fileHandle_t com_journalFile
Referenced by Com_GetRealEvent(), Com_InitJournaling(), and Com_Shutdown().
cvar_t* com_maxfpsMinimized
cvar_t* com_maxfpsUnfocused
cvar_t* com_minimized
Referenced by S_Update().
cvar_t* com_protocol
Referenced by CL_CheckForResend(), CL_CompleteDemoName(), CL_ConnectionlessPacket(), CL_PlayDemo_f(), CL_Record_f(), CL_ServerInfoPacket(), CL_WalkDemoExt(), FS_IsDemoExt(), SV_AuthorizeIpPacket(), SV_DirectConnect(), SV_GetChallenge(), and SVC_Info().
cvar_t* com_speeds
Referenced by SCR_UpdateScreen(), and SV_Frame().
cvar_t* com_standalone
Referenced by CL_CheckForResend(), FS_CheckPak0(), FS_Startup(), SV_AddOperatorCommands(), and SV_GetChallenge().
cvar_t* com_sv_running
Referenced by CL_ClearMemory(), CL_Connect_f(), CL_Frame(), CL_GetServerCommand(), CL_SendCmd(), CL_SetCGameTime(), CL_Vid_Restart_f(), Cmd_ExecuteString(), NET_Event(), SV_AddBanToList(), SV_Ban_f(), SV_BanNum_f(), SV_ConSay_f(), SV_DumpUser_f(), SV_Frame(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickNum_f(), SV_MapRestart_f(), SV_Shutdown(), and SV_Status_f().
cvar_t* com_timescale
Referenced by CIN_RunCinematic(), CL_AdjustTimeDelta(), CL_Frame(), CL_ScaledMilliseconds(), NET_QueuePacket(), RoQ_init(), RoQInterrupt(), SV_Frame(), SV_RateMsec(), and SV_SendClientMessages().
cvar_t* com_unfocused
Referenced by S_Update().
cvar_t* com_version
Referenced by CL_RequestMotd().
int cvar_modifiedFlags
Referenced by CL_CheckForResend(), CL_CheckUserinfo(), CLUI_SetCDKey(), Com_Init(), Com_WriteConfiguration(), Cvar_Get(), Cvar_Set2(), Cvar_Set_f(), Key_SetBinding(), SV_Frame(), and SV_SpawnServer().
int demo_protocols[]
Referenced by CL_PlayDemo_f(), CL_WalkDemoExt(), and FS_IsDemoExt().
cvar_t* sv_packetdelay
Referenced by NET_SendPacket().
cvar_t* sv_paused
Referenced by CL_CheckTimeout(), CL_SendCmd(), CL_SetCGameTime(), and SV_CheckPaused().
int time_backend
Referenced by Com_Frame(), and SCR_UpdateScreen().
int time_frontend
Referenced by Com_Frame(), and SCR_UpdateScreen().
int time_game
Referenced by Com_Frame(), and SV_Frame().