ioquake3: code/libspeex/quant_lsp.c File Reference
quant_lsp.c File Reference
#include "quant_lsp.h"
#include "os_support.h"
#include <math.h>
#include "arch.h"
Defines
#define M_PI 3.14159265358979323846
#define LSP_LINEAR(i) (.25*(i)+.25)
#define LSP_LINEAR_HIGH(i) (.3125*(i)+.75)
#define LSP_SCALE 256.
#define LSP_DIV_256(x) (0.0039062*(x))
#define LSP_DIV_512(x) (0.0019531*(x))
#define LSP_DIV_1024(x) (0.00097656*(x))
#define LSP_PI M_PI
Functions
static void compute_quant_weights (spx_lsp_t *qlsp, spx_word16_t *quant_weight, int order)
static int lsp_quant (spx_word16_t *x, const signed char *cdbk, int nbVec, int nbDim)
static int lsp_weight_quant (spx_word16_t *x, spx_word16_t *weight, const signed char *cdbk, int nbVec, int nbDim)
void lsp_quant_nb (spx_lsp_t *lsp, spx_lsp_t *qlsp, int order, SpeexBits *bits)
void lsp_unquant_nb (spx_lsp_t *lsp, int order, SpeexBits *bits)
void lsp_quant_lbr (spx_lsp_t *lsp, spx_lsp_t *qlsp, int order, SpeexBits *bits)
void lsp_unquant_lbr (spx_lsp_t *lsp, int order, SpeexBits *bits)
void lsp_quant_high (spx_lsp_t *lsp, spx_lsp_t *qlsp, int order, SpeexBits *bits)
void lsp_unquant_high (spx_lsp_t *lsp, int order, SpeexBits *bits)
Variables
const signed char high_lsp_cdbk []
const signed char high_lsp_cdbk2 []
Define Documentation
#define LSP_DIV_1024 (x) (0.00097656*(x))
Referenced by lsp_unquant_nb().
#define LSP_DIV_256 (x) (0.0039062*(x))
Referenced by lsp_unquant_high(), lsp_unquant_lbr(), and lsp_unquant_nb().
#define LSP_DIV_512 (x) (0.0019531*(x))
Referenced by lsp_unquant_high(), lsp_unquant_lbr(), and lsp_unquant_nb().
#define LSP_LINEAR (i) (.25*(i)+.25)
Referenced by lsp_quant_lbr(), lsp_quant_nb(), lsp_unquant_lbr(), and lsp_unquant_nb().
#define LSP_LINEAR_HIGH (i) (.3125*(i)+.75)
Referenced by lsp_quant_high(), and lsp_unquant_high().
#define LSP_PI M_PI
Referenced by compute_quant_weights().
#define LSP_SCALE 256.
Referenced by lsp_quant_high(), lsp_quant_lbr(), and lsp_quant_nb().
#define M_PI 3.14159265358979323846
Referenced by AAS_Reachability_Grapple(), AngleVectors(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), Bullet_Fire(), CG_AddScorePlum(), CG_CalcFov(), CG_CalcViewValues(), CG_DrawCrosshair3D(), CG_DrawPlayerHead(), CG_DrawStatusBarHead(), CG_OffsetThirdPersonView(), CG_Player(), CG_PlayerFlag(), CG_TeamBase(), InitShooter(), Item_Paint(), lsp_enforce_margin(), ParseShader(), Q_acos(), R_SetupProjection(), RB_CalcBulgeVertexes(), RB_SurfaceSprite(), SP_func_pendulum(), speex_echo_state_init(), spx_cos(), UI_DrawPlayer(), UI_LegsSequencing(), vectoangles(), and vectoyaw().
Function Documentation
static void compute_quant_weights (spx_lsp_t * qlsp, spx_word16_t * quant_weight, int order) [static]
References ADD16, DIV32_16, and LSP_PI.
Referenced by lsp_quant_high(), lsp_quant_lbr(), and lsp_quant_nb().
static int lsp_quant (spx_word16_t * x, const signed char * cdbk, int nbVec, int nbDim) [static]
References MAC16_16, ptr(), SHL16, SUB16, and VERY_LARGE32.
Referenced by lsp_quant_high(), lsp_quant_lbr(), lsp_quant_nb(), nb_encode(), and sb_encode().
void lsp_quant_high (spx_lsp_t * lsp, spx_lsp_t * qlsp, int order, SpeexBits * bits)
References compute_quant_weights(), high_lsp_cdbk, high_lsp_cdbk2, LSP_LINEAR_HIGH, lsp_quant(), LSP_SCALE, lsp_weight_quant(), PSHR16, speex_bits_pack(), and SUB16.
void lsp_quant_lbr (spx_lsp_t * lsp, spx_lsp_t * qlsp, int order, SpeexBits * bits)
References cdbk_nb, cdbk_nb_high1, cdbk_nb_low1, compute_quant_weights(), LSP_LINEAR, lsp_quant(), LSP_SCALE, lsp_weight_quant(), NB_CDBK_SIZE, NB_CDBK_SIZE_HIGH1, NB_CDBK_SIZE_LOW1, PSHR16, speex_bits_pack(), and SUB16.
void lsp_quant_nb (spx_lsp_t * lsp, spx_lsp_t * qlsp, int order, SpeexBits * bits)
References cdbk_nb, cdbk_nb_high1, cdbk_nb_high2, cdbk_nb_low1, cdbk_nb_low2, compute_quant_weights(), LSP_LINEAR, lsp_quant(), LSP_SCALE, lsp_weight_quant(), NB_CDBK_SIZE, NB_CDBK_SIZE_HIGH1, NB_CDBK_SIZE_HIGH2, NB_CDBK_SIZE_LOW1, NB_CDBK_SIZE_LOW2, PSHR16, speex_bits_pack(), and SUB16.
void lsp_unquant_high (spx_lsp_t * lsp, int order, SpeexBits * bits)
References high_lsp_cdbk, high_lsp_cdbk2, LSP_DIV_256, LSP_DIV_512, LSP_LINEAR_HIGH, and speex_bits_unpack_unsigned().
void lsp_unquant_lbr (spx_lsp_t * lsp, int order, SpeexBits * bits)
References cdbk_nb, cdbk_nb_high1, cdbk_nb_low1, LSP_DIV_256, LSP_DIV_512, LSP_LINEAR, and speex_bits_unpack_unsigned().
void lsp_unquant_nb (spx_lsp_t * lsp, int order, SpeexBits * bits)
References ADD16, ADD32, cdbk_nb, cdbk_nb_high1, cdbk_nb_high2, cdbk_nb_low1, cdbk_nb_low2, LSP_DIV_1024, LSP_DIV_256, LSP_DIV_512, LSP_LINEAR, and speex_bits_unpack_unsigned().
static int lsp_weight_quant (spx_word16_t * x, spx_word16_t * weight, const signed char * cdbk, int nbVec, int nbDim) [static]
References MAC16_32_Q15, MULT16_16, ptr(), SHL16, SUB16, and VERY_LARGE32.
Referenced by lsp_quant_high(), lsp_quant_lbr(), and lsp_quant_nb().
Variable Documentation
const signed char high_lsp_cdbk[]
Referenced by lsp_quant_high(), and lsp_unquant_high().
const signed char high_lsp_cdbk2[]
Referenced by lsp_quant_high(), and lsp_unquant_high().