ioquake3: code/libspeex/sb_celp.c File Reference
sb_celp.c File Reference
#include <math.h>
#include "sb_celp.h"
#include "filters.h"
#include "lpc.h"
#include "lsp.h"
#include "stack_alloc.h"
#include "cb_search.h"
#include "quant_lsp.h"
#include "vq.h"
#include "ltp.h"
#include "arch.h"
#include "math_approx.h"
#include "os_support.h"
Defines
#define NULL 0
#define SB_ENC_STACK (10000*sizeof(spx_sig_t))
#define SB_DEC_STACK (6000*sizeof(spx_sig_t))
#define sqr(x) ((x)*(x))
#define SUBMODE(x) st->submodes[st->submodeID]->x
#define LSP_MARGIN .05
#define LSP_DELTA1 .2
#define LSP_DELTA2 .05
#define QMF_ORDER 64
Functions
void * sb_encoder_init (const SpeexMode *m)
void sb_encoder_destroy (void *state)
int sb_encode (void *state, void *vin, SpeexBits *bits)
void * sb_decoder_init (const SpeexMode *m)
void sb_decoder_destroy (void *state)
static void sb_decode_lost (SBDecState *st, spx_word16_t *out, int dtx, char *stack)
int sb_decode (void *state, SpeexBits *bits, void *vout)
int sb_encoder_ctl (void *state, int request, void *ptr)
int sb_decoder_ctl (void *state, int request, void *ptr)
Variables
static const spx_word16_t gc_quant_bound [16]
static const spx_word16_t fold_quant_bound [32]
static const float h0 [64]
const spx_word16_t lag_window []
const spx_word16_t lpc_window []
Define Documentation
#define LSP_DELTA1 .2
Referenced by sb_encode().
#define LSP_DELTA2 .05
Referenced by sb_encode().
#define LSP_MARGIN .05
Referenced by sb_decode(), and sb_encode().
#define NULL 0
Referenced by sb_decode(), sb_decoder_init(), sb_encode(), and sb_encoder_init().
#define QMF_ORDER 64
Referenced by sb_decode(), sb_decode_lost(), sb_decoder_ctl(), sb_decoder_init(), sb_encode(), sb_encoder_ctl(), and sb_encoder_init().
#define SB_DEC_STACK (6000*sizeof(spx_sig_t))
#define SB_ENC_STACK (10000*sizeof(spx_sig_t))
#define sqr (x) ((x)*(x))
#define SUBMODE (x) st->submodes[st->submodeID]->x
Referenced by sb_decode(), sb_decoder_ctl(), sb_encode(), and sb_encoder_ctl().
Function Documentation
int sb_decode (void * state, SpeexBits * bits, void * out)
Decodes one frame
References ADD32, ALLOC, bits(), compute_rms16(), DIV32, SBDecState::encode_submode, SBDecState::exc_rms, SBDecState::excBuf, EXTRACT16, SBDecState::first, SpeexSBMode::folding_gain, SBDecState::frame_size, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, gc_quant_bound, h0, iir_mem16(), SBDecState::innov_save, SBDecState::interp_qlpc, SBDecState::last_ener, LPC_SCALING, SBDecState::lpcSize, lsp_enforce_margin(), lsp_interpolate(), LSP_MARGIN, lsp_to_lpc(), SBDecState::mem_sp, SBDecState::mode, SpeexMode::mode, MULT16_16, MULT16_16_P14, MULT16_16_Q15, MULT16_32_P15, SBDecState::nbSubframes, NEG32, NULL, SBDecState::old_qlsp, out, PDIV32, SBDecState::pi_gain, PSHR32, QCONST16, QMF_ORDER, qmf_synth(), SATURATE, sb_decode_lost(), SB_SUBMODE_BITS, SBDecState::seed, SHL32, signal_mul(), speex_bits_peek(), speex_bits_remaining(), speex_bits_unpack_unsigned(), speex_decode_native(), speex_decoder_ctl(), SPEEX_GET_DTX_STATUS, SPEEX_GET_EXC, SPEEX_GET_PI_GAIN, SPEEX_MEMSET, speex_notify(), SPEEX_SET_INNOVATION_SAVE, spx_exp, spx_sqrt, SBDecState::st_low, SBDecState::stack, SBDecState::subframeSize, SUBMODE, SBDecState::submodeID, SBDecState::submodes, VARDECL, and VERY_SMALL.
static void sb_decode_lost (SBDecState * st, spx_word16_t * out, int dtx, char * stack) [static]
References bw_lpc(), SBDecState::first, SBDecState::frame_size, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, h0, iir_mem16(), SBDecState::interp_qlpc, SBDecState::last_ener, SBDecState::lpcSize, SBDecState::mem_sp, MULT16_16_Q15, QCONST16, QMF_ORDER, qmf_synth(), SBDecState::seed, speex_rand(), and SBDecState::submodeID.
Referenced by sb_decode().
int sb_decoder_ctl (void * state, int request, void * ptr)
References SBDecState::encode_submode, SBDecState::exc_rms, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, SBDecState::innov_save, SBDecState::last_ener, SBDecState::lpc_enh_enabled, SBDecState::lpcSize, SBDecState::mem_sp, SBDecState::mode, SpeexMode::mode, SBDecState::nbSubframes, SBDecState::pi_gain, ptr(), QMF_ORDER, quality, quality_map, SBDecState::sampling_rate, SB_SUBMODE_BITS, speex_decoder_ctl(), SPEEX_GET_ACTIVITY, SPEEX_GET_BITRATE, SPEEX_GET_DTX_STATUS, SPEEX_GET_ENH, SPEEX_GET_EXC, SPEEX_GET_FRAME_SIZE, SPEEX_GET_HIGHPASS, SPEEX_GET_LOOKAHEAD, SPEEX_GET_LOW_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_GET_SUBMODE_ENCODING, SPEEX_RESET_STATE, SPEEX_SET_ENH, SPEEX_SET_HANDLER, SPEEX_SET_HIGH_MODE, SPEEX_SET_HIGHPASS, SPEEX_SET_INNOVATION_SAVE, SPEEX_SET_LOW_MODE, SPEEX_SET_MODE, SPEEX_SET_QUALITY, SPEEX_SET_SAMPLING_RATE, SPEEX_SET_SUBMODE_ENCODING, SPEEX_SET_USER_HANDLER, SPEEX_SET_WIDEBAND, speex_warning_int(), SBDecState::st_low, SBDecState::stack, SUBMODE, SBDecState::submodeID, and SBDecState::submodes.
void sb_decoder_destroy (void * state)
De-allocates decoder state resources
References SBDecState::exc_rms, SBDecState::excBuf, SBDecState::g0_mem, SBDecState::g1_mem, SBDecState::interp_qlpc, SBDecState::mem_sp, SBDecState::old_qlsp, SBDecState::pi_gain, speex_decoder_destroy(), speex_free(), and SBDecState::st_low.
void* sb_decoder_init (const SpeexMode * m)
Initializes decoder state
References SpeexSBMode::defaultSubmode, SBDecState::encode_submode, SBDecState::exc_rms, SBDecState::excBuf, SBDecState::first, SBDecState::frame_size, SpeexSBMode::frameSize, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, SBDecState::innov_save, SBDecState::interp_qlpc, SBDecState::lpc_enh_enabled, SBDecState::lpcSize, SpeexSBMode::lpcSize, m, SBDecState::mem_sp, SBDecState::mode, SpeexMode::mode, SpeexSBMode::nb_mode, SBDecState::nbSubframes, NULL, SBDecState::old_qlsp, SBDecState::pi_gain, QMF_ORDER, SBDecState::sampling_rate, SBDecState::seed, speex_alloc(), speex_decoder_ctl(), speex_decoder_init(), SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_SET_WIDEBAND, SBDecState::st_low, SBDecState::stack, SBDecState::subframeSize, SpeexSBMode::subframeSize, SBDecState::submodeID, SBDecState::submodes, and SpeexSBMode::submodes.
int sb_encode (void * state, void * in, SpeexBits * bits)
Encodes one frame
References _spx_autocorr(), _spx_lpc(), SBEncState::abr_count, SBEncState::abr_drift, SBEncState::abr_drift2, SBEncState::abr_enabled, ADD16, ADD32, ALLOC, bits(), SpeexSubmode::bits_per_frame, bw_lpc(), SBEncState::complexity, compute_impulse_response(), compute_rms(), compute_rms16(), SBEncState::encode_submode, SBEncState::exc_rms, EXTEND32, EXTRACT16, filter_mem16(), fir_mem16(), SBEncState::first, fold_quant_bound, SBEncState::frame_size, SBEncState::full_frame_size, SBEncState::gamma1, SBEncState::gamma2, gc_quant_bound, h0, SBEncState::h0_mem, SBEncState::high, iir_mem16(), in, SBEncState::innov_rms_save, int(), SBEncState::interp_qlpc, SBEncState::lagWindow, SBEncState::lpc_floor, LPC_SCALING, lpc_to_lsp(), SBEncState::lpcSize, LSP_DELTA1, LSP_DELTA2, lsp_enforce_margin(), lsp_interpolate(), LSP_MARGIN, lsp_quant(), lsp_to_lpc(), SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::mode, SpeexMode::mode, MULT16_16, MULT16_16_P13, MULT16_16_P14, MULT16_16_P15, MULT16_16_Q14, MULT16_16_Q15, MULT16_32_P15, SpeexSBMode::nb_modes, SBEncState::nbSubframes, NULL, SBEncState::old_lsp, SBEncState::old_qlsp, PDIV32, PDIV32_16, SBEncState::pi_gain, PSHR32, QCONST16, qmf_decomp(), QMF_ORDER, SBEncState::relative_quality, SBEncState::sampling_rate, SATURATE, SB_SUBMODE_BITS, scal_quant(), SHL32, SHR32, signal_div(), signal_mul(), speex_bits_pack(), SPEEX_COPY, speex_encode_native(), speex_encoder_ctl(), SPEEX_GET_BITRATE, SPEEX_GET_EXC, SPEEX_GET_LOW_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_RELATIVE_QUALITY, SPEEX_MEMSET, SPEEX_SET_HIGH_MODE, SPEEX_SET_INNOVATION_SAVE, SBEncState::st_low, SBEncState::stack, SUB16, SBEncState::subframeSize, SUBMODE, SBEncState::submodeID, SBEncState::submodes, SBEncState::submodeSelect, SBEncState::vad_enabled, VARDECL, SBEncState::vbr_enabled, SBEncState::vbr_max_high, SBEncState::vbr_quality, SpeexSBMode::vbr_thresh, VERY_SMALL, SBEncState::window, and SBEncState::windowSize.
int sb_encoder_ctl (void * state, int request, void * ptr)
References SBEncState::abr_count, SBEncState::abr_drift, SBEncState::abr_drift2, SBEncState::abr_enabled, SBEncState::complexity, DIV32, SBEncState::encode_submode, SBEncState::exc_rms, SBEncState::first, SBEncState::full_frame_size, SBEncState::h0_mem, SBEncState::h1_mem, SBEncState::innov_rms_save, int(), SBEncState::lpcSize, SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::mode, SpeexMode::mode, MULT16_16, SBEncState::nbSubframes, SBEncState::old_lsp, SBEncState::pi_gain, ptr(), QCONST16, QMF_ORDER, qual(), quality, quality_map, SBEncState::relative_quality, SBEncState::sampling_rate, SB_SUBMODE_BITS, speex_encoder_ctl(), SPEEX_GET_ABR, SPEEX_GET_BITRATE, SPEEX_GET_COMPLEXITY, SPEEX_GET_DTX, SPEEX_GET_EXC, SPEEX_GET_FRAME_SIZE, SPEEX_GET_HIGHPASS, SPEEX_GET_LOOKAHEAD, SPEEX_GET_LOW_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_PLC_TUNING, SPEEX_GET_RELATIVE_QUALITY, SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_GET_SUBMODE_ENCODING, SPEEX_GET_VAD, SPEEX_GET_VBR, SPEEX_GET_VBR_MAX_BITRATE, SPEEX_GET_VBR_QUALITY, SPEEX_RESET_STATE, SPEEX_SET_ABR, SPEEX_SET_BITRATE, SPEEX_SET_COMPLEXITY, SPEEX_SET_DTX, SPEEX_SET_HIGH_MODE, SPEEX_SET_HIGHPASS, SPEEX_SET_INNOVATION_SAVE, SPEEX_SET_LOW_MODE, SPEEX_SET_MODE, SPEEX_SET_PLC_TUNING, SPEEX_SET_QUALITY, SPEEX_SET_SAMPLING_RATE, SPEEX_SET_SUBMODE_ENCODING, SPEEX_SET_VAD, SPEEX_SET_VBR, SPEEX_SET_VBR_MAX_BITRATE, SPEEX_SET_VBR_QUALITY, SPEEX_SET_WIDEBAND, speex_warning_int(), SBEncState::st_low, SBEncState::stack, SBEncState::subframeSize, SUBMODE, SBEncState::submodeID, SBEncState::submodes, SBEncState::submodeSelect, SBEncState::vad_enabled, SBEncState::vbr_enabled, SBEncState::vbr_max, SBEncState::vbr_max_high, and SBEncState::vbr_quality.
void sb_encoder_destroy (void * state)
De-allocates encoder state resources
References SBEncState::exc_rms, SBEncState::h0_mem, SBEncState::h1_mem, SBEncState::high, SBEncState::interp_qlpc, SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::old_lsp, SBEncState::old_qlsp, SBEncState::pi_gain, speex_encoder_destroy(), speex_free(), and SBEncState::st_low.
void* sb_encoder_init (const SpeexMode * m)
Initializes encoder state
References SBEncState::abr_enabled, SBEncState::complexity, SpeexSBMode::defaultSubmode, DIV32, SBEncState::encode_submode, SBEncState::exc_rms, SBEncState::first, SBEncState::frame_size, SpeexSBMode::frameSize, SBEncState::full_frame_size, SBEncState::gamma1, SpeexSBMode::gamma1, SBEncState::gamma2, SpeexSBMode::gamma2, SBEncState::h0_mem, SBEncState::h1_mem, SBEncState::high, SBEncState::innov_rms_save, SBEncState::interp_qlpc, lag_window, SBEncState::lagWindow, SBEncState::lpc_floor, SpeexSBMode::lpc_floor, lpc_window, SBEncState::lpcSize, SpeexSBMode::lpcSize, m, SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::mode, SpeexMode::mode, MULT16_16, SpeexSBMode::nb_mode, SBEncState::nbSubframes, NULL, SBEncState::old_lsp, SBEncState::old_qlsp, SBEncState::pi_gain, QCONST16, QMF_ORDER, SBEncState::relative_quality, SBEncState::sampling_rate, speex_alloc(), speex_encoder_ctl(), speex_encoder_init(), SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_SET_QUALITY, SPEEX_SET_WIDEBAND, SBEncState::st_low, SBEncState::stack, SBEncState::subframeSize, SpeexSBMode::subframeSize, SBEncState::submodeID, SBEncState::submodes, SpeexSBMode::submodes, SBEncState::submodeSelect, SBEncState::vad_enabled, SBEncState::vbr_enabled, SBEncState::vbr_max, SBEncState::vbr_max_high, SBEncState::vbr_quality, SBEncState::window, and SBEncState::windowSize.
Variable Documentation
const spx_word16_t fold_quant_bound[32] [static]
Initial value:
 {
   0.30498, 0.34559, 0.39161, 0.44375, 0.50283, 0.56979, 0.64565, 0.73162,
   0.82903, 0.93942, 1.06450, 1.20624, 1.36685, 1.54884, 1.75506, 1.98875,
   2.25355, 2.55360, 2.89361, 3.27889, 3.71547, 4.21018, 4.77076, 5.40598,
   6.12577, 6.94141, 7.86565, 8.91295, 10.09969, 11.44445, 12.96826, 14.69497}
Referenced by sb_encode().
const spx_word16_t gc_quant_bound[16] [static]
Initial value:
 {
      0.97979, 1.28384, 1.68223, 2.20426, 2.88829, 3.78458, 4.95900, 6.49787,
      8.51428, 11.15642, 14.61846, 19.15484, 25.09895, 32.88761, 43.09325, 56.46588}
Referenced by sb_decode(), and sb_encode().
const float h0[64] [static]
Referenced by sb_decode(), sb_decode_lost(), and sb_encode().
const spx_word16_t lag_window[]
const spx_word16_t lpc_window[]