ioquake3: code/SDL12/include/SDL_error.h File Reference
SDL_error.h File Reference
#include "SDL_stdinc.h"
#include "begin_code.h"
#include "close_code.h"
Functions
Public functions
DECLSPEC void SDLCALL SDL_SetError (const char *fmt,...)
DECLSPEC char *SDLCALL SDL_GetError (void)
DECLSPEC void SDLCALL SDL_ClearError (void)
Private functions
Private error message function - used internally
#define SDL_OutOfMemory() SDL_Error(SDL_ENOMEM)
#define SDL_Unsupported() SDL_Error(SDL_UNSUPPORTED)
enum SDL_errorcode {
SDL_ENOMEM, SDL_EFREAD, SDL_EFWRITE, SDL_EFSEEK,
SDL_UNSUPPORTED, SDL_LASTERROR
}
DECLSPEC void SDLCALL SDL_Error (SDL_errorcode code)
Detailed Description
Simple error message routines for SDL
Define Documentation
#define SDL_OutOfMemory () SDL_Error(SDL_ENOMEM)
#define SDL_Unsupported () SDL_Error(SDL_UNSUPPORTED)
Enumeration Type Documentation
enum SDL_errorcode
Enumerator:
SDL_ENOMEM
SDL_EFREAD
SDL_EFWRITE
SDL_EFSEEK
SDL_UNSUPPORTED
SDL_LASTERROR
Function Documentation
DECLSPEC void SDLCALL SDL_ClearError (void)
DECLSPEC void SDLCALL SDL_Error (SDL_errorcode code)
DECLSPEC char* SDLCALL SDL_GetError (void)
Referenced by GLimp_SetMode(), GLimp_StartDriverAndSetMode(), IN_InitJoystick(), and SNDDMA_Init().
DECLSPEC void SDLCALL SDL_SetError (const char * fmt, ...)