ioquake3: code/sdl/sdl_glimp.c File Reference
sdl_glimp.c File Reference
#include <SDL.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "../renderer/tr_local.h"
#include "../client/client.h"
#include "../sys/sys_local.h"
#include "sdl_icon.h"
Defines
#define GLimp_GetCurrentContext() (NULL)
#define GLimp_SetCurrentContext(ctx)
#define R_MODE_FALLBACK 3
Typedefs
typedef void * QGLContext
Enumerations
enum rserr_t { RSERR_OK, RSERR_INVALID_FULLSCREEN, RSERR_INVALID_MODE, RSERR_UNKNOWN }
Functions
void (APIENTRYP qglActiveTextureARB)(GLenum texture)
void GLimp_Shutdown (void)
void GLimp_Minimize (void)
void GLimp_LogComment (char *comment)
static int GLimp_CompareModes (const void *a, const void *b)
static void GLimp_DetectAvailableModes (void)
static int GLimp_SetMode (int mode, qboolean fullscreen, qboolean noborder)
static qboolean GLimp_StartDriverAndSetMode (int mode, qboolean fullscreen, qboolean noborder)
static qboolean GLimp_HaveExtension (const char *ext)
static void GLimp_InitExtensions (void)
void GLimp_Init (void)
void GLimp_EndFrame (void)
void GLimp_RenderThreadWrapper (void *arg)
qboolean GLimp_SpawnRenderThread (void(*function)(void))
void * GLimp_RendererSleep (void)
void GLimp_FrontEndSleep (void)
void GLimp_WakeRenderer (void *data)
Variables
static QGLContext opengl_context
static SDL_Surface * screen = NULL
static const SDL_VideoInfo * videoInfo = NULL
cvar_t * r_allowSoftwareGL
cvar_t * r_allowResize
cvar_t * r_centerWindow
cvar_t * r_sdlDriver
GLfloat s
GLfloat GLfloat t
GLsizei count
Define Documentation
#define GLimp_GetCurrentContext () (NULL)
Referenced by GLimp_SetMode().
#define GLimp_SetCurrentContext (ctx)
#define R_MODE_FALLBACK 3
Referenced by GLimp_Init().
Typedef Documentation
typedef void* QGLContext
Enumeration Type Documentation
enum rserr_t
Enumerator:
RSERR_OK
RSERR_INVALID_FULLSCREEN
RSERR_INVALID_MODE
RSERR_UNKNOWN
Function Documentation
static int GLimp_CompareModes (const void * a, const void * b) [static]
References displayAspect, SDL_Rect::h, and SDL_Rect::w.
Referenced by GLimp_DetectAvailableModes().
static void GLimp_DetectAvailableModes (void) [static]
References refimport_t::Cvar_Set, GLimp_CompareModes(), h, MAX_STRING_CHARS, modes, PRINT_ALL, PRINT_WARNING, Q_strcat(), ri, SDL_FULLSCREEN, SDL_ListModes(), SDL_OPENGL, va(), and SDL_VideoInfo::vfmt.
Referenced by GLimp_SetMode().
void GLimp_EndFrame (void)
References refimport_t::Cmd_ExecuteText, refimport_t::Cvar_Set, refimport_t::Cvar_VariableIntegerValue, EXEC_APPEND, SDL_Surface::flags, refimport_t::IN_Restart, cvar_s::integer, cvar_s::modified, PRINT_ALL, Q_stricmp(), qfalse, qtrue, r_drawBuffer, r_fullscreen, ri, s, SDL_FULLSCREEN, SDL_GetVideoSurface(), SDL_GL_SwapBuffers(), SDL_WM_ToggleFullScreen(), and cvar_s::string.
void GLimp_FrontEndSleep (void)
Referenced by R_IssueRenderCommands(), and R_SyncRenderThread().
static qboolean GLimp_HaveExtension (const char * ext) [static]
References glconfig_t::extensions_string, glConfig, NULL, ptr(), Q_stristr(), and qfalse.
Referenced by GLimp_InitExtensions().
void GLimp_Init (void)
References CVAR_ARCHIVE, refimport_t::Cvar_Get, CVAR_LATCH, CVAR_ROM, refimport_t::Cvar_Set, refimport_t::Cvar_VariableIntegerValue, glconfig_t::deviceSupportsGamma, glconfig_t::driverType, ERR_FATAL, glconfig_t::extensions_string, glConfig, GLDRV_ICD, GLHW_GENERIC, GLimp_InitExtensions(), GLimp_StartDriverAndSetMode(), glconfig_t::hardwareType, refimport_t::IN_Init, cvar_s::integer, PRINT_ALL, Q_strncpyz(), qfalse, qglGetString, r_fullscreen, r_mode, R_MODE_FALLBACK, r_noborder, glconfig_t::renderer_string, ri, SDL_SetGamma(), refimport_t::Sys_GLimpInit, refimport_t::Sys_GLimpSafeInit, refimport_t::Sys_SetEnv, va(), glconfig_t::vendor_string, and glconfig_t::version_string.
static void GLimp_InitExtensions (void) [static]
References ERR_FATAL, glConfig, GLimp_HaveExtension(), int(), cvar_s::integer, maxAnisotropy, NULL, glconfig_t::numTextureUnits, PRINT_ALL, qfalse, qglActiveTextureARB, qglClientActiveTextureARB, qglGetIntegerv, qglLockArraysEXT, qglMultiTexCoord2fARB, qglUnlockArraysEXT, qtrue, r_allowExtensions, r_ext_compiled_vertex_array, r_ext_compressed_textures, r_ext_multitexture, r_ext_texture_env_add, r_ext_texture_filter_anisotropic, ri, SDL_GL_GetProcAddress(), TC_NONE, TC_S3TC, TC_S3TC_ARB, glconfig_t::textureCompression, glconfig_t::textureEnvAddAvailable, textureFilterAnisotropic, cvar_s::value, and void().
Referenced by GLimp_Init().
void GLimp_LogComment (char * comment)
void GLimp_Minimize (void)
References SDL_WM_IconifyWindow().
Referenced by R_Register().
void* GLimp_RendererSleep (void)
References NULL.
Referenced by RB_RenderThread().
void GLimp_RenderThreadWrapper (void * arg)
static int GLimp_SetMode (int mode, qboolean fullscreen, qboolean noborder) [static]
References CLIENT_WINDOW_ICON, CLIENT_WINDOW_MIN_TITLE, CLIENT_WINDOW_TITLE, glconfig_t::colorBits, Com_Memcpy, SDL_VideoInfo::current_h, SDL_VideoInfo::current_w, glconfig_t::depthBits, displayAspect, glConfig, GLimp_DetectAvailableModes(), GLimp_GetCurrentContext, icon(), cvar_s::integer, glconfig_t::isFullscreen, NULL, opengl_context, SDL_PixelFormat::palette, PRINT_ALL, PRINT_DEVELOPER, qfalse, qglGetString, qtrue, r_colorbits, r_depthbits, r_ext_multisample, R_GetModeInfo(), r_stencilbits, r_stereoEnabled, r_swapInterval, ri, RSERR_INVALID_MODE, RSERR_OK, SDL_CreateRGBSurfaceFrom(), SDL_FreeSurface(), SDL_FULLSCREEN, SDL_GetError(), SDL_GetVideoInfo(), SDL_GL_ACCELERATED_VISUAL, SDL_GL_ALPHA_SIZE, SDL_GL_BLUE_SIZE, SDL_GL_DEPTH_SIZE, SDL_GL_DOUBLEBUFFER, SDL_GL_GREEN_SIZE, SDL_GL_MULTISAMPLEBUFFERS, SDL_GL_MULTISAMPLESAMPLES, SDL_GL_RED_SIZE, SDL_GL_SetAttribute(), SDL_GL_STENCIL_SIZE, SDL_GL_STEREO, SDL_GL_SWAP_CONTROL, SDL_NOFRAME, SDL_OPENGL, SDL_RESIZABLE, SDL_SetVideoMode(), SDL_ShowCursor(), SDL_WM_SetCaption(), SDL_WM_SetIcon(), glconfig_t::stencilBits, glconfig_t::stereoEnabled, cvar_s::value, SDL_VideoInfo::vfmt, glconfig_t::vidHeight, glconfig_t::vidWidth, and glconfig_t::windowAspect.
Referenced by GLimp_StartDriverAndSetMode().
void GLimp_Shutdown (void)
References Com_Memset, glConfig, glState, refimport_t::IN_Shutdown, NULL, ri, SDL_INIT_VIDEO, and SDL_QuitSubSystem().
qboolean GLimp_SpawnRenderThread (void(*)(void) function)
References PRINT_WARNING, qfalse, and ri.
Referenced by R_InitCommandBuffers().
static qboolean GLimp_StartDriverAndSetMode (int mode, qboolean fullscreen, qboolean noborder) [static]
References refimport_t::Cvar_Set, refimport_t::Cvar_VariableIntegerValue, GLimp_SetMode(), cvar_s::modified, PRINT_ALL, qfalse, qtrue, r_fullscreen, ri, RSERR_INVALID_FULLSCREEN, RSERR_INVALID_MODE, SDL_GetError(), SDL_Init(), SDL_INIT_VIDEO, SDL_VideoDriverName(), and SDL_WasInit().
Referenced by GLimp_Init().
void GLimp_WakeRenderer (void * data)
Referenced by R_IssueRenderCommands(), and R_ShutdownCommandBuffers().
void (APIENTRYP qglActiveTextureARB)
Variable Documentation
GLsizei count
QGLContext opengl_context [static]
Referenced by GLimp_SetMode().
cvar_t* r_allowResize
cvar_t* r_allowSoftwareGL
cvar_t* r_centerWindow
cvar_t* r_sdlDriver
GLfloat s
SDL_Surface* screen = NULL [static]
GLfloat GLfloat t
const SDL_VideoInfo* videoInfo = NULL [static]