ioquake3: code/libspeex/smallft.c File Reference
smallft.c File Reference
#include <math.h>
#include "smallft.h"
#include "arch.h"
#include "os_support.h"
Functions
static void drfti1 (int n, float *wa, int *ifac)
static void fdrffti (int n, float *wsave, int *ifac)
static void dradf2 (int ido, int l1, float *cc, float *ch, float *wa1)
static void dradf4 (int ido, int l1, float *cc, float *ch, float *wa1, float *wa2, float *wa3)
static void dradfg (int ido, int ip, int l1, int idl1, float *cc, float *c1, float *c2, float *ch, float *ch2, float *wa)
static void drftf1 (int n, float *c, float *ch, float *wa, int *ifac)
static void dradb2 (int ido, int l1, float *cc, float *ch, float *wa1)
static void dradb3 (int ido, int l1, float *cc, float *ch, float *wa1, float *wa2)
static void dradb4 (int ido, int l1, float *cc, float *ch, float *wa1, float *wa2, float *wa3)
static void dradbg (int ido, int ip, int l1, int idl1, float *cc, float *c1, float *c2, float *ch, float *ch2, float *wa)
static void drftb1 (int n, float *c, float *ch, float *wa, int *ifac)
void spx_drft_forward (struct drft_lookup *l, float *data)
void spx_drft_backward (struct drft_lookup *l, float *data)
void spx_drft_init (struct drft_lookup *l, int n)
void spx_drft_clear (struct drft_lookup *l)
Function Documentation
static void dradb2 (int ido, int l1, float * cc, float * ch, float * wa1) [static]
Referenced by drftb1().
static void dradb3 (int ido, int l1, float * cc, float * ch, float * wa1, float * wa2) [static]
References cr2, and cr3.
Referenced by drftb1().
static void dradb4 (int ido, int l1, float * cc, float * ch, float * wa1, float * wa2, float * wa3) [static]
References cr2, cr3, and cr4.
Referenced by drftb1().
static void dradbg (int ido, int ip, int l1, int idl1, float * cc, float * c1, float * c2, float * ch, float * ch2, float * wa) [static]
Referenced by drftb1().
static void dradf2 (int ido, int l1, float * cc, float * ch, float * wa1) [static]
Referenced by drftf1().
static void dradf4 (int ido, int l1, float * cc, float * ch, float * wa1, float * wa2, float * wa3) [static]
References cr2, cr3, and cr4.
Referenced by drftf1().
static void dradfg (int ido, int ip, int l1, int idl1, float * cc, float * c1, float * c2, float * ch, float * ch2, float * wa) [static]
Referenced by drftf1().
static void drftb1 (int n, float * c, float * ch, float * wa, int * ifac) [static]
References dradb2(), dradb3(), dradb4(), dradbg(), and n.
Referenced by spx_drft_backward().
static void drftf1 (int n, float * c, float * ch, float * wa, int * ifac) [static]
References dradf2(), dradf4(), dradfg(), and n.
Referenced by spx_drft_forward().
static void drfti1 (int n, float * wa, int * ifac) [static]
References ld, and n.
Referenced by fdrffti().
static void fdrffti (int n, float * wsave, int * ifac) [static]
References drfti1().
Referenced by spx_drft_init().
void spx_drft_backward (struct drft_lookup * l, float * data)
References drftb1(), drft_lookup::n, drft_lookup::splitcache, and drft_lookup::trigcache.
void spx_drft_clear (struct drft_lookup * l)
References speex_free(), drft_lookup::splitcache, and drft_lookup::trigcache.
void spx_drft_forward (struct drft_lookup * l, float * data)
References drftf1(), drft_lookup::n, drft_lookup::splitcache, and drft_lookup::trigcache.
void spx_drft_init (struct drft_lookup * l, int n)
References fdrffti(), drft_lookup::n, n, speex_alloc(), drft_lookup::splitcache, and drft_lookup::trigcache.