ioquake3: code/client/snd_dma.c File Reference
snd_dma.c File Reference
#include "snd_local.h"
#include "snd_codec.h"
#include "client.h"
Defines
#define SOUND_FULLVOLUME 80
#define SOUND_ATTENUATE 0.0008f
#define MAX_SFX 4096
#define LOOP_HASH 128
Functions
void S_Update_ (void)
void S_Base_StopAllSounds (void)
void S_Base_StopBackgroundTrack (void)
void S_Base_SoundInfo (void)
void S_Base_SoundList (void)
void S_ChannelFree (channel_t *v)
channel_t * S_ChannelMalloc (void)
void S_ChannelSetup (void)
static long S_HashSFXName (const char *name)
static sfx_t * S_FindName (const char *name)
void S_DefaultSound (sfx_t *sfx)
void S_Base_DisableSounds (void)
sfxHandle_t S_Base_RegisterSound (const char *name, qboolean compressed)
void S_Base_BeginRegistration (void)
void S_memoryLoad (sfx_t *sfx)
void S_SpatializeOrigin (vec3_t origin, int master_vol, int *left_vol, int *right_vol)
void S_Base_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfxHandle)
void S_Base_StartLocalSound (sfxHandle_t sfxHandle, int channelNum)
void S_Base_ClearSoundBuffer (void)
void S_Base_StopLoopingSound (int entityNum)
void S_Base_ClearLoopingSounds (qboolean killall)
void S_Base_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfxHandle)
void S_Base_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfxHandle)
void S_AddLoopSounds (void)
void S_ByteSwapRawSamples (int samples, int width, int s_channels, const byte *data)
void S_Base_RawSamples (int stream, int samples, int rate, int width, int s_channels, const byte *data, float volume, int entityNum)
void S_Base_UpdateEntityPosition (int entityNum, const vec3_t origin)
void S_Base_Respatialize (int entityNum, const vec3_t head, vec3_t axis[3], int inwater)
qboolean S_ScanChannelStarts (void)
void S_Base_Update (void)
void S_GetSoundtime (void)
void S_Base_StartBackgroundTrack (const char *intro, const char *loop)
void S_UpdateBackgroundTrack (void)
void S_FreeOldestSound (void)
void S_Base_Shutdown (void)
qboolean S_Base_Init (soundInterface_t *si)
Variables
snd_stream_t * s_backgroundStream = NULL
static char s_backgroundLoop [MAX_QPATH]
channel_t s_channels [MAX_CHANNELS]
channel_t loop_channels [MAX_CHANNELS]
int numLoopChannels
static int s_soundStarted
static qboolean s_soundMuted
dma_t dma
static int listener_number
static vec3_t listener_origin
static vec3_t listener_axis [3]
int s_soundtime
int s_paintedtime
sfx_t s_knownSfx [MAX_SFX]
int s_numSfx = 0
static sfx_t * sfxHash [LOOP_HASH]
cvar_t * s_testsound
cvar_t * s_show
cvar_t * s_mixahead
cvar_t * s_mixPreStep
static loopSound_t loopSounds [MAX_GENTITIES]
static channel_t * freelist = NULL
int s_rawend [MAX_RAW_STREAMS]
portable_samplepair_t s_rawsamples [MAX_RAW_STREAMS][MAX_RAW_SAMPLES]
Define Documentation
#define LOOP_HASH 128
Referenced by S_Base_BeginRegistration(), S_Base_Init(), and S_HashSFXName().
#define MAX_SFX 4096
Referenced by S_FindName().
#define SOUND_ATTENUATE 0.0008f
Referenced by S_SpatializeOrigin().
#define SOUND_FULLVOLUME 80
Referenced by S_SpatializeOrigin().
Function Documentation
void S_AddLoopSounds (void)
References loopSound_s::active, Com_Milliseconds(), loopSound_s::doppler, channel_t::doppler, loopSound_s::dopplerScale, channel_t::dopplerScale, loopSound_s::kill, sfx_s::lastTimeUsed, channel_t::leftvol, channel_t::master_vol, MAX_CHANNELS, MAX_GENTITIES, loopSound_s::mergeFrame, numLoopChannels, loopSound_s::oldDopplerScale, channel_t::oldDopplerScale, loopSound_s::origin, right, channel_t::rightvol, S_SpatializeOrigin(), loopSound_s::sfx, and channel_t::thesfx.
Referenced by S_Base_Respatialize().
void S_Base_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfxHandle)
References loopSound_s::active, cls, Com_Error(), Com_Printf(), DistanceSquared(), loopSound_s::doppler, loopSound_s::dopplerScale, ERR_DROP, clientStatic_t::framecount, loopSound_s::framenum, sfx_s::inMemory, cvar_s::integer, loopSound_s::kill, listener_number, MAX_DOPPLER_SCALE, loopSound_s::oldDopplerScale, out, qfalse, qtrue, S_COLOR_YELLOW, s_doppler, S_memoryLoad(), s_numSfx, s_soundMuted, s_soundStarted, loopSound_s::sfx, sfx_s::soundLength, sfx_s::soundName, VectorAdd, VectorCopy, and VectorLengthSquared().
Referenced by S_Base_Init().
void S_Base_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfxHandle)
References loopSound_s::active, Com_Error(), Com_Printf(), loopSound_s::doppler, ERR_DROP, sfx_s::inMemory, loopSound_s::kill, qfalse, qtrue, S_COLOR_YELLOW, S_memoryLoad(), s_numSfx, s_soundMuted, s_soundStarted, loopSound_s::sfx, sfx_s::soundLength, sfx_s::soundName, and VectorCopy.
Referenced by S_Base_Init().
void S_Base_BeginRegistration (void)
References Com_Memset, LOOP_HASH, qfalse, S_Base_RegisterSound(), s_numSfx, s_soundMuted, and SND_setup().
Referenced by S_Base_Init().
void S_Base_ClearLoopingSounds (qboolean killall)
References kill(), loopSound_s::kill, MAX_GENTITIES, numLoopChannels, qfalse, qtrue, and S_Base_StopLoopingSound().
Referenced by S_Base_Init().
void S_Base_ClearSoundBuffer (void)
References dma_t::buffer, Com_Memset, MAX_CHANNELS, MAX_GENTITIES, numLoopChannels, S_ChannelSetup(), s_rawend, s_soundStarted, dma_t::samplebits, dma_t::samples, SNDDMA_BeginPainting(), and SNDDMA_Submit().
Referenced by S_Base_Init(), and S_Base_StopAllSounds().
void S_Base_DisableSounds (void)
References qtrue, S_Base_StopAllSounds(), and s_soundMuted.
Referenced by S_Base_Init().
qboolean S_Base_Init (soundInterface_t * si)
References soundInterface_t::AddLoopingSound, soundInterface_t::AddRealLoopingSound, soundInterface_t::BeginRegistration, soundInterface_t::ClearLoopingSounds, soundInterface_t::ClearSoundBuffer, Com_Memset, CVAR_ARCHIVE, CVAR_CHEAT, Cvar_Get(), soundInterface_t::DisableSounds, LOOP_HASH, qfalse, qtrue, soundInterface_t::RawSamples, soundInterface_t::RegisterSound, soundInterface_t::Respatialize, S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_BeginRegistration(), S_Base_ClearLoopingSounds(), S_Base_ClearSoundBuffer(), S_Base_DisableSounds(), S_Base_RawSamples(), S_Base_RegisterSound(), S_Base_Respatialize(), S_Base_Shutdown(), S_Base_SoundInfo(), S_Base_SoundList(), S_Base_StartBackgroundTrack(), S_Base_StartLocalSound(), S_Base_StartSound(), S_Base_StopAllSounds(), S_Base_StopBackgroundTrack(), S_Base_StopLoopingSound(), S_Base_Update(), S_Base_UpdateEntityPosition(), s_paintedtime, s_soundMuted, s_soundStarted, s_soundtime, soundInterface_t::Shutdown, SNDDMA_Init(), soundInterface_t::SoundInfo, soundInterface_t::SoundList, soundInterface_t::StartBackgroundTrack, soundInterface_t::StartLocalSound, soundInterface_t::StartSound, soundInterface_t::StopAllSounds, soundInterface_t::StopBackgroundTrack, soundInterface_t::StopLoopingSound, soundInterface_t::Update, and soundInterface_t::UpdateEntityPosition.
Referenced by S_Init().
void S_Base_RawSamples (int stream, int samples, int rate, int width, int s_channels, const byte * data, float volume, int entityNum)
References Com_DPrintf(), if(), cvar_s::integer, portable_samplepair_t::left, MAX_RAW_SAMPLES, MAX_RAW_STREAMS, portable_samplepair_t::right, s_muted, s_rawend, s_soundMuted, s_soundStarted, s_soundtime, s_volume, dma_t::speed, src, and cvar_s::value.
Referenced by S_Base_Init(), and S_UpdateBackgroundTrack().
sfxHandle_t S_Base_RegisterSound (const char * name, qboolean compressed)
References Com_Printf(), sfx_s::defaultSound, sfx_s::inMemory, MAX_QPATH, qfalse, S_COLOR_YELLOW, S_FindName(), s_knownSfx, S_memoryLoad(), s_soundStarted, sfx_s::soundCompressed, sfx_s::soundData, and sfx_s::soundName.
Referenced by S_Base_BeginRegistration(), and S_Base_Init().
void S_Base_Respatialize (int entityNum, const vec3_t head, vec3_t axis[3], int inwater)
References channel_t::entnum, channel_t::fixed_origin, channel_t::leftvol, listener_axis, listener_number, listener_origin, channel_t::master_vol, MAX_CHANNELS, loopSound_s::origin, channel_t::origin, channel_t::rightvol, S_AddLoopSounds(), s_channels, s_soundMuted, s_soundStarted, S_SpatializeOrigin(), channel_t::thesfx, and VectorCopy.
Referenced by S_Base_Init().
void S_Base_Shutdown (void)
References Cmd_RemoveCommand(), s_numSfx, s_soundStarted, SND_shutdown(), and SNDDMA_Shutdown().
Referenced by S_Base_Init().
void S_Base_SoundInfo (void)
References dma_t::buffer, dma_t::channels, Com_Printf(), s_backgroundLoop, s_soundStarted, dma_t::samplebits, dma_t::samples, dma_t::speed, and dma_t::submission_chunk.
Referenced by S_Base_Init().
void S_Base_SoundList (void)
References Com_Printf(), sfx_s::inMemory, S_DisplayFreeMemory(), s_numSfx, sfx_s::soundCompressionMethod, sfx_s::soundLength, and sfx_s::soundName.
Referenced by S_Base_Init().
void S_Base_StartBackgroundTrack (const char * intro, const char * loop)
References snd_info_s::channels, Com_DPrintf(), Com_Printf(), snd_stream_s::info, NULL, Q_strncpyz(), snd_info_s::rate, s_backgroundLoop, S_Base_StopBackgroundTrack(), S_CodecCloseStream(), S_CodecOpenStream(), and S_COLOR_YELLOW.
Referenced by S_Base_Init(), and S_UpdateBackgroundTrack().
void S_Base_StartLocalSound (sfxHandle_t sfxHandle, int channelNum)
References Com_Printf(), listener_number, NULL, S_Base_StartSound(), S_COLOR_YELLOW, s_numSfx, s_soundMuted, and s_soundStarted.
Referenced by S_Base_Init().
void S_Base_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfxHandle)
References channel_t::allocTime, CHAN_ANNOUNCER, Com_Error(), Com_Milliseconds(), Com_Printf(), channel_t::doppler, channel_t::entchannel, channel_t::entnum, ERR_DROP, channel_t::fixed_origin, sfx_s::inMemory, cvar_s::integer, sfx_s::lastTimeUsed, channel_t::leftvol, listener_number, channel_t::master_vol, MAX_CHANNELS, MAX_GENTITIES, channel_t::origin, qfalse, qtrue, channel_t::rightvol, S_ChannelMalloc(), s_channels, S_COLOR_YELLOW, S_memoryLoad(), s_numSfx, s_paintedtime, s_soundMuted, s_soundStarted, sfx_s::soundName, START_SAMPLE_IMMEDIATE, channel_t::startSample, channel_t::thesfx, and VectorCopy.
Referenced by S_Base_Init(), and S_Base_StartLocalSound().
void S_Base_StopAllSounds (void)
References S_Base_ClearSoundBuffer(), S_Base_StopBackgroundTrack(), and s_soundStarted.
Referenced by S_Base_DisableSounds(), S_Base_Init(), and S_GetSoundtime().
void S_Base_StopBackgroundTrack (void)
References NULL, S_CodecCloseStream(), and s_rawend.
Referenced by S_Base_Init(), S_Base_StartBackgroundTrack(), S_Base_StopAllSounds(), and S_UpdateBackgroundTrack().
void S_Base_StopLoopingSound (int entityNum)
References loopSound_s::active, loopSound_s::kill, and qfalse.
Referenced by S_Base_ClearLoopingSounds(), and S_Base_Init().
void S_Base_Update (void)
References Com_Printf(), cvar_s::integer, channel_t::leftvol, MAX_CHANNELS, channel_t::rightvol, s_channels, s_paintedtime, s_soundMuted, s_soundStarted, S_Update_(), S_UpdateBackgroundTrack(), sfx_s::soundName, and channel_t::thesfx.
Referenced by S_Base_Init().
void S_Base_UpdateEntityPosition (int entityNum, const vec3_t origin)
References Com_Error(), ERR_DROP, MAX_GENTITIES, and VectorCopy.
Referenced by S_Base_Init().
void S_ByteSwapRawSamples (int samples, int width, int s_channels, const byte * data)
void S_ChannelFree (channel_t * v)
References NULL, and channel_t::thesfx.
Referenced by S_ScanChannelStarts().
channel_t* S_ChannelMalloc (void)
References channel_t::allocTime, Com_Milliseconds(), freelist, and NULL.
Referenced by S_Base_StartSound().
void S_ChannelSetup (void)
References Com_DPrintf(), Com_Memset, MAX_CHANNELS, NULL, and s_channels.
Referenced by S_Base_ClearSoundBuffer().
void S_DefaultSound (sfx_t * sfx)
References sndBuffer_s::next, NULL, SND_malloc(), sndBuffer_s::sndChunk, sfx_s::soundData, and sfx_s::soundLength.
static sfx_t* S_FindName (const char * name) [static]
References Com_Error(), Com_Memset, ERR_FATAL, hash(), MAX_QPATH, MAX_SFX, sfx_s::next, Q_stricmp(), S_HashSFXName(), s_numSfx, and sfx_s::soundName.
Referenced by S_Base_RegisterSound().
void S_FreeOldestSound (void)
References buffer, Com_DPrintf(), Com_Milliseconds(), sfx_s::inMemory, sfx_s::lastTimeUsed, sndBuffer_s::next, NULL, qfalse, s_numSfx, SND_free(), sfx_s::soundData, and sfx_s::soundName.
Referenced by SND_malloc().
void S_GetSoundtime (void)
References dma_t::channels, cl_aviFrameRate, CL_VideoRecording(), Com_DPrintf(), int(), S_Base_StopAllSounds(), s_paintedtime, s_soundtime, dma_t::samples, SNDDMA_GetDMAPos(), dma_t::speed, dma_t::submission_chunk, and cvar_s::value.
Referenced by S_Update_().
static long S_HashSFXName (const char * name) [static]
References hash(), long(), and LOOP_HASH.
Referenced by S_FindName().
void S_memoryLoad (sfx_t * sfx)
References sfx_s::defaultSound, sfx_s::inMemory, qtrue, and S_LoadSound().
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_RegisterSound(), and S_Base_StartSound().
qboolean S_ScanChannelStarts (void)
References MAX_CHANNELS, qfalse, qtrue, S_ChannelFree(), s_channels, s_paintedtime, sfx_s::soundLength, START_SAMPLE_IMMEDIATE, channel_t::startSample, and channel_t::thesfx.
Referenced by S_Update_().
void S_SpatializeOrigin (vec3_t origin, int master_vol, int * left_vol, int * right_vol)
References dma_t::channels, listener_axis, listener_origin, SOUND_ATTENUATE, SOUND_FULLVOLUME, VectorNormalize(), VectorRotate(), and VectorSubtract.
Referenced by S_AddLoopSounds(), and S_Base_Respatialize().
void S_Update_ (void)
References dma_t::channels, Com_Milliseconds(), op, S_GetSoundtime(), S_PaintChannels(), S_ScanChannelStarts(), s_soundMuted, s_soundStarted, s_soundtime, dma_t::samples, SNDDMA_BeginPainting(), SNDDMA_Submit(), dma_t::speed, dma_t::submission_chunk, and cvar_s::value.
Referenced by S_Base_Update().
void S_UpdateBackgroundTrack (void)
References snd_info_s::channels, snd_stream_s::info, MAX_RAW_SAMPLES, NULL, snd_info_s::rate, s_backgroundLoop, S_Base_RawSamples(), S_Base_StartBackgroundTrack(), S_Base_StopBackgroundTrack(), S_CodecCloseStream(), S_CodecReadStream(), s_musicVolume, s_rawend, s_soundtime, dma_t::speed, cvar_s::value, and snd_info_s::width.
Referenced by S_Base_Update().
Variable Documentation
dma_t dma
Referenced by CL_OpenAVIForWriting(), ResampleSfx(), ResampleSfxRaw(), S_AdpcmMemoryNeeded(), S_TransferPaintBuffer(), S_TransferStereo16(), SNDDMA_AudioCallback(), SNDDMA_Init(), and SNDDMA_Shutdown().
channel_t* freelist = NULL [static]
Referenced by S_ChannelMalloc().
vec3_t listener_axis[3] [static]
Referenced by S_Base_Respatialize(), and S_SpatializeOrigin().
int listener_number [static]
Referenced by S_Base_AddLoopingSound(), S_Base_Respatialize(), S_Base_StartLocalSound(), and S_Base_StartSound().
vec3_t listener_origin [static]
Referenced by S_Base_Respatialize(), and S_SpatializeOrigin().
channel_t loop_channels[MAX_CHANNELS]
Referenced by S_PaintChannels().
loopSound_t loopSounds[MAX_GENTITIES] [static]
int numLoopChannels
Referenced by S_AddLoopSounds(), S_Base_ClearLoopingSounds(), S_Base_ClearSoundBuffer(), and S_PaintChannels().
char s_backgroundLoop[MAX_QPATH] [static]
Referenced by S_Base_SoundInfo(), S_Base_StartBackgroundTrack(), and S_UpdateBackgroundTrack().
snd_stream_t* s_backgroundStream = NULL
channel_t s_channels[MAX_CHANNELS]
Referenced by S_Base_Respatialize(), S_Base_StartSound(), S_Base_Update(), S_ChannelSetup(), S_PaintChannels(), and S_ScanChannelStarts().
sfx_t s_knownSfx[MAX_SFX]
Referenced by S_Base_RegisterSound().
cvar_t* s_mixahead
cvar_t* s_mixPreStep
int s_numSfx = 0
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_BeginRegistration(), S_Base_Shutdown(), S_Base_SoundList(), S_Base_StartLocalSound(), S_Base_StartSound(), S_FindName(), and S_FreeOldestSound().
int s_paintedtime
Referenced by S_Base_Init(), S_Base_StartSound(), S_Base_Update(), S_GetSoundtime(), S_PaintChannels(), S_ScanChannelStarts(), S_TransferPaintBuffer(), and S_TransferStereo16().
int s_rawend[MAX_RAW_STREAMS]
Referenced by CIN_PlayCinematic(), RoQInterrupt(), S_Base_ClearSoundBuffer(), S_Base_RawSamples(), S_Base_StopBackgroundTrack(), S_PaintChannels(), and S_UpdateBackgroundTrack().
portable_samplepair_t s_rawsamples[MAX_RAW_STREAMS][MAX_RAW_SAMPLES]
Referenced by S_PaintChannels().
cvar_t* s_show
qboolean s_soundMuted [static]
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_BeginRegistration(), S_Base_DisableSounds(), S_Base_Init(), S_Base_RawSamples(), S_Base_Respatialize(), S_Base_StartLocalSound(), S_Base_StartSound(), S_Base_Update(), and S_Update_().
int s_soundStarted [static]
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_ClearSoundBuffer(), S_Base_Init(), S_Base_RawSamples(), S_Base_RegisterSound(), S_Base_Respatialize(), S_Base_Shutdown(), S_Base_SoundInfo(), S_Base_StartLocalSound(), S_Base_StartSound(), S_Base_StopAllSounds(), S_Base_Update(), and S_Update_().
int s_soundtime
Referenced by CIN_PlayCinematic(), RoQInterrupt(), S_Base_Init(), S_Base_RawSamples(), S_GetSoundtime(), S_Update_(), and S_UpdateBackgroundTrack().
cvar_t* s_testsound
Referenced by S_TransferPaintBuffer().
sfx_t* sfxHash[LOOP_HASH] [static]