ioquake3: code/client/snd_mix.c File Reference
snd_mix.c File Reference
#include "client.h"
#include "snd_local.h"
Functions
void S_WriteLinearBlastStereo16 (void)
void S_TransferStereo16 (unsigned long *pbuf, int endtime)
void S_TransferPaintBuffer (int endtime)
static void S_PaintChannelFrom16_scalar (channel_t *ch, const sfx_t *sc, int count, int sampleOffset, int bufferOffset)
static void S_PaintChannelFrom16 (channel_t *ch, const sfx_t *sc, int count, int sampleOffset, int bufferOffset)
void S_PaintChannelFromWavelet (channel_t *ch, sfx_t *sc, int count, int sampleOffset, int bufferOffset)
void S_PaintChannelFromADPCM (channel_t *ch, sfx_t *sc, int count, int sampleOffset, int bufferOffset)
void S_PaintChannelFromMuLaw (channel_t *ch, sfx_t *sc, int count, int sampleOffset, int bufferOffset)
void S_PaintChannels (int endtime)
Variables
static portable_samplepair_t paintbuffer [PAINTBUFFER_SIZE]
static int snd_vol
int * snd_p
int snd_linear_count
short * snd_out
Function Documentation
static void S_PaintChannelFrom16 (channel_t * ch, const sfx_t * sc, int count, int sampleOffset, int bufferOffset) [static]
References com_altivec, cvar_s::integer, and S_PaintChannelFrom16_scalar().
Referenced by S_PaintChannels().
static void S_PaintChannelFrom16_scalar (channel_t * ch, const sfx_t * sc, int count, int sampleOffset, int bufferOffset) [static]
References count, data, channel_t::doppler, channel_t::dopplerScale, portable_samplepair_t::left, channel_t::leftvol, sndBuffer_s::next, channel_t::oldDopplerScale, portable_samplepair_t::right, channel_t::rightvol, SND_CHUNK_SIZE, snd_vol, sndBuffer_s::sndChunk, and sfx_s::soundData.
Referenced by S_PaintChannelFrom16().
void S_PaintChannelFromADPCM (channel_t * ch, sfx_t * sc, int count, int sampleOffset, int bufferOffset)
References count, data, channel_t::doppler, portable_samplepair_t::left, channel_t::leftvol, sndBuffer_s::next, channel_t::oldDopplerScale, portable_samplepair_t::right, channel_t::rightvol, S_AdpcmGetSamples(), sfxScratchBuffer, sfxScratchIndex, sfxScratchPointer, SND_CHUNK_SIZE, snd_vol, and sfx_s::soundData.
Referenced by S_PaintChannels().
void S_PaintChannelFromMuLaw (channel_t * ch, sfx_t * sc, int count, int sampleOffset, int bufferOffset)
References count, data, channel_t::doppler, channel_t::dopplerScale, int(), portable_samplepair_t::left, channel_t::leftvol, mulawToShort, sndBuffer_s::next, portable_samplepair_t::right, channel_t::rightvol, SND_CHUNK_SIZE, snd_vol, sndBuffer_s::sndChunk, and sfx_s::soundData.
Referenced by S_PaintChannels().
void S_PaintChannelFromWavelet (channel_t * ch, sfx_t * sc, int count, int sampleOffset, int bufferOffset)
References count, data, decodeWavelet(), portable_samplepair_t::left, channel_t::leftvol, sndBuffer_s::next, portable_samplepair_t::right, channel_t::rightvol, S_AdpcmGetSamples(), sfxScratchBuffer, sfxScratchIndex, sfxScratchPointer, SND_CHUNK_SIZE, SND_CHUNK_SIZE_FLOAT, snd_vol, and sfx_s::soundData.
Referenced by S_PaintChannels().
void S_PaintChannels (int endtime)
References Com_Memset, count, end, cvar_s::integer, portable_samplepair_t::left, channel_t::leftvol, loop_channels, MAX_CHANNELS, MAX_RAW_SAMPLES, MAX_RAW_STREAMS, NULL, numLoopChannels, PAINTBUFFER_SIZE, portable_samplepair_t::right, channel_t::rightvol, s, s_channels, s_muted, S_PaintChannelFrom16(), S_PaintChannelFromADPCM(), S_PaintChannelFromMuLaw(), S_PaintChannelFromWavelet(), s_paintedtime, s_rawend, s_rawsamples, S_TransferPaintBuffer(), s_volume, snd_vol, sfx_s::soundCompressionMethod, sfx_s::soundData, sfx_s::soundLength, channel_t::startSample, channel_t::thesfx, and cvar_s::value.
Referenced by S_Update_().
void S_TransferPaintBuffer (int endtime)
References dma_t::buffer, dma_t::channels, count, dma, if(), cvar_s::integer, out, right, s_paintedtime, s_testsound, S_TransferStereo16(), dma_t::samplebits, dma_t::samples, and val.
Referenced by S_PaintChannels().
void S_TransferStereo16 (unsigned long * pbuf, int endtime)
References CL_VideoRecording(), CL_WriteAVIAudioFrame(), dma, s_paintedtime, S_WriteLinearBlastStereo16(), dma_t::samples, snd_linear_count, snd_out, and snd_p.
Referenced by S_TransferPaintBuffer().
void S_WriteLinearBlastStereo16 (void)
References snd_linear_count, snd_out, snd_p, and val.
Referenced by S_TransferStereo16().
Variable Documentation
portable_samplepair_t paintbuffer[PAINTBUFFER_SIZE] [static]
int snd_linear_count
Referenced by S_TransferStereo16(), and S_WriteLinearBlastStereo16().
short* snd_out
Referenced by S_TransferStereo16(), and S_WriteLinearBlastStereo16().
int* snd_p
Referenced by S_TransferStereo16(), and S_WriteLinearBlastStereo16().
int snd_vol [static]
Referenced by S_PaintChannelFrom16_scalar(), S_PaintChannelFromADPCM(), S_PaintChannelFromMuLaw(), S_PaintChannelFromWavelet(), and S_PaintChannels().