ioquake3: code/libspeex/include/speex/speex_buffer.h File Reference
speex_buffer.h File Reference
#include "speex/speex_types.h"
Typedefs
typedef struct SpeexBuffer_ SpeexBuffer
Functions
SpeexBuffer * speex_buffer_init (int size)
void speex_buffer_destroy (SpeexBuffer *st)
int speex_buffer_write (SpeexBuffer *st, void *data, int len)
int speex_buffer_writezeros (SpeexBuffer *st, int len)
int speex_buffer_read (SpeexBuffer *st, void *data, int len)
int speex_buffer_get_available (SpeexBuffer *st)
int speex_buffer_resize (SpeexBuffer *st, int len)
Typedef Documentation
typedef struct SpeexBuffer_ SpeexBuffer
Function Documentation
void speex_buffer_destroy (SpeexBuffer * st)
References SpeexBuffer_::data, and speex_free().
int speex_buffer_get_available (SpeexBuffer * st)
References SpeexBuffer_::available.
SpeexBuffer* speex_buffer_init (int size)
References SpeexBuffer_::available, SpeexBuffer_::data, SpeexBuffer_::read_ptr, SpeexBuffer_::size, speex_alloc(), and SpeexBuffer_::write_ptr.
int speex_buffer_read (SpeexBuffer * st, void * data, int len)
References SpeexBuffer_::available, SpeexBuffer_::data, data, end, SpeexBuffer_::read_ptr, SpeexBuffer_::size, SPEEX_COPY, and SPEEX_MEMSET.
int speex_buffer_resize (SpeexBuffer * st, int len)
References SpeexBuffer_::data, SpeexBuffer_::size, and speex_realloc().
int speex_buffer_write (SpeexBuffer * st, void * data, int len)
References SpeexBuffer_::available, SpeexBuffer_::data, data, end, SpeexBuffer_::read_ptr, SpeexBuffer_::size, SPEEX_COPY, and SpeexBuffer_::write_ptr.
int speex_buffer_writezeros (SpeexBuffer * st, int len)
References SpeexBuffer_::available, SpeexBuffer_::data, end, SpeexBuffer_::read_ptr, SpeexBuffer_::size, SPEEX_MEMSET, and SpeexBuffer_::write_ptr.