ioquake3: code/tools/lcc/src/stmt.c File Reference
stmt.c File Reference
#include "c.h"
Defines
#define SWSIZE 512
#define den(i, j) ((j-buckets[i]+1.0)/(v[j]-v[buckets[i]]+1))
Functions
static int foldcond (Tree e1, Tree e2)
static void caselabel (Swtch, long, int)
static void cmp (int, Symbol, long, int)
static Tree conditional (int)
static void dostmt (int, Swtch, int)
static int equal (Symbol, Symbol)
static void forstmt (int, Swtch, int)
static void ifstmt (int, int, Swtch, int)
static Symbol localaddr (Tree)
static void stmtlabel (void)
static void swstmt (int, int, int)
static void whilestmt (int, Swtch, int)
Code code (int kind)
int reachable (int kind)
void addlocal (Symbol p)
void definept (Coordinate *p)
void statement (int loop, Swtch swp, int lev)
void swgen (Swtch swp)
void swcode (Swtch swp, int b[], int lb, int ub)
void retcode (Tree p)
void definelab (int lab)
Node jump (int lab)
void branch (int lab)
void equatelab (Symbol old, Symbol new)
Variables
struct code codehead = { Start }
Code codelist = &codehead
float density = 0.5
Table stmtlabs
Define Documentation
#define den (i, j) ((j-buckets[i]+1.0)/(v[j]-v[buckets[i]]+1))
Referenced by filter_mem16_10(), filter_mem16_8(), fir_mem16(), highpass(), iir_mem16_10(), iir_mem16_8(), main(), make_odither_array(), PM_CrashLand(), and swgen().
#define SWSIZE 512
Referenced by swstmt().
Function Documentation
void addlocal (Symbol p)
References code, symbol::defined, level, code::Local, and symbol::scope.
Referenced by addrtree(), listnodes(), primary(), retcode(), swstmt(), tracecall(), and undag().
void branch (int lab)
References code, cp, equal(), equatelab(), findlabel(), code::forest, jump(), code::kind, code::next, NULL, node::op, code::prev, symbol::ref, node::syms, code::u, V, walk(), and warning().
Referenced by forstmt(), ifstmt(), statement(), swcode(), swstmt(), and whilestmt().
static void caselabel (Swtch swp, long val, int lab) [static]
References Aflag, error(), findlabel(), FUNC, swtch::labels, swtch::ncases, newarray(), swtch::size, val, vals, swtch::values, and warning().
Referenced by statement().
static void cmp (int op, Symbol p, long n, int lab) [static]
References cast(), cnsttree(), eqtree, idtree(), listnodes(), signedint(), and symbol::type.
Referenced by swcode().
Code code (int kind)
References codelist, cp, FUNC, code::kind, kind, NEW, code::next, NULL, code::prev, reachable(), and warning().
static Tree conditional (int tok) [static]
References Aflag, cond(), expr(), funcname(), isfunc, tree::type, and warning().
Referenced by dostmt(), forstmt(), ifstmt(), and whilestmt().
void definelab (int lab)
References code, cp, findlabel(), code::forest, node::kids, code::kind, symbol::l, newnode(), code::next, NULL, node::op, P, code::prev, symbol::ref, specific, node::syms, code::u, symbol::u, V, and walk().
Referenced by dostmt(), forstmt(), funcdefn(), ifstmt(), statement(), stmtlabel(), swcode(), swstmt(), and whilestmt().
void definept (Coordinate * p)
References apply(), code, cp, code::Defpoint, events, findcount(), code::Gen, glevel, identifiers, listnodes(), locus(), n, ncalled, npoints, NULL, code::point, Events::points, reachable(), refinc, src, and code::u.
Referenced by compound(), dcllocal(), dostmt(), forstmt(), ifstmt(), statement(), swstmt(), and whilestmt().
static void dostmt (int lab, Swtch swp, int lev) [static]
References conditional(), definelab(), definept(), expect(), findlabel(), gettok(), NULL, refinc, statement(), t, and walk().
Referenced by statement().
static int equal (Symbol lprime, Symbol dst) [static]
References symbol::l, and symbol::u.
Referenced by branch().
void equatelab (Symbol old, Symbol new)
References symbol::l, NULL, and symbol::u.
Referenced by branch(), labelnode(), and listnodes().
static int foldcond (Tree e1, Tree e2) [static]
References ASGN, EQ, GT, value::i, I, isaddrop, tree::kids, LT, tree::op, op, simplify(), tree::sym, tree::type, tree::u, and tree::v.
Referenced by forstmt().
static void forstmt (int lab, Swtch swp, int lev) [static]
References branch(), conditional(), definelab(), definept(), expect(), expr0(), findlabel(), foldcond(), FUNC, gettok(), ID, kind, NULL, refinc, src, statement(), t, test(), texpr(), and walk().
Referenced by statement().
static void ifstmt (int lab, int loop, Swtch swp, int lev) [static]
References branch(), conditional(), definelab(), definept(), expect(), findlabel(), gettok(), NULL, refinc, statement(), t, and walk().
Referenced by statement().
Node jump (int lab)
References findlabel(), newnode(), NULL, symbol::ref, ttob(), V, and voidptype.
Referenced by branch(), and listnodes().
static Symbol localaddr (Tree p) [static]
References ASGN, CALL, COND, tree::kids, NULL, tree::op, RIGHT, tree::sym, and tree::u.
Referenced by retcode().
int reachable (int kind)
References cp, if(), code::Jump, code::kind, code::Label, code::prev, code::Start, and code::Switch.
Referenced by code(), compound(), and definept().
void retcode (Tree p)
References addlocal(), apply(), ASGN, asgn(), asgntree, assign(), B, CALL, cast(), cfunc, symbol::computed, error(), events, freturn(), symbol::generated, genident(), idtree(), iscallb(), isfloat, isptr, tree::kids, level, localaddr(), mkop, symbol::name, NULL, PARAM, pointer(), promote(), Events::returns, retv, RIGHT, rvalue(), symbol::scope, tree(), symbol::type, tree::type, walk(), and warning().
Referenced by funcdefn(), jpeg_consume_input(), jpeg_read_header(), LOCAL(), and statement().
void statement (int loop, Swtch swp, int lev)
References Aflag, branch(), caselabel(), cast(), cfunc, compound(), constexpr(), deallocate(), definelab(), definept(), swtch::deflab, dostmt(), error(), expect(), expr(), expr0(), extend, symbol::f, findlabel(), forstmt(), freturn(), FUNC, genlabel(), getchr(), gettok(), glevel, value::i, ID, ifstmt(), install(), isint, kind, symbol::l, swtch::lab, LABELS, listnodes(), lookup(), needconst, nodecount, NULL, tree::op, type::op, refinc, retcode(), symbol::scope, skipto(), symbol::src, src, statement(), STMT, stmtlabel(), swstmt(), swtch::sym, t, test(), symbol::type, tree::type, value::u, symbol::u, tree::u, use(), tree::v, voidtype, walk(), warning(), and whilestmt().
Referenced by compound(), dostmt(), forstmt(), ifstmt(), statement(), swstmt(), and whilestmt().
static void stmtlabel (void) [static]
References symbol::defined, definelab(), error(), expect(), FUNC, genlabel(), gettok(), install(), symbol::l, LABELS, lookup(), symbol::name, NULL, symbol::scope, symbol::src, src, t, and symbol::u.
Referenced by statement().
void swcode (Swtch swp, int b[], int lb, int ub)
References ADD, array(), branch(), cast(), cmp(), cnsttree(), code, definelab(), swtch::deflab, interface::defsymbol, EQ, genident(), genlabel(), GLOBAL, GT, idtree(), IR, isunsigned, symbol::l, swtch::labels, LT, NULL, optree, pointer(), rvalue(), signedint(), type::size, SUB, swcode(), code::swtch, swtch::sym, table, tree(), symbol::type, tree::type, code::u, symbol::u, unsignedlong, unsignedptr, swtch::values, voidptype, voidtype, walk(), and warning().
void swgen (Swtch swp)
References buckets, den, density, FUNC, n, swtch::ncases, newarray(), swcode(), and swtch::values.
Referenced by swstmt().
static void swstmt (int loop, int lab, int lev) [static]
References addlocal(), asgn(), branch(), cast(), code, codelist, definelab(), definept(), swtch::deflab, error(), expect(), expr(), findlabel(), FUNC, genident(), gettok(), head, inttype, isaddrop, isint, isvolatile, tree::kids, swtch::lab, swtch::labels, level, swtch::ncases, newarray(), code::next, NULL, tree::op, code::prev, promote(), refinc, retype(), swtch::size, statement(), swgen(), SWSIZE, swtch::sym, tree::sym, t, tail, symbol::type, tree::type, tree::u, swtch::values, walk(), and warning().
Referenced by statement().
static void whilestmt (int lab, Swtch swp, int lev) [static]
References branch(), conditional(), definelab(), definept(), expect(), findlabel(), FUNC, gettok(), NULL, refinc, src, statement(), t, texpr(), and walk().
Referenced by statement().
Variable Documentation
struct code codehead = { Start }
Referenced by emitcode(), funcdefn(), and gencode().
Code codelist = &codehead
Referenced by code(), funcdefn(), gencode(), and swstmt().
float density = 0.5
Referenced by main_init(), and swgen().
Table stmtlabs
Referenced by funcdefn().