ioquake3: ea_export_s Struct Reference
ea_export_s Struct Reference
#include <botlib.h>
Data Fields
void(* EA_Command)(int client, char *command)
void(* EA_Say)(int client, char *str)
void(* EA_SayTeam)(int client, char *str)
void(* EA_Action)(int client, int action)
void(* EA_Gesture)(int client)
void(* EA_Talk)(int client)
void(* EA_Attack)(int client)
void(* EA_Use)(int client)
void(* EA_Respawn)(int client)
void(* EA_MoveUp)(int client)
void(* EA_MoveDown)(int client)
void(* EA_MoveForward)(int client)
void(* EA_MoveBack)(int client)
void(* EA_MoveLeft)(int client)
void(* EA_MoveRight)(int client)
void(* EA_Crouch)(int client)
void(* EA_SelectWeapon)(int client, int weapon)
void(* EA_Jump)(int client)
void(* EA_DelayedJump)(int client)
void(* EA_Move)(int client, vec3_t dir, float speed)
void(* EA_View)(int client, vec3_t viewangles)
void(* EA_EndRegular)(int client, float thinktime)
void(* EA_GetInput)(int client, float thinktime, bot_input_t *input)
void(* EA_ResetInput)(int client)
Field Documentation
void(* ea_export_s::EA_Action)(int client, int action)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Attack)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Command)(int client, char *command)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Crouch)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_DelayedJump)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_EndRegular)(int client, float thinktime)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Gesture)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_GetInput)(int client, float thinktime, bot_input_t *input)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Jump)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Move)(int client, vec3_t dir, float speed)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_MoveBack)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_MoveDown)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_MoveForward)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_MoveLeft)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_MoveRight)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_MoveUp)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_ResetInput)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Respawn)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Say)(int client, char *str)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_SayTeam)(int client, char *str)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_SelectWeapon)(int client, int weapon)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Talk)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_Use)(int client)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
void(* ea_export_s::EA_View)(int client, vec3_t viewangles)
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
The documentation for this struct was generated from the following file:
code/botlib/botlib.h