ioquake3: botlib_import_s Struct Reference
botlib_import_s Struct Reference
#include <botlib.h>
Public Member Functions
void (QDECL *Print)(int type
char __attribute__ ((format(printf, 2, 3)))
Data Fields
char * fmt
void(* Trace)(bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
void(* EntityTrace)(bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int entnum, int contentmask)
int(* PointContents)(vec3_t point)
int(* inPVS)(vec3_t p1, vec3_t p2)
char *(* BSPEntityData)(void)
void(* BSPModelMinsMaxsOrigin)(int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
void(* BotClientCommand)(int client, char *command)
void *(* GetMemory)(int size)
void(* FreeMemory)(void *ptr)
int(* AvailableMemory)(void)
void *(* HunkAlloc)(int size)
int(* FS_FOpenFile)(const char *qpath, fileHandle_t *file, fsMode_t mode)
int(* FS_Read)(void *buffer, int len, fileHandle_t f)
int(* FS_Write)(const void *buffer, int len, fileHandle_t f)
void(* FS_FCloseFile)(fileHandle_t f)
int(* FS_Seek)(fileHandle_t f, long offset, int origin)
int(* DebugLineCreate)(void)
void(* DebugLineDelete)(int line)
void(* DebugLineShow)(int line, vec3_t start, vec3_t end, int color)
int(* DebugPolygonCreate)(int color, int numPoints, vec3_t *points)
void(* DebugPolygonDelete)(int id)
Member Function Documentation
char botlib_import_s::__attribute__ ((format(printf, 2, 3)))
botlib_import_s::void (QDECL * Print)
Field Documentation
int(* botlib_import_s::AvailableMemory)(void)
Referenced by AvailableMemory(), and SV_BotInitBotLib().
void(* botlib_import_s::BotClientCommand)(int client, char *command)
Referenced by EA_Command(), EA_DropInv(), EA_DropItem(), EA_Say(), EA_SayTeam(), EA_Tell(), EA_UseInv(), EA_UseItem(), and SV_BotInitBotLib().
char*(* botlib_import_s::BSPEntityData)(void)
Referenced by AAS_LoadBSPFile(), and SV_BotInitBotLib().
void(* botlib_import_s::BSPModelMinsMaxsOrigin)(int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
Referenced by AAS_BSPModelMinsMaxsOrigin(), and SV_BotInitBotLib().
int(* botlib_import_s::DebugLineCreate)(void)
Referenced by AAS_DebugLine(), AAS_DrawPermanentCross(), AAS_DrawPlaneCross(), AAS_PermanentLine(), AAS_ShowArea(), AAS_ShowBoundingBox(), BotExportTest(), BotTravel_Grapple(), and SV_BotInitBotLib().
void(* botlib_import_s::DebugLineDelete)(int line)
Referenced by AAS_ClearShownDebugLines(), and SV_BotInitBotLib().
void(* botlib_import_s::DebugLineShow)(int line, vec3_t start, vec3_t end, int color)
Referenced by AAS_DebugLine(), AAS_DrawPermanentCross(), AAS_DrawPlaneCross(), AAS_PermanentLine(), AAS_ShowArea(), AAS_ShowBoundingBox(), BotExportTest(), BotTravel_Grapple(), and SV_BotInitBotLib().
int(* botlib_import_s::DebugPolygonCreate)(int color, int numPoints, vec3_t *points)
Referenced by AAS_ShowPolygon(), and SV_BotInitBotLib().
void(* botlib_import_s::DebugPolygonDelete)(int id)
Referenced by AAS_ClearShownPolygons(), and SV_BotInitBotLib().
void(* botlib_import_s::EntityTrace)(bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int entnum, int contentmask)
Referenced by AAS_EntityCollision(), and SV_BotInitBotLib().
char* botlib_import_s::fmt
void(* botlib_import_s::FreeMemory)(void *ptr)
Referenced by FreeMemory(), and SV_BotInitBotLib().
void(* botlib_import_s::FS_FCloseFile)(fileHandle_t f)
Referenced by AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_ReadRouteCache(), AAS_WriteAASFile(), AAS_WriteRouteCache(), LoadScriptFile(), and SV_BotInitBotLib().
int(* botlib_import_s::FS_FOpenFile)(const char *qpath, fileHandle_t *file, fsMode_t mode)
Referenced by AAS_LoadAASFile(), AAS_ReadRouteCache(), AAS_WriteAASFile(), AAS_WriteRouteCache(), LoadScriptFile(), and SV_BotInitBotLib().
int(* botlib_import_s::FS_Read)(void *buffer, int len, fileHandle_t f)
Referenced by AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_ReadCache(), AAS_ReadRouteCache(), LoadScriptFile(), and SV_BotInitBotLib().
int(* botlib_import_s::FS_Seek)(fileHandle_t f, long offset, int origin)
Referenced by AAS_LoadAASLump(), AAS_WriteAASFile(), and SV_BotInitBotLib().
int(* botlib_import_s::FS_Write)(const void *buffer, int len, fileHandle_t f)
Referenced by AAS_WriteAASFile(), AAS_WriteAASLump(), AAS_WriteRouteCache(), and SV_BotInitBotLib().
void*(* botlib_import_s::GetMemory)(int size)
Referenced by GetMemory(), and SV_BotInitBotLib().
void*(* botlib_import_s::HunkAlloc)(int size)
Referenced by GetHunkMemory(), and SV_BotInitBotLib().
int(* botlib_import_s::inPVS)(vec3_t p1, vec3_t p2)
Referenced by AAS_inPVS(), and SV_BotInitBotLib().
int(* botlib_import_s::PointContents)(vec3_t point)
Referenced by AAS_PointContents(), and SV_BotInitBotLib().
void(* botlib_import_s::Trace)(bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
Referenced by AAS_Trace(), and SV_BotInitBotLib().
The documentation for this struct was generated from the following file:
code/botlib/botlib.h