ioquake3: aas_export_s Struct Reference
aas_export_s Struct Reference
#include <botlib.h>
Data Fields
void(* AAS_EntityInfo)(int entnum, struct aas_entityinfo_s *info)
int(* AAS_Initialized)(void)
void(* AAS_PresenceTypeBoundingBox)(int presencetype, vec3_t mins, vec3_t maxs)
float(* AAS_Time)(void)
int(* AAS_PointAreaNum)(vec3_t point)
int(* AAS_PointReachabilityAreaIndex)(vec3_t point)
int(* AAS_TraceAreas)(vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
int(* AAS_BBoxAreas)(vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
int(* AAS_AreaInfo)(int areanum, struct aas_areainfo_s *info)
int(* AAS_PointContents)(vec3_t point)
int(* AAS_NextBSPEntity)(int ent)
int(* AAS_ValueForBSPEpairKey)(int ent, char *key, char *value, int size)
int(* AAS_VectorForBSPEpairKey)(int ent, char *key, vec3_t v)
int(* AAS_FloatForBSPEpairKey)(int ent, char *key, float *value)
int(* AAS_IntForBSPEpairKey)(int ent, char *key, int *value)
int(* AAS_AreaReachability)(int areanum)
int(* AAS_AreaTravelTimeToGoalArea)(int areanum, vec3_t origin, int goalareanum, int travelflags)
int(* AAS_EnableRoutingArea)(int areanum, int enable)
int(* AAS_PredictRoute)(struct aas_predictroute_s *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
int(* AAS_AlternativeRouteGoals)(vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, struct aas_altroutegoal_s *altroutegoals, int maxaltroutegoals, int type)
int(* AAS_Swimming)(vec3_t origin)
int(* AAS_PredictClientMovement)(struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Field Documentation
int(* aas_export_s::AAS_AlternativeRouteGoals)(vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, struct aas_altroutegoal_s *altroutegoals, int maxaltroutegoals, int type)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_AreaInfo)(int areanum, struct aas_areainfo_s *info)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_AreaReachability)(int areanum)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_AreaTravelTimeToGoalArea)(int areanum, vec3_t origin, int goalareanum, int travelflags)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_BBoxAreas)(vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_EnableRoutingArea)(int areanum, int enable)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
void(* aas_export_s::AAS_EntityInfo)(int entnum, struct aas_entityinfo_s *info)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_FloatForBSPEpairKey)(int ent, char *key, float *value)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_Initialized)(void)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_IntForBSPEpairKey)(int ent, char *key, int *value)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_NextBSPEntity)(int ent)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_PointAreaNum)(vec3_t point)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_PointContents)(vec3_t point)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_PointReachabilityAreaIndex)(vec3_t point)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_PredictClientMovement)(struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_PredictRoute)(struct aas_predictroute_s *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
void(* aas_export_s::AAS_PresenceTypeBoundingBox)(int presencetype, vec3_t mins, vec3_t maxs)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_Swimming)(vec3_t origin)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
float(* aas_export_s::AAS_Time)(void)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_TraceAreas)(vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_ValueForBSPEpairKey)(int ent, char *key, char *value, int size)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
int(* aas_export_s::AAS_VectorForBSPEpairKey)(int ent, char *key, vec3_t v)
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
The documentation for this struct was generated from the following file:
code/botlib/botlib.h