ioquake3: displayContextDef_t Struct Reference
displayContextDef_t Struct Reference
#include <ui_shared.h>
Data Fields
qhandle_t(* registerShaderNoMip)(const char *p)
void(* setColor)(const vec4_t v)
void(* drawHandlePic)(float x, float y, float w, float h, qhandle_t asset)
void(* drawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void(* drawText)(float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
int(* textWidth)(const char *text, float scale, int limit)
int(* textHeight)(const char *text, float scale, int limit)
qhandle_t(* registerModel)(const char *p)
void(* modelBounds)(qhandle_t model, vec3_t min, vec3_t max)
void(* fillRect)(float x, float y, float w, float h, const vec4_t color)
void(* drawRect)(float x, float y, float w, float h, float size, const vec4_t color)
void(* drawSides)(float x, float y, float w, float h, float size)
void(* drawTopBottom)(float x, float y, float w, float h, float size)
void(* clearScene)(void)
void(* addRefEntityToScene)(const refEntity_t *re)
void(* renderScene)(const refdef_t *fd)
void(* registerFont)(const char *pFontname, int pointSize, fontInfo_t *font)
void(* ownerDrawItem)(float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, float scale, vec4_t color, qhandle_t shader, int textStyle)
float(* getValue)(int ownerDraw)
qboolean(* ownerDrawVisible)(int flags)
void(* runScript)(char **p)
void(* getTeamColor)(vec4_t *color)
void(* getCVarString)(const char *cvar, char *buffer, int bufsize)
float(* getCVarValue)(const char *cvar)
void(* setCVar)(const char *cvar, const char *value)
void(* drawTextWithCursor)(float x, float y, float scale, vec4_t color, const char *text, int cursorPos, char cursor, int limit, int style)
void(* setOverstrikeMode)(qboolean b)
qboolean(* getOverstrikeMode)(void)
void(* startLocalSound)(sfxHandle_t sfx, int channelNum)
qboolean(* ownerDrawHandleKey)(int ownerDraw, int flags, float *special, int key)
int(* feederCount)(float feederID)
const char *(* feederItemText)(float feederID, int index, int column, qhandle_t *handle)
qhandle_t(* feederItemImage)(float feederID, int index)
void(* feederSelection)(float feederID, int index)
void(* keynumToStringBuf)(int keynum, char *buf, int buflen)
void(* getBindingBuf)(int keynum, char *buf, int buflen)
void(* setBinding)(int keynum, const char *binding)
void(* executeText)(int exec_when, const char *text)
void(* Error)(int level, const char *error,...) __attribute__((noreturn
void(* format)(printf, 2, 3)))
void(* Print)(const char *msg,...) __attribute__((format(printf
void(*) void(* Pause)(qboolean b)
int(* ownerDrawWidth)(int ownerDraw, float scale)
sfxHandle_t(* registerSound)(const char *name, qboolean compressed)
void(* startBackgroundTrack)(const char *intro, const char *loop)
void(* stopBackgroundTrack)(void)
int(* playCinematic)(const char *name, float x, float y, float w, float h)
void(* stopCinematic)(int handle)
void(* drawCinematic)(int handle, float x, float y, float w, float h)
void(* runCinematicFrame)(int handle)
float yscale
float xscale
float bias
int realTime
int frameTime
int cursorx
int cursory
qboolean debug
cachedAssets_t Assets
glconfig_t glconfig
qhandle_t whiteShader
qhandle_t gradientImage
qhandle_t cursor
float FPS
Field Documentation
void(* displayContextDef_t::addRefEntityToScene)(const refEntity_t *re)
Referenced by _UI_Init(), and Item_Model_Paint().
cachedAssets_t displayContextDef_t::Assets
Referenced by _UI_Refresh(), Asset_Parse(), AssetCache(), CG_Text_Paint_Limit(), Font_Report(), GradientBar_Paint(), Item_ListBox_Paint(), Item_SetFocus(), Item_Slider_Paint(), Menu_Init(), MenuParse_font(), Script_SetFocus(), Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), Text_Width(), UI_DrawCrosshair(), and UI_DrawEffects().
float displayContextDef_t::bias
Referenced by _UI_Init(), and UI_AdjustFrom640().
void(* displayContextDef_t::clearScene)(void)
Referenced by _UI_Init(), and Item_Model_Paint().
qhandle_t displayContextDef_t::cursor
Referenced by _UI_Init().
int displayContextDef_t::cursorx
Referenced by _UI_MouseEvent(), _UI_Refresh(), Item_Bind_HandleKey(), Item_ListBox_HandleKey(), Item_ListBox_ThumbDrawPosition(), Item_Multi_HandleKey(), Item_Slider_HandleKey(), Item_StartCapture(), Item_YesNo_HandleKey(), Menu_HandleKey(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), Menus_HandleOOBClick(), Scroll_ListBox_ThumbFunc(), Scroll_Slider_ThumbFunc(), UI_CursorInRect(), and vmMain().
int displayContextDef_t::cursory
Referenced by _UI_MouseEvent(), _UI_Refresh(), Item_Bind_HandleKey(), Item_ListBox_HandleKey(), Item_ListBox_ThumbDrawPosition(), Item_Multi_HandleKey(), Item_Slider_HandleKey(), Item_StartCapture(), Item_YesNo_HandleKey(), Menu_HandleKey(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), Menus_HandleOOBClick(), Scroll_ListBox_ThumbFunc(), UI_CursorInRect(), and vmMain().
qboolean displayContextDef_t::debug
Referenced by _UI_Refresh().
void(* displayContextDef_t::drawCinematic)(int handle, float x, float y, float w, float h)
Referenced by _UI_Init(), and Window_Paint().
void(* displayContextDef_t::drawHandlePic)(float x, float y, float w, float h, qhandle_t asset)
Referenced by _UI_Init(), GradientBar_Paint(), Item_Image_Paint(), Item_ListBox_Paint(), Item_Slider_Paint(), Menu_Paint(), and Window_Paint().
void(* displayContextDef_t::drawRect)(float x, float y, float w, float h, float size, const vec4_t color)
Referenced by _UI_Init(), Item_ListBox_Paint(), Item_Paint(), Menu_Paint(), and Window_Paint().
void(* displayContextDef_t::drawSides)(float x, float y, float w, float h, float size)
Referenced by _UI_Init(), and Window_Paint().
void(* displayContextDef_t::drawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Referenced by _UI_Init().
void(* displayContextDef_t::drawText)(float x, float y, float scale, vec4_t color, const char *text, float adjust, int limit, int style)
Referenced by _UI_Init(), Item_Bind_Paint(), Item_ListBox_Paint(), Item_Multi_Paint(), Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), Item_Text_Wrapped_Paint(), Item_TextField_Paint(), Item_YesNo_Paint(), and Menu_PaintAll().
void(* displayContextDef_t::drawTextWithCursor)(float x, float y, float scale, vec4_t color, const char *text, int cursorPos, char cursor, int limit, int style)
Referenced by _UI_Init(), and Item_TextField_Paint().
void(* displayContextDef_t::drawTopBottom)(float x, float y, float w, float h, float size)
Referenced by _UI_Init(), and Window_Paint().
void(* displayContextDef_t::Error)(int level, const char *error,...) __attribute__((noreturn
Referenced by _UI_Init().
void(* displayContextDef_t::executeText)(int exec_when, const char *text)
Referenced by _UI_Init(), Controls_SetConfig(), Menu_HandleKey(), and Script_Exec().
int(* displayContextDef_t::feederCount)(float feederID)
Referenced by _UI_Init(), Item_ListBox_HandleKey(), Item_ListBox_MaxScroll(), and Item_ListBox_Paint().
qhandle_t(* displayContextDef_t::feederItemImage)(float feederID, int index)
Referenced by _UI_Init(), and Item_ListBox_Paint().
const char*(* displayContextDef_t::feederItemText)(float feederID, int index, int column, qhandle_t *handle)
Referenced by _UI_Init(), and Item_ListBox_Paint().
void(* displayContextDef_t::feederSelection)(float feederID, int index)
Referenced by _UI_Init(), Item_ListBox_HandleKey(), and Menu_SetFeederSelection().
void(* displayContextDef_t::fillRect)(float x, float y, float w, float h, const vec4_t color)
Referenced by _UI_Init(), Item_ListBox_Paint(), and Window_Paint().
void(* displayContextDef_t::format)(printf, 2, 3)))
float displayContextDef_t::FPS
Referenced by _UI_Refresh(), and Menu_PaintAll().
int displayContextDef_t::frameTime
Referenced by _UI_Refresh(), UI_ConsoleCommand(), UI_PlayerAnimation(), and UI_SwingAngles().
void(* displayContextDef_t::getBindingBuf)(int keynum, char *buf, int buflen)
Referenced by _UI_Init(), Controls_GetKeyAssignment(), and String_Init().
void(* displayContextDef_t::getCVarString)(const char *cvar, char *buffer, int bufsize)
Referenced by _UI_Init(), Item_EnableShowViaCvar(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_SetTextExtents(), Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), Item_Text_Wrapped_Paint(), Item_TextField_HandleKey(), and Item_TextField_Paint().
float(* displayContextDef_t::getCVarValue)(const char *cvar)
Referenced by _UI_Init(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_Slider_ThumbPosition(), Item_YesNo_HandleKey(), Item_YesNo_Paint(), Menu_HandleKey(), and Script_ConditionalOpen().
qboolean(* displayContextDef_t::getOverstrikeMode)(void)
Referenced by _UI_Init(), Item_TextField_HandleKey(), and Item_TextField_Paint().
void(* displayContextDef_t::getTeamColor)(vec4_t *color)
Referenced by _UI_Init(), Script_SetTeamColor(), and Window_Paint().
float(* displayContextDef_t::getValue)(int ownerDraw)
Referenced by _UI_Init(), and Item_OwnerDraw_Paint().
glconfig_t displayContextDef_t::glconfig
Referenced by _UI_Init(), and UI_DrawGLInfo().
qhandle_t displayContextDef_t::gradientImage
void(* displayContextDef_t::keynumToStringBuf)(int keynum, char *buf, int buflen)
Referenced by _UI_Init(), and BindingFromName().
void(* displayContextDef_t::modelBounds)(qhandle_t model, vec3_t min, vec3_t max)
Referenced by _UI_Init(), and Item_Model_Paint().
qboolean(* displayContextDef_t::ownerDrawHandleKey)(int ownerDraw, int flags, float *special, int key)
Referenced by _UI_Init(), and Item_OwnerDraw_HandleKey().
void(* displayContextDef_t::ownerDrawItem)(float x, float y, float w, float h, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, float scale, vec4_t color, qhandle_t shader, int textStyle)
Referenced by _UI_Init(), and Item_OwnerDraw_Paint().
qboolean(* displayContextDef_t::ownerDrawVisible)(int flags)
Referenced by _UI_Init(), Item_Paint(), and Menu_Paint().
int(* displayContextDef_t::ownerDrawWidth)(int ownerDraw, float scale)
Referenced by _UI_Init(), and Item_SetTextExtents().
void(*) void(* displayContextDef_t::Pause)(qboolean b)
Referenced by _UI_Init(), and Menus_HandleOOBClick().
int(* displayContextDef_t::playCinematic)(const char *name, float x, float y, float w, float h)
Referenced by _UI_Init(), Window_CacheContents(), and Window_Paint().
void(* displayContextDef_t::Print)(const char *msg,...) __attribute__((format(printf
Referenced by _UI_Init(), Item_Slider_HandleKey(), and UI_Alloc().
int displayContextDef_t::realTime
Referenced by _UI_Refresh(), Fade(), Item_Bind_Paint(), Item_ListBox_HandleKey(), Item_Model_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Paint(), Item_Slider_Paint(), Item_StartCapture(), Item_TextColor(), Item_TextField_Paint(), Item_YesNo_Paint(), Scroll_ListBox_AutoFunc(), Scroll_ListBox_ThumbFunc(), Text_PaintWithCursor(), UI_BuildFindPlayerList(), UI_BuildServerDisplayList(), UI_BuildServerStatus(), UI_CalcPostGameStats(), UI_ConsoleCommand(), UI_DisplayDownloadInfo(), UI_DoServerRefresh(), UI_DrawOpponent(), UI_DrawPlayerModel(), UI_DrawSelectedPlayer(), UI_DrawServerMOTD(), UI_DrawServerRefreshDate(), UI_FeederCount(), UI_FeederItemText(), UI_OwnerDrawVisible(), UI_StartServerRefresh(), and UI_UpdatePendingPings().
void(* displayContextDef_t::registerFont)(const char *pFontname, int pointSize, fontInfo_t *font)
Referenced by _UI_Init(), and MenuParse_font().
qhandle_t(* displayContextDef_t::registerModel)(const char *p)
Referenced by _UI_Init(), and ItemParse_asset_model().
qhandle_t(* displayContextDef_t::registerShaderNoMip)(const char *p)
Referenced by _UI_Init(), ItemParse_asset_shader(), ItemParse_background(), MenuParse_background(), and Script_SetBackground().
sfxHandle_t(* displayContextDef_t::registerSound)(const char *name, qboolean compressed)
Referenced by _UI_Init(), ItemParse_focusSound(), Menu_CacheContents(), and Script_Play().
void(* displayContextDef_t::renderScene)(const refdef_t *fd)
Referenced by _UI_Init(), and Item_Model_Paint().
void(* displayContextDef_t::runCinematicFrame)(int handle)
Referenced by _UI_Init(), and Window_Paint().
void(* displayContextDef_t::runScript)(char **p)
Referenced by _UI_Init(), and Item_RunScript().
void(* displayContextDef_t::setBinding)(int keynum, const char *binding)
Referenced by _UI_Init(), Controls_SetConfig(), and Item_Bind_HandleKey().
void(* displayContextDef_t::setColor)(const vec4_t v)
Referenced by _UI_Init(), GradientBar_Paint(), Item_Slider_Paint(), and Window_Paint().
void(* displayContextDef_t::setCVar)(const char *cvar, const char *value)
Referenced by _UI_Init(), Item_Multi_HandleKey(), Item_Slider_HandleKey(), Item_TextField_HandleKey(), Item_YesNo_HandleKey(), Script_SetCvar(), Script_SetPlayerHead(), Script_SetPlayerModel(), and Scroll_Slider_ThumbFunc().
void(* displayContextDef_t::setOverstrikeMode)(qboolean b)
Referenced by _UI_Init(), and Item_TextField_HandleKey().
void(* displayContextDef_t::startBackgroundTrack)(const char *intro, const char *loop)
Referenced by _UI_Init(), Menus_Activate(), and Script_playLooped().
void(* displayContextDef_t::startLocalSound)(sfxHandle_t sfx, int channelNum)
Referenced by _UI_Init(), Item_SetFocus(), Script_Play(), and Script_SetFocus().
void(* displayContextDef_t::stopBackgroundTrack)(void)
Referenced by _UI_Init(), and Script_playLooped().
void(* displayContextDef_t::stopCinematic)(int handle)
Referenced by _UI_Init(), Menu_CloseCinematics(), Menu_ShowItemByName(), Window_CacheContents(), and Window_CloseCinematic().
int(* displayContextDef_t::textHeight)(const char *text, float scale, int limit)
Referenced by _UI_Init(), and Item_SetTextExtents().
int(* displayContextDef_t::textWidth)(const char *text, float scale, int limit)
Referenced by _UI_Init(), Item_SetTextExtents(), and Item_Text_AutoWrapped_Paint().
qhandle_t displayContextDef_t::whiteShader
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), _UI_Init(), UI_DrawSides(), UI_DrawTopBottom(), and UI_FillRect().
float displayContextDef_t::xscale
Referenced by _UI_DrawSides(), _UI_Init(), AdjustFrom640(), and UI_AdjustFrom640().
float displayContextDef_t::yscale
Referenced by _UI_DrawTopBottom(), _UI_Init(), AdjustFrom640(), and UI_AdjustFrom640().
The documentation for this struct was generated from the following file:
code/ui/ui_shared.h