ioquake3: interface Struct Reference
interface Struct Reference
#include <c.h>
Data Fields
Metrics charmetric
Metrics shortmetric
Metrics intmetric
Metrics longmetric
Metrics longlongmetric
Metrics floatmetric
Metrics doublemetric
Metrics longdoublemetric
Metrics ptrmetric
Metrics structmetric
unsigned little_endian:1
unsigned mulops_calls:1
unsigned wants_callb:1
unsigned wants_argb:1
unsigned left_to_right:1
unsigned wants_dag:1
unsigned unsigned_char:1
void(* address)(Symbol p, Symbol q, long n)
void(* blockbeg)(Env *)
void(* blockend)(Env *)
void(* defaddress)(Symbol)
void(* defconst)(int suffix, int size, Value v)
void(* defstring)(int n, char *s)
void(* defsymbol)(Symbol)
void(* emit)(Node)
void(* export)(Symbol)
void(* function)(Symbol, Symbol[], Symbol[], int)
Node(* gen)(Node)
void(* global)(Symbol)
void(* import)(Symbol)
void(* local)(Symbol)
void(* progbeg)(int argc, char *argv[])
void(* progend)(void)
void(* segment)(int)
void(* space)(int)
void(* stabblock)(int, int, Symbol *)
void(* stabend)(Coordinate *, Symbol, Coordinate **, Symbol *, Symbol *)
void(* stabfend)(Symbol, int)
void(* stabinit)(char *, int, char *[])
void(* stabline)(Coordinate *)
void(* stabsym)(Symbol)
void(* stabtype)(Symbol)
Xinterface x
Field Documentation
void(* interface::address)(Symbol p, Symbol q, long n)
Referenced by addrtree(), and gencode().
void(* interface::blockbeg)(Env *)
Referenced by gencode().
void(* interface::blockend)(Env *)
Referenced by gencode().
Metrics interface::charmetric
void(* interface::defaddress)(Symbol)
Referenced by defpointer(), emitcode(), and genconst().
void(* interface::defconst)(int suffix, int size, Value v)
Referenced by bbcall(), bbfunc(), bbvars(), defpointer(), doconst(), genconst(), initfields(), and initializer().
void(* interface::defstring)(int n, char *s)
Referenced by doconst(), initchar(), and initializer().
void(* interface::defsymbol)(Symbol)
Referenced by address(), constant(), dclglobal(), dcllocal(), emitSymbol(), emitSymRef(), findlabel(), function(), genident(), local(), main_init(), mksymbol(), primary(), and swcode().
Metrics interface::doublemetric
void(* interface::emit)(Node)
Referenced by emitcode().
void(* interface::export)(Symbol)
Referenced by defglobal(), and funcdefn().
Metrics interface::floatmetric
void(* interface::function)(Symbol, Symbol[], Symbol[], int)
Referenced by funcdefn().
Node(* interface::gen)(Node)
Referenced by gencode().
void(* interface::global)(Symbol)
Referenced by defglobal().
void(* interface::import)(Symbol)
Referenced by doextern(), and doglobal().
Metrics interface::intmetric
unsigned interface::left_to_right
Referenced by listnodes(), and main_init().
unsigned interface::little_endian
Referenced by bbcall(), bbfunc(), bbincr(), initfields(), and main_init().
void(* interface::local)(Symbol)
Referenced by gencode(), newtemp(), and prune().
Metrics interface::longdoublemetric
Metrics interface::longlongmetric
Metrics interface::longmetric
unsigned interface::mulops_calls
Referenced by hascall(), listnodes(), and main_init().
void(* interface::progbeg)(int argc, char *argv[])
Referenced by main().
void(* interface::progend)(void)
Referenced by main().
Metrics interface::ptrmetric
Referenced by genreload(), genspill(), ptr(), and type_init().
void(* interface::segment)(int)
Referenced by function(), and swtoseg().
Metrics interface::shortmetric
void(* interface::space)(int)
Referenced by bbvars(), dcllocal(), doglobal(), initializer(), initstruct(), and tracecall().
void(* interface::stabblock)(int, int, Symbol *)
Referenced by emitcode().
void(* interface::stabend)(Coordinate *, Symbol, Coordinate **, Symbol *, Symbol *)
Referenced by main(), main_init(), and stabend().
void(* interface::stabfend)(Symbol, int)
Referenced by funcdefn().
void(* interface::stabinit)(char *, int, char *[])
Referenced by main().
void(* interface::stabline)(Coordinate *)
Referenced by emitcode(), main_init(), and stabline().
void(* interface::stabsym)(Symbol)
Referenced by dclglobal(), doglobal(), emitcode(), funcdefn(), gencode(), and typestab().
void(* interface::stabtype)(Symbol)
Referenced by typestab().
Metrics interface::structmetric
unsigned interface::unsigned_char
Referenced by type_init().
unsigned interface::wants_argb
Referenced by call(), funcdefn(), idtree(), and main_init().
unsigned interface::wants_callb
Referenced by compound(), funcdefn(), listnodes(), and main_init().
unsigned interface::wants_dag
Referenced by gen(), gencode(), main_init(), and walk().
Xinterface interface::x
Referenced by blkcopy(), blkunroll(), dumpcover(), dumprule(), emitasm(), gen(), genspill(), getrule(), prelabel(), ralloc(), reduce(), reprune(), and rewrite().
The documentation for this struct was generated from the following file:
code/tools/lcc/src/c.h