ioquake3: ai_export_s Struct Reference
ai_export_s Struct Reference
#include <botlib.h>
Data Fields
int(* BotLoadCharacter)(char *charfile, float skill)
void(* BotFreeCharacter)(int character)
float(* Characteristic_Float)(int character, int index)
float(* Characteristic_BFloat)(int character, int index, float min, float max)
int(* Characteristic_Integer)(int character, int index)
int(* Characteristic_BInteger)(int character, int index, int min, int max)
void(* Characteristic_String)(int character, int index, char *buf, int size)
int(* BotAllocChatState)(void)
void(* BotFreeChatState)(int handle)
void(* BotQueueConsoleMessage)(int chatstate, int type, char *message)
void(* BotRemoveConsoleMessage)(int chatstate, int handle)
int(* BotNextConsoleMessage)(int chatstate, struct bot_consolemessage_s *cm)
int(* BotNumConsoleMessages)(int chatstate)
void(* BotInitialChat)(int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int(* BotNumInitialChats)(int chatstate, char *type)
int(* BotReplyChat)(int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int(* BotChatLength)(int chatstate)
void(* BotEnterChat)(int chatstate, int client, int sendto)
void(* BotGetChatMessage)(int chatstate, char *buf, int size)
int(* StringContains)(char *str1, char *str2, int casesensitive)
int(* BotFindMatch)(char *str, struct bot_match_s *match, unsigned long int context)
void(* BotMatchVariable)(struct bot_match_s *match, int variable, char *buf, int size)
void(* UnifyWhiteSpaces)(char *string)
void(* BotReplaceSynonyms)(char *string, unsigned long int context)
int(* BotLoadChatFile)(int chatstate, char *chatfile, char *chatname)
void(* BotSetChatGender)(int chatstate, int gender)
void(* BotSetChatName)(int chatstate, char *name, int client)
void(* BotResetGoalState)(int goalstate)
void(* BotResetAvoidGoals)(int goalstate)
void(* BotRemoveFromAvoidGoals)(int goalstate, int number)
void(* BotPushGoal)(int goalstate, struct bot_goal_s *goal)
void(* BotPopGoal)(int goalstate)
void(* BotEmptyGoalStack)(int goalstate)
void(* BotDumpAvoidGoals)(int goalstate)
void(* BotDumpGoalStack)(int goalstate)
void(* BotGoalName)(int number, char *name, int size)
int(* BotGetTopGoal)(int goalstate, struct bot_goal_s *goal)
int(* BotGetSecondGoal)(int goalstate, struct bot_goal_s *goal)
int(* BotChooseLTGItem)(int goalstate, vec3_t origin, int *inventory, int travelflags)
int(* BotChooseNBGItem)(int goalstate, vec3_t origin, int *inventory, int travelflags, struct bot_goal_s *ltg, float maxtime)
int(* BotTouchingGoal)(vec3_t origin, struct bot_goal_s *goal)
int(* BotItemGoalInVisButNotVisible)(int viewer, vec3_t eye, vec3_t viewangles, struct bot_goal_s *goal)
int(* BotGetLevelItemGoal)(int index, char *classname, struct bot_goal_s *goal)
int(* BotGetNextCampSpotGoal)(int num, struct bot_goal_s *goal)
int(* BotGetMapLocationGoal)(char *name, struct bot_goal_s *goal)
float(* BotAvoidGoalTime)(int goalstate, int number)
void(* BotSetAvoidGoalTime)(int goalstate, int number, float avoidtime)
void(* BotInitLevelItems)(void)
void(* BotUpdateEntityItems)(void)
int(* BotLoadItemWeights)(int goalstate, char *filename)
void(* BotFreeItemWeights)(int goalstate)
void(* BotInterbreedGoalFuzzyLogic)(int parent1, int parent2, int child)
void(* BotSaveGoalFuzzyLogic)(int goalstate, char *filename)
void(* BotMutateGoalFuzzyLogic)(int goalstate, float range)
int(* BotAllocGoalState)(int client)
void(* BotFreeGoalState)(int handle)
void(* BotResetMoveState)(int movestate)
void(* BotMoveToGoal)(struct bot_moveresult_s *result, int movestate, struct bot_goal_s *goal, int travelflags)
int(* BotMoveInDirection)(int movestate, vec3_t dir, float speed, int type)
void(* BotResetAvoidReach)(int movestate)
void(* BotResetLastAvoidReach)(int movestate)
int(* BotReachabilityArea)(vec3_t origin, int testground)
int(* BotMovementViewTarget)(int movestate, struct bot_goal_s *goal, int travelflags, float lookahead, vec3_t target)
int(* BotPredictVisiblePosition)(vec3_t origin, int areanum, struct bot_goal_s *goal, int travelflags, vec3_t target)
int(* BotAllocMoveState)(void)
void(* BotFreeMoveState)(int handle)
void(* BotInitMoveState)(int handle, struct bot_initmove_s *initmove)
void(* BotAddAvoidSpot)(int movestate, vec3_t origin, float radius, int type)
int(* BotChooseBestFightWeapon)(int weaponstate, int *inventory)
void(* BotGetWeaponInfo)(int weaponstate, int weapon, struct weaponinfo_s *weaponinfo)
int(* BotLoadWeaponWeights)(int weaponstate, char *filename)
int(* BotAllocWeaponState)(void)
void(* BotFreeWeaponState)(int weaponstate)
void(* BotResetWeaponState)(int weaponstate)
int(* GeneticParentsAndChildSelection)(int numranks, float *ranks, int *parent1, int *parent2, int *child)
Field Documentation
void(* ai_export_s::BotAddAvoidSpot)(int movestate, vec3_t origin, float radius, int type)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotAllocChatState)(void)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotAllocGoalState)(int client)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotAllocMoveState)(void)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotAllocWeaponState)(void)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
float(* ai_export_s::BotAvoidGoalTime)(int goalstate, int number)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotChatLength)(int chatstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotChooseBestFightWeapon)(int weaponstate, int *inventory)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotChooseLTGItem)(int goalstate, vec3_t origin, int *inventory, int travelflags)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotChooseNBGItem)(int goalstate, vec3_t origin, int *inventory, int travelflags, struct bot_goal_s *ltg, float maxtime)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotDumpAvoidGoals)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotDumpGoalStack)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotEmptyGoalStack)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotEnterChat)(int chatstate, int client, int sendto)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotFindMatch)(char *str, struct bot_match_s *match, unsigned long int context)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotFreeCharacter)(int character)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotFreeChatState)(int handle)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotFreeGoalState)(int handle)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotFreeItemWeights)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotFreeMoveState)(int handle)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotFreeWeaponState)(int weaponstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotGetChatMessage)(int chatstate, char *buf, int size)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotGetLevelItemGoal)(int index, char *classname, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotGetMapLocationGoal)(char *name, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotGetNextCampSpotGoal)(int num, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotGetSecondGoal)(int goalstate, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotGetTopGoal)(int goalstate, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotGetWeaponInfo)(int weaponstate, int weapon, struct weaponinfo_s *weaponinfo)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotGoalName)(int number, char *name, int size)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotInitialChat)(int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotInitLevelItems)(void)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotInitMoveState)(int handle, struct bot_initmove_s *initmove)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotInterbreedGoalFuzzyLogic)(int parent1, int parent2, int child)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotItemGoalInVisButNotVisible)(int viewer, vec3_t eye, vec3_t viewangles, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotLoadCharacter)(char *charfile, float skill)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotLoadChatFile)(int chatstate, char *chatfile, char *chatname)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotLoadItemWeights)(int goalstate, char *filename)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotLoadWeaponWeights)(int weaponstate, char *filename)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotMatchVariable)(struct bot_match_s *match, int variable, char *buf, int size)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotMoveInDirection)(int movestate, vec3_t dir, float speed, int type)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotMovementViewTarget)(int movestate, struct bot_goal_s *goal, int travelflags, float lookahead, vec3_t target)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotMoveToGoal)(struct bot_moveresult_s *result, int movestate, struct bot_goal_s *goal, int travelflags)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotMutateGoalFuzzyLogic)(int goalstate, float range)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotNextConsoleMessage)(int chatstate, struct bot_consolemessage_s *cm)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotNumConsoleMessages)(int chatstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotNumInitialChats)(int chatstate, char *type)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotPopGoal)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotPredictVisiblePosition)(vec3_t origin, int areanum, struct bot_goal_s *goal, int travelflags, vec3_t target)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotPushGoal)(int goalstate, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotQueueConsoleMessage)(int chatstate, int type, char *message)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotReachabilityArea)(vec3_t origin, int testground)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotRemoveConsoleMessage)(int chatstate, int handle)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotRemoveFromAvoidGoals)(int goalstate, int number)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotReplaceSynonyms)(char *string, unsigned long int context)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotReplyChat)(int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotResetAvoidGoals)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotResetAvoidReach)(int movestate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotResetGoalState)(int goalstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotResetLastAvoidReach)(int movestate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotResetMoveState)(int movestate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotResetWeaponState)(int weaponstate)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotSaveGoalFuzzyLogic)(int goalstate, char *filename)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotSetAvoidGoalTime)(int goalstate, int number, float avoidtime)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotSetChatGender)(int chatstate, int gender)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotSetChatName)(int chatstate, char *name, int client)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::BotTouchingGoal)(vec3_t origin, struct bot_goal_s *goal)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::BotUpdateEntityItems)(void)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
float(* ai_export_s::Characteristic_BFloat)(int character, int index, float min, float max)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::Characteristic_BInteger)(int character, int index, int min, int max)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
float(* ai_export_s::Characteristic_Float)(int character, int index)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::Characteristic_Integer)(int character, int index)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::Characteristic_String)(int character, int index, char *buf, int size)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::GeneticParentsAndChildSelection)(int numranks, float *ranks, int *parent1, int *parent2, int *child)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
int(* ai_export_s::StringContains)(char *str1, char *str2, int casesensitive)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
void(* ai_export_s::UnifyWhiteSpaces)(char *string)
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
The documentation for this struct was generated from the following file:
code/botlib/botlib.h