ioquake3: refexport_t Struct Reference
refexport_t Struct Reference
#include <tr_public.h>
Data Fields
void(* Shutdown)(qboolean destroyWindow)
void(* BeginRegistration)(glconfig_t *config)
qhandle_t(* RegisterModel)(const char *name)
qhandle_t(* RegisterSkin)(const char *name)
qhandle_t(* RegisterShader)(const char *name)
qhandle_t(* RegisterShaderNoMip)(const char *name)
void(* LoadWorld)(const char *name)
void(* SetWorldVisData)(const byte *vis)
void(* EndRegistration)(void)
void(* ClearScene)(void)
void(* AddRefEntityToScene)(const refEntity_t *re)
void(* AddPolyToScene)(qhandle_t hShader, int numVerts, const polyVert_t *verts, int num)
int(* LightForPoint)(vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void(* AddLightToScene)(const vec3_t org, float intensity, float r, float g, float b)
void(* AddAdditiveLightToScene)(const vec3_t org, float intensity, float r, float g, float b)
void(* RenderScene)(const refdef_t *fd)
void(* SetColor)(const float *rgba)
void(* DrawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void(* DrawStretchRaw)(int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
void(* UploadCinematic)(int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
void(* BeginFrame)(stereoFrame_t stereoFrame)
void(* EndFrame)(int *frontEndMsec, int *backEndMsec)
int(* MarkFragments)(int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
int(* LerpTag)(orientation_t *tag, qhandle_t model, int startFrame, int endFrame, float frac, const char *tagName)
void(* ModelBounds)(qhandle_t model, vec3_t mins, vec3_t maxs)
void(* RegisterFont)(const char *fontName, int pointSize, fontInfo_t *font)
void(* RemapShader)(const char *oldShader, const char *newShader, const char *offsetTime)
qboolean(* GetEntityToken)(char *buffer, int size)
qboolean(* inPVS)(const vec3_t p1, const vec3_t p2)
void(* TakeVideoFrame)(int h, int w, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
Field Documentation
void(* refexport_t::AddAdditiveLightToScene)(const vec3_t org, float intensity, float r, float g, float b)
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::AddLightToScene)(const vec3_t org, float intensity, float r, float g, float b)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddPolyToScene)(qhandle_t hShader, int numVerts, const polyVert_t *verts, int num)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::AddRefEntityToScene)(const refEntity_t *re)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::BeginFrame)(stereoFrame_t stereoFrame)
Referenced by GetRefAPI(), and SCR_DrawScreenField().
void(* refexport_t::BeginRegistration)(glconfig_t *config)
Referenced by CL_InitRenderer(), and GetRefAPI().
void(* refexport_t::ClearScene)(void)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::DrawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetRefAPI(), SCR_DrawChar(), SCR_DrawDebugGraph(), SCR_DrawNamedPic(), SCR_DrawPic(), SCR_DrawScreenField(), SCR_DrawSmallChar(), and SCR_FillRect().
void(* refexport_t::DrawStretchRaw)(int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Referenced by CIN_DrawCinematic(), and GetRefAPI().
void(* refexport_t::EndFrame)(int *frontEndMsec, int *backEndMsec)
Referenced by GetRefAPI(), and SCR_UpdateScreen().
void(* refexport_t::EndRegistration)(void)
Referenced by CL_InitCGame(), and GetRefAPI().
qboolean(* refexport_t::GetEntityToken)(char *buffer, int size)
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
qboolean(* refexport_t::inPVS)(const vec3_t p1, const vec3_t p2)
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
int(* refexport_t::LerpTag)(orientation_t *tag, qhandle_t model, int startFrame, int endFrame, float frac, const char *tagName)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
int(* refexport_t::LightForPoint)(vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::LoadWorld)(const char *name)
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
int(* refexport_t::MarkFragments)(int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
void(* refexport_t::ModelBounds)(qhandle_t model, vec3_t mins, vec3_t maxs)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::RegisterFont)(const char *fontName, int pointSize, fontInfo_t *font)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterModel)(const char *name)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterShader)(const char *name)
Referenced by CL_CgameSystemCalls(), CL_InitRenderer(), GetRefAPI(), and SCR_DrawNamedPic().
qhandle_t(* refexport_t::RegisterShaderNoMip)(const char *name)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
qhandle_t(* refexport_t::RegisterSkin)(const char *name)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::RemapShader)(const char *oldShader, const char *newShader, const char *offsetTime)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::RenderScene)(const refdef_t *fd)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
void(* refexport_t::SetColor)(const float *rgba)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), GetRefAPI(), SCR_DrawDebugGraph(), SCR_DrawScreenField(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), and SCR_FillRect().
void(* refexport_t::SetWorldVisData)(const byte *vis)
Referenced by GetRefAPI().
void(* refexport_t::Shutdown)(qboolean destroyWindow)
Referenced by CL_ShutdownAll(), CL_ShutdownRef(), and GetRefAPI().
void(* refexport_t::TakeVideoFrame)(int h, int w, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
Referenced by CL_TakeVideoFrame(), and GetRefAPI().
void(* refexport_t::UploadCinematic)(int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Referenced by CIN_UploadCinematic(), and GetRefAPI().
The documentation for this struct was generated from the following file:
code/renderer/tr_public.h