ioquake3: botlib_export_s Struct Reference
botlib_export_s Struct Reference
#include <botlib.h>
Data Fields
aas_export_t aas
ea_export_t ea
ai_export_t ai
int(* BotLibSetup)(void)
int(* BotLibShutdown)(void)
int(* BotLibVarSet)(char *var_name, char *value)
int(* BotLibVarGet)(char *var_name, char *value, int size)
int(* PC_AddGlobalDefine)(char *string)
int(* PC_LoadSourceHandle)(const char *filename)
int(* PC_FreeSourceHandle)(int handle)
int(* PC_ReadTokenHandle)(int handle, pc_token_t *pc_token)
int(* PC_SourceFileAndLine)(int handle, char *filename, int *line)
int(* BotLibStartFrame)(float time)
int(* BotLibLoadMap)(const char *mapname)
int(* BotLibUpdateEntity)(int ent, bot_entitystate_t *state)
int(* Test)(int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
Field Documentation
aas_export_t botlib_export_s::aas
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
ai_export_t botlib_export_s::ai
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::BotLibLoadMap)(const char *mapname)
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::BotLibSetup)(void)
Referenced by GetBotLibAPI(), and SV_BotLibSetup().
int(* botlib_export_s::BotLibShutdown)(void)
Referenced by GetBotLibAPI(), and SV_BotLibShutdown().
int(* botlib_export_s::BotLibStartFrame)(float time)
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::BotLibUpdateEntity)(int ent, bot_entitystate_t *state)
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::BotLibVarGet)(char *var_name, char *value, int size)
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::BotLibVarSet)(char *var_name, char *value)
Referenced by BotDrawDebugPolygons(), GetBotLibAPI(), and SV_GameSystemCalls().
ea_export_t botlib_export_s::ea
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_AddGlobalDefine)(char *string)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_FreeSourceHandle)(int handle)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_LoadSourceHandle)(const char *filename)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_ReadTokenHandle)(int handle, pc_token_t *pc_token)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::PC_SourceFileAndLine)(int handle, char *filename, int *line)
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
int(* botlib_export_s::Test)(int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
Referenced by BotDrawDebugPolygons(), GetBotLibAPI(), and SV_GameSystemCalls().
The documentation for this struct was generated from the following file:
code/botlib/botlib.h