ioquake3: soundInterface_t Struct Reference
soundInterface_t Struct Reference
#include <snd_local.h>
Data Fields
void(* Shutdown)(void)
void(* StartSound)(vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx)
void(* StartLocalSound)(sfxHandle_t sfx, int channelNum)
void(* StartBackgroundTrack)(const char *intro, const char *loop)
void(* StopBackgroundTrack)(void)
void(* RawSamples)(int stream, int samples, int rate, int width, int channels, const byte *data, float volume, int entityNum)
void(* StopAllSounds)(void)
void(* ClearLoopingSounds)(qboolean killall)
void(* AddLoopingSound)(int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void(* AddRealLoopingSound)(int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void(* StopLoopingSound)(int entityNum)
void(* Respatialize)(int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
void(* UpdateEntityPosition)(int entityNum, const vec3_t origin)
void(* Update)(void)
void(* DisableSounds)(void)
void(* BeginRegistration)(void)
sfxHandle_t(* RegisterSound)(const char *sample, qboolean compressed)
void(* ClearSoundBuffer)(void)
void(* SoundInfo)(void)
void(* SoundList)(void)
Field Documentation
void(* soundInterface_t::AddLoopingSound)(int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Referenced by S_AddLoopingSound(), S_AL_Init(), S_Base_Init(), and S_ValidSoundInterface().
void(* soundInterface_t::AddRealLoopingSound)(int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Referenced by S_AddRealLoopingSound(), S_AL_Init(), S_Base_Init(), and S_ValidSoundInterface().
void(* soundInterface_t::BeginRegistration)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_BeginRegistration(), and S_ValidSoundInterface().
void(* soundInterface_t::ClearLoopingSounds)(qboolean killall)
Referenced by S_AL_Init(), S_Base_Init(), S_ClearLoopingSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::ClearSoundBuffer)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_ClearSoundBuffer(), and S_ValidSoundInterface().
void(* soundInterface_t::DisableSounds)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_DisableSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::RawSamples)(int stream, int samples, int rate, int width, int channels, const byte *data, float volume, int entityNum)
Referenced by S_AL_Init(), S_Base_Init(), S_RawSamples(), and S_ValidSoundInterface().
sfxHandle_t(* soundInterface_t::RegisterSound)(const char *sample, qboolean compressed)
Referenced by S_AL_Init(), S_Base_Init(), S_Play_f(), S_RegisterSound(), and S_ValidSoundInterface().
void(* soundInterface_t::Respatialize)(int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
Referenced by S_AL_Init(), S_Base_Init(), S_Respatialize(), and S_ValidSoundInterface().
void(* soundInterface_t::Shutdown)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_Shutdown(), and S_ValidSoundInterface().
void(* soundInterface_t::SoundInfo)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_SoundInfo(), and S_ValidSoundInterface().
void(* soundInterface_t::SoundList)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_SoundList(), and S_ValidSoundInterface().
void(* soundInterface_t::StartBackgroundTrack)(const char *intro, const char *loop)
Referenced by S_AL_Init(), S_Base_Init(), S_Music_f(), S_StartBackgroundTrack(), and S_ValidSoundInterface().
void(* soundInterface_t::StartLocalSound)(sfxHandle_t sfx, int channelNum)
Referenced by S_AL_Init(), S_Base_Init(), S_Play_f(), S_StartLocalSound(), and S_ValidSoundInterface().
void(* soundInterface_t::StartSound)(vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx)
Referenced by S_AL_Init(), S_Base_Init(), S_StartSound(), and S_ValidSoundInterface().
void(* soundInterface_t::StopAllSounds)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_StopAllSounds(), and S_ValidSoundInterface().
void(* soundInterface_t::StopBackgroundTrack)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_StopBackgroundTrack(), S_StopMusic_f(), and S_ValidSoundInterface().
void(* soundInterface_t::StopLoopingSound)(int entityNum)
Referenced by S_AL_Init(), S_Base_Init(), S_StopLoopingSound(), and S_ValidSoundInterface().
void(* soundInterface_t::Update)(void)
Referenced by S_AL_Init(), S_Base_Init(), S_Update(), and S_ValidSoundInterface().
void(* soundInterface_t::UpdateEntityPosition)(int entityNum, const vec3_t origin)
Referenced by S_AL_Init(), S_Base_Init(), S_UpdateEntityPosition(), and S_ValidSoundInterface().
The documentation for this struct was generated from the following file:
code/client/snd_local.h