ioquake3: Xinterface Struct Reference
Xinterface Struct Reference
#include <config.h>
Data Fields
unsigned char max_unaligned_load
Symbol(* rmap)(int)
void(* blkfetch)(int size, int off, int reg, int tmp)
void(* blkstore)(int size, int off, int reg, int tmp)
void(* blkloop)(int dreg, int doff, int sreg, int soff, int size, int tmps[])
void(* _label)(Node)
int(* _rule)(void *, int)
short ** _nts
void(* _kids)(Node, int, Node *)
char ** _string
char ** _templates
char * _isinstruction
char ** _ntname
void(* emit2)(Node)
void(* doarg)(Node)
void(* target)(Node)
void(* clobber)(Node)
Field Documentation
char* Xinterface::_isinstruction
Referenced by dumprule(), emitasm(), and reduce().
void(* Xinterface::_kids)(Node, int, Node *)
Referenced by dumpcover(), emitasm(), and reduce().
void(* Xinterface::_label)(Node)
Referenced by rewrite().
char** Xinterface::_ntname
short** Xinterface::_nts
Referenced by dumpcover(), emitasm(), and reduce().
int(* Xinterface::_rule)(void *, int)
Referenced by getrule().
char** Xinterface::_string
Referenced by dumprule().
char** Xinterface::_templates
Referenced by dumprule(), emitasm(), and ralloc().
void(* Xinterface::blkfetch)(int size, int off, int reg, int tmp)
Referenced by blkunroll().
void(* Xinterface::blkloop)(int dreg, int doff, int sreg, int soff, int size, int tmps[])
Referenced by blkcopy().
void(* Xinterface::blkstore)(int size, int off, int reg, int tmp)
Referenced by blkunroll().
void(* Xinterface::clobber)(Node)
Referenced by ralloc().
void(* Xinterface::doarg)(Node)
Referenced by gen().
void(* Xinterface::emit2)(Node)
Referenced by emitasm().
unsigned char Xinterface::max_unaligned_load
Referenced by blkunroll().
Symbol(* Xinterface::rmap)(int)
Referenced by gen(), genspill(), prelabel(), and ralloc().
void(* Xinterface::target)(Node)
Referenced by prelabel(), and reprune().
The documentation for this struct was generated from the following file:
code/tools/lcc/src/config.h