ioquake3: code/server/sv_rankings.c File Reference
sv_rankings.c File Reference
#include "server.h"
#include "..\rankings\1.0\gr\grapi.h"
#include "..\rankings\1.0\gr\grlog.h"
Data Structures
struct ranked_player_t
Functions
static void SV_RankNewGameCBF (GR_NEWGAME *gr_newgame, void *cbf_arg)
static void SV_RankUserCBF (GR_LOGIN *gr_login, void *cbf_arg)
static void SV_RankJoinGameCBF (GR_JOINGAME *gr_joingame, void *cbf_arg)
static void SV_RankSendReportsCBF (GR_STATUS *gr_status, void *cbf_arg)
static void SV_RankCleanupCBF (GR_STATUS *gr_status, void *cbf_arg)
static void SV_RankCloseContext (ranked_player_t *ranked_player)
static int SV_RankAsciiEncode (char *dest, const unsigned char *src, int src_len)
static int SV_RankAsciiDecode (unsigned char *dest, const char *src, int src_len)
static void SV_RankEncodeGameID (uint64_t game_id, char *result, int len)
static uint64_t SV_RankDecodePlayerID (const char *string)
static void SV_RankDecodePlayerKey (const char *string, GR_PLAYER_TOKEN key)
static char * SV_RankStatusString (GR_STATUS status)
static void SV_RankError (const char *fmt,...) __attribute__((format(printf
void SV_RankBegin (char *gamekey)
void SV_RankEnd (void)
void SV_RankPoll (void)
qboolean SV_RankCheckInit (void)
qboolean SV_RankActive (void)
grank_status_t SV_RankUserStatus (int index)
int SV_RankUserGrank (int index)
void SV_RankUserReset (int index)
void SV_RankUserSpectate (int index)
void SV_RankUserCreate (int index, char *username, char *password, char *email)
void SV_RankUserLogin (int index, char *username, char *password)
qboolean SV_RankUserValidate (int index, const char *player_id, const char *key, int token_len, int rank, char *name)
void SV_RankUserLogout (int index)
void SV_RankReportInt (int index1, int index2, int key, int value, qboolean accum)
void SV_RankReportStr (int index1, int index2, int key, char *value)
void SV_RankQuit (void)
Variables
static int s_rankings_contexts = 0
static qboolean s_rankings_active = qfalse
static GR_CONTEXT s_server_context = 0
static uint64_t s_server_match = 0
static char * s_rankings_game_key = NULL
static uint64_t s_rankings_game_id = 0
static ranked_player_t * s_ranked_players = NULL
static qboolean s_server_quitting = qfalse
static const char s_ascii_encoding [] = "MNOPQRSTUVWXYZ[]"
static void static char SV_RankGameKey [64]
Function Documentation
qboolean SV_RankActive (void)
References s_rankings_active.
static int SV_RankAsciiDecode (unsigned char * dest, const char * src, int src_len) [static]
References NULL, and s_ascii_encoding.
Referenced by SV_RankDecodePlayerID(), and SV_RankDecodePlayerKey().
static int SV_RankAsciiEncode (char * dest, const unsigned char * src, int src_len) [static]
References NULL, and s_ascii_encoding.
Referenced by SV_RankEncodeGameID().
void SV_RankBegin (char * gamekey)
References com_developer, Com_DPrintf(), Cvar_Set(), Cvar_VariableString(), Cvar_VariableValue(), GT_1FCTF, GT_CTF, GT_FFA, GT_HARVESTER, GT_OBELISK, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, init(), NULL, qfalse, s_rankings_active, s_rankings_contexts, s_rankings_game_key, s_server_context, sv_maxclients, SV_RankError(), SV_RankNewGameCBF(), SV_RankStatusString(), cvar_s::value, and Z_Malloc.
qboolean SV_RankCheckInit (void)
References s_rankings_contexts.
static void SV_RankCleanupCBF (GR_STATUS * gr_status, void * cbf_arg) [static]
References Com_DPrintf(), NULL, SV_RankCloseContext(), SV_RankError(), and SV_RankStatusString().
Referenced by SV_RankJoinGameCBF(), SV_RankQuit(), SV_RankSendReportsCBF(), SV_RankUserCBF(), and SV_RankUserLogout().
static void SV_RankCloseContext (ranked_player_t * ranked_player) [static]
References Com_DPrintf(), ranked_player_t::context, Cvar_Set(), ranked_player_t::final_status, ranked_player_t::grank_status, ranked_player_t::match, ranked_player_t::name, NULL, ranked_player_t::player_id, qfalse, s_rankings_active, s_rankings_contexts, s_server_context, s_server_match, ranked_player_t::token, and Z_Free().
Referenced by SV_RankCleanupCBF(), SV_RankEnd(), SV_RankJoinGameCBF(), SV_RankSendReportsCBF(), SV_RankUserCBF(), and SV_RankUserLogout().
static uint64_t SV_RankDecodePlayerID (const char * string) [static]
References buffer, Com_DPrintf(), NULL, and SV_RankAsciiDecode().
Referenced by SV_RankUserValidate().
static void SV_RankDecodePlayerKey (const char * string, GR_PLAYER_TOKEN key) [static]
References buffer, Com_DPrintf(), NULL, and SV_RankAsciiDecode().
Referenced by SV_RankUserValidate().
static void SV_RankEncodeGameID (uint64_t game_id, char * result, int len) [static]
References Com_DPrintf(), NULL, and SV_RankAsciiEncode().
Referenced by SV_RankNewGameCBF().
void SV_RankEnd (void)
References Com_DPrintf(), Cvar_Set(), NULL, qfalse, s_rankings_active, s_server_context, sv_maxclients, SV_RankCloseContext(), SV_RankError(), SV_RankSendReportsCBF(), SV_RankStatusString(), SV_RankUserLogout(), and cvar_s::value.
static void SV_RankError (const char * fmt, ...) [static]
References Com_DPrintf(), Cvar_Set(), Q_vsnprintf, qfalse, and s_rankings_active.
Referenced by SV_RankBegin(), SV_RankCleanupCBF(), SV_RankEnd(), SV_RankJoinGameCBF(), SV_RankNewGameCBF(), SV_RankQuit(), SV_RankReportInt(), SV_RankReportStr(), SV_RankSendReportsCBF(), SV_RankUserCBF(), SV_RankUserCreate(), SV_RankUserLogin(), SV_RankUserLogout(), and SV_RankUserValidate().
static void SV_RankJoinGameCBF (GR_JOINGAME * gr_joingame, void * cbf_arg) [static]
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::grank, ranked_player_t::match, ranked_player_t::name, NULL, ranked_player_t::player_id, sv_maxclients, SV_RankCleanupCBF(), SV_RankCloseContext(), SV_RankError(), SV_RankStatusString(), SV_RankUserValidate(), ranked_player_t::token, and cvar_s::value.
Referenced by SV_RankUserCBF().
static void SV_RankNewGameCBF (GR_NEWGAME * gr_newgame, void * cbf_arg) [static]
References Com_DPrintf(), Cvar_Set(), ranked_player_t::game_id, info, Info_SetValueForKey(), MAX_INFO_STRING, NULL, qtrue, s_rankings_active, s_rankings_game_id, s_rankings_game_key, s_server_context, s_server_match, sv_maxclients, SV_RankEncodeGameID(), SV_RankError(), SV_RankStatusString(), SV_SetConfigstring(), and cvar_s::value.
Referenced by SV_RankBegin().
void SV_RankPoll (void)
Referenced by SV_RankQuit().
void SV_RankQuit (void)
References Com_DPrintf(), NULL, s_rankings_contexts, sv_maxclients, SV_RankCleanupCBF(), SV_RankError(), SV_RankPoll(), SV_RankStatusString(), SV_RankUserLogout(), and cvar_s::value.
void SV_RankReportInt (int index1, int index2, int key, int value, qboolean accum)
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::match, ranked_player_t::player_id, s_rankings_active, s_server_context, s_server_match, SV_RankError(), and SV_RankStatusString().
void SV_RankReportStr (int index1, int index2, int key, char * value)
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::match, ranked_player_t::player_id, s_rankings_active, s_server_context, s_server_match, SV_RankError(), and SV_RankStatusString().
static void SV_RankSendReportsCBF (GR_STATUS * gr_status, void * cbf_arg) [static]
References Com_DPrintf(), ranked_player_t::context, NULL, s_server_context, SV_RankCleanupCBF(), SV_RankCloseContext(), SV_RankError(), and SV_RankStatusString().
Referenced by SV_RankEnd(), and SV_RankUserLogout().
static char * SV_RankStatusString (GR_STATUS status) [static]
Referenced by SV_RankBegin(), SV_RankCleanupCBF(), SV_RankEnd(), SV_RankJoinGameCBF(), SV_RankNewGameCBF(), SV_RankQuit(), SV_RankReportInt(), SV_RankReportStr(), SV_RankSendReportsCBF(), SV_RankUserCBF(), SV_RankUserCreate(), SV_RankUserLogin(), SV_RankUserLogout(), and SV_RankUserValidate().
static void SV_RankUserCBF (GR_LOGIN * gr_login, void * cbf_arg) [static]
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::final_status, NULL, s_rankings_game_id, SV_RankCleanupCBF(), SV_RankCloseContext(), SV_RankError(), SV_RankJoinGameCBF(), and SV_RankStatusString().
Referenced by SV_RankUserCreate(), and SV_RankUserLogin().
void SV_RankUserCreate (int index, char * username, char * password, char * email)
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::final_status, ranked_player_t::grank_status, init(), NULL, s_rankings_active, s_rankings_contexts, SV_RankError(), SV_RankGameKey, SV_RankStatusString(), and SV_RankUserCBF().
int SV_RankUserGrank (int index)
References ranked_player_t::grank, NULL, and s_rankings_active.
void SV_RankUserLogin (int index, char * username, char * password)
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::final_status, ranked_player_t::grank_status, init(), NULL, s_rankings_active, s_rankings_contexts, SV_RankError(), SV_RankGameKey, SV_RankStatusString(), and SV_RankUserCBF().
void SV_RankUserLogout (int index)
References Com_DPrintf(), ranked_player_t::final_status, ranked_player_t::grank_status, s_rankings_active, SV_RankCleanupCBF(), SV_RankCloseContext(), SV_RankError(), SV_RankSendReportsCBF(), and SV_RankStatusString().
Referenced by SV_RankEnd(), and SV_RankQuit().
void SV_RankUserReset (int index)
References ranked_player_t::grank_status, NULL, and s_rankings_active.
void SV_RankUserSpectate (int index)
References ranked_player_t::grank_status, NULL, and s_rankings_active.
grank_status_t SV_RankUserStatus (int index)
References ranked_player_t::grank_status, NULL, and s_rankings_active.
qboolean SV_RankUserValidate (int index, const char * player_id, const char * key, int token_len, int rank, char * name)
References Com_DPrintf(), ranked_player_t::context, ranked_player_t::final_status, ranked_player_t::grank, ranked_player_t::grank_status, init(), ranked_player_t::name, NULL, ranked_player_t::player_id, Q_strncpyz(), qfalse, qtrue, s_rankings_active, s_rankings_contexts, s_server_context, sv_maxclients, SV_RankDecodePlayerID(), SV_RankDecodePlayerKey(), SV_RankError(), SV_RankGameKey, SV_RankStatusString(), ranked_player_t::token, and cvar_s::value.
Referenced by SV_RankJoinGameCBF().
Variable Documentation
const char s_ascii_encoding[] = "MNOPQRSTUVWXYZ[]" [static]
Referenced by SV_RankAsciiDecode(), and SV_RankAsciiEncode().
ranked_player_t* s_ranked_players = NULL [static]
qboolean s_rankings_active = qfalse [static]
Referenced by SV_RankActive(), SV_RankBegin(), SV_RankCloseContext(), SV_RankEnd(), SV_RankError(), SV_RankNewGameCBF(), SV_RankReportInt(), SV_RankReportStr(), SV_RankUserCreate(), SV_RankUserGrank(), SV_RankUserLogin(), SV_RankUserLogout(), SV_RankUserReset(), SV_RankUserSpectate(), SV_RankUserStatus(), and SV_RankUserValidate().
int s_rankings_contexts = 0 [static]
Referenced by SV_RankBegin(), SV_RankCheckInit(), SV_RankCloseContext(), SV_RankQuit(), SV_RankUserCreate(), SV_RankUserLogin(), and SV_RankUserValidate().
uint64_t s_rankings_game_id = 0 [static]
Referenced by SV_RankNewGameCBF(), and SV_RankUserCBF().
char* s_rankings_game_key = NULL [static]
Referenced by SV_RankBegin(), and SV_RankNewGameCBF().
GR_CONTEXT s_server_context = 0 [static]
Referenced by SV_RankBegin(), SV_RankCloseContext(), SV_RankEnd(), SV_RankNewGameCBF(), SV_RankReportInt(), SV_RankReportStr(), SV_RankSendReportsCBF(), and SV_RankUserValidate().
uint64_t s_server_match = 0 [static]
Referenced by SV_RankCloseContext(), SV_RankNewGameCBF(), SV_RankReportInt(), and SV_RankReportStr().
qboolean s_server_quitting = qfalse [static]
void static char SV_RankGameKey[64] [static]
Referenced by SV_RankUserCreate(), SV_RankUserLogin(), and SV_RankUserValidate().