ioquake3: code/server/sv_main.c File Reference
sv_main.c File Reference
#include "server.h"
Data Structures
struct leakyBucket_s
Defines
#define HEARTBEAT_MSEC 300*1000
#define MAX_BUCKETS 16384
#define MAX_HASHES 1024
#define SV_OUTPUTBUF_LENGTH (1024 - 16)
#define UDPIP_HEADER_SIZE 28
#define UDPIP6_HEADER_SIZE 48
Typedefs
typedef struct leakyBucket_s leakyBucket_t
Functions
static char * SV_ExpandNewlines (char *in)
void SV_AddServerCommand (client_t *client, const char *cmd)
void QDECL SV_SendServerCommand (client_t *cl, const char *fmt,...)
void SV_MasterHeartbeat (const char *message)
void SV_MasterShutdown (void)
static long SVC_HashForAddress (netadr_t address)
static leakyBucket_t * SVC_BucketForAddress (netadr_t address, int burst, int period)
static qboolean SVC_RateLimit (leakyBucket_t *bucket, int burst, int period)
static qboolean SVC_RateLimitAddress (netadr_t from, int burst, int period)
static void SVC_Status (netadr_t from)
void SVC_Info (netadr_t from)
static void SV_FlushRedirect (char *outputbuf)
static void SVC_RemoteCommand (netadr_t from, msg_t *msg)
static void SV_ConnectionlessPacket (netadr_t from, msg_t *msg)
void SV_PacketEvent (netadr_t from, msg_t *msg)
static void SV_CalcPings (void)
static void SV_CheckTimeouts (void)
static qboolean SV_CheckPaused (void)
int SV_FrameMsec ()
void SV_Frame (int msec)
int SV_RateMsec (client_t *client)
int SV_SendQueuedPackets ()
Variables
serverStatic_t svs
server_t sv
vm_t * gvm = NULL
cvar_t * sv_fps = NULL
cvar_t * sv_timeout
cvar_t * sv_zombietime
cvar_t * sv_rconPassword
cvar_t * sv_privatePassword
cvar_t * sv_allowDownload
cvar_t * sv_maxclients
cvar_t * sv_privateClients
cvar_t * sv_hostname
cvar_t * sv_master [MAX_MASTER_SERVERS]
cvar_t * sv_reconnectlimit
cvar_t * sv_showloss
cvar_t * sv_padPackets
cvar_t * sv_killserver
cvar_t * sv_mapname
cvar_t * sv_mapChecksum
cvar_t * sv_serverid
cvar_t * sv_minRate
cvar_t * sv_maxRate
cvar_t * sv_dlRate
cvar_t * sv_minPing
cvar_t * sv_maxPing
cvar_t * sv_gametype
cvar_t * sv_pure
cvar_t * sv_floodProtect
cvar_t * sv_lanForceRate
cvar_t * sv_strictAuth
cvar_t * sv_banFile
serverBan_t serverBans [SERVER_MAXBANS]
int serverBansCount = 0
static leakyBucket_t buckets [MAX_BUCKETS]
static leakyBucket_t * bucketHashes [MAX_HASHES]
Define Documentation
#define HEARTBEAT_MSEC 300*1000
Referenced by SV_MasterHeartbeat().
#define MAX_BUCKETS 16384
Referenced by SVC_BucketForAddress().
#define MAX_HASHES 1024
Referenced by SVC_HashForAddress().
#define SV_OUTPUTBUF_LENGTH (1024 - 16)
Referenced by SVC_RemoteCommand().
#define UDPIP6_HEADER_SIZE 48
Referenced by SV_RateMsec().
#define UDPIP_HEADER_SIZE 28
Referenced by SV_RateMsec().
Typedef Documentation
typedef struct leakyBucket_s leakyBucket_t
Function Documentation
void SV_AddServerCommand (client_t * client, const char * cmd)
References Com_Printf(), CS_PRIMED, MAX_RELIABLE_COMMANDS, Q_strncpyz(), client_s::reliableAcknowledge, client_s::reliableCommands, client_s::reliableSequence, client_s::state, and SV_DropClient().
Referenced by SV_MapRestart_f(), and SV_SendServerCommand().
static void SV_CalcPings (void) [static]
References cl, serverStatic_t::clients, count, CS_ACTIVE, client_s::frames, client_s::gentity, cvar_s::integer, clientSnapshot_t::messageAcked, clientSnapshot_t::messageSent, PACKET_BACKUP, client_s::ping, playerState_s::ping, sharedEntity_t::r, client_s::state, SV_GameClientNum(), SVF_BOT, and entityShared_t::svFlags.
Referenced by SV_Frame().
static qboolean SV_CheckPaused (void) [static]
References cl, cl_paused, serverStatic_t::clients, count, CS_CONNECTED, Cvar_Set(), cvar_s::integer, NA_BOT, client_s::netchan, qfalse, qtrue, netchan_t::remoteAddress, client_s::state, sv_paused, and netadr_t::type.
Referenced by SV_Frame().
static void SV_CheckTimeouts (void) [static]
References cl, serverStatic_t::clients, Com_DPrintf(), CS_CONNECTED, CS_FREE, CS_ZOMBIE, cvar_s::integer, client_s::lastPacketTime, client_s::state, SV_DropClient(), serverStatic_t::time, and client_s::timeoutCount.
Referenced by SV_Frame().
static void SV_ConnectionlessPacket (netadr_t from, msg_t * msg) [static]
References Cmd_Argv(), Cmd_TokenizeString(), Com_DPrintf(), msg_t::data, Huff_Decompress(), MSG_BeginReadingOOB(), MSG_ReadLong(), MSG_ReadStringLine(), NET_AdrToString(), Q_stricmp(), Q_strncmp(), s, SV_AuthorizeIpPacket(), SV_DirectConnect(), SV_GetChallenge(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
Referenced by SV_PacketEvent().
static char* SV_ExpandNewlines (char * in) [static]
References in, and string().
Referenced by SV_SendServerCommand().
static void SV_FlushRedirect (char * outputbuf) [static]
References NET_OutOfBandPrint(), NS_SERVER, and serverStatic_t::redirectAddress.
Referenced by SVC_RemoteCommand().
void SV_Frame (int msec)
References Cbuf_AddText(), com_dedicated, com_speeds, com_sv_running, com_timescale, CS_SERVERINFO, CS_SYSTEMINFO, Cvar_InfoString(), Cvar_InfoString_Big(), cvar_modifiedFlags, CVAR_SERVERINFO, Cvar_Set(), CVAR_SYSTEMINFO, Cvar_VariableString(), GAME_RUN_FRAME, HEARTBEAT_FOR_MASTER, cvar_s::integer, serverStatic_t::nextSnapshotEntities, serverStatic_t::numSnapshotEntities, server_t::restartTime, startTime, SV_BotFrame(), SV_CalcPings(), SV_CheckPaused(), SV_CheckTimeouts(), SV_MasterHeartbeat(), SV_SendClientMessages(), SV_SetConfigstring(), SV_Shutdown(), Sys_Milliseconds(), Sys_Sleep(), server_t::time, serverStatic_t::time, time_game, server_t::timeResidual, va(), cvar_s::value, and VM_Call().
Referenced by CL_Connect_f(), and Com_Frame().
int SV_FrameMsec (void)
References server_t::timeResidual, and cvar_s::value.
Referenced by Com_Frame().
void SV_MasterHeartbeat (const char * message)
References com_dedicated, Com_Printf(), Cvar_Set(), Cvar_VariableIntegerValue(), HEARTBEAT_MSEC, cvar_s::integer, MAX_MASTER_SERVERS, cvar_s::modified, NA_BAD, NA_IP, NA_IP6, NET_AdrToStringwPort(), NET_ENABLEV4, NET_ENABLEV6, NET_OutOfBandPrint(), NET_StringToAdr(), serverStatic_t::nextHeartbeatTime, NS_SERVER, netadr_t::port, PORT_MASTER, qfalse, and serverStatic_t::time.
Referenced by SV_Frame(), and SV_MasterShutdown().
void SV_MasterShutdown (void)
References HEARTBEAT_FOR_MASTER, serverStatic_t::nextHeartbeatTime, and SV_MasterHeartbeat().
Referenced by SV_Shutdown().
void SV_PacketEvent (netadr_t from, msg_t * msg)
References cl, serverStatic_t::clients, Com_Printf(), CS_FREE, CS_ZOMBIE, msg_t::cursize, msg_t::data, client_s::lastPacketTime, MSG_BeginReadingOOB(), MSG_ReadLong(), MSG_ReadShort(), NET_CompareBaseAdr(), client_s::netchan, netadr_t::port, qport, netchan_t::qport, netchan_t::remoteAddress, client_s::state, SV_ConnectionlessPacket(), SV_ExecuteClientMessage(), SV_Netchan_Process(), and serverStatic_t::time.
Referenced by Com_RunAndTimeServerPacket().
int SV_RateMsec (client_t * client)
References com_timescale, Cvar_Set(), int(), cvar_s::integer, netchan_t::lastSentSize, netchan_t::lastSentTime, NA_IP6, client_s::netchan, client_s::rate, netchan_t::remoteAddress, Sys_Milliseconds(), netadr_t::type, UDPIP6_HEADER_SIZE, UDPIP_HEADER_SIZE, and cvar_s::value.
Referenced by SV_Netchan_TransmitNextFragment(), SV_SendClientMessages(), and SV_SendQueuedMessages().
int SV_SendQueuedPackets (void)
References INT_MAX, cvar_s::integer, MAX_DOWNLOAD_BLKSIZE, SV_SendDownloadMessages(), SV_SendQueuedMessages(), and Sys_Milliseconds().
Referenced by Com_Frame().
void QDECL SV_SendServerCommand (client_t * cl, const char * fmt, ...)
References serverStatic_t::clients, com_dedicated, Com_Printf(), cvar_s::integer, MAX_MSGLEN, NULL, Q_vsnprintf, SV_AddServerCommand(), and SV_ExpandNewlines().
static leakyBucket_t* SVC_BucketForAddress (netadr_t address, int burst, int period) [static]
References leakyBucket_s::_4, leakyBucket_s::_6, leakyBucket_s::burst, Com_Memcpy, Com_Memset, hash(), leakyBucket_s::hash, netadr_t::ip, netadr_t::ip6, leakyBucket_s::ipv, leakyBucket_s::lastTime, MAX_BUCKETS, NA_BAD, NA_IP, NA_IP6, leakyBucket_s::next, NULL, leakyBucket_s::prev, SVC_HashForAddress(), Sys_Milliseconds(), netadr_t::type, and leakyBucket_s::type.
Referenced by SVC_RateLimitAddress().
static long SVC_HashForAddress (netadr_t address) [static]
References hash(), netadr_t::ip, netadr_t::ip6, long(), MAX_HASHES, NA_IP, NA_IP6, NULL, and netadr_t::type.
Referenced by SVC_BucketForAddress().
void SVC_Info (netadr_t from)
References serverStatic_t::clients, Cmd_Argv(), com_gamename, com_legacyprotocol, com_protocol, count, CS_CONNECTED, Cvar_VariableIntegerValue(), Cvar_VariableString(), Cvar_VariableValue(), gamedir, GT_SINGLE_PLAYER, Info_SetValueForKey(), cvar_s::integer, MAX_INFO_STRING, NA_BOT, NET_OutOfBandPrint(), client_s::netchan, NS_SERVER, netchan_t::remoteAddress, client_s::state, cvar_s::string, netadr_t::type, and va().
Referenced by SV_ConnectionlessPacket().
static qboolean SVC_RateLimit (leakyBucket_t * bucket, int burst, int period) [static]
References leakyBucket_s::burst, leakyBucket_s::lastTime, NULL, qfalse, qtrue, and Sys_Milliseconds().
Referenced by SVC_RateLimitAddress(), SVC_RemoteCommand(), and SVC_Status().
static qboolean SVC_RateLimitAddress (netadr_t from, int burst, int period) [static]
References SVC_BucketForAddress(), and SVC_RateLimit().
Referenced by SVC_RemoteCommand(), and SVC_Status().
static void SVC_RemoteCommand (netadr_t from, msg_t * msg) [static]
References Cmd_ArgsFrom(), Cmd_Argv(), Cmd_Cmd(), Cmd_ExecuteString(), Com_BeginRedirect(), Com_DPrintf(), Com_EndRedirect(), Com_Printf(), NET_AdrToString(), Q_strcat(), qfalse, qtrue, serverStatic_t::redirectAddress, cvar_s::string, SV_FlushRedirect(), SV_OUTPUTBUF_LENGTH, SVC_RateLimit(), and SVC_RateLimitAddress().
Referenced by SV_ConnectionlessPacket().
static void SVC_Status (netadr_t from) [static]
References cl, serverStatic_t::clients, Cmd_Argv(), Com_DPrintf(), Com_sprintf(), CS_CONNECTED, Cvar_InfoString(), CVAR_SERVERINFO, Cvar_VariableValue(), GT_SINGLE_PLAYER, Info_SetValueForKey(), cvar_s::integer, MAX_INFO_STRING, MAX_MSGLEN, client_s::name, NET_AdrToString(), NET_OutOfBandPrint(), NS_SERVER, PERS_SCORE, playerState_s::persistant, client_s::ping, client_s::state, SV_GameClientNum(), SVC_RateLimit(), and SVC_RateLimitAddress().
Referenced by SV_ConnectionlessPacket().
Variable Documentation
leakyBucket_t* bucketHashes[MAX_HASHES] [static]
leakyBucket_t buckets[MAX_BUCKETS] [static]
Referenced by hashtable_init(), and swgen().
vm_t* gvm = NULL
Referenced by SV_BotFrame(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_GameCommand(), SV_InitGameProgs(), SV_InitGameVM(), SV_MapRestart_f(), SV_RestartGameProgs(), SV_ShutdownGameProgs(), SV_SpawnServer(), and SV_UpdateUserinfo_f().
serverBan_t serverBans[SERVER_MAXBANS]
Referenced by SV_AddBanToList(), SV_DelBanEntryFromList(), SV_DelBanFromList(), SV_IsBanned(), SV_ListBans_f(), SV_RehashBans_f(), and SV_WriteBans().
int serverBansCount = 0
Referenced by SV_AddBanToList(), SV_DelBanEntryFromList(), SV_DelBanFromList(), SV_FlushBans_f(), SV_IsBanned(), SV_ListBans_f(), SV_RehashBans_f(), and SV_WriteBans().
server_t sv
Referenced by arith_decode(), arith_encode(), Com_Frame(), SV_AddEntitiesVisibleFromPoint(), SV_AddEntToSnapshot(), SV_AreaEntities_r(), SV_BuildClientSnapshot(), SV_ClearServer(), SV_CreateBaseline(), SV_EmitPacketEntities(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_GameClientNum(), SV_GameCommand(), SV_GameSystemCalls(), SV_GEntityForSvEntity(), SV_GentityNum(), SV_GetConfigstring(), SV_InitGameVM(), SV_LinkEntity(), SV_LocateGameData(), SV_MapRestart_f(), SV_NumForGentity(), SV_SendClientGameState(), SV_SendConfigstring(), SV_SetConfigstring(), SV_SpawnServer(), SV_SvEntityForGentity(), SV_UserMove(), SV_VerifyPaks_f(), and SV_WriteSnapshotToClient().
cvar_t* sv_allowDownload
Referenced by SV_Init(), and SV_WriteDownloadToClient().
cvar_t* sv_banFile
Referenced by SV_Init(), SV_RehashBans_f(), and SV_WriteBans().
cvar_t* sv_dlRate
Referenced by SV_Init().
cvar_t* sv_floodProtect
Referenced by SV_ClientCommand(), and SV_Init().
cvar_t* sv_fps = NULL
Referenced by SV_Init(), and SV_UserinfoChanged().
cvar_t* sv_gametype
Referenced by SV_Init(), SV_Map_f(), SV_MapRestart_f(), and SV_SpawnServer().
cvar_t* sv_hostname
Referenced by SV_Init().
cvar_t* sv_killserver
Referenced by SV_Init(), SV_Shutdown(), and SV_Startup().
cvar_t* sv_lanForceRate
Referenced by SV_Init(), SV_SendClientMessages(), and SV_UserinfoChanged().
cvar_t* sv_mapChecksum
Referenced by SV_Init().
cvar_t* sv_mapname
Referenced by SV_Init(), and SV_Status_f().
cvar_t* sv_master[MAX_MASTER_SERVERS]
Referenced by SV_Init().
cvar_t* sv_maxclients
Referenced by SV_BotAllocateClient(), SV_BotFreeClient(), SV_BoundMaxClients(), SV_ChangeMaxClients(), SV_DirectConnect(), SV_DropClient(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GetPlayerByNum(), SV_GetUsercmd(), SV_GetUserinfo(), SV_Init(), SV_InitGameVM(), SV_MapRestart_f(), SV_RankBegin(), SV_RankEnd(), SV_RankJoinGameCBF(), SV_RankNewGameCBF(), SV_RankQuit(), SV_RankUserValidate(), SV_SendClientMessages(), SV_SendDownloadMessages(), SV_SendQueuedMessages(), SV_SetUserinfo(), SV_Shutdown(), SV_SpawnServer(), and SV_Startup().
cvar_t* sv_maxPing
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_maxRate
Referenced by SV_Init().
cvar_t* sv_minPing
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_minRate
Referenced by SV_Init().
cvar_t* sv_padPackets
Referenced by SV_Init(), and SV_WriteSnapshotToClient().
cvar_t* sv_privateClients
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_privatePassword
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_pure
Referenced by SV_Init(), SV_SpawnServer(), SV_UserMove(), SV_VerifyPaks_f(), and SV_WriteDownloadToClient().
cvar_t* sv_rconPassword
Referenced by SV_Init().
cvar_t* sv_reconnectlimit
Referenced by SV_DirectConnect(), and SV_Init().
cvar_t* sv_serverid
Referenced by SV_Init().
cvar_t* sv_showloss
Referenced by SV_Init().
cvar_t* sv_strictAuth
Referenced by SV_GetChallenge(), and SV_Init().
cvar_t* sv_timeout
Referenced by SV_Init().
cvar_t* sv_zombietime
Referenced by SV_Init().
serverStatic_t svs
Referenced by BotClientCommand(), BotDrawDebugPolygons(), SV_AuthorizeIpPacket(), SV_Ban_f(), SV_BanNum_f(), SV_BotAllocateClient(), SV_BotFreeClient(), SV_BotGetConsoleMessage(), SV_BotGetSnapshotEntity(), SV_BuildClientSnapshot(), SV_ChangeMaxClients(), SV_ClientCommand(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DirectConnect(), SV_DropClient(), SV_EmitPacketEntities(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_FinalMessage(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GameSystemCalls(), SV_GetChallenge(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_GetUsercmd(), SV_GetUserinfo(), SV_Heartbeat_f(), SV_InitGameVM(), SV_Kick_f(), SV_KickNum_f(), SV_MapRestart_f(), SV_NextDownload_f(), SV_SendClientGameState(), SV_SendClientMessages(), SV_SendDownloadMessages(), SV_SendMessageToClient(), SV_SendQueuedMessages(), SV_SetConfigstring(), SV_SetUserinfo(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), SV_Status_f(), SV_StopDownload_f(), SV_UpdateUserinfo_f(), SV_UserMove(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().