ioquake3: code/libspeex/testenc_wb.c File Reference
testenc_wb.c File Reference
#include <speex/speex.h>
#include <stdio.h>
#include <stdlib.h>
#include <speex/speex_callbacks.h>
#include <math.h>
Defines
#define FRAME_SIZE 320
Functions
int main (int argc, char **argv)
Define Documentation
#define FRAME_SIZE 320
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
References bits(), SpeexCallback::callback_id, SpeexCallback::data, fclose(), fout, FRAME_SIZE, fread(), SpeexCallback::func, fwrite(), SpeexBits::nbBits, NULL, printf(), s, speex_bits_destroy(), speex_bits_init(), speex_bits_reset(), speex_bits_rewind(), speex_bits_write(), speex_decode_int(), speex_decoder_ctl(), speex_decoder_destroy(), speex_decoder_init(), speex_encode_int(), speex_encoder_ctl(), speex_encoder_destroy(), speex_encoder_init(), SPEEX_GET_LOOKAHEAD, SPEEX_INBAND_CHAR, SPEEX_INBAND_MODE_REQUEST, speex_lib_get_mode, SPEEX_MODEID_WB, SPEEX_SET_COMPLEXITY, SPEEX_SET_ENH, SPEEX_SET_HANDLER, SPEEX_SET_QUALITY, SPEEX_SET_VBR, speex_std_char_handler(), speex_std_mode_request_handler(), and spx_mips.