ioquake3: code/renderer/tr_init.c File Reference
tr_init.c File Reference
#include "tr_local.h"
Data Structures
struct vidmode_s
Typedefs
typedef struct vidmode_s vidmode_t
Functions
static void GfxInfo_f (void)
static void InitOpenGL (void)
void GL_CheckErrors (void)
qboolean R_GetModeInfo (int *width, int *height, float *windowAspect, int mode)
static void R_ModeList_f (void)
byte * RB_ReadPixels (int x, int y, int width, int height, size_t *offset, int *padlen)
void RB_TakeScreenshot (int x, int y, int width, int height, char *fileName)
void RB_TakeScreenshotJPEG (int x, int y, int width, int height, char *fileName)
const void * RB_TakeScreenshotCmd (const void *data)
void R_TakeScreenshot (int x, int y, int width, int height, char *name, qboolean jpeg)
void R_ScreenshotFilename (int lastNumber, char *fileName)
void R_ScreenshotFilenameJPEG (int lastNumber, char *fileName)
void R_LevelShot (void)
void R_ScreenShot_f (void)
void R_ScreenShotJPEG_f (void)
const void * RB_TakeVideoFrameCmd (const void *data)
void GL_SetDefaultState (void)
void R_Register (void)
void R_Init (void)
void RE_Shutdown (qboolean destroyWindow)
void RE_EndRegistration (void)
refexport_t * GetRefAPI (int apiVersion, refimport_t *rimp)
Variables
glconfig_t glConfig
qboolean textureFilterAnisotropic = qfalse
int maxAnisotropy = 0
float displayAspect = 0.0f
glstate_t glState
cvar_t * r_flareSize
cvar_t * r_flareFade
cvar_t * r_flareCoeff
cvar_t * r_railWidth
cvar_t * r_railCoreWidth
cvar_t * r_railSegmentLength
cvar_t * r_ignoreFastPath
cvar_t * r_verbose
cvar_t * r_ignore
cvar_t * r_detailTextures
cvar_t * r_znear
cvar_t * r_zproj
cvar_t * r_stereoSeparation
cvar_t * r_smp
cvar_t * r_showSmp
cvar_t * r_skipBackEnd
cvar_t * r_stereoEnabled
cvar_t * r_anaglyphMode
cvar_t * r_greyscale
cvar_t * r_ignorehwgamma
cvar_t * r_measureOverdraw
cvar_t * r_inGameVideo
cvar_t * r_fastsky
cvar_t * r_drawSun
cvar_t * r_dynamiclight
cvar_t * r_dlightBacks
cvar_t * r_lodbias
cvar_t * r_lodscale
cvar_t * r_norefresh
cvar_t * r_drawentities
cvar_t * r_drawworld
cvar_t * r_speeds
cvar_t * r_fullbright
cvar_t * r_novis
cvar_t * r_nocull
cvar_t * r_facePlaneCull
cvar_t * r_showcluster
cvar_t * r_nocurves
cvar_t * r_allowExtensions
cvar_t * r_ext_compressed_textures
cvar_t * r_ext_multitexture
cvar_t * r_ext_compiled_vertex_array
cvar_t * r_ext_texture_env_add
cvar_t * r_ext_texture_filter_anisotropic
cvar_t * r_ext_max_anisotropy
cvar_t * r_ignoreGLErrors
cvar_t * r_logFile
cvar_t * r_stencilbits
cvar_t * r_depthbits
cvar_t * r_colorbits
cvar_t * r_primitives
cvar_t * r_texturebits
cvar_t * r_ext_multisample
cvar_t * r_drawBuffer
cvar_t * r_lightmap
cvar_t * r_vertexLight
cvar_t * r_uiFullScreen
cvar_t * r_shadows
cvar_t * r_flares
cvar_t * r_mode
cvar_t * r_nobind
cvar_t * r_singleShader
cvar_t * r_roundImagesDown
cvar_t * r_colorMipLevels
cvar_t * r_picmip
cvar_t * r_showtris
cvar_t * r_showsky
cvar_t * r_shownormals
cvar_t * r_finish
cvar_t * r_clear
cvar_t * r_swapInterval
cvar_t * r_textureMode
cvar_t * r_offsetFactor
cvar_t * r_offsetUnits
cvar_t * r_gamma
cvar_t * r_intensity
cvar_t * r_lockpvs
cvar_t * r_noportals
cvar_t * r_portalOnly
cvar_t * r_subdivisions
cvar_t * r_lodCurveError
cvar_t * r_fullscreen
cvar_t * r_noborder
cvar_t * r_customwidth
cvar_t * r_customheight
cvar_t * r_customPixelAspect
cvar_t * r_overBrightBits
cvar_t * r_mapOverBrightBits
cvar_t * r_debugSurface
cvar_t * r_simpleMipMaps
cvar_t * r_showImages
cvar_t * r_ambientScale
cvar_t * r_directedScale
cvar_t * r_debugLight
cvar_t * r_debugSort
cvar_t * r_printShaders
cvar_t * r_saveFontData
cvar_t * r_marksOnTriangleMeshes
cvar_t * r_aviMotionJpegQuality
cvar_t * r_screenshotJpegQuality
cvar_t * r_maxpolys
int max_polys
cvar_t * r_maxpolyverts
int max_polyverts
vidmode_t r_vidModes []
static int s_numVidModes = ARRAY_LEN(r_vidModes)
Typedef Documentation
typedef struct vidmode_s vidmode_t
Function Documentation
refexport_t* GetRefAPI (int apiVersion, refimport_t * rimp)
References refexport_t::AddAdditiveLightToScene, refexport_t::AddLightToScene, refexport_t::AddPolyToScene, refexport_t::AddRefEntityToScene, refexport_t::BeginFrame, refexport_t::BeginRegistration, refexport_t::ClearScene, Com_Memset, refexport_t::DrawStretchPic, refexport_t::DrawStretchRaw, refexport_t::EndFrame, refexport_t::EndRegistration, refexport_t::GetEntityToken, refexport_t::inPVS, refexport_t::LerpTag, refexport_t::LightForPoint, refexport_t::LoadWorld, refexport_t::MarkFragments, refexport_t::ModelBounds, NULL, PRINT_ALL, R_GetEntityToken(), R_inPVS(), R_LerpTag(), R_LightForPoint(), R_MarkFragments(), R_ModelBounds(), R_RemapShader(), re, RE_AddAdditiveLightToScene(), RE_AddLightToScene(), RE_AddPolyToScene(), RE_AddRefEntityToScene(), RE_BeginFrame(), RE_BeginRegistration(), RE_ClearScene(), RE_EndFrame(), RE_EndRegistration(), RE_LoadWorldMap(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterShader(), RE_RegisterShaderNoMip(), RE_RegisterSkin(), RE_RenderScene(), RE_SetColor(), RE_SetWorldVisData(), RE_Shutdown(), RE_StretchPic(), RE_StretchRaw(), RE_TakeVideoFrame(), RE_UploadCinematic(), REF_API_VERSION, refexport_t::RegisterFont, refexport_t::RegisterModel, refexport_t::RegisterShader, refexport_t::RegisterShaderNoMip, refexport_t::RegisterSkin, refexport_t::RemapShader, refexport_t::RenderScene, ri, refexport_t::SetColor, refexport_t::SetWorldVisData, refexport_t::Shutdown, refexport_t::TakeVideoFrame, and refexport_t::UploadCinematic.
Referenced by CL_InitRef().
void GfxInfo_f (void) [static]
References glconfig_t::colorBits, glconfig_t::depthBits, glconfig_t::deviceSupportsGamma, glconfig_t::displayFrequency, glconfig_t::extensions_string, GLHW_PERMEDIA2, GLHW_RAGEPRO, GLHW_RIVA128, glconfig_t::hardwareType, cvar_s::integer, glconfig_t::maxTextureSize, glconfig_t::numTextureUnits, trGlobals_t::overbrightBits, PRINT_ALL, qglActiveTextureARB, qglLockArraysEXT, glconfig_t::renderer_string, ri, glconfig_t::smpActive, glconfig_t::stencilBits, cvar_s::string, TC_NONE, glconfig_t::textureCompression, glconfig_t::textureEnvAddAvailable, tr, glconfig_t::vendor_string, glconfig_t::version_string, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by InitOpenGL(), and R_Register().
void GL_CheckErrors (void)
References Com_sprintf(), ERR_FATAL, cvar_s::integer, qglGetError, ri, and s.
Referenced by Upload32().
void GL_SetDefaultState (void)
References GL_SelectTexture(), GL_TexEnv(), GL_TextureMode(), GLS_DEPTHMASK_TRUE, GLS_DEPTHTEST_DISABLE, glstate_t::glStateBits, qglActiveTextureARB, qglClearDepth, qglColor4f, qglCullFace, qglDepthFunc, qglDepthMask, qglDisable, qglEnable, qglEnableClientState, qglPolygonMode, qglShadeModel, and cvar_s::string.
Referenced by InitOpenGL().
static void InitOpenGL (void) [static]
References GfxInfo_f(), GL_SetDefaultState(), GLimp_Init(), glconfig_t::maxTextureSize, Q_strlwr(), qglGetIntegerv, R_InitCommandBuffers(), glconfig_t::renderer_string, and glconfig_t::vidWidth.
Referenced by R_Init().
qboolean R_GetModeInfo (int * width, int * height, float * windowAspect, int mode)
References vidmode_s::height, cvar_s::integer, vidmode_s::pixelAspect, qfalse, qtrue, s_numVidModes, cvar_s::value, and vidmode_s::width.
Referenced by GLimp_SetMode().
void R_Init (void)
References backEnd, backEndData, Com_Memset, DEG2RAD, ERR_FATAL, FUNCTABLE_SIZE, h_low, refimport_t::Hunk_Alloc, InitOpenGL(), cvar_s::integer, intptr_t(), trGlobals_t::inverseSawToothTable, max_polys, MAX_POLYS, max_polyverts, MAX_POLYVERTS, NULL, backEndData_t::polys, backEndData_t::polyVerts, PRINT_ALL, PRINT_WARNING, ptr(), qglGetError, R_InitFogTable(), R_InitFreeType(), R_InitImages(), R_InitShaders(), R_InitSkins(), R_ModelInit(), R_NoiseInit(), R_Register(), R_ToggleSmpFrame(), ri, trGlobals_t::sawToothTable, trGlobals_t::sinTable, trGlobals_t::squareTable, tess, tr, and trGlobals_t::triangleTable.
Referenced by RE_BeginRegistration().
void R_LevelShot (void)
References b, world_t::baseName, buffer, Com_Memset, Com_sprintf(), glconfig_t::deviceSupportsGamma, refimport_t::FS_WriteFile, refimport_t::Hunk_AllocateTempMemory, refimport_t::Hunk_FreeTempMemory, int(), MAX_OSPATH, PRINT_ALL, R_GammaCorrect(), RB_ReadPixels(), ri, src, tr, glconfig_t::vidHeight, glconfig_t::vidWidth, trGlobals_t::world, xx, and yy.
Referenced by R_ScreenShot_f(), and R_ScreenShotJPEG_f().
static void R_ModeList_f (void) [static]
References PRINT_ALL, ri, and s_numVidModes.
Referenced by R_Register().
void R_Register (void)
References refimport_t::Cmd_AddCommand, CVAR_ARCHIVE, CVAR_CHEAT, refimport_t::Cvar_CheckRange, refimport_t::Cvar_Get, CVAR_LATCH, CVAR_TEMP, FLARE_STDCOEFF, GfxInfo_f(), GLimp_Minimize(), MAX_POLYS, MAX_POLYVERTS, qfalse, qtrue, R_ImageList_f(), R_ModeList_f(), R_Modellist_f(), R_ScreenShot_f(), R_ScreenShotJPEG_f(), R_ShaderList_f(), R_SkinList_f(), ri, and va().
Referenced by R_Init().
void R_ScreenShot_f (void)
References refimport_t::Cmd_Argc, refimport_t::Cmd_Argv, Com_sprintf(), refimport_t::FS_FileExists, MAX_OSPATH, PRINT_ALL, qfalse, qtrue, R_LevelShot(), R_ScreenshotFilename(), R_TakeScreenshot(), ri, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by R_Register().
void R_ScreenshotFilename (int lastNumber, char * fileName)
References b, Com_sprintf(), and MAX_OSPATH.
Referenced by R_ScreenShot_f().
void R_ScreenshotFilenameJPEG (int lastNumber, char * fileName)
References b, Com_sprintf(), and MAX_OSPATH.
Referenced by R_ScreenShotJPEG_f().
void R_ScreenShotJPEG_f (void)
References refimport_t::Cmd_Argc, refimport_t::Cmd_Argv, Com_sprintf(), refimport_t::FS_FileExists, MAX_OSPATH, PRINT_ALL, qfalse, qtrue, R_LevelShot(), R_ScreenshotFilenameJPEG(), R_TakeScreenshot(), ri, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by R_Register().
void R_TakeScreenshot (int x, int y, int width, int height, char * name, qboolean jpeg)
References screenshotCommand_t::commandId, screenshotCommand_t::fileName, height, screenshotCommand_t::height, screenshotCommand_t::jpeg, MAX_OSPATH, Q_strncpyz(), R_GetCommandBuffer(), RC_SCREENSHOT, width, screenshotCommand_t::width, screenshotCommand_t::x, and screenshotCommand_t::y.
Referenced by R_ScreenShot_f(), and R_ScreenShotJPEG_f().
byte* RB_ReadPixels (int x, int y, int width, int height, size_t * offset, int * padlen)
References buffer, refimport_t::Hunk_AllocateTempMemory, intptr_t(), PAD, PADP, qglGetIntegerv, qglReadPixels, and ri.
Referenced by R_LevelShot(), RB_TakeScreenshot(), and RB_TakeScreenshotJPEG().
void RB_TakeScreenshot (int x, int y, int width, int height, char * fileName)
References buffer, Com_Memset, glconfig_t::deviceSupportsGamma, refimport_t::FS_WriteFile, height, refimport_t::Hunk_FreeTempMemory, R_GammaCorrect(), RB_ReadPixels(), and ri.
Referenced by RB_TakeScreenshotCmd().
const void* RB_TakeScreenshotCmd (const void * data)
References screenshotCommand_t::fileName, screenshotCommand_t::height, screenshotCommand_t::jpeg, RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), screenshotCommand_t::width, screenshotCommand_t::x, and screenshotCommand_t::y.
Referenced by RB_ExecuteRenderCommands().
void RB_TakeScreenshotJPEG (int x, int y, int width, int height, char * fileName)
References buffer, glconfig_t::deviceSupportsGamma, refimport_t::Hunk_FreeTempMemory, cvar_s::integer, R_GammaCorrect(), RB_ReadPixels(), RE_SaveJPG(), and ri.
Referenced by RB_TakeScreenshotCmd().
const void* RB_TakeVideoFrameCmd (const void * data)
References AVI_LINE_PADDING, videoFrameCommand_t::captureBuffer, refimport_t::CL_WriteAVIVideoFrame, Com_Memset, glconfig_t::deviceSupportsGamma, videoFrameCommand_t::encodeBuffer, videoFrameCommand_t::height, cvar_s::integer, videoFrameCommand_t::motionJpeg, PAD, PADP, qglGetIntegerv, qglReadPixels, R_GammaCorrect(), RE_SaveJPGToBuffer(), ri, and videoFrameCommand_t::width.
Referenced by RB_ExecuteRenderCommands().
void RE_EndRegistration (void)
References R_SyncRenderThread(), RB_ShowImages(), ri, and refimport_t::Sys_LowPhysicalMemory.
Referenced by GetRefAPI().
void RE_Shutdown (qboolean destroyWindow)
References refimport_t::Cmd_RemoveCommand, GLimp_Shutdown(), PRINT_ALL, qfalse, R_DeleteTextures(), R_DoneFreeType(), R_ShutdownCommandBuffers(), R_SyncRenderThread(), trGlobals_t::registered, ri, and tr.
Referenced by GetRefAPI().
Variable Documentation
float displayAspect = 0.0f
Referenced by GLimp_CompareModes(), and GLimp_SetMode().
glconfig_t glConfig
Referenced by CollapseMultitexture(), FinishShader(), GL_TextureMode(), GLimp_HaveExtension(), GLimp_Init(), GLimp_InitExtensions(), GLimp_SetGamma(), GLimp_SetMode(), GLimp_Shutdown(), R_InitCommandBuffers(), R_IssueRenderCommands(), R_LightScaleTexture(), R_LoadLightmaps(), R_PerformanceCounters(), R_SetColorMappings(), R_ShutdownCommandBuffers(), R_SyncRenderThread(), RB_IterateStagesGeneric(), RB_SetGL2D(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_ShowImages(), RB_SwapBuffers(), RE_AddDynamicLightToScene(), RE_AddPolyToScene(), RE_BeginFrame(), RE_BeginRegistration(), RE_RenderScene(), ShaderForShaderNum(), SurfIsOffscreen(), and Upload32().
glstate_t glState
Referenced by GL_Bind(), GL_BindMultitexture(), GL_Cull(), GL_SelectTexture(), GL_State(), GL_TexEnv(), GLimp_Shutdown(), R_ArrayElementDiscrete(), R_DeleteTextures(), RB_BeginDrawingView(), RB_SwapBuffers(), RB_TestFlare(), and RE_BeginFrame().
int max_polys
Referenced by R_Init(), and RE_AddPolyToScene().
int max_polyverts
Referenced by R_Init(), and RE_AddPolyToScene().
int maxAnisotropy = 0
Referenced by GLimp_InitExtensions(), and Upload32().
cvar_t* r_allowExtensions
Referenced by GLimp_InitExtensions().
cvar_t* r_ambientScale
cvar_t* r_anaglyphMode
Referenced by RE_BeginFrame().
cvar_t* r_aviMotionJpegQuality
cvar_t* r_clear
Referenced by RB_DrawBuffer().
cvar_t* r_colorbits
Referenced by GLimp_SetMode().
cvar_t* r_colorMipLevels
Referenced by Upload32().
cvar_t* r_customheight
cvar_t* r_customPixelAspect
cvar_t* r_customwidth
cvar_t* r_debugLight
cvar_t* r_debugSort
Referenced by RB_EndSurface().
cvar_t* r_debugSurface
Referenced by R_DebugGraphics().
cvar_t* r_depthbits
Referenced by GLimp_SetMode().
cvar_t* r_detailTextures
Referenced by FinishShader().
cvar_t* r_directedScale
cvar_t* r_dlightBacks
Referenced by ProjectDlightTexture_scalar().
cvar_t* r_drawBuffer
Referenced by GLimp_EndFrame(), and RE_BeginFrame().
cvar_t* r_drawentities
Referenced by R_AddEntitySurfaces().
cvar_t* r_drawSun
Referenced by RB_DrawSun().
cvar_t* r_drawworld
Referenced by R_AddWorldSurfaces().
cvar_t* r_dynamiclight
Referenced by RE_RenderScene().
cvar_t* r_ext_compiled_vertex_array
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_compressed_textures
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_max_anisotropy
Referenced by Upload32().
cvar_t* r_ext_multisample
Referenced by GLimp_SetMode().
cvar_t* r_ext_multitexture
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_texture_env_add
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_texture_filter_anisotropic
Referenced by GLimp_InitExtensions().
cvar_t* r_facePlaneCull
Referenced by R_CullSurface().
cvar_t* r_fastsky
Referenced by R_MirrorViewBySurface(), RB_BeginDrawingView(), and RB_StageIteratorSky().
cvar_t* r_finish
Referenced by RB_BeginDrawingView().
cvar_t* r_flareCoeff
Referenced by RB_RenderFlares().
cvar_t* r_flareFade
Referenced by RB_TestFlare().
cvar_t* r_flares
Referenced by RB_AddDlightFlares(), RB_RenderFlares(), and RB_SurfaceFlare().
cvar_t* r_flareSize
Referenced by RB_RenderFlare().
cvar_t* r_fullbright
Referenced by ShaderForShaderNum().
cvar_t* r_fullscreen
Referenced by GLimp_EndFrame(), GLimp_Init(), and GLimp_StartDriverAndSetMode().
cvar_t* r_gamma
Referenced by R_SetColorMappings(), and RE_BeginFrame().
cvar_t* r_greyscale
Referenced by ComputeColors(), ProjectDlightTexture_scalar(), and Upload32().
cvar_t* r_ignore
cvar_t* r_ignoreFastPath
Referenced by ComputeStageIteratorFunc().
cvar_t* r_ignoreGLErrors
Referenced by RE_BeginFrame().
cvar_t* r_ignorehwgamma
Referenced by GLimp_SetGamma().
cvar_t* r_inGameVideo
cvar_t* r_intensity
Referenced by R_SetColorMappings().
cvar_t* r_lightmap
Referenced by DrawMultitextured(), R_LoadLightmaps(), RB_IterateStagesGeneric(), and RB_StageIteratorLightmappedMultitexture().
cvar_t* r_lockpvs
Referenced by R_MarkLeaves().
cvar_t* r_lodbias
Referenced by R_ComputeLOD().
cvar_t* r_lodCurveError
Referenced by LodErrorForVolume().
cvar_t* r_lodscale
Referenced by R_ComputeLOD().
cvar_t* r_logFile
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
cvar_t* r_mapOverBrightBits
Referenced by R_ColorShiftLightingBytes().
cvar_t* r_marksOnTriangleMeshes
Referenced by R_MarkFragments().
cvar_t* r_maxpolys
cvar_t* r_maxpolyverts
cvar_t* r_measureOverdraw
Referenced by RB_BeginDrawingView(), RB_SwapBuffers(), and RE_BeginFrame().
cvar_t* r_mode
Referenced by GLimp_Init().
cvar_t* r_nobind
Referenced by GL_Bind(), and GL_BindMultitexture().
cvar_t* r_noborder
Referenced by GLimp_Init().
cvar_t* r_nocull
Referenced by R_CullLocalBox(), R_CullPointAndRadius(), R_CullSurface(), and R_RecursiveWorldNode().
cvar_t* r_nocurves
Referenced by R_CullGrid().
cvar_t* r_noportals
Referenced by R_MirrorViewBySurface().
cvar_t* r_norefresh
Referenced by RE_RenderScene().
cvar_t* r_novis
Referenced by R_MarkLeaves().
cvar_t* r_offsetFactor
Referenced by RB_StageIteratorGeneric().
cvar_t* r_offsetUnits
Referenced by RB_StageIteratorGeneric().
cvar_t* r_overBrightBits
Referenced by R_SetColorMappings().
cvar_t* r_picmip
Referenced by Upload32().
cvar_t* r_portalOnly
Referenced by R_SortDrawSurfs().
cvar_t* r_primitives
Referenced by R_DrawElements().
cvar_t* r_printShaders
Referenced by R_FindShader().
cvar_t* r_railCoreWidth
Referenced by RB_SurfaceRailCore().
cvar_t* r_railSegmentLength
Referenced by RB_SurfaceRailRings().
cvar_t* r_railWidth
Referenced by DoRailDiscs().
cvar_t* r_roundImagesDown
Referenced by Upload32().
cvar_t* r_saveFontData
Referenced by RE_RegisterFont().
cvar_t* r_screenshotJpegQuality
cvar_t* r_shadows
Referenced by R_AddIQMSurfaces(), R_AddMD3Surfaces(), RB_BeginDrawingView(), RB_ShadowFinish(), and RE_BeginFrame().
cvar_t* r_showcluster
Referenced by R_MarkLeaves().
cvar_t* r_showImages
Referenced by RB_ClearDepth(), RB_ShowImages(), and RB_SwapBuffers().
cvar_t* r_shownormals
Referenced by RB_EndSurface().
cvar_t* r_showsky
Referenced by RB_StageIteratorSky().
cvar_t* r_showSmp
Referenced by R_IssueRenderCommands().
cvar_t* r_showtris
Referenced by RB_EndSurface().
cvar_t* r_simpleMipMaps
Referenced by R_MipMap().
cvar_t* r_singleShader
Referenced by ParseFace(), ParseFlare(), ParseMesh(), and ParseTriSurf().
cvar_t* r_skipBackEnd
Referenced by R_IssueRenderCommands().
cvar_t* r_smp
Referenced by R_FindShader(), R_InitCommandBuffers(), R_ToggleSmpFrame(), RB_ExecuteRenderCommands(), and RE_RegisterShaderFromImage().
cvar_t* r_speeds
Referenced by R_PerformanceCounters(), and RE_StretchRaw().
cvar_t* r_stencilbits
Referenced by GLimp_SetMode().
cvar_t* r_stereoEnabled
Referenced by GLimp_SetMode().
cvar_t* r_stereoSeparation
Referenced by R_SetupProjection().
cvar_t* r_subdivisions
cvar_t* r_swapInterval
Referenced by GLimp_SetMode().
cvar_t* r_texturebits
Referenced by Upload32().
cvar_t* r_textureMode
Referenced by RE_BeginFrame().
cvar_t* r_uiFullScreen
Referenced by FinishShader(), and RB_IterateStagesGeneric().
cvar_t* r_verbose
cvar_t* r_vertexLight
Referenced by FinishShader(), R_LoadEntities(), R_LoadLightmaps(), RB_IterateStagesGeneric(), RE_RenderScene(), and ShaderForShaderNum().
vidmode_t r_vidModes[]
Initial value:
{
        { "Mode  0: 320x240",           320,    240,    1 },
        { "Mode  1: 400x300",           400,    300,    1 },
        { "Mode  2: 512x384",           512,    384,    1 },
        { "Mode  3: 640x480",           640,    480,    1 },
        { "Mode  4: 800x600",           800,    600,    1 },
        { "Mode  5: 960x720",           960,    720,    1 },
        { "Mode  6: 1024x768",          1024,   768,    1 },
        { "Mode  7: 1152x864",          1152,   864,    1 },
        { "Mode  8: 1280x1024",         1280,   1024,   1 },
        { "Mode  9: 1600x1200",         1600,   1200,   1 },
        { "Mode 10: 2048x1536",         2048,   1536,   1 },
        { "Mode 11: 856x480 (wide)",856,        480,    1 }
}
cvar_t* r_znear
Referenced by R_SetupProjectionZ(), and RB_RenderDrawSurfList().
cvar_t* r_zproj
Referenced by R_RenderView().
int s_numVidModes = ARRAY_LEN(r_vidModes) [static]
Referenced by R_GetModeInfo(), and R_ModeList_f().
qboolean textureFilterAnisotropic = qfalse
Referenced by GLimp_InitExtensions(), and Upload32().