ioquake3: code/renderer/tr_animation.c File Reference
tr_animation.c File Reference
#include "tr_local.h"
Functions
void R_AddAnimSurfaces (trRefEntity_t *ent)
void RB_SurfaceAnim (md4Surface_t *surface)
Function Documentation
void R_AddAnimSurfaces (trRefEntity_t * ent)
References trGlobals_t::currentModel, model_s::modelData, md4LOD_t::numSurfaces, md4Header_t::ofsLODs, md4LOD_t::ofsSurfaces, qfalse, R_AddDrawSurf(), R_GetShaderByHandle(), shader, md4Surface_t::shaderIndex, and tr.
Referenced by R_AddEntitySurfaces().
void RB_SurfaceAnim (md4Surface_t * surface)
References backEnd, refEntity_t::backlerp, md4Weight_t::boneIndex, md4Frame_t::bones, md4Weight_t::boneWeight, backEndState_t::currentEntity, DotProduct, trRefEntity_t::e, refEntity_t::frame, md4Bone_t::matrix, MD4_MAX_BONES, md4Vertex_t::normal, md4Header_t::numBones, shaderCommands_s::numIndexes, md4Surface_t::numTriangles, shaderCommands_s::numVertexes, md4Surface_t::numVerts, md4Vertex_t::numWeights, md4Weight_t::offset, md4Header_t::ofsFrames, md4Surface_t::ofsHeader, md4Surface_t::ofsTriangles, md4Surface_t::ofsVerts, refEntity_t::oldframe, RB_CheckOverflow(), tess, md4Vertex_t::texCoords, VectorClear, and md4Vertex_t::weights.