ioquake3: code/renderer/tr_local.h File Reference
tr_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qfiles.h"
#include "../qcommon/qcommon.h"
#include "tr_public.h"
#include "qgl.h"
#include "iqm.h"
Data Structures
struct dlight_s
struct trRefEntity_t
struct orientationr_t
struct image_s
struct waveForm_t
struct deformStage_t
struct texModInfo_t
struct textureBundle_t
struct shaderStage_t
struct skyParms_t
struct fogParms_t
struct shader_s
struct shaderState_s
struct trRefdef_t
struct skinSurface_t
struct skin_s
struct fog_t
struct viewParms_t
struct drawSurf_s
struct srfPoly_s
struct srfDisplayList_s
struct srfFlare_s
struct srfGridMesh_s
struct srfSurfaceFace_t
struct srfTriangles_t
struct iqmData_t
struct srfIQModel_s
struct msurface_s
struct mnode_s
struct bmodel_t
struct world_t
struct model_s
struct frontEndCounters_t
struct glstate_t
struct backEndCounters_t
struct backEndState_t
struct trGlobals_t
struct stageVars
struct shaderCommands_s
struct renderCommandList_t
struct setColorCommand_t
struct drawBufferCommand_t
struct subImageCommand_t
struct swapBuffersCommand_t
struct endFrameCommand_t
struct stretchPicCommand_t
struct drawSurfsCommand_t
struct screenshotCommand_t
struct videoFrameCommand_t
struct colorMaskCommand_t
struct clearDepthCommand_t
struct backEndData_t
Defines
#define GL_INDEX_TYPE GL_UNSIGNED_INT
#define SMP_FRAMES 2
#define SHADERNUM_BITS 14
#define MAX_SHADERS (1<<SHADERNUM_BITS)
#define MAX_STATES_PER_SHADER 32
#define MAX_STATE_NAME 32
#define MAX_SHADER_STAGES 8
#define TR_MAX_TEXMODS 4
#define MAX_SHADER_DEFORMS 3
#define MAX_IMAGE_ANIMATIONS 8
#define NUM_TEXTURE_BUNDLES 2
#define LIGHTMAP_2D -4
#define LIGHTMAP_BY_VERTEX -3
#define LIGHTMAP_WHITEIMAGE -2
#define LIGHTMAP_NONE -1
#define MAX_FACE_POINTS 64
#define MAX_PATCH_SIZE 32
#define MAX_GRID_SIZE 65
#define VERTEXSIZE 8
#define SIDE_FRONT 0
#define SIDE_BACK 1
#define SIDE_ON 2
#define CONTENTS_NODE -1
#define MAX_MOD_KNOWN 1024
#define MAX_DRAWIMAGES 2048
#define MAX_SKINS 1024
#define MAX_DRAWSURFS 0x10000
#define DRAWSURF_MASK (MAX_DRAWSURFS-1)
#define QSORT_FOGNUM_SHIFT 2
#define QSORT_ENTITYNUM_SHIFT 7
#define QSORT_SHADERNUM_SHIFT (QSORT_ENTITYNUM_SHIFT+ENTITYNUM_BITS)
#define FOG_TABLE_SIZE 256
#define FUNCTABLE_SIZE 1024
#define FUNCTABLE_SIZE2 10
#define FUNCTABLE_MASK (FUNCTABLE_SIZE-1)
#define FLARE_STDCOEFF "150"
#define CULL_IN 0
#define CULL_CLIP 1
#define CULL_OUT 2
#define GLS_SRCBLEND_ZERO 0x00000001
#define GLS_SRCBLEND_ONE 0x00000002
#define GLS_SRCBLEND_DST_COLOR 0x00000003
#define GLS_SRCBLEND_ONE_MINUS_DST_COLOR 0x00000004
#define GLS_SRCBLEND_SRC_ALPHA 0x00000005
#define GLS_SRCBLEND_ONE_MINUS_SRC_ALPHA 0x00000006
#define GLS_SRCBLEND_DST_ALPHA 0x00000007
#define GLS_SRCBLEND_ONE_MINUS_DST_ALPHA 0x00000008
#define GLS_SRCBLEND_ALPHA_SATURATE 0x00000009
#define GLS_SRCBLEND_BITS 0x0000000f
#define GLS_DSTBLEND_ZERO 0x00000010
#define GLS_DSTBLEND_ONE 0x00000020
#define GLS_DSTBLEND_SRC_COLOR 0x00000030
#define GLS_DSTBLEND_ONE_MINUS_SRC_COLOR 0x00000040
#define GLS_DSTBLEND_SRC_ALPHA 0x00000050
#define GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA 0x00000060
#define GLS_DSTBLEND_DST_ALPHA 0x00000070
#define GLS_DSTBLEND_ONE_MINUS_DST_ALPHA 0x00000080
#define GLS_DSTBLEND_BITS 0x000000f0
#define GLS_DEPTHMASK_TRUE 0x00000100
#define GLS_POLYMODE_LINE 0x00001000
#define GLS_DEPTHTEST_DISABLE 0x00010000
#define GLS_DEPTHFUNC_EQUAL 0x00020000
#define GLS_ATEST_GT_0 0x10000000
#define GLS_ATEST_LT_80 0x20000000
#define GLS_ATEST_GE_80 0x40000000
#define GLS_ATEST_BITS 0x70000000
#define GLS_DEFAULT GLS_DEPTHMASK_TRUE
#define RB_CHECKOVERFLOW(v, i) if (tess.numVertexes + (v) >= SHADER_MAX_VERTEXES || tess.numIndexes + (i) >= SHADER_MAX_INDEXES) {RB_CheckOverflow(v,i);}
#define PATCH_STITCHING
#define MAX_RENDER_COMMANDS 0x40000
#define MAX_POLYS 600
#define MAX_POLYVERTS 3000
Typedefs
typedef unsigned int glIndex_t
typedef struct dlight_s dlight_t
typedef struct image_s image_t
typedef struct shader_s shader_t
typedef struct shaderState_s shaderState_t
typedef struct skin_s skin_t
typedef struct drawSurf_s drawSurf_t
typedef struct srfPoly_s srfPoly_t
typedef struct srfDisplayList_s srfDisplayList_t
typedef struct srfFlare_s srfFlare_t
typedef struct srfGridMesh_s srfGridMesh_t
typedef struct srfIQModel_s srfIQModel_t
typedef struct msurface_s msurface_t
typedef struct mnode_s mnode_t
typedef struct model_s model_t
typedef byte color4ub_t [4]
typedef struct stageVars stageVars_t
typedef struct shaderCommands_s shaderCommands_t
Enumerations
enum shaderSort_t {
SS_BAD, SS_PORTAL, SS_ENVIRONMENT, SS_OPAQUE,
SS_DECAL, SS_SEE_THROUGH, SS_BANNER, SS_FOG,
SS_UNDERWATER, SS_BLEND0, SS_BLEND1, SS_BLEND2,
SS_BLEND3, SS_BLEND6, SS_STENCIL_SHADOW, SS_ALMOST_NEAREST,
SS_NEAREST
}
enum genFunc_t {
GF_NONE, GF_SIN, GF_SQUARE, GF_TRIANGLE,
GF_SAWTOOTH, GF_INVERSE_SAWTOOTH, GF_NOISE
}
enum deform_t {
DEFORM_NONE, DEFORM_WAVE, DEFORM_NORMALS, DEFORM_BULGE,
DEFORM_MOVE, DEFORM_PROJECTION_SHADOW, DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2,
DEFORM_TEXT0, DEFORM_TEXT1, DEFORM_TEXT2, DEFORM_TEXT3,
DEFORM_TEXT4, DEFORM_TEXT5, DEFORM_TEXT6, DEFORM_TEXT7
}
enum alphaGen_t {
AGEN_IDENTITY, AGEN_SKIP, AGEN_ENTITY, AGEN_ONE_MINUS_ENTITY,
AGEN_VERTEX, AGEN_ONE_MINUS_VERTEX, AGEN_LIGHTING_SPECULAR, AGEN_WAVEFORM,
AGEN_PORTAL, AGEN_CONST
}
enum colorGen_t {
CGEN_BAD, CGEN_IDENTITY_LIGHTING, CGEN_IDENTITY, CGEN_ENTITY,
CGEN_ONE_MINUS_ENTITY, CGEN_EXACT_VERTEX, CGEN_VERTEX, CGEN_ONE_MINUS_VERTEX,
CGEN_WAVEFORM, CGEN_LIGHTING_DIFFUSE, CGEN_FOG, CGEN_CONST
}
enum texCoordGen_t {
TCGEN_BAD, TCGEN_IDENTITY, TCGEN_LIGHTMAP, TCGEN_TEXTURE,
TCGEN_ENVIRONMENT_MAPPED, TCGEN_FOG, TCGEN_VECTOR
}
enum acff_t { ACFF_NONE, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, ACFF_MODULATE_ALPHA }
enum texMod_t {
TMOD_NONE, TMOD_TRANSFORM, TMOD_TURBULENT, TMOD_SCROLL,
TMOD_SCALE, TMOD_STRETCH, TMOD_ROTATE, TMOD_ENTITY_TRANSLATE
}
enum cullType_t { CT_FRONT_SIDED, CT_BACK_SIDED, CT_TWO_SIDED }
enum fogPass_t { FP_NONE, FP_EQUAL, FP_LE }
enum surfaceType_t {
SF_BAD, SF_SKIP, SF_FACE, SF_GRID,
SF_TRIANGLES, SF_POLY, SF_MD3, SF_MD4,
SF_IQM, SF_FLARE, SF_ENTITY, SF_DISPLAY_LIST,
SF_NUM_SURFACE_TYPES, SF_MAX = 0x7fffffff
}
enum modtype_t {
MOD_BAD, MOD_BRUSH, MOD_MESH, MOD_MD4,
MOD_IQM
}
enum renderCommand_t {
RC_END_OF_LIST, RC_SET_COLOR, RC_STRETCH_PIC, RC_DRAW_SURFS,
RC_DRAW_BUFFER, RC_SWAP_BUFFERS, RC_SCREENSHOT, RC_VIDEOFRAME,
RC_COLORMASK, RC_CLEARDEPTH
}
Functions
void R_ModelInit (void)
model_t * R_GetModelByHandle (qhandle_t hModel)
int R_LerpTag (orientation_t *tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char *tagName)
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
void R_Modellist_f (void)
float R_NoiseGet4f (float x, float y, float z, float t)
void R_NoiseInit (void)
void R_SwapBuffers (int)
void R_RenderView (viewParms_t *parms)
void R_AddMD3Surfaces (trRefEntity_t *e)
void R_AddNullModelSurfaces (trRefEntity_t *e)
void R_AddBeamSurfaces (trRefEntity_t *e)
void R_AddRailSurfaces (trRefEntity_t *e, qboolean isUnderwater)
void R_AddLightningBoltSurfaces (trRefEntity_t *e)
void R_AddPolygonSurfaces (void)
void R_DecomposeSort (unsigned sort, int *entityNum, shader_t **shader, int *fogNum, int *dlightMap)
void R_AddDrawSurf (surfaceType_t *surface, shader_t *shader, int fogIndex, int dlightMap)
void R_LocalNormalToWorld (vec3_t local, vec3_t world)
void R_LocalPointToWorld (vec3_t local, vec3_t world)
int R_CullLocalBox (vec3_t bounds[2])
int R_CullPointAndRadius (vec3_t origin, float radius)
int R_CullLocalPointAndRadius (vec3_t origin, float radius)
void R_SetupProjection (viewParms_t *dest, float zProj, qboolean computeFrustum)
void R_RotateForEntity (const trRefEntity_t *ent, const viewParms_t *viewParms, orientationr_t *or)
void GL_Bind (image_t *image)
void GL_SetDefaultState (void)
void GL_SelectTexture (int unit)
void GL_TextureMode (const char *string)
void GL_CheckErrors (void)
void GL_State (unsigned long stateVector)
void GL_TexEnv (int env)
void GL_Cull (int cullType)
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
void RE_BeginFrame (stereoFrame_t stereoFrame)
void RE_BeginRegistration (glconfig_t *glconfig)
void RE_LoadWorldMap (const char *mapname)
void RE_SetWorldVisData (const byte *vis)
qhandle_t RE_RegisterModel (const char *name)
qhandle_t RE_RegisterSkin (const char *name)
void RE_Shutdown (qboolean destroyWindow)
qboolean R_GetEntityToken (char *buffer, int size)
model_t * R_AllocModel (void)
void R_Init (void)
image_t * R_FindImageFile (const char *name, qboolean mipmap, qboolean allowPicmip, int glWrapClampMode)
image_t * R_CreateImage (const char *name, const byte *pic, int width, int height, qboolean mipmap, qboolean allowPicmip, int wrapClampMode)
qboolean R_GetModeInfo (int *width, int *height, float *windowAspect, int mode)
void R_SetColorMappings (void)
void R_GammaCorrect (byte *buffer, int bufSize)
void R_ImageList_f (void)
void R_SkinList_f (void)
const void * RB_TakeScreenshotCmd (const void *data)
void R_ScreenShot_f (void)
void R_InitFogTable (void)
float R_FogFactor (float s, float t)
void R_InitImages (void)
void R_DeleteTextures (void)
int R_SumOfUsedImages (void)
void R_InitSkins (void)
skin_t * R_GetSkinByHandle (qhandle_t hSkin)
int R_ComputeLOD (trRefEntity_t *ent)
const void * RB_TakeVideoFrameCmd (const void *data)
qhandle_t RE_RegisterShaderLightMap (const char *name, int lightmapIndex)
qhandle_t RE_RegisterShader (const char *name)
qhandle_t RE_RegisterShaderNoMip (const char *name)
qhandle_t RE_RegisterShaderFromImage (const char *name, int lightmapIndex, image_t *image, qboolean mipRawImage)
shader_t * R_FindShader (const char *name, int lightmapIndex, qboolean mipRawImage)
shader_t * R_GetShaderByHandle (qhandle_t hShader)
shader_t * R_GetShaderByState (int index, long *cycleTime)
shader_t * R_FindShaderByName (const char *name)
void R_InitShaders (void)
void R_ShaderList_f (void)
void R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
void GLimp_Init (void)
void GLimp_Shutdown (void)
void GLimp_EndFrame (void)
qboolean GLimp_SpawnRenderThread (void(*function)(void))
void * GLimp_RendererSleep (void)
void GLimp_FrontEndSleep (void)
void GLimp_WakeRenderer (void *data)
void GLimp_LogComment (char *comment)
void GLimp_Minimize (void)
void GLimp_SetGamma (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
void RB_BeginSurface (shader_t *shader, int fogNum)
void RB_EndSurface (void)
void RB_CheckOverflow (int verts, int indexes)
void RB_StageIteratorGeneric (void)
void RB_StageIteratorSky (void)
void RB_StageIteratorVertexLitTexture (void)
void RB_StageIteratorLightmappedMultitexture (void)
void RB_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, byte *color)
void RB_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, byte *color, float s1, float t1, float s2, float t2)
void RB_ShowImages (void)
void R_AddBrushModelSurfaces (trRefEntity_t *e)
void R_AddWorldSurfaces (void)
qboolean R_inPVS (const vec3_t p1, const vec3_t p2)
void R_ClearFlares (void)
void RB_AddFlare (void *surface, int fogNum, vec3_t point, vec3_t color, vec3_t normal)
void RB_AddDlightFlares (void)
void RB_RenderFlares (void)
void R_DlightBmodel (bmodel_t *bmodel)
void R_SetupEntityLighting (const trRefdef_t *refdef, trRefEntity_t *ent)
void R_TransformDlights (int count, dlight_t *dl, orientationr_t *or)
int R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void RB_ShadowTessEnd (void)
void RB_ShadowFinish (void)
void RB_ProjectionShadowDeform (void)
void R_BuildCloudData (shaderCommands_t *shader)
void R_InitSkyTexCoords (float cloudLayerHeight)
void R_DrawSkyBox (shaderCommands_t *shader)
void RB_DrawSun (void)
void RB_ClipSkyPolygons (shaderCommands_t *shader)
srfGridMesh_t * R_SubdividePatchToGrid (int width, int height, drawVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
srfGridMesh_t * R_GridInsertColumn (srfGridMesh_t *grid, int column, int row, vec3_t point, float loderror)
srfGridMesh_t * R_GridInsertRow (srfGridMesh_t *grid, int row, int column, vec3_t point, float loderror)
void R_FreeSurfaceGridMesh (srfGridMesh_t *grid)
int R_MarkFragments (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
void R_ToggleSmpFrame (void)
void RE_ClearScene (void)
void RE_AddRefEntityToScene (const refEntity_t *ent)
void RE_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int num)
void RE_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
void RE_AddAdditiveLightToScene (const vec3_t org, float intensity, float r, float g, float b)
void RE_RenderScene (const refdef_t *fd)
void R_AddAnimSurfaces (trRefEntity_t *ent)
void RB_SurfaceAnim (md4Surface_t *surfType)
qboolean R_LoadIQM (model_t *mod, void *buffer, int filesize, const char *name)
void R_AddIQMSurfaces (trRefEntity_t *ent)
void RB_IQMSurfaceAnim (surfaceType_t *surface)
int R_IQMLerpTag (orientation_t *tag, iqmData_t *data, int startFrame, int endFrame, float frac, const char *tagName)
void R_LoadBMP (const char *name, byte **pic, int *width, int *height)
void R_LoadJPG (const char *name, byte **pic, int *width, int *height)
void R_LoadPCX (const char *name, byte **pic, int *width, int *height)
void R_LoadPNG (const char *name, byte **pic, int *width, int *height)
void R_LoadTGA (const char *name, byte **pic, int *width, int *height)
void R_TransformModelToClip (const vec3_t src, const float *modelMatrix, const float *projectionMatrix, vec4_t eye, vec4_t dst)
void R_TransformClipToWindow (const vec4_t clip, const viewParms_t *view, vec4_t normalized, vec4_t window)
void RB_DeformTessGeometry (void)
void RB_CalcEnvironmentTexCoords (float *dstTexCoords)
void RB_CalcFogTexCoords (float *dstTexCoords)
void RB_CalcScrollTexCoords (const float scroll[2], float *dstTexCoords)
void RB_CalcRotateTexCoords (float rotSpeed, float *dstTexCoords)
void RB_CalcScaleTexCoords (const float scale[2], float *dstTexCoords)
void RB_CalcTurbulentTexCoords (const waveForm_t *wf, float *dstTexCoords)
void RB_CalcTransformTexCoords (const texModInfo_t *tmi, float *dstTexCoords)
void RB_CalcModulateColorsByFog (unsigned char *dstColors)
void RB_CalcModulateAlphasByFog (unsigned char *dstColors)
void RB_CalcModulateRGBAsByFog (unsigned char *dstColors)
void RB_CalcWaveAlpha (const waveForm_t *wf, unsigned char *dstColors)
void RB_CalcWaveColor (const waveForm_t *wf, unsigned char *dstColors)
void RB_CalcAlphaFromEntity (unsigned char *dstColors)
void RB_CalcAlphaFromOneMinusEntity (unsigned char *dstColors)
void RB_CalcStretchTexCoords (const waveForm_t *wf, float *texCoords)
void RB_CalcColorFromEntity (unsigned char *dstColors)
void RB_CalcColorFromOneMinusEntity (unsigned char *dstColors)
void RB_CalcSpecularAlpha (unsigned char *alphas)
void RB_CalcDiffuseColor (unsigned char *colors)
void RB_RenderThread (void)
void RB_ExecuteRenderCommands (const void *data)
void * R_GetCommandBuffer (int bytes)
void R_InitCommandBuffers (void)
void R_ShutdownCommandBuffers (void)
void R_SyncRenderThread (void)
void R_AddDrawSurfCmd (drawSurf_t *drawSurfs, int numDrawSurfs)
void RE_SetColor (const float *rgba)
void RE_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void RE_EndFrame (int *frontEndMsec, int *backEndMsec)
void RE_SaveJPG (char *filename, int quality, int image_width, int image_height, unsigned char *image_buffer, int padding)
size_t RE_SaveJPGToBuffer (byte *buffer, size_t bufSize, int quality, int image_width, int image_height, byte *image_buffer, int padding)
void RE_TakeVideoFrame (int width, int height, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
void R_InitFreeType (void)
void R_DoneFreeType (void)
void RE_RegisterFont (const char *fontName, int pointSize, fontInfo_t *font)
Variables
void(* rb_surfaceTable [SF_NUM_SURFACE_TYPES])(void *)
refimport_t ri
int gl_filter_min
int gl_filter_max
backEndState_t backEnd
trGlobals_t tr
glconfig_t glConfig
glstate_t glState
qboolean textureFilterAnisotropic
int maxAnisotropy
float displayAspect
cvar_t * r_flareSize
cvar_t * r_flareFade
cvar_t * r_flareCoeff
cvar_t * r_railWidth
cvar_t * r_railCoreWidth
cvar_t * r_railSegmentLength
cvar_t * r_ignore
cvar_t * r_verbose
cvar_t * r_ignoreFastPath
cvar_t * r_znear
cvar_t * r_zproj
cvar_t * r_stereoSeparation
cvar_t * r_stencilbits
cvar_t * r_depthbits
cvar_t * r_colorbits
cvar_t * r_texturebits
cvar_t * r_ext_multisample
cvar_t * r_measureOverdraw
cvar_t * r_lodbias
cvar_t * r_lodscale
cvar_t * r_primitives
cvar_t * r_inGameVideo
cvar_t * r_fastsky
cvar_t * r_drawSun
cvar_t * r_dynamiclight
cvar_t * r_dlightBacks
cvar_t * r_norefresh
cvar_t * r_drawentities
cvar_t * r_drawworld
cvar_t * r_speeds
cvar_t * r_detailTextures
cvar_t * r_novis
cvar_t * r_nocull
cvar_t * r_facePlaneCull
cvar_t * r_nocurves
cvar_t * r_showcluster
cvar_t * r_mode
cvar_t * r_fullscreen
cvar_t * r_noborder
cvar_t * r_gamma
cvar_t * r_ignorehwgamma
cvar_t * r_allowExtensions
cvar_t * r_ext_compressed_textures
cvar_t * r_ext_multitexture
cvar_t * r_ext_compiled_vertex_array
cvar_t * r_ext_texture_env_add
cvar_t * r_ext_texture_filter_anisotropic
cvar_t * r_ext_max_anisotropy
cvar_t * r_nobind
cvar_t * r_singleShader
cvar_t * r_roundImagesDown
cvar_t * r_colorMipLevels
cvar_t * r_picmip
cvar_t * r_finish
cvar_t * r_drawBuffer
cvar_t * r_swapInterval
cvar_t * r_textureMode
cvar_t * r_offsetFactor
cvar_t * r_offsetUnits
cvar_t * r_fullbright
cvar_t * r_lightmap
cvar_t * r_vertexLight
cvar_t * r_uiFullScreen
cvar_t * r_logFile
cvar_t * r_showtris
cvar_t * r_showsky
cvar_t * r_shownormals
cvar_t * r_clear
cvar_t * r_shadows
cvar_t * r_flares
cvar_t * r_intensity
cvar_t * r_lockpvs
cvar_t * r_noportals
cvar_t * r_portalOnly
cvar_t * r_subdivisions
cvar_t * r_lodCurveError
cvar_t * r_smp
cvar_t * r_showSmp
cvar_t * r_skipBackEnd
cvar_t * r_stereoEnabled
cvar_t * r_anaglyphMode
cvar_t * r_greyscale
cvar_t * r_ignoreGLErrors
cvar_t * r_overBrightBits
cvar_t * r_mapOverBrightBits
cvar_t * r_debugSurface
cvar_t * r_simpleMipMaps
cvar_t * r_showImages
cvar_t * r_debugSort
cvar_t * r_printShaders
cvar_t * r_saveFontData
cvar_t * r_marksOnTriangleMeshes
shaderCommands_t tess
int max_polys
int max_polyverts
backEndData_t * backEndData [SMP_FRAMES]
volatile renderCommandList_t * renderCommandList
volatile qboolean renderThreadActive
Define Documentation
#define CONTENTS_NODE -1
Referenced by R_LoadNodesAndLeafs().
#define CULL_CLIP 1
Referenced by R_CullGrid(), R_CullIQM(), R_CullLocalBox(), R_CullModel(), and R_CullPointAndRadius().
#define CULL_IN 0
Referenced by R_CullGrid(), R_CullIQM(), R_CullLocalBox(), R_CullModel(), and R_CullPointAndRadius().
#define CULL_OUT 2
Referenced by R_AddBrushModelSurfaces(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_CullGrid(), R_CullIQM(), R_CullLocalBox(), R_CullModel(), R_CullPointAndRadius(), and R_CullTriSurf().
#define DRAWSURF_MASK (MAX_DRAWSURFS-1)
Referenced by R_AddDrawSurf().
#define FLARE_STDCOEFF "150"
Referenced by R_Register(), and RB_RenderFlares().
#define FOG_TABLE_SIZE 256
Referenced by R_FogFactor(), and R_InitFogTable().
#define FUNCTABLE_MASK (FUNCTABLE_SIZE-1)
Referenced by LerpMeshVertexes_scalar(), R_SetupEntityLightingGrid(), RB_CalcBulgeVertexes(), RB_CalcRotateTexCoords(), and RB_CalcTurbulentTexCoords().
#define FUNCTABLE_SIZE 1024
Referenced by LerpMeshVertexes_scalar(), R_BindAnimatedImage(), R_Init(), R_SetupEntityLightingGrid(), RB_CalcBulgeVertexes(), RB_CalcRotateTexCoords(), and RB_CalcTurbulentTexCoords().
#define FUNCTABLE_SIZE2 10
Referenced by R_BindAnimatedImage().
#define GL_INDEX_TYPE GL_UNSIGNED_INT
Referenced by R_DrawElements().
#define GLS_ATEST_BITS 0x70000000
Referenced by GL_State().
#define GLS_ATEST_GE_80 0x40000000
Referenced by GL_State(), and NameToAFunc().
#define GLS_ATEST_GT_0 0x10000000
Referenced by GL_State(), and NameToAFunc().
#define GLS_ATEST_LT_80 0x20000000
Referenced by GL_State(), and NameToAFunc().
#define GLS_DEFAULT GLS_DEPTHMASK_TRUE
Referenced by CreateInternalShaders(), R_FindShader(), RB_BeginDrawingView(), RB_StageIteratorLightmappedMultitexture(), and RE_RegisterShaderFromImage().
#define GLS_DEPTHFUNC_EQUAL 0x00020000
Referenced by GL_State(), ParseStage(), ProjectDlightTexture_scalar(), and RB_FogPass().
#define GLS_DEPTHMASK_TRUE 0x00000100
Referenced by CollapseMultitexture(), DrawNormals(), DrawTris(), FinishShader(), GL_SetDefaultState(), GL_State(), ParseStage(), R_DebugPolygon(), RB_ShadowFinish(), and VertexLightingCollapse().
#define GLS_DEPTHTEST_DISABLE 0x00010000
Referenced by CreateExternalShaders(), GL_SetDefaultState(), GL_State(), R_FindShader(), RB_SetGL2D(), and RE_RegisterShaderFromImage().
#define GLS_DSTBLEND_BITS 0x000000f0
Referenced by CollapseMultitexture(), FinishShader(), GL_State(), and VertexLightingCollapse().
#define GLS_DSTBLEND_DST_ALPHA 0x00000070
Referenced by GL_State(), and NameToDstBlendMode().
#define GLS_DSTBLEND_ONE 0x00000020
Referenced by FinishShader(), GL_State(), NameToDstBlendMode(), ParseStage(), ProjectDlightTexture_scalar(), R_DebugPolygon(), and RB_SurfaceBeam().
#define GLS_DSTBLEND_ONE_MINUS_DST_ALPHA 0x00000080
Referenced by GL_State(), and NameToDstBlendMode().
#define GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA 0x00000060
Referenced by FinishShader(), GL_State(), NameToDstBlendMode(), ParseStage(), R_FindShader(), RB_FogPass(), RB_SetGL2D(), and RE_RegisterShaderFromImage().
#define GLS_DSTBLEND_ONE_MINUS_SRC_COLOR 0x00000040
Referenced by FinishShader(), GL_State(), and NameToDstBlendMode().
#define GLS_DSTBLEND_SRC_ALPHA 0x00000050
Referenced by GL_State(), and NameToDstBlendMode().
#define GLS_DSTBLEND_SRC_COLOR 0x00000030
Referenced by GL_State(), and NameToDstBlendMode().
#define GLS_DSTBLEND_ZERO 0x00000010
Referenced by GL_State(), NameToDstBlendMode(), ParseStage(), R_FindShader(), RB_ShadowFinish(), RB_ShadowTessEnd(), and RE_RegisterShaderFromImage().
#define GLS_POLYMODE_LINE 0x00001000
Referenced by DrawNormals(), DrawTris(), GL_State(), and R_DebugPolygon().
#define GLS_SRCBLEND_ALPHA_SATURATE 0x00000009
Referenced by GL_State(), and NameToSrcBlendMode().
#define GLS_SRCBLEND_BITS 0x0000000f
Referenced by CollapseMultitexture(), FinishShader(), GL_State(), and VertexLightingCollapse().
#define GLS_SRCBLEND_DST_ALPHA 0x00000007
Referenced by GL_State(), and NameToSrcBlendMode().
#define GLS_SRCBLEND_DST_COLOR 0x00000003
Referenced by GL_State(), NameToSrcBlendMode(), ParseStage(), ProjectDlightTexture_scalar(), R_FindShader(), RB_ShadowFinish(), and RE_RegisterShaderFromImage().
#define GLS_SRCBLEND_ONE 0x00000002
Referenced by FinishShader(), GL_State(), NameToSrcBlendMode(), ParseStage(), ProjectDlightTexture_scalar(), R_DebugPolygon(), RB_ShadowTessEnd(), and RB_SurfaceBeam().
#define GLS_SRCBLEND_ONE_MINUS_DST_ALPHA 0x00000008
Referenced by GL_State(), and NameToSrcBlendMode().
#define GLS_SRCBLEND_ONE_MINUS_DST_COLOR 0x00000004
Referenced by GL_State(), and NameToSrcBlendMode().
#define GLS_SRCBLEND_ONE_MINUS_SRC_ALPHA 0x00000006
Referenced by GL_State(), and NameToSrcBlendMode().
#define GLS_SRCBLEND_SRC_ALPHA 0x00000005
Referenced by FinishShader(), GL_State(), NameToSrcBlendMode(), ParseStage(), R_FindShader(), RB_FogPass(), RB_SetGL2D(), and RE_RegisterShaderFromImage().
#define GLS_SRCBLEND_ZERO 0x00000001
Referenced by FinishShader(), GL_State(), and NameToSrcBlendMode().
#define LIGHTMAP_2D -4
Referenced by R_FindShader(), RE_RegisterFont(), RE_RegisterShader(), RE_RegisterShaderFromImage(), and RE_RegisterShaderNoMip().
#define LIGHTMAP_BY_VERTEX -3
Referenced by ParseFlare(), ParseTriSurf(), R_FindShader(), RE_RegisterShaderFromImage(), and ShaderForShaderNum().
#define LIGHTMAP_NONE -1
Referenced by CreateExternalShaders(), CreateInternalShaders(), FinishShader(), R_FindShader(), R_LoadFogs(), R_LoadIQM(), R_LoadMD3(), R_LoadMD4(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), and VertexLightingCollapse().
#define LIGHTMAP_WHITEIMAGE -2
Referenced by R_FindShader(), RE_RegisterShaderFromImage(), and ShaderForShaderNum().
#define MAX_DRAWIMAGES 2048
Referenced by R_CreateImage().
#define MAX_DRAWSURFS 0x10000
Referenced by R_RadixSort(), and R_SortDrawSurfs().
#define MAX_FACE_POINTS 64
Referenced by ParseFace().
#define MAX_GRID_SIZE 65
#define MAX_IMAGE_ANIMATIONS 8
Referenced by ParseStage().
#define MAX_MOD_KNOWN 1024
Referenced by R_AllocModel().
#define MAX_PATCH_SIZE 32
Referenced by ParseMesh().
#define MAX_POLYS 600
Referenced by R_Init(), and R_Register().
#define MAX_POLYVERTS 3000
Referenced by R_Init(), and R_Register().
#define MAX_RENDER_COMMANDS 0x40000
Referenced by R_GetCommandBuffer().
#define MAX_SHADER_DEFORMS 3
Referenced by ParseDeform().
#define MAX_SHADER_STAGES 8
Referenced by CollapseMultitexture(), FinishShader(), ParseShader(), R_BuildCloudData(), R_FindShader(), RB_IterateStagesGeneric(), RE_RegisterShaderFromImage(), and VertexLightingCollapse().
#define MAX_SHADERS (1<<SHADERNUM_BITS)
Referenced by FixRenderCommandList(), GeneratePermanentShader(), and R_DecomposeSort().
#define MAX_SKINS 1024
Referenced by RE_RegisterSkin().
#define MAX_STATE_NAME 32
#define MAX_STATES_PER_SHADER 32
#define NUM_TEXTURE_BUNDLES 2
Referenced by ComputeTexCoords(), and GeneratePermanentShader().
#define PATCH_STITCHING
#define QSORT_ENTITYNUM_SHIFT 7
Referenced by R_AddEntitySurfaces(), R_AddPolygonSurfaces(), R_AddWorldSurfaces(), and R_DecomposeSort().
#define QSORT_FOGNUM_SHIFT 2
Referenced by FixRenderCommandList(), R_AddDrawSurf(), and R_DecomposeSort().
#define QSORT_SHADERNUM_SHIFT (QSORT_ENTITYNUM_SHIFT+ENTITYNUM_BITS)
Referenced by FixRenderCommandList(), R_AddDrawSurf(), and R_DecomposeSort().
#define RB_CHECKOVERFLOW (v, i) if (tess.numVertexes + (v) >= SHADER_MAX_VERTEXES || tess.numIndexes + (i) >= SHADER_MAX_INDEXES) {RB_CheckOverflow(v,i);}
Referenced by DoRailDiscs(), RB_AddQuadStampExt(), RB_IQMSurfaceAnim(), RB_StretchPic(), RB_SurfaceFace(), RB_SurfaceMesh(), RB_SurfacePolychain(), and RB_SurfaceTriangles().
#define SHADERNUM_BITS 14
#define SIDE_BACK 1
#define SIDE_FRONT 0
#define SIDE_ON 2
#define SMP_FRAMES 2
#define TR_MAX_TEXMODS 4
Referenced by ComputeTexCoords(), and ParseTexMod().
#define VERTEXSIZE 8
Referenced by R_MarkFragments(), and RB_SurfaceFace().
Typedef Documentation
typedef byte color4ub_t[4]
typedef struct dlight_s dlight_t
typedef struct drawSurf_s drawSurf_t
typedef unsigned int glIndex_t
typedef struct image_s image_t
typedef struct mnode_s mnode_t
typedef struct model_s model_t
typedef struct msurface_s msurface_t
typedef struct shader_s shader_t
typedef struct shaderCommands_s shaderCommands_t
typedef struct shaderState_s shaderState_t
typedef struct skin_s skin_t
typedef struct srfDisplayList_s srfDisplayList_t
typedef struct srfFlare_s srfFlare_t
typedef struct srfGridMesh_s srfGridMesh_t
typedef struct srfIQModel_s srfIQModel_t
typedef struct srfPoly_s srfPoly_t
typedef struct stageVars stageVars_t
Enumeration Type Documentation
enum acff_t
Enumerator:
ACFF_NONE
ACFF_MODULATE_RGB
ACFF_MODULATE_RGBA
ACFF_MODULATE_ALPHA
enum alphaGen_t
Enumerator:
AGEN_IDENTITY
AGEN_SKIP
AGEN_ENTITY
AGEN_ONE_MINUS_ENTITY
AGEN_VERTEX
AGEN_ONE_MINUS_VERTEX
AGEN_LIGHTING_SPECULAR
AGEN_WAVEFORM
AGEN_PORTAL
AGEN_CONST
enum colorGen_t
Enumerator:
CGEN_BAD
CGEN_IDENTITY_LIGHTING
CGEN_IDENTITY
CGEN_ENTITY
CGEN_ONE_MINUS_ENTITY
CGEN_EXACT_VERTEX
CGEN_VERTEX
CGEN_ONE_MINUS_VERTEX
CGEN_WAVEFORM
CGEN_LIGHTING_DIFFUSE
CGEN_FOG
CGEN_CONST
enum cullType_t
Enumerator:
CT_FRONT_SIDED
CT_BACK_SIDED
CT_TWO_SIDED
enum deform_t
Enumerator:
DEFORM_NONE
DEFORM_WAVE
DEFORM_NORMALS
DEFORM_BULGE
DEFORM_MOVE
DEFORM_PROJECTION_SHADOW
DEFORM_AUTOSPRITE
DEFORM_AUTOSPRITE2
DEFORM_TEXT0
DEFORM_TEXT1
DEFORM_TEXT2
DEFORM_TEXT3
DEFORM_TEXT4
DEFORM_TEXT5
DEFORM_TEXT6
DEFORM_TEXT7
enum fogPass_t
Enumerator:
FP_NONE
FP_EQUAL
FP_LE
enum genFunc_t
Enumerator:
GF_NONE
GF_SIN
GF_SQUARE
GF_TRIANGLE
GF_SAWTOOTH
GF_INVERSE_SAWTOOTH
GF_NOISE
enum modtype_t
Enumerator:
MOD_BAD
MOD_BRUSH
MOD_MESH
MOD_MD4
MOD_IQM
enum renderCommand_t
Enumerator:
RC_END_OF_LIST
RC_SET_COLOR
RC_STRETCH_PIC
RC_DRAW_SURFS
RC_DRAW_BUFFER
RC_SWAP_BUFFERS
RC_SCREENSHOT
RC_VIDEOFRAME
RC_COLORMASK
RC_CLEARDEPTH
enum shaderSort_t
Enumerator:
SS_BAD
SS_PORTAL
SS_ENVIRONMENT
SS_OPAQUE
SS_DECAL
SS_SEE_THROUGH
SS_BANNER
SS_FOG
SS_UNDERWATER
SS_BLEND0
SS_BLEND1
SS_BLEND2
SS_BLEND3
SS_BLEND6
SS_STENCIL_SHADOW
SS_ALMOST_NEAREST
SS_NEAREST
enum surfaceType_t
Enumerator:
SF_BAD
SF_SKIP
SF_FACE
SF_GRID
SF_TRIANGLES
SF_POLY
SF_MD3
SF_MD4
SF_IQM
SF_FLARE
SF_ENTITY
SF_DISPLAY_LIST
SF_NUM_SURFACE_TYPES
SF_MAX
enum texCoordGen_t
Enumerator:
TCGEN_BAD
TCGEN_IDENTITY
TCGEN_LIGHTMAP
TCGEN_TEXTURE
TCGEN_ENVIRONMENT_MAPPED
TCGEN_FOG
TCGEN_VECTOR
enum texMod_t
Enumerator:
TMOD_NONE
TMOD_TRANSFORM
TMOD_TURBULENT
TMOD_SCROLL
TMOD_SCALE
TMOD_STRETCH
TMOD_ROTATE
TMOD_ENTITY_TRANSLATE
Function Documentation
void GL_Bind (image_t * image)
References glstate_t::currenttextures, glstate_t::currenttmu, trGlobals_t::defaultImage, trGlobals_t::dlightImage, trGlobals_t::frameCount, image_s::frameUsed, glState, cvar_s::integer, PRINT_WARNING, qglBindTexture, r_nobind, ri, image_s::texnum, and tr.
Referenced by DrawNormals(), DrawSkySide(), DrawTris(), GL_TextureMode(), ProjectDlightTexture_scalar(), R_BindAnimatedImage(), R_CreateImage(), R_DebugGraphics(), RB_FogPass(), RB_IterateStagesGeneric(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_ShowImages(), RB_SurfaceAxis(), RB_SurfaceBeam(), RE_StretchRaw(), and RE_UploadCinematic().
void GL_CheckErrors (void)
References Com_sprintf(), ERR_FATAL, cvar_s::integer, qglGetError, ri, and s.
Referenced by Upload32().
void GL_Cull (int cullType)
References CT_BACK_SIDED, CT_TWO_SIDED, glstate_t::faceCulling, glState, viewParms_t::isMirror, qglCullFace, qglDisable, qglEnable, and backEndState_t::viewParms.
Referenced by R_DebugGraphics(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
void GL_SelectTexture (int unit)
References glstate_t::currenttmu, ERR_DROP, GLimp_LogComment(), glState, qglActiveTextureARB, qglClientActiveTextureARB, and ri.
Referenced by DrawMultitextured(), GL_BindMultitexture(), GL_SetDefaultState(), R_CreateImage(), R_DeleteTextures(), and RB_StageIteratorLightmappedMultitexture().
void GL_SetDefaultState (void)
References GL_SelectTexture(), GL_TexEnv(), GL_TextureMode(), GLS_DEPTHMASK_TRUE, GLS_DEPTHTEST_DISABLE, glstate_t::glStateBits, qglActiveTextureARB, qglClearDepth, qglColor4f, qglCullFace, qglDepthFunc, qglDepthMask, qglDisable, qglEnable, qglEnableClientState, qglPolygonMode, qglShadeModel, and cvar_s::string.
Referenced by InitOpenGL().
void GL_State (unsigned long stateVector)
References ERR_DROP, GLS_ATEST_BITS, GLS_ATEST_GE_80, GLS_ATEST_GT_0, GLS_ATEST_LT_80, GLS_DEPTHFUNC_EQUAL, GLS_DEPTHMASK_TRUE, GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_BITS, GLS_DSTBLEND_DST_ALPHA, GLS_DSTBLEND_ONE, GLS_DSTBLEND_ONE_MINUS_DST_ALPHA, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ONE_MINUS_SRC_COLOR, GLS_DSTBLEND_SRC_ALPHA, GLS_DSTBLEND_SRC_COLOR, GLS_DSTBLEND_ZERO, GLS_POLYMODE_LINE, GLS_SRCBLEND_ALPHA_SATURATE, GLS_SRCBLEND_BITS, GLS_SRCBLEND_DST_ALPHA, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, GLS_SRCBLEND_ONE_MINUS_DST_ALPHA, GLS_SRCBLEND_ONE_MINUS_DST_COLOR, GLS_SRCBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, GLS_SRCBLEND_ZERO, glState, glstate_t::glStateBits, qglAlphaFunc, qglBlendFunc, qglDepthFunc, qglDepthMask, qglDisable, qglEnable, qglPolygonMode, and ri.
Referenced by DrawMultitextured(), DrawNormals(), DrawTris(), ProjectDlightTexture_scalar(), R_DebugPolygon(), RB_BeginDrawingView(), RB_FogPass(), RB_IterateStagesGeneric(), RB_SetGL2D(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), and RB_SurfaceBeam().
void GL_TexEnv (int env)
References glstate_t::currenttmu, ERR_DROP, glState, qglTexEnvf, ri, and glstate_t::texEnv.
Referenced by DrawMultitextured(), GL_SetDefaultState(), and RB_StageIteratorLightmappedMultitexture().
void GL_TextureMode (const char * string)
References GL_Bind(), gl_filter_max, gl_filter_min, glConfig, GLHW_3DFX_2D3D, glconfig_t::hardwareType, trGlobals_t::images, textureMode_t::maximize, textureMode_t::minimize, image_s::mipmap, trGlobals_t::numImages, PRINT_ALL, Q_stricmp(), qglTexParameterf, ri, and tr.
Referenced by GL_SetDefaultState(), and RE_BeginFrame().
void GLimp_EndFrame (void)
References refimport_t::Cmd_ExecuteText, refimport_t::Cvar_Set, refimport_t::Cvar_VariableIntegerValue, EXEC_APPEND, SDL_Surface::flags, refimport_t::IN_Restart, cvar_s::integer, cvar_s::modified, PRINT_ALL, Q_stricmp(), qfalse, qtrue, r_drawBuffer, r_fullscreen, ri, s, SDL_FULLSCREEN, SDL_GetVideoSurface(), SDL_GL_SwapBuffers(), SDL_WM_ToggleFullScreen(), and cvar_s::string.
Referenced by RB_SwapBuffers().
void GLimp_FrontEndSleep (void)
Referenced by R_IssueRenderCommands(), and R_SyncRenderThread().
void GLimp_Init (void)
References CVAR_ARCHIVE, refimport_t::Cvar_Get, CVAR_LATCH, CVAR_ROM, refimport_t::Cvar_Set, refimport_t::Cvar_VariableIntegerValue, glconfig_t::deviceSupportsGamma, glconfig_t::driverType, ERR_FATAL, glconfig_t::extensions_string, glConfig, GLDRV_ICD, GLHW_GENERIC, GLimp_InitExtensions(), GLimp_StartDriverAndSetMode(), glconfig_t::hardwareType, refimport_t::IN_Init, cvar_s::integer, PRINT_ALL, Q_strncpyz(), qfalse, qglGetString, r_fullscreen, r_mode, R_MODE_FALLBACK, r_noborder, glconfig_t::renderer_string, ri, SDL_SetGamma(), refimport_t::Sys_GLimpInit, refimport_t::Sys_GLimpSafeInit, refimport_t::Sys_SetEnv, va(), glconfig_t::vendor_string, and glconfig_t::version_string.
Referenced by InitOpenGL().
void GLimp_LogComment (char * comment)
Referenced by DrawTris(), GL_SelectTexture(), RB_EndSurface(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorVertexLitTexture(), RB_SwapBuffers(), and RE_RenderScene().
void GLimp_Minimize (void)
References SDL_WM_IconifyWindow().
Referenced by R_Register().
void* GLimp_RendererSleep (void)
References NULL.
Referenced by RB_RenderThread().
void GLimp_SetGamma (unsigned char red[256], unsigned char green[256], unsigned char blue[256])
References glconfig_t::deviceSupportsGamma, glConfig, cvar_s::integer, PRINT_DEVELOPER, r_ignorehwgamma, ri, and SDL_SetGammaRamp().
Referenced by R_SetColorMappings().
void GLimp_Shutdown (void)
References Com_Memset, glConfig, glState, refimport_t::IN_Shutdown, NULL, ri, SDL_INIT_VIDEO, and SDL_QuitSubSystem().
Referenced by RE_Shutdown().
qboolean GLimp_SpawnRenderThread (void(*)(void) function)
References PRINT_WARNING, qfalse, and ri.
Referenced by R_InitCommandBuffers().
void GLimp_WakeRenderer (void * data)
Referenced by R_IssueRenderCommands(), and R_ShutdownCommandBuffers().
void R_AddAnimSurfaces (trRefEntity_t * ent)
References trGlobals_t::currentModel, model_s::modelData, md4LOD_t::numSurfaces, md4Header_t::ofsLODs, md4LOD_t::ofsSurfaces, qfalse, R_AddDrawSurf(), R_GetShaderByHandle(), shader, md4Surface_t::shaderIndex, and tr.
Referenced by R_AddEntitySurfaces().
void R_AddBeamSurfaces (trRefEntity_t * e)
void R_AddBrushModelSurfaces (trRefEntity_t * e)
References model_s::bmodel, bmodel_t::bounds, CULL_OUT, trGlobals_t::currentEntity, trRefEntity_t::e, bmodel_t::firstSurface, refEntity_t::hModel, trRefEntity_t::needDlights, bmodel_t::numSurfaces, R_AddWorldSurface(), R_CullLocalBox(), R_DlightBmodel(), R_GetModelByHandle(), R_SetupEntityLighting(), trGlobals_t::refdef, and tr.
Referenced by R_AddEntitySurfaces().
void R_AddDrawSurf (surfaceType_t * surface, shader_t * shader, int fogIndex, int dlightMap)
References DRAWSURF_MASK, trRefdef_t::drawSurfs, int(), trRefdef_t::numDrawSurfs, QSORT_FOGNUM_SHIFT, QSORT_SHADERNUM_SHIFT, trGlobals_t::refdef, trGlobals_t::shiftedEntityNum, drawSurf_s::sort, shader_s::sortedIndex, and drawSurf_s::surface.
Referenced by R_AddAnimSurfaces(), R_AddEntitySurfaces(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_AddPolygonSurfaces(), and R_AddWorldSurface().
void R_AddDrawSurfCmd (drawSurf_t * drawSurfs, int numDrawSurfs)
References drawSurfsCommand_t::commandId, drawSurfsCommand_t::drawSurfs, drawSurfsCommand_t::numDrawSurfs, R_GetCommandBuffer(), RC_DRAW_SURFS, trGlobals_t::refdef, drawSurfsCommand_t::refdef, tr, trGlobals_t::viewParms, and drawSurfsCommand_t::viewParms.
Referenced by R_SortDrawSurfs().
void R_AddIQMSurfaces (trRefEntity_t * ent)
References CULL_OUT, trGlobals_t::currentModel, refEntity_t::customShader, refEntity_t::customSkin, data, trGlobals_t::defaultShader, trRefEntity_t::e, refEntity_t::frame, if(), cvar_s::integer, viewParms_t::isPortal, model_s::modelData, skinSurface_t::name, srfIQModel_s::name, model_s::name, iqmData_t::num_frames, iqmData_t::num_surfaces, trGlobals_t::numSkins, skin_s::numSurfaces, refEntity_t::oldframe, PRINT_DEVELOPER, trGlobals_t::projectionShadowShader, R_AddDrawSurf(), R_ComputeIQMFogNum(), R_CullIQM(), R_GetShaderByHandle(), R_GetSkinByHandle(), R_SetupEntityLighting(), r_shadows, trGlobals_t::refdef, refEntity_t::renderfx, RF_DEPTHHACK, RF_NOSHADOW, RF_SHADOW_PLANE, RF_THIRD_PERSON, RF_WRAP_FRAMES, ri, shader, skinSurface_t::shader, srfIQModel_s::shader, trGlobals_t::shadowShader, shader_s::sort, SS_OPAQUE, skin_s::surfaces, iqmData_t::surfaces, tr, and trGlobals_t::viewParms.
Referenced by R_AddEntitySurfaces().
void R_AddLightningBoltSurfaces (trRefEntity_t * e)
void R_AddMD3Surfaces (trRefEntity_t * e)
References CULL_OUT, trGlobals_t::currentModel, refEntity_t::customShader, refEntity_t::customSkin, shader_s::defaultShader, trGlobals_t::defaultShader, trRefEntity_t::e, refEntity_t::frame, if(), cvar_s::integer, viewParms_t::isPortal, model_s::md3, md3Surface_t::name, shader_s::name, skinSurface_t::name, skin_s::name, model_s::name, NULL, md3Header_t::numFrames, md3Surface_t::numShaders, trGlobals_t::numSkins, md3Header_t::numSurfaces, skin_s::numSurfaces, md3Surface_t::ofsEnd, md3Surface_t::ofsShaders, md3Header_t::ofsSurfaces, refEntity_t::oldframe, PRINT_DEVELOPER, trGlobals_t::projectionShadowShader, qfalse, R_AddDrawSurf(), R_ComputeFogNum(), R_ComputeLOD(), R_CullModel(), R_GetShaderByHandle(), R_GetSkinByHandle(), R_SetupEntityLighting(), r_shadows, trGlobals_t::refdef, refEntity_t::renderfx, RF_DEPTHHACK, RF_NOSHADOW, RF_SHADOW_PLANE, RF_THIRD_PERSON, RF_WRAP_FRAMES, ri, shader, skinSurface_t::shader, md3Shader_t::shaderIndex, trGlobals_t::shaders, trGlobals_t::shadowShader, refEntity_t::skinNum, shader_s::sort, SS_OPAQUE, skin_s::surfaces, tr, and trGlobals_t::viewParms.
Referenced by R_AddEntitySurfaces().
void R_AddNullModelSurfaces (trRefEntity_t * e)
void R_AddPolygonSurfaces (void)
References trGlobals_t::currentEntityNum, ENTITYNUM_WORLD, srfPoly_s::hShader, trRefdef_t::numPolys, trRefdef_t::polys, qfalse, QSORT_ENTITYNUM_SHIFT, R_AddDrawSurf(), R_GetShaderByHandle(), trGlobals_t::refdef, trGlobals_t::shiftedEntityNum, and tr.
Referenced by R_GenerateDrawSurfs().
void R_AddRailSurfaces (trRefEntity_t * e, qboolean isUnderwater)
void R_AddWorldSurfaces (void)
References ClearBounds(), trGlobals_t::currentEntityNum, ENTITYNUM_WORLD, cvar_s::integer, world_t::nodes, trRefdef_t::num_dlights, QSORT_ENTITYNUM_SHIFT, r_drawworld, R_MarkLeaves(), R_RecursiveWorldNode(), RDF_NOWORLDMODEL, trRefdef_t::rdflags, trGlobals_t::refdef, trGlobals_t::shiftedEntityNum, tr, trGlobals_t::viewParms, viewParms_t::visBounds, and trGlobals_t::world.
Referenced by R_GenerateDrawSurfs().
model_t* R_AllocModel (void)
References h_low, refimport_t::Hunk_Alloc, model_s::index, MAX_MOD_KNOWN, trGlobals_t::models, NULL, trGlobals_t::numModels, ri, and tr.
Referenced by R_LoadSubmodels(), R_ModelInit(), and RE_RegisterModel().
void R_BuildCloudData (shaderCommands_t * shader)
References skyParms_t::cloudHeight, FillCloudBox(), shader_s::isSky, MAX_SHADER_STAGES, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, shader, shaderCommands_s::shader, shader_s::sky, sky_max, sky_min, tess, and shaderCommands_s::xstages.
Referenced by RB_StageIteratorSky().
void R_ClearFlares (void)
References Com_Memset, MAX_FLARES, flare_s::next, NULL, and r_inactiveFlares.
Referenced by RE_BeginRegistration().
int R_ComputeLOD (trRefEntity_t * ent)
References md3Frame_s::bounds, trGlobals_t::currentModel, trRefEntity_t::e, refEntity_t::frame, refimport_t::ftol, cvar_s::integer, model_s::md3, model_s::modelData, model_s::numLods, md3Header_t::ofsFrames, refEntity_t::origin, ProjectRadius(), r_lodbias, r_lodscale, RadiusFromBounds(), ri, tr, model_s::type, and cvar_s::value.
Referenced by R_AddMD3Surfaces().
image_t* R_CreateImage (const char * name, const byte * pic, int width, int height, qboolean mipmap, qboolean allowPicmip, int wrapClampMode)
References image_s::allowPicmip, ERR_DROP, generateHashValue(), GL_Bind(), GL_SelectTexture(), h_low, hash(), height, image_s::height, refimport_t::Hunk_Alloc, trGlobals_t::images, image_s::imgName, image_s::internalFormat, MAX_DRAWIMAGES, MAX_QPATH, image_s::mipmap, image_s::next, trGlobals_t::numImages, qfalse, qglActiveTextureARB, qglBindTexture, qglTexParameterf, qtrue, ri, image_s::texnum, image_s::TMU, tr, Upload32(), image_s::uploadHeight, image_s::uploadWidth, width, image_s::width, and image_s::wrapClampMode.
Referenced by R_CreateBuiltinImages(), R_CreateDefaultImage(), R_CreateDlightImage(), R_CreateFogImage(), R_FindImageFile(), R_LoadLightmaps(), and RE_RegisterFont().
int R_CullLocalBox (vec3_t bounds[2])
References orientationr_t::axis, CULL_CLIP, CULL_IN, CULL_OUT, cplane_s::dist, DotProduct, viewParms_t::frustum, cvar_s::integer, cplane_s::normal, trGlobals_t::or, orientationr_t::origin, r_nocull, VectorCopy, VectorMA(), and trGlobals_t::viewParms.
Referenced by R_AddBrushModelSurfaces(), R_CullGrid(), R_CullIQM(), R_CullModel(), and R_CullTriSurf().
int R_CullLocalPointAndRadius (vec3_t origin, float radius)
References R_CullPointAndRadius(), and R_LocalPointToWorld().
Referenced by R_CullGrid(), and R_CullModel().
int R_CullPointAndRadius (vec3_t origin, float radius)
References CULL_CLIP, CULL_IN, CULL_OUT, cplane_s::dist, DotProduct, viewParms_t::frustum, cvar_s::integer, cplane_s::normal, qfalse, qtrue, r_nocull, and trGlobals_t::viewParms.
Referenced by R_CullGrid(), and R_CullLocalPointAndRadius().
void R_DecomposeSort (unsigned sort, int * entityNum, shader_t ** shader, int * fogNum, int * dlightMap)
References MAX_ENTITIES, MAX_SHADERS, QSORT_ENTITYNUM_SHIFT, QSORT_FOGNUM_SHIFT, QSORT_SHADERNUM_SHIFT, and trGlobals_t::sortedShaders.
Referenced by FixRenderCommandList(), R_SortDrawSurfs(), RB_RenderDrawSurfList(), and SurfIsOffscreen().
void R_DeleteTextures (void)
References Com_Memset, glstate_t::currenttextures, GL_SelectTexture(), glState, trGlobals_t::images, trGlobals_t::numImages, qglActiveTextureARB, qglBindTexture, qglDeleteTextures, image_s::texnum, and tr.
Referenced by RE_Shutdown().
void R_DlightBmodel (bmodel_t * bmodel)
References bmodel_t::bounds, trGlobals_t::currentEntity, msurface_s::data, trRefdef_t::dlights, bmodel_t::firstSurface, trRefEntity_t::needDlights, trRefdef_t::num_dlights, bmodel_t::numSurfaces, trGlobals_t::or, R_TransformDlights(), dlight_s::radius, trGlobals_t::refdef, SF_FACE, SF_GRID, SF_TRIANGLES, trGlobals_t::smpFrame, tr, and dlight_s::transformed.
Referenced by R_AddBrushModelSurfaces().
void R_DoneFreeType (void)
References NULL, and registeredFontCount.
Referenced by RE_Shutdown().
void R_DrawSkyBox (shaderCommands_t * shader)
image_t* R_FindImageFile (const char * name, qboolean mipmap, qboolean allowPicmip, int glWrapClampMode)
References image_s::allowPicmip, refimport_t::Free, generateHashValue(), hash(), height, image_s::imgName, image_s::mipmap, image_s::next, NULL, PRINT_ALL, PRINT_DEVELOPER, R_CreateImage(), R_LoadImage(), ri, width, and image_s::wrapClampMode.
Referenced by ParseSkyParms(), ParseStage(), and R_FindShader().
shader_t* R_FindShader (const char * name, int lightmapIndex, qboolean mipRawImage)
References shaderStage_t::active, AGEN_SKIP, AGEN_VERTEX, shaderStage_t::alphaGen, shaderStage_t::bundle, CGEN_EXACT_VERTEX, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_VERTEX, Com_Memset, COM_StripExtension(), shader_s::defaultShader, trGlobals_t::defaultShader, FILE_HASH_SIZE, FindShaderInShaderText(), FinishShader(), generateHashValue(), GLS_DEFAULT, GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_SRC_ALPHA, hash(), textureBundle_t::image, cvar_s::integer, textureBundle_t::isLightmap, LIGHTMAP_2D, LIGHTMAP_BY_VERTEX, LIGHTMAP_NONE, LIGHTMAP_WHITEIMAGE, shader_s::lightmapIndex, trGlobals_t::lightmaps, MAX_QPATH, MAX_SHADER_STAGES, shader_s::name, shader_s::needsColor, shader_s::needsNormal, shader_s::needsST1, shader_s::needsST2, shader_s::next, trGlobals_t::numLightmaps, ParseShader(), PRINT_ALL, PRINT_DEVELOPER, PRINT_WARNING, Q_stricmp(), Q_strncpyz(), qtrue, R_FindImageFile(), r_printShaders, r_smp, R_SyncRenderThread(), shaderStage_t::rgbGen, ri, shaderStage_t::stateBits, textureBundle_t::texMods, tr, and trGlobals_t::whiteImage.
Referenced by CreateExternalShaders(), R_LoadFogs(), R_LoadIQM(), R_LoadMD3(), R_LoadMD4(), RE_RegisterShader(), RE_RegisterShaderLightMap(), RE_RegisterShaderNoMip(), RE_RegisterSkin(), and ShaderForShaderNum().
shader_t* R_FindShaderByName (const char * name)
References COM_StripExtension(), trGlobals_t::defaultShader, FILE_HASH_SIZE, generateHashValue(), hash(), MAX_QPATH, shader_s::name, shader_s::next, NULL, Q_stricmp(), and tr.
Referenced by R_RemapShader().
float R_FogFactor (float s, float t)
References FOG_TABLE_SIZE, trGlobals_t::fogTable, int(), and tr.
Referenced by R_CreateFogImage(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), and RB_CalcModulateRGBAsByFog().
void R_FreeSurfaceGridMesh (srfGridMesh_t * grid)
References refimport_t::Free, srfGridMesh_s::heightLodError, ri, and srfGridMesh_s::widthLodError.
Referenced by R_GridInsertColumn(), R_GridInsertRow(), and R_MovePatchSurfacesToHunk().
void R_GammaCorrect (byte * buffer, int bufSize)
References s_gammatable.
Referenced by R_LevelShot(), RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), and RB_TakeVideoFrameCmd().
void* R_GetCommandBuffer (int bytes)
References backEndData, renderCommandList_t::cmds, backEndData_t::commands, ERR_FATAL, MAX_RENDER_COMMANDS, NULL, PAD, ri, trGlobals_t::smpFrame, tr, and renderCommandList_t::used.
Referenced by R_AddDrawSurfCmd(), R_TakeScreenshot(), RE_BeginFrame(), RE_EndFrame(), RE_SetColor(), RE_StretchPic(), and RE_TakeVideoFrame().
qboolean R_GetEntityToken (char * buffer, int size)
References COM_Parse(), world_t::entityParsePoint, world_t::entityString, Q_strncpyz(), qfalse, qtrue, and s.
Referenced by GetRefAPI().
qboolean R_GetModeInfo (int * width, int * height, float * windowAspect, int mode)
References vidmode_s::height, cvar_s::integer, vidmode_s::pixelAspect, qfalse, qtrue, s_numVidModes, cvar_s::value, and vidmode_s::width.
Referenced by GLimp_SetMode().
model_t* R_GetModelByHandle (qhandle_t hModel)
References trGlobals_t::models, trGlobals_t::numModels, and tr.
Referenced by R_AddBrushModelSurfaces(), R_AddEntitySurfaces(), R_LerpTag(), and R_ModelBounds().
shader_t* R_GetShaderByHandle (qhandle_t hShader)
References trGlobals_t::defaultShader, trGlobals_t::numShaders, PRINT_WARNING, ri, trGlobals_t::shaders, and tr.
Referenced by R_AddAnimSurfaces(), R_AddEntitySurfaces(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_AddPolygonSurfaces(), R_RemapShader(), and RE_StretchPic().
shader_t* R_GetShaderByState (int index, long * cycleTime)
skin_t* R_GetSkinByHandle (qhandle_t hSkin)
References trGlobals_t::numSkins, trGlobals_t::skins, and tr.
Referenced by R_AddIQMSurfaces(), and R_AddMD3Surfaces().
srfGridMesh_t* R_GridInsertColumn (srfGridMesh_t * grid, int column, int row, vec3_t point, float loderror)
References height, srfGridMesh_s::height, srfGridMesh_s::heightLodError, LerpDrawVert(), srfGridMesh_s::lodOrigin, srfGridMesh_s::lodRadius, MakeMeshNormals(), MAX_GRID_SIZE, NULL, R_CreateSurfaceGridMesh(), R_FreeSurfaceGridMesh(), VectorCopy, srfGridMesh_s::verts, width, srfGridMesh_s::width, and srfGridMesh_s::widthLodError.
Referenced by R_StitchPatches().
srfGridMesh_t* R_GridInsertRow (srfGridMesh_t * grid, int row, int column, vec3_t point, float loderror)
References height, srfGridMesh_s::height, srfGridMesh_s::heightLodError, LerpDrawVert(), srfGridMesh_s::lodOrigin, srfGridMesh_s::lodRadius, MakeMeshNormals(), MAX_GRID_SIZE, NULL, R_CreateSurfaceGridMesh(), R_FreeSurfaceGridMesh(), VectorCopy, srfGridMesh_s::verts, width, srfGridMesh_s::width, and srfGridMesh_s::widthLodError.
Referenced by R_StitchPatches().
void R_ImageList_f (void)
References trGlobals_t::images, image_s::imgName, image_s::internalFormat, image_s::mipmap, trGlobals_t::numImages, PRINT_ALL, ri, image_s::TMU, tr, image_s::uploadHeight, image_s::uploadWidth, and image_s::wrapClampMode.
Referenced by R_Register().
void R_Init (void)
References backEnd, backEndData, Com_Memset, DEG2RAD, ERR_FATAL, FUNCTABLE_SIZE, h_low, refimport_t::Hunk_Alloc, InitOpenGL(), cvar_s::integer, intptr_t(), trGlobals_t::inverseSawToothTable, max_polys, MAX_POLYS, max_polyverts, MAX_POLYVERTS, NULL, backEndData_t::polys, backEndData_t::polyVerts, PRINT_ALL, PRINT_WARNING, ptr(), qglGetError, R_InitFogTable(), R_InitFreeType(), R_InitImages(), R_InitShaders(), R_InitSkins(), R_ModelInit(), R_NoiseInit(), R_Register(), R_ToggleSmpFrame(), ri, trGlobals_t::sawToothTable, trGlobals_t::sinTable, trGlobals_t::squareTable, tess, tr, and trGlobals_t::triangleTable.
Referenced by RE_BeginRegistration().
void R_InitCommandBuffers (void)
References glConfig, GLimp_SpawnRenderThread(), cvar_s::integer, PRINT_ALL, qfalse, qtrue, r_smp, RB_RenderThread(), ri, and glconfig_t::smpActive.
Referenced by InitOpenGL().
void R_InitFogTable (void)
References FOG_TABLE_SIZE, trGlobals_t::fogTable, and tr.
Referenced by R_Init().
void R_InitFreeType (void)
References PRINT_WARNING, registeredFontCount, and ri.
Referenced by R_Init().
void R_InitImages (void)
References Com_Memset, R_CreateBuiltinImages(), and R_SetColorMappings().
Referenced by R_Init().
void R_InitShaders (void)
References Com_Memset, CreateExternalShaders(), CreateInternalShaders(), PRINT_ALL, ri, and ScanAndLoadShaderFiles().
Referenced by R_Init().
void R_InitSkins (void)
References trGlobals_t::defaultShader, h_low, refimport_t::Hunk_Alloc, skin_s::name, trGlobals_t::numSkins, skin_s::numSurfaces, Q_strncpyz(), ri, skinSurface_t::shader, trGlobals_t::skins, skin_s::surfaces, and tr.
Referenced by R_Init().
void R_InitSkyTexCoords (float cloudLayerHeight)
References backEnd, DotProduct, HALF_SKY_SUBDIVISIONS, MakeSkyVec(), NULL, Q_acos(), s, s_cloudTexCoords, s_cloudTexP, SKY_SUBDIVISIONS, SQR, t, VectorNormalize(), VectorScale, backEndState_t::viewParms, and viewParms_t::zFar.
Referenced by ParseSkyParms().
qboolean R_inPVS (const vec3_t p1, const vec3_t p2)
References mnode_s::cluster, refimport_t::CM_ClusterPVS, qfalse, qtrue, R_PointInLeaf(), and ri.
Referenced by GetRefAPI().
int R_IQMLerpTag (orientation_t * tag, iqmData_t * data, int startFrame, int endFrame, float frac, const char * tagName)
References orientation_t::axis, AxisClear(), ComputeJointMats(), IQM_MAX_JOINTS, iqmData_t::names, iqmData_t::num_joints, orientation_t::origin, qfalse, qtrue, and VectorClear.
Referenced by R_LerpTag().
int R_LerpTag (orientation_t * tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char * tagName)
References md3Tag_s::axis, orientation_t::axis, AxisClear(), end, model_s::md3, MOD_IQM, model_s::modelData, md3Tag_s::origin, orientation_t::origin, qfalse, qtrue, R_GetModelByHandle(), R_GetTag(), R_IQMLerpTag(), start, model_s::type, VectorClear, and VectorNormalize().
Referenced by GetRefAPI().
int R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
References trRefEntity_t::ambientLight, Com_Memset, trRefEntity_t::directedLight, trRefEntity_t::e, trRefEntity_t::lightDir, world_t::lightGridData, NULL, refEntity_t::origin, qfalse, qtrue, R_SetupEntityLightingGrid(), tr, VectorCopy, and trGlobals_t::world.
Referenced by GetRefAPI().
void R_LoadBMP (const char * name, byte ** pic, int * width, int * height)
References b, BMPHeader_t::bitmapDataOffset, BMPHeader_t::bitmapDataSize, BMPHeader_t::bitmapHeaderSize, BMPHeader_t::bitsPerPixel, buffer, BMPHeader_t::colors, Com_Memcpy, BMPHeader_t::compression, end, ERR_DROP, BMPHeader_t::fileSize, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, BMPHeader_t::height, BMPHeader_t::hRes, BMPHeader_t::id, BMPHeader_t::importantColors, length(), refimport_t::Malloc, NULL, BMPHeader_t::palette, BMPHeader_t::planes, BMPHeader_t::reserved0, ri, BMPHeader_t::vRes, and BMPHeader_t::width.
qboolean R_LoadIQM (model_t * mod, void * buffer, int filesize, const char * name)
References iqmbounds::bbmax, iqmbounds::bbmin, iqmData_t::blendIndexes, iqmData_t::blendWeights, iqmData_t::bounds, iqmpose::channeloffset, iqmpose::channelscale, iqmData_t::colors, Com_Memcpy, srfIQModel_s::data, shader_s::defaultShader, trGlobals_t::defaultShader, iqmheader::filesize, iqmmesh::first_triangle, srfIQModel_s::first_triangle, iqmmesh::first_vertex, srfIQModel_s::first_vertex, iqmheader::flags, iqmvertexarray::format, h_low, refimport_t::Hunk_Alloc, int(), IQM_BLENDINDEXES, IQM_BLENDWEIGHTS, IQM_BYTE, IQM_CheckRange(), IQM_COLOR, IQM_FLOAT, IQM_INT, IQM_MAGIC, IQM_MAX_JOINTS, IQM_NORMAL, IQM_POSITION, IQM_TANGENT, IQM_TEXCOORD, IQM_UBYTE, IQM_UINT, IQM_VERSION, iqmData_t::jointParents, JointToMatrix(), LIGHTMAP_NONE, LL, iqmheader::magic, iqmpose::mask, iqmmesh::material, Matrix34Invert(), Matrix34Multiply(), MOD_IQM, model_s::modelData, n, iqmmesh::name, iqmjoint::name, srfIQModel_s::name, iqmData_t::names, iqmData_t::normals, iqmheader::num_anims, iqmheader::num_comment, iqmheader::num_extensions, iqmheader::num_framechannels, iqmheader::num_frames, iqmData_t::num_frames, iqmheader::num_joints, iqmData_t::num_joints, iqmheader::num_meshes, iqmheader::num_poses, iqmData_t::num_surfaces, iqmheader::num_text, iqmheader::num_triangles, iqmmesh::num_triangles, iqmData_t::num_triangles, srfIQModel_s::num_triangles, iqmheader::num_vertexarrays, iqmheader::num_vertexes, iqmmesh::num_vertexes, iqmData_t::num_vertexes, srfIQModel_s::num_vertexes, iqmvertexarray::offset, iqmheader::ofs_adjacency, iqmheader::ofs_anims, iqmheader::ofs_bounds, iqmheader::ofs_comment, iqmheader::ofs_extensions, iqmheader::ofs_frames, iqmheader::ofs_joints, iqmheader::ofs_meshes, iqmheader::ofs_poses, iqmheader::ofs_text, iqmheader::ofs_triangles, iqmheader::ofs_vertexarrays, iqmjoint::parent, iqmpose::parent, iqmData_t::poseMats, iqmData_t::positions, PRINT_WARNING, Q_strlwr(), Q_strncmp(), Q_strncpyz(), qfalse, qtrue, R_FindShader(), ri, iqmjoint::rotate, iqmjoint::scale, SF_IQM, srfIQModel_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, iqmvertexarray::size, iqmData_t::surfaces, srfIQModel_s::surfaceType, iqmData_t::tangents, iqmData_t::texcoords, tr, iqmjoint::translate, iqmData_t::triangles, iqmvertexarray::type, model_s::type, iqmheader::version, and iqmtriangle::vertex.
Referenced by R_RegisterIQM().
void R_LoadJPG (const char * name, byte ** pic, int * width, int * height)
References b, buffer, ERR_DROP, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, JCS_RGB, jpeg_create_decompress, jpeg_destroy_decompress(), jpeg_finish_decompress(), jpeg_mem_src(), jpeg_read_header(), jpeg_read_scanlines(), jpeg_std_error(), refimport_t::Malloc, NULL, out, jpeg_decompress_struct::out_color_space, jpeg_decompress_struct::output_components, jpeg_decompress_struct::output_height, jpeg_decompress_struct::output_scanline, jpeg_decompress_struct::output_width, R_JPGErrorExit(), R_JPGOutputMessage(), ri, and void().
void R_LoadPCX (const char * name, byte ** pic, int * width, int * height)
References b, pcx_t::bits_per_pixel, pcx_t::color_planes, pcx_t::data, pcx_t::encoding, end, refimport_t::Free, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, h, refimport_t::Malloc, pcx_t::manufacturer, NULL, out, PRINT_ALL, ri, pcx_t::version, pcx_t::xmax, and pcx_t::ymax.
void R_LoadPNG (const char * name, byte ** pic, int * width, int * height)
References BufferedFileRead(), BufferedFileRewind(), BufferedFileSkip(), CloseBufferedFile(), PNG_Chunk_IHDR::ColourType, PNG_Chunk_IHDR::CompressionMethod, DecodeImageInterlaced(), DecodeImageNonInterlaced(), DecompressIDATs(), PNG_Chunk_IHDR::FilterMethod, FindChunk(), refimport_t::Free, PNG_Chunk_IHDR::Height, INT_MAX, PNG_Chunk_IHDR::InterlaceMethod, PNG_ChunkHeader::Length, refimport_t::Malloc, NULL, PNG_Chunk_IHDR_Size, PNG_ChunkCRC_Size, PNG_ChunkHeader_Size, PNG_ChunkType_IHDR, PNG_ChunkType_PLTE, PNG_ChunkType_tRNS, PNG_ColourType_Grey, PNG_ColourType_Indexed, PNG_ColourType_True, PNG_CompressionMethod_0, PNG_FilterMethod_0, PNG_InterlaceMethod_Interlaced, PNG_InterlaceMethod_NonInterlaced, PNG_Signature, PNG_Signature_Size, PRINT_WARNING, Q3IMAGE_BYTESPERPIXEL, qfalse, qtrue, ReadBufferedFile(), ri, PNG_ChunkHeader::Type, and PNG_Chunk_IHDR::Width.
void R_LoadTGA (const char * name, byte ** pic, int * width, int * height)
References _TargaHeader::attributes, b, buffer, _TargaHeader::colormap_index, _TargaHeader::colormap_length, _TargaHeader::colormap_size, _TargaHeader::colormap_type, end, ERR_DROP, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, _TargaHeader::height, _TargaHeader::id_length, _TargaHeader::image_type, length(), refimport_t::Malloc, NULL, _TargaHeader::pixel_size, PRINT_WARNING, ri, src, _TargaHeader::width, _TargaHeader::x_origin, and _TargaHeader::y_origin.
void R_LocalNormalToWorld (vec3_t local, vec3_t world)
References orientationr_t::axis, and trGlobals_t::or.
Referenced by IsMirror(), and R_GetPortalOrientations().
void R_LocalPointToWorld (vec3_t local, vec3_t world)
References orientationr_t::axis, trGlobals_t::or, and orientationr_t::origin.
Referenced by R_CullLocalPointAndRadius().
int R_MarkFragments (int numPoints, const vec3_t * points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t * fragmentBuffer)
References AddPointToBounds(), ClearBounds(), CrossProduct(), DotProduct, srfGridMesh_s::height, srfTriangles_t::indexes, cvar_s::integer, m, MARKER_OFFSET, MAX_VERTS_ON_POLY, n, world_t::nodes, drawVert_t::normal, cplane_s::normal, srfTriangles_t::numIndexes, srfSurfaceFace_t::numIndices, numPlanes, srfSurfaceFace_t::ofsIndices, srfSurfaceFace_t::plane, srfSurfaceFace_t::points, R_AddMarkFragments(), R_BoxSurfaces_r(), r_marksOnTriangleMeshes, SF_FACE, SF_GRID, SF_TRIANGLES, tr, VectorAdd, VectorCopy, VectorInverse(), VectorMA(), VectorNormalize2(), VectorNormalizeFast(), VectorSubtract, VERTEXSIZE, srfGridMesh_s::verts, srfTriangles_t::verts, trGlobals_t::viewCount, srfGridMesh_s::width, trGlobals_t::world, and drawVert_t::xyz.
Referenced by GetRefAPI().
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
References model_s::bmodel, md3Frame_s::bounds, md4Frame_t::bounds, iqmData_t::bounds, bmodel_t::bounds, model_s::md3, MOD_BRUSH, MOD_IQM, MOD_MD4, MOD_MESH, model_s::modelData, md3Header_t::ofsFrames, md4Header_t::ofsFrames, R_GetModelByHandle(), model_s::type, VectorClear, and VectorCopy.
Referenced by GetRefAPI().
void R_ModelInit (void)
References MOD_BAD, trGlobals_t::numModels, R_AllocModel(), tr, and model_s::type.
Referenced by R_Init().
void R_Modellist_f (void)
References world_t::dataSize, model_s::dataSize, model_s::md3, MD3_MAX_LODS, trGlobals_t::models, world_t::name, model_s::name, trGlobals_t::numModels, PRINT_ALL, ri, tr, and trGlobals_t::world.
Referenced by R_Register().
float R_NoiseGet4f (float x, float y, float z, float t)
References GetNoiseValue(), int(), and LERP.
Referenced by RB_CalcDeformNormals(), and RB_CalcWaveColor().
void R_NoiseInit (void)
References NOISE_SIZE, s_noise_perm, and s_noise_table.
Referenced by R_Init().
void R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
References COM_StripExtension(), trGlobals_t::defaultShader, FILE_HASH_SIZE, generateHashValue(), h, hash(), MAX_QPATH, shader_s::name, shader_s::next, NULL, PRINT_WARNING, Q_stricmp(), R_FindShaderByName(), R_GetShaderByHandle(), RE_RegisterShaderLightMap(), shader_s::remappedShader, ri, shader_s::timeOffset, and tr.
Referenced by GetRefAPI(), and R_LoadEntities().
void R_RenderView (viewParms_t * parms)
References trRefdef_t::drawSurfs, viewParms_t::frameCount, trGlobals_t::frameCount, viewParms_t::frameSceneNum, trGlobals_t::frameSceneNum, trRefdef_t::numDrawSurfs, qtrue, R_DebugGraphics(), R_GenerateDrawSurfs(), R_RotateForViewer(), R_SetupProjection(), R_SortDrawSurfs(), r_zproj, trGlobals_t::refdef, cvar_s::value, trGlobals_t::viewCount, trGlobals_t::viewParms, viewParms_t::viewportHeight, and viewParms_t::viewportWidth.
Referenced by R_MirrorViewBySurface(), and RE_RenderScene().
void R_RotateForEntity (const trRefEntity_t * ent, const viewParms_t * viewParms, orientationr_t * or)
References orientationr_t::axis, refEntity_t::axis, DotProduct, trRefEntity_t::e, orientationr_t::modelMatrix, myGlMultMatrix(), refEntity_t::nonNormalizedAxes, viewParms_t::or, orientationr_t::origin, refEntity_t::origin, refEntity_t::reType, RT_MODEL, VectorCopy, VectorLength(), VectorSubtract, orientationr_t::viewOrigin, and viewParms_t::world.
Referenced by IsMirror(), R_AddEntitySurfaces(), R_GetPortalOrientations(), and RB_RenderDrawSurfList().
void R_ScreenShot_f (void)
References refimport_t::Cmd_Argc, refimport_t::Cmd_Argv, Com_sprintf(), refimport_t::FS_FileExists, MAX_OSPATH, PRINT_ALL, qfalse, qtrue, R_LevelShot(), R_ScreenshotFilename(), R_TakeScreenshot(), ri, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by R_Register().
void R_SetColorMappings (void)
References glconfig_t::colorBits, refimport_t::Cvar_Set, glconfig_t::deviceSupportsGamma, glConfig, GLimp_SetGamma(), trGlobals_t::identityLight, trGlobals_t::identityLightByte, cvar_s::integer, glconfig_t::isFullscreen, trGlobals_t::overbrightBits, r_gamma, r_intensity, r_overBrightBits, ri, s_gammatable, s_intensitytable, tr, and cvar_s::value.
Referenced by R_InitImages(), and RE_BeginFrame().
void R_SetupEntityLighting (const trRefdef_t * refdef, trRefEntity_t * ent)
References trRefEntity_t::ambientLight, trRefEntity_t::ambientLightInt, refEntity_t::axis, dlight_s::color, trRefEntity_t::directedLight, DLIGHT_AT_RADIUS, DLIGHT_MINIMUM_RADIUS, trRefdef_t::dlights, DotProduct, trRefEntity_t::e, refimport_t::ftol, trGlobals_t::identityLight, trGlobals_t::identityLightByte, cvar_s::integer, trRefEntity_t::lightDir, world_t::lightGridData, trRefEntity_t::lightingCalculated, refEntity_t::lightingOrigin, lightOrigin, LogLight(), trRefdef_t::num_dlights, dlight_s::origin, refEntity_t::origin, qtrue, R_SetupEntityLightingGrid(), dlight_s::radius, RDF_NOWORLDMODEL, trRefdef_t::rdflags, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, ri, trGlobals_t::sunDirection, tr, VectorCopy, VectorLength(), VectorMA(), VectorNormalize(), VectorScale, VectorSubtract, and trGlobals_t::world.
Referenced by R_AddBrushModelSurfaces(), R_AddIQMSurfaces(), and R_AddMD3Surfaces().
void R_SetupProjection (viewParms_t * dest, float zProj, qboolean computeFrustum)
References viewParms_t::fovX, viewParms_t::fovY, height, M_PI, viewParms_t::projectionMatrix, R_SetupFrustum(), r_stereoSeparation, STEREO_LEFT, STEREO_RIGHT, viewParms_t::stereoFrame, cvar_s::value, and width.
Referenced by R_RenderView(), and RB_RenderDrawSurfList().
void R_ShaderList_f (void)
References refimport_t::Cmd_Argc, count, shader_s::defaultShader, shader_s::explicitlyDefined, shader_s::lightmapIndex, shader_s::multitextureEnv, shader_s::name, trGlobals_t::numShaders, shader_s::numUnfoggedPasses, shader_s::optimalStageIteratorFunc, PRINT_ALL, RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), ri, shader, trGlobals_t::shaders, trGlobals_t::sortedShaders, and tr.
Referenced by R_Register().
void R_ShutdownCommandBuffers (void)
References glConfig, GLimp_WakeRenderer(), NULL, qfalse, and glconfig_t::smpActive.
Referenced by RE_Shutdown().
void R_SkinList_f (void)
References shader_s::name, skinSurface_t::name, skin_s::name, trGlobals_t::numSkins, skin_s::numSurfaces, PRINT_ALL, ri, skinSurface_t::shader, trGlobals_t::skins, skin_s::surfaces, and tr.
Referenced by R_Register().
srfGridMesh_t* R_SubdividePatchToGrid (int width, int height, drawVert_t points[MAX_PATCH_SIZE *MAX_PATCH_SIZE])
References DotProduct, drawVert_t_cleared, height, InvertCtrl(), InvertErrorTable(), LerpDrawVert(), MakeMeshNormals(), MAX_GRID_SIZE, PutPointsOnCurve(), R_CreateSurfaceGridMesh(), t, Transpose(), VectorLengthSquared(), VectorNormalize(), VectorScale, VectorSubtract, width, and drawVert_t::xyz.
Referenced by ParseMesh().
int R_SumOfUsedImages (void)
References trGlobals_t::frameCount, image_s::frameUsed, trGlobals_t::images, trGlobals_t::numImages, tr, image_s::uploadHeight, and image_s::uploadWidth.
Referenced by R_PerformanceCounters().
void R_SwapBuffers (int)
void R_SyncRenderThread (void)
References glConfig, GLimp_FrontEndSleep(), qfalse, R_IssueRenderCommands(), trGlobals_t::registered, glconfig_t::smpActive, and tr.
Referenced by R_DebugGraphics(), R_FindShader(), R_LoadLightmaps(), RE_BeginFrame(), RE_BeginRegistration(), RE_EndRegistration(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), RE_Shutdown(), and RE_StretchRaw().
void R_ToggleSmpFrame (void)
References backEndData, backEndData_t::commands, cvar_s::integer, r_firstSceneDlight, r_firstSceneDrawSurf, r_firstSceneEntity, r_firstScenePoly, r_numdlights, r_numentities, r_numpolys, r_numpolyverts, r_smp, trGlobals_t::smpFrame, tr, and renderCommandList_t::used.
Referenced by R_Init(), and RE_EndFrame().
void R_TransformClipToWindow (const vec4_t clip, const viewParms_t * view, vec4_t normalized, vec4_t window)
References int(), viewParms_t::viewportHeight, and viewParms_t::viewportWidth.
Referenced by RB_AddFlare().
void R_TransformDlights (int count, dlight_t * dl, orientationr_t * or)
References orientationr_t::axis, count, DotProduct, dlight_s::origin, orientationr_t::origin, dlight_s::transformed, and VectorSubtract.
Referenced by R_DlightBmodel(), and RB_RenderDrawSurfList().
void R_TransformModelToClip (const vec3_t src, const float * modelMatrix, const float * projectionMatrix, vec4_t eye, vec4_t dst)
Referenced by RB_AddFlare(), and SurfIsOffscreen().
void RB_AddDlightFlares (void)
References backEnd, fog_t::bounds, trRefdef_t::dlights, world_t::fogs, cvar_s::integer, NULL, trRefdef_t::num_dlights, world_t::numfogs, dlight_s::origin, r_flares, RB_AddFlare(), backEndState_t::refdef, tr, and trGlobals_t::world.
void RB_AddFlare (void * surface, int fogNum, vec3_t point, vec3_t color, vec3_t normal)
References flare_s::addedFrame, backEnd, backEndCounters_t::c_flareAdds, flare_s::color, DotProduct, flare_s::eyeZ, flare_s::fadeTime, flare_s::fogNum, viewParms_t::frameCount, flare_s::frameSceneNum, viewParms_t::frameSceneNum, flare_s::inPortal, viewParms_t::isPortal, local, orientationr_t::modelMatrix, flare_s::next, viewParms_t::or, backEndState_t::or, flare_s::origin, orientationr_t::origin, backEndState_t::pc, viewParms_t::projectionMatrix, qfalse, r_activeFlares, r_inactiveFlares, R_TransformClipToWindow(), R_TransformModelToClip(), backEndState_t::refdef, flare_s::surface, trRefdef_t::time, VectorCopy, VectorNormalizeFast(), VectorScale, VectorSubtract, backEndState_t::viewParms, viewParms_t::viewportHeight, viewParms_t::viewportWidth, viewParms_t::viewportX, viewParms_t::viewportY, flare_s::visible, flare_s::windowX, and flare_s::windowY.
Referenced by RB_AddDlightFlares(), and RB_SurfaceFlare().
void RB_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, byte * color)
References RB_AddQuadStampExt().
Referenced by AutospriteDeform(), and RB_SurfaceSprite().
void RB_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, byte * color, float s1, float t1, float s2, float t2)
References orientationr_t::axis, backEnd, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, viewParms_t::or, RB_CHECKOVERFLOW, tess, vec3_origin, VectorSubtract, and backEndState_t::viewParms.
Referenced by DeformText(), and RB_AddQuadStamp().
void RB_BeginSurface (shader_t * shader, int fogNum)
References backEnd, shader_s::clampTime, shaderCommands_s::currentStageIteratorFunc, shaderCommands_s::dlightBits, trRefdef_t::floatTime, shaderCommands_s::fogNum, if(), shaderCommands_s::numIndexes, shaderCommands_s::numPasses, shader_s::numUnfoggedPasses, shaderCommands_s::numVertexes, shader_s::optimalStageIteratorFunc, backEndState_t::refdef, shader_s::remappedShader, shaderCommands_s::shader, shaderCommands_s::shaderTime, shader_s::stages, shader_s::timeOffset, and shaderCommands_s::xstages.
Referenced by RB_CheckOverflow(), RB_DrawSun(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), and SurfIsOffscreen().
void RB_CalcAlphaFromEntity (unsigned char * dstColors)
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, shaderCommands_s::numVertexes, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
void RB_CalcAlphaFromOneMinusEntity (unsigned char * dstColors)
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, shaderCommands_s::numVertexes, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
void RB_CalcColorFromEntity (unsigned char * dstColors)
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, shaderCommands_s::numVertexes, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
void RB_CalcColorFromOneMinusEntity (unsigned char * dstColors)
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, shaderCommands_s::numVertexes, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
void RB_CalcDiffuseColor (unsigned char * colors)
References com_altivec, cvar_s::integer, and RB_CalcDiffuseColor_scalar().
Referenced by ComputeColors(), and RB_StageIteratorVertexLitTexture().
void RB_CalcEnvironmentTexCoords (float * dstTexCoords)
References backEnd, DotProduct, shaderCommands_s::numVertexes, backEndState_t::or, tess, VectorNormalizeFast(), VectorSubtract, and orientationr_t::viewOrigin.
Referenced by ComputeTexCoords().
void RB_CalcFogTexCoords (float * dstTexCoords)
References orientationr_t::axis, backEnd, DotProduct, shaderCommands_s::fogNum, world_t::fogs, fog_t::hasSurface, local, orientationr_t::modelMatrix, shaderCommands_s::numVertexes, viewParms_t::or, backEndState_t::or, orientationr_t::origin, qfalse, qtrue, s, fog_t::surface, t, fog_t::tcScale, tess, tr, VectorSubtract, orientationr_t::viewOrigin, backEndState_t::viewParms, and trGlobals_t::world.
Referenced by ComputeTexCoords(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), and RB_FogPass().
void RB_CalcModulateAlphasByFog (unsigned char * dstColors)
References shaderCommands_s::numVertexes, R_FogFactor(), RB_CalcFogTexCoords(), SHADER_MAX_VERTEXES, and tess.
Referenced by ComputeColors().
void RB_CalcModulateColorsByFog (unsigned char * dstColors)
References shaderCommands_s::numVertexes, R_FogFactor(), RB_CalcFogTexCoords(), SHADER_MAX_VERTEXES, and tess.
Referenced by ComputeColors(), and RB_RenderFlare().
void RB_CalcModulateRGBAsByFog (unsigned char * dstColors)
References shaderCommands_s::numVertexes, R_FogFactor(), RB_CalcFogTexCoords(), SHADER_MAX_VERTEXES, and tess.
Referenced by ComputeColors().
void RB_CalcRotateTexCoords (float rotSpeed, float * dstTexCoords)
References FUNCTABLE_MASK, FUNCTABLE_SIZE, texModInfo_t::matrix, RB_CalcTransformTexCoords(), shaderCommands_s::shaderTime, trGlobals_t::sinTable, tess, tr, and texModInfo_t::translate.
Referenced by ComputeTexCoords().
void RB_CalcScaleTexCoords (const float scale[2], float * dstTexCoords)
References shaderCommands_s::numVertexes, and tess.
Referenced by ComputeTexCoords().
void RB_CalcScrollTexCoords (const float scroll[2], float * dstTexCoords)
References shaderCommands_s::numVertexes, shaderCommands_s::shaderTime, and tess.
Referenced by ComputeTexCoords().
void RB_CalcSpecularAlpha (unsigned char * alphas)
References b, backEnd, DotProduct, lightOrigin, shaderCommands_s::numVertexes, backEndState_t::or, Q_rsqrt(), tess, VectorNormalizeFast(), VectorSubtract, and orientationr_t::viewOrigin.
Referenced by ComputeColors().
void RB_CalcStretchTexCoords (const waveForm_t * wf, float * texCoords)
References EvalWaveForm(), texModInfo_t::matrix, RB_CalcTransformTexCoords(), and texModInfo_t::translate.
Referenced by ComputeTexCoords().
void RB_CalcTransformTexCoords (const texModInfo_t * tmi, float * dstTexCoords)
References texModInfo_t::matrix, shaderCommands_s::numVertexes, s, t, tess, and texModInfo_t::translate.
Referenced by ComputeTexCoords(), RB_CalcRotateTexCoords(), and RB_CalcStretchTexCoords().
void RB_CalcTurbulentTexCoords (const waveForm_t * wf, float * dstTexCoords)
References waveForm_t::amplitude, waveForm_t::frequency, FUNCTABLE_MASK, FUNCTABLE_SIZE, int(), shaderCommands_s::numVertexes, waveForm_t::phase, s, shaderCommands_s::shaderTime, trGlobals_t::sinTable, t, tess, and tr.
Referenced by ComputeTexCoords().
void RB_CalcWaveAlpha (const waveForm_t * wf, unsigned char * dstColors)
References EvalWaveFormClamped(), shaderCommands_s::numVertexes, and tess.
Referenced by ComputeColors().
void RB_CalcWaveColor (const waveForm_t * wf, unsigned char * dstColors)
References waveForm_t::amplitude, waveForm_t::base, EvalWaveForm(), waveForm_t::frequency, refimport_t::ftol, waveForm_t::func, GF_NOISE, trGlobals_t::identityLight, shaderCommands_s::numVertexes, waveForm_t::phase, R_NoiseGet4f(), ri, shaderCommands_s::shaderTime, tess, and tr.
Referenced by ComputeColors().
void RB_CheckOverflow (int verts, int indexes)
References ERR_DROP, shaderCommands_s::fogNum, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, RB_BeginSurface(), RB_EndSurface(), ri, shaderCommands_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, and tess.
Referenced by RB_SurfaceAnim().
void RB_ClipSkyPolygons (shaderCommands_t * shader)
References backEnd, ClearSkyBox(), ClipSkyPolygon(), shaderCommands_s::numIndexes, viewParms_t::or, orientationr_t::origin, VectorSubtract, and backEndState_t::viewParms.
Referenced by RB_StageIteratorSky().
void RB_DeformTessGeometry (void)
References Autosprite2Deform(), AutospriteDeform(), backEnd, DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2, DEFORM_BULGE, DEFORM_MOVE, DEFORM_NONE, DEFORM_NORMALS, DEFORM_PROJECTION_SHADOW, DEFORM_TEXT0, DEFORM_TEXT1, DEFORM_TEXT2, DEFORM_TEXT3, DEFORM_TEXT4, DEFORM_TEXT5, DEFORM_TEXT6, DEFORM_TEXT7, DEFORM_WAVE, deformStage_t::deformation, shader_s::deforms, DeformText(), shader_s::numDeforms, RB_CalcBulgeVertexes(), RB_CalcDeformNormals(), RB_CalcDeformVertexes(), RB_CalcMoveVertexes(), RB_ProjectionShadowDeform(), backEndState_t::refdef, shaderCommands_s::shader, tess, and trRefdef_t::text.
Referenced by RB_StageIteratorGeneric().
void RB_DrawSun (void)
References backEnd, CrossProduct(), shaderCommands_s::fogNum, cvar_s::integer, orientationr_t::modelMatrix, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, viewParms_t::or, orientationr_t::origin, PerpendicularVector(), qglDepthRange, qglLoadMatrixf, qglTranslatef, r_drawSun, RB_BeginSurface(), RB_EndSurface(), backEndState_t::skyRenderedThisView, trGlobals_t::sunDirection, trGlobals_t::sunShader, tess, tr, VectorAdd, VectorCopy, VectorScale, VectorSubtract, backEndState_t::viewParms, viewParms_t::world, and viewParms_t::zFar.
Referenced by RB_RenderDrawSurfList().
void RB_EndSurface (void)
References backEnd, backEndCounters_t::c_indexes, backEndCounters_t::c_shaders, backEndCounters_t::c_totalIndexes, backEndCounters_t::c_vertexes, shaderCommands_s::currentStageIteratorFunc, DrawNormals(), DrawTris(), ERR_DROP, GLimp_LogComment(), cvar_s::integer, shaderCommands_s::numIndexes, shaderCommands_s::numPasses, shaderCommands_s::numVertexes, backEndState_t::pc, r_debugSort, r_shownormals, r_showtris, RB_ShadowTessEnd(), ri, shaderCommands_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, trGlobals_t::shadowShader, shader_s::sort, tess, and tr.
Referenced by RB_CheckOverflow(), RB_ClearDepth(), RB_DrawSun(), RB_DrawSurfs(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), and RB_SwapBuffers().
void RB_ExecuteRenderCommands (const void * data)
References renderCommandList_t::cmds, backEndData_t::commands, cvar_s::integer, refimport_t::Milliseconds, backEndCounters_t::msec, PADP, backEndState_t::pc, r_smp, RB_ClearDepth(), RB_ColorMask(), RB_DrawBuffer(), RB_DrawSurfs(), RB_SetColor(), RB_StretchPic(), RB_SwapBuffers(), RB_TakeScreenshotCmd(), RB_TakeVideoFrameCmd(), RC_CLEARDEPTH, RC_COLORMASK, RC_DRAW_BUFFER, RC_DRAW_SURFS, RC_END_OF_LIST, RC_SCREENSHOT, RC_SET_COLOR, RC_STRETCH_PIC, RC_SWAP_BUFFERS, RC_VIDEOFRAME, ri, and backEndState_t::smpFrame.
Referenced by R_IssueRenderCommands(), and RB_RenderThread().
void RB_IQMSurfaceAnim (surfaceType_t * surface)
References backEnd, refEntity_t::backlerp, iqmData_t::blendIndexes, iqmData_t::blendWeights, iqmData_t::colors, ComputeJointMats(), backEndState_t::currentEntity, srfIQModel_s::data, data, trRefEntity_t::e, srfIQModel_s::first_triangle, srfIQModel_s::first_vertex, refEntity_t::frame, IQM_MAX_JOINTS, iqmData_t::normals, iqmData_t::num_frames, srfIQModel_s::num_triangles, srfIQModel_s::num_vertexes, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, refEntity_t::oldframe, iqmData_t::positions, ptr(), RB_CHECKOVERFLOW, tess, iqmData_t::texcoords, and iqmData_t::triangles.
void RB_ProjectionShadowDeform (void)
References orientationr_t::axis, backEnd, backEndState_t::currentEntity, DotProduct, trRefEntity_t::e, h, trRefEntity_t::lightDir, shaderCommands_s::numVertexes, backEndState_t::or, orientationr_t::origin, refEntity_t::shadowPlane, tess, VectorCopy, and VectorMA().
Referenced by RB_DeformTessGeometry().
void RB_RenderFlares (void)
References flare_s::addedFrame, backEnd, backEndState_t::currentEntity, flare_s::drawIntensity, FLARE_STDCOEFF, flareCoeff, viewParms_t::frameCount, flare_s::frameSceneNum, viewParms_t::frameSceneNum, flare_s::inPortal, cvar_s::integer, viewParms_t::isPortal, cvar_s::modified, flare_s::next, NULL, backEndState_t::or, qfalse, qglDisable, qglLoadIdentity, qglMatrixMode, qglOrtho, qglPopMatrix, qglPushMatrix, qtrue, r_activeFlares, r_flareCoeff, r_flares, r_inactiveFlares, RB_RenderFlare(), RB_TestFlare(), tr, cvar_s::value, backEndState_t::viewParms, viewParms_t::viewportHeight, viewParms_t::viewportWidth, viewParms_t::viewportX, viewParms_t::viewportY, viewParms_t::world, and trGlobals_t::worldEntity.
Referenced by RB_RenderDrawSurfList().
void RB_RenderThread (void)
References data, GLimp_RendererSleep(), qfalse, qtrue, RB_ExecuteRenderCommands(), and renderThreadActive.
Referenced by R_InitCommandBuffers().
void RB_ShadowFinish (void)
References GL_Bind(), GL_State(), glConfig, GLS_DEPTHMASK_TRUE, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, cvar_s::integer, qglBegin, qglColor3f, qglColor4f, qglDisable, qglEnable, qglEnd, qglLoadIdentity, qglStencilFunc, qglVertex3f, r_shadows, glconfig_t::stencilBits, tr, and trGlobals_t::whiteImage.
Referenced by RB_RenderDrawSurfList().
void RB_ShadowTessEnd (void)
References backEnd, Com_Memset, CrossProduct(), backEndState_t::currentEntity, DotProduct, facing, GL_Bind(), GL_State(), glConfig, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_ONE, viewParms_t::isMirror, trRefEntity_t::lightDir, numEdgeDefs, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, qglColor3f, qglColorMask, qglCullFace, qglEnable, qglGetBooleanv, qglStencilFunc, qglStencilOp, R_AddEdgeDef(), R_RenderShadowEdges(), SHADER_MAX_VERTEXES, glconfig_t::stencilBits, tess, tr, VectorCopy, VectorMA(), VectorSubtract, backEndState_t::viewParms, and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
void RB_ShowImages (void)
References end, GL_Bind(), glConfig, h, trGlobals_t::images, cvar_s::integer, refimport_t::Milliseconds, trGlobals_t::numImages, PRINT_ALL, backEndState_t::projection2D, qglBegin, qglClear, qglEnd, qglFinish, qglTexCoord2f, qglVertex2f, r_showImages, RB_SetGL2D(), ri, start, tr, image_s::uploadHeight, image_s::uploadWidth, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by RB_ClearDepth(), RB_SwapBuffers(), and RE_EndRegistration().
void RB_StageIteratorGeneric (void)
References shader_s::cullType, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, shader_s::fogPass, GL_Cull(), GLimp_LogComment(), cvar_s::integer, shader_s::multitextureEnv, shader_s::name, shaderCommands_s::numPasses, shaderCommands_s::numVertexes, shader_s::polygonOffset, ProjectDlightTexture(), qfalse, qglColorPointer, qglDisable, qglDisableClientState, qglEnable, qglEnableClientState, qglLockArraysEXT, qglPolygonOffset, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, qtrue, r_logFile, r_offsetFactor, r_offsetUnits, RB_DeformTessGeometry(), RB_FogPass(), RB_IterateStagesGeneric(), shader, shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, SURF_NODLIGHT, SURF_SKY, shader_s::surfaceFlags, tess, va(), and cvar_s::value.
Referenced by ComputeStageIteratorFunc(), R_ShaderList_f(), and RB_StageIteratorSky().
void RB_StageIteratorLightmappedMultitexture (void)
References shaderStage_t::bundle, shader_s::cullType, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, shader_s::fogPass, GL_Cull(), GL_SelectTexture(), GL_State(), GL_TexEnv(), GLimp_LogComment(), GLS_DEFAULT, cvar_s::integer, shader_s::name, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, ProjectDlightTexture(), qglColor3f, qglColorPointer, qglDisable, qglDisableClientState, qglEnable, qglEnableClientState, qglLockArraysEXT, qglShadeModel, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, r_logFile, RB_FogPass(), shader, shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, tess, va(), and shaderCommands_s::xstages.
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
void RB_StageIteratorSky (void)
References backEnd, trGlobals_t::defaultImage, DrawSkyBox(), GL_State(), trGlobals_t::identityLight, cvar_s::integer, viewParms_t::or, orientationr_t::origin, skyParms_t::outerbox, qglColor3f, qglDepthRange, qglPopMatrix, qglPushMatrix, qglTranslatef, qtrue, R_BuildCloudData(), r_fastsky, r_showsky, RB_ClipSkyPolygons(), RB_StageIteratorGeneric(), shaderCommands_s::shader, shader_s::sky, backEndState_t::skyRenderedThisView, tess, tr, and backEndState_t::viewParms.
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
void RB_StageIteratorVertexLitTexture (void)
References shaderStage_t::bundle, shader_s::cullType, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, shader_s::fogPass, GL_Cull(), GL_State(), GLimp_LogComment(), cvar_s::integer, shader_s::name, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, ProjectDlightTexture(), qglColorPointer, qglEnableClientState, qglLockArraysEXT, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, R_BindAnimatedImage(), R_DrawElements(), r_logFile, RB_CalcDiffuseColor(), RB_FogPass(), shader, shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, shaderStage_t::stateBits, tess, va(), and shaderCommands_s::xstages.
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
void RB_SurfaceAnim (md4Surface_t * surfType)
References backEnd, refEntity_t::backlerp, md4Weight_t::boneIndex, md4Frame_t::bones, md4Weight_t::boneWeight, backEndState_t::currentEntity, DotProduct, trRefEntity_t::e, refEntity_t::frame, md4Bone_t::matrix, MD4_MAX_BONES, md4Vertex_t::normal, md4Header_t::numBones, shaderCommands_s::numIndexes, md4Surface_t::numTriangles, shaderCommands_s::numVertexes, md4Surface_t::numVerts, md4Vertex_t::numWeights, md4Weight_t::offset, md4Header_t::ofsFrames, md4Surface_t::ofsHeader, md4Surface_t::ofsTriangles, md4Surface_t::ofsVerts, refEntity_t::oldframe, RB_CheckOverflow(), tess, md4Vertex_t::texCoords, VectorClear, and md4Vertex_t::weights.
const void* RB_TakeScreenshotCmd (const void * data)
References screenshotCommand_t::fileName, screenshotCommand_t::height, screenshotCommand_t::jpeg, RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), screenshotCommand_t::width, screenshotCommand_t::x, and screenshotCommand_t::y.
Referenced by RB_ExecuteRenderCommands().
const void* RB_TakeVideoFrameCmd (const void * data)
References AVI_LINE_PADDING, videoFrameCommand_t::captureBuffer, refimport_t::CL_WriteAVIVideoFrame, Com_Memset, glconfig_t::deviceSupportsGamma, videoFrameCommand_t::encodeBuffer, videoFrameCommand_t::height, cvar_s::integer, videoFrameCommand_t::motionJpeg, PAD, PADP, qglGetIntegerv, qglReadPixels, R_GammaCorrect(), RE_SaveJPGToBuffer(), ri, and videoFrameCommand_t::width.
Referenced by RB_ExecuteRenderCommands().
void RE_AddAdditiveLightToScene (const vec3_t org, float intensity, float r, float g, float b)
References qtrue, and RE_AddDynamicLightToScene().
Referenced by GetRefAPI().
void RE_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
References qfalse, and RE_AddDynamicLightToScene().
Referenced by GetRefAPI().
void RE_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int num)
References AddPointToBounds(), backEndData, fog_t::bounds, Com_Memcpy, srfPoly_s::fogIndex, world_t::fogs, glConfig, GLHW_RAGEPRO, glconfig_t::hardwareType, srfPoly_s::hShader, max_polys, max_polyverts, polyVert_t::modulate, NULL, world_t::numfogs, srfPoly_s::numVerts, backEndData_t::polys, backEndData_t::polyVerts, PRINT_DEVELOPER, PRINT_WARNING, r_numpolys, r_numpolyverts, trGlobals_t::registered, ri, SF_POLY, trGlobals_t::smpFrame, srfPoly_s::surfaceType, tr, VectorCopy, srfPoly_s::verts, trGlobals_t::world, and polyVert_t::xyz.
Referenced by GetRefAPI().
void RE_AddRefEntityToScene (const refEntity_t * ent)
References backEndData, trRefEntity_t::e, backEndData_t::entities, ERR_DROP, trRefEntity_t::lightingCalculated, MAX_ENTITIES, refEntity_t::origin, PRINT_DEVELOPER, PRINT_WARNING, Q_isnan(), qfalse, qtrue, r_numentities, trGlobals_t::registered, refEntity_t::reType, ri, RT_MAX_REF_ENTITY_TYPE, trGlobals_t::smpFrame, and tr.
Referenced by GetRefAPI().
void RE_BeginFrame (stereoFrame_t stereoFrame)
References drawBufferCommand_t::buffer, drawBufferCommand_t::commandId, colorMaskCommand_t::commandId, clearDepthCommand_t::commandId, refimport_t::Cvar_Set, ERR_FATAL, glstate_t::finishCalled, trGlobals_t::frameCount, trGlobals_t::frameSceneNum, GL_TextureMode(), glConfig, glState, int(), cvar_s::integer, cvar_s::modified, NULL, PRINT_ALL, Q_stricmp(), qfalse, qglClear, qglClearColor, qglClearStencil, qglColorMask, qglDisable, qglDrawBuffer, qglEnable, qglGetError, qglStencilFunc, qglStencilMask, qglStencilOp, r_anaglyphMode, r_drawBuffer, r_gamma, R_GetCommandBuffer(), r_ignoreGLErrors, r_measureOverdraw, R_SetColorMappings(), R_SetColorMode(), r_shadows, R_SyncRenderThread(), r_textureMode, RC_CLEARDEPTH, RC_COLORMASK, RC_DRAW_BUFFER, trGlobals_t::refdef, trGlobals_t::registered, colorMaskCommand_t::rgba, ri, glconfig_t::stencilBits, STEREO_CENTER, STEREO_LEFT, STEREO_RIGHT, glconfig_t::stereoEnabled, trRefdef_t::stereoFrame, cvar_s::string, tr, and U.
Referenced by GetRefAPI().
void RE_BeginRegistration (glconfig_t * glconfig)
References glConfig, qtrue, R_ClearFlares(), R_Init(), R_SyncRenderThread(), RE_ClearScene(), trGlobals_t::registered, tr, and trGlobals_t::viewCluster.
Referenced by GetRefAPI().
void RE_ClearScene (void)
References r_firstSceneDlight, r_firstSceneEntity, r_firstScenePoly, r_numdlights, r_numentities, and r_numpolys.
Referenced by GetRefAPI(), and RE_BeginRegistration().
void RE_EndFrame (int * frontEndMsec, int * backEndMsec)
References backEnd, swapBuffersCommand_t::commandId, trGlobals_t::frontEndMsec, backEndCounters_t::msec, backEndState_t::pc, qtrue, R_GetCommandBuffer(), R_IssueRenderCommands(), R_ToggleSmpFrame(), RC_SWAP_BUFFERS, trGlobals_t::registered, and tr.
Referenced by GetRefAPI().
void RE_LoadWorldMap (const char * mapname)
References b, world_t::baseName, BSP_VERSION, buffer, c_gridVerts, Com_Memset, COM_SkipPath(), COM_StripExtension(), world_t::dataSize, ERR_DROP, fileBase, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, h_low, refimport_t::Hunk_Alloc, LUMP_BRUSHES, LUMP_BRUSHSIDES, LUMP_DRAWINDEXES, LUMP_DRAWVERTS, LUMP_ENTITIES, LUMP_FOGS, LUMP_LEAFS, LUMP_LEAFSURFACES, LUMP_LIGHTGRID, LUMP_LIGHTMAPS, LUMP_MODELS, LUMP_NODES, LUMP_PLANES, LUMP_SHADERS, LUMP_SURFACES, LUMP_VISIBILITY, dheader_t::lumps, world_t::name, NULL, Q_strncpyz(), qtrue, R_LoadEntities(), R_LoadFogs(), R_LoadLightGrid(), R_LoadLightmaps(), R_LoadMarksurfaces(), R_LoadNodesAndLeafs(), R_LoadPlanes(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_LoadVisibility(), ri, s_worldData, trGlobals_t::sunDirection, tr, VectorNormalize(), dheader_t::version, trGlobals_t::world, and trGlobals_t::worldMapLoaded.
Referenced by GetRefAPI().
void RE_RegisterFont (const char * fontName, int pointSize, fontInfo_t * font)
References glyphInfo_t::bottom, Com_Memcpy, Com_Memset, Com_sprintf(), refimport_t::Free, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, refimport_t::FS_WriteFile, glyphInfo_t::glyph, GLYPH_END, GLYPH_START, fontInfo_t::glyphs, GLYPHS_PER_FONT, fontInfo_t::glyphScale, h, glyphInfo_t::height, glyphInfo_t::imageHeight, glyphInfo_t::imageWidth, cvar_s::integer, LIGHTMAP_2D, refimport_t::Malloc, MAX_FONTS, MAX_QPATH, fontInfo_t::name, NULL, out, glyphInfo_t::pitch, PRINT_ALL, PRINT_WARNING, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, R_CreateImage(), r_saveFontData, R_SyncRenderThread(), RE_RegisterShaderFromImage(), RE_RegisterShaderNoMip(), readFloat(), readInt(), registeredFontCount, ri, glyphInfo_t::s, glyphInfo_t::s2, glyphInfo_t::shaderName, glyphInfo_t::t, glyphInfo_t::t2, glyphInfo_t::top, va(), and glyphInfo_t::xSkip.
Referenced by GetRefAPI().
qhandle_t RE_RegisterModel (const char * name)
References COM_GetExtension(), Com_sprintf(), COM_StripExtension(), ext, model_s::index, MAX_QPATH, MOD_BAD, modelExtToLoaderMap_t::ModelLoader, trGlobals_t::models, model_s::name, NULL, model_s::numLods, numModelLoaders, trGlobals_t::numModels, PRINT_ALL, PRINT_DEVELOPER, PRINT_WARNING, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, R_AllocModel(), R_SyncRenderThread(), ri, tr, and model_s::type.
Referenced by GetRefAPI().
qhandle_t RE_RegisterShader (const char * name)
References shader_s::defaultShader, shader_s::index, LIGHTMAP_2D, MAX_QPATH, PRINT_ALL, qtrue, R_FindShader(), and ri.
Referenced by GetRefAPI().
qhandle_t RE_RegisterShaderFromImage (const char * name, int lightmapIndex, image_t * image, qboolean mipRawImage)
References shaderStage_t::active, AGEN_SKIP, AGEN_VERTEX, shaderStage_t::alphaGen, shaderStage_t::bundle, CGEN_EXACT_VERTEX, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_VERTEX, Com_Memset, shader_s::defaultShader, FILE_HASH_SIZE, FinishShader(), generateHashValue(), GLS_DEFAULT, GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_SRC_ALPHA, hash(), textureBundle_t::image, shader_s::index, cvar_s::integer, textureBundle_t::isLightmap, LIGHTMAP_2D, LIGHTMAP_BY_VERTEX, LIGHTMAP_NONE, LIGHTMAP_WHITEIMAGE, shader_s::lightmapIndex, trGlobals_t::lightmaps, MAX_SHADER_STAGES, shader_s::name, shader_s::needsColor, shader_s::needsNormal, shader_s::needsST1, shader_s::needsST2, shader_s::next, trGlobals_t::numLightmaps, Q_stricmp(), Q_strncpyz(), qtrue, r_smp, R_SyncRenderThread(), shaderStage_t::rgbGen, shaderStage_t::stateBits, textureBundle_t::texMods, tr, and trGlobals_t::whiteImage.
Referenced by RE_RegisterFont().
qhandle_t RE_RegisterShaderLightMap (const char * name, int lightmapIndex)
References shader_s::defaultShader, shader_s::index, MAX_QPATH, PRINT_ALL, qtrue, R_FindShader(), and ri.
Referenced by R_RemapShader().
qhandle_t RE_RegisterShaderNoMip (const char * name)
References shader_s::defaultShader, shader_s::index, LIGHTMAP_2D, MAX_QPATH, PRINT_ALL, qfalse, R_FindShader(), and ri.
Referenced by GetRefAPI(), and RE_RegisterFont().
qhandle_t RE_RegisterSkin (const char * name)
References CommaParse(), refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, h_low, refimport_t::Hunk_Alloc, LIGHTMAP_NONE, MAX_QPATH, MAX_SKINS, skinSurface_t::name, skin_s::name, trGlobals_t::numSkins, skin_s::numSurfaces, PRINT_DEVELOPER, PRINT_WARNING, Q_stricmp(), Q_strlwr(), Q_strncpyz(), qtrue, R_FindShader(), R_SyncRenderThread(), ri, skinSurface_t::shader, trGlobals_t::skins, skin_s::surfaces, token, and tr.
Referenced by GetRefAPI().
void RE_RenderScene (const refdef_t * fd)
References refdef_t::areamask, trRefdef_t::areamask, trRefdef_t::areamaskModified, orientationr_t::axis, backEndData, Com_Memcpy, Com_Memset, trRefdef_t::dlights, backEndData_t::dlights, trRefdef_t::drawSurfs, backEndData_t::drawSurfs, trRefdef_t::entities, backEndData_t::entities, ERR_DROP, trRefdef_t::floatTime, refdef_t::fov_x, trRefdef_t::fov_x, refdef_t::fov_y, trRefdef_t::fov_y, viewParms_t::fovX, viewParms_t::fovY, trGlobals_t::frameSceneNum, trGlobals_t::frontEndMsec, glConfig, GLHW_PERMEDIA2, GLimp_LogComment(), glconfig_t::hardwareType, refdef_t::height, trRefdef_t::height, cvar_s::integer, viewParms_t::isPortal, MAX_MAP_AREA_BYTES, refimport_t::Milliseconds, trRefdef_t::num_dlights, trRefdef_t::num_entities, trRefdef_t::numDrawSurfs, trRefdef_t::numPolys, viewParms_t::or, orientationr_t::origin, trRefdef_t::polys, backEndData_t::polys, viewParms_t::pvsOrigin, qfalse, qtrue, r_dynamiclight, r_firstSceneDlight, r_firstSceneDrawSurf, r_firstSceneEntity, r_firstScenePoly, r_norefresh, r_numdlights, r_numentities, r_numpolys, R_RenderView(), r_vertexLight, RDF_NOWORLDMODEL, refdef_t::rdflags, trRefdef_t::rdflags, trGlobals_t::refdef, trGlobals_t::registered, ri, trGlobals_t::sceneCount, trGlobals_t::smpFrame, startTime, trRefdef_t::stereoFrame, viewParms_t::stereoFrame, refdef_t::text, trRefdef_t::text, refdef_t::time, trRefdef_t::time, tr, VectorCopy, glconfig_t::vidHeight, refdef_t::viewaxis, trRefdef_t::viewaxis, refdef_t::vieworg, trRefdef_t::vieworg, viewParms_t::viewportHeight, viewParms_t::viewportWidth, viewParms_t::viewportX, viewParms_t::viewportY, refdef_t::width, trRefdef_t::width, trGlobals_t::world, refdef_t::x, trRefdef_t::x, refdef_t::y, and trRefdef_t::y.
Referenced by GetRefAPI().
void RE_SaveJPG (char * filename, int quality, int image_width, int image_height, unsigned char * image_buffer, int padding)
References refimport_t::FS_WriteFile, refimport_t::Hunk_AllocateTempMemory, refimport_t::Hunk_FreeTempMemory, out, RE_SaveJPGToBuffer(), and ri.
Referenced by RB_TakeScreenshotJPEG().
size_t RE_SaveJPGToBuffer (byte * buffer, size_t bufSize, int quality, int image_width, int image_height, byte * image_buffer, int padding)
References jpeg_compress_struct::comp_info, jpeg_compress_struct::dest, jpeg_destination_mgr::free_in_buffer, jpeg_component_info::h_samp_factor, jpeg_compress_struct::image_height, jpeg_compress_struct::image_width, jpeg_compress_struct::in_color_space, jpeg_compress_struct::input_components, JCS_RGB, jpeg_create_compress, jpeg_destroy_compress(), jpeg_finish_compress(), jpeg_set_defaults(), jpeg_set_quality(), jpeg_start_compress(), jpeg_std_error(), jpeg_write_scanlines(), jpegDest(), jpeg_compress_struct::next_scanline, my_destination_mgr::pub, R_JPGErrorExit(), R_JPGOutputMessage(), my_destination_mgr::size, jpeg_component_info::v_samp_factor, and void().
Referenced by RB_TakeVideoFrameCmd(), and RE_SaveJPG().
void RE_SetColor (const float * rgba)
References setColorCommand_t::color, colorWhite, setColorCommand_t::commandId, R_GetCommandBuffer(), RC_SET_COLOR, trGlobals_t::registered, and tr.
Referenced by GetRefAPI().
void RE_SetWorldVisData (const byte * vis)
References trGlobals_t::externalVisData, and tr.
Referenced by GetRefAPI().
void RE_Shutdown (qboolean destroyWindow)
References refimport_t::Cmd_RemoveCommand, GLimp_Shutdown(), PRINT_ALL, qfalse, R_DeleteTextures(), R_DoneFreeType(), R_ShutdownCommandBuffers(), R_SyncRenderThread(), trGlobals_t::registered, ri, and tr.
Referenced by GetRefAPI().
void RE_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
References stretchPicCommand_t::commandId, h, stretchPicCommand_t::h, R_GetCommandBuffer(), R_GetShaderByHandle(), RC_STRETCH_PIC, trGlobals_t::registered, stretchPicCommand_t::s1, stretchPicCommand_t::s2, stretchPicCommand_t::shader, stretchPicCommand_t::t1, stretchPicCommand_t::t2, tr, stretchPicCommand_t::w, stretchPicCommand_t::x, and stretchPicCommand_t::y.
Referenced by GetRefAPI().
void RE_StretchRaw (int x, int y, int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
References end, ERR_DROP, GL_Bind(), image_s::height, trGlobals_t::identityLight, cvar_s::integer, refimport_t::Milliseconds, PRINT_ALL, qglBegin, qglColor3f, qglEnd, qglFinish, qglTexCoord2f, qglTexImage2D, qglTexParameterf, qglTexSubImage2D, qglVertex2f, r_speeds, R_SyncRenderThread(), RB_SetGL2D(), trGlobals_t::registered, ri, trGlobals_t::scratchImage, start, tr, image_s::uploadHeight, image_s::uploadWidth, and image_s::width.
Referenced by GetRefAPI().
void RE_TakeVideoFrame (int width, int height, byte * captureBuffer, byte * encodeBuffer, qboolean motionJpeg)
References videoFrameCommand_t::captureBuffer, videoFrameCommand_t::commandId, videoFrameCommand_t::encodeBuffer, height, videoFrameCommand_t::height, videoFrameCommand_t::motionJpeg, R_GetCommandBuffer(), RC_VIDEOFRAME, trGlobals_t::registered, tr, width, and videoFrameCommand_t::width.
Referenced by GetRefAPI().
void RE_UploadCinematic (int w, int h, int cols, int rows, const byte * data, int client, qboolean dirty)
References GL_Bind(), image_s::height, qglTexImage2D, qglTexParameterf, qglTexSubImage2D, trGlobals_t::scratchImage, tr, image_s::uploadHeight, image_s::uploadWidth, and image_s::width.
Referenced by GetRefAPI().
Variable Documentation
backEndState_t backEnd
Referenced by Autosprite2Deform(), AutospriteDeform(), ComputeColors(), ComputeTexCoords(), DoRailCore(), DoRailDiscs(), DrawMultitextured(), FillCloudySkySide(), GlobalVectorToLocal(), LerpMeshVertexes_scalar(), LodErrorForVolume(), MakeSkyVec(), ProjectDlightTexture_scalar(), R_Init(), R_InitSkyTexCoords(), R_PerformanceCounters(), RB_AddDlightFlares(), RB_AddFlare(), RB_AddQuadStampExt(), RB_BeginSurface(), RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcBulgeVertexes(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDiffuseColor_scalar(), RB_CalcEnvironmentTexCoords(), RB_CalcFogTexCoords(), RB_CalcSpecularAlpha(), RB_ClipSkyPolygons(), RB_DeformTessGeometry(), RB_DrawSun(), RB_EndSurface(), RB_IQMSurfaceAnim(), RB_ProjectionShadowDeform(), RB_RenderFlare(), RB_RenderFlares(), RB_ShadowTessEnd(), RB_StageIteratorSky(), RB_SurfaceAnim(), RB_SurfaceBeam(), RB_SurfaceEntity(), RB_SurfaceFace(), RB_SurfaceGrid(), RB_SurfaceLightningBolt(), RB_SurfaceMesh(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RB_SurfaceSprite(), RB_SurfaceTriangles(), RB_TestFlare(), and RE_EndFrame().
backEndData_t* backEndData[SMP_FRAMES]
Referenced by FixRenderCommandList(), R_GetCommandBuffer(), R_Init(), R_IssueRenderCommands(), R_ToggleSmpFrame(), RE_AddDynamicLightToScene(), RE_AddPolyToScene(), RE_AddRefEntityToScene(), and RE_RenderScene().
float displayAspect
Referenced by GLimp_CompareModes(), and GLimp_SetMode().
int gl_filter_max
Referenced by GL_TextureMode(), and Upload32().
int gl_filter_min
Referenced by GL_TextureMode(), and Upload32().
glconfig_t glConfig
Referenced by CollapseMultitexture(), FinishShader(), GL_TextureMode(), GLimp_HaveExtension(), GLimp_Init(), GLimp_InitExtensions(), GLimp_SetGamma(), GLimp_SetMode(), GLimp_Shutdown(), R_InitCommandBuffers(), R_IssueRenderCommands(), R_LightScaleTexture(), R_LoadLightmaps(), R_PerformanceCounters(), R_SetColorMappings(), R_ShutdownCommandBuffers(), R_SyncRenderThread(), RB_IterateStagesGeneric(), RB_SetGL2D(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_ShowImages(), RB_SwapBuffers(), RE_AddDynamicLightToScene(), RE_AddPolyToScene(), RE_BeginFrame(), RE_BeginRegistration(), RE_RenderScene(), ShaderForShaderNum(), SurfIsOffscreen(), and Upload32().
glstate_t glState
Referenced by GL_Bind(), GL_BindMultitexture(), GL_Cull(), GL_SelectTexture(), GL_State(), GL_TexEnv(), GLimp_Shutdown(), R_ArrayElementDiscrete(), R_DeleteTextures(), RB_BeginDrawingView(), RB_SwapBuffers(), RB_TestFlare(), and RE_BeginFrame().
int max_polys
Referenced by R_Init(), and RE_AddPolyToScene().
int max_polyverts
Referenced by R_Init(), and RE_AddPolyToScene().
int maxAnisotropy
Referenced by GLimp_InitExtensions(), and Upload32().
cvar_t* r_allowExtensions
Referenced by GLimp_InitExtensions().
cvar_t* r_anaglyphMode
Referenced by RE_BeginFrame().
cvar_t* r_clear
Referenced by RB_DrawBuffer().
cvar_t* r_colorbits
Referenced by GLimp_SetMode().
cvar_t* r_colorMipLevels
Referenced by Upload32().
cvar_t* r_debugSort
Referenced by RB_EndSurface().
cvar_t* r_debugSurface
Referenced by R_DebugGraphics().
cvar_t* r_depthbits
Referenced by GLimp_SetMode().
cvar_t* r_detailTextures
Referenced by FinishShader().
cvar_t* r_dlightBacks
Referenced by ProjectDlightTexture_scalar().
cvar_t* r_drawBuffer
Referenced by GLimp_EndFrame(), and RE_BeginFrame().
cvar_t* r_drawentities
Referenced by R_AddEntitySurfaces().
cvar_t* r_drawSun
Referenced by RB_DrawSun().
cvar_t* r_drawworld
Referenced by R_AddWorldSurfaces().
cvar_t* r_dynamiclight
Referenced by RE_RenderScene().
cvar_t* r_ext_compiled_vertex_array
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_compressed_textures
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_max_anisotropy
Referenced by Upload32().
cvar_t* r_ext_multisample
Referenced by GLimp_SetMode().
cvar_t* r_ext_multitexture
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_texture_env_add
Referenced by GLimp_InitExtensions().
cvar_t* r_ext_texture_filter_anisotropic
Referenced by GLimp_InitExtensions().
cvar_t* r_facePlaneCull
Referenced by R_CullSurface().
cvar_t* r_fastsky
Referenced by R_MirrorViewBySurface(), RB_BeginDrawingView(), and RB_StageIteratorSky().
cvar_t* r_finish
Referenced by RB_BeginDrawingView().
cvar_t* r_flareCoeff
Referenced by RB_RenderFlares().
cvar_t* r_flareFade
Referenced by RB_TestFlare().
cvar_t* r_flares
Referenced by RB_AddDlightFlares(), RB_RenderFlares(), and RB_SurfaceFlare().
cvar_t* r_flareSize
Referenced by RB_RenderFlare().
cvar_t* r_fullbright
Referenced by ShaderForShaderNum().
cvar_t* r_fullscreen
Referenced by GLimp_EndFrame(), GLimp_Init(), and GLimp_StartDriverAndSetMode().
cvar_t* r_gamma
Referenced by R_SetColorMappings(), and RE_BeginFrame().
cvar_t* r_greyscale
Referenced by ComputeColors(), ProjectDlightTexture_scalar(), and Upload32().
cvar_t* r_ignore
cvar_t* r_ignoreFastPath
Referenced by ComputeStageIteratorFunc().
cvar_t* r_ignoreGLErrors
Referenced by RE_BeginFrame().
cvar_t* r_ignorehwgamma
Referenced by GLimp_SetGamma().
cvar_t* r_inGameVideo
cvar_t* r_intensity
Referenced by R_SetColorMappings().
cvar_t* r_lightmap
Referenced by DrawMultitextured(), R_LoadLightmaps(), RB_IterateStagesGeneric(), and RB_StageIteratorLightmappedMultitexture().
cvar_t* r_lockpvs
Referenced by R_MarkLeaves().
cvar_t* r_lodbias
Referenced by R_ComputeLOD().
cvar_t* r_lodCurveError
Referenced by LodErrorForVolume().
cvar_t* r_lodscale
Referenced by R_ComputeLOD().
cvar_t* r_logFile
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
cvar_t* r_mapOverBrightBits
Referenced by R_ColorShiftLightingBytes().
cvar_t* r_marksOnTriangleMeshes
Referenced by R_MarkFragments().
cvar_t* r_measureOverdraw
Referenced by RB_BeginDrawingView(), RB_SwapBuffers(), and RE_BeginFrame().
cvar_t* r_mode
Referenced by GLimp_Init().
cvar_t* r_nobind
Referenced by GL_Bind(), and GL_BindMultitexture().
cvar_t* r_noborder
Referenced by GLimp_Init().
cvar_t* r_nocull
Referenced by R_CullLocalBox(), R_CullPointAndRadius(), R_CullSurface(), and R_RecursiveWorldNode().
cvar_t* r_nocurves
Referenced by R_CullGrid().
cvar_t* r_noportals
Referenced by R_MirrorViewBySurface().
cvar_t* r_norefresh
Referenced by RE_RenderScene().
cvar_t* r_novis
Referenced by R_MarkLeaves().
cvar_t* r_offsetFactor
Referenced by RB_StageIteratorGeneric().
cvar_t* r_offsetUnits
Referenced by RB_StageIteratorGeneric().
cvar_t* r_overBrightBits
Referenced by R_SetColorMappings().
cvar_t* r_picmip
Referenced by Upload32().
cvar_t* r_portalOnly
Referenced by R_SortDrawSurfs().
cvar_t* r_primitives
Referenced by R_DrawElements().
cvar_t* r_printShaders
Referenced by R_FindShader().
cvar_t* r_railCoreWidth
Referenced by RB_SurfaceRailCore().
cvar_t* r_railSegmentLength
Referenced by RB_SurfaceRailRings().
cvar_t* r_railWidth
Referenced by DoRailDiscs().
cvar_t* r_roundImagesDown
Referenced by Upload32().
cvar_t* r_saveFontData
Referenced by RE_RegisterFont().
cvar_t* r_shadows
Referenced by R_AddIQMSurfaces(), R_AddMD3Surfaces(), RB_BeginDrawingView(), RB_ShadowFinish(), and RE_BeginFrame().
cvar_t* r_showcluster
Referenced by R_MarkLeaves().
cvar_t* r_showImages
Referenced by RB_ClearDepth(), RB_ShowImages(), and RB_SwapBuffers().
cvar_t* r_shownormals
Referenced by RB_EndSurface().
cvar_t* r_showsky
Referenced by RB_StageIteratorSky().
cvar_t* r_showSmp
Referenced by R_IssueRenderCommands().
cvar_t* r_showtris
Referenced by RB_EndSurface().
cvar_t* r_simpleMipMaps
Referenced by R_MipMap().
cvar_t* r_singleShader
Referenced by ParseFace(), ParseFlare(), ParseMesh(), and ParseTriSurf().
cvar_t* r_skipBackEnd
Referenced by R_IssueRenderCommands().
cvar_t* r_smp
Referenced by R_FindShader(), R_InitCommandBuffers(), R_ToggleSmpFrame(), RB_ExecuteRenderCommands(), and RE_RegisterShaderFromImage().
cvar_t* r_speeds
Referenced by R_PerformanceCounters(), and RE_StretchRaw().
cvar_t* r_stencilbits
Referenced by GLimp_SetMode().
cvar_t* r_stereoEnabled
Referenced by GLimp_SetMode().
cvar_t* r_stereoSeparation
Referenced by R_SetupProjection().
cvar_t* r_subdivisions
cvar_t* r_swapInterval
Referenced by GLimp_SetMode().
cvar_t* r_texturebits
Referenced by Upload32().
cvar_t* r_textureMode
Referenced by RE_BeginFrame().
cvar_t* r_uiFullScreen
Referenced by FinishShader(), and RB_IterateStagesGeneric().
cvar_t* r_verbose
cvar_t* r_vertexLight
Referenced by FinishShader(), R_LoadEntities(), R_LoadLightmaps(), RB_IterateStagesGeneric(), RE_RenderScene(), and ShaderForShaderNum().
cvar_t* r_znear
Referenced by R_SetupProjectionZ(), and RB_RenderDrawSurfList().
cvar_t* r_zproj
Referenced by R_RenderView().
void(* rb_surfaceTable[SF_NUM_SURFACE_TYPES])(void *)
Referenced by RB_RenderDrawSurfList(), and SurfIsOffscreen().
volatile renderCommandList_t* renderCommandList
volatile qboolean renderThreadActive
Referenced by R_IssueRenderCommands(), and RB_RenderThread().
refimport_t ri
Referenced by Autosprite2Deform(), AutospriteDeform(), CL_InitRef(), ClipSkyPolygon(), CloseBufferedFile(), Com_Error(), Com_Printf(), ComputeTexCoords(), DecompressIDATs(), empty_output_buffer(), FillCloudBox(), FillCloudySkySide(), FinishShader(), GeneratePermanentShader(), GetRefAPI(), GfxInfo_f(), GL_Bind(), GL_CheckErrors(), GL_SelectTexture(), GL_State(), GL_TexEnv(), GL_TextureMode(), GLimp_DetectAvailableModes(), GLimp_EndFrame(), GLimp_Init(), GLimp_InitExtensions(), GLimp_SetGamma(), GLimp_SetMode(), GLimp_Shutdown(), GLimp_SpawnRenderThread(), GLimp_StartDriverAndSetMode(), LogLight(), NameToAFunc(), NameToDstBlendMode(), NameToGenFunc(), NameToSrcBlendMode(), ParseDeform(), ParseFace(), ParseFlare(), ParseShader(), ParseSkyParms(), ParseSort(), ParseStage(), ParseTexMod(), ParseTriSurf(), ParseVector(), ParseWaveForm(), ProjectDlightTexture_scalar(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_AllocModel(), R_BindAnimatedImage(), R_ComputeLOD(), R_CreateFogImage(), R_CreateImage(), R_CreateSurfaceGridMesh(), R_FindImageFile(), R_FindShader(), R_FreeSurfaceGridMesh(), R_GetCommandBuffer(), R_GetShaderByHandle(), R_ImageList_f(), R_Init(), R_InitCommandBuffers(), R_InitFreeType(), R_InitShaders(), R_InitSkins(), R_inPVS(), R_IssueRenderCommands(), R_JPGErrorExit(), R_JPGOutputMessage(), R_LevelShot(), R_LoadBMP(), R_LoadEntities(), R_LoadFogs(), R_LoadImage(), R_LoadIQM(), R_LoadJPG(), R_LoadLightGrid(), R_LoadLightmaps(), R_LoadMarksurfaces(), R_LoadMD3(), R_LoadMD4(), R_LoadNodesAndLeafs(), R_LoadPCX(), R_LoadPlanes(), R_LoadPNG(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_LoadTGA(), R_LoadVisibility(), R_MarkLeaves(), R_MipMap2(), R_ModeList_f(), R_Modellist_f(), R_MovePatchSurfacesToHunk(), R_PerformanceCounters(), R_PointInLeaf(), R_Register(), R_RegisterIQM(), R_RegisterMD3(), R_RemapShader(), R_ScreenShot_f(), R_ScreenShotJPEG_f(), R_SetColorMappings(), R_SetupEntityLighting(), R_ShaderList_f(), R_SkinList_f(), R_StitchAllPatches(), RB_CalcDiffuseColor_scalar(), RB_CalcWaveColor(), RB_CheckOverflow(), RB_EndSurface(), RB_ExecuteRenderCommands(), RB_ReadPixels(), RB_SetGL2D(), RB_ShowImages(), RB_SurfaceBad(), RB_SwapBuffers(), RB_TakeScreenshot(), RB_TakeScreenshotJPEG(), RB_TakeVideoFrameCmd(), RE_AddPolyToScene(), RE_AddRefEntityToScene(), RE_BeginFrame(), RE_EndRegistration(), RE_LoadWorldMap(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterShader(), RE_RegisterShaderLightMap(), RE_RegisterShaderNoMip(), RE_RegisterSkin(), RE_RenderScene(), RE_SaveJPG(), RE_Shutdown(), RE_StretchRaw(), ReadBufferedFile(), ResampleTexture(), ScanAndLoadShaderFiles(), ShaderForShaderNum(), spillee(), TableForFunc(), and Upload32().
shaderCommands_t tess
Referenced by Autosprite2Deform(), AutospriteDeform(), DeformText(), DoRailCore(), DoRailDiscs(), FillCloudySkySide(), LerpMeshVertexes_scalar(), R_ArrayElementDiscrete(), R_BuildCloudData(), R_DrawStripElements(), R_Init(), R_RenderShadowEdges(), RB_AddQuadStampExt(), RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcBulgeVertexes(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDeformNormals(), RB_CalcDeformVertexes(), RB_CalcDiffuseColor_scalar(), RB_CalcEnvironmentTexCoords(), RB_CalcFogTexCoords(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_CalcMoveVertexes(), RB_CalcRotateTexCoords(), RB_CalcScaleTexCoords(), RB_CalcScrollTexCoords(), RB_CalcSpecularAlpha(), RB_CalcTransformTexCoords(), RB_CalcTurbulentTexCoords(), RB_CalcWaveAlpha(), RB_CalcWaveColor(), RB_CheckOverflow(), RB_ClearDepth(), RB_DeformTessGeometry(), RB_DrawSun(), RB_DrawSurfs(), RB_EndSurface(), RB_IQMSurfaceAnim(), RB_ProjectionShadowDeform(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_ShadowTessEnd(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), RB_StretchPic(), RB_SurfaceAnim(), RB_SurfaceFace(), RB_SurfaceFlare(), RB_SurfaceGrid(), RB_SurfaceMesh(), RB_SurfacePolychain(), RB_SurfaceTriangles(), RB_SwapBuffers(), SurfIsOffscreen(), and TableForFunc().
qboolean textureFilterAnisotropic
Referenced by GLimp_InitExtensions(), and Upload32().
trGlobals_t tr
Referenced by Autosprite2Deform(), AutospriteDeform(), Bullet_Fire(), CanDamage(), CG_ShotgunPellet(), CheckGauntletAttack(), ComputeColors(), CreateExternalShaders(), CreateInternalShaders(), DrawNormals(), DrawTris(), FinishSpawningItem(), FixRenderCommandList(), G_CheckProxMinePosition(), G_RunItem(), G_RunMissile(), G_TestEntityPosition(), GeneratePermanentShader(), genline(), GfxInfo_f(), GL_Bind(), GL_BindMultitexture(), GL_TextureMode(), kf_bfly2(), LerpMeshVertexes_scalar(), main(), ParseFace(), ParseFlare(), ParseMesh(), ParseShader(), ParseSkyParms(), ParseStage(), ParseTriSurf(), Pickup_Powerup(), ProjectDlightTexture_scalar(), ProjectRadius(), R_AddAnimSurfaces(), R_AddBrushModelSurfaces(), R_AddDrawSurfCmd(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_AddPolygonSurfaces(), R_AddWorldSurface(), R_AddWorldSurfaces(), R_AllocModel(), R_BoxSurfaces_r(), R_ClusterPVS(), R_ColorShiftLightingBytes(), R_ComputeFogNum(), R_ComputeIQMFogNum(), R_ComputeLOD(), R_CreateBuiltinImages(), R_CreateDefaultImage(), R_CreateDlightImage(), R_CreateFogImage(), R_CreateImage(), R_CullGrid(), R_CullIQM(), R_CullModel(), R_CullSurface(), R_DeleteTextures(), R_DlightBmodel(), R_DlightFace(), R_DlightGrid(), R_DlightSurface(), R_DlightTrisurf(), R_FindShader(), R_FindShaderByName(), R_FogFactor(), R_GetCommandBuffer(), R_GetModelByHandle(), R_GetShaderByHandle(), R_GetSkinByHandle(), R_ImageList_f(), R_Init(), R_InitFogTable(), R_InitSkins(), R_IssueRenderCommands(), R_LevelShot(), R_LightForPoint(), R_LoadFogs(), R_LoadIQM(), R_LoadLightmaps(), R_LoadVisibility(), R_MarkFragments(), R_MarkLeaves(), R_ModelInit(), R_Modellist_f(), R_PerformanceCounters(), R_PointInLeaf(), R_RecursiveWorldNode(), R_RemapShader(), R_SetColorMappings(), R_SetupEntityLighting(), R_SetupEntityLightingGrid(), R_ShaderList_f(), R_SkinList_f(), R_SumOfUsedImages(), R_SyncRenderThread(), R_ToggleSmpFrame(), RB_AddDlightFlares(), RB_CalcBulgeVertexes(), RB_CalcFogTexCoords(), RB_CalcRotateTexCoords(), RB_CalcTurbulentTexCoords(), RB_CalcWaveColor(), RB_DrawSun(), RB_EndSurface(), RB_FogPass(), RB_IterateStagesGeneric(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_RenderFlares(), RB_ShadowFinish(), RB_ShadowTessEnd(), RB_ShowImages(), RB_StageIteratorSky(), RB_SurfaceAxis(), RB_SurfaceBeam(), RE_AddDynamicLightToScene(), RE_AddPolyToScene(), RE_AddRefEntityToScene(), RE_BeginFrame(), RE_BeginRegistration(), RE_EndFrame(), RE_LoadWorldMap(), RE_RegisterModel(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), RE_RenderScene(), RE_SetColor(), RE_SetWorldVisData(), RE_Shutdown(), RE_StretchPic(), RE_StretchRaw(), RE_TakeVideoFrame(), RE_UploadCinematic(), setup(), ShaderForShaderNum(), ShotgunPellet(), SortNewShader(), stringify(), TableForFunc(), target_laser_think(), and Weapon_LightningFire().