ioquake3: code/renderer/tr_surface.c File Reference
tr_surface.c File Reference
#include "tr_local.h"
Defines
#define NUM_BEAM_SEGS 6
Functions
void RB_CheckOverflow (int verts, int indexes)
void RB_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, byte *color, float s1, float t1, float s2, float t2)
void RB_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, byte *color)
static void RB_SurfaceSprite (void)
static void RB_SurfacePolychain (srfPoly_t *p)
static void RB_SurfaceTriangles (srfTriangles_t *srf)
static void RB_SurfaceBeam (void)
static void DoRailCore (const vec3_t start, const vec3_t end, const vec3_t up, float len, float spanWidth)
static void DoRailDiscs (int numSegs, const vec3_t start, const vec3_t dir, const vec3_t right, const vec3_t up)
static void RB_SurfaceRailRings (void)
static void RB_SurfaceRailCore (void)
static void RB_SurfaceLightningBolt (void)
static void VectorArrayNormalize (vec4_t *normals, unsigned int count)
static void LerpMeshVertexes_scalar (md3Surface_t *surf, float backlerp)
static void LerpMeshVertexes (md3Surface_t *surf, float backlerp)
static void RB_SurfaceMesh (md3Surface_t *surface)
static void RB_SurfaceFace (srfSurfaceFace_t *surf)
static float LodErrorForVolume (vec3_t local, float radius)
static void RB_SurfaceGrid (srfGridMesh_t *cv)
static void RB_SurfaceAxis (void)
static void RB_SurfaceEntity (surfaceType_t *surfType)
static void RB_SurfaceBad (surfaceType_t *surfType)
static void RB_SurfaceFlare (srfFlare_t *surf)
static void RB_SurfaceDisplayList (srfDisplayList_t *surf)
static void RB_SurfaceSkip (void *surf)
Variables
void(* rb_surfaceTable [SF_NUM_SURFACE_TYPES])(void *)
Define Documentation
#define NUM_BEAM_SEGS 6
Referenced by RB_SurfaceBeam().
Function Documentation
static void DoRailCore (const vec3_t start, const vec3_t end, const vec3_t up, float len, float spanWidth) [static]
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, refEntity_t::shaderRGBA, t, tess, and VectorMA().
Referenced by RB_SurfaceLightningBolt(), and RB_SurfaceRailCore().
static void DoRailDiscs (int numSegs, const vec3_t start, const vec3_t dir, const vec3_t right, const vec3_t up) [static]
References backEnd, backEndState_t::currentEntity, DEG2RAD, trRefEntity_t::e, cvar_s::integer, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, r_railWidth, RB_CHECKOVERFLOW, s, refEntity_t::shaderRGBA, tess, VectorAdd, and VectorCopy.
Referenced by RB_SurfaceRailRings().
static void LerpMeshVertexes (md3Surface_t * surf, float backlerp) [static]
References com_altivec, cvar_s::integer, and LerpMeshVertexes_scalar().
Referenced by RB_SurfaceMesh().
static void LerpMeshVertexes_scalar (md3Surface_t * surf, float backlerp) [static]
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, refEntity_t::frame, FUNCTABLE_MASK, FUNCTABLE_SIZE, MD3_XYZ_SCALE, shaderCommands_s::numVertexes, md3Surface_t::numVerts, md3Surface_t::ofsXyzNormals, refEntity_t::oldframe, trGlobals_t::sinTable, tess, tr, and VectorArrayNormalize().
Referenced by LerpMeshVertexes().
static float LodErrorForVolume (vec3_t local, float radius) [static]
References orientationr_t::axis, backEnd, DotProduct, viewParms_t::or, backEndState_t::or, orientationr_t::origin, r_lodCurveError, cvar_s::value, VectorSubtract, and backEndState_t::viewParms.
Referenced by RB_SurfaceGrid().
void RB_AddQuadStamp (vec3_t origin, vec3_t left, vec3_t up, byte * color)
References RB_AddQuadStampExt().
Referenced by AutospriteDeform(), and RB_SurfaceSprite().
void RB_AddQuadStampExt (vec3_t origin, vec3_t left, vec3_t up, byte * color, float s1, float t1, float s2, float t2)
References orientationr_t::axis, backEnd, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, viewParms_t::or, RB_CHECKOVERFLOW, tess, vec3_origin, VectorSubtract, and backEndState_t::viewParms.
Referenced by DeformText(), and RB_AddQuadStamp().
void RB_CheckOverflow (int verts, int indexes)
References ERR_DROP, shaderCommands_s::fogNum, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, RB_BeginSurface(), RB_EndSurface(), ri, shaderCommands_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, and tess.
Referenced by RB_SurfaceAnim().
static void RB_SurfaceAxis (void) [static]
References GL_Bind(), qglBegin, qglColor3f, qglEnd, qglLineWidth, qglVertex3f, tr, and trGlobals_t::whiteImage.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceBad (surfaceType_t * surfType) [static]
References PRINT_ALL, and ri.
static void RB_SurfaceBeam (void) [static]
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, GL_Bind(), GL_State(), GLS_DSTBLEND_ONE, GLS_SRCBLEND_ONE, NUM_BEAM_SEGS, refEntity_t::oldorigin, refEntity_t::origin, PerpendicularVector(), qglBegin, qglColor3f, qglEnd, qglVertex3fv, RotatePointAroundVector(), tr, VectorAdd, VectorNormalize(), VectorScale, and trGlobals_t::whiteImage.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceDisplayList (srfDisplayList_t * surf) [static]
References srfDisplayList_s::listNum, and qglCallList.
static void RB_SurfaceEntity (surfaceType_t * surfType) [static]
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, RB_SurfaceAxis(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RB_SurfaceSprite(), refEntity_t::reType, RT_BEAM, RT_LIGHTNING, RT_RAIL_CORE, RT_RAIL_RINGS, and RT_SPRITE.
static void RB_SurfaceFace (srfSurfaceFace_t * surf) [static]
References backEnd, srfSurfaceFace_t::dlightBits, shaderCommands_s::dlightBits, shader_s::needsNormal, shaderCommands_s::numIndexes, srfSurfaceFace_t::numIndices, srfSurfaceFace_t::numPoints, shaderCommands_s::numVertexes, RB_CHECKOVERFLOW, shaderCommands_s::shader, backEndState_t::smpFrame, tess, VectorCopy, and VERTEXSIZE.
static void RB_SurfaceFlare (srfFlare_t * surf) [static]
References srfFlare_s::color, shaderCommands_s::fogNum, cvar_s::integer, srfFlare_s::normal, srfFlare_s::origin, r_flares, RB_AddFlare(), and tess.
static void RB_SurfaceGrid (srfGridMesh_t * cv) [static]
References backEnd, drawVert_t::color, srfGridMesh_s::dlightBits, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, h, srfGridMesh_s::height, srfGridMesh_s::heightLodError, drawVert_t::lightmap, LodErrorForVolume(), srfGridMesh_s::lodOrigin, srfGridMesh_s::lodRadius, MAX_GRID_SIZE, shader_s::needsNormal, drawVert_t::normal, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, RB_BeginSurface(), RB_EndSurface(), shaderCommands_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, backEndState_t::smpFrame, drawVert_t::st, tess, srfGridMesh_s::verts, srfGridMesh_s::width, srfGridMesh_s::widthLodError, and drawVert_t::xyz.
static void RB_SurfaceLightningBolt (void) [static]
References backEnd, CrossProduct(), backEndState_t::currentEntity, DoRailCore(), trRefEntity_t::e, end, refEntity_t::oldorigin, viewParms_t::or, orientationr_t::origin, refEntity_t::origin, right, RotatePointAroundVector(), start, VectorCopy, VectorNormalize(), VectorSubtract, and backEndState_t::viewParms.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceMesh (md3Surface_t * surface) [static]
References backEnd, refEntity_t::backlerp, backEndState_t::currentEntity, trRefEntity_t::e, refEntity_t::frame, LerpMeshVertexes(), shaderCommands_s::numIndexes, md3Surface_t::numTriangles, shaderCommands_s::numVertexes, md3Surface_t::numVerts, md3Surface_t::ofsSt, md3Surface_t::ofsTriangles, refEntity_t::oldframe, RB_CHECKOVERFLOW, and tess.
static void RB_SurfacePolychain (srfPoly_t * p) [static]
References polyVert_t::modulate, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, srfPoly_s::numVerts, RB_CHECKOVERFLOW, polyVert_t::st, tess, VectorCopy, srfPoly_s::verts, and polyVert_t::xyz.
static void RB_SurfaceRailCore (void) [static]
References backEnd, CrossProduct(), backEndState_t::currentEntity, DoRailCore(), trRefEntity_t::e, end, cvar_s::integer, refEntity_t::oldorigin, viewParms_t::or, orientationr_t::origin, refEntity_t::origin, r_railCoreWidth, right, start, VectorCopy, VectorNormalize(), VectorSubtract, and backEndState_t::viewParms.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceRailRings (void) [static]
References backEnd, backEndState_t::currentEntity, DoRailDiscs(), trRefEntity_t::e, end, if(), MakeNormalVectors(), refEntity_t::oldorigin, refEntity_t::origin, r_railSegmentLength, right, start, up, cvar_s::value, VectorCopy, VectorNormalize(), VectorScale, and VectorSubtract.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceSkip (void * surf) [static]
static void RB_SurfaceSprite (void) [static]
References orientationr_t::axis, backEnd, backEndState_t::currentEntity, trRefEntity_t::e, viewParms_t::isMirror, M_PI, viewParms_t::or, refEntity_t::origin, refEntity_t::radius, RB_AddQuadStamp(), refEntity_t::rotation, s, refEntity_t::shaderRGBA, up, vec3_origin, VectorMA(), VectorScale, VectorSubtract, and backEndState_t::viewParms.
Referenced by RB_SurfaceEntity().
static void RB_SurfaceTriangles (srfTriangles_t * srf) [static]
References backEnd, srfTriangles_t::dlightBits, shaderCommands_s::dlightBits, srfTriangles_t::indexes, shader_s::needsNormal, srfTriangles_t::numIndexes, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, srfTriangles_t::numVerts, RB_CHECKOVERFLOW, shaderCommands_s::shader, backEndState_t::smpFrame, tess, and srfTriangles_t::verts.
static void VectorArrayNormalize (vec4_t * normals, unsigned int count) [static]
References B, and VectorNormalizeFast().
Referenced by LerpMeshVertexes_scalar().
Variable Documentation
void(* rb_surfaceTable[SF_NUM_SURFACE_TYPES])(void *)
Initial value:
 {
        (void(*)(void*))RB_SurfaceBad,
        (void(*)(void*))RB_SurfaceSkip,
        (void(*)(void*))RB_SurfaceFace,
        (void(*)(void*))RB_SurfaceGrid,
        (void(*)(void*))RB_SurfaceTriangles,
        (void(*)(void*))RB_SurfacePolychain,
        (void(*)(void*))RB_SurfaceMesh,
        (void(*)(void*))RB_SurfaceAnim,
        (void(*)(void*))RB_IQMSurfaceAnim,
        (void(*)(void*))RB_SurfaceFlare,
        (void(*)(void*))RB_SurfaceEntity,
        (void(*)(void*))RB_SurfaceDisplayList
}
Referenced by RB_RenderDrawSurfList(), and SurfIsOffscreen().