ioquake3: code/renderer/tr_image_png.c File Reference
tr_image_png.c File Reference
#include "tr_local.h"
#include "../qcommon/puff.h"
Data Structures
struct PNG_ChunkHeader
struct PNG_Chunk_IHDR
struct PNG_ZlibHeader
struct BufferedFile
Defines
#define INT_MAX 0x1fffffff
#define Q3IMAGE_BYTESPERPIXEL (4)
#define PNG_Signature "\x89\x50\x4E\x47\xD\xA\x1A\xA"
#define PNG_Signature_Size (8)
#define PNG_ChunkHeader_Size (8)
#define PNG_ChunkCRC_Size (4)
#define MAKE_CHUNKTYPE(a, b, c, d) (((a) << 24) | ((b) << 16) | ((c) << 8) | ((d)))
#define PNG_ChunkType_IHDR MAKE_CHUNKTYPE('I', 'H', 'D', 'R')
#define PNG_ChunkType_PLTE MAKE_CHUNKTYPE('P', 'L', 'T', 'E')
#define PNG_ChunkType_IDAT MAKE_CHUNKTYPE('I', 'D', 'A', 'T')
#define PNG_ChunkType_IEND MAKE_CHUNKTYPE('I', 'E', 'N', 'D')
#define PNG_ChunkType_tRNS MAKE_CHUNKTYPE('t', 'R', 'N', 'S')
#define PNG_Chunk_IHDR_Size (13)
#define PNG_ColourType_Grey (0)
#define PNG_ColourType_True (2)
#define PNG_ColourType_Indexed (3)
#define PNG_ColourType_GreyAlpha (4)
#define PNG_ColourType_TrueAlpha (6)
#define PNG_NumColourComponents_Grey (1)
#define PNG_NumColourComponents_True (3)
#define PNG_NumColourComponents_Indexed (1)
#define PNG_NumColourComponents_GreyAlpha (2)
#define PNG_NumColourComponents_TrueAlpha (4)
#define PNG_BitDepth_1 (1)
#define PNG_BitDepth_2 (2)
#define PNG_BitDepth_4 (4)
#define PNG_BitDepth_8 (8)
#define PNG_BitDepth_16 (16)
#define PNG_CompressionMethod_0 (0)
#define PNG_FilterMethod_0 (0)
#define PNG_FilterType_None (0)
#define PNG_FilterType_Sub (1)
#define PNG_FilterType_Up (2)
#define PNG_FilterType_Average (3)
#define PNG_FilterType_Paeth (4)
#define PNG_InterlaceMethod_NonInterlaced (0)
#define PNG_InterlaceMethod_Interlaced (1)
#define PNG_Adam7_NumPasses (7)
#define PNG_ZlibHeader_Size (2)
#define PNG_ZlibCheckValue_Size (4)
Typedefs
typedef uint32_t PNG_ChunkCRC
Functions
static struct BufferedFile * ReadBufferedFile (const char *name)
static void CloseBufferedFile (struct BufferedFile *BF)
static void * BufferedFileRead (struct BufferedFile *BF, unsigned Length)
static qboolean BufferedFileRewind (struct BufferedFile *BF, unsigned Offset)
static qboolean BufferedFileSkip (struct BufferedFile *BF, unsigned Offset)
static qboolean FindChunk (struct BufferedFile *BF, uint32_t ChunkType)
static uint32_t DecompressIDATs (struct BufferedFile *BF, uint8_t **Buffer)
static uint8_t PredictPaeth (uint8_t a, uint8_t b, uint8_t c)
static qboolean UnfilterImage (uint8_t *DecompressedData, uint32_t ImageHeight, uint32_t BytesPerScanline, uint32_t BytesPerPixel)
static qboolean ConvertPixel (struct PNG_Chunk_IHDR *IHDR, byte *OutPtr, uint8_t *DecompPtr, qboolean HasTransparentColour, uint8_t *TransparentColour, uint8_t *OutPal)
static qboolean DecodeImageNonInterlaced (struct PNG_Chunk_IHDR *IHDR, byte *OutBuffer, uint8_t *DecompressedData, uint32_t DecompressedDataLength, qboolean HasTransparentColour, uint8_t *TransparentColour, uint8_t *OutPal)
static qboolean DecodeImageInterlaced (struct PNG_Chunk_IHDR *IHDR, byte *OutBuffer, uint8_t *DecompressedData, uint32_t DecompressedDataLength, qboolean HasTransparentColour, uint8_t *TransparentColour, uint8_t *OutPal)
void R_LoadPNG (const char *name, byte **pic, int *width, int *height)
Define Documentation
#define INT_MAX 0x1fffffff
Referenced by array(), CL_CheckFileSize(), CL_SetCGameTime(), iss32(), R_LoadPNG(), SV_SendQueuedPackets(), Team_TouchEnemyFlag(), and yylex().
#define MAKE_CHUNKTYPE (a, b, c, d) (((a) << 24) | ((b) << 16) | ((c) << 8) | ((d)))
#define PNG_Adam7_NumPasses (7)
Referenced by DecodeImageInterlaced().
#define PNG_BitDepth_1 (1)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_BitDepth_16 (16)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_BitDepth_2 (2)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_BitDepth_4 (4)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_BitDepth_8 (8)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_Chunk_IHDR_Size (13)
Referenced by R_LoadPNG().
#define PNG_ChunkCRC_Size (4)
Referenced by DecompressIDATs(), FindChunk(), and R_LoadPNG().
#define PNG_ChunkHeader_Size (8)
Referenced by DecompressIDATs(), FindChunk(), and R_LoadPNG().
#define PNG_ChunkType_IDAT MAKE_CHUNKTYPE('I', 'D', 'A', 'T')
Referenced by DecompressIDATs().
#define PNG_ChunkType_IEND MAKE_CHUNKTYPE('I', 'E', 'N', 'D')
#define PNG_ChunkType_IHDR MAKE_CHUNKTYPE('I', 'H', 'D', 'R')
Referenced by R_LoadPNG().
#define PNG_ChunkType_PLTE MAKE_CHUNKTYPE('P', 'L', 'T', 'E')
Referenced by R_LoadPNG().
#define PNG_ChunkType_tRNS MAKE_CHUNKTYPE('t', 'R', 'N', 'S')
Referenced by R_LoadPNG().
#define PNG_ColourType_Grey (0)
Referenced by ConvertPixel(), DecodeImageInterlaced(), DecodeImageNonInterlaced(), and R_LoadPNG().
#define PNG_ColourType_GreyAlpha (4)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_ColourType_Indexed (3)
Referenced by ConvertPixel(), DecodeImageInterlaced(), DecodeImageNonInterlaced(), and R_LoadPNG().
#define PNG_ColourType_True (2)
Referenced by ConvertPixel(), DecodeImageInterlaced(), DecodeImageNonInterlaced(), and R_LoadPNG().
#define PNG_ColourType_TrueAlpha (6)
Referenced by ConvertPixel(), DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_CompressionMethod_0 (0)
Referenced by R_LoadPNG().
#define PNG_FilterMethod_0 (0)
Referenced by R_LoadPNG().
#define PNG_FilterType_Average (3)
Referenced by UnfilterImage().
#define PNG_FilterType_None (0)
Referenced by UnfilterImage().
#define PNG_FilterType_Paeth (4)
Referenced by UnfilterImage().
#define PNG_FilterType_Sub (1)
Referenced by UnfilterImage().
#define PNG_FilterType_Up (2)
Referenced by UnfilterImage().
#define PNG_InterlaceMethod_Interlaced (1)
Referenced by R_LoadPNG().
#define PNG_InterlaceMethod_NonInterlaced (0)
Referenced by R_LoadPNG().
#define PNG_NumColourComponents_Grey (1)
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_NumColourComponents_GreyAlpha (2)
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_NumColourComponents_Indexed (1)
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_NumColourComponents_True (3)
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_NumColourComponents_TrueAlpha (4)
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().
#define PNG_Signature "\x89\x50\x4E\x47\xD\xA\x1A\xA"
Referenced by R_LoadPNG().
#define PNG_Signature_Size (8)
Referenced by R_LoadPNG().
#define PNG_ZlibCheckValue_Size (4)
Referenced by DecompressIDATs().
#define PNG_ZlibHeader_Size (2)
Referenced by DecompressIDATs().
#define Q3IMAGE_BYTESPERPIXEL (4)
Referenced by ConvertPixel(), DecodeImageInterlaced(), DecodeImageNonInterlaced(), and R_LoadPNG().
Typedef Documentation
typedef uint32_t PNG_ChunkCRC
Function Documentation
static void* BufferedFileRead (struct BufferedFile * BF, unsigned Length) [static]
References BufferedFile::BytesLeft, NULL, and BufferedFile::Ptr.
Referenced by DecompressIDATs(), FindChunk(), and R_LoadPNG().
static qboolean BufferedFileRewind (struct BufferedFile * BF, unsigned Offset) [static]
References BufferedFile::Buffer, BufferedFile::BytesLeft, BufferedFile::Length, BufferedFile::Ptr, qfalse, and qtrue.
Referenced by DecompressIDATs(), FindChunk(), and R_LoadPNG().
static qboolean BufferedFileSkip (struct BufferedFile * BF, unsigned Offset) [static]
References BufferedFile::BytesLeft, BufferedFile::Ptr, qfalse, and qtrue.
Referenced by DecompressIDATs(), FindChunk(), and R_LoadPNG().
static void CloseBufferedFile (struct BufferedFile * BF) [static]
References BufferedFile::Buffer, refimport_t::Free, refimport_t::FS_FreeFile, and ri.
Referenced by R_LoadPNG().
static qboolean ConvertPixel (struct PNG_Chunk_IHDR * IHDR, byte * OutPtr, uint8_t * DecompPtr, qboolean HasTransparentColour, uint8_t * TransparentColour, uint8_t * OutPal) [static]
References PNG_Chunk_IHDR::BitDepth, PNG_Chunk_IHDR::ColourType, PNG_BitDepth_1, PNG_BitDepth_16, PNG_BitDepth_2, PNG_BitDepth_4, PNG_BitDepth_8, PNG_ColourType_Grey, PNG_ColourType_GreyAlpha, PNG_ColourType_Indexed, PNG_ColourType_True, PNG_ColourType_TrueAlpha, Q3IMAGE_BYTESPERPIXEL, qfalse, and qtrue.
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().
static qboolean DecodeImageInterlaced (struct PNG_Chunk_IHDR * IHDR, byte * OutBuffer, uint8_t * DecompressedData, uint32_t DecompressedDataLength, qboolean HasTransparentColour, uint8_t * TransparentColour, uint8_t * OutPal) [static]
References PNG_Chunk_IHDR::BitDepth, PNG_Chunk_IHDR::ColourType, ConvertPixel(), h, PNG_Chunk_IHDR::Height, PNG_Adam7_NumPasses, PNG_BitDepth_1, PNG_BitDepth_16, PNG_BitDepth_2, PNG_BitDepth_4, PNG_BitDepth_8, PNG_ColourType_Grey, PNG_ColourType_GreyAlpha, PNG_ColourType_Indexed, PNG_ColourType_True, PNG_ColourType_TrueAlpha, PNG_NumColourComponents_Grey, PNG_NumColourComponents_GreyAlpha, PNG_NumColourComponents_Indexed, PNG_NumColourComponents_True, PNG_NumColourComponents_TrueAlpha, Q3IMAGE_BYTESPERPIXEL, qfalse, qtrue, UnfilterImage(), and PNG_Chunk_IHDR::Width.
Referenced by R_LoadPNG().
static qboolean DecodeImageNonInterlaced (struct PNG_Chunk_IHDR * IHDR, byte * OutBuffer, uint8_t * DecompressedData, uint32_t DecompressedDataLength, qboolean HasTransparentColour, uint8_t * TransparentColour, uint8_t * OutPal) [static]
References PNG_Chunk_IHDR::BitDepth, PNG_Chunk_IHDR::ColourType, ConvertPixel(), h, PNG_Chunk_IHDR::Height, PNG_BitDepth_1, PNG_BitDepth_16, PNG_BitDepth_2, PNG_BitDepth_4, PNG_BitDepth_8, PNG_ColourType_Grey, PNG_ColourType_GreyAlpha, PNG_ColourType_Indexed, PNG_ColourType_True, PNG_ColourType_TrueAlpha, PNG_NumColourComponents_Grey, PNG_NumColourComponents_GreyAlpha, PNG_NumColourComponents_Indexed, PNG_NumColourComponents_True, PNG_NumColourComponents_TrueAlpha, Q3IMAGE_BYTESPERPIXEL, qfalse, qtrue, UnfilterImage(), and PNG_Chunk_IHDR::Width.
Referenced by R_LoadPNG().
static uint32_t DecompressIDATs (struct BufferedFile * BF, uint8_t ** Buffer) [static]
References BufferedFileRead(), BufferedFileRewind(), BufferedFileSkip(), FindChunk(), refimport_t::Free, PNG_ChunkHeader::Length, refimport_t::Malloc, NULL, PNG_ChunkCRC_Size, PNG_ChunkHeader_Size, PNG_ChunkType_IDAT, PNG_ZlibCheckValue_Size, PNG_ZlibHeader_Size, puff(), qtrue, ri, and PNG_ChunkHeader::Type.
Referenced by R_LoadPNG().
static qboolean FindChunk (struct BufferedFile * BF, uint32_t ChunkType) [static]
References BufferedFileRead(), BufferedFileRewind(), BufferedFileSkip(), PNG_ChunkHeader::Length, PNG_ChunkCRC_Size, PNG_ChunkHeader_Size, qfalse, qtrue, and PNG_ChunkHeader::Type.
Referenced by DecompressIDATs(), and R_LoadPNG().
static uint8_t PredictPaeth (uint8_t a, uint8_t b, uint8_t c) [static]
References abs(), b, int(), and pc.
Referenced by UnfilterImage().
void R_LoadPNG (const char * name, byte ** pic, int * width, int * height)
References BufferedFileRead(), BufferedFileRewind(), BufferedFileSkip(), CloseBufferedFile(), PNG_Chunk_IHDR::ColourType, PNG_Chunk_IHDR::CompressionMethod, DecodeImageInterlaced(), DecodeImageNonInterlaced(), DecompressIDATs(), PNG_Chunk_IHDR::FilterMethod, FindChunk(), refimport_t::Free, PNG_Chunk_IHDR::Height, INT_MAX, PNG_Chunk_IHDR::InterlaceMethod, PNG_ChunkHeader::Length, refimport_t::Malloc, NULL, PNG_Chunk_IHDR_Size, PNG_ChunkCRC_Size, PNG_ChunkHeader_Size, PNG_ChunkType_IHDR, PNG_ChunkType_PLTE, PNG_ChunkType_tRNS, PNG_ColourType_Grey, PNG_ColourType_Indexed, PNG_ColourType_True, PNG_CompressionMethod_0, PNG_FilterMethod_0, PNG_InterlaceMethod_Interlaced, PNG_InterlaceMethod_NonInterlaced, PNG_Signature, PNG_Signature_Size, PRINT_WARNING, Q3IMAGE_BYTESPERPIXEL, qfalse, qtrue, ReadBufferedFile(), ri, PNG_ChunkHeader::Type, and PNG_Chunk_IHDR::Width.
static struct BufferedFile* ReadBufferedFile (const char * name) [static, read]
References b, BF, buffer, BufferedFile::Buffer, BufferedFile::BytesLeft, refimport_t::Free, refimport_t::FS_ReadFile, BufferedFile::Length, refimport_t::Malloc, NULL, BufferedFile::Ptr, and ri.
Referenced by R_LoadPNG().
static qboolean UnfilterImage (uint8_t * DecompressedData, uint32_t ImageHeight, uint32_t BytesPerScanline, uint32_t BytesPerPixel) [static]
References h, PNG_FilterType_Average, PNG_FilterType_None, PNG_FilterType_Paeth, PNG_FilterType_Sub, PNG_FilterType_Up, PredictPaeth(), qfalse, and qtrue.
Referenced by DecodeImageInterlaced(), and DecodeImageNonInterlaced().