ioquake3: code/renderer/tr_flares.c File Reference
tr_flares.c File Reference
#include "tr_local.h"
Data Structures
struct flare_s
Defines
#define MAX_FLARES 128
Typedefs
typedef struct flare_s flare_t
Functions
void R_ClearFlares (void)
void RB_AddFlare (void *surface, int fogNum, vec3_t point, vec3_t color, vec3_t normal)
void RB_AddDlightFlares (void)
void RB_TestFlare (flare_t *f)
void RB_RenderFlare (flare_t *f)
void RB_RenderFlares (void)
Variables
flare_t r_flareStructs [MAX_FLARES]
flare_t * r_activeFlares
flare_t * r_inactiveFlares
int flareCoeff
Define Documentation
#define MAX_FLARES 128
Referenced by R_ClearFlares().
Typedef Documentation
typedef struct flare_s flare_t
Function Documentation
void R_ClearFlares (void)
References Com_Memset, MAX_FLARES, flare_s::next, NULL, and r_inactiveFlares.
Referenced by RE_BeginRegistration().
void RB_AddDlightFlares (void)
References backEnd, fog_t::bounds, trRefdef_t::dlights, world_t::fogs, cvar_s::integer, NULL, trRefdef_t::num_dlights, world_t::numfogs, dlight_s::origin, r_flares, RB_AddFlare(), backEndState_t::refdef, tr, and trGlobals_t::world.
void RB_AddFlare (void * surface, int fogNum, vec3_t point, vec3_t color, vec3_t normal)
References flare_s::addedFrame, backEnd, backEndCounters_t::c_flareAdds, flare_s::color, DotProduct, flare_s::eyeZ, flare_s::fadeTime, flare_s::fogNum, viewParms_t::frameCount, flare_s::frameSceneNum, viewParms_t::frameSceneNum, flare_s::inPortal, viewParms_t::isPortal, local, orientationr_t::modelMatrix, flare_s::next, viewParms_t::or, backEndState_t::or, flare_s::origin, orientationr_t::origin, backEndState_t::pc, viewParms_t::projectionMatrix, qfalse, r_activeFlares, r_inactiveFlares, R_TransformClipToWindow(), R_TransformModelToClip(), backEndState_t::refdef, flare_s::surface, trRefdef_t::time, VectorCopy, VectorNormalizeFast(), VectorScale, VectorSubtract, backEndState_t::viewParms, viewParms_t::viewportHeight, viewParms_t::viewportWidth, viewParms_t::viewportX, viewParms_t::viewportY, flare_s::visible, flare_s::windowX, and flare_s::windowY.
Referenced by RB_AddDlightFlares(), and RB_SurfaceFlare().
void RB_RenderFlare (flare_t * f)
References backEnd, backEndCounters_t::c_flareRenders, flare_s::color, flare_s::drawIntensity, flare_s::eyeZ, flareCoeff, trGlobals_t::flareShader, flare_s::fogNum, shaderCommands_s::fogNum, world_t::numfogs, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, flare_s::origin, backEndState_t::pc, r_flareSize, RB_BeginSurface(), RB_CalcModulateColorsByFog(), RB_EndSurface(), tess, tr, cvar_s::value, VectorCopy, VectorScale, backEndState_t::viewParms, viewParms_t::viewportWidth, flare_s::windowX, flare_s::windowY, and trGlobals_t::world.
Referenced by RB_RenderFlares().
void RB_RenderFlares (void)
References flare_s::addedFrame, backEnd, backEndState_t::currentEntity, flare_s::drawIntensity, FLARE_STDCOEFF, flareCoeff, viewParms_t::frameCount, flare_s::frameSceneNum, viewParms_t::frameSceneNum, flare_s::inPortal, cvar_s::integer, viewParms_t::isPortal, cvar_s::modified, flare_s::next, NULL, backEndState_t::or, qfalse, qglDisable, qglLoadIdentity, qglMatrixMode, qglOrtho, qglPopMatrix, qglPushMatrix, qtrue, r_activeFlares, r_flareCoeff, r_flares, r_inactiveFlares, RB_RenderFlare(), RB_TestFlare(), tr, cvar_s::value, backEndState_t::viewParms, viewParms_t::viewportHeight, viewParms_t::viewportWidth, viewParms_t::viewportX, viewParms_t::viewportY, viewParms_t::world, and trGlobals_t::worldEntity.
Referenced by RB_RenderDrawSurfList().
void RB_TestFlare (flare_t * f)
References backEnd, backEndCounters_t::c_flareTests, depth, flare_s::drawIntensity, flare_s::eyeZ, flare_s::fadeTime, glstate_t::finishCalled, glState, backEndState_t::pc, viewParms_t::projectionMatrix, qfalse, qglReadPixels, qtrue, r_flareFade, backEndState_t::refdef, trRefdef_t::time, cvar_s::value, backEndState_t::viewParms, flare_s::visible, flare_s::windowX, and flare_s::windowY.
Referenced by RB_RenderFlares().
Variable Documentation
int flareCoeff
Referenced by RB_RenderFlare(), and RB_RenderFlares().
flare_t* r_activeFlares
Referenced by RB_AddFlare(), and RB_RenderFlares().
flare_t r_flareStructs[MAX_FLARES]
flare_t * r_inactiveFlares
Referenced by R_ClearFlares(), RB_AddFlare(), and RB_RenderFlares().