ioquake3: code/renderer/tr_shade.c File Reference
tr_shade.c File Reference
#include "tr_local.h"
Functions
static void APIENTRY R_ArrayElementDiscrete (GLint index)
static void R_DrawStripElements (int numIndexes, const glIndex_t *indexes, void(APIENTRY *element)(GLint))
static void R_DrawElements (int numIndexes, const glIndex_t *indexes)
static void R_BindAnimatedImage (textureBundle_t *bundle)
static void DrawTris (shaderCommands_t *input)
static void DrawNormals (shaderCommands_t *input)
void RB_BeginSurface (shader_t *shader, int fogNum)
static void DrawMultitextured (shaderCommands_t *input, int stage)
static void ProjectDlightTexture_scalar (void)
static void ProjectDlightTexture (void)
static void RB_FogPass (void)
static void ComputeColors (shaderStage_t *pStage)
static void ComputeTexCoords (shaderStage_t *pStage)
static void RB_IterateStagesGeneric (shaderCommands_t *input)
void RB_StageIteratorGeneric (void)
void RB_StageIteratorVertexLitTexture (void)
void RB_StageIteratorLightmappedMultitexture (void)
void RB_EndSurface (void)
Variables
static int c_vertexes
static int c_begins
shaderCommands_t tess
static qboolean setArraysOnce
Function Documentation
static void ComputeColors (shaderStage_t * pStage) [static]
References ACFF_MODULATE_ALPHA, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, ACFF_NONE, shaderStage_t::adjustColorsForFog, AGEN_CONST, AGEN_ENTITY, AGEN_IDENTITY, AGEN_LIGHTING_SPECULAR, AGEN_ONE_MINUS_ENTITY, AGEN_ONE_MINUS_VERTEX, AGEN_PORTAL, AGEN_SKIP, AGEN_VERTEX, AGEN_WAVEFORM, shaderStage_t::alphaGen, shaderStage_t::alphaWave, backEnd, CGEN_CONST, CGEN_ENTITY, CGEN_EXACT_VERTEX, CGEN_FOG, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_ONE_MINUS_ENTITY, CGEN_ONE_MINUS_VERTEX, CGEN_VERTEX, CGEN_WAVEFORM, fog_t::colorInt, Com_Memcpy, Com_Memset, shaderStage_t::constantColor, shaderCommands_s::fogNum, world_t::fogs, trGlobals_t::identityLight, trGlobals_t::identityLightByte, cvar_s::integer, LERP, LUMA, shaderCommands_s::numVertexes, viewParms_t::or, orientationr_t::origin, shader_s::portalRange, r_greyscale, RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDiffuseColor(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_CalcSpecularAlpha(), RB_CalcWaveAlpha(), RB_CalcWaveColor(), shaderStage_t::rgbGen, shaderStage_t::rgbWave, shaderCommands_s::shader, tr, cvar_s::value, VectorLength(), VectorSubtract, backEndState_t::viewParms, and trGlobals_t::world.
Referenced by RB_IterateStagesGeneric().
static void ComputeTexCoords (shaderStage_t * pStage) [static]
References b, backEnd, shaderStage_t::bundle, Com_Memset, backEndState_t::currentEntity, DotProduct, trRefEntity_t::e, ERR_DROP, shader_s::name, NUM_TEXTURE_BUNDLES, textureBundle_t::numTexMods, shaderCommands_s::numVertexes, RB_CalcEnvironmentTexCoords(), RB_CalcFogTexCoords(), RB_CalcRotateTexCoords(), RB_CalcScaleTexCoords(), RB_CalcScrollTexCoords(), RB_CalcStretchTexCoords(), RB_CalcTransformTexCoords(), RB_CalcTurbulentTexCoords(), ri, texModInfo_t::rotateSpeed, texModInfo_t::scale, texModInfo_t::scroll, shaderCommands_s::shader, refEntity_t::shaderTexCoord, textureBundle_t::tcGen, TCGEN_BAD, TCGEN_ENVIRONMENT_MAPPED, TCGEN_FOG, TCGEN_IDENTITY, TCGEN_LIGHTMAP, TCGEN_TEXTURE, TCGEN_VECTOR, textureBundle_t::tcGenVectors, textureBundle_t::texMods, TMOD_ENTITY_TRANSLATE, TMOD_NONE, TMOD_ROTATE, TMOD_SCALE, TMOD_SCROLL, TMOD_STRETCH, TMOD_TRANSFORM, TMOD_TURBULENT, TR_MAX_TEXMODS, texModInfo_t::type, and texModInfo_t::wave.
Referenced by RB_IterateStagesGeneric().
static void DrawMultitextured (shaderCommands_t * input, int stage) [static]
References backEnd, shaderStage_t::bundle, GL_SelectTexture(), GL_State(), GL_TexEnv(), cvar_s::integer, viewParms_t::isPortal, shader_s::multitextureEnv, shaderCommands_s::numIndexes, qglDisable, qglEnable, qglEnableClientState, qglPolygonMode, qglTexCoordPointer, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, shaderCommands_s::shader, shaderStage_t::stateBits, backEndState_t::viewParms, and shaderCommands_s::xstages.
Referenced by RB_IterateStagesGeneric().
static void DrawNormals (shaderCommands_t * input) [static]
References GL_Bind(), GL_State(), GLS_DEPTHMASK_TRUE, GLS_POLYMODE_LINE, shaderCommands_s::numVertexes, qglBegin, qglColor3f, qglDepthRange, qglEnd, qglVertex3fv, tr, VectorMA(), and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
static void DrawTris (shaderCommands_t * input) [static]
References GL_Bind(), GL_State(), GLimp_LogComment(), GLS_DEPTHMASK_TRUE, GLS_POLYMODE_LINE, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, qglColor3f, qglDepthRange, qglDisableClientState, qglLockArraysEXT, qglUnlockArraysEXT, qglVertexPointer, R_DrawElements(), tr, and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
static void ProjectDlightTexture (void) [static]
References com_altivec, cvar_s::integer, and ProjectDlightTexture_scalar().
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void ProjectDlightTexture_scalar (void) [static]
References dlight_s::additive, b, backEnd, backEndCounters_t::c_dlightIndexes, backEndCounters_t::c_dlightVertexes, backEndCounters_t::c_totalIndexes, dlight_s::color, shaderCommands_s::dlightBits, trGlobals_t::dlightImage, trRefdef_t::dlights, refimport_t::ftol, GL_Bind(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, cvar_s::integer, LERP, LUMA, trRefdef_t::num_dlights, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, backEndState_t::pc, Q_fabs(), qglColorPointer, qglEnableClientState, qglTexCoordPointer, r_dlightBacks, R_DrawElements(), r_greyscale, dlight_s::radius, backEndState_t::refdef, ri, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, tr, dlight_s::transformed, cvar_s::value, VectorCopy, and VectorSubtract.
Referenced by ProjectDlightTexture().
static void APIENTRY R_ArrayElementDiscrete (GLint index) [static]
References glstate_t::currenttmu, glState, qglColor4ubv, qglMultiTexCoord2fARB, qglTexCoord2fv, qglVertex3fv, and tess.
Referenced by R_DrawElements().
static void R_BindAnimatedImage (textureBundle_t * bundle) [static]
References refimport_t::CIN_RunCinematic, refimport_t::CIN_UploadCinematic, refimport_t::ftol, FUNCTABLE_SIZE, FUNCTABLE_SIZE2, GL_Bind(), textureBundle_t::image, textureBundle_t::imageAnimationSpeed, textureBundle_t::isVideoMap, textureBundle_t::numImageAnimations, ri, shaderCommands_s::shaderTime, and textureBundle_t::videoMapHandle.
Referenced by DrawMultitextured(), RB_IterateStagesGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void R_DrawElements (int numIndexes, const glIndex_t * indexes) [static]
References GL_INDEX_TYPE, cvar_s::integer, qglArrayElement, qglDrawElements, qglLockArraysEXT, R_ArrayElementDiscrete(), R_DrawStripElements(), and r_primitives.
Referenced by DrawMultitextured(), DrawTris(), ProjectDlightTexture_scalar(), RB_FogPass(), RB_IterateStagesGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void R_DrawStripElements (int numIndexes, const glIndex_t * indexes, void(APIENTRY *element)(GLint)) [static]
References c_begins, c_vertexes, shaderCommands_s::numVertexes, qfalse, qglBegin, qglEnd, qtrue, and tess.
Referenced by R_DrawElements().
void RB_BeginSurface (shader_t * shader, int fogNum)
References backEnd, shader_s::clampTime, shaderCommands_s::currentStageIteratorFunc, shaderCommands_s::dlightBits, trRefdef_t::floatTime, shaderCommands_s::fogNum, if(), shaderCommands_s::numIndexes, shaderCommands_s::numPasses, shader_s::numUnfoggedPasses, shaderCommands_s::numVertexes, shader_s::optimalStageIteratorFunc, backEndState_t::refdef, shader_s::remappedShader, shaderCommands_s::shader, shaderCommands_s::shaderTime, shader_s::stages, shader_s::timeOffset, and shaderCommands_s::xstages.
Referenced by RB_CheckOverflow(), RB_DrawSun(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), and SurfIsOffscreen().
void RB_EndSurface (void)
References backEnd, backEndCounters_t::c_indexes, backEndCounters_t::c_shaders, backEndCounters_t::c_totalIndexes, backEndCounters_t::c_vertexes, shaderCommands_s::currentStageIteratorFunc, DrawNormals(), DrawTris(), ERR_DROP, GLimp_LogComment(), cvar_s::integer, shaderCommands_s::numIndexes, shaderCommands_s::numPasses, shaderCommands_s::numVertexes, backEndState_t::pc, r_debugSort, r_shownormals, r_showtris, RB_ShadowTessEnd(), ri, shaderCommands_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, trGlobals_t::shadowShader, shader_s::sort, tess, and tr.
Referenced by RB_CheckOverflow(), RB_ClearDepth(), RB_DrawSun(), RB_DrawSurfs(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), and RB_SwapBuffers().
static void RB_FogPass (void) [static]
References fog_t::colorInt, trGlobals_t::fogImage, shaderCommands_s::fogNum, shader_s::fogPass, world_t::fogs, FP_EQUAL, GL_Bind(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, qglColorPointer, qglEnableClientState, qglTexCoordPointer, R_DrawElements(), RB_CalcFogTexCoords(), shaderCommands_s::shader, tr, and trGlobals_t::world.
Referenced by RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
static void RB_IterateStagesGeneric (shaderCommands_t * input) [static]
References shaderStage_t::bundle, ComputeColors(), ComputeTexCoords(), DrawMultitextured(), GL_Bind(), GL_State(), glConfig, GLHW_PERMEDIA2, glconfig_t::hardwareType, textureBundle_t::image, cvar_s::integer, textureBundle_t::isLightmap, MAX_SHADER_STAGES, shaderCommands_s::numIndexes, qglColorPointer, qglEnableClientState, qglTexCoordPointer, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, r_uiFullScreen, r_vertexLight, shaderStage_t::stateBits, tr, textureBundle_t::vertexLightmap, trGlobals_t::whiteImage, and shaderCommands_s::xstages.
Referenced by RB_StageIteratorGeneric().
void RB_StageIteratorGeneric (void)
References shader_s::cullType, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, shader_s::fogPass, GL_Cull(), GLimp_LogComment(), cvar_s::integer, shader_s::multitextureEnv, shader_s::name, shaderCommands_s::numPasses, shaderCommands_s::numVertexes, shader_s::polygonOffset, ProjectDlightTexture(), qfalse, qglColorPointer, qglDisable, qglDisableClientState, qglEnable, qglEnableClientState, qglLockArraysEXT, qglPolygonOffset, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, qtrue, r_logFile, r_offsetFactor, r_offsetUnits, RB_DeformTessGeometry(), RB_FogPass(), RB_IterateStagesGeneric(), shader, shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, SURF_NODLIGHT, SURF_SKY, shader_s::surfaceFlags, tess, va(), and cvar_s::value.
Referenced by ComputeStageIteratorFunc(), R_ShaderList_f(), and RB_StageIteratorSky().
void RB_StageIteratorLightmappedMultitexture (void)
References shaderStage_t::bundle, shader_s::cullType, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, shader_s::fogPass, GL_Cull(), GL_SelectTexture(), GL_State(), GL_TexEnv(), GLimp_LogComment(), GLS_DEFAULT, cvar_s::integer, shader_s::name, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, ProjectDlightTexture(), qglColor3f, qglColorPointer, qglDisable, qglDisableClientState, qglEnable, qglEnableClientState, qglLockArraysEXT, qglShadeModel, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, r_logFile, RB_FogPass(), shader, shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, tess, va(), and shaderCommands_s::xstages.
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
void RB_StageIteratorVertexLitTexture (void)
References shaderStage_t::bundle, shader_s::cullType, shaderCommands_s::dlightBits, shaderCommands_s::fogNum, shader_s::fogPass, GL_Cull(), GL_State(), GLimp_LogComment(), cvar_s::integer, shader_s::name, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, ProjectDlightTexture(), qglColorPointer, qglEnableClientState, qglLockArraysEXT, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, R_BindAnimatedImage(), R_DrawElements(), r_logFile, RB_CalcDiffuseColor(), RB_FogPass(), shader, shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, shaderStage_t::stateBits, tess, va(), and shaderCommands_s::xstages.
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
Variable Documentation
int c_begins [static]
Referenced by R_DrawStripElements().
int c_vertexes [static]
Referenced by R_DrawStripElements().
qboolean setArraysOnce [static]
shaderCommands_t tess
Referenced by Autosprite2Deform(), AutospriteDeform(), DeformText(), DoRailCore(), DoRailDiscs(), FillCloudySkySide(), LerpMeshVertexes_scalar(), R_ArrayElementDiscrete(), R_BuildCloudData(), R_DrawStripElements(), R_Init(), R_RenderShadowEdges(), RB_AddQuadStampExt(), RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcBulgeVertexes(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDeformNormals(), RB_CalcDeformVertexes(), RB_CalcDiffuseColor_scalar(), RB_CalcEnvironmentTexCoords(), RB_CalcFogTexCoords(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_CalcMoveVertexes(), RB_CalcRotateTexCoords(), RB_CalcScaleTexCoords(), RB_CalcScrollTexCoords(), RB_CalcSpecularAlpha(), RB_CalcTransformTexCoords(), RB_CalcTurbulentTexCoords(), RB_CalcWaveAlpha(), RB_CalcWaveColor(), RB_CheckOverflow(), RB_ClearDepth(), RB_DeformTessGeometry(), RB_DrawSun(), RB_DrawSurfs(), RB_EndSurface(), RB_IQMSurfaceAnim(), RB_ProjectionShadowDeform(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_ShadowTessEnd(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), RB_StretchPic(), RB_SurfaceAnim(), RB_SurfaceFace(), RB_SurfaceFlare(), RB_SurfaceGrid(), RB_SurfaceMesh(), RB_SurfacePolychain(), RB_SurfaceTriangles(), RB_SwapBuffers(), SurfIsOffscreen(), and TableForFunc().