ioquake3: code/renderer/tr_shader.c File Reference
tr_shader.c File Reference
#include "tr_local.h"
Data Structures
struct infoParm_t
struct collapse_t
Defines
#define FILE_HASH_SIZE 1024
#define MAX_SHADERTEXT_HASH 2048
#define MAX_SHADER_FILES 4096
Functions
static long generateHashValue (const char *fname, const int size)
void R_RemapShader (const char *shaderName, const char *newShaderName, const char *timeOffset)
static qboolean ParseVector (char **text, int count, float *v)
static unsigned NameToAFunc (const char *funcname)
static int NameToSrcBlendMode (const char *name)
static int NameToDstBlendMode (const char *name)
static genFunc_t NameToGenFunc (const char *funcname)
static void ParseWaveForm (char **text, waveForm_t *wave)
static void ParseTexMod (char *_text, shaderStage_t *stage)
static qboolean ParseStage (shaderStage_t *stage, char **text)
static void ParseDeform (char **text)
static void ParseSkyParms (char **text)
void ParseSort (char **text)
static void ParseSurfaceParm (char **text)
static qboolean ParseShader (char **text)
static void ComputeStageIteratorFunc (void)
static qboolean CollapseMultitexture (void)
static void FixRenderCommandList (int newShader)
static void SortNewShader (void)
static shader_t * GeneratePermanentShader (void)
static void VertexLightingCollapse (void)
static shader_t * FinishShader (void)
static char * FindShaderInShaderText (const char *shadername)
shader_t * R_FindShaderByName (const char *name)
shader_t * R_FindShader (const char *name, int lightmapIndex, qboolean mipRawImage)
qhandle_t RE_RegisterShaderFromImage (const char *name, int lightmapIndex, image_t *image, qboolean mipRawImage)
qhandle_t RE_RegisterShaderLightMap (const char *name, int lightmapIndex)
qhandle_t RE_RegisterShader (const char *name)
qhandle_t RE_RegisterShaderNoMip (const char *name)
shader_t * R_GetShaderByHandle (qhandle_t hShader)
void R_ShaderList_f (void)
static void ScanAndLoadShaderFiles (void)
static void CreateInternalShaders (void)
static void CreateExternalShaders (void)
void R_InitShaders (void)
Variables
static char * s_shaderText
static shaderStage_t stages [MAX_SHADER_STAGES]
static shader_t shader
static texModInfo_t texMods [MAX_SHADER_STAGES][TR_MAX_TEXMODS]
static shader_t * hashTable [FILE_HASH_SIZE]
static char ** shaderTextHashTable [MAX_SHADERTEXT_HASH]
infoParm_t infoParms []
static collapse_t collapse []
Define Documentation
#define FILE_HASH_SIZE 1024
Referenced by GeneratePermanentShader(), R_FindShader(), R_FindShaderByName(), R_RemapShader(), and RE_RegisterShaderFromImage().
#define MAX_SHADER_FILES 4096
Referenced by ScanAndLoadShaderFiles().
#define MAX_SHADERTEXT_HASH 2048
Referenced by FindShaderInShaderText(), and ScanAndLoadShaderFiles().
Function Documentation
static qboolean CollapseMultitexture (void) [static]
References AGEN_WAVEFORM, shaderStage_t::alphaGen, collapse_t::blendA, shaderStage_t::bundle, CGEN_IDENTITY, CGEN_WAVEFORM, Com_Memset, glconfig_t::driverType, glConfig, GLDRV_VOODOO, GLS_DEPTHMASK_TRUE, GLS_DSTBLEND_BITS, GLS_SRCBLEND_BITS, MAX_SHADER_STAGES, memmove(), collapse_t::multitextureBlend, shader_s::multitextureEnv, collapse_t::multitextureEnv, qfalse, qglActiveTextureARB, qtrue, shaderStage_t::stateBits, and glconfig_t::textureEnvAddAvailable.
Referenced by FinishShader().
static void ComputeStageIteratorFunc (void) [static]
References AGEN_IDENTITY, CGEN_IDENTITY, CGEN_LIGHTING_DIFFUSE, cvar_s::integer, shader_s::isSky, shader_s::multitextureEnv, shader_s::numDeforms, shader_s::numUnfoggedPasses, shader_s::optimalStageIteratorFunc, shader_s::polygonOffset, r_ignoreFastPath, RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), TCGEN_LIGHTMAP, and TCGEN_TEXTURE.
Referenced by FinishShader().
static void CreateExternalShaders (void) [static]
References ACFF_NONE, shaderStage_t::adjustColorsForFog, shader_s::defaultShader, trGlobals_t::flareShader, GLS_DEPTHTEST_DISABLE, LIGHTMAP_NONE, shader_s::numUnfoggedPasses, trGlobals_t::projectionShadowShader, qtrue, R_FindShader(), shader_s::stages, shaderStage_t::stateBits, trGlobals_t::sunShader, and tr.
Referenced by R_InitShaders().
static void CreateInternalShaders (void) [static]
References shaderStage_t::active, shaderStage_t::bundle, Com_Memset, trGlobals_t::defaultImage, trGlobals_t::defaultShader, FinishShader(), GLS_DEFAULT, textureBundle_t::image, LIGHTMAP_NONE, shader_s::lightmapIndex, shader_s::name, trGlobals_t::numShaders, Q_strncpyz(), qtrue, trGlobals_t::shadowShader, shader_s::sort, SS_STENCIL_SHADOW, shaderStage_t::stateBits, and tr.
Referenced by R_InitShaders().
static char* FindShaderInShaderText (const char * shadername) [static]
References COM_ParseExt(), generateHashValue(), hash(), MAX_SHADERTEXT_HASH, NULL, Q_stricmp(), qtrue, s_shaderText, shaderTextHashTable, SkipBracedSection(), and token.
Referenced by R_FindShader().
static shader_t* FinishShader (void) [static]
References ACFF_MODULATE_ALPHA, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, shaderStage_t::active, shaderStage_t::adjustColorsForFog, shaderStage_t::bundle, CollapseMultitexture(), Com_Memset, ComputeStageIteratorFunc(), GeneratePermanentShader(), glConfig, GLHW_PERMEDIA2, GLS_DEPTHMASK_TRUE, GLS_DSTBLEND_BITS, GLS_DSTBLEND_ONE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ONE_MINUS_SRC_COLOR, GLS_SRCBLEND_BITS, GLS_SRCBLEND_ONE, GLS_SRCBLEND_SRC_ALPHA, GLS_SRCBLEND_ZERO, glconfig_t::hardwareType, textureBundle_t::image, cvar_s::integer, shaderStage_t::isDetail, textureBundle_t::isLightmap, shader_s::isSky, LIGHTMAP_NONE, shader_s::lightmapIndex, MAX_SHADER_STAGES, memmove(), shader_s::name, shader_s::numUnfoggedPasses, shader_s::polygonOffset, PRINT_DEVELOPER, PRINT_WARNING, qfalse, qtrue, r_detailTextures, r_uiFullScreen, r_vertexLight, ri, shader_s::sort, SS_BLEND0, SS_DECAL, SS_ENVIRONMENT, SS_FOG, SS_OPAQUE, SS_SEE_THROUGH, shaderStage_t::stateBits, textureBundle_t::tcGen, TCGEN_BAD, TCGEN_LIGHTMAP, TCGEN_TEXTURE, and VertexLightingCollapse().
Referenced by CreateInternalShaders(), R_FindShader(), and RE_RegisterShaderFromImage().
static void FixRenderCommandList (int newShader) [static]
References backEndData, renderCommandList_t::cmds, backEndData_t::commands, drawSurfsCommand_t::drawSurfs, int(), MAX_SHADERS, PADP, QSORT_FOGNUM_SHIFT, QSORT_SHADERNUM_SHIFT, R_DecomposeSort(), RC_DRAW_BUFFER, RC_DRAW_SURFS, RC_END_OF_LIST, RC_SET_COLOR, RC_STRETCH_PIC, RC_SWAP_BUFFERS, shader, trGlobals_t::smpFrame, drawSurf_s::sort, and tr.
Referenced by SortNewShader().
static long generateHashValue (const char * fname, const int size) [static]
References hash(), and long().
Referenced by FindShaderInShaderText(), GeneratePermanentShader(), R_FindShader(), R_FindShaderByName(), R_RemapShader(), RE_RegisterShaderFromImage(), and ScanAndLoadShaderFiles().
static shader_t* GeneratePermanentShader (void) [static]
References b, shaderStage_t::bundle, Com_Memcpy, shader_s::contentFlags, CONTENTS_FOG, trGlobals_t::defaultShader, FILE_HASH_SIZE, shader_s::fogPass, FP_EQUAL, FP_LE, generateHashValue(), h_low, hash(), refimport_t::Hunk_Alloc, shader_s::index, MAX_SHADERS, shader_s::name, shader_s::next, NUM_TEXTURE_BUNDLES, trGlobals_t::numShaders, textureBundle_t::numTexMods, shader_s::numUnfoggedPasses, PRINT_WARNING, ri, shader, trGlobals_t::shaders, shader_s::sort, shader_s::sortedIndex, trGlobals_t::sortedShaders, SortNewShader(), SS_OPAQUE, shader_s::stages, textureBundle_t::texMods, and tr.
Referenced by FinishShader().
static unsigned NameToAFunc (const char * funcname) [static]
References GLS_ATEST_GE_80, GLS_ATEST_GT_0, GLS_ATEST_LT_80, shader_s::name, PRINT_WARNING, Q_stricmp(), and ri.
Referenced by ParseStage().
static int NameToDstBlendMode (const char * name) [static]
References GLS_DSTBLEND_DST_ALPHA, GLS_DSTBLEND_ONE, GLS_DSTBLEND_ONE_MINUS_DST_ALPHA, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ONE_MINUS_SRC_COLOR, GLS_DSTBLEND_SRC_ALPHA, GLS_DSTBLEND_SRC_COLOR, GLS_DSTBLEND_ZERO, shader_s::name, PRINT_WARNING, Q_stricmp(), and ri.
Referenced by ParseStage().
static genFunc_t NameToGenFunc (const char * funcname) [static]
References GF_INVERSE_SAWTOOTH, GF_NOISE, GF_SAWTOOTH, GF_SIN, GF_SQUARE, GF_TRIANGLE, shader_s::name, PRINT_WARNING, Q_stricmp(), and ri.
Referenced by ParseTexMod(), and ParseWaveForm().
static int NameToSrcBlendMode (const char * name) [static]
References GLS_SRCBLEND_ALPHA_SATURATE, GLS_SRCBLEND_DST_ALPHA, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, GLS_SRCBLEND_ONE_MINUS_DST_ALPHA, GLS_SRCBLEND_ONE_MINUS_DST_COLOR, GLS_SRCBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, GLS_SRCBLEND_ZERO, shader_s::name, PRINT_WARNING, Q_stricmp(), and ri.
Referenced by ParseStage().
static void ParseDeform (char ** text) [static]
References waveForm_t::amplitude, deformStage_t::bulgeHeight, deformStage_t::bulgeSpeed, deformStage_t::bulgeWidth, COM_ParseExt(), DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2, DEFORM_BULGE, DEFORM_MOVE, DEFORM_NORMALS, DEFORM_PROJECTION_SHADOW, DEFORM_TEXT0, DEFORM_WAVE, deformStage_t::deformation, deformStage_t::deformationSpread, deformStage_t::deformationWave, shader_s::deforms, waveForm_t::frequency, MAX_SHADER_DEFORMS, deformStage_t::moveVector, n, shader_s::name, shader_s::numDeforms, ParseWaveForm(), PRINT_WARNING, Q_stricmp(), Q_stricmpn(), qfalse, ri, and token.
Referenced by ParseShader().
static qboolean ParseShader (char ** text) [static]
References shaderStage_t::active, b, shader_s::clampTime, fogParms_t::color, COM_ParseExt(), shader_s::contentFlags, CONTENTS_FOG, CT_BACK_SIDED, CT_TWO_SIDED, shader_s::cullType, fogParms_t::depthForOpaque, shader_s::entityMergable, shader_s::explicitlyDefined, shader_s::fogParms, shader_s::isSky, M_PI, MAX_SHADER_STAGES, shader_s::name, shader_s::noMipMaps, shader_s::noPicMip, ParseDeform(), ParseSkyParms(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseVector(), shader_s::polygonOffset, PRINT_WARNING, Q_stricmp(), Q_stricmpn(), qfalse, qtrue, ri, s, SkipRestOfLine(), shader_s::sort, SS_PORTAL, trGlobals_t::sunDirection, trGlobals_t::sunLight, token, tr, VectorNormalize(), and VectorScale.
Referenced by R_FindShader().
static void ParseSkyParms (char ** text) [static]
References skyParms_t::cloudHeight, COM_ParseExt(), Com_sprintf(), trGlobals_t::defaultImage, skyParms_t::innerbox, shader_s::isSky, MAX_QPATH, shader_s::name, skyParms_t::outerbox, PRINT_WARNING, qfalse, qtrue, R_FindImageFile(), R_InitSkyTexCoords(), ri, shader_s::sky, token, and tr.
Referenced by ParseShader().
void ParseSort (char ** text)
References COM_ParseExt(), shader_s::name, PRINT_WARNING, Q_stricmp(), qfalse, ri, shader_s::sort, SS_BANNER, SS_BLEND1, SS_DECAL, SS_ENVIRONMENT, SS_NEAREST, SS_OPAQUE, SS_PORTAL, SS_SEE_THROUGH, SS_UNDERWATER, and token.
Referenced by ParseShader().
static qboolean ParseStage (shaderStage_t * stage, char ** text) [static]
References shaderStage_t::active, AGEN_CONST, AGEN_ENTITY, AGEN_IDENTITY, AGEN_LIGHTING_SPECULAR, AGEN_ONE_MINUS_ENTITY, AGEN_ONE_MINUS_VERTEX, AGEN_PORTAL, AGEN_SKIP, AGEN_VERTEX, AGEN_WAVEFORM, shaderStage_t::alphaGen, shaderStage_t::alphaWave, buffer, shaderStage_t::bundle, CGEN_BAD, CGEN_CONST, CGEN_ENTITY, CGEN_EXACT_VERTEX, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_ONE_MINUS_ENTITY, CGEN_ONE_MINUS_VERTEX, CGEN_VERTEX, CGEN_WAVEFORM, CIN_loop, refimport_t::CIN_PlayCinematic, CIN_shader, CIN_silent, COM_ParseExt(), shaderStage_t::constantColor, GLS_DEPTHFUNC_EQUAL, GLS_DEPTHMASK_TRUE, GLS_DSTBLEND_ONE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, GLS_SRCBLEND_SRC_ALPHA, textureBundle_t::image, textureBundle_t::imageAnimationSpeed, shaderStage_t::isDetail, textureBundle_t::isLightmap, textureBundle_t::isVideoMap, shader_s::lightmapIndex, trGlobals_t::lightmaps, MAX_IMAGE_ANIMATIONS, shader_s::name, NameToAFunc(), NameToDstBlendMode(), NameToSrcBlendMode(), shader_s::noMipMaps, shader_s::noPicMip, textureBundle_t::numImageAnimations, ParseTexMod(), ParseVector(), ParseWaveForm(), shader_s::portalRange, PRINT_WARNING, Q_stricmp(), qfalse, qtrue, R_FindImageFile(), shaderStage_t::rgbGen, shaderStage_t::rgbWave, ri, trGlobals_t::scratchImage, shaderStage_t::stateBits, textureBundle_t::tcGen, TCGEN_ENVIRONMENT_MAPPED, TCGEN_LIGHTMAP, TCGEN_TEXTURE, TCGEN_VECTOR, textureBundle_t::tcGenVectors, token, tr, textureBundle_t::videoMapHandle, and trGlobals_t::whiteImage.
Referenced by ParseShader().
static void ParseSurfaceParm (char ** text) [static]
References ARRAY_LEN, COM_ParseExt(), shader_s::contentFlags, infoParm_t::contents, CONTENTS_SOLID, Q_stricmp(), qfalse, si, shader_s::surfaceFlags, infoParm_t::surfaceFlags, and token.
Referenced by ParseShader().
static void ParseTexMod (char * _text, shaderStage_t * stage) [static]
References waveForm_t::amplitude, waveForm_t::base, shaderStage_t::bundle, COM_ParseExt(), ERR_DROP, waveForm_t::frequency, waveForm_t::func, texModInfo_t::matrix, shader_s::name, NameToGenFunc(), textureBundle_t::numTexMods, waveForm_t::phase, PRINT_WARNING, Q_stricmp(), qfalse, ri, texModInfo_t::rotateSpeed, texModInfo_t::scale, texModInfo_t::scroll, textureBundle_t::texMods, TMOD_ENTITY_TRANSLATE, TMOD_ROTATE, TMOD_SCALE, TMOD_SCROLL, TMOD_STRETCH, TMOD_TRANSFORM, TMOD_TURBULENT, token, TR_MAX_TEXMODS, texModInfo_t::translate, texModInfo_t::type, and texModInfo_t::wave.
Referenced by ParseStage().
static qboolean ParseVector (char ** text, int count, float * v) [static]
References COM_ParseExt(), count, shader_s::name, PRINT_WARNING, qfalse, qtrue, ri, and token.
Referenced by ParseShader(), and ParseStage().
static void ParseWaveForm (char ** text, waveForm_t * wave) [static]
References waveForm_t::amplitude, waveForm_t::base, COM_ParseExt(), waveForm_t::frequency, waveForm_t::func, shader_s::name, NameToGenFunc(), waveForm_t::phase, PRINT_WARNING, qfalse, ri, and token.
Referenced by ParseDeform(), and ParseStage().
shader_t* R_FindShader (const char * name, int lightmapIndex, qboolean mipRawImage)
References shaderStage_t::active, AGEN_SKIP, AGEN_VERTEX, shaderStage_t::alphaGen, shaderStage_t::bundle, CGEN_EXACT_VERTEX, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_VERTEX, Com_Memset, COM_StripExtension(), shader_s::defaultShader, trGlobals_t::defaultShader, FILE_HASH_SIZE, FindShaderInShaderText(), FinishShader(), generateHashValue(), GLS_DEFAULT, GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_SRC_ALPHA, hash(), textureBundle_t::image, cvar_s::integer, textureBundle_t::isLightmap, LIGHTMAP_2D, LIGHTMAP_BY_VERTEX, LIGHTMAP_NONE, LIGHTMAP_WHITEIMAGE, shader_s::lightmapIndex, trGlobals_t::lightmaps, MAX_QPATH, MAX_SHADER_STAGES, shader_s::name, shader_s::needsColor, shader_s::needsNormal, shader_s::needsST1, shader_s::needsST2, shader_s::next, trGlobals_t::numLightmaps, ParseShader(), PRINT_ALL, PRINT_DEVELOPER, PRINT_WARNING, Q_stricmp(), Q_strncpyz(), qtrue, R_FindImageFile(), r_printShaders, r_smp, R_SyncRenderThread(), shaderStage_t::rgbGen, ri, shaderStage_t::stateBits, textureBundle_t::texMods, tr, and trGlobals_t::whiteImage.
Referenced by CreateExternalShaders(), R_LoadFogs(), R_LoadIQM(), R_LoadMD3(), R_LoadMD4(), RE_RegisterShader(), RE_RegisterShaderLightMap(), RE_RegisterShaderNoMip(), RE_RegisterSkin(), and ShaderForShaderNum().
shader_t* R_FindShaderByName (const char * name)
References COM_StripExtension(), trGlobals_t::defaultShader, FILE_HASH_SIZE, generateHashValue(), hash(), MAX_QPATH, shader_s::name, shader_s::next, NULL, Q_stricmp(), and tr.
Referenced by R_RemapShader().
shader_t* R_GetShaderByHandle (qhandle_t hShader)
References trGlobals_t::defaultShader, trGlobals_t::numShaders, PRINT_WARNING, ri, trGlobals_t::shaders, and tr.
Referenced by R_AddAnimSurfaces(), R_AddEntitySurfaces(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_AddPolygonSurfaces(), R_RemapShader(), and RE_StretchPic().
void R_InitShaders (void)
References Com_Memset, CreateExternalShaders(), CreateInternalShaders(), PRINT_ALL, ri, and ScanAndLoadShaderFiles().
Referenced by R_Init().
void R_RemapShader (const char * shaderName, const char * newShaderName, const char * timeOffset)
References COM_StripExtension(), trGlobals_t::defaultShader, FILE_HASH_SIZE, generateHashValue(), h, hash(), MAX_QPATH, shader_s::name, shader_s::next, NULL, PRINT_WARNING, Q_stricmp(), R_FindShaderByName(), R_GetShaderByHandle(), RE_RegisterShaderLightMap(), shader_s::remappedShader, ri, shader_s::timeOffset, and tr.
Referenced by GetRefAPI(), and R_LoadEntities().
void R_ShaderList_f (void)
References refimport_t::Cmd_Argc, count, shader_s::defaultShader, shader_s::explicitlyDefined, shader_s::lightmapIndex, shader_s::multitextureEnv, shader_s::name, trGlobals_t::numShaders, shader_s::numUnfoggedPasses, shader_s::optimalStageIteratorFunc, PRINT_ALL, RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorSky(), RB_StageIteratorVertexLitTexture(), ri, shader, trGlobals_t::shaders, trGlobals_t::sortedShaders, and tr.
Referenced by R_Register().
qhandle_t RE_RegisterShader (const char * name)
References shader_s::defaultShader, shader_s::index, LIGHTMAP_2D, MAX_QPATH, PRINT_ALL, qtrue, R_FindShader(), and ri.
Referenced by GetRefAPI().
qhandle_t RE_RegisterShaderFromImage (const char * name, int lightmapIndex, image_t * image, qboolean mipRawImage)
References shaderStage_t::active, AGEN_SKIP, AGEN_VERTEX, shaderStage_t::alphaGen, shaderStage_t::bundle, CGEN_EXACT_VERTEX, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_VERTEX, Com_Memset, shader_s::defaultShader, FILE_HASH_SIZE, FinishShader(), generateHashValue(), GLS_DEFAULT, GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_SRC_ALPHA, hash(), textureBundle_t::image, shader_s::index, cvar_s::integer, textureBundle_t::isLightmap, LIGHTMAP_2D, LIGHTMAP_BY_VERTEX, LIGHTMAP_NONE, LIGHTMAP_WHITEIMAGE, shader_s::lightmapIndex, trGlobals_t::lightmaps, MAX_SHADER_STAGES, shader_s::name, shader_s::needsColor, shader_s::needsNormal, shader_s::needsST1, shader_s::needsST2, shader_s::next, trGlobals_t::numLightmaps, Q_stricmp(), Q_strncpyz(), qtrue, r_smp, R_SyncRenderThread(), shaderStage_t::rgbGen, shaderStage_t::stateBits, textureBundle_t::texMods, tr, and trGlobals_t::whiteImage.
Referenced by RE_RegisterFont().
qhandle_t RE_RegisterShaderLightMap (const char * name, int lightmapIndex)
References shader_s::defaultShader, shader_s::index, MAX_QPATH, PRINT_ALL, qtrue, R_FindShader(), and ri.
Referenced by R_RemapShader().
qhandle_t RE_RegisterShaderNoMip (const char * name)
References shader_s::defaultShader, shader_s::index, LIGHTMAP_2D, MAX_QPATH, PRINT_ALL, qfalse, R_FindShader(), and ri.
Referenced by GetRefAPI(), and RE_RegisterFont().
static void ScanAndLoadShaderFiles (void) [static]
References COM_Compress(), Com_Memset, COM_ParseExt(), Com_sprintf(), ERR_DROP, refimport_t::FS_FreeFile, refimport_t::FS_FreeFileList, refimport_t::FS_ListFiles, refimport_t::FS_ReadFile, generateHashValue(), h_low, hash(), refimport_t::Hunk_Alloc, MAX_QPATH, MAX_SHADER_FILES, MAX_SHADERTEXT_HASH, NULL, PRINT_DEVELOPER, PRINT_WARNING, qtrue, ri, s_shaderText, shaderTextHashTable, SkipBracedSection(), and token.
Referenced by R_InitShaders().
static void SortNewShader (void) [static]
References FixRenderCommandList(), trGlobals_t::numShaders, trGlobals_t::shaders, shader_s::sort, shader_s::sortedIndex, trGlobals_t::sortedShaders, and tr.
Referenced by GeneratePermanentShader().
static void VertexLightingCollapse (void) [static]
References shaderStage_t::active, AGEN_SKIP, shaderStage_t::alphaGen, shaderStage_t::bundle, CGEN_EXACT_VERTEX, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_ONE_MINUS_ENTITY, CGEN_WAVEFORM, Com_Memset, waveForm_t::func, GF_INVERSE_SAWTOOTH, GF_SAWTOOTH, GLS_DEPTHMASK_TRUE, GLS_DSTBLEND_BITS, GLS_SRCBLEND_BITS, textureBundle_t::isLightmap, LIGHTMAP_NONE, shader_s::lightmapIndex, MAX_SHADER_STAGES, textureBundle_t::numTexMods, shaderStage_t::rgbGen, shaderStage_t::rgbWave, shader_s::sort, SS_OPAQUE, shaderStage_t::stateBits, textureBundle_t::tcGen, and TCGEN_TEXTURE.
Referenced by FinishShader().
Variable Documentation
collapse_t collapse[] [static]
Initial value:
 {
        { 0, GLS_DSTBLEND_SRC_COLOR | GLS_SRCBLEND_ZERO,
                GL_MODULATE, 0 },
        { 0, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR,
                GL_MODULATE, 0 },
        { GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR,
                GL_MODULATE, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR },
        { GLS_DSTBLEND_SRC_COLOR | GLS_SRCBLEND_ZERO, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR,
                GL_MODULATE, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR },
        { GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR, GLS_DSTBLEND_SRC_COLOR | GLS_SRCBLEND_ZERO,
                GL_MODULATE, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR },
        { GLS_DSTBLEND_SRC_COLOR | GLS_SRCBLEND_ZERO, GLS_DSTBLEND_SRC_COLOR | GLS_SRCBLEND_ZERO,
                GL_MODULATE, GLS_DSTBLEND_ZERO | GLS_SRCBLEND_DST_COLOR },
        { 0, GLS_DSTBLEND_ONE | GLS_SRCBLEND_ONE,
                GL_ADD, 0 },
        { GLS_DSTBLEND_ONE | GLS_SRCBLEND_ONE, GLS_DSTBLEND_ONE | GLS_SRCBLEND_ONE,
                GL_ADD, GLS_DSTBLEND_ONE | GLS_SRCBLEND_ONE },
        { -1 }
}
shader_t* hashTable[FILE_HASH_SIZE] [static]
infoParm_t infoParms[]
char* s_shaderText [static]
Referenced by FindShaderInShaderText(), and ScanAndLoadShaderFiles().
shader_t shader [static]
Referenced by CG_MakeExplosion(), CG_MissileHitWall(), CG_PlayerFloatSprite(), CIN_RunCinematic(), FixRenderCommandList(), GeneratePermanentShader(), pushReward(), R_AddAnimSurfaces(), R_AddEntitySurfaces(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_BuildCloudData(), R_LoadFogs(), R_LoadMD3(), R_ShaderList_f(), R_SortDrawSurfs(), RB_RenderDrawSurfList(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorVertexLitTexture(), RB_StretchPic(), ShaderForShaderNum(), SurfIsOffscreen(), and UI_PlayerFloatSprite().
char** shaderTextHashTable[MAX_SHADERTEXT_HASH] [static]
Referenced by FindShaderInShaderText(), and ScanAndLoadShaderFiles().
shaderStage_t stages[MAX_SHADER_STAGES] [static]
texModInfo_t texMods[MAX_SHADER_STAGES][TR_MAX_TEXMODS] [static]