ioquake3: code/renderer/tr_model_iqm.c File Reference
tr_model_iqm.c File Reference
#include "tr_local.h"
Defines
#define LL(x) x=LittleLong(x)
Functions
static qboolean IQM_CheckRange (iqmHeader_t *header, int offset, int count, int size)
static void Matrix34Multiply (float *a, float *b, float *out)
static void InterpolateMatrix (float *a, float *b, float lerp, float *mat)
static void JointToMatrix (vec4_t rot, vec3_t scale, vec3_t trans, float *mat)
static void Matrix34Invert (float *inMat, float *outMat)
qboolean R_LoadIQM (model_t *mod, void *buffer, int filesize, const char *mod_name)
static int R_CullIQM (iqmData_t *data, trRefEntity_t *ent)
int R_ComputeIQMFogNum (iqmData_t *data, trRefEntity_t *ent)
void R_AddIQMSurfaces (trRefEntity_t *ent)
static void ComputeJointMats (iqmData_t *data, int frame, int oldframe, float backlerp, float *mat)
void RB_IQMSurfaceAnim (surfaceType_t *surface)
int R_IQMLerpTag (orientation_t *tag, iqmData_t *data, int startFrame, int endFrame, float frac, const char *tagName)
Define Documentation
#define LL (x) x=LittleLong(x)
Referenced by R_LoadIQM().
Function Documentation
static void ComputeJointMats (iqmData_t * data, int frame, int oldframe, float backlerp, float * mat) [static]
References Com_Memcpy, InterpolateMatrix(), iqmData_t::jointParents, Matrix34Multiply(), iqmData_t::num_joints, and iqmData_t::poseMats.
Referenced by R_IQMLerpTag(), and RB_IQMSurfaceAnim().
static void InterpolateMatrix (float * a, float * b, float lerp, float * mat) [static]
Referenced by ComputeJointMats().
static qboolean IQM_CheckRange (iqmHeader_t * header, int offset, int count, int size) [static]
References iqmheader::filesize.
Referenced by R_LoadIQM().
static void JointToMatrix (vec4_t rot, vec3_t scale, vec3_t trans, float * mat) [static]
References xx, and yy.
Referenced by R_LoadIQM().
static void Matrix34Invert (float * inMat, float * outMat) [static]
References DotProduct, and VectorScale.
Referenced by R_LoadIQM().
static void Matrix34Multiply (float * a, float * b, float * out) [static]
Referenced by ComputeJointMats(), and R_LoadIQM().
void R_AddIQMSurfaces (trRefEntity_t * ent)
References CULL_OUT, trGlobals_t::currentModel, refEntity_t::customShader, refEntity_t::customSkin, data, trGlobals_t::defaultShader, trRefEntity_t::e, refEntity_t::frame, if(), cvar_s::integer, viewParms_t::isPortal, model_s::modelData, skinSurface_t::name, srfIQModel_s::name, model_s::name, iqmData_t::num_frames, iqmData_t::num_surfaces, trGlobals_t::numSkins, skin_s::numSurfaces, refEntity_t::oldframe, PRINT_DEVELOPER, trGlobals_t::projectionShadowShader, R_AddDrawSurf(), R_ComputeIQMFogNum(), R_CullIQM(), R_GetShaderByHandle(), R_GetSkinByHandle(), R_SetupEntityLighting(), r_shadows, trGlobals_t::refdef, refEntity_t::renderfx, RF_DEPTHHACK, RF_NOSHADOW, RF_SHADOW_PLANE, RF_THIRD_PERSON, RF_WRAP_FRAMES, ri, shader, skinSurface_t::shader, srfIQModel_s::shader, trGlobals_t::shadowShader, shader_s::sort, SS_OPAQUE, skin_s::surfaces, iqmData_t::surfaces, tr, and trGlobals_t::viewParms.
Referenced by R_AddEntitySurfaces().
int R_ComputeIQMFogNum (iqmData_t * data, trRefEntity_t * ent)
References fog_t::bounds, iqmData_t::bounds, trRefEntity_t::e, world_t::fogs, refEntity_t::frame, world_t::numfogs, refEntity_t::origin, RDF_NOWORLDMODEL, trRefdef_t::rdflags, trGlobals_t::refdef, tr, VectorAdd, VectorLength(), VectorMA(), VectorSubtract, and trGlobals_t::world.
Referenced by R_AddIQMSurfaces().
static int R_CullIQM (iqmData_t * data, trRefEntity_t * ent) [static]
References iqmData_t::bounds, frontEndCounters_t::c_box_cull_md3_clip, frontEndCounters_t::c_box_cull_md3_in, frontEndCounters_t::c_box_cull_md3_out, CULL_CLIP, CULL_IN, CULL_OUT, trRefEntity_t::e, refEntity_t::frame, refEntity_t::oldframe, trGlobals_t::pc, R_CullLocalBox(), and tr.
Referenced by R_AddIQMSurfaces().
int R_IQMLerpTag (orientation_t * tag, iqmData_t * data, int startFrame, int endFrame, float frac, const char * tagName)
References orientation_t::axis, AxisClear(), ComputeJointMats(), IQM_MAX_JOINTS, iqmData_t::names, iqmData_t::num_joints, orientation_t::origin, qfalse, qtrue, and VectorClear.
Referenced by R_LerpTag().
qboolean R_LoadIQM (model_t * mod, void * buffer, int filesize, const char * mod_name)
References iqmbounds::bbmax, iqmbounds::bbmin, iqmData_t::blendIndexes, iqmData_t::blendWeights, iqmData_t::bounds, iqmpose::channeloffset, iqmpose::channelscale, iqmData_t::colors, Com_Memcpy, srfIQModel_s::data, shader_s::defaultShader, trGlobals_t::defaultShader, iqmheader::filesize, iqmmesh::first_triangle, srfIQModel_s::first_triangle, iqmmesh::first_vertex, srfIQModel_s::first_vertex, iqmheader::flags, iqmvertexarray::format, h_low, refimport_t::Hunk_Alloc, int(), IQM_BLENDINDEXES, IQM_BLENDWEIGHTS, IQM_BYTE, IQM_CheckRange(), IQM_COLOR, IQM_FLOAT, IQM_INT, IQM_MAGIC, IQM_MAX_JOINTS, IQM_NORMAL, IQM_POSITION, IQM_TANGENT, IQM_TEXCOORD, IQM_UBYTE, IQM_UINT, IQM_VERSION, iqmData_t::jointParents, JointToMatrix(), LIGHTMAP_NONE, LL, iqmheader::magic, iqmpose::mask, iqmmesh::material, Matrix34Invert(), Matrix34Multiply(), MOD_IQM, model_s::modelData, n, iqmmesh::name, iqmjoint::name, srfIQModel_s::name, iqmData_t::names, iqmData_t::normals, iqmheader::num_anims, iqmheader::num_comment, iqmheader::num_extensions, iqmheader::num_framechannels, iqmheader::num_frames, iqmData_t::num_frames, iqmheader::num_joints, iqmData_t::num_joints, iqmheader::num_meshes, iqmheader::num_poses, iqmData_t::num_surfaces, iqmheader::num_text, iqmheader::num_triangles, iqmmesh::num_triangles, iqmData_t::num_triangles, srfIQModel_s::num_triangles, iqmheader::num_vertexarrays, iqmheader::num_vertexes, iqmmesh::num_vertexes, iqmData_t::num_vertexes, srfIQModel_s::num_vertexes, iqmvertexarray::offset, iqmheader::ofs_adjacency, iqmheader::ofs_anims, iqmheader::ofs_bounds, iqmheader::ofs_comment, iqmheader::ofs_extensions, iqmheader::ofs_frames, iqmheader::ofs_joints, iqmheader::ofs_meshes, iqmheader::ofs_poses, iqmheader::ofs_text, iqmheader::ofs_triangles, iqmheader::ofs_vertexarrays, iqmjoint::parent, iqmpose::parent, iqmData_t::poseMats, iqmData_t::positions, PRINT_WARNING, Q_strlwr(), Q_strncmp(), Q_strncpyz(), qfalse, qtrue, R_FindShader(), ri, iqmjoint::rotate, iqmjoint::scale, SF_IQM, srfIQModel_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, iqmvertexarray::size, iqmData_t::surfaces, srfIQModel_s::surfaceType, iqmData_t::tangents, iqmData_t::texcoords, tr, iqmjoint::translate, iqmData_t::triangles, iqmvertexarray::type, model_s::type, iqmheader::version, and iqmtriangle::vertex.
Referenced by R_RegisterIQM().
void RB_IQMSurfaceAnim (surfaceType_t * surface)
References backEnd, refEntity_t::backlerp, iqmData_t::blendIndexes, iqmData_t::blendWeights, iqmData_t::colors, ComputeJointMats(), backEndState_t::currentEntity, srfIQModel_s::data, data, trRefEntity_t::e, srfIQModel_s::first_triangle, srfIQModel_s::first_vertex, refEntity_t::frame, IQM_MAX_JOINTS, iqmData_t::normals, iqmData_t::num_frames, srfIQModel_s::num_triangles, srfIQModel_s::num_vertexes, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, refEntity_t::oldframe, iqmData_t::positions, ptr(), RB_CHECKOVERFLOW, tess, iqmData_t::texcoords, and iqmData_t::triangles.