ioquake3: code/ui/ui_local.h File Reference
ui_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../renderer/tr_types.h"
#include "ui_public.h"
#include "../client/keycodes.h"
#include "../game/bg_public.h"
#include "ui_shared.h"
Data Structures
struct _tag_menuframework
struct menucommon_s
struct mfield_t
struct menufield_s
struct menuslider_s
struct menulist_s
struct menuaction_s
struct menuradiobutton_s
struct menubitmap_s
struct menutext_s
struct lerpFrame_t
struct playerInfo_t
struct uiStatic_t
struct characterInfo
struct aliasInfo
struct teamInfo
struct gameTypeInfo
struct mapInfo
struct tierInfo
struct serverFilter_s
struct pinglist_t
struct serverStatus_s
struct pendingServer_t
struct pendingServerStatus_t
struct serverStatusInfo_t
struct modInfo_t
struct uiInfo_t
struct postGameInfo_s
Defines
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
#define SLIDER_RANGE 10
#define MAX_EDIT_LINE 256
#define MAX_MENUDEPTH 8
#define MAX_MENUITEMS 96
#define MTYPE_NULL 0
#define MTYPE_SLIDER 1
#define MTYPE_ACTION 2
#define MTYPE_SPINCONTROL 3
#define MTYPE_FIELD 4
#define MTYPE_RADIOBUTTON 5
#define MTYPE_BITMAP 6
#define MTYPE_TEXT 7
#define MTYPE_SCROLLLIST 8
#define MTYPE_PTEXT 9
#define MTYPE_BTEXT 10
#define QMF_BLINK 0x00000001
#define QMF_SMALLFONT 0x00000002
#define QMF_LEFT_JUSTIFY 0x00000004
#define QMF_CENTER_JUSTIFY 0x00000008
#define QMF_RIGHT_JUSTIFY 0x00000010
#define QMF_NUMBERSONLY 0x00000020
#define QMF_HIGHLIGHT 0x00000040
#define QMF_HIGHLIGHT_IF_FOCUS 0x00000080
#define QMF_PULSEIFFOCUS 0x00000100
#define QMF_HASMOUSEFOCUS 0x00000200
#define QMF_NOONOFFTEXT 0x00000400
#define QMF_MOUSEONLY 0x00000800
#define QMF_HIDDEN 0x00001000
#define QMF_GRAYED 0x00002000
#define QMF_INACTIVE 0x00004000
#define QMF_NODEFAULTINIT 0x00008000
#define QMF_OWNERDRAW 0x00010000
#define QMF_PULSE 0x00020000
#define QMF_LOWERCASE 0x00040000
#define QMF_UPPERCASE 0x00080000
#define QMF_SILENT 0x00100000
#define QM_GOTFOCUS 1
#define QM_LOSTFOCUS 2
#define QM_ACTIVATED 3
#define MAX_FAVORITESERVERS 16
#define UI_NUMFX 7
#define MAX_HEADS 64
#define MAX_ALIASES 64
#define MAX_HEADNAME 32
#define MAX_TEAMS 64
#define MAX_GAMETYPES 16
#define MAX_MAPS 128
#define MAX_SPMAPS 16
#define PLAYERS_PER_TEAM 5
#define MAX_PINGREQUESTS 32
#define MAX_ADDRESSLENGTH 64
#define MAX_HOSTNAMELENGTH 22
#define MAX_MAPNAMELENGTH 16
#define MAX_STATUSLENGTH 64
#define MAX_LISTBOXWIDTH 59
#define UI_FONT_THRESHOLD 0.1
#define MAX_DISPLAY_SERVERS 2048
#define MAX_SERVERSTATUS_LINES 128
#define MAX_SERVERSTATUS_TEXT 1024
#define MAX_FOUNDPLAYER_SERVERS 16
#define TEAM_MEMBERS 5
#define GAMES_ALL 0
#define GAMES_FFA 1
#define GAMES_TEAMPLAY 2
#define GAMES_TOURNEY 3
#define GAMES_CTF 4
#define MAPS_PER_TIER 3
#define MAX_TIERS 16
#define MAX_MODS 64
#define MAX_DEMOS 512
#define MAX_MOVIES 256
#define MAX_PLAYERMODELS 256
#define ASSET_BACKGROUND "uiBackground"
Typedefs
typedef struct _tag_menuframework menuframework_s
typedef struct serverFilter_s serverFilter_t
typedef struct serverStatus_s serverStatus_t
typedef struct postGameInfo_s postGameInfo_t
Enumerations
enum awardType_t {
AWARD_ACCURACY, AWARD_IMPRESSIVE, AWARD_EXCELLENT, AWARD_GAUNTLET,
AWARD_FRAGS, AWARD_PERFECT, AWARD_ACCURACY, AWARD_IMPRESSIVE,
AWARD_EXCELLENT, AWARD_GAUNTLET, AWARD_FRAGS, AWARD_PERFECT
}
Functions
void Menu_Cache (void)
void Menu_Focus (menucommon_s *m)
void Menu_AddItem (menuframework_s *menu, void *item)
void Menu_AdjustCursor (menuframework_s *menu, int dir)
void Menu_Draw (menuframework_s *menu)
void * Menu_ItemAtCursor (menuframework_s *m)
sfxHandle_t Menu_ActivateItem (menuframework_s *s, menucommon_s *item)
void Menu_SetCursor (menuframework_s *s, int cursor)
void Menu_SetCursorToItem (menuframework_s *m, void *ptr)
sfxHandle_t Menu_DefaultKey (menuframework_s *s, int key)
void Bitmap_Init (menubitmap_s *b)
void Bitmap_Draw (menubitmap_s *b)
void ScrollList_Draw (menulist_s *l)
sfxHandle_t ScrollList_Key (menulist_s *l, int key)
void MField_Clear (mfield_t *edit)
void MField_KeyDownEvent (mfield_t *edit, int key)
void MField_CharEvent (mfield_t *edit, int ch)
void MField_Draw (mfield_t *edit, int x, int y, int style, vec4_t color)
void MenuField_Init (menufield_s *m)
void MenuField_Draw (menufield_s *f)
sfxHandle_t MenuField_Key (menufield_s *m, int *key)
void UI_Report (void)
void UI_Load (void)
void UI_LoadMenus (const char *menuFile, qboolean reset)
void _UI_SetActiveMenu (uiMenuCommand_t menu)
int UI_AdjustTimeByGame (int time)
void UI_ShowPostGame (qboolean newHigh)
void UI_ClearScores (void)
void UI_LoadArenas (void)
void MainMenu_Cache (void)
void UI_MainMenu (void)
void UI_RegisterCvars (void)
void UI_UpdateCvars (void)
void UI_CreditMenu (void)
void InGame_Cache (void)
void UI_InGameMenu (void)
void ConfirmMenu_Cache (void)
void UI_ConfirmMenu (const char *question, void(*draw)(void), void(*action)(qboolean result))
void UI_SetupMenu_Cache (void)
void UI_SetupMenu (void)
void UI_TeamMainMenu (void)
void TeamMain_Cache (void)
void UI_DrawConnectScreen (qboolean overlay)
void UI_ControlsMenu (void)
void Controls_Cache (void)
void UI_DemosMenu (void)
void Demos_Cache (void)
void UI_CinematicsMenu (void)
void UI_CinematicsMenu_f (void)
void UI_CinematicsMenu_Cache (void)
void UI_ModsMenu (void)
void UI_ModsMenu_Cache (void)
void UI_CDKeyMenu (void)
void UI_CDKeyMenu_Cache (void)
void UI_CDKeyMenu_f (void)
void UI_PlayerModelMenu (void)
void PlayerModel_Cache (void)
void UI_PlayerSettingsMenu (void)
void PlayerSettings_Cache (void)
void UI_PreferencesMenu (void)
void Preferences_Cache (void)
void UI_SpecifyLeagueMenu (void)
void SpecifyLeague_Cache (void)
void UI_SpecifyServerMenu (void)
void SpecifyServer_Cache (void)
void UI_ArenaServersMenu (void)
void ArenaServers_Cache (void)
void UI_StartServerMenu (qboolean multiplayer)
void StartServer_Cache (void)
void ServerOptions_Cache (void)
void UI_BotSelectMenu (char *bot)
void UI_BotSelectMenu_Cache (void)
void UI_ServerInfoMenu (void)
void ServerInfo_Cache (void)
void UI_GraphicsOptionsMenu (void)
void GraphicsOptions_Cache (void)
void DriverInfo_Cache (void)
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t *pi, int time)
void UI_PlayerInfo_SetModel (playerInfo_t *pi, const char *model, const char *headmodel, char *teamName)
void UI_PlayerInfo_SetInfo (playerInfo_t *pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNum, qboolean chat)
qboolean UI_RegisterClientModelname (playerInfo_t *pi, const char *modelSkinName, const char *headName, const char *teamName)
void UI_Init (void)
void UI_Shutdown (void)
void UI_KeyEvent (int key)
void UI_MouseEvent (int dx, int dy)
void UI_Refresh (int realtime)
qboolean UI_ConsoleCommand (int realTime)
float UI_ClampCvar (float min, float max, float value)
void UI_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_DrawRect (float x, float y, float width, float height, const float *color)
void UI_DrawTopBottom (float x, float y, float w, float h)
void UI_DrawSides (float x, float y, float w, float h)
void UI_UpdateScreen (void)
void UI_SetColor (const float *rgba)
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
float UI_ProportionalSizeScale (int style)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
int UI_ProportionalStringWidth (const char *str)
void UI_DrawString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
qboolean UI_CursorInRect (int x, int y, int width, int height)
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
void UI_DrawTextBox (int x, int y, int width, int lines)
qboolean UI_IsFullscreen (void)
void UI_SetActiveMenu (uiMenuCommand_t menu)
void UI_PushMenu (menuframework_s *menu)
void UI_PopMenu (void)
void UI_ForceMenuOff (void)
char * UI_Argv (int arg)
char * UI_Cvar_VariableString (const char *var_name)
void UI_StartDemoLoop (void)
void UI_LoadBestScores (const char *map, int game)
void UI_SPLevelMenu_Cache (void)
void UI_SPLevelMenu (void)
void UI_SPLevelMenu_f (void)
void UI_SPLevelMenu_ReInit (void)
void UI_SPArena_Start (const char *arenaInfo)
void UI_SPPostgameMenu_Cache (void)
void UI_SPPostgameMenu_f (void)
void UI_SPSkillMenu (const char *arenaInfo)
void UI_SPSkillMenu_Cache (void)
void trap_Print (const char *string)
void trap_Error (const char *string) __attribute__((noreturn))
int trap_Milliseconds (void)
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
void trap_Cvar_Update (vmCvar_t *vmCvar)
void trap_Cvar_Set (const char *var_name, const char *value)
float trap_Cvar_VariableValue (const char *var_name)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
void trap_Cvar_SetValue (const char *var_name, float value)
void trap_Cvar_Reset (const char *name)
void trap_Cvar_Create (const char *var_name, const char *var_value, int flags)
void trap_Cvar_InfoStringBuffer (int bit, char *buffer, int bufsize)
int trap_Argc (void)
void trap_Argv (int n, char *buffer, int bufferLength)
void trap_Cmd_ExecuteText (int exec_when, const char *text)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
qhandle_t trap_R_RegisterModel (const char *name)
qhandle_t trap_R_RegisterSkin (const char *name)
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
void trap_R_ClearScene (void)
void trap_R_AddRefEntityToScene (const refEntity_t *re)
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
void trap_R_RenderScene (const refdef_t *fd)
void trap_R_SetColor (const float *rgba)
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
void trap_UpdateScreen (void)
int trap_CM_LerpTag (orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName)
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
void trap_Key_SetBinding (int keynum, const char *binding)
qboolean trap_Key_IsDown (int keynum)
qboolean trap_Key_GetOverstrikeMode (void)
void trap_Key_SetOverstrikeMode (qboolean state)
void trap_Key_ClearStates (void)
int trap_Key_GetCatcher (void)
void trap_Key_SetCatcher (int catcher)
void trap_GetClipboardData (char *buf, int bufsize)
void trap_GetClientState (uiClientState_t *state)
void trap_GetGlconfig (glconfig_t *glconfig)
int trap_GetConfigString (int index, char *buff, int buffsize)
int trap_LAN_GetServerCount (int source)
void trap_LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
void trap_LAN_GetServerInfo (int source, int n, char *buf, int buflen)
int trap_LAN_GetServerPing (int source, int n)
int trap_LAN_GetPingQueueCount (void)
void trap_LAN_ClearPing (int n)
void trap_LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
void trap_LAN_GetPingInfo (int n, char *buf, int buflen)
void trap_LAN_LoadCachedServers (void)
void trap_LAN_SaveCachedServers (void)
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
int trap_LAN_ServerIsVisible (int source, int n)
qboolean trap_LAN_UpdateVisiblePings (int source)
int trap_LAN_AddServer (int source, const char *name, const char *addr)
void trap_LAN_RemoveServer (int source, const char *addr)
void trap_LAN_ResetPings (int n)
int trap_LAN_ServerStatus (const char *serverAddress, char *serverStatus, int maxLen)
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
int trap_MemoryRemaining (void)
void trap_GetCDKey (char *buf, int buflen)
void trap_SetCDKey (char *buf)
void trap_R_RegisterFont (const char *pFontname, int pointSize, fontInfo_t *font)
void trap_S_StopBackgroundTrack (void)
void trap_S_StartBackgroundTrack (const char *intro, const char *loop)
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
e_status trap_CIN_StopCinematic (int handle)
e_status trap_CIN_RunCinematic (int handle)
void trap_CIN_DrawCinematic (int handle)
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
int trap_RealTime (qtime_t *qtime)
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
qboolean trap_VerifyCDKey (const char *key, const char *chksum)
void trap_SetPbClStatus (int status)
void UI_AddBots_Cache (void)
void UI_AddBotsMenu (void)
void UI_RemoveBots_Cache (void)
void UI_RemoveBotsMenu (void)
void UI_TeamOrdersMenu (void)
void UI_TeamOrdersMenu_f (void)
void UI_TeamOrdersMenu_Cache (void)
void UI_LoadConfig_Cache (void)
void UI_LoadConfigMenu (void)
void UI_SaveConfigMenu_Cache (void)
void UI_SaveConfigMenu (void)
void UI_DisplayOptionsMenu_Cache (void)
void UI_DisplayOptionsMenu (void)
void UI_SoundOptionsMenu_Cache (void)
void UI_SoundOptionsMenu (void)
void UI_NetworkOptionsMenu_Cache (void)
void UI_NetworkOptionsMenu (void)
const char * UI_GetArenaInfoByNumber (int num)
const char * UI_GetArenaInfoByMap (const char *map)
const char * UI_GetSpecialArenaInfo (const char *tag)
int UI_GetNumArenas (void)
int UI_GetNumSPArenas (void)
int UI_GetNumSPTiers (void)
char * UI_GetBotInfoByNumber (int num)
char * UI_GetBotInfoByName (const char *name)
int UI_GetNumBots (void)
void UI_LoadBots (void)
char * UI_GetBotNameByNumber (int num)
void UI_GetBestScore (int level, int *score, int *skill)
void UI_SetBestScore (int level, int score)
int UI_TierCompleted (int levelWon)
qboolean UI_ShowTierVideo (int tier)
qboolean UI_CanShowTierVideo (int tier)
int UI_GetCurrentGame (void)
void UI_NewGame (void)
void UI_LogAwardData (int award, int data)
int UI_GetAwardLevel (int award)
void UI_SPUnlock_f (void)
void UI_SPUnlockMedals_f (void)
void UI_InitGameinfo (void)
void Login_Cache (void)
void UI_LoginMenu (void)
void Signup_Cache (void)
void UI_SignupMenu (void)
void RankStatus_Cache (void)
void UI_RankStatusMenu (void)
Variables
vmCvar_t ui_ffa_fraglimit
vmCvar_t ui_ffa_timelimit
vmCvar_t ui_tourney_fraglimit
vmCvar_t ui_tourney_timelimit
vmCvar_t ui_team_fraglimit
vmCvar_t ui_team_timelimit
vmCvar_t ui_team_friendly
vmCvar_t ui_ctf_capturelimit
vmCvar_t ui_ctf_timelimit
vmCvar_t ui_ctf_friendly
vmCvar_t ui_arenasFile
vmCvar_t ui_botsFile
vmCvar_t ui_spScores1
vmCvar_t ui_spScores2
vmCvar_t ui_spScores3
vmCvar_t ui_spScores4
vmCvar_t ui_spScores5
vmCvar_t ui_spAwards
vmCvar_t ui_spVideos
vmCvar_t ui_spSkill
vmCvar_t ui_spSelection
vmCvar_t ui_browserMaster
vmCvar_t ui_browserGameType
vmCvar_t ui_browserShowFull
vmCvar_t ui_browserShowEmpty
vmCvar_t ui_brassTime
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_marks
vmCvar_t ui_server1
vmCvar_t ui_server2
vmCvar_t ui_server3
vmCvar_t ui_server4
vmCvar_t ui_server5
vmCvar_t ui_server6
vmCvar_t ui_server7
vmCvar_t ui_server8
vmCvar_t ui_server9
vmCvar_t ui_server10
vmCvar_t ui_server11
vmCvar_t ui_server12
vmCvar_t ui_server13
vmCvar_t ui_server14
vmCvar_t ui_server15
vmCvar_t ui_server16
vmCvar_t ui_cdkey
vmCvar_t ui_cdkeychecked
vmCvar_t ui_captureLimit
vmCvar_t ui_fragLimit
vmCvar_t ui_gameType
vmCvar_t ui_netGameType
vmCvar_t ui_actualNetGameType
vmCvar_t ui_joinGameType
vmCvar_t ui_netSource
vmCvar_t ui_serverFilterType
vmCvar_t ui_dedicated
vmCvar_t ui_opponentName
vmCvar_t ui_menuFiles
vmCvar_t ui_currentTier
vmCvar_t ui_currentMap
vmCvar_t ui_currentNetMap
vmCvar_t ui_mapIndex
vmCvar_t ui_currentOpponent
vmCvar_t ui_selectedPlayer
vmCvar_t ui_selectedPlayerName
vmCvar_t ui_lastServerRefresh_0
vmCvar_t ui_lastServerRefresh_1
vmCvar_t ui_lastServerRefresh_2
vmCvar_t ui_lastServerRefresh_3
vmCvar_t ui_singlePlayerActive
vmCvar_t ui_scoreAccuracy
vmCvar_t ui_scoreImpressives
vmCvar_t ui_scoreExcellents
vmCvar_t ui_scoreDefends
vmCvar_t ui_scoreAssists
vmCvar_t ui_scoreGauntlets
vmCvar_t ui_scoreScore
vmCvar_t ui_scorePerfect
vmCvar_t ui_scoreTeam
vmCvar_t ui_scoreBase
vmCvar_t ui_scoreTimeBonus
vmCvar_t ui_scoreSkillBonus
vmCvar_t ui_scoreShutoutBonus
vmCvar_t ui_scoreTime
vmCvar_t ui_smallFont
vmCvar_t ui_bigFont
vmCvar_t ui_serverStatusTimeOut
sfxHandle_t menu_in_sound
sfxHandle_t menu_move_sound
sfxHandle_t menu_out_sound
sfxHandle_t menu_buzz_sound
sfxHandle_t menu_null_sound
sfxHandle_t weaponChangeSound
vec4_t menu_text_color
vec4_t menu_grayed_color
vec4_t menu_dark_color
vec4_t menu_highlight_color
vec4_t menu_red_color
vec4_t menu_black_color
vec4_t menu_dim_color
vec4_t color_black
vec4_t color_white
vec4_t color_yellow
vec4_t color_blue
vec4_t color_orange
vec4_t color_red
vec4_t color_dim
vec4_t name_color
vec4_t list_color
vec4_t listbar_color
vec4_t text_color_disabled
vec4_t text_color_normal
vec4_t text_color_highlight
char * ui_medalNames []
char * ui_medalPicNames []
char * ui_medalSounds []
uiInfo_t uiInfo
qboolean m_entersound
uiStatic_t uis
Define Documentation
#define ASSET_BACKGROUND "uiBackground"
#define GAMES_ALL 0
#define GAMES_CTF 4
#define GAMES_FFA 1
#define GAMES_TEAMPLAY 2
#define GAMES_TOURNEY 3
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
#define MAPS_PER_TIER 3
Referenced by UI_DrawTierGameType(), and UI_DrawTierMapName().
#define MAX_ADDRESSLENGTH 64
#define MAX_ALIASES 64
Referenced by Alias_Parse().
#define MAX_DEMOS 512
#define MAX_DISPLAY_SERVERS 2048
#define MAX_EDIT_LINE 256
#define MAX_FAVORITESERVERS 16
#define MAX_FOUNDPLAYER_SERVERS 16
Referenced by UI_BuildFindPlayerList().
#define MAX_GAMETYPES 16
Referenced by GameType_Parse().
#define MAX_HEADNAME 32
#define MAX_HEADS 64
Referenced by Character_Parse().
#define MAX_HOSTNAMELENGTH 22
#define MAX_LISTBOXWIDTH 59
#define MAX_MAPNAMELENGTH 16
#define MAX_MAPS 128
Referenced by MapList_Parse(), and UI_LoadArenas().
#define MAX_MENUDEPTH 8
#define MAX_MENUITEMS 96
#define MAX_MODS 64
#define MAX_MOVIES 256
Referenced by UI_LoadMovies().
#define MAX_PINGREQUESTS 32
#define MAX_PLAYERMODELS 256
#define MAX_SERVERSTATUS_LINES 128
Referenced by UI_GetServerStatusInfo().
#define MAX_SERVERSTATUS_TEXT 1024
#define MAX_SPMAPS 16
#define MAX_STATUSLENGTH 64
#define MAX_TEAMS 64
Referenced by Team_Parse().
#define MAX_TIERS 16
#define MTYPE_ACTION 2
#define MTYPE_BITMAP 6
#define MTYPE_BTEXT 10
#define MTYPE_FIELD 4
#define MTYPE_NULL 0
#define MTYPE_PTEXT 9
#define MTYPE_RADIOBUTTON 5
#define MTYPE_SCROLLLIST 8
#define MTYPE_SLIDER 1
#define MTYPE_SPINCONTROL 3
#define MTYPE_TEXT 7
#define PLAYERS_PER_TEAM 5
Referenced by UI_RunMenuScript().
#define QM_ACTIVATED 3
#define QM_GOTFOCUS 1
#define QM_LOSTFOCUS 2
#define QMF_BLINK 0x00000001
#define QMF_CENTER_JUSTIFY 0x00000008
#define QMF_GRAYED 0x00002000
#define QMF_HASMOUSEFOCUS 0x00000200
#define QMF_HIDDEN 0x00001000
#define QMF_HIGHLIGHT 0x00000040
#define QMF_HIGHLIGHT_IF_FOCUS 0x00000080
#define QMF_INACTIVE 0x00004000
#define QMF_LEFT_JUSTIFY 0x00000004
#define QMF_LOWERCASE 0x00040000
#define QMF_MOUSEONLY 0x00000800
#define QMF_NODEFAULTINIT 0x00008000
#define QMF_NOONOFFTEXT 0x00000400
#define QMF_NUMBERSONLY 0x00000020
#define QMF_OWNERDRAW 0x00010000
#define QMF_PULSE 0x00020000
#define QMF_PULSEIFFOCUS 0x00000100
#define QMF_RIGHT_JUSTIFY 0x00000010
#define QMF_SILENT 0x00100000
#define QMF_SMALLFONT 0x00000002
#define QMF_UPPERCASE 0x00080000
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
#define SLIDER_RANGE 10
#define TEAM_MEMBERS 5
Referenced by Team_Parse(), and UI_HeadCountByTeam().
#define UI_FONT_THRESHOLD 0.1
#define UI_NUMFX 7
Typedef Documentation
typedef struct _tag_menuframework menuframework_s
typedef struct postGameInfo_s postGameInfo_t
typedef struct serverFilter_s serverFilter_t
typedef struct serverStatus_s serverStatus_t
Enumeration Type Documentation
enum awardType_t
Enumerator:
AWARD_ACCURACY
AWARD_IMPRESSIVE
AWARD_EXCELLENT
AWARD_GAUNTLET
AWARD_FRAGS
AWARD_PERFECT
AWARD_ACCURACY
AWARD_IMPRESSIVE
AWARD_EXCELLENT
AWARD_GAUNTLET
AWARD_FRAGS
AWARD_PERFECT
Function Documentation
void _UI_SetActiveMenu (uiMenuCommand_t menu)
References uiInfo_t::inGameLoad, vmCvar_t::integer, KEYCATCH_UI, Menu_Count(), Menus_ActivateByName(), Menus_CloseAll(), trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Key_ClearStates(), trap_Key_GetCatcher(), trap_Key_SetCatcher(), UI_BuildPlayerList(), UI_LoadNonIngame(), ui_singlePlayerActive, UIMENU_BAD_CD_KEY, UIMENU_INGAME, UIMENU_MAIN, UIMENU_NEED_CD, UIMENU_NONE, UIMENU_POSTGAME, and UIMENU_TEAM.
Referenced by UI_ShowPostGame(), and vmMain().
void ArenaServers_Cache (void)
References ART_ARROWS0, ART_ARROWS_DOWN, ART_ARROWS_UP, ART_BACK0, ART_BACK1, ART_CONNECT0, ART_CONNECT1, ART_CREATE0, ART_CREATE1, ART_PUNKBUSTER, ART_REFRESH0, ART_REFRESH1, ART_SPECIFY0, ART_SPECIFY1, ART_UNKNOWNMAP, and trap_R_RegisterShaderNoMip().
void Bitmap_Draw (menubitmap_s * b)
References colorMdGrey, menubitmap_s::errorpic, menucommon_s::flags, menubitmap_s::focuscolor, menubitmap_s::focuspic, menubitmap_s::focusshader, menubitmap_s::generic, h, menubitmap_s::height, Menu_ItemAtCursor(), menucommon_s::name, NULL, menucommon_s::parent, pulse_color, PULSE_DIVISOR, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_HIGHLIGHT, QMF_HIGHLIGHT_IF_FOCUS, QMF_PULSE, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, uiStatic_t::realtime, menubitmap_s::shader, trap_R_RegisterShaderNoMip(), trap_R_SetColor(), UI_DrawHandlePic(), uis, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
void Bitmap_Init (menubitmap_s * b)
References menucommon_s::bottom, menucommon_s::flags, menubitmap_s::focusshader, menubitmap_s::generic, h, menubitmap_s::height, menucommon_s::left, QMF_CENTER_JUSTIFY, QMF_RIGHT_JUSTIFY, menucommon_s::right, menubitmap_s::shader, menucommon_s::top, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
void ConfirmMenu_Cache (void)
References ART_CONFIRM_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), UI_ConfirmMenu_Style(), and UI_Message().
void Controls_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by Controls_MenuInit(), and UI_Cache_f().
void Demos_Cache (void)
References ART_ARROWLEFT, ART_ARROWRIGHT, ART_ARROWS, ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, ART_GO0, ART_GO1, and trap_R_RegisterShaderNoMip().
Referenced by Demos_MenuInit(), and UI_Cache_f().
void DriverInfo_Cache (void)
References driverinfo_artlist, and trap_R_RegisterShaderNoMip().
void GraphicsOptions_Cache (void)
References GRAPHICSOPTIONS_ACCEPT0, GRAPHICSOPTIONS_ACCEPT1, GRAPHICSOPTIONS_BACK0, GRAPHICSOPTIONS_BACK1, GRAPHICSOPTIONS_FRAMEL, GRAPHICSOPTIONS_FRAMER, and trap_R_RegisterShaderNoMip().
void InGame_Cache (void)
References INGAME_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by InGame_MenuInit(), and UI_Cache_f().
void Login_Cache (void)
References LOGIN_FRAME, and trap_R_RegisterShaderNoMip().
void MainMenu_Cache (void)
References mainmenu_t::bannerModel, MAIN_BANNER_MODEL, and trap_R_RegisterModel().
sfxHandle_t Menu_ActivateItem (menuframework_s * s, menucommon_s * item)
References menucommon_s::callback, menucommon_s::flags, menu_move_sound, QM_ACTIVATED, and QMF_SILENT.
void Menu_AddItem (menuframework_s * menu, void * item)
References Action_Init(), Bitmap_Init(), BText_Init(), menucommon_s::flags, _tag_menuframework::items, MAX_MENUITEMS, MenuField_Init(), MTYPE_ACTION, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, MTYPE_TEXT, _tag_menuframework::nitems, PText_Init(), QMF_HASMOUSEFOCUS, QMF_NODEFAULTINIT, RadioButton_Init(), ScrollList_Init(), Slider_Init(), SpinControl_Init(), Text_Init(), trap_Error(), menucommon_s::type, and va().
void Menu_AdjustCursor (menuframework_s * menu, int dir)
References _tag_menuframework::cursor, _tag_menuframework::cursor_prev, menucommon_s::flags, if(), _tag_menuframework::items, _tag_menuframework::nitems, NULL, qfalse, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, qtrue, and _tag_menuframework::wrapAround.
void Menu_Cache (void)
References uiStatic_t::charset, uiStatic_t::charsetProp, uiStatic_t::charsetPropB, uiStatic_t::charsetPropGlow, uiStatic_t::cursor, uiStatic_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, menu_buzz_sound, menu_in_sound, menu_move_sound, menu_null_sound, menu_out_sound, uiStatic_t::menuBackNoLogoShader, uiStatic_t::menuBackShader, qfalse, uiStatic_t::rb_off, uiStatic_t::rb_on, sliderBar, sliderButton_0, sliderButton_1, trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), uis, weaponChangeSound, and uiStatic_t::whiteShader.
sfxHandle_t Menu_DefaultKey (menuframework_s * s, int key)
References _tag_menuframework::cursor, _tag_menuframework::cursor_prev, uiStatic_t::debug, EXEC_APPEND, menucommon_s::flags, K_AUX1, K_AUX10, K_AUX11, K_AUX12, K_AUX13, K_AUX14, K_AUX15, K_AUX16, K_AUX2, K_AUX3, K_AUX4, K_AUX5, K_AUX6, K_AUX7, K_AUX8, K_AUX9, K_DOWNARROW, K_ENTER, K_ESCAPE, K_F11, K_F12, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_MOUSE1, K_MOUSE2, K_MOUSE3, K_TAB, K_UPARROW, Menu_ActivateItem(), Menu_AdjustCursor(), Menu_CursorMoved(), Menu_ItemAtCursor(), menu_move_sound, menu_out_sound, MenuField_Key(), MTYPE_FIELD, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, _tag_menuframework::nitems, QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_MOUSEONLY, RadioButton_Key(), ScrollList_Key(), Slider_Key(), SpinControl_Key(), trap_Cmd_ExecuteText(), menucommon_s::type, UI_PopMenu(), and uis.
void Menu_Draw (menuframework_s * menu)
References Action_Draw(), Bitmap_Draw(), menucommon_s::bottom, BText_Draw(), colorWhite, colorYellow, uiStatic_t::debug, menucommon_s::flags, h, if(), _tag_menuframework::items, menucommon_s::left, Menu_ItemAtCursor(), MenuField_Draw(), MTYPE_ACTION, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, MTYPE_TEXT, _tag_menuframework::nitems, menucommon_s::ownerdraw, PText_Draw(), QMF_HASMOUSEFOCUS, QMF_HIDDEN, QMF_INACTIVE, RadioButton_Draw(), menucommon_s::right, ScrollList_Draw(), Slider_Draw(), SpinControl_Draw(), menucommon_s::statusbar, Text_Draw(), menucommon_s::top, trap_Error(), menucommon_s::type, UI_DrawRect(), uis, and va().
void Menu_Focus (menucommon_s * m)
void* Menu_ItemAtCursor (menuframework_s * m)
References _tag_menuframework::cursor, _tag_menuframework::items, _tag_menuframework::nitems, and NULL.
void Menu_SetCursor (menuframework_s * s, int cursor)
References _tag_menuframework::cursor, _tag_menuframework::cursor_prev, _tag_menuframework::items, Menu_CursorMoved(), QMF_GRAYED, and QMF_INACTIVE.
void Menu_SetCursorToItem (menuframework_s * m, void * ptr)
References _tag_menuframework::items, Menu_SetCursor(), and _tag_menuframework::nitems.
void MenuField_Draw (menufield_s * f)
References BIGCHAR_WIDTH, menucommon_s::bottom, menufield_s::field, menucommon_s::flags, menufield_s::generic, menucommon_s::left, listbar_color, Menu_ItemAtCursor(), MField_Draw(), menucommon_s::name, menucommon_s::parent, qfalse, QMF_GRAYED, QMF_SMALLFONT, qtrue, menucommon_s::right, SMALLCHAR_WIDTH, text_color_disabled, text_color_highlight, text_color_normal, menucommon_s::top, UI_BIGFONT, UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_FillRect(), UI_PULSE, UI_RIGHT, UI_SMALLFONT, menucommon_s::x, and menucommon_s::y.
void MenuField_Init (menufield_s * m)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, menucommon_s::bottom, menufield_s::field, menucommon_s::flags, menufield_s::generic, h, menucommon_s::left, MField_Clear(), menucommon_s::name, QMF_SMALLFONT, menucommon_s::right, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menucommon_s::top, mfield_t::widthInChars, menucommon_s::x, and menucommon_s::y.
sfxHandle_t MenuField_Key (menufield_s * m, int * key)
References menufield_s::field, menucommon_s::flags, menufield_s::generic, K_CHAR_FLAG, K_DOWNARROW, K_ENTER, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_TAB, K_UPARROW, menu_buzz_sound, MField_CharEvent(), MField_KeyDownEvent(), Q_isalpha(), Q_islower(), Q_isupper(), QMF_LOWERCASE, QMF_NUMBERSONLY, and QMF_UPPERCASE.
void MField_CharEvent (mfield_t * edit, int ch)
References mfield_t::buffer, mfield_t::cursor, MAX_EDIT_LINE, mfield_t::maxchars, memmove(), MField_Clear(), MField_Paste(), mfield_t::scroll, trap_Key_GetOverstrikeMode(), and mfield_t::widthInChars.
void MField_Clear (mfield_t * edit)
References mfield_t::buffer, mfield_t::cursor, and mfield_t::scroll.
void MField_Draw (mfield_t * edit, int x, int y, int style, vec4_t color)
References BIGCHAR_WIDTH, mfield_t::buffer, mfield_t::cursor, GIANTCHAR_WIDTH, MAX_STRING_CHARS, mfield_t::scroll, SMALLCHAR_WIDTH, trap_Error(), trap_Key_GetOverstrikeMode(), UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_GIANTFONT, UI_PULSE, UI_RIGHT, UI_SMALLFONT, and mfield_t::widthInChars.
void MField_KeyDownEvent (mfield_t * edit, int key)
References mfield_t::buffer, mfield_t::cursor, K_CTRL, K_DEL, K_END, K_HOME, K_INS, K_KP_DEL, K_KP_END, K_KP_HOME, K_KP_INS, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_RIGHTARROW, K_SHIFT, memmove(), MField_Paste(), mfield_t::scroll, trap_Key_GetOverstrikeMode(), trap_Key_IsDown(), trap_Key_SetOverstrikeMode(), and mfield_t::widthInChars.
void PlayerModel_Cache (void)
References playermodel_t::modelnames, playermodel_t::nummodels, playermodel_artlist, PlayerModel_BuildList(), and trap_R_RegisterShaderNoMip().
void PlayerSettings_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, ART_FX_BASE, ART_FX_BLUE, ART_FX_CYAN, ART_FX_GREEN, ART_FX_RED, ART_FX_TEAL, ART_FX_WHITE, ART_FX_YELLOW, ART_MODEL0, ART_MODEL1, playersettings_t::fxBasePic, playersettings_t::fxPic, and trap_R_RegisterShaderNoMip().
void Preferences_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, preferences_t::crosshairShader, n, NUM_CROSSHAIRS, trap_R_RegisterShaderNoMip(), and va().
void RankStatus_Cache (void)
References RANKSTATUS_FRAME, and trap_R_RegisterShaderNoMip().
void ScrollList_Draw (menulist_s * l)
References menulist_s::columns, _tag_menuframework::cursor, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, menulist_s::itemnames, listbar_color, menucommon_s::menuPosition, menulist_s::numitems, menucommon_s::parent, QMF_CENTER_JUSTIFY, menulist_s::seperation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, text_color_highlight, text_color_normal, menulist_s::top, UI_CENTER, UI_DrawString(), UI_FillRect(), UI_LEFT, UI_SMALLFONT, menulist_s::width, menucommon_s::x, and menucommon_s::y.
sfxHandle_t ScrollList_Key (menulist_s * l, int key)
References menucommon_s::callback, menulist_s::columns, uiStatic_t::cursorx, uiStatic_t::cursory, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, if(), menulist_s::itemnames, K_DOWNARROW, K_END, K_HOME, K_KP_DOWNARROW, K_KP_END, K_KP_HOME, K_KP_LEFTARROW, K_KP_PGDN, K_KP_PGUP, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_PGDN, K_PGUP, K_RIGHTARROW, K_UPARROW, menu_buzz_sound, menu_move_sound, menu_null_sound, menulist_s::numitems, menulist_s::oldvalue, Q_isprint(), Q_isupper(), QM_GOTFOCUS, QMF_CENTER_JUSTIFY, QMF_HASMOUSEFOCUS, menulist_s::seperation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menulist_s::top, UI_CursorInRect(), uis, menulist_s::width, menucommon_s::x, and menucommon_s::y.
void ServerInfo_Cache (void)
References serverinfo_artlist, and trap_R_RegisterShaderNoMip().
void ServerOptions_Cache (void)
References GAMESERVER_BACK0, GAMESERVER_BACK1, GAMESERVER_FIGHT0, GAMESERVER_FIGHT1, GAMESERVER_SELECT, GAMESERVER_UNKNOWNMAP, and trap_R_RegisterShaderNoMip().
void Signup_Cache (void)
References SIGNUP_FRAME, and trap_R_RegisterShaderNoMip().
void SpecifyLeague_Cache (void)
References specifyleague_artlist, and trap_R_RegisterShaderNoMip().
void SpecifyServer_Cache (void)
References specifyserver_artlist, and trap_R_RegisterShaderNoMip().
void StartServer_Cache (void)
References Com_sprintf(), GAMESERVER_ARROWS, GAMESERVER_ARROWSL, GAMESERVER_ARROWSR, GAMESERVER_BACK0, GAMESERVER_BACK1, GAMESERVER_FRAMEL, GAMESERVER_FRAMER, GAMESERVER_NEXT0, GAMESERVER_NEXT1, GAMESERVER_SELECT, GAMESERVER_SELECTED, GAMESERVER_UNKNOWNMAP, info, Info_ValueForKey(), MAX_NAMELENGTH, Q_strncpyz(), Q_strupr(), trap_Cvar_VariableValue(), trap_R_RegisterShaderNoMip(), UI_GetArenaInfoByNumber(), and UI_GetNumArenas().
void TeamMain_Cache (void)
References TEAMMAIN_FRAME, and trap_R_RegisterShaderNoMip().
int trap_Argc (void)
References CG_ARGC, G_ARGC, and UI_ARGC.
void trap_Argv (int n, char * buffer, int bufferLength)
References CG_ARGV, G_ARGV, and UI_ARGV.
void trap_CIN_DrawCinematic (int handle)
References CG_CIN_DRAWCINEMATIC, and UI_CIN_DRAWCINEMATIC.
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
References CG_CIN_PLAYCINEMATIC, and UI_CIN_PLAYCINEMATIC.
e_status trap_CIN_RunCinematic (int handle)
References CG_CIN_RUNCINEMATIC, and UI_CIN_RUNCINEMATIC.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
References CG_CIN_SETEXTENTS, and UI_CIN_SETEXTENTS.
e_status trap_CIN_StopCinematic (int handle)
References CG_CIN_STOPCINEMATIC, and UI_CIN_STOPCINEMATIC.
int trap_CM_LerpTag (orientation_t * tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char * tagName)
References PASSFLOAT(), and UI_CM_LERPTAG.
void trap_Cmd_ExecuteText (int exec_when, const char * text)
References UI_CMD_EXECUTETEXT.
void trap_Cvar_Create (const char * var_name, const char * var_value, int flags)
References UI_CVAR_CREATE.
void trap_Cvar_InfoStringBuffer (int bit, char * buffer, int bufsize)
References UI_CVAR_INFOSTRINGBUFFER.
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
References CG_CVAR_REGISTER, G_CVAR_REGISTER, and UI_CVAR_REGISTER.
void trap_Cvar_Reset (const char * name)
References UI_CVAR_RESET.
void trap_Cvar_Set (const char * var_name, const char * value)
References CG_CVAR_SET, G_CVAR_SET, and UI_CVAR_SET.
void trap_Cvar_SetValue (const char * var_name, float value)
References PASSFLOAT(), and UI_CVAR_SETVALUE.
void trap_Cvar_Update (vmCvar_t * vmCvar)
References CG_CVAR_UPDATE, G_CVAR_UPDATE, and UI_CVAR_UPDATE.
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
References CG_CVAR_VARIABLESTRINGBUFFER, G_CVAR_VARIABLE_STRING_BUFFER, and UI_CVAR_VARIABLESTRINGBUFFER.
float trap_Cvar_VariableValue (const char * var_name)
References floatint_t::f, floatint_t::i, trap_Cvar_VariableStringBuffer(), and UI_CVAR_VARIABLEVALUE.
Referenced by _UI_Init(), ArenaServers_MaxPing(), ArenaServers_MenuInit(), ArenaServers_StartRefresh(), Controls_InitCvars(), Controls_SetConfig(), Demos_MenuInit(), G_AddRandomBot(), G_SpawnBots(), GraphicsOptions_SetMenuItems(), InGame_MenuInit(), PlayerModel_BuildList(), PlayerSettings_SetMenuItems(), Preferences_SetMenuItems(), Punkbuster_ConfirmDisable(), Punkbuster_ConfirmEnable(), Rankings_MenuInit(), ServerOptions_MenuInit(), ServerOptions_SetMenuItems(), Signup_MenuInit(), StartServer_Cache(), UI_AddBotsMenu_Init(), UI_BotName_HandleKey(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_DisplayDownloadInfo(), UI_DisplayOptionsMenu_Init(), UI_DrawBotName(), UI_DrawHandicap(), UI_DrawPlayerModel(), UI_DrawSkill(), UI_DrawTeamMember(), UI_DrawTier(), UI_DrawTierGameType(), UI_DrawTierMap(), UI_DrawTierMapName(), UI_Handicap_HandleKey(), UI_LoadBestScores(), UI_LoadDemos(), UI_NetworkOptionsMenu_Init(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_PlayerInfo_SetInfo(), UI_RankStatusMenu(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_ServerInfoMenu(), UI_SetBestScore(), UI_SetupMenu_Init(), UI_Skill_HandleKey(), UI_SoundOptionsMenu_Init(), UI_SPArena_Start(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_Cache(), UI_SPPostgameMenu_MenuDraw(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_SkillEvent(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_StopServerRefresh(), UI_TeamMember_HandleKey(), and UI_Update().
void trap_Error (const char * string)
References CG_ERROR, G_ERROR, and UI_ERROR.
void trap_FS_FCloseFile (fileHandle_t f)
References CG_FS_FCLOSEFILE, G_FS_FCLOSE_FILE, and UI_FS_FCLOSEFILE.
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
References CG_FS_FOPENFILE, G_FS_FOPEN_FILE, and UI_FS_FOPENFILE.
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
References G_FS_GETFILELIST, and UI_FS_GETFILELIST.
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
References CG_FS_READ, G_FS_READ, and UI_FS_READ.
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
References CG_FS_SEEK, G_FS_SEEK, and UI_FS_SEEK.
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
References CG_FS_WRITE, G_FS_WRITE, and UI_FS_WRITE.
void trap_GetCDKey (char * buf, int buflen)
References UI_GET_CDKEY.
void trap_GetClientState (uiClientState_t * state)
References UI_GETCLIENTSTATE.
void trap_GetClipboardData (char * buf, int bufsize)
References UI_GETCLIPBOARDDATA.
int trap_GetConfigString (int index, char * buff, int buffsize)
References UI_GETCONFIGSTRING.
void trap_GetGlconfig (glconfig_t * glconfig)
References CG_GETGLCONFIG, and UI_GETGLCONFIG.
void trap_Key_ClearStates (void)
References UI_KEY_CLEARSTATES.
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
References UI_KEY_GETBINDINGBUF.
int trap_Key_GetCatcher (void)
References CG_KEY_GETCATCHER, and UI_KEY_GETCATCHER.
qboolean trap_Key_GetOverstrikeMode (void)
References UI_KEY_GETOVERSTRIKEMODE.
qboolean trap_Key_IsDown (int keynum)
References CG_KEY_ISDOWN, and UI_KEY_ISDOWN.
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
References UI_KEY_KEYNUMTOSTRINGBUF.
void trap_Key_SetBinding (int keynum, const char * binding)
References UI_KEY_SETBINDING.
void trap_Key_SetCatcher (int catcher)
References CG_KEY_SETCATCHER, and UI_KEY_SETCATCHER.
void trap_Key_SetOverstrikeMode (qboolean state)
References UI_KEY_SETOVERSTRIKEMODE.
int trap_LAN_AddServer (int source, const char * name, const char * addr)
References UI_LAN_ADDSERVER.
Referenced by UI_RunMenuScript().
void trap_LAN_ClearPing (int n)
References UI_LAN_CLEARPING.
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
References UI_LAN_COMPARESERVERS.
Referenced by UI_BinaryServerInsertion(), and UI_ServersQsortCompare().
void trap_LAN_GetPing (int n, char * buf, int buflen, int * pingtime)
References UI_LAN_GETPING.
void trap_LAN_GetPingInfo (int n, char * buf, int buflen)
References UI_LAN_GETPINGINFO.
int trap_LAN_GetPingQueueCount (void)
References UI_LAN_GETPINGQUEUECOUNT.
void trap_LAN_GetServerAddressString (int source, int n, char * buf, int buflen)
References UI_LAN_GETSERVERADDRESSSTRING.
int trap_LAN_GetServerCount (int source)
References UI_LAN_GETSERVERCOUNT.
void trap_LAN_GetServerInfo (int source, int n, char * buf, int buflen)
References UI_LAN_GETSERVERINFO.
int trap_LAN_GetServerPing (int source, int n)
References UI_LAN_GETSERVERPING.
Referenced by UI_BuildServerDisplayList().
void trap_LAN_LoadCachedServers (void)
References UI_LAN_LOADCACHEDSERVERS.
Referenced by _UI_Init().
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
References UI_LAN_MARKSERVERVISIBLE.
Referenced by UI_BuildServerDisplayList(), and UI_StartServerRefresh().
void trap_LAN_RemoveServer (int source, const char * addr)
References UI_LAN_REMOVESERVER.
Referenced by UI_RunMenuScript().
void trap_LAN_ResetPings (int n)
References UI_LAN_RESETPINGS.
Referenced by UI_StartServerRefresh(), and UI_UpdatePendingPings().
void trap_LAN_SaveCachedServers (void)
References UI_LAN_SAVECACHEDSERVERS.
Referenced by _UI_Shutdown().
int trap_LAN_ServerIsVisible (int source, int n)
References UI_LAN_SERVERISVISIBLE.
Referenced by UI_BuildServerDisplayList().
int trap_LAN_ServerStatus (const char * serverAddress, char * serverStatus, int maxLen)
References UI_LAN_SERVERSTATUS.
qboolean trap_LAN_UpdateVisiblePings (int source)
References UI_LAN_UPDATEVISIBLEPINGS.
Referenced by UI_DoServerRefresh().
int trap_MemoryRemaining (void)
References CG_MEMORY_REMAINING, and UI_MEMORY_REMAINING.
int trap_Milliseconds (void)
References CG_MILLISECONDS, G_MILLISECONDS, and UI_MILLISECONDS.
void trap_Print (const char * string)
References CG_PRINT, and UI_PRINT.
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
References CG_R_ADDLIGHTTOSCENE, PASSFLOAT(), and UI_R_ADDLIGHTTOSCENE.
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
References CG_R_ADDPOLYTOSCENE, and UI_R_ADDPOLYTOSCENE.
void trap_R_AddRefEntityToScene (const refEntity_t * re)
References CG_R_ADDREFENTITYTOSCENE, and UI_R_ADDREFENTITYTOSCENE.
void trap_R_ClearScene (void)
References CG_R_CLEARSCENE, and UI_R_CLEARSCENE.
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
References CG_R_DRAWSTRETCHPIC, PASSFLOAT(), and UI_R_DRAWSTRETCHPIC.
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
References CG_R_MODELBOUNDS, and UI_R_MODELBOUNDS.
void trap_R_RegisterFont (const char * pFontname, int pointSize, fontInfo_t * font)
References CG_R_REGISTERFONT, and UI_R_REGISTERFONT.
qhandle_t trap_R_RegisterModel (const char * name)
References CG_R_REGISTERMODEL, and UI_R_REGISTERMODEL.
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
References CG_R_REGISTERSHADERNOMIP, and UI_R_REGISTERSHADERNOMIP.
qhandle_t trap_R_RegisterSkin (const char * name)
References CG_R_REGISTERSKIN, and UI_R_REGISTERSKIN.
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
References CG_R_REMAP_SHADER, and UI_R_REMAP_SHADER.
void trap_R_RenderScene (const refdef_t * fd)
References CG_R_RENDERSCENE, and UI_R_RENDERSCENE.
void trap_R_SetColor (const float * rgba)
References CG_R_SETCOLOR, and UI_R_SETCOLOR.
int trap_RealTime (qtime_t * qtime)
References CG_REAL_TIME, G_REAL_TIME, and UI_REAL_TIME.
Referenced by UI_StartServerRefresh().
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
References CG_S_REGISTERSOUND, and UI_S_REGISTERSOUND.
void trap_S_StartBackgroundTrack (const char * intro, const char * loop)
References CG_S_STARTBACKGROUNDTRACK, and UI_S_STARTBACKGROUNDTRACK.
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
References CG_S_STARTLOCALSOUND, and UI_S_STARTLOCALSOUND.
void trap_S_StopBackgroundTrack (void)
References CG_S_STOPBACKGROUNDTRACK, and UI_S_STOPBACKGROUNDTRACK.
void trap_SetCDKey (char * buf)
References UI_SET_CDKEY.
void trap_SetPbClStatus (int status)
References UI_SET_PBCLSTATUS.
void trap_UpdateScreen (void)
References CG_UPDATESCREEN, and UI_UPDATESCREEN.
qboolean trap_VerifyCDKey (const char * key, const char * chksum)
References UI_VERIFY_CDKEY.
void UI_AddBots_Cache (void)
References ART_ARROWDOWN, ART_ARROWS, ART_ARROWUP, ART_BACK0, ART_BACK1, ART_BACKGROUND, ART_FIGHT0, ART_FIGHT1, and trap_R_RegisterShaderNoMip().
Referenced by UI_AddBotsMenu_Init(), and UI_Cache_f().
void UI_AddBotsMenu (void)
References addBotsMenuInfo_t::menu, UI_AddBotsMenu_Init(), and UI_PushMenu().
Referenced by InGame_Event().
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
References displayContextDef_t::bias, uiStatic_t::bias, uiInfo_t::uiDC, uiInfo, displayContextDef_t::xscale, uiStatic_t::xscale, displayContextDef_t::yscale, and uiStatic_t::yscale.
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), Main_MenuDraw(), Text_PaintChar(), UI_DrawHandlePic(), UI_DrawNamedPic(), UI_DrawPlayer(), UI_DrawRect(), UI_DrawSides(), UI_DrawTopBottom(), and UI_FillRect().
int UI_AdjustTimeByGame (int time)
void UI_ArenaServersMenu (void)
References ArenaServers_MenuInit(), arenaservers_t::menu, and UI_PushMenu().
char* UI_Argv (int arg)
References buffer, MAX_STRING_CHARS, and trap_Argv().
Referenced by UI_CalcPostGameStats(), UI_CinematicsMenu_f(), UI_ConsoleCommand(), and UI_SPPostgameMenu_f().
void UI_BotSelectMenu (char * bot)
References botSelectInfo_t::menu, UI_BotSelectMenu_Init(), and UI_PushMenu().
void UI_BotSelectMenu_Cache (void)
References BOTSELECT_ACCEPT0, BOTSELECT_ACCEPT1, BOTSELECT_ARROWS, BOTSELECT_ARROWSL, BOTSELECT_ARROWSR, BOTSELECT_BACK0, BOTSELECT_BACK1, BOTSELECT_SELECT, BOTSELECT_SELECTED, and trap_R_RegisterShaderNoMip().
qboolean UI_CanShowTierVideo (int tier)
References Com_sprintf(), uiStatic_t::demoversion, Info_ValueForKey(), MAX_INFO_VALUE, qfalse, qtrue, trap_Cvar_VariableStringBuffer(), and uis.
Referenced by UI_CinematicsMenu_Init().
void UI_CDKeyMenu (void)
References cdkeyMenuInfo_t::menu, UI_CDKeyMenu_Init(), and UI_PushMenu().
Referenced by UI_CDKeyMenu_f(), UI_MainMenu(), and UI_SetupMenu_Event().
void UI_CDKeyMenu_Cache (void)
References ART_ACCEPT0, ART_ACCEPT1, ART_BACK0, ART_BACK1, ART_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_CDKeyMenu_Init().
void UI_CDKeyMenu_f (void)
References UI_CDKeyMenu().
Referenced by UI_ConsoleCommand().
void UI_CinematicsMenu (void)
References cinematicsMenuInfo_t::menu, UI_CinematicsMenu_Init(), and UI_PushMenu().
Referenced by Main_MenuEvent(), and UI_CinematicsMenu_f().
void UI_CinematicsMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_CinematicsMenu_Init().
void UI_CinematicsMenu_f (void)
References _tag_menuframework::items, cinematicsMenuInfo_t::menu, Menu_SetCursorToItem(), n, UI_Argv(), and UI_CinematicsMenu().
Referenced by UI_ConsoleCommand().
float UI_ClampCvar (float min, float max, float value)
References value().
Referenced by Controls_GetConfig().
void UI_ClearScores (void)
References count, FS_WRITE, qfalse, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_GetFileList(), trap_FS_Write(), UI_SetBestScores(), and va().
Referenced by UI_RunMenuScript().
void UI_ConfirmMenu (const char * question, void(*)(void) draw, void(*)(qboolean result) action)
References UI_CENTER, UI_ConfirmMenu_Style(), and UI_INVERSE.
Referenced by Controls_MenuEvent(), InGame_Event(), Main_MenuEvent(), UI_SetActiveMenu(), UI_SetupMenu_Event(), and UI_SPLevelMenu_ResetEvent().
qboolean UI_ConsoleCommand (int realTime)
References displayContextDef_t::frameTime, uiStatic_t::frametime, MAX_QPATH, Menu_Cache(), Q_stricmp(), Q_strncpyz(), qfalse, qtrue, displayContextDef_t::realTime, uiStatic_t::realtime, trap_Argc(), trap_R_RemapShader(), UI_Argv(), UI_Cache_f(), UI_CalcPostGameStats(), UI_CDKeyMenu_f(), UI_CinematicsMenu_f(), UI_Load(), UI_Report(), UI_ShowPostGame(), UI_SPLevelMenu_f(), UI_SPPostgameMenu_f(), UI_SPUnlock_f(), UI_SPUnlockMedals_f(), UI_TeamOrdersMenu_f(), uiInfo_t::uiDC, and uiInfo.
Referenced by vmMain().
void UI_ControlsMenu (void)
References Controls_MenuInit(), controls_t::menu, and UI_PushMenu().
Referenced by UI_SetupMenu_Event().
void UI_CreditMenu (void)
References _tag_menuframework::draw, _tag_menuframework::fullscreen, _tag_menuframework::key, creditsmenu_t::menu, qtrue, UI_CreditMenu_Draw(), UI_CreditMenu_Key(), and UI_PushMenu().
Referenced by InGame_QuitAction(), and MainMenu_ExitAction().
qboolean UI_CursorInRect (int x, int y, int width, int height)
References displayContextDef_t::cursorx, uiStatic_t::cursorx, displayContextDef_t::cursory, uiStatic_t::cursory, qfalse, qtrue, uiInfo_t::uiDC, and uiInfo.
Referenced by ScrollList_Key(), and UI_TeamOrdersMenu_Key().
char* UI_Cvar_VariableString (const char * var_name)
References buffer, MAX_STRING_CHARS, and trap_Cvar_VariableStringBuffer().
Referenced by _UI_Init(), Controls_InitModel(), GraphicsOptions_GetResolutions(), GraphicsOptions_SetMenuItems(), PlayerSettings_SetMenuItems(), ServerOptions_SetMenuItems(), SpecifyLeague_MenuInit(), UI_CalcPostGameStats(), UI_ClanName_HandleKey(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawClanName(), UI_DrawOpponent(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawOpponentName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawPlayerModel(), UI_DrawSelectedPlayer(), UI_DrawServerRefreshDate(), UI_DrawTeamName(), UI_HeadCountByTeam(), UI_Load(), UI_LoadNonIngame(), UI_NextOpponent(), UI_OpponentLeaderName(), UI_OwnerDrawWidth(), UI_PriorOpponent(), UI_RunMenuScript(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_StopCinematic(), UI_TeamName_HandleKey(), and UI_Update().
void UI_DemosMenu (void)
References Demos_MenuInit(), demos_t::menu, and UI_PushMenu().
Referenced by Main_MenuEvent().
void UI_DisplayOptionsMenu (void)
References displayOptionsInfo_t::display, displayOptionsInfo_t::menu, Menu_SetCursorToItem(), UI_DisplayOptionsMenu_Init(), and UI_PushMenu().
Referenced by GraphicsOptions_Event(), Options_Event(), UI_NetworkOptionsMenu_Event(), and UI_SoundOptionsMenu_Event().
void UI_DisplayOptionsMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_DisplayOptionsMenu_Init().
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
References PROPB_GAP_WIDTH, PROPB_SPACE_WIDTH, propMapB, s, UI_CENTER, UI_DrawBannerString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_LEFT, UI_RIGHT, and width.
Referenced by BText_Draw(), and UI_AddBotsMenu_Draw().
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
References UI_DrawString().
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), MField_Draw(), PlayerName_Draw(), PlayerSettings_DrawName(), RadioButton_Draw(), Rankings_DrawText(), SpinControl_Draw(), and UI_CDKeyMenu_DrawKey().
void UI_DrawConnectScreen (qboolean overlay)
References mfield_t::buffer, CA_CHALLENGING, CA_CONNECTED, CA_CONNECTING, CA_LOADING, CA_PRIMED, menucommon_s::callback, color_white, colorWhite, uiClientState_t::connectPacketCount, uiClientState_t::connState, CS_SERVERINFO, Cvar_VariableString(), menufield_s::field, Field_Clear(), menufield_s::generic, info, Info_ValueForKey(), ITEM_TEXTSTYLE_SHADOWEDMORE, lastConnState, lastLoadingText, MAX_INFO_VALUE, Menu_AddItem(), Menu_Cache(), Menu_Paint(), menu_text_color, uiStatic_t::menuBackShader, Menus_FindByName(), uiClientState_t::messageString, MField_Draw(), MTYPE_FIELD, menucommon_s::name, passwordNeeded, Q_stricmp(), Q_strncpyz(), qtrue, s, SCREEN_HEIGHT, SCREEN_WIDTH, uiClientState_t::servername, Text_PaintCenter(), Text_PaintCenter_AutoWrapped(), trap_Cvar_VariableStringBuffer(), trap_GetClientState(), trap_GetConfigString(), menucommon_s::type, UI_BIGFONT, UI_CENTER, UI_DisplayDownloadInfo(), UI_DrawHandlePic(), UI_DrawProportionalString(), UI_DrawProportionalString_AutoWrapped(), UI_DROPSHADOW, UI_SetColor(), UI_SMALLFONT, uis, uiClientState_t::updateInfoString, va(), mfield_t::widthInChars, menucommon_s::x, and menucommon_s::y.
Referenced by vmMain().
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
References h, trap_R_DrawStretchPic(), and UI_AdjustFrom640().
Referenced by _UI_Init(), _UI_Refresh(), Bitmap_Draw(), Crosshair_Draw(), PlayerSettings_DrawEffects(), RadioButton_Draw(), Slider_Draw(), StartServer_LevelshotDraw(), UI_DrawCenteredPic(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawConnectScreen(), UI_DrawCrosshair(), UI_DrawEffects(), UI_DrawMapPreview(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawTierMap(), UI_Refresh(), and UI_SPLevelMenu_MenuDraw().
void UI_DrawNamedPic (float x, float y, float width, float height, const char * picname)
References trap_R_DrawStretchPic(), trap_R_RegisterShaderNoMip(), and UI_AdjustFrom640().
Referenced by ConfirmMenu_Draw(), MessageMenu_Draw(), Reset_MenuDraw(), UI_AddBotsMenu_Draw(), and UI_SPPostgameMenu_DrawAwardsMedals().
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t * pi, int time)
References AnglesToAxis(), playerInfo_t::animations, refEntity_t::axis, AxisClear(), refEntity_t::backlerp, playerInfo_t::barrelModel, Byte4Copy, playerInfo_t::c1RGBA, CHAN_LOCAL, playerInfo_t::chat, colorWhite, playerInfo_t::currentWeapon, refEntity_t::customSkin, DEG2RAD, dp_realtime, playerInfo_t::flashDlightColor, playerInfo_t::flashModel, refdef_t::fov_x, refdef_t::fov_y, refEntity_t::frame, h, head, playerInfo_t::headModel, playerInfo_t::headSkin, refdef_t::height, refEntity_t::hModel, int(), jumpHeight, playerInfo_t::lastWeapon, playerInfo_t::legsModel, playerInfo_t::legsSkin, refEntity_t::lightingOrigin, M_PI, animation_s::numFrames, refEntity_t::oldframe, refEntity_t::oldorigin, refEntity_t::origin, playerInfo_t::pendingWeapon, PITCH, RDF_NOWORLDMODEL, refdef_t::rdflags, playerInfo_t::realWeapon, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, ROLL, refEntity_t::shaderRGBA, refdef_t::time, playerInfo_t::torsoModel, playerInfo_t::torsoSkin, trap_R_AddLightToScene(), trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RegisterShaderNoMip(), trap_R_RenderScene(), trap_S_StartLocalSound(), UI_AdjustFrom640(), UI_MachinegunSpinAngle(), UI_PlayerAngles(), UI_PlayerAnimation(), UI_PlayerFloatSprite(), UI_PositionEntityOnTag(), UI_PositionRotatedEntityOnTag(), VectorCopy, refdef_t::viewaxis, playerInfo_t::weapon, weaponChangeSound, playerInfo_t::weaponModel, playerInfo_t::weaponTimer, refdef_t::width, WP_BFG, WP_GAUNTLET, WP_MACHINEGUN, WP_NONE, WP_RAILGUN, refdef_t::x, xx, refdef_t::y, and YAW.
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
References cg, cgs, uiStatic_t::charsetProp, cgMedia_t::charsetProp, uiStatic_t::charsetPropGlow, cgMedia_t::charsetPropGlow, cgs_t::media, PULSE_DIVISOR, uiStatic_t::realtime, cg_t::time, UI_CENTER, UI_DrawProportionalString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_INVERSE, UI_LEFT, UI_ProportionalSizeScale(), UI_ProportionalStringWidth(), UI_PULSE, UI_RIGHT, and width.
Referenced by CG_DrawInformation(), ConfirmMenu_Draw(), Controls_ResetDefaults_Draw(), Main_MenuDraw(), MessageMenu_Draw(), PlayerModel_DrawPlayer(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), PText_Draw(), Reset_MenuDraw(), Setup_ResetDefaults_Draw(), UI_CDKeyMenu_DrawKey(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), UI_DrawProportionalString_AutoWrapped(), UI_SaveConfigMenu_SavenameDraw(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_ResetDraw(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_MenuDraw(), and UI_TeamOrdersMenu_ListDraw().
void UI_DrawRect (float x, float y, float width, float height, const float * color)
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), UI_DrawSides(), UI_DrawTopBottom(), and uiStatic_t::whiteShader.
Referenced by Menu_Draw(), and UI_DrawTextBox().
void UI_DrawSides (float x, float y, float w, float h)
References trap_R_DrawStretchPic(), UI_AdjustFrom640(), uiInfo_t::uiDC, uiInfo, and displayContextDef_t::whiteShader.
Referenced by UI_DrawRect().
void UI_DrawString (int x, int y, const char * str, int style, vec4_t color)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, BLINK_DIVISOR, GIANTCHAR_HEIGHT, GIANTCHAR_WIDTH, PULSE_DIVISOR, uiStatic_t::realtime, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, UI_BLINK, UI_CENTER, UI_DrawString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_GIANTFONT, UI_LerpColor(), UI_PULSE, UI_RIGHT, and UI_SMALLFONT.
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Controls_StatusBar(), Crosshair_Draw(), DriverInfo_MenuDraw(), Main_MenuDraw(), MenuField_Draw(), MField_Draw(), PlayerName_Draw(), RadioButton_Draw(), ScrollList_Draw(), ServerInfo_MenuDraw(), ServerOptions_LevelshotDraw(), ServerOptions_StatusBar(), Slider_Draw(), SpinControl_Draw(), StartServer_LevelshotDraw(), Text_Draw(), UI_CDKeyMenu_DrawKey(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DrawChar(), UI_Refresh(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_DrawAwardsMedals(), and UI_SPPostgameMenu_MenuDrawScoreLine().
void UI_DrawTextBox (int x, int y, int width, int lines)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, colorBlack, colorWhite, UI_DrawRect(), and UI_FillRect().
void UI_DrawTopBottom (float x, float y, float w, float h)
References trap_R_DrawStretchPic(), UI_AdjustFrom640(), uiInfo_t::uiDC, uiInfo, and displayContextDef_t::whiteShader.
Referenced by UI_DrawRect().
void UI_FillRect (float x, float y, float width, float height, const float * color)
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), uiInfo_t::uiDC, uiInfo, displayContextDef_t::whiteShader, and uiStatic_t::whiteShader.
Referenced by _UI_Init(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), RadioButton_Draw(), ScrollList_Draw(), ServerOptions_LevelshotDraw(), SpinControl_Draw(), StartServer_LevelshotDraw(), UI_CDKeyMenu_DrawKey(), UI_DrawTextBox(), UI_SaveConfigMenu_SavenameDraw(), and UI_SPLevelMenu_MenuDraw().
void UI_ForceMenuOff (void)
References uiStatic_t::activemenu, KEYCATCH_UI, uiStatic_t::menusp, NULL, trap_Cvar_Set(), trap_Key_ClearStates(), trap_Key_GetCatcher(), and trap_Key_SetCatcher().
Referenced by Demos_MenuEvent(), Login_MenuEvent(), Rankings_MenuEvent(), Signup_MenuEvent(), TeamMain_MenuEvent(), UI_PopMenu(), UI_RankStatusMenu(), UI_SetActiveMenu(), and UI_SoundOptionsMenu_Event().
const char* UI_GetArenaInfoByMap (const char * map)
References Info_ValueForKey(), n, NULL, Q_stricmp(), ui_arenaInfos, and ui_numArenas.
Referenced by ServerOptions_InitBotNames(), and UI_SPPostgameMenu_f().
const char* UI_GetArenaInfoByNumber (int num)
References Info_ValueForKey(), n, NULL, S_COLOR_RED, trap_Print(), ui_arenaInfos, ui_numArenas, va(), and value().
Referenced by ServerOptions_SetMenuItems(), ServerOptions_Start(), StartServer_Cache(), StartServer_GametypeEvent(), StartServer_LevelshotDraw(), StartServer_Update(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_SetMenuItems(), and UI_SPPostgameMenu_NextEvent().
int UI_GetAwardLevel (int award)
References Com_sprintf(), Info_ValueForKey(), MAX_INFO_VALUE, and trap_Cvar_VariableStringBuffer().
Referenced by UI_SPLevelMenu_Init(), and UI_SPPostgameMenu_f().
void UI_GetBestScore (int level, int * score, int * skill)
References Com_sprintf(), Info_ValueForKey(), MAX_INFO_VALUE, n, trap_Cvar_VariableStringBuffer(), ui_numArenas, and va().
Referenced by UI_GetCurrentGame(), UI_SPLevelMenu_SetMenuArena(), and UI_TierCompleted().
char* UI_GetBotInfoByName (const char * name)
References Info_ValueForKey(), n, NULL, Q_stricmp(), ui_botInfos, ui_numBots, and value().
Referenced by ServerOptions_InitBotNames(), and UI_SPLevelMenu_SetBots().
char* UI_GetBotInfoByNumber (int num)
References NULL, S_COLOR_RED, trap_Print(), ui_botInfos, ui_numBots, and va().
Referenced by ServerOptions_InitBotNames(), UI_AddBotsMenu_SetBotNames(), UI_AddBotsMenu_SortCompare(), UI_BotSelectMenu_Default(), UI_BotSelectMenu_SortCompare(), UI_BotSelectMenu_UpdateGrid(), UI_GetBotNameByNumber(), and UI_SPLevelMenu_SetBots().
char* UI_GetBotNameByNumber (int num)
References info, Info_ValueForKey(), and UI_GetBotInfoByNumber().
Referenced by UI_DrawBotName(), UI_DrawTeamMember(), and UI_RunMenuScript().
int UI_GetCurrentGame (void)
References info, Info_ValueForKey(), level, UI_GetBestScore(), UI_GetSpecialArenaInfo(), and ui_numSinglePlayerArenas.
Referenced by UI_SPLevelMenu(), and UI_SPPostgameMenu_NextEvent().
int UI_GetNumArenas (void)
References ui_numArenas.
Referenced by StartServer_Cache(), and StartServer_GametypeEvent().
int UI_GetNumBots (void)
References ui_numBots.
Referenced by UI_AddBotsMenu_Init(), UI_BotName_HandleKey(), UI_BotSelectMenu_BuildList(), UI_DrawBotName(), UI_DrawTeamMember(), and UI_TeamMember_HandleKey().
int UI_GetNumSPArenas (void)
References ui_numSinglePlayerArenas.
Referenced by UI_SPLevelMenu().
int UI_GetNumSPTiers (void)
References ARENAS_PER_TIER, and ui_numSinglePlayerArenas.
Referenced by UI_SPArena_Start(), UI_SPLevelMenu(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_NextEvent(), and UI_TierCompleted().
const char* UI_GetSpecialArenaInfo (const char * tag)
References Info_ValueForKey(), n, NULL, Q_stricmp(), ui_arenaInfos, and ui_numArenas.
Referenced by UI_GetCurrentGame(), UI_SPLevelMenu(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_f(), and UI_TierCompleted().
void UI_GraphicsOptionsMenu (void)
References graphicsoptions_t::graphics, GraphicsOptions_MenuInit(), graphicsoptions_t::menu, Menu_SetCursorToItem(), and UI_PushMenu().
void UI_InGameMenu (void)
References uiStatic_t::cursorx, uiStatic_t::cursory, InGame_MenuInit(), ingamemenu_t::menu, uiStatic_t::menusp, UI_PushMenu(), and uis.
Referenced by UI_SetActiveMenu().
void UI_Init (void)
References uiStatic_t::activemenu, uiStatic_t::bias, uiStatic_t::glconfig, Menu_Cache(), uiStatic_t::menusp, NULL, trap_GetGlconfig(), UI_InitGameinfo(), UI_RegisterCvars(), glconfig_t::vidHeight, glconfig_t::vidWidth, uiStatic_t::xscale, and uiStatic_t::yscale.
Referenced by vmMain().
void UI_InitGameinfo (void)
References uiStatic_t::demoversion, qfalse, UI_InitMemory(), UI_LoadArenas(), UI_LoadBots(), and uis.
Referenced by UI_Init().
qboolean UI_IsFullscreen (void)
References uiStatic_t::activemenu, _tag_menuframework::fullscreen, KEYCATCH_UI, qfalse, and trap_Key_GetCatcher().
Referenced by vmMain().
void UI_KeyEvent (int key)
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Referenced by UI_DrawString().
void UI_Load (void)
References Menu_GetFocused(), Menus_ActivateByName(), Menus_CloseAll(), windowDef_t::name, NULL, qtrue, String_Init(), UI_Cvar_VariableString(), UI_LoadArenas(), UI_LoadMenus(), UI_ParseGameInfo(), and menuDef_t::window.
Referenced by UI_ConsoleCommand().
void UI_LoadArenas (void)
References mapInfo::cinematic, CVAR_INIT, CVAR_ROM, GT_1FCTF, GT_CTF, GT_FFA, GT_HARVESTER, GT_OBELISK, GT_TOURNAMENT, mapInfo::imageName, Info_ValueForKey(), mapInfo::levelShot, uiInfo_t::mapCount, uiInfo_t::mapList, mapInfo::mapLoadName, mapInfo::mapName, MAX_MAPS, n, S_COLOR_YELLOW, vmCvar_t::string, String_Alloc(), trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), type(), mapInfo::typeBits, ui_arenaInfos, UI_LoadArenasFromFile(), ui_numArenas, UI_OutOfMemory(), uiInfo, and va().
void UI_LoadBestScores (const char * map, int game)
References Com_sprintf(), uiInfo_t::demoAvailable, DEMOEXT, FS_READ, MAX_QPATH, qfalse, qtrue, trap_Cvar_VariableValue(), trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), UI_SetBestScores(), and uiInfo.
Referenced by _UI_Init(), UI_FeederSelection(), UI_GameType_HandleKey(), and UI_RunMenuScript().
void UI_LoadBots (void)
References CVAR_INIT, CVAR_ROM, vmCvar_t::string, trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), UI_LoadBotsFromFile(), ui_numBots, and va().
void UI_LoadConfig_Cache (void)
References ART_ARROWLEFT, ART_ARROWRIGHT, ART_ARROWS, ART_BACK0, ART_BACK1, ART_FIGHT0, ART_FIGHT1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by LoadConfig_MenuInit().
void UI_LoadConfigMenu (void)
References LoadConfig_MenuInit(), configs_t::menu, and UI_PushMenu().
void UI_LoadMenus (const char * menuFile, qboolean reset)
References Com_Printf(), vmCvar_t::integer, Load_Menu(), Menu_Reset(), Q_stricmp(), S_COLOR_RED, S_COLOR_YELLOW, start, pc_token_s::string, token, trap_Error(), trap_Milliseconds(), trap_PC_FreeSource(), trap_PC_LoadSource(), trap_PC_ReadToken(), and va().
Referenced by _UI_Init(), UI_Load(), and UI_LoadNonIngame().
void UI_LogAwardData (int award, int data)
References AWARD_PERFECT, Com_sprintf(), Info_SetValueForKey(), Info_ValueForKey(), MAX_INFO_VALUE, S_COLOR_RED, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Print(), and va().
Referenced by UI_SPPostgameMenu_f().
void UI_LoginMenu (void)
References Login_MenuInit(), login_t::menu, and UI_PushMenu().
void UI_MainMenu (void)
References menucommon_s::callback, mainmenu_t::cinematics, menutext_s::color, color_red, mainmenu_t::demos, uiStatic_t::demoversion, _tag_menuframework::draw, errorMessage_t::errorMessage, ErrorMessage_Key(), mainmenu_t::exit, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_CINEMATICS, ID_DEMOS, ID_EXIT, ID_MODS, ID_MULTIPLAYER, ID_SETUP, ID_SINGLEPLAYER, ID_TEAMARENA, vmCvar_t::integer, _tag_menuframework::key, KEYCATCH_UI, MAIN_MENU_VERTICAL_SPACING, Main_MenuDraw(), Main_MenuEvent(), MainMenu_Cache(), mainmenu_t::menu, errorMessage_t::menu, Menu_AddItem(), uiStatic_t::menusp, mainmenu_t::mods, MTYPE_PTEXT, mainmenu_t::multiplayer, NULL, qfalse, QMF_CENTER_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, mainmenu_t::setup, _tag_menuframework::showlogo, mainmenu_t::singleplayer, menutext_s::string, menutext_s::style, mainmenu_t::teamArena, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_GetCDKey(), trap_Key_SetCatcher(), trap_VerifyCDKey(), menucommon_s::type, ui_cdkeychecked, UI_CDKeyMenu(), UI_CENTER, UI_DROPSHADOW, UI_PushMenu(), UI_TeamArenaExists(), uis, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
void UI_ModsMenu (void)
References mods_t::menu, UI_Mods_MenuInit(), and UI_PushMenu().
void UI_ModsMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_FIGHT0, ART_FIGHT1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
void UI_MouseEvent (int dx, int dy)
References uiStatic_t::activemenu, uiStatic_t::bias, menucommon_s::bottom, CHAN_LOCAL_SOUND, _tag_menuframework::cursor, _tag_menuframework::cursor_prev, uiStatic_t::cursorx, uiStatic_t::cursory, menucommon_s::flags, if(), _tag_menuframework::items, menucommon_s::left, m, menu_move_sound, Menu_SetCursor(), _tag_menuframework::nitems, QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_SILENT, menucommon_s::right, SCREEN_HEIGHT, SCREEN_WIDTH, menucommon_s::top, and trap_S_StartLocalSound().
Referenced by UI_Refresh(), and vmMain().
void UI_NetworkOptionsMenu (void)
References networkOptionsInfo_t::menu, Menu_SetCursorToItem(), networkOptionsInfo_t::network, UI_NetworkOptionsMenu_Init(), and UI_PushMenu().
void UI_NetworkOptionsMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
void UI_NewGame (void)
References trap_Cvar_Set().
Referenced by Reset_MenuEvent(), and UI_SPLevelMenu_ResetAction().
void UI_PlayerInfo_SetInfo (playerInfo_t * pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNum, qboolean chat)
References ANIM_TOGGLEBIT, BOTH_DEATH1, playerInfo_t::c1RGBA, playerInfo_t::chat, playerInfo_t::color1, playerInfo_t::currentWeapon, dp_realtime, int(), jumpHeight, playerInfo_t::lastWeapon, playerInfo_t::legs, LEGS_JUMP, LEGS_LAND, playerInfo_t::legsAnim, playerInfo_t::moveAngles, playerInfo_t::muzzleFlashTime, playerInfo_t::newModel, playerInfo_t::pendingLegsAnim, playerInfo_t::pendingTorsoAnim, playerInfo_t::pendingWeapon, qfalse, playerInfo_t::torso, TORSO_ATTACK, TORSO_ATTACK2, TORSO_DROP, TORSO_GESTURE, TORSO_RAISE, TORSO_STAND, TORSO_STAND2, playerInfo_t::torsoAnim, trap_Cvar_VariableValue(), UI_ForceLegsAnim(), UI_ForceTorsoAnim(), UI_PlayerInfo_SetWeapon(), UI_TIMER_MUZZLE_FLASH, UI_TIMER_WEAPON_DELAY, VectorClear, VectorCopy, VectorSet, playerInfo_t::viewAngles, playerInfo_t::weapon, playerInfo_t::weaponTimer, WP_GAUNTLET, WP_NONE, YAW, lerpFrame_t::yawAngle, and lerpFrame_t::yawing.
void UI_PlayerInfo_SetModel (playerInfo_t * pi, const char * model, const char * headmodel, char * teamName)
References playerInfo_t::chat, playerInfo_t::currentWeapon, playerInfo_t::lastWeapon, playerInfo_t::newModel, playerInfo_t::pendingWeapon, qfalse, qtrue, UI_PlayerInfo_SetWeapon(), UI_RegisterClientModelname(), playerInfo_t::weapon, playerInfo_t::weaponTimer, and WP_MACHINEGUN.
void UI_PlayerModelMenu (void)
References MAX_MODELSPERPAGE, playermodel_t::menu, Menu_SetCursorToItem(), playermodel_t::pics, PlayerModel_MenuInit(), playermodel_t::selectedmodel, and UI_PushMenu().
void UI_PlayerSettingsMenu (void)
References playersettings_t::menu, PlayerSettings_MenuInit(), and UI_PushMenu().
void UI_PopMenu (void)
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, uiStatic_t::firstdraw, menu_out_sound, uiStatic_t::menusp, qtrue, uiStatic_t::stack, trap_Error(), trap_S_StartLocalSound(), and UI_ForceMenuOff().
Referenced by ArenaServers_Event(), ConfirmMenu_Event(), Controls_MenuEvent(), Demos_MenuEvent(), DriverInfo_Event(), GraphicsOptions_Event(), InGame_Event(), InGame_QuitAction(), InGame_RestartAction(), LoadConfig_MenuEvent(), Login_MenuEvent(), MainMenu_ExitAction(), Menu_DefaultKey(), Options_Event(), PlayerModel_MenuEvent(), PlayerSettings_MenuEvent(), Preferences_Event(), RankStatus_MenuEvent(), Reset_MenuEvent(), ServerInfo_Event(), ServerOptions_Event(), Signup_MenuEvent(), SpecifyLeague_Event(), SpecifyServer_Event(), StartServer_MenuEvent(), UI_AddBotsMenu_BackEvent(), UI_BotSelectMenu_BackEvent(), UI_BotSelectMenu_SelectEvent(), UI_CDKeyMenu_Event(), UI_CinematicsMenu_BackEvent(), UI_DisplayOptionsMenu_Event(), UI_Mods_MenuEvent(), UI_NetworkOptionsMenu_Event(), UI_RemoveBotsMenu_BackEvent(), UI_SaveConfigMenu_BackEvent(), UI_SaveConfigMenu_SaveEvent(), UI_SetupMenu_Event(), UI_SoundOptionsMenu_Event(), UI_SPLevelMenu_BackEvent(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_ResetAction(), UI_SPPostgameMenu_AgainEvent(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuEvent(), UI_SPPostgameMenu_NextEvent(), UI_SPSkillMenu_BackEvent(), UI_TeamOrdersMenu_BackEvent(), and UI_TeamOrdersMenu_ListEvent().
void UI_PreferencesMenu (void)
References preferences_t::menu, Preferences_MenuInit(), and UI_PushMenu().
float UI_ProportionalSizeScale (int style)
References PROP_SMALL_SIZE_SCALE, and UI_SMALLFONT.
Referenced by PText_Init(), UI_DisplayDownloadInfo(), UI_DrawProportionalString(), and UI_DrawProportionalString_AutoWrapped().
int UI_ProportionalStringWidth (const char * str)
References PROP_GAP_WIDTH, propMap, s, and width.
Referenced by Prepname(), PText_Init(), UI_ConfirmMenu_Style(), UI_DisplayDownloadInfo(), UI_DrawProportionalString(), UI_DrawProportionalString_AutoWrapped(), UI_Message(), and UI_ResetMenu().
void UI_PushMenu (menuframework_s * menu)
References uiStatic_t::activemenu, _tag_menuframework::cursor, _tag_menuframework::cursor_prev, uiStatic_t::firstdraw, menucommon_s::flags, if(), _tag_menuframework::items, KEYCATCH_UI, m_entersound, MAX_MENUDEPTH, Menu_SetCursor(), uiStatic_t::menusp, _tag_menuframework::nitems, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, qtrue, uiStatic_t::stack, trap_Error(), and trap_Key_SetCatcher().
Referenced by UI_AddBotsMenu(), UI_ArenaServersMenu(), UI_BotSelectMenu(), UI_CDKeyMenu(), UI_CinematicsMenu(), UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_CreditMenu(), UI_DemosMenu(), UI_DisplayOptionsMenu(), UI_DriverInfo_Menu(), UI_GraphicsOptionsMenu(), UI_InGameMenu(), UI_LoadConfigMenu(), UI_LoginMenu(), UI_MainMenu(), UI_Message(), UI_ModsMenu(), UI_NetworkOptionsMenu(), UI_PlayerModelMenu(), UI_PlayerSettingsMenu(), UI_PreferencesMenu(), UI_RankingsMenu(), UI_RankStatusMenu(), UI_RemoveBotsMenu(), UI_ResetMenu(), UI_SaveConfigMenu(), UI_ServerInfoMenu(), UI_ServerOptionsMenu(), UI_SetupMenu(), UI_SignupMenu(), UI_SoundOptionsMenu(), UI_SpecifyLeagueMenu(), UI_SpecifyServerMenu(), UI_SPLevelMenu(), UI_SPPostgameMenu_f(), UI_SPSkillMenu(), UI_StartServerMenu(), UI_SystemConfigMenu(), UI_TeamMainMenu(), and UI_TeamOrdersMenu().
void UI_RankStatusMenu (void)
References rankstatus_t::menu, RankStatus_MenuInit(), s_rankstatus_message, s_status, trap_Cvar_VariableValue(), UI_ForceMenuOff(), and UI_PushMenu().
void UI_Refresh (int realtime)
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, colorRed, uiStatic_t::cursor, uiStatic_t::cursorx, uiStatic_t::cursory, uiStatic_t::debug, _tag_menuframework::draw, uiStatic_t::firstdraw, uiStatic_t::frametime, _tag_menuframework::fullscreen, KEYCATCH_UI, m_entersound, Menu_Draw(), menu_in_sound, uiStatic_t::menuBackNoLogoShader, uiStatic_t::menuBackShader, NULL, qfalse, uiStatic_t::realtime, SCREEN_HEIGHT, SCREEN_WIDTH, _tag_menuframework::showlogo, trap_Key_GetCatcher(), trap_S_StartLocalSound(), UI_DrawHandlePic(), UI_DrawString(), UI_LEFT, UI_MouseEvent(), UI_SetColor(), UI_SMALLFONT, UI_UpdateCvars(), and va().
Referenced by vmMain().
qboolean UI_RegisterClientModelname (playerInfo_t * pi, const char * modelSkinName, const char * headName, const char * teamName)
References playerInfo_t::animations, Com_Printf(), Com_sprintf(), playerInfo_t::headModel, playerInfo_t::legsModel, MAX_QPATH, Q_strncpyz(), qfalse, qtrue, playerInfo_t::torsoModel, trap_R_RegisterModel(), UI_ParseAnimationFile(), and UI_RegisterClientSkin().
void UI_RegisterCvars (void)
References cvarTable_t::cvarFlags, cvarTable_t::cvarName, cvarTableSize, cvarTable_t::defaultString, trap_Cvar_Register(), and cvarTable_t::vmCvar.
void UI_RemoveBots_Cache (void)
References ART_BACK0, ART_BACK1, ART_BACKGROUND, ART_DELETE0, ART_DELETE1, and trap_R_RegisterShaderNoMip().
void UI_RemoveBotsMenu (void)
References removeBotsMenuInfo_t::menu, UI_PushMenu(), and UI_RemoveBotsMenu_Init().
void UI_Report (void)
References String_Report().
Referenced by UI_ConsoleCommand().
void UI_SaveConfigMenu (void)
References saveConfig_t::menu, UI_PushMenu(), and UI_SaveConfigMenu_Init().
void UI_SaveConfigMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_BACKGROUND, ART_SAVE0, ART_SAVE1, and trap_R_RegisterShaderNoMip().
void UI_ServerInfoMenu (void)
References serverinfo_t::add, serverinfo_t::back, serverinfo_t::banner, menucommon_s::callback, menutext_s::color, color_red, color_white, CS_SERVERINFO, _tag_menuframework::draw, menucommon_s::flags, menubitmap_s::focuspic, serverinfo_t::framel, serverinfo_t::framer, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_ADD, ID_BACK, serverinfo_t::info, Info_NextPair(), _tag_menuframework::key, MAX_INFO_KEY, MAX_INFO_STRING, MAX_INFO_VALUE, serverinfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, serverinfo_t::numlines, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s, SERVERINFO_BACK0, SERVERINFO_BACK1, ServerInfo_Cache(), ServerInfo_Event(), SERVERINFO_FRAMEL, SERVERINFO_FRAMER, ServerInfo_MenuDraw(), ServerInfo_MenuKey(), menutext_s::string, menutext_s::style, trap_Cvar_VariableValue(), trap_GetConfigString(), menucommon_s::type, UI_CENTER, UI_PushMenu(), UI_SMALLFONT, menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
void UI_SetActiveMenu (uiMenuCommand_t menu)
References Com_Printf(), Menu_Cache(), NeedCDAction(), NeedCDKeyAction(), trap_Cvar_Set(), UI_ConfirmMenu(), UI_ForceMenuOff(), UI_InGameMenu(), UI_MainMenu(), UIMENU_BAD_CD_KEY, UIMENU_INGAME, UIMENU_MAIN, UIMENU_NEED_CD, UIMENU_NONE, UIMENU_POSTGAME, and UIMENU_TEAM.
Referenced by vmMain().
void UI_SetBestScore (int level, int score)
References Com_sprintf(), Info_SetValueForKey(), Info_ValueForKey(), int(), MAX_INFO_VALUE, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Cvar_VariableValue(), and va().
Referenced by UI_SPPostgameMenu_f().
void UI_SetColor (const float * rgba)
References trap_R_SetColor().
Referenced by _UI_Init(), _UI_Refresh(), Slider_Draw(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), and UI_Refresh().
void UI_SetupMenu (void)
References setupMenuInfo_t::menu, UI_PushMenu(), and UI_SetupMenu_Init().
void UI_SetupMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
void UI_ShowPostGame (qboolean newHigh)
References _UI_SetActiveMenu(), uiInfo_t::soundHighScore, trap_Cvar_Set(), and UIMENU_POSTGAME.
Referenced by UI_CalcPostGameStats(), and UI_ConsoleCommand().
qboolean UI_ShowTierVideo (int tier)
References Com_sprintf(), Info_SetValueForKey(), Info_ValueForKey(), MAX_INFO_VALUE, qfalse, qtrue, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and va().
Referenced by UI_SPPostgameMenu_MenuDraw(), and UI_SPUnlock_f().
void UI_Shutdown (void)
Referenced by vmMain().
void UI_SignupMenu (void)
References signup_t::menu, Signup_MenuInit(), and UI_PushMenu().
void UI_SoundOptionsMenu (void)
References soundOptionsInfo_t::menu, Menu_SetCursorToItem(), soundOptionsInfo_t::sound, UI_PushMenu(), and UI_SoundOptionsMenu_Init().
void UI_SoundOptionsMenu_Cache (void)
References ART_ACCEPT0, ART_ACCEPT1, ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
void UI_SPArena_Start (const char * arenaInfo)
References ARENAS_PER_TIER, EXEC_APPEND, Info_ValueForKey(), int(), level, map, n, Q_stricmp(), trap_Cmd_ExecuteText(), trap_Cvar_SetValue(), trap_Cvar_VariableValue(), UI_GetNumSPTiers(), and va().
void UI_SpecifyLeagueMenu (void)
References specifyleague_t::menu, SpecifyLeague_MenuInit(), and UI_PushMenu().
void UI_SpecifyServerMenu (void)
References specifyserver_t::menu, SpecifyServer_MenuInit(), and UI_PushMenu().
void UI_SPLevelMenu (void)
References ARENAS_PER_TIER, currentGame, currentSet, finalTier, Info_ValueForKey(), levelMenuInfo_t::item_next, level, maxTier, levelMenuInfo_t::menu, Menu_SetCursorToItem(), minTier, trainingTier, UI_GetCurrentGame(), UI_GetNumSPArenas(), UI_GetNumSPTiers(), UI_GetSpecialArenaInfo(), UI_PushMenu(), and UI_SPLevelMenu_Init().
void UI_SPLevelMenu_Cache (void)
References ART_ARROW, ART_ARROW_FOCUS, ART_BACK0, ART_BACK1, ART_CUSTOM0, ART_CUSTOM1, ART_FIGHT0, ART_FIGHT1, ART_LEVELFRAME_FOCUS, ART_LEVELFRAME_SELECTED, ART_MAP_COMPLETE1, ART_MAP_COMPLETE2, ART_MAP_COMPLETE3, ART_MAP_COMPLETE4, ART_MAP_COMPLETE5, ART_MAP_UNKNOWN, ART_RESET0, ART_RESET1, levelMenuInfo_t::awardSounds, levelMenuInfo_t::levelCompletePic, levelMenuInfo_t::levelFocusPic, levelMenuInfo_t::levelSelectedPic, n, qfalse, trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), ui_medalPicNames, and ui_medalSounds.
void UI_SPLevelMenu_f (void)
References KEYCATCH_UI, uiStatic_t::menusp, trap_Key_SetCatcher(), UI_SPLevelMenu(), and uis.
void UI_SPLevelMenu_ReInit (void)
References qtrue, and levelMenuInfo_t::reinit.
void UI_SPPostgameMenu_Cache (void)
References ART_MENU0, ART_MENU1, ART_NEXT0, ART_NEXT1, ART_REPLAY0, ART_REPLAY1, n, qfalse, trap_Cvar_VariableValue(), trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), ui_medalPicNames, and ui_medalSounds.
void UI_SPPostgameMenu_f (void)
References arena, arenainfo, AWARD_ACCURACY, AWARD_EXCELLENT, AWARD_FRAGS, AWARD_GAUNTLET, AWARD_IMPRESSIVE, AWARD_PERFECT, postgameMenuInfo_t::awardsEarned, postgameMenuInfo_t::awardsLevels, postgameMenuInfo_t::clientNums, CS_SERVERINFO, CS_SYSTEMINFO, EXEC_APPEND, info, Info_ValueForKey(), postgameMenuInfo_t::item_again, postgameMenuInfo_t::item_next, KEYCATCH_UI, postgameMenuInfo_t::lastTier, postgameMenuInfo_t::level, MAX_INFO_STRING, MAX_QPATH, MAX_SCOREBOARD_CLIENTS, postgameMenuInfo_t::menu, Menu_SetCursorToItem(), uiStatic_t::menusp, n, postgameMenuInfo_t::numAwards, postgameMenuInfo_t::numClients, postgameMenuInfo_t::phase, postgameMenuInfo_t::placeNames, Prepname(), Q_strncpyz(), qfalse, RANK_TIED_FLAG, postgameMenuInfo_t::ranks, uiStatic_t::realtime, postgameMenuInfo_t::scoreboardtime, postgameMenuInfo_t::scores, postgameMenuInfo_t::serverId, postgameMenuInfo_t::starttime, trap_Cmd_ExecuteText(), trap_GetConfigString(), trap_Key_SetCatcher(), trap_S_RegisterSound(), UI_Argv(), UI_GetArenaInfoByMap(), UI_GetAwardLevel(), UI_GetNumSPTiers(), UI_GetSpecialArenaInfo(), UI_LogAwardData(), UI_PushMenu(), UI_SetBestScore(), UI_SPPostgameMenu_Init(), UI_TierCompleted(), uis, va(), postgameMenuInfo_t::winnerSound, and postgameMenuInfo_t::won.
void UI_SPSkillMenu (const char * arenaInfo)
References skillMenuInfo_t::arenaInfo, skillMenuInfo_t::item_fight, skillMenuInfo_t::menu, Menu_SetCursorToItem(), UI_PushMenu(), and UI_SPSkillMenu_Init().
void UI_SPSkillMenu_Cache (void)
References ART_BACK, ART_BACK_FOCUS, ART_FIGHT, ART_FIGHT_FOCUS, ART_FRAME, ART_MAP_COMPLETE1, ART_MAP_COMPLETE2, ART_MAP_COMPLETE3, ART_MAP_COMPLETE4, ART_MAP_COMPLETE5, skillMenuInfo_t::nightmareSound, qfalse, skillMenuInfo_t::silenceSound, skillMenuInfo_t::skillpics, trap_R_RegisterShaderNoMip(), and trap_S_RegisterSound().
void UI_SPUnlock_f (void)
References Com_sprintf(), Info_SetValueForKey(), level, MAX_INFO_VALUE, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Print(), ui_numSinglePlayerArenas, ui_numSpecialSinglePlayerArenas, UI_ShowTierVideo(), and UI_SPLevelMenu_ReInit().
Referenced by UI_ConsoleCommand().
void UI_SPUnlockMedals_f (void)
References Com_sprintf(), Info_SetValueForKey(), MAX_INFO_VALUE, n, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and trap_Print().
Referenced by UI_ConsoleCommand().
void UI_StartDemoLoop (void)
References EXEC_APPEND, and trap_Cmd_ExecuteText().
void UI_StartServerMenu (qboolean multiplayer)
References startserver_t::menu, startserver_t::multiplayer, StartServer_MenuInit(), and UI_PushMenu().
void UI_TeamMainMenu (void)
References teammain_t::menu, TeamMain_MenuInit(), and UI_PushMenu().
void UI_TeamOrdersMenu (void)
References teamOrdersMenuInfo_t::menu, UI_PushMenu(), and UI_TeamOrdersMenu_Init().
void UI_TeamOrdersMenu_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAME, and trap_R_RegisterShaderNoMip().
void UI_TeamOrdersMenu_f (void)
References uiClientState_t::clientNum, CS_PLAYERS, CS_SERVERINFO, teamOrdersMenuInfo_t::gametype, GT_TEAM, info, Info_ValueForKey(), MAX_INFO_STRING, TEAM_SPECTATOR, trap_GetClientState(), trap_GetConfigString(), and UI_TeamOrdersMenu().
int UI_TierCompleted (int levelWon)
References ARENAS_PER_TIER, info, Info_ValueForKey(), level, n, UI_GetBestScore(), UI_GetNumSPTiers(), and UI_GetSpecialArenaInfo().
Referenced by UI_SPPostgameMenu_f().
void UI_UpdateCvars (void)
References cvarTableSize, trap_Cvar_Update(), and cvarTable_t::vmCvar.
void UI_UpdateScreen (void)
References trap_UpdateScreen().
Variable Documentation
vec4_t color_black
vec4_t color_blue
vec4_t color_dim
vec4_t color_orange
vec4_t color_red
vec4_t color_white
vec4_t color_yellow
vec4_t list_color
vec4_t listbar_color
qboolean m_entersound
Referenced by UI_PushMenu(), and UI_Refresh().
vec4_t menu_black_color
sfxHandle_t menu_buzz_sound
vec4_t menu_dark_color
vec4_t menu_dim_color
vec4_t menu_grayed_color
vec4_t menu_highlight_color
sfxHandle_t menu_in_sound
sfxHandle_t menu_move_sound
sfxHandle_t menu_null_sound
sfxHandle_t menu_out_sound
vec4_t menu_red_color
vec4_t menu_text_color
vec4_t name_color
vec4_t text_color_disabled
vec4_t text_color_highlight
vec4_t text_color_normal
vmCvar_t ui_actualNetGameType
Referenced by UI_DrawTeamMember(), UI_RunMenuScript(), and UI_TeamMember_HandleKey().
vmCvar_t ui_arenasFile
vmCvar_t ui_bigFont
Referenced by Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), and Text_Width().
vmCvar_t ui_botsFile
vmCvar_t ui_brassTime
vmCvar_t ui_browserGameType
vmCvar_t ui_browserMaster
vmCvar_t ui_browserShowEmpty
vmCvar_t ui_browserShowFull
vmCvar_t ui_captureLimit
vmCvar_t ui_cdkey
vmCvar_t ui_cdkeychecked
vmCvar_t ui_ctf_capturelimit
vmCvar_t ui_ctf_friendly
vmCvar_t ui_ctf_timelimit
vmCvar_t ui_currentMap
Referenced by _UI_Init(), UI_CalcPostGameStats(), UI_DrawAllMapsSelection(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_DrawMapTimeToBeat(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_RunMenuScript(), UI_StartSkirmish(), and UI_StopCinematic().
vmCvar_t ui_currentNetMap
Referenced by UI_DrawAllMapsSelection(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_DrawNetMapCinematic(), UI_FeederSelection(), and UI_RunMenuScript().
vmCvar_t ui_currentOpponent
vmCvar_t ui_currentTier
vmCvar_t ui_dedicated
Referenced by UI_RunMenuScript().
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_ffa_fraglimit
vmCvar_t ui_ffa_timelimit
vmCvar_t ui_fragLimit
vmCvar_t ui_gameType
Referenced by _UI_Init(), UI_DrawGameType(), UI_DrawMapTimeToBeat(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_MapCountByGameType(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_RunMenuScript(), UI_SetCapFragLimits(), and UI_StartSkirmish().
vmCvar_t ui_joinGameType
Referenced by UI_BuildServerDisplayList(), UI_DrawJoinGameType(), and UI_JoinGameType_HandleKey().
vmCvar_t ui_lastServerRefresh_0
vmCvar_t ui_lastServerRefresh_1
vmCvar_t ui_lastServerRefresh_2
vmCvar_t ui_lastServerRefresh_3
vmCvar_t ui_mapIndex
Referenced by UI_FeederSelection(), and UI_RunMenuScript().
vmCvar_t ui_marks
char* ui_medalNames[]
char* ui_medalPicNames[]
char* ui_medalSounds[]
vmCvar_t ui_menuFiles
vmCvar_t ui_netGameType
Referenced by _UI_Init(), UI_DrawNetGameType(), UI_MapCountByGameType(), UI_NetGameType_HandleKey(), UI_OwnerDrawVisible(), and UI_RunMenuScript().
vmCvar_t ui_netSource
Referenced by UI_BuildServerDisplayList(), UI_DrawNetSource(), UI_DrawServerRefreshDate(), UI_FeederItemText(), UI_NetSource_HandleKey(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_RunMenuScript(), and UI_SourceForLAN().
vmCvar_t ui_opponentName
vmCvar_t ui_scoreAccuracy
vmCvar_t ui_scoreAssists
vmCvar_t ui_scoreBase
vmCvar_t ui_scoreDefends
vmCvar_t ui_scoreExcellents
vmCvar_t ui_scoreGauntlets
vmCvar_t ui_scoreImpressives
vmCvar_t ui_scorePerfect
vmCvar_t ui_scoreScore
vmCvar_t ui_scoreShutoutBonus
vmCvar_t ui_scoreSkillBonus
vmCvar_t ui_scoreTeam
vmCvar_t ui_scoreTime
vmCvar_t ui_scoreTimeBonus
vmCvar_t ui_selectedPlayer
Referenced by UI_OwnerDrawVisible().
vmCvar_t ui_selectedPlayerName
vmCvar_t ui_server1
vmCvar_t ui_server10
vmCvar_t ui_server11
vmCvar_t ui_server12
vmCvar_t ui_server13
vmCvar_t ui_server14
vmCvar_t ui_server15
vmCvar_t ui_server16
vmCvar_t ui_server2
vmCvar_t ui_server3
vmCvar_t ui_server4
vmCvar_t ui_server5
vmCvar_t ui_server6
vmCvar_t ui_server7
vmCvar_t ui_server8
vmCvar_t ui_server9
vmCvar_t ui_serverFilterType
Referenced by UI_BuildServerDisplayList(), UI_DrawNetFilter(), UI_NetFilter_HandleKey(), and UI_OwnerDrawWidth().
vmCvar_t ui_serverStatusTimeOut
Referenced by UI_BuildFindPlayerList().
vmCvar_t ui_singlePlayerActive
Referenced by _UI_SetActiveMenu().
vmCvar_t ui_smallFont
Referenced by Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), and Text_Width().
vmCvar_t ui_spAwards
vmCvar_t ui_spScores1
vmCvar_t ui_spScores2
vmCvar_t ui_spScores3
vmCvar_t ui_spScores4
vmCvar_t ui_spScores5
vmCvar_t ui_spSelection
vmCvar_t ui_spSkill
vmCvar_t ui_spVideos
vmCvar_t ui_team_fraglimit
vmCvar_t ui_team_friendly
vmCvar_t ui_team_timelimit
vmCvar_t ui_tourney_fraglimit
vmCvar_t ui_tourney_timelimit
uiInfo_t uiInfo
Referenced by UI_AdjustFrom640(), UI_CalcPostGameStats(), UI_ConsoleCommand(), UI_CursorInRect(), UI_DrawSides(), UI_DrawTopBottom(), UI_FillRect(), UI_LoadArenas(), UI_LoadBestScores(), UI_PlayerAnimation(), and UI_SwingAngles().
uiStatic_t uis
Referenced by ArenaServers_DoRefresh(), ArenaServers_StartRefresh(), Bitmap_Draw(), Controls_DrawPlayer(), DriverInfo_MenuDraw(), GraphicsOptions_MenuInit(), Main_MenuDraw(), Menu_Cache(), Menu_DefaultKey(), Menu_Draw(), PlayerModel_DrawPlayer(), PlayerSettings_DrawPlayer(), RadioButton_Draw(), ScrollList_Key(), Slider_Key(), UI_CanShowTierVideo(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Event(), UI_CinematicsMenu_Init(), UI_DisplayDownloadInfo(), UI_DisplayOptionsMenu_Init(), UI_DrawConnectScreen(), UI_DriverInfo_Menu(), UI_InGameMenu(), UI_InitGameinfo(), UI_MainMenu(), UI_PlayerAnimation(), UI_SPLevelMenu_f(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_Init(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuKey(), UI_SwingAngles(), and UI_TeamOrdersMenu_Key().
sfxHandle_t weaponChangeSound