ioquake3: code/ui/ui_players.c File Reference
ui_players.c File Reference
#include "ui_local.h"
Defines
#define UI_TIMER_GESTURE 2300
#define UI_TIMER_JUMP 1000
#define UI_TIMER_LAND 130
#define UI_TIMER_WEAPON_SWITCH 300
#define UI_TIMER_ATTACK 500
#define UI_TIMER_MUZZLE_FLASH 20
#define UI_TIMER_WEAPON_DELAY 250
#define JUMP_HEIGHT 56
#define SWINGSPEED 0.3f
#define SPIN_SPEED 0.9f
#define COAST_TIME 1000
Functions
static void UI_PlayerInfo_SetWeapon (playerInfo_t *pi, weapon_t weaponNum)
static void UI_ForceLegsAnim (playerInfo_t *pi, int anim)
static void UI_SetLegsAnim (playerInfo_t *pi, int anim)
static void UI_ForceTorsoAnim (playerInfo_t *pi, int anim)
static void UI_SetTorsoAnim (playerInfo_t *pi, int anim)
static void UI_TorsoSequencing (playerInfo_t *pi)
static void UI_LegsSequencing (playerInfo_t *pi)
static void UI_PositionEntityOnTag (refEntity_t *entity, const refEntity_t *parent, clipHandle_t parentModel, char *tagName)
static void UI_PositionRotatedEntityOnTag (refEntity_t *entity, const refEntity_t *parent, clipHandle_t parentModel, char *tagName)
static void UI_SetLerpFrameAnimation (playerInfo_t *ci, lerpFrame_t *lf, int newAnimation)
static void UI_RunLerpFrame (playerInfo_t *ci, lerpFrame_t *lf, int newAnimation)
static void UI_PlayerAnimation (playerInfo_t *pi, int *legsOld, int *legs, float *legsBackLerp, int *torsoOld, int *torso, float *torsoBackLerp)
static void UI_SwingAngles (float destination, float swingTolerance, float clampTolerance, float speed, float *angle, qboolean *swinging)
static float UI_MovedirAdjustment (playerInfo_t *pi)
static void UI_PlayerAngles (playerInfo_t *pi, vec3_t legs[3], vec3_t torso[3], vec3_t head[3])
static void UI_PlayerFloatSprite (playerInfo_t *pi, vec3_t origin, qhandle_t shader)
float UI_MachinegunSpinAngle (playerInfo_t *pi)
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t *pi, int time)
static qboolean UI_FileExists (const char *filename)
static qboolean UI_FindClientHeadFile (char *filename, int length, const char *teamName, const char *headModelName, const char *headSkinName, const char *base, const char *ext)
static qboolean UI_RegisterClientSkin (playerInfo_t *pi, const char *modelName, const char *skinName, const char *headModelName, const char *headSkinName, const char *teamName)
static qboolean UI_ParseAnimationFile (const char *filename, animation_t *animations)
qboolean UI_RegisterClientModelname (playerInfo_t *pi, const char *modelSkinName, const char *headModelSkinName, const char *teamName)
void UI_PlayerInfo_SetModel (playerInfo_t *pi, const char *model, const char *headmodel, char *teamName)
void UI_PlayerInfo_SetInfo (playerInfo_t *pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNumber, qboolean chat)
Variables
static int dp_realtime
static float jumpHeight
sfxHandle_t weaponChangeSound
Define Documentation
#define COAST_TIME 1000
Referenced by UI_MachinegunSpinAngle().
#define JUMP_HEIGHT 56
Referenced by UI_LegsSequencing().
#define SPIN_SPEED 0.9f
Referenced by UI_MachinegunSpinAngle().
#define SWINGSPEED 0.3f
Referenced by UI_PlayerAngles().
#define UI_TIMER_ATTACK 500
Referenced by UI_ForceTorsoAnim().
#define UI_TIMER_GESTURE 2300
Referenced by UI_ForceTorsoAnim().
#define UI_TIMER_JUMP 1000
Referenced by UI_ForceLegsAnim(), and UI_LegsSequencing().
#define UI_TIMER_LAND 130
Referenced by UI_LegsSequencing().
#define UI_TIMER_MUZZLE_FLASH 20
Referenced by UI_PlayerInfo_SetInfo().
#define UI_TIMER_WEAPON_DELAY 250
Referenced by UI_PlayerInfo_SetInfo().
#define UI_TIMER_WEAPON_SWITCH 300
Referenced by UI_TorsoSequencing().
Function Documentation
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t * pi, int time)
References AnglesToAxis(), playerInfo_t::animations, refEntity_t::axis, AxisClear(), refEntity_t::backlerp, playerInfo_t::barrelModel, Byte4Copy, playerInfo_t::c1RGBA, CHAN_LOCAL, playerInfo_t::chat, colorWhite, playerInfo_t::currentWeapon, refEntity_t::customSkin, DEG2RAD, dp_realtime, playerInfo_t::flashDlightColor, playerInfo_t::flashModel, refdef_t::fov_x, refdef_t::fov_y, refEntity_t::frame, h, head, playerInfo_t::headModel, playerInfo_t::headSkin, refdef_t::height, refEntity_t::hModel, int(), jumpHeight, playerInfo_t::lastWeapon, playerInfo_t::legsModel, playerInfo_t::legsSkin, refEntity_t::lightingOrigin, M_PI, animation_s::numFrames, refEntity_t::oldframe, refEntity_t::oldorigin, refEntity_t::origin, playerInfo_t::pendingWeapon, PITCH, RDF_NOWORLDMODEL, refdef_t::rdflags, playerInfo_t::realWeapon, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, ROLL, refEntity_t::shaderRGBA, refdef_t::time, playerInfo_t::torsoModel, playerInfo_t::torsoSkin, trap_R_AddLightToScene(), trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RegisterShaderNoMip(), trap_R_RenderScene(), trap_S_StartLocalSound(), UI_AdjustFrom640(), UI_MachinegunSpinAngle(), UI_PlayerAngles(), UI_PlayerAnimation(), UI_PlayerFloatSprite(), UI_PositionEntityOnTag(), UI_PositionRotatedEntityOnTag(), VectorCopy, refdef_t::viewaxis, playerInfo_t::weapon, weaponChangeSound, playerInfo_t::weaponModel, playerInfo_t::weaponTimer, refdef_t::width, WP_BFG, WP_GAUNTLET, WP_MACHINEGUN, WP_NONE, WP_RAILGUN, refdef_t::x, xx, refdef_t::y, and YAW.
Referenced by Controls_DrawPlayer(), PlayerModel_DrawPlayer(), PlayerSettings_DrawPlayer(), UI_DrawOpponent(), and UI_DrawPlayerModel().
static qboolean UI_FileExists (const char * filename) [static]
References FS_READ, NULL, qfalse, qtrue, and trap_FS_FOpenFile().
Referenced by UI_FindClientHeadFile().
static qboolean UI_FindClientHeadFile (char * filename, int length, const char * teamName, const char * headModelName, const char * headSkinName, const char * base, const char * ext) [static]
References Com_sprintf(), qfalse, qtrue, and UI_FileExists().
Referenced by UI_RegisterClientSkin().
static void UI_ForceLegsAnim (playerInfo_t * pi, int anim) [static]
References ANIM_TOGGLEBIT, LEGS_JUMP, playerInfo_t::legsAnim, playerInfo_t::legsAnimationTimer, and UI_TIMER_JUMP.
Referenced by UI_LegsSequencing(), UI_PlayerInfo_SetInfo(), and UI_SetLegsAnim().
static void UI_ForceTorsoAnim (playerInfo_t * pi, int anim) [static]
References ANIM_TOGGLEBIT, TORSO_ATTACK, TORSO_ATTACK2, TORSO_GESTURE, playerInfo_t::torsoAnim, playerInfo_t::torsoAnimationTimer, UI_TIMER_ATTACK, and UI_TIMER_GESTURE.
Referenced by UI_PlayerInfo_SetInfo(), UI_SetTorsoAnim(), and UI_TorsoSequencing().
static void UI_LegsSequencing (playerInfo_t * pi) [static]
References ANIM_TOGGLEBIT, JUMP_HEIGHT, jumpHeight, LEGS_IDLE, LEGS_JUMP, LEGS_LAND, playerInfo_t::legsAnim, playerInfo_t::legsAnimationTimer, M_PI, UI_ForceLegsAnim(), UI_SetLegsAnim(), UI_TIMER_JUMP, and UI_TIMER_LAND.
Referenced by UI_PlayerAnimation().
float UI_MachinegunSpinAngle (playerInfo_t * pi)
References AngleMod(), ANIM_TOGGLEBIT, playerInfo_t::barrelAngle, playerInfo_t::barrelSpinning, playerInfo_t::barrelTime, COAST_TIME, dp_realtime, SPIN_SPEED, TORSO_ATTACK, TORSO_ATTACK2, and playerInfo_t::torsoAnim.
static float UI_MovedirAdjustment (playerInfo_t * pi) [static]
References AngleVectors(), playerInfo_t::moveAngles, NULL, Q_fabs(), VectorSubtract, and playerInfo_t::viewAngles.
Referenced by UI_PlayerAngles().
static qboolean UI_ParseAnimationFile (const char * filename, animation_t * animations) [static]
References COM_Compress(), COM_Parse(), Com_Printf(), animation_s::firstFrame, animation_s::frameLerp, FS_READ, animation_s::initialLerp, LEGS_WALKCR, animation_s::loopFrames, MAX_ANIMATIONS, animation_s::numFrames, Q_stricmp(), qfalse, qtrue, token, TORSO_GESTURE, trap_FS_FCloseFile(), trap_FS_FOpenFile(), and trap_FS_Read().
Referenced by UI_RegisterClientModelname().
static void UI_PlayerAngles (playerInfo_t * pi, vec3_t legs[3], vec3_t torso[3], vec3_t head[3]) [static]
References AngleMod(), AnglesSubtract(), AnglesToAxis(), ANIM_TOGGLEBIT, playerInfo_t::legs, LEGS_IDLE, playerInfo_t::legsAnim, PITCH, lerpFrame_t::pitchAngle, lerpFrame_t::pitching, qtrue, SWINGSPEED, playerInfo_t::torso, TORSO_STAND, playerInfo_t::torsoAnim, UI_MovedirAdjustment(), UI_SwingAngles(), VectorClear, VectorCopy, playerInfo_t::viewAngles, YAW, lerpFrame_t::yawAngle, and lerpFrame_t::yawing.
Referenced by UI_DrawPlayer().
static void UI_PlayerAnimation (playerInfo_t * pi, int * legsOld, int * legs, float * legsBackLerp, int * torsoOld, int * torso, float * torsoBackLerp) [static]
References ANIM_TOGGLEBIT, lerpFrame_t::backlerp, lerpFrame_t::frame, displayContextDef_t::frameTime, playerInfo_t::legs, LEGS_IDLE, LEGS_TURN, playerInfo_t::legsAnim, playerInfo_t::legsAnimationTimer, lerpFrame_t::oldFrame, playerInfo_t::torso, playerInfo_t::torsoAnim, playerInfo_t::torsoAnimationTimer, UI_LegsSequencing(), UI_RunLerpFrame(), UI_TorsoSequencing(), uiInfo_t::uiDC, uiInfo, and lerpFrame_t::yawing.
Referenced by UI_DrawPlayer().
static void UI_PlayerFloatSprite (playerInfo_t * pi, vec3_t origin, qhandle_t shader) [static]
References refEntity_t::customShader, refEntity_t::origin, refEntity_t::radius, refEntity_t::renderfx, refEntity_t::reType, RT_SPRITE, shader, trap_R_AddRefEntityToScene(), and VectorCopy.
Referenced by UI_DrawPlayer().
void UI_PlayerInfo_SetInfo (playerInfo_t * pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNumber, qboolean chat)
References ANIM_TOGGLEBIT, BOTH_DEATH1, playerInfo_t::c1RGBA, playerInfo_t::chat, playerInfo_t::color1, playerInfo_t::currentWeapon, dp_realtime, int(), jumpHeight, playerInfo_t::lastWeapon, playerInfo_t::legs, LEGS_JUMP, LEGS_LAND, playerInfo_t::legsAnim, playerInfo_t::moveAngles, playerInfo_t::muzzleFlashTime, playerInfo_t::newModel, playerInfo_t::pendingLegsAnim, playerInfo_t::pendingTorsoAnim, playerInfo_t::pendingWeapon, qfalse, playerInfo_t::torso, TORSO_ATTACK, TORSO_ATTACK2, TORSO_DROP, TORSO_GESTURE, TORSO_RAISE, TORSO_STAND, TORSO_STAND2, playerInfo_t::torsoAnim, trap_Cvar_VariableValue(), UI_ForceLegsAnim(), UI_ForceTorsoAnim(), UI_PlayerInfo_SetWeapon(), UI_TIMER_MUZZLE_FLASH, UI_TIMER_WEAPON_DELAY, VectorClear, VectorCopy, VectorSet, playerInfo_t::viewAngles, playerInfo_t::weapon, playerInfo_t::weaponTimer, WP_GAUNTLET, WP_NONE, YAW, lerpFrame_t::yawAngle, and lerpFrame_t::yawing.
Referenced by Controls_UpdateModel(), PlayerModel_UpdateModel(), PlayerSettings_DrawPlayer(), PlayerSettings_SetMenuItems(), UI_DrawOpponent(), and UI_DrawPlayerModel().
void UI_PlayerInfo_SetModel (playerInfo_t * pi, const char * model, const char * headmodel, char * teamName)
References playerInfo_t::chat, playerInfo_t::currentWeapon, playerInfo_t::lastWeapon, playerInfo_t::newModel, playerInfo_t::pendingWeapon, qfalse, qtrue, UI_PlayerInfo_SetWeapon(), UI_RegisterClientModelname(), playerInfo_t::weapon, playerInfo_t::weaponTimer, and WP_MACHINEGUN.
static void UI_PlayerInfo_SetWeapon (playerInfo_t * pi, weapon_t weaponNum) [static]
References playerInfo_t::barrelModel, bg_itemlist, gitem_s::classname, COM_StripExtension(), playerInfo_t::currentWeapon, playerInfo_t::flashDlightColor, playerInfo_t::flashModel, gitem_s::giTag, gitem_s::giType, IT_WEAPON, MAKERGB, MAX_QPATH, playerInfo_t::realWeapon, trap_R_RegisterModel(), playerInfo_t::weaponModel, gitem_s::world_model, WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_NONE, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by UI_PlayerInfo_SetInfo(), UI_PlayerInfo_SetModel(), and UI_TorsoSequencing().
static void UI_PositionEntityOnTag (refEntity_t * entity, const refEntity_t * parent, clipHandle_t parentModel, char * tagName) [static]
References refEntity_t::axis, orientation_t::axis, refEntity_t::backlerp, refEntity_t::frame, MatrixMultiply(), refEntity_t::oldframe, refEntity_t::origin, orientation_t::origin, trap_CM_LerpTag(), VectorCopy, and VectorMA().
Referenced by UI_DrawPlayer().
static void UI_PositionRotatedEntityOnTag (refEntity_t * entity, const refEntity_t * parent, clipHandle_t parentModel, char * tagName) [static]
References refEntity_t::axis, orientation_t::axis, refEntity_t::backlerp, refEntity_t::frame, MatrixMultiply(), refEntity_t::oldframe, refEntity_t::origin, orientation_t::origin, trap_CM_LerpTag(), VectorCopy, and VectorMA().
Referenced by UI_DrawPlayer().
qboolean UI_RegisterClientModelname (playerInfo_t * pi, const char * modelSkinName, const char * headModelSkinName, const char * teamName)
References playerInfo_t::animations, Com_Printf(), Com_sprintf(), playerInfo_t::headModel, playerInfo_t::legsModel, MAX_QPATH, Q_strncpyz(), qfalse, qtrue, playerInfo_t::torsoModel, trap_R_RegisterModel(), UI_ParseAnimationFile(), and UI_RegisterClientSkin().
static qboolean UI_RegisterClientSkin (playerInfo_t * pi, const char * modelName, const char * skinName, const char * headModelName, const char * headSkinName, const char * teamName) [static]
References Com_sprintf(), playerInfo_t::headSkin, playerInfo_t::legsSkin, MAX_QPATH, qfalse, qtrue, playerInfo_t::torsoSkin, trap_R_RegisterSkin(), and UI_FindClientHeadFile().
Referenced by UI_RegisterClientModelname().
static void UI_RunLerpFrame (playerInfo_t * ci, lerpFrame_t * lf, int newAnimation) [static]
References lerpFrame_t::animation, lerpFrame_t::animationNumber, lerpFrame_t::animationTime, lerpFrame_t::backlerp, dp_realtime, animation_s::firstFrame, lerpFrame_t::frame, animation_s::frameLerp, lerpFrame_t::frameTime, if(), animation_s::loopFrames, animation_s::numFrames, lerpFrame_t::oldFrame, lerpFrame_t::oldFrameTime, and UI_SetLerpFrameAnimation().
Referenced by UI_PlayerAnimation().
static void UI_SetLegsAnim (playerInfo_t * pi, int anim) [static]
References playerInfo_t::pendingLegsAnim, and UI_ForceLegsAnim().
Referenced by UI_LegsSequencing().
static void UI_SetLerpFrameAnimation (playerInfo_t * ci, lerpFrame_t * lf, int newAnimation) [static]
References ANIM_TOGGLEBIT, lerpFrame_t::animation, lerpFrame_t::animationNumber, playerInfo_t::animations, lerpFrame_t::animationTime, lerpFrame_t::frameTime, animation_s::initialLerp, MAX_ANIMATIONS, trap_Error(), and va().
Referenced by UI_RunLerpFrame().
static void UI_SetTorsoAnim (playerInfo_t * pi, int anim) [static]
References playerInfo_t::pendingTorsoAnim, and UI_ForceTorsoAnim().
Referenced by UI_TorsoSequencing().
static void UI_SwingAngles (float destination, float swingTolerance, float clampTolerance, float speed, float * angle, qboolean * swinging) [static]
References AngleMod(), AngleSubtract(), displayContextDef_t::frameTime, move(), qfalse, qtrue, uiInfo_t::uiDC, and uiInfo.
Referenced by UI_PlayerAngles().
static void UI_TorsoSequencing (playerInfo_t * pi) [static]
References ANIM_TOGGLEBIT, playerInfo_t::currentWeapon, TORSO_ATTACK, TORSO_ATTACK2, TORSO_DROP, TORSO_GESTURE, TORSO_RAISE, TORSO_STAND, playerInfo_t::torsoAnim, playerInfo_t::torsoAnimationTimer, UI_ForceTorsoAnim(), UI_PlayerInfo_SetWeapon(), UI_SetTorsoAnim(), UI_TIMER_WEAPON_SWITCH, and playerInfo_t::weapon.
Referenced by UI_PlayerAnimation().
Variable Documentation
int dp_realtime [static]
Referenced by UI_DrawPlayer(), UI_MachinegunSpinAngle(), UI_PlayerInfo_SetInfo(), and UI_RunLerpFrame().
float jumpHeight [static]
Referenced by UI_DrawPlayer(), UI_LegsSequencing(), and UI_PlayerInfo_SetInfo().
sfxHandle_t weaponChangeSound
Referenced by Menu_Cache(), and UI_DrawPlayer().