ioquake3: code/q3_ui/ui_mfield.c File Reference
ui_mfield.c File Reference
#include "ui_local.h"
Functions
void MField_Draw (mfield_t *edit, int x, int y, int style, vec4_t color)
void MField_Paste (mfield_t *edit)
void MField_KeyDownEvent (mfield_t *edit, int key)
void MField_CharEvent (mfield_t *edit, int ch)
void MField_Clear (mfield_t *edit)
void MenuField_Init (menufield_s *m)
void MenuField_Draw (menufield_s *f)
sfxHandle_t MenuField_Key (menufield_s *m, int *key)
Function Documentation
void MenuField_Draw (menufield_s * f)
References BIGCHAR_WIDTH, menucommon_s::bottom, menufield_s::field, menucommon_s::flags, menufield_s::generic, menucommon_s::left, listbar_color, Menu_ItemAtCursor(), MField_Draw(), menucommon_s::name, menucommon_s::parent, qfalse, QMF_GRAYED, QMF_SMALLFONT, qtrue, menucommon_s::right, SMALLCHAR_WIDTH, text_color_disabled, text_color_highlight, text_color_normal, menucommon_s::top, UI_BIGFONT, UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_FillRect(), UI_PULSE, UI_RIGHT, UI_SMALLFONT, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_Draw().
void MenuField_Init (menufield_s * m)
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, menucommon_s::bottom, menufield_s::field, menucommon_s::flags, menufield_s::generic, h, menucommon_s::left, MField_Clear(), menucommon_s::name, QMF_SMALLFONT, menucommon_s::right, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menucommon_s::top, mfield_t::widthInChars, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_AddItem().
sfxHandle_t MenuField_Key (menufield_s * m, int * key)
References menufield_s::field, menucommon_s::flags, menufield_s::generic, K_CHAR_FLAG, K_DOWNARROW, K_ENTER, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_TAB, K_UPARROW, menu_buzz_sound, MField_CharEvent(), MField_KeyDownEvent(), Q_isalpha(), Q_islower(), Q_isupper(), QMF_LOWERCASE, QMF_NUMBERSONLY, and QMF_UPPERCASE.
Referenced by Menu_DefaultKey().
void MField_CharEvent (mfield_t * edit, int ch)
References mfield_t::buffer, mfield_t::cursor, MAX_EDIT_LINE, mfield_t::maxchars, memmove(), MField_Clear(), MField_Paste(), mfield_t::scroll, trap_Key_GetOverstrikeMode(), and mfield_t::widthInChars.
Referenced by MenuField_Key(), and MField_Paste().
void MField_Clear (mfield_t * edit)
References mfield_t::buffer, mfield_t::cursor, and mfield_t::scroll.
Referenced by MenuField_Init(), and MField_CharEvent().
void MField_Draw (mfield_t * edit, int x, int y, int style, vec4_t color)
References BIGCHAR_WIDTH, mfield_t::buffer, mfield_t::cursor, GIANTCHAR_WIDTH, MAX_STRING_CHARS, mfield_t::scroll, SMALLCHAR_WIDTH, trap_Error(), trap_Key_GetOverstrikeMode(), UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_GIANTFONT, UI_PULSE, UI_RIGHT, UI_SMALLFONT, and mfield_t::widthInChars.
Referenced by MenuField_Draw(), UI_DrawConnectScreen(), and UI_SaveConfigMenu_SavenameDraw().
void MField_KeyDownEvent (mfield_t * edit, int key)
References mfield_t::buffer, mfield_t::cursor, K_CTRL, K_DEL, K_END, K_HOME, K_INS, K_KP_DEL, K_KP_END, K_KP_HOME, K_KP_INS, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_RIGHTARROW, K_SHIFT, memmove(), MField_Paste(), mfield_t::scroll, trap_Key_GetOverstrikeMode(), trap_Key_IsDown(), trap_Key_SetOverstrikeMode(), and mfield_t::widthInChars.
Referenced by MenuField_Key().
void MField_Paste (mfield_t * edit)
References MField_CharEvent(), and trap_GetClipboardData().
Referenced by MField_CharEvent(), and MField_KeyDownEvent().