ioquake3: code/q3_ui/ui_sparena.c File Reference
ui_sparena.c File Reference
#include "ui_local.h"
Functions
void UI_SPArena_Start (const char *arenaInfo)
Function Documentation
void UI_SPArena_Start (const char * arenaInfo)
References ARENAS_PER_TIER, EXEC_APPEND, Info_ValueForKey(), int(), level, map, n, Q_stricmp(), trap_Cmd_ExecuteText(), trap_Cvar_SetValue(), trap_Cvar_VariableValue(), UI_GetNumSPTiers(), and va().
Referenced by UI_SPPostgameMenu_NextEvent(), and UI_SPSkillMenu_FightEvent().