ioquake3: code/q3_ui/ui_playersettings.c File Reference
ui_playersettings.c File Reference
#include "ui_local.h"
Data Structures
struct playersettings_t
Defines
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define ART_MODEL0 "menu/art/model_0"
#define ART_MODEL1 "menu/art/model_1"
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FX_BASE "menu/art/fx_base"
#define ART_FX_BLUE "menu/art/fx_blue"
#define ART_FX_CYAN "menu/art/fx_cyan"
#define ART_FX_GREEN "menu/art/fx_grn"
#define ART_FX_RED "menu/art/fx_red"
#define ART_FX_TEAL "menu/art/fx_teal"
#define ART_FX_WHITE "menu/art/fx_white"
#define ART_FX_YELLOW "menu/art/fx_yel"
#define ID_NAME 10
#define ID_HANDICAP 11
#define ID_EFFECTS 12
#define ID_BACK 13
#define ID_MODEL 14
#define MAX_NAMELENGTH 20
Functions
static void PlayerSettings_DrawName (void *self)
static void PlayerSettings_DrawHandicap (void *self)
static void PlayerSettings_DrawEffects (void *self)
static void PlayerSettings_DrawPlayer (void *self)
static void PlayerSettings_SaveChanges (void)
static sfxHandle_t PlayerSettings_MenuKey (int key)
static void PlayerSettings_SetMenuItems (void)
static void PlayerSettings_MenuEvent (void *ptr, int event)
static void PlayerSettings_MenuInit (void)
void PlayerSettings_Cache (void)
void UI_PlayerSettingsMenu (void)
Variables
static playersettings_t s_playersettings
static int gamecodetoui [] = {4,2,3,0,5,1,6}
static int uitogamecode [] = {4,6,2,3,1,5,7}
static const char * handicap_items []
Define Documentation
#define ART_BACK0 "menu/art/back_0"
Referenced by PlayerSettings_Cache(), and PlayerSettings_MenuInit().
#define ART_BACK1 "menu/art/back_1"
Referenced by PlayerSettings_Cache(), and PlayerSettings_MenuInit().
#define ART_FRAMEL "menu/art/frame2_l"
Referenced by PlayerSettings_Cache(), and PlayerSettings_MenuInit().
#define ART_FRAMER "menu/art/frame1_r"
Referenced by PlayerSettings_Cache(), and PlayerSettings_MenuInit().
#define ART_FX_BASE "menu/art/fx_base"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_BLUE "menu/art/fx_blue"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_CYAN "menu/art/fx_cyan"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_GREEN "menu/art/fx_grn"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_RED "menu/art/fx_red"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_TEAL "menu/art/fx_teal"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_WHITE "menu/art/fx_white"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_FX_YELLOW "menu/art/fx_yel"
Referenced by AssetCache(), and PlayerSettings_Cache().
#define ART_MODEL0 "menu/art/model_0"
Referenced by PlayerSettings_Cache(), and PlayerSettings_MenuInit().
#define ART_MODEL1 "menu/art/model_1"
Referenced by PlayerSettings_Cache(), and PlayerSettings_MenuInit().
#define ID_BACK 13
Referenced by PlayerSettings_MenuEvent(), and PlayerSettings_MenuInit().
#define ID_EFFECTS 12
Referenced by PlayerSettings_MenuInit().
#define ID_HANDICAP 11
Referenced by PlayerSettings_MenuEvent(), and PlayerSettings_MenuInit().
#define ID_MODEL 14
Referenced by PlayerSettings_MenuEvent(), and PlayerSettings_MenuInit().
#define ID_NAME 10
#define MAX_NAMELENGTH 20
Referenced by PlayerSettings_MenuInit().
Function Documentation
void PlayerSettings_Cache (void)
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, ART_FX_BASE, ART_FX_BLUE, ART_FX_CYAN, ART_FX_GREEN, ART_FX_RED, ART_FX_TEAL, ART_FX_WHITE, ART_FX_YELLOW, ART_MODEL0, ART_MODEL1, playersettings_t::fxBasePic, playersettings_t::fxPic, and trap_R_RegisterShaderNoMip().
Referenced by PlayerSettings_MenuInit(), and UI_Cache_f().
static void PlayerSettings_DrawEffects (void * self) [static]
References _tag_menuframework::cursor, menulist_s::curvalue, playersettings_t::fxBasePic, playersettings_t::fxPic, menulist_s::generic, menucommon_s::menuPosition, menucommon_s::parent, PROP_HEIGHT, text_color_highlight, text_color_normal, UI_DrawHandlePic(), UI_DrawProportionalString(), UI_LEFT, UI_PULSE, UI_SMALLFONT, menucommon_s::x, and menucommon_s::y.
Referenced by PlayerSettings_MenuInit().
static void PlayerSettings_DrawHandicap (void * self) [static]
References _tag_menuframework::cursor, menulist_s::curvalue, menulist_s::generic, handicap_items, menucommon_s::menuPosition, menucommon_s::parent, PROP_HEIGHT, text_color_highlight, text_color_normal, UI_DrawProportionalString(), UI_LEFT, UI_PULSE, UI_SMALLFONT, menucommon_s::x, and menucommon_s::y.
Referenced by PlayerSettings_MenuInit().
static void PlayerSettings_DrawName (void * self) [static]
References mfield_t::buffer, color_white, COLOR_WHITE, ColorIndex, _tag_menuframework::cursor, mfield_t::cursor, menufield_s::field, g_color_table, menufield_s::generic, menucommon_s::menuPosition, n, menucommon_s::parent, PROP_HEIGHT, Q_CleanStr(), Q_IsColorString, Q_strncpyz(), SMALLCHAR_WIDTH, text_color_highlight, text_color_normal, trap_Key_GetOverstrikeMode(), UI_BIGFONT, UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawProportionalString(), UI_LEFT, UI_PULSE, UI_SMALLFONT, menucommon_s::x, and menucommon_s::y.
Referenced by PlayerSettings_MenuInit().
static void PlayerSettings_DrawPlayer (void * self) [static]
References b, menubitmap_s::generic, menubitmap_s::height, LEGS_IDLE, MAX_QPATH, PITCH, playersettings_t::playerinfo, playersettings_t::playerModel, qfalse, uiStatic_t::realtime, ROLL, TORSO_STAND, trap_Cvar_VariableStringBuffer(), UI_DrawPlayer(), UI_PlayerInfo_SetInfo(), UI_PlayerInfo_SetModel(), uis, vec3_origin, menubitmap_s::width, WP_MACHINEGUN, menucommon_s::x, menucommon_s::y, and YAW.
Referenced by PlayerSettings_MenuInit().
static void PlayerSettings_MenuEvent (void * ptr, int event) [static]
References menulist_s::curvalue, playersettings_t::handicap, ID_BACK, ID_HANDICAP, ID_MODEL, PlayerSettings_SaveChanges(), QM_ACTIVATED, trap_Cvar_Set(), UI_PlayerModelMenu(), UI_PopMenu(), and va().
Referenced by PlayerSettings_MenuInit().
static void PlayerSettings_MenuInit (void) [static]
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, ART_MODEL0, ART_MODEL1, playersettings_t::back, playersettings_t::banner, menucommon_s::bottom, menucommon_s::callback, menutext_s::color, color_white, playersettings_t::effects, menufield_s::field, menucommon_s::flags, menubitmap_s::focuspic, playersettings_t::framel, playersettings_t::framer, _tag_menuframework::fullscreen, menufield_s::generic, menulist_s::generic, menubitmap_s::generic, menutext_s::generic, playersettings_t::handicap, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_EFFECTS, ID_HANDICAP, ID_MODEL, playersettings_t::item_null, _tag_menuframework::key, menucommon_s::left, MAX_NAMELENGTH, mfield_t::maxchars, playersettings_t::menu, Menu_AddItem(), playersettings_t::model, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_SPINCONTROL, playersettings_t::name, menucommon_s::name, menulist_s::numitems, menucommon_s::ownerdraw, playersettings_t::player, PlayerSettings_Cache(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), PlayerSettings_DrawPlayer(), PlayerSettings_MenuEvent(), PlayerSettings_MenuKey(), PlayerSettings_SetMenuItems(), PROP_HEIGHT, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_MOUSEONLY, QMF_NODEFAULTINIT, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, QMF_SILENT, qtrue, menucommon_s::right, menutext_s::string, menutext_s::style, menucommon_s::top, menucommon_s::type, UI_CENTER, menubitmap_s::width, mfield_t::widthInChars, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_PlayerSettingsMenu().
static sfxHandle_t PlayerSettings_MenuKey (int key) [static]
References K_ESCAPE, K_MOUSE2, playersettings_t::menu, Menu_DefaultKey(), and PlayerSettings_SaveChanges().
Referenced by PlayerSettings_MenuInit().
static void PlayerSettings_SaveChanges (void) [static]
References mfield_t::buffer, menulist_s::curvalue, playersettings_t::effects, menufield_s::field, playersettings_t::handicap, playersettings_t::name, trap_Cvar_Set(), trap_Cvar_SetValue(), and uitogamecode.
Referenced by PlayerSettings_MenuEvent(), and PlayerSettings_MenuKey().
static void PlayerSettings_SetMenuItems (void) [static]
References mfield_t::buffer, Com_Clamp(), menulist_s::curvalue, playersettings_t::effects, menufield_s::field, gamecodetoui, h, playersettings_t::handicap, LEGS_IDLE, playersettings_t::name, PITCH, playersettings_t::playerinfo, Q_strncpyz(), qfalse, ROLL, TORSO_STAND, trap_Cvar_VariableValue(), UI_Cvar_VariableString(), UI_PlayerInfo_SetInfo(), UI_PlayerInfo_SetModel(), vec3_origin, WP_MACHINEGUN, and YAW.
Referenced by PlayerSettings_MenuInit().
void UI_PlayerSettingsMenu (void)
References playersettings_t::menu, PlayerSettings_MenuInit(), and UI_PushMenu().
Referenced by UI_SetupMenu_Event(), and UI_SPLevelMenu_PlayerEvent().
Variable Documentation
int gamecodetoui[] = {4,2,3,0,5,1,6} [static]
Referenced by PlayerSettings_SetMenuItems().
const char* handicap_items[] [static]
Initial value:
 {
        "None",
        "95",
        "90",
        "85",
        "80",
        "75",
        "70",
        "65",
        "60",
        "55",
        "50",
        "45",
        "40",
        "35",
        "30",
        "25",
        "20",
        "15",
        "10",
        "5",
        NULL
}
Referenced by PlayerSettings_DrawHandicap().
playersettings_t s_playersettings [static]
int uitogamecode[] = {4,6,2,3,1,5,7} [static]
Referenced by PlayerSettings_SaveChanges().