ioquake3: code/q3_ui/ui_splevel.c File Reference
ui_splevel.c File Reference
#include "ui_local.h"
Data Structures
struct levelMenuInfo_t
Defines
#define ART_LEVELFRAME_FOCUS "menu/art/maps_select"
#define ART_LEVELFRAME_SELECTED "menu/art/maps_selected"
#define ART_ARROW "menu/art/narrow_0"
#define ART_ARROW_FOCUS "menu/art/narrow_1"
#define ART_MAP_UNKNOWN "menu/art/unknownmap"
#define ART_MAP_COMPLETE1 "menu/art/level_complete1"
#define ART_MAP_COMPLETE2 "menu/art/level_complete2"
#define ART_MAP_COMPLETE3 "menu/art/level_complete3"
#define ART_MAP_COMPLETE4 "menu/art/level_complete4"
#define ART_MAP_COMPLETE5 "menu/art/level_complete5"
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FIGHT0 "menu/art/fight_0"
#define ART_FIGHT1 "menu/art/fight_1"
#define ART_RESET0 "menu/art/reset_0"
#define ART_RESET1 "menu/art/reset_1"
#define ART_CUSTOM0 "menu/art/skirmish_0"
#define ART_CUSTOM1 "menu/art/skirmish_1"
#define ID_LEFTARROW 10
#define ID_PICTURE0 11
#define ID_PICTURE1 12
#define ID_PICTURE2 13
#define ID_PICTURE3 14
#define ID_RIGHTARROW 15
#define ID_PLAYERPIC 16
#define ID_AWARD1 17
#define ID_AWARD2 18
#define ID_AWARD3 19
#define ID_AWARD4 20
#define ID_AWARD5 21
#define ID_AWARD6 22
#define ID_BACK 23
#define ID_RESET 24
#define ID_CUSTOM 25
#define ID_NEXT 26
#define PLAYER_Y 314
#define AWARDS_Y (PLAYER_Y + 26)
#define LEVEL_DESC_LEFT_MARGIN 332
Functions
static void PlayerIcon (const char *modelAndSkin, char *iconName, int iconNameMaxSize)
static qhandle_t PlayerIconHandle (const char *modelAndSkin)
static void UI_SPLevelMenu_SetBots (void)
static void UI_SPLevelMenu_SetMenuArena (int n, int level, const char *arenaInfo)
static void UI_SPLevelMenu_SetMenuItems (void)
static void UI_SPLevelMenu_ResetDraw (void)
static void UI_SPLevelMenu_ResetAction (qboolean result)
static void UI_SPLevelMenu_ResetEvent (void *ptr, int event)
static void UI_SPLevelMenu_LevelEvent (void *ptr, int notification)
static void UI_SPLevelMenu_LeftArrowEvent (void *ptr, int notification)
static void UI_SPLevelMenu_RightArrowEvent (void *ptr, int notification)
static void UI_SPLevelMenu_PlayerEvent (void *ptr, int notification)
static void UI_SPLevelMenu_AwardEvent (void *ptr, int notification)
static void UI_SPLevelMenu_NextEvent (void *ptr, int notification)
static void UI_SPLevelMenu_BackEvent (void *ptr, int notification)
static void UI_SPLevelMenu_CustomEvent (void *ptr, int notification)
static void UI_SPLevelMenu_MenuDraw (void)
void UI_SPLevelMenu_Cache (void)
static void UI_SPLevelMenu_Init (void)
void UI_SPLevelMenu (void)
void UI_SPLevelMenu_f (void)
void UI_SPLevelMenu_ReInit (void)
Variables
static levelMenuInfo_t levelMenuInfo
static int selectedArenaSet
static int selectedArena
static int currentSet
static int currentGame
static int trainingTier
static int finalTier
static int minTier
static int maxTier
Define Documentation
#define ART_ARROW "menu/art/narrow_0"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_ARROW_FOCUS "menu/art/narrow_1"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_BACK0 "menu/art/back_0"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_BACK1 "menu/art/back_1"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_CUSTOM0 "menu/art/skirmish_0"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_CUSTOM1 "menu/art/skirmish_1"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_FIGHT0 "menu/art/fight_0"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_FIGHT1 "menu/art/fight_1"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_LEVELFRAME_FOCUS "menu/art/maps_select"
Referenced by UI_SPLevelMenu_Cache().
#define ART_LEVELFRAME_SELECTED "menu/art/maps_selected"
Referenced by UI_SPLevelMenu_Cache().
#define ART_MAP_COMPLETE1 "menu/art/level_complete1"
Referenced by UI_SPLevelMenu_Cache().
#define ART_MAP_COMPLETE2 "menu/art/level_complete2"
Referenced by UI_SPLevelMenu_Cache().
#define ART_MAP_COMPLETE3 "menu/art/level_complete3"
Referenced by UI_SPLevelMenu_Cache().
#define ART_MAP_COMPLETE4 "menu/art/level_complete4"
Referenced by UI_SPLevelMenu_Cache().
#define ART_MAP_COMPLETE5 "menu/art/level_complete5"
Referenced by UI_SPLevelMenu_Cache().
#define ART_MAP_UNKNOWN "menu/art/unknownmap"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_SetMenuArena().
#define ART_RESET0 "menu/art/reset_0"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define ART_RESET1 "menu/art/reset_1"
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
#define AWARDS_Y (PLAYER_Y + 26)
Referenced by UI_SPLevelMenu_Init(), and UI_SPLevelMenu_MenuDraw().
#define ID_AWARD1 17
Referenced by UI_SPLevelMenu_AwardEvent(), and UI_SPLevelMenu_Init().
#define ID_AWARD2 18
#define ID_AWARD3 19
#define ID_AWARD4 20
#define ID_AWARD5 21
#define ID_AWARD6 22
#define ID_BACK 23
Referenced by UI_SPLevelMenu_Init().
#define ID_CUSTOM 25
Referenced by UI_SPLevelMenu_Init().
#define ID_LEFTARROW 10
Referenced by UI_SPLevelMenu_Init().
#define ID_NEXT 26
Referenced by UI_SPLevelMenu_Init().
#define ID_PICTURE0 11
Referenced by UI_SPLevelMenu_Init(), and UI_SPLevelMenu_LevelEvent().
#define ID_PICTURE1 12
Referenced by UI_SPLevelMenu_Init().
#define ID_PICTURE2 13
Referenced by UI_SPLevelMenu_Init().
#define ID_PICTURE3 14
Referenced by UI_SPLevelMenu_Init().
#define ID_PLAYERPIC 16
Referenced by UI_SPLevelMenu_Init().
#define ID_RESET 24
Referenced by UI_SPLevelMenu_Init().
#define ID_RIGHTARROW 15
Referenced by UI_SPLevelMenu_Init().
#define LEVEL_DESC_LEFT_MARGIN 332
#define PLAYER_Y 314
Referenced by UI_SPLevelMenu_MenuDraw().
Function Documentation
static void PlayerIcon (const char * modelAndSkin, char * iconName, int iconNameMaxSize) [static]
References Com_sprintf(), MAX_QPATH, Q_stricmp(), Q_strncpyz(), and trap_R_RegisterShaderNoMip().
Referenced by PlayerIconHandle(), UI_SPLevelMenu_Init(), and UI_SPLevelMenu_MenuDraw().
static qhandle_t PlayerIconHandle (const char * modelAndSkin) [static]
References MAX_QPATH, PlayerIcon(), and trap_R_RegisterShaderNoMip().
Referenced by UI_SPLevelMenu_SetBots().
void UI_SPLevelMenu (void)
References ARENAS_PER_TIER, currentGame, currentSet, finalTier, Info_ValueForKey(), levelMenuInfo_t::item_next, level, maxTier, levelMenuInfo_t::menu, Menu_SetCursorToItem(), minTier, trainingTier, UI_GetCurrentGame(), UI_GetNumSPArenas(), UI_GetNumSPTiers(), UI_GetSpecialArenaInfo(), UI_PushMenu(), and UI_SPLevelMenu_Init().
Referenced by Main_MenuEvent(), Reset_MenuEvent(), UI_SPLevelMenu_f(), UI_SPLevelMenu_MenuDraw(), and UI_SPLevelMenu_ResetAction().
static void UI_SPLevelMenu_AwardEvent (void * ptr, int notification) [static]
References levelMenuInfo_t::awardSounds, CHAN_ANNOUNCER, ID_AWARD1, n, QM_ACTIVATED, and trap_S_StartLocalSound().
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_BackEvent (void * ptr, int notification) [static]
References QM_ACTIVATED, selectedArena, and UI_PopMenu().
Referenced by UI_SPLevelMenu_Init().
void UI_SPLevelMenu_Cache (void)
References ART_ARROW, ART_ARROW_FOCUS, ART_BACK0, ART_BACK1, ART_CUSTOM0, ART_CUSTOM1, ART_FIGHT0, ART_FIGHT1, ART_LEVELFRAME_FOCUS, ART_LEVELFRAME_SELECTED, ART_MAP_COMPLETE1, ART_MAP_COMPLETE2, ART_MAP_COMPLETE3, ART_MAP_COMPLETE4, ART_MAP_COMPLETE5, ART_MAP_UNKNOWN, ART_RESET0, ART_RESET1, levelMenuInfo_t::awardSounds, levelMenuInfo_t::levelCompletePic, levelMenuInfo_t::levelFocusPic, levelMenuInfo_t::levelSelectedPic, n, qfalse, trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), ui_medalPicNames, and ui_medalSounds.
Referenced by UI_Cache_f(), and UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_CustomEvent (void * ptr, int notification) [static]
References qfalse, QM_ACTIVATED, and UI_StartServerMenu().
Referenced by UI_SPLevelMenu_Init().
void UI_SPLevelMenu_f (void)
References KEYCATCH_UI, uiStatic_t::menusp, trap_Key_SetCatcher(), UI_SPLevelMenu(), and uis.
Referenced by UI_ConsoleCommand().
static void UI_SPLevelMenu_Init (void) [static]
References ARENAS_PER_TIER, ART_ARROW, ART_ARROW_FOCUS, ART_BACK0, ART_BACK1, ART_CUSTOM0, ART_CUSTOM1, ART_FIGHT0, ART_FIGHT1, ART_RESET0, ART_RESET1, AWARD_FRAGS, levelMenuInfo_t::awardLevels, AWARDS_Y, menucommon_s::bottom, menucommon_s::callback, menutext_s::color, color_red, count, currentGame, currentSet, _tag_menuframework::draw, menucommon_s::flags, menubitmap_s::focuspic, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_AWARD1, ID_BACK, ID_CUSTOM, ID_LEFTARROW, ID_NEXT, ID_PICTURE0, ID_PICTURE1, ID_PICTURE2, ID_PICTURE3, ID_PLAYERPIC, ID_RESET, ID_RIGHTARROW, int(), levelMenuInfo_t::item_awards, levelMenuInfo_t::item_back, levelMenuInfo_t::item_banner, levelMenuInfo_t::item_custom, levelMenuInfo_t::item_leftarrow, levelMenuInfo_t::item_maps, levelMenuInfo_t::item_next, levelMenuInfo_t::item_null, levelMenuInfo_t::item_player, levelMenuInfo_t::item_reset, levelMenuInfo_t::item_rightarrow, levelMenuInfo_t::levelPicNames, MAX_QPATH, levelMenuInfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, n, menucommon_s::name, PlayerIcon(), levelMenuInfo_t::playerModel, levelMenuInfo_t::playerPicName, QMF_LEFT_JUSTIFY, QMF_MOUSEONLY, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, QMF_SILENT, qtrue, selectedArena, selectedArenaSet, menutext_s::string, menutext_s::style, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Cvar_VariableValue(), menucommon_s::type, UI_CENTER, UI_GetAwardLevel(), ui_medalPicNames, UI_SPLevelMenu_AwardEvent(), UI_SPLevelMenu_BackEvent(), UI_SPLevelMenu_Cache(), UI_SPLevelMenu_CustomEvent(), UI_SPLevelMenu_LeftArrowEvent(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_NextEvent(), UI_SPLevelMenu_PlayerEvent(), UI_SPLevelMenu_ResetEvent(), UI_SPLevelMenu_RightArrowEvent(), UI_SPLevelMenu_SetMenuItems(), menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SPLevelMenu().
static void UI_SPLevelMenu_LeftArrowEvent (void * ptr, int notification) [static]
References minTier, QM_ACTIVATED, selectedArenaSet, and UI_SPLevelMenu_SetMenuItems().
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_LevelEvent (void * ptr, int notification) [static]
References ARENAS_PER_TIER, finalTier, ID_PICTURE0, QM_ACTIVATED, selectedArena, levelMenuInfo_t::selectedArenaInfo, selectedArenaSet, trainingTier, trap_Cvar_SetValue(), UI_GetArenaInfoByNumber(), and UI_SPLevelMenu_SetBots().
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_MenuDraw (void) [static]
References levelMenuInfo_t::awardLevels, AWARDS_Y, levelMenuInfo_t::botNames, levelMenuInfo_t::botPics, color_black, color_orange, color_red, color_white, color_yellow, Com_sprintf(), currentSet, menubitmap_s::generic, Info_ValueForKey(), levelMenuInfo_t::item_maps, levelMenuInfo_t::item_player, level, levelMenuInfo_t::levelCompletePic, levelMenuInfo_t::levelFocusPic, levelMenuInfo_t::levelNames, levelMenuInfo_t::levelScores, levelMenuInfo_t::levelScoresSkill, levelMenuInfo_t::levelSelectedPic, MAX_INFO_VALUE, levelMenuInfo_t::menu, Menu_Draw(), Menu_ItemAtCursor(), n, NULL, levelMenuInfo_t::numBots, levelMenuInfo_t::numMaps, PLAYER_Y, PlayerIcon(), levelMenuInfo_t::playerModel, levelMenuInfo_t::playerPicName, PULSE_DIVISOR, Q_CleanStr(), Q_stricmp(), Q_strncpyz(), Q_strupr(), uiStatic_t::realtime, levelMenuInfo_t::reinit, selectedArena, levelMenuInfo_t::selectedArenaInfo, selectedArenaSet, menubitmap_s::shader, trap_Cvar_VariableStringBuffer(), trap_R_SetColor(), UI_BIGFONT, UI_CENTER, UI_DrawHandlePic(), UI_DrawProportionalString(), UI_DrawString(), UI_FillRect(), UI_LEFT, UI_PopMenu(), UI_SMALLFONT, UI_SPLevelMenu(), uis, va(), Vector4Copy, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_NextEvent (void * ptr, int notification) [static]
References currentSet, QM_ACTIVATED, selectedArena, levelMenuInfo_t::selectedArenaInfo, selectedArenaSet, and UI_SPSkillMenu().
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_PlayerEvent (void * ptr, int notification) [static]
References QM_ACTIVATED, and UI_PlayerSettingsMenu().
Referenced by UI_SPLevelMenu_Init().
void UI_SPLevelMenu_ReInit (void)
References qtrue, and levelMenuInfo_t::reinit.
Referenced by UI_SPUnlock_f().
static void UI_SPLevelMenu_ResetAction (qboolean result) [static]
References trap_Cvar_SetValue(), UI_NewGame(), UI_PopMenu(), and UI_SPLevelMenu().
Referenced by UI_SPLevelMenu_ResetEvent().
static void UI_SPLevelMenu_ResetDraw (void) [static]
References color_yellow, PROP_HEIGHT, SCREEN_WIDTH, UI_CENTER, UI_DrawProportionalString(), and UI_SMALLFONT.
Referenced by UI_SPLevelMenu_ResetEvent().
static void UI_SPLevelMenu_ResetEvent (void * ptr, int event) [static]
References QM_ACTIVATED, UI_ConfirmMenu(), UI_SPLevelMenu_ResetAction(), and UI_SPLevelMenu_ResetDraw().
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_RightArrowEvent (void * ptr, int notification) [static]
References maxTier, QM_ACTIVATED, selectedArenaSet, and UI_SPLevelMenu_SetMenuItems().
Referenced by UI_SPLevelMenu_Init().
static void UI_SPLevelMenu_SetBots (void) [static]
References levelMenuInfo_t::botNames, levelMenuInfo_t::botPics, currentSet, Info_ValueForKey(), MAX_INFO_STRING, levelMenuInfo_t::numBots, PlayerIconHandle(), Q_CleanStr(), Q_strncpyz(), levelMenuInfo_t::selectedArenaInfo, selectedArenaSet, UI_GetBotInfoByName(), and UI_GetBotInfoByNumber().
Referenced by UI_SPLevelMenu_LevelEvent(), and UI_SPLevelMenu_SetMenuItems().
static void UI_SPLevelMenu_SetMenuArena (int n, int level, const char * arenaInfo) [static]
References ART_MAP_UNKNOWN, currentSet, menucommon_s::flags, menubitmap_s::generic, Info_ValueForKey(), levelMenuInfo_t::item_maps, levelMenuInfo_t::levelNames, levelMenuInfo_t::levelPicNames, levelMenuInfo_t::levelScores, levelMenuInfo_t::levelScoresSkill, MAX_QPATH, n, Q_strncpyz(), Q_strupr(), QMF_GRAYED, QMF_INACTIVE, selectedArenaSet, menubitmap_s::shader, trap_R_RegisterShaderNoMip(), UI_GetBestScore(), and va().
Referenced by UI_SPLevelMenu_SetMenuItems().
static void UI_SPLevelMenu_SetMenuItems (void) [static]
References ARENAS_PER_TIER, Bitmap_Init(), menucommon_s::bottom, currentSet, finalTier, menucommon_s::flags, menubitmap_s::generic, Info_ValueForKey(), levelMenuInfo_t::item_leftarrow, levelMenuInfo_t::item_maps, levelMenuInfo_t::item_rightarrow, level, levelMenuInfo_t::levelPicNames, maxTier, minTier, n, levelMenuInfo_t::numMaps, QMF_HIDDEN, QMF_INACTIVE, selectedArena, levelMenuInfo_t::selectedArenaInfo, selectedArenaSet, menubitmap_s::shader, trainingTier, trap_Cvar_SetValue(), UI_GetArenaInfoByNumber(), UI_GetSpecialArenaInfo(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), and menucommon_s::x.
Referenced by UI_SPLevelMenu_Init(), UI_SPLevelMenu_LeftArrowEvent(), and UI_SPLevelMenu_RightArrowEvent().
Variable Documentation
int currentGame [static]
Referenced by UI_SPLevelMenu(), and UI_SPLevelMenu_Init().
int currentSet [static]
Referenced by UI_SPLevelMenu(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_NextEvent(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), UI_SPLevelMenu_SetMenuItems(), and UI_SPPostgameMenu_NextEvent().
int finalTier [static]
Referenced by UI_SPLevelMenu(), UI_SPLevelMenu_LevelEvent(), and UI_SPLevelMenu_SetMenuItems().
levelMenuInfo_t levelMenuInfo [static]
int maxTier [static]
Referenced by UI_SPLevelMenu(), UI_SPLevelMenu_RightArrowEvent(), and UI_SPLevelMenu_SetMenuItems().
int minTier [static]
Referenced by UI_SPLevelMenu(), UI_SPLevelMenu_LeftArrowEvent(), and UI_SPLevelMenu_SetMenuItems().
int selectedArena [static]
Referenced by UI_SPLevelMenu_BackEvent(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_NextEvent(), and UI_SPLevelMenu_SetMenuItems().
int selectedArenaSet [static]
Referenced by UI_SPLevelMenu_Init(), UI_SPLevelMenu_LeftArrowEvent(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_NextEvent(), UI_SPLevelMenu_RightArrowEvent(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), and UI_SPLevelMenu_SetMenuItems().
int trainingTier [static]
Referenced by UI_SPLevelMenu(), UI_SPLevelMenu_LevelEvent(), and UI_SPLevelMenu_SetMenuItems().