ioquake3: code/ui/ui_shared.c File Reference
ui_shared.c File Reference
#include "ui_shared.h"
Data Structures
struct scrollInfo_s
struct stringDef_s
struct bind_t
struct configcvar_t
struct keywordHash_s
Defines
#define SCROLL_TIME_START 500
#define SCROLL_TIME_ADJUST 150
#define SCROLL_TIME_ADJUSTOFFSET 40
#define SCROLL_TIME_FLOOR 20
#define DOUBLE_CLICK_DELAY 300
#define MEM_POOL_SIZE 1024 * 1024
#define HASH_TABLE_SIZE 2048
#define KEYWORDHASH_SIZE 512
Typedefs
typedef struct scrollInfo_s scrollInfo_t
typedef struct stringDef_s stringDef_t
typedef struct keywordHash_s keywordHash_t
Functions
void Item_RunScript (itemDef_t *item, const char *s)
void Item_SetupKeywordHash (void)
void Menu_SetupKeywordHash (void)
int BindingIDFromName (const char *name)
qboolean Item_Bind_HandleKey (itemDef_t *item, int key, qboolean down)
itemDef_t * Menu_SetPrevCursorItem (menuDef_t *menu)
itemDef_t * Menu_SetNextCursorItem (menuDef_t *menu)
static qboolean Menu_OverActiveItem (menuDef_t *menu, float x, float y)
void * UI_Alloc (int size)
void UI_InitMemory (void)
qboolean UI_OutOfMemory (void)
static unsigned hashForString (const char *str)
const char * String_Alloc (const char *p)
void String_Report (void)
void String_Init (void)
static __attribute__ ((format(printf, 2, 3)))
void LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
qboolean Float_Parse (char **p, float *f)
qboolean PC_Float_Parse (int handle, float *f)
qboolean Color_Parse (char **p, vec4_t *c)
qboolean PC_Color_Parse (int handle, vec4_t *c)
qboolean Int_Parse (char **p, int *i)
qboolean PC_Int_Parse (int handle, int *i)
qboolean Rect_Parse (char **p, rectDef_t *r)
qboolean PC_Rect_Parse (int handle, rectDef_t *r)
qboolean String_Parse (char **p, const char **out)
qboolean PC_String_Parse (int handle, const char **out)
qboolean PC_Script_Parse (int handle, const char **out)
void Init_Display (displayContextDef_t *dc)
void GradientBar_Paint (rectDef_t *rect, vec4_t color)
void Window_Init (Window *w)
void Fade (int *flags, float *f, float clamp, int *nextTime, int offsetTime, qboolean bFlags, float fadeAmount)
void Window_Paint (Window *w, float fadeAmount, float fadeClamp, float fadeCycle)
void Item_SetScreenCoords (itemDef_t *item, float x, float y)
void Item_UpdatePosition (itemDef_t *item)
void Menu_UpdatePosition (menuDef_t *menu)
void Menu_PostParse (menuDef_t *menu)
itemDef_t * Menu_ClearFocus (menuDef_t *menu)
qboolean IsVisible (int flags)
qboolean Rect_ContainsPoint (rectDef_t *rect, float x, float y)
int Menu_ItemsMatchingGroup (menuDef_t *menu, const char *name)
itemDef_t * Menu_GetMatchingItemByNumber (menuDef_t *menu, int index, const char *name)
void Script_SetColor (itemDef_t *item, char **args)
void Script_SetAsset (itemDef_t *item, char **args)
void Script_SetBackground (itemDef_t *item, char **args)
itemDef_t * Menu_FindItemByName (menuDef_t *menu, const char *p)
void Script_SetTeamColor (itemDef_t *item, char **args)
void Script_SetItemColor (itemDef_t *item, char **args)
void Menu_ShowItemByName (menuDef_t *menu, const char *p, qboolean bShow)
void Menu_FadeItemByName (menuDef_t *menu, const char *p, qboolean fadeOut)
menuDef_t * Menus_FindByName (const char *p)
void Menus_ShowByName (const char *p)
void Menus_OpenByName (const char *p)
static void Menu_RunCloseScript (menuDef_t *menu)
void Menus_CloseByName (const char *p)
void Menus_CloseAll (void)
void Script_Show (itemDef_t *item, char **args)
void Script_Hide (itemDef_t *item, char **args)
void Script_FadeIn (itemDef_t *item, char **args)
void Script_FadeOut (itemDef_t *item, char **args)
void Script_Open (itemDef_t *item, char **args)
void Script_ConditionalOpen (itemDef_t *item, char **args)
void Script_Close (itemDef_t *item, char **args)
void Menu_TransitionItemByName (menuDef_t *menu, const char *p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt)
void Script_Transition (itemDef_t *item, char **args)
void Menu_OrbitItemByName (menuDef_t *menu, const char *p, float x, float y, float cx, float cy, int time)
void Script_Orbit (itemDef_t *item, char **args)
void Script_SetFocus (itemDef_t *item, char **args)
void Script_SetPlayerModel (itemDef_t *item, char **args)
void Script_SetPlayerHead (itemDef_t *item, char **args)
void Script_SetCvar (itemDef_t *item, char **args)
void Script_Exec (itemDef_t *item, char **args)
void Script_Play (itemDef_t *item, char **args)
void Script_playLooped (itemDef_t *item, char **args)
qboolean Item_EnableShowViaCvar (itemDef_t *item, int flag)
qboolean Item_SetFocus (itemDef_t *item, float x, float y)
int Item_ListBox_MaxScroll (itemDef_t *item)
int Item_ListBox_ThumbPosition (itemDef_t *item)
int Item_ListBox_ThumbDrawPosition (itemDef_t *item)
float Item_Slider_ThumbPosition (itemDef_t *item)
int Item_Slider_OverSlider (itemDef_t *item, float x, float y)
int Item_ListBox_OverLB (itemDef_t *item, float x, float y)
void Item_ListBox_MouseEnter (itemDef_t *item, float x, float y)
void Item_MouseEnter (itemDef_t *item, float x, float y)
void Item_MouseLeave (itemDef_t *item)
itemDef_t * Menu_HitTest (menuDef_t *menu, float x, float y)
void Item_SetMouseOver (itemDef_t *item, qboolean focus)
qboolean Item_OwnerDraw_HandleKey (itemDef_t *item, int key)
qboolean Item_ListBox_HandleKey (itemDef_t *item, int key, qboolean down, qboolean force)
qboolean Item_YesNo_HandleKey (itemDef_t *item, int key)
int Item_Multi_CountSettings (itemDef_t *item)
int Item_Multi_FindCvarByValue (itemDef_t *item)
const char * Item_Multi_Setting (itemDef_t *item)
qboolean Item_Multi_HandleKey (itemDef_t *item, int key)
qboolean Item_TextField_HandleKey (itemDef_t *item, int key)
static void Scroll_ListBox_AutoFunc (void *p)
static void Scroll_ListBox_ThumbFunc (void *p)
static void Scroll_Slider_ThumbFunc (void *p)
void Item_StartCapture (itemDef_t *item, int key)
void Item_StopCapture (itemDef_t *item)
qboolean Item_Slider_HandleKey (itemDef_t *item, int key, qboolean down)
qboolean Item_HandleKey (itemDef_t *item, int key, qboolean down)
void Item_Action (itemDef_t *item)
static void Window_CloseCinematic (windowDef_t *window)
static void Menu_CloseCinematics (menuDef_t *menu)
static void Display_CloseCinematics (void)
void Menus_Activate (menuDef_t *menu)
int Display_VisibleMenuCount (void)
void Menus_HandleOOBClick (menuDef_t *menu, int key, qboolean down)
static rectDef_t * Item_CorrectedTextRect (itemDef_t *item)
void Menu_HandleKey (menuDef_t *menu, int key, qboolean down)
void ToWindowCoords (float *x, float *y, windowDef_t *window)
void Rect_ToWindowCoords (rectDef_t *rect, windowDef_t *window)
void Item_SetTextExtents (itemDef_t *item, int *width, int *height, const char *text)
void Item_TextColor (itemDef_t *item, vec4_t *newColor)
void Item_Text_AutoWrapped_Paint (itemDef_t *item)
void Item_Text_Wrapped_Paint (itemDef_t *item)
void Item_Text_Paint (itemDef_t *item)
void Item_TextField_Paint (itemDef_t *item)
void Item_YesNo_Paint (itemDef_t *item)
void Item_Multi_Paint (itemDef_t *item)
static void Controls_GetKeyAssignment (char *command, int *twokeys)
void Controls_GetConfig (void)
void Controls_SetConfig (qboolean restart)
void Controls_SetDefaults (void)
void BindingFromName (const char *cvar)
void Item_Slider_Paint (itemDef_t *item)
void Item_Bind_Paint (itemDef_t *item)
qboolean Display_KeyBindPending (void)
void AdjustFrom640 (float *x, float *y, float *w, float *h)
void Item_Model_Paint (itemDef_t *item)
void Item_Image_Paint (itemDef_t *item)
void Item_ListBox_Paint (itemDef_t *item)
void Item_OwnerDraw_Paint (itemDef_t *item)
void Item_Paint (itemDef_t *item)
void Menu_Init (menuDef_t *menu)
itemDef_t * Menu_GetFocusedItem (menuDef_t *menu)
menuDef_t * Menu_GetFocused (void)
void Menu_ScrollFeeder (menuDef_t *menu, int feeder, qboolean down)
void Menu_SetFeederSelection (menuDef_t *menu, int feeder, int index, const char *name)
qboolean Menus_AnyFullScreenVisible (void)
menuDef_t * Menus_ActivateByName (const char *p)
void Item_Init (itemDef_t *item)
void Menu_HandleMouseMove (menuDef_t *menu, float x, float y)
void Menu_Paint (menuDef_t *menu, qboolean forcePaint)
void Item_ValidateTypeData (itemDef_t *item)
int KeywordHash_Key (char *keyword)
void KeywordHash_Add (keywordHash_t *table[], keywordHash_t *key)
keywordHash_t * KeywordHash_Find (keywordHash_t *table[], char *keyword)
qboolean ItemParse_name (itemDef_t *item, int handle)
qboolean ItemParse_focusSound (itemDef_t *item, int handle)
qboolean ItemParse_text (itemDef_t *item, int handle)
qboolean ItemParse_group (itemDef_t *item, int handle)
qboolean ItemParse_asset_model (itemDef_t *item, int handle)
qboolean ItemParse_asset_shader (itemDef_t *item, int handle)
qboolean ItemParse_model_origin (itemDef_t *item, int handle)
qboolean ItemParse_model_fovx (itemDef_t *item, int handle)
qboolean ItemParse_model_fovy (itemDef_t *item, int handle)
qboolean ItemParse_model_rotation (itemDef_t *item, int handle)
qboolean ItemParse_model_angle (itemDef_t *item, int handle)
qboolean ItemParse_rect (itemDef_t *item, int handle)
qboolean ItemParse_style (itemDef_t *item, int handle)
qboolean ItemParse_decoration (itemDef_t *item, int handle)
qboolean ItemParse_notselectable (itemDef_t *item, int handle)
qboolean ItemParse_wrapped (itemDef_t *item, int handle)
qboolean ItemParse_autowrapped (itemDef_t *item, int handle)
qboolean ItemParse_horizontalscroll (itemDef_t *item, int handle)
qboolean ItemParse_type (itemDef_t *item, int handle)
qboolean ItemParse_elementwidth (itemDef_t *item, int handle)
qboolean ItemParse_elementheight (itemDef_t *item, int handle)
qboolean ItemParse_feeder (itemDef_t *item, int handle)
qboolean ItemParse_elementtype (itemDef_t *item, int handle)
qboolean ItemParse_columns (itemDef_t *item, int handle)
qboolean ItemParse_border (itemDef_t *item, int handle)
qboolean ItemParse_bordersize (itemDef_t *item, int handle)
qboolean ItemParse_visible (itemDef_t *item, int handle)
qboolean ItemParse_ownerdraw (itemDef_t *item, int handle)
qboolean ItemParse_align (itemDef_t *item, int handle)
qboolean ItemParse_textalign (itemDef_t *item, int handle)
qboolean ItemParse_textalignx (itemDef_t *item, int handle)
qboolean ItemParse_textaligny (itemDef_t *item, int handle)
qboolean ItemParse_textscale (itemDef_t *item, int handle)
qboolean ItemParse_textstyle (itemDef_t *item, int handle)
qboolean ItemParse_backcolor (itemDef_t *item, int handle)
qboolean ItemParse_forecolor (itemDef_t *item, int handle)
qboolean ItemParse_bordercolor (itemDef_t *item, int handle)
qboolean ItemParse_outlinecolor (itemDef_t *item, int handle)
qboolean ItemParse_background (itemDef_t *item, int handle)
qboolean ItemParse_cinematic (itemDef_t *item, int handle)
qboolean ItemParse_doubleClick (itemDef_t *item, int handle)
qboolean ItemParse_onFocus (itemDef_t *item, int handle)
qboolean ItemParse_leaveFocus (itemDef_t *item, int handle)
qboolean ItemParse_mouseEnter (itemDef_t *item, int handle)
qboolean ItemParse_mouseExit (itemDef_t *item, int handle)
qboolean ItemParse_mouseEnterText (itemDef_t *item, int handle)
qboolean ItemParse_mouseExitText (itemDef_t *item, int handle)
qboolean ItemParse_action (itemDef_t *item, int handle)
qboolean ItemParse_special (itemDef_t *item, int handle)
qboolean ItemParse_cvarTest (itemDef_t *item, int handle)
qboolean ItemParse_cvar (itemDef_t *item, int handle)
qboolean ItemParse_maxChars (itemDef_t *item, int handle)
qboolean ItemParse_maxPaintChars (itemDef_t *item, int handle)
qboolean ItemParse_cvarFloat (itemDef_t *item, int handle)
qboolean ItemParse_cvarStrList (itemDef_t *item, int handle)
qboolean ItemParse_cvarFloatList (itemDef_t *item, int handle)
qboolean ItemParse_addColorRange (itemDef_t *item, int handle)
qboolean ItemParse_ownerdrawFlag (itemDef_t *item, int handle)
qboolean ItemParse_enableCvar (itemDef_t *item, int handle)
qboolean ItemParse_disableCvar (itemDef_t *item, int handle)
qboolean ItemParse_showCvar (itemDef_t *item, int handle)
qboolean ItemParse_hideCvar (itemDef_t *item, int handle)
qboolean Item_Parse (int handle, itemDef_t *item)
void Item_InitControls (itemDef_t *item)
qboolean MenuParse_font (itemDef_t *item, int handle)
qboolean MenuParse_name (itemDef_t *item, int handle)
qboolean MenuParse_fullscreen (itemDef_t *item, int handle)
qboolean MenuParse_rect (itemDef_t *item, int handle)
qboolean MenuParse_style (itemDef_t *item, int handle)
qboolean MenuParse_visible (itemDef_t *item, int handle)
qboolean MenuParse_onOpen (itemDef_t *item, int handle)
qboolean MenuParse_onClose (itemDef_t *item, int handle)
qboolean MenuParse_onESC (itemDef_t *item, int handle)
qboolean MenuParse_border (itemDef_t *item, int handle)
qboolean MenuParse_borderSize (itemDef_t *item, int handle)
qboolean MenuParse_backcolor (itemDef_t *item, int handle)
qboolean MenuParse_forecolor (itemDef_t *item, int handle)
qboolean MenuParse_bordercolor (itemDef_t *item, int handle)
qboolean MenuParse_focuscolor (itemDef_t *item, int handle)
qboolean MenuParse_disablecolor (itemDef_t *item, int handle)
qboolean MenuParse_outlinecolor (itemDef_t *item, int handle)
qboolean MenuParse_background (itemDef_t *item, int handle)
qboolean MenuParse_cinematic (itemDef_t *item, int handle)
qboolean MenuParse_ownerdrawFlag (itemDef_t *item, int handle)
qboolean MenuParse_ownerdraw (itemDef_t *item, int handle)
qboolean MenuParse_popup (itemDef_t *item, int handle)
qboolean MenuParse_outOfBounds (itemDef_t *item, int handle)
qboolean MenuParse_soundLoop (itemDef_t *item, int handle)
qboolean MenuParse_fadeClamp (itemDef_t *item, int handle)
qboolean MenuParse_fadeAmount (itemDef_t *item, int handle)
qboolean MenuParse_fadeCycle (itemDef_t *item, int handle)
qboolean MenuParse_itemDef (itemDef_t *item, int handle)
qboolean Menu_Parse (int handle, menuDef_t *menu)
void Menu_New (int handle)
int Menu_Count (void)
void Menu_PaintAll (void)
void Menu_Reset (void)
displayContextDef_t * Display_GetContext (void)
void * Display_CaptureItem (int x, int y)
qboolean Display_MouseMove (void *p, int x, int y)
int Display_CursorType (int x, int y)
void Display_HandleKey (int key, qboolean down, int x, int y)
static void Window_CacheContents (windowDef_t *window)
static void Item_CacheContents (itemDef_t *item)
static void Menu_CacheContents (menuDef_t *menu)
void Display_CacheAll (void)
Variables
static scrollInfo_t scrollInfo
static void(* captureFunc)(void *p)=0
static void * captureData = NULL
static itemDef_t * itemCapture = NULL
displayContextDef_t * DC = NULL
static qboolean g_waitingForKey = qfalse
static qboolean g_editingField = qfalse
static itemDef_t * g_bindItem = NULL
static itemDef_t * g_editItem = NULL
menuDef_t Menus [MAX_MENUS]
int menuCount = 0
menuDef_t * menuStack [MAX_OPEN_MENUS]
int openMenuCount = 0
static qboolean debugMode = qfalse
static int lastListBoxClickTime = 0
static char memoryPool [MEM_POOL_SIZE]
static int allocPoint
static int outOfMemory
static int strPoolIndex = 0
static char strPool [STRING_POOL_SIZE]
static int strHandleCount = 0
static stringDef_t * strHandle [HASH_TABLE_SIZE]
commandDef_t commandList []
int scriptCommandCount = ARRAY_LEN(commandList)
static bind_t g_bindings []
static const int g_bindCount = ARRAY_LEN(g_bindings)
static configcvar_t g_configcvars []
char g_nameBind1 [32]
char g_nameBind2 [32]
keywordHash_t itemParseKeywords []
keywordHash_t * itemParseKeywordHash [KEYWORDHASH_SIZE]
keywordHash_t menuParseKeywords []
keywordHash_t * menuParseKeywordHash [KEYWORDHASH_SIZE]
static float captureX
static float captureY
Define Documentation
#define DOUBLE_CLICK_DELAY 300
Referenced by Item_ListBox_HandleKey().
#define HASH_TABLE_SIZE 2048
Referenced by hashForString(), and String_Init().
#define KEYWORDHASH_SIZE 512
Referenced by KeywordHash_Key().
#define MEM_POOL_SIZE 1024 * 1024
Referenced by String_Report(), and UI_Alloc().
#define SCROLL_TIME_ADJUST 150
Referenced by Item_StartCapture(), Scroll_ListBox_AutoFunc(), and Scroll_ListBox_ThumbFunc().
#define SCROLL_TIME_ADJUSTOFFSET 40
Referenced by Scroll_ListBox_AutoFunc(), and Scroll_ListBox_ThumbFunc().
#define SCROLL_TIME_FLOOR 20
Referenced by Scroll_ListBox_AutoFunc(), and Scroll_ListBox_ThumbFunc().
#define SCROLL_TIME_START 500
Referenced by Item_StartCapture().
Typedef Documentation
typedef struct keywordHash_s keywordHash_t
typedef struct scrollInfo_s scrollInfo_t
typedef struct stringDef_s stringDef_t
Function Documentation
static __attribute__ ((format(printf, 2, 3))) [static]
References Com_Printf(), line, Q_vsnprintf, S_COLOR_RED, and trap_PC_SourceFileAndLine().
void AdjustFrom640 (float * x, float * y, float * w, float * h)
References displayContextDef_t::xscale, and displayContextDef_t::yscale.
Referenced by Item_Model_Paint().
void BindingFromName (const char * cvar)
References b1, b2, bind_t::bind1, bind_t::bind2, g_bindCount, displayContextDef_t::keynumToStringBuf, Q_stricmp(), and Q_strupr().
Referenced by Item_Bind_Paint().
int BindingIDFromName (const char * name)
References g_bindCount, and Q_stricmp().
Referenced by Item_Bind_HandleKey().
qboolean Color_Parse (char ** p, vec4_t * c)
References Float_Parse(), qfalse, and qtrue.
Referenced by Script_SetItemColor().
void Controls_GetConfig (void)
References bind_t::bind1, bind_t::bind2, Controls_GetKeyAssignment(), and g_bindCount.
static void Controls_GetKeyAssignment (char * command, int * twokeys) [static]
References b, count, displayContextDef_t::getBindingBuf, and Q_stricmp().
Referenced by Controls_GetConfig().
void Controls_SetConfig (qboolean restart)
References EXEC_APPEND, displayContextDef_t::executeText, g_bindCount, and displayContextDef_t::setBinding.
void Controls_SetDefaults (void)
References bind_t::bind1, bind_t::bind2, bind_t::defaultbind1, bind_t::defaultbind2, and g_bindCount.
void Display_CacheAll (void)
References Menu_CacheContents(), and menuCount.
Referenced by UI_Cache_f().
void* Display_CaptureItem (int x, int y)
References menuCount, NULL, and Rect_ContainsPoint().
Referenced by CG_KeyEvent(), and Display_HandleKey().
static void Display_CloseCinematics (void) [static]
References Menu_CloseCinematics(), and menuCount.
Referenced by Menus_Activate(), Menus_ActivateByName(), and Menus_HandleOOBClick().
int Display_CursorType (int x, int y)
References CURSOR_ARROW, CURSOR_SIZER, rectDef_t::h, menuCount, r2, windowDef_t::rect, Rect_ContainsPoint(), rectDef_t::w, menuDef_t::window, rectDef_t::x, and rectDef_t::y.
Referenced by CG_MouseEvent().
displayContextDef_t* Display_GetContext (void)
References DC.
void Display_HandleKey (int key, qboolean down, int x, int y)
References Display_CaptureItem(), Menu_GetFocused(), Menu_HandleKey(), and NULL.
Referenced by CG_KeyEvent().
qboolean Display_KeyBindPending (void)
References g_waitingForKey.
Referenced by UI_DrawKeyBindStatus(), and UI_OwnerDrawWidth().
qboolean Display_MouseMove (void * p, int x, int y)
References windowDef_t::flags, Menu_GetFocused(), Menu_HandleMouseMove(), Menu_UpdatePosition(), menuCount, NULL, qtrue, windowDef_t::rect, menuDef_t::window, WINDOW_POPUP, rectDef_t::x, and rectDef_t::y.
Referenced by _UI_MouseEvent(), CG_MouseEvent(), and Menu_HandleKey().
int Display_VisibleMenuCount (void)
References count, menuCount, WINDOW_FORCED, and WINDOW_VISIBLE.
Referenced by Menus_HandleOOBClick().
void Fade (int * flags, float * f, float clamp, int * nextTime, int offsetTime, qboolean bFlags, float fadeAmount)
References displayContextDef_t::realTime, WINDOW_FADINGIN, WINDOW_FADINGOUT, and WINDOW_VISIBLE.
Referenced by Item_OwnerDraw_Paint(), Item_TextColor(), and Window_Paint().
qboolean Float_Parse (char ** p, float * f)
References COM_ParseExt(), qfalse, qtrue, and token.
Referenced by Color_Parse(), Rect_Parse(), Script_Orbit(), Script_SetColor(), and Script_Transition().
void GradientBar_Paint (rectDef_t * rect, vec4_t color)
References displayContextDef_t::Assets, displayContextDef_t::drawHandlePic, cachedAssets_t::gradientBar, rectDef_t::h, NULL, displayContextDef_t::setColor, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by Window_Paint().
static unsigned hashForString (const char * str) [static]
References hash(), and HASH_TABLE_SIZE.
Referenced by String_Alloc().
void Init_Display (displayContextDef_t * dc)
Referenced by _UI_Init().
qboolean Int_Parse (char ** p, int * i)
References COM_ParseExt(), qfalse, qtrue, and token.
Referenced by GameType_Parse(), MapList_Parse(), Script_Orbit(), Script_Transition(), and UI_RunMenuScript().
qboolean IsVisible (int flags)
References WINDOW_FADINGOUT, and WINDOW_VISIBLE.
Referenced by Menu_HandleMouseMove().
void Item_Action (itemDef_t * item)
References itemDef_s::action, and Item_RunScript().
Referenced by Menu_HandleKey().
qboolean Item_Bind_HandleKey (itemDef_t * item, int key, qboolean down)
References bind_t::bind1, bind_t::bind2, BindingIDFromName(), Controls_SetConfig(), displayContextDef_t::cursorx, displayContextDef_t::cursory, itemDef_s::cvar, g_bindCount, g_waitingForKey, K_BACKSPACE, K_CHAR_FLAG, K_ENTER, K_ESCAPE, K_MOUSE1, NULL, qfalse, qtrue, windowDef_t::rect, Rect_ContainsPoint(), displayContextDef_t::setBinding, and itemDef_s::window.
Referenced by Item_HandleKey(), and Menu_HandleKey().
void Item_Bind_Paint (itemDef_t * item)
References BindingFromName(), itemDef_s::cvar, displayContextDef_t::drawText, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, Item_Text_Paint(), LerpColor(), itemDef_s::parent, PULSE_DIVISOR, displayContextDef_t::realTime, itemDef_s::text, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
static void Item_CacheContents (itemDef_t * item) [static]
References itemDef_s::window, and Window_CacheContents().
Referenced by Menu_CacheContents().
static rectDef_t* Item_CorrectedTextRect (itemDef_t * item) [static]
References rectDef_t::h, itemDef_s::textRect, rectDef_t::w, and rectDef_t::y.
Referenced by Item_Paint(), Menu_HandleKey(), Menu_HandleMouseMove(), and Menu_OverActiveItem().
qboolean Item_EnableShowViaCvar (itemDef_t * item, int flag)
References itemDef_s::cvarFlags, itemDef_s::cvarTest, itemDef_s::enableCvar, displayContextDef_t::getCVarString, Q_strcat(), Q_stricmp(), qfalse, qtrue, String_Parse(), and val.
Referenced by Item_MouseEnter(), Item_OwnerDraw_Paint(), Item_Paint(), Item_SetFocus(), Item_TextColor(), and Menu_HandleMouseMove().
qboolean Item_HandleKey (itemDef_t * item, int key, qboolean down)
References captureData, captureFunc, Item_Bind_HandleKey(), Item_ListBox_HandleKey(), Item_Multi_HandleKey(), Item_OwnerDraw_HandleKey(), Item_Slider_HandleKey(), Item_StartCapture(), Item_StopCapture(), ITEM_TYPE_BIND, ITEM_TYPE_BUTTON, ITEM_TYPE_CHECKBOX, ITEM_TYPE_COMBO, ITEM_TYPE_EDITFIELD, ITEM_TYPE_LISTBOX, ITEM_TYPE_MULTI, ITEM_TYPE_NUMERICFIELD, ITEM_TYPE_OWNERDRAW, ITEM_TYPE_RADIOBUTTON, ITEM_TYPE_SLIDER, ITEM_TYPE_YESNO, Item_YesNo_HandleKey(), K_MOUSE1, K_MOUSE2, K_MOUSE3, NULL, qfalse, and itemDef_s::type.
Referenced by Menu_HandleKey().
void Item_Image_Paint (itemDef_t * item)
References itemDef_s::asset, displayContextDef_t::drawHandlePic, rectDef_t::h, NULL, windowDef_t::rect, rectDef_t::w, itemDef_s::window, rectDef_t::x, and rectDef_t::y.
void Item_Init (itemDef_t * item)
References itemDef_s::textscale, itemDef_s::window, and Window_Init().
Referenced by MenuParse_itemDef().
void Item_InitControls (itemDef_t * item)
References listBoxDef_s::cursorPos, itemDef_s::cursorPos, listBoxDef_s::endPos, if(), ITEM_TYPE_LISTBOX, NULL, listBoxDef_s::startPos, itemDef_s::type, and itemDef_s::typeData.
Referenced by MenuParse_itemDef().
qboolean Item_ListBox_HandleKey (itemDef_t * item, int key, qboolean down, qboolean force)
References listBoxDef_s::cursorPos, itemDef_s::cursorPos, displayContextDef_t::cursorx, displayContextDef_t::cursory, DOUBLE_CLICK_DELAY, listBoxDef_s::doubleClick, listBoxDef_s::elementHeight, listBoxDef_s::elementWidth, displayContextDef_t::feederCount, displayContextDef_t::feederSelection, windowDef_t::flags, rectDef_t::h, Item_ListBox_MaxScroll(), Item_RunScript(), K_DOWNARROW, K_END, K_HOME, K_KP_DOWNARROW, K_KP_END, K_KP_HOME, K_KP_LEFTARROW, K_KP_PGDN, K_KP_PGUP, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_MOUSE2, K_PGDN, K_PGUP, K_RIGHTARROW, K_UPARROW, lastListBoxClickTime, listBoxDef_s::notselectable, qfalse, qtrue, displayContextDef_t::realTime, windowDef_t::rect, Rect_ContainsPoint(), itemDef_s::special, listBoxDef_s::startPos, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, WINDOW_HORIZONTAL, WINDOW_LB_LEFTARROW, WINDOW_LB_PGDN, WINDOW_LB_PGUP, WINDOW_LB_RIGHTARROW, and WINDOW_LB_THUMB.
Referenced by Item_HandleKey(), Menu_ScrollFeeder(), Scroll_ListBox_AutoFunc(), and Scroll_ListBox_ThumbFunc().
int Item_ListBox_MaxScroll (itemDef_t * item)
References listBoxDef_s::elementHeight, listBoxDef_s::elementWidth, displayContextDef_t::feederCount, windowDef_t::flags, rectDef_t::h, windowDef_t::rect, itemDef_s::special, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, and WINDOW_HORIZONTAL.
Referenced by Item_ListBox_HandleKey(), Item_ListBox_ThumbPosition(), and Scroll_ListBox_ThumbFunc().
void Item_ListBox_MouseEnter (itemDef_t * item, float x, float y)
References listBoxDef_s::cursorPos, listBoxDef_s::drawPadding, listBoxDef_s::elementHeight, listBoxDef_s::elementStyle, listBoxDef_s::elementWidth, listBoxDef_s::endPos, windowDef_t::flags, rectDef_t::h, if(), int(), Item_ListBox_OverLB(), LISTBOX_IMAGE, windowDef_t::rect, Rect_ContainsPoint(), SCROLLBAR_SIZE, listBoxDef_s::startPos, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, WINDOW_HORIZONTAL, WINDOW_LB_LEFTARROW, WINDOW_LB_PGDN, WINDOW_LB_PGUP, WINDOW_LB_RIGHTARROW, WINDOW_LB_THUMB, rectDef_t::x, and rectDef_t::y.
Referenced by Item_MouseEnter().
int Item_ListBox_OverLB (itemDef_t * item, float x, float y)
References windowDef_t::flags, rectDef_t::h, Item_ListBox_ThumbPosition(), windowDef_t::rect, Rect_ContainsPoint(), SCROLLBAR_SIZE, rectDef_t::w, itemDef_s::window, WINDOW_HORIZONTAL, WINDOW_LB_LEFTARROW, WINDOW_LB_PGDN, WINDOW_LB_PGUP, WINDOW_LB_RIGHTARROW, WINDOW_LB_THUMB, rectDef_t::x, and rectDef_t::y.
Referenced by Item_ListBox_MouseEnter(), and Item_StartCapture().
void Item_ListBox_Paint (itemDef_t * item)
References displayContextDef_t::Assets, windowDef_t::borderColor, windowDef_t::borderSize, listBoxDef_s::columnInfo, count, itemDef_s::cursorPos, displayContextDef_t::drawHandlePic, listBoxDef_s::drawPadding, displayContextDef_t::drawRect, displayContextDef_t::drawText, listBoxDef_s::elementHeight, listBoxDef_s::elementStyle, listBoxDef_s::elementWidth, listBoxDef_s::endPos, displayContextDef_t::feederCount, displayContextDef_t::feederItemImage, displayContextDef_t::feederItemText, displayContextDef_t::fillRect, windowDef_t::flags, windowDef_t::foreColor, rectDef_t::h, Item_ListBox_ThumbDrawPosition(), LISTBOX_IMAGE, columnInfo_s::maxChars, listBoxDef_s::numColumns, windowDef_t::outlineColor, columnInfo_s::pos, windowDef_t::rect, cachedAssets_t::scrollBar, SCROLLBAR_SIZE, cachedAssets_t::scrollBarArrowDown, cachedAssets_t::scrollBarArrowLeft, cachedAssets_t::scrollBarArrowRight, cachedAssets_t::scrollBarArrowUp, cachedAssets_t::scrollBarThumb, itemDef_s::special, listBoxDef_s::startPos, itemDef_s::textscale, itemDef_s::textStyle, itemDef_s::typeData, rectDef_t::w, columnInfo_s::width, itemDef_s::window, WINDOW_HORIZONTAL, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
int Item_ListBox_ThumbDrawPosition (itemDef_t * item)
References displayContextDef_t::cursorx, displayContextDef_t::cursory, windowDef_t::flags, rectDef_t::h, Item_ListBox_ThumbPosition(), windowDef_t::rect, SCROLLBAR_SIZE, rectDef_t::w, itemDef_s::window, WINDOW_HORIZONTAL, rectDef_t::x, and rectDef_t::y.
Referenced by Item_ListBox_Paint().
int Item_ListBox_ThumbPosition (itemDef_t * item)
References windowDef_t::flags, rectDef_t::h, Item_ListBox_MaxScroll(), windowDef_t::rect, SCROLLBAR_SIZE, listBoxDef_s::startPos, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, WINDOW_HORIZONTAL, rectDef_t::x, and rectDef_t::y.
Referenced by Item_ListBox_OverLB(), and Item_ListBox_ThumbDrawPosition().
void Item_Model_Paint (itemDef_t * item)
References displayContextDef_t::addRefEntityToScene, AdjustFrom640(), modelDef_s::angle, AnglesToAxis(), itemDef_s::asset, refEntity_t::axis, AxisClear(), displayContextDef_t::clearScene, refdef_t::fov_x, modelDef_s::fov_x, refdef_t::fov_y, modelDef_s::fov_y, h, rectDef_t::h, refdef_t::height, refEntity_t::hModel, if(), int(), refEntity_t::lightingOrigin, displayContextDef_t::modelBounds, windowDef_t::nextTime, NULL, refEntity_t::oldorigin, refEntity_t::origin, qtrue, RDF_NOWORLDMODEL, refdef_t::rdflags, displayContextDef_t::realTime, windowDef_t::rect, refEntity_t::renderfx, displayContextDef_t::renderScene, RF_LIGHTING_ORIGIN, RF_NOSHADOW, modelDef_s::rotationSpeed, itemDef_s::textscale, refdef_t::time, itemDef_s::typeData, VectorCopy, VectorSet, refdef_t::viewaxis, rectDef_t::w, refdef_t::width, itemDef_s::window, rectDef_t::x, refdef_t::x, rectDef_t::y, and refdef_t::y.
Referenced by Item_Paint().
void Item_MouseEnter (itemDef_t * item, float x, float y)
References CVAR_DISABLE, CVAR_ENABLE, CVAR_HIDE, CVAR_SHOW, itemDef_s::cvarFlags, windowDef_t::flags, rectDef_t::h, Item_EnableShowViaCvar(), Item_ListBox_MouseEnter(), Item_RunScript(), ITEM_TYPE_LISTBOX, itemDef_s::mouseEnter, itemDef_s::mouseEnterText, itemDef_s::mouseExitText, Rect_ContainsPoint(), itemDef_s::textRect, itemDef_s::type, itemDef_s::window, WINDOW_MOUSEOVER, WINDOW_MOUSEOVERTEXT, and rectDef_t::y.
Referenced by Menu_HandleMouseMove().
void Item_MouseLeave (itemDef_t * item)
References windowDef_t::flags, Item_RunScript(), itemDef_s::mouseExit, itemDef_s::mouseExitText, itemDef_s::window, WINDOW_LB_LEFTARROW, WINDOW_LB_RIGHTARROW, and WINDOW_MOUSEOVERTEXT.
Referenced by Menu_HandleMouseMove().
int Item_Multi_CountSettings (itemDef_t * item)
References multiDef_s::count, if(), NULL, and itemDef_s::typeData.
Referenced by Item_Multi_HandleKey().
int Item_Multi_FindCvarByValue (itemDef_t * item)
References multiDef_s::count, itemDef_s::cvar, multiDef_s::cvarStr, multiDef_s::cvarValue, displayContextDef_t::getCVarString, displayContextDef_t::getCVarValue, if(), Q_stricmp(), multiDef_s::strDef, and itemDef_s::typeData.
Referenced by Item_Multi_HandleKey().
qboolean Item_Multi_HandleKey (itemDef_t * item, int key)
References current, displayContextDef_t::cursorx, displayContextDef_t::cursory, itemDef_s::cvar, multiDef_s::cvarStr, multiDef_s::cvarValue, windowDef_t::flags, if(), Item_Multi_CountSettings(), Item_Multi_FindCvarByValue(), K_ENTER, K_MOUSE1, K_MOUSE2, K_MOUSE3, qfalse, qtrue, windowDef_t::rect, Rect_ContainsPoint(), displayContextDef_t::setCVar, multiDef_s::strDef, itemDef_s::typeData, va(), itemDef_s::window, and WINDOW_HASFOCUS.
Referenced by Item_HandleKey().
void Item_Multi_Paint (itemDef_t * item)
References displayContextDef_t::drawText, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, if(), Item_Multi_Setting(), Item_Text_Paint(), LerpColor(), itemDef_s::parent, PULSE_DIVISOR, displayContextDef_t::realTime, itemDef_s::text, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
const char* Item_Multi_Setting (itemDef_t * item)
References multiDef_s::count, itemDef_s::cvar, multiDef_s::cvarList, multiDef_s::cvarStr, multiDef_s::cvarValue, displayContextDef_t::getCVarString, displayContextDef_t::getCVarValue, if(), Q_stricmp(), multiDef_s::strDef, and itemDef_s::typeData.
Referenced by Item_Multi_Paint().
qboolean Item_OwnerDraw_HandleKey (itemDef_t * item, int key)
References windowDef_t::ownerDraw, windowDef_t::ownerDrawFlags, displayContextDef_t::ownerDrawHandleKey, qfalse, itemDef_s::special, and itemDef_s::window.
Referenced by Item_HandleKey().
void Item_OwnerDraw_Paint (itemDef_t * item)
References itemDef_s::alignment, windowDef_t::background, BLINK_DIVISOR, colorRangeDef_t::color, itemDef_s::colorRanges, Com_Memcpy, CVAR_DISABLE, CVAR_ENABLE, itemDef_s::cvarFlags, menuDef_t::disableColor, Fade(), menuDef_t::fadeAmount, menuDef_t::fadeClamp, menuDef_t::fadeCycle, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, displayContextDef_t::getValue, rectDef_t::h, Item_EnableShowViaCvar(), Item_Text_Paint(), ITEM_TEXTSTYLE_BLINK, LerpColor(), colorRangeDef_t::low, windowDef_t::nextTime, NULL, itemDef_s::numColors, windowDef_t::ownerDraw, windowDef_t::ownerDrawFlags, displayContextDef_t::ownerDrawItem, itemDef_s::parent, PULSE_DIVISOR, qtrue, displayContextDef_t::realTime, windowDef_t::rect, itemDef_s::special, itemDef_s::text, itemDef_s::textalignx, itemDef_s::textaligny, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
void Item_Paint (itemDef_t * item)
References CVAR_HIDE, CVAR_SHOW, itemDef_s::cvarFlags, debugMode, displayContextDef_t::drawRect, menuDef_t::fadeAmount, menuDef_t::fadeClamp, menuDef_t::fadeCycle, windowDef_t::flags, h, rectDef_t::h, if(), Item_Bind_Paint(), Item_CorrectedTextRect(), Item_EnableShowViaCvar(), Item_ListBox_Paint(), Item_Model_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Slider_Paint(), Item_Text_Paint(), Item_TextField_Paint(), ITEM_TYPE_BIND, ITEM_TYPE_BUTTON, ITEM_TYPE_CHECKBOX, ITEM_TYPE_COMBO, ITEM_TYPE_EDITFIELD, ITEM_TYPE_LISTBOX, ITEM_TYPE_MODEL, ITEM_TYPE_MULTI, ITEM_TYPE_NUMERICFIELD, ITEM_TYPE_OWNERDRAW, ITEM_TYPE_RADIOBUTTON, ITEM_TYPE_SLIDER, ITEM_TYPE_TEXT, ITEM_TYPE_YESNO, Item_UpdatePosition(), Item_YesNo_Paint(), M_PI, windowDef_t::nextTime, NULL, windowDef_t::offsetTime, windowDef_t::ownerDrawFlags, displayContextDef_t::ownerDrawVisible, itemDef_s::parent, displayContextDef_t::realTime, windowDef_t::rectClient, windowDef_t::rectEffects, windowDef_t::rectEffects2, s, itemDef_s::type, rectDef_t::w, itemDef_s::window, WINDOW_INTRANSITION, WINDOW_ORBITING, Window_Paint(), WINDOW_TIMEDVISIBLE, WINDOW_VISIBLE, rectDef_t::x, and rectDef_t::y.
Referenced by Menu_Paint().
qboolean Item_Parse (int handle, itemDef_t * item)
References keywordHash_s::func, KeywordHash_Find(), qfalse, qtrue, pc_token_s::string, token, and trap_PC_ReadToken().
Referenced by MenuParse_itemDef().
void Item_RunScript (itemDef_t * item, const char * s)
References commandDef_t::handler, Q_strcat(), Q_stricmp(), qfalse, qtrue, displayContextDef_t::runScript, scriptCommandCount, and String_Parse().
Referenced by Item_Action(), Item_ListBox_HandleKey(), Item_MouseEnter(), Item_MouseLeave(), Item_SetFocus(), Menu_ClearFocus(), Menu_HandleKey(), Menu_RunCloseScript(), Menus_Activate(), and Script_SetFocus().
qboolean Item_SetFocus (itemDef_t * item, float x, float y)
References displayContextDef_t::Assets, CHAN_LOCAL_SOUND, menuDef_t::cursorItem, CVAR_DISABLE, CVAR_ENABLE, CVAR_HIDE, CVAR_SHOW, itemDef_s::cvarFlags, windowDef_t::flags, itemDef_s::focusSound, rectDef_t::h, if(), Item_EnableShowViaCvar(), Item_RunScript(), ITEM_TYPE_TEXT, menuDef_t::itemCount, cachedAssets_t::itemFocusSound, menuDef_t::items, Menu_ClearFocus(), NULL, itemDef_s::onFocus, itemDef_s::parent, qfalse, qtrue, Rect_ContainsPoint(), displayContextDef_t::startLocalSound, itemDef_s::textRect, itemDef_s::type, itemDef_s::window, WINDOW_DECORATION, WINDOW_HASFOCUS, WINDOW_VISIBLE, and rectDef_t::y.
Referenced by Menu_HandleMouseMove(), Menu_SetNextCursorItem(), and Menu_SetPrevCursorItem().
void Item_SetMouseOver (itemDef_t * item, qboolean focus)
References windowDef_t::flags, itemDef_s::window, and WINDOW_MOUSEOVER.
Referenced by Menu_HandleMouseMove().
void Item_SetScreenCoords (itemDef_t * item, float x, float y)
References windowDef_t::border, windowDef_t::borderSize, rectDef_t::h, NULL, windowDef_t::rect, windowDef_t::rectClient, itemDef_s::textRect, rectDef_t::w, itemDef_s::window, rectDef_t::x, and rectDef_t::y.
Referenced by Item_UpdatePosition(), and Menu_UpdatePosition().
void Item_SetTextExtents (itemDef_t * item, int * width, int * height, const char * text)
References itemDef_s::cvar, displayContextDef_t::getCVarString, rectDef_t::h, height, if(), ITEM_ALIGN_CENTER, ITEM_ALIGN_RIGHT, ITEM_TYPE_EDITFIELD, ITEM_TYPE_OWNERDRAW, NULL, windowDef_t::ownerDraw, displayContextDef_t::ownerDrawWidth, itemDef_s::text, itemDef_s::textalignment, itemDef_s::textalignx, itemDef_s::textaligny, displayContextDef_t::textHeight, itemDef_s::textRect, itemDef_s::textscale, displayContextDef_t::textWidth, ToWindowCoords(), itemDef_s::type, rectDef_t::w, width, itemDef_s::window, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), and Item_Text_Wrapped_Paint().
void Item_SetupKeywordHash (void)
References keywordHash_s::keyword, and KeywordHash_Add().
Referenced by String_Init().
qboolean Item_Slider_HandleKey (itemDef_t * item, int key, qboolean down)
References displayContextDef_t::cursorx, displayContextDef_t::cursory, itemDef_s::cvar, windowDef_t::flags, K_ENTER, K_MOUSE1, K_MOUSE2, K_MOUSE3, editFieldDef_s::maxVal, editFieldDef_s::minVal, displayContextDef_t::Print, qfalse, qtrue, windowDef_t::rect, Rect_ContainsPoint(), displayContextDef_t::setCVar, SLIDER_THUMB_WIDTH, SLIDER_WIDTH, itemDef_s::text, itemDef_s::textRect, itemDef_s::typeData, va(), value(), rectDef_t::w, width, itemDef_s::window, WINDOW_HASFOCUS, and rectDef_t::x.
Referenced by Item_HandleKey().
int Item_Slider_OverSlider (itemDef_t * item, float x, float y)
References rectDef_t::h, Item_Slider_ThumbPosition(), windowDef_t::rect, Rect_ContainsPoint(), SLIDER_THUMB_HEIGHT, SLIDER_THUMB_WIDTH, rectDef_t::w, itemDef_s::window, WINDOW_LB_THUMB, rectDef_t::x, and rectDef_t::y.
Referenced by Item_StartCapture().
void Item_Slider_Paint (itemDef_t * item)
References displayContextDef_t::Assets, displayContextDef_t::drawHandlePic, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, if(), Item_Slider_ThumbPosition(), Item_Text_Paint(), LerpColor(), itemDef_s::parent, PULSE_DIVISOR, displayContextDef_t::realTime, windowDef_t::rect, displayContextDef_t::setColor, SLIDER_HEIGHT, SLIDER_THUMB_HEIGHT, SLIDER_THUMB_WIDTH, SLIDER_WIDTH, cachedAssets_t::sliderBar, cachedAssets_t::sliderThumb, itemDef_s::text, itemDef_s::textRect, rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
float Item_Slider_ThumbPosition (itemDef_t * item)
References itemDef_s::cvar, displayContextDef_t::getCVarValue, editFieldDef_s::maxVal, editFieldDef_s::minVal, NULL, range(), windowDef_t::rect, SLIDER_WIDTH, itemDef_s::text, itemDef_s::textRect, itemDef_s::typeData, value(), rectDef_t::w, itemDef_s::window, and rectDef_t::x.
Referenced by Item_Slider_OverSlider(), and Item_Slider_Paint().
void Item_StartCapture (itemDef_t * item, int key)
References scrollInfo_s::adjustValue, captureData, captureFunc, displayContextDef_t::cursorx, displayContextDef_t::cursory, scrollInfo_s::item, Item_ListBox_OverLB(), Item_Slider_OverSlider(), ITEM_TYPE_EDITFIELD, ITEM_TYPE_LISTBOX, ITEM_TYPE_NUMERICFIELD, ITEM_TYPE_SLIDER, scrollInfo_s::nextAdjustTime, scrollInfo_s::nextScrollTime, qfalse, qtrue, displayContextDef_t::realTime, Scroll_ListBox_AutoFunc(), Scroll_ListBox_ThumbFunc(), Scroll_Slider_ThumbFunc(), SCROLL_TIME_ADJUST, SCROLL_TIME_START, scrollInfo_s::scrollDir, scrollInfo, scrollInfo_s::scrollKey, itemDef_s::type, WINDOW_LB_LEFTARROW, WINDOW_LB_RIGHTARROW, WINDOW_LB_THUMB, scrollInfo_s::xStart, and scrollInfo_s::yStart.
Referenced by Item_HandleKey().
void Item_StopCapture (itemDef_t * item)
Referenced by Item_HandleKey().
void Item_Text_AutoWrapped_Paint (itemDef_t * item)
References itemDef_s::cvar, displayContextDef_t::drawText, displayContextDef_t::getCVarString, height, ITEM_ALIGN_CENTER, ITEM_ALIGN_LEFT, ITEM_ALIGN_RIGHT, Item_SetTextExtents(), Item_TextColor(), NULL, windowDef_t::rect, itemDef_s::text, itemDef_s::textalignment, itemDef_s::textalignx, itemDef_s::textaligny, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, displayContextDef_t::textWidth, ToWindowCoords(), rectDef_t::w, width, itemDef_s::window, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Text_Paint().
void Item_Text_Paint (itemDef_t * item)
References itemDef_s::cvar, displayContextDef_t::drawText, windowDef_t::flags, displayContextDef_t::getCVarString, height, Item_SetTextExtents(), Item_Text_AutoWrapped_Paint(), Item_Text_Wrapped_Paint(), Item_TextColor(), NULL, itemDef_s::text, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, width, itemDef_s::window, WINDOW_AUTOWRAPPED, WINDOW_WRAPPED, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Bind_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Paint(), Item_Slider_Paint(), Item_TextField_Paint(), and Item_YesNo_Paint().
void Item_Text_Wrapped_Paint (itemDef_t * item)
References itemDef_s::cvar, displayContextDef_t::drawText, displayContextDef_t::getCVarString, height, Item_SetTextExtents(), Item_TextColor(), NULL, start, itemDef_s::text, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, width, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Text_Paint().
void Item_TextColor (itemDef_t * item, vec4_t * newColor)
References BLINK_DIVISOR, CVAR_DISABLE, CVAR_ENABLE, itemDef_s::cvarFlags, itemDef_s::cvarTest, menuDef_t::disableColor, itemDef_s::enableCvar, Fade(), menuDef_t::fadeAmount, menuDef_t::fadeClamp, menuDef_t::fadeCycle, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, Item_EnableShowViaCvar(), ITEM_TEXTSTYLE_BLINK, LerpColor(), windowDef_t::nextTime, itemDef_s::parent, PULSE_DIVISOR, qtrue, displayContextDef_t::realTime, itemDef_s::textStyle, itemDef_s::window, and WINDOW_HASFOCUS.
Referenced by Item_Text_AutoWrapped_Paint(), Item_Text_Paint(), and Item_Text_Wrapped_Paint().
qboolean Item_TextField_HandleKey (itemDef_t * item, int key)
References itemDef_s::cursorPos, itemDef_s::cvar, displayContextDef_t::getCVarString, displayContextDef_t::getOverstrikeMode, if(), ITEM_TYPE_EDITFIELD, ITEM_TYPE_NUMERICFIELD, K_CHAR_FLAG, K_DEL, K_DOWNARROW, K_END, K_ENTER, K_ESCAPE, K_HOME, K_INS, K_KP_DEL, K_KP_DOWNARROW, K_KP_END, K_KP_ENTER, K_KP_HOME, K_KP_INS, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_RIGHTARROW, K_TAB, K_UPARROW, MAX_EDITFIELD, editFieldDef_s::maxChars, editFieldDef_s::maxPaintChars, memmove(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), NULL, editFieldDef_s::paintOffset, itemDef_s::parent, qfalse, qtrue, displayContextDef_t::setCVar, displayContextDef_t::setOverstrikeMode, itemDef_s::type, and itemDef_s::typeData.
Referenced by Menu_HandleKey().
void Item_TextField_Paint (itemDef_t * item)
References itemDef_s::cursorPos, itemDef_s::cvar, displayContextDef_t::drawText, displayContextDef_t::drawTextWithCursor, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, g_editingField, displayContextDef_t::getCVarString, displayContextDef_t::getOverstrikeMode, Item_Text_Paint(), LerpColor(), itemDef_s::parent, PULSE_DIVISOR, displayContextDef_t::realTime, itemDef_s::text, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
void Item_UpdatePosition (itemDef_t * item)
References windowDef_t::border, windowDef_t::borderSize, Item_SetScreenCoords(), NULL, itemDef_s::parent, windowDef_t::rect, menuDef_t::window, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint(), Menu_OrbitItemByName(), and Menu_TransitionItemByName().
void Item_ValidateTypeData (itemDef_t * item)
References ITEM_TYPE_BIND, ITEM_TYPE_EDITFIELD, ITEM_TYPE_LISTBOX, ITEM_TYPE_MODEL, ITEM_TYPE_MULTI, ITEM_TYPE_NUMERICFIELD, ITEM_TYPE_SLIDER, ITEM_TYPE_TEXT, ITEM_TYPE_YESNO, MAX_EDITFIELD, itemDef_s::type, itemDef_s::typeData, and UI_Alloc().
Referenced by ItemParse_asset_model(), ItemParse_columns(), ItemParse_cvar(), ItemParse_cvarFloat(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), ItemParse_doubleClick(), ItemParse_elementheight(), ItemParse_elementtype(), ItemParse_elementwidth(), ItemParse_maxChars(), ItemParse_maxPaintChars(), ItemParse_model_angle(), ItemParse_model_fovx(), ItemParse_model_fovy(), ItemParse_model_origin(), ItemParse_model_rotation(), ItemParse_notselectable(), and ItemParse_type().
qboolean Item_YesNo_HandleKey (itemDef_t * item, int key)
References displayContextDef_t::cursorx, displayContextDef_t::cursory, itemDef_s::cvar, windowDef_t::flags, displayContextDef_t::getCVarValue, K_ENTER, K_MOUSE1, K_MOUSE2, K_MOUSE3, qfalse, qtrue, windowDef_t::rect, Rect_ContainsPoint(), displayContextDef_t::setCVar, va(), itemDef_s::window, and WINDOW_HASFOCUS.
Referenced by Item_HandleKey().
void Item_YesNo_Paint (itemDef_t * item)
References itemDef_s::cvar, displayContextDef_t::drawText, windowDef_t::flags, menuDef_t::focusColor, windowDef_t::foreColor, displayContextDef_t::getCVarValue, Item_Text_Paint(), LerpColor(), itemDef_s::parent, PULSE_DIVISOR, displayContextDef_t::realTime, itemDef_s::text, itemDef_s::textRect, itemDef_s::textscale, itemDef_s::textStyle, value(), rectDef_t::w, itemDef_s::window, WINDOW_HASFOCUS, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint().
qboolean ItemParse_action (itemDef_t * item, int handle)
References itemDef_s::action, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_addColorRange (itemDef_t * item, int handle)
References colorRangeDef_t::color, itemDef_s::colorRanges, colorRangeDef_t::high, colorRangeDef_t::low, MAX_COLOR_RANGES, itemDef_s::numColors, PC_Color_Parse(), PC_Float_Parse(), qfalse, and qtrue.
qboolean ItemParse_align (itemDef_t * item, int handle)
References itemDef_s::alignment, PC_Int_Parse(), qfalse, and qtrue.
qboolean ItemParse_asset_model (itemDef_t * item, int handle)
References modelDef_s::angle, itemDef_s::asset, if(), Item_ValidateTypeData(), PC_String_Parse(), qfalse, qtrue, displayContextDef_t::registerModel, and itemDef_s::typeData.
qboolean ItemParse_asset_shader (itemDef_t * item, int handle)
References itemDef_s::asset, PC_String_Parse(), qfalse, qtrue, and displayContextDef_t::registerShaderNoMip.
qboolean ItemParse_autowrapped (itemDef_t * item, int handle)
References windowDef_t::flags, qtrue, itemDef_s::window, and WINDOW_AUTOWRAPPED.
qboolean ItemParse_backcolor (itemDef_t * item, int handle)
References windowDef_t::backColor, PC_Float_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_background (itemDef_t * item, int handle)
References windowDef_t::background, PC_String_Parse(), qfalse, qtrue, displayContextDef_t::registerShaderNoMip, and itemDef_s::window.
qboolean ItemParse_border (itemDef_t * item, int handle)
References windowDef_t::border, PC_Int_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_bordercolor (itemDef_t * item, int handle)
References windowDef_t::borderColor, PC_Float_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_bordersize (itemDef_t * item, int handle)
References windowDef_t::borderSize, PC_Float_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_cinematic (itemDef_t * item, int handle)
References windowDef_t::cinematicName, PC_String_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_columns (itemDef_t * item, int handle)
References listBoxDef_s::columnInfo, if(), Item_ValidateTypeData(), MAX_LB_COLUMNS, columnInfo_s::maxChars, listBoxDef_s::numColumns, PC_Int_Parse(), columnInfo_s::pos, qfalse, qtrue, itemDef_s::typeData, width, and columnInfo_s::width.
qboolean ItemParse_cvar (itemDef_t * item, int handle)
References itemDef_s::cvar, editFieldDef_s::defVal, Item_ValidateTypeData(), editFieldDef_s::maxVal, editFieldDef_s::minVal, PC_String_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_cvarFloat (itemDef_t * item, int handle)
References itemDef_s::cvar, editFieldDef_s::defVal, if(), Item_ValidateTypeData(), editFieldDef_s::maxVal, editFieldDef_s::minVal, PC_Float_Parse(), PC_String_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_cvarFloatList (itemDef_t * item, int handle)
References multiDef_s::count, multiDef_s::cvarList, multiDef_s::cvarValue, if(), Item_ValidateTypeData(), MAX_MULTI_CVARS, PC_Float_Parse(), qfalse, qtrue, multiDef_s::strDef, pc_token_s::string, String_Alloc(), token, trap_PC_ReadToken(), and itemDef_s::typeData.
qboolean ItemParse_cvarStrList (itemDef_t * item, int handle)
References multiDef_s::count, multiDef_s::cvarList, multiDef_s::cvarStr, if(), Item_ValidateTypeData(), MAX_MULTI_CVARS, pass, qfalse, qtrue, multiDef_s::strDef, pc_token_s::string, String_Alloc(), token, trap_PC_ReadToken(), and itemDef_s::typeData.
qboolean ItemParse_cvarTest (itemDef_t * item, int handle)
References itemDef_s::cvarTest, PC_String_Parse(), qfalse, and qtrue.
qboolean ItemParse_decoration (itemDef_t * item, int handle)
References windowDef_t::flags, qtrue, itemDef_s::window, and WINDOW_DECORATION.
qboolean ItemParse_disableCvar (itemDef_t * item, int handle)
References CVAR_DISABLE, itemDef_s::cvarFlags, itemDef_s::enableCvar, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_doubleClick (itemDef_t * item, int handle)
References listBoxDef_s::doubleClick, if(), Item_ValidateTypeData(), PC_Script_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_elementheight (itemDef_t * item, int handle)
References listBoxDef_s::elementHeight, if(), Item_ValidateTypeData(), PC_Float_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_elementtype (itemDef_t * item, int handle)
References listBoxDef_s::elementStyle, if(), Item_ValidateTypeData(), PC_Int_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_elementwidth (itemDef_t * item, int handle)
References listBoxDef_s::elementWidth, if(), Item_ValidateTypeData(), PC_Float_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_enableCvar (itemDef_t * item, int handle)
References CVAR_ENABLE, itemDef_s::cvarFlags, itemDef_s::enableCvar, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_feeder (itemDef_t * item, int handle)
References PC_Float_Parse(), qfalse, qtrue, and itemDef_s::special.
qboolean ItemParse_focusSound (itemDef_t * item, int handle)
References itemDef_s::focusSound, PC_String_Parse(), qfalse, qtrue, and displayContextDef_t::registerSound.
qboolean ItemParse_forecolor (itemDef_t * item, int handle)
References windowDef_t::flags, windowDef_t::foreColor, PC_Float_Parse(), qfalse, qtrue, itemDef_s::window, and WINDOW_FORECOLORSET.
qboolean ItemParse_group (itemDef_t * item, int handle)
References windowDef_t::group, PC_String_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_hideCvar (itemDef_t * item, int handle)
References CVAR_HIDE, itemDef_s::cvarFlags, itemDef_s::enableCvar, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_horizontalscroll (itemDef_t * item, int handle)
References windowDef_t::flags, qtrue, itemDef_s::window, and WINDOW_HORIZONTAL.
qboolean ItemParse_leaveFocus (itemDef_t * item, int handle)
References itemDef_s::leaveFocus, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_maxChars (itemDef_t * item, int handle)
References Item_ValidateTypeData(), editFieldDef_s::maxChars, PC_Int_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_maxPaintChars (itemDef_t * item, int handle)
References Item_ValidateTypeData(), editFieldDef_s::maxPaintChars, PC_Int_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_model_angle (itemDef_t * item, int handle)
References modelDef_s::angle, if(), Item_ValidateTypeData(), PC_Int_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_model_fovx (itemDef_t * item, int handle)
References modelDef_s::fov_x, if(), Item_ValidateTypeData(), PC_Float_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_model_fovy (itemDef_t * item, int handle)
References modelDef_s::fov_y, if(), Item_ValidateTypeData(), PC_Float_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_model_origin (itemDef_t * item, int handle)
References if(), Item_ValidateTypeData(), modelDef_s::origin, PC_Float_Parse(), qfalse, qtrue, and itemDef_s::typeData.
qboolean ItemParse_model_rotation (itemDef_t * item, int handle)
References if(), Item_ValidateTypeData(), PC_Int_Parse(), qfalse, qtrue, modelDef_s::rotationSpeed, and itemDef_s::typeData.
qboolean ItemParse_mouseEnter (itemDef_t * item, int handle)
References itemDef_s::mouseEnter, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_mouseEnterText (itemDef_t * item, int handle)
References itemDef_s::mouseEnterText, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_mouseExit (itemDef_t * item, int handle)
References itemDef_s::mouseExit, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_mouseExitText (itemDef_t * item, int handle)
References itemDef_s::mouseExitText, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_name (itemDef_t * item, int handle)
References windowDef_t::name, PC_String_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_notselectable (itemDef_t * item, int handle)
References if(), ITEM_TYPE_LISTBOX, Item_ValidateTypeData(), listBoxDef_s::notselectable, qtrue, itemDef_s::type, and itemDef_s::typeData.
qboolean ItemParse_onFocus (itemDef_t * item, int handle)
References itemDef_s::onFocus, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_outlinecolor (itemDef_t * item, int handle)
References windowDef_t::outlineColor, PC_Color_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_ownerdraw (itemDef_t * item, int handle)
References ITEM_TYPE_OWNERDRAW, windowDef_t::ownerDraw, PC_Int_Parse(), qfalse, qtrue, itemDef_s::type, and itemDef_s::window.
qboolean ItemParse_ownerdrawFlag (itemDef_t * item, int handle)
References windowDef_t::ownerDrawFlags, PC_Int_Parse(), qfalse, qtrue, and itemDef_s::window.
qboolean ItemParse_rect (itemDef_t * item, int handle)
References PC_Rect_Parse(), qfalse, qtrue, windowDef_t::rectClient, and itemDef_s::window.
qboolean ItemParse_showCvar (itemDef_t * item, int handle)
References CVAR_SHOW, itemDef_s::cvarFlags, itemDef_s::enableCvar, PC_Script_Parse(), qfalse, and qtrue.
qboolean ItemParse_special (itemDef_t * item, int handle)
References PC_Float_Parse(), qfalse, qtrue, and itemDef_s::special.
qboolean ItemParse_style (itemDef_t * item, int handle)
References PC_Int_Parse(), qfalse, qtrue, windowDef_t::style, and itemDef_s::window.
qboolean ItemParse_text (itemDef_t * item, int handle)
References PC_String_Parse(), qfalse, qtrue, and itemDef_s::text.
qboolean ItemParse_textalign (itemDef_t * item, int handle)
References PC_Int_Parse(), qfalse, qtrue, and itemDef_s::textalignment.
qboolean ItemParse_textalignx (itemDef_t * item, int handle)
References PC_Float_Parse(), qfalse, qtrue, and itemDef_s::textalignx.
qboolean ItemParse_textaligny (itemDef_t * item, int handle)
References PC_Float_Parse(), qfalse, qtrue, and itemDef_s::textaligny.
qboolean ItemParse_textscale (itemDef_t * item, int handle)
References PC_Float_Parse(), qfalse, qtrue, and itemDef_s::textscale.
qboolean ItemParse_textstyle (itemDef_t * item, int handle)
References PC_Int_Parse(), qfalse, qtrue, and itemDef_s::textStyle.
qboolean ItemParse_type (itemDef_t * item, int handle)
References Item_ValidateTypeData(), PC_Int_Parse(), qfalse, qtrue, and itemDef_s::type.
qboolean ItemParse_visible (itemDef_t * item, int handle)
References windowDef_t::flags, PC_Int_Parse(), qfalse, qtrue, itemDef_s::window, and WINDOW_VISIBLE.
qboolean ItemParse_wrapped (itemDef_t * item, int handle)
References windowDef_t::flags, qtrue, itemDef_s::window, and WINDOW_WRAPPED.
void KeywordHash_Add (keywordHash_t * table[], keywordHash_t * key)
References hash(), keywordHash_s::keyword, KeywordHash_Key(), and keywordHash_s::next.
Referenced by Item_SetupKeywordHash(), and Menu_SetupKeywordHash().
keywordHash_t* KeywordHash_Find (keywordHash_t * table[], char * keyword)
References hash(), keywordHash_s::keyword, KeywordHash_Key(), keywordHash_s::next, NULL, and Q_stricmp().
Referenced by Item_Parse(), and Menu_Parse().
int KeywordHash_Key (char * keyword)
References hash(), and KEYWORDHASH_SIZE.
Referenced by KeywordHash_Add(), and KeywordHash_Find().
void LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Referenced by Item_Bind_Paint(), Item_Multi_Paint(), Item_OwnerDraw_Paint(), Item_Slider_Paint(), Item_TextColor(), Item_TextField_Paint(), Item_YesNo_Paint(), and UI_DrawServerRefreshDate().
static void Menu_CacheContents (menuDef_t * menu) [static]
References Item_CacheContents(), menuDef_t::itemCount, menuDef_t::items, qfalse, displayContextDef_t::registerSound, menuDef_t::soundName, menuDef_t::window, and Window_CacheContents().
Referenced by Display_CacheAll().
itemDef_t* Menu_ClearFocus (menuDef_t * menu)
References windowDef_t::flags, Item_RunScript(), menuDef_t::itemCount, menuDef_t::items, itemDef_s::leaveFocus, NULL, itemDef_s::window, and WINDOW_HASFOCUS.
Referenced by Item_SetFocus(), and Script_SetFocus().
static void Menu_CloseCinematics (menuDef_t * menu) [static]
References ITEM_TYPE_OWNERDRAW, menuDef_t::itemCount, menuDef_t::items, windowDef_t::ownerDraw, displayContextDef_t::stopCinematic, itemDef_s::type, itemDef_s::window, menuDef_t::window, and Window_CloseCinematic().
Referenced by Display_CloseCinematics().
int Menu_Count (void)
References menuCount.
Referenced by _UI_KeyEvent(), _UI_MouseEvent(), _UI_Refresh(), _UI_SetActiveMenu(), and Menu_PaintAll().
void Menu_FadeItemByName (menuDef_t * menu, const char * p, qboolean fadeOut)
References count, windowDef_t::flags, Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), NULL, itemDef_s::window, WINDOW_FADINGIN, WINDOW_FADINGOUT, and WINDOW_VISIBLE.
Referenced by Script_FadeIn(), and Script_FadeOut().
itemDef_t* Menu_FindItemByName (menuDef_t * menu, const char * p)
References menuDef_t::itemCount, menuDef_t::items, windowDef_t::name, NULL, Q_stricmp(), and itemDef_s::window.
Referenced by Script_SetFocus().
menuDef_t* Menu_GetFocused (void)
References windowDef_t::flags, menuCount, NULL, menuDef_t::window, WINDOW_HASFOCUS, and WINDOW_VISIBLE.
Referenced by _UI_KeyEvent(), Display_HandleKey(), Display_MouseMove(), Menu_SetFeederSelection(), Menus_ActivateByName(), and UI_Load().
itemDef_t* Menu_GetFocusedItem (menuDef_t * menu)
References windowDef_t::flags, menuDef_t::itemCount, menuDef_t::items, NULL, itemDef_s::window, and WINDOW_HASFOCUS.
itemDef_t* Menu_GetMatchingItemByNumber (menuDef_t * menu, int index, const char * name)
References windowDef_t::group, menuDef_t::itemCount, menuDef_t::items, windowDef_t::name, NULL, Q_stricmp(), and itemDef_s::window.
Referenced by Menu_FadeItemByName(), Menu_OrbitItemByName(), Menu_ShowItemByName(), Menu_TransitionItemByName(), and Script_SetItemColor().
void Menu_HandleKey (menuDef_t * menu, int key, qboolean down)
References itemDef_s::cursorPos, displayContextDef_t::cursorx, displayContextDef_t::cursory, debugMode, Display_MouseMove(), EXEC_APPEND, displayContextDef_t::executeText, windowDef_t::flags, g_editingField, g_waitingForKey, displayContextDef_t::getCVarValue, Item_Action(), Item_Bind_HandleKey(), Item_CorrectedTextRect(), Item_HandleKey(), Item_RunScript(), Item_TextField_HandleKey(), ITEM_TYPE_EDITFIELD, ITEM_TYPE_NUMERICFIELD, ITEM_TYPE_TEXT, menuDef_t::itemCount, menuDef_t::items, K_AUX1, K_AUX10, K_AUX11, K_AUX12, K_AUX13, K_AUX14, K_AUX15, K_AUX16, K_AUX2, K_AUX3, K_AUX4, K_AUX5, K_AUX6, K_AUX7, K_AUX8, K_AUX9, K_DOWNARROW, K_ENTER, K_ESCAPE, K_F11, K_F12, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_MOUSE1, K_MOUSE2, K_MOUSE3, K_TAB, K_UPARROW, Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), Menus_HandleOOBClick(), NULL, menuDef_t::onESC, itemDef_s::parent, qfalse, qtrue, windowDef_t::rect, Rect_ContainsPoint(), itemDef_s::type, itemDef_s::window, menuDef_t::window, WINDOW_HASFOCUS, and WINDOW_POPUP.
Referenced by _UI_KeyEvent(), Display_HandleKey(), and Menus_HandleOOBClick().
void Menu_HandleMouseMove (menuDef_t * menu, float x, float y)
References CVAR_DISABLE, CVAR_ENABLE, CVAR_HIDE, CVAR_SHOW, itemDef_s::cvarFlags, windowDef_t::flags, g_editingField, g_waitingForKey, IsVisible(), Item_CorrectedTextRect(), Item_EnableShowViaCvar(), Item_MouseEnter(), Item_MouseLeave(), Item_SetFocus(), Item_SetMouseOver(), ITEM_TYPE_TEXT, menuDef_t::itemCount, menuDef_t::items, NULL, pass, qfalse, windowDef_t::rect, Rect_ContainsPoint(), itemDef_s::text, itemDef_s::type, itemDef_s::window, menuDef_t::window, WINDOW_FORCED, WINDOW_MOUSEOVER, and WINDOW_VISIBLE.
Referenced by Display_MouseMove(), Menu_SetNextCursorItem(), Menu_SetPrevCursorItem(), and Menus_HandleOOBClick().
itemDef_t* Menu_HitTest (menuDef_t * menu, float x, float y)
References menuDef_t::itemCount, menuDef_t::items, NULL, windowDef_t::rect, Rect_ContainsPoint(), and itemDef_s::window.
void Menu_Init (menuDef_t * menu)
References displayContextDef_t::Assets, menuDef_t::cursorItem, menuDef_t::fadeAmount, cachedAssets_t::fadeAmount, menuDef_t::fadeClamp, cachedAssets_t::fadeClamp, menuDef_t::fadeCycle, cachedAssets_t::fadeCycle, menuDef_t::window, and Window_Init().
Referenced by Menu_New().
int Menu_ItemsMatchingGroup (menuDef_t * menu, const char * name)
References count, windowDef_t::group, menuDef_t::itemCount, menuDef_t::items, windowDef_t::name, Q_stricmp(), and itemDef_s::window.
Referenced by Menu_FadeItemByName(), Menu_OrbitItemByName(), Menu_ShowItemByName(), Menu_TransitionItemByName(), and Script_SetItemColor().
void Menu_New (int handle)
References MAX_MENUS, Menu_Init(), Menu_Parse(), Menu_PostParse(), and menuCount.
Referenced by UI_ParseMenu().
void Menu_OrbitItemByName (menuDef_t * menu, const char * p, float x, float y, float cx, float cy, int time)
References count, windowDef_t::flags, Item_UpdatePosition(), Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), NULL, windowDef_t::offsetTime, windowDef_t::rectClient, windowDef_t::rectEffects, itemDef_s::window, WINDOW_ORBITING, WINDOW_VISIBLE, rectDef_t::x, and rectDef_t::y.
Referenced by Script_Orbit().
static qboolean Menu_OverActiveItem (menuDef_t * menu, float x, float y) [static]
References windowDef_t::flags, Item_CorrectedTextRect(), ITEM_TYPE_TEXT, menuDef_t::itemCount, menuDef_t::items, qfalse, qtrue, windowDef_t::rect, Rect_ContainsPoint(), itemDef_s::text, itemDef_s::type, itemDef_s::window, menuDef_t::window, WINDOW_DECORATION, WINDOW_FORCED, and WINDOW_VISIBLE.
Referenced by Menus_HandleOOBClick().
void Menu_Paint (menuDef_t * menu, qboolean forcePaint)
References windowDef_t::background, debugMode, displayContextDef_t::drawHandlePic, displayContextDef_t::drawRect, menuDef_t::fadeAmount, menuDef_t::fadeClamp, menuDef_t::fadeCycle, windowDef_t::flags, menuDef_t::fullScreen, rectDef_t::h, Item_Paint(), menuDef_t::itemCount, menuDef_t::items, NULL, windowDef_t::ownerDrawFlags, displayContextDef_t::ownerDrawVisible, windowDef_t::rect, SCREEN_HEIGHT, SCREEN_WIDTH, rectDef_t::w, menuDef_t::window, WINDOW_FORCED, Window_Paint(), WINDOW_VISIBLE, rectDef_t::x, and rectDef_t::y.
Referenced by CG_DrawScoreboard(), Menu_PaintAll(), and UI_DrawConnectScreen().
void Menu_PaintAll (void)
References captureData, captureFunc, debugMode, displayContextDef_t::drawText, displayContextDef_t::FPS, Menu_Count(), Menu_Paint(), qfalse, and va().
Referenced by _UI_Refresh(), and CG_Draw2D().
qboolean Menu_Parse (int handle, menuDef_t * menu)
References keywordHash_s::func, KeywordHash_Find(), qfalse, qtrue, pc_token_s::string, token, and trap_PC_ReadToken().
Referenced by Menu_New().
void Menu_PostParse (menuDef_t * menu)
References menuDef_t::fullScreen, rectDef_t::h, Menu_UpdatePosition(), NULL, windowDef_t::rect, rectDef_t::w, menuDef_t::window, rectDef_t::x, and rectDef_t::y.
Referenced by Menu_New().
void Menu_Reset (void)
References menuCount.
Referenced by UI_LoadMenus().
static void Menu_RunCloseScript (menuDef_t * menu) [static]
References windowDef_t::flags, Item_RunScript(), menuDef_t::onClose, itemDef_s::parent, menuDef_t::window, and WINDOW_VISIBLE.
Referenced by Menus_CloseAll(), Menus_CloseByName(), and Menus_HandleOOBClick().
void Menu_ScrollFeeder (menuDef_t * menu, int feeder, qboolean down)
References Item_ListBox_HandleKey(), menuDef_t::itemCount, menuDef_t::items, K_DOWNARROW, K_UPARROW, qtrue, and itemDef_s::special.
void Menu_SetFeederSelection (menuDef_t * menu, int feeder, int index, const char * name)
References listBoxDef_s::cursorPos, itemDef_s::cursorPos, displayContextDef_t::feederSelection, menuDef_t::itemCount, menuDef_t::items, Menu_GetFocused(), Menus_FindByName(), NULL, itemDef_s::special, listBoxDef_s::startPos, and itemDef_s::typeData.
Referenced by UI_BuildServerDisplayList(), UI_BuildServerStatus(), UI_FeederSelection(), UI_GameType_HandleKey(), UI_NetGameType_HandleKey(), UI_RunMenuScript(), UI_SetNextMap(), and UI_StartSkirmish().
itemDef_t * Menu_SetNextCursorItem (menuDef_t * menu)
References menuDef_t::cursorItem, displayContextDef_t::cursorx, displayContextDef_t::cursory, Item_SetFocus(), menuDef_t::itemCount, menuDef_t::items, Menu_HandleMouseMove(), NULL, qfalse, qtrue, windowDef_t::rect, itemDef_s::window, rectDef_t::x, and rectDef_t::y.
Referenced by Item_TextField_HandleKey(), and Menu_HandleKey().
itemDef_t * Menu_SetPrevCursorItem (menuDef_t * menu)
References menuDef_t::cursorItem, displayContextDef_t::cursorx, displayContextDef_t::cursory, Item_SetFocus(), menuDef_t::itemCount, menuDef_t::items, Menu_HandleMouseMove(), NULL, qfalse, qtrue, windowDef_t::rect, itemDef_s::window, rectDef_t::x, and rectDef_t::y.
Referenced by Item_TextField_HandleKey(), and Menu_HandleKey().
void Menu_SetupKeywordHash (void)
References keywordHash_s::keyword, and KeywordHash_Add().
Referenced by String_Init().
void Menu_ShowItemByName (menuDef_t * menu, const char * p, qboolean bShow)
References windowDef_t::cinematic, count, windowDef_t::flags, Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), NULL, displayContextDef_t::stopCinematic, itemDef_s::window, and WINDOW_VISIBLE.
Referenced by Script_Hide(), and Script_Show().
void Menu_TransitionItemByName (menuDef_t * menu, const char * p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt)
References abs(), count, windowDef_t::flags, rectDef_t::h, Item_UpdatePosition(), Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), NULL, windowDef_t::offsetTime, windowDef_t::rectClient, windowDef_t::rectEffects, windowDef_t::rectEffects2, rectDef_t::w, itemDef_s::window, WINDOW_INTRANSITION, WINDOW_VISIBLE, rectDef_t::x, and rectDef_t::y.
Referenced by Script_Transition().
void Menu_UpdatePosition (menuDef_t * menu)
References windowDef_t::border, windowDef_t::borderSize, Item_SetScreenCoords(), menuDef_t::itemCount, menuDef_t::items, NULL, windowDef_t::rect, menuDef_t::window, rectDef_t::x, and rectDef_t::y.
Referenced by Display_MouseMove(), and Menu_PostParse().
qboolean MenuParse_backcolor (itemDef_t * item, int handle)
References windowDef_t::backColor, PC_Float_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_background (itemDef_t * item, int handle)
References windowDef_t::background, PC_String_Parse(), qfalse, qtrue, displayContextDef_t::registerShaderNoMip, and menuDef_t::window.
qboolean MenuParse_border (itemDef_t * item, int handle)
References windowDef_t::border, PC_Int_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_bordercolor (itemDef_t * item, int handle)
References windowDef_t::borderColor, PC_Float_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_borderSize (itemDef_t * item, int handle)
References windowDef_t::borderSize, PC_Float_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_cinematic (itemDef_t * item, int handle)
References windowDef_t::cinematicName, PC_String_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_disablecolor (itemDef_t * item, int handle)
References menuDef_t::disableColor, PC_Float_Parse(), qfalse, and qtrue.
qboolean MenuParse_fadeAmount (itemDef_t * item, int handle)
References menuDef_t::fadeAmount, PC_Float_Parse(), qfalse, and qtrue.
qboolean MenuParse_fadeClamp (itemDef_t * item, int handle)
References menuDef_t::fadeClamp, PC_Float_Parse(), qfalse, and qtrue.
qboolean MenuParse_fadeCycle (itemDef_t * item, int handle)
References menuDef_t::fadeCycle, PC_Int_Parse(), qfalse, and qtrue.
qboolean MenuParse_focuscolor (itemDef_t * item, int handle)
References menuDef_t::focusColor, PC_Float_Parse(), qfalse, and qtrue.
qboolean MenuParse_font (itemDef_t * item, int handle)
References displayContextDef_t::Assets, menuDef_t::font, cachedAssets_t::fontRegistered, PC_String_Parse(), qfalse, qtrue, displayContextDef_t::registerFont, and cachedAssets_t::textFont.
qboolean MenuParse_forecolor (itemDef_t * item, int handle)
References windowDef_t::flags, windowDef_t::foreColor, PC_Float_Parse(), qfalse, qtrue, menuDef_t::window, and WINDOW_FORECOLORSET.
qboolean MenuParse_fullscreen (itemDef_t * item, int handle)
References b, menuDef_t::fullScreen, PC_Int_Parse(), qfalse, and qtrue.
qboolean MenuParse_itemDef (itemDef_t * item, int handle)
References Item_Init(), Item_InitControls(), Item_Parse(), menuDef_t::itemCount, menuDef_t::items, MAX_MENUITEMS, itemDef_s::parent, qfalse, qtrue, and UI_Alloc().
qboolean MenuParse_name (itemDef_t * item, int handle)
References windowDef_t::name, PC_String_Parse(), Q_stricmp(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_onClose (itemDef_t * item, int handle)
References menuDef_t::onClose, PC_Script_Parse(), qfalse, and qtrue.
qboolean MenuParse_onESC (itemDef_t * item, int handle)
References menuDef_t::onESC, PC_Script_Parse(), qfalse, and qtrue.
qboolean MenuParse_onOpen (itemDef_t * item, int handle)
References menuDef_t::onOpen, PC_Script_Parse(), qfalse, and qtrue.
qboolean MenuParse_outlinecolor (itemDef_t * item, int handle)
References windowDef_t::outlineColor, PC_Color_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_outOfBounds (itemDef_t * item, int handle)
References windowDef_t::flags, qtrue, menuDef_t::window, and WINDOW_OOB_CLICK.
qboolean MenuParse_ownerdraw (itemDef_t * item, int handle)
References windowDef_t::ownerDraw, PC_Int_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_ownerdrawFlag (itemDef_t * item, int handle)
References windowDef_t::ownerDrawFlags, PC_Int_Parse(), qfalse, qtrue, and menuDef_t::window.
qboolean MenuParse_popup (itemDef_t * item, int handle)
References windowDef_t::flags, qtrue, menuDef_t::window, and WINDOW_POPUP.
qboolean MenuParse_rect (itemDef_t * item, int handle)
References PC_Rect_Parse(), qfalse, qtrue, windowDef_t::rect, and menuDef_t::window.
qboolean MenuParse_soundLoop (itemDef_t * item, int handle)
References PC_String_Parse(), qfalse, qtrue, and menuDef_t::soundName.
qboolean MenuParse_style (itemDef_t * item, int handle)
References PC_Int_Parse(), qfalse, qtrue, windowDef_t::style, and menuDef_t::window.
qboolean MenuParse_visible (itemDef_t * item, int handle)
References windowDef_t::flags, PC_Int_Parse(), qfalse, qtrue, menuDef_t::window, and WINDOW_VISIBLE.
void Menus_Activate (menuDef_t * menu)
References Display_CloseCinematics(), windowDef_t::flags, Item_RunScript(), menuDef_t::onOpen, itemDef_s::parent, menuDef_t::soundName, displayContextDef_t::startBackgroundTrack, menuDef_t::window, WINDOW_HASFOCUS, and WINDOW_VISIBLE.
Referenced by Menus_ActivateByName(), Menus_HandleOOBClick(), and Menus_ShowByName().
menuDef_t* Menus_ActivateByName (const char * p)
References Display_CloseCinematics(), windowDef_t::flags, m, MAX_OPEN_MENUS, Menu_GetFocused(), menuCount, Menus_Activate(), NULL, openMenuCount, Q_stricmp(), menuDef_t::window, and WINDOW_HASFOCUS.
Referenced by _UI_SetActiveMenu(), Menus_OpenByName(), UI_Load(), and UI_RunMenuScript().
qboolean Menus_AnyFullScreenVisible (void)
References menuDef_t::fullScreen, menuCount, qfalse, qtrue, and WINDOW_VISIBLE.
Referenced by _UI_IsFullscreen(), and _UI_KeyEvent().
void Menus_CloseAll (void)
References windowDef_t::flags, Menu_RunCloseScript(), menuCount, menuDef_t::window, WINDOW_HASFOCUS, and WINDOW_VISIBLE.
Referenced by _UI_Init(), _UI_KeyEvent(), _UI_SetActiveMenu(), UI_Load(), and UI_RunMenuScript().
void Menus_CloseByName (const char * p)
References windowDef_t::flags, Menu_RunCloseScript(), Menus_FindByName(), NULL, menuDef_t::window, WINDOW_HASFOCUS, and WINDOW_VISIBLE.
Referenced by CG_HideTeamMenu(), Script_Close(), and UI_RunMenuScript().
menuDef_t* Menus_FindByName (const char * p)
References menuCount, NULL, and Q_stricmp().
Referenced by CG_DrawScoreboard(), Menu_SetFeederSelection(), Menus_CloseByName(), Menus_ShowByName(), and UI_DrawConnectScreen().
void Menus_HandleOOBClick (menuDef_t * menu, int key, qboolean down)
References displayContextDef_t::cursorx, displayContextDef_t::cursory, Display_CloseCinematics(), Display_VisibleMenuCount(), windowDef_t::flags, Menu_HandleKey(), Menu_HandleMouseMove(), Menu_OverActiveItem(), Menu_RunCloseScript(), menuCount, Menus_Activate(), displayContextDef_t::Pause, qfalse, menuDef_t::window, WINDOW_HASFOCUS, WINDOW_OOB_CLICK, and WINDOW_VISIBLE.
Referenced by Menu_HandleKey().
void Menus_OpenByName (const char * p)
References Menus_ActivateByName().
Referenced by CG_ShowResponseHead(), CG_ShowTeamMenu(), Script_ConditionalOpen(), Script_Open(), and UI_RunMenuScript().
void Menus_ShowByName (const char * p)
References Menus_Activate(), and Menus_FindByName().
qboolean PC_Color_Parse (int handle, vec4_t * c)
References PC_Float_Parse(), qfalse, and qtrue.
Referenced by Asset_Parse(), ItemParse_addColorRange(), ItemParse_outlinecolor(), and MenuParse_outlinecolor().
qboolean PC_Float_Parse (int handle, float * f)
References pc_token_s::floatvalue, qfalse, qtrue, pc_token_s::string, token, trap_PC_ReadToken(), TT_NUMBER, and pc_token_s::type.
Referenced by Asset_Parse(), ItemParse_addColorRange(), ItemParse_backcolor(), ItemParse_bordercolor(), ItemParse_bordersize(), ItemParse_cvarFloat(), ItemParse_cvarFloatList(), ItemParse_elementheight(), ItemParse_elementwidth(), ItemParse_feeder(), ItemParse_forecolor(), ItemParse_model_fovx(), ItemParse_model_fovy(), ItemParse_model_origin(), ItemParse_special(), ItemParse_textalignx(), ItemParse_textaligny(), ItemParse_textscale(), MenuParse_backcolor(), MenuParse_bordercolor(), MenuParse_borderSize(), MenuParse_disablecolor(), MenuParse_fadeAmount(), MenuParse_fadeClamp(), MenuParse_focuscolor(), MenuParse_forecolor(), PC_Color_Parse(), and PC_Rect_Parse().
qboolean PC_Int_Parse (int handle, int * i)
References pc_token_s::intvalue, qfalse, qtrue, pc_token_s::string, token, trap_PC_ReadToken(), TT_NUMBER, and pc_token_s::type.
Referenced by Asset_Parse(), ItemParse_align(), ItemParse_border(), ItemParse_columns(), ItemParse_elementtype(), ItemParse_maxChars(), ItemParse_maxPaintChars(), ItemParse_model_angle(), ItemParse_model_rotation(), ItemParse_ownerdraw(), ItemParse_ownerdrawFlag(), ItemParse_style(), ItemParse_textalign(), ItemParse_textstyle(), ItemParse_type(), ItemParse_visible(), MenuParse_border(), MenuParse_fadeCycle(), MenuParse_fullscreen(), MenuParse_ownerdraw(), MenuParse_ownerdrawFlag(), MenuParse_style(), and MenuParse_visible().
qboolean PC_Rect_Parse (int handle, rectDef_t * r)
References rectDef_t::h, PC_Float_Parse(), qfalse, qtrue, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by ItemParse_rect(), and MenuParse_rect().
qboolean PC_Script_Parse (int handle, const char ** out)
References Q_strcat(), Q_stricmp(), qfalse, qtrue, pc_token_s::string, String_Alloc(), token, trap_PC_ReadToken(), and va().
Referenced by ItemParse_action(), ItemParse_disableCvar(), ItemParse_doubleClick(), ItemParse_enableCvar(), ItemParse_hideCvar(), ItemParse_leaveFocus(), ItemParse_mouseEnter(), ItemParse_mouseEnterText(), ItemParse_mouseExit(), ItemParse_mouseExitText(), ItemParse_onFocus(), ItemParse_showCvar(), MenuParse_onClose(), MenuParse_onESC(), and MenuParse_onOpen().
qboolean PC_String_Parse (int handle, const char ** out)
References out, qfalse, qtrue, pc_token_s::string, String_Alloc(), token, and trap_PC_ReadToken().
Referenced by Asset_Parse(), ItemParse_asset_model(), ItemParse_asset_shader(), ItemParse_background(), ItemParse_cinematic(), ItemParse_cvar(), ItemParse_cvarFloat(), ItemParse_cvarTest(), ItemParse_focusSound(), ItemParse_group(), ItemParse_name(), ItemParse_text(), MenuParse_background(), MenuParse_cinematic(), MenuParse_font(), MenuParse_name(), and MenuParse_soundLoop().
qboolean Rect_ContainsPoint (rectDef_t * rect, float x, float y)
References rectDef_t::h, qfalse, qtrue, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by Display_CaptureItem(), Display_CursorType(), Item_Bind_HandleKey(), Item_ListBox_HandleKey(), Item_ListBox_MouseEnter(), Item_ListBox_OverLB(), Item_MouseEnter(), Item_Multi_HandleKey(), Item_SetFocus(), Item_Slider_HandleKey(), Item_Slider_OverSlider(), Item_YesNo_HandleKey(), Menu_HandleKey(), Menu_HandleMouseMove(), Menu_HitTest(), and Menu_OverActiveItem().
qboolean Rect_Parse (char ** p, rectDef_t * r)
References Float_Parse(), rectDef_t::h, qfalse, qtrue, rectDef_t::w, rectDef_t::x, and rectDef_t::y.
Referenced by Script_Transition().
void Rect_ToWindowCoords (rectDef_t * rect, windowDef_t * window)
References ToWindowCoords(), rectDef_t::x, and rectDef_t::y.
void Script_Close (itemDef_t * item, char ** args)
References Menus_CloseByName(), and String_Parse().
void Script_ConditionalOpen (itemDef_t * item, char ** args)
References displayContextDef_t::getCVarValue, Menus_OpenByName(), String_Parse(), and val.
void Script_Exec (itemDef_t * item, char ** args)
References EXEC_APPEND, displayContextDef_t::executeText, String_Parse(), va(), and val.
void Script_FadeIn (itemDef_t * item, char ** args)
References Menu_FadeItemByName(), itemDef_s::parent, qfalse, and String_Parse().
void Script_FadeOut (itemDef_t * item, char ** args)
References Menu_FadeItemByName(), itemDef_s::parent, qtrue, and String_Parse().
void Script_Hide (itemDef_t * item, char ** args)
References Menu_ShowItemByName(), itemDef_s::parent, qfalse, and String_Parse().
void Script_Open (itemDef_t * item, char ** args)
References Menus_OpenByName(), and String_Parse().
void Script_Orbit (itemDef_t * item, char ** args)
References Float_Parse(), Int_Parse(), Menu_OrbitItemByName(), itemDef_s::parent, and String_Parse().
void Script_Play (itemDef_t * item, char ** args)
References CHAN_LOCAL_SOUND, qfalse, displayContextDef_t::registerSound, displayContextDef_t::startLocalSound, String_Parse(), and val.
void Script_playLooped (itemDef_t * item, char ** args)
References displayContextDef_t::startBackgroundTrack, displayContextDef_t::stopBackgroundTrack, String_Parse(), and val.
void Script_SetAsset (itemDef_t * item, char ** args)
References ITEM_TYPE_MODEL, String_Parse(), and itemDef_s::type.
void Script_SetBackground (itemDef_t * item, char ** args)
References windowDef_t::background, displayContextDef_t::registerShaderNoMip, String_Parse(), and itemDef_s::window.
void Script_SetColor (itemDef_t * item, char ** args)
References windowDef_t::backColor, windowDef_t::borderColor, windowDef_t::flags, Float_Parse(), windowDef_t::foreColor, NULL, out, Q_stricmp(), String_Parse(), itemDef_s::window, WINDOW_BACKCOLORSET, and WINDOW_FORECOLORSET.
void Script_SetCvar (itemDef_t * item, char ** args)
References displayContextDef_t::setCVar, String_Parse(), and val.
void Script_SetFocus (itemDef_t * item, char ** args)
References displayContextDef_t::Assets, CHAN_LOCAL_SOUND, windowDef_t::flags, Item_RunScript(), cachedAssets_t::itemFocusSound, Menu_ClearFocus(), Menu_FindItemByName(), itemDef_s::onFocus, itemDef_s::parent, displayContextDef_t::startLocalSound, String_Parse(), itemDef_s::window, WINDOW_DECORATION, and WINDOW_HASFOCUS.
void Script_SetItemColor (itemDef_t * item, char ** args)
References windowDef_t::backColor, windowDef_t::borderColor, Color_Parse(), count, windowDef_t::flags, windowDef_t::foreColor, Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), NULL, out, itemDef_s::parent, Q_stricmp(), String_Parse(), itemDef_s::window, and WINDOW_FORECOLORSET.
void Script_SetPlayerHead (itemDef_t * item, char ** args)
References displayContextDef_t::setCVar, and String_Parse().
void Script_SetPlayerModel (itemDef_t * item, char ** args)
References displayContextDef_t::setCVar, and String_Parse().
void Script_SetTeamColor (itemDef_t * item, char ** args)
References windowDef_t::backColor, displayContextDef_t::getTeamColor, and itemDef_s::window.
void Script_Show (itemDef_t * item, char ** args)
References Menu_ShowItemByName(), itemDef_s::parent, qtrue, and String_Parse().
void Script_Transition (itemDef_t * item, char ** args)
References Float_Parse(), Int_Parse(), Menu_TransitionItemByName(), itemDef_s::parent, Rect_Parse(), and String_Parse().
static void Scroll_ListBox_AutoFunc (void * p) [static]
References scrollInfo_s::adjustValue, scrollInfo_s::item, Item_ListBox_HandleKey(), scrollInfo_s::nextAdjustTime, scrollInfo_s::nextScrollTime, qfalse, qtrue, displayContextDef_t::realTime, SCROLL_TIME_ADJUST, SCROLL_TIME_ADJUSTOFFSET, SCROLL_TIME_FLOOR, scrollInfo_s::scrollKey, and si.
Referenced by Item_StartCapture().
static void Scroll_ListBox_ThumbFunc (void * p) [static]
References scrollInfo_s::adjustValue, displayContextDef_t::cursorx, displayContextDef_t::cursory, windowDef_t::flags, rectDef_t::h, if(), scrollInfo_s::item, Item_ListBox_HandleKey(), Item_ListBox_MaxScroll(), scrollInfo_s::nextAdjustTime, scrollInfo_s::nextScrollTime, qfalse, qtrue, displayContextDef_t::realTime, windowDef_t::rect, SCROLL_TIME_ADJUST, SCROLL_TIME_ADJUSTOFFSET, SCROLL_TIME_FLOOR, SCROLLBAR_SIZE, scrollInfo_s::scrollKey, si, listBoxDef_s::startPos, itemDef_s::typeData, rectDef_t::w, itemDef_s::window, WINDOW_HORIZONTAL, rectDef_t::x, scrollInfo_s::xStart, rectDef_t::y, and scrollInfo_s::yStart.
Referenced by Item_StartCapture().
static void Scroll_Slider_ThumbFunc (void * p) [static]
References displayContextDef_t::cursorx, itemDef_s::cvar, scrollInfo_s::item, editFieldDef_s::maxVal, editFieldDef_s::minVal, windowDef_t::rect, displayContextDef_t::setCVar, si, SLIDER_WIDTH, itemDef_s::text, itemDef_s::textRect, itemDef_s::typeData, va(), value(), rectDef_t::w, itemDef_s::window, and rectDef_t::x.
Referenced by Item_StartCapture().
const char* String_Alloc (const char * p)
References hash(), hashForString(), stringDef_s::next, NULL, stringDef_s::str, STRING_POOL_SIZE, strPool, strPoolIndex, and UI_Alloc().
Referenced by Character_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), PC_Script_Parse(), PC_String_Parse(), String_Parse(), UI_LoadArenas(), UI_LoadDemos(), UI_LoadMods(), and UI_LoadMovies().
void String_Init (void)
References Controls_GetConfig(), displayContextDef_t::getBindingBuf, HASH_TABLE_SIZE, Item_SetupKeywordHash(), Menu_SetupKeywordHash(), menuCount, NULL, openMenuCount, strHandleCount, strPoolIndex, and UI_InitMemory().
Referenced by _UI_Init(), CG_Init(), and UI_Load().
qboolean String_Parse (char ** p, const char ** out)
References COM_ParseExt(), out, qfalse, qtrue, String_Alloc(), and token.
Referenced by Alias_Parse(), Character_Parse(), GameType_Parse(), Item_EnableShowViaCvar(), Item_RunScript(), MapList_Parse(), Script_Close(), Script_ConditionalOpen(), Script_Exec(), Script_FadeIn(), Script_FadeOut(), Script_Hide(), Script_Open(), Script_Orbit(), Script_Play(), Script_playLooped(), Script_SetAsset(), Script_SetBackground(), Script_SetColor(), Script_SetCvar(), Script_SetFocus(), Script_SetItemColor(), Script_SetPlayerHead(), Script_SetPlayerModel(), Script_Show(), Script_Transition(), Team_Parse(), and UI_RunMenuScript().
void String_Report (void)
References allocPoint, Com_Printf(), MEM_POOL_SIZE, STRING_POOL_SIZE, and strPoolIndex.
Referenced by UI_Report().
void ToWindowCoords (float * x, float * y, windowDef_t * window)
References windowDef_t::border, windowDef_t::borderSize, windowDef_t::rect, rectDef_t::x, and rectDef_t::y.
Referenced by Item_SetTextExtents(), Item_Text_AutoWrapped_Paint(), and Rect_ToWindowCoords().
void* UI_Alloc (int size)
References allocPoint, MEM_POOL_SIZE, memoryPool, NULL, outOfMemory, POOLSIZE, displayContextDef_t::Print, and qtrue.
void UI_InitMemory (void)
References allocPoint, outOfMemory, and qfalse.
qboolean UI_OutOfMemory (void)
References outOfMemory.
Referenced by UI_LoadArenas().
static void Window_CacheContents (windowDef_t * window) [static]
References cin, windowDef_t::cinematicName, displayContextDef_t::playCinematic, and displayContextDef_t::stopCinematic.
Referenced by Item_CacheContents(), and Menu_CacheContents().
static void Window_CloseCinematic (windowDef_t * window) [static]
References windowDef_t::cinematic, displayContextDef_t::stopCinematic, windowDef_t::style, and WINDOW_STYLE_CINEMATIC.
Referenced by Menu_CloseCinematics().
void Window_Init (Window * w)
References windowDef_t::borderSize, windowDef_t::cinematic, and windowDef_t::foreColor.
Referenced by Item_Init(), and Menu_Init().
void Window_Paint (Window * w, float fadeAmount, float fadeClamp, float fadeCycle)
References windowDef_t::backColor, windowDef_t::background, windowDef_t::border, windowDef_t::borderColor, windowDef_t::borderSize, windowDef_t::cinematic, windowDef_t::cinematicName, debugMode, displayContextDef_t::drawCinematic, displayContextDef_t::drawHandlePic, displayContextDef_t::drawRect, displayContextDef_t::drawSides, displayContextDef_t::drawTopBottom, Fade(), displayContextDef_t::fillRect, windowDef_t::flags, windowDef_t::foreColor, displayContextDef_t::getTeamColor, GradientBar_Paint(), rectDef_t::h, windowDef_t::nextTime, NULL, displayContextDef_t::playCinematic, qtrue, windowDef_t::rect, displayContextDef_t::runCinematicFrame, displayContextDef_t::setColor, windowDef_t::style, rectDef_t::w, WINDOW_BORDER_FULL, WINDOW_BORDER_HORZ, WINDOW_BORDER_KCGRADIENT, WINDOW_BORDER_VERT, WINDOW_FORECOLORSET, WINDOW_STYLE_CINEMATIC, WINDOW_STYLE_FILLED, WINDOW_STYLE_GRADIENT, WINDOW_STYLE_SHADER, WINDOW_STYLE_TEAMCOLOR, rectDef_t::x, and rectDef_t::y.
Referenced by Item_Paint(), and Menu_Paint().
Variable Documentation
int allocPoint [static]
Referenced by String_Report(), UI_Alloc(), and UI_InitMemory().
void* captureData = NULL [static]
Referenced by Item_HandleKey(), Item_StartCapture(), and Menu_PaintAll().
void(* captureFunc)(void *p)=0 [static]
Referenced by Item_HandleKey(), Item_StartCapture(), and Menu_PaintAll().
float captureX [static]
float captureY [static]
commandDef_t commandList[]
Initial value:
{
  {"fadein", &Script_FadeIn},
  {"fadeout", &Script_FadeOut},
  {"show", &Script_Show},
  {"hide", &Script_Hide},
  {"setcolor", &Script_SetColor},
  {"open", &Script_Open},
        {"conditionalopen", &Script_ConditionalOpen},
  {"close", &Script_Close},
  {"setasset", &Script_SetAsset},
  {"setbackground", &Script_SetBackground},
  {"setitemcolor", &Script_SetItemColor},
  {"setteamcolor", &Script_SetTeamColor},
  {"setfocus", &Script_SetFocus},
  {"setplayermodel", &Script_SetPlayerModel},
  {"setplayerhead", &Script_SetPlayerHead},
  {"transition", &Script_Transition},
  {"setcvar", &Script_SetCvar},
  {"exec", &Script_Exec},
  {"play", &Script_Play},
  {"playlooped", &Script_playLooped},
  {"orbit", &Script_Orbit}
}
displayContextDef_t* DC = NULL
Referenced by Display_GetContext().
qboolean debugMode = qfalse [static]
Referenced by Item_Paint(), Menu_HandleKey(), Menu_Paint(), Menu_PaintAll(), and Window_Paint().
const int g_bindCount = ARRAY_LEN(g_bindings) [static]
Referenced by BindingFromName(), BindingIDFromName(), Controls_GetConfig(), Controls_SetConfig(), Controls_SetDefaults(), and Item_Bind_HandleKey().
bind_t g_bindings[] [static]
itemDef_t* g_bindItem = NULL [static]
configcvar_t g_configcvars[] [static]
Initial value:
{
        {"cl_run",                      0,                                      0},
        {"m_pitch",                     0,                                      0},
        {"cg_autoswitch",       0,                                      0},
        {"sensitivity",         0,                                      0},
        {"in_joystick",         0,                                      0},
        {"joy_threshold",       0,                                      0},
        {"m_filter",            0,                                      0},
        {"cl_freelook",         0,                                      0},
        {NULL,                          0,                                      0}
}
qboolean g_editingField = qfalse [static]
Referenced by Item_TextField_Paint(), Menu_HandleKey(), and Menu_HandleMouseMove().
itemDef_t* g_editItem = NULL [static]
char g_nameBind1[32]
char g_nameBind2[32]
qboolean g_waitingForKey = qfalse [static]
Referenced by Display_KeyBindPending(), Item_Bind_HandleKey(), Menu_HandleKey(), and Menu_HandleMouseMove().
itemDef_t* itemCapture = NULL [static]
keywordHash_t* itemParseKeywordHash[KEYWORDHASH_SIZE]
keywordHash_t itemParseKeywords[]
int lastListBoxClickTime = 0 [static]
Referenced by Item_ListBox_HandleKey().
char memoryPool[MEM_POOL_SIZE] [static]
Referenced by UI_Alloc().
int menuCount = 0
Referenced by Display_CacheAll(), Display_CaptureItem(), Display_CloseCinematics(), Display_CursorType(), Display_MouseMove(), Display_VisibleMenuCount(), Menu_Count(), Menu_GetFocused(), Menu_New(), Menu_Reset(), Menus_ActivateByName(), Menus_AnyFullScreenVisible(), Menus_CloseAll(), Menus_FindByName(), Menus_HandleOOBClick(), and String_Init().
keywordHash_t* menuParseKeywordHash[KEYWORDHASH_SIZE]
keywordHash_t menuParseKeywords[]
menuDef_t Menus[MAX_MENUS]
menuDef_t* menuStack[MAX_OPEN_MENUS]
int openMenuCount = 0
Referenced by Menus_ActivateByName(), and String_Init().
int outOfMemory [static]
Referenced by UI_Alloc(), UI_InitMemory(), and UI_OutOfMemory().
int scriptCommandCount = ARRAY_LEN(commandList)
Referenced by Item_RunScript().
scrollInfo_t scrollInfo [static]
Referenced by Item_StartCapture().
stringDef_t* strHandle[HASH_TABLE_SIZE] [static]
int strHandleCount = 0 [static]
Referenced by String_Init().
char strPool[STRING_POOL_SIZE] [static]
Referenced by String_Alloc().
int strPoolIndex = 0 [static]
Referenced by String_Alloc(), String_Init(), and String_Report().