ioquake3: code/q3_ui/ui_signup.c File Reference
ui_signup.c File Reference
#include "ui_local.h"
Data Structures
struct signup_t
Defines
#define SIGNUP_FRAME "menu/art/cut_frame"
#define ID_NAME 100
#define ID_NAME_BOX 101
#define ID_PASSWORD 102
#define ID_PASSWORD_BOX 103
#define ID_AGAIN 104
#define ID_AGAIN_BOX 105
#define ID_EMAIL 106
#define ID_EMAIL_BOX 107
#define ID_SIGNUP 108
#define ID_CANCEL 109
Functions
static void Signup_MenuEvent (void *ptr, int event)
void Signup_MenuInit (void)
void Signup_Cache (void)
void UI_SignupMenu (void)
Variables
static signup_t s_signup
static menuframework_s s_signup_menu
static menuaction_s s_signup_signup
static menuaction_s s_signup_cancel
static vec4_t s_signup_color_prompt = {1.00, 0.43, 0.00, 1.00}
Define Documentation
#define ID_AGAIN 104
Referenced by Signup_MenuInit().
#define ID_AGAIN_BOX 105
#define ID_CANCEL 109
Referenced by Signup_MenuEvent(), and Signup_MenuInit().
#define ID_EMAIL 106
Referenced by Signup_MenuInit().
#define ID_EMAIL_BOX 107
#define ID_NAME 100
Referenced by Signup_MenuInit().
#define ID_NAME_BOX 101
#define ID_PASSWORD 102
Referenced by Signup_MenuInit().
#define ID_PASSWORD_BOX 103
#define ID_SIGNUP 108
Referenced by Signup_MenuEvent(), and Signup_MenuInit().
#define SIGNUP_FRAME "menu/art/cut_frame"
Referenced by Signup_Cache(), and Signup_MenuInit().
Function Documentation
void Signup_Cache (void)
References SIGNUP_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by Signup_MenuInit().
static void Signup_MenuEvent (void * ptr, int event) [static]
References signup_t::again_box, mfield_t::buffer, signup_t::email_box, menufield_s::field, ID_CANCEL, ID_SIGNUP, signup_t::name_box, signup_t::password_box, QM_ACTIVATED, UI_ForceMenuOff(), and UI_PopMenu().
Referenced by Signup_MenuInit().
void Signup_MenuInit (void)
References signup_t::again, signup_t::again_box, menucommon_s::callback, signup_t::cancel, menutext_s::color, colorMdGrey, colorRed, signup_t::email, signup_t::email_box, menufield_s::field, menucommon_s::flags, signup_t::frame, _tag_menuframework::fullscreen, menufield_s::generic, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_AGAIN, ID_CANCEL, ID_EMAIL, ID_NAME, ID_PASSWORD, ID_SIGNUP, MAX_EDIT_LINE, mfield_t::maxchars, signup_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_FIELD, MTYPE_PTEXT, signup_t::name, menucommon_s::name, signup_t::name_box, menucommon_s::ownerdraw, signup_t::password, signup_t::password_box, qfalse, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, qtrue, Rankings_DrawName(), Rankings_DrawPassword(), Rankings_DrawText(), s_signup_color_prompt, signup_t::signup, Signup_Cache(), SIGNUP_FRAME, Signup_MenuEvent(), menutext_s::string, menutext_s::style, trap_Cvar_VariableValue(), menucommon_s::type, UI_LEFT, UI_RIGHT, UI_SMALLFONT, menubitmap_s::width, mfield_t::widthInChars, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SignupMenu().
void UI_SignupMenu (void)
References signup_t::menu, Signup_MenuInit(), and UI_PushMenu().
Referenced by Rankings_MenuEvent(), and RankStatus_MenuEvent().
Variable Documentation
signup_t s_signup [static]
menuaction_s s_signup_cancel [static]
vec4_t s_signup_color_prompt = {1.00, 0.43, 0.00, 1.00} [static]
Referenced by Signup_MenuInit().
menuframework_s s_signup_menu [static]
menuaction_s s_signup_signup [static]