ioquake3: code/q3_ui/ui_video.c File Reference
ui_video.c File Reference
#include "ui_local.h"
Data Structures
struct driverinfo_t
struct graphicsoptions_t
struct InitialVideoOptions_s
Defines
#define DRIVERINFO_FRAMEL "menu/art/frame2_l"
#define DRIVERINFO_FRAMER "menu/art/frame1_r"
#define DRIVERINFO_BACK0 "menu/art/back_0"
#define DRIVERINFO_BACK1 "menu/art/back_1"
#define ID_DRIVERINFOBACK 100
#define GRAPHICSOPTIONS_FRAMEL "menu/art/frame2_l"
#define GRAPHICSOPTIONS_FRAMER "menu/art/frame1_r"
#define GRAPHICSOPTIONS_BACK0 "menu/art/back_0"
#define GRAPHICSOPTIONS_BACK1 "menu/art/back_1"
#define GRAPHICSOPTIONS_ACCEPT0 "menu/art/accept_0"
#define GRAPHICSOPTIONS_ACCEPT1 "menu/art/accept_1"
#define ID_BACK2 101
#define ID_FULLSCREEN 102
#define ID_LIST 103
#define ID_MODE 104
#define ID_DRIVERINFO 105
#define ID_GRAPHICS 106
#define ID_DISPLAY 107
#define ID_SOUND 108
#define ID_NETWORK 109
#define ID_RATIO 110
#define NUM_IVO_TEMPLATES (ARRAY_LEN(s_ivo_templates))
#define MAX_RESOLUTIONS 32
Functions
void GraphicsOptions_MenuInit (void)
static void DriverInfo_Event (void *ptr, int event)
static void DriverInfo_MenuDraw (void)
void DriverInfo_Cache (void)
static void UI_DriverInfo_Menu (void)
static int GraphicsOptions_FindBuiltinResolution (int mode)
static int GraphicsOptions_FindDetectedResolution (int mode)
static void GraphicsOptions_GetAspectRatios (void)
static void GraphicsOptions_GetInitialVideo (void)
static void GraphicsOptions_GetResolutions (void)
static void GraphicsOptions_CheckConfig (void)
static void GraphicsOptions_UpdateMenuItems (void)
static void GraphicsOptions_ApplyChanges (void *unused, int notification)
static void GraphicsOptions_Event (void *ptr, int event)
static void GraphicsOptions_TQEvent (void *ptr, int event)
void GraphicsOptions_MenuDraw (void)
static void GraphicsOptions_SetMenuItems (void)
void GraphicsOptions_Cache (void)
void UI_GraphicsOptionsMenu (void)
Variables
static char * driverinfo_artlist []
static driverinfo_t s_driverinfo
static InitialVideoOptions_s s_ivo
static graphicsoptions_t s_graphicsoptions
static InitialVideoOptions_s s_ivo_templates []
static const char * builtinResolutions []
static const char * knownRatios [][2]
static const char * ratios [MAX_RESOLUTIONS]
static char ratioBuf [MAX_RESOLUTIONS][8]
static int ratioToRes [MAX_RESOLUTIONS]
static int resToRatio [MAX_RESOLUTIONS]
static char resbuf [MAX_STRING_CHARS]
static const char * detectedResolutions [MAX_RESOLUTIONS]
static const char ** resolutions = builtinResolutions
static qboolean resolutionsDetected = qfalse
Define Documentation
#define DRIVERINFO_BACK0 "menu/art/back_0"
Referenced by UI_DriverInfo_Menu().
#define DRIVERINFO_BACK1 "menu/art/back_1"
Referenced by UI_DriverInfo_Menu().
#define DRIVERINFO_FRAMEL "menu/art/frame2_l"
Referenced by UI_DriverInfo_Menu().
#define DRIVERINFO_FRAMER "menu/art/frame1_r"
Referenced by UI_DriverInfo_Menu().
#define GRAPHICSOPTIONS_ACCEPT0 "menu/art/accept_0"
Referenced by GraphicsOptions_Cache(), and GraphicsOptions_MenuInit().
#define GRAPHICSOPTIONS_ACCEPT1 "menu/art/accept_1"
Referenced by GraphicsOptions_Cache(), and GraphicsOptions_MenuInit().
#define GRAPHICSOPTIONS_BACK0 "menu/art/back_0"
Referenced by GraphicsOptions_Cache(), and GraphicsOptions_MenuInit().
#define GRAPHICSOPTIONS_BACK1 "menu/art/back_1"
Referenced by GraphicsOptions_Cache(), and GraphicsOptions_MenuInit().
#define GRAPHICSOPTIONS_FRAMEL "menu/art/frame2_l"
Referenced by GraphicsOptions_Cache(), and GraphicsOptions_MenuInit().
#define GRAPHICSOPTIONS_FRAMER "menu/art/frame1_r"
Referenced by GraphicsOptions_Cache(), and GraphicsOptions_MenuInit().
#define ID_BACK2 101
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_DISPLAY 107
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_DRIVERINFO 105
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_DRIVERINFOBACK 100
Referenced by DriverInfo_Event(), and UI_DriverInfo_Menu().
#define ID_FULLSCREEN 102
#define ID_GRAPHICS 106
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_LIST 103
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_MODE 104
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_NETWORK 109
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_RATIO 110
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define ID_SOUND 108
Referenced by GraphicsOptions_Event(), and GraphicsOptions_MenuInit().
#define MAX_RESOLUTIONS 32
#define NUM_IVO_TEMPLATES (ARRAY_LEN(s_ivo_templates))
Referenced by GraphicsOptions_CheckConfig().
Function Documentation
void DriverInfo_Cache (void)
References driverinfo_artlist, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_DriverInfo_Menu().
static void DriverInfo_Event (void * ptr, int event) [static]
References ID_DRIVERINFOBACK, QM_ACTIVATED, and UI_PopMenu().
Referenced by UI_DriverInfo_Menu().
static void DriverInfo_MenuDraw (void) [static]
References color_red, glconfig_t::colorBits, glconfig_t::depthBits, uiStatic_t::glconfig, driverinfo_t::menu, Menu_Draw(), driverinfo_t::numstrings, glconfig_t::renderer_string, SMALLCHAR_HEIGHT, glconfig_t::stencilBits, driverinfo_t::strings, text_color_normal, UI_CENTER, UI_DrawString(), UI_LEFT, UI_RIGHT, UI_SMALLFONT, uis, va(), glconfig_t::vendor_string, and glconfig_t::version_string.
Referenced by UI_DriverInfo_Menu().
static void GraphicsOptions_ApplyChanges (void * unused, int notification) [static]
References graphicsoptions_t::allow_extensions, ARRAY_LEN, menuslider_s::curvalue, menulist_s::curvalue, detectedResolutions, EXEC_APPEND, graphicsoptions_t::filter, graphicsoptions_t::fs, graphicsoptions_t::geometry, GraphicsOptions_FindBuiltinResolution(), h, graphicsoptions_t::lighting, graphicsoptions_t::mode, Q_strncpyz(), QM_ACTIVATED, resolutionsDetected, graphicsoptions_t::texturebits, graphicsoptions_t::tq, trap_Cmd_ExecuteText(), trap_Cvar_Reset(), trap_Cvar_Set(), and trap_Cvar_SetValue().
Referenced by GraphicsOptions_MenuInit().
void GraphicsOptions_Cache (void)
References GRAPHICSOPTIONS_ACCEPT0, GRAPHICSOPTIONS_ACCEPT1, GRAPHICSOPTIONS_BACK0, GRAPHICSOPTIONS_BACK1, GRAPHICSOPTIONS_FRAMEL, GRAPHICSOPTIONS_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by GraphicsOptions_MenuInit(), and UI_Cache_f().
static void GraphicsOptions_CheckConfig (void) [static]
References menuslider_s::curvalue, menulist_s::curvalue, graphicsoptions_t::driver, graphicsoptions_t::filter, graphicsoptions_t::fs, graphicsoptions_t::geometry, GraphicsOptions_FindDetectedResolution(), graphicsoptions_t::lighting, graphicsoptions_t::list, graphicsoptions_t::mode, NUM_IVO_TEMPLATES, and graphicsoptions_t::tq.
Referenced by GraphicsOptions_UpdateMenuItems().
static void GraphicsOptions_Event (void * ptr, int event) [static]
References menuslider_s::curvalue, menulist_s::curvalue, graphicsoptions_t::driver, graphicsoptions_t::filter, InitialVideoOptions_s::filter, graphicsoptions_t::fs, InitialVideoOptions_s::fullscreen, graphicsoptions_t::geometry, InitialVideoOptions_s::geometry, GraphicsOptions_FindDetectedResolution(), ID_BACK2, ID_DISPLAY, ID_DRIVERINFO, ID_GRAPHICS, ID_LIST, ID_MODE, ID_NETWORK, ID_RATIO, ID_SOUND, graphicsoptions_t::lighting, InitialVideoOptions_s::lighting, graphicsoptions_t::list, graphicsoptions_t::mode, InitialVideoOptions_s::mode, QM_ACTIVATED, graphicsoptions_t::ratio, ratioToRes, resToRatio, graphicsoptions_t::texturebits, InitialVideoOptions_s::texturebits, graphicsoptions_t::tq, InitialVideoOptions_s::tq, UI_DisplayOptionsMenu(), UI_DriverInfo_Menu(), UI_NetworkOptionsMenu(), UI_PopMenu(), and UI_SoundOptionsMenu().
Referenced by GraphicsOptions_MenuInit().
static int GraphicsOptions_FindBuiltinResolution (int mode) [static]
References builtinResolutions, detectedResolutions, Q_stricmp(), and resolutionsDetected.
Referenced by GraphicsOptions_ApplyChanges().
static int GraphicsOptions_FindDetectedResolution (int mode) [static]
References builtinResolutions, detectedResolutions, Q_stricmp(), and resolutionsDetected.
Referenced by GraphicsOptions_CheckConfig(), GraphicsOptions_Event(), and GraphicsOptions_SetMenuItems().
static void GraphicsOptions_GetAspectRatios (void) [static]
References Com_sprintf(), h, knownRatios, NULL, Q_stricmp(), Q_strncpyz(), ratioBuf, ratios, ratioToRes, resolutions, and resToRatio.
Referenced by GraphicsOptions_MenuInit().
static void GraphicsOptions_GetInitialVideo (void) [static]
References graphicsoptions_t::allow_extensions, menuslider_s::curvalue, menulist_s::curvalue, graphicsoptions_t::driver, InitialVideoOptions_s::driver, InitialVideoOptions_s::extensions, graphicsoptions_t::filter, InitialVideoOptions_s::filter, graphicsoptions_t::fs, InitialVideoOptions_s::fullscreen, graphicsoptions_t::geometry, InitialVideoOptions_s::geometry, graphicsoptions_t::lighting, InitialVideoOptions_s::lighting, graphicsoptions_t::mode, InitialVideoOptions_s::mode, graphicsoptions_t::texturebits, InitialVideoOptions_s::texturebits, graphicsoptions_t::tq, and InitialVideoOptions_s::tq.
Referenced by GraphicsOptions_MenuInit().
static void GraphicsOptions_GetResolutions (void) [static]
References ARRAY_LEN, detectedResolutions, NULL, Q_strncpyz(), qtrue, resbuf, resolutions, resolutionsDetected, s, and UI_Cvar_VariableString().
Referenced by GraphicsOptions_MenuInit().
void GraphicsOptions_MenuDraw (void)
References GraphicsOptions_UpdateMenuItems(), graphicsoptions_t::menu, and Menu_Draw().
Referenced by GraphicsOptions_MenuInit().
void GraphicsOptions_MenuInit (void)
References graphicsoptions_t::allow_extensions, graphicsoptions_t::apply, graphicsoptions_t::back, graphicsoptions_t::banner, BIGCHAR_HEIGHT, menucommon_s::callback, menutext_s::color, color_red, color_white, menulist_s::curvalue, graphicsoptions_t::display, _tag_menuframework::draw, graphicsoptions_t::driver, graphicsoptions_t::driverinfo, glconfig_t::driverType, graphicsoptions_t::filter, menucommon_s::flags, menubitmap_s::focuspic, graphicsoptions_t::framel, graphicsoptions_t::framer, graphicsoptions_t::fs, _tag_menuframework::fullscreen, menuslider_s::generic, menulist_s::generic, menubitmap_s::generic, menutext_s::generic, graphicsoptions_t::geometry, uiStatic_t::glconfig, GLDRV_ICD, GLDRV_VOODOO, GLHW_3DFX_2D3D, graphicsoptions_t::graphics, GRAPHICSOPTIONS_ACCEPT0, GRAPHICSOPTIONS_ACCEPT1, GraphicsOptions_ApplyChanges(), GRAPHICSOPTIONS_BACK0, GRAPHICSOPTIONS_BACK1, GraphicsOptions_Cache(), GraphicsOptions_Event(), GRAPHICSOPTIONS_FRAMEL, GRAPHICSOPTIONS_FRAMER, GraphicsOptions_GetAspectRatios(), GraphicsOptions_GetInitialVideo(), GraphicsOptions_GetResolutions(), GraphicsOptions_MenuDraw(), GraphicsOptions_SetMenuItems(), GraphicsOptions_TQEvent(), glconfig_t::hardwareType, menubitmap_s::height, menucommon_s::id, ID_BACK2, ID_DISPLAY, ID_DRIVERINFO, ID_GRAPHICS, ID_LIST, ID_MODE, ID_NETWORK, ID_RATIO, ID_SOUND, menulist_s::itemnames, graphicsoptions_t::lighting, graphicsoptions_t::list, menuslider_s::maxvalue, graphicsoptions_t::menu, Menu_AddItem(), menuslider_s::minvalue, graphicsoptions_t::mode, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, MTYPE_SLIDER, MTYPE_SPINCONTROL, menucommon_s::name, graphicsoptions_t::network, NULL, PROP_HEIGHT, QMF_CENTER_JUSTIFY, QMF_HIDDEN, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, QMF_SMALLFONT, qtrue, graphicsoptions_t::ratio, ratios, resolutions, graphicsoptions_t::sound, menutext_s::string, menutext_s::style, graphicsoptions_t::texturebits, graphicsoptions_t::tq, menucommon_s::type, UI_CENTER, UI_RIGHT, UI_SMALLFONT, uis, menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_GraphicsOptionsMenu().
static void GraphicsOptions_SetMenuItems (void) [static]
References graphicsoptions_t::allow_extensions, menuslider_s::curvalue, menulist_s::curvalue, detectedResolutions, graphicsoptions_t::filter, graphicsoptions_t::fs, graphicsoptions_t::geometry, GraphicsOptions_FindDetectedResolution(), graphicsoptions_t::lighting, MAX_STRING_CHARS, graphicsoptions_t::mode, Q_stricmp(), graphicsoptions_t::ratio, resolutionsDetected, resToRatio, graphicsoptions_t::texturebits, graphicsoptions_t::tq, trap_Cvar_VariableStringBuffer(), trap_Cvar_VariableValue(), and UI_Cvar_VariableString().
Referenced by GraphicsOptions_MenuInit().
static void GraphicsOptions_TQEvent (void * ptr, int event) [static]
References menuslider_s::curvalue, int(), QM_ACTIVATED, and graphicsoptions_t::tq.
Referenced by GraphicsOptions_MenuInit().
static void GraphicsOptions_UpdateMenuItems (void) [static]
References graphicsoptions_t::allow_extensions, graphicsoptions_t::apply, menuslider_s::curvalue, menulist_s::curvalue, graphicsoptions_t::driver, InitialVideoOptions_s::driver, InitialVideoOptions_s::extensions, graphicsoptions_t::filter, InitialVideoOptions_s::filter, menucommon_s::flags, graphicsoptions_t::fs, InitialVideoOptions_s::fullscreen, menulist_s::generic, menubitmap_s::generic, graphicsoptions_t::geometry, InitialVideoOptions_s::geometry, GraphicsOptions_CheckConfig(), graphicsoptions_t::lighting, InitialVideoOptions_s::lighting, graphicsoptions_t::mode, InitialVideoOptions_s::mode, QMF_GRAYED, QMF_HIDDEN, QMF_INACTIVE, graphicsoptions_t::texturebits, InitialVideoOptions_s::texturebits, graphicsoptions_t::tq, and InitialVideoOptions_s::tq.
Referenced by GraphicsOptions_MenuDraw().
static void UI_DriverInfo_Menu (void) [static]
References driverinfo_t::back, driverinfo_t::banner, menucommon_s::callback, menutext_s::color, color_white, _tag_menuframework::draw, DRIVERINFO_BACK0, DRIVERINFO_BACK1, DriverInfo_Cache(), DriverInfo_Event(), DRIVERINFO_FRAMEL, DRIVERINFO_FRAMER, DriverInfo_MenuDraw(), glconfig_t::extensions_string, menucommon_s::flags, menubitmap_s::focuspic, driverinfo_t::framel, driverinfo_t::framer, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, uiStatic_t::glconfig, menubitmap_s::height, menucommon_s::id, ID_DRIVERINFOBACK, driverinfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, menucommon_s::name, driverinfo_t::numstrings, Q_strncpyz(), QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, menutext_s::string, driverinfo_t::stringbuff, driverinfo_t::strings, menutext_s::style, menucommon_s::type, UI_CENTER, UI_PushMenu(), uis, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by GraphicsOptions_Event().
void UI_GraphicsOptionsMenu (void)
References graphicsoptions_t::graphics, GraphicsOptions_MenuInit(), graphicsoptions_t::menu, Menu_SetCursorToItem(), and UI_PushMenu().
Referenced by Options_Event(), UI_DisplayOptionsMenu_Event(), UI_NetworkOptionsMenu_Event(), UI_SetupMenu_Event(), and UI_SoundOptionsMenu_Event().
Variable Documentation
const char* builtinResolutions[] [static]
Initial value:
{
        "320x240",
        "400x300",
        "512x384",
        "640x480",
        "800x600",
        "960x720",
        "1024x768",
        "1152x864",
        "1280x1024",
        "1600x1200",
        "2048x1536",
        "856x480",
        NULL
}
Referenced by GraphicsOptions_FindBuiltinResolution(), and GraphicsOptions_FindDetectedResolution().
const char* detectedResolutions[MAX_RESOLUTIONS] [static]
Referenced by GraphicsOptions_ApplyChanges(), GraphicsOptions_FindBuiltinResolution(), GraphicsOptions_FindDetectedResolution(), GraphicsOptions_GetResolutions(), and GraphicsOptions_SetMenuItems().
char* driverinfo_artlist[] [static]
Initial value:
{
        DRIVERINFO_FRAMEL,
        DRIVERINFO_FRAMER,
        DRIVERINFO_BACK0,
        DRIVERINFO_BACK1,
        NULL,
}
Referenced by DriverInfo_Cache().
const char* knownRatios[][2] [static]
Initial value:
{
        { "1.25:1", "5:4"   },
        { "1.33:1", "4:3"   },
        { "1.50:1", "3:2"   },
        { "1.56:1", "14:9"  },
        { "1.60:1", "16:10" },
        { "1.67:1", "5:3"   },
        { "1.78:1", "16:9"  },
        { NULL    , NULL    }
}
Referenced by GraphicsOptions_GetAspectRatios().
char ratioBuf[MAX_RESOLUTIONS][8] [static]
Referenced by GraphicsOptions_GetAspectRatios().
const char* ratios[MAX_RESOLUTIONS] [static]
Referenced by GraphicsOptions_GetAspectRatios(), and GraphicsOptions_MenuInit().
int ratioToRes[MAX_RESOLUTIONS] [static]
Referenced by GraphicsOptions_Event(), and GraphicsOptions_GetAspectRatios().
char resbuf[MAX_STRING_CHARS] [static]
Referenced by GraphicsOptions_GetResolutions().
const char** resolutions = builtinResolutions [static]
Referenced by GraphicsOptions_GetAspectRatios(), GraphicsOptions_GetResolutions(), and GraphicsOptions_MenuInit().
qboolean resolutionsDetected = qfalse [static]
Referenced by GraphicsOptions_ApplyChanges(), GraphicsOptions_FindBuiltinResolution(), GraphicsOptions_FindDetectedResolution(), GraphicsOptions_GetResolutions(), and GraphicsOptions_SetMenuItems().
int resToRatio[MAX_RESOLUTIONS] [static]
Referenced by GraphicsOptions_Event(), GraphicsOptions_GetAspectRatios(), and GraphicsOptions_SetMenuItems().
driverinfo_t s_driverinfo [static]
graphicsoptions_t s_graphicsoptions [static]
InitialVideoOptions_s s_ivo [static]
InitialVideoOptions_s s_ivo_templates[] [static]
Initial value:
{
        {
                6, qtrue, 3, 0, 2, 2, 1, 0, qtrue
        },
        {
                4, qtrue, 2, 0, 2, 1, 1, 0, qtrue
        },
        {
                3, qtrue, 2, 0, 0, 1, 0, 0, qtrue
        },
        {
                2, qtrue, 1, 0, 0, 0, 0, 0, qtrue
        },
        {
                2, qtrue, 1, 1, 0, 0, 0, 0, qtrue
        },
        {
                3, qtrue, 1, 0, 0, 1, 0, 0, qtrue
        }
}