ioquake3: code/q3_ui/ui_serverinfo.c File Reference
ui_serverinfo.c File Reference
#include "ui_local.h"
Data Structures
struct serverinfo_t
Defines
#define SERVERINFO_FRAMEL "menu/art/frame2_l"
#define SERVERINFO_FRAMER "menu/art/frame1_r"
#define SERVERINFO_BACK0 "menu/art/back_0"
#define SERVERINFO_BACK1 "menu/art/back_1"
#define ID_ADD 100
#define ID_BACK 101
Functions
void Favorites_Add (void)
static void ServerInfo_Event (void *ptr, int event)
static void ServerInfo_MenuDraw (void)
static sfxHandle_t ServerInfo_MenuKey (int key)
void ServerInfo_Cache (void)
void UI_ServerInfoMenu (void)
Variables
static char * serverinfo_artlist []
static serverinfo_t s_serverinfo
Define Documentation
#define ID_ADD 100
Referenced by ServerInfo_Event(), and UI_ServerInfoMenu().
#define ID_BACK 101
Referenced by ServerInfo_Event(), and UI_ServerInfoMenu().
#define SERVERINFO_BACK0 "menu/art/back_0"
Referenced by UI_ServerInfoMenu().
#define SERVERINFO_BACK1 "menu/art/back_1"
Referenced by UI_ServerInfoMenu().
#define SERVERINFO_FRAMEL "menu/art/frame2_l"
Referenced by UI_ServerInfoMenu().
#define SERVERINFO_FRAMER "menu/art/frame1_r"
Referenced by UI_ServerInfoMenu().
Function Documentation
void Favorites_Add (void)
References MAX_FAVORITESERVERS, Q_stricmp(), trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and va().
Referenced by ServerInfo_Event().
void ServerInfo_Cache (void)
References serverinfo_artlist, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_ServerInfoMenu().
static void ServerInfo_Event (void * ptr, int event) [static]
References Favorites_Add(), ID_ADD, ID_BACK, QM_ACTIVATED, and UI_PopMenu().
Referenced by UI_ServerInfoMenu().
static void ServerInfo_MenuDraw (void) [static]
References color_red, serverinfo_t::info, Info_NextPair(), MAX_INFO_KEY, MAX_INFO_VALUE, serverinfo_t::menu, Menu_Draw(), serverinfo_t::numlines, Q_strcat(), s, SCREEN_HEIGHT, SCREEN_WIDTH, SMALLCHAR_HEIGHT, text_color_normal, UI_DrawString(), UI_LEFT, UI_RIGHT, and UI_SMALLFONT.
Referenced by UI_ServerInfoMenu().
static sfxHandle_t ServerInfo_MenuKey (int key) [static]
References serverinfo_t::menu, and Menu_DefaultKey().
Referenced by UI_ServerInfoMenu().
void UI_ServerInfoMenu (void)
References serverinfo_t::add, serverinfo_t::back, serverinfo_t::banner, menucommon_s::callback, menutext_s::color, color_red, color_white, CS_SERVERINFO, _tag_menuframework::draw, menucommon_s::flags, menubitmap_s::focuspic, serverinfo_t::framel, serverinfo_t::framer, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_ADD, ID_BACK, serverinfo_t::info, Info_NextPair(), _tag_menuframework::key, MAX_INFO_KEY, MAX_INFO_STRING, MAX_INFO_VALUE, serverinfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, serverinfo_t::numlines, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s, SERVERINFO_BACK0, SERVERINFO_BACK1, ServerInfo_Cache(), ServerInfo_Event(), SERVERINFO_FRAMEL, SERVERINFO_FRAMER, ServerInfo_MenuDraw(), ServerInfo_MenuKey(), menutext_s::string, menutext_s::style, trap_Cvar_VariableValue(), trap_GetConfigString(), menucommon_s::type, UI_CENTER, UI_PushMenu(), UI_SMALLFONT, menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by InGame_Event().
Variable Documentation
serverinfo_t s_serverinfo [static]
char* serverinfo_artlist[] [static]
Initial value:
{
        SERVERINFO_FRAMEL,
        SERVERINFO_FRAMER,
        SERVERINFO_BACK0,
        SERVERINFO_BACK1,
        NULL
}
Referenced by ServerInfo_Cache().