ioquake3: code/q3_ui/ui_rankstatus.c File Reference
ui_rankstatus.c File Reference
#include "ui_local.h"
Data Structures
struct rankstatus_t
Defines
#define RANKSTATUS_FRAME "menu/art/cut_frame"
#define ID_MESSAGE 100
#define ID_OK 101
Functions
static void RankStatus_MenuEvent (void *ptr, int event)
void RankStatus_MenuInit (void)
void RankStatus_Cache (void)
void UI_RankStatusMenu (void)
Variables
static rankstatus_t s_rankstatus
static menuframework_s s_rankstatus_menu
static menuaction_s s_rankstatus_ok
static grank_status_t s_status = 0
static char * s_rankstatus_message = NULL
static vec4_t s_rankingstatus_color_prompt = {1.00, 0.43, 0.00, 1.00}
Define Documentation
#define ID_MESSAGE 100
Referenced by RankStatus_MenuInit().
#define ID_OK 101
Referenced by RankStatus_MenuEvent(), and RankStatus_MenuInit().
#define RANKSTATUS_FRAME "menu/art/cut_frame"
Referenced by RankStatus_Cache(), and RankStatus_MenuInit().
Function Documentation
void RankStatus_Cache (void)
References RANKSTATUS_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by RankStatus_MenuInit().
static void RankStatus_MenuEvent (void * ptr, int event) [static]
References ID_OK, QM_ACTIVATED, s_status, UI_LoginMenu(), UI_PopMenu(), UI_RankingsMenu(), and UI_SignupMenu().
Referenced by RankStatus_MenuInit().
void RankStatus_MenuInit (void)
References menucommon_s::callback, menutext_s::color, colorRed, menucommon_s::flags, rankstatus_t::frame, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_MESSAGE, ID_OK, rankstatus_t::menu, Menu_AddItem(), rankstatus_t::message, MTYPE_BITMAP, MTYPE_PTEXT, menucommon_s::name, rankstatus_t::ok, qfalse, QMF_CENTER_JUSTIFY, QMF_INACTIVE, QMF_PULSEIFFOCUS, qtrue, RankStatus_Cache(), RANKSTATUS_FRAME, RankStatus_MenuEvent(), s_rankingstatus_color_prompt, s_rankstatus_message, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CENTER, UI_SMALLFONT, menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_RankStatusMenu().
void UI_RankStatusMenu (void)
References rankstatus_t::menu, RankStatus_MenuInit(), s_rankstatus_message, s_status, trap_Cvar_VariableValue(), UI_ForceMenuOff(), and UI_PushMenu().
Variable Documentation
vec4_t s_rankingstatus_color_prompt = {1.00, 0.43, 0.00, 1.00} [static]
Referenced by RankStatus_MenuInit().
rankstatus_t s_rankstatus [static]
menuframework_s s_rankstatus_menu [static]
char* s_rankstatus_message = NULL [static]
Referenced by RankStatus_MenuInit(), and UI_RankStatusMenu().
menuaction_s s_rankstatus_ok [static]
grank_status_t s_status = 0 [static]
Referenced by RankStatus_MenuEvent(), and UI_RankStatusMenu().