ioquake3: code/libspeex/vbr.h File Reference
vbr.h File Reference
Variable Bit-Rate (VBR) related routines.
#include "arch.h"
Data Structures
struct VBRState
Defines
#define VBR_MEMORY_SIZE 5
Typedefs
typedef struct VBRState VBRState
Functions
void vbr_init (VBRState *vbr)
float vbr_analysis (VBRState *vbr, spx_word16_t *sig, int len, int pitch, float pitch_coef)
void vbr_destroy (VBRState *vbr)
Variables
const float vbr_nb_thresh [9][11]
const float vbr_hb_thresh [5][11]
const float vbr_uhb_thresh [2][11]
Detailed Description
Variable Bit-Rate (VBR) related routines.
Define Documentation
#define VBR_MEMORY_SIZE 5
Referenced by vbr_analysis(), and vbr_init().
Typedef Documentation
typedef struct VBRState VBRState
VBR state.
Function Documentation
float vbr_analysis (VBRState * vbr, spx_word16_t * sig, int len, int pitch, float pitch_coef)
References VBRState::average_energy, VBRState::consec_noise, VBRState::energy_alpha, VBRState::last_energy, VBRState::last_log_energy, VBRState::last_pitch_coef, VBRState::last_quality, MIN_ENERGY, VBRState::noise_accum, VBRState::noise_accum_count, VBRState::noise_level, NOISE_POW, qual(), VBRState::soft_pitch, sqr, and VBR_MEMORY_SIZE.
Referenced by nb_encode().
void vbr_destroy (VBRState * vbr)
Referenced by nb_encoder_destroy().
void vbr_init (VBRState * vbr)
References VBRState::accum_sum, VBRState::average_energy, VBRState::consec_noise, VBRState::energy_alpha, VBRState::last_energy, VBRState::last_log_energy, VBRState::last_pitch_coef, VBRState::last_quality, MIN_ENERGY, VBRState::noise_accum, VBRState::noise_accum_count, VBRState::noise_level, NOISE_POW, VBRState::soft_pitch, and VBR_MEMORY_SIZE.
Referenced by nb_encoder_init().
Variable Documentation
const float vbr_hb_thresh[5][11]
const float vbr_nb_thresh[9][11]
Referenced by nb_encode().
const float vbr_uhb_thresh[2][11]