ioquake3: code/qcommon/vm_interpreted.c File Reference
vm_interpreted.c File Reference
#include "vm_local.h"
Defines
#define DEBUGSTR va("%s%i", VM_Indent(vm), opStackOfs)
#define r2 codeImage[programCounter]
Functions
static ID_INLINE int loadWord (void *addr)
char * VM_Indent (vm_t *vm)
void VM_StackTrace (vm_t *vm, int programCounter, int programStack)
void VM_PrepareInterpreter (vm_t *vm, vmHeader_t *header)
int VM_CallInterpreted (vm_t *vm, int *args)
Define Documentation
#define DEBUGSTR va("%s%i", VM_Indent(vm), opStackOfs)
Referenced by VM_CallInterpreted().
#define r2 codeImage[programCounter]
Referenced by CG_DrawAreaPowerUp(), Display_CursorType(), split_cb_search_shape_sign(), split_cb_search_shape_sign_N1(), and VM_CallInterpreted().
Function Documentation
static ID_INLINE int loadWord (void * addr) [static]
Referenced by VM_PrepareInterpreter().
int VM_CallInterpreted (vm_t * vm, int * args)
References vm_s::breakCount, vm_s::breakFunction, vm_s::codeBase, vm_s::codeLength, Com_Error(), Com_Printf(), vm_s::currentlyInterpreting, vm_s::dataBase, vm_s::dataMask, DEBUGSTR, ERR_DROP, vm_s::instructionCount, vm_s::instructionPointers, int(), intptr_t(), OP_ADD, OP_ADDF, OP_ARG, OP_BAND, OP_BCOM, OP_BLOCK_COPY, OP_BOR, OP_BREAK, OP_BXOR, OP_CALL, OP_CONST, OP_CVFI, OP_CVIF, OP_DIVF, OP_DIVI, OP_DIVU, OP_ENTER, OP_EQ, OP_EQF, OP_GEF, OP_GEI, OP_GEU, OP_GTF, OP_GTI, OP_GTU, OP_JUMP, OP_LEAVE, OP_LEF, OP_LEI, OP_LEU, OP_LOAD1, OP_LOAD2, OP_LOAD4, OP_LOCAL, OP_LSH, OP_LTF, OP_LTI, OP_LTU, OP_MODI, OP_MODU, OP_MULF, OP_MULI, OP_MULU, OP_NE, OP_NEF, OP_NEGF, OP_NEGI, OP_POP, OP_PUSH, OP_RSHI, OP_RSHU, OP_SEX16, OP_SEX8, OP_STORE1, OP_STORE2, OP_STORE4, OP_SUB, OP_SUBF, opnames, OPSTACK_SIZE, PADP, vmSymbol_s::profileCount, vm_s::programStack, Q_ftol, qfalse, qtrue, r0, r1, r2, vm_s::systemCall, VM_BlockCopy(), VM_Debug(), vm_debugLevel, VM_ValueToFunctionSymbol(), and VM_ValueToSymbol().
Referenced by VM_Call().
char* VM_Indent (vm_t * vm)
References vm_s::callLevel, and string().
void VM_PrepareInterpreter (vm_t * vm, vmHeader_t * header)
References code, vm_s::codeBase, vmHeader_t::codeLength, vm_s::codeLength, vmHeader_t::codeOffset, Com_Error(), ERR_DROP, h_high, Hunk_Alloc, instruction, vm_s::instructionCount, instructionCount, vm_s::instructionPointers, int(), loadWord(), op, OP_ARG, OP_BLOCK_COPY, OP_CONST, OP_ENTER, OP_EQ, OP_EQF, OP_GEF, OP_GEI, OP_GEU, OP_GTF, OP_GTI, OP_GTU, OP_LEAVE, OP_LEF, OP_LEI, OP_LEU, OP_LOCAL, OP_LTF, OP_LTI, OP_LTU, OP_NE, and OP_NEF.
Referenced by VM_Create().
void VM_StackTrace (vm_t * vm, int programCounter, int programStack)
References Com_Printf(), count, vm_s::dataBase, and VM_ValueToSymbol().